### ISSUE TITLE
[csharp] 'var' not colored as keyword

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#100]
_From @aeschli on February 11, 2016 7:40_

![image](https://cloud.githubusercontent.com/assets/12577765/12968515/14730ad4-d041-11e5-9206-c75112175524.png)

'var' should be colored as keyword.

_Copied from original issue: Microsoft/vscode#2919_

**Comment by DustinCampbell** [comment]
I realize that @Pilchie saw this too, but I can't repro on the dev branch. Did it get fixed?

![image](https://cloud.githubusercontent.com/assets/116161/14726144/f8e7fa92-07d4-11e6-81d2-37cd4f5c0da6.png)
