### ISSUE TITLE
Function Parameters show XML instead of parsed XML in description part.

### ISSUE THREAD

**Issue by chrmarti** [OmniSharp/omnisharp-vscode#1003]
_From @sorab2142 on November 30, 2016 7:31_

- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|python|donjayamanne|0.5.2|
|Theme-FlatlandMonokai|gerane|0.0.4|
|Go|lukehoban|0.6.45|
|cpptools|ms-vscode|0.9.1|
|omnisharp|ms-vscode|0.3.3|
|vscode-icons|robertohuertasm|4.0.2|
|unity-debug|Unity|1.1.0|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. Trigger autocomplete on function parameters
2. Notice that instead of parsing xml, the xml itself is visible in the description part.

![image](https://cloud.githubusercontent.com/assets/3336237/20743520/e50c9834-b6fc-11e6-9b5b-2b6f57239bf3.png)

_Copied from original issue: Microsoft/vscode#16252_

**Comment by chrmarti** [comment]
Not sure if that's on our side. @joaomoreno ?

**Comment by chrmarti** [comment]
_From @joaomoreno on November 30, 2016 16:43_

This is an issue with the extension providing the contents to the parameter hints: [omnisharp](https://github.com/OmniSharp/omnisharp-vscode). Please file an issue there.

**Comment by DustinCampbell** [comment]
Hi, sorry for the delay here.

It looks like you're using the "C# Legacy Support" extension for Unity development, which is no longer supported. The good news is that the normal "C#" extension fully supports Unity development and this particular bug was fixed there long ago.

I recommend that you uninstall the "C# Legacy Support" extension and install [C#](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp).
