### ISSUE TITLE
Debugger doesn't correctly format AggregateException

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#1006]
## Environment data
`dotnet --info` output: 
```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```
C# extension version: 1.6.0-beta3

## Steps to reproduce
Run the following program under the debugger

```csharp
        public static void Main(string[] args)
        {
            var innerException = new Exception("My inner exception");
            throw new AggregateException(innerException);
        }
```

## Result:
The expression evaluator cannot format the aggregate exception:
$exception
Count = error CS0103: The name 'InnerExceptionCount' does not exist in the current context

## Notes:
The issue looks like a problem with invoking the private property:
https://github.com/dotnet/coreclr/blob/59c9e61eb49aad0f5a1306d13e08731b7669fcbe/src/mscorlib/src/System/AggregateException.cs#L33

**Comment by kevint2017** [comment]
Anyone figure out a fix for this yet?

**Comment by gregg-miskelly** [comment]
I took a look and it actually looks like this is NOT a debugger bug, but rather a CoreCLR bug -- the 1.1 version of System.Private.CoreLib.dll doesn't define an 'InnerExceptionCount' property on System.AggregateException. It has been fixed for .NET Core 2.0.
