### ISSUE TITLE
Exception experience in VS Code is somwhat confusing

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#1007]
## Environment data
VS Code version: 1.8.0-insider (Commit be33bcdb2beb2d01c76ec8f830a70feaaa6721f5)

## Steps to reproduce
Run the following program under the debugger

```csharp
        public static void Main(string[] args)
        {
            throw new Exception("Example Exception Message");
        }
```

## Expected  behavior
VS Code should somewhat prominently show me the Exception type, if this is an unhandled exception, and the exception message. While in this trivial example these things are obvious from looking at the code, if they exception comes from library code this is often not the case.

## Actual behavior
* The exception message can only be found by finding $exception in the locals window, which can be confusing to find if one is in a big function
* The exception type and unhandled/handled status can be found by hovering over the 'PAUSED ON EXCEPTION' text, which is nice, but not all that discoverable

![vscode-exception](https://cloud.githubusercontent.com/assets/11078489/20804347/6600c064-b7a7-11e6-9111-85b78eae0486.png)

Equivalent scenario with VS:
![vs-exception](https://cloud.githubusercontent.com/assets/11078489/20804455/d56c98ce-b7a7-11e6-9f79-0910ed84d846.png)

**Comment by gregg-miskelly** [comment]
@weinand is providing a basic dialog that comes up to display the `text` property of the exception something that VS Code might consider adding? Or should we just try and solve this on our side by dumping more information to the console?

**Comment by DustinCampbell** [comment]
@weinand: Ping?

**Comment by gregg-miskelly** [comment]
@DustinCampbell Andre and Isidor are planning to look at this in January. https://github.com/Microsoft/vscode/issues/16860 tracks that.

**Comment by DustinCampbell** [comment]
Awesome! Thanks for the update. Sounds great!

**Comment by gregg-miskelly** [comment]
Here is what things look like in VS Code 1.11. Remaining work is to improve our message.

![exception-vscode-1 11](https://cloud.githubusercontent.com/assets/11078489/23715270/e13bc2c6-03e0-11e7-8e1b-a32f20675cb5.png)

**Comment by weinand** [comment]
@gregg-miskelly this feature is not finished yet. Please see https://github.com/Microsoft/vscode/issues/22078

**Comment by gregg-miskelly** [comment]
@weinand ahh. Thanks!

**Comment by gregg-miskelly** [comment]
This will be improved in 1.9, but there are still some changes I would like to see on the C# extension (ex: func-eval'ing the `Message` property) that I don't think will make 1.9, so moving out.
