### ISSUE TITLE
Types inside the renamed file are seen as duplicate

### ISSUE THREAD

**Issue by tugberkugurlu** [OmniSharp/omnisharp-vscode#1008]
## Environment data
`dotnet --info` output:
```
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
```

VS Code version:

```
Version 1.7.2 (1.7.2)
7ba55c5860b152d999dda59393ca3ebeb1b5c85f
```

C# Extension version: 

```
1.5.3
```

## Steps to reproduce
Load a project, rename a file which has a class in it.

## Expected  behavior

Should work as it has been before.

## Actual behavior

It doesn't unload the type inside the deleted file and see the type inside new file as a duplicate:

![image](https://cloud.githubusercontent.com/assets/328122/20808658/5096ed12-b7fb-11e6-80f5-0f115fa12d79.png)

**Comment by matthamil** [comment]
This is the same bug in https://github.com/OmniSharp/omnisharp-vscode/issues/785 and https://github.com/OmniSharp/omnisharp-vscode/issues/803

**Comment by tugberkugurlu** [comment]
In addition to this one, there is also another bug which is related to file delete. If you delete a file, the members inside that file still seems valid (e.g. shows up on IntelliSense list, etc.). Should I open a separate issue for this?

**Comment by matthamil** [comment]
@tugberkugurlu I'm able to recreate that bug too. I think it's related. The Intellisense seems to not update when any existing files are renamed or deleted; however, it works fine when you're adding new files that didn't previously exist. Hoping this gets fixed, it's been a reported issue since September (https://github.com/OmniSharp/omnisharp-vscode/issues/785).

**Comment by filipw** [comment]
The problem is that at the moment, upon rename, the Workspace only raises a `DocumentAdded` event for the renamed doc, but never raises `DocumentRemoved` for the old one.

If you continue renaming 10 times, you end up with 10 copies of the same document in the workspace.

**Comment by DustinCampbell** [comment]
Yeah, we need to fix that.

**Comment by DustinCampbell** [comment]
OK. We're going to use https://github.com/OmniSharp/omnisharp-vscode/issues/785 to track fixing this issue.
