### ISSUE TITLE
OmniSharp puts up 'This application requires one of the follwing versions of the .NET Framework..' prompt

### ISSUE THREAD

**Issue by qian6** [OmniSharp/omnisharp-vscode#1010]
## Environment data
`dotnet --info` output:
VS Code version: 1.7.2
C# Extension version: v.1.6.0-beta3
.NET Core version: 1.0.0-SDK Preview2-003133

## Steps to reproduce
1. Open vscode and click Extensions button install C# Extension. 
![capture](https://cloud.githubusercontent.com/assets/20922638/20826282/c28d28ba-b8a4-11e6-9c59-e7c6b1153cd3.PNG)
2. click Restart Now button.
3. Open hwapp folder in attachments directly.
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/626595/hwapp.zip)

## Expected  behavior
It can successfully install package and no error messages.

## Actual behavior
It pops up error message as following:
![capture1](https://cloud.githubusercontent.com/assets/20922638/20826381/63264e14-b8a5-11e6-9df9-50b9d2774cad.PNG)

## Investigation
1. It pops up error message but when I press No button it have no influence for debugging.
2. This issue occur in win8.1 x64.
3. I only wonder if he is not by design.

**Comment by gregg-miskelly** [comment]
@qian6 as of C# extension 1.5, this is expected on Windows. Its not debugger related, so it will not impact the debugger (other than things like generating a launch.json will not work). If you click 'yes' should hopefully get help installing .NET 4.6.
