### ISSUE TITLE
Debugger launch has a race condition making breakpoints in startup code are unreliable

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#1011]
## Environment data
`dotnet --info` output:
VS Code version: 1.7.2
C# Extension version: v.1.6.0-beta3
.NET Core version: 1.0.0-preview2 -1 - 003177
OS: Linux Mint

## Steps to reproduce
1. Download Attach folder in attachments directly and open with VSCode
[Attach.zip](https://github.com/OmniSharp/omnisharp-vscode/files/626780/Attach.zip)
2. Select the debug type ''.Net core Launch(console)"
3. Set a bp at line of 15( fun(); ) in Program.cs
4. Press F5 to start debugging
5. Stop debugging when the bp got hit;
6. Press F5
## Expected  behavior
The bp should be hit.

## Actual behavior
The bp can't be hit and the program just ran to end. The log file is attached below:
[log.txt](https://github.com/OmniSharp/omnisharp-vscode/files/626817/log.txt)

## Investigation
This issue doesn't appear every time.

**Comment by jamesnpu** [comment]
I've run to the similar issue.

The same version of VS Code, C# Extension and .NET Core
OS: CentOS-7-x86_64-DVD-1511
Desktop: KDE

The BP could be seldom hit. Once hit, pressed restart and it just missed to hit the BP.
While the same issue didn't reproduce in a same OS with a  gnome desktop.

**Comment by jamesnpu** [comment]
Similar issue in Oracle Linux, failed to hit BP.

VS Code version: 1.7.2
C# Extension version: v.1.6.0-beta3
.NET Core version: 1.0.0-preview2 -1 - 003177
OS: Oracle Linux Release 7

**Comment by gregg-miskelly** [comment]
From the Grace's log I don't have any good guess as to what went wrong -- symbols were loaded, the breakpoint was bound, and the app exited normally.

**Comment by gregg-miskelly** [comment]
I have a repro now. This is a launch race. If I change the code to do --

```csharp
while (true)
{
    Console.WriteLine("Hello"); // set bp here
    Thread.Sleep(100);
}
```

My breakpoint always hits, but frequently it doesn't hit until the second iteration of the loop. I thought this might be a regression in dbgshim, but I switched back to the 1.0 version of dbgshim and I see the same issue.

**Comment by GraceDong** [comment]
Yes, you're right. I used your code, the same issue appeared on my Oracle Linux.

**Comment by richardzeng1985** [comment]
This issue also happened on my machine with Ubuntu 14 x64 installed.

**Comment by jamesnpu** [comment]
This issue also happened on my Ubuntu 16.10 x64.

What's more, sometimes it fails to stop at entry of a program although I've set "stopAtEntry" true.
I wonder if this issue shares a same problem with the "BP missed" issue.

**Comment by gregg-miskelly** [comment]
@jamesnpu yes, that sounds like the same thing.

**Comment by gregg-miskelly** [comment]
This appears to be an issue in CoreCLR that clrdbg cannot work around. We are now tracking this with https://github.com/dotnet/coreclr/issues/8606.

**Comment by GraceDong** [comment]
When I insert "Debugger.Break()"in a project, this issue can repro on Ubuntu(14.04/16.04/16.10) and Fedora(23/24).

**Comment by GraceDong** [comment]
Debugger.IsAttached doesn't work, is it the same issue?

**Comment by gregg-miskelly** [comment]
@GraceDong Yes

**Comment by GraceDong** [comment]
Got it, thanks.

**Comment by jamesnpu** [comment]
I found a issue which may be the same as this one when testing the latest C# extension on Oracle Linux 7 x64.
While doing exception testing, sometimes the program just terminated without a cursor pointing to the line where exception happened, and only with the exception logged in DEBUG CONSOLE window. Sometimes, it just ran as expected, say, broke when exception occurred and with a cursor, a line showing exception type in Locals window and right CALL STACK info.

**Comment by gregg-miskelly** [comment]
@jamesnpu when you say that the exception is 'logged' in the debug console? Do you mean a message like this --

    Exception thrown: 'System.Exception' in clicon.dll

Or something else? If you are seeing a message like that -- you have found a new bug. If you are seeing a message that indicates that the program itself is reporting the exception, and the exception reporting is happening very close to the start of the program (ex: its the first stopping event), then yes, that sounds likely to be the same problem. You can always avoid the bug by adding while (!Debugger.IsAttached) Thread.Sleep(100) to the start of the program.

**Comment by GraceDong** [comment]
He means that the program should be break in running because of Unhandled Exception (e.g: 1/0), in fact, it can not break, and the program end of run and printed the correctly exception message in DEBUG CONSOLE window (e.g: Unhandled Exception: System.DivideByZeroException: Attempted to divide by zero ). This issue can repro on other Linux OS. If this is a new bug, should I need to open this bug on GitHub?

**Comment by gregg-miskelly** [comment]
@GraceDong Thanks! That sounds like this launch issue then. To test for sure, try adding the sleep loop to the first line of the program. If the bug goes away then we can pretty confidently say its the same issue. 

BTW: The CLR team now has a fix for the launch issue in their master branch, and they are working on getting it into release branches. So hopefully we will have a few in a week or two.

**Comment by qian6** [comment]
For this issue,It has very high chance of reproduce on Centos, oracle, redhat and have a very bad influence on my testing.

**Comment by gregg-miskelly** [comment]
@qian6 the fix is just about to ship. The 1.8-beta2 version of the debugger has the debugger side of the fix. But the more important part comes from CoreCLR, and that will ship very soon.

**Comment by gregg-miskelly** [comment]
The .NET team released new versions of .NET today which should resolve this issue. Please follow instructions on https://www.microsoft.com/net/core to update to the 1.1.1 or 1.0.4 version of the framework.
