### ISSUE TITLE
Doesn't deal with spaces in dll hintpaths in .csproj files

### ISSUE THREAD

**Issue by almo2001** [OmniSharp/omnisharp-vscode#1013]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64

VS Code version: 1.7.2
C# Extension version: 1.5.3

## Steps to reproduce
Put Unity.app in a folder with a space in its path, like /Applications/Unity 5.5.0f3/Unity.app
Do Assets->Open C# Project in Code

## Expected  behavior
UnityEngine should be a known symbol in Intellisense.

## Actual behavior
UnityEngine is not a known symbol in Intellisense.

Moving it to /Applications/Unity5.5.0f3/Unity.app fixed it.

I suspect this in the .csproj file is failing due to the space:
    <Reference Include="UnityEngine">
      <HintPath>/Applications/Unity 5.5.0f3/Unity.app/Contents/Managed/UnityEngine.dll</HintPath>
    </Reference>

My game project was in a folder without spaces, and Intellisense worked on symbols defined in my own code.

**Comment by DustinCampbell** [comment]
Thanks for the report. I'll take a look.

**Comment by akshita31** [comment]
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

VSCode Version : 1.19.0
C# Extension version: 1.13.1

My Folder is present in "/Documents/New Unity/Unity.app" and the <HintPath> for the dll contains "/Documents/New Unity/Unity.app/Contents/Managed/UnityEngine.dll" , but the assemblies are being loaded properly and intellisense also works for "UnityEngine".

@almo2001 Does this still reproduce ?  If yes, please share the omnisharp log.

**Comment by almo2001** [comment]
I just tried it, and it seems to be fixed. I verified the path in the .csproj file, and it did have a space in it.

**Comment by akshita31** [comment]
@almo2001 If you have verified the behavior, can we go ahead and close this issue ?

**Comment by almo2001** [comment]
Sure. If it happens again, I'll reopen it.

**Comment by DustinCampbell** [comment]
This was likely due to a bug somewhere else (perhaps MSBuild?) that was fixed at some point.
