### ISSUE TITLE
ASP.NET Core Project templates- Feature Request

### ISSUE THREAD

**Issue by alexandrudima** [OmniSharp/omnisharp-vscode#1016]
Moved from Microsoft/vscode#16521

From @chandusekhar 

---

If ASP.NET Core Project templates are introduced in VSCODE it will be great.

**Comment by DustinCampbell** [comment]
This is similar to #944 and #261, though not entirely the same.

There isn't really a facility for producing project templates in VS Code today like we have in Visual Studio. For ASP.NET Core in VS Code, it's generally expected that users will create projects using the command line tools. For example, the following command-line should do exactly what you want.

```
mkdir test-web
cd test-web
dotnet new -t web
```

Then, if VS Code is on your path you can type `code .` to open your newly created project. Or, you can just open the folder from VS Code's menu.

(@alexandrudima, please let me know if I'm missing anything, or point me to plans for project templates in VS Code if any exist.)

**Comment by DustinCampbell** [comment]
Closing this for now as I don't think there's much we can do in the C# extension itself. However, you can use `dotnet new -t web` from from the command-line to create an ASP .NET Core project template with the .NET CLI.

**Comment by filipw** [comment]
or possibly use something like https://github.com/SamVerschueren/vscode-yo + https://github.com/OmniSharp/generator-aspnet to scaffold stuff

**Comment by DustinCampbell** [comment]
Right -- sorry, I'd forgotten to mention that. Also, @sayedihashimi has been thinking a lot about what we might want to do with .NET Core templates at the command-line in the future.
