### ISSUE TITLE
C# extension should provide launch.json templates

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#1024]
With the November 2016 release of VS Code, there is now support for launch.json templates. See https://github.com/Microsoft/vscode/issues/16937 for examples.

This is less interesting for the C# extension since we normally generate launch.json, but it is useful in a few cases --
* Users with multiple launch projects that would like multiple launch configurations
* Adding templates for SSH

We should add new templates for local launch, local attach, ssh launch and ssh attach.

**Comment by WardenGnaw** [comment]
Do we want to dynamically create the configuration snippets or just list all possible configurations?

If it is dynamically created, we will be able to filter out non-usable configurations. This also reduces the amount of non-usable choices for the user. 

The image below shows how crowded the list becomes with a couple of extensions installed. 
![image](https://cloud.githubusercontent.com/assets/3953714/24767498/fe8d676e-1ab3-11e7-858f-ae9a9a82157b.png)

If we decide to add 4 configurations multiplied by 2 for Windows/Linux differences it will get crowded.

Sadly, creating snippets via a command, like initial configurations, does not work:  https://github.com/Microsoft/vscode/issues/23961

**Comment by gregg-miskelly** [comment]
Here are the node snippets as an example: https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L117

**Comment by gregg-miskelly** [comment]
@WardenGnaw should we leave this open to react to a possible VS Code fix in the future to make this better? Or should we close this for now?

**Comment by WardenGnaw** [comment]
I think we can close this one and then create a new issue asking for "dynamic launch.json templates with comments". That can be worked on once Microsoft/vscode#23961 is completed.
