### ISSUE TITLE
Problems with .NET Core 1.1 projects

### ISSUE THREAD

**Issue by GGG-KILLER** [OmniSharp/omnisharp-vscode#1025]
## Environment data
`dotnet --info` output:
```
A:\Programming\ASP.NET\Test>dotnet --info
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```
VS Code version:
```
Version 1.7.2
Commit 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
Date 2016-11-21T22:06:37.428Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0
```
C# Extension version: 1.5.3

OmniSharp Log: 

```
Starting OmniSharp server at 12/10/2016, 11:47:20 PM
    Target: a:\Programming\ASP.NET\Test

OmniSharp server started
    Path: C:\Users\xxxxx\.vscode\extensions\ms-vscode.csharp-1.5.3\bin\omnisharp\OmniSharp.exe
    PID: 7064

OmniSharp: -s a:\Programming\ASP.NET\Test --hostPID 6972 --stdio DotNet:enablePackageRestore=false --encoding utf-8
[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location 'a:\Programming\ASP.NET\Test' on host 6972.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in a:\Programming\ASP.NET\Test
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp#MSBuild] No solution files found in 'a:\Programming\ASP.NET\Test'
[INFORMATION:OmniSharp#ProjectFileInfo] Using tools version: 15.0
[INFORMATION:OmniSharp#MSBuild] Add project: a:\Programming\ASP.NET\Test\Test.csproj
[INFORMATION:OmniSharp#MSBuild] Update project: Test
[INFORMATION:OmniSharp.Startup] Configuration finished.
Starting OmniSharp server at 12/10/2016, 11:48:46 PM
    Target: a:\Programming\ASP.NET\Test

OmniSharp server started
    Path: C:\Users\gggki\.vscode\extensions\ms-vscode.csharp-1.5.3\bin\omnisharp\OmniSharp.exe
    PID: 10928

OmniSharp: -s a:\Programming\ASP.NET\Test --hostPID 6972 --stdio DotNet:enablePackageRestore=false --encoding utf-8
[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location 'a:\Programming\ASP.NET\Test' on host 6972.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in a:\Programming\ASP.NET\Test
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp#MSBuild] No solution files found in 'a:\Programming\ASP.NET\Test'
[INFORMATION:OmniSharp#ProjectFileInfo] Using tools version: 15.0
[INFORMATION:OmniSharp#MSBuild] Add project: a:\Programming\ASP.NET\Test\Test.csproj
[INFORMATION:OmniSharp#MSBuild] Update project: Test
[INFORMATION:OmniSharp.Startup] Configuration finished.
```

## Steps to reproduce
- Create new project `dotnet new -t Web`
- Open containing folder with VS Code

## Expected  behavior
- Extension generates appropriate `.launch.json`/`tasks.json` files;
- Extension offers to restore packages;
- Debugging configuration is set to C#.

## Actual behavior
- No `launch.json`/`tasks.json` files are created;
- Extension does not offer to restore packages;
- Debugging configuration says `No Configurations`;
- Projects icon says `0 projects`;
- Opening `Program.cs` shows errors that the namespace `Microsoft.AspNetCore` does not exists;
- Only way to partially enable Debugging is to select the `Configure or Fix 'launch.json'` option in the debugging menu and select `.NET Core` as the option.
- When trying to use the `OmniSharp: Select Project` command, it throws the following error:
`command 'o.pickProjectAndStart' not found`

According to https://github.com/OmniSharp/omnisharp-vscode#initial-support-for-csproj-net-core-projects there should be at least a minimal support for `.csproj` files, or have I interpreted that wrong?

## Possibly related issues
#283 and #767

**Comment by gregg-miskelly** [comment]
@GGG-KILLER you look at https://github.com/OmniSharp/omnisharp-vscode/projects/2 to track the various work items related to support for .NET Core csproj.

To get dependencies to resolve, try doing a `dotnet restore` on the command line.

**Comment by GGG-KILLER** [comment]
@gregg-miskelly Oh, thank you! Since the description on the readme was a bit ambiguous I had no idea of what was actually available or not.

I suppose I'll just close this as a duplicate of #767 then.
