### ISSUE TITLE
Always show "Downloading package 'OmniSharp (.NET 4.6 / x64)' (12310 KB) ."

### ISSUE THREAD

**Issue by qslcna** [OmniSharp/omnisharp-vscode#1028]
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
```

VS Code version: `1.7.2`
C# Extension version: `1.5.3`

## Steps to reproduce
Open vscode
Open a .cs file 

## Actual behavior
OUTPUT
```
Updating C# dependencies...
Platform: win32, x86_64 (win7-x64)

Downloading package 'OmniSharp (.NET 4.6 / x64)' (12310 KB) .Failed at stage: downloadPackages
Error: read ECONNRESET

Finished
[ERROR]: C# Extension failed to install the debugger package
```
##
I check the package.json file and find the this:
```
{
	"description": "OmniSharp (.NET 4.6 / x64)",
	"url": "https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.9-beta19.zip",
	"installPath": "./bin/omnisharp",
	"platforms": [
		"win32"
	],
	"architectures": [
		"x86_64"
	]
},
```
and 
```
{
	"description": ".NET Core Debugger (Windows / x64)",
	"url": "https://vsdebugger.azureedge.net/coreclr-debug-1-5-0/coreclr-debug-win7-x64.zip",
	"fallbackUrl": "https://vsdebugger.blob.core.windows.net/coreclr-debug-1-5-0/coreclr-debug-win7-x64.zip",
	"installPath": ".debugger",
	"runtimeIds": [
		"win7-x64"
	]
}
```
I download those files(`coreclr-debug-win7-x64.zip` and  `omnisharp-win-x64-1.9-beta19.zip`) manually and decompression those files, and copy them to
 `.vscode\extensions\ms-vscode.csharp-1.5.3\bin\omnisharp` and
 `.vscode\extensions\ms-vscode.csharp-1.5.3\.debugger`
But can't resolve it. Is there some way install them manually?

**Comment by DustinCampbell** [comment]
@qslcna: Sorry for the delay here. Are you behind a proxy of some sort?

**Comment by qslcna** [comment]
@DustinCampbell  At first I use Shadowsocks. While I close the proxy, still has this issue. I am china. So the speed is relatively slow.

**Comment by DustinCampbell** [comment]
I see -- it may in fact just be that the download is struggling. Do you still get the ECONNRESET error when the proxy is closed? Does that happen immediately or after several seconds or minutes.

**Comment by qslcna** [comment]
Yes, same error as use proxy. Both happened after several minutes.

**Comment by qslcna** [comment]
@DustinCampbell  So is there some way install them manually?

**Comment by ZHY95** [comment]
same question. want to install them manually

**Comment by DustinCampbell** [comment]
Sorry for the delay. I needed to get 1.6 out the door before taking some time to write up the steps below. Note that this isn't much fun, but you can use these steps to download the necessary packages and installing them manually. This really isn't supported but it should work.

1. Download the relevant packages using the URLs from the "runtimeDependencies" node in the extension's [package.json](https://github.com/OmniSharp/omnisharp-vscode/blob/master/package.json) file. Make a note of which package entries in the "runtimeDependencies" node you're downloading from because you'll use additional information from those entries in the next steps.
    * Windows:
        * **OmniSharp**: Either `"OmniSharp (.NET 4.6 / x86)"` or `"OmniSharp (.NET 4.6 / x64)"` depending on whether you're running 32-bit or 64-bit Windows respectively.
        * **Debugger**: `".NET Core Debugger (Windows / x64)"` (**Note:** 32-bit Windows is not yet supported by the debugger. If you're running 32-bit Windows, you can skip the debugger.)
    * OSX:
        * **Mono**: `"Mono Runtime (macOS)"` and `"Mono Framework Assemblies"`
        * **OmniSharp**: `"OmniSharp (Mono 4.6)"`
        * **Debugger**: `".NET Core Debugger (macOS / x64)"`
    * Linux:
        * **Mono**: Either `"Mono Runtime (Linux / x86)"` or `"Mono Runtime (Linux / x64)"` (depending on whether your're running on 32-bit or 64-bit Linux), and `"Mono Framework Assemblies"`
        * **OmniSharp**: `"OmniSharp (Mono 4.6)"`
        * **Debugger**: A version of the debugger that matches your distro (there are several).

2. Unzip each package that you downloaded into a subdirectory within the extension install folder.
    * **Extension install folder**: The extension install folder is located at `%UserProfile%\.vscode\extensions\ms-vscode.csharp-<version>` on Windows and `~/.vscode/extensions/ms-vscode.csharp-<version>` on OSX/Linux.
    * **Subdirectory**: The subdirectory is specified by the package's "installPath" from the "runtimeDependencies" node.

    For example, on 64-bit Windows, you'd unzip `"OmniSharp (.NET 4.6 / x64)"` to `%UserProfile%\.vscode\extensions\ms-vscode.csharp-<version>\bin\omnisharp`.

3. _(OSX/Linux-only)_ Mark files in the "binaries" section of a package's "runtimeDependencies" entry as executable with `chmod 755 <file path>`. Note that these file paths are relative to the package's "installPath".

4. Create a 0-length file called "install.Lock" in the extension install folder. This is easily done with `touch install.Lock` in an OSX/Linux terminal window or `copy NUL > install.Lock` at a Windows command prompt.

And that should be it! If everything is right, you should be able to launch Visual Studio Code with a C# .NET Core project and get IntelliSense and debugging (if the debugger is supported on your platform).

**Comment by renkun-ken** [comment]
I'm under Ubuntu 16.04 and the updating takes forever:

```
Updating C# dependencies...
Platform: linux, x86_64, name=ubuntu, version=16.04 (ubuntu.16.04-x64)

Downloading package 'Mono Runtime (Linux / x64)' (1549 KB) ...
```

Hanging for a while the updating ends up with similar error.

**Comment by DustinCampbell** [comment]
@renkun-ken: It's only downloading a 1.5 MB file. Do you see a similar issue when downloading https://omnisharpdownload.blob.core.windows.net/ext/mono.linux-x86_64-4.6.1.zip directly?

**Comment by renkun-ken** [comment]
I tried the link and the download was very slow (most time <10kb/s and decay to 100 b/s).  The hanging mostly happens when it downloads Ominsharp packages (more than 40MB if I remember correctly), it usually fails.

**Comment by qslcna** [comment]
@DustinCampbell Thanks, it works!

**Comment by qslcna** [comment]
@renkun-ken Use xunlei maybe better.

**Comment by fangqifan** [comment]
@qslcna  我按照上面的方法试了一遍 但是重启vscode之后 它又开始执行下载了
Updating C# dependencies...
Platform: win32, x86_64 (win7-x64)

Downloading package 'OmniSharp (.NET 4.6 / x64)' (17539 KB) ............
你有碰到这种情况吗

**Comment by renkun-ken** [comment]
I use [Lantern](https://github.com/getlantern/lantern) and set `http.proxy` to lantern proxy and the download becomes quite smooth.

**Comment by fangqifan** [comment]
@qslcna  我手动从runtimeDependencies删除了相应的节点然后好了~

**Comment by DeanHH** [comment]
@DustinCampbell Thanks a lot, the download issue really bother me a lot.
And I think there is another way to help auto running the steps you written above.
That is make a temporary host for the urls in package.json,mapping them to the location in local.After that restart you vscode ,I believe it will works well.
Because i still encounter the download too slow problem,so when finish downloaded I will give a reply to tell if it will work. :-)

**Comment by xiexin36** [comment]
Finally,It work on mac, here is the package.json, https://github.com/OmniSharp/omnisharp-vscode/blob/3363d7306cc4faeb65e9ac2f172682537104dd15/package.json.

**Comment by xiexin36** [comment]
@fangqifan 是不是没有生成install.Lock这个文件?

**Comment by Imhven** [comment]
@xiexin36 .vscode\extensions\ms-vscode.csharp-1.6.2\bin\omnisharp\install.Lock 是在这文件夹吧？我这跟@fangqifan 遇到一样的问题

**Comment by Imhven** [comment]
lock file location:.vscode\extensions\ms-vscode.csharp-1.6.2\install.Lock

**Comment by luizptm** [comment]
I didn't did the steps above and it worked for me. I justed deleted de .lock file.

**Comment by peheje** [comment]
I deleted C:\Users\USER\.vscode\extensions\ms-vscode.csharp-1.8.1\install.Begin and it worked

**Comment by szz0104** [comment]
大家好，我也遇到过这个问题，总结了下解决方案，供大家参考（本人安装的是Windows 下的  x64 架构）。
联网安装
插件库安装C#插件，点击重新加载页面
Updating C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (21928 KB) .................... Done!
Downloading package '.NET Core Debugger (Windows / x64)' (39217 KB) .................... Done!

Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'
Installing package '.NET Core Debugger (Windows / x64)'

Finished

离线安装
1.离线安装C#插件
  ms-vscode.csharp-1.12.1.vsix
2.解压到指定文件夹（路径根据用户确定：Microsoft为%UserProfile%）
  C:\Users\Microsoft\.vscode\extensions\ms-vscode.csharp-1.12.1
3.点击重新加载页面
需要离线文件（压缩的OmniSharp for Windows (.NET 4.6 / x64)' (21928 KB) 和 .NET Core Debugger (Windows / x64)' (39217 KB)）的我稍后留下Email或者公共下载链接
Email: szz0104@hotmail.com
链接: https://pan.baidu.com/s/1dFKXpQD 密码: n4wm
欢迎使用 .NET Core!
---------------------
若要详细了解 .NET Core，请访问 https://aka.ms/dotnet-docs。使用 dotnet --help 查看 可用的命令或转到 https://aka.ms/dotnet-cli-docs。

遥测


   .NET Core 收集使用情况数据，以便改善用户体验。数据是匿名的且不包含命令行参数。数据 由 
   Microsoft 收集，并与社区共享。
   可选择使用你最喜爱的 shell 将 DOTNET_CLI_TELEMETRY_OPTOUT 环境变量设置为 1，从而退 出遥测。
   若要深入了解 .NET Core 工具遥测，请访问 https://aka.ms/dotnet-cli-telemetry。
关闭遥测Shell命令：SETX DOTNET_CLI_TELEMETRY_OPTOUT 1

**Comment by 1mpossibleHacker** [comment]
Thank You All That Worked .But Second Downloading Still İn Procces Looks Like It'll Never End

**Comment by liangmah** [comment]
the Subdirectories of 1.14.0 in Windows 10 has been changed to:
for coredlr: .../ms-vscode.csharp-1.14.0/.debugger
for omnisharp: .../ms-vscode.csharp-1.14.0/.omnisharp

**Comment by mota57** [comment]
![image](https://user-images.githubusercontent.com/7569989/39976077-cdfbc080-56ff-11e8-9579-019cf051b51d.png)


When I click on a the debug with XDEBUG it shows me those packages that are download again :(

**Comment by vnextcoder** [comment]
If you want to download the OmniSharp package on your own via Browser , you can do so using your 'favorite' browser from path below depending on your Windows' architecture. 

**X64**
    https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.30.1.zip
**X86**
    https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x86-1.30.1.zip

Full Path of the `OmniSharp.exe` would be like `C:\Users\yourusername\.vscode\extensions\ms-vscode.csharp-1.15.2\.omnisharp\1.30.1\OmniSharp.exe` to allow VSCode to pick it up and launch it.

Also make sure the install.lock is placed in `C:\Users\yourusername\.vscode\extensions\ms-vscode.csharp-1.15.2` folder as described in earlier comments. 

Full details on my Blog https://vnextcoder.wordpress.com/2018/05/23/install-omnisharp-win-x64-1-30-1-zip-vs-debugger-for-vs-code-manually/

**Comment by ejamshidiasl** [comment]
i had same problem and now i solved this.
after downloading and installing omnisharp jst wait.vscode downloading new extenision(size is about 42Mb).after 2-3 minutes download complete and after that omnisharp is ot going to download again.

**Comment by mota57** [comment]
for I just have to download .net framework 4.7.2 and it only download one time. 💃

**Comment by tluyben** [comment]
This is still happening to me with the latest version (of VSC) on all 3 OSs (win/mac/lin); after a VSC restart, it always downloads these again.

**Comment by breadnone** [comment]
Confirmed, it's still happening on Windows 10

**Comment by JoeRobich** [comment]
@tluyben @breadnone The only reason I can think of that it would be continually downloading is that the setting `omnisharp.path` has accidentally been set to `latest`. If this is the case, you can set it back to default or remove it.

**Comment by Hakej** [comment]
Still happening, on Manjaro.

**Comment by usernameSplash** [comment]
It's still happening on macOS 10.15.7.

**Comment by chipbite** [comment]
I still have an issue like this... It is quite annoying, you cant just reload vs code, it will always download foooorrreeever ;-)

![image](https://user-images.githubusercontent.com/559199/132650646-5bbd9bca-04ce-4e49-a30f-694032a2c1db.png)

I will check out the steps above. Or maybe uninstall for now.
