### ISSUE TITLE
Debugger: Failed to debugging with bits for VSCode

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#1029]
## Environment data
`dotnet --info` output:
VS Code version: 1.7.2
C# Extension version: v.1.6.0-beta3
.NET Core version: 1.0.0-preview2 -1 - 003177
OS: Fedora 24

## Steps to reproduce
1. Open VSCode
2. Install C# Extension v.1.6.0-beta3
3. Delete all files in C:\Users\<alias>\.vscode\extensions\ms-vscode.csharp-<version>\.debugger except “install.complete”
4. Unzip the contents of the matching zip file into the C:\Users\<alias>\.vscode\extensions\ms-vscode.csharp-<version>\.debugger
5. Download hwapp folder in attachments directly and open with VSCode
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/645082/hwapp.zip)
6. Set a BP at line of 9
7. F5

## Expected  behavior
The BP should be hit

## Actual behavior
The BP can't be hit and show a error message as follow:
![image](https://cloud.githubusercontent.com/assets/20184778/21088630/ec8d486a-c06b-11e6-8221-c1ec38017516.png)

**Comment by GraceDong** [comment]
This issue can reproduced on Debian 8.2.

**Comment by gregg-miskelly** [comment]
Are we just missing a `chmod +x` when manually installing? Or is this something else.

**Comment by rajkumar42** [comment]
It probably is because of the chmod +x. I'll give it a try with omnisharp vsix to see if it fixes that.

**Comment by rajkumar42** [comment]
just verified, it is a side effect of the manual install. Installing from vsix doesn't have the same problem.

**Comment by GraceDong** [comment]
Yes, this is because of the chmod +x, thanks.
