### ISSUE TITLE
Debugger:  Attach doesn't work correctly on Windows 8.1 x64 when the BP is set before debugging

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#1035]
## Environment data
`dotnet --info` output:
VS Code version: 1.7.2
C# Extension version: v.1.6.0-beat3
.NET Core version: 1.0.0-preview2 -1 - 003177
OS: Windows 8.1 x64

## Steps to reproduce
1. Open VSCode
2. Install C# Extension v.1.6.0-beta3
3. Delete all files in C:\Users.vscode\extensions\ms-vscode.csharp-.debugger except “install.complete”
4. Unzip the contents of the matching zip file into the C:\Users.vscode\extensions\ms-vscode.csharp-.debugger
5. Download hwapp folder in attachments directly and open with VSCode
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/645561/hwapp.zip)
6. Launch the project in Command Prompt using the command "dotnet run"
7. Select the debug type “.Net core Attach”
8. Set a BP at line of 13
9. Press F5 to start debugging
10. Select process ID on UI

## Expected  behavior
This bp should be hit

## Actual behavior
The bp can't be hit and show error message in debug console as following:
"ERROR: Unable to start debugging. Unexpected CLRDBG output from command "-interpreter-exec console "info sharedlibrary"". Undefined MI command: interpreter-exec
"
##Investigation:
This issue doesn't appear every time, but if steps 9 and 10 are executed first, then executed step 8, the bp can always be hit.

**Comment by gregg-miskelly** [comment]
Sounds like an issue with the MI Engine...

**Comment by GraceDong** [comment]
May be... And this issue also happened on my machine with openSUSE 42.2 installed.

**Comment by GraceDong** [comment]
Similar issue on Rhel 7.

**Comment by qian6** [comment]
Similar issue on win7 x64 and win10 x64

**Comment by GraceDong** [comment]
This issue can repro on my Debian and CentOS.
