### ISSUE TITLE
Debugger: The .NET CLI tools cannot be located on RHEL Linux. 

### ISSUE THREAD

**Issue by ClaireKang** [OmniSharp/omnisharp-vscode#1037]
dotnet --info output:
VS Code version: 1.7.2
C# Extension version: v.1.6.0-beat3
.NET Core version: 1.0.0-preview2 -1 - 003131
OS: Redhat7.2 

## Steps to reproduce
1. Install .Net Core for Red Hat Enterprise Linux 7 Server [according](https://www.microsoft.com/net/core#linuxredhat)

2. Download hwapp folder in attachments directly and open with VSCode
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/648283/hwapp.zip)

3. Install C# Extension v.1.6.0-beta3

## Expected  behavior
Install successfully without any error 

## Actual behavior
![error](https://cloud.githubusercontent.com/assets/20184768/21132450/094de9da-c14f-11e6-9da4-647ab5023af9.png)

##Investigation
1. I have successfully installed .net core, and created a project using the command 'dotnet new'.
2. I installed .net core, then run './code' within the same terminal to open VS code. VS code worked correctly and the error didn't reproduce. When I double click to open a VS code instance, the error reproduce. 
3. The .net core can be automatically located by vscode on other Linux distributions(eg: Ubuntu14 /Fedora23 /Centos7 /opensuse42.2).

**Comment by gregg-miskelly** [comment]
Yes, this is expected on RHEL. See https://github.com/OmniSharp/omnisharp-vscode/issues/508.

The work around --
Launch VS Code from the .NET environment with: `scl-enable rh-dotnetcore10 code` (or really probably 11 now)
