### ISSUE TITLE
Alarming interpretation of license requirement

### ISSUE THREAD

**Issue by vossad01** [OmniSharp/omnisharp-vscode#1039]
I just got VS Code compiling a Hello World program on Linux.  The first thing I saw when it worked was this banner:

> ```
> --------------------------------------------------------------------------------
> You may only use the C# Extension for Visual Studio Code with Visual Studio
> Code, Visual Studio or Xamarin Studio software to help you develop and test your
> applications.
> --------------------------------------------------------------------------------
> ```

Which lead me on the chase of **_???! they are trying to throw some license restriction controlling what editors I can use to write my applications_**, which really did not match my understanding of what MS had been up to with open source.  I tracked that message back to this code base.

I don't think that my initial interpretation was correct.  However, I am not a lawyer, nor are most developers, so if there is a way to make that message's intent a little more clear, have a link to "more information," or otherwise make it less alarming it would probably be good.  As is, there are about 3 different ways I could potentially parse the statement.

**Comment by gregg-miskelly** [comment]
The intended meaning of that sentence is to say that you cannot take the debugger out of VS Code and use it in another IDE. But it was written by lawyers, so it is maybe not so readable :)

We actually just tweaked the wording today. Is now says the following. Is that any more clear? I am happy to take suggestions back to the lawyers.

```
You may only use the Microsoft .NET Core Debugger (clrdbg) with Visual Studio
Code, Visual Studio or Visual Studio for Mac software to help you develop and
test your applications.
```

**Comment by vossad01** [comment]
That version fixes my initial misinterpretation which I am happy to see.

If it is any help, here is how I read the tweaked wording:

> You may only use the Microsoft .NET Core Debugger (clrdbg) with Visual Studio
Code, Visual Studio or Visual Studio for Mac software to help you develop and
test your applications.

The above tells me:
 * The debugger may only be used with those softwares
 * Therein, it can only used to "help develop" and "test",
 * and only for "my" applications

I don't know if the part I bolded above actually carries the legal weight I interpreted it as above, or if it is just explaining the role of the debugger.

> You may only use the Microsoft .NET Core Debugger (clrdbg) with Visual Studio
Code, Visual Studio or Visual Studio for Mac software.

Tells me that the debugger can only be used with those applications, matching what you said the indented meaning is.

> You may only use the Microsoft .NET Core Debugger (clrdbg) with Visual Studio
Code, Visual Studio or Visual Studio for Mac software **and only** to help you develop and
test your applications.

The above modification removes [for me] the potential ambiguity in the above making it explicit that the last part is intentioned as restrictions.

**Comment by gregg-miskelly** [comment]
Thanks! I sent your feedback on to our legal team.

**Comment by DustinCampbell** [comment]
@gregg-miskelly: Is there anything else to follow up on here or can this issue be closed?

**Comment by phillip-haydon** [comment]
Why is there license restrictions to begin with?
