### ISSUE TITLE
How to re-enable auto generate assets for build and debug in VSC

### ISSUE THREAD

**Issue by LiangZugeng** [OmniSharp/omnisharp-vscode#1040]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

VS Code version: 1.7.2
C# Extension version: 1.5.3

## Steps to reproduce
1. md test1
2. cd test1
3. dotnet new
4. Open test1 folder in VSC, then VSC asks "Required assets to build and debug are missing from your project, Add them?", click "Don't ask again".
5. Close VSC
6. Re-open VSC and test1 folder in it, there is no prompt to allow auto generate .vscode folder in test1

I should NOT have clicked the "Don't ask again" button, that was a mistake, I want to re-enable this prompt but failed to find where to configure this option, the only option for me now is to press F1 and type generate and then select ".NET: Generate Assets for Build and Debug" but it requires extra typing and selection.

**Comment by LiangZugeng** [comment]
Never mind, I found the prompt shows for new projects created in new folders, for this project I can simply use the command to generate .vscode, it's no big deal.

**Comment by simeyla** [comment]
All it does is creates .vscode folder and adds launch.json ?
