### ISSUE TITLE
Typing "override" gives no suggestion based on the base class.

### ISSUE THREAD

**Issue by AlexandreFiset** [OmniSharp/omnisharp-vscode#1044]
## Environment data
`dotnet --info` output:
VS Code version: 1.8.0
C# Extension version: 1.5.3

## Steps to reproduce
1. Create a class.
2. Create a virtual/abstract method.
3. Create a new class that derives from class 1.
4. Type "override".
5. Notice there is no autocomplete as opposed to Monodevelop and VS2015 that both support this awesome, practical behaviour.

## Expected  behavior
Typing "override" should show me a list of all possible overrides from base class.

## Actual behavior
Typing "override" gives no suggestion based on the base class.

**Comment by grzegorz-herman** [comment]
I second this request. When inheriting generic base classes with elaborate type arguments, not having to re-type the signatures would save a lot of energy!

**Comment by Leopotam** [comment]
+1 - i have alot of pain each time for searching parent class with method signature (it can be down 2-4 levels of abstraction sequence), want to write "override" keyword and select method from list.

**Comment by juanfornospomelo** [comment]
+1

**Comment by appetizermonster** [comment]
+1

**Comment by Leopotam** [comment]
@DustinCampbell multiple requests during last 3 months - no assignees. Can we know devs plans about this problem?

**Comment by DustinCampbell** [comment]
The work is primarily in omnisharp-roslyn, where we need to create a new endpoint. It's on my list, but at the moment, all work goes serially through me. So, as I work through the backlog in priority order, I'll get to it.

Do note that this is an open source project and we're accepting contributions! :smile:

**Comment by chuckries** [comment]
@DustinCampbell I'd be interested in taking a shot at this, but I really have no clue what's going on. I set up a debuggable Omnisharp on my box and hooked it up to VS Code. All I've determined so far is that after typing 'override' and a space, the csharp intellisense service is not getting an AutocompleteRequest. Any suggestions on where to go from there?

**Comment by DustinCampbell** [comment]
In the VS Code extension, you'll need to ensure that completion can trigger on a space character.

**Comment by chuckries** [comment]
There are some immediate issues with this. If we include the space character as a completion target, the full completion list appears on every space. It does not look like vscodes 'provideCompletionItems' gives any indication of whether the autcomplete was triggered automatically by typing or manually by a gesture (ctrl + space being the default). 

I know VS IDE's behavior is to show the completion list for override items on space after 'override'. Maybe here we include these items when typing override?

**Comment by DustinCampbell** [comment]
Note: You'd need to update OmniSharp itself to make this work. This can't be done via extension alone and requires a new endpoint to be added to OmniSharp.

I would prefer to replicate Visual Studio's behavior here if we can. We have a goal of making features which are heavy on muscle memory somewhat consistent within the Visual Studio family.

**Comment by chuckries** [comment]
Even with the correct endpoint in place on the server, I'm not sure how we could get the extension to trigger the request at the right time.

**Comment by DustinCampbell** [comment]
Sure we can. We need a new endpoint in the OmniSharp server and the extension would *stop* listening to the old /autocomplete endpoint. The new endpoint would essentially be a passthrough to the Roslyn CompletionService API. That API provides a lot more smarts about whether a list should trigger or not.

**Comment by chuckries** [comment]
I'm a little confused, it looks like the existing AutoComplete endpoint is using Roslyn's CompletionService. In fact, the CompletionService is actually giving me the correct completions for override:
![image](https://cloud.githubusercontent.com/assets/6598594/24268382/da0832a0-0fca-11e7-9c39-07f2f7b17eba.png)

These are getting dropped on the floor because they are not keywords. 

Is a new server endpoint part of a bigger work item?

**Comment by DustinCampbell** [comment]
Yes, it is part of a bigger work item. Today, we only use it for keywords because of backward compatibility of the /autocomplete endpoint with other OmniSharp editors (like VIM, Emacs, Sublime, Atom, etc.). In addition, the /autocomplete endpoint is not suitable for all of the information that can be returned by the Roslyn CompletionService.

That bigger work item is tracked here: https://github.com/OmniSharp/omnisharp-roslyn/issues/78.

**Comment by chuckries** [comment]
I see. I think in that case I'll bow out. Thanks for the info!

**Comment by chuckries** [comment]
FWIW, I still think you will run into issues on the VS Code side. You will need to begin triggering autocomplete v2 requests on space. This will cause available 'recommended symbols' to show up on every space.

**Comment by DustinCampbell** [comment]
Only if the new service allows triggers on space. The Roslyn CompletionService allows completion to be triggered differently depending on what character was typed and what the current position is in the syntax tree. So, it returns a completion list when SPACE is typed after "override" and "new". It won't return a list at all in other situations.

**Comment by chuckries** [comment]
Today's implementation gets the completion list and then appends all 'recommended symbols' for the position as well.
```csharp
                var model = await document.GetSemanticModelAsync();
                var symbols = await Recommender.GetRecommendedSymbolsAtPositionAsync(model, position, _workspace);
```
If the extensions queries Omnisharp on SPACE, even though Roslyn's CompletetionService returns no completions, the list of recommended symbols would still be returned and shown on every SPACE. It seems like we would want to show recommended symbols ONLY if the autocomplete was triggered manually with a gesture (ctrl + SPACE). VS Code's API does not allow you to determine if the autcomplete is triggered manually or not.

**Comment by DustinCampbell** [comment]
Yes. I know that's how it works today. That code would all go away with the new end point.

**Comment by DustinCampbell** [comment]
The thing that might not be clear is that this would be a brand new end point that lives next to autocomplete. It would all be new code that just talks to Roslyn's CompletionService.

**Comment by chuckries** [comment]
The issues I think I am seeing all relate to querying Omnisharp from the extension, regardless of new endpoint. In VS there are instances where intellisense shows nothing until you manually invoke it using ctrl + SPACE. If we want to show autcomplete after the `override` keyword, the extension must be invoking it's completionProvider on SPACE. On most SPACE's, there will be no autcompletes to show. However, the user may want to manually invoke autcomplete to show recommendations. I do not believe VS Code will allow you to distinguish between these two. A space and a ctrl + space would trigger the exact same request.

**Comment by DustinCampbell** [comment]
Space and Ctrl+Space *should* trigger the same request. This is something we've been trying to move toward in VS.

**Comment by chuckries** [comment]
Thank you for your patience and information. I am asking simply because I am interested in this space. I am curious what the plan is for cases where there are no autocomplete items, but the user may want to invoke intellisense with ctrl + SPACE in order to see available suggestions that are not necessarily autocomplete items. For example, if I type `int i =` followed by a SPACE, there are no autocomplete items but I may want to invoke Intellisense with ctrl + SPACE to see all available suggestions.

**Comment by DustinCampbell** [comment]
Correct. After typing `int i =` followed by <kbd>SPACE</kbd>, the Roslyn CompletionService won't return a completion list. The issue here is that OmniSharp will need a completion end point that allows different triggers to be specified by the VS Code extension. Roslyn distinguishes between typing as a trigger (e.g. <kbd>SPACE</kbd>) and an invocation of the list (e.g. <kbd>CTRL+SPACE</kbd>).

**Comment by chuckries** [comment]
>that allows different triggers to be specified by the VS Code extension

I think this may be an issue. I couldn't find any way to distinguish these triggers from the VS Code endpoint. VS Code's API reports <kbd>SPACE</kbd> and <kbd>CTRL+SPACE</kbd> as identical triggers.

**Comment by DustinCampbell** [comment]
If that's the case, we'll probably need an ask on VS Code to help us distinguish between them.

**Comment by appetizermonster** [comment]
Is there any news? :smiley:

**Comment by Leopotam** [comment]
**appetizermonster**

> Assignees
> No one assigned

I think, no. You can check commits, logging and addiing TODO-s comments more important than basic language features :)

**Comment by pedro15** [comment]
Any news ?? :D

**Comment by DustinCampbell** [comment]
@pedro15: A crude form of override completion is already present. It just doesn't trigger on SPACE. You have type the first character of the override method.

**Comment by pedro15** [comment]
@DustinCampbel Thanks !

**Comment by AlexandreFiset** [comment]
As of the latest version of both VSCode and OmniSharp (October 10th), the auto-complete for overriding of methods still isn't implemented. 

If you were to override MyMethod (int myInt), you would have to manually type the requirement, plus do all the formatting by yourself. 

Yes, typing "override M" now gives me the name of the base method, but at the bottom of the list of suggestions (even if that is the only method to override) and with no autoformat.

Again a deal breaker to me. I can't believe people are using VSCode; even Monodevelop is vastly superior.

Going back to Visual Studio.

**Comment by AlexandreFiset** [comment]
@DustinCampbell I understand that and unfortunately with my company and the growing team I can't really invest time in other projects for the time being. That being said, I left a comment to avoid other people wasting their time installing VSCode and hit the same wall as I did. I'll try to budget some resources to help out in the future.

**Comment by AbhimanyuAryan** [comment]
Looking forward to this. Anytime timeline/roadmap when will this fix?

**Comment by helios02** [comment]
Any update on auto-completing method signatures for overrides? Thanks.

**Comment by Leopotam** [comment]
@Necronux why not cstop developing omnisharp-vscode then? What is main goal of this extension?

**Comment by Necronux** [comment]
@Leopotam I'm not saying it's worthless, but I'm saying it's still far behind full-blown IDEs to be productive with it. You will certainly spend more time writing some piece of code with omnisharp-vscode than with vs or rider.

It's meant to be lightweight but we aren't there yet with features to compete with IDEs

**Comment by sattha** [comment]
+1 still hoping for this in 2019

**Comment by keithelder** [comment]
@DustinCampbell I just ran into this and sitting here thinking I was doing something weird in VSCode by not getting the return arguments from the method I override. Is it time to start with beer bribery to maybe get this implemented? :)

**Comment by ssameng** [comment]
I check back every hundred times Visual Studio Mac hangs and crashes on me (so every week?) hoping this is implemented. I sadly am just not nearly as productive without this feature.

I'd love to support this in some way so I can finally switch to VS Code.

**Comment by npuc85** [comment]
If I type `override ` and then press `ctrl + space` intellisense opens with methods I can override, but when I choose one it only autofills the method name and parameter list. You still need to know what the return type is and go back and manually type it out.

**Comment by kasradzenika** [comment]
1,188 days later...

**Comment by hermitcat** [comment]
> 1,188 days later...

Created a github account just to second this.

**Comment by webczat** [comment]
now that seems to partially work for me except it does not put the return type, and doesn't type the accessibility modifier. So I have to guess more or less. Still better than nothing though

**Comment by FreshlyBrewedCode** [comment]
+1 current workaround for this is to hit CTRL+. on the class definition and select "Generate overrides".

**Comment by Koopa1018** [comment]
Didn't know about that shortcut. Thanks!

**Comment by toptensoftware** [comment]
+1 for this.

As temporary stop gap until the "override" + space can be made to work properly, any chance of "Generate override" command?   Basically the same as the "Generate overrides" command, but instead of generating all available overrides prompts for which method to override?

Also, there probably shouldn't be ellipsis on the "Generate Overrides..." command as it doesn't prompt before it does its thing. Nor on the other Generate commands for that matter.

Brad

**Comment by gzz100** [comment]
+1

**Comment by NemoStein** [comment]
`No one assigned` for
- 114,307,200 seconds
- 1,905,120 minutes
- 31,752 hours
- 1323 days

Or 3 years, 7 months, 15 days and counting...
