### ISSUE TITLE
omnisharp server not found

### ISSUE THREAD

**Issue by enricforn** [OmniSharp/omnisharp-vscode#1056]
## Environment data
`dotnet --info` output:
PS C:\Users\Enric> dotnet --info
.NET Command Line Tools (1.0.0-preview5-004232)

Product Information:
 Version:            1.0.0-preview5-004232
 Commit SHA-1 hash:  355b6233cb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview5-004232

VS Code version: 1.8.0
C# Extension version: 1.5.3

## Steps to reproduce
Open a brand new web app with visual studio code, try to compile and it seems omnisharp.exe file is not found:

Message found to omnisharp log:

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

Message found to c# log:

Updating C# dependencies...
Platform: win32, unknown

Finished

Message found to tasks log:

Failed to launch external program msbuild /property:GenerateFullPaths=true.
spawn msbuild ENOENT

## Expected  behavior

dotnet core web app should be compiled and able to debug properly.

## Actual behavior

dotnet core web app could not be compiled from vs code.

@DustinCampbell new issue created from #938 .

**Comment by DustinCampbell** [comment]
That's for creating a new issue! This bit is likely where the problem lies:

```
Platform: win32, unknown
```

It looks to me like it's unable to detect the Windows architecture (i.e. 32-bit or 64-bit) that you're running on. So, it fails to pick an OmniSharp server to download.

Could you do the following for me? At a command line, run `wmic os get osarchitecture` and let me know the output.

**Comment by enricforn** [comment]
Command run, and the output is:

PS C:\Users\Enric> C:\Windows\System32\wbem\wmic.exe os get osarchitecture
OSArchitecture
64 bits


Let me know if you need  additional info about my environment.

**Comment by DustinCampbell** [comment]
Hmmm... that's weird. This line should be catching it: https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/platform.ts#L178.

I note that you typed the full path. Is `wmic` not on your path?

**Comment by enricforn** [comment]
Yes I must type full path because wmic seems was not on path. I review system environment variable "path", and I found C:\Windows\System32...

**Comment by enricforn** [comment]
Just added wmi to path and it work fine.

Thanks for your help :) @DustinCampbell
