### ISSUE TITLE
The .NET CLI tools cannot be located.

### ISSUE THREAD

**Issue by dmumladze** [OmniSharp/omnisharp-vscode#1062]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-1-003155)

Product Information:
 Version:            1.0.0-preview2-1-003155
 Commit SHA-1 hash:  d7b0190bd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

VS Code version:
C# Extension version:
1.5.3

## Steps to reproduce
The issue is that not entire %PATH% is getting loaded into VS Code. For example, I can reproduce it on Windows OS with a %PATH% variable that is up to 2k chars long and if I add the dotnet.exe location at the end. Moving the location at the beginning of the $PATH% variable solves the issue.

## Actual behavior
Getting error upon launching VS Code: The .NET CLI tools cannot be located. .NET Core debugging will not be enabled. Make sure .NET CLI tools are installed and are on the path.

**Comment by gregg-miskelly** [comment]
@damieng I don't know that we can really do anything about this issue. Any suggestions?

**Comment by damieng** [comment]
Did you mean to ping me?  I don't have anything specific to do with omnisharp-vscode other than some collaboration on the syntax grammar.

**Comment by gregg-miskelly** [comment]
@damieng sorry, no

**Comment by gregg-miskelly** [comment]
@dmumladze I don't know that we can really do anything about this issue. Any suggestions?

**Comment by dmumladze** [comment]
@gregg-miskelly Hmm, I though the Windows environment variable limit was much more than 2k chars, but if that's not how it is, I'm not sure what to suggest. :-)

**Comment by gregg-miskelly** [comment]
From what I can gather on [msdn](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682653(v=vs.85).aspx) the maximum size at the very lowest levels on Windows is much larger -- 32,767. But fundamentally someone is calling GetEnvironmentVariable("PATH", ...) + SearchPath to locate the path to dotnet, and something must be using a much smaller limit.

**Comment by gregg-miskelly** [comment]
Oh, I just realized that we are talking the system environment, which means its stored in the registry, which means it is subjected to the 2048 character limit that Raymond Chen talked about [here](https://blogs.msdn.microsoft.com/oldnewthing/20100203-00/?p=15083/). So I don't think there is anything that can be done.
