### ISSUE TITLE
Upgrade from package.json/xproj --> csproj?

### ISSUE THREAD

**Issue by asadsahi** [OmniSharp/omnisharp-vscode#1073]
With 1.6.0 release, can we use dotnet core web project which is on .net 1.1 and using project.json?

Perhaps answer is yet, but two questions:

1) How to upgrade?
2) Will we be able to add packages through intellisense same as project.json currently allowes to see versions etc?

**Comment by DustinCampbell** [comment]
Yes, you can still use project.json-based .NET Core projects as you did before. If you want to upgrade from a project.json-based .NET Core project to a csproj-based .NET Core project, you should:

1. Ensure that you have a recent .NET Core SDK installed. (Ideally, a preview5 build downloaded from https://github.com/dotnet/cli).
2. Run `dotnet migrate` at the command line.

Let me know if you have any other questions.

**Comment by asadsahi** [comment]
@DustinCampbell migration succeeds, next question is how we can manage the nuget packages for the project now? With project.json Vs code was giving intellisense, but with csproj, what is the strategy of maintaining  project dependencies?

Thanks

**Comment by DustinCampbell** [comment]
There isn't IntelliSense in csproj files for NuGet packages yet. This is planned (https://github.com/OmniSharp/omnisharp-vscode/issues/436) but probably won't happen for awhile.

Note that the .NET CLI is also adding commands for updating projects and solution files: https://github.com/dotnet/cli/issues/4746.
