### ISSUE TITLE
1.6.0 for VSCode reintroduced the syntax bug for escape double quote

### ISSUE THREAD

**Issue by xuzf-thl** [OmniSharp/omnisharp-vscode#1078]
VS Code version: 1.7.1
C# Extension version: 1.6.0

## Steps to reproduce
in a .cs file, if the string as an escape double quote `\"`, Omnisharp will not show proper syntax for the code following it.
Like the code below:
```C#
            configContent = rgx.Replace(configContent, $"name{suffix}\"");
            File.WriteAllText(_testConfigFile, configContent);
        }
```
**Note**: C# Extension version 1.5.3 doesn't have this bug.
## Expected  behavior
the code after `\"` should still show the proper syntax.

## Actual behavior
the code after it shows as string, until the next double quote.

**Comment by DustinCampbell** [comment]
Thanks for taking the time to report this issue!

cc @ivanz

**Comment by ivanz** [comment]
Will fix this and add some tests when I am back from holidays in a week or so 👍

**Comment by aadnehovda** [comment]
Same issue, another example:
![image](https://cloud.githubusercontent.com/assets/1244723/21702188/803357ca-d3aa-11e6-9f12-67edfd41e568.png)

**Comment by DustinCampbell** [comment]
I'll have fixes for this in the near future.

**Comment by DustinCampbell** [comment]
Both of these examples should be working in the next release:

![image](https://cloud.githubusercontent.com/assets/116161/21740099/4c48db9c-d463-11e6-8b84-0d8d9ddb47e0.png)

![image](https://cloud.githubusercontent.com/assets/116161/21740100/4f1ef36a-d463-11e6-8a1c-37971bdb038f.png)

**Comment by xuzf-thl** [comment]
for reference: this bug was reported and fixed before: https://github.com/OmniSharp/omnisharp-vscode/issues/442

**Comment by DustinCampbell** [comment]
The bug regressed. This is fixed properly now and tests are in place to ensure it doesn't return. We've written a completely new TextMate grammar for C# that is much more robust than what shipped previously.
