### ISSUE TITLE
After update the Unity to Latest version,I cannot use the IntelliSense.

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#108]
_From @zhe13 on March 18, 2016 12:35_

- VSCode Version:0.10.11 (0.10.11)
- OS Version:OS X 10.11.3
- Unity Version:5.3.4f1

I am sure that I am not faced with the OmniSharp problem cause my Code tells me it is running  with the x-sharp.sln.And I have update the vscode-unity plugin.
I can not get any of them -- Syntax Highlighting or Bracket matching or IntelliSense.

I have update home-brew and reinstall the mono.
How can I do next?

_Copied from original issue: Microsoft/vscode#4416_

**Comment by rakkarage** [comment]
it still works fine for me in 11 and 12
ensure all your vscode extensions are updated (c# & unity)
what does view->output->omnisharp log say?

**Comment by zhe13** [comment]
>Thx for repeating.

Omnisharp log looks like that
>[INFO] Starting OmniSharp at '/Users/wutianzhe/Developer/Unity/UnityDemo－Zombie/UnityDemo－Zombie-csharp.sln'...
[INFO] Started OmniSharp from '/Users/wutianzhe/.vscode/extensions/ms-vscode.csharp-0.3.7/bin/omnisharp' with process id 1473...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location '/Users/wutianzhe/Developer/Unity/UnityDemo－Zombie' on host 1459.
[ERROR:OmniSharp.Dnx.DnxPaths] The specified runtime path 'default' does not exist. Searched locations /Users/wutianzhe/.dnx/runtimes/dnx-mono.default
/Users/wutianzhe/.dnx/runtimes/kre-mono.default
/Users/wutianzhe/.dnx/packages/KRE-Mono.default
/Users/wutianzhe/.k/runtimes/dnx-mono.default
/Users/wutianzhe/.k/runtimes/kre-mono.default
/Users/wutianzhe/.k/packages/KRE-Mono.default
/Users/wutianzhe/.kre/runtimes/dnx-mono.default
/Users/wutianzhe/.kre/runtimes/kre-mono.default
/Users/wutianzhe/.kre/packages/KRE-Mono.default.
Visit https://github.com/aspnet/Home for an installation guide.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning '/Users/wutianzhe/Developer/Unity/UnityDemo－Zombie' for DNX projects
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] No project.json based projects found
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Detecting projects in '/Users/wutianzhe/Developer/Unity/UnityDemo－Zombie/UnityDemo－Zombie-csharp.sln'.
[WARNING:OmniSharp.MSBuild.MSBuildProjectSystem] Skipped unsupported project type 'Assembly-CSharp-vs.csproj'
[WARNING:OmniSharp.MSBuild.MSBuildProjectSystem] Skipped unsupported project type 'Assembly-CSharp-Editor-firstpass-vs.csproj'
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in '/Users/wutianzhe/Developer/Unity/UnityDemo－Zombie'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Solution has finished loading


It tells Error--"The specified runtime path 'default' does not exist. Searched locations /Users/wutianzhe/.dnx/runtimes/dnx-mono.default"

**Comment by zhe13** [comment]
Maybe I need to reinstall the ASP.NET Framework on Mac OS X ?

**Comment by zhe13** [comment]
@rakkarage I have reinstalled my ASP.NET 5 on OS X .
Error is still here,but something has changed.
>The specified runtime path 'default' does not exist. Searched locations /Users/wutianzhe/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-rc1-update1
/Users/wutianzhe/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-rc1-update1
/Users/wutianzhe/.dnx/packages/dnx-coreclr-darwin-x64.1.0.0-rc1-update1
/Users/wutianzhe/.k/runtimes/dnx-mono.default
/Users/wutianzhe/.k/runtimes/kre-mono.default
/Users/wutianzhe/.k/packages/KRE-Mono.default
/Users/wutianzhe/.kre/runtimes/dnx-mono.default
/Users/wutianzhe/.kre/runtimes/kre-mono.default
/Users/wutianzhe/.kre/packages/KRE-Mono.default.
Visit https://github.com/aspnet/Home for an installation guide.

**Comment by zhe13** [comment]
& the dnvm logs like that

```bash
Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
  *    1.0.0-rc1-update1    coreclr x64          darwin          default
       1.0.0-rc1-update1    mono                 linux/osx       
```

**Comment by zhe13** [comment]
I have solved this issue by referring (Mac Omnisharp Error on RC1 #126)[https://github.com/Microsoft/vscode/issues/126] .However, there is no more IntelliScene

**Comment by pflannery** [comment]
I have this same intellisense issue for  `5.3.4f1`. But I have a project in `5.3.1p2` and it works.

When trying to access intellisense this is output to the console

![image](https://cloud.githubusercontent.com/assets/1727302/13905837/eedccb70-eec2-11e5-88c7-2e4decf15735.png)

**Comment by DustinCampbell** [comment]
Hi everybody!

I've just added a new release that provides support for MSBuild projects on OS X and Linux [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.1.7). Could you install this new VSIX into VS Code and see if it works for you? Be sure to uninstall the Legacy C# Support extension if you have it installed.

**Comment by hunterloftis** [comment]
@DustinCampbell I installed the file (I think - VS code gives no user feedback) via `$ code csharp-1.1.7.vsix`. Nothing seems to happen and there are no new extensions.

**Comment by pflannery** [comment]
This is working for me now. thanks
```
unity v5.3.5p7
vs code v1.3.0
c# v1.2.2 (vscode extension) 
```

**Comment by DustinCampbell** [comment]
Take Two! I've just released [v.1.3.0-beta1](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.3.0-beta1) which brings support for two OmniSharp servers: a .NET Core one for project.json projects, and a Mono/Desktop version for .csproj/.sln projects. Please try this out and let me know if it fixes Unity development for you.

**Comment by DustinCampbell** [comment]
I've released another version, [v1.3.0-beta2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.3.0-beta2), which improves the experience even further. If you've got a chance to take this for a spin, please let me know if it works for you or not.

**Comment by DustinCampbell** [comment]
@hunterloftis: Sorry that I missed your comment. You can install an extension packaged as a VSIX in VS Code simply by opening VS Code, and then opening the VSIX with File->Open File.

**Comment by DustinCampbell** [comment]
We'll be pushing this release to marketplace soon, which fixes this issue.
