### ISSUE TITLE
Is it possible to have code formatter accept tab and many spaces as whitespace

### ISSUE THREAD

**Issue by Thaina** [OmniSharp/omnisharp-vscode#1081]
There are option `SpaceBeforeXXX` which only accept true/false

But sometimes I was using tab to make space before operator, `=` and `+=`'s family operator in particular

But formatter always convert it to space and code alignment I used was gone

So I wish that formatter about spacing that set to true will just see that tab, tabs, and spaces is also whitespace and ignore it if it is there, else will insert a space into it

**Comment by DustinCampbell** [comment]
I'm not sure I fully understand your request. Are you looking the `editor.insertSpaces` setting in Visual Studio Code? If so, you can set that to `false` and tabs will be inserted instead of spaces. In addition, this setting is passed on to the C# formatter, so the formatter will use tabs as well. Does that help? If not, could you provide some code samples showing exactly what you'd like to see?

**Comment by Thaina** [comment]
@DustinCampbell I mean `FormattingOptions : { SpaceBeforeXXX }` in omnisharp.json which omnisharp use to format

`int i=0;`
into
`int i = 0;`

Something like this

But then I always use

```C#
int i	= 0;
long l	= 0;
//smart tab aligning
```

When format document it became

```C#
int i = 0;
long l = 0;
```

Maybe I place request in wrong repo, this should be in omnisharp-roslyn ?

**Comment by filipw** [comment]
These are all the options that OmniSharp can deal with at the moment https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.Abstractions/Options/FormattingOptions.cs

However, those are actually just forwarding to Roslyn https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Formatting/CSharpFormattingOptions.cs

What you are trying to do (with the smart alignment) is not possible at this time in OmniSharp - and as a feature request, it sounds to me like it actually belongs into Roslyn itself.

**Comment by Thaina** [comment]
Thanks. I was creating issue there

https://github.com/dotnet/roslyn/issues/16088

**Comment by DustinCampbell** [comment]
Thanks!
