### ISSUE TITLE
Syntax Highlighting seems not correct with cases like "new void foo()"

### ISSUE THREAD

**Issue by heshuimu** [OmniSharp/omnisharp-vscode#1084]
## Environment data
`dotnet --info` output:
VS Code version: 1.8.1
C# Extension version: 1.6.1

## Steps to reproduce

In a C# class that hides the base class method using new keyword:
```
private new void foo1() //Correct highlight
{
}

new void foo2() //Function name not highlighted
{
}
```
![capture](https://cloud.githubusercontent.com/assets/7824592/21461025/7a472e46-c913-11e6-89e9-40390d9a156e.PNG)

**Comment by DustinCampbell** [comment]
Thanks for taking the time to file this issue!

**Comment by DustinCampbell** [comment]
This should look better in the next release:

![image](https://cloud.githubusercontent.com/assets/116161/21740143/82cd4a76-d464-11e6-957b-bf31dc7f7fd4.png)
![image](https://cloud.githubusercontent.com/assets/116161/21740144/8f7f53c2-d464-11e6-8c59-3e335cd45e30.png)
