### ISSUE TITLE
Improve experience downloading C# dependencies over slow internet

### ISSUE THREAD

**Issue by renkun-ken** [OmniSharp/omnisharp-vscode#1085]
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
```

VS Code version: 1.8.1
C# Extension version: 1.6.1

## Steps to reproduce

1. Upgrade C# Extension and reload VSCode
2. Open a C# file in a .NET Core project to trigger updating C# dependencies

## Expected  behavior

The update should finish in a reasonable time.

## Actual behavior

In nearly all recent versions of updates of C# Extension, the downloading of the following packages is extremely slow and very often cannot finish, sometimes simply fails with connection error. I have to restart VSCode and again trigger the update. It has to re-download the files that have been successfully downloaded in the previous session. The following is the log hanging overnight.

```
Updating C# dependencies...
Platform: linux, x86_64, name=ubuntu, version=16.04 (ubuntu.16.04-x64)

Downloading package 'Mono Runtime (Linux / x64)' (1549 KB) .................... Done!
Downloading package 'Mono Framework Assemblies' (5828 KB) .................... Done!
Downloading package 'OmniSharp (Mono 4.6)' (16807 KB) .................... Done!
Downloading package '.NET Core Debugger (Ubuntu 16.04 / x64)' (47391 KB) ...
```

I wonder if it's possible to allow alternative download links or cache what is done?

**Comment by Richeir** [comment]
Same issue...
Every time downloading the package, it's a very terrible waiting...

**Comment by caslan** [comment]
@Richeir, is it the same ".NET Core Debugger" downloading step that is taking a long time for you?

**Comment by Richeir** [comment]
Yes, it is. @caslan
There are four packages to be downloaded before debugging the code. I tried so many times to do this step, but when it downloaded first one or two packages, it stopped, and never tried to reconnect and continue (through the Mac's network monitor).

**Comment by xiexin36** [comment]
Yes, I have the same problem, and the worst is I never downloaded the "NET Core Debugger", always failed. I have tried many times again, and again.

**Comment by HADB** [comment]
same issue. These files will be downloaded every time...

**Comment by karldodd** [comment]
Same issue. I guess this happens **a lot** in China, which is supposed to be a big market for VSCode : )

Please switch to a China-friendly link, or at least improve the download experience. Thanks.

**Comment by odboy** [comment]
When I switch the network to my personal Hotspot(4G), these files downloaded and installed only in 1 minute.  [Facepalm]

**Comment by renkun-ken** [comment]
The network problem seems to be gone.

**Comment by Mailaender** [comment]
At the moment it is painfully slow even with a fast DSL connection.

**Comment by Kryptos-FR** [comment]
Happening again. I have a 1 Gb/s connection, so it's not on my end.
