### ISSUE TITLE
Single-line comments at end of line change syntax highlighting when character after the first space is typed

### ISSUE THREAD

**Issue by chronicgamedev** [OmniSharp/omnisharp-vscode#1091]
## Environment data
`dotnet --info` output: .NET Command Line Tools (1.0.0-preview2-003121)
VS Code version: 1.9.0-insider
C# Extension version: 1.6.2

![bug](https://cloud.githubusercontent.com/assets/22398672/21477426/97c611be-caf6-11e6-8542-249dfc025f8b.gif)

## Steps to reproduce
1.  create a class
2.  create an abstract function
3.  add a // comment to the end of the line
4.  type comment, press space bar, type another character

## Expected  behavior
The function's syntax coloring remains the same and the comment stays comment-colored

## Actual behavior
The function's syntax coloring changes when adding the space and the comment takes on keyword colors.  The auto-complete suggestion list appears as well.

**Comment by DustinCampbell** [comment]
Thanks for the report!

**Comment by DustinCampbell** [comment]
This should look much better in the next release:

![image](https://cloud.githubusercontent.com/assets/116161/21822602/afe12c92-d72c-11e6-9a33-1b0c6916c1b6.png)

![image](https://cloud.githubusercontent.com/assets/116161/21822605/b2bf010a-d72c-11e6-8ae6-ff27ed1327fb.png)

![image](https://cloud.githubusercontent.com/assets/116161/21822607/b51d94fc-d72c-11e6-836c-4c38d7b2a0e9.png)
