### ISSUE TITLE
Omnisharp - c# - Vscode - Intellisense stops for few seconds then resume

### ISSUE THREAD

**Issue by ammarsabir26** [OmniSharp/omnisharp-vscode#1092]
## Environment data
`dotnet --info` output:
VS Code version: 1.8.1
C# Extension version: 1.6.2

## Steps to reproduce
I am facing this issue for past few weeks. 
Suddenly while typing the IntelliSense stops for few seconds and after some random seconds it starts working again. 

## Expected  behavior
IntelliSense should not stop while typing

## Actual behavior
Currently while i am typing , Intellisense gets off and i have to wait for it to appear again

**Comment by DustinCampbell** [comment]
Hi @ammarsabir26 --

Sorry for the delay here. Is this problem still happening for you? If so, could provide the OmniSharp Log from Visual Studio Code? Just open your project and get IntelliSense to appear. Then, select View->Output to display the Output pane and select "OmniSharp Log" from the drop-down at the top-right corner of the Output pane. Select all of the text there, copy it to the clipboard and paste it here.

**Comment by cartermp** [comment]
Closing as it has been a while and the completion service is now different
