### ISSUE TITLE
Literals wrapped in curly brackets to initialize Dictionary are not colored if opening bracket is on another line

### ISSUE THREAD

**Issue by heshuimu** [OmniSharp/omnisharp-vscode#1096]
## Environment data
`dotnet --info` output:
VS Code version: 1.8.1
C# Extension version: 1.6.1

## Steps to reproduce

<img width="668" alt="qq20161227-132739 2x" src="https://cloud.githubusercontent.com/assets/7824592/21506852/0901d4ba-cc39-11e6-8a72-68fb5834b790.png">

**Comment by DustinCampbell** [comment]
This should look much better in the next release:

![image](https://cloud.githubusercontent.com/assets/116161/21743540/0726c05a-d4b9-11e6-8720-39c58c48f3ee.png)
