### ISSUE TITLE
Fields with qualified type names are not highlighted properly

### ISSUE THREAD

**Issue by heshuimu** [OmniSharp/omnisharp-vscode#1097]
## Environment data
`dotnet --info` output:
VS Code version: 1.8.1
C# Extension version: 1.6.1

## Steps to reproduce

<img width="401" alt="qq20161227-132753 2x" src="https://cloud.githubusercontent.com/assets/7824592/21506930/b6efc79e-cc39-11e6-8cbb-7154972ed00a.png">

**Comment by DustinCampbell** [comment]
This should look much better in the next release:

![image](https://cloud.githubusercontent.com/assets/116161/21740206/825bb994-d467-11e6-84df-74da93247ac1.png)
