### ISSUE TITLE
Global omnisharp.json

### ISSUE THREAD

**Issue by zeroskyx** [OmniSharp/omnisharp-vscode#1101]
Is there any way to use omnisharp.json globally instead of having to copy it to every project manually?
Placing one in C:\Users\<User>\AppData\Roaming\Code\User does not seem to work.

Help is greatly appreciated. Thanks in advance
-Simon

**Comment by DustinCampbell** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#717

**Comment by DustinCampbell** [comment]
Moved over to omnisharp-roslyn repo as this really is a broader OmniSharp question rather than an issue for the VS Code C# extension.
