### ISSUE TITLE
omnisharp does not update package reference until restart in csproj

### ISSUE THREAD

**Issue by itn3000** [OmniSharp/omnisharp-vscode#1104]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233

VS Code version: 1.8.1
C# Extension version: 1.6.2

## Steps to reproduce

1. `dotnet new` in the empty directory
2. execute `dotnet restore`
3. open the folder in vscode
4. add Newtonsoft.Json-9.0.1 as PackageReference in csproj
5. execute `dotnet restore`
6. add `using Newtonsoft.Json;` to top of Program.cs

## Expected  behavior

no compilation error output, only `Unnecessary using` warning.

## Actual behavior

omnisharp reports error `The type or namespace name 'Newtonsoft.Json' could not be found (are you missing a using directive or an assembly reference?) ...`

It is fixed after restarting omnisharp.

**Comment by DustinCampbell** [comment]
Thanks for the report. This is still unimplemented, though should be in the near future. It is being tracked by https://github.com/OmniSharp/omnisharp-vscode/issues/439.
