### ISSUE TITLE
Syntax highlighting trouble with Linq

### ISSUE THREAD

**Issue by aadnehovda** [OmniSharp/omnisharp-vscode#1106]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

VS Code version: 1.8.1

C# Extension version: 1.6.2

## Steps to reproduce
This is the code I'm writing (using Sprache parser combinator): 

```csharp
private static readonly Parser<Node> NodeParser =
    from name in NodeName.Token()
    from type in NodeValueType.Token()
    from eq in Parse.Char('=')
    from value in QuotedString.Token()
    from lcurl in Parse.Char('{').Token()
    from children in Parse.Ref(() => ChildrenNodesParser)
    from rcurl in Parse.Char('}').Token()
    select new Node
        {
            Name = name,
            Type = type,
            Value = value,
            Children = children
        };
```

## Expected behavior
Correct syntax highlighting in Linq queries.

## Actual behavior

The syntax highlighting breaks at `from eq in Parse.Char('=')`. 

See picture:
![image](https://cloud.githubusercontent.com/assets/1244723/21694079/d063b20c-d383-11e6-9ef6-a3aa8b9e7be3.png)

**Comment by DustinCampbell** [comment]
This will look much better in the next release:

![image](https://cloud.githubusercontent.com/assets/116161/21778212/5993958a-d657-11e6-88d5-1e589d247988.png)
