### ISSUE TITLE
Wrong color in C#

### ISSUE THREAD

**Issue by sandy081** [OmniSharp/omnisharp-vscode#1108]
From @PotterDai Ref - https://github.com/Microsoft/vscode/issues/18204

- VSCode Version: 1.8.1
- OS Version: macOS sierra

Steps to Reproduce:
1.  Define an enum.
2.  Assign enum items int value.
Color theme starts to mess up.
Please check the following screenshot:

![screenshot 2017-01-05 21 18 14](https://cloud.githubusercontent.com/assets/3758951/21705250/c80a8db6-d38c-11e6-8c61-df6085d98a15.png)

**Comment by DustinCampbell** [comment]
This should look much better in the next release:

![image](https://cloud.githubusercontent.com/assets/116161/21740244/af53ecb8-d468-11e6-95a7-a30748beda0c.png)
