### ISSUE TITLE
[Feature Request] Add feature to disable or grey-out obsolete/deprecated C# methods, attributes, etc on autocomplete

### ISSUE THREAD

**Issue by CanisLupus** [OmniSharp/omnisharp-vscode#1109]
I couldn't find a setting for this, nor find results about it on Google. It would be really helpful to avoid auto-completing obsolete stuff when using an API that has legacy methods and attributes. In VSCode, greying out things marked Obsolete (and showing them last in the autocomplete list) - or maybe even being able to disable them - would be great.

Thanks,
Daniel

**Comment by DustinCampbell** [comment]
Note: You should also make this feature request at https://github.com/dotnet/roslyn/issues. I would add this to VS Code without first adding it to Visual Studio.

cc @Pilchie

**Comment by DustinCampbell** [comment]
Closing this in favor of https://github.com/dotnet/roslyn/issues/16817. If we decide to add this Roslyn and Visual Studio, we'll consider it for C# in VS Code as well.

**Comment by CanisLupus** [comment]
Got it. Thanks for considering it!
