### ISSUE TITLE
[BUG/FEAT]Allow goto definition when inside in-memory class 

### ISSUE THREAD

**Issue by eByte23** [OmniSharp/omnisharp-vscode#1111]
When f12'ing on a Type/Object it will go to definition but if you then try to go to a type or definition from the generate metafile it does nothing.

This works in visual studio and really should work in vscode as well, I use this quite often when exploring third party libraries.

Thanks!

**Comment by DustinCampbell** [comment]
Thanks for reporting this. It's ultimately a bug since we support this behavior in Visual Studio. However, this issue is a duplicate of #771.
