### ISSUE TITLE
VSCode requires Mono even for dnxcore50 version OmniSharp

### ISSUE THREAD

**Issue by troydai** [OmniSharp/omnisharp-vscode#112]
### Repo
_Issue is found on Linux. It should apply to Unit, too_

1. Install VS Code
2. Download a dnxcore50 version OmniSharp
3. Set up `csharp.omnisharp` path
4. Start a project

```
[INFO] Starting OmniSharp at '/home/troydai/code/omnisharp-roslyn'...
[ERROR] Error: Cannot start Omnisharp because Mono version >=4.0.1 is required. See http://go.microsoft.com/fwlink/?linkID=534832#_20001
```

**Comment by DustinCampbell** [comment]
This is already fixed by PR #106. Try using C# extension from the https://github.com/OmniSharp/omnisharp-vscode/tree/dev branch.
