### ISSUE TITLE
Remote attach picker from Windows to Linux does not work properly

### ISSUE THREAD

**Issue by pieandcakes** [OmniSharp/omnisharp-vscode#1130]
in [processPicker.ts] (https://github.com/OmniSharp/omnisharp-vscode/blob/58c5b8d2b9c66ebc12a88a6598a84c8efa687e40/src/features/processPicker.ts) 

Line 151:
`let lines = output.split(os.EOL);`

when remoting from Windows to Linux, this uses Windows EOL `\r\n` when this should be the Linux EOL `\n`
 
I think this should be hard coded as `\n` since only Darwin and Linux are supported.

**Comment by WardenGnaw** [comment]
This may be an issue depending on the pipeProgram. plink seems to convert the newline characters to be \r\n. 

Solution may be to handle both,
```let lines = output.split(/\r?\n/);```
