### ISSUE TITLE
Debugger: [Unstable] Log are missing some message

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#1133]
## Environment data
`dotnet --info` output:
OS: Ubuntu.16.10-x64
VS Code version: 1.8.1
C# Extension version: 1.6.2
.NET Core version: 1.0.0-preview2 - 003177

## Steps to reproduce
1. Enable MIEngine logging ( .VSCode->project.josn )
2. Download hwapp folder in attachments directly and open with VSCode
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/715959/hwapp.zip)
3. Update launch.json as following: "logging":{ "engineLogging": true }
4. Press F5 to start debugging

## Expected  behavior
The log are include ' *stopped, reason="entry-point-hit" '
[correctlog.txt](https://github.com/OmniSharp/omnisharp-vscode/files/715997/correctlog.txt)

## Actual behavior
The log are missing ' *stopped, reason="entry-point-hit" '.
[errorlog.txt](https://github.com/OmniSharp/omnisharp-vscode/files/715979/errorlog.txt)

## Investigation
This issue doesn't appear every time. This issue reproduced frequently at first, but as the test times increase, it reproduced less, as 20~30%.

**Comment by gregg-miskelly** [comment]
This is the same issue as https://github.com/OmniSharp/omnisharp-vscode/issues/1011

**Comment by GraceDong** [comment]
Got it, thanks!
