### ISSUE TITLE
Please ignore keywords such as 'if' inside strings.

### ISSUE THREAD

**Issue by borgdylan** [OmniSharp/omnisharp-vscode#1141]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview3-003236)

Product Information:
 Version:            1.0.0-preview3-003236
 Commit SHA-1 hash:  8f00e03c43

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.10
 OS Platform: Linux
 RID:         ubuntu.16.10-x64

VS Code version: 1.9.0 insider
C# Extension version: 1.6.2

## Steps to reproduce
Put some code such as an if statement inside a string.

## Expected  behavior
I expect the string to be highlighted normally as it was in the 1.5.x versions of the extension.

## Actual behavior
The keywords get highlighted as if they were not inside a string literal.

**Comment by borgdylan** [comment]
The issue also existed in v. 1.6.1. For the last known good C# syntax file was shipped in v. 1.5.3

**Comment by DustinCampbell** [comment]
This should already be fixed with https://github.com/OmniSharp/omnisharp-vscode/pull/1115. Could you the latest beta release [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.7.0-beta1) to verify? Use these instructions to install the beta: https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases

**Comment by DustinCampbell** [comment]
And, if you don't want to take the time to install a beta release, please feel free to provide a code sample and I'll verify the highlighting.

**Comment by borgdylan** [comment]
I'll take a backup of my current extension install and verify it.

**Comment by borgdylan** [comment]
I confirm that not only is the issue fixed, but also that the highlighting looks richer and nicer than ever before! It looks on par with the TS grammar.

**Comment by DustinCampbell** [comment]
Excellent! That was definitely the goal. :smile:
