### ISSUE TITLE
Fail to work with OpenSSL-1.1.0c

### ISSUE THREAD

**Issue by charlessz** [OmniSharp/omnisharp-vscode#1142]
## Environment data
`dotnet --info` output:
Product Information:
 Version:            1.0.0-preview2-1-003177
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64

VS Code version: 1.8.1
C# Extension version: 1.6.2

## Steps to reproduce
1. Manually install OpenSSL newest version 1.1.0c
2. Create link by:
ln -s /usr/local/openssldirectory/lib/libcrypto.1.1.dylib /usr/local/lib/
ln -s /usr/local/openssldirectory/lib/libssl.1.1.dylib /usr/local/lib/
3. Create a C# project in VS Code and debug

## Expected  behavior
Debugger should work.

## Actual behavior
"[ERROR] The debugger cannot be installed. A required component, OpenSSL, is not correctly configured."
But when open C# code file in terminal, run "dotnet new", "dotnet restore", "dotnet run", it is working.

Checking code:
In https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/coreclr-debug/util.ts it tries to match exactly "/usr/local/lib/libcrypto.1.0.0.dylib" and "/usr/local/lib/libssl.1.0.0.dylib", but the newest version is libcrypto.1.1.dylib and libssl.1.1.dylib.
This could be the problem.

**Comment by gregg-miskelly** [comment]
@charlessz I believe even if you also have OpenSSL 1.1, you will still need 1.0 installed with the symlinks present for the debugger to work.

**Comment by charlessz** [comment]
OK, thanks!
