### ISSUE TITLE
Cannot determine executable for debug adapter 'C:/Users/<username>/.vscode-insiders/extensions/ms-vscode.csharp-1.6.2/.debugger/OpenDebugAD7.exe'.

### ISSUE THREAD

**Issue by wc-matteo** [OmniSharp/omnisharp-vscode#1147]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-1-003155)

Product Information:
 Version:            1.0.0-preview2-1-003155
 Commit SHA-1 hash:  d7b0190bd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

VS Code version: 1.9.0-insider

C# Extension version: 1.6.2 

## Steps to reproduce

`mkdir test && cd test`

`dotnet new`

`code-insiders`

`Required assets to build and debug are missing from 'test'. Add them?` **Yes**

`There are unresolved dependencies from 'project.json'. Please execute the restore command to continue.` **Restore**

`Start Debugging`

## Expected  behavior

The debugger starts.

## Actual behavior

**Error:**

`Cannot determine executable for debug adapter 'C:/Users/<username>/.vscode-insiders/extensions/ms-vscode.csharp-1.6.2/.debugger/OpenDebugAD7.exe'.`

**Comment by wc-matteo** [comment]
Similar issue with the c++ tools: https://github.com/Microsoft/vscode-cpptools/issues/455

**Comment by pellea** [comment]
This issue happens also on the latest 1.7.0-beta1.

**Comment by gregg-miskelly** [comment]
This sounds like a VS Code issue, but I will do some poking.

**Comment by wc-matteo** [comment]
@gregg-miskelly Should I report it there now or...?

**Comment by gregg-miskelly** [comment]
I created https://github.com/Microsoft/vscode/issues/19386
