### ISSUE TITLE
Syntax highlighting stops without ; in 1.7 beta

### ISSUE THREAD

**Issue by tverboon** [OmniSharp/omnisharp-vscode#1152]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64

VS Code version: 1.8.1
C# Extension version: 1.7.0-beta1

## Steps to reproduce

```
namespace MyTest
{
    public class ColorTest
    {
        private readonly string _color
        public ColorTest(string white)
        {
            _color = white;
        }
    }
}
```

## Expected  behavior
This behavior happens when there is a syntax error (missing ;), so this makes it absolutely clear. Maybe it's a feature 😄 Visual Studio syntax highlighting continues to work for other lines, so I guess most users will expect that to be with VS Code also.

## Actual behavior
<img width="391" alt="screen shot 2017-01-27 at 08 01 07" src="https://cloud.githubusercontent.com/assets/6871049/22363000/62ca9cde-e467-11e6-8ce2-3da88d57105c.png">

Edit: It looks like that it only happens within class block and not in a method:
<img width="341" alt="screen shot 2017-01-27 at 13 57 16" src="https://cloud.githubusercontent.com/assets/6871049/22371661/95e18318-e498-11e6-959f-e271a63de342.png">

**Comment by DustinCampbell** [comment]
This issue was moved to dotnet/csharp-tmLanguage#15

**Comment by DustinCampbell** [comment]
Thanks Tom! I've moved this over to the https://github.com/dotnet/csharp-tmLanguage repo. I'll make the fix over there.
