### ISSUE TITLE
Omnisharp support for CompactFramework

### ISSUE THREAD

**Issue by ppasieka** [OmniSharp/omnisharp-vscode#1153]
## Environment data
`dotnet --info` output:

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

Additional env data:
- VisualStudio 2008 with ServicePacks
- SDK to support WindowsMobile projects

VS Code version: 1.8.1
C# Extension version: 1.6.2

## Steps to reproduce
I have solution where two projects target CompactFramework .net3.5.  (UI for WindowsMobile and WindowsCE). When I open solution - VSCode is unable to process these two projects. Other (not CF) are fine. 

Visual Studio 2008 has no problems with compiling. Also I can successfully compile solution from CMD.exe with msbuild command 

## Expected  behavior

Process projects targeting CompactFramework and enable all goodnes

## Actual behavior

Currentlu OmpniSharp outputs:
`Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project   "C:\Users\Piotr\.vscode\extensions\ms-vscode.csharp-1.6.2\bin\omnisharp\msbuild\Microsoft.CompactFramework.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  
`

**Comment by DustinCampbell** [comment]
Support for legacy compact framework projects isn't going to be added for C# in VS Code. You should continue using Visual Studio 2008.

**Comment by ppasieka** [comment]
Only one question ... 
I just opened the same solution in Sublime with omnisharp and funny thing ... I can navigate between types using F12, I also can find usages of given class etc..... this seems to be impossible with visual studio code.

Why is that?

**Comment by DustinCampbell** [comment]
It's likely due to the fact that Sublime Text is using an older version of OmniSharp which uses the MSBuild that is installed globally. With VS 2017, MSBuild is no longer installed globally and OmniSharp must carry a copy of MSBuild with it. Getting it to work with the CompactFramework *may* just be a matter of setting some MSBuild environment variables.
