### ISSUE TITLE
Immediate / Interactive Window?

### ISSUE THREAD

**Issue by frumkinwy** [OmniSharp/omnisharp-vscode#1159]
## Environment data
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version: 1.8.1
C# Extension version: 1.1.0

## Steps to reproduce
Run C# Debugging Session, hit breakpoint

## Expected  behavior
Would love to see an interactive terminal, or "immediate window"  where we can execute code against the current stack.

## Actual behavior
Not available yet in vscode it seems.

**Comment by gregg-miskelly** [comment]
@frumkinwy you can evaluate expressions in the debug console window. Is there some missing functionality in that Window you would like to see, or did you just not know about it?

**Comment by DustinCampbell** [comment]
@frumkinwy: Did you have anything to add here?

**Comment by DustinCampbell** [comment]
I'm going ahead and closing this for now. @frumkinwy: Please let us know if you had anything more to add per @gregg-miskelly's question.

**Comment by dps999** [comment]
Hi,
what about LINQ requests? 
I always get Expression not supported.

destroyingItems.Select(i=>i.falling)
Evaluate request failed (Expression not supported.).

**Comment by gregg-miskelly** [comment]
@dps999 please open a new issue instead of commenting on a closed issue.
