### ISSUE TITLE
Set up experience on Ubuntu is bad

### ISSUE THREAD

**Issue by Tyriar** [OmniSharp/omnisharp-vscode#116]
See https://github.com/Microsoft/vscode/issues/4517 for some notes on my first setting up of OmniSharp on Ubuntu using the latest insiders build. Basically some documentation needs to be updated and any advice on how to install mono should probably be deferred to the [mono download page](http://www.mono-project.com/download/).

**Comment by DustinCampbell** [comment]
Thanks for touching base. I looked at the conversation in Microsoft/vscode#4517 and can confirm that Mono 4.01 has been a requirement for a long while. That said, we have recently removed the Mono requirement in our [dev branch](https://github.com/OmniSharp/omnisharp-vscode/tree/dev) and should have a release available soon that removes it entirely.

**Comment by DustinCampbell** [comment]
This should be working properly with the latest release here: https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.0.0-rc2

**Comment by Tyriar** [comment]
@DustinCampbell does the error message still point to the [vscode docs](https://code.visualstudio.com/docs/supporting/errors#_20001)?

**Comment by DustinCampbell** [comment]
Well, there shouldn't be an error message any longer.
