### ISSUE TITLE
Operation not permitted when running bash script from task

### ISSUE THREAD

**Issue by egamma** [OmniSharp/omnisharp-vscode#1162]
_From @spboyer on January 30, 2017 16:49_

VSCode Version: Version 1.8.1
OS Version: macOS Sierra 10.12.2 (16C67)

Steps to Reproduce:

1. clone repo https://github.com/spboyer/dockerdebugapp
2. open debug pane and run 
3. Console outputs: "/bin/bash: ./dockerTask.sh: Operation not permitted"

Can run bash script from terminal with no problems without sudo.

_Copied from original issue: Microsoft/vscode#19586_

**Comment by spboyer** [comment]
Steps

1.       Clone repo
2.       Deleted bin and obj
3.       `dotnet restore -r debian.8-x64`
4.       Open project in vscode
5.       Set breakpoint in Program.cs
6.       Open debug pan - click "play"
7.       Console outputs: "/bin/bash: ./dockerTask.sh: Operation not permitted"

Get error on one machine but not another, same version of VS Code and OS and C# extension.

**Comment by gregg-miskelly** [comment]
This issue seems to be in the wrong repo. This should be in the repo of 'dockerTask.sh' I would assume.

**Comment by gregg-miskelly** [comment]
This issue was moved to Microsoft/generator-docker#131

**Comment by spboyer** [comment]
@gregg-miskelly please re-open

**Comment by gregg-miskelly** [comment]
I am not at all sure that this is actually a problem with the C# extension. But I can reopen for now.

**Comment by DustinCampbell** [comment]
@spboyer, could you explain why this would be an issue with the C# extension?

**Comment by spboyer** [comment]
@DustinCampbell - I can't, to be honest I believe that its an integrated shell issue. @egamma moved it here from vscode.  

The following works in terminal OUTSIDE of shell, same error happens on integrated shell (see screenshot)
cd <project-root>
/bin/bash -c "./dockerTask.sh startDebugging"

I'm ok closing this considering the above. It does not belong in the yo docker repo. I believe that it should go to vscode IMO. 

cc:/ @egamma @chrisdias

**Comment by DustinCampbell** [comment]
Got it, thanks! @egamma, @chrisdias, we don't think this is likely a C# extension issue. Could you take a look?

**Comment by egamma** [comment]
@DustinCampbell sorry for the wrong move. First assessment was that the message is from C# debugger adapter and not from VS Code. 

@spboyer since you suspect it has to do with the integrated terminal. Can you change the launch configuration so that it uses an external console, To do so set `externalConsole` to `true` (see below).

    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}\\bin\\Debug\\netcoreapp1.1\\hwapp.dll",
            "args": [],
            "cwd": "${workspaceRoot}",
            "externalConsole": false,   <======= true
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart"
        },

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode#19664
