### ISSUE TITLE
Syntax highlight issues with unity

### ISSUE THREAD

**Issue by cemuka** [OmniSharp/omnisharp-vscode#1164]
Working with unity quite cool but it doesn't behave like monodevelop for syntax highlighting for me. Is there any progress or can anybody explain how I can achive that?

**Comment by DustinCampbell** [comment]
Hi @cemuka!

Syntax highlighting is achieved in VS Code with TextMate grammars using regular expressions. So, the syntax highlighting won't be as high quality as what you might see in MonoDevelop or Visual Studio. That said, we have _just_ created a new TextMate grammar that likely fixes most of the issues you might be running into. Could you try the latest beta version of C# for Visual Studio from [here](https://github.com/OmniSharp/omnisharp-vscode/releases)? Be sure to following our instructions for [installing beta releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases).

**Comment by DustinCampbell** [comment]
I'm going to go ahead and close this issue. Let us know if you find any syntax highlighting issues with the latest beta release.

**Comment by cemuka** [comment]
Hi @DustinCampbell !,

I've tried and working well! Tried some other themes too and result positive.

Thank you.

**Comment by DustinCampbell** [comment]
Glad to hear it! Thanks!
