### ISSUE TITLE
Mac+Unity=Couldn't locate mono 

### ISSUE THREAD

**Issue by guoboism** [OmniSharp/omnisharp-vscode#1166]
## Environment data
`dotnet --info` output:
[INFORMATION:OmniSharp#MSBuild] Loading project from '/Users/name/Desktop/Project17/Assembly-CSharp-Editor.csproj'.
[WARNING:OmniSharp#ProjectFileInfo] Couldn't locate Mono, TargetFrameworkRootPath not specified
[ERROR:OmniSharp#ProjectFileInfo] The reference assemblies for framework ".NETFramework,Version=v2.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[WARNING:OmniSharp#MSBuild] Failed to process project file '/Users/name/Desktop/Project17/Assembly-CSharp-Editor.csproj'.
/Users/name/Desktop/Project17/Assembly-CSharp-Editor.csproj

VS Code version:1.81
C# Extension version:1.62
Unity:5.5

## Steps to reproduce
Install unity
Install vscode and unity related plugins

## Expected  behavior
provide auto-completion for Unity classes

## Actual behavior
No auto-completion for Unity classes
Output complains about can not locate mono

Yet, I do have a mono 3.2.7 at Library/Frameworks/Mono.framework

I have added the path to $PATH
echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/:/Library/Frameworks/Mono.framework:/Library/Frameworks/Mono.framework/Versions/Current

If I call mono from terminal(anywhere):
-bash: /Library/Frameworks/Mono.framework/mono: cannot execute binary file

This should mean mono is included in the path?

What should I do now? How to find the mono?

**Comment by DustinCampbell** [comment]
It does look like mono is found on your path. Have you tried upgrading Mono to the latest? The latest stable release is 4.6.2.

**Comment by DustinCampbell** [comment]
Also, are you using bash as your shell, or something else?

**Comment by guoboism** [comment]
@DustinCampbell Thanks for your concern.
I just got it solved by:

install .net core
install (another) mono[4.6] with brew

I guess the latter does the fix

**Comment by DustinCampbell** [comment]
Glad to hear you got it working. Thanks for the update!
