### ISSUE TITLE
Add a setting to disable code lens

### ISSUE THREAD

**Issue by filipw** [OmniSharp/omnisharp-vscode#1168]
This is a feature request.

### Description

As a user I would like to disable the code lens feature (reference count, run tests). 
Ideally the feature would be hidden in the UI + the unnecessary requests to OmniSharp would not be happening under the hood.

### Impact on existing users

None. Feature would be entirely opt-in via settings.

**Comment by geirsagberg** [comment]
Already exists:

```
 // Controls if the editor shows code lenses
  "editor.codeLens": true,
```

**Comment by DustinCampbell** [comment]
As @geirsagberg, this already exists as a setting in VS Code, so it can be set globally or for the current workspace.

**Comment by filipw** [comment]
Ah great - did not know that 👍
