### ISSUE TITLE
No syntax highlighting in new expressions.

### ISSUE THREAD

**Issue by cateyes99** [OmniSharp/omnisharp-vscode#1172]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-preview4-004233

VS Code version:
C# Extension version: 1.6.2

## Steps to reproduce
Write statements like: new ClassA();

## Expected  behavior
"ClassA" should be recognised and display with syntax highlighting, just like what's in Visual Studio.

## Actual behavior
No syntax highlighting for "ClassA" in the new statement.

**Comment by DustinCampbell** [comment]
Hi @cateyes99:

I recommend you try out the [latest beta](https://github.com/OmniSharp/omnisharp-vscode/releases) of C# for Visual Studio Code. (Be sure to follow our instructions for [Installing Beta Releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases).) We've completely rewritten the TextMate grammar used for syntax highlighting from the ground up, and you should see much improved highlighting, and yes, 'new' expressions are definitely much better.

Let me know if the new TextMate grammar in the latest beta does not work better for you.

Also, note that _semantic_ highlighting of identifiers (e.g. highlighting class names differently from other identifiers) is not available today. We're tracking https://github.com/Microsoft/vscode/issues/585 for an API that would allow us to add this feature in the future.

**Comment by cateyes99** [comment]
thanks, now it works in v1.7.0, sweet 👍
