### ISSUE TITLE
Add option to to address all "Unnecessary using directive"

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-vscode#1179]
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4-004706)

Product Information:
 Version:            1.0.0-rc4-004706
 Commit SHA-1 hash:  e38bc4950c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004706


```
VS Code version: 1.9.0
C# Extension version: 1.7.0-beta3

## Steps to reproduce
Open a project, open the Problems pane. Get numerous information points about `Unnecessary using directive`.  

## Expected  behavior
Could there be an option to globally address all these where it loops through those lines and removes the unnecessary usings?

## Actual behavior
Nothing, just information/warnings

**Comment by DustinCampbell** [comment]
I don't think we'll add a specific command for this. In VS Code, we'll to have the ability to provide "Fix All in {scope}" like we have in Visual Studio:

![image](https://cloud.githubusercontent.com/assets/116161/22607335/482dd710-ea0c-11e6-871d-908603064023.png)

Now, eventually we might just have a general "clean up" command, but that's definitely different than a specific command only for remove unnecessary usings.

**Comment by jchannon** [comment]
A general clean up command would be good ala Resharper

**Comment by steve-lillis-cko** [comment]
@DustinCampbell Before I go ahead and raise a separate issue for this, can you confirm if unnecessary usings should be highlighted in some way?  If not, is there a specific motivation as to why?  Currently I'm having to select each using until I find one that isn't needed so I can use "Remove Unnecessary Usings" to clear them all

**Comment by DustinCampbell** [comment]
@steve-lillis-cko: Follow the discussion on https://github.com/OmniSharp/omnisharp-vscode/issues/1429 for the details. We've added an option in the latest beta of C# for Visual Studio to make hidden diagnostics appear in the editor and Problems tab.

**Comment by kleber-swf** [comment]
A command for a remove usings would be nice for cases like that:

![image](https://user-images.githubusercontent.com/871682/34265636-9e139cc0-e65d-11e7-9c9a-86c911b6d2e7.png)

**Comment by jools-adams** [comment]
It would be great to have unnecessary using's to be highlighted (or greyed out, as per VS for Mac) in VS Code.

**Comment by DustinCampbell** [comment]
@jools-adams: Agreed. I'm tracking https://github.com/Microsoft/vscode/issues/20219 to get API support for VS Code so we can do exactly that.

**Comment by andrewb273** [comment]
@DustinCampbell did a separate issue get created for including removal of unused usings in a general cleanup command? As it stands, I need to jump back to VS2017 to efficiently clean up usings.

**Comment by rszemplinski** [comment]
Would love to see this feature added to VSCode.

**Comment by larryPlayabl** [comment]
Would love to see this added!

**Comment by andrewb273** [comment]
I've become quite accustomed to `ctr+r,g` for C# in VS2017, and using `shift+alt+o`/`f10` for TS in vscode. Is it an option for the omnisharp extension to provide an implementation of `editor.action.organiseImports` for C#? Seems to be logical & consistent to me, and the fastest way for me to keep my code clean.

**Comment by jools-adams** [comment]
For bonus marks make it possible to use full alphabetical order, or put
system stuff separately.

**Comment by CrossBound** [comment]
Any update on this? I would really love to have this available... It is so nice in VS to be able to run a keystroke and it remove & sort my usings.

I would say removing is more important than sorting to me but having both is having the cake and eating it too.
