### ISSUE TITLE
Unable to open file from error/warnings window

### ISSUE THREAD

**Issue by salerth** [OmniSharp/omnisharp-vscode#118]
Everything about the plugin works well, however I can't navigate to errors/warnings from the error/warning popup.   Seems the file path has a repeating section which is invalid `src/Kraken.Hosting/src/Kraken.Hosting`

![image](https://cloud.githubusercontent.com/assets/768512/13955623/5c60e0b8-f013-11e5-967d-cfcdfd5bb5d2.png)

Running plugin v0.3.7 on 0.10.12-insiders on OSX.

**Comment by DustinCampbell** [comment]
Are you still experiencing this problem with the latest release (1.5.2)?

**Comment by salerth** [comment]
No, works fine now... forgot I posted this error, sorry!

**Comment by DustinCampbell** [comment]
Thanks for checking!
