### ISSUE TITLE
Preprocessor scopes in middle of inheritance list lack meta.preprocessor.cs scope

### ISSUE THREAD

**Issue by Tyriar** [OmniSharp/omnisharp-vscode#1182]
## Environment data
`dotnet --info` output: N/A
VS Code version: 1.10.0-insiders
C# Extension version: 1.6.2

## Steps to reproduce

Inspect the scopes of the following snippet:

```
#if !PCL
    [Serializable]
#endif
    public struct Interval : IEquatable<Interval>, IXmlSerializable
#if !PCL
        , ISerializable
#endif
```

## Expected  behavior

The `#if` and `#endif` should have scopes something like:

```
meta.preprocessor.cs
storage.type.cs
meta.class.cs
source.cs
```

![image](https://cloud.githubusercontent.com/assets/2193314/22624298/48566a4c-eb2c-11e6-87b6-70a7633be920.png)

With the if condition `!PCL` having an extra type scope like so:

```
storage.type.cs
meta.preprocessor.cs
storage.type.cs
meta.class.cs
source.cs
```

This will allow themes to handle this case.

## Actual behavior

![image](https://cloud.githubusercontent.com/assets/2193314/22624288/fded32ce-eb2b-11e6-9404-8cc32afb7821.png)

**Comment by DustinCampbell** [comment]
This issue was moved to dotnet/csharp-tmLanguage#32

**Comment by DustinCampbell** [comment]
Moved this to the csharp-tmLanguage repo.
