### ISSUE TITLE
Debugger should show unescaped strings

### ISSUE THREAD

**Issue by KallDrexx** [OmniSharp/omnisharp-vscode#1188]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64

VS Code version: 1.9.0
C# Extension version: 1.6.2

## Steps to reproduce

1. Create a new .net core project with `dotnet new`
2. Specify the following main function:
```
        public static void Main(string[] args)
        {
            var test = @"{""Test"": 123}";
            Console.WriteLine(test);
        }
```
3) Put a break point on the last ending brace of the function
4) Debug

## Expected  behavior

It should show the unescaped value of `{"Test": 123}`. (unescaped)

## Actual behavior

Observe the variables and watch window shows the value of the string as `"{\"Test\": 123}"` 

This is important because I"m in the process of writing an application to read and write structured (json) logs and trying to verify some things with the debugger, and it's adding extra steps to verifying the json being output (since I have to manually unescape it in order to pretty print it for verification)

Was told this was an Omnisharp-vscode plugin issue in https://github.com/Microsoft/vscode/issues/20048

**Comment by gregg-miskelly** [comment]
@KallDrexx the C# expression evaluator is working as it was designed here -- the evaluator tries to show valid C#. However, you can use the `,nq` format specifier if you don't want C#. See https://msdn.microsoft.com/en-us/library/e514eeby.aspx for more information.

**Comment by KallDrexx** [comment]
Neat, never knew about that thanks.
