### ISSUE TITLE
not able to see input

### ISSUE THREAD

**Issue by AbhimanyuAryan** [OmniSharp/omnisharp-vscode#1193]
So, I am practicing competitive coding in VS Code. But whenever i type input in close I don't see inputs being typed when I hit enter then I see entire result 

Also I am using watcher so that I don't have to compile/debug(which takes time)....I using cmd+S to compile the code by watcher 

Please fix this input not showing problem? 

Also watcher waits for file to be changed. How can I configure watcher to trigger automatically when I types some new inputs. Say if I want to test more 

<img width="1115" alt="screen shot 2017-02-07 at 2 15 43 pm" src="https://cloud.githubusercontent.com/assets/8083613/22683977/60489ed4-ed40-11e6-8721-31bd7e22b258.png">

**Comment by DustinCampbell** [comment]
Hi, could you provide more information per the issue template? This template should have appeared when you create the issue, and the information there is very important for us to help you:

## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:
Operating system and version:

## Steps to reproduce


## Expected  behavior


## Actual behavior

**Comment by AbhimanyuAryan** [comment]
```
dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
```

VSCODE version: Version 1.9.0 (1.9.0)

C# extension version: latest up to date

**Comment by DustinCampbell** [comment]
I'm guessing that you have 1.6.2 of the C# extension installed, correct? Please note that there are also betas of 1.7 available on this GitHub repo, so it's not clear what "latest up to date" means.

**Comment by DustinCampbell** [comment]
> Please fix this input not showing problem?

I'm not sure I understand what "input" you're referring to? Are you expecting something to appear in the terminal window? Please try to be a bit more clear about what you're expecting to see.

> Also watcher waits for file to be changed. How can I configure watcher to trigger automatically when I types some new inputs. Say if I want to test more

This repo is for C# in VS Code. We don't have much expertise on the DotNetWatcher and probably aren't the right people to ask about that. Is that using `dotnet watch`?

**Comment by AbhimanyuAryan** [comment]
yes it using `dotnet watch` so I'll ask in `dotnet watch` group thanks 

Ok I re-install VS Code & seems to work now
