### ISSUE TITLE
VS code doesn't take me to the definition

### ISSUE THREAD

**Issue by AbhimanyuAryan** [OmniSharp/omnisharp-vscode#1194]
Hi, I am using a asp dotnet core mvc project & I wish to see some inbuilt classes of dotnet core but when I click on class for ex "Entity Framework"/ "Console" & click on "Go to Definition" VS Code doesn't take me anywhere

**Comment by DustinCampbell** [comment]
Hi, could you provide more information per the issue template? This template should have appeared when you create the issue, and the information there is very important for us to help you:

## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:
Operating system and version:

## Steps to reproduce


## Expected  behavior


## Actual behavior

**Comment by AbhimanyuAryan** [comment]
```
dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
```

**Comment by DustinCampbell** [comment]
Could you let me know what VS Code version and C# extension version you're using? Also, if you have a repro project and repro steps I could try, that'd be helpful.

**Comment by AbhimanyuAryan** [comment]
I want it to so to definitions of inbuilt classes.

**Comment by DustinCampbell** [comment]
Yup. I understand what you're looking for, and we definitely support "Go to Definition" for types and members declared in referenced metadata. So, it sounds like this feature isn't working properly for you and I'd like more information to understand why.

**Comment by AbhimanyuAryan** [comment]
fixed re-install VS code. Something was wrong with the app

**Comment by DustinCampbell** [comment]
Cool -- I'm glad to hear that worked for you.
