### ISSUE TITLE
Remote attach doesn't show the command line arguments in the process listing

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#1208]
## Environment data
C# Extension version: 1.7.0-beta5

## Steps to reproduce
- Follow steps on https://github.com/OmniSharp/omnisharp-vscode/wiki/Attaching-to-remote-processes to setup SSH remote. I am remoting from MacOS to Ubuntu 14.
- Bring up the attach to process dialog

## Expected  behavior
Command line arguments should show up

## Actual behavior
Command line arguments are dropped

**Comment by gregg-miskelly** [comment]
This looks to be broken by the zsh fix (commit 84b3a3b204940acf077acf0bf82a26f202101922).

**Comment by DustinCampbell** [comment]
Resolve fixed?
