### ISSUE TITLE
Intellisense appears after typing an open or close brace and autoselects "Action"

### ISSUE THREAD

**Issue by agocke** [OmniSharp/omnisharp-vscode#121]
![image](https://cloud.githubusercontent.com/assets/515774/14004584/697e3416-f118-11e5-82c1-3402ff3865e4.png)

This causes subsequent `return` presses on the keyboard to insert the text "Action" instead of moving to a new line.

**Comment by DustinCampbell** [comment]
@agocke, are you still seeing this problem? I've been unable to reproduce it.

**Comment by agocke** [comment]
@DustinCampbell I think this was a bad interaction between extensions. I'll try and repro and re-open if I find anything.

**Comment by DustinCampbell** [comment]
thanks! No rush here. The idea that two extensions were interacting badly sounds like a good theory to me.
