### ISSUE TITLE
Debugger: The "stopAtEntry" property  has no effect

### ISSUE THREAD

**Issue by ClaireKang** [OmniSharp/omnisharp-vscode#1216]
## Environment data
`dotnet --info` output:
VS Code version: 1.9.1
C# Extension version: 1.7.0
OS: Windows 10 Enterprise Insider Preview
Build: 15032.1000.AMD64FRE.RS_ONECORE_BASE_BPT1.170207-1700_CLIENT_ENTERPRISE_EN-US_VL.VHDX
Scenarios: WSL Pipe

## Steps to reproduce
1. Open attached folder 
[app1.zip](https://github.com/OmniSharp/omnisharp-vscode/files/766085/app1.zip)

2. Change the configurations in launch.json (Pipe launch)
    "stopAtEntry": true,
3. Copy the code from Windows with the command "cp /mnt/c/temp/app1/Program.cs ." in "Bash on Ubuntu on Windows" window.
4. dotnet build.
5. Select 'Pipe launch'.
6. F5 to start debugging.

## Expected  behavior
Break at the first line of main.(int a=1).

## Actual behavior
There is any line being hit while debugging.

##Investigation
1. Change the configurations in launch.json (Pipe launch)
    "externalConsole": true,
There is not occur the Console window.
2. Expressions can output on debug console window.
3. Could you please help me to confirm #1 is expected?

**Comment by rajkumar42** [comment]
This is probably https://github.com/dotnet/coreclr/issues/8606, I'm closing this issue.

"externalConsole" for remote pipe, will not open up a new console.
