### ISSUE TITLE
Debugger: when start to debugging with  message "Failed to initialize CoreCLR, HRESULT: 0x80004005 "

### ISSUE THREAD

**Issue by qian6** [OmniSharp/omnisharp-vscode#1217]
## Environment data
`dotnet --info` output:
VS Code version: 1.9.1
C# Extension version: v1.7.0
.NET Core version: 1.0.0-preview2 -1 - 003177
OS: Windows 10 Enterprise Insider Preview
Build: 15032.1000.AMD64FRE.RS_ONECORE_BASE_BPT1.170207-1700_CLIENT_ENTERPRISE_EN-US_VL.VHDX
Scenarios: WSL Pipe

## Steps to reproduce
1. Open app2 folder in vscode.
[app2.zip](https://github.com/OmniSharp/omnisharp-vscode/files/766167/app2.zip)
2. Modify configurations in launch.json file and add a pipe launch
                 "name": "Pipe launch",
                 "pipeTransport": {
                "pipeCwd": "${workspaceRoot}",
                "pipeProgram": "bash.exe",
                "pipeArgs": [ "-c" ],
                "debuggerPath": "~/temp/latest/clrdbg
            },
            "program": "/home/qian/temp/app2/bin/Debug/netcoreapp1.1/app2.dll",
            "cwd": "/home/qian/temp/app2",
            "sourceFileMap": {
                           "/home/qian/temp/app2/Views": "${workspaceRoot}/Views"
            }
3. Set a breakpoint at line of  21 line in Program.cs .
4. Select 'Pipe launch'.
5. Press F5 to start  debugging.

## Expected  behavior
It can hit breakpoint.

## Actual behavior
It input an error message as follow:
![capture](https://cloud.githubusercontent.com/assets/20922638/22819480/37e1fe94-efad-11e6-9e2d-b0730761d43e.PNG)

## Investigation
1. open "Bash on Ubuntu on Windows" and use "dotnet run " to run this app2 ,it has also the same as error message.
2. when I create web project in local ubuntu16.04, it is normal.

**Comment by rajkumar42** [comment]
@qian6, I cannot reproduce this. I guess your dotnet on WSL and windows maybe different and hence causing issues. 

- Uninstall other dotnet versions just to be sure.
- Please try installing 1.0.0-preview2-1-003177 on Windows and WSL. 
- On Windows "dotnet new -t web".  dotnet restore and dotnet build.
- Copy the same source to WSL. dotnet restore and dotnet build.
- Add Pipe Launch.
- Debug. 

Please reactivate the issue if you still cannot make it work with above instructions.
