### ISSUE TITLE
Please convert stacktrace string into vscode format of document link

### ISSUE THREAD

**Issue by Thaina** [OmniSharp/omnisharp-vscode#1223]
Currently now omnisharp would log stacktrace as 

`at Program.Main(String[] args) in c:\Users\Thaina\Documents\Projects\TT\Program.cs:line 44`

While vscode prefer this format

`at Program.Main(String[] args) in c:\Users\Thaina\Documents\Projects\TT\Program.cs:44:0` (column number)

I was just `e.StackTrace.Replace("line ","") + ":0"` and it just work

**Comment by DustinCampbell** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#767

**Comment by DustinCampbell** [comment]
I think you meant this for omnisharp-roslyn rather than omnisharp-vscode. At least, the change you suggest would need to go into omnisharp-roslyn.

**Comment by Thaina** [comment]
I don't think so

I'm not sure is all editor accept that format. I think it only vscode. So omnisharp-vscode should just capture debug log and convert it

**Comment by DustinCampbell** [comment]
Sorry, maybe I misunderstood what you meant? You said that this is the OmniSharp log text. Is that what you meant? Did you instead mean the exception stack trace as printed by the debugger? (That's not the OmniSharp log at all, which is why I was confused if that is indeed what you meant.)

**Comment by Thaina** [comment]
>Did you instead mean the exception stack trace as printed by the debugger?

Yes I mean that

It is the format from Exception.ToString itself. So I think what we could do is proxy the debug log output line by line in omnisharp-vscode and detect that, if that line has url with line number, it will `replace(":line ",":")` before output

**Comment by DustinCampbell** [comment]
OK. I'll re-open this and mark it for the debugger folks to make a call here.

**Comment by DustinCampbell** [comment]
cc @gregg-miskelly

**Comment by Thaina** [comment]
@DustinCampbell By the way, I don't know if this format `url:line:column` is standard in all editor, is it not?

If all of editor that omnisharp covered would like this format maybe we should still place it in `omnisharp-roslyn` ?

**Comment by DustinCampbell** [comment]
No, I don't know.

**Comment by gregg-miskelly** [comment]
@Thaina Unless there is something I am missing I don't think there is anything the debugger can do here. This request seems like it would be better either in the http://github.com/dotnet/corefx to have the default stack trace include a column number (because that would be useful anyway) or over at http://github.com/Microsoft/vscode to have VS Code support the format emitted by Exception.StackTrace.

**Comment by Thaina** [comment]
@gregg-miskelly That's not the point. We don't need column number. It just automate document link in vscode need at least `:0` as column number to be parsed

As I said I think opposite way, roslyn just output stacktrace as `url:line XX`. So omnisharp-vscode should just proxy output from the program being debugged, detect that it has file url (regex match `at someFunc in url:line XX`) and replace it with `url:XX:0`

**Comment by DustinCampbell** [comment]
@Thania: Roslyn didn't output any stack trace. My understanding is that this is the stack trace you see when you debug your own program in VS Code and hit an exception, correct? In that case, this comes from the debugger, which is just calling into System.Exception.ToString(), which is part of the .NET Framework. (If not, could you provide some repro steps?)

**Comment by Thaina** [comment]
@DustinCampbell I think you are right, sorry

Still that's the same. I really don't know where the output came from but I think it was somewhere in the core of C#. But to go to that place and change it format just for match up with vscode does not feel right

I think it is the responsibility of extension to translate console line output from debugger to match with each IDE isn't it?

**Comment by DustinCampbell** [comment]
> I think it is the responsibility of extension to translate console line output from debugger to match with each IDE isn't it?

No, the extension itself actually isn't involved in the communication between the debugger and VS Code. The extension ensures that the debugger is set up and registered, and handles some other details of launching (such as allowing the user to pick a process for debugger-attach scenarios). However, the debugger itself is a separate component that interacts with VS Code other a [different protocol](http://code.visualstudio.com/docs/extensionAPI/api-debugging). Note that the debugger is not part of OmniSharp or Roslyn.

**Comment by Thaina** [comment]
@DustinCampbell Thanks for your clarification

So this mean C# debugger in vscode does not regulate by roslyn?

Sorry for misunderstanding. I just think debugger is also a part of roslyn so omnisharp would need to be translator of it too

**Comment by DustinCampbell** [comment]
Correct, the C# debugger is not part of OmniSharp or Roslyn. It is downloaded by C# for Visual Studio (i.e. the VS Code extension that is produced from the 'omnisharp-vscode' extension) which is developed in the open by Microsoft.

The debugger *could* do so something (and @gregg-miskelly is the representative owner of the debugger here), but I suspect the best place for a solution is in VS Code itself. I think it'd be great if VS Code supported the `uri:line number` format. After all, it allows configurable "problem matchers" for output of tasks in VS Code. This seems similar to that.

**Comment by Thaina** [comment]
@DustinCampbell @gregg-miskelly Thank you very much
But please let me ask a little more questions

Where does .net core debugger hosted? Is it open source?
and
Does .net debugger also have middleman for vscode. Or it just universal debugger for any IDE?

**Comment by gregg-miskelly** [comment]
@Thaina the debugger itself isn't open source, but we use this repo for issue tracking. We use this same debugger in VS, VS Code, and VS for Mac.

But as I said, I think the right way to deal with this issue is in VS Code. The debugger doesn't really know that it is outputting a stack trace -- the target program just decides to write out text that the debugger displays for you. Having the debugger intercept that and rewrite it seems wrong to me. It seems far better to have VS Code support the same format as .NET stack traces (and more) for navigation.

**Comment by Thaina** [comment]
@gregg-miskelly Well, right I agree with you that if debugger is used many places then it should not specifically output just for one IDE

But on the other hand I think universal IDE like vscode should not support specific debugger too

Which is why I ask that, does the debugger has a middleman for translation debug log or anything like that?

Should we have wrapper for debugger and let omnisharp-vscode download it along with debugger itself?

But if the format `url:line XX` also used in debugger of other languages too I would totally agree with you

**Comment by gregg-miskelly** [comment]
@Thaina The debugger isn't creating these strings, so I don't think it makes any sense for the debugger to try and re-write them. I opened https://github.com/Microsoft/vscode/issues/20556 to track the issue.
