### ISSUE TITLE
Problems list dominated by unused usings

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-vscode#1231]
_From @davidfowl on February 12, 2017 18:13_

Makes it hard to see real problems. Can we downgrade this thing so it doesn't show up by default in the list of problems?

![image](https://cloud.githubusercontent.com/assets/95136/22864750/c453da50-f10b-11e6-8289-9312e135b828.png)

_Copied from original issue: OmniSharp/omnisharp-roslyn#769_

**Comment by DustinCampbell** [comment]
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/315 but I'm going to keep it on the backlog.

Sadly, there is no way to downgrade a diagnostic such that it's completely hidden in the Problems window today. We could make it a "hint", but that only hides the squiggle in the editor and leaves it in the Problems window, which isn't what we want.

I have https://github.com/Microsoft/vscode/issues/20219 open to get an API that'll allow us to have a better more VS-like experience here.

**Comment by davidfowl** [comment]
Maybe we can just remove them as problems for now in general? It's just noise at this point. When we get the new API then we can improve the experience all up.

**Comment by DustinCampbell** [comment]
Maybe, I'm not super-keen on the user experience of having no presentation in the editor at all for this remove unnecessary usings. That said, maybe you're right and it's worth it to hide for now and bring back in it's full glory later. :smile:

I'll take a look for 1.8.

**Comment by davidfowl** [comment]
Keep the code fix but remove the info 😄

**Comment by skryshi** [comment]
I was so looking forward to this in 1.8... (

**Comment by DustinCampbell** [comment]
Sorry about this. I had to slip this one to get 1.8 out for some important debugger changes. Fixing this is on my list after restoring test support for csproj .NET Core projects.
