### ISSUE TITLE
VSCode debugger not available for Fedora 25

### ISSUE THREAD

**Issue by cruz82** [OmniSharp/omnisharp-vscode#1242]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     fedora
 OS Version:  25
 OS Platform: Linux
 RID:         fedora.23-x64
 Base Path:   /opt/dotnet/sdk/1.0.0-rc4-004771

VS Code version: 1.9.1
C# Extension version: 1.7.0

## Steps to reproduce
Install extension on Fedora 25.

## Expected  behavior
Debugger is downloaded.

## Actual behavior
[WARNING]: The current Linux distribution 'fedora' version '25' is not currently supported by the .NET Core debugger. Debugging will not be available.

**Comment by cruz82** [comment]
I know that Fedora 25 is not officially supported but the download links for the Fedora 24 version would be helpful as I know that works on Fedora 25 as well.
I used to copy the .debugger folder every time I upgraded the extension but after an upgrade to 1.7.0, the previous versions of the plugin were deleted along with the debugger.

**Comment by gregg-miskelly** [comment]
You can find the links in https://github.com/OmniSharp/omnisharp-vscode/blob/master/package.json#L212 if you want to try hacking it up. You can also try tweaking [this line](https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/platform.ts#L314) to treat Fedora 25 as Fedora 24. If that works, we are happy to take a PR. Make sure to try expression evaluation in at least some basic way.

**Comment by cruz82** [comment]
The process of getting the debugger running in Fedora 25 is a little bit more involved so I won't submit a PR.

The steps are as follows for anyone that is interested:

- Get the source for https://github.com/dotnet/coreclr
- Compile coreclr on your machine
- Download the debugger from the link provided by @gregg-miskelly.
- Place the debugger in a folder .debugger/ under ~/.vscode/extensions/ms-vscode.csharp
- Replace the System.Globalization.Native.so from the coreclr build output.

This should give you a working debugger in Fedora 25.

Thanks for your help @gregg-miskelly.

**Comment by gregg-miskelly** [comment]
@cruz82 Thanks! Hopefully the .NET Core team will have official builds sooner rather than later so we have an official story.
