### ISSUE TITLE
Problems due to MSBuild 15.0 syntax

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-vscode#1248]
_From @aggieben on February 16, 2017 23:35_

I mentioned this offhand in #301, but in the interest of not hijacking that issue, I've opened a new one.

My original comment:

> In my case, OmniSharp is still a little behind with respect to the new RC4 tooling, so I see issues listed in the Problems tab; they are intellisense issues in csproj files relating to missing syntax that would be expected in MSBuild 12.0, but not in the lastest build tools.

A response from @DustinCampbell:

> The latest version of omnisharp-roslyn is up-to-date with VS 2017 RC4 tooling. It even includes a build of MSBuild 15.0 inside of it.

By "latest version", do you mean latest release, or something nightly?  Here's what I see:

![image](https://cloud.githubusercontent.com/assets/1321/23046176/accb7d92-f46d-11e6-8381-afc19cd18101.png)

![image](https://cloud.githubusercontent.com/assets/1321/23046188/c6e2fae8-f46d-11e6-81e5-178d0cb15a8b.png)

![image](https://cloud.githubusercontent.com/assets/1321/23046192/cb6e3636-f46d-11e6-895b-641f183a305d.png)

_Copied from original issue: OmniSharp/omnisharp-roslyn#778_

**Comment by DustinCampbell** [comment]
_From @willl on February 16, 2017 23:42_

@aggieben What @DustinCampbell meant was the version of the [omnisharp-vscode](https://github.com/OmniSharp/omnisharp-vscode) extension, and not VS Code itself.

Current version if installed from the marketplace is 1.7. If you look at the [releases page](https://github.com/OmniSharp/omnisharp-vscode/releases) there is a v1.8.0-beta1.

**Comment by DustinCampbell** [comment]
_From @aggieben on February 16, 2017 23:59_

Sorry - I goofed on reporting my versions.  I have the 1.7.0 version of the extension through the marketplace.  

Are you implying that 1.7 doesn't have support for MSBuild 15.0 and 1.8.0-beta-1 does?

**Comment by DustinCampbell** [comment]
When I said "the latest version", I meant the latest version of C# for VS Code that shipped on the extension marketplace last week. That's version 1.7, which should be able to handle a project file like the one you screencapped above just fine (I just checked). I suspect something is set up wrong on your machine. Could you check the following points about your set up?

1. Check to ensure that you don't have multiple versions of C# for VS Code installed. To do this, check the following folder:
    * On Windows, `%USERPROFILE%\.vscode\extensions`
    * On OSX/Linux, `~/.vscode/extensions`

    In that folder, there should be *one* `ms-vscode.csharp-*`. If there's more than one, close VS Code, and delete all of `ms-vscode.csharp.*` folders.. That, install 1.7 of C# for VS Code from inside VS Code.

2. In VS Code, select Preferences->Settings from the main menu. This will open the "settings.json" file. If you have set "omnisharp.path" and/or "omnisharp.usesMono", please remove those settings.

**Comment by DustinCampbell** [comment]
Additionally, if neither of those ideas yields any fruit, could you provide your OmniSharp log when loading that project? Just select View->Output from the VS Code menu and select "OmniSharp Log" from the top-right of the Output pane.

**Comment by aggieben** [comment]
It looks to me like I only have one installation of the extension:
```
D:\Users\ben
λ ls D:\Users\ben\.vscode\extensions\ms-*


    Directory: D:\Users\ben\.vscode\extensions


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2/10/2017  11:43 AM                ms-vscode.cpptools-0.10.1
d-----        2/10/2017  11:44 AM                ms-vscode.csharp-1.7.0
d-----         2/8/2017   5:15 PM                ms-vscode.PowerShell-0.9.0
```

Here are my user settings:
```
// Place your settings in this file to overwrite the default settings
{
    "editor.fontSize": 12,
    "editor.fontFamily": "Hasklig, 'Courier New', monospace",
    "extensions.autoUpdate": true,
    "rewrap.wrappingColumn": 125,
    "git.confirmSync": false,
    "workbench.sideBar.location": "left",
    "window.zoomLevel": 0,
    "editor.renderWhitespace": "all"
}
```

and my workspace settings:
```
{
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/bin": true,
        "**/obj": true,
        "**/node_modules": true
    },
    "files.associations": {
        "**/.ebextensions/*.config": "yaml"
    }
}
```
Here's the omnisharp log:
```
Starting OmniSharp server at 2/17/2017, 11:05:57 AM
    Target: d:\Users\ben\proj\sb\IdentityServer\IdentityServer.sln

OmniSharp server started
    Path: D:\Users\ben\.vscode\extensions\ms-vscode.csharp-1.7.0\bin\omnisharp\OmniSharp.exe
    PID: 14324

OmniSharp: -s d:\Users\ben\proj\sb\IdentityServer\IdentityServer.sln --hostPID 166116 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
[info]: OmniSharp.Startup
        Omnisharp server running using Stdio at location 'd:\Users\ben\proj\sb\IdentityServer' on host 166116.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in d:\Users\ben\proj\sb\IdentityServer
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBUILD_EXE_PATH environment variable set to D:\Users\ben\.vscode\extensions\ms-vscode.csharp-1.7.0\bin\omnisharp\msbuild\MSBuild.exe
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildExtensionsPath environment variable set to D:\Users\ben\.vscode\extensions\ms-vscode.csharp-1.7.0\bin\omnisharp\msbuild
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildSDKsPath environment variable set to D:\Users\ben\.vscode\extensions\ms-vscode.csharp-1.7.0\bin\omnisharp\msbuild\Sdks
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in 'd:\Users\ben\proj\sb\IdentityServer\IdentityServer.sln'.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Skipped unsupported project type 'src'
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from 'd:\Users\ben\proj\sb\IdentityServer\src\Saddleback.IdentityServer.Data\Saddleback.IdentityServer.Data.csproj'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Add project: d:\Users\ben\proj\sb\IdentityServer\src\Saddleback.IdentityServer.Data\Saddleback.IdentityServer.Data.csproj
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from 'd:\Users\ben\proj\sb\IdentityServer\src\Saddleback.IdentityServer.Web\Saddleback.IdentityServer.Web.csproj'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Add project: d:\Users\ben\proj\sb\IdentityServer\src\Saddleback.IdentityServer.Web\Saddleback.IdentityServer.Web.csproj
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Skipped unsupported project type '_'
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Skipped unsupported project type '.elasticbeanstalk'
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Skipped unsupported project type '.ebextensions-dev'
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Skipped unsupported project type '.ebextensions-stage'
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Skipped unsupported project type '.ebextensions-prod'
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Skipped unsupported project type 'sample'
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from 'd:\Users\ben\proj\sb\IdentityServer\sample\Saddleback.IdentityServer.SampleApi\Saddleback.IdentityServer.SampleApi.csproj'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Add project: d:\Users\ben\proj\sb\IdentityServer\sample\Saddleback.IdentityServer.SampleApi\Saddleback.IdentityServer.SampleApi.csproj
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: Saddleback.IdentityServer.Data
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: Saddleback.IdentityServer.Web
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: Saddleback.IdentityServer.SampleApi
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\Users\ben\proj\sb\IdentityServer'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Startup
        Configuration finished.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: Saddleback.IdentityServer.Data
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: Saddleback.IdentityServer.Web
```

**Comment by DustinCampbell** [comment]
Hmmm... this is extremely strange behavior. I _suspect_ the errors that you're seeing are coming from C# for VS Code. They look like something that would come from XML validation of some sort. What other extensions do you have installed? That is, what extensions do you have installed other than the ms-* extensions you listed above?

**Comment by aggieben** [comment]
![image](https://cloud.githubusercontent.com/assets/1321/23090426/7300d732-f563-11e6-8ba8-e679fcedbb44.png)

**Comment by DustinCampbell** [comment]
OK. These errors are *not* coming from C# for VS Code. They are coming from the [MSBuild Tools](https://marketplace.visualstudio.com/items?itemName=qub.qub-msbuild) extension that you have installed. I just installed that extension and see similar errors:

![image](https://cloud.githubusercontent.com/assets/116161/23093505/80973396-f59a-11e6-91a2-3c3e9b44177a.png)

If you uninstall that extension, I expect the errors will go away. Are IntelliSense and Find All References are working properly for you?

**Comment by aggieben** [comment]
🤦‍♂️ good grief, I should have spotted that.  Yes, once I uninstall qub-msbuild the problems/squigglies go away.

Thank you for help diagnosing!

**Comment by DustinCampbell** [comment]
Glad to hear it! Let me know if you have any other trouble.

**Comment by danschultequb** [comment]
@aggieben I'm sorry you had to deal with this. I've added this [issue](https://github.com/danschultequb/qub-typescript-msbuild/issues/1) in my MSBuild parser repository.
