### ISSUE TITLE
Issue with conditional variables

### ISSUE THREAD

**Issue by nigurr** [OmniSharp/omnisharp-vscode#1249]
## Environment data
VS Code version: 1.9.1
C# Extension version: 1.7.0

## Steps to reproduce
      public static class Agent
      {
        #if OS_LINUX
            public static readonly OSPlatform Platform = OSPlatform.Linux;
        #elif OS_OSX
            public static readonly OSPlatform Platform = OSPlatform.OSX;
        #elif OS_WINDOWS
            public static readonly OSPlatform Platform = OSPlatform.Windows;
        #endif
      }

## Expected  behavior
Compiler/Editor shouldn't throw error "Platform" variable is not found. it should be resolved

## Actual behavior
severity: 'Error'
message: ''Constants.Agent' does not contain a definition for 'Platform' [Agent.Listener]'
at: '21,37'

**Comment by DustinCampbell** [comment]
Could you provide a complete repro?

**Comment by nigurr** [comment]
@DustinCampbell https://github.com/Microsoft/vsts-agent :)

**Comment by DustinCampbell** [comment]
In the future, when asked for a repro, a little more direction would be helpful. It would also be helpful if you provided the output of `dotnet --info` as requested in the issue template when you filed this bug.

**Comment by DustinCampbell** [comment]
It looks to me like this is working as expected. There is a particular MSBuild variable that is not set anywhere, called OSConstant.

```XML
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>$(OSConstant);TRACE;DEBUG;</DefineConstants>
    <DebugType>portable</DebugType>
  </PropertyGroup>
```

This variable does not have a value anywhere. So, the compiler does not actually generate the `Platform` field, since each is under a `#if`.

**Comment by DustinCampbell** [comment]
It looks like `OSConstant` is specified at build time and isn't available at designtime. I see exactly the same issue in VS 2017 RC4 if I open these projects:

![image](https://cloud.githubusercontent.com/assets/116161/23133914/ac8494d6-f747-11e6-8936-51237d7fd433.png)
