### ISSUE TITLE
Trouble running debugger with csproj tooling

### ISSUE THREAD

**Issue by aggieben** [OmniSharp/omnisharp-vscode#1253]
## Environment data
`dotnet --info` output:
```
λ dotnet --info
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
```

VS Code version:  1.9.1
C# Extension version: 1.7.0

## Steps to reproduce
1.  Remove .vscode/launch.json
2.  Restart vscode and open project folder
3.  Agree to let OmniSharp-vscode generate new launch.json
4.  Try to launch

## Expected  behavior
Debugger launches web app, attaches to process

## Actual behavior
The following output is observed:
```
Microsoft (R) Build Engine version 15.1.545.13942
Copyright (C) Microsoft Corporation. All rights reserved.
MSBUILD : error MSB1009: Project file does not exist.
Switch: d:\Users\ben\proj\MyProject\src\MyProject.Web\project.json
```

I suspect there may be something in my csproj that causes this because when I create a new empty web project with `dotnet new web` and then open that folder in vscode, I'm able to run the debugger using the generating `launch.json` and it works fine.

Here's my project file:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <Product>MyProject Web Application</Product>
    <VersionPrefix>1.0.0</VersionPrefix>
    <PackageId>MyProject.Web</PackageId>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <!--<DebugType>portable</DebugType>-->
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>MyProject.Web</AssemblyName>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifiers>win10-x64;debian.8-x64;ubuntu.14.04-x64;ubuntu.16.04-x64</RuntimeIdentifiers>
    <!--<MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>-->
    <!--<GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>-->
    <Optimize Condition="'$(Configuration)' != 'Debug'">true</Optimize>
  </PropertyGroup>
  
  <ItemGroup>
    <Content Remove="config.local.json" />
    <None Include="config.local.json" />
    <!-- this is necessary because the default includes actually exclude these certs -->
    <None Remove="idsrv_signing_cert.pfx" />
    <None Remove="localhost.pfx" />
    <Content Include="idsrv_signing_cert.pfx" />
    <Content Include="localhost.pfx" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Update="Content/countries.json;hosting.json;config.json;idsrv_signing_cert.pfx;localhost.pfx;Features\**\*;wwwroot\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Content/countries.json;Features\**\*;wwwroot\**\*;hosting.json;config.json;config.dev.json;config.stage.json;config.prod.json;idsrv_signing_cert.pfx;localhost.pfx">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyProject.Data\MyProject.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.3.7.1" />
    <PackageReference Include="AWSSDK.CloudWatch" Version="3.3.1.3" />
    <PackageReference Include="AWSSDK.EC2" Version="3.3.4.4" />
    <PackageReference Include="IdentityModel" Version="2.5.1" />
    <PackageReference Include="IdentityServer4" Version="1.1.1" />
    <PackageReference Include="IdentityServer4.AspNetIdentity" Version="1.0.0" />
    <PackageReference Include="IdentityServer4.EntityFramework" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.HttpOverrides" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.DataAnnotations" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="1.1.0-msbuild3-update1">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel.Https" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.0" />
    <PackageReference Include="Serilog" Version="2.3.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="1.3.1" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="2.2.0" />
    <PackageReference Include="Serilog.Sinks.AwsCloudWatch" Version="2.0.49" />
    <PackageReference Include="Serilog.Sinks.Literate" Version="2.0.0" />
  </ItemGroup>
</Project>
```

I tried commenting out the `DebugType` property, as you can see above, but it didn't have any affect.  I'm not sure what else could be causing it though.

**Comment by aggieben** [comment]
I should add: it seems that the debugger will actually launch and attach if I click on the "debug anyway" prompt after the error occurs.

**Comment by caslan** [comment]
Maybe obvious, but the error you are getting is during "building" of the project. "Debug anyway" would work and let you debug the previously built version sitting on disk. Have you tried regenerating tasks.json file?

**Comment by aggieben** [comment]
@caslan is there a way to generate it with the tool, or is it something I will have to fill in manually?

**Comment by gregg-miskelly** [comment]
@aggieben it looks like your problem is that you have a project.json project, but the version of the .NET CLI that you have installed is a .csproj based one (\> preview-2). You are supposed to be able to drop a global.json file to force the CLI to use the preview-2 version, but that doesn't work for me at least. So you can do one of two things --

1. Migrate your project from project.json to csproj.
-or-
2. Install the preview-2 CLI from https://www.microsoft.com/net/core#windowscmd, and change your tasks.json so that the command line that runs in `dotnet %ProgramW6432%\dotnet\sdk\1.0.0-preview2-1-003177\dotnet.dll build` instead of `dotnet build`.

**Comment by aggieben** [comment]
@gregg-miskelly This project is one that had already been migrated.  There is no `project.json`.

**Comment by gregg-miskelly** [comment]
@aggieben in that case, if you look at your tasks.json file, can you see why the path to a project.json file is being provided to `dotnet build`?

**Comment by aggieben** [comment]
I can't see any apparent reason.  I just did `gci -rec -filter project.json` and it found a couple that were hiding in `backup` folder, but I've now deleted those, deleted the `tasks.json` and reopened the folder, and after switching to the debug tab it regenerated `.vscode/tasks.json`.  Now it points to a .csproj file, albeit the wrong one.

After manually editing it to point to the right one, it appears to try to start, but then immediately exits with `The program 'd:\path\to\my\project\project.dll` has exited with code 0`.  I've been seeing this same behavior in another, new project (never migrated, created with CLI RC4).

**Comment by aggieben** [comment]
Ok, looks like I got it now.  My `launch.json` was also still pointing to the wrong `.csproj`.  After I edited that to agree with what I edited into my `tasks.json`, I'm able to debug effectively.

Thanks for the help.  Oddly, I'm not even sure what changed here, because these are steps I tried previously.

**Comment by aggieben** [comment]
I closed this because the immediate issue has been resolved - however, I still see the `The program has exited with code 0` in another project (new with CLI RC4, not migrated).

**Comment by gregg-miskelly** [comment]
@aggieben if you want to open a new issue I can try and help you through it. A few questions for the new issue --

Do you always see the `program has exited with code 0` or is it intermittent? 

If you always get it --
* What is `program` set to in launch.json?
* Can you send me the output you get in your console window?
