### ISSUE TITLE
Argument name suggestions in methods/ctors

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-vscode#1254]
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004771
```
VS Code version:1.9
C# Extension version:1.8 beta

## Steps to reproduce
Enter a type into a constructor then begin to type the name of the argument

## Expected  behavior
Suggestions of what to call it in a drop down eg. if you have `public Foo(Bar` it should give suggest `bar`

## Actual behavior
N/A

**Comment by DustinCampbell** [comment]
I'm confused by the title, which talks about field names, but the expected behavior seems to describe the completion list suggesting parameter names. Is your request essentially https://github.com/dotnet/roslyn/issues/7055?

**Comment by jchannon** [comment]
My bad.

Yup that roslyn feature 😄

**Comment by DustinCampbell** [comment]
Thanks for clarifying. I wouldn't spend the effect adding this to VS Code since we don't want the C# editing experience to diverge. But once we get it in Roslyn, we'll definitely bring it here.

cc @Pilchie

**Comment by jchannon** [comment]
Looks like it's in. What needs to be done to bring it in?

**Comment by DustinCampbell** [comment]
It's just a matter of time now. We've got some [changes coming](https://github.com/OmniSharp/omnisharp-roslyn/pull/840) that should allow this feature to show up in VS Code.

**Comment by jchannon** [comment]
Does it come automatically or does something else need doing, do you need some help?

**Comment by DustinCampbell** [comment]
We'll always take help! :smile: That said, this should come in naturally when we update OmniSharp to the latest Roslyn packages. AFAIK, these changes aren't available on NuGet yet, and I'd prefer that over grabbing random nightlies from the Roslyn MyGet feed.
