### ISSUE TITLE
Error: read ECONNRESET When debugging

### ISSUE THREAD

**Issue by gregflynn** [OmniSharp/omnisharp-vscode#1255]
## Environment data
`dotnet --info` output:
> dotnet --info
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /opt/dotnet/sdk/1.0.0-rc4-004771

VS Code version:
> code --version
1.9.1
f9d0c687ff2ea7aabd85fb9a43129117c0ecf519

C# Extension version: 1.7.0

## Steps to reproduce
debug a C# process

## Expected  behavior
debugger launches and attaches

## Actual behavior
errors in console, doesn't start or attach
if using the run configuration (as opposed to attach) it will prelaunch build but fail after prelaunch

distro is Arch, up to date
![image](https://cloud.githubusercontent.com/assets/295898/23131511/3e5ca654-f758-11e6-9b44-29736824f942.png)

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/bin/Debug/netcoreapp1.0/mercury.dll",
            "cwd": "${workspaceRoot}",
            "externalConsole": false,
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart"
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command.pickProcess}"
        }
    ]
}
```

**Comment by gregg-miskelly** [comment]
@gregflynn my _guess_ is that our debug adapter process is crashing, though this is just a guess. Arch isn't really a supposed OS distro for .NET Core, so we are happy to help if we can, but it might turn out we can't get this to work. Based on other Arch customers, we currently use the Ubuntu 16.04 version of .NET Core for running the debugger itself. Sounds like you are using the Ubuntu 14.04 .NET Core. So I am not sure if something changed in Arch, or if they both run (which would be somewhat weird since they don't even manage that on Ubuntu).

To see if our adapter is just completely on the floor, you can try:
    cd ~/.vscode/extensions/ms-vscode.csharp-1.7.0/.debugger
    ./OpenDebugAD7 --help

If that successfully prints something then you can try:
    ./OpenDebugAD7 --server
// which will launch our debugger on a socket

And then try adding: `"debugServer":4711,` to your active launch.json configuration setting and try launching that way.

Hopefully you will find that at least one of these crashes giving something useful over stderr.

**Comment by gregflynn** [comment]
```
 ./OpenDebugAD7 --help
Failed to initialize CoreCLR, HRESULT: 0x80131500
```

:disappointed: 


From a command I found on another thread:
```
 find /opt/dotnet -name '*.so' -type f -print | xargs ldd | grep 'not found'
	liblldb-3.6.so => not found
	liblldb-3.6.so => not found
/opt/dotnet/shared/Microsoft.NETCore.App/1.0.3/System.Net.Http.Native.so: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /opt/dotnet/shared/Microsoft.NETCore.App/1.0.3/System.Net.Http.Native.so)
```

```
 pacman -Ss lldb
extra/lldb 3.9.1-2 [installed]
    Next generation, high-performance debugger
```
So that's installed just too new :thinking: 

This is the AUR package link also https://aur.archlinux.org/packages/dotnet-cli/

**Comment by gregg-miskelly** [comment]
That HRESULT is not helpful unfortunately -- COR_E_EXCEPTION.
lldb shouldn't be the problem - CoreCLR doesn't need it in this scenario.
System.Net.Http.Native sounds like it may be an issue if you are trying to ASP.NET, but I don't think OpenDebugAD7 will have an issue.

The first thing I might suggest is downloading https://vsdebugger.azureedge.net/coreclr-debug-1-7-1/coreclr-debug-ubuntu.14.04-x64.zip and see if `OpenDebugAD7 -h` works any better there.

If that doesn't help, you are finding over the version of dotnet installed to run apps, but the debugger has its own copy of CoreCLR/CoreFX in the .debugger directory, so you could try running find in the .debugger directory instead. I think there are also ways to get CoreCLR to print some logging. So we could try that too.

**Comment by gregflynn** [comment]
Alright something worked

```
 ./OpenDebugAD7 -h
OpenDebugAD7: Visual Studio Code debug adapter bridge for using Visual Studio
debug engines in VS Code

Available command line arguments:
--trace: print the requests coming from VS Code to the console.
--trace=response: print requests and response from VS Code to the console.
--engineLogging[=filePath]: Enable logging from the debug engine. If not
    specified, the log will go to the console.
--server[=port_num] : Start the debug adapter listening for requests on the
    specified TCP/IP port instead of stdin/out. If port is not specified
    TCP 4711 will be used.
--pauseForDebugger: Pause the OpenDebugAD7.exe process at startup until a
    debugger attaches.
```

and 
```
 ./OpenDebugAD7 --server
waiting for v8 protocol on port 4711
waiting for v8 protocol on stdin/stdout
```

When running `OpenDebugAD7` from within that zip archive, I'm not quite sure what this means though

**Comment by gregg-miskelly** [comment]
@gregflynn you can try this then --
Replace the .debugger folder
`echo install.complete > .debugger/install.complete`
`chmod +x .debugger/OpenDebugAD7`
`chmod +x .debugger/clrdbg`

And see if this produces something that works.

**Comment by gregflynn** [comment]
@gregg-miskelly works like a charm, a little hacky but I'll take it :smile:
