### ISSUE TITLE
Syntax highlighting is wrong for comments after the class name

### ISSUE THREAD

**Issue by cateyes99** [OmniSharp/omnisharp-vscode#1256]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004771

VS Code version: 1.8.1
C# Extension version: 1.7.0

## Steps to reproduce
```C#
public cass A //comments : BaseClass
{}
```
or
```c#
public cass A
//comments : BaseClass
{}
```

## Expected  behavior
the commented out stuff should be highlighted as comments in dark green

## Actual behavior
`//comments :` is in white, and `BaseClass` is still highlighted as a class.

**Comment by DustinCampbell** [comment]
This is already fixed and checked into VS Code for the February release.

https://github.com/dotnet/csharp-tmLanguage/issues/41
https://github.com/Microsoft/vscode/pull/20831
