### ISSUE TITLE
Debugging f# on .net core

### ISSUE THREAD

**Issue by enricosada** [OmniSharp/omnisharp-vscode#1257]
ref https://github.com/ionide/ionide-vscode-fsharp/issues/366

I'd like to support debugging of .net core f# apps. That app will generate portable pdb, and is built with latest released f# .net core compiler (`fsc`)

Doing some tests, it works sort of, 

![image](https://cloud.githubusercontent.com/assets/147243/23175285/32bf2864-f85f-11e6-8558-3cde7ab9adf4.png)

Repro:

- clone https://github.com/enricosada/vscode-debugging-repro
- follow [readme.md](https://github.com/enricosada/vscode-debugging-repro/blob/master/README.md), so `dotnet restore && code .` and `F5`

launch.fs is the one generated by omnisharp

## What works?

- stop on exception
- eval/locals (c# style)
- breakpoints **require dev version of ionide**
- nested functions (need a new repro, but just extract `failwith` in a function)  **require dev version of ionide**

## What doesnt work

- eval f# style

Some guidance from debugger team on how add debugger breakpoints? It's something the vs extension ionide https://github.com/ionide/ionide-vscode-fsharp should do?

Thanks to @DustinCampbell @filipw for help.

/cc @KevinRansom @cartermp @Krzysztof-Cieslak

## Environment data
`dotnet --info` output: `1.0.0-rc4-004771`
VS Code version:  `1.9.1`
C# Extension version: `1.7.0`
F# Ionide Extension version: `2.22.3`

**Comment by DustinCampbell** [comment]
cc @gregg-miskelly

**Comment by enricosada** [comment]
some info about portablepdb and breakpoint from @filipw : https://github.com/dotnet/roslyn/pull/16489#discussion_r96521263 to not lose it :D

**Comment by enricosada** [comment]
Some progress thanks to @Krzysztof-Cieslak 

If i add `mono-debugger` extension, breakpoint magically start to work for .net core debugger too.
Checking source code, `mono-debugger` [enable breakpoints](https://github.com/Microsoft/vscode-mono-debug/blob/dd1348275afc2357403663b33ef0a5ff451d5ead/src/MonoDebugSession.cs#L487) [checking](https://github.com/Microsoft/vscode-mono-debug/blob/dd1348275afc2357403663b33ef0a5ff451d5ead/src/MonoDebugSession.cs#L436-L440) the [filename extension](https://github.com/Microsoft/vscode-mono-debug/blob/dd1348275afc2357403663b33ef0a5ff451d5ead/src/MonoDebugSession.cs#L21-L24)

So where is the code who does that for c# in .net core debugger? a similar fix maybe is enough.

**Comment by enricosada** [comment]
related, also unity debugger work like `mono-debugger` but [doesnt enable f# extensions](https://github.com/Unity-Technologies/vscode-unity-debug/blob/master/UnityDebug/UnityDebugSession.cs#L23)

**Comment by enricosada** [comment]
More progress. breakpoints works, steps too

![debug-breakpoints](https://cloud.githubusercontent.com/assets/147243/23219994/d8e688ba-f920-11e6-88dd-9284f9f3fb23.gif)


Added to `package.json` to enable breakpoints

```json
     "breakpoints": [
        {
          "language": "fsharp"
        }
      ]
```

**Comment by gregg-miskelly** [comment]
@enricosada that sounds correct that you would add 'fsharp' under breakpoint languages in package.json.

**Comment by gregg-miskelly** [comment]
@enricosada does this issue track anything else, or should I close it?

**Comment by gregg-miskelly** [comment]
@enricosada I am closing this for now. But feel free to ping back and/or open a new issue if there is more that we can try and help with.

**Comment by enricosada** [comment]
Thank @gregg-miskelly i think can be closed too, sry for late reply. Debugging will works ok with f#.

I didnt had the opportunity to reach the debugger team yet (i have no points of contact atm because i dont know who they are) to have come clarification about how to improve things (like eval), etc. will try other ways (suggestion welcome :D)

But is ok :D, thx for help!

**Comment by gregg-miskelly** [comment]
@enricosada the debugger team is my team. You can open issues here and we will see them.

For supporting F# expressions - someone would need to develop an F# expression evaluator. There is a sample expression evaluator on https://github.com/Microsoft/ConcordExtensibilitySamples/wiki/Managed-Expression-Evaluator-Sample.

**Comment by enricosada** [comment]
Sorry Gregg, i confused your reply because in this repo.
I also didnt check the teams list on dotnet org (but that is visibile only if logged, uops two times)
So my bad.

> Our model is that we provide the language-neutral infrastructure and language teams write the language-specific portions

Perfect for me, i like that. if is language neutral by default, is easier to add other langs like f#. When is c# first and extensibility is added instead is a pain (just an example the lang, is valid for all extensible tools)

> We are happy to provide some assistance in getting started / when folks get stuck. But it isn't something we have the resources or F# expertise to implement ourselves

I think that's enough, can be done by F# community, just need a bit of guidance/pointers at start. and the repo you linked is a really good start. The real hard part is to find info to start 😄

**Comment by enricosada** [comment]
@gregg-miskelly added https://github.com/Microsoft/visualfsharp/issues/2544 to track f# evaluator, if someone in community want to try implement that. Thx a lot another time!

**Comment by enricosada** [comment]
@gregg-miskelly @DustinCampbell as a note, thx a lot for support.

now F# works ootb (ionide obv) with `dotnet new` -> `dotnet restore` -> intellisense! -> F5 -> debug!

with packagererences, projectreferences etc 😄 

![recf-ionide2](https://cloud.githubusercontent.com/assets/147243/24160683/cad857ce-0e62-11e7-925f-ade49e5ad333.gif)

**Comment by DustinCampbell** [comment]
Very nice! cc @cartermp

**Comment by gregg-miskelly** [comment]
@enricosada Very cool!

**Comment by cartermp** [comment]
Huge work @enricosada!

**Comment by kontomondo** [comment]
@enricosada I tried the steps in the video but I'm not getting the .NET Core environment selection. If I manually add a launch.json with debug type coreclr it says no such debugger registered. This is on Linux. Anything extra I need to do ?

**Comment by rubberduck203** [comment]
If anyone finds themselves here wondering why you keep getting errors while trying to debug, make sure you pay attention to the error message. I had to download the .Net Core debugger to get this to work.

`Ctrl` + `P` to open the command palette then type

```
> Debug: Download Download .NET Core Debugger
```
