### ISSUE TITLE
CodeLens and Data Annotations

### ISSUE THREAD

**Issue by rhires** [OmniSharp/omnisharp-vscode#1260]
Posted originally here: Microsoft/vscode/issues/21208

## Environment data
`dotnet --info` output:
bash-3.2$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.10
 OS Platform: Darwin
 RID:         osx.10.10-x64

VS Code version: 1.10 insiders
C# Extension version:1.7.0

I have been advised that perhaps this is the right place for this feature request. 

VSCode Version: Version 1.10.0-insider (1.10.0-insider)
OS Version: Mac OS

Currently, CodeLens in the Model classes sticks right above the POCO. But when I add annotations, I get the CodeLens in between the POCO and the Annotation, and when I have a couple of them, it gets confusing:

![image](https://cloud.githubusercontent.com/assets/12577765/23234696/e259c060-f920-11e6-9909-94ab7f68cb56.png)

What I would like to see is that the CodeLens be included above the annotation for the POCO, so that it's all treated as a single unit:

![image](https://cloud.githubusercontent.com/assets/12577765/23234716/ef0e24d6-f920-11e6-8fea-0346ed4e7226.png)

Thank you for all of the great work you do!

**Comment by DustinCampbell** [comment]
This looks like a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/429. Is that right?

**Comment by rhires** [comment]
@DustinCampbell Yes. Totally a duplicate. I looked for dupes before using "codelens" (and variations) but didn't find it. Can you mark it appropriately?

**Comment by DustinCampbell** [comment]
FWIW, the issue is marked with a CodeLens tag.
