### ISSUE TITLE
Debugger: Failed to attach to proccess:Unknown Error:0x80131c08

### ISSUE THREAD

**Issue by ClaireKang** [OmniSharp/omnisharp-vscode#1261]
## Environment data
dotnet --info output:
OS: ubuntu14.04
VS Code version: 1.9.1
C# Extension version: 1.8.0-beta1
dotnet cli: 1.0.0-preview2-1-003177

## Steps to reproduce
1. Open attached folder with VSCode.
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/798908/hwapp.zip)

2. Select '.NET Core Attach'.
3. Open one terminal, and 'dotnet run' the project.
4. F5 to start debugging and select the running process to attach to.
5. Stop debugging after the process run correctly.
6. Continue to do the step #4 above.

## Expected  behavior
The process can work correctly.

## Actual behavior
Pop up a following error message:
![error](https://cloud.githubusercontent.com/assets/20184768/23299395/6a0afd2a-fabc-11e6-84df-84e7746ef990.PNG)

## Investigation
1. After the #6, maybe need to wait about 15 seconds or more.
2. This issue often occur second 'Attach' operation.

**Comment by rajkumar42** [comment]
I'm unable to reproduce.. lets keep the issue open for now.

**Comment by chuckries** [comment]
cc @gregg-miskelly 
This appears to be yet another issue with testing with tight loops. After attaching to this process that is running a tight, infinite loop, we are unable to disconnect cleanly from the debuggee. This leaves us in a state where vsdbg-ui is just killed out from underneath us and the debuggee process is left in a bad state. Attaching to it again is then completely broken. Adding a `Thread.Sleep(100);` to the loop appears to fix all issues. 

@ClaireKang Can you please try this tests again after adding `Thread.Sleep(100);` to your loop?

**Comment by ClaireKang** [comment]
This issue didn't reproduce after adding Thread.Sleep(100).

**Comment by gregg-miskelly** [comment]
Thanks! In that case this is more or less the same issue as dotnet/coreclr#4623. Please avoid super tight loop in test debuggees until that is resolved (which is likely to be a long time).
