### ISSUE TITLE
Unable to open 'Program.cs': File not found (\Program.cs).

### ISSUE THREAD

**Issue by billwert** [OmniSharp/omnisharp-vscode#1262]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-alpha-004853)

Product Information:
 Version:            2.0.0-alpha-004853
 Commit SHA-1 hash:  e7689a3116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15040
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\work\dotnets\2.0.0-alpha-004853\sdk\2.0.0-alpha-004853\

VS Code version:
Version 1.9.1
Commit f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
Date 2017-02-09T00:26:45.394Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
C# Extension version:
1.7.0

## Steps to reproduce
mkdir test
dotnet new console
dotnet restore
code .
Introduce a syntax error (remove the " from the WriteLine or something)
configure task runner for .NET core
build

## Expected  behavior
Build fails, error window can be double clicked to take me to the error

## Actual behavior
![errors](https://cloud.githubusercontent.com/assets/4523120/23344357/eabe101e-fc2f-11e6-98e1-c00cd3e2a994.jpg)

Note that Program.cs is listed twice. The ones from the first ("Program.cs \\") only appear after build.

**Comment by DustinCampbell** [comment]
I suspect that Program is listed twice because errors are duplicated between the build and live in the editor. The issues you ran into should be tracked by https://github.com/OmniSharp/omnisharp-vscode/issues/1197 and https://github.com/OmniSharp/omnisharp-vscode/issues/1198.

**Comment by billwert** [comment]
Cool. The workaround in #1197 did the trick for this issue.
