### ISSUE TITLE
Debugger: Expression execute twice in watch window

### ISSUE THREAD

**Issue by qian6** [OmniSharp/omnisharp-vscode#1267]
## Environment data
`dotnet --info` output:
VS Code version: 1.9.1
 C# Extension version: [\scratch2\scratch\janraj\vsdbg2\csharp-1.8.0-beta1.vsix ](\scratch2\scratch\janraj\vsdbg2\csharp-1.8.0-beta1.vsix )
 .NET Core SDK: 1.0.0-preview2-1-003177

## Steps to reproduce
1. Open hwapp folder in vscode.
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/803171/hwapp.zip)
2. Set a breakpoint at line of 11 in Program.cs file.
3. Press F5 to start debugging.
4. Evaluate "i++" in watch windows

## Expected  behavior
"i++" value should be 2.

## Actual behavior
"i++" value is 3.

## Investigation
1. it is normal when press restart.

**Comment by qian6** [comment]
This issue repro on all OS.

**Comment by gregg-miskelly** [comment]
This sounds like a VS Code issue, but we will confirm.

**Comment by chuckries** [comment]
@gregg-miskelly I can confirm that VS Code is sending evaluate commands twice and that this also repros in the 1.7.0 release. I will log an issue against VS Code.

**Comment by chuckries** [comment]
VS Code issue: https://github.com/Microsoft/vscode/issues/21524

**Comment by qian6** [comment]
ok,Got it!
