### ISSUE TITLE
"Sorting Using Directives" is missing

### ISSUE THREAD

**Issue by cateyes99** [OmniSharp/omnisharp-vscode#1268]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004771
VS Code version: 1.9.1
C# Extension version: 1.7.0

## Steps to reproduce
Create a C# file in .NET Core project, add some using directives at the top of the file in an unsorted order.

## Expected  behavior
It should provide an option to sort these using directives. (the old plugin for DNX provides this feature)

## Actual behavior
No such feature available now.

**Comment by DustinCampbell** [comment]
We're tracking Sort Usings with https://github.com/OmniSharp/omnisharp-vscode/issues/788.
