### ISSUE TITLE
Unity3D Experimental Scripting Preview

### ISSUE THREAD

**Issue by rakkarage** [OmniSharp/omnisharp-vscode#1269]
## Environment data
`dotnet --info` output:
VS Code version: 1.10.0-insider
C# Extension version:
"1.7.0 (February 8, 2017)" - changelog

## Steps to reproduce
Install new Unity3D Experimental Scripting Preview.
Make new project in unity. Make a new file that uses System.Threading.Tasks.
Open in vscode.

## Expected  behavior

Works fine in current Release Unity3D so I don't know if it is a Unity3D problem or a OmniSharp problem yet.

## Actual behavior

[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The reference assemblies for framework ".NETFramework,Version=v4.6" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

**Comment by DustinCampbell** [comment]
Make sure you have Mono installed. I'm not sure what OS you're running, but if you're on OSX, "brew install mono" will likely solve the issue.

**Comment by rakkarage** [comment]
the project file is generated with 4.6 if generated with (or changed to) 4.6.1 it is resolved
unity's problem

`
using System.IO;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;
[InitializeOnLoad]
class Fix : AssetPostprocessor
{
	private static void OnGeneratedCSProjectFiles()
	{
		Debug.Log("OnGeneratedCSProjectFiles");
		var dir = Directory.GetCurrentDirectory();
		var files = Directory.GetFiles(dir, "*.csproj");
		foreach (var file in files)
			FixProject(file);
	}
	static bool FixProject(string file)
	{
		var text = File.ReadAllText(file);
		var find = "<TargetFrameworkVersion>v4.6</TargetFrameworkVersion>";
		var replace = "<TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>";
		if (text.IndexOf(find) != -1)
		{
			text = Regex.Replace(text, find, replace);
			File.WriteAllText(file, text);
			return true;
		}
		else
			return false;
	}
}
`

**Comment by DustinCampbell** [comment]
Ah -- that makes sense. Thanks!
