### ISSUE TITLE
Debugger: The "externalConsole" property has no effect

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#1270]
## Environment data
`dotnet --info` output:
VS Code version: 1.9.1
C# Extension version: \\scratch2\scratch\janraj\vsdbg2\csharp-1.8.0-beta1.vsix 
.NET Core SDK: 1.0.0-preview2-1-003177
OS: Debian 8.2 x64

## Steps to reproduce
1. Open attached folder
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/806159/hwapp.zip)
2. Change the configurations in launch.json 
       "externalConsole": true,
3. Select '.NET Core Launch(console).
4. Set a breakpoint at line of 9.
5. F5 to start debugging.

## Expected  behavior
The Console window should be open.

## Actual behavior
There is not occur the Console window.

## Investigation
The Console window can be open on windows OS and Zorin OS. Could you please help me to confirm this is expected?

**Comment by gregg-miskelly** [comment]
This is expected as of this moment -- we are working on implementing this.

**Comment by gregg-miskelly** [comment]
This is now fixed internally. The next release will include it.
