### ISSUE TITLE
Debugger: Steps by statment instead of by line in VS Code

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#1271]
## Environment data
`dotnet --info` output:
VS Code version: 1.9.1
C# Extension version: \scratch2\scratch\janraj\vsdbg2\csharp-1.8.0-beta1.vsix
.NET Core SDK: 1.0.0-preview2-1-003177
OS: Debian 8.2 x64

## Steps to reproduce
1. Open attached folder.
[step.zip](https://github.com/OmniSharp/omnisharp-vscode/files/806190/step.zip)
2. Select '.NET Core Launch(console).
3. Set a breakpoint at line of 22.
4. F5 to start debugging.
5. Press F11 after the breakpoint be hit.

## Expected  behavior
The cursor should be hit 14 line.

## Actual behavior
The cursor still stays at 22 line.

## Investigation
1. This is automation test case, expected cursor hit 14 line. 
2. On Zorin OS, the cursor hit 14 line after step#5 .
3. Could you please help me to confirm which is expected?

**Comment by gregg-miskelly** [comment]
I am a little surprised this ever worked -- there are multiple statements on line 22, and I didn't think we did work to put the debugger in 'step by line' mode. At any rate, it wouldn't be too hard to put ourselves in 'step by line' mode in the VS Code case (we wouldn't want to for VS).

**Comment by qian6** [comment]
This issue also repro on windows.
Repro steps:
1. Perform the above repro steps .
2. Press F11 twice .

Expected behavior
The cursor should be hit 14 line.

Actual behavior
The cursor still stays at 22 line.

Investigation
1. **If I press F11 Three times, The cursor hit in 23 line.**

**Comment by gregg-miskelly** [comment]
@pieandcakes please resolve this when you checkin.

**Comment by pieandcakes** [comment]
@gregg-miskelly I checked in but I don't have access to assign myself or close issue.

**Comment by gregg-miskelly** [comment]
@DustinCampbell any objection if I add Pierson as a member of this repo?

I will close this one now.

**Comment by gregg-miskelly** [comment]
This issue will be resolved in the next 1.8 beta.

**Comment by DustinCampbell** [comment]
> @DustinCampbell any objection if I add Pierson as a member of this repo?

nope

**Comment by qian6** [comment]
This issue also repro on windows.
 Repro steps:
1.Perform the above repro steps .

Expected behavior
 The cursor should be hit 14 line.

Actual behavior
 The cursor still stays at 23 line.

**Comment by gregg-miskelly** [comment]
@qian6 I am not able to repro this. If you clear out all your breakpoints (so VS Code isn't restoring your breakpoints from previous sessions) and reset them, do you still see it? If so, can you add a trace?

**Comment by qian6** [comment]
This issue can not repro, Thanks for your share information.

**Comment by gregg-miskelly** [comment]
Thanks for checking.
