### ISSUE TITLE
Unable to use go to definition

### ISSUE THREAD

**Issue by ashishmansukhani** [OmniSharp/omnisharp-vscode#1273]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:
1.7.0
## Steps to reproduce
install extention. 
try to use go to or peek definition

**Comment by DustinCampbell** [comment]
Could you provide more detailed repro steps? Do you have a C# project we could use to reproduce the issue?

**Comment by DustinCampbell** [comment]
I'm going to go ahead and close this since there's not enough information provided to investigate. If you have more information that could help us reproduce the issue, let me know.
