### ISSUE TITLE
launch.json template should switch from 'command.' to 'command:'

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#1275]
In VS Code 1.10, the `${command.` was deprecated, and gives a warning to switch to `${command:`. But our templates still use the '.' version.

**Comment by chuckries** [comment]
Do we need to update our minimum VS Code version with this fix as well?

**Comment by gregg-miskelly** [comment]
I think so. We will be doing so with the vsdbg work anyway, so I don't see any downside of doing that.
