### ISSUE TITLE
Project.json dependencies autocomplete does not appear

### ISSUE THREAD

**Issue by Sniperumm** [OmniSharp/omnisharp-vscode#1277]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

VS Code version: 1.10.1
C# Extension version: 1.7.0

## Steps to reproduce
1 - Create new dotnet project (dotnet new)
2 - Open project in vs code
3 - Go to project.json
4 - Start adding a new dependency under "dependencies"

## Expected  behavior
Dependency autocompletetion should appear.

## Actual behavior
Dependency autocompletetion does not appear.

**Comment by DustinCampbell** [comment]
Yes, we've transferred this functionality from VS Code proper into the C# for VS Code extension. However, we aren't quite ready to ship the new version of C# for VS Code just yet. Once we have a beta available for the latest extension, I'll be sure to ping back here.

**Comment by Sniperumm** [comment]
Thanks for your quick reply :) I've downgraded vscode until the c# extension update.

**Comment by SailleshPawar** [comment]
Thanks for the update @gregg-miskelly

**Comment by DustinCampbell** [comment]
I'm going to go ahead and close this. The feature will be back in our 1.8 release and is currently available in the 1.8-beta2 release on this repo.

**Comment by Sniperumm** [comment]
Hi @DustinCampbell. I updated Visual Studio Code to the latest version as well as the extension to 1.8. Still not getting any autocompletion with the dependencies. Has this definitely been added to 1.8?

**Comment by DustinCampbell** [comment]
You're right. I'm not seeing completion working. I *am* seeing hover tooltips, but not completion. Taking a look.

**Comment by DustinCampbell** [comment]
@aeschli: Any chance you could take a look at this? While debugging, As far as I can tell, the VS Code JSON language server is overriding the project.json completion provider such that `provideCompletionItems` never gets called. If I change the registration of the project.json completion provider to include a couple of "trigger" characters (e.g. `'.'`), `provideCompletionItems` is called and properly produces a valid `CompletionList` when those characters are typed. However, `resolveCompletionItem` is never called for any of the items in the list so they never get displayed.

Is there a way I can register the project.json completion provider to ensure it has priority over the JSON language server?

**Comment by aeschli** [comment]
With 1.8 I see the proposals in project.json, but only after first opening a .cs file. Is that the problem?
I see that you have '"workspaceContains:project.json"' in your package.json. I think that has the limitation to only look for the file in the top level workspace folder.

**Comment by DustinCampbell** [comment]
You see them? They appear in the editor while typing within a project.json?

I do see the completion list appear for values or properties in a project.json file (other than those in the schema). However, I *do* see hover tooltips.

No completion:

![image](https://cloud.githubusercontent.com/assets/116161/24022498/0dac2f92-0a64-11e7-9680-5e323ddf961a.png)

But hover tooltips:

![image](https://cloud.githubusercontent.com/assets/116161/24022503/14c648bc-0a64-11e7-827a-635327424491.png)


Yes, I've opened a C# file to activate the extension.

**Comment by aeschli** [comment]
I get them with Ctrl+Space.

![image](https://cloud.githubusercontent.com/assets/6461412/24032078/7877e884-0ae6-11e7-906c-505116e35c41.png)
![image](https://cloud.githubusercontent.com/assets/6461412/24032209/13235616-0ae7-11e7-9424-6f1d0b0358da.png)

**Comment by DustinCampbell** [comment]
Awesome! Any idea why they wouldn't show up during typing?

**Comment by DustinCampbell** [comment]
Also, to verify, yes, I see them showing up on Ctrl+Space as well.

**Comment by DustinCampbell** [comment]
OK. I'm seeing some pretty inconsistent behavior from VS Code here. If I register the `JSONCompletionItemProvider` to trigger with the `"` and ':' characters like the JSON extension in VS Code does, `provideCompletionItems` gets called when typing `"` or alphanumeric characters within property names, but `resolveCompletionItem` does not get called.

First, I changed the registration:

```TypeScript
    // register completion and hove providers for JSON setting file(s)
    let contributions = [new ProjectJSONContribution(xhr)];
    contributions.forEach(contribution => {
        let selector = contribution.getDocumentSelector();
        subscriptions.push(languages.registerCompletionItemProvider(selector, new JSONCompletionItemProvider(contribution), '"', ':'));
        subscriptions.push(languages.registerHoverProvider(selector, new JSONHoverProvider(contribution)));
    });
```

Next, I compiled and started debugging. Upon typing a `"` in the dependencies node, my breakpoint is hit in `provideCompletionItems`:

![image](https://cloud.githubusercontent.com/assets/116161/24045550/c172a132-0adc-11e7-8bff-cc227abdc7d9.png)

Next, I press F5 and my second breakpoint is hit, showing a `CompletionList` properly being returned and populated with NuGet packages.

![image](https://cloud.githubusercontent.com/assets/116161/24045616/f0d6aacc-0adc-11e7-8583-458bfb5776e9.png)

I press F5 again and my breakpoint in `resolveCompletionItem` is not hit. The completion list does not appear. Any ideas?

**Comment by DustinCampbell** [comment]
@aeschli: Do you have any thoughts on my post above? It would be great to have a completion experience in project.json where the completion list appears as the user types rather than just on Ctrl+Space.

cc @jrieken as well.

**Comment by aeschli** [comment]
'resolveCompletionItem' would only be called once the suggestion widget is open and an entry selected.
Adding `"` and `:` is a good thing to do as trigger characters.
Automatic opening (as you type) of the suggestion dialog is controlled by the configuration setting `editor.quickSuggestions`. It should be on by default and work. For it to work, you must type at the end of a word (no `" ` directly after the cursor).
In case you are using the latest insiders, it was not working for strings in JSON. I just pushed a fix for that.

**Comment by DustinCampbell** [comment]
> In case you are using the latest insiders, it was not working for strings in JSON. I just pushed a fix for that.

That sounds like the problem we're seeing. Was that bug only in insiders or in the main release?

**Comment by aeschli** [comment]
Only in insiders, for like the last week.

**Comment by DustinCampbell** [comment]
OK. I'm seeing this problem in the main release of VS Code (1.10.2). Even with trigger characters set to '"' and ':', we're only seeing completion in specific cases, and the experience isn't great.

I *do* see completion as I type, if I don't type quotes first. For example:

![image](https://cloud.githubusercontent.com/assets/116161/24154233/d9ad4ac0-0e0d-11e7-8e5e-3f02f5041b2d.png)

However, if I type a `"`, I see the behavior described above where `provideCompletionItems` is called and returns a list, but `resolveCompletionItem` is never called because the list doesn't get displayed. I'm guessing there's some conflict between the in-product JSON schema completion and our completion item provider that causes this issue. Any ideas how to address that?

**Comment by aeschli** [comment]
It's likely a filtering issue. Your proposals get filtered out.
Can you add after https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/features/json/projectJSONContribution.ts#L107
`proposal.filterText = JSON.stringify(name);`

**Comment by DustinCampbell** [comment]
Ah ha! That's what was missing. Thanks for your help and patience @aeschli!

**Comment by DustinCampbell** [comment]
OK, I've got a PR out with changes that should greatly improve the experience for project.json completion. Thanks again @aeschli!

**Comment by DustinCampbell** [comment]
@Sniperumm: I've created a new [v1.9.0-beta1](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.9.0-beta1) release that should fix this for you. Be sure to use the [Installing Beta Releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) instructions if you want to try the beta.
