### ISSUE TITLE
I just now updated the VS code

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#1283]
_From @SailleshPawar on March 3, 2017 17:8_

HI Team,

I just now updated VS code i am not able to get IntelliSense while downloading package in project.json file.
Is anybody facing the same.

_Copied from original issue: Microsoft/vscode#21909_

**Comment by aeschli** [comment]
That code moved to the [C# extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp).

**Comment by gregg-miskelly** [comment]
@SailleshPawar this is the same issue as https://github.com/OmniSharp/omnisharp-vscode/issues/1277. It will be fixed in the next version of the C# extension. If you want it to work now, you can roll back to the previous version of VS Code for now.
