### ISSUE TITLE
syntax highlight is dead after '@' keyword.

### ISSUE THREAD

**Issue by sassembla** [OmniSharp/omnisharp-vscode#1288]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003148)

Product Information:
 Version:            1.0.0-preview2-003148
 Commit SHA-1 hash:  18ca244551

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version:version 1.10.1 (1.10.1)
C# Extension version:1.7.0

## Steps to reproduce
use '@' character as field name like below.

```
public class SampleClass {
    public int MyInt;

    public int @class;// syntax highlight is disabled from @class.

    public double MyDouble;

    public void SomeMethod () {        
        var str = "";// syntax highlight is back!
    }
}
```

<img width="536" alt="2017-03-05 18 17 30" src="https://cloud.githubusercontent.com/assets/944441/23586059/d1ab6922-01d0-11e7-9d45-34f438f25581.png">

## Expected  behavior
syntax highlight is alive.

## Actual behavior
syntax highlight is dead after '@' keyword.

**Comment by DustinCampbell** [comment]
This issue was moved to dotnet/csharp-tmLanguage#46

**Comment by DustinCampbell** [comment]
Moving this over to the csharp-tmLanguage repo where the syntax highlighting grammar lives.
