### ISSUE TITLE
Indentation style ignored in C# files

### ISSUE THREAD

**Issue by dylanparry** [OmniSharp/omnisharp-vscode#1290]
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  d881d45b75

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
```

VS Code version: 1.10.1
C# Extension version: 1.7.0

## Steps to reproduce

Set following options:

```json
{
  "editor.tabSize": 2,
  "editor.insertSpaces": true,
}
```

Right-click in `.cs` file and choose "Format Document", or set to auto-format on save and save the file.

## Expected  behavior

Code should be formatted like this:

```csharp
using Xunit;

namespace Example
{
  public class Tests
  {
    [Fact]
    public void Test1()
    {
      Assert.True(true);
    }
  }
}
```

Where code blocks are indented by two spaces.

## Actual behavior

Code is actually formatted like this:

```csharp
using Xunit;

namespace Example
{
    public class Tests
    {
        [Fact]
        public void Test1()
        {
            Assert.True(true);
        }
    }
}
```

The indentation settings have been ignored, and the code has been formatted using four-space indentation as per the default settings.

Here's a screenshot of my editor:

![image](https://cloud.githubusercontent.com/assets/3692873/23618498/641079f8-0288-11e7-93cc-1c27ca49b3d5.png)

Notice how the bottom of the editor clearly states "Spaces: 2" for the indentation settings. This appears to make no difference at all.

It would appear that the settings are always being used from the defaults rather than the user-defined settings, which are supposed to overwrite them. Is that the case?

**Comment by filipw** [comment]
@dylanparry OmniSharp will correctly import C# formatting settings from your user settings since version 1.7.0.
However, at the moment Omnisharp doesn't detect changes to settings in real time - if you change the default VS Code settings to, as you mentioned:

```
{
  "editor.tabSize": 2,
  "editor.insertSpaces": true,
}
```

you need to restart Omnisharp to have it pick up your changes. 
This would happen on VS Code restart or by pressing `CMD+shift+p` (`ctrl+shift+p` on Windows) and selecting `Restart OmniSharp` command.

**Comment by dylanparry** [comment]
Hi, thanks for that. It does seem to have worked. Pretty sure I'd tried that already, but it seems to work now. Thanks.

**Comment by filipw** [comment]
thanks - FWIW, there is an open issue tracking an improvement to the current behavior (https://github.com/OmniSharp/omnisharp-roslyn/issues/366) - to make Omnisharp pick up these changes without a need to restart
