### ISSUE TITLE
Generates wrong ${command.pickProcess} for .NET Core project 

### ISSUE THREAD

**Issue by cateyes99** [OmniSharp/omnisharp-vscode#1291]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```
VS Code version: 1.10.1
C# Extension version: 1.7.0

## Steps to reproduce
1. create a .net core project by running the command `dotnet new console`
2. In `Show Debug` window, click `Add Configuration...`, in the drop-down list select `.NET Core`
3. In the newly generated `launch.json` file, check `"processId": "${command.pickProcess}"` which should be `"processId": "${command:pickProcess}"`

**Comment by gregg-miskelly** [comment]
@cateyes99 Thanks for the report. This has already been fixed in the latest beta. See https://github.com/OmniSharp/omnisharp-vscode/issues/1275
