### ISSUE TITLE
Debugger: Ctrl-C is not correctly handled in 1.8-beta2

### ISSUE THREAD

**Issue by ClaireKang** [OmniSharp/omnisharp-vscode#1293]
## Environment data
`dotnet --info` output:
VS Code version: 1.10.1
C# Extension version: v1.8.0-beta2(https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.8.0-beta2)
.NET Core SDK: 1.0.0-preview2-1-003177
OS: centos7

## Steps to reproduce
1. Open attached folder with VSCode.
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/823572/hwapp.zip)
2. Update "console" configuration in launch.json file as following: 
    "console":"externalTerminal",
3. Press F5 to start debugging.
4. Press Ctrl+C to shut down in externalTerminal window.

## Expected  behavior
Stop debugging without any error.

## Actual behavior
1. Pop up an error following the pic:
![error](https://cloud.githubusercontent.com/assets/20184768/23645257/301cb116-0346-11e7-9d8e-83871a0f7a71.PNG)
2. Print 'vsdbg exited unexpectedly' on Debug Console Window.

## Investigation
1. This issue occured all Linux OS and Mac that we tested. (eg: centos7 /linuxmint17 /opensuse13.2 /debian /Zorin)
2. The cursor hit the loop after step #4 on Windows.
3. Some OS only print 'vsdbg exited unexpectedly' on Debug Console Window after step #4, and the state of UI still running, but pop up the error message when you stop debugging or pause.
4. This issue also reproduce when update "console" configuration in launch.json file as following: 
    "console":"integratedTerminal",

**Comment by gregg-miskelly** [comment]
NOTE: As far as I can tell this isn't solvable on OSX for the scenario of closing the terminal. Otherwise I believe I have this fixed.

**Comment by gregg-miskelly** [comment]
This issue is fixed (excluding the one osx case that I mentioned). It will be available in the next release of 1.8.

**Comment by ClaireKang** [comment]
Ok, Got it. Thanks. I will do the validation it while the next release of 1.8 is update.
