### ISSUE TITLE
can't set the value of a string if it includes an escaped bracket (\[)

### ISSUE THREAD

**Issue by JamesWTruher** [OmniSharp/omnisharp-vscode#1294]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview3-003716)

Product Information:
 Version:        1.0.0-preview3-003716
 Commit SHA-1 hash: bbf9fe92cf

Runtime Environment:
 OS Name: ubuntu
 OS Version: 16.04
 OS Platform: Linux
 RID: ubuntu.16.04-x64

VS Code version: 1.10.1
C# Extension version: 1.7.0

## Steps to reproduce
![codeescapebracket](https://cloud.githubusercontent.com/assets/10214008/23672169/a70f1008-0322-11e7-8b6a-3211a838dd9d.jpg)

set the value of a string to `file\[wc\].txt` whilst debugging

## Expected  behavior
I can set the value of the string 

## Actual behavior
got an error message `Unrecognized escape sequence`

**Comment by gregg-miskelly** [comment]
@JamesWTruher this is 'by design'. Typeing in expressions in the debugger is just like typing it into the source file. Your expression isn't valid C#. You need to escape those back slashes. So you want `file\\[wc\\].txt`.

**Comment by JamesWTruher** [comment]
thanks
