### ISSUE TITLE
c# anonymous type breaks syntax highlight

### ISSUE THREAD

**Issue by rakkarage** [OmniSharp/omnisharp-vscode#1295]
c# disabled:
![2017-03-07 5](https://cloud.githubusercontent.com/assets/962340/23690599/e7c990b4-0390-11e7-80f3-5bf525676cba.png)

c# enabled:
![2017-03-07 7](https://cloud.githubusercontent.com/assets/962340/23690656/6e6919be-0391-11e7-91b1-ae7aa2d7317d.png)

and combined with a custom theme (https://marketplace.visualstudio.com/items?itemName=henrysoftware.theme-rage) equals:
![2017-03-07 2](https://cloud.githubusercontent.com/assets/962340/23690615/09a4710e-0391-11e7-8746-29abb5f963c1.png)

**Comment by DustinCampbell** [comment]
This issue was moved to dotnet/csharp-tmLanguage#47
