### ISSUE TITLE
Debugger:Incorrent breakpoint information dispaly on breakpoints window

### ISSUE THREAD

**Issue by v-sjian** [OmniSharp/omnisharp-vscode#1296]
## Environment data
Server machine:
    OS: centos7
   .NET Core SDK:1.0.1
   CLRDBG: https://aka.ms/getclrdbgsh 
Client machine: 
    OS:win10 x64
    VS: VS Enterprise 2015
## Steps to reproduce
1.open the hwapp(program.cs) file on Client machine VS
2.set a breakpoint on a line
3.Run command: **Debug.MIDebugLaunch /Executable:dotnet /OptionsFile:C:\Users\v-sjian.FAREAST\Desktop\lanuch.xml** on Command Window
3. Verify the breakpoints window information when hit the breakpoint need to
## Expected  behavior
There is only one hit message  and currently  value should be 1 on breakpoints window
## Actual behavior
There are several hits message and currently value is still 0 on breakpoints window.

**Comment by gregg-miskelly** [comment]
@v-sjian thanks for the report. This is really an issue with the MIEngine. We already have a really similar bug over there, and I don't think it makes sense to implement one part without the other, so I will consider this part of https://github.com/Microsoft/MIEngine/issues/472.
