### ISSUE TITLE
Debugger: Remove breakpoint is invalid in the case of lanuch 

### ISSUE THREAD

**Issue by qian6** [OmniSharp/omnisharp-vscode#1297]
## Environment data
`dotnet --info` output:
VS Code version: 1.10.1
C# Extension version: v1.8.0-beta2
OS: Win10 RS2 
 Build: [\\winbuilds\release\RS_ONECORE_BASE_BPT1\15150.1000.170305-1700\amd64fre\vhdx\vhdx_client_enterprise_en-us_vl\15150.1000.AMD64FRE.RS_ONECORE_BASE_BPT1.170305-1700_CLIENT_ENTERPRISE_EN-US_VL.VHDX ](\\winbuilds\release\RS_ONECORE_BASE_BPT1\15150.1000.170305-1700\amd64fre\vhdx\vhdx_client_enterprise_en-us_vl\15150.1000.AMD64FRE.RS_ONECORE_BASE_BPT1.170305-1700_CLIENT_ENTERPRISE_EN-US_VL.VHDX )
 Scenarios: WSL Pipe

## Steps to reproduce
1. Open hwapp folder in vscode .
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/827209/hwapp.zip)
2. Select “lanuch” configuration
3. Use command to run process.
4. Set a breakpoint at line of 11 in Program.cs and it hit breakpoint.
5. Remove breakpoint and press continue.

## Expected  behavior
It should in running mode.

## Actual behavior
It is in break mode.

## Investigation
**This issue can repro in the case of attach.**

**Comment by qian6** [comment]
The issue reproduce on following scenario:
1.Add a for loop as bellow:  
 for(int a=0;a<1000;a++)
{
    Console.WriteLine("hello"); // Run to cursor here
}
2.F5.
3.Right click the vs , choose the "Run to cursor" on the line which contains text " Console.WriteLine("hello"); "
4.F5.

[Expected]
Vs would not stop at line which contains text " Console.WriteLine("hello"); "                                     
[Actual]
Vs stopped at the line which contains text " Console.WriteLine("hello"); "

**Comment by rajkumar42** [comment]
Should be available with https://github.com/Microsoft/vscode/milestone/37 release of VSCode.
