### ISSUE TITLE
Debugger: [Remote] Unexpected VSDBG output from command "-target-attach".

### ISSUE THREAD

**Issue by qian6** [OmniSharp/omnisharp-vscode#1304]
## Environment data
Server:
VS Code version: 1.10.2
C# Extension version: 1.0.1
CLRDBG:  https://aka.ms/getvsdbgsh
Client :
OS:win10 x64
VS: vsucorediag (26308.0)

## Steps to reproduce
1. Open Program.cs in VS2017.
[Program.zip](https://github.com/OmniSharp/omnisharp-vscode/files/830611/Program.zip)
2. Set a breakpoint at line of 11 in Program.cs
3. Configuration attach.xml file as following.
**<PipeLaunchOptions xmlns="http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014"
  PipePath="C:\Users\v-wqian\Downloads\plink.exe" PipeArguments="-i C:\Users\v-wqian\Documents\puttykey.ppk qian@172.18.4.15 -batch -t ~/vsdbg/vsdbg --interpreter=mi"
  TargetArchitecture="x64" MIMode="vsdbg">
  <CustomLaunchSetupCommands>
    <Command>-target-attach 18741</Command>
  </CustomLaunchSetupCommands>
 <LaunchCompleteCommand>None</LaunchCompleteCommand>
</PipeLaunchOptions>**
4. Run a process in server machine
5. Modify attach id in attach.xml file
4. Run command: 
Debug.MIDebugLaunch /Executable:dotnet /OptionsFile:<path-to-the-xml-file-you-saved>

## Expected  behavior
It should hit the breakpoint.

## Actual behavior
It has an error message as following:
![capture](https://cloud.githubusercontent.com/assets/20922638/23747989/b6a9d21a-04fc-11e7-9df8-c145f3f71bb1.PNG)

##Investigation
1. It works fine while launch process.
2. Could you please help me check if the configuration attach.xml  file is correct?

**Comment by rajkumar42** [comment]
Please use the ProcessId parameter instead of -target-attach.

<?xml version="1.0" encoding="utf-8" ?>
<LocalLaunchOptions xmlns="http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014"
  ExePath="dotnet" ExeArguments="c:\temp\app7\bin\Debug\netcoreapp1.0\app7.dll"
  MIMode="vsdbg" WorkingDirectory="c:\temp\app7" MIDebuggerPath="c:\vsdbg\vsdbg.exe" ProcessId="13656" >
</LocalLaunchOptions>
