### ISSUE TITLE
Debugging test doesn't use environment variables

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-vscode#1305]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

```
VS Code version: 1.10.2
C# Extension version:1.8-beta

## Steps to reproduce
Click `debug test` over a test
Environment variables are not taken into account

## Expected  behavior
Debugging test uses envvars

## Actual behavior
It doesn't use envvars. This can be seen here https://github.com/OmniSharp/omnisharp-vscode/blob/7faa070f33a89e7bba27362eb77a0e1caf00720f/src/features/dotnetTest.ts#L61

**Comment by gregg-miskelly** [comment]
@jchannon what environment variables are you expecting to get passed? The behavior that I would expect to see is that any environment variable present in the VS Code process would make it there. Any additional environment variables will not.

**Comment by jchannon** [comment]
Agree but doesn't seem to be the case.

In my .zshrc file I have various export lines but using C# to inspect env
vars they aren't present.

Due to .netcore and ssl nuances I have an export line to allow https
connections. In my test I make a https connection but it fails as this env
bar isn't picked up

**Comment by gregg-miskelly** [comment]
@jchannon this sounds like a VS Code issue then.

Do you see the same problem from tasks in tasks.json? (ex: add a task that checks for that environment variable)

If you have the problem there too, and you want to take it to the next level, there are a bunch of troubleshooting steps in https://github.com/Microsoft/vscode/issues/21655.

**Comment by jchannon** [comment]
how do you have a task to check envvars?

**Comment by gregg-miskelly** [comment]
Make a little program that calls `Console.WriteLine(Envirnoment.GetEnvironmentVariable("whatever-you-want"));`

**Comment by gregg-miskelly** [comment]
Or you could also attach the developer tools to VS Code and execute `process.env` (see the VS Code bug I referenced).

**Comment by jchannon** [comment]
The `Console.WriteLine` returns null yet if I do `echo $FOO` in my terminal it outputs the value

**Comment by gregg-miskelly** [comment]
@jchannon I believe this means that VS Code is having trouble fetching your environment variables from your shell at startup. Can you open an issue in https://github.com/microsoft/vscode/issues?

**Comment by jchannon** [comment]
Done, just put a link back to this

**Comment by gregg-miskelly** [comment]
Thanks!
