### ISSUE TITLE
Debugger will show threads as 'Paused' when they are running

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#1317]
## Environment data
`dotnet --info` output: 
- Version: 1.0.1
- OS Name: Ubuntu 
- OS Version: 16.04
- RID: Ubuntu.16.04-x64

VS Code version: 1.10.2
C# Extension version: v1.8.0

## Steps to reproduce
1. Create an app: 
- dotnet new mvc -o webtest
- cd webtest
- dotnet restore && dotnet build
2. Set a breakpoint at the line which contains text ‘ ViewData["Title"]="Home Page"; ’ in Index.cshtml.
3. Press F5 to start debugging
4. Press Continue

## Expected  behavior
The call stack frame seems like incorrectly.

## Actual behavior
When the breakpoint is hit, the call stack window as following:
![hitbp](https://cloud.githubusercontent.com/assets/20184778/23845442/1a77a57a-0803-11e7-82e5-a9cedf1e4689.PNG)
After press Continue, the call stack window as following:
![continue](https://cloud.githubusercontent.com/assets/20184778/23845496/76531762-0803-11e7-8b18-f786aea899ac.PNG)
After about 30 seconds, the call stack window as following:
![wait](https://cloud.githubusercontent.com/assets/20184778/23845658/612bbd7a-0804-11e7-8b4d-93bb6a65860e.PNG)
Is this expect? Could you please help me confirm it?

**Comment by gregg-miskelly** [comment]
@GraceDong to make sure I understand, the part you are asking about is that a bunch of threads are listed as 'Paused on breakpoint' when in fact they are NOT paused on a breakpoint. Is that correct?

**Comment by GraceDong** [comment]
Yes, and after 30 seconds, 1 paused thread and 2 running threads has exit, is this expect?

**Comment by gregg-miskelly** [comment]
@GraceDong the fact that a thread is listed as 'paused' is a bug. It is somewhat of a VS Code bug, but I will fix it on our side.

The fact that threads go away is just how the ASP.NET runtime works. Its expected.

**Comment by gregg-miskelly** [comment]
I checked in a fix for this for 1.9

**Comment by gregg-miskelly** [comment]
I have posted a new release of the C# extension that includes the fix. 

To try it -- use the use the [Installing Beta Releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) instructions to install [v1.9.0-beta2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.9.0-beta2).
