### ISSUE TITLE
Need a way to avoid quoting 'debuggerPath' when using pipe transport

### ISSUE THREAD

**Issue by weinand** [OmniSharp/omnisharp-vscode#1318]
_From @tanaka-takayoshi on March 13, 2017 9:7_

- VSCode Version:
 1.11.0-insider
- OS Version:
RHEL 7.3

Steps to Reproduce:
1. Generate launch.json to set up remote debug configuration.

```
{
  "version": "0.2.0",
  "configurations": [        
    {
        "name": ".NET Core Docker Remote Attach",
        "type": "coreclr",
        "request": "attach",
        "processId": "21",
        "pipeTransport": {
            "pipeProgram": "docler",
            "pipeArgs": [ "exec", "remotedebug-1-mispn"],
            "debuggerPath": "/opt/app-root/src/clrdbg/clrdbg",
            "pipeCwd": "${workspaceRoot}"
        },
        "sourceFileMap": {
            "/opt/app-root/src": "${workspaceRoot}"
        }
    }
  ]
}
```

2. Start debug ".NET Core Docker Remote Attach"

3. Failed to execute docker command. This is because VS Code escape the debuggerPath with parameters.
```
"docker" exec remotedebug-1-mispn "/opt/app-root/src/clrdbg/clrdbg --interpreter=mi"
```

The docker command recognizes "/opt/app-root/src/clrdbg/clrdbg --interpreter=mi" as one file path, then failed. I'm not sure which version, but the previous version (maybe 1.10.x-insider or 1.9.x-insider) VS Code didn't escape with option but not escaped like below.
```
"docker" exec remotedebug-1-mispn /opt/app-root/src/clrdbg/clrdbg --interpreter=mi
```

I submitted to StackOverflow as a question. But, I found this issue occurred with not only "oc (OpenShit CLI)" command but also "docker" command. So I decided to submit this issue as a bug.
http://stackoverflow.com/questions/42731558/how-not-to-escape-debuggerpath-of-pipetransport-in-launch-json

This issue prevents me from executing remote debug from VS Code to docker.

_Copied from original issue: Microsoft/vscode#22514_

**Comment by weinand** [comment]
@tanaka-takayoshi please file .NET related issues against https://github.com/OmniSharp/omnisharp-vscode/issues

**Comment by gregg-miskelly** [comment]
@tanaka-takayoshi this change was intentional as we had to deal with other transports that needed the other quoting behavior, and we wanted to be able to support scripts and pass though as many command line args as we needed. 

That said, I can definitely see the need for this. So we will need some new syntax for dealing with pipe programs that don't want quotes. My immediate thought is to allow `pipeArgs` to also be a string (instead of an array of strings) so that one can fully specify any quotes (or lack of quotes) that one wants. Though if anyone has a better idea I am all ears.

**Comment by gregg-miskelly** [comment]
@rajkumar42 had the alternate suggestion of adding a new Boolean property to disable all argument quoting. Something like: `"quoteArgs":false`.

@tanaka-takayoshi until we fix this, I believe you can work around the issue with --

        pipeProgram = "bash",
        pipeArgs = [ "-c", "docker exec -i remotedebug-1-mispn ${debuggerCommand}" ],

Or on Windows with:
                "pipeProgram": "C:\\windows\\system32\\cmd.exe",
                "pipeArgs": [ "/c", "docker.exe exec -i 3a8fd27f5878 ${debuggerCommand}"],

Note that in our testing, at least on Windows, we needed to also add `-i` (Keep STDIN open even if not attached) to the docker command line.

**Comment by tanaka-takayoshi** [comment]
@gregg-miskelly Thanks for your workaround! It works well for me.

**Comment by gregg-miskelly** [comment]
If anyone wants to try the fix, I have posted a new release of the C# extension that includes it. 

To try it -- use the use the [Installing Beta Releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) instructions to install [v1.9.0-beta2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.9.0-beta2).
