### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by sushilbaid** [OmniSharp/omnisharp-vscode#132]
1) dotnet download and demo is really quick and took order of 10 min as told on http://dotnet.github.io/getting-started/
2) Link (https://github.com/OmniSharp/omnisharp-vscode/blob/dev/template-tasks.json) on the page 
http://aka.ms/vscclrdebugger (https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md) seems to be broken.
3) mono download takes long time to download (16 min and still at 14%)

**Comment by DustinCampbell** [comment]
Hi @sushilbaid, thanks very much for your feedback!

1. Glad to hear this worked well for you.
2. Yes we removed template-tasks.json for the next release. Try the one in master here: https://github.com/OmniSharp/omnisharp-vscode/blob/master/template-tasks.json.
3. Your Mono download *does* seem long, but you'll need to chat with the Mono folks about that.
