### ISSUE TITLE
Highlight unused variables in the editor

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-vscode#1324]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

```
VS Code version: 1.10.2
C# Extension version:1.8.0

## Steps to reproduce
Create a variable and assign it a value. Don't use that variable.

## Expected  behavior
A highlighted or slightly greyed out variable name

## Actual behavior
Nothing

**Comment by DustinCampbell** [comment]
@Pilchie: Is there an equivalent request for roslyn?

**Comment by Pilchie** [comment]
No - the compiler already issues a warning, so there should be a squiggle (maybe not if it's initialized to an expression that might have side-effects though).

We did just take a PR to support a code fix to remove unused variables with that warning though.

**Comment by DustinCampbell** [comment]
That's what I was thinking. Also, we don't have the ability to fade things out in VS Code. FWIW, it'd be great if Roslyn marked that particular diagnostic with an Unnecessary tag. Any chance we could get @cyrusnajmabadi to do that? :smile:

**Comment by jchannon** [comment]
👀

**Comment by blogcraft** [comment]
I have this line in C#:

            List<IndicadorConFecha> indicadores = await _tipoCambio.GetIndicadores(desde, hasta);

The variable `indicadores` that gets asigned by an asyncronous method. But never gets used.

Why I don't get a warning or a squiggle?

**Comment by cartermp** [comment]
This should light up once analyzers are moved over to the .NET SDK

**Comment by marcospgp** [comment]
Any ETA on this? Thanks guys!

**Comment by suadev** [comment]
knock knock

**Comment by CyrusNajmabadi** [comment]
I don't believe there's been any progress on this.  I imagine a PR would be accepted to enable that behavior if someone wanted to contribute it.

**Comment by cartermp** [comment]
@CyrusNajmabadi See here :) https://github.com/OmniSharp/omnisharp-vscode/pull/3733
