### ISSUE TITLE
[ERROR:OmniSharp#ProjectFileInfo] The target "ResolveReferences" does not exist in the project.

### ISSUE THREAD

**Issue by psoszynski** [OmniSharp/omnisharp-vscode#1325]
## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

VS Code version: 1.10.2

C# Extension version:

## Steps to reproduce

In cmd:
dotnet new console
dotnet restore
code .
open output window

## Expected  behavior
No error

## Actual behavior
Starting OmniSharp server at 14.3.2017, 19.25.51
    Target: c:\Users\psoszyns\programming\test

OmniSharp server started
    Path: C:\Users\psoszyns\.vscode\extensions\ms-vscode.csharp-1.6.0-beta2\bin\omnisharp\OmniSharp.exe
    PID: 25172

OmniSharp: -s c:\Users\psoszyns\programming\test --hostPID 25664 --stdio DotNet:enablePackageRestore=false --encoding utf-8
[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location 'c:\Users\psoszyns\programming\test' on host 25664.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in c:\Users\psoszyns\programming\test
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp#MSBuild] No solution files found in 'c:\Users\psoszyns\programming\test'
[INFORMATION:OmniSharp#ProjectFileInfo] Using tools version: 15.0
[ERROR:OmniSharp#ProjectFileInfo] The target "ResolveReferences" does not exist in the project.
[WARNING:OmniSharp#MSBuild] Failed to process project file 'c:\Users\psoszyns\programming\test\test.csproj'.
c:\Users\psoszyns\programming\test\test.csproj

[INFORMATION:OmniSharp.Startup] Configuration finished.

I tried running restore from Visual Studio Code but got error: "No .NET Core projects found".

dotnet restore was ok from cmd though.

**Comment by filipw** [comment]
your C# extension is at version `ms-vscode.csharp-1.6.0-beta2`, can you update to the latest (`1.8.0`) and check again?

**Comment by psoszynski** [comment]
That's better now :)

But, now I have a different problem. I run, then update the value for "program" in launch.json to:

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/bin/Debug/netcoreapp1.1/test.dll>",
            "args": [],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "console": "internalConsole"
        },
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/bin/Debug/<target-framework>/<project-name.dll>",
            "args": [],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceRoot}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}

run again, add tasks.json, and after I run again I get the following error: 

"launch: program 'c:\Users\psoszyns\programming\test\bin\Debug\netcoreapp1.1\test.dll>' does not exist."

But it does exist:

C:\Users\psoszyns\programming\test
λ dir
 Volume in drive C has no label.
 Volume Serial Number is BCEC-471F

 Directory of C:\Users\psoszyns\programming\test

14.03.2017  19:54    <DIR>          .
14.03.2017  19:54    <DIR>          ..
14.03.2017  19:54    <DIR>          .vscode
14.03.2017  19:40    <DIR>          bin
14.03.2017  19:40    <DIR>          obj
14.03.2017  19:04               174 Program.cs
14.03.2017  19:04               170 test.csproj

C:\Users\psoszyns\programming\test
λ tree /f /a
Folder PATH listing
Volume serial number is 00000012 BCEC:471F
C:.
|   Program.cs
|   test.csproj
|
+---.vscode
|       launch.json
|       tasks.json
|
+---bin
|   \---Debug
|       \---netcoreapp1.1
|               test.deps.json
|               test.dll
|               test.pdb
|               test.runtimeconfig.dev.json
|               test.runtimeconfig.json

Any idea?

**Comment by gregg-miskelly** [comment]
@psoszynski You have a trailing '>' in your program path.

**Comment by psoszynski** [comment]
The previous error was probably because I was continuing working on an existing project.

Startet from scratch, dotnet new console, dotnet restore, code ., opened program.cs, accepted to add project files, launch.json already had proper values!.

F5 OK!

Thanks
