### ISSUE TITLE
Adjust namespaces

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-vscode#1329]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004771

```
VS Code version:1.10.2
C# Extension version:1.8.0

## Steps to reproduce
Have a class under a folder/namespace. Move the class to a different folder

## Expected  behavior
Option to adjust the namespace in the class to the correct namespace based on its new location. I believe R# has this.

## Actual behavior
None

**Comment by DustinCampbell** [comment]
@Pilchie? Do we have a request for Roslyn already?

**Comment by Pilchie** [comment]
I know I've heard @kuhlenh mention it, but I don't think it's actually tracked on Roslyn right now.

**Comment by DustinCampbell** [comment]
OK. This is tracked on Roslyn here: https://github.com/dotnet/roslyn/issues/14341. Once it's in Roslyn, we can get it into C# for VS Code.
