### ISSUE TITLE
C# editor insert space when autoformat instead of tab

### ISSUE THREAD

**Issue by egamma** [OmniSharp/omnisharp-vscode#133]
_From @Thaina on March 29, 2016 5:59_

I already set a setting as `"editor.insertSpaces": false,`

But when I trigger autoformat,type } to close block for example, all tab in that block was convert into 4 space

This only happen to C#

_Copied from original issue: Microsoft/vscode#4729_

**Comment by DustinCampbell** [comment]
This is a duplicate of #93
