### ISSUE TITLE
Too many restore prompts are hard to dismiss

### ISSUE THREAD

**Issue by natemcmaster** [OmniSharp/omnisharp-vscode#1330]
## Environment data
`dotnet --info` output: 1.0.1, Windows
VS Code version: 1.1.0.2
C# Extension version: 1.8.0

## Steps to reproduce
Open a clean, unrestored project with lots of csproj files. Example:
git clone https://github.com/aspnet/Entropy
Open Entropy folder 
Open any *.cs file to trigger OmniSharp load

## Expected  behavior
There should be some way to dismiss all "restore" prompts, or suppress them from showing.

Even better, it would be nice to condense to prompting to restore the solution file, or a condensed restore operation that does "Restore all".

## Actual behavior
The restore prompt obscures tabs and buttons in the activity bars, like the Git or Debug bar. **You have to dismiss them to use any of those buttons.**

VS Code only shows max of 5 prompts, but in reality there will be on for every csproj + 1 for the "Required assets to debug" prompt.

![image](https://cloud.githubusercontent.com/assets/2696087/24022868/1eeb1410-0a66-11e7-9413-1a5933d188a6.png)

Also, it's really annoying that as I'm rapidly clicking "Close" on the restore prompts, I almost always accidentally also click "Yes" on the "required assets" prompt. 

![image](https://cloud.githubusercontent.com/assets/2696087/24023043/01df8f8a-0a67-11e7-9e7e-0814f7002efc.png)

**Comment by cateyes99** [comment]
You can just press the `esc` key to dismiss all of them :)

**Comment by natemcmaster** [comment]
Thanks @cateyes99! Wish I had found that sooner.
