### ISSUE TITLE
Debugger fails to launch if project contains 'dotnet' folder

### ISSUE THREAD

**Issue by lutzroeder** [OmniSharp/omnisharp-vscode#1336]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.1)
Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

VS Code version: 1.10.2

C# Extension version: 1.8.0

## Steps to reproduce
1) Create new console project (dotnet new console)
2) Load into VS, add Launch.json etc.
3) Launch debugger (F5) ... succeeds
4) Add a folder named 'dotnet' into the project root
5) Launch debugger

## Expected  behavior
Debugger launches

## Actual behavior
Debugger shows an error: "The filename, directory name, or volume label syntax is incorrect."

**Comment by gregg-miskelly** [comment]
I am in this code now anyway, I will see if I can fix it real quick.

**Comment by gregg-miskelly** [comment]
This will be fixed in 1.9
