### ISSUE TITLE
C# IntelliSense problem

### ISSUE THREAD

**Issue by nomenon** [OmniSharp/omnisharp-vscode#1337]
.NET Command Line Tools (1.0.0-preview2-003133)
Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
VS Code version: 1.10.2
C# Extension version: 1.8
How to fix this? Width block or smth
![default](https://cloud.githubusercontent.com/assets/16668962/24147364/8568aeca-0e42-11e7-95af-cac507d15720.png)

**Comment by DustinCampbell** [comment]
Unfortunately, we don't have control over the actual hover tooltip UI from C# for VS Code. We just provide data and VS Code decides how to display it. It looks like there's a request for this on VS Code already: https://github.com/Microsoft/vscode/issues/14165.
