### ISSUE TITLE
[c#] Syntax highlighter not recognizing strings

### ISSUE THREAD

**Issue by egamma** [OmniSharp/omnisharp-vscode#134]
_From @jamesqo on March 29, 2016 0:46_

- VSCode Version: 0.10.11
- OS Version: Windows 10.0.10586

The VSCode editor sometimes doesn't recognize strings in C# source files, leading it to highlight code as strings and other strings as code. Here's an example of what I mean:

![vscode-grammar](https://cloud.githubusercontent.com/assets/9159214/14094590/b8c3bd8c-f525-11e5-8ecb-9ddcc714256f.PNG)

The source for the repro can be found here:

https://github.com/dotnet/corefx/blob/b55b8085528d0199bd14fb417d3b764e643b8533/src/System.Runtime.Extensions/tests/System/Runtime/Versioning/FrameworkName.cs

Since GitHub seems to be choking on this as well, I'll also be opening an issue in Atom's [C# grammar repo](https://github.com/atom/language-csharp), but I thought it would be good to let you guys know.

_Copied from original issue: Microsoft/vscode#4725_

**Comment by DustinCampbell** [comment]
I believe this is the same issue with syntax highlighting around string literal parameters as #89.

**Comment by vorov2** [comment]
This issue is still reproducible with the latest VSCode:

![image](https://cloud.githubusercontent.com/assets/10725688/19784351/835adc88-9ca6-11e6-8ed8-7558281b1925.png)

**Comment by DustinCampbell** [comment]
When version of the C# extension do you have installed?

**Comment by vorov2** [comment]
It is 1.4.1.
