### ISSUE TITLE
The preLaunchTask 'build' terminated with exit code 3221225506.

### ISSUE THREAD

**Issue by Xarkam** [OmniSharp/omnisharp-vscode#1340]
## Environment data
`dotnet --info` output:
```.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```
VS Code version: 1.10.2

Hello,

Does omnisharp support the pre-build and post-build in a csproj file?
A cli `dotnet build` works perfectly with prebuild.

My csproj:
```
<PropertyGroup>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
    <PreBuildEvent>mkdir "F:\Developpements\DevisChantier\DevisChantier\DevisChantier\Extensions"
xcopy /Y "F:\Developpements\DevisChantier\DevisChantier\UserManagment\bin\Debug\netcoreapp1.1\UserManagment.dll" "F:\Developpements\DevisChantier\DevisChantier\DevisChantier\Extensions"</PreBuildEvent>
  </PropertyGroup>
```

**Comment by gregg-miskelly** [comment]
@Xarkam this extension doesn't really have much of anything to do with build. The only thing we do is help craft a task.json file to invoke `dotnet build`.

Does the 'Tasks' output panel provide any more context as to what is failing?

**Comment by Xarkam** [comment]
Hello @gregg-miskelly 
No. There is my output
![image](https://cloud.githubusercontent.com/assets/331816/24371115/200af7b2-132a-11e7-8de4-f14217827ba3.png)
Just one file not found because my prebuildevent try to delete a non existant folder.

dotnet build take sln file (from vs2017) to build the solution project whitout any errors.
My solution contains two projet
![image](https://cloud.githubusercontent.com/assets/331816/24371656/cea9bc58-132b-11e7-8709-6e8ad350afa7.png)

**Comment by DustinCampbell** [comment]
@Xarkam: C# for VS Code doesn't control your build. It just creates a tasks.json file in the .vscode folder of your workspace which shells out to "dotnet build". It might be worth taking a look at that file to see if anything looks out of order.

**Comment by Xarkam** [comment]
I use simply the auto generated file [tasks.json]
```
"version": "0.1.0",
    "command": "dotnet",
    "isShellCommand": true,
    "args": [],
    "tasks": [
        {
            "taskName": "build",
            "args": [ ],
            "isBuildCommand": true,
            "showOutput": "silent",
            "problemMatcher": "$msCompile"
        }
    ]
```
Build from command line give me this output:
![image](https://cloud.githubusercontent.com/assets/331816/24449055/74db5078-1476-11e7-8ee4-5a5c767d007d.png)
And by vscode with tasks.json:
![image](https://cloud.githubusercontent.com/assets/331816/24449147/cc6598b2-1476-11e7-9dfb-456cadd0e23f.png)

**Comment by gregg-miskelly** [comment]
@Xarkam can you try temporarily changing your tasks.json to the following and tell us what error code you get? Also, can you give us a snippet of your msbuild task that is producing that 'File not found' message.

```json
{
    "version": "0.1.0",
    "command": "cmd",
    "isShellCommand": true,
    "args": [],
    "tasks": [
        {
            "suppressTaskName": true,
            "taskName": "build",
            "args": [
                "/c", "dotnet", "build", "${workspaceRoot}\\clicon.csproj", "&", "echo", "Error level is %ERRORLEVEL%"
            ],
            "isBuildCommand": true,
            "problemMatcher": "$msCompile"
        }
    ]
}
```

**Comment by Xarkam** [comment]
Ok, I discover that the prebuild event give the `file not found`.

And this highlights that the postbuild event on my csproj is not executed.
```
<PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <PreBuildEvent>rmdir /s /q "F:\Developpements\DevisChantiers\DevisChantiers\Extensions"
    </PreBuildEvent>
    <PostBuildEvent>mkdir "F:\Developpements\DevisChantiers\DevisChantiers\Extensions"
    xcopy /Y "F:\Developpements\DevisChantiers\UsersManagmentExt.Data.EntityFramework.Sqlite\bin\Debug\netcoreapp1.1\*.dll" "F:\Developpements\DevisChantiers\DevisChantiers\Extensions"
    xcopy /Y /D "F:\Developpements\DevisChantiers\UsersManagmentExtention\bin\Debug\netcoreapp1.1\*.dll" "F:\Developpements\DevisChantiers\DevisChantiers\Extensions"</PostBuildEvent>
  </PropertyGroup>
```
I would have seen the problem directly if I had had an information for the postbuild not executed
And I not understand why the post build event is not executed by command line while the prebuilt is executed

**Comment by gregg-miskelly** [comment]
@Xarkam Sorry, I am not quite sure I am following if you are running into a bug or not -- what was the exit code that was returned?

**Comment by Xarkam** [comment]
The code was returned is 0

**Comment by gregg-miskelly** [comment]
@Xarkam thanks. Unfortunately I can't repro your problem myself so I don't have a good way to troubleshoot. But this sounds like a VS Code issue if they are reporting the build failed even if it is exiting with code zero and doesn't look to be outputting any errors. Would you mind opening an issue at https://github.com/microsoft/vscode/issues so they can help you troubleshoot?

**Comment by Xarkam** [comment]
After analysis, the construction does not fail. The dlls are well built.
From what I understand, dotnet build runs the `<PreBuildEvent>` section of the csproj but does not run the `<PostBuildEvent>` section.

An error occurs because in my solution if the dependencies are not copied, then the application can not start

This is quite confusing because Visual Studio 2017 creates these sections of postbuild and prebuild.
And according to Microsoft's documentation, these sections must be used:
```
<Target Name="MyPreCompileTarget" BeforeTargets="Build">
  <Exec Command="generateCode.cmd" />
</Target>

<Target Name="MyPostCompileTarget" AfterTargets="Build">
 ...
</Target
```

I think there is a concern about the csproj file between visual studio 2017 and the documentation for use not with Visual Studio Code but the dotnet command line.

**Comment by gregg-miskelly** [comment]
@Xarkam in this case it sounds like we can close this issue. Does that sound right to you?

**Comment by Xarkam** [comment]
Yes.

I will wait for other returns and I will make further build attempts.
