### ISSUE TITLE
F5 doesn't work when focus is in editor

### ISSUE THREAD

**Issue by richlander** [OmniSharp/omnisharp-vscode#1341]
F5 doesn't work when focus is in the text editor. It does work when focus is elsewhere.

Finally figured out what was going on. This also repros for a node.js issue. I'm guessing that this is a VS Code issue, then?

Can you repro this?

/cc @DustinCampbell @gregg-miskelly

**Comment by DustinCampbell** [comment]
I've not seen this in the latest release of VS Code (1.10.2). I haven't tried VS Code Insiders though -- are you using that?

Yes, if it repros for node.js, it's probably a VS Code issue.

**Comment by DustinCampbell** [comment]
Or, it could be some other extension causing problems.

**Comment by richlander** [comment]
I only have 3 extensions installed: C#, Docker and Sublime (all from MSFT).

I am using 1.10.2.

**Comment by DustinCampbell** [comment]
Any chance you could share your project?

**Comment by richlander** [comment]
Sure, but I see the exact same thing with your project (this repo). Same thing with "dotnet new console". It doesn't seem to have anything to do with my project.

**Comment by richlander** [comment]
It is the Sublime Extension. If I uninstall that, everything works. Uninstalling the Docker one has no effect. Do you know where I'd file an issue on the Sublime extension?

**Comment by DustinCampbell** [comment]
Find the extension in the [marketplace](https://marketplace.visualstudio.com/vscode). There'll likely be a link for "Issues".

**Comment by DustinCampbell** [comment]
Note: If this is the Sublime Text Keymap extension, it's entirely possible that the extension remaps F5 to something more appropriate for Sublime. I.e. it could just be by design.

**Comment by richlander** [comment]
Could be. Didn't do anything obvious. That would still be a "choice". I'll find out.
