### ISSUE TITLE
Highlighting as in Xamarin

### ISSUE THREAD

**Issue by Avatarchik** [OmniSharp/omnisharp-vscode#1342]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Actual behavior
Is it possible to make code highlighting like in Xamarin?

**Comment by DustinCampbell** [comment]
Could you describe a little clearly what you mean? Properly filling out the template above with version numbers and any screenshots would be helpful for understanding what you are seeing and what you are looking for.

Syntax highlighting in VS Code is achieved via TextMate grammars, so we are limited in what we can do. C# for VS Code uses the official C# TextMate grammar from https://github.com/dotnet/csharp-tmLanguage.

**Comment by DustinCampbell** [comment]
@Avatarchik: Did you have more information for us to better understand your request?

**Comment by Avatarchik** [comment]
Hi! Here's how:
rider
https://monosnap.com/file/yUhub2yjJrJm7MNadywd6k9B85W9IP
xamarine
https://monosnap.com/file/l4KqyV5Z2ZfywviZdru7auLtLM4iBa

But as in the Vs Code, half the code is not highlighted ...
https://monosnap.com/file/eEI5NIEweFSkPcff49jnnXMMaBsK31

**Comment by DustinCampbell** [comment]
Considering your image, there are two issues that I see:

![image](https://cloud.githubusercontent.com/assets/116161/24468713/0439096c-146e-11e7-843b-17d95b44c153.png)

1. There's a bug in the C# TextMate grammar when a space appears between an identifier and a `(` in a dotted name. That should be colored as a method name but isn't today. That is easily fixed. This problem accounts for the first and third issues pointed to in the image.

2. The second issue pointed to the image requires semantic information to perform the highlight. However, VS Code only supports highlighting via regular expressions in a TextMate grammar. That means that there isn't currently a way to perform semantic highlighting, such as highlighting types and members differently. Fixing this requires a new API from VS Code to address.

I've filed https://github.com/dotnet/csharp-tmLanguage/issues/54 to track the first issue. The VS Code API needed to solve the second problem is tracked by https://github.com/Microsoft/vscode/issues/585.
