### ISSUE TITLE
Omnisharp as a Vala extension

### ISSUE THREAD

**Issue by GaZaTu** [OmniSharp/omnisharp-vscode#1343]
Hello
Not sure if this is the right place to ask but im gonna do it anyway. ;)
I want to use your project to get autocompletion for `Vala` projects.
The problem is that I don't really know how to change some things.
For example: I want to use the C# `delegate` syntax to make a Vala `signal`.
(A Vala signal is basically an event)

From: public delegate void some_event(string arg);
To: public signal void some_event(string arg);

It would be even better if I could make it visible in the autocompletion of an object.

How could I achieve this?

**Comment by GaZaTu** [comment]
Now that I think about it again its probably too hard to do. :/
But it would be a nice feature if I could disable syntax error messages
so my Vala code looks clean and still has the autocompletion.

**Comment by DustinCampbell** [comment]
Unfortunately, this really isn't something we can support. Using C# for VS Code to add support for a different language is going to be challenging without proper support in OmniSharp itself (https://github.com/OmniSharp/omnisharp-roslyn). And then, it'll be hard. Even though Vala is syntactically *similar* to C#, it is not C# and a lot of Vala code will appear as broken C# code to Roslyn.

**Comment by GaZaTu** [comment]
Ok thank you anyways
