### ISSUE TITLE
Problems panel not clearing problems from deleted file

### ISSUE THREAD

**Issue by elirnm** [OmniSharp/omnisharp-vscode#1344]
I'm reposting this from https://github.com/Microsoft/vscode/issues/23010 because https://github.com/Microsoft/vscode/issues/23010#issuecomment-288755175 thinks it might be a bug with this extension.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

VS Code version: 1.10.2
C# Extension version: 1.8.0

## Steps to reproduce
1. Create a file with errors.

2. Delete the file (through VS Code or Explorer, I've reproduced it with both).

3. See that the problems reported from that file are still showing in the problems pane.

## Expected  behavior
Problems are cleared when a file is deleted.

## Actual behavior
The problems panel is still showing problems for a file that has been deleted from disk.

![probs](https://cloud.githubusercontent.com/assets/19817004/24196030/52af5426-0eb9-11e7-8dbb-54758e2422f0.PNG)
![fis](https://cloud.githubusercontent.com/assets/19817004/24196037/5a3e256e-0eb9-11e7-9d4f-8afcaeb98ce3.PNG)

Notice that there's no test.cs in the second picture.

If I click on a problem to open the file I get a file not found error as expected.

![err](https://cloud.githubusercontent.com/assets/19817004/24196082/8c9fa97e-0eb9-11e7-801e-b484273daf70.PNG)

**Comment by DustinCampbell** [comment]
Definitely sounds like a bug with the extension. Thanks for reporting!

**Comment by akshita31** [comment]
`dotnet --info`
.NET Command Line Tools (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

VSCode Version : 1.19.0
C# Extension Version : 1.13.1

The bug doesn't reproduce on my system. Although there is an observable time lag after which the error disappear. Could you try updating the extension and see if it still reproduces ?

**Comment by akshita31** [comment]
@elirnm Any updates here ?

**Comment by elirnm** [comment]
@akshita31 I can't reproduce it anymore. It seems to be fixed.

**Comment by akshita31** [comment]
@elirnm I will close this for now. Feel free to reopen if you face the issue again.

**Comment by NarDd** [comment]
I am not sure if this is the same issue but I seem to reproduce the same error 
![image](https://user-images.githubusercontent.com/22251150/53063897-bdacc780-3500-11e9-96ad-059d4cf2d30c.png)

As you can see, the DataModels folder has been deleted however the errors still exist. I have tried cleaning and rebuilding using dotnet clean and dotnet build, but nothing is resolving this issue.

Using dotnet run, the project is able to be compiled and launch successfully.

**Comment by akshita31** [comment]
@NarDd Can you try `F1--> Restart OmniSharp` ?

**Comment by NarDd** [comment]
@akshita31 that works! Thank you 👍

**Comment by bernatgy** [comment]
I had the same problem... @akshita31 That solved it, thanks.
