### ISSUE TITLE
Respect path with spaces

### ISSUE THREAD

**Issue by liubko** [OmniSharp/omnisharp-vscode#1346]
## Environment data
`dotnet --info` output:
```
> dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```
VS Code version:
```
> code -v
1.10.2
8076a19fdcab7e1fc1707952d652f0bb6c6db331
```
C# Extension version:
```
1.8.0
```

## Steps to reproduce
I have `~/.vscode` folder symlinked to `~/.vscode -> /Users/liubko/Resilio Sync/dotfiles/.vscode`
Please notice the space in the folder's name.

## Expected  behavior
Respect path with space, and start OmniSharp

## Actual behavior
Can't start OmniSharp server because of the broken path.
![screen shot 2017-03-25 at 11 33 52 pm](https://cloud.githubusercontent.com/assets/4257937/24326313/56fd7e74-11b4-11e7-8750-78cb311cf1aa.png)

**Comment by DustinCampbell** [comment]
This is now fixed. Uninstalling and re-installing the extension should fix the issue.
