### ISSUE TITLE
Can't read from stdin in debug console

### ISSUE THREAD

**Issue by mitutee** [OmniSharp/omnisharp-vscode#1352]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
VS Code version: 1.10.2
C# Extension version: 1.8.0

## Steps to reproduce
Read from stdin (Console.ReadLine()) in DEBUG CONSOLE.

## Expected  behavior
Program reads from debug console input and pauses on breakpoints.

## Actual behavior
I cant do interactive debugging in this console. Input doesn't cause any effect. When program reaches point with reading from stdin, it just waits. Maybe, I didn't configured VS Code in a proper way?

**Comment by gregg-miskelly** [comment]
@mitutee the debug console is not intended to be used with applications that need to read from stdin. For such programs, set `console` to be `integratedTerminal' or 'externalTerminal'. GitHub's printing of markdown seems to not be working at the second, but for full documentation see https://github.com/OmniSharp/omnisharp-vscode/blob/release/debugger.md.
