### ISSUE TITLE
Error: Cannot start Omnisharp because Mono version >=4.0.1

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#1353]
_From @blopez2010 on March 29, 2017 5:15_

- VSCode Version: 1.10.2 (1.10.2)
- OS Version: macOS Sierra 10.12.3 (16D32)

Steps to Reproduce:

1. Install latest dotnet core cli.
1. Follow steps on https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-on-macos
1. Go to output and look for following error:

> [INFO] Starting OmniSharp at '/Users/blopez/Documents/CODEI/gitrepos/dotNetCore/tutorial/golden/golden.sln'...
[ERROR] Error: Cannot start Omnisharp because Mono version >=4.0.1 is required. See http://go.microsoft.com/fwlink/?linkID=534832#_20001

and this is what I got from vscode dev tools.

> shell.ts:426Cannot start Omnisharp because Mono version >=4.0.1 is required. See http://go.microsoft.com/fwlink/?linkID=534832#_20001: Error: Cannot start Omnisharp because Mono version >=4.0.1 is required. See http://go.microsoft.com/fwlink/?linkID=534832#_20001
    at /Users/blopez/.vscode/extensions/ms-vscode.omnisharp-0.3.3/out/omnisharpServerLauncher.js:59:24
    at process._tickCallback (internal/process/next_tick.js:103:7)

I have downloaded and installed that mono version several times from http://www.mono-project.com/download/#download-mac, close vscode and reopened, restarted my mac and same error message in vscode output.

![image](https://cloud.githubusercontent.com/assets/15872584/24439573/4eacc7a2-140c-11e7-8ac9-2a86b5c8fb8a.png)

Does anyone have this error too?

Thanks in advance.

_Copied from original issue: Microsoft/vscode#23517_

**Comment by DustinCampbell** [comment]
Hi -- it looks like you are using the old legacy OmniSharp extension installed, which is no longer supported. You should uninstall that extension and install the latest C# extension.

**Comment by blopez2010** [comment]
Thanks Dustin, 

Are you talking about this one?

https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

If it does, that is the one I'm using though.

Regards,

**Comment by DustinCampbell** [comment]
The detail you provided above indicates that is not the one being loaded. It's likely that you have both installed:

```
/Users/blopez/.vscode/extensions/ms-vscode.omnisharp-0.3.3/out/omnisharpServerLauncher.js:59:24
```

Remove ms-vscode.omnisharp and everything should work fine assuming you have the latest ms-vscode.csharp.

**Comment by blopez2010** [comment]
Thank you @DustinCampbell I didn't noticed I had the legacy extension installed... sorry to waste your time.

**Comment by DustinCampbell** [comment]
It wasn't a waste at all. Does that fix the problem for you?

**Comment by blopez2010** [comment]
Yes it did!! thanks man!

**Comment by DustinCampbell** [comment]
Excellent. Happy to help.
