### ISSUE TITLE
[1.9-beta2] Debugger: The debugger adapter crashed after click the [External Code] in Call Stack Window.

### ISSUE THREAD

**Issue by ClaireKang** [OmniSharp/omnisharp-vscode#1355]
## Environment data
`dotnet --info` output:
VS Code version: 1.10.2
C# Extension version: https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.9.0-beta2
.NET Core SDK: 1.0.1
OS: Win10 RS2 [rs2_release.15063.0.170317-1834]
Machine: [TEN14366](http://maddog/goto/MDGoto.Application?md://OrcasTS/Machine/655249)
Ip Address: 10.185.116.176

## Steps to reproduce
1. Open attached folder with VSCode 
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/881683/hwapp.zip)
2. Set a bp at the line of 10 in Program.cs.
3. Press F5 to start debugging.(Hit the bp at the line of 10)
4. Click the [External Code] frame in Call Stack Window.

## Expected  behavior
There is no any error or prompt message.

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/20184768/24498689/d43ee5ba-1571-11e7-9355-ebd2beec8b11.png)

**Comment by gregg-miskelly** [comment]
This issue will be fixed in the next 1.9 beta.
