### ISSUE TITLE
Debugger: Debug adapter crashed after closed external Terminal

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#1356]
## Environment data
VS Code version: 1.10.2
C# Extension version:  v1.9.0-beta2
.NET Core SDK: 1.0.1
OS: macOS Sierra v10.12.4

## Steps to reproduce
1.  Open attached folder with VSCode
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/881791/hwapp.zip)

2.  Update "console" configuration in launch.json as following:
          "console": "externalTerminal",
3. Set a breakpoint at the line of 9 in Program.cs
4. F5
5. Close the external Terminal

## Expected  behavior
The debugger worker process exited correctly.

## Actual behavior
The debugger worker process (vsdbg) exited unexpectedly and pop an error message as following:
![image](https://cloud.githubusercontent.com/assets/20184778/24498724/faf0ca3e-1571-11e7-8cf2-3e79992c5657.png)
## Investigation
If I press "Ctrl + C" to stop debugging in external Terminal, the application can exited correctly and no error message.

**Comment by gregg-miskelly** [comment]
There isn't much we can do about this I am afraid. When you close the terminal on OSX, OSX will terminate all processes running in that terminal immediately.
