### ISSUE TITLE
#define directives get reformatted on save

### ISSUE THREAD

**Issue by TheColorRed** [OmniSharp/omnisharp-vscode#1374]
- VSCode Version: 1.11.x
- OS Version: Windows 10

When writing code with `#define directives` like the following:

```c#
public MyClass {
    void MyMethod() {
        #if UNITY_ANDROID
            Vector3 target = Camera.main.ScreenToWorldPoint(Input.touches[0].position);
        #else
            Vector3 target = Camera.main.ScreenToWorldPoint(Input.mousePosition);
        #endif
    }
}
```

The code gets reformatted on save to look something like this:

```c#
public MyClass {
    void MyMethod() {
#if UNITY_ANDROID
            Vector3 target = Camera.main.ScreenToWorldPoint(Input.touches[0].position);
#else
            Vector3 target = Camera.main.ScreenToWorldPoint(Input.mousePosition);
#endif
    }
}
```

As you can see it moves it `#if`, `#else` and `#endif` all the way to the left hand side of the document.

**Comment by DustinCampbell** [comment]
Unfortunately, this is the default behavior for C# formatting in Roslyn and Visual Studio 2017. All preprocessor directives are formatted to the left. We would need to take a change in Roslyn to address this.

@Pilchie: Is there already a request on https://github.com/dotnet/roslyn for this behavior? It seems like there should be an option to control this formatting behavior.

**Comment by Pilchie** [comment]
https://github.com/dotnet/roslyn/issues/12306 tracks this feature request.

**Comment by DustinCampbell** [comment]
Thanks @Pilchie! @TheColorRed, feel free to track https://github.com/dotnet/roslyn/issues/12306 for a fix (or take a stab at yourself! :smile:). Once that happens and we update OmniSharp to use a newer version of Roslyn that has the fix, you'll be able to configure this in VS Code with an omnisharp.json file.

**Comment by TheColorRed** [comment]
Thanks! To bad that issue is almost a year old and no updates :(
