### ISSUE TITLE
Feature Request: Silverlight Support

### ISSUE THREAD

**Issue by aersamkull** [OmniSharp/omnisharp-vscode#1380]
Yes, I know, no body uses Silverlight anymore. But for those who do it would be really great to have support for it in VS Code especially as VS 2017 does not support Silverlight anymore.

**Comment by DustinCampbell** [comment]
Hi, I appreciate the request. Unfortunately, we can't prioritize having support for legacy technologies like Silverlight in C# for VS Code. I haven't tried one, but I would expect Silverlight projects to at least provide IntelliSense in VS Code. However, beyond that there isn't much we can do for VS Code.

**Comment by DustinCampbell** [comment]
I'd definitely be willing to take a bug report for that to see if something can be done. :smile: Could you provide a bit of information to help us investigate?

* What operating system are you running on?
* VS Code version:
* C# for VS Code version:
* Could you provide your OmniSharp Log after opening a Silverlight project? You can grab this by selecting View->Output from the menu and selecting OmniSharp Log from the dropdown at the top-right corner of the Output pane.

**Comment by aersamkull** [comment]
I get this error on Windows 10, VS Code  1.11.1:

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from 'e:\Code\D\FOOO.csproj'.
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The Silverlight 4 SDK is not installed.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to process project file 'e:\Code\D\FOO.csproj

However, I do have SL4 SDK installed. Do I have to set a path somewhere?

**Comment by DustinCampbell** [comment]
Is that the whole log?

**Comment by DustinCampbell** [comment]
Also, what version of C# for VS Code do you have installed?
