### ISSUE TITLE
Cant find the "Legacy C# Support" in vscode Marketplace. And C# 1.7.0 extension is not able to detect errors in the code.

### ISSUE THREAD

**Issue by rahul-sinha1908** [OmniSharp/omnisharp-vscode#1393]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     fedora
 OS Version:  23
 OS Platform: Linux
 RID:         fedora.23-x64

VS Code version: 1.7.2
C# Extension version: 1.7.0

## Steps to reproduce
I am using fedora and I can nowhere find the dotnet framework 2.0 for fedora. I have a dotnet framework v4.5 installed but since Unity3d works on framework 2.0, every time it generates .csproj file, which has the Target Framework as v2.0.
Because of this issue, my code completion of vscode stops to work. It starts working again only after I manually change the <TargetFramework> tag to v4.5. Is there any easier way of doing it?

Moreover, I reinstalled my VSCODE and now I cant even find the "Legacy C# support" on the vscode marketplace. So I installed "C#" (ms-vscode.csharp) plugin, but this plugin is not able to detect the errors in the code at all.

**Comment by DustinCampbell** [comment]
Legacy C# Support extension has been removed from the marketplace as it no longer functions properly. It was only left on the marketplace as a stop gap. The latest C# extension supports Unity development, so the Legacy C# Support extension has gone away.

Is it accurate that you only have VS Code version 1.7.2 and C# for VS Code 1.7.0? The reason I ask is because the latest version numbers for these are 1.11.2 and 1.8.1 respectively.

**Comment by rahul-sinha1908** [comment]
Thanks alot. I found out that I was using the outdated version, so updated it. But still, I cant find the dotnet Framework 2.0 for fedora. Everytime when Unity generates the .csproj file, I need to go to the .csproj file and change the tag TargetFrameworkVersion to v4.5(from v2.0) to make the code completion, error detection work properly.
Is there any easier way to set the things by default in VSCode or something like that.
I am sure that all the Unity developer using VSCode, might have faced the same issue.
Thanks in advance.

**Comment by DustinCampbell** [comment]
It should work. Do you have the latest Mono installed (e.g. 4.8.0)? What do you get when you enter `mono ---version` at a Terminal window?

**Comment by rahul-sinha1908** [comment]
It says - 
Mono JIT compiler version 4.2.4 (tarball Mon Sep 19 02:09:55 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen


The EPEL7 provides version 4.2.4  as the highest.
I also came across that we need to install mono-complete, referenceassemblies-pcl and ca-certificates-mono for proper functioning of the mono environment (http://www.mono-project.com/docs/getting-started/install/linux/#usage)
But I found out that epel7 doesnot provide mono-complete or other above mentioned packages. How or from where do I install those in my fedora-23 system?

**Comment by DustinCampbell** [comment]
Yes, mono-complete should handle the issue.

Fedora is a little bit behind WRT to Mono (see my comment in https://github.com/OmniSharp/omnisharp-vscode/issues/1213#issuecomment-279229392 where I helped work through a Fedora Mono issue).

**Comment by Leopotam** [comment]
@rahul-sinha1908, you can use target framework fix on unity side. For example, you can take 2 files ([this one](https://github.com/Leopotam/LeopotamGroupLibraryUnity/blob/develop/EditorHelpers/Editor/PatchTargetFramework.cs) and [this one](https://github.com/Leopotam/LeopotamGroupLibraryUnity/blob/develop/EditorHelpers/Editor/PostSolutionGenerationAttribute.cs) ) and put them at Editor folder of unity project, then add "DEV_FW46" as build preprocessor define. After force "Assets / Open C# Project" - csproj file will force use 4.6 as target framework.

**Comment by rahul-sinha1908** [comment]
@Leopotam Thanks alot. But I am beginner in this. Can you please explain me how to do this - "add "DEV_FW46" as build preprocessor define."

**Comment by Leopotam** [comment]
@rahul-sinha1908 [official docs](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html), "Platform custom #defines".

**Comment by DustinCampbell** [comment]
Hi! Just wanted to check in and see if this is still an issue.

**Comment by rahul-sinha1908** [comment]
@DustinCampbell @Leopotam Thanks a lot for your help. The issue is resolved. :)

**Comment by DustinCampbell** [comment]
Glad to hear it -- thanks!
