### ISSUE TITLE
current Linux distribution 'ubuntu' version '17.04' is not currently supported by the .NET Core debugger. Debugging will not be available.

### ISSUE THREAD

**Issue by alexrand** [OmniSharp/omnisharp-vscode#1394]
## Environment data

.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.04
 OS Platform: Linux
 RID:         ubuntu.16.10-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1

VS Code version:
C# Extension version:
1.8.1 (March 31, 2017)
## Steps to reproduce

hit f5 
## Expected  behavior

run 
## Actual behavior

output as title in log

**Comment by gregg-miskelly** [comment]
See https://github.com/OmniSharp/omnisharp-vscode/issues/1381
