### ISSUE TITLE
Respect <NoWarn> in .csproj

### ISSUE THREAD

**Issue by anfomin** [OmniSharp/omnisharp-vscode#1399]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```
VS Code version: 1.11.2
C# Extension version: 1.9.0-beta3

## Steps to reproduce

Create project with single class. In `.csproj` add line:
```xml
<NoWarn>$(NoWarn);CS1591;CS1573</NoWarn>
```

## Expected  behavior

There should be no warnings in "Problems" output.

## Actual behavior

![2017-04-18 18 01 08](https://cloud.githubusercontent.com/assets/1905503/25131918/08a6971e-2461-11e7-9db4-5b9812e4f5ab.png)

**Comment by anfomin** [comment]
This issue was fixed for `project.json` (https://github.com/OmniSharp/omnisharp-roslyn/pull/734), but new `.csproj` still does not respect nowarn.

**Comment by DustinCampbell** [comment]
OmniSharp does support NoWarn for csproj, it's just a little finicky about it. Don't include the "CS" -- just the raw numbers.

`<NoWarn>$(NoWarn);1591;1573</NoWarn>`

I've filed https://github.com/OmniSharp/omnisharp-roslyn/issues/826 to improve the support here. Thanks!

**Comment by anfomin** [comment]
@DustinCampbell thank you! It works!
