### ISSUE TITLE
OmniSharp on Debian 8.2 "Squeeze" can't resolve mscorlib

### ISSUE THREAD

**Issue by mezzodrinker** [OmniSharp/omnisharp-vscode#14]
I recently installed Visual Studio Code on my Debian 8.2 "Squeeze" laptop, along with Mono, DNVM, the .NET version that goes along with Mono (`dnx-mono.1.0.0-rc1-update1`) and their respective dependencies.

Now, whenever I start up a Unity C# project and open a C# file, OmniSharp marks basically everything as an error, as seen below:
![Screenshot of VS Code showing the (erroneous) syntax errors](http://puu.sh/mFh0j/9fadafe540.png)
On the right side, you can see the OmniSharp output, which reads:
```
[ERROR:OmniSharp.MSBuild.MSBuildProjectSystem] The predefined type [...] is not defined or imported
[...]
[WARNING:OmniSharp.MSBuild.MSBuildProjectSystem] Reference 'mscorlib' not resolved
```
I loaded the Unity project via a modified Unity C# solution/project which actually references `mscorlib` because that was what the Internet told me to do when I was confronting the "The predefined type [...] is not defined or imported" error.

What am I supposed to do so that OmniSharp is able to resolve/detect `mscorlib`?

The whole log, along with the used `.csproj` file, are located in the attachments. If you need any additional information, I'll be glad to provide it.

Kind regards.

***Attachments:***
* [complete OmniSharp log](https://github.com/OmniSharp/omnisharp-vscode/files/100792/omnisharp.txt)
* [used `.csproj` file](https://github.com/OmniSharp/omnisharp-vscode/files/100799/Assembly-CSharp.txt)

**Comment by lukas-123** [comment]
Try installling mono-reference-assemblies-* with your package manager. They are not installed automatically with mono-complete. This fixed the problem at least for me.

**Comment by DustinCampbell** [comment]
Sorry that this issue has grown so stale. I realize that the days of DNX and DNVM are behind us at this point, so that bit is probably not relevant any longer.

The latest release, [v1.3.0](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.3.0), brings back support for Unity to the C# extension. Does this version of the extension work better for you?

**Comment by DustinCampbell** [comment]
Closing this issue as it's not actionable at this point.
