### ISSUE TITLE
why the tip of method and parameters is Chinese garbled

### ISSUE THREAD

**Issue by alexandrudima** [OmniSharp/omnisharp-vscode#140]
Moved Microsoft/vscode#4950:

From @mrpengfei 

- VSCode Version:0.10.11
- OS Version:windows 10

Steps to Reproduce:
why the tip of method and parameters is Chinese garbled. 

1. 
![qq 20160405161945](https://cloud.githubusercontent.com/assets/5754718/14276360/12949f8a-fb51-11e5-8fac-4a940491a161.png)

2.

**Comment by DustinCampbell** [comment]
Could you provide some code that I can copy and paste as part of a repro?

**Comment by mrpengfei** [comment]
Thanks for your replay,
I open the project which is created by  visual studio 2013(chinese simple)
[ConsoleApplication1.zip](https://github.com/OmniSharp/omnisharp-vscode/files/207671/ConsoleApplication1.zip)

**Comment by DustinCampbell** [comment]
thanks! I'll take a look

**Comment by DustinCampbell** [comment]
I believe this will be fixed by https://github.com/OmniSharp/omnisharp-roslyn/pull/598.
