### ISSUE TITLE
Clean up profiles

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-vscode#1400]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

```
VS Code version:1.11.2
C# Extension version:1.8.1

## Steps to reproduce
Select all code in file or method

## Expected  behavior
Option to cleanup/tidy code based on a settings file like Resharper eg/ add `this` to variables etc etc

## Actual behavior
Nothing

**Comment by DustinCampbell** [comment]
We're planning this for C# generally in https://github.com/dotnet/roslyn/issues/8928. We'll be adding support for editorconfig files like VS 2017.

**Comment by DustinCampbell** [comment]
cc @Pilchie as well.

**Comment by jchannon** [comment]
How's that progressing? Its over a year since that was raised

**Comment by DustinCampbell** [comment]
Everything always seems to progress slowly, no matter how hard we work! :smile:

It's been a year because it's our own backlog item. That said, we're also tracking https://github.com/dotnet/roslyn/issues/7068 as current work.
