### ISSUE TITLE
Unit test 'debug test' button sometimes doesn't rebuild the test

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#1412]
## Environment data
OS: MacOS Sierra
C# Extension version: 1.9.0

## Notes
I reproduced this a few times in a row, but now I am no longer able to do so. Maybe a timing issue?

## Steps to reproduce

1: Create a new xunit test
2: Create a new test as follows:

```csharp 
        public void Test1()
        {
            Console.WriteLine("foo");
            Assert.False(true);
        }
 ```

3: Click the ‘run test’ button
4: Wait for it to fail
5: Change the `true` to `false` so that the test should succeed
6: Save the file and click ‘debug test’

## Expected  behavior
Test should now pass and the debugger should no longer stop on an exception.

## Actual behavior
Test still failed since it was still somehow running the old code.

**Comment by DustinCampbell** [comment]
This should be fixed now.
