### ISSUE TITLE
Debugger:Frame display incorrectly in call stack window 

### ISSUE THREAD

**Issue by qian6** [OmniSharp/omnisharp-vscode#1414]
## Environment data
`dotnet --info` output:
VS Code version: v1.11.2
C# Extension version: v1.9.0
SDK Version: 1.0.1

## Steps to reproduce

1. Open attached folder with VSCode.
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/946119/hwapp.zip)
2. Press F5 to start to debug.
3. Press Pause button.

## Expected  behavior
It can hit 13 line in Program.cs file. and call stack frame as following:
![capture](https://cloud.githubusercontent.com/assets/20922638/25264765/b1e306be-269b-11e7-9248-9db430ef4392.PNG)

## Actual behavior
Call Stack frame display incorrectly.
![capturesss](https://cloud.githubusercontent.com/assets/20922638/25264794/d907dee0-269b-11e7-99f0-68b75ff8fa47.PNG)

Log:
[log.txt](https://github.com/OmniSharp/omnisharp-vscode/files/946126/log.txt)

**Comment by gregg-miskelly** [comment]
This is a VS Code issue. This is very related to https://github.com/Microsoft/vscode/issues/25104, so I think I will just add details to that bug rather than opening a new one.

**Comment by gregg-miskelly** [comment]
Actually I take it back. They are certainly related, but different enough that it seems worth a separate bug. I will open something in the morning.

**Comment by qian6** [comment]
Ok, I Known ,Thank you very much!

**Comment by gregg-miskelly** [comment]
Issue moved to ttps://github.com/Microsoft/vscode/issues/25148
