### ISSUE TITLE
Debugger:It can not hit breakpoint when Debug test

### ISSUE THREAD

**Issue by qian6** [OmniSharp/omnisharp-vscode#1415]
## Environment data
`dotnet --info` output:
VS Code version: v1.11.2
 C# Extension version: v1.9.0
 SDK Version: 1.0.1

## Steps to reproduce

1. Open attached folder with VSCode.
[xunit-test.tar.gz](https://github.com/OmniSharp/omnisharp-vscode/files/946141/xunit-test.tar.gz)
2. Set a breakpoint at line of 11 in UnitTest1.cs file
3. Click "debug test"

## Expected  behavior
It should be hit breakpoint.

## Actual behavior
It can not hit breakpoint.

Log:[log.txt](https://github.com/OmniSharp/omnisharp-vscode/files/946158/log.txt)

**Comment by qian6** [comment]
When press "stop (Shift+F5)" button, and press "debug test" again ,It has error message as following: 
![capture111](https://cloud.githubusercontent.com/assets/20922638/25265599/70db56f8-26a0-11e7-94f6-8d11095e3909.PNG)
Log:
[log.txt](https://github.com/OmniSharp/omnisharp-vscode/files/946187/log.txt)

**Comment by DustinCampbell** [comment]
@GraceDong, @qian6: This one looks really similar to #1413. Are they the same?

**Comment by DustinCampbell** [comment]
Also, is it possible to capture the OmniSharp Log when this happens? You can get it by selecting View->Output in VS Code. Then, in the Output pane, select "OmniSharp Log" from the combobox in the top-right corner.

**Comment by DustinCampbell** [comment]
After reproducing #1413, I'm pretty confident these are the same issue.
