### ISSUE TITLE
dotnet restore fails when the .csproj name is xunit.csproj

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#1416]
## Environment data
`dotnet --info` output:

- `Product Information:`
- `Version: 1.0.1`
- `Commit SHA-1 hsah: 005db40cd1`
- `Runtime Environment:`
- `OS Name: fedora`
- `OS Version: 23`
- `OS Platform: Linux`
- `RID: fedora.23-x64`
- `Base Path: /opt/dotnet/sdk/1.0.1`

VS Code version: v1.11.2
C# Extension version: v1.9.0

## Steps to reproduce

1. Open Terminal
2. Create new console project as following:
- `mkdir xunit`
- `cd xunit`
- `dotnet new xunit`
- `dotnet restore`

## Expected  behavior
Restore package successfully.

## Actual behavior
Show some error message as following:
![image](https://cloud.githubusercontent.com/assets/20184778/25266312/516c0846-26a3-11e7-8913-dd5e362e8a77.png)
## Investigation
This issue repro on other platform. Could you please help me to confirm if it is expected?

**Comment by gregg-miskelly** [comment]
That is really weird. But it isn't anything to do with the debugger. Moving your issue to the CLI repo.

**Comment by gregg-miskelly** [comment]
This issue was moved to dotnet/cli#6374
