### ISSUE TITLE
.NET Core attach debugger template defaults to "processname" and the flydown says use "pid" 

### ISSUE THREAD

**Issue by jeffschwMSFT** [OmniSharp/omnisharp-vscode#142]
<img width="952" alt="screen shot 2016-04-05 at 11 09 50 am" src="https://cloud.githubusercontent.com/assets/9561583/14292952/313e9166-fb1f-11e5-88ef-d841b224322c.png">

When you try to debug attach a .NET Core application the default launch.json has "processname", but if you use "dotnet" it says it has found multiple and you need to use "pid".  But in reality you need to use "processId".  I recommend that we change the default template to replace "processName" with "processId" and update the fly down text to use "processId" instead of "pid".

**Comment by gregg-miskelly** [comment]
Sounds reasonable. @caslan @DustinCampbell anyone have an opinion as to if we should change this for RC2?

**Comment by DustinCampbell** [comment]
It'd be nice to make it work. :smile:

**Comment by caslan** [comment]
It's very low risk so I'm in favor of changing especially now running apps via dotnet ... is more common

**Comment by gregg-miskelly** [comment]
Yes, should be ~0 risk.

**Comment by gregg-miskelly** [comment]
@MattGertz are you okay taking this?

**Comment by MattGertz** [comment]
I'm OK but it will need an escrow check from Dmitry/JoC.

**Comment by MattGertz** [comment]
Talked with Gregg offline; I didn't realize that there was a distinct part from the error message change.  This won't meet an escrow bar; we can pick it up afterwards.

**Comment by DustinCampbell** [comment]
Sounds good. Anyway, there'll be interim releases available that we can point customers to afterward.

**Comment by caslan** [comment]
Fixed with https://github.com/OmniSharp/omnisharp-vscode/pull/197

**Comment by kerryjiang** [comment]
Was this issue fixed?
I tried the v1.0.5-rc2, it still stays there.

**Comment by DustinCampbell** [comment]
@kerryjiiang: It is fixed in the dev branch in our RTM milestone.
