### ISSUE TITLE
There is no intellisense for the referenced project from a test project

### ISSUE THREAD

**Issue by nozer** [OmniSharp/omnisharp-vscode#1420]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```
VS Code version: Version 1.11.2 (1.11.2) 6eaebe3b9c70406d67c97779468c324a7a95db0e

C# Extension version: 1.9.0 

## Steps to reproduce

1 - Create a new lib  via `dotnet new classlib` 
2 - Create a test project via `dotnet new xunit`
3 - Reference the lib # 1 from test project at # 2
4 - Open the test project on visual studio code by itself
5 - Try to use namespace / class etc from the lib in your test project

## Expected  behavior

Intellisense
## Actual behavior

No intellisense

**Comment by nozer** [comment]
If I open the parent directory that contains both the `lib` and `test` directories, that intellisense works fine. I will assume this is how it is intended to be done and close the issue.

**Comment by DustinCampbell** [comment]
That's right. I'm working on a fix for https://github.com/OmniSharp/omnisharp-vscode/issues/963 in 1.10 that should address this.
