### ISSUE TITLE
Error processing "configurationDone" request

### ISSUE THREAD

**Issue by alexandrudima** [OmniSharp/omnisharp-vscode#1431]
Moved from Microsoft/vscode#25333
From @bhkeys

---

- VSCode Version: 1.11
- OS Version: CentOS7

Steps to Reproduce:

1. Set up a .NET core project and install extension
2. Build the project
3. Try to debug it; you will get this error

![selection_001](https://cloud.githubusercontent.com/assets/28019043/25404798/3d5fe24e-29cf-11e7-8ff7-89d67f8e97c7.png)

```
{
   // Use IntelliSense to find out which attributes exist for C# debugging
   // Use hover for the description of the existing attributes
   // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
   "version": "0.2.0",
   "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceRoot}/bin/Debug/netcoreapp1.1/core.dll",
            "args": [],
            "cwd": "${workspaceRoot}",
            // For more information about the 'console' field, see https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#console-terminal-window
            "console": "internalConsole",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart"
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}
```

**Comment by gregg-miskelly** [comment]
@bhkeys do you have an official VS Code rpm from Microsoft installed? Or the OSS version?

**Comment by bhkeys** [comment]
The OSS version

**Comment by gregg-miskelly** [comment]
@bhkeys can you try the official version?

**Comment by bhkeys** [comment]
It works on the official version but not on the OSS version. However there should be support for the OSS version that way people can use vscode without being under the MS EULA

**Comment by gregg-miskelly** [comment]
The .NET Core debugger the C# extension uses is a component that is shared across Visual Studio, Visual Studio for Mac, and Visual Studio Code.  As such, it ships under a proprietary license that does not allow for it to be used with products other than the official Microsoft Visual Studio family (see https://github.com/OmniSharp/omnisharp-vscode/blob/master/RuntimeLicenses/license.txt and https://www.visualstudio.com/en-us/support/legal/mt644895).

**Comment by shaycraft** [comment]
This same thing is happening to me on the official version.

**Comment by mstarrrsui** [comment]
Same here.  On the official version.   

To replicate:

1. Set up a JavaScriptServices ASP.NET core project using "dotnet new angular"
2. install extension
3. Build the project
4. Try to debug it; you will get this error

**Comment by DustinCampbell** [comment]
This is a VS Code issue that slipped into 1.12. It's being tracked with https://github.com/OmniSharp/omnisharp-vscode/issues/1456.

**Comment by mstarrrsui** [comment]
FYI - I turned on logging and the issue appears to be this... 

`"(C) {"type":"response","seq":3,"command":"handshake","request_seq":2,"success":false,"message":"The module '\\\\?\\C:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\node_modules\\vsda\\build\\Release\\vsda_win32.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 50. This version of Node.js requires\nNODE_MODULE_VERSION 53. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or`npm install`)."}"`

**Comment by DustinCampbell** [comment]
Correct. That's precisely the issue. The VS Code team is working on it.

**Comment by DustinCampbell** [comment]
I expect there will be a recovery build soonish

**Comment by mstarrrsui** [comment]
Ah - OK.  Thanks!

**Comment by gregg-miskelly** [comment]
@mstarrrsui the VS Code issue seems to be fixed now. See VS Code version 1.12.1.

**Comment by nesshoever** [comment]
Seems to be happening again with the insider build:
```
Version 1.22.0-insider
Commit 31c30b99345e65fffdc33066726d0962dfbecfa3
Date 2018-03-21T06:14:55.070Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by gregg-miskelly** [comment]
@nesshoever Is this the full error message you are getting?

Error processing 'configurationDone' request. Unknown Error: 0x89720010

**Comment by nesshoever** [comment]
@gregg-miskelly Yes, that's it:
Error processing 'configurationDone' request. Unknown Error: 0x89720010

**Comment by gregg-miskelly** [comment]
I opened https://github.com/Microsoft/vscode/issues/46270 for this.

**Comment by bpasero** [comment]
@nesshoever OS?

**Comment by nesshoever** [comment]
@bpasero Ubuntu 16.04 x64

**Comment by GoodGuyGregory** [comment]
What is the current solution to this? it has been opened and closed. I am still receiving the same errors on my Mac. I will gladly assist

**Comment by gregg-miskelly** [comment]
@GoodGuyGregory I don't think whatever problem you are experiencing is related to this issue. Please open a new issue if you want help.
