### ISSUE TITLE
Xunit tests debug failed when Fact attribute has DisplayName value

### ISSUE THREAD

**Issue by Jodan-pz** [OmniSharp/omnisharp-vscode#1432]
## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.3

VS Code version: Version 1.11.2 (1.11.2)
C# Extension version: 1.9.0

## Steps to reproduce
Just add a DisplayName value to a unit test and try to use code lens debug or run.
Example: 
[Fact(**DisplayName**="My Test Name")]
public void Test(){
}

## Expected  behavior
Debugging test session working

## Actual behavior

Nothing, and the debugger must be restarted to be consistent. (restart omnisharp)

**Comment by DustinCampbell** [comment]
Thanks for the report!

**Comment by dgiove-pioneer** [comment]
👍
