### ISSUE TITLE
Opening project does not download C# debugger automatically

### ISSUE THREAD

**Issue by douglasstarnes** [OmniSharp/omnisharp-vscode#1433]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.3
VS Code version:
1.11.2
C# Extension version:
1.9.0
## Steps to reproduce
Open a new .NET Core project folder

## Expected  behavior
Visual Studio Code should prompt to download the debugger, add debugging resources, and restore dependencies. 

## Actual behavior
Nothing.

In addition I can try to run the command manually in the Command Palette but I get the error:

`command 'csharp.downloadDebugger' not found`

However, it downloads the debugger (only the first time) and then adds the debugging resource and restores the dependencies successfully.  Without the error and extra step of manually running the command, it works.  I've reinstalled the C# extension and tried both the stable and insider versions of VS Code.  It's the same in both of them.

**Comment by gregg-miskelly** [comment]
@douglasstarnes Currently there is nothing the C# extension can reasonably do to download on project open. We have been asking the VS Code team to provide support for this. When VS Code supports this, we are tracking the C# extension side of the work in https://github.com/OmniSharp/omnisharp-vscode/issues/1150.

But I am not sure why the `downloadDebugger` command doesn't work. That sounds like we may be doing something wrong.

**Comment by DustinCampbell** [comment]
@gregg-miskelly: The issue of commands not loading the extension was also mentioned in https://github.com/OmniSharp/omnisharp-vscode/issues/1375.

**Comment by douglasstarnes** [comment]
@gregg-miskelly In previous version of vscode the prompts came up automatically on opening a project folder.  The user still had to confirm the prompt to start the download(s).  They didn't start without confirming the prompt.  But the issue I am having is that there is no prompt and trying to run commands manually gives the error.

**Comment by DustinCampbell** [comment]
@douglasstarnes: It did come up previously, but only if you have a C# file open. In the project.json days, the download would start because of the presence of a well-known file name: 'project.json'. There isn't yet a way in VS Code to load the extension for a file with wildcards (e.g. *.csproj, *.sln, *.cs).

**Comment by DustinCampbell** [comment]
Seems like this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1150.

**Comment by douglasstarnes** [comment]
@DustinCampbell Ok, I understand.  Opening a C# file triggers the prompt to download the debugging assets and restore dependencies.  I'm going to close this now.  Thanks for the help! /cc @gregg-miskelly
