### ISSUE TITLE
IntelliSense incompletely shows methods from base classes

### ISSUE THREAD

**Issue by MikeBeaton** [OmniSharp/omnisharp-vscode#1440]
## Environment data
`dotnet --info` output:
````
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
````
Same behaviour also on:
````
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
````

VS Code version: 1.11.2
C# Extension version: 1.9.0

## Steps to reproduce

````
public class MyBase
{
    public void MyMethod(int a) { }
    public void MyMethod(int a, int b) { }
}

public class Class1 : MyBase
{
    public void MyMethod(int a, int b, int c) { }
    public void MyMethod(int a, int b, int c, int d) { }
}

public class Class2
{
    void foo()
    {
        var c1 = new Class1();
        c1.My ... typing here ...
    }
}
````

## Expected  behavior

While typing, all autocompletes (from class and base class) should be offered.

## Actual behavior

Before reaching the end of the method name, IntelliSense is correct: it says: `MyMethod void MyMethod(int a, int b, int c) (+3 overlo...`.

However, on reaching the end of the method name and typing the opening bracket, IntelliSense becomes incorrect: in the above example, it shows `1/2 void Class1.MyMethod(int a, int b, int c)`; more generally, it only shows the methods from the class, not the available methods from the base. (Note that all methods from class and base class are shown by IntelliSense in full Visual Studio, for example.)

**Comment by akshita31** [comment]
This issue has been fixed in the 1.14 milestone. We just released a beta of 1.14 -  https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.14.0-beta4. Follow [these instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) to a beta release of C# for VS Code.
