### ISSUE TITLE
Added Reference Not Available in Application

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-vscode#1444]
_From @RobertMeakin on May 1, 2017 22:46_

The following behaviour confirmed on three computers and by someone else.

I've written a few test applications in dotnet core 1.1 but am suddenly having difficulty adding libraries / references to other projects.

If I create a new library like this: **FooLibrary**
`dotnet new classlib`

And create a simple class like this:

```
namespace FooLibrary

{
    public class TestClass
    {
        public string GetMyString(){ return "Here I am."; }
    }
}
```

And then create a separate project in another folder: **BarApp**
`dotnet new console`

Add the reference:
`dotnet add reference ..\FooLibrary\FooLibrary.csproj`

After restoring and building both projects and reloading the window I would expect the FooLibrary to be available in BarApp. It isn't. In VSCode I get this error after adding the using reference:

> Could not load file or assembly 'FooLibrary ...

If I open the project in Visual Studio Pro I have a similar warning (saying it cannot resolve the reference), but if I run restore and save I can then run the app in both Visual Studio Pro and VSCode and get the value from the class library, even though I still get all the warnings and there's no intellisense.

_In the first attached screenshot note that the using statement and the new TestClass() initialisation are underlined in red and yet while debugging a value is still returned._

![capture1](https://cloud.githubusercontent.com/assets/8604571/25597687/2481f5f2-2ec8-11e7-9c43-8deb5f345820.JPG)

![capture2](https://cloud.githubusercontent.com/assets/8604571/25597697/33b2e996-2ec8-11e7-9cef-9600a167e33d.JPG)

_Copied from original issue: OmniSharp/omnisharp-roslyn#845_

**Comment by DustinCampbell** [comment]
Hi!

Thanks for the detailed information. I'm curious to know what folder you have opened in VS Code. If you open VS Code on the folder containing the console app, you won't be able to see the library.

**Comment by RobertMeakin** [comment]
Hi,

Screenshot below shows the folder structure.
![capture3](https://cloud.githubusercontent.com/assets/8604571/25598010/3d1ed57e-2eca-11e7-846e-815339062702.JPG)

**Comment by DustinCampbell** [comment]
Thanks! That's what I suspected. This is a duplicate of #963 and #1420. Essentially, C# for VS Code 1.9 won't process projects outside of the folder opened in VS Code. So, you can open the folder above this one to get IntelliSense to work.

The good news is that the issue is already fixed. If you like, you can download [v1.10.0-beta1] and install it using the instructions here: [Installing Beta Releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases).

**Comment by RobertMeakin** [comment]
Thanks, Dustin,

Appreciate it.
