### ISSUE TITLE
Create derived type

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-vscode#1447]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

```
VS Code version:1.11.2
C# Extension version:1.9.0

## Steps to reproduce
Create an interface
Put cursor on interface name

## Expected  behavior
Completion option to "Create derived type"

## Actual behavior
Nothing

**Comment by DustinCampbell** [comment]
I'm not exactly sure what you want this feature to do. Could you be more specific? Is this a feature that's already in Visual Studio or Roslyn that you'd like brought to VS Code?

**Comment by jchannon** [comment]
It might be R#
<img width="295" alt="screen shot 2017-05-02 at 14 25 54" src="https://cloud.githubusercontent.com/assets/105126/25619573/4d2eca0e-2f43-11e7-8a6a-60ff9bae181d.png">

That option creates a class like so

```
public class Foo : IFoo
{

}
```

**Comment by DustinCampbell** [comment]
Yup, that looks like R#. cc @Pilchie.

If this is added to Roslyn and VS, we'll pick it up in C# for VS Code.

**Comment by Pilchie** [comment]
Added https://github.com/dotnet/roslyn/issues/19181 to the roslyn backlog.

**Comment by Pilchie** [comment]
PRs welcome BTW :)

**Comment by DustinCampbell** [comment]
Let's track this with the roslyn backlog issue.
