### ISSUE TITLE
[BUG] Format document not working

### ISSUE THREAD

**Issue by bodynar** [OmniSharp/omnisharp-vscode#1448]
## Environment data
`dotnet --info` output: --
VS Code version: 1.11.2
C# Extension version: 1.9.0

## Steps to reproduce
1. Open \ create .cs file
2. Write some unformatted code (like:
```
public     class Student{
public int Age{get;set;}}
```
3. Use keybinding to format all document

## Expected  behavior
format document to
```
public class Student 
{
public int Age { get; set; } 
}
```

## Actual behavior
nothing happened at all
also there's no command in context menu

**Comment by DustinCampbell** [comment]
Hi! In order to get various features working (like formatting, IntelliSense, etc.), you'll need to have a C# project. Check out the introductory video [here] to get started.

**Comment by bernardbr** [comment]
@DustinCampbell I have a question: The omnisharp have the responsability to format document, like [CodeMaid](http://www.codemaid.net/) extension in Visual studio?

**Comment by bodynar** [comment]
@DustinCampbell, sure, i'm tryin format code in c# project.

Also i've installed dotnet core via vs17 installer.

**Comment by DustinCampbell** [comment]
@bernardbr: OmniSharp simply calls Roslyn APIs to format code and doesn't add anything more. A request like that is probably better over at https://github.com/dotnet/roslyn/issues.

**Comment by DustinCampbell** [comment]
@bodynar: The reason I asked is because you didn't include your `dotnet --info` information above and you only mentioned working in C# file in your repro steps.

Could you provide your OmniSharp Log after opening your C# file? You can get to the OmniSharp Log by selecting View->Output from the menu in VS Code. Then, in the Output pane, choose "OmniSharp Log" from the combobox in the top-right corner.

**Comment by bernardbr** [comment]
Thanks @DustinCampbell !
I'll be open there!

**Comment by bodynar** [comment]
@DustinCampbell, sure.

I opened .cs file.

OmniSharp output:

```
Starting OmniSharp server at 04.05.2017, 15:42:40
    Target: c:\Users\2\Desktop\study\inf\apps\MAS\asp.project\EmployeeCatalog\MAS.Work.EmployeeCatalog

OmniSharp server started
    Path: C:\Users\2\.vscode\extensions\ms-vscode.csharp-1.9.0\bin\omnisharp\OmniSharp.exe
    PID: 14184

OmniSharp: -s c:\Users\2\Desktop\study\inf\apps\MAS\asp.project\EmployeeCatalog\MAS.Work.EmployeeCatalog --hostPID 11856 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
[info]: OmniSharp.Startup
        Omnisharp server running using Stdio at location 'c:\Users\2\Desktop\study\inf\apps\MAS\asp.project\EmployeeCatalog\MAS.Work.EmployeeCatalog' on host 11856.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\Users\2\Desktop\study\inf\apps\MAS\asp.project\EmployeeCatalog\MAS.Work.EmployeeCatalog
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuild will use local Visual Studio installation.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        No solution files found in 'c:\Users\2\Desktop\study\inf\apps\MAS\asp.project\EmployeeCatalog\MAS.Work.EmployeeCatalog'

```

**Comment by DustinCampbell** [comment]
It sounds like there's no C# project or solution in the location you've opened in VS Code. Is that the case?

**Comment by bodynar** [comment]
@DustinCampbell, yep, i opened subfolder (.sln file is toplevel).

Here's output when i opened project folder

```
Starting OmniSharp server at 04.05.2017, 16:53:24
    Target: c:\Users\2\Desktop\study\inf\apps\MAS\MAS.Stuff.DependencyResolver\MAS.Stuff.DependencyResolver.sln

OmniSharp server started
    Path: C:\Users\2\.vscode\extensions\ms-vscode.csharp-1.9.0\bin\omnisharp\OmniSharp.exe
    PID: 10336

OmniSharp: -s c:\Users\2\Desktop\study\inf\apps\MAS\MAS.Stuff.DependencyResolver\MAS.Stuff.DependencyResolver.sln --hostPID 15276 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```

**Comment by DustinCampbell** [comment]
Hmmm... it seems like OmniSharp isn't launching properly. Have you tried reinstalling C# for VS Code? Perhaps the installation was corrupted in some way?

**Comment by bodynar** [comment]
Yes, i tried this and it didn't helped :(

**Comment by DustinCampbell** [comment]
This seems a bit similar to https://github.com/OmniSharp/omnisharp-vscode/issues/1377. Is there any chance you could share your project?

**Comment by bodynar** [comment]
Oh, i can upload project 'DependencyResolver', but i think there's no sense, 'cause i've got no formatting action in every c# project what i've had. (like DependencyResolver or EmployeeCatalog)

All projects created by VS17 Enterprise, if it necessary.

**Comment by DustinCampbell** [comment]
OK then...

Are you able to launch OmniSharp with your solution from command prompt? Try running the following. It should produce lots of JSON output (if your folders haven't changed):

`C:\Users\2\.vscode\extensions\ms-vscode.csharp-1.9.0\bin\omnisharp\OmniSharp.exe -s c:\Users\2\Desktop\study\inf\apps\MAS\MAS.Stuff.DependencyResolver\MAS.Stuff.DependencyResolver.sln --stdio`

**Comment by bodynar** [comment]
Hm. i cant execute first command, i've getting exception (pic)
![image](https://cloud.githubusercontent.com/assets/22620134/25774783/1040d24a-329f-11e7-9676-55b9193c7dad.png)

**Comment by DustinCampbell** [comment]
You only passed the first bit of the command I specified in github. Here it is again for reference:

```
`C:\Users\2\.vscode\extensions\ms-vscode.csharp-1.9.0\bin\omnisharp\OmniSharp.exe -s c:\Users\2\Desktop\study\inf\apps\MAS\MAS.Stuff.DependencyResolver\MAS.Stuff.DependencyResolver.sln --stdio
```

**Comment by bodynar** [comment]
Oh, my bad.

I launched command in cmd.exe and gets a lot of json response (90% of this is loggin' (level: information)).
and last row:

> {"Event":"started","Body":null,"Seq":18,"Type":"event"}

so what it gives me?

**Comment by DustinCampbell** [comment]
I just wanted to see if this process would launch properly on your machine with your project. It seems that it works. However, it seems that it didn't work when launched within VS Code according to your comment [here](https://github.com/OmniSharp/omnisharp-vscode/issues/1448#issuecomment-299192306).

**Comment by bodynar** [comment]
@DustinCampbell, i dunno. I opened today project folder, waited omniSharp loaded and get working formatting command.

magic..

**Comment by DustinCampbell** [comment]
hmmm... That's really strange. Out of curiosity is this some sort of shared machine (e.g. a computer lab or Internet cafe)? I ask because of the user profile being listed as "2" rather than a user name.

**Comment by bodynar** [comment]
No, its my personal computer with strange username (:

**Comment by DustinCampbell** [comment]
ah. Ok.
