### ISSUE TITLE
Go to Definition not working

### ISSUE THREAD

**Issue by jia463223499** [OmniSharp/omnisharp-vscode#1449]
## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.3)
Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917
Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3

VS Code version:  1.11.2
C# Extension version: 1.9.0

## Steps to reproduce

1. visual studio code open a folder that containstodoApi.csproj and some *.cs files 
2. open a .cs file and right click a class, "got to definition" appeared, but it does not work. and wait a minute "go to definition" disappered.

## Expected  behavior
"go to definition" work well

## Actual behavior
"go to definition" does not work 

omnisharp log：

Starting OmniSharp server at 2017/5/3 上午11:37:28
    Target: e:\Visual Studio Code\DotNetCore\todoApi
OmniSharp server started
    Path: C:\Users\user\.vscode\extensions\ms-vscode.csharp-1.9.0\bin\omnisharp\OmniSharp.exe
    PID: 8820
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

Visual Studio 2010 Installed

**Comment by DustinCampbell** [comment]
Is that your full OmniSharp log?

**Comment by jia463223499** [comment]
@DustinCampbell Yes,  I followed the following steps,  selecting View->Output in VS Code. Then, click the combobox at the top-right of the Output pane and choose "OmniSharp Log".

**Comment by DustinCampbell** [comment]
Sorry for the delay. Are you able to run the following at a command prompt?

```
C:\Users\user.vscode\extensions\ms-vscode.csharp-1.9.0\bin\omnisharp\OmniSharp.exe -s e:\Visual Studio Code\DotNetCore\todoApi --stdio
```

If so, could you share the output here?

**Comment by DustinCampbell** [comment]
Note: This looks a lot like #1448

**Comment by jia463223499** [comment]
Thanks @DustinCampbell . when I run the command at a command prompt，a  windows exception exists. 

-------------------------------------------------------------------------------
OmniSharp.exe - .NET Framework Initialization Error
To run this application, you first must install one of the following versions of the .NET Framework:
  .NETFramework,Version=v4.6
Would you like to download and install .NETFramework,Version=v4.6 now?
-------------------------------------------------------------------------------

Does it mean OmniSharp depend on .NETFramework 4.6？ Whether the .NETFramework 4.6 package must be installed ? Now .NETFramework 4.0 is installed on my computer.

**Comment by DustinCampbell** [comment]
Yes. OmniSharp requires at least .NET Framework 4.6 to run.

**Comment by jia463223499** [comment]
Thanks

**Comment by DustinCampbell** [comment]
Did installing 4.6 work for you?

**Comment by jia463223499** [comment]
@DustinCampbell .Thank you for your concern. My Development Environment does not allow me to install .NET Framework 4.6. So there is no answer you now.

**Comment by jia463223499** [comment]
@DustinCampbell .Thank you for your concern. My Development Environment does not allow me to install .NET Framework 4.6. So there is no answer now.

**Comment by AndyPook** [comment]
Just in case it helps anyone...
There may be multiple "projects" in the folder and VSCode has selected the "wrong" one.

Use ctrl-shift-P and select "OmniSharp: Select Project" to select the correct project (a .sln file).

If you have the Output window open with "OmniSharp Logs" selected, you will see it reading your csproj's. Once finished your goto definition will start to work

**Comment by sgentile** [comment]
@AndyPook  I get this:

command 'o.restart' not found
command 'o.pickProjectAndStart' not found

**Comment by rchande** [comment]
@sgentile Can you file a new issue and include in it:
the output of `dotnet --version`
your VS Code version
your C# extension version

**Comment by rchande** [comment]
Sorry @sgentile, looks like you did that already. Thanks.

**Comment by RDavis3000** [comment]
I had the same issue; I looked at the OmniSharp logs and found

```
OmniSharp server started with .NET 6.0.400
.
    Path: C:\Users\Richa\.vscode\extensions\ms-dotnettools.csharp-1.25.0-win32-x64\.omnisharp\1.39.0-net6.0\OmniSharp.dll
    PID: 876

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```

For me the problem was that OmniSharp was trying to execute \OmniSharp.dll
If you go to settings Omnisharp:path and put the full path to OmniSharp.exe it works.
In your example @spy653 it would be :
**C:\Users\Richa\.vscode\extensions\ms-dotnettools.csharp-1.25.0-win32-x64\.omnisharp\1.39.0-net6.0\OmniSharp.exe**
YMMV but hope it helps someone!
