### ISSUE TITLE
Do omnisharp has a build error cache?

### ISSUE THREAD

**Issue by bernardbr** [OmniSharp/omnisharp-vscode#1452]
I'm converting a legacy code to net core and during this process, I need adjust some issues. When I finally resolve it, the editor keeps a part of the code underlined, as if it's still in error...

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

VS Code version: 
Version 1.11.2
Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
Date 2017-04-13T08:03:11.395Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

C# Extension version: 1.10.0-beta2

## Steps to reproduce

I can't reproduce this...

## Actual behavior

It looks like it has an error cache
![sem titulo](https://cloud.githubusercontent.com/assets/4705034/25717029/9982b83a-30d7-11e7-881a-f4361f2abda3.png)

When I do `Reload Window` the problem desapears...

**Comment by DustinCampbell** [comment]
I've seen this occasionally but haven't been able to reproduce it either. My _suspicion_ is that the problem is actually in VS Code itself, but I haven't been able to trigger the problem under the debugger to know for sure.

**Comment by bernardbr** [comment]
Thanks @DustinCampbell 

This problem is more often in beta versions!

**Comment by DustinCampbell** [comment]
And to specifically answer your question, no we don't cache diagnostics in OmniSharp or C# for VS Code. The only cache of diagnostics is in the DiagnosticCollection that VS Code provides us with ([code](https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/features/diagnosticsProvider.ts#L126)).

If you keep running into this problem, would you mind providing your OmniSharp Log? It'd also be helpful if you set the "omnisharp.loggingLevel" setting in VS Code to "debug" to provide more information.

Some things to watch out for:

1. Are the diagnostics that seem to be hanging around produced by typing, or by building?
2. Are there particular diagnostics that seem to hang around more than others?
3. Are there particular activities that seem to leave diagnostics hanging around? For example, running a code action from a light bulb might be such an activity.

**Comment by bernardbr** [comment]
## OmniSharp Log:

[omnisharp.log.txt](https://github.com/OmniSharp/omnisharp-vscode/files/977247/omnisharp.log.txt)
![sem titulo 2](https://cloud.githubusercontent.com/assets/4705034/25719989/af977cd2-30e1-11e7-995c-bf461c746439.png)

#### Q: Are the diagnostics that seem to be hanging around produced by typing, or by building?
##### A: The problem occurs when I'm typing but still after build.

#### Q: Are there particular diagnostics that seem to hang around more than others?
##### A: Yes. In my case, I had a virtual method called "Remover", but it isn't virtual anymore. So I need to changed it to a new method "CriarComandoRemover". When I do this, the problem occurs.
         But the problem also occurs in other cases...

#### Q: Are there particular activities that seem to leave diagnostics hanging around? For example, running a code action from a light bulb might be such an activity.
##### A: Normally I clean unused usings (ctrl + .) and refactoring the class.

**Comment by DustinCampbell** [comment]
OK, so here's what I understand:

1. You build and there's a bunch of errors.
2. You type, and the errors from the build don't go away. Is that correct?

**Comment by bernardbr** [comment]
Yes, but only on Editor. On the "Problems" output doesn't show anymore.

**Comment by DustinCampbell** [comment]
@bernardbr: Is this still an issue for you? If so, have you been able to lock down a repro?

**Comment by bernardbr** [comment]
Hello, @DustinCampbell I'm using the last beta version on OmniSharp and it works fine!
I'm closing this issue.
Thanks!

**Comment by DustinCampbell** [comment]
Glad to hear it -- thanks!
