### ISSUE TITLE
Method intellisense does not add parentheses

### ISSUE THREAD

**Issue by tetious** [OmniSharp/omnisharp-vscode#1453]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-1-003175)

Product Information:
 Version:            1.0.0-preview2-1-003175
 Commit SHA-1 hash:  bb053ed000

Runtime Environment:
 OS Name:     fedora
 OS Version:  25
 OS Platform: Linux
 RID:         fedora.25-x64
```
VS Code version: 1.11.2
C# Extension version: 1.9.0

## Steps to reproduce
Allow intellisense to complete a method.

## Expected  behavior
Intellisense adds method call parentheses and moves the insertion point **inside** the parentheses when the method has at least one parameter **without a default**, otherwise the insertion point should go **after** the close parenthesis.

This behavior mirrors what I'm long used to with Resharper, and not having it breaks muscle memory. :) I can't remember if Visual Studio's intellisense behaves this way. If not, this feature might belong behind a preference setting. 

## Actual behavior
No parentheses are generated.

Thanks for your consideration!

**Comment by DustinCampbell** [comment]
Hi @tetious, Visual Studio's IntelliSense does not behave this way. If we add it in Visual Studio, you can be sure that it'll make an appearance in VS Code.

@Pilchie, do we already have a request for this feature in Roslyn?

**Comment by Pilchie** [comment]
I'm not aware of any requests for this feature.

**Comment by DustinCampbell** [comment]
Maybe https://github.com/dotnet/roslyn/issues/12363?

**Comment by Pilchie** [comment]
Good find!

**Comment by DustinCampbell** [comment]
Let's track this over in the Roslyn issue. Ultimately, we'll want the change in Visual Studio before we make it for VS Code.

**Comment by Nik-Lz** [comment]
+1 Any updates on this? I can't be the only one bothered that much by it. Many other major IDEs have this feature and latest version of VS2017 does not. Or does it? Have things changed, or is there any such extension that supports it?

**Comment by DustinCampbell** [comment]
@Nik-Lz: The issue is being tracked with https://github.com/dotnet/roslyn/issues/12363.
