### ISSUE TITLE
Visual Studio Code 1.12 debugger fails to run with Omnisharp and Dotnet projects

### ISSUE THREAD

**Issue by mdmoura** [OmniSharp/omnisharp-vscode#1454]
## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.1)
Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

VS Code version: 1.12

C# Extension version:
1.10.0-beta2

## Steps to reproduce

I upgraded Visual Studio Code from 1.11 to 1.12 and got the following error when debugging a dotnet project:

    Error processing 'configurationDone' request. Unknown Error: 0x89720010

Everything was working fine before upgrading to Visual Studio Code 1.12.

And I was using Omnisharp extension1.10.0-beta1. I then upgraded to 1.10.0-beta2.

However I keep getting the same error. What might be wrong?

**Comment by egamma** [comment]
@gregg-miskelly can please help us to track down whether this is 1.12 releated?

**Comment by jasonsturges** [comment]
Same issue - every ASP.NET Core web application or DotNet Core command line application that previously functioned before the v.1.12.0 update now exhibits this error.

**Comment by mjosephsmith** [comment]
Same issue - all ASP.NET Core web apps would build and run just minutes prior to the update.

**Comment by miguelcaravantes** [comment]
same issue v1.12

**Comment by bernardbr** [comment]
Same issue here!
```Error processing 'configurationDone' request. Unknown Error: 0x89720010```

**Comment by miguelcaravantes** [comment]
in VS code "Insiders" 1.12 works fine

**Comment by isidorn** [comment]
Yes, as a workaround you can use VSCode insiders https://code.visualstudio.com/insiders
While we are investigating the issue...

**Comment by bernardbr** [comment]
In a meanwhile I'll downgrade https://code.visualstudio.com/updates/v1_11

**Comment by INGCRENGIFO** [comment]
@bernardbr Great idea, I'll do the same.

**Comment by mjosephsmith** [comment]
I took the downgrade path, as the Insiders version immediately through an error stating that "coreclr" was not a valid configuration type... 👎

**Comment by winterlimelight** [comment]
If you can get away without debug in the short term you can run the following from PowerShell to have things run as normal:
<path-to-folder-with-proj-file>$Env:ASPNETCORE_ENVIRONMENT = "Development"
<path-to-folder-with-proj-file>dotnet run

**Comment by emersonsoares** [comment]
As @isidorn recommended, vs code insiders is working fine here.

**Comment by RichardD012** [comment]
@mjosephsmith if you open the console you can install a .NET debugger.

**Comment by zeroskyx** [comment]
Same issue here -- related to [https://github.com/OmniSharp/omnisharp-vscode/issues/1323](url)?

**Comment by gregg-miskelly** [comment]
No. This is a bug in VS Code. The VS Code team is working on fixing it. Either install insiders or roll back in the mean time.

**Comment by gregg-miskelly** [comment]
We will not close this yet since this is a hot issue, but https://github.com/Microsoft/vscode/issues/25918 tracks fixing this.

**Comment by gregg-miskelly** [comment]
VS Code 1.12.1 is now out, and contains the fix. So closing this.

**Comment by omerlh** [comment]
I am having the same issue, using vscode 1.15. It happens to me when trying to attach to docker process, as described in #1369. Regular start of dotnet core app works, so I guess this is something related to this configuration. I have 2 errors when running the configuration, the original error and:
```
unknown request 'attach'
```
The launch configuration:
```
        {
            "name": "Debug Api",
            "type": "coreclr",
            "request": "attach",
            "processName": "dotnet",
            "pipeTransport": {
                "debuggerPath": "/vsdbg/vsdbg",
                "pipeProgram": "docker-compose",
                "pipeCwd": "${workspaceRoot}",
                "pipeArgs": [
                    "exec", "app"
                ],
                "quoteArgs": false
            }
        },
```

**Comment by gregg-miskelly** [comment]
@omerlh you are seeing `Unknown Error: 0x89720010`, and you are only seeing it for docker??? If not, please open a new issue.

**Comment by omerlh** [comment]
Yes, I saw it only for docker-compose. When switched to docker instead it worked...
