### ISSUE TITLE
Auto indentation doesn't work (C#, mac)

### ISSUE THREAD

**Issue by IvanSorokin** [OmniSharp/omnisharp-vscode#1455]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 15.0.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.9.0|
|mono-debug|ms-vscode|0.15.5|;

Auto indentation doesn't work after update. Code formatting hotkey sets it, but no real time auto indentation. Tried to reinstall, no result. Settings.json is default.

http://imgur.com/zdpjV3n

**Comment by DustinCampbell** [comment]
Which update are you referring to? C# for VS Code 1.9? (That update is a couple of weeks old, which is why I'm asking to clarify.)

**Comment by IvanSorokin** [comment]
@DustinCampbell, yes.

**Comment by DustinCampbell** [comment]
> Strange thing is that indentation work with {}, but not without them.

@IvanSorokin: I'm not sure what you meant by that. Could you share some repro steps?

**Comment by IvanSorokin** [comment]
@DustinCampbell, I recorded this situation https://www.youtube.com/watch?v=pKxdup7cLgY

**Comment by DustinCampbell** [comment]
I'm not sure we've ever had that level of auto-indentation in VS Code. Are you sure it worked before the update?

**Comment by IvanSorokin** [comment]
@DustinCampbell, yes

**Comment by DustinCampbell** [comment]
I just downloaded an older version of C# for VS Code from our GitHub releases page (1.6), and the indentation is the same. 

@jrieken: Do you know if anything has changed around indentation in VS Code? AFAIK, we do't do anything special to support it in C# for VS Code. Honestly, I'm not sure there's an indentation API that we could support.

**Comment by DustinCampbell** [comment]
Out of curiosity, is the problem that you need to turn on set the `"edit.FormatOnType": true` setting in VS Code? I don't think we've ever handled indentation in this way, but turning that option on causes formatting to occur when typing a `;` or `}`

**Comment by jrieken** [comment]
> @jrieken: Do you know if anything has changed around indentation in VS Code? AFAIK, we do't do anything special to support it in C# for VS Code. Honestly, I'm not sure there's an indentation API that we could support.

Not that I know of. @alexandrudima will know

**Comment by IvanSorokin** [comment]
@DustinCampbell Thanks for workaround, it works! It seems that problem was with my settings.

**Comment by DustinCampbell** [comment]
Glad to hear this worked for you. I'd love to be able to add proper indentation support. Hopefully, we'll have a way to add custom language support for indentation in VS Code at some point to allow us to have parity with VS. However, until then, I don't think there's much we can do.

@jrieken, @alexandrudima: Are there any issues on the VS Code I should track for this issue? I found https://github.com/Microsoft/vscode/issues/9241 and https://github.com/Microsoft/vscode/issues/16998.
