### ISSUE TITLE
ProjectReferences in csproj break intellisense

### ISSUE THREAD

**Issue by lewislabs** [OmniSharp/omnisharp-vscode#1457]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1```
VS Code version:
1.12.1
C# Extension version:
1.9.0
## Steps to reproduce
Adding a project based reference to a .csproj e.g.
```xml
<ItemGroup>
       <ProjectReference Include="..\MyOtherProject\MyOtherProject.csproj" />
</ItemGroup>
```
## Expected  behavior
Omnisharp can handle `<ProjectReference>` the same way it can handle `<PackageReference>`.
## Actual behavior
Adding the reference results in omnisharp not being able to recognise any namespaces or types from the referenced project. And intellisense doesn't work as expected.

**Comment by lewislabs** [comment]
This could be the same problem as described in #371

**Comment by lewislabs** [comment]
and #963

**Comment by DustinCampbell** [comment]
It's not #371, but it sounds to me like the same issue as #963, which is already fixed for the next release. Would you be willing to try the latest beta release and let us know if it works better for you? The release is available [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.10.0-beta2). Be sure to follow the instructions at [Installing Beta Releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases).

**Comment by lewislabs** [comment]
I'll give it a go and let you know. If it fixes the problem I will be very happy!

**Comment by fshauge** [comment]
Had the same problem, and the beta release fixed it!

**Comment by lewislabs** [comment]
Thanks @DustinCampbell, that's worked perfectly for me!

**Comment by DustinCampbell** [comment]
Glad to hear it. Thanks!
