### ISSUE TITLE
No suggestions after typing new keyword

### ISSUE THREAD

**Issue by pflannery** [OmniSharp/omnisharp-vscode#146]
When typing the `new` keyword no suggestions are shown. i.e. `List<string> myList = new` at this point visual studio would suggestion completions.

**Comment by pflannery** [comment]
Is there a block on this? anything I can do to fix this?

**Comment by pflannery** [comment]
@DustinCampbell at'ing you just in case you missed my comments

**Comment by DustinCampbell** [comment]
Unfortunately, it'll require some significant tweaks to both OmniSharp and probably a change to VS Code to make it work. It's definitely on my list to get working, but triggering completion on <SPACE> in specific positions is tricky.

**Comment by Novack-** [comment]
This in an old one! Following.

**Comment by pflannery** [comment]
@DustinCampbell thanks for the progress on this

However I'm seeing this in v1.13.1 

![image](https://user-images.githubusercontent.com/1727302/32752151-07f04668-c8c0-11e7-81e7-735ddbb74856.png)

But I expected something like this

![image](https://user-images.githubusercontent.com/1727302/32752206-4308e3f4-c8c0-11e7-988b-d37fc275acc6.png)

**Comment by DustinCampbell** [comment]
Yes, there's is some work yet to handle sorting. It's getting much closer though! :smile: cc @rchande, who's working on this as part of https://github.com/OmniSharp/omnisharp-vscode/issues/1765.

**Comment by Novack-** [comment]
The last missing piece before @DustinCampbell can do his magic seems to be happening on #35551.
