### ISSUE TITLE
Snippets not loading properly.

### ISSUE THREAD

**Issue by Pulstura** [OmniSharp/omnisharp-vscode#1462]
Snippets don't seem to be working anymore...? I had to copy your snippets and add it manually to users snippet and that started working again.

# Environment data
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

VS Code version: 1.12.1
C# Extension version: 1.9.0

**Comment by DustinCampbell** [comment]
Hi! Does this look to you like the same problem described by https://github.com/OmniSharp/omnisharp-vscode/issues/1459?

**Comment by Pulstura** [comment]
Yes it seems it's the same issue. To be specific the issue I had was, I tried to use the prop snippet it wouldn't show up, until I added the user snippets.

I see you've resolved the issue, will this fix be released in the next release?

**Comment by DustinCampbell** [comment]
Yes. we've already taken a fix for this for 1.10 of C# for VS Code.
