### ISSUE TITLE
Additional comma is added to for auto complete shortcut

### ISSUE THREAD

**Issue by MarkWangSichun** [OmniSharp/omnisharp-vscode#1464]
## Environment data
`dotnet --info` output:
VS Code version: 1.9.0
C# Extension version:

## Steps to reproduce
Use "for" auto complete shortcut

## Expected  behavior
for(int i; i < length; i++)
{

}

## Actual behavior
for(int i; i < length; i++)
{

,
}

An additional "," is added before the closing bracket.

**Comment by Acidic9** [comment]
I don't believe this issue is related to OmniSharp's extension. I disabled OmniSharp on a Golang project and I still had this issue after reloading. There is an issue about this posted here: https://github.com/Microsoft/vscode/issues/26101#issuecomment-299817145

**Comment by DustinCampbell** [comment]
This looks like a VS Code issue (we haven't changed C# snippets in many, many releases). I've posted on https://github.com/Microsoft/vscode/issues/26101 for this to be investigated there.
