### ISSUE TITLE
Intellisense not working with Unity (5.5.0f3) project (MacOSX)

### ISSUE THREAD

**Issue by rocketedaway** [OmniSharp/omnisharp-vscode#1465]
## Environment data
Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.3

Mac OSX Version: 10.12.4 (Sierra)
Unity Version: 5.5.0f3
Unity Extension Version: 1.2.0
VS Code version: 1.12.1
C# Extension version: 1.9.0

## Steps to reproduce
Open the C# project via Unity (See log below)

## Expected  behaviour
Omnisharp loads and the intellisense works

## Actual behaviour
Omnisharp throws an error and intellisense does not work (See logs below)

**Notes:**

- Output of `which mono` in bash: `/usr/local/bin/mono` 
- I uninstalled mono and reinstalled via `brew`
- I uninstalled VSCode plugins and reinstalled (C# and Unity)
- Mono 3.5 API is located at `/usr/local/Cellar/mono/4.8.1.0/lib/mono/3.5-api`
- I unlinked and relinked `mono` via `brew`
- I restarted my computer :)
- This was working up until just recently.

**Log Output:**

Starting OmniSharp server at 5/8/2017, 8:11:34 PM
    Target: /Users/user/Projects/unity/pong-3d/pong-3d.sln

OmniSharp server started wth Mono
    Path: /Users/user/.vscode/extensions/ms-vscode.csharp-1.9.0/bin/run
    PID: 14677

OmniSharp: -s /Users/user/Projects/unity/pong-3d/pong-3d.sln --hostPID 14386 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
﻿﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/Users/user/Projects/unity/pong-3d' on host 14386."},"Seq":1,"Type":"event"}
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /Users/user/Projects/unity/pong-3d
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBUILD_EXE_PATH environment variable set to /Users/user/.vscode/extensions/ms-vscode.csharp-1.9.0/bin/omnisharp/msbuild/MSBuild.dll
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildExtensionsPath environment variable set to /Users/user/.vscode/extensions/ms-vscode.csharp-1.9.0/bin/omnisharp/msbuild
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildSDKsPath environment variable set to /Users/user/.vscode/extensions/ms-vscode.csharp-1.9.0/bin/omnisharp/msbuild/Sdks
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuild will use local OmniSharp installation.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in '/Users/user/Projects/unity/pong-3d/pong-3d.sln'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from '/Users/user/Projects/unity/pong-3d/Assembly-CSharp-firstpass.csproj'.
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The reference assemblies for framework ".NETFramework,Version=v3.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to process project file '/Users/user/Projects/unity/pong-3d/Assembly-CSharp-firstpass.csproj'.
/Users/user/Projects/unity/pong-3d/Assembly-CSharp-firstpass.csproj

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from '/Users/user/Projects/unity/pong-3d/Assembly-CSharp.csproj'.
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The reference assemblies for framework ".NETFramework,Version=v3.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to process project file '/Users/user/Projects/unity/pong-3d/Assembly-CSharp.csproj'.
/Users/user/Projects/unity/pong-3d/Assembly-CSharp.csproj

[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/user/Projects/unity/pong-3d'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Startup
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Startup
        Configuration finished.

**Comment by rocketedaway** [comment]
I figured out how to get it working for now. If I load the project via Unity the OmniSharp extension fails to load and intellisense does not work. If I navigate to the root of the project via terminal and start VSCode from there the OmniSharp extension loads and intellisense works fine. Not sure what is actually causing the problem though.

**Comment by curiousbrandon** [comment]
FYI I got this fixed by updating monoframework to the latest version.
