### ISSUE TITLE
Question: When debugging how can I step into an external referenced class library?

### ISSUE THREAD

**Issue by bernardbr** [OmniSharp/omnisharp-vscode#1467]
Hi!
I'm using an external class lib referenced via Nuget. The NuGet have a pdb file and I want to debug it. This NuGet package is mine too, and I have the source code.

How can I step into this external referenced class library when debugging?

Thanks!

**Comment by gregg-miskelly** [comment]
@bernardbr I am assuming the dll in the nuget package is release-compiled (optimized) correct? If so, what you want to do is set 'justMyCode` in your launch.json file to false. There are some more instructions for this [in our documentation](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md#debugging-code-compiled-on-another-computer).

Someday you will also be able to use [SourceLink](https://github.com/dotnet/core/blob/master/Documentation/diagnostics/source_link.md), but we don't support this yet for VS Code.

**Comment by bernardbr** [comment]
Hello @gregg-miskelly ! 
Thank you for your answer. Is the same solution for debugging unit tests? I tried in a console app and worked fine, but when I try during unit test debug it doesn't work...

Thanks!

**Comment by bernardbr** [comment]
Hello again @gregg-miskelly !

I saw your PR https://github.com/OmniSharp/omnisharp-vscode/pull/1446 about this.
I'm using the 1.10.0-beta2 version. Is this functionality in this version?
If yes: Need I just add ```"unitTestDebugingOptions": true``` on lauch.json?

Thanks!

**Comment by gregg-miskelly** [comment]
@bernardbr Correct. To be clear, in the "csharp" section.

**Comment by gregg-miskelly** [comment]
Oh, and to be clear, you add these under 'Preferences-\>Settings'.

**Comment by bernardbr** [comment]
Thanks a lot @gregg-miskelly !
It Works perfectly!  
Do you want me to close this issue?

**Comment by gregg-miskelly** [comment]
I can. Glad it worked!

**Comment by etmyhome** [comment]
> but we don't support this yet for VS Code.

any support to VSCODE ? 
i SourceLink support in vscode

**Comment by gregg-miskelly** [comment]
@etmyhome Soure Link to servers that don't require authentication is supported. Source Link to servers that require authentication is tracked with https://github.com/dotnet/vscode-csharp/issues/2071

**Comment by etmyhome** [comment]
any update? i using  [github packages ](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry)
