### ISSUE TITLE
Local variables declaration: Type keywords are not highlighted if the identifiers are on the next line

### ISSUE THREAD

**Issue by heshuimu** [OmniSharp/omnisharp-vscode#1468]
## Environment data
`dotnet --info` output:
VS Code version: 1.12.1
C# Extension version: 1.9.0

## Steps to reproduce
<img width="193" alt="qq20170509-172731 2x" src="https://cloud.githubusercontent.com/assets/7824592/25875479/5304cd44-34dd-11e7-8457-09c123e3b3e5.png">

**Comment by DustinCampbell** [comment]
This issue was moved to dotnet/csharp-tmLanguage#62

**Comment by DustinCampbell** [comment]
Note that this is pretty much impossible because of how syntax highlighting is achieved in VS Code by executing regular expressions line-by-line. I've moved this issue to repo where the C# TextMate grammar used by VS Code lives.
