### ISSUE TITLE
Function Signatures: Function names are not highlighted correctly when parameters are on the next line

### ISSUE THREAD

**Issue by heshuimu** [OmniSharp/omnisharp-vscode#1469]
## Environment data
`dotnet --info` output:
VS Code version: 1.12.1
C# Extension version: 1.9.0

## Steps to reproduce
<img width="214" alt="qq20170509-173949 2x" src="https://cloud.githubusercontent.com/assets/7824592/25875711/8eb7bd78-34de-11e7-9d06-c95bba1dd604.png">

<img width="183" alt="qq20170509-174413 2x" src="https://cloud.githubusercontent.com/assets/7824592/25875842/4251908e-34df-11e7-9e05-05b800a31a1f.png">

<img width="206" alt="qq20170509-174423 2x" src="https://cloud.githubusercontent.com/assets/7824592/25875959/ec3f1922-34df-11e7-9771-91f4cb74f9d2.png">

**Comment by DustinCampbell** [comment]
This issue was moved to dotnet/csharp-tmLanguage#61

**Comment by DustinCampbell** [comment]
I've moved this to the csharp-tmLanguage repo where the grammar used for syntax highlighting lives. Note that syntax highlighting in VS Code is handled via regular expressions that are executed line-by-line. So, achieving what you've specified will be extremely difficult without new VS Code APIs. Both bugs already exist in the core JavaScript and TypeScript colorization in VS Code.
