### ISSUE TITLE
install error : Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. 

### ISSUE THREAD

**Issue by 717009629** [OmniSharp/omnisharp-vscode#147]
Error: Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.

dotnet version (1.0.0-beta-002244)

**Comment by BeelzeBu** [comment]
You need to put in your project.json:

runtimes: {
      win10-x64: { }
}

**Comment by DustinCampbell** [comment]
Have you tried the latest extension here: https://github.com/OmniSharp/omnisharp-vscode/releases/download/v0.3.9/csharp-0.3.9.vsix?

**Comment by DustinCampbell** [comment]
Note: the error that you described is not returned by this VS Code extension. Should this be filed on https://github.com/dotnet/cli?

**Comment by 717009629** [comment]
@BeelzeBu @DustinCampbell thanks very much

**Comment by DustinCampbell** [comment]
Did you get this working properly or can I close this issue now?

**Comment by 717009629** [comment]
@DustinCampbell  yes， thank you

**Comment by DustinCampbell** [comment]
Excellent -- thanks!
