### ISSUE TITLE
Question: How to run the test task for multiple projects?

### ISSUE THREAD

**Issue by bernardbr** [OmniSharp/omnisharp-vscode#1471]
Excuse me if here isn't the best place to do this question, but I searched on the Internet and I didn't found a solution.

When dotnet core was "project.json" based I could configure the test task this way:
```javascript
        {
            "taskName": "test",
            "args": [
                "tests/unit/model/project.json",
                "tests/unit/domainService/project.json"
            ],
            "isTestCommand": true,
            "showOutput": "silent",
            "problemMatcher": "$msCompile"
        }
```

But in the .csproj based version, when I try to do the same thing I get this message: ```Specify a single project file to run tests from.```

Actually is there any way to do this?

Thank you!

**Comment by DustinCampbell** [comment]
This is more of a .NET CLI question. However, remember that 'dotnet test' now essentially shells out to MSBuild, and MSBuild won't take multiple projects at the command line. Instead, you should add both projects to a solution and add pass that to 'dotnet test'. (Note: I'm typing this without being able to try it myself, but that's how I understand that this is supposed to work.)

**Comment by bernardbr** [comment]
Thanks for your answer @DustinCampbell!
It didn't work: ```Couldn't find a project to run test from. Ensure a project exists in path```

And you are correct, it's a .NET CLI question. I will open it there!

Thanks a lot for your attention!

**Comment by bernardbr** [comment]
Nowadays doesn't have a solution to this issue.

In my case, I solved it with a python script. I've tried to do it with a PowerShell script, but I got restriction error.

### Python solution:
```python
import subprocess
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument("-f", "--files", nargs="+", dest="files", help="Define a .csproj file list.")

args = parser.parse_args()

for f in args.files:
	subprocess.call(r"C:\Program Files\dotnet\dotnet.exe" +  " test " + f)
```

### PowerShell solution:
```powershell
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string[]]$csProjFiles
)    

foreach ($csProjFile in $csProjFiles)
{
    dotnet test $csProjFile
}
```

### My task.json
```javascript
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "isShellCommand": true,
    "args": [],
    "tasks": [
        {
            "taskName": "build",
            "command": "dotnet",
            "args": [
                "build",
                "solution.sln"
            ],
            "isBuildCommand": true,
            "showOutput": "silent",
            "problemMatcher": "$msCompile"
        },
        {
            "taskName": "test",
            "command": "py",
            "args": [
                "${cwd}/run_tests.py",
                "-a",
                "${cwd}/test/unit/model/model.csproj",
                "${cwd}/test/unit/repository/repository.csproj"
            ],
            "isTestCommand": true,
            "showOutput": "silent"
        }
    ]
}
```
