### ISSUE TITLE
When Run Test is called it does not save the document

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-vscode#1473]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

```
VS Code version:1.12.1
C# Extension version:1.9.0

## Steps to reproduce
Write unit test, save, click Run Test to make sure it passes. Edit the test knowing it will cause a failure, don't save and click Run Test. It will pass. 

## Expected  behavior
Document to be saved so when Run Test is invoked it builds the project with saved files.

## Actual behavior
File not saved and uses pre existing build

**Comment by DustinCampbell** [comment]
Thanks for filing @jchannon!

**Comment by jchannon** [comment]
No worries, I think the issue also applies to Debug Test too
