### ISSUE TITLE
VSCode 1.12.1: No 'dotnet' command at all

### ISSUE THREAD

**Issue by MrScoville** [OmniSharp/omnisharp-vscode#1474]
Pardon for the ugly formatting... Don't know what is happening there

## Environment data
`dotnet --info` output:
(as the title explains, exactly this is the problem: NO 'dotnet' command)
`uname -a` (so, it's Linux...):
Linux juliet 3.16.0-4.686-pae #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-17) i686 GNU/Linux
(yes, it's i686, not x64)

VS Code version: 1.12.1
C# Extension version: 1.9.0
Mono Debug version: 0.15.5

## Steps to reproduce
1st - On a clean Debian Jessie i686, as root, open a bash and:
- `apt-get update`
- `apt-get dist-upgrade`
- `apt-get install locate`
- `apt-get install mono-complete`
- `sync ; updatedb`
- close the bash

2nd - Install VSCode and the extensions.

3rd - Open a bash and try:
- `which dotnet`
- `whereis dotnet`
- `locate dotnet`

## Expected  behavior
Well? I don't know!

## Actual behavior
ad 1:
`root@juliet:~# which dotnet`
`root@juliet:~# _`
(means the which command returned nothing)

ad 2:
`root@juliet:~# whereis dotnet`
`dotnet: /usr/share/dotnet`
`root@juliet:~# cd /usr/share/dotnet ; ls -l`
`total 0`

ad 3:
`root@juliet:~# locate dotnet | grep dotnet$`
`/usr/lib/mono/gac/gtk-dotnet`
`/usr/lib/mono/gac/policy.2.10.gtk-dotnet`
`/usr/lib/mono/gac/policy.2.4.gtk-dotnet`
`/usr/lib/mono/gac/policy.2.6.gtk-dotnet`
`/usr/lib/mono/gac/policy.2.8.gtk-dotnet`
`/usr/share/dotnet`
`/usr/share/cli-common/policies.d/010-2.10.gtk-dotnet`
`/usr/share/cli-common/policies.d/010-2.4.gtk-dotnet`
`/usr/share/cli-common/policies.d/010-2.6.gtk-dotnet`
`/usr/share/cli-common/policies.d/010-2.8.gtk-dotnet`

**Comment by gregg-miskelly** [comment]
@MrScoville are you trying to do .NET Core development? If so, from your install steps it looks like you didn't install the .NET Core SDK. If so, follow instruction on: https://www.microsoft.com/net/core#linuxdebian

**Comment by MrScoville** [comment]
No, I want to do Mono development.

Thank you in advance!

2017-05-11 18:09 GMT+02:00 Gregg Miskelly <notifications@github.com>:

**Comment by gregg-miskelly** [comment]
@MrScoville In that case you don't need `dotnet`. You can set csharp.suppressDotnetInstallWarning in your settings (Preferences-\>Settings in VS Code to open the file) to disable the warning.

**Comment by DustinCampbell** [comment]
@MrScoville: Did @gregg-miskelly's response above solve the problem for you?

**Comment by DustinCampbell** [comment]
Hopefully @gregg-miskelly's response helped solve the problem you described. Let me know if that's not the case.
