### ISSUE TITLE
SUGGESTION: add formatting option to leave lines with '#' alone

### ISSUE THREAD

**Issue by guoboism** [OmniSharp/omnisharp-vscode#1475]
Have a option that when turned on:
When formatting, lines with #if #region are left alone. (Not move to a indention like regular code)
And this would allow Indention-based folding to work on #region
 
#region s
    public void SetSize() { 
    }
#endregion

should NOT be formatted to:

    #region s
    public void SetSize() { 
    }
    #endregion

**Comment by DustinCampbell** [comment]
Hi -- there is a request for this already in Roslyn: https://github.com/dotnet/roslyn/issues/12305. When this is implemented in Roslyn, we'll be able to expose it here.
