### ISSUE TITLE
Error: Canceled  

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#148]
Error reported by error telemetry 

~3000 occurrences:
Error: Canceled  
at /Users/aioutecism/.vscode-insiders/extensions/ms-vscode.csharp-0.3.7/out/omnisharpServer.js:235:31 <no sourcemaps> 
 /vs/base/common/callbackList.ts#63:26 (apply) 
 /vs/base/common/event.ts#107:26 (call) 
 /vs/base/common/cancellation.ts#42:18 (fire) 
 /vs/base/common/cancellation.ts#83:31 (cancel) 
 at DiagnosticsProvider._validateProject (/Users/aioutecism/.vscode-insiders/extensions/ms-vscode.csharp-0.3.7/out/features/diagnosticsProvider.js:149:37) <no sourcemaps> 
 at DiagnosticsProvider._onDocumentAddOrChange (/Users/aioutecism/.vscode-insiders/extensions/ms-vscode.csharp-0.3.7/out/features/diagnosticsProvider.js:102:18) <no sourcemaps>

**Comment by DustinCampbell** [comment]
@aeschli, I'm not sure what to do with this issue. If I understand the issue. It is due to a cancellation token being cancelled, which should be expected. Why is telemetry being triggered for cancellation? That seems like a normal operation that telemetry shouldn't capture.

**Comment by aeschli** [comment]
@jrieken Joh, any ideas?

**Comment by jrieken** [comment]
I'd guess this is because a [rejected promise](https://github.com/OmniSharp/omnisharp-vscode/blob/bc40a7f4bb3b4f1cd9016c8148e0ab71acdce28a/src/omnisharpServer.ts#L398) isn't handled  and ends up in our unhandled rejection handler.

**Comment by DustinCampbell** [comment]
Ah ha! So, it was *your* fault @jrieken. :smile:

I'll take a look.

**Comment by jrieken** [comment]
Dude - all of this is my fault 🙈 Code written timely before a release in the middle of the night

**Comment by rchande** [comment]
@aeschli @jrieken It doesn't look like we have code that spews that particular message any more. I'm going to close this issue. Feel free to reopen/comment if you disagree.
