### ISSUE TITLE
Enable MSTest framework based tests targeting .NET Core to be run and debugged from within VSCode

### ISSUE THREAD

**Issue by pvlakshm** [OmniSharp/omnisharp-vscode#1482]
As of C# for Visual Studio Code extension: 1.9.0, only xUnit and NUnit based tests targeting .NET Core can be run and debugged from within VSCode.
This issue tracks the addition of MSTest support.

**Comment by DustinCampbell** [comment]
Re-opening until https://github.com/OmniSharp/omnisharp-roslyn/pull/856 is merged and we update to a new build of OmniSharp.

**Comment by DustinCampbell** [comment]
The new [1.10-beta3](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.10.0-beta3) release is out with this feature.
