### ISSUE TITLE
format code does not work with c sharp file

### ISSUE THREAD

**Issue by almoazib** [OmniSharp/omnisharp-vscode#1483]
## Environment data
`dotnet --info` output:
VS Code version:

.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
C# Extension version:
1.9.0
vscode 1.12.1
## Steps to reproduce

create a file  press shift+alt + f.  
  
 public static class CombosCtrl
 {
    
public string a;

void Test() {

}

}

## Expected  behavior

auto indent

## Actual behavior
nothing

**Comment by DustinCampbell** [comment]
Hi! Formatting doesn't work unless the file is included in a project. Is this a loose C# file, or is it included in csproj proejct?

**Comment by almoazib** [comment]
is included in a Unity  3D project.

**Comment by DustinCampbell** [comment]
Could you provide your OmniSharp log? You can do this like so:

1. Open your project in VS Code (open the folder containing the .sln files).
2. Open a C# file from the project
3. Select View->Output to display the Output pane.
4. In the Output pane, select "OmniSharp Log" from the drop-down in the top-right corner.

Once you've got the OmniSharp Log displayed, go ahead and copy and paste the whole mess here. :smile:

**Comment by almoazib** [comment]
Starting OmniSharp server at 17/5/2017 22:54:49
    Target: c:\xlives\DeadDancers\Unity\DeadDancers\DeadDancers.sln

OmniSharp server started
    Path: C:\Users\julio\.vscode\extensions\ms-vscode.csharp-1.9.0\bin\omnisharp\OmniSharp.exe
    PID: 5464

OmniSharp: -s c:\xlives\DeadDancers\Unity\DeadDancers\DeadDancers.sln --hostPID 8460 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
[info]: OmniSharp.Startup
        Omnisharp server running using Stdio at location 'c:\xlives\DeadDancers\Unity\DeadDancers' on host 8460.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\xlives\DeadDancers\Unity\DeadDancers
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuild will use local Visual Studio installation.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in 'c:\xlives\DeadDancers\Unity\DeadDancers\DeadDancers.sln'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from 'c:\xlives\DeadDancers\Unity\DeadDancers\Assembly-CSharp-firstpass.csproj'.
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to process project file 'c:\xlives\DeadDancers\Unity\DeadDancers\Assembly-CSharp-firstpass.csproj'.
c:\xlives\DeadDancers\Unity\DeadDancers\Assembly-CSharp-firstpass.csproj

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from 'c:\xlives\DeadDancers\Unity\DeadDancers\Assembly-CSharp.csproj'.
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to process project file 'c:\xlives\DeadDancers\Unity\DeadDancers\Assembly-CSharp.csproj'.
c:\xlives\DeadDancers\Unity\DeadDancers\Assembly-CSharp.csproj

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from 'c:\xlives\DeadDancers\Unity\DeadDancers\Assembly-CSharp-Editor-firstpass.csproj'.
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to process project file 'c:\xlives\DeadDancers\Unity\DeadDancers\Assembly-CSharp-Editor-firstpass.csproj'.
c:\xlives\DeadDancers\Unity\DeadDancers\Assembly-CSharp-Editor-firstpass.csproj

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from 'c:\xlives\DeadDancers\Unity\DeadDancers\Assembly-CSharp-Editor.csproj'.
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to process project file 'c:\xlives\DeadDancers\Unity\DeadDancers\Assembly-CSharp-Editor.csproj'.
c:\xlives\DeadDancers\Unity\DeadDancers\Assembly-CSharp-Editor.csproj

[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\xlives\DeadDancers\Unity\DeadDancers'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Startup
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Startup
        Configuration finished.

**Comment by DustinCampbell** [comment]
I reformatted your post.

It sounds like you'll want to install the .NET Framework 4.0 SDK. I _believe_ the download that you want is this one: https://www.microsoft.com/en-us/download/details.aspx?id=8279.

**Comment by almoazib** [comment]
Fixed after update unity -> visual studio code plugin

**Comment by DustinCampbell** [comment]
Glad to hear it! Thanks for following up.
