### ISSUE TITLE
Unnecessary usings are no longer underlined

### ISSUE THREAD

**Issue by robl33** [OmniSharp/omnisharp-vscode#1485]
My first issue so apologies if it's in the wrong format/place.

## Environment data
`dotnet --info` output:
not installed (OSX, developing for Unity3D 5.6.0f3)

VS Code version: 1.12.2

C# Extension version: 1.9.0

## Steps to reproduce
in any .cs file, add a `using` unnecessarily

## Expected  behavior
line with unnecessary `using` is underlined in green

## Actual behavior
no underline - note that if the cursor is on the line, the suggestion light bulb correctly gives the option to 'Remove Unnecessary Usings'

**Comment by cateyes99** [comment]
this is a dup of #1429 and has been resolved by https://github.com/OmniSharp/omnisharp-vscode/pull/1435. so this should be closed.

**Comment by robl33** [comment]
huh.. didn't see that when I searched. Apologies - closing.
