### ISSUE TITLE
Adopt new auto commit characters for completion items

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#1487]
Omnisharp-vscode can accept suggestions while also insert certain characters, like `Cons` will insert `Console` *and* insert a `.` when the dot-character is pressed. This has been "implemented" via [keybindings](https://github.com/OmniSharp/omnisharp-vscode/blob/master/package.json#L558). Mea culpa

The keybindings "implementation" has its weakness and in the meantime VS Code as an API for [commit characters](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2559). In short, when creating a completion item you can assign it a set of commit characters: 

```ts
item1 = new CompletionItem('Console')
item1.commitCharacters = ['.']; // no '(' because Console cannot be called

item2 = new CompletionItem('SomeMethod')
item2.commitCharacters = ['('] // can be called

// etc
```

**Comment by DustinCampbell** [comment]
@jrieken: Nice! Does the API tell us what character actually caused the completion item to commit? In VS, there are cases where completion can commit differently depending on what character is pressed.

**Comment by jrieken** [comment]
No, once we have what we want we don't talk back to the provider...
