### ISSUE TITLE
Syntax highlighting breaks when opening bracket of a method is placed in a new line

### ISSUE THREAD

**Issue by zeroskyx** [OmniSharp/omnisharp-vscode#1489]
The following code placed in a class breaks syntax highlighting:

    public void Routine
    (
      IInterface Interface0,
      IInterface Interface1,
      IInterface Interface2
    )
    {
      string One = "";
      string Two = "";
      string Three = "";
    }

    interface IInterface
    {
    }

Beginning with the second instance of IInterface and after the method body, everything is white -- in more complex projects, somewhere it works again later in the file.
Screenshot:
![capture](https://cloud.githubusercontent.com/assets/7782966/26170357/77cae1ee-3b41-11e7-8d0d-75bfc1fc972c.PNG)

Removing the newline after public void Routine does not cause the issue:
![capture1](https://cloud.githubusercontent.com/assets/7782966/26170402/9dcf9394-3b41-11e7-8333-be1242bcdb97.PNG)

I am aware that this appears to be a "strange" coding style; it makes reading constructors with loads of dependency injections much cleaner though (issue happens with both methods and constructors).

**Comment by DustinCampbell** [comment]
There's not much we can do about the first example as colorization is handled by running regular expressions in a line-by-line fashion. When the open and close parens are both placed on separate lines, it's pretty much impossible to detect.

**Comment by DustinCampbell** [comment]
This issue was moved to dotnet/csharp-tmLanguage#63
