### ISSUE TITLE
Completion list incorrectly includes full signatures for members

### ISSUE THREAD

**Issue by Leopotam** [OmniSharp/omnisharp-vscode#1491]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```

VS Code version:
1.13.0-insider (1.13.0-insider) 3bb9b5314ef50bd8225aba0565cadc6ca19bc821 2017-05-18T06:18:32.269Z

C# Extension version:
1.10.0-beta3 dc1908d0e984a52536289f34fe4be5f80eb94f10
## Steps to reproduce
1. Enter "if", it will show "if" snippet item in autocomplete list.
2. Enter space as part of "if (xxx)" expression, it will show methods list, "if" snippets will disappear.
3. Enter "(" as part of "if (xxx)" expression.
## Expected  behavior
Autocomplete with closing pair of parenthesis ")", or nothing. Even I try to insert "IF"-snippet with tab-key - it will do it only on second attempt (first one is just closing autocomplete popup). Totally not usable when you write condition expression in fast manner.
## Actual behavior
Automatic insertion of first item at autocomplete list.

**Comment by DustinCampbell** [comment]
Unfortunately, I'm unable to reproduce this. I tried the following:

1. Create new C# file.
2. Type `class` and press <kbd>TAB</kbd> followed by <kbd>ENTER</kbd> to expand the 'class' snippet and position the caret inside.
3. Type `svm` and press <kbd>TAB</kbd> to create a new static Main method with the caret positioned inside.
4. Type `if` to display the completion list with the 'if' snippet selected.

    ![image](https://cloud.githubusercontent.com/assets/116161/26212320/09ee79ce-3baa-11e7-8193-7353382823a7.png)

5. Press <kbd>SPACE</kbd>. At this point your repro steps state that a completion list of methods appears, but it doesn't (and shouldn't).

Could you clarify your repro steps? Thanks!

**Comment by Leopotam** [comment]
@DustinCampbell very strange behaviour, btw. Looks like it depends on base class methods. I recorded [video](https://youtu.be/rhi3aRW2xOM) with issue (it raised only on first attempt).

**Comment by bernardbr** [comment]
@DustinCampbell in my case happens it:
![image](https://cloud.githubusercontent.com/assets/4705034/26214038/6625f998-3bd1-11e7-8338-c44ea294a906.png)

I write ```if``` and press ```space``` then ```if``` snippet appears and press any key its happen:
![image](https://cloud.githubusercontent.com/assets/4705034/26214249/1057790a-3bd2-11e7-8c51-aa9cd3280291.png)

**Comment by DustinCampbell** [comment]
@Leopotam: Thanks for the video. That *is* very strange behavior. :smile: I notice that you're using VS Code Insiders. I wonder if the issues is there. I'll install and take a look.

@bernardbr: The behavior you described is different than what @Leopotam is seeing. Note that in your example there is code *after* the "if".

**Comment by bernardbr** [comment]
@DustinCampbell 

Yeah, I realized that now ... I'm sorry.
But, it's a strange behavior. It's happening with using statement too.
But thinking now, maybe it isn't a behavior of omnisharp. I'm gonna try to do the same with only omnisharp extension enabled.

**Comment by Leopotam** [comment]
@DustinCampbell class was created in unity3d solution - its why i can used UnityEngine.MonoBehaviour class. All methods at popup list are valid methods of MonoBehaviour type.

**Comment by DustinCampbell** [comment]
@Leopotam: I don't have Unity set up to precisely repro. Do you see the same problem on the RTM version of VS Code?

**Comment by bernardbr** [comment]
@DustinCampbell Sorry about my first comment. This behavior wasn't of Omnisharp. I disabled all other extensions and the problems gone.

Thanks for your attention!

**Comment by DustinCampbell** [comment]
@bernardbr: Glad to hear it -- thanks @bernardbr!

**Comment by Leopotam** [comment]
@DustinCampbell i uploaded minimal [unity3d-solution](https://drive.google.com/open?id=0BzXJzWlUcV9lY2kzZE5UTUVYNm8), you can try reproduce issue on it.

**Comment by DustinCampbell** [comment]
Thanks! I can totally repro with this solution.

**Comment by DustinCampbell** [comment]
OK. I can repro with a smaller code example:

```C#
class Base
{
    public void Invoke(float value) { }
}

class Derived : Base
{
    public void M()
    {
        // if here
    }
}
```

**Comment by DustinCampbell** [comment]
OK. I see what's wrong.
