### ISSUE TITLE
 Cannot read property 'uri' of null

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#15]
_From @vscodeerrors on January 25, 2016 16:53_

Issue Id: <b>5158e8e3-2e09-43c1-badd-5989e08cdab3</b><br /><br />*Versions* <br />- 0.10.6-release<br />-  dfc08dc9edf6607483b193bf934d3badc3fa2e11<br />*Stack* <br />TypeError: Cannot read property 'uri' of null<br />[vs/workbench/node/pluginHostProcess.js#L9:0 (define)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/srcvs/workbench/node/pluginHostProcess.js#L9:0 (define))<br />    at render (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\jrieken.vscode-omnisharp\out\features\omnisharpStatus.js:43:57) <no sourcemaps><br />[/vs/base/common/arrays.ts#L5:0](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/base/common/arrays.ts#L5:0)<br />[/vs/base/common/arrays.ts#L5:0](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/base/common/arrays.ts#L5:0)<br />[vs/workbench/node/pluginHostProcess.js#L9:0 (define)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/srcvs/workbench/node/pluginHostProcess.js#L9:0 (define))<br />[vs/workbench/node/pluginHostProcess.js#L9:0 (define)](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/srcvs/workbench/node/pluginHostProcess.js#L9:0 (define))<br />[/vs/base/common/arrays.ts#L5:0](https://github.com/microsoft/vscode/blob/a80232bbcfe8a5cdad1ebc98638673d9dcb02458/src/vs/base/common/arrays.ts#L5:0)<br />    at Object.p.handle (c:\Program Files (x86)\<br />

_Copied from original issue: Microsoft/vscode#2244_

**Comment by DustinCampbell** [comment]
This is pretty ancient and the code in omnisharpStatus.ts has changed enough that I'm not sure whether it's still a problem or not. Closing this for now. Please re-open if it comes up again.

**Comment by karnavkumar** [comment]
`Cannot read property 'uri' of null`this error throws in VS code 1.20 also my javascript Formatter is not Working. is this error related to this?

**Comment by Evan1995** [comment]
this error throws in VS vode 1.24 also ,
my python formatter is not working,but other formatter is well,
so how can I fix this problem?

**Comment by DustinCampbell** [comment]
@karnavkumar / @Evan1995 : This repo is for C# for VS Code. You should file an issue over at https://github.com/Microsoft/vscode/issues.

**Comment by fanhhoon** [comment]
I was unable to install C# extension on VScode version 1.19.3 with error Cannot read property 'uri' of null. Does anyone know what could possible cause it?

Fyi, I had to use this version of VScode due to the legacy developer software that were only compatible with VScode 2017.
