### ISSUE TITLE
Red squiggles persist when doing restore and build outside of VS Code

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-vscode#1501]
_From @danroth27 on May 20, 2017 16:40_

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|gc-excelviewer|GrapeCity|1.1.13|
|csharp|ms-vscode|1.9.0|;

---

Steps to Reproduce:

1. Using .NET Core SDK 1.0.4, run `dotnet new console`
2. Open the project in VS Code with the C# extension 1.9.0
1. `dotnet add package Microsoft.AspNetCore`
1. `dotnet restore`
1. `dotnet build`
1. In VS Code add the following using statements in Program.cs
   ``` c#
   using Microsoft.AspNetCore.Builder;
   using Microsoft.AspNetCore.Http;
   using Microsoft.AspNetCore.Hosting;
   ```
1. Red squiggles, even though the build just succeeded:

![image](https://cloud.githubusercontent.com/assets/1874516/26277637/4bd28730-3d40-11e7-948c-4a2d87ccab10.png)

_Copied from original issue: OmniSharp/omnisharp-roslyn#869_

**Comment by DustinCampbell** [comment]
_From @danroth27 on May 20, 2017 16:41_

Doing the restore from within VS Code seems to address the issue.

**Comment by DustinCampbell** [comment]
_From @danroth27 on May 20, 2017 16:42_

@DustinCampbell

**Comment by DustinCampbell** [comment]
@danroth27: I wasn't able to reproduce with the latest version of C# for VS Code (1.10). Could you try with the latest update to C# for VS Code and let me know if you still see the issue? If so, maybe I'm missing something in the repro steps.

**Comment by herecydev** [comment]
![image](https://cloud.githubusercontent.com/assets/11328618/26725557/fcd070d2-4796-11e7-928c-d900c6d72d3f.png)

Not sure if this is exactly the same issue but it feels similar. I'm often switching between VS and Code. With 1.10.0 (and previous versions), I am getting problems being highlighted for errors even if they have been fixed. The problems will go away if you start editing the class. So I'm guessing unless code "feels" like it's being modified it refuses to check, regardless if the file contents change.

**Comment by cartermp** [comment]
Closing out older issue without a repro. This doesn't reproduce for me either, so my guess is it got resolved somewhere along the line.
