### ISSUE TITLE
Intellisense doesn't seem to work for referenced projects in .net core

### ISSUE THREAD

**Issue by pshort** [OmniSharp/omnisharp-vscode#1503]
## Environment data
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

VS Code version: 1.12.2 
C# Extension version: 1.9.0

## Steps to reproduce

create a lib + console project in sibling directories using **dotnet new**
reference the lib project from the console using **dotnet add reference**

![image](https://cloud.githubusercontent.com/assets/140266/26303722/1d7f54b4-3ed8-11e7-9dce-9839378a83d5.png)

![image](https://cloud.githubusercontent.com/assets/140266/26303697/085ae36e-3ed8-11e7-9281-e96cd7cce709.png)

## Expected  behavior

I expect that the C# extension would see the project reference in the csproj and know that at least after a build that it should be able to provide completion and intellisense on that assembly inside the current project (if I am working on the console project in vscode).

## Actual behavior

I get red squiggly lines on all types from the referenced project. 

dotnet build gives 0 errors.

![image](https://cloud.githubusercontent.com/assets/140266/26303648/dda50884-3ed7-11e7-8c62-ebb6e2789cb3.png)

**Comment by DustinCampbell** [comment]
Do you have only the console app open in VS Code? If so, you this issue is already in the latest 1.10 beta (#963) and you can work around it by opening a folder higher in the hierarchy to ensure that both projects are open.

**Comment by pshort** [comment]
Ok, thanks for the help :) The plugin is working, loving omnisharp!
