### ISSUE TITLE
Code autoformating not working for *.cshtml files

### ISSUE THREAD

**Issue by ivankarpey** [OmniSharp/omnisharp-vscode#1508]
in my *cshtml file code formating just not working al all (for *.cs it's work fine btw). When pressing format hotkey nothing happen.

env: latest vs code + C# ext. 1.10-beta4, Ubuntu 16.04

**Comment by DustinCampbell** [comment]
Hi @ivankarpey, C# for VS Code doesn't understand .cshtml (Razor) files today (except for debugging). We'd like to add this eventually, but there's no timeline for when that might happen. We're using https://github.com/OmniSharp/omnisharp-vscode/issues/168 to track this work happening someday.
