### ISSUE TITLE
Unsafe C# and Unity

### ISSUE THREAD

**Issue by roblourens** [OmniSharp/omnisharp-vscode#1509]
_From @Southgrove on May 23, 2017 12:27_

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|unity-debug|Unity|1.2.0|
|hopscotch|idleberg|0.1.4|
|csharp|ms-vscode|1.9.0|;

---

I get the "Unsafe code may only appear if compiling with /unsafe" error even though I've set Unity to do that.

Steps to Reproduce:

1. Create an unsafe method in a C# class (in a unity project).
2. Watch the faulty error message and cry a little.

_Copied from original issue: Microsoft/vscode#27134_

**Comment by Leopotam** [comment]
@roblourens its unity issue, in 2017.1 version - fixed.

**Comment by DustinCampbell** [comment]
Thanks @Leopotam! It was on my TODO list to see if we pass the '/unsafe' flag properly onto the C# compiler, but I'm glad to hear that this is already solved.

**Comment by Southgrove** [comment]
Will it get fixed in Unity 5.x as well?

**Comment by DustinCampbell** [comment]
That's not a question for C# for VS Code. You'd need to ask this of Unity.

Note: If you add `<AllowUnsafeBlocks>true</AllowUnsafeBlocks>` to your Unity .csproj, I would expect it to work in C# for VS Code.

**Comment by Southgrove** [comment]
Oh, sorry. I thought we had unity people here too.
Thanks for the tip.

**Comment by DustinCampbell** [comment]
@roblourens: Did updating Unity fix this issue for you?

**Comment by roblourens** [comment]
This is @Southgrove's issue ported from our repo

**Comment by DustinCampbell** [comment]
Ah, sorry about that @roblourens

**Comment by DustinCampbell** [comment]
@Southgrove: Were you able to update Unity to 2017.1 (as @Leopotam) or did the workaround that I mentioned help?

**Comment by Leopotam** [comment]
@Southgrove  [unity 2017.1 f1 beta](https://unity3d.com/ru/unity/beta)

> Editor: Defines in mcs.rsp are added to .csproj files generated for MonoDevelop, Xamarin Studio, Visual Studio Code & JetBrains Rider

**Comment by DustinCampbell** [comment]
I'm going to go ahead and close this issue. @Southgrove, please let me know if updating Unity does not address this problem for you.
