### ISSUE TITLE
Unable to download package - OmniSharp

### ISSUE THREAD

**Issue by avikenjale** [OmniSharp/omnisharp-vscode#1511]
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

VS Code version:
1.12.2

C# Extension version:
1.9.0

## Steps to reproduce
Download OmniSharp extension

## Expected  behavior
Should download package correctly after any C# file opened in VSCode editor.

## Actual behavior
Getting Following error:

Downloading package 'OmniSharp (.NET 4.6 / x64)' Failed at stage: downloadPackages
Error: unable to get local issuer certificate

**Comment by avikenjale** [comment]
After changing following setting, `true` to `false`  it worked.

`"http.proxyStrictSSL": false`

**Comment by CodeSwimBikeRunner** [comment]
Where? @avikenjale
