### ISSUE TITLE
C# extension cannot start omnisharp on Linux due to wrong casing of 'omnisharp' executable

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#152]
1. Install daily build of .NET CLI
2. Install the 1.0.0-rc2 build of the C# extension

Result:
[INFO] Starting OmniSharp at '/home/greggm/clicon'...
[ERROR] Error: Could not fnd launch file in /home/greggm/.vscode-alpha/extensions/ms-vscode.csharp-1.0.0-rc2/.omnisharp. Expected 'run', 'omnisharp', 'omnisharp'

Expected:
Omnisharp starts

This is from:

    omnisharp-vscode\src\omnisharpPath.ts(14):const omnisharpExeFileName = process.platform === 'win32' ? 'omnisharp.exe' : 'omnisharp';
    omnisharp-vscode\src\omnisharpPath.ts(41):        throw new Error(`Could not fnd launch file in ${filePathOrFolder}. Expected '${runFileName}', '${omnisharpFileName}', '${omnisharpExeFileName}'`);

The issue is that the file casing is wrong.

**Comment by DustinCampbell** [comment]
@MattGertz -- because Linux has a case-sensitive file system, the C# extension fails to start the OmniSharp server. It works on Windows and OS X perfectly, but fails on Linux. Does this meet the bar for escrow?

**Comment by MattGertz** [comment]
Yes, I would definitely take this to Escrow.  I'll send a note to TPTB.

**Comment by DustinCampbell** [comment]
OK. I just sent you an email that you can use to start the conversation.
