### ISSUE TITLE
Debugger won't launch nor attach on Mac OSX El Capitan

### ISSUE THREAD

**Issue by rocifier** [OmniSharp/omnisharp-vscode#1520]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```

VS Code version: `1.12.2`

C# Extension version: `1.10.0`

## Steps to reproduce
Use the default configured launch.json for .NET Core (replacing the paths with the actual dll paths).
Open the workspace for a netcoreapp1.1 project (.csproj format)
1) Try to press .NET Core Launch (web).
2) Because that fails, try attach to process.

## Expected  behavior
1) .NET Core Launch would work (as `dotnet run` does).
2) A list of processes would be shown that I can attach the debugger to.

## Actual behavior
1) Error: `Debug adapter process has terminated unexpectedly`

2) Info: `Please set up the launch configuration file for your application. command 'csharp.listProcess' not found`

Consequently, I am unable to debug dotnet core at all.

**Comment by gregg-miskelly** [comment]
Lets tackle your second issue first, as that one is easier - this means you haven't activated the C# extension yet in your VS Code instance. Open up a .cs file and that one should go away. @WardenGnaw do you know if we have a bug here that this does this, or is this a VS Code bug?

For your first issue - can you follow the instructions in https://github.com/OmniSharp/omnisharp-vscode/wiki/Diagnosting-%22Debug-adapter-process-has-terminated-unexpectedly%22 to tell us where this is crashing?

**Comment by rocifier** [comment]
Hi @gregg-miskelly thanks for your reply. I had .cs files open in the editor, so I have tried closing all documents and then VS Code, and then re-opening VS Code and a .cs file in the project. I can see syntax highlighting and intellisense, but I still get the same error when using attach.

I will try following those instructions for the first issue.

**Comment by rocifier** [comment]
Unfortunately for the first issue I'm not seeing any system logs generated from the "terminated unexpectedly" message. I caused it to crash at 9:09am but here is my screenshot after reloading:

[Attached Screenshot](http://i.imgur.com/BTdDV0B.png)

**Comment by rocifier** [comment]
It seems I need to enable logging? I tried following this https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging but my configuration looked slightly different so I have inserted the logging here, is it correct? Because it didn't generate the file in my home folder:

[Attached Screenshot](http://i.imgur.com/GP9ovMm.png)

**Comment by WardenGnaw** [comment]
@gregg-miskelly I think this would be a bug on us for now. However, that should not be happening since it should register the command on startup. https://github.com/OmniSharp/omnisharp-vscode/blob/5ca3c5de10eb1e970a2fa60184312b62197993f0/package.json#L334

We filed an issue to VS Code about this a while back. https://github.com/Microsoft/vscode/issues/26335

**Comment by rocifier** [comment]
Hi. I reinstalled the extension and both use cases now work perfectly. I think it may have been an issue completing a double upgrade without restarting VS Code between each upgrade, or something like that. You may close this issue, thanks.

**Comment by gregg-miskelly** [comment]
Glad to hear it!
