### ISSUE TITLE
autocomplete issue for < when I add blank right after <

### ISSUE THREAD

**Issue by PeikangHu** [OmniSharp/omnisharp-vscode#1521]
## Environment data
`dotnet --info` output:

```
Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.3

VS Code version: Version 1.12.2 (1.12.2)
C# Extension version: 1.10.0
```

## Steps to reproduce

Type in:
for (int i=0;i</*when I type in blank, it autocomplete Action*/)

Thanks.

like: for(int i = 0; i<Action )

## Expected  behavior

for(int i = 0; i< )
if it is for loop, could you disable autocomplete for "<" ?

## Actual behavior

for(int i = 0; i<Action )

**Comment by DustinCampbell** [comment]
Thanks! Great bug! It appears as though our completion provider is [incorrectly registered](https://github.com/OmniSharp/omnisharp-vscode/blob/v1.10.0/src/omnisharp/extension.ts#L60) to trigger on '<'.
