### ISSUE TITLE
Test Result should show more details (Suggestion)

### ISSUE THREAD

**Issue by avikenjale** [OmniSharp/omnisharp-vscode#1527]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

VS Code version:
1.12.2

C# Extension version:
1.10.0

## Steps to reproduce
Run NUnit test using newly introduced feature, link above test method 'run test'

## Expected  behavior
Should show test results with more details, like what we see after running 'dotnet test' command:

NUnit Adapter 3.8.0.0: Test execution started
Running all tests in <<project_location_folder>>

NUnit3TestExecutor converted 1 of 1 NUnit test cases
NUnit Adapter 3.8.0.0: Test execution complete
Failed   test_method_assert()
Error Message:
 Shouldly.ShouldAssertException : 4
    should be
2
    but was not
Test Run Failed.
Stack Trace:
   at Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T](T actual, Func`2 specifiedConstraint, Object originalActual, Object originalExpe
cted, Func`1 customMessage, String shouldlyMethod)
   at Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected, Func`1 customMessage)
   at Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected)
   at webapi.test.Models.HazardTests.model_properties_should_not_change() in <<project_location_test_file>>

Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
Test execution time: 2.2615 Seconds

## Actual behavior
NUnit Adapter 3.8.0.0: Test discovery starting
NUnit Adapter 3.8.0.0: Test discovery complete
NUnit Adapter 3.8.0.0: Test execution started
Running selected tests in <<Project_Location_Folder>>
NUnit3TestExecutor converted 1 of 1 NUnit test cases
NUnit Adapter 3.8.0.0: Test execution complete

Total tests: 1. Passed: 0. Failed: 1. Skipped: 0

**Comment by bernardbr** [comment]
It's an NUnit's issue, and it's already opened: https://github.com/nunit/nunit3-vs-adapter/issues/329

**Comment by DustinCampbell** [comment]
Thanks for the assist @bernardbr!
