### ISSUE TITLE
Unable to debug/run netcoreapp1.1 webapi project which has a reference to netstandard1.6 class library

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-vscode#1529]
_From @thammadi on May 26, 2017 7:32_

Using Visual Studio Code 1.12.2 on Windows 7 Pro

## Steps to reproduce
1) Create a webapi (dotnet new webapi) "TestWebApi"
2) Create a class library (dotnet new classlib) "TestClassLibrary"
3) Add Microsoft.AspNetCore.Mvc reference to "TestClassLibrary"
3) Change TargetFramework for "TestClassLibrary" to netstandard1.6 (in TestClassLibrary.csproj)
4) Cut and past Controller folder from "TestWebApi" to "TestClassLibrary"
5) Add "TestClassLibrary" reference to "TestWebApi" (dotnet add reference ..\TestClassLibrary\TestClassLibrary.csproj)
6) Modify ConfigureServices (Startup.cs) method in "TestWebApi" as
```C#
services.AddMvc()
        .AddApplicationPart(typeof(ValuesController).GetTypeInfo().Assembly)
        .AddControllersAsServices();
```
and also add appropriate using statement
7) Hit F5 to debug

## Expected  behavior
Web api to build and run without any issues and also able to access sample api method (api/values)

## Actual behavior
Build error:
System.DllNotFoundException: Unable to load DLL 'combase.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Win32.UnsafeNativeMethods.RoGetActivationFactory(String activatableClassId, Guid& iid, Object& factory)
   at System.Threading.Tasks.AsyncCausalityTracer..cctor()

Note: `dotnet build` on individual projects work fine
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```

_Copied from original issue: dotnet/cli#6699_

**Comment by DustinCampbell** [comment]
_From @livarcocc on May 29, 2017 1:4_

@DustinCampbell any idea on even how to direct this? I don't believe the exception above is coming from the CLI.

**Comment by DustinCampbell** [comment]
This should be moved to C# for VS Code at https://github.com/OmniSharp/omnisharp-vscode.

**Comment by DustinCampbell** [comment]
FWIW, I was unable to reproduce this issue on Windows 10:

![image](https://cloud.githubusercontent.com/assets/116161/26603309/34fa5f12-453b-11e7-927d-7dd89c677d74.png)

**Comment by gregg-miskelly** [comment]
@DustinCampbell is there a reason you think this is a C# extension issue? Since this is a build failure, doesn't seem like this is the right place for the issue.

In case this is helpful: AsyncCausalityTracer is part of coreclr ([see source](https://github.com/dotnet/coreclr/blob/68f72dd2587c3365a9fe74d1991f93612c3bc62a/src/mscorlib/src/System/Threading/Tasks/AsyncCausalityTracer.cs#L85)). My understanding is that it wouldn't normally be logging such events, so @thammadi must have something running on their box which has enabled that ETW provider.

@thammadi I am assuming you are on Windows?

**Comment by DustinCampbell** [comment]
It wasn't clear to me where the issue was actually happening, so I figured this was as good a place as any to investigate. Now that I look more closely, I definitely see that you're right. It's trying to P/Invoke something that isn't present on Windows 7. @livarcocc, can you help re-route?

**Comment by JamieKeeling** [comment]
What was the resolution to this issue?

**Comment by JamieKeeling** [comment]
What was the resolution to this?

**Comment by DustinCampbell** [comment]
I'm not 100%. It turned out not to be a C# for VS Code issue, which is why it was closed here.

**Comment by JamieKeeling** [comment]
Agreed - I'm on VS 2017 and having the exact same problem. Unfortunately the raised issues seem to trail off with no resolution.

Unfortunately installing Windows 10 isn't an option for me right now as I'm using a corporate machine.
