### ISSUE TITLE
Feature-Request: Document/Selection Formatting to support vertical alignment

### ISSUE THREAD

**Issue by PradeepKumarRajamanickam** [OmniSharp/omnisharp-vscode#1534]
It would be nice to have an option in settings to align the variable assignments vertically when format document is called. I know that there are extensions like [vscode-align](https://github.com/steve8708/vscode-align) but the problem is, after manually invoking [vscode-align](https://github.com/steve8708/vscode-align) if you invoke format document the entire vertical alignment is reset to default format.

**Comment by DustinCampbell** [comment]
Thanks for the request!

@Pilchie: Do we have a request for this on https://github.com/dotnet/roslyn.

**Comment by DustinCampbell** [comment]
I suspect https://github.com/dotnet/roslyn/issues/16088 is probably the right issue to track. Does that look right to you @Pilchie?

**Comment by Pilchie** [comment]
Yes.  Looks right to me.
