### ISSUE TITLE
Autocomplete class member and method sorting priority in drop-down list

### ISSUE THREAD

**Issue by alex-birch** [OmniSharp/omnisharp-vscode#1535]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

VS Code version:
 1.12.2 (1.12.2)
C# Extension version:
1.10.0

## Steps to reproduce
Imagine a class with the following property and method

```
public class SomeClass
{
   public int Foo { get; set; }
   public void ZBar()
   {
   }
}

public static class SomeClassExtensions
{
   public static Extend(this SomeClassInst)
   {
   }
}
```

Now I use that class somewhere like this:
```
var inst = new SomeClass();
inst. // now I hit <CTRL> <SPACE>
```

## Expected  behavior
Get a sorted list of members relevant to me in priority order. IE:

Class Members:
- Foo
- ZBar
Referenced Extension Members:
- Extend
Other dot net possibilities:
- attribute
- checked
- class
- ctor
- cw
... etc.
I have to scroll down a long way to see the members. I end up having to go to the class and then viewing the member names and then going back to type.

## Actual behavior

Alphabetized list of all the available dotnet members and the relevant class members are hidden in a big long list.

**Comment by DustinCampbell** [comment]
Thanks for the request! We're unlikely to make a change like this without also making it in Visual Studio as well.

@Pilchie: Do we already have an issue filed for sorting like this in https://github.com/dotnet/roslyn?

**Comment by DustinCampbell** [comment]
This sounds similar to https://github.com/dotnet/roslyn/issues/16685.

**Comment by Pilchie** [comment]
Yes, although in the example it looks like snippets are showing up after `.`, which doesn't seem right...

**Comment by DustinCampbell** [comment]
Unfortunately, we don't control that at all. VS Code inserts snippets into the completion list based on the "editor.snippetSuggestions" option. I'm not sure whether our CompletionItems could provide a "sortText" value that would allow snippets to be sorted last.

@jrieken: Do you know of a way this could be achieved with VS Code's API?

**Comment by jrieken** [comment]
Yeah, you can do something here. It is complex. So, there is *default*-sorting and *ranked*-sorting. The former (default-sorting) comes into play when we collect all completion items from all providers and *before* we show them in the UI. The default-sorting uses the `sortText`-property of a completion item and if there is no `sortText` we fall back to the `label` (hence the alphabetical sort in most cases). Now, before we show the completions in the UI we take the text left of the cursor and  score each completion item against it. For instance `bk<cursor>` scores against `black_hole` but  scores higher against `black_knight` (matching on two *strong* characters). So, despite the initial (alphabetical) sorting they are now re-sorted. 

![jun-01-2017 18-24-23](https://cloud.githubusercontent.com/assets/1794099/26689904/a164fcc6-46f7-11e7-8515-ae294616e1e6.gif)

In case of equal scores (just having `b` above) the initial sorting is used to resolve the conflict. So, if you make OmniSharp return completions in *smart* order we should honour it as long as the user hasn't typed anything yet. When something is typed, we use as a strong signal to now reveal/resort the best matches.

**Comment by jrieken** [comment]
> Yes, although in the example it looks like snippets are showing up after ., which doesn't seem right...

Yeah, (static) snippets are kind of stupid and we have no means to statically know the scopes in which they make sense or not...

**Comment by Pilchie** [comment]
We address that in VS basically by allowing them to only show at the start of "statement contexts".

**Comment by lukemurray** [comment]
So is there an outcome here?

**Comment by DustinCampbell** [comment]
> So is there an outcome here?

The outcome is that we won't do this specifically for VS Code. Instead, we'll wait until it is implemented for VS as part of Roslyn and then leverage that work. We have a goal of ensuring that we have some consistency between the C# editing behavior in VS, VS for Mac, and VS Code. VS for Mac has a similar feature already and it's on our backlog for VS as well. Once that happens there, we'll be able to do it here. Actually, until it happens in Roslyn, we wouldn't be able to implement it for VS Code anyway. So, we'll use https://github.com/dotnet/roslyn/issues/16685 to ultimately track the feature.

The rest of the discussion here is around the nuance of snippet completion and how the completion list is sorted, which is very useful information.

**Comment by dubeg** [comment]
Is this something that could be done in Omnisharp, now that Visual Studio has it? If I'm in the right issue, that is. I'm speaking of the new filter options in intellisense in VS 2017. 

I recognize that filtering buttons is not `Get a sorted list of members relevant to me in priority order`, but it's  something that could help fill the need behind this request.

**Visual Studio - Intellisense**
Icons in the bottom bar provides filtering for bunch of things: locals, properties, fields, methods, ..

![vs-intellisence-filtering](https://user-images.githubusercontent.com/6020602/45589919-18137d80-b8fc-11e8-803d-5f97aa92e1f4.png)

**Comment by rchande** [comment]
@dubeg This issue was discussing whether it would be possible to order the completion list in a smarter-than-alphabetical order. I don't believe that Visual Studio has implemented that yet. Regarding the filter tab, that would also need to be implemented as a VS Code platform feature (cc @jrieken )
