### ISSUE TITLE
Roslyn extensions gotten by PackageReference is not working.

### ISSUE THREAD

**Issue by itn3000** [OmniSharp/omnisharp-vscode#1536]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```
VS Code version: 1.12.2
C# Extension version: 1.10.0

## Steps to reproduce

1. create console project by `dotnet new`
2. add ClrHeapAllocationAnalyzer(https://www.nuget.org/packages/ClrHeapAllocationAnalyzer/) to PackageReference
3. open the project folder by vscode
4. Open Program.cs and add `object x = 0;` in Main method
5. save it

## Expected  behavior

following warning is displayed in problems(quoted from `dotnet build` output).
```
warning HeapAnalyzerBoxingRule: Value type to reference type conversion causes boxing at call site (here), and unboxing at the callee-site. Consider using generics if applicable 
```

## Actual behavior

no warning displayed in problem.

**Comment by DustinCampbell** [comment]
Unfortunately, we don't support analyzers today. This is being tracked by https://github.com/OmniSharp/omnisharp-vscode/issues/43.

**Comment by itn3000** [comment]
Oh, sorry for creating duplicated issue.
I hope it would be supported.

**Comment by DustinCampbell** [comment]
It's not a problem at all! We do hope to get to this eventually. Note that analyzers should still run and return errors during build.
