### ISSUE TITLE
Intellisense activating inside of strings

### ISSUE THREAD

**Issue by v-codeel** [OmniSharp/omnisharp-vscode#154]
(Migrated from https://github.com/Microsoft/vscode/issues/5051)

- VSCode Version: 0.10.11
- OS Version: Windows 10 (also repros on OSX)

(Code examples will be in C#, but also repro's with other languages)

Scenario 1 Repro:
1. `var x = "%%`
2. With the cursor at `%%`, Type `C`
3. Code Completion suggestions are shown.
![image](https://cloud.githubusercontent.com/assets/10519323/14332053/be020618-fbfc-11e5-97d1-668ce22db799.png)

Scenario 2 Repro:
1. `Console.WriteLine("%%)`
2. Intellisense will be showing. Click elsewhere in the file to dismiss it.
3. Type `(`
4. Intellisense is shown again.
![image](https://cloud.githubusercontent.com/assets/10519323/14332327/e327a668-fbfd-11e5-867c-2dcffad8a61d.png)
(This would be normal if it hadn't been previously dismissed.)

**Comment by DustinCampbell** [comment]
Note that the completion that appears inside strings is text token based and includes snippets. These are included by default in VS Code. However, symbol completion is not appearing inside strings.

The signature help issue should already be fixed.
