### ISSUE TITLE
Highlight `throw` expression

### ISSUE THREAD

**Issue by andy-hanson** [OmniSharp/omnisharp-vscode#1540]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         ubuntu.16.10-x64
 Base Path:   /opt/dotnet/sdk/1.0.4
```
VS Code version: 1.11.0-insider
C# Extension version: 1.9.0

## Steps to reproduce

Type this code:

```cs
public static void A(string str) => throw new Exception(str);
public static void B(string str) { throw new Exception(str); }
```

## Expected  behavior

Highlights the `throw` keyword.

## Actual behavior

![shot](https://cloud.githubusercontent.com/assets/5387404/26748879/2de7efb8-47b7-11e7-995a-1acf1fe37e14.jpg)

**Comment by DustinCampbell** [comment]
This issue was moved to dotnet/csharp-tmLanguage#69

**Comment by DustinCampbell** [comment]
Thanks for filing! I moved it to the csharp-tmLanguage repo, where the official C# TextMate grammar lives.
