### ISSUE TITLE
Remote debug application published by buildserver: File not found when hitting breakpoint

### ISSUE THREAD

**Issue by langsweirdt** [OmniSharp/omnisharp-vscode#1543]
INFO: I don't think this is a bug, but rather ignorance on my side or some missing piece in the documentation....

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version:
Version 1.12.2

C# Extension version:
Version 1.12.2

## Steps to reproduce

1. have your application built, packaged and deployed using a separate buildserver (atlassian bamboo in this case), or any 3th machine for that matter.
2. setup your application server (ubuntu 16.04 in this case) and development machine (mac os 10.12) following the remote debugging instructions from: https://github.com/OmniSharp/omnisharp-vscode/wiki/Attaching-to-remote-processes
3. start the remote debugging process, trigger the remote app to hit a breakpoint

## Expected  behavior
Debugging works :-) As in: VSCode allows to step through the source code.

## Actual behavior
VSCode displays an error message in the lines of:
Unable to open 'HealthCheckMiddleware.cs': File not found (/Users/bamboo-user/bamboo-agent-home/xml-data/build-dir/MY-PRJ-JOB1/src/MyNamespace.Api/Middleware/HealthCheckMiddleware.cs).

So the debugger is searching for the original source file on the build agent (which is no longer relevant nor accessible in this scenario), instead of the development machine. I don't know enough about this process but the only way for the debugger to know about this path is if it is included in the files (I assume PDB's) that got deployed to the application server after the build. So my question: why is this path used, and can it be overwritten somehow?

I have tried changing the variables "pipeCwd": "${workspaceRoot}" and sourceFileMap in my launch.json, but that does not seem to change anything.

Thanks a lot!

**Comment by gregg-miskelly** [comment]
@langsweirdt you need to add a `sourceMap` to your launch.json to fix this.

**Comment by langsweirdt** [comment]
@gregg-miskelly Thank you for your reply. You made me realise my mistake: I used the wrong paths in the sourceFileMap entries. It should be like this:

`
"sourceFileMap": {
    "/Users/bamboo-user/bamboo-agent-home/xml-data/build-dir/MY-PRJ-JOB1": "${workspaceRoot}"
}
`
However, this also means this path will change as the 'MY-PRJ-JOB1' part is variable (could change each build/deploy). Which is not so convenient...

**Comment by gregg-miskelly** [comment]
@langsweirdt in case this helps fix that: the C# compiler does support a '/pathmap' option that I _believe_ lets you change the paths that are in your PDBs. So you could add something to your projects that does something like 'if (officialBuild) { add_path_map(<rootDir>, "/bamboo-official-builds")' so the paths in the PDB will always start with '/bamboo-official-builds'.
