### ISSUE TITLE
Inconsistent ordering above unit tests

### ISSUE THREAD

**Issue by masaeedu** [OmniSharp/omnisharp-vscode#1544]
Very minor nit: I just noticed that the "debug test", "run test" and "n references" indicators can appear in any jumbled up order above unit tests:

![demo](https://r7g9vq.by3302.livefilestore.com/y4m-yg0QEyXyPP3Uq6U_SKrjy9pND92M6JgwQ8Qa44lFWTaDBQPbcwLsbREvNDA9Ykl-wirhnG2s-H_TTvJbRavoqKSc5_ISfyobAZhPTevcJyjOMfksvucn_QAm2Sg_C4uckGK96Q7E7PAsvJS0AJSZEZt6b7jP9FSPH5JQf2XvXByCjkO2jhUcU-YQM2bN6SGKfGEiR5Lz5VOf_hHwzA7RQ/Code_2017-06-05_13-20-15.png?psid=1)

Not really sure if this is a general problem with VS Code or specific to Omnisharp.

## Environment data
**`dotnet --info` output:** 
```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\


Microsoft .NET Core Shared Framework Host



  Version  : 2.0.0-preview1-002111-00

  Build    : 1ff021936263d492539399688f46fd3827169983
```
**VS Code version:** 
```
1.12.2
19222cdc84ce72202478ba1cec5cb557b71163de
```
**C# Extension version:** 
```
1.10.0
```
## Steps to reproduce
 - Create a C# unit test project using `dotnet new xunit`
 - Write some unit tests
 - Wait for CodeLens suggestions to appear above unit test functions (might have to reload Omnisharp until the issue manifests itself)

## Expected  behavior
Consistent relative ordering of indicators above unit tests

## Actual behavior
Arbitrary relative ordering of indicators above unit tests.

**Comment by DustinCampbell** [comment]
Thanks for filing this issue! We're already tracking it https://github.com/OmniSharp/omnisharp-vscode/issues/936.
