### ISSUE TITLE
Error: end of central directory record signature not found

### ISSUE THREAD

**Issue by sameer-kumar** [OmniSharp/omnisharp-vscode#1549]
## Environment data
`dotnet --info` output:

> Updating C# dependencies...
> Platform: win32, x86_64
> 
> Downloading package 'OmniSharp (.NET 4.6 / x64)' (15684 KB) .................... Done!
> Downloading package '.NET Core Debugger (Windows / x64)' (43510 KB) .................... Done!
> 
> Installing package 'OmniSharp (.NET 4.6 / x64)'
> Installing package '.NET Core Debugger (Windows / x64)'
> Failed at stage: installPackages
> Error: end of central directory record signature not found
> 
> Finished

VS Code version:

> 1.12.2

C# Extension version:

> 1.10.0

## Steps to reproduce

> F1
> Debug: Download .NET Core Debugger

## Expected  behavior

> Installation of .Net core debugger package should succeed.

## Actual behavior

> ERROR installing debugging package

**Comment by gregg-miskelly** [comment]
@sameer-kumar I believe what this means is that the file that was downloaded got corrupted along the way. Can you try restarting VS Code and try the download again?

**Comment by sameer-kumar** [comment]
I tried all but no success.
This is what I did to make it work:

Download the debugger from https://vsdebugger.blob.core.windows.net/coreclr-debug-1-10-1/coreclr-debug-win7-x64.zip

Extract the debugger zip it here:

C:\Users\<USER>\.vscode\extensions\ms-vscode.csharp-1.10.0\.debugger

It works like a charm.

**Comment by gregg-miskelly** [comment]
Glad you got it to work. No idea why you saw the problem in the first place.

**Comment by DustinCampbell** [comment]
It sounds like this can be closed?

**Comment by DustinCampbell** [comment]
Closing this. It doesn't seem actionable at this point.

**Comment by satano** [comment]
Hello

I ran into the same issue.

- VS Code version 1.16.1
- C# Extension version 1.12.1

Downloaded and "installed" debugger as @sameer-kumar said. But still got the same error with OmniSharp package.

> Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' 	Retrying from 'https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.23.2.zip' Skipping package '.NET Core Debugger (Windows / x64)' (already downloaded).
> 
> Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'
> Failed at stage: installPackages
> Error: end of central directory record signature not found
> 
> Finished

I made it work with same principle - downloaded package manually and extracted it into **.omnisharp** folder next to the **.debugger** folder.

**Comment by paolofulgoni** [comment]
The same here...

VS code 1.15.1
C# extension 1.12.1

```
Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' 	Retrying from 'https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.23.2.zip' Downloading package '.NET Core Debugger (Windows / x64)' 	Retrying from 'https://vsdebugger.blob.core.windows.net/coreclr-debug-1-12-5/coreclr-debug-win7-x64.zip' 
Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'
Failed at stage: installPackages
Error: end of central directory record signature not found
```

**Comment by DustinCampbell** [comment]
It sounds like the download was corrupted. Does restarting VS Code fix it?

**Comment by paolofulgoni** [comment]
No, I tried several times, but I got the same error all the times.
No issues when downloading from chrome

**Comment by gregg-miskelly** [comment]
@paolofulgoni are you behind a proxy server? If so, there are instructions in https://github.com/OmniSharp/omnisharp-vscode/issues/1712 that you want to follow.

**Comment by paolofulgoni** [comment]
Yes, I am, thanks for the suggestion!
