### ISSUE TITLE
Locate OmniSharp launch executable more robustly

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-vscode#155]
This is a follow-up work item to PR #153. That change addressed a problem where searching for the OmniSharp launcher was failing on Linux because we assumed that the underlying system was case-insensitive. We had fixed it by simply changing the case of the executable that we searched for, but this is not necessarily robust against future OmniSharp changes.

**Comment by gregg-miskelly** [comment]
BTW: 'fnd' is spelled wrong in that error message too.

**Comment by DustinCampbell** [comment]
thanks Gregg!
