### ISSUE TITLE
Autocomplete symbols from namespaces that haven't been used yet

### ISSUE THREAD

**Issue by sttz** [OmniSharp/omnisharp-vscode#1560]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4
```
VS Code version: 1.13.0
C# Extension version: 1.10.0

## Steps to reproduce
There's no way to autocomplete a symbol from a different namespace for which there has been no using directive added yet.

## Expected  behavior
I'm coming from MonoDevelop/Xamarin Studio/Visual Studio Mac, where it's possible to press ctrl-alt-space to bring up intellisense completions for all symbols in all referenced assemblies. Choosing one of these suggestions then automatically adds the necessary using directive as well.

This enables autocomplete to work with any symbol and frees the user from worrying in which namespace a symbol resides and wether that namespace is used already.

I'm not suggesting adding all symbols to the default intellisense list. Just like in MD/XS/VSM, it should be a key combination that can be used to enable showing all known symbols.

## Actual behavior
With VSCode I have to type out the full symbol name before I can bring up the quick fix menu to add the using directive. Typing out the full name is cumbersome and error prone.

Also, the quick fix menu cannot be opened immediately at all times, requiring to backtrack to add the using directive. E.g. when adding a field to a class, I have to type out the field name before I can go back to the field type to use the quick fix menu. The same applies to methods and properties.

**Comment by DustinCampbell** [comment]
Thanks for the request! Completion list support in C# for VS Code is built on Roslyn, and we're tracking this improvement at https://github.com/dotnet/roslyn/issues/7053. cc @Pilchie.
