### ISSUE TITLE
Disable references code lens

### ISSUE THREAD

**Issue by andy-hanson** [OmniSharp/omnisharp-vscode#1570]
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  18.1
 OS Platform: Linux
 RID:         linuxmint.18.1-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

VS Code version: 1.14.0-insider
C# Extension version: 1.10.0

## Steps to reproduce

Open any file, see references code lens

## Expected  behavior

I would like a way to disable the code lens.

## Actual behavior

According to Microsoft/vscode#10238 there is no way to disable references from within vscode. Could this be an option in omnisharp.json so I can use the xunit codelens but not the references codelens?

**Comment by DustinCampbell** [comment]
Good request. Thanks!

**Comment by anfomin** [comment]
+1

**Comment by teize001** [comment]
+1

**Comment by pnloyd** [comment]
+1
