### ISSUE TITLE
OmniSharp picks up F# projects and gives back C# errors for fs files

### ISSUE THREAD

**Issue by NinoFloris** [OmniSharp/omnisharp-vscode#1571]
## Environment data
`dotnet --info` output: 2.1.0-preview1-006329 (suddenly preview 2 is 2.1.0 preview 1)
VS Code version: latest insiders
C# Extension version: 1.11.0-beta4

## Steps to reproduce
Have a simple project tree with an F# lib and a C# host, this triggers (after load) C# errors for F# files

**Comment by DustinCampbell** [comment]
@NinoFloris: Is this a new issue with this release of C# for VS Code?? We have known problems with F# projects when they are not yet built (see https://github.com/OmniSharp/omnisharp-vscode/issues/371).

If it's a new issue, could you provide a simple repro project?

**Comment by NinoFloris** [comment]
Alright for future reference, it seems to be fixed by removing the FSharp.NET.Sdk from the Project Sdk attribute, this must have conflicted with each other now that Microsoft.NET.Sdk does all of the F# work, confusing OmniSharp in some way.

Oh this is great, I'm going to cherish this build until preview 2 is released as everything seems to work 💯 

Again thank you for your swift help and fixes for these issues, it is really appreciated on my end and I'm not the only one.

**Comment by DustinCampbell** [comment]
FWIW, I have a good idea of how to address issues with F#, but it'll have to happen after I'm back from vacation. The quick responses are going to have to slow down for a bit. :smile:

**Comment by NinoFloris** [comment]
I would love some of that, do those plans by a small chance also include support for assembly metadata scanning or sharing type info in another way? So C# projects can reference F# types with autocomplete? That would be huge

**Comment by DustinCampbell** [comment]
Unfortunately, no. OmniSharp is built on Roslyn, which does not natively support F#.

**Comment by mohd-akram** [comment]
I'm still experiencing this issue (which causes red squiggly lines everywhere) and it was introduced in the last couple of versions. I'm using .NET Core 1 so cannot remove `FSharp.NET.Sdk`. Is it fixed in 1.12?
