### ISSUE TITLE
In which conditions browser can be not launched?

### ISSUE THREAD

**Issue by xperiandri** [OmniSharp/omnisharp-vscode#1573]
I created a launch.json as in fable-compiler/Fable#979 and when I run it browser does not launch.
Why could this happen?
As I didn't get answer on StackOwerflow I ask here.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```
VS Code version: 1.13.1
C# Extension version: 1.10.0

## Steps to reproduce
1. dotnet new fable
2. add specified `launch.json`
3. start debugging

## Expected  behavior
Browser launches

## Actual behavior
Browser does not launch

_______________
Reposted from https://github.com/Microsoft/vscode/issues/28723#event-1125524688

**Comment by gregg-miskelly** [comment]
The debugger waits for the target app to write a line to stdout that meets the following condition:

```C#
    if (serverOutput.StartsWith("Now listening on", StringComparison.Ordinal))
```

**Comment by xperiandri** [comment]
@gregg-miskelly could you post a link to the source code line so that we have it here in history?

**Comment by gregg-miskelly** [comment]
@xperiandri this part of the debugger is closed source

**Comment by gregg-miskelly** [comment]
@xperiandri can we close this issue now?

**Comment by xperiandri** [comment]
Yes, thanks.
