### ISSUE TITLE
Incorrect indentation character(s) used when formatting code

### ISSUE THREAD

**Issue by smarts** [OmniSharp/omnisharp-vscode#1574]
## Environment data
`dotnet --info` output: (this has nothing to do with compilation)
VS Code version: `1.13.1`
C# Extension version: `1.10.0`

## Steps to reproduce
1. VS Code [relevant] defaultsetting:
```json
{
  "editor.detectIndentation": true,
  "editor.insertSpaces": true,
  "editor.tabSize": 4,
}
```
1. VS code user settings:
```json
{
  "editor.insertSpaces": false,
  "[csharp]": {
    "editor.insertSpaces": true
  }
}
```
1. open a C# file that uses spaces for indentation
1. format the document (alt-shift-f on Windows or right-click in the document and choose Format Document)
## Expected  behavior
the configured indentation is used:
```
indentation strategy <= [
  detected indentation strategy,
  language-specific indentation strategy,
  global indentation strategy].firstNonEmptyValue()
```

## Actual behavior
tabs are used for indentation in C# files - (i assume it's just using the global `editor.insertSpaces` value, ignoring `editor.detectIndentation` and the language-specific `editor.insertSpaces`.)

**Comment by Aciho** [comment]
I'm currently having the opposite problem - formatting the document always replaces tabs with spaces, ignoring all editor settings. Is it possible this behaviour was just reversed, without fixing the bug?

**Comment by DustinCampbell** [comment]
Looking at the change that was merged, no that's not possible. Could you file a new issue with the settings that you have specified?

**Comment by Aciho** [comment]
I could do that. Or I could just update to 1.15 🤦

**Comment by DustinCampbell** [comment]
Sorry, I don't understand your reply. Does that fix the issue?

**Comment by Aciho** [comment]
Yeah, I was just using an old version. Sorry to bother you.

**Comment by DustinCampbell** [comment]
Ah - got it! No worries! Glad you got it working.
