### ISSUE TITLE
The project system 'DotNetProjectSystem' threw exception during initialization.

### ISSUE THREAD

**Issue by developerTN** [OmniSharp/omnisharp-vscode#1578]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:
 v1.9-alpha3 release
## Steps to reproduce
I had a problem with VScode , it didn't underliny for me errors in red so I downloaded  v1.9-alpha3 release and added a line in my settings.js with omnisharp path

## Expected  behavior
errors should be underlined. 

## Actual behavior
An error has been thrown The project system 'DotNetProjectSystem' threw exception during initialization.
And errors are still not being underlined

**Comment by DustinCampbell** [comment]
@developerTN: I'm a bit confused. Where did you download a v1.9-alpha3 of C# for VS Code? There's been no such release. Could you provide a bit more information? For example, what led to believe you needed to download an old release?

**Comment by developerTN** [comment]
Hi,
I found in a this ticket https://github.com/OmniSharp/omnisharp-roslyn/issues/375
I was googling my issue ,which is errors are not highlighted.

**Comment by DustinCampbell** [comment]
That's from a year ago and the exception is the old DNX stuff. I'd be really surprised if it's the same issue.

Please don't use v1.9-alpha3 of omnisharp-roslyn. That's very unlikely to work with a more recent .NET Core SDK. Instead, use the OmniSharp release that's included with the C# for VS Code that you have installed (I assume that's 1.10.0?).

If possible, please provide the following information:

1. Run `dotnet --info` from your project folder and paste the output here.
2. Remove your `"omnisharp.path"` setting and relaunch VS Code on your project. Copy and paste the OmniSharp Log from the Output pane here.
3. What sort of project is this? Is it a `project.json`-based .NET Core project, or is it csproj-based?

**Comment by developerTN** [comment]
1.
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
2.
Starting OmniSharp server at 18/06/2017 à 13:38:42
    Target: c:\vega

OmniSharp server started
    Path: C:\Users\Nourhene\.vscode\extensions\ms-vscode.csharp-1.10.0\bin\omnisharp\OmniSharp.exe
    PID: 6044

OmniSharp: -s c:\vega --hostPID 6300 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
[info]: OmniSharp.Startup
        Omnisharp server running using Stdio at location 'c:\vega' on host 6300.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\vega
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuild will use local Visual Studio installation.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        No solution files found in 'c:\vega'
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: c:\vega\Vega.csproj
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file 'c:\vega\Vega.csproj'.
c:\vega\Vega.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.CSharp.CurrentVersion.targets
   à Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   à Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(IElementLocation elementLocation, String resourceName, Object arg0)
   à Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   à Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, Boolean throwOnFileNotExistsError)
   à Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   à Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   à Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   à Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   à Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   à Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   à Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   à Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   à Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   à Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   à Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   à Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   à Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   à Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   à Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   à Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   à Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   à OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.LoadProject(String filePath, String solutionDirectory, String sdksPath, ILogger logger, MSBuildOptions options, ICollection`1 diagnostics, ImmutableArray`1& targetFrameworks)
   à OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create(String filePath, String solutionDirectory, String sdksPath, ILogger logger, MSBuildOptions options, ICollection`1 diagnostics)
   à OmniSharp.MSBuild.MSBuildProjectSystem.LoadProject(String projectFilePath)

[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\vega'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Startup
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Startup
        Configuration finished.

3.  it 's csproj-based

**Comment by DustinCampbell** [comment]
Ok. From the log, it looks like the Visual Studio 2017 that OmniSharp located doesn't have C# installed into it. Do you have multiple versions of VS 2017 installed? If so, try launching VS Code by typing "code" at a VS 2017 Developer Command Prompt where the VS 2017 install for that command prompt has C# installed.

**Comment by developerTN** [comment]
Yes I have VS 2015 & VS 2017
I did whatyou advised, and still getting the same result

**Comment by DustinCampbell** [comment]
Sure. But you do not have C# installed into VS 2017, correct? The errors shows that MSBuild is not able to find C# targets in your VS 2017 installation.

**Comment by developerTN** [comment]
Hi,
I just installed c#. then retried and this is hat  i m getting
Starting OmniSharp server at 18/06/2017 à 16:12:17
    Target: c:\vega

OmniSharp server started
    Path: C:\Users\Nourhene\.vscode\extensions\ms-vscode.csharp-1.10.0\bin\omnisharp\OmniSharp.exe
    PID: 2560

OmniSharp: -s c:\vega --hostPID 5476 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
[info]: OmniSharp.Startup
        Omnisharp server running using Stdio at location 'c:\vega' on host 5476.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\vega
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuild will use local Visual Studio installation.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        No solution files found in 'c:\vega'
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: c:\vega\Vega.csproj
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

**Comment by DustinCampbell** [comment]
Try doing what the error said to do? This can happen if your projects take a long time for MSBuild to process. It normally shouldn't happen except with largish projects.

**Comment by developerTN** [comment]
Hello dustin,
So I did that , errors are now highlighted (yay!!) but I m not getting the suggestion of how to resolve them ( adding the associated reference causing the error for example)

**Comment by developerTN** [comment]
Hi dustin,
Everything works fine now. I'm getting the expected behaviour
Thank you for supporting me along the way

**Comment by DustinCampbell** [comment]
If you move the editor caret into the squiggle, does a light bulb appear in the margin?

**Comment by developerTN** [comment]
Yes it does, and it shows me indeed how to resolve the error.
Thank you for your support

**Comment by DustinCampbell** [comment]
Excellent! I'm going to add some additional logging to try and clarify some details when this issue occurs. Please let me know if encounter any additional problems.
