### ISSUE TITLE
 Could not find any CSX files

### ISSUE THREAD

**Issue by developerTN** [OmniSharp/omnisharp-vscode#1579]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983

 C# Extension version:
1.10
## Steps to reproduce
open VScode
Errors exist but not highlighted
no suggestion when typing ctrl + space

## Expected  behavior
working with errors highliting

## Actual behavior
when seeing omnishap output , there is  Could not find any CSX files

**Comment by developerTN** [comment]
I hope that somebody from the omnisharp team answers this, as I'm stuck with for more than 1 week

**Comment by filipw** [comment]
are you trying to use VS Code to edit CSX (C# script) files?

If so, this message indicates no files have been find (recursively) in the folder currently being open - make sure that CSX files are really located there (also, permissions are important).

If you are not explicitly trying to work with C# scripts, then this is not an error of any sort - this message is purely informational and simply means that Omnisharp will not provide any language services for C# scripts, but only for MSBuild / project.json projects.

**Comment by developerTN** [comment]
no. I m only working with c# classes. Asp.net Core and angular. If it just informational, so why Errors are not being highlighted ?

**Comment by DustinCampbell** [comment]
Note: this is not a bug. This is just an informative message in the OmniSharp Log that it didn't find CSX files. Since you aren't using CSX, that's 100% expected.

Please provide the requested information in the other bug you filed. We can't answer your question without digging in further.
