### ISSUE TITLE
'System.Text.RegularExpressions does not exist' in .csx files

### ISSUE THREAD

**Issue by remcoros** [OmniSharp/omnisharp-vscode#1581]
## Environment data
`dotnet --info` output:

> .NET Command Line Tools (2.0.0-preview3-006474)
> 
> Product Information:
>  Version:            2.0.0-preview3-006474
>  Commit SHA-1 hash:  3aa22300ac
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.15063
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview3-006474\
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.0-preview3-25415-01
>   Build    : 0fb328316c72fef971a096d14f93b2474290210e
> 

VS Code version: 1.13.1
C# Extension version: 1.10.0

## Steps to reproduce

- Create a .csx file and use 'System.Text.RegularExpressions' like in the screenshot below

## Expected  behavior

No errors

## Actual behavior

![image](https://user-images.githubusercontent.com/130373/27350025-70e5effe-55f9-11e7-9f32-8bc4c37e9f3a.png)

I'm not sure if this is even valid in .csx files. I read the content of this .csx file in a powershell script and use Add-Type to run it (see: [https://github.com/remcoros/til](https://github.com/remcoros/til)). It runs fine from powershell.

If you have an idea and can point me in the direction, I could look into a fix.

**Comment by filipw** [comment]
Thanks for the report - this is indeed a bug.
I have a fix locally already, but I need to make sure that this will not break other things accidentally 😀

![](http://g.recordit.co/xlcJf5e24o.gif)

**Comment by remcoros** [comment]
ah, that's quick 👍 nice.
