### ISSUE TITLE
After i add some nuget package, I can not the code intelicense immediately unless i restart the Visual Stuido Code 

### ISSUE THREAD

**Issue by chenxizhang** [OmniSharp/omnisharp-vscode#1583]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

VS Code version:
![image](https://user-images.githubusercontent.com/1996954/27412734-418f6f92-5729-11e7-8b63-173520197601.png)

C# Extension version: 1.10.0

## Steps to reproduce
1. dotnet new web
2. dotnet add package Microsoft.Graph
3. dotnet restore

## Expected  behavior
My expected behavior is when I restored the package, I can get the code intellisense in the Code Editor。
I switch to one cs file, on the top , type "using Microsoft. " I want get "Graph“ in the Intellisense list。

## Actual behavior
I CAN not get this behavior， unless I restart the vs code and everything is fine.

**Comment by bernardbr** [comment]
The same behavior occurs with me. And it occurs frequently when I do the Restore using the popup menu from IDE.

**Comment by DustinCampbell** [comment]
I just tried this and was not able to repro with the instructions. I tried executing the `dotnet` commands at both the command prompt and in VS Code's integrated terminal. I also tried using the restore popup. Are there more specific steps that can reliably repro this issue?

**Comment by THuffam** [comment]
Same issue here.  Add a nuget package and intellisense does not recognise it.  Have to restart VS Code to resolve. 
I have a similar, maybe related issue, when I rename a class file name, intellisense highlights the class and ctor as errors (eg The name space mynamespace already contains a definition for myoriginalclassname) - so have to restart VS Code to fix.

**Comment by jsheely** [comment]
This is labelled as needs more info. Here is more info

https://github.com/OmniSharp/omnisharp-vscode/issues/1661

**Comment by yarrgh** [comment]
I'm being affected as well. Very annoying to have to restart vscode to get intellisense on the newly added nuget packages

**Comment by yarrgh** [comment]
As a temporary workaround, you can run the reload command in vscode. 

Press Ctrl+Shift+P then type reload

Faster than restarting vscode

**Comment by develorem** [comment]
I'm getting this as well. In my case I added package from dotnet cli. 
Happened with both EF package, and Autofac. Restart VS code fixes it.

**Comment by DustinCampbell** [comment]
I'm not going to close this until we have a build of C# for VS Code that includes the fix.

**Comment by DustinCampbell** [comment]
This issue has been fixed in the 1.14 milestone. We just released our [first beta of 1.14](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.14.0-beta1) if you're interested in giving it a spin. Follow [these instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) to a beta release of C# for VS Code.
