### ISSUE TITLE
Debugger can not step in symbol loaded assembly

### ISSUE THREAD

**Issue by jwnoz** [OmniSharp/omnisharp-vscode#1584]
## Environment data
`dotnet --info` output:

 .NET Command Line Tools (1.0.4)
Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4

VS Code version: 1.13.1
C# Extension version: 1.10.0

## Steps to reproduce
1.  Create a mstest project
2.  Create a classlib project
3.  Reference classlib project from mstest project
4.  Debug mstest project

## Expected  behavior
Able to step into classlib assembly

## Actual behavior
classlib code is treated as non-user code

Debug console shows following:
Loaded '/home/Public/src/Ant.Tests/bin/Debug/netcoreapp1.1/Ant.Tests.dll'. Symbols loaded.
Loaded '/home/Public/src/Ant.Tests/bin/Debug/netcoreapp1.1/Ant.dll'. Symbols loaded.
Step into: Stepping over non-user code 'Ant.Worker..ctor'
The program '[15435] dotnet' has exited with code 0 (0x0).

**Comment by gregg-miskelly** [comment]
@jwnoz:
1. You are debugging the mstest project using the code lens buttons? (links above the method)
2. The Ant.Worker contructor is user-written and doesn't have any attributes to block debugging of it (ex: DebuggerNonUserCode)?
3. You see this with all methods in the Ant assembly?
