### ISSUE TITLE
Debugging unit tests always uses coreclr launch, even for non-coreclr project

### ISSUE THREAD

**Issue by AHelper** [OmniSharp/omnisharp-vscode#1586]
## Environment data
`dotnet --info` output:

> .NET Command Line Tools (1.0.0-preview2-003131)
> 
> Product Information:
>  Version:            1.0.0-preview2-003131
>  Commit SHA-1 hash:  635cf40e58
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  6.1.7601
>  OS Platform: Windows
>  RID:         win7-x64

VS Code version: `1.13.1`
C# Extension version: `1.10.0`

## Steps to reproduce
Using [example.zip](https://github.com/OmniSharp/omnisharp-vscode/files/1098983/example.zip) as base net46 xunit workspace:
Set a breakpoint on Console.WriteLine line in Test method
Click `debug test` on Test method

## Expected  behavior
Breakpoint should be hit

## Actual behavior
Breakpoint is missed, the debug launch uses a coreclr configuration and vsdbg outputs

> The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.

Looking at https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/features/dotnetTest.ts#L116 the launch configuration generated has the type hard-coded to "coreclr" while this assumption may be (and in this case is) invalid.  It appears that the csharp.unitTestDebuggingOptions setting is used as a basis for the launch configuration, but the type is set after the fact.

Manually setting the type to "clr" in the extension allows the debugger to properly attach to the process and debugging works as expected.

I'm not sure about the effort required to auto-detect the launch type, however a suitable workaround would be to allow type to be specified in unitTestDebuggingOptions.

**Comment by gregg-miskelly** [comment]
@AHelper Do you know if the unit test worker process will run as a 32-bit or 64-bit process when using desktop CLR?

**Comment by AHelper** [comment]
@gregg-miskelly 64-bit process.

**Comment by gregg-miskelly** [comment]
@AHelper in that case, this sounds pretty easy to do via unitTestDebuggingOptions if needed. @DustinCampbell would OmniSharp know what framework a test is supposed to run in?

**Comment by gregg-miskelly** [comment]
@DustinCampbell would OmniSharp know what framework a test is supposed to run in? Or should I just allow 'type' to be set like AHelper suggested.

**Comment by DustinCampbell** [comment]
Today, there's no input that tells us what the TargetFramework is unless it's specified in the project.

**Comment by gregg-miskelly** [comment]
Okay, I will make a tweak to let 'type' be settable.

**Comment by DustinCampbell** [comment]
To be clear, if there's a single TargetFramework, we can do the right thing in OmniSharp. However, there's a further experience that needs built around having a switcher for TargetFramework, similar to Debug|Release, x86|x64, etc.

**Comment by gregg-miskelly** [comment]
@AHelper I created a [fix](https://github.com/gregg-miskelly/omnisharp-vscode/tree/UnitTestDebugType) for you. Can you give it a try and verify it actually works end-to-end for your scenario?

1. Download [csharp-1.12.0-beta3.zip](https://github.com/OmniSharp/omnisharp-vscode/files/1174301/csharp-1.12.0-beta3.zip)
2. Change the extension from .zip to .vsix
3. Follow [beta release instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) to install

**Comment by gregg-miskelly** [comment]
Actually, hold up one sec. I accidentally included more changes than I wanted to in that .vsix.

**Comment by gregg-miskelly** [comment]
Okay, .zip updated. This should now work.

**Comment by AHelper** [comment]
Just got to testing this on my end, the fix works perfectly, thanks!

**Comment by gregg-miskelly** [comment]
Great! This fix will ship in 1.12.
