### ISSUE TITLE
OmniSharp doesn't honor propertygroup condition when loading csproj

### ISSUE THREAD

**Issue by yaronyg** [OmniSharp/omnisharp-vscode#1587]
## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

Note: I'm using an old version because Azure IoT Edge Gateway requires it

VS Code version: 1.13.1
C# Extension version: 1.10.0

## Steps to reproduce
Create a SLN and add csproj and set the TargetFramework inside of a PropertyGroup with a condition, for example:
```XML
  <PropertyGroup Condition="'$(Framework)'=='1.1.1'">
      <TargetFramework>netstandard1.3</TargetFramework>
  </PropertyGroup>
```

## Expected  behavior
When VSCode Project loading parses the SLN which contains this csproj I expect it to evaluate the condition and process the TargetFramework as defined. This works fine when I run 'dotnet build' for example (and yes, I made sure the environment variable is set). So this would cause OmniSharp to recognize the project as being netstandard1.3.

## Actual behavior
OmniSharp thinks the project is .NETFramework,Version=v0.0 and all sorts of failures start coming from OmniSharp.

**Comment by DustinCampbell** [comment]
Hi @yaronyg: I'm a bit confused by the behavior you described. Could you provide a project that reproduces the issue?

**Comment by yaronyg** [comment]
This came up as part of https://github.com/yaronyg/IotEdgeHackfest where we were trying to create a tool to make it much easier to create modules for Azure IoT Edge. We were focused on .net core. Edge officially supports core 1.1.1 but we were working with a partner that wanted to try out 2.0 as well. But we needed to be able to switch back and forth. Originally what we wanted to do was to use a PropertyGroup Condition in the csproj files to let us control the TargetFramework. That way if we configured the machine for 1.1.1 then the csprojs would load as 1.1.1 and if we configured the machine for 2.0 it would load the csproj as 2.0. Obviously this is a very limited case because if any 2.0 only code is put in the module then loading as 1.1.1 would blow everything up. But since we were just kicking the tires of the 2.0 support we weren't too worried about that.

So I was surprised when I tried to load the csproj that the PropertyGroup condition didn't appear to be processed but instead the PropertyGroup was just ignored.

BTW, I completely get that this is an edge case of an edge case. But it was just surprising.

**Comment by DustinCampbell** [comment]
Thanks for the clarification!

Looking at your repro steps, is `Framework` a property that you're setting in your project or somewhere on the command-line? This property isn't defined by .NET Core targets.

**Comment by yaronyg** [comment]
It's a property I set in the environment.

**Comment by DustinCampbell** [comment]
I see now -- thanks!

FWIW, I was able to verify that this scenario works just fine with the latest [v1.12-beta2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.12.0-beta2) of C# for VS Code.

Here's what I did to verify:

1. At the console:

    ```
    > mkdir test
    > cd test
    > dotnet new console
    > code .
    ```
2. In VS Code, open the .csproj for the project and delete the `<TargetFramework>` property.
3. Add the following `<PropertyGroup>` to the .csproj and save.

    ```XML
    <PropertyGroup Condition="'$(Framework)'=='1.1.1'">
        <TargetFramework>netstandard1.3</TargetFramework>
    </PropertyGroup>
    ```
4. Close VS Code
5. At the console:

    ```
    > set Framework=1.1.1
    > code .
    ```

6. Verify that project opens successfully with no errors.
7. Close VS Code.
8. At the console:

    ```
    > set Framework=1.1.2
    > code .
    ```
9. Verify that project has errors due to the `<TargetFramework>` not being set.

If you're interesting in trying the beta, follow the [Installing Beta Releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases).

**Comment by yaronyg** [comment]
That's awesome! Thank you!

**Comment by DustinCampbell** [comment]
@yaronyg: I hope this is working for you in the latest release. Do let me know if it's not.
