### ISSUE TITLE
Debug install fails with no diagnostics if 'dotnet --info' doesn't return the RID

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#159]
Repro steps:
1. Install older build of .NET CLI (build 2202 seems to cause this, probably others would too)
2. Install VS Code+C# extension
3. Try to restore debugger

Result:
Error saying "Error while installing .NET Core Debugger" whenever I open VS Code with the extension installed. When I hit the "View Log" button next to it, nothing happens (no log opens).

Notes:
On the following line, we will throw an error if the dotnet --info doesn't return the RID:
   https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/coreclr-debug/util.ts#L137

But the error from the exception is dropped on the floor here:
  https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/coreclr-debug/main.ts#L89

Suggested changes:
1. Write the call and output from dotnet --info to the log
2. Write the error message to the log

**Comment by gregg-miskelly** [comment]
@MattGertz I know you were asking about upgrade testing. Do you care enough about this scenario that you would want to take the fix, or should we move this to RTM?

**Comment by MattGertz** [comment]
RTM, and we can educate in the interim.

**Comment by gregg-miskelly** [comment]
Fixed for post-RC2
