### ISSUE TITLE
The .NET CLI tools cannot be located. .NET Core debugging will not be enabled.

### ISSUE THREAD

**Issue by realuser** [OmniSharp/omnisharp-vscode#1603]
## Environment data
`dotnet --info` output:
`'dotnet' is not recognized as an internal or external command, operable program or batch file.`

VS Code version: 
1.13.1

C# Extension version:
1.11.0

## Steps to reproduce
Open C# file in Visual Code and install extension

Here's my user experience:
I opened a C# file for the first time in VS Code. It suggests I use the C# extension.  Install the extension. The output window says:

```
Updating C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp (.NET 4.6 / x64)' (15622 KB) .................... Done!
Downloading package '.NET Core Debugger (Windows / x64)' (43510 KB) .................... Done!

Installing package 'OmniSharp (.NET 4.6 / x64)'
Installing package '.NET Core Debugger (Windows / x64)'

Finished
Failed to spawn 'dotnet --info'

```

Then I get a message:
`The .NET CLI tools cannot be located. .NET Core debugging will not be enabled. Make su...`
`Disable this message in user settings`
`Get .NET CLI tools`
`Close`

Should this work out of the box? Or is there some dependency that is missing that I need? The extension says it has no dependencies.

**Comment by gregg-miskelly** [comment]
@realuser Are you trying to do .NET Core debugging?

**Comment by realuser** [comment]
I don't know what that is so I'm going to say no.  In what scenario would I want that?

**Comment by gregg-miskelly** [comment]
Windows has three different versions of .NET --

* Desktop (Full) Framework - this is the traditional version of .NET that has been around for a long time now. It offers stability and the widest possible API surface (example: it includes support for UI technologies of WinForms and WPF).
* .NET Core - this is a newer version of .NET which is designed to be smaller (so it can work better in things like MicroServices), server/console-only, cross-platform and more command line friendly
* Windows Store (a.k.a. UWP) .NET - if you are trying to make a Windows Store App, this is what you would use

VS Code support is mostly tailored to .NET Core. If this is what you want you need to install the [.NET Core SDK](https://www.microsoft.com/net/core/#windowscmd).

If you want one of the other versions of .NET, you can certainly use this extension to provide editing, but I would recommend [Visual Studio 2017](https://www.visualstudio.com/) if you want a full IDE.

**Comment by gregg-miskelly** [comment]
@realuser do you have any other questions, or can I close this?

**Comment by realuser** [comment]
Ok thank you that answers it I guess. Just found it to be an odd user experience for it to be an error upon install, but admittedly I didn't read the extension description which does have as it's first bullet point: "Lightweight development tools for .NET Core."
