### ISSUE TITLE
Debugger breaks on ghost breakpoints.

### ISSUE THREAD

**Issue by JohnLozano** [OmniSharp/omnisharp-vscode#1607]
I'm experiencing an issue where my debugger keeps breaking on breakpoints that have since been removed. After I've made it through the code in question and removed a breakpoint during a debug session, the debugger will continue to pause code execution at the ghost breakpoint until it is killed and a new session is started. Especially annoying if you put a break point on something like a foreach(), Linq, or multi-line statement.

## Environment data
`dotnet --info` output: 
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
VS Code version: 1.13.1
C# Extension version:
1.10.0
## Steps to reproduce

Attach debugger to .NET app running in a docker container.
Set break point in code.
Perform an action in the app to trigger the break point.
Remove the breakpoint while the debugger session is still going.
Perform the action again and observe the debugger breaking on a nonexistent breakpoint.

## Expected  behavior
Debugger should not pause code execution after the breakpoint has been removed.

## Actual behavior
Debugger continually pauses code execution where no breakpoint is currently set.

**Comment by gregg-miskelly** [comment]
@JohnLozano What version of the debugger do you have installed in the target container? (you can check version.txt)

**Comment by JohnLozano** [comment]
root@10c344e4f20a:/vsdbg# cat version.txt
15.1.10519.1 commit:8c288976a491f9b38bcb0febfcd5aba296893758

**Comment by gregg-miskelly** [comment]
@JohnLozano I wasn't able to reproduce your problem. Questions:
1. After you delete the breakpoint, is it gone from VS Code's breakpoint list (lower left side of debug tab)
2. Are you using a sourceMap in your launch.json?
3. Can you [Enable logging](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging) and either save the full log, or if you don't want to share out the full thing, copy out the request/responses from the 'setBreakpoints' requests/responses and the 'breakpoint' events.

The logging should look something like:
```
-> (C) {"command":"setBreakpoints","arguments":{"source":{"path":"d:\\proj\\cliInfiniteLoop\\Program.cs","name":"Program.cs","checksums":[{"algorithm":"SHA1","checksum":"9cdc1f1db64de21ebeeb7b6761bf3c5349f3aa7a"},{"algorithm":"SHA256","checksum":"52f85b76f0a534ffccd7744b97307fceac018d793c349ab0b36c4b1138af7dad"},{"algorithm":"SHA1","checksum":"7e0b2f702dcc1b8e83d6835975755eaa45600e8d"},{"algorithm":"SHA256","checksum":"5a3d1d355ecddd8d626f586e5551775eee02e03399ae7135efaf8c87c06f53ab"}]},"lines":[12],"breakpoints":[{"line":12}],"sourceModified":false},"type":"request","seq":4}
<- (R) {"seq":6,"type":"response","request_seq":4,"success":true,"command":"setBreakpoints","message":"","body":{"breakpoints":[{"id":1,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":12}]}}
...
<- (E) {"seq":20,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":1,"verified":true,"source":{"name":"Program.cs","path":"d:\\proj\\cliInfiniteLoop\\Program.cs","checksums":[]},"line":12,"endLine":12}}}
...
-> (C) {"command":"setBreakpoints","arguments":{"source":{"name":"Program.cs","path":"d:\\proj\\cliInfiniteLoop\\Program.cs","sourceReference":0,"checksums":[{"algorithm":"SHA1","checksum":"9cdc1f1db64de21ebeeb7b6761bf3c5349f3aa7a"},{"algorithm":"SHA256","checksum":"52f85b76f0a534ffccd7744b97307fceac018d793c349ab0b36c4b1138af7dad"},{"algorithm":"SHA1","checksum":"7e0b2f702dcc1b8e83d6835975755eaa45600e8d"},{"algorithm":"SHA256","checksum":"5a3d1d355ecddd8d626f586e5551775eee02e03399ae7135efaf8c87c06f53ab"}]},"lines":[],"breakpoints":[],"sourceModified":false},"type":"request","seq":15}
<- (R) {"seq":50,"type":"response","request_seq":15,"success":true,"command":"setBreakpoints","message":"","body":{"breakpoints":[]}}
```

**Comment by JohnLozano** [comment]
@gregg-miskelly 
1. The breakpoint list in the debug tab gets updated appropriately.
2. I am using the following in my launch.json configuration
    ```
    "sourceFileMap": {
        "/app": "${workspaceRoot}" 
    }
3. Here are the setBreakpoints calls I collected from my console logs. All I did was set and remove the breakpoint.
```
-> (C) {"command":"setBreakpoints","arguments":{"source":{"path":"c:\\path\\to\\file\\ImageController.cs","name":"ImageController.cs","checksums":[{"algorithm":"SHA1","checksum":"71a20a9afc72a677f65934585cfa8e161c3b1adf"},{"algorithm":"SHA256","checksum":"05f78f2e1e9fb7f627c64da5e379dd9a204f4fc1b8f5644ff5844f9d0f61915b"},{"algorithm":"SHA1","checksum":"ed9f7013c9df69b4362695c2df6dcdea3fd58ac5"},{"algorithm":"SHA256","checksum":"29746dd8aad7b663468c462f3617fe94ed6511fcb9954ae4027c53730d970366"}]},"lines":[60],"breakpoints":[{"line":60}],"sourceModified":false},"type":"request","seq":14}
<- (R) {"seq":294,"type":"response","request_seq":14,"success":true,"command":"setBreakpoints","message":"","body":{"breakpoints":[{"id":3,"verified":true,"source":{"name":"ImageController.cs","path":"c:\\path\\to\\file\\ImageController.cs","checksums":[]},"line":60,"endLine":60}]}}
-> (C) {"command":"setBreakpoints","arguments":{"source":{"path":"c:\\path\\to\\file\\ImageController.cs","name":"ImageController.cs","checksums":[{"algorithm":"SHA1","checksum":"71a20a9afc72a677f65934585cfa8e161c3b1adf"},{"algorithm":"SHA256","checksum":"05f78f2e1e9fb7f627c64da5e379dd9a204f4fc1b8f5644ff5844f9d0f61915b"},{"algorithm":"SHA1","checksum":"ed9f7013c9df69b4362695c2df6dcdea3fd58ac5"},{"algorithm":"SHA256","checksum":"29746dd8aad7b663468c462f3617fe94ed6511fcb9954ae4027c53730d970366"}]},"lines":[],"breakpoints":[],"sourceModified":false},"type":"request","seq":15}
<- (R) {"seq":295,"type":"response","request_seq":15,"success":true,"command":"setBreakpoints","message":"","body":{"breakpoints":[]}}
```

**Comment by gregg-miskelly** [comment]
@JohnLozano when you run into the problem, can you check if the file casing for whatever the real value of the `path` in the two `setBreakpoints` requests is the same?

**Comment by JohnLozano** [comment]
@gregg-miskelly in both the ```setBreakpoints``` command and response the ```path``` field has the correctly cased path to the file on disk.

**Comment by gregg-miskelly** [comment]
What does the `stopped` event look like in the log?

**Comment by mmaguigan** [comment]
This is driving me batty. Has anyone looked into this any further. I notice this problem when attaching to a debugger via docker exec on Windows. I set a breakpoint and all is well, until I clear it and it won't clear. I'm writing some automation to be used by other engineers and this is a pretty big deal given the size of the application to be debugged.

**Comment by gregg-miskelly** [comment]
We don't currently have any guesses as to the cause. Are you by chance able to share your project?

**Comment by mmaguigan** [comment]
Unfortunately not :(
I'll have to see if I can reproduce it on a dummy project.

**Comment by JohnLozano** [comment]
Recently updated the omnisharp plugin to 1.14, unable to reproduce this issue since then.
