### ISSUE TITLE
"run test" code lens mstest doesn't output errors

### ISSUE THREAD

**Issue by jamesikanos** [OmniSharp/omnisharp-vscode#1612]
## Environment data
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.3

VS Code version: Version 1.13.1 (1.13.1)
C# Extension version: 1.11.0

## Steps to reproduce
Create an MSTest project with `dotnet new mstest`.
Create single [TestMethod] with `Assert.Fail("Error Message");`
Select code lens "run test" above method

## Expected  behavior
I expect to see "Error Message" in either the console window or the problems window.

## Actual behavior
Console correctly displays that 1 test has failed but no error messages are available. Problem window is silent.

Actual Output:
```
Running test Banksy.Server.Tests.RegisterTests.BasicRegistration...

Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

  Banksy.Server.Tests -> /git/Banksy.Server.Tests/bin/Debug/netcoreapp1.1/Banksy.Server.Tests.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.93



Total tests: 1. Passed: 0. Failed: 1. Skipped: 0

Running test Banksy.Server.Tests.RegisterTests.BasicRegistration...

Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

  Banksy.Server.Tests -> /git/Banksy.Server.Tests/bin/Debug/netcoreapp1.1/Banksy.Server.Tests.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.96



Total tests: 1. Passed: 0. Failed: 1. Skipped: 0
```

**Comment by DustinCampbell** [comment]
Thanks for reporting! I've noticed this same behavior too.

**Comment by benday** [comment]
I'm still getting this as of yesterday (Jul 30, 2018).  Any updates?

**Comment by akshita31** [comment]
@DustinCampbell We have added the error and the standard output logging in https://github.com/OmniSharp/omnisharp-vscode/pull/2343.

Here is the current output for an error case : 
![errorlog](https://user-images.githubusercontent.com/12554141/43481236-406e37f4-94ba-11e8-9c41-4ddddca53141.PNG)

**Comment by benday** [comment]
@akshita31 -- Can you share how you got that to work?  Because I'm still getting the problem when I try to run using the CodeLens "Run Test" feature.  

Here's a video reproducing the problem.  
https://1drv.ms/v/s!ApAioVNgnHVmh_4C5LzVlgqx9Mtz6w

Thanks,
-Ben

**Comment by rchande** [comment]
@akshita31 Is that an xunit or mstest test?

**Comment by benday** [comment]
MSTest.

**Comment by akshita31** [comment]
@rchande  It is an mstest project. It is the project used in the tutorial here: https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code

**Comment by akshita31** [comment]
@benday The change has been merged into the master branch, however we do not have a release yet with those changes.
However, if you wish to give it a try, you can follow the steps here: https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-the-C%23-extension-to-a-computer-without-internet-connectivity#installing-on-a-computer-that-cannot-connect-to-the-internet, to use the code from the latest master branch, these steps will give a vsix , to install the vsix you could follow the steps here: https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases

**Comment by DustinCampbell** [comment]
@akshita31, @rchande : We *should* be releasing beta VSIXs fairly regularly so that users don't have to go through these steps. We used to do that in the past.
