### ISSUE TITLE
Debugger: It should be point to loop boby when break all for the first time

### ISSUE THREAD

**Issue by qian6** [OmniSharp/omnisharp-vscode#1614]
## Environment data
`dotnet --info` output:
 Runtime Environment:

- OS Name:        ol
- OS Version:     7.1
- OS Platform:    Linux
- RID:                  ol.7.1-x64
- Base Path:        /opt/dotnet/sdk/1.0.4

VS Code version:   1.13.1
C# Extension version: v1.12.0-beta1  

## Steps to reproduce

1. Open the attachment in vscode.
[hwapp.tar.gz](https://github.com/OmniSharp/omnisharp-vscode/files/1118594/hwapp.tar.gz)
2. Press F5.
3. Click Pause.

## Expected  behavior
It can point to 13 lines as following:
![excepted](https://user-images.githubusercontent.com/20922638/27780653-c97a61e2-5ffc-11e7-896c-f35bb51803b1.PNG)

## Actual behavior

![actual](https://user-images.githubusercontent.com/20922638/27780655-cf307d88-5ffc-11e7-8aa2-dce21f43a14c.PNG)

## Investigate

1. I collected the log, hoping to help you analyze.
[log.txt](https://github.com/OmniSharp/omnisharp-vscode/files/1118623/log.txt)
2. If I execute step #2 and step #3 again. It display normally.

**Comment by gregg-miskelly** [comment]
This is a problem with VS Code. It is already fixed in Insiders. It was fixed as part of https://github.com/Microsoft/vscode/issues/25104.
