### ISSUE TITLE
Debug: adapter not respecting threadId for stopped events

### ISSUE THREAD

**Issue by isidorn** [OmniSharp/omnisharp-vscode#1617]
Original comments from user:

- VSCode Version: 1.13.1
- OS Version: Fedora 21

Steps to Reproduce:

1. Place a breakpoint to interrupt execution.
2. Once the breakpoint is hit, step over (F10).

The focus in the call stack window will change from the current thread's call stack to the first call stack in the list. To continue stepping, the correct call stack (thread) must first be selected. 

This make stepping through threaded code quite tedious. 

The expected behaviour is that the focus in the call stack window remains at the top of the call stack for the current thread and doesn't change.

**Comment by isidorn** [comment]
The issue here is that the `stop` event coming from the debug adapter does not respect the threadId for the `next` request from vscode.

Example, there are threads with the following ids 1, 2, 3. User focuses thread 1, preses step, VSCode sends `next` request for threadId: 1, adapter incorrectly sends stopped event for threadId: 2 with allThreadsStopped: true. Adapter should respect the threadId in the `next` request.

As the user is pointing out this makes debugging tedious and it would be great to fix.

**Comment by gregg-miskelly** [comment]
@Anketell is your scenario that you have the same code running on multiple threads and so when you hit step your original breakpoint winds up getting hit on the first thread?

**Comment by Anketell** [comment]
@gregg-miskelly apologies, I didn't mention that I am running C++. FWIT, it was different code running on different threads.

**Comment by gregg-miskelly** [comment]
@Anketell: A few more questions to try and get your bug to the right place:

1. You are using the Microsoft C++ VS Code extension correct?
2. What OS are you on? 
3. If Windows, what debug adapter 'type' in your launch.json?
4. If using MIEngine, are you using LLDB or GDB?
5. The behavior you are seeing is that you hit a breakpoint on a thread other than the main thread, you do a step, and it acts like it is stepping the main thread?

**Comment by Anketell** [comment]
@gregg-miskelly 

1. Yes, I have raised an issue under vscode-cpptools.

2. See above.

3. N/A

4. GDB

5. No. It focuses the correct stack (not main) after the break then steps the correct thread (currently focused) but incorrectly focuses the main thread immediately after the step. 

Having used GDB extensively for well over a decade directly and also with various front ends, it tracks the correct thread. Somewhere in the adaptor it's getting lost.

_Sent from my HTC 0PJA10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gregg-miskelly** [comment]
@Anketell thanks! I will move your issue. Hopefully the folks over there can help.

**Comment by gregg-miskelly** [comment]
This issue was moved to Microsoft/vscode-cpptools#867

**Comment by isidorn** [comment]
@gregg-miskelly please note that I was able to repro also for C# so I think your adapter is suffering from the same problem.

**Comment by gregg-miskelly** [comment]
@isidorn do you know what your repro steps were? In C#, when you are stepping one thread, all the other threads will continue to execute and can hit breakpoints. So depending on what you were doing, what you are seeing may be 'by design'.

**Comment by isidorn** [comment]
@gregg-miskelly sure, here's my c# program. Have a breakpoint on the for loop, line 23. When I step over I would expect that the same thread is always focussed, and not that they switch in-between. This might be expected behavior but does not seem smooth to me

```
using System;
using System.Threading;

namespace dotnet
{

    class Program
    {
        static void Main()
        {
            Thread thread1 = new Thread(new ThreadStart(A));
            Thread thread2 = new Thread(new ThreadStart(A));
            thread1.Start();
            thread2.Start();
            thread1.Join();
            thread2.Join();
        }

        static void A()
        {
            Console.WriteLine("hello there 5");
            Thread.Sleep(100);
            for (var i = 0; i < 100; i++) {
                Console.WriteLine("isidor");
            }
            String.Format(null, 12);
            Console.WriteLine('A');
        }

        static void B()
        {
            Thread.Sleep(1000);
            String.Format(null, 12);
            Console.WriteLine('B');
        }
    }
}
```

**Comment by gregg-miskelly** [comment]
@isidorn I think the issue is your test app looks to have a typeo -- on line 12 I am assuming you meant to start your second thread using function 'B', but it actually started with 'A' so now you have two threads executing the same code, and they will both hit breakpoints and the experience can be a bit confusing.

**Comment by isidorn** [comment]
@gregg-miskelly thanks, but even if I have the following code and have breakpoints in each for loop the step exeprience will be confusing. E.g. the exectuion will jump between threads, where I would expect that the same thread always has focus

```c#
using System;
using System.Threading;

namespace dotnet
{

    class Program
    {
        static void Main()
        {
            Thread thread1 = new Thread(new ThreadStart(A));
            Thread thread2 = new Thread(new ThreadStart(B));
            thread1.Start();
            thread2.Start();
            thread1.Join();
            thread2.Join();
        }

        static void A()
        {
            Console.WriteLine("hello there 5");
            Thread.Sleep(100);
            for (var i = 0; i < 100; i++) {
                Console.WriteLine("isidor");
            }
            String.Format(null, 12);
            Console.WriteLine('A');
        }

        static void B()
        {
             for (var i = 0; i < 100; i++) {
                Console.WriteLine("isidor");
            }
        }
    }
}
```

**Comment by gregg-miskelly** [comment]
@isidorn Correct. There is no way to prevent the jumps back and forth in C# (unless you don't mind hanging the user's app when they have shared locks). We have talked about, but never implemented, giving the stepping thread a 'head start' where we don't resume the other threads for a little while, but fundamentally this is an unsolvable problem.

**Comment by isidorn** [comment]
@gregg-miskelly thanks for clarification
