### ISSUE TITLE
Debugger:There is no pop Exception Throw when DivideByZeroException

### ISSUE THREAD

**Issue by zhangmn799** [OmniSharp/omnisharp-vscode#1619]
## **# Environment data**
`dotnet --info` output:
OS Name: win10 Enterprise x64
SDK: 1.0.4
VS Code version:1.13.1
C# Extension version: v1.12.0-beta1
## Steps to reproduce
1.open "Command Prompt" as administrator.
1.Create a new project in Command with 'dotnet new console & dotnet restore ' .
2.Open project with VSCode.
3.Add code in main() as following:
int x = 10;
int y = 0;
try{int val = x/y;}//set an BP in there
catch(Exception e)
{
Console>writeLine("this is an exception");
}
4.Debug->BREAKPOINTS->ALL Exceprions
6.F5->F10
## Expected  behavior
It will pop an ExceptionThrow as following:
![image](https://user-images.githubusercontent.com/26423555/27789716-2b1c393e-6020-11e7-9f36-1d3440d9e48e.png)

## Actual behavior
There is an "PAUSED ON EXCEPTION" tag In call stack windows as following:
![image](https://user-images.githubusercontent.com/26423555/27789620-d295a598-601f-11e7-86d4-3b1f300dac0e.png)

**Comment by gregg-miskelly** [comment]
This is a problem with VS Code: https://github.com/Microsoft/vscode/issues/25104. It is already fixed in Insiders.

**Comment by zhangmn111** [comment]
ok, thanks.
