### ISSUE TITLE
Debugger installation fails on Debian.8.2

### ISSUE THREAD

**Issue by caslan** [OmniSharp/omnisharp-vscode#162]
The debugger installation script fails to publish native clrdbg binaries into the debugger folder with no errors causing F5 to give "Unable to launch. Clrdbg is missing." error.

This appears to have started after recent CLI changes we had to react to last week.

**Comment by caslan** [comment]
@MattGertz, @jaredpar, @gregg-miskelly 

An internal user reported this issue to us and we are able to repro. I seems an issue with our supported 'runtime id' declared in the clrdbg package (debian.8.2 vs debian.8) which would be a low-risk fix. Assuming that's the problem do we want to consider this for RC2?

**Comment by MattGertz** [comment]
Is there a workaround, and what does one have to use in a project to get into this state?  (I will give a heads up to .NET War regardless.)

**Comment by caslan** [comment]
You will get into this state whenever you are on Debian OS.

There is an ugly workaround of modifying /etc/os-release file to update the VERSION field from 8 to 8.2 that seems to be pulling in the debugger bits but we are investigating a 'runtime' error we are seeing after that. I don't have data yet whether that is a result of the 'workaround' not working or a separate issue. I'll update you once we know more.

**Comment by MattGertz** [comment]
Thanks.  Keep digging & let us know what you find, and feel free to tee up a fix/PR just in case, so that War can review it and decide.  I've sent mail to War in order to better understand the Escrow bar here.  This process will almost certainly go into my OOF, which is about an hour away, so Jared may be on point for War depending on how fast this turns around.

**Comment by MattGertz** [comment]
Since Ubuntu is in the Debian family tree, is it affected too?

**Comment by gregg-miskelly** [comment]
No, we aren't seeing these problems on Ubuntu.

**Comment by caslan** [comment]
The 'runtime' error we are seeing appears to be a separate coreclr bug. I opened https://github.com/dotnet/coreclr/issues/4263 to track it. Meanwhile I'll prep a PR for this issue.

**Comment by caslan** [comment]
We decided not to take the other issue for RC2. Once we have proper Debian bits we think the issue will go away for RC2. We are going to prep a PR and get this ready to take it to War.

**Comment by caslan** [comment]
Fixed with https://github.com/OmniSharp/omnisharp-vscode/pull/197
