### ISSUE TITLE
[Question] Is it possible to contribute to the project from anybody?

### ISSUE THREAD

**Issue by seunghwanh** [OmniSharp/omnisharp-vscode#1625]
I forked this repository and made some changes in CompletionProvider and CodeActionProvider. 
Is it possible to create a pull request to review my changes? The changes are to auto generate snippets for methods and types, and to convert the expression body members into normal brackets, etc.

**Comment by DustinCampbell** [comment]
Yes, we accept pull requests if you're willing to sign our Contributor License Agreement (CLA). However, note that this is a Microsoft project and we have a goal of aligning the end user experience with Visual Studio and Visual Studio for Mac. Changes like the ones you described might not be appropriate/accepted.

**Comment by DustinCampbell** [comment]
Let me know if you have any further questions.
