### ISSUE TITLE
How to offline install those packages?

### ISSUE THREAD

**Issue by guoboism** [OmniSharp/omnisharp-vscode#1626]
Downloading package 'OmniSharp (.NET 4.6 / x64)' (15622 KB) .................... Done!
Downloading package '.NET Core Debugger (Windows / x64)' (43510 KB) .

Anytime update VSCode or OminiSharp plug, these two packages have to be redownloaded.
But the connections are really slow, here in China.

I hope there is alternative way to install the packages. If we can download and install the packages manually, we can solve it with p2p download tool.

Currently, we can only try different VPN, but none helps.

**Comment by DustinCampbell** [comment]
Hopefully you've seen other issues already reported about this:

* https://github.com/OmniSharp/omnisharp-vscode/issues/1542
* https://github.com/OmniSharp/omnisharp-vscode/issues/747
* https://github.com/OmniSharp/omnisharp-vscode/issues/955

There was a blog post written by a community member just yesterday that shows how to create offline packages for C# for VS Code: https://www.towfeek.se/2017/07/05/enabling-csharp-and-dotnet-core-debugging-in-vs-code-from-an-offline-environment/

**Comment by gregg-miskelly** [comment]
For the next version (1.12), I am also hoping to switch to a new CDN which should improve the download experience in China (see https://github.com/OmniSharp/omnisharp-vscode/issues/1542).

**Comment by clarkis117** [comment]
@DustinCampbell that still requires that npm has online access

**Comment by DustinCampbell** [comment]
@clarkis117: Yes it does, but getting VS Code and C# for VS Code also requires online access. If you're using C# for VS Code at all, you must have had online access at some point.

**Comment by akshita31** [comment]
@newpost The debugger files can be found in the .debugger folder in your extension path - `.vscode/extensions/ms-vscode.csharp-version/.debugger`

**Comment by akshita31** [comment]
@DustinCampbell Can we close this issue now ?

**Comment by DustinCampbell** [comment]
Yes, I think so.
