### ISSUE TITLE
Goto definition for type in tuple

### ISSUE THREAD

**Issue by andy-hanson** [OmniSharp/omnisharp-vscode#1629]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  18.1
 OS Platform: Linux
 RID:         linuxmint.18.1-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

VS Code version: 1.15.0-insider
C# Extension version: 1.11.0

## Steps to reproduce

```cs
class C
{
	(C, C) pair() =>
		(new C(), new C());
}
```
Move the cursor to either `C` in `(C, C)` and goto definition.

## Expected  behavior

Get taken to `C` in `class C`.

## Actual behavior

Don't get taken anywhere.

**Comment by rchande** [comment]
@akshita31 Want to take a look?

**Comment by akshita31** [comment]
Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\


Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

VS Code version: 1.19.0
C# Extension version: 1.13.1

Could you try updating your vscode version and checking whether the issue still persists?

**Comment by DustinCampbell** [comment]
@andy-hanson : Does this still repro for you on the latest version of VS Code and C# for VS Code?

**Comment by filipw** [comment]
This has been resolved - feel free to reopen if it still repros.
