### ISSUE TITLE
Debugger doesnt hit breakpoint when XUnit.net is installed

### ISSUE THREAD

**Issue by jflepp** [OmniSharp/omnisharp-vscode#1630]
## Environment data
`dotnet --info` output:
````
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
````
VS Code version: 1.13.1
C# Extension version: 1.11.0

## Steps to reproduce
Install Xunit.net, csproj:
```` csproj
  <ItemGroup>
    <PackageReference Include="xunit" Version="2.3.0-beta2-build3683" />
     <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta2-build3683" /> 
  </ItemGroup>
````
and then run a dotnet restore

## Expected  behavior
The debugger should hit a breakpoint set

## Actual behavior
The programm runs without hitting any breakpoint

## Already tried
- Reinstalling dotnet core sdk
- Reinstalling c# extension and omnisharp
- Reinstalling vscode

**Comment by gregg-miskelly** [comment]
@jflepp Sorry for the delay in responding.

Questions:
1. What does the debug console output look like?
2. If you add a 'Debugger.IsAttached' check, does that return true?

**Comment by jflepp** [comment]
@gregg-miskelly no problem
here is the debug output:
```
Loaded 'c:\workspace\MDparser\bin\Debug\netcoreapp1.1\parser.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.1.2\mscorlib.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Console.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.1.2\System.IO.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
```

where should i add the `debugger.IsAttached` check?

**Comment by gregg-miskelly** [comment]
@jflepp based on that output, it looks like the debugger is successfully attached, so no need to add the call to Debugger.IsAttached.

Is parser.dll where your break point is set? If so, the warning listed is your problem. See https://github.com/OmniSharp/omnisharp-vscode/wiki/Portable-PDBs for more info.

**Comment by jflepp** [comment]
@gregg-miskelly yes you were right, the breakpoint was set in the parser.dll

i added following line in the csproj:
``` csproj
<DebugType>portable</DebugType>
```
and then i worked

maybe the debugger had problems because xunit is attaching it's portable PDBs to my windows only PDB

thank you for your support and best regards

**Comment by gregg-miskelly** [comment]
Glad to help, and sorry for the delay.
