### ISSUE TITLE
openSUSE Tumbleweed Debugging Support

### ISSUE THREAD

**Issue by aerkefiende** [OmniSharp/omnisharp-vscode#1631]
## Environment data
`dotnet --info` output:

> .NET Command Line Tools (2.0.0-preview2-006497)
>
>Product Information:
> Version:            2.0.0-preview2-006497
> Commit SHA-1 hash:  06a2093335
>
>Runtime Environment:
> OS Name:     opensuse
> OS Version:  20170709
> OS Platform: Linux
> RID:         linux-x64
> Base Path:   /opt/dotnet/sdk/2.0.0-preview2-006497/
>
>Microsoft .NET Core Shared Framework Host
>
>  Version  : 2.0.0-preview2-25407-01
>  Build    : 40c565230930ead58a50719c0ec799df77bddee9

VS Code version: 1.13.1
C# Extension version: 1.11.0

Currently openSUSE Tumbleweed is not supported for debugging. Is there a workaround or are there plans to add support?

**Comment by gregg-miskelly** [comment]
@aerkefiende Please try the latest beta release. Instructions are on https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases

**Comment by aerkefiende** [comment]
1.12beta2 worked fine. Thanks!
