### ISSUE TITLE
Configure excludes is not suitable for mono-repos

### ISSUE THREAD

**Issue by chrmarti** [OmniSharp/omnisharp-vscode#1633]
_From @danielo515 on July 12, 2017 10:49_

Probably related with #26337 and #16115

- VSCode Version: 1.14 insiders
- OS Version: Mac OSx El capitan

Steps to Reproduce:

1. Create any kind of mono_repo, with subfolders including node modules
2. Intellisense will ask you to configure excludes very often

Reproduces without extensions: Yes

Basically the problem is that you can not exclude recursive subdirectories. I have a mono-repo structure, where each package has it's own node_modules folder. I tried with all kind of exclude patterns, but none of them works

```json
{
    "exclude": [
        "node_modules",
        "**/node_modules",
        "**/*.log"
    ]
}
```

_Copied from original issue: Microsoft/vscode#30498_

**Comment by DustinCampbell** [comment]
@chrmarti: I'm not seeing anything in this bug that makes this a C# for VS Code issue. Could you clarify?

**Comment by chrmarti** [comment]
Ack, closing.

**Comment by DustinCampbell** [comment]
Thanks! No worries!
