### ISSUE TITLE
Debugger doesn't provide nice error message when 'program' is set to a path that doesn't exist

### ISSUE THREAD

**Issue by xplicit** [OmniSharp/omnisharp-vscode#1634]
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

VS Code version: 1.13.1
C# Extension version: 1.11.0

## Steps to reproduce

When I hit F5 with following config I get an error 

```
No executable found matching command "dotnet-/home/sergey/Projects/ServiceStack/netcore/ServiceStack.Azure/bin/Debug/netcoreapp1.1/ServiceStack.Azure.Tests.dll
```

it adds prefix `dotnet-` to all commands and of course it can't find it. So debuging does not work in the latest version, in previous version I did not notice any issues with debugging.

```json
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/bin/Debug/netcoreapp1.1/ServiceStack.Azure.Tests.dll",
            "args": [],
            "cwd": "${workspaceRoot}/tests/ServiceStack.Azure.Tests",
            "stopAtEntry": false,
            "console": "internalConsole"
        }
```

**Comment by gregg-miskelly** [comment]
I noticed that you have the .NET Core preview2 installed, but your `program` value is targeting `netcoreapp1.1`. Is that right?

I believe the problem here is that your `program` path is wrong (for this reason or something else), and it looks like the debugger is missing a better error message when this happens.

**Comment by xplicit** [comment]
You're right, it was path issue. The message "file not found" without `dotnet-` prefix and with full path will be good solution for this issue.

**Comment by gregg-miskelly** [comment]
Thanks for confirming. We should have a better experience in the next version.
