### ISSUE TITLE
NUnit "run test" and "debug test" links in VS Code no longer work

### ISSUE THREAD

**Issue by lgreenlee** [OmniSharp/omnisharp-vscode#1635]
## Environment data
`dotnet --info` output:
Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64

VS Code version:
C# Extension version:
1.11.0

## Steps to reproduce
Load an NUnit based unit test
Click "Run Test" on a properly annotated test

## Expected  behavior
Test runs

## Actual behavior
NUnit .NET Core Runner 3.4.0 
Copyright (C) 2016 Charlie Poole
Invalid argument: -method

**Comment by DustinCampbell** [comment]
Any chance you could provide a project that reproduces the issue? From your 'dotnet --info' listing above, it appears that this is an older project.json-based .NET Core project?

**Comment by lgreenlee** [comment]
@DustinCampbell Thanks for the response. Unfortunately the project is a proprietary code base. It is a .NET Core, project.json project. It looks like -method is no longer supported either in dotnet-test-nunit, NUnit or the test runner harness but I suspect OmniSharp is actually initiating the call. It is hard to figure out who is making the call. Using -where "method=MethodName" works though. It seems like the format of the command line args "just" needs to be changed. This worked fine up until a month or two ago when I upgraded VSCode and OmniSharp and things broke.

**Comment by DustinCampbell** [comment]
OmniSharp does have tests for NUnit that are currently passing: https://github.com/OmniSharp/omnisharp-roslyn/blob/master/test-assets/test-projects/LegacyNunitTestProject/project.json.

**Comment by lgreenlee** [comment]
Hmm I am using 3.6.0... I will try 3.5 and see if that makes a difference.

**Comment by DustinCampbell** [comment]
@lgreenlee: Did that address the issue?

**Comment by lgreenlee** [comment]
Unfortunately, it did not

**Comment by DustinCampbell** [comment]
This should now be fixed.
