### ISSUE TITLE
Option for disabling the snippets functionality

### ISSUE THREAD

**Issue by panicoenlaxbox** [OmniSharp/omnisharp-vscode#1641]
Hello,

Have you thought that, in the future, you can disable the snippets functionality? I think that this will be good if you have installed another extension that it's focused only in snippets. In this moment, for example with this extension [C# Snippets](https://marketplace.visualstudio.com/items?itemName=jorgeserrano.vscode-csharp-snippets), when you are going to insert and snippet you have a duplicated entry for every snippet. What is your opinion about this? Thanks and congratulations for your extension!

**Comment by DustinCampbell** [comment]
Unfortunately, we currently don't control how snippets appear in the completion list. This is controlled by the VS Code setting, `"editor.snippetSuggestions"`, which has a default value of `inline`.

**Comment by panicoenlaxbox** [comment]
Thank you for your quick response, I know that it's not a definitive solution but the author of the mentioned extension has writed a post telling how to disable manually some snippets, regardless from who are (sadly in his case it's yours, but it's a solution for any snippet extension) [How to disable the C# snippets for the C# extension of Visual Studio Code](https://geeks.ms/jorge/2017/07/16/how-to-disable-the-c-snippets-for-the-c-extension-of-visual-studio-code)/ Thank you so much, I will close this question, thank you again.
