### ISSUE TITLE
Cant Run (compile / debug) C# code .

### ISSUE THREAD

**Issue by weinand** [OmniSharp/omnisharp-vscode#1642]
_From @Nasr-Z1 on July 16, 2017 13:58_

- VSCode Version: 1.14.4
- OS Version: win7

cant run C# code , i already installed C# plugin , and other plugin to be able to work with C# in VSC ,
what plugin should i install to compile or debug C# thk in advance.

_Copied from original issue: Microsoft/vscode#30806_

**Comment by gregg-miskelly** [comment]
@Nasr-Z1 Are you trying to run/debug .NET Core or full .NET?

**Comment by Nasr-Z1** [comment]
a simple c# program and also .net project

**Comment by gregg-miskelly** [comment]
@Nasr-Z1 That doesn't really answer my question.

.NET Core is the new open source, xcopiable, cross-platform version of .NET designed primarily for web scenarios (though it certainly works well for other command line scenarios also.

.NET Full framework, is the older and more stable version of .NET that comes with Windows and allows creation of not just web and console apps, but really any kind of Windows app.

If you want to use .NET Core follow instructions on https://www.microsoft.com/net/core#windowscmd. You can also use full [Visual Studio](https://www.visualstudio.com/downloads/).

If you are interested in .NET Full Framework - there is some basic scenarios you can do in VS code if you know what you are doing, but unless you are an expert I would highly recommend Visual Studio: https://www.visualstudio.com/downloads/

**Comment by gregg-miskelly** [comment]
@Nasr-Z1 Let me know if you need more help. I am closing this for now.
