### ISSUE TITLE
How to stop auto closing comment?

### ISSUE THREAD

**Issue by Thaina** [OmniSharp/omnisharp-vscode#1643]
## Environment data
version 1.11
VS Code version: 1.14

## Steps to reproduce
type `/*`

## Expected  behavior
Just emit `/*`

## Actual behavior
It emit `/*  */`

I have my habit to switch active block for debugging by using `*/` and `/*` around it. But not only the autocomplete not aware of existing `*/`. When typing `/*`, it emit the unneccessary `*/` to have me delete it. This behaviour should have setting to shut it somewhere

**Comment by DustinCampbell** [comment]
VS Code has a setting to disable automatic closing brackets. You can use `"editor.autoClosingBrackets": false` in your settings.json.

**Comment by Thaina** [comment]
@DustinCampbell Always set that to false for my whole life. And it seem it work only on bracket, not a comment

**Comment by DustinCampbell** [comment]
Unfortunately, it doesn't appear that there's a way to do this in VS Code, though there's an issue tracking it: https://github.com/Microsoft/vscode/issues/1966.

We actually don't do anything special for closing brackets and comments in C# for VS Code. We've defined the delimiters [here](https://github.com/Microsoft/vscode/blob/master/extensions/csharp/language-configuration.json) but the auto-closing behavior is in VS Code itself.

**Comment by Thaina** [comment]
I see thank you very much
