### ISSUE TITLE
Assembly Metadata View did not Support

### ISSUE THREAD

**Issue by ChongWangUBI** [OmniSharp/omnisharp-vscode#165]
Does vscode support Metadata View Support like atom ?
like omnisharp-atom/lib/server/metadata-editor.ts

**Comment by ChongWangUBI** [comment]
by Add a WantMetaData:true in the gotodefine request [typeConvertion.js]
I implement a simple version:
test code in CSharpDefinitionProvider like follow:
<img width="1006" alt="test" src="https://cloud.githubusercontent.com/assets/16005289/14434636/85199110-0046-11e6-9859-daf24b143607.png">

**Comment by Pilchie** [comment]
Definitely need this.

**Comment by ivanz** [comment]
Claiming this one. Have some work in progress already. Will finish off and create a pull request in the next couple of days.

**Comment by ivanz** [comment]
Here is what I managed to do (thanks to ChongWangUBI for the screenshot which gave me a lot of the info that I needed):

![2016-08-16_15-23-19](https://cloud.githubusercontent.com/assets/79742/17702328/67034850-63c5-11e6-832f-b64ee0634350.gif)
