### ISSUE TITLE
Debugger: Call Stack frame duplicate display 

### ISSUE THREAD

**Issue by qian6** [OmniSharp/omnisharp-vscode#1653]
## Environment data
 dotnet --info  output:

- OS Name: Windows
- OS Version: 10.0.15063
- OS Platform: Windows
- RID: win10-x64
- Base Path: C:\Program Files\dotnet\sdk\1.0.4

VS Code version: 1.14.1
 C# Extension version: https://github.com/OmniSharp/omnisharpvscode/releases/download/v1.12.0-beta3

## Steps to reproduce

1. Run command to create dotnet project as following:

   dotnet new console -o hwapp
   cd hwapp
   dotnet restore
   dotnet run

2. Open hwapp project in vscode.

3. Press F5 to start debugging.

5. Observer Call Stack window.

## Expected  behavior
It can display normally.

## Actual behavior
![capture](https://user-images.githubusercontent.com/20922638/28410314-dcd16648-6d6f-11e7-9ffd-7bdffdb1f902.PNG)

**Comment by qian6** [comment]
This issue can reproduce in all OS(windows/mac/Linux)

**Comment by rajkumar42** [comment]
This issue was moved to Microsoft/vscode#31150
