### ISSUE TITLE
Syntax highlighting lost after certain comments

### ISSUE THREAD

**Issue by cateyes99** [OmniSharp/omnisharp-vscode#1659]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```
VS Code version: `1.14.2`
C# Extension version: `1.11.0`

## Steps to reproduce
Create below C# snippet
![image](https://user-images.githubusercontent.com/19678455/28496233-8cb1a694-6fba-11e7-9047-c1f87d90e8aa.png)

## Expected  behavior
The method `F2()` should still have correct syntax highlighting.

## Actual behavior
The method `F2()` doesn't have correct syntax highlighting.

I **notice**:
if I remove the **Line 9**, the the syntax highlighting is back:
![image](https://user-images.githubusercontent.com/19678455/28496257-19dbc84c-6fbb-11e7-8ac4-caa7c95cff45.png)

or remove the **namespance**, the the syntax highlighting is also back:
![image](https://user-images.githubusercontent.com/19678455/28496260-4e033952-6fbb-11e7-9a2c-776680890d53.png)

**Comment by DustinCampbell** [comment]
This issue was moved to dotnet/csharp-tmLanguage#80

**Comment by DustinCampbell** [comment]
Moved over to the csharp-tmLanguage repo where the C# TextMate grammar lives. Note that syntax highlighting in VS Code isn't syntactic at all. Instead, it's handled via regular expressions and is very easy to "trick".
