### ISSUE TITLE
Multi thread debugging: wrong Paused on Breakpoint label 

### ISSUE THREAD

**Issue by isidorn** [OmniSharp/omnisharp-vscode#1667]
Moved from https://github.com/Microsoft/vscode/issues/29547

1. Have a multithreaded C# App
2. One thread hits a breakpoints
3. All threads say "Paused on breakpoints" - the label is misleading, only the the thread that hit the breakpoints should have `"reason": "breakpoint"`

**Comment by gregg-miskelly** [comment]
This doesn't sound like an issue with the C# extension. Following up in the VS Code issue...
