### ISSUE TITLE
launch.json: default value and help text for 'program' is confusing

### ISSUE THREAD

**Issue by stephtr** [OmniSharp/omnisharp-vscode#1668]
## Environment data
`dotnet --info` output: 2.0.0-preview2-006497
VS Code version: 1.14.2
C# Extension version: 1.11.0

## Steps to reproduce
Generate and open a new dotnet core project
Select .NET Core as debugging environment
Select .NET Core tasks

~~tasks.json contains ```"command": "dotnet",```, however since task versions 2.0.0 the task name does not get appended automatically, so by default it should be ```"command": "dotnet build",```~~ (coming directly from VS Code)

launch.json contains ```"program": "${workspaceRoot}/bin/Debug/<target-framework>/<project-name.dll>",```, however according to the tooltip (which shows <project\-name>, containing a backslash) it should be ```<project-name>.dll``` instead of ```<project-name.dll>```.

However even when using ```<project-name.dll>``` debugging is not working, one needs to manually replace both placeholders (the tooltip mentions that the project.json file, not the .csproj file, gets read).

**Comment by gregg-miskelly** [comment]
This is an issue with the tasks.json template which is in VS Code. So closing this issue.

**Comment by stephtr** [comment]
The first part of my issue is an issue within VS Code, but the second one (launch.json) gets generated by this extension.

**Comment by stephtr** [comment]
Ah, am I correct that it was never intended to automatically replace `<target-framework>` and `<project-name>` by their according values and that one has to replace them manually?

**Comment by gregg-miskelly** [comment]
Correct

**Comment by stephtr** [comment]
Oh, then sorry. Maybe it would be useful to state it more clearly in the description (I always thought that is a bug).
Would it be that hard to automatically fetch the used framework and project name?

**Comment by gregg-miskelly** [comment]
We do that. But we can't plugged the vscode templating system that way. To have the C# extension generate things nicely, follow the [instructions](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md#once-for-each-project).

**Comment by stephtr** [comment]
Thank you for the information (To me it was never quite clear that those assets are the task and launch jsons) and sorry for bothering you.

**Comment by gregg-miskelly** [comment]
Its okay. Its good feedback that this is difficult. Is this more understandable:

Default value: "${workspaceRoot}/bin/Debug/<insert-target-framework-here>/<insert-project-name-here>.dll"

Description: "Path to the application dll or .NET Core host executable to launch. Example: '${workspaceRoot}/bin/Debug/netcoreapp1.1/MyProject.dll' 

Where:
'netcoreapp1.1' is the target framework that the project is set to build. This is normally found in the project file as the 'TargetFramework' property.
'MyProject.dll': the name executable file that your project builds. This is normally the same as the project file name.",

**Comment by stephtr** [comment]
In my opinion that would be definitely better.

**Comment by gregg-miskelly** [comment]
Thanks. I will verify that actually displays well in our tool tips. If so, I will make it so.

**Comment by stephtr** [comment]
One thing I noticed is that the `-` in the description tooltip get displayed falsely escaped (`\-`), but that is an issue of VS Code and your example doesn't contain any hyphens.

**Comment by gregg-miskelly** [comment]
@dcu-sharepoint a closed issue is probably not the best place to discuss things, but we are happy to try and help if we can. For documentation about using C# with VS Code, your can start with the [README for this repo](https://github.com/omnisharp/omnisharp-vscode#c-for-visual-studio-code-powered-by-omnisharp), which has links to a bunch of other useful documents for using C# and VS Code.

If you have questions, or suggestions for improvements, please open a new issue and we are happy to try and help.

**Comment by Mona1988** [comment]
I had the same problem and I had to download the version that specified in the console error. And then 
follow the steps in this link.. make sure to open a new command prompt to execute the commands

https://www.microsoft.com/net/learn/get-started/windows

**Comment by OmerPasa** [comment]
It is still confusing to understand how to configure the program in launch.json.  I am still struggling. Would you mind explaining it ?
What I have written:
"program": "${workspaceFolder}/bin/Debug/<netcoreapp5.0>/<E:/Code Scripts/Level.cs>",

**Comment by gregg-miskelly** [comment]
It should be set to the path of your project's output executable. Example: `${workspaceRoot}/bin/Debug/net5.0/MyProject.dll`.
