### ISSUE TITLE
Xamarin project error

### ISSUE THREAD

**Issue by egamma** [OmniSharp/omnisharp-vscode#167]
_From @PierBover on April 10, 2016 7:52_
- VSCode Version:0.10.11
- OS Version: 10.11.3

Steps to Reproduce:
1. Create a blank cross platform Xamarin project
2. Open the project folder in VSCode

I get this error in VSCode

```
[ERROR:OmniSharp.MSBuild.MSBuildProjectSystem] Error initializing task MakeDir: Could not load file or assembly 'Xamarin.iOS.Tasks.Core' or one of its dependencies
[WARNING:OmniSharp.MSBuild.MSBuildProjectSystem] Failed to process project file '/Users/pier/Projects/TestHTTP/iOS/TestHTTP.iOS.csproj'.
[ERROR] Error: Failed to start OmniSharp
```

The project builds fine in Xamarin btw.

_Copied from original issue: Microsoft/vscode#5127_

**Comment by egamma** [comment]
moving to omnisharp-vscode for investigation.

**Comment by PierBover** [comment]
Hi @egamma, can you reproduce the issue?

**Comment by egamma** [comment]
Hi @PierBover the issue was not closed because I cannot reproduce it, it was closed because it was moved to the owners of the OmniSharp extension for vscode, it will be in good hands over there.

**Comment by PierBover** [comment]
Yes, I know. :)

I'm just asking if you can reproduce or not.

**Comment by mikebluestein** [comment]
I get the same error with VSCode 1.0.0 when attempting to load a Xamarin.iOS project:

`[ERROR:OmniSharp.MSBuild.MSBuildProjectSystem] Error initializing task MakeDir: Could not load file or assembly 'Xamarin.iOS.Tasks.Core' or one of its dependencies`

**Comment by DustinCampbell** [comment]
Hi, if you're still experiencing this issue, could you try the latest release of the C# extension, [v1.3.0](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.3.0)? This version adds better support for Mono projects in general, so it'd be great to know if it helps the problem you've been experiencing.

**Comment by DustinCampbell** [comment]
Just pinging here to see if @PierBover and @mikebluestein were able to reproduce with the latest C# extension as requested.
