### ISSUE TITLE
Debugger stopped working after some changes

### ISSUE THREAD

**Issue by fabioluz** [OmniSharp/omnisharp-vscode#1672]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

VS Code version:
1.14.2
C# Extension version:
1.11.0

## Steps to reproduce

Attach a breakpoint - Start debugging

## Expected  behavior

Breakpoint should remain red after build.
Breakpoint should be hit.

## Actual behavior

Breakpoint is greyed after build, with message: "No symbols have been loaded of this document".
Breakpoint doesn't hit.

The debugger used to work when I created the project, but it stopped working after some changes. I tried to delete and create task.json and launch.json again, no luck. The debugger works in a brand new project, though. I probably have done something that "broke" the thing but I have no idea what.

Useful Info:

- I tried to set `<DebugType>portable</DebugType>` in `.csproj`, nothing changes.
- Debugger works fine in VS2017.

Current packages:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="6.1.1" />
    <PackageReference Include="Dapper" Version="1.50.2" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" />
    <PackageReference Include="System.Data.Common" Version="4.3.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.3.1" />
    <PackageReference Include="xunit" Version="2.3.0-beta2-build3683" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta2-build3683" />
  </ItemGroup>
</Project>
```

**Comment by gregg-miskelly** [comment]
@fabioluz if you look in the debug console, do symbols load?
If they do, what message do you get if you hover over your breakpoint?

**Comment by fabioluz** [comment]
No, they don't load. This is what appears in the debugger console: https://pastebin.com/j69yg8aG

When I hover over the breakpoint, I get the message "No symbols have been loaded for this document".

**Comment by gregg-miskelly** [comment]
Are you trying to set a break point in RF.dll? If so, it looks like it is still building a Windows PDB.

```
WARNING: Could not load symbols for 'RF.dll'. 'c:\Projects\RF\bin\Debug\netcoreapp1.1\RF.pdb' is a Windows PDB. These are not supported by the cross-platform .NET Core debugger.
```

**Comment by fabioluz** [comment]
Yeah, it is building an `RF.pdb`. I'm not sure what it means or how I can avoid it.

**Comment by gregg-miskelly** [comment]
I am on vacation this week, but there is information about portable PDBs in the wiki for this project.

**Comment by rajkumar42** [comment]
@fabioluz, it might be worth deleting RF.* and rebuilding the project with the portablepdb flag set. 
https://github.com/OmniSharp/omnisharp-vscode/wiki/Portable-PDBs

**Comment by fabioluz** [comment]
@rajkumar42 @gregg-miskelly According to the docs, portable-pdbs should be enabled by default in my case. If I "force" portable-pdb by setting ` <DebugType>portable</DebugType>` in the `.csproj`, I get the error `The preLaunchTask 'build' terminated with exit code 1.`

For some reason it's still building a Windows PDB. Could it be one of my dependencies?
