### ISSUE TITLE
Omnisharp server startup is considerably longer after project.json to csproj conversion

### ISSUE THREAD

**Issue by tetious** [OmniSharp/omnisharp-vscode#1674]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4

VS Code version:
1.14.1
C# Extension version:
1.11.0

After converting my medium sized "solution" (11 total projects) from project.json to csproj, omnisharp server takes 40-50 seconds to start. (measured from opening a C# file in the editor until code-lens visibility)
Pre-conversion it took about 5 seconds. 

I'm not sure what information I can add to help narrow this down. I'll help in any way I can. My guess though is that it might be related to the terrible dotnet build performance in the same scenario, due to the "upgraded" project system: https://github.com/dotnet/cli/issues/5918

**Comment by DustinCampbell** [comment]
Yes, I'm looking at this performance issue right now actually. I'm using https://github.com/OmniSharp/omnisharp-roslyn/issues/926 to track the work. You can follow that too.
