### ISSUE TITLE
DateTimeOffset comparison on Debug Console totally messed up

### ISSUE THREAD

**Issue by cateyes99** [OmniSharp/omnisharp-vscode#1677]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```
VS Code version: `1.14.2`
C# Extension version: `1.11.0`

## Steps to reproduce
Given the below code
```C#
            var dtString = "2017-07-27T00:00:00Z";
            var d = DateTimeOffset.Parse(dtString);
            var d2 = DateTimeOffset.Parse(dtString);
            var f = d == d2;
            var f2 = d > d2;
            var f3 = d2 > d;
            var f4 = d < d2;
            var f5 = d2 < d;
```
When debugging it, in the `Show Dedug` window I can see `f` is `true`, as well as `f2`, `f3`, `f4` and `f5` are all `false` which are correct. But if I do comparisons of `d` and `d2` in the `Debug Console` then **odd** things happened!

## Expected  behavior
```
d == d2
true
d > d2
false
d2 > d
false
d < d2
false
d2 < d
false
```

## Actual behavior
```
d == d2
false
d > d2
true
d2 > d
true
d < d2
false
d2 < d
false
```

**Comment by gregg-miskelly** [comment]
This looks like a bug in CoreCLR. It was fixed in .net core CLR 2.0 if you want to give it a try. I can try and help more when I get back from vacation if needed.

**Comment by cateyes99** [comment]
@gregg-miskelly if it's a bug from CoreCLR, why the following works at runtime and debugging?

**Comment by gregg-miskelly** [comment]
Because the low level debugging support is in CoreCLR, and that is where the bug was.

**Comment by cateyes99** [comment]
i've tried the same code on` Windows 10` with:
`dotnet --info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```
VS Code version: `1.10.2`
C# Extension version: `1.8.1`

It **`doesn't`** have this issue. I'll try it on `.NET Core CLR 2.0 preview 2`

**Comment by cateyes99** [comment]
Tried to install `.NET Core CLR 2.0 preview 2` on my Mac, but cannot run it, because `OS X 10.12` is required for it, my one is `10.11.6`.

**Comment by cateyes99** [comment]
So i've upgraded my `OS X` to `10.12`, and debugged it with the same version of `VS Code` and `Omnisharp` extension on `.NET Core CLR 2.0 preview 2`. It does not have this issue.
