### ISSUE TITLE
Breakpoint behaviours odd for local function

### ISSUE THREAD

**Issue by cateyes99** [OmniSharp/omnisharp-vscode#1678]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```
VS Code version: `1.14.2`
C# Extension version: `1.11.0`

## Steps to reproduce
I have the below piece of code, and set up breakpoints at Line 12, 14.
![image](https://user-images.githubusercontent.com/19678455/28823305-fd106a26-7710-11e7-9dcc-af6e9f2a5728.png)

After running and debugging it as shown below, the breakpoints at Line 14 automatically moves to Line 18! If i hit <kbd>F5</kbd>, it does break at Line 14 though, but **note:** now during debugging, I cannot set up any breakpoint in the `local function` as usual, for example at Line 15! Outside the `local function` I can set up breakpoints as usual.
![image](https://user-images.githubusercontent.com/19678455/28823366-4bb73718-7711-11e7-887b-cb06e592793e.png)

After finishing debugging, the breakpoint setup previous at Line 14 won't come back, instead stay at Line 18 as shown below. So next time, if I re-run and debug it, it won't break at Line 14 any more!
![image](https://user-images.githubusercontent.com/19678455/28823551-37acedf2-7712-11e7-91ce-9559b0778bf3.png)

## Expected  behavior
Breakpoints setup in `local functions` before debugging shouldn't be moved outside it after starting debugging.

During debugging, should be able to set up breakpoints for the statements in `local functions`

## Actual behavior
Very **odd**

**Comment by cateyes99** [comment]
Also I noticed the feature `Trigger Parameter Hints` <kbd>⇧</kbd><kbd>⌘</kbd><kbd>Space</kbd> does not trigger parameter hints for a call to a `local function`. And when type the call to it, no `IntelliSense` provided as well!

**Comment by gregg-miskelly** [comment]
I _think_ I know what is happening - that line will actually be in two functions according to the debug info -- the inner function and the outer function. I believe vsdbg is actually setting the breakpoint in both places, but it is only reporting the breaking in the outer function to the UI. The result is that the breakpoint will really be set in both spots, but there will be no indicator for the first spot, and the breakpoint will appear to move (and really will move after we restart debugging).

We should be able to tweak our logic to prefer the inner function as a better match.

**Comment by gregg-miskelly** [comment]
I have a fix for the debugger issue. @DustinCampbell should @cateyes99 open a separate issue for the completion issue (see his second comment), or is that already tracked somewhere else?

**Comment by DustinCampbell** [comment]
We need a separate issue for that.

**Comment by gregg-miskelly** [comment]
@cateyes99 if you wouldn't mind please create a new bug for the parameter hints issue.

**Comment by cateyes99** [comment]
@gregg-miskelly a new issue #1715 created as per u ask. cheers
