### ISSUE TITLE
Cannot be used inside the DLL "go to definition" feature

### ISSUE THREAD

**Issue by hubluesky** [OmniSharp/omnisharp-vscode#1679]
## Environment data
`dotnet --info` output:
VS Code version:1.14.2
C# Extension version:1.11.0

## Actual behavior
无法在DLL里面使用“转到定义”功能，还望可以支持此功能。
sorry my pool english, please support "go define" for dll code.

**Comment by DustinCampbell** [comment]
Hi! We've recently fixed an issue around Go To Definition within a "metadata" file. Does look like the same thing that you're asking for? https://github.com/OmniSharp/omnisharp-vscode/issues/771

**Comment by hubluesky** [comment]
是的，就是这个问题，我已经在新版本里更新到了，非常感谢。
（Google Translate）
Yes, that is the problem, I have been updated in the new version, and very grateful.

**Comment by DustinCampbell** [comment]
Glad to hear it! Thank you for confirming.
