### ISSUE TITLE
Format Document changes the cursor position.

### ISSUE THREAD

**Issue by BjarkeCK** [OmniSharp/omnisharp-vscode#1680]
I have set it to format the document when ever I save the file. And I save the file constantly, sometimes just to format the document, other times to save, and other times out of muscle memory for no good reason. So It's annoying that it takes away the cursor from where I'm at each time it happens.

![format document](https://user-images.githubusercontent.com/11874914/28888699-de955f3c-77c1-11e7-9a2a-1fd4a03e4fc9.gif)

**Comment by akshita31** [comment]
The problem here is with VSCode not being able to place a caret if there are no spaces. Filed #https://github.com/Microsoft/vscode/issues/40676 for the same.

**Comment by BachiMjavanadze** [comment]
Please fix it

**Comment by nohwnd** [comment]
This needs to be fixed in VSCode, https://github.com/microsoft/vscode/issues/13960
