### ISSUE TITLE
[Question] How to debug .NET Core apps inside Docker container

### ISSUE THREAD

**Issue by formulahendry** [OmniSharp/omnisharp-vscode#1683]
From this [doc](https://github.com/OmniSharp/omnisharp-vscode/wiki/Attaching-to-remote-processes), I see the C# extension supports remote debugging through different transports (include Docker).
And in this [post](http://blog.jonathanchannon.com/2017/06/07/debugging-netcore-docker/), I see it could  debug a .NET Core console app inside Docker on Mac.
I want to know whether there is any guideline to debug a .NET Core console app insider Docker on **Windows**? How could I set the launch.json. Thanks!

**Comment by gregg-miskelly** [comment]
Do you mean a Windows container? Or a Linux container running on a Windows host?

**Comment by formulahendry** [comment]
Currently, I want to debug Linux container running on a Windows host.
Furthermore, I want to debug Windows container running on a Windows host.

**Comment by gregg-miskelly** [comment]
Linux containers should work using a 'pipeTransport' of docker.exe.

Windows containers are not currently supported. You would need to use full VS for that.

**Comment by formulahendry** [comment]
Thanks @gregg-miskelly for the info!
Could you please kindly let me know how to use 'pipeTransport' to debug .NET Core console app in Linux containers? Or any doc I could refer to?

**Comment by WardenGnaw** [comment]
@formulahendry #1369 has an example of using pipeTransport for .NET Core app in a Linux container. We do not have any official documentation on Docker but someone wrote a guide at https://github.com/sleemer/docker.dotnet.debug

**Comment by formulahendry** [comment]
Thanks @WardenGnaw !

**Comment by WardenGnaw** [comment]
If you have any other questions feel free to reopen this issue. I will be closing it for now.

**Comment by formulahendry** [comment]
Hi @WardenGnaw , I am here again to ask whether we have plan to support debugging Windows container? Thanks! (BTW, seems I am not able to reopen the issue.)

**Comment by WardenGnaw** [comment]
@formulahendry Which Windows container are you looking to use, windowservercore or nanoserver?

**Comment by formulahendry** [comment]
nanoserver

**Comment by formulahendry** [comment]
Open an separate issue #2195 to track the feature request of supporting debugging .NET Core apps in Docker Windows Container

**Comment by icenold** [comment]
Too much drama just to even debug a hello world app.
