### ISSUE TITLE
[QUESTION] Cake support in Omnisharp

### ISSUE THREAD

**Issue by gep13** [OmniSharp/omnisharp-vscode#1684]
We the [Cake](http://cakebuild.net/) Team, through the amazing work of @mholo65 have been working on adding Cake support in OmniSharp in order to provide Intellisense support within *.cake files.  The necessary work to get this working are contained within these PR's:

https://github.com/OmniSharp/omnisharp-roslyn/pull/932
https://github.com/OmniSharp/omnisharp-vscode/pull/1681

All this seems to work, with the exception of one thing...

As part of the Cake extension for Visual Studio we provide syntax highlighting for .cake files through registering a new language, as can be seen here:

![image](https://user-images.githubusercontent.com/1271146/28962413-8fac9592-78fd-11e7-9389-968608d972bf.png)

However, when trying to use Omnisharp through the changes in the above PR's, the only way that we have been able to get this to work is by changing the Language Mode to C#, which obviously loses the syntax highlighting that we provide.

We have been pointed at this location:

https://github.com/Microsoft/vscode/blob/master/extensions/csharp/package.json

What is required in order to get Omnisharp to "light" for .cake files, whilst still providing syntax highlighting?

**Comment by DustinCampbell** [comment]
Cross posting from #1681:

> Cake is really just C# script with some semantic differences, correct? If that's the case, I would proposal that the Cake Support extension doesn't provide it's own syntax highlighting, but takes advantage of C#'s. Then, the Cake Support extension would be modified to operate on the "csharp" language but only when the extension is ".cake". Thoughts?

**Comment by gep13** [comment]
@DustinCampbell I am more than happy to remove the syntax highlighting from the VSCode Extension for Cake.  Cake is built on C#, so obviously most things will be highlighted correctly.  In the above screenshot you will see things like `Task` and `Does` being highlighted.  These are parts of the DSL that Cake is providing.

**Comment by DustinCampbell** [comment]
I hadn't noticed that the syntax highlighting above had colored Task and Does specially. Have you looked at the C# syntax highlighting in a more robust color theme (like the default Dark+ theme)? That has much richer colors, and you can see that function calls are highlight differently, which draws attention to top-level Task and Does functions quite nicely:

![image](https://user-images.githubusercontent.com/116161/28977655-cc8ef92e-78f7-11e7-87b2-ff435214bdd4.png)

**Comment by mholo65** [comment]
I'd say we ditch our Cake specific highlighting and use C# default instead. But @gep13 could have last call.

This would also have to be synced with Cake Extension for VS Code.

**Comment by gep13** [comment]
@DustinCampbell oh, interesting! No I hadn't seen the highlighting in that theme.  In which case, I would tend to agree that we could remove the syntax highlighting from the Cake Extension for VSCode, and instead, point people at using the existing Themes.

@patriksvensson @devlead @mholo65 @agc93 thoughts?

**Comment by devlead** [comment]
I'm all for deleting custom code, so if standard C# works, yes lets ditch the specific one.

**Comment by DustinCampbell** [comment]
OK. I contributed this as a PR and it is now merged into VS Code: https://github.com/Microsoft/vscode/pull/32253.

So, Cake files will be treated as C#. We should see this show up in VS Code Insiders builds soon.

**Comment by mholo65** [comment]
Great! Thanks @DustinCampbell 

@gep13 could probably start looking at removing Cake highlighting from Cake-VSCode

**Comment by gep13** [comment]
@DustinCampbell sweet!

@mholo65 yip, it is on my list for over the weekend, so hopefully get to this, and get a new version of the extension out for testing.

**Comment by DustinCampbell** [comment]
I forgot to update everyone here, but the latest VS Code release (1.16.1) now colorizes cake files by default (even when C# for VS Code is not installed).

**Comment by devlead** [comment]
Oh nice 👍

**Comment by gep13** [comment]
@DustinCampbell that is very cool! Thanks for letting us know! 😄

**Comment by DustinCampbell** [comment]
@mholo65: I've released v1.13.0-beta4, which contains the new Cake bits. However, when testing it on Windows, I got the following:

```
[warn]: OmniSharp.Cake.CakeProjectSystem
        Cake script service not connected. Aborting.
```

**Comment by mholo65** [comment]
@DustinCampbell nice! The warning you are getting is due to `cake.bakery` is not installed in your `tools` folder.

See examle in test-project https://github.com/OmniSharp/omnisharp-roslyn/blob/master/test-assets/test-projects/CakeProject/tools/packages.config

**Comment by gep13** [comment]
@DustinCampbell  assuming you have the latest Cake extension for VSCode, there is a new command that will help with installing that dependency.

**Comment by DustinCampbell** [comment]
Ah. I need the Cake extension. thanks!

**Comment by patriksvensson** [comment]
@DustinCampbell You don't need the Cake extension, but it makes it a lot easier to install `Cake.Bakery`.

**Comment by DustinCampbell** [comment]
I just installed the Cake extension and invoked the "Cake: install intellisense support" command. All is now well. Looks great!

I think we can close this issue now. Nice work everyone!

**Comment by gep13** [comment]
@DustinCampbell that is great news!
