### ISSUE TITLE
No red wavy underlines (squiggly lines) for error generating/gibberish code.

### ISSUE THREAD

**Issue by neetdev** [OmniSharp/omnisharp-vscode#1687]
## Environment data
`dotnet --info` output:
![image](https://user-images.githubusercontent.com/24647234/29008794-a4d7a40e-7aea-11e7-8a4f-2d0a11bc41d3.png)

VS Code version: 1.14.2
C# Extension version: 1.11.0

## Steps to reproduce
Open C# file in Unity3D with VS Code

## Expected  behavior
Errors are detected and show red squiggles/wavy underline

## Actual behavior
Gibberish code is interpreted as normal and does not notify you of an error.
![image](https://user-images.githubusercontent.com/24647234/29008816-10462184-7aeb-11e7-8d59-f8e19ca6d63e.png)

## Omnisharp Log Output
```
Starting OmniSharp server at 2017-08-06, 8:39:01 PM
    Target: c:\Users\Antoine\Documents\Unity Projects\The Deep\The Deep-csharp.sln

OmniSharp server started
    Path: C:\Users\Antoine\.vscode\extensions\ms-vscode.csharp-1.11.0\bin\omnisharp\OmniSharp.exe
    PID: 197284

OmniSharp: -s c:\Users\Antoine\Documents\Unity Projects\The Deep\The Deep-csharp.sln --hostPID 194180 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
[info]: OmniSharp.Startup
        Omnisharp server running using Stdio at location 'c:\Users\Antoine\Documents\Unity Projects\The Deep' on host 194180.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\Users\Antoine\Documents\Unity Projects\The Deep
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuild will use local Visual Studio installation.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in 'c:\Users\Antoine\Documents\Unity Projects\The Deep\The Deep-csharp.sln'.
[fail]: OmniSharp.Startup
        The project system 'OmniSharp.MSBuild.MSBuildProjectSystem' threw exception during initialization.
System.ArgumentException: "parenthesizedName" must be a non-null and non-empty string.
   à OmniSharp.MSBuild.SolutionParsing.SectionBlock..ctor(String type, String parenthesizedName, String value, ReadOnlyCollection`1 keyValuePairs)
   à OmniSharp.MSBuild.SolutionParsing.SectionBlock.Parse(TextReader reader)
   à OmniSharp.MSBuild.SolutionParsing.SolutionFile.ParseGlobal(TextReader reader)
   à OmniSharp.MSBuild.SolutionParsing.SolutionFile.Parse(TextReader reader)
   à OmniSharp.MSBuild.SolutionParsing.SolutionFile.Parse(String solutionFileName)
   à OmniSharp.MSBuild.MSBuildProjectSystem.GetProjectPathsFromSolution(String solutionFilePath)
   à OmniSharp.MSBuild.MSBuildProjectSystem.Initalize(IConfiguration configuration)
   à OmniSharp.Startup.InitializeWorkspace(OmniSharpWorkspace workspace, CompositionHost compositionHost, IConfiguration configuration, ILogger logger, OmniSharpOptions options)
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Antoine\Documents\Unity Projects\The Deep'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Startup
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Startup
        Configuration finished.
```
## Extensions used
![image](https://user-images.githubusercontent.com/24647234/29008689-306349bc-7ae9-11e7-82b0-e0a9daa67e94.png)

I've already tried reinstalling VS Code, the C# extension and every other extension by itself after. I cannot get errors to be reported and I've googled for hours to no avail. Hopefully I'm posting this in the right place.

**Comment by DustinCampbell** [comment]
Hi! Thanks for reporting this issue. Could you share the content of the `c:\Users\Antoine\Documents\Unity Projects\The Deep\The Deep-csharp.sln` file?

**Comment by neetdev** [comment]
Microsoft Visual Studio Solution File, Format Version 11.00
# Visual Studio 2008

Project("{6047D3CE-DFF5-F069-3D1C-FDA0F6C01AC4}") = "The Deep", "Assembly-CSharp-firstpass-vs.csproj", "{A76A5766-4AE0-65BD-01D4-20AA44EA5D16}"
EndProject
Project("{6047D3CE-DFF5-F069-3D1C-FDA0F6C01AC4}") = "The Deep", "Assembly-CSharp-vs.csproj", "{E6E16ADF-8415-DD75-A4F7-4AC3655E1DE7}"
EndProject
Project("{6047D3CE-DFF5-F069-3D1C-FDA0F6C01AC4}") = "The Deep", "Assembly-CSharp-Editor-vs.csproj", "{9ADD63FB-E635-F11E-1D10-9B2BF9FCD85C}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{A76A5766-4AE0-65BD-01D4-20AA44EA5D16}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{A76A5766-4AE0-65BD-01D4-20AA44EA5D16}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{A76A5766-4AE0-65BD-01D4-20AA44EA5D16}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{A76A5766-4AE0-65BD-01D4-20AA44EA5D16}.Release|Any CPU.Build.0 = Release|Any CPU
		{E6E16ADF-8415-DD75-A4F7-4AC3655E1DE7}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{E6E16ADF-8415-DD75-A4F7-4AC3655E1DE7}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{E6E16ADF-8415-DD75-A4F7-4AC3655E1DE7}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{E6E16ADF-8415-DD75-A4F7-4AC3655E1DE7}.Release|Any CPU.Build.0 = Release|Any CPU
		{9ADD63FB-E635-F11E-1D10-9B2BF9FCD85C}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{9ADD63FB-E635-F11E-1D10-9B2BF9FCD85C}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{9ADD63FB-E635-F11E-1D10-9B2BF9FCD85C}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{9ADD63FB-E635-F11E-1D10-9B2BF9FCD85C}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
																																																																																																																																																																																																																																																						GlobalSection(MonoDevelopProperties) = preSolution
		StartupItem = Assembly-CSharp.csproj
		Policies = $0
		$0.TextStylePolicy = $1
		$1.inheritsSet = null
		$1.scope = text/x-csharp
		$0.CSharpFormattingPolicy = $2
		$2.inheritsSet = Mono
		$2.inheritsScope = text/x-csharp
		$2.scope = text/x-csharp
		$0.TextStylePolicy = $3
		$3.FileWidth = 120
		$3.TabWidth = 4
		$3.EolMarker = Unix
		$3.inheritsSet = Mono
		$3.inheritsScope = text/plain
		$3.scope = text/plain
	EndGlobalSection

EndGlobal

**Comment by DustinCampbell** [comment]
It looks to me like there's an extra `EndGlobalSection` after the line that reads `HideSolutionNode = FALSE` causing the solution file to be invalid (maybe a source control mismerge?). Try deleting that extra `EndGlobalSection` and the blank line the follows it so that the `HideSolutionNode` and `StartupItem` are next to each other.

**Comment by neetdev** [comment]
Tried that, restarted VS Code and nothing seems to have changed in the log or the missing errors.

**Comment by DustinCampbell** [comment]
Hmmm... OK. The call stack of the exception definitely looks like something wrong in one of the `GlobalSection` headers.

Another idea: Try downloading and install the latest [1.12 beta](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.12.0-beta4). We've made a lot of changes in this particular area to be a bit more resilient. You can follow the instructions at [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) to install the beta.

**Comment by neetdev** [comment]
Thank you for the quick answers I'll keep you updated.

**Comment by DustinCampbell** [comment]
No problem. If that doesn't work, would it be possible to share your project? A could take a look at it tomorrow.

**Comment by neetdev** [comment]
![image](https://user-images.githubusercontent.com/24647234/29009733-dbf28540-7af3-11e7-84de-4e970c107a21.png)
Good news! Thanks again for your time and patience.

**Comment by DustinCampbell** [comment]
Excellent! Is that with the beta?

**Comment by DustinCampbell** [comment]
I'm going to go ahead and close this since it looks like you have it working.

**Comment by TheBanker1710** [comment]
Same error, no underline for c# errors... Could you help?

**Comment by JoeRobich** [comment]
@TheBanker1710 Sorry you are having issues. Can you open a new issue and provide the requested logs and information? You scenario may not be the same as the one from this issue.

**Comment by Wamperit** [comment]
a

**Comment by Wamperit** [comment]
This is the process which helped me to appear the squiggles in Visual Studio 2017 professional again:
- I deinstalled Visual Studio 2017 & and 2019 Professional
-I deleted all folder in my case under harddrive c -> visual studio
- I installed CCleaner and cleaned the harddisk & registry
- Reinstall Visual Studio 2017 pro
- Open Visual Studio 2017 pro.
- Go to Tools -> Import & Export Settings -> Reset all settings -> and choose C# or C++

In Visual Studio 2019 pro, it still doesnt work for me.

**Comment by Huang2077** [comment]
I found this to be a bug, when you open vscode from Unity (double click on the script component - provided you have set your unity preferences) the red underline does not appear at this point, i.e. no realistic spelling errors can be made. When you open vscode from the desktop or another shortcut and go to the same cs file, the red underline will appear. In summary, do not open vscode from unity, open it from a desktop shortcut or open the cs file directly from the project folder of your project

**Comment by Huang2077** [comment]
I found this to be a bug, when you open vscode from Unity (double click on the script component - provided you have set your unity preferences) the red underline does not appear. no spelling errors can be made. When you open vscode from the desktop or another shortcut and go to the same cs file, the red underline will appear. In summary, do not open vscode from unity, open it from a desktop shortcut or open the cs file directly from the project folder of your project
