### ISSUE TITLE
Can you tel me a link to Debug a  C# testcases in vs code?? With Launch.json configuration and how to run testcases?

### ISSUE THREAD

**Issue by AmsaAmrutha** [OmniSharp/omnisharp-vscode#1689]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

**Comment by DustinCampbell** [comment]
It'd be great if you could provide a little bit more information.

C# for VS Code provides unit testing support for .NET Core projects that have xUnit, NUnit or MSTest unit tests. Once you have your .NET Core project opened and working in VS Code, small adornments should appear over unit testing methods with the text, "run test" and "debug test". Clicking these will do the job.

**Comment by AmsaAmrutha** [comment]
hi,
I am very new to this C# and also automation in C#.
I am very glad if you can give me more details about this... :-)

**Comment by DustinCampbell** [comment]
This isn't a great place to provide tutorials, but I can provide you with a few links:

* https://channel9.msdn.com/Blogs/dotnet/Get-started-with-VS-Code-using-CSharp-and-NET-Core
* https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code
* https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test

I hope that helps!

**Comment by DustinCampbell** [comment]
Hopefully those links helped out. I'll close this for now.
