### ISSUE TITLE
debugger always fails to "restore"

### ISSUE THREAD

**Issue by egamma** [OmniSharp/omnisharp-vscode#169]
_From @ciel on April 8, 2016 21:13_

- VSCode Version:
`0.10.11`

- OS Version:
Windows 10x64
Steps to Reproduce:

- .NET CLI version
````
.NET Command Line Tools (1.0.0-rc2-002306)

Product Information:
 Version:     1.0.0-rc2-002306
 Commit Sha:  0747d31f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
````

1. Install Visual Studio Code
2. Install the [dot net cli](https://github.com/dotnet/cli)
3. Open a command line (`cmd` or `PowerShell`)
4. Navigate to a folder
5. Type `dot net new` and hit `ENTER` to create a new project.
6. Right click inside the folder (`Windows Explorer`) and select `Open with VS Code`

The `OUTPUT` window appears and spouts off a lot of attempts to pull in files, and then yields an error; it is different each time for me.

![sample](http://i.xomf.com/rpbvf.jpg)

_Copied from original issue: Microsoft/vscode#5107_

**Comment by gregg-miskelly** [comment]
The latest builds of the .NET CLI aren't compatible with the version of the C# extension currently in the gallery. So you will either need to install a newer build of the C# extension, or go back to the 'beta' build of the CLI referenced from http://dotnet.github.io/getting-started.

Instructions for the getting-started builds: https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md
Instructions for the latest builds: http://aka.ms/vscclrdogfood

**Comment by ciel** [comment]
I have the best newest version of the C# extension.

**Comment by ciel** [comment]
The newest**

**Comment by gregg-miskelly** [comment]
@ceil you have 1.0.1-rc? The output above looks to be from the latest version from the VS Code Gallery.

**Comment by gregg-miskelly** [comment]
If you do have 1.0.1-rc, please copy/paste the output from the coreclr-debug output pain.

**Comment by ciel** [comment]
So that isn't the latest build? Where do I get a newer one, then?

**Comment by gregg-miskelly** [comment]
As I said -- http://aka.ms/vscclrdogfood

**Comment by ciel** [comment]
Sorry. That part got chopped off on the email from my phone. I'll take a look at it momentarily.

**Comment by ciel** [comment]
Yes, that did seem to resolve the problem. Thank you very much.
