### ISSUE TITLE
C# syntactic colorization not working

### ISSUE THREAD

**Issue by FalconWarriorr** [OmniSharp/omnisharp-vscode#1690]
## Environment data
`dotnet --info` output:
VS Code version:1.14.2
C# Extension version:1.11.0

## Steps to reproduce
I install the C# extension and enable it

## Expected  behavior
expected the different parts of syntax to be colored differently but almost everything is colored the same
This is how I expect it to look
![image](https://user-images.githubusercontent.com/4342051/29083370-84484340-7c36-11e7-8ea1-199a41838b71.png)

## Actual behavior
this is how my code looks
![image](https://user-images.githubusercontent.com/4342051/29083348-729a2de8-7c36-11e7-9e1d-7490e06cc590.png)

**Comment by DustinCampbell** [comment]
It looks to me like the problem is that you don't have semi-colons after `using System` or `Console.WriteLine(...)`

**Comment by DustinCampbell** [comment]
FWIW, do let me know if this doesn't fix the problem for you.

**Comment by FalconWarriorr** [comment]
Yes that did fix my issue. Thanks!
