### ISSUE TITLE
omnisharp-vscode 1.12.0 macOS: Missing Roslyn/mcs.exe

### ISSUE THREAD

**Issue by andersonkent** [OmniSharp/omnisharp-vscode#1704]
## Environment data
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4

VS Code version: 1.15.0
C# Extension version: 1.12.0

## Steps to reproduce
Upon startup, open a C# file in a C# project. Omnisharp plugin states that some projects have problems loading. The Omnisharp log says this:

[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The specified task executable location "/Users/someuser/.vscode/extensions/ms-vscode.csharp-1.12.0/.omnisharp/omnisharp/msbuild/Roslyn/mcs.exe" is invalid.

Navigating to that location shows that there is no mcs.exe installed there. (csc.exe exists)

## Expected  behavior
The installation should contain all of the files necessary to run the plugin.

## Actual behavior
The installation appears to be missing at least the mcs.exe executable.

**Comment by DustinCampbell** [comment]
Please try updating to the latest stable Mono (5.0.1)

**Comment by andersonkent** [comment]
Updated from mono 4.8.0 to mono 5.0.1.1. Problem solved.
