### ISSUE TITLE
Not stopping at breakpoint ( IIS + VSCode)

### ISSUE THREAD

**Issue by weinand** [OmniSharp/omnisharp-vscode#1706]
_From @tiaraju on August 11, 2017 14:1_

- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.9.6
net-core-starters-pack|bla|0.3.0
bracket-pair-colorizer|Coe|0.10.8
gitlens|eam|4.3.3
EditorConfig|Edi|0.9.4
git-project-manager|fel|1.3.2
csharpextensions|jch|1.3.0
csharpfixformat|Leo|0.0.31
csharp|ms-|1.12.0
mono-debug|ms-|0.15.7
resharper9-keybindings|ms-|1.1.0
material-icon-theme|PKi|2.1.0
aspnet-helper|sch|0.6.3
autoimport|ste|1.2.2
gitblame|wad|2.0.2
highlight-trailing-white-spaces|yba|0.0.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Run a .NET web application on IIS
2. Attach vs code to an existing process 
3. Try to debug using breakpoints

Reproduces without extensions: Yes/No

_Copied from original issue: Microsoft/vscode#32332_

**Comment by weinand** [comment]
VS Code has no builtin C#/.net debugger. Moving.

**Comment by gregg-miskelly** [comment]
@tiaraju 

* Are you debugging a .NET Core application, or a .NET full framework? Does this match the 'type' you have set  in launch.json
* if you check the debug console, you can see if symbols were loaded for your module. Are they loaded?

**Comment by tiaraju** [comment]
Hello @gregg-miskelly , thank you for replying.
I'm running a .NET application. We're using C# 5.0. With Visual Studio 2013 I'm able to attach to the running process and debug it properly. Our application is running in IIS.

When I try to pin a breakpoint, it says:  No symbols have been loaded for this document.
Can't see anything on the Debug Console.

My launch.json looks like this:

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}

Best Regards.

**Comment by gregg-miskelly** [comment]
@tiaraju you are telling it to debug with coreclr, but you project is not a coreclr project. You can fix that my changing the `type` to `clr`. But keep in mind that your scenario is not one that the C# extension is really designed for. We do offer some basic support of the Desktop framework, but this is more of a full-VS scenario.

**Comment by tiaraju** [comment]
Ok @gregg-miskelly. 
Thank you!
