### ISSUE TITLE
Unable to load Kestrel solution on Linux

### ISSUE THREAD

**Issue by cesarbs** [OmniSharp/omnisharp-vscode#1707]
## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.0-preview1-007026)

Product Information:
 Version:            2.1.0-preview1-007026
 Commit SHA-1 hash:  6164c26938

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/cesars/.dotnet/sdk/2.1.0-preview1-007026/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

VS Code version: 1.14.2
C# Extension version: 1.12.0
Mono version: 5.0.1.1

## Steps to reproduce

1. Clone https://github.com/aspnet/KestrelHttpServer
1. Open VSCode

## Expected  behavior

Solution loads and Intellisense works, etc.

## Actual behavior

All projects fail to load with the same error:

```
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The specified task executable location "/home/cesars/.vscode/extensions/ms-vscode.csharp-1.12.0/.omnisharp/omnisharp/msbuild/Roslyn/RunCsc" is invalid.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file '/home/cesars/src/aspnet/KestrelHttpServer/src/Kestrel.Core/Kestrel.Core.csproj'.
/home/cesars/src/aspnet/KestrelHttpServer/src/Kestrel.Core/Kestrel.Core.csproj
```

This is what I have under `/home/cesars/.vscode/extensions/ms-vscode.csharp-1.12.0/.omnisharp/omnisharp/msbuild/Roslyn`

```
csc.exe
csc.exe.config
csc.rsp
csi.exe
csi.exe.config
csi.rsp
Microsoft.Build.Tasks.CodeAnalysis.dll
Microsoft.CodeAnalysis.CSharp.dll
Microsoft.CodeAnalysis.CSharp.Scripting.dll
Microsoft.CodeAnalysis.dll
Microsoft.CodeAnalysis.Scripting.dll
Microsoft.CSharp.Core.targets
Microsoft.DiaSymReader.Native.amd64.dll
Microsoft.DiaSymReader.Native.x86.dll
Microsoft.Win32.Primitives.dll
System.AppContext.dll
System.Collections.Immutable.dll
System.Console.dll
System.Diagnostics.FileVersionInfo.dll
System.Diagnostics.Process.dll
System.Diagnostics.StackTrace.dll
System.IO.Compression.dll
System.IO.FileSystem.dll
System.IO.FileSystem.DriveInfo.dll
System.IO.FileSystem.Primitives.dll
System.IO.Pipes.dll
System.Reflection.Metadata.dll
System.Security.AccessControl.dll
System.Security.Claims.dll
System.Security.Cryptography.Algorithms.dll
System.Security.Cryptography.Encoding.dll
System.Security.Cryptography.Primitives.dll
System.Security.Cryptography.X509Certificates.dll
System.Security.Principal.Windows.dll
System.Text.Encoding.CodePages.dll
System.Threading.Thread.dll
System.ValueTuple.dll
System.Xml.ReaderWriter.dll
System.Xml.XmlDocument.dll
System.Xml.XPath.dll
System.Xml.XPath.XDocument.dll
```

**Comment by DustinCampbell** [comment]
Does the Kestrel solution set CscToolPath?

**Comment by cesarbs** [comment]
I can't find CscToolPath explicitly in the solution, but we do consume private builds of the C# compiler (https://github.com/aspnet/KestrelHttpServer/commit/659fa967a1900653f7a82f02624c7c7995a3b786), which I guess would set that.

**Comment by DustinCampbell** [comment]
Yeah, that's probably the issue. I have a fix in mind for this, but am already away for the weekend and travelling. When I get some time, I'll make the fix and push a new release of C# for VS Code. In that meantime, you can roll back to a recent beta (probably 1.12-beta4) or 1.11. I'll ping back here once this is fixed (hopefully this weekend). Sound good?

**Comment by cesarbs** [comment]
Great! 👍

**Comment by DustinCampbell** [comment]
This should fix the issue: https://github.com/OmniSharp/omnisharp-roslyn/pull/939
