### ISSUE TITLE
Break on exception doesn't show exception

### ISSUE THREAD

**Issue by Pilchie** [OmniSharp/omnisharp-vscode#171]
It seems that the variables window only shows `$exception` if the active frame has symbols, but hitting an exception doesn't seem to automatically switch threads, or find the nearest frame with symbols if the exception is thrown in `[ExternalCode]`.

**Comment by gregg-miskelly** [comment]
I think this is https://github.com/Microsoft/vscode/issues/4027, you can confirm/deny this theory by installing an 'insiders' build of VS Code.

**Comment by gregg-miskelly** [comment]
Yes, this works correctly for me with latest VS Code Alpha, so this should be fixed.

**Comment by gregg-miskelly** [comment]
Though poking around more, I discovered that evaluating $exception is pretty broken in trivial apps (might not be a problem in more real ones) -- #173

**Comment by Pilchie** [comment]
Thanks @gregg-miskelly, definitely looks like the same issue.
