### ISSUE TITLE
Display StyleCop.Analyzers Warnings in VS Code

### ISSUE THREAD

**Issue by kalahari** [OmniSharp/omnisharp-vscode#1714]
## Environment data
`dotnet --info` output:
> .NET Command Line Tools (1.0.4)
> 
> Product Information:
>  Version:            1.0.4
>  Commit SHA-1 hash:  af1e6684fd
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.12
>  OS Platform: Darwin
>  RID:         osx.10.12-x64
>  Base Path:   /usr/local/share/dotnet/sdk/1.0.4

VS Code version: 1.15.0
C# Extension version: 1.12.1

## Steps to reproduce
Follow the steps here to enable StyleCop.Analyzers:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/DotNetCli.md
using this ruleset:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers.ruleset
and this settings file:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/stylecop.json

## Expected  behavior
`SAXXXX` warnings appear in the "Problems" tab of VS Code, and inline in the source files.

## Actual behavior
Warnings reported in the "Problems" tab of VS Code are not changed from the default set (even after restarting OmniSharp), but running `dotnet build` does display the warnings from StyleCop.Analyzers.

**Comment by DustinCampbell** [comment]
Thanks for taking the time to report this issue. We're using https://github.com/OmniSharp/omnisharp-vscode/issues/43 to track this work for the future.
