### ISSUE TITLE
Go To Implementation is not available

### ISSUE THREAD

**Issue by agoretsky** [OmniSharp/omnisharp-vscode#1717]
## Environment data
`dotnet --info` output:
Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
VS Code version: 1.15.0
C# Extension version: 1.12.1

## Steps to reproduce

Right click on interface or interface's method

## Expected  behavior
there is context menu with item - "Go To implementation"

## Actual behavior
"Go To implementation" item doesn't exist in context menu

**Comment by bernardbr** [comment]
It's have been happening since version 1.14.0 of vs code and 1.11 of C# Extension.
But you can access this functionality pressing ```F1``` and typing "gti".

I hope I have helped.

**Comment by agoretsky** [comment]
@bernardbr, thanks

**Comment by Jonatthu** [comment]
This is still happening on latest releases on windows 10
