### ISSUE TITLE
mono.osx operation not permitted

### ISSUE THREAD

**Issue by JasonWorks** [OmniSharp/omnisharp-vscode#1719]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

VS Code version:
1.14.2

C# Extension version:
1.12.1

## Steps to reproduce
Attempt to Go to Definition on a class type in my code

## Expected  behavior
To switch to my source file with my class definition.

## Actual behavior
Nothing happens, except for the following errors...

OmniSharp server started wth Mono
    Path: /Users/jasonworks/.vscode/extensions/ms-vscode.csharp-1.12.1/.omnisharp/run
    PID: 83884

/Users/jasonworks/.vscode/extensions/ms-vscode.csharp-1.12.1/.omnisharp/run: line 43: /Users/jasonworks/.vscode/extensions/ms-vscode.csharp-1.12.1/.omnisharp/mono.osx: Operation not permitted

**Comment by DustinCampbell** [comment]
Hmmm... I haven't seen this issue before. I would expect to see this error if permissions have been changed in some way. Perhaps the extension was installed as a different user? Could you provide the full directory listing of `/Users/jasonworks/.vscode/extensions/ms-vscode.csharp-1.12.1/.omnisharp`. You can follow these steps to do that:

1. Open a new Terminal window.
2. Type the following:

```
cd /Users/jasonworks/.vscode/extensions/ms-vscode.csharp-1.12.1/.omnisharp
ls -al
```

3. Copy and paste the directory listing from the terminal window to here.

**Comment by JasonWorks** [comment]
total 8304
drwxr-xr-x    7 jasonworks  5001      238 Aug 16 11:57 .
drwxr-xr-x   20 jasonworks  5001      680 Aug 16 11:57 ..
drwxr-xr-x    4 jasonworks  5001      136 Aug 16 11:57 etc
drwxr-xr-x   69 jasonworks  5001     2346 Aug 16 11:57 framework
-rwxr-xr-x    1 jasonworks  5001  4245036 Aug 16 11:57 mono.osx
drwxr-xr-x  137 jasonworks  5001     4658 Aug 16 11:57 omnisharp
-rwxr-xr-x    1 jasonworks  5001     1036 Aug 16 11:57 run

**Comment by DustinCampbell** [comment]
That looks OK to me. Are you able to run `mono.osx` from this directory? If so, could you also try running it from within the Terminal window inside VS Code?

**Comment by JasonWorks** [comment]
Sorry, I'm not sure what you mean by run mono.osx.  Based on your request, here's what I have tried...

jasonworks-macbookpro:.omnisharp jasonworks$ mono --version
Mono JIT compiler version 4.6.1 (mono-4.6.0-branch-c8sr0/abb06f1 Fri Sep 23 19:24:23 EDT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/8b1520c)
	GC:            sgen
jasonworks-macbookpro:.omnisharp jasonworks$ mono.osx
-bash: mono.osx: command not found
jasonworks-macbookpro:.omnisharp jasonworks$ mono mono.osx
Cannot open assembly 'mono.osx': File does not contain a valid CIL image.

**Comment by JasonWorks** [comment]
Sorry, I have fledgling knowledge of mac/linux terminal.  Running ./mono.osx showed that the company I work for requires that I request the application be whitelisted.  Once I did that I was able to properly run mono.osx.  I'm now able to get intellisense and such working with VS Code.

Thanks!

**Comment by DustinCampbell** [comment]
Excellent! I had expected it was some sort of permissions issue. I'm very glad to hear it's working now.
