### ISSUE TITLE
launch.json should configure the "Environment" to be "development" for ASP.Net Core apps.

### ISSUE THREAD

**Issue by Pilchie** [OmniSharp/omnisharp-vscode#172]
Things like connection strings, user-secrets, etc, are often store in evironment specific app.*environment*.json settings.  We should make the default experience launch in the "Development" environment.

**Comment by gregg-miskelly** [comment]
How do we do that?

**Comment by Pilchie** [comment]
I'm not entirely sure - I *thought* that setting the command line arguments, so that they make it into the call to [UseDefaultHostingConfiguration](https://github.com/aspnet/Hosting/blob/b5816f22cf476542e989fc500f793a2149f27c55/src/Microsoft.AspNetCore.Hosting/WebHostBuilderExtensions.cs#L34), in the template's Program.cs would work, but it didn't seem to in my quick trial.

**Comment by Pilchie** [comment]
@davidfowl - do you know the right way to do this?

**Comment by gregg-miskelly** [comment]
@davidfowl @BillHiebert, is there a way that VS Code can launch the target app to use the devolper environment.json file?

**Comment by GeorgDangl** [comment]
I think as in the [example here](https://code.visualstudio.com/docs/editor/debugging#_launch-configurations), adding

    "env": {
        "ASPNETCORE_ENVIRONMENT": "Development"
    }

to the launch.json is supposed to set environment variables, but it's not working for launch configurations of type "coreclr" at the moment.

**Comment by gregg-miskelly** [comment]
Yup, looks we don't have code to process 'env'. Looks easy enough to add through.

**Comment by sayedihashimi** [comment]
+1 this would be great for ASP.NET projects.

**Comment by gregg-miskelly** [comment]
This is fixed internally and will be available in our 1.1.* releases.
