### ISSUE TITLE
Incorrect syntax highlighting

### ISSUE THREAD

**Issue by CoenraadS** [OmniSharp/omnisharp-vscode#1721]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.1.0)

Product Information:
 Version:            1.1.0
 Commit SHA-1 hash:  d6f4336106

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.1.0
```
VS Code version: `1.15.1`
C# Extension version: `1.12.1`

## Steps to reproduce

Have a unity .cs file with the following contents:

```
 void Start()
    {
        Vector2 point1 = new Vector2(1, 1);
	int z = 1;
        var newPoint = new Vector2(point1.x * z, 0);
    }
````
![2017-08-17 12_02_28-clipboard](https://user-images.githubusercontent.com/5593825/29407352-6f39b97e-8344-11e7-8590-b0ca5b38b511.png)

## Expected  behavior
point1.x should be a light blue color

## Actual behavior
point1.x has the same color as 'Vector2'

**Comment by DustinCampbell** [comment]
This issue was moved to dotnet/csharp-tmLanguage#82

**Comment by DustinCampbell** [comment]
Thanks for filing this issue. I've moved it over to the repo for the C# TextMate grammar.
