### ISSUE TITLE
Upgrading to VSC 1.15 64-bit Made It Unresponsive

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#1723]
_From @johancyprich on August 17, 2017 16:4_

- VSCode Version: 1.15.1
- OS Version: Windows 10 Pro :: 10.0.15063 Build 15063

I upgrade VSC to the latest 64-bit version and from there the app became unresponsive. Task Manager showed that VSC was using 98%+ CPU and the memory usage for the multiple instances was very large (100s of MB and typically 1 GB as well).

I tried installing earlier versions and also went back to 32-bit, but the same problem occurred. So, I did a complete uninstall and deleted the %USERS%/.vscode folder, and then did a reinstall of the 1.15 64-bit. While running Task Manager, I installed one extension at a time. When I tried to open a .cs file, VSC installed C# extensions and then the CPU/memory usage went to extreme levels which caused VSC to lag. When I disabled the C# extension, CPU/memory usage went to an acceptable level.

So I uninstall the C# extension and I'm happily using VSC. I think that the OmniSharp extension was causing the problems.

_Copied from original issue: Microsoft/vscode#32728_

**Comment by DustinCampbell** [comment]
Hi @johancyprich! When the C# extension initially starts up, it loads the project that you have open. Much like Visual Studio, it should eventually drop to a steady state after it is finishes loading your project. Did you observe this, or are you seeing constant memory/CPU activity?

**Comment by DustinCampbell** [comment]
I just updated to the Windows 64-bit version of VS Code 1.15.1 and do not see a difference in CPU or memory usage.

**Comment by johancyprich** [comment]
Hi @DustinCampbell. The resource usage stays high continuously.  I've tried the same version of VSC on a Windows 7 machine and it ran without any of these problems. I'm not sure why my Windows 10 machine works poorly with these VSC extensions.

**Comment by cartermp** [comment]
Closing out old issue. There are (unfortunately) numerous issues related to performance that are more recent.
