### ISSUE TITLE
More then one solution in workspace

### ISSUE THREAD

**Issue by flypixel** [OmniSharp/omnisharp-vscode#1725]
## Environment data
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

VS Code version: 1.15.1
C# Extension version: 1.12.1

## Steps to reproduce
1. create two solution files in one workspace (root folder)
2. create two projects
3. add one project to the first solution and second project to the second one
## Expected  behavior
for both projects intelligence and errors highlighting should work correctly

## Actual behavior
only for one of them intelligence and errors highlighting work correctly
and don't work for another one.
other features also don't work correctly

**Comment by DustinCampbell** [comment]
Just as you can only have one solution open in Visual Studio, C# for VS Code can only be "focused" on a single solution at a time. Click the solution-selector at the bottom of the screen to switch between solutions:

![image](https://user-images.githubusercontent.com/116161/29487989-1ed92b94-84b7-11e7-846a-7020566b467e.png)

**Comment by flypixel** [comment]
Thanks for the answer
