### ISSUE TITLE
Error when loading project: "Could not write lines to file "obj\Debug\netcoreapp1.1\Vega.csproj.CoreCompileInputs.cache"

### ISSUE THREAD

**Issue by FilipLaurentiu** [OmniSharp/omnisharp-vscode#1730]
## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
VS Code version: 1.15.1
C# Extension version: 1.12.0

## Steps to reproduce
I just open or start a project. I got this on every project

## Actual behavior
I don't get any IntelliSense

Starting OmniSharp server at 21.08.2017, 21:43:58 Target: c:\Users\flaur\Desktop\vega

OmniSharp server started Path: C:\Users\flaur.vscode\extensions\ms-vscode.csharp-1.12.1.omnisharp\OmniSharp.exe PID: 8684

OmniSharp: -s c:\Users\flaur\Desktop\vega --hostPID 1416 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4 [info]: OmniSharp.Startup Omnisharp server running using Stdio at location 'c:\Users\flaur\Desktop\vega' on host 1416. [info]: OmniSharp.DotNet.DotNetProjectSystem Initializing in c:\Users\flaur\Desktop\vega [info]: OmniSharp.DotNet.DotNetProjectSystem Auto package restore: False [info]: OmniSharp.DotNet.DotNetProjectSystem Update workspace context [info]: OmniSharp.DotNet.DotNetProjectSystem Resolving projects references [info]: OmniSharp.MSBuild.MSBuildProjectSystem Omnisharp will use local MSBuild. MSBUILD_EXE_PATH: C:\Users\flaur.vscode\extensions\ms-vscode.csharp-1.12.1.omnisharp\msbuild\MSBuild.exe MSBuildExtensionsPath: C:\Users\flaur.vscode\extensions\ms-vscode.csharp-1.12.1.omnisharp\msbuild

[info]: OmniSharp.MSBuild.MSBuildProjectSystem No solution files found in 'c:\Users\flaur\Desktop\vega' [info]: OmniSharp.MSBuild.MSBuildProjectSystem Loading project: c:\Users\flaur\Desktop\vega\Vega.csproj [fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo Could not write lines to file "obj\Debug\netcoreapp1.1\Vega.csproj.CoreCompileInputs.cache". Access to the path 'c:\Users\flaur\Desktop\vega\obj\Debug\netcoreapp1.1\Vega.csproj.CoreCompileInputs.cache' is denied. [warn]: OmniSharp.MSBuild.MSBuildProjectSystem Failed to load project file 'c:\Users\flaur\Desktop\vega\Vega.csproj'. c:\Users\flaur\Desktop\vega\Vega.csproj

[info]: OmniSharp.Script.ScriptProjectSystem Detecting CSX files in 'c:\Users\flaur\Desktop\vega'. [info]: OmniSharp.Script.ScriptProjectSystem Could not find any CSX files [info]: OmniSharp.Services.WorkspaceHelper Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider [info]: OmniSharp.Startup Configuration finished.

**Comment by DustinCampbell** [comment]
It looks like a permissions issue with `c:\Users\flaur\Desktop\vega`?

**Comment by FilipLaurentiu** [comment]
I don't have anything like that. 
I got this problem even if I start a project with "dotnet new .."

**Comment by DustinCampbell** [comment]
Was VS Code started in a way that lacks permissions? What happens if you launch VS Code as an administrator?

**Comment by FilipLaurentiu** [comment]
Starting OmniSharp server at 22.08.2017, 19:30:52
    Target: c:\Users\flaur\Desktop\vega-master\vega.sln

OmniSharp server started
    Path: C:\Users\flaur\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\OmniSharp.exe
    PID: 27204

OmniSharp: -s c:\Users\flaur\Desktop\vega-master\vega.sln --hostPID 20340 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
[info]: OmniSharp.Startup
        Omnisharp server running using Stdio at location 'c:\Users\flaur\Desktop\vega-master' on host 20340.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\Users\flaur\Desktop\vega-master
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Omnisharp will use local MSBuild.
    MSBUILD_EXE_PATH: C:\Users\flaur\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild\MSBuild.exe
    MSBuildExtensionsPath: C:\Users\flaur\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in 'c:\Users\flaur\Desktop\vega-master\vega.sln'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: c:\Users\flaur\Desktop\vega-master\vega.csproj
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        Could not write lines to file "obj\Debug\netcoreapp2.0\vega.csproj.CoreCompileInputs.cache". Access to the path 'c:\Users\flaur\Desktop\vega-master\obj\Debug\netcoreapp2.0\vega.csproj.CoreCompileInputs.cache' is denied.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file 'c:\Users\flaur\Desktop\vega-master\vega.csproj'.
c:\Users\flaur\Desktop\vega-master\vega.csproj

[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\flaur\Desktop\vega-master'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Services.WorkspaceHelper
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Startup
        Configuration finished.

**Comment by FilipLaurentiu** [comment]
same thing

**Comment by DustinCampbell** [comment]
That was launching VS Code as an admin?

**Comment by FilipLaurentiu** [comment]
yes

**Comment by DustinCampbell** [comment]
interesting. Is it possible that this something else has this file locked? I've not seen particular issue before.

**Comment by FilipLaurentiu** [comment]
I start a new project, just "dotnet new web" and no modification

Starting OmniSharp server at 22.08.2017, 19:34:06
    Target: c:\Users\flaur\Desktop\test1

OmniSharp server started
    Path: C:\Users\flaur\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\OmniSharp.exe
    PID: 16776

OmniSharp: -s c:\Users\flaur\Desktop\test1 --hostPID 21588 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
[info]: OmniSharp.Startup
        Omnisharp server running using Stdio at location 'c:\Users\flaur\Desktop\test1' on host 21588.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\Users\flaur\Desktop\test1
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Omnisharp will use local MSBuild.
    MSBUILD_EXE_PATH: C:\Users\flaur\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild\MSBuild.exe
    MSBuildExtensionsPath: C:\Users\flaur\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        No solution files found in 'c:\Users\flaur\Desktop\test1'
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: c:\Users\flaur\Desktop\test1\test1.csproj
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        Could not write lines to file "obj\Debug\netcoreapp2.0\test1.csproj.CoreCompileInputs.cache". Access to the path 'c:\Users\flaur\Desktop\test1\obj\Debug\netcoreapp2.0\test1.csproj.CoreCompileInputs.cache' is denied.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file 'c:\Users\flaur\Desktop\test1\test1.csproj'.
c:\Users\flaur\Desktop\test1\test1.csproj

[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\flaur\Desktop\test1'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Services.WorkspaceHelper
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Startup
        Configuration finished.

**Comment by DustinCampbell** [comment]
Out of curiosity, could you try creating a project within a folder other than your desktop? This looks very much like a permissions problem but I'm not sure what might cause it.

Try this: right click on C:\Users\DustinCa\Desktop in Windows Explorer, choose Properties, and then click the Security tab. Does every group or user have full control?

**Comment by FilipLaurentiu** [comment]
Every Group or user have full control. But I start a new project in different location and now work. Where is the problem ?

**Comment by DustinCampbell** [comment]
I'm not certain what the cause is as I'm unfamiliar with your system setup. However, it seems that there's some sort of permissions problem on your machine that keeps OmniSharp unable to write files to your Desktop folder. The issue doesn't seem to be a problem with C# for VS Code, but I'm not an expert on file permissions. :smile:

**Comment by FilipLaurentiu** [comment]
I found the problem. Bitdefender 2017

**Comment by FilipLaurentiu** [comment]
Thank you very much for help !

**Comment by DustinCampbell** [comment]
Excellent! I'm glad to hear you found the cause!
