### ISSUE TITLE
not getting csharp intellisense

### ISSUE THREAD

**Issue by Jack85** [OmniSharp/omnisharp-vscode#1741]
Extension | Author (truncated) | Version
-- | -- | --
aessoft-class-autocomplete | AES | 0.1.0
stylus | Ala | 0.0.4
stylus | buz | 0.1.0
npm-intellisense | chr | 1.3.0
path-intellisense | chr | 1.4.2
vscode-eslint | dba | 1.2.11
vscode-npm-source | dku | 1.0.0
vscode-npm-script | eg2 | 0.2.0
vscode-nupkg | eri | 0.0.8
vscode-npm | fkn | 3.3.0
flow-for-vscode | flo | 0.7.1
vscode-firefox-debug | hbe | 0.15.3
vue-snippets | hol | 0.1.2
csharpextensions | jch | 1.3.0
nuget-reverse-package-search | jes | 0.1.68
vscode-nuget-package-manager | jmr | 1.1.4
sublime-babel-vscode | jos | 0.2.6
net-core-project-manager | ksu | 0.3.6
csharpfixformat | Leo | 0.0.32
tgit-cmds | mbi | 1.1.1
vscode-less | mrm | 0.6.3
csharp | ms- | 1.12.1
debugger-for-chrome | msj | 3.2.0
vetur | oct | 0.9.5
csharp2ts | raf | 0.0.17
vscode-flow | rto | 276.3.0
aspnet-helper | sch | 0.6.3
stylelint | shi | 0.28.0
language-stylus | sys | 1.7.3

Steps to Reproduce:

    dotnet build
    no csharp intelisense

using extension omnisharp>
yes c# ver 1.12.1

in vs 2017 intellisense works

**Comment by DustinCampbell** [comment]
Hi! Could you provide more detailed repro steps? That would greatly help us try and reproduce the issue.

**Comment by Jack85** [comment]
any csharp file I have, I get no intellisense even after dotnet build, you can try main or startup.cs

**Comment by DustinCampbell** [comment]
Could you provide your OmniSharp Log from VS Code? You can retrieve it using the following steps:

1. Open your project folder in VS Code.
2. Select View->Output from the menu to open the Output pane.
3. Select "OmniSharp Log" from the dropdown in the top-right corner of the Output pane.

Select the whole log and paste it here.

**Comment by lukepuplett** [comment]
I initially couldn't get this to work either. The C# extension seemed to install fine weeks ago, and I reinstalled, but after `dotnet new webapi` no flame icon appeared and no intellisense for my .cs files.

Also no OmniSharp Log in the dropdown. So I restarted VS Code and then spotted in the Output pane for C# these messages:

> Updating C# dependencies...
> Platform: win32, x86_64
> 
> Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (21928 KB) .................... Done!
> Downloading package '.NET Core Debugger (Windows / x64)' (39217 KB) .................... Done!
> 
> Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'
> Installing package '.NET Core Debugger (Windows / x64)'
> 
> Finished

So I left it alone for a bit and it all kicked in. Not sure how its supposed to work but merely installing the extension, when it says its installed, it isn't and needs a restart and then it begins installing. I dunno. Odd design.

All working now.

Luke

**Comment by DustinCampbell** [comment]
@lukepuplett: I'm not sure what happened in you install, but the design does not require a restart. When the C# extension loads (usually because a .cs file is opened) it checks to see if it has downloaded the platform-specific dependencies, and if not, goes and gets them. That's all.

**Comment by DustinCampbell** [comment]
@Jack85: Are you still experiencing this issue? If so, could you provide the OmniSharp Log using the steps I specified above?

**Comment by Jack85** [comment]
I can check on 18th sept,  currently out of ofice.  Meanwhile tried on smaller computer,  there was it working.qurious if that will be conected with restart. I ll let u know..

**Comment by Jack85** [comment]
still getting no intelisense on working machine, in output I get log for omnisharp
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

**Comment by DustinCampbell** [comment]
Have you tried increasing the timeout as suggested by the message above?

**Comment by Jack85** [comment]
no, no Idea where to do it, message gives no clue.

**Comment by DustinCampbell** [comment]
In VS Code, select Preferences->Settings and add it in your User Settings.

**Comment by Jack85** [comment]
ok, just disabled another csharp extension that was active and omnisharp works now. 
Other one was: jchannon.csharpextensions

**Comment by Jack85** [comment]
so connected to multiple csharp extensions at same time running, causing it not to work with misleading messages. Thanks for directions, closing now.

**Comment by DustinCampbell** [comment]
FYI @jchannon
