### ISSUE TITLE
The .NET Core debugger cannot be installed. The debugger requires macOS 10.12 (Sierra) or newer

### ISSUE THREAD

**Issue by Andergraw** [OmniSharp/omnisharp-vscode#1742]
## Environment data
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4

## Steps to reproduce
Install C# Extension and open any template solution

## Expected  behavior
Install extension correctly

## Actual behavior
Cannot install on macOS El Capitan (10.11.6). I installed dotnet v1 because v2 is not available for my OS.

**Comment by gregg-miskelly** [comment]
@Andergraw The debugger can no longer run on El Capitan. If you are only interested in editing, you can shut this warning off. Is it possible for you to upgrade?

**Comment by Andergraw** [comment]
No, it's not. But it used to work, right? Isn't there a way to install a previous version or something?
Thank you very much for your super fast answer, BTW!

**Comment by gregg-miskelly** [comment]
Will you be stuck on El Capitan for a long time? Or it just that this isn't something you have the time to change right now?

You can set the option to disable auto extension updates in VS Code, and then manually install [v1.11.0](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.11.0) from the .vsix file using [these instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases). Though the one problem with this is that you will also miss out on new language service features. But this is certainly a great option if you can't upgrade your OS yet, but it is a point-in-time problem.

**Comment by Andergraw** [comment]
Not sure how long, but I'm in the middle of a project right now and I have no intention to migrate.
So that's a great temporary solution. Just as a comment, it's kind of a dead end...I cannot install .NET v2 because I don't have Sierra and I cannot be updated with v1 because I don't have Sierra. And it's just the previous OS, we are not talking about an oldie.
In any case, thank you very much for your kind attention, Gregg. 30 minutes to solve my problem. That's awesome.
Cheers!
