### ISSUE TITLE
Improvement: Auto-Complete switch statements containing enums

### ISSUE THREAD

**Issue by spaggi** [OmniSharp/omnisharp-vscode#1752]
Hi,

this is not an issue but an improvement suggestion.
In Visual Studio, I always heavily relied on switch statement autocompletion with enums. As far as I understood, this cannot be done with snippets currently.

Example:

```
enum teams {
red,
blue
}

teams team;

//I type
switch (team) -> Press Tab
```

Shoudl autocomplete to
```

switch (team) {
     case teams.red:
        break;
     case team.blue:
        break;
```

Thank you very much!

**Comment by DustinCampbell** [comment]
Thanks for the request. Yes, this is very difficult to do with VS Code's snippets today.

**Comment by aldass** [comment]
agreed! I'm a longtime Visual Studio w/ReSharper user in the process of converting to VSCode and **really**, **_really_**, **_`really`_** miss this feature in VSCode.

**Comment by JDeuce** [comment]
any chance you can elaborate on what the challenges are?

**Comment by Shizola** [comment]
I too really, really miss this feature :(

**Comment by danoli3** [comment]
Absolutely please add this

**Comment by DustinCampbell** [comment]
@TheRealPiotrP: No. This is a code snippets feature.

**Comment by PaulWilhelmsen** [comment]
Will it be added? I really miss this feature

**Comment by MatthewS2077** [comment]
Please add this, but if it can't be done as a snippet can it be done some other way, like generate the statement in the clipboard so I can manually paste...

**Comment by tarwich** [comment]
This is a great idea. However, I wouldn't recommend this as a snippet, but rather as a code action. A code action is the little lightbulb that pops up, or the menu you get when you press `Ctrl` + `.`. 

I rarely need to be able to tab-complete an enum. I don't need that kind of speed. But typing out an enum, and pressing `Ctrl` + `.` and then selecting "Populate enum variants" or something would be quite sufficient. Not to mention it would work on a switch statement that's already partially filled out -- for example, if a new option has been added to an enum.

**Comment by rchande** [comment]
This does work in Visual Studio...

**Comment by Thomas-6freedom** [comment]
I really like this too in VSCode

**Comment by JoeRobich** [comment]
You can invoke this from the fixes menu when your cursor is on the `switch` keyword

![image](https://user-images.githubusercontent.com/611219/71859250-1ba7b680-30a3-11ea-8c9a-5a5a6313fa23.png)

after

![image](https://user-images.githubusercontent.com/611219/71859279-2f531d00-30a3-11ea-819d-e4773afa6435.png)

**Comment by JDeuce** [comment]
If that is implemented now then this issue is probably closable. There was nothing like that before.

**Comment by yogster** [comment]
Which version of omnisharp-vscode has this been implemented in? I'm using 1.21.9 and can't seem to make it work.

**Comment by JoeRobich** [comment]
@yogster I have "OmniSharp: Enable Roslyn Analyzers" enabled but not sure if that is necessary.

**Comment by yogster** [comment]
@JoeRobich That did the trick! Thanks for the tip.

**Comment by patrick-radulian** [comment]
@yogster How'd you manage to trigger auto-complete? I am also running version 1.21.9 and cannot seem to tickle this behavior out of vs-code.

**Comment by yogster** [comment]
@patrick-radulian go to settings, and search for "Roslyn":

<img width="973" alt="Screenshot 2021-03-10 at 20 47 56" src="https://user-images.githubusercontent.com/4075933/110695601-ff8d3100-81e1-11eb-9038-38fb912a8801.png">

**Comment by patrick-radulian** [comment]
@yogster I have that setting activated - I meant how do you trigger the actual autocomplete suggestion in the editor? I can't seem to get any useful suggestions.

**Comment by DanArcherOnline** [comment]
@patrick-radulian 
for anyone else ending up here,
on a mac, press <kbd>cmd</kbd> + <kbd>.</kbd> on the `switch` keyword
I can only assume it would be <kbd>ctrl</kbd> + <kbd>.</kbd> on windows 🤔
![image](https://user-images.githubusercontent.com/46483718/115273387-71aa4b80-a17a-11eb-8843-f685ec1f44fc.png)

**Comment by PCoelho** [comment]
This worked for me but a couple of gotchas:

- After enabling the Roslyn Analyzers you have to restart vsc or restart Omnisharp
- The "Add missing cases" only shows up for me if my ticker is just before the _s_ in _switch_ **and** _default:_ is within the brackets already. If the switch is empty { } it wont work.
