### ISSUE TITLE
Set next line in debugger

### ISSUE THREAD

**Issue by kostyamy** [OmniSharp/omnisharp-vscode#1753]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

are there any plan to implement similar feature outlined here:
https://github.com/Microsoft/vscode-cpptools/issues/1025

without such feature it makes little sense to stay in VS Code on windows but rather go straight to full blown Visual Studio.

Thanks in advance

**Comment by gregg-miskelly** [comment]
It has been on our backlog, and it is something we are interested in. But VS Code doesn't actually support it (just the protocol) so it hasn't been a big priority for us.

**Comment by gregg-miskelly** [comment]
And just to be clear: if you are happy with VS, please don't think Microsoft is trying to convince you to switch to VS Code. We hope VS Code is an interesting option for folks who either can't use VS (ex: because they are on Linux) or who prefer the "lightweight editor" way of working that VS Code specializes in to the "full IDE" experience that VS aims to provide. But IMHO I hope VS always stays the best C# IDE for folks who want a "full IDE" experience.

**Comment by kostyamy** [comment]
Thank you Gregg for responding. Perhaps you have misunderstood me but I never implied that anyone is trying to convince me to switch back to VS. I use both on daily basis. Been working with MS build tools and IDEs since 89 and still convinced at this time VS is the best IDE out there. However in highly diverse dev team i have to make an attempt to stay somewhat on the same page with our non-ms developers - guys who works on client side and mostly use MAC (i'm sure you that kind -ms haters for no reason). So having unified tools set would definitely help overall moral..

Another good feature to have would be variable inspector similar to VS so i can extract/replace variable name with pre-formatted value.
for example sqlCommand.ConnextText reveals text value without "\r\n" but as actual "printed" text so i can copy/paste into SQL Management tool to debug resulted query.

**Comment by gregg-miskelly** [comment]
@kostyamy You can achieve a "poor man's" version of the raw text visualizer with the ",nq" format specifier.

Example: 
1. Go to the debug console.
2. Evaluate 'exampleVariable'
3. Result: `"Hello\nWorld"`
4. Evaluate 'exampleVariable,nq'
5. Result:
```
Hello
World
```

**Comment by bernardbr** [comment]
Thanks a lot @gregg-miskelly !

**Comment by gregg-miskelly** [comment]
I had trouble finding this issue, so adding a note here - this issue tracks supporting Set Next Statement in vsdbg.

**Comment by mokcsayadam** [comment]
Still no progress with this feature?

**Comment by kostyamy** [comment]
Thank you Greg

> I had trouble finding this issue, so adding a note here - this issue tracks supporting Set Next Statement in vsdbg.

Thank you  Greg

**Comment by gregg-miskelly** [comment]
We have heard a few requests for this lately, and from my own usage I also constantly use this feature, so I decided to create a quick prototype to see if we can support this from the editor context menu through VS Code's extensibility APIs. So far, things are looking promising. So I will tentatively add this to 1.18.
