### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by zhangmn799** [OmniSharp/omnisharp-vscode#1757]
## Environment data
VS Code version:1.16.1
C++ Extension version:0.13.0

## Steps to reproduce
1.Install preinstall [\\vspreinstall.corp.microsoft.com\preinstall\preinstall.cmd ](url)
2.Install vscode
3.Install cingwin32
4.install c++ extension [\\cpvsbuild\Drops\MDDDebugger\CppTools\20170914.3\Extension\cpptools.vsix
](url)
5.Create a folder named test, create a file named main.cpp in test as following:
#include<iostream>
using namespace std;
int main()
{
cout<<"hello world"<<endl;//set a bp
return 0;
}
6.Compara project with command "g++ -g -o main.exe main.cpp"
7.Open vscode, open test folder, configure launch.json file
8.Set a bp in line cout<<"hello world"<<endl of main.cpp.
9.F5

## Expected  behavior
It will hit bp

## Actual behavior
It will pop an picture similar to Debug->configure->c++(GDB/LLGDB), F5(or hit mouse) it will pop a error as following:
![4](https://user-images.githubusercontent.com/26423555/30478401-7d8387a6-9a43-11e7-9bee-82ef453d372d.PNG)

**Comment by DustinCampbell** [comment]
This repo is for C# for VS Code. I'll go ahead and move your issue over to https://github.com/Microsoft/vscode-cpptools/issues.

**Comment by DustinCampbell** [comment]
This issue was moved to Microsoft/vscode-cpptools#1038

**Comment by bobbrow** [comment]
moderator: can you please redact Microsoft internal paths?  @zhangmn799, please don't post those.

**Comment by DustinCampbell** [comment]
Done. Sorry -- I hadn't noticed that.

**Comment by pieandcakes** [comment]
@DustinCampbell @bobbrow I assume this is CTI filing bugs.

**Comment by DustinCampbell** [comment]
@pieandcakes: It'd be good to let them know that their GitHub account should at least be identifiable. :smile:
