### ISSUE TITLE
Blocking Startup of Other Extensions

### ISSUE THREAD

**Issue by TheColorRed** [OmniSharp/omnisharp-vscode#1759]
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
```

VS Code version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:27:49.891Z)
C# Extension version: 1.12.1

## Steps to reproduce

Start VS Code

## Expected  behavior

The needed extensions should all start up nearly instantly

## Actual behavior

This extension is blocking startup of other extensions causing them to take ~45+ seconds for the other extensions to become usable.

This seems to only occurs on non C# workspaces. When I open my `php` workspace this happens.

**Comment by DustinCampbell** [comment]
VS Code is designed such that extensions run in separate processes and shouldn't block one another. Could you provide a specific repro? Do you have an example of an extension that seems blocked while the C# extension is starting up?

**Comment by TheColorRed** [comment]
Here is a repo: https://github.com/laravel/laravel

Here is an extension: https://marketplace.visualstudio.com/items?itemName=ryannaddy.laravel-artisan

Command: `Artisan: Start Server`

**Comment by cartermp** [comment]
Will close this out since it's been quite a while and the extension loading mechanism for VSCode has certainly improved over the past 3 years. Please do ping back if this happens again with an updated VSCode and C# extension, though.
