### ISSUE TITLE
Multi Root Workspaces not supported

### ISSUE THREAD

**Issue by NCC1701M** [OmniSharp/omnisharp-vscode#1762]
## Environment data
`dotnet --info` output:
.NET-Befehlszeilentools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

VS Code version: 1.17.0-insider
C# Extension version: 1.12.1

## Steps to reproduce
Run the following commands
````batch
mkdir XPlatform
cd .\XPlatform
mkdir XPlatform.Shared
dotnet new web -n XPlatform.Server
tns create XPlatform.Mobile --ng --appid com.ejot.XPlatform
ng new XPlatform.Web
````
Then create a code workspace file (XPlatform.code-workspace) with the fpllowing content:
````json
{
  "folders": [
    {
      "path": "XPlatform.Mobile"
    },
    {
      "path": "XPlatform.Server"
    },
    {
      "path": "XPlatform.Shared"
    },
    {
      "path": "XPlatform.Web"
    }
  ],
  "settings": {}
}
````
Open VSCode Insider.

## Expected  behavior
Omnisharp-vscode should detect that there is a c# project in XPlatform.Server and provide intellisense for .cs files in this folder.

## Actual behavior
Omnisharp still shows the Running state
![image](https://user-images.githubusercontent.com/7260053/30631396-642a6fb4-9de4-11e7-9494-21e4ae81dcf3.png)

When I click on "Running" it only let me select the project XPlatform.Mobile
![image](https://user-images.githubusercontent.com/7260053/30631464-9499f53e-9de4-11e7-919e-7e6e059bc1ec.png)

The Omnisharp log shows the following output:
````
Starting OmniSharp server at 2017-9-20 09:18:10
    Target: C:\VSCode\XPlatform\XPlatform.Mobile

OmniSharp server started
    Path: C:\Users\<<user>>\.vscode-insiders\extensions\ms-vscode.csharp-1.12.1\.omnisharp\OmniSharp.exe
    PID: 9460

OmniSharp: -s C:\VSCode\XPlatform\XPlatform.Mobile --hostPID 8552 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
[info]: OmniSharp.Startup
        Omnisharp server running using Stdio at location 'C:\VSCode\XPlatform\XPlatform.Mobile' on host 8552.
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in C:\VSCode\XPlatform\XPlatform.Mobile
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Omnisharp will use local MSBuild.
    MSBUILD_EXE_PATH: C:\Users\<<user>>\.vscode-insiders\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild\MSBuild.exe
    MSBuildExtensionsPath: C:\Users\<<user>>\.vscode-insiders\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        No solution files found in 'C:\VSCode\XPlatform\XPlatform.Mobile'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'C:\VSCode\XPlatform\XPlatform.Mobile'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Services.WorkspaceHelper
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Startup
        Configuration finished.
````

**Comment by DustinCampbell** [comment]
We're planning on adding support to OmniSharp here: https://github.com/OmniSharp/omnisharp-roslyn/issues/909. I'll keep this to track the updates that will be needed to C# for VS Code.

**Comment by Jonatthu** [comment]
![image](https://user-images.githubusercontent.com/3742176/45591106-2b731880-b8fd-11e8-87fc-8d5a068ade23.png)
Looks like this is still happening on 1.16.1

**Comment by AlseinX** [comment]
On the last few days of Year 2019, this problem still happens.
Switching among multiple VS Code instances is still needed for multiple solutions.
This issue has been lasting for over 2 years without being solved.
It there any technical problem that prevents implementing this or this commonly requested feature is placed on very low priority?
