### ISSUE TITLE
Question: Support for Roslyn Syntax Visualizer

### ISSUE THREAD

**Issue by jensg** [OmniSharp/omnisharp-vscode#1766]
Is there a tool/plugin like: [https://github.com/dotnet/roslyn/wiki/Syntax-Visualizer](https://github.com/dotnet/roslyn/wiki/Syntax-Visualizer) available or on a roadmap?

**Comment by DustinCampbell** [comment]
No, there is nothing like this on the road map. The ability to create UIs in VS Code is extremely limited.
