### ISSUE TITLE
c# Dynamic variable intellisense not working

### ISSUE THREAD

**Issue by franklupo** [OmniSharp/omnisharp-vscode#1768]
## Environment data
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  18.2
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
C# Extension version:

## Steps to reproduce
Create dynamic variable

> int time=1000;
> TimeSpan.FromSeconds(time).  

dot or  ctrl + space show combo selection 

> dynamic time=1000;
> TimeSpan.FromSeconds(time).

dot or  ctrl + space not workign

**Comment by DustinCampbell** [comment]
Unfortunately, as soon as you use a dynamic variable, the type of the expression cannot be determined until runtime. Visual Studio has the same behavior.

cc @Pilchie: Is there a Roslyn issue tracking dynamic IntelliSense? All I could find was https://github.com/dotnet/roslyn/issues/15974.

**Comment by Pilchie** [comment]
Not that I can think of.  @kuhlenh or @rchande?

**Comment by franklupo** [comment]
Ok thanks
