### ISSUE TITLE
This extension is breaking the vscode search service for some reason (setting my computer on fire)

### ISSUE THREAD

**Issue by peabnuts123** [OmniSharp/omnisharp-vscode#1770]
## Environment data
**`dotnet --info` output**:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

```
**VS Code version**: Version 1.16.1 (1.16.1)
**C# Extension version**: 1.12.1

## Steps to reproduce
1.) Install and enable this extension

## Expected  behavior
My computer does not catch on fire.

## Actual behavior
My computer catches on fire.

Jokes aside, as far as I can tell, something is currently very wrong with this extension as within ~the last couple of weeks my computer has been lighting up when I run vscode. An entire core goes to 100% usage when I open it and stays that way _forever_. I've tracked this down to the vscode SearchService which is maintaining about 6-7 `find` processes that go to sleep after ~10-20 seconds but don't ever exit and, as I said, leave the searchService at ~100% core utilisation perpetually.

I've tracked the cause of this down to this extension. If I disable it, it fixes the problem completely. If i re-enable it, the problem comes back. This occurs with **no** custom settings enabled in my user or workspace settings other than a few folder excludes (to ensure the search service doesn't index my node_modules folder, etc.).

I can't think of anything that would effect this, I run a Macbook Pro with a fairly standard setup all things considered. It really seems like a recent release has created some kind of epic bug. 

Any ideas?

Edit: It should also be noted that this is not developing in a .NET project, I am working in a JavaScript NodeJS project. I am not using .NET at the moment at all.

**Comment by DustinCampbell** [comment]
There's not really much we can do with the C# for VS Code extension. Essentially, we have defined the extension to activate based on the presence of [several globbing patterns](https://github.com/OmniSharp/omnisharp-vscode/blob/master/package.json#L205-L211):

```
"workspaceContains:project.json",
"workspaceContains:*.csproj",
"workspaceContains:*.sln",
"workspaceContains:*.csx",
"workspaceContains:**/*.csproj",
"workspaceContains:**/*.sln",
"workspaceContains:**/*.csx"
```

I wouldn't expect that VS Code would take quite so long to search these globs.

**Comment by peabnuts123** [comment]
It seems I may have jumped the gun a bit on creating this issue. As per some comments on [this thread](https://github.com/Microsoft/vscode/issues/34434#issuecomment-332034680) it looks like that `workspaceContains` call is the root cause but is an upstream issue. This issue can probably be closed. Sorry about that!

**Comment by DustinCampbell** [comment]
Not a problem! Thanks for bringing the issue to my attention. I'm tracking the issues on the VS Code repo now.
