### ISSUE TITLE
Place dialog shows every time I open a folder with multiple @dotnet core 'roots'

### ISSUE THREAD

**Issue by BryanWilhite** [OmniSharp/omnisharp-vscode#1773]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```
VS Code version:
1.16.1
27492b6bf3acb0775d82d2f87b25a93490673c6d

C# Extension version:
see attachment for extensions report
[vscode-extensions.zip](https://github.com/OmniSharp/omnisharp-vscode/files/1353652/vscode-extensions.zip)

## Steps to reproduce

* open vscode from the folder of [my dotnet-core repo](https://github.com/BryanWilhite/dotnet-core)
* wait around 30 seconds for loading to complete (especially that F# extension)

## Expected  behavior
Nothing should happen: vscode should be in expected ready state.

## Actual behavior
vscode shows this dialog:
![dlkouufvoaapmp5](https://user-images.githubusercontent.com/5226627/31145382-78ee69b0-a838-11e7-861b-b39c88e38bee.jpg)

**Comment by DustinCampbell** [comment]
FWIW, after looking at this dialog again, I don't think it's displayed by C# for VS Code. We have a project and solution picker dialog, but we don't prefix items in it with [SLN] or [DIR]. It looks to me like this is displayed by the Ionide extenion here: https://github.com/ionide/ionide-vscode-fsharp/blob/ab7f3edce0a9d3a5613cd81cc9bbfeb2d24eb69d/src/Core/Project.fs#L234-L254. cc @enricosada

**Comment by BryanWilhite** [comment]
Got it: extension hell.
