### ISSUE TITLE
Intellisense is shown inside comments with XML documentation

### ISSUE THREAD

**Issue by jasoncavett** [OmniSharp/omnisharp-vscode#1778]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```

VS Code version: 1.16.1
C# Extension version: 1.12.1

## Steps to reproduce
1. Create a block comment with XML documentation like:
```
/// <summary>
/// 
/// </summary>
```

2. Type sentences in the comment.
3. Ending with a period causes auto complete to trigger and is very annoying to type.

## Expected  behavior
I would expect that the plugin honors the `editor.quickSuggestions` in https://github.com/Microsoft/vscode/issues/9504. The editor behaves the way I would expect if I disable the C# plugin.

## Actual behavior
Intellisense is shown and is triggered when I'm trying to type sentences in my comment.

**Comment by DustinCampbell** [comment]
I believe this is a duplicate #1424. Does that look like the same issue you're seeing?

**Comment by jasoncavett** [comment]
Yes, this is the exact issue. Closing this one out in favor of duplicate #1424. Thank you!

**Comment by DustinCampbell** [comment]
Thanks for checking.
