### ISSUE TITLE
Rename Symbol command not working - text does not change

### ISSUE THREAD

**Issue by jtsom** [OmniSharp/omnisharp-vscode#1793]
## Environment data
`dotnet --info` output: 2.0.0
C# Extension version: 1.12.1

- VSCode Version: Code - Insiders 1.18.0-insider (de68b077b53d6eeafeaf39699d6384c4b8750a19, 2017-10-16T05:22:08.224Z)
- OS Version: Linux x64 4.10.0-37-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7
bracket-pair-colorizer|Coe|0.10.9
erb|Cra|0.0.1
html-leaf|Fra|0.1.3
json-to-ts|Mar|1.5.3
Angular-BeastCode|Mik|5.0.7
material-icon-theme|PKi|2.2.2
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
githistory|don|0.2.3
tslint|eg2|1.0.11
vscode-ember|emb|0.1.0
prettier-vscode|esb|0.24.0
auto-rename-tag|for|0.0.14
search-node-modules|jas|1.2.0
Angular2|joh|2.7.0
csharp|ms-|1.12.1
debugger-for-chrome|msj|3.3.1
EmberES6Snippets|pha|2.1.2
typescript-hero|rbb|1.5.0
vscode-icons|rob|7.15.0
git-merger|sha|0.3.6
autoimport|ste|1.2.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Click on a symbol (class name)
2. Hit F2 (Or right click and choose rename)
3. Should rename the symbol and any references to it, but it does not, nothing changes.

**Comment by DustinCampbell** [comment]
Hi! Could you provide your OmniSharp Log? You can see this by selecting View->Output from the VS Code main menu and then choose "OmniSharp Log" from the drop-down at the top-right of the Output pane.

**Comment by franklupo** [comment]
I have sane problem.

Best regards

**Comment by DustinCampbell** [comment]
@franklupo: I have the same request:

> Hi! Could you provide your OmniSharp Log? You can see this by selecting View->Output from the VS Code main menu and then choose "OmniSharp Log" from the drop-down at the top-right of the Output pane.

**Comment by franklupo** [comment]
Story not riproduce error

**Comment by douglaswaugh** [comment]
I'm having the same problem.

Here's my omnisharp log

```
Starting OmniSharp server at 2017-12-27 13:01:50
    Target: /Users/douglas/repos/noughts-and-crosses/noughts-and-crosses.sln

OmniSharp server started wth Mono
    Path: /Users/douglas/.vscode/extensions/ms-vscode.csharp-1.13.1/.omnisharp/omnisharp/OmniSharp.exe
    PID: 31198

﻿[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.12.6 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/Users/douglas/.vscode/extensions/ms-vscode.csharp-1.13.1/.omnisharp/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin"
            CscToolPath = /Users/douglas/.vscode/extensions/ms-vscode.csharp-1.13.1/.omnisharp/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/douglas/repos/noughts-and-crosses'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /Users/douglas/repos/noughts-and-crosses
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in '/Users/douglas/repos/noughts-and-crosses/noughts-and-crosses.sln'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/douglas/repos/noughts-and-crosses'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/douglas/repos/noughts-and-crosses' on host 31180.
```

**Comment by arie-itecho** [comment]
I'm having the same issue. Here is my Omnisharp log:

`[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 245,
  "Command": "/rename",
  "Arguments": {
    "FileName": "c:\\work\\aircost\\PartDrawings\\Sketches\\RectTaper.cs",
    "Line": 7,
    "Column": 25,
    "WantsTextChanges": true,
    "RenameTo": "OffsetX"
  }
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 245,
  "Command": "/rename",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "Changes": [],
    "ErrorMessage": null
  },
  "Seq": 1699,
  "Type": "response"
}
`

**Comment by cartermp** [comment]
This doesn't reproduce with the latest VSCode and C# plugin, so I'll close out this older issue.
