### ISSUE TITLE
Debugger cannot load symbols when target app is running under .NET Core 2.1 on Mac/Linux

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#1796]
https://github.com/dotnet/coreclr/pull/10772 made a change so that IL-only modules will be directly mapped into the target process on Mac/Linux so they will be in the on-disk format. The debugger expects imagines to be in the in-memory PE format (see `System.Reflection.Adds.MetadataFileAndRvaResolver` and `ManagedDM::CDbiCallback::DoLoadModuleImpl` in debugger closed-source repos). This will cause the debugger to read in the wrong place for certain things, such as the debugger directory.

The debugger needs to either switch to always reading off disk, or get an API from CoreCLR to understand the memory format.

**Comment by gregg-miskelly** [comment]
It would be nice if we could resolve this for 1.12

**Comment by chuckries** [comment]
Embedded pdb support is broken on UNIX platforms starting in coreclr 2.1 due to this same issue.

**Comment by gregg-miskelly** [comment]
I think we could fix this by:
1. Fixing PEFile.cpp to encode record PointerToRawData when the module is either in the Unknown or On Disk memory layout.
2. Have the the symbol provider use `DkmFileTransferStream.ReadFirst` if it needs to get the bytes off disk.
3. Compiling impl\BaseDMServices\Deployment.cpp on Unix

**Comment by GuerrillaCoder** [comment]
I am unable to hit breakpoints when attaching to process. I get the symbols not loaded message.

My project is set to `<TargetFramework>netcoreapp2.0</TargetFramework>`.  Is this the same as issue you are discussing for 2.1?

Any workaround?

**Comment by gregg-miskelly** [comment]
@GuerrillaCoder: This issue only applies to the not-yet-released version of CoreCLR. Whatever you are running into is something different. Make sure your project is building portable PDBs, and if it is, please open a new issue if you want help.

**Comment by chuckb** [comment]
Unfortunately if this is broken, it makes it kinda hard to debug 2.1 issues...

**Comment by gregg-miskelly** [comment]
@chuckb I hope that we get a fix out soon. If you can debug on Windows in the mean time you can avoid the problem.

**Comment by gregg-miskelly** [comment]
Fixed in 1.14.0-beta2
