### ISSUE TITLE
Add tracepoint support

### ISSUE THREAD

**Issue by rkeithhill** [OmniSharp/omnisharp-vscode#1797]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```
VS Code version: 1.17.2

C# Extension version: 1.12.1

## Steps to reproduce
This is what I need to know.  How can you configure a conditional breakpoint to print a message and continue.  BTW the PowerShell ext debugger supports this (I implemented it :-) )

## Expected  behavior
Should be able to configure a conditional breakpoint that does stuff (write's to output with variable values) and expression specifies whether the debugger breaks or continues.

## Actual behavior
Well none yet, I'm not sure what the syntax would be.

**Comment by gregg-miskelly** [comment]
@rkeithhill How did you hook this feature up to VS Code in the powershell debugger? Does VS Code have some extensibility point for a breakpoint's context menu?

**Comment by rkeithhill** [comment]
No, we use the `Condition` expression.  You can enter either a simple Boolean expression (in PowerShell syntax):
![image](https://user-images.githubusercontent.com/5177512/31917967-834c0a5e-b817-11e7-84cc-5e502ee36223.png)
Or you can enter a statement like so:
![image](https://user-images.githubusercontent.com/5177512/31917980-9799afac-b817-11e7-8dfd-08e9d3497181.png)
The statement has to specify the `continue` keyword otherwise the breakpoint will break at the line.

This was relatively easy to implement because PoweShell supports this capability with the [Set-PSBreakpoint](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/set-psbreakpoint?view=powershell-5.1) command which we use.
