### ISSUE TITLE
LangVersion isn't recognized

### ISSUE THREAD

**Issue by acid-chicken** [OmniSharp/omnisharp-vscode#1798]
## Environment data

`dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

VS Code version:
```
Version 1.18.0-insider
Commit 4b01451cea60f32412098735709fddcac567b33d
Date 2017-10-19T08:25:22.140Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

C# Extension version: `1.12.1`

## Steps to reproduce

1. Create new dotnet project.
2. Open it on VS Code.
3. Click Yes to a dialog which says `Required assets to build and debug are missing from '{project_name}'. Add them?`.
4. Add a node to the csproj file like this.
```diff
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
+   <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
```
5. Edit Program.cs like this.
```csharp
using System;
using System.Threading;
using System.Threading.Tasks;

namespace BugTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            await HelloWorld(CancellationToken.None);
        }

        static async Task HelloWorld(CancellationToken token = default)
        {
            while (token != default && !token.IsCancellationRequested)
            {
                await Console.Out.WriteLineAsync("Hello, world!");
            }
        }
    }
}

```

## Expected  behavior

There is no error.

## Actual behavior

The extension says `Feature 'default literal' is not available in C# 7. Please use language version 7.1 or greater.`.

**Comment by filipw** [comment]
@acid-chicken thanks for the report - this is already fixed in 1.13.0-beta3 release (see [release notes](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.13.0-beta3)). 

You can install the beta yourself [instructions here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) manually or wait for the fix until 1.13.0 stable is out.
