### ISSUE TITLE
1.13.0-beta 3 LangVersion still gives workspace errors

### ISSUE THREAD

**Issue by NinoFloris** [OmniSharp/omnisharp-vscode#1799]
## Steps to reproduce
See https://github.com/OmniSharp/omnisharp-roslyn/issues/961
Run a project with LangVersion latest/7.1 and try one of the new features (default, generic pattern match etc) see an error explaining you need to use 7.1 to use that feature.

**Comment by filipw** [comment]
Can you post the output of your OmniSharp Log? FWIW, it works on my machine (with both `latest` and `7.1`) 🤔

<img width="237" alt="screen shot 2017-10-23 at 17 08 40" src="https://user-images.githubusercontent.com/1710369/31896776-e47ec3c8-b814-11e7-8561-6a3d4712672d.png">

**Comment by NinoFloris** [comment]
Ok reinstalled in my normal vscode, and it seems something was breaking in my insiders version. 
Happy to see it does work 👍
