### ISSUE TITLE
SignatureHelp UI is still open when completionlist ui open

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#18]
_From @BleyChen on January 26, 2016 9:47_

Repro steps:

   1. type c# code as following to trigger the SignatureHelp UI:
    Console.Beep(
   2. backspace four characters ,signaturehelp ui still exists when completionlist ui display   
   
![33](https://cloud.githubusercontent.com/assets/15098626/12577242/1de2b748-c454-11e5-87fa-75d9a43e69fe.png)

  

_Copied from original issue: Microsoft/vscode#2274_

**Comment by DustinCampbell** [comment]
@jrieken -- how would this be an extension issue?

**Comment by jrieken** [comment]
Signature help works like this in VS Code. 

1. you register a trigger character, like `(`
2. when that is hit the language service is asked for signature help on basically each subsequent character being typed
3. signature help stops/hides when the language service return something *falsy* (undefined  et al)

**Comment by DustinCampbell** [comment]
got it -- thanks!

**Comment by DustinCampbell** [comment]
This was fixed by #107
