### ISSUE TITLE
Muti-root workspace issues

### ISSUE THREAD

**Issue by WardenGnaw** [OmniSharp/omnisharp-vscode#1802]
In multi-root workspaces, omnisharp does not correctly use the correct workspace. 

## Environment data
`dotnet --info` output:
.NET Command Line Tools (15.5.0-preview-007044)

Product Information:
 Version:            15.5.0-preview-007044
 Commit SHA-1 hash:  278cbf6c44

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\15.5.0-preview-007044\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.1
  Build    : 5eb2f9bd659ad2161a8e035ac4bccd8f892caa0a
VS Code version: 1.18.0-insider
C# Extension version: 1.12.1

## Steps to reproduce
mkdir console
mkdir mvc
cd console && dotnet new console
cd ..\mvc && dotnet new mvc
open vscode
create launch.json and tasks.json for both projects.
add console folder to workspace
add mvc folder to workspace
debug mvc

## Expected  behavior
Use binaries from mvc bin

## Actual behavior
Loading binaries from the console project instead of mvc, but runs the mvc.dll
Loaded 'C:\Program Files\console \shared\Microsoft.NETCore.App\2.0.1\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Breakpoint warning: A copy of Program.cs was found in dotnetmvc.dll, but the current source code is different from the version built into dotnetmvc.dll.
To allow this breakpoint to be hit: Add '"requireExactSource": false' to launch.json and restart debugging. - e:\VsCodeTest\console\Program.cs:9
**Loaded 'e:\VsCodeTest\mvc\bin\Debug\netcoreapp2.0\mvc.dll'. Symbols loaded.**
Loaded 'C:\Program Files\console\shared\Microsoft.NETCore.App\2.0.1\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\console\store\x64\netcoreapp2.0\microsoft.aspnetcore.hosting.abstractions\2.0.0\lib\netstandard2.0\Microsoft.AspNetCore.Hosting.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\console\shared\Microsoft.NETCore.App\2.0.1\netstandard.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\console\store\x64\netcoreapp2.0\microsoft.aspnetcore.hosting\2.0.0\lib\netstandard2.0\Microsoft.AspNetCore.Hosting.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\console\store\x64\netcoreapp2.0\microsoft.aspnetcore\2.0.0\lib\netstandard2.0\Microsoft.AspNetCore.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\console\store\x64\netcoreapp2.0\microsoft.extensions.configuration.abstractions\2.0.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

**Comment by RichardD012** [comment]
I believe there's already an issue with this: https://github.com/OmniSharp/omnisharp-vscode/issues/1762

**Comment by WardenGnaw** [comment]
Missed that issue. Closing as duplicate.
