### ISSUE TITLE
Cannot evaluate the item metadata "%(FullPath)"

### ISSUE THREAD

**Issue by martinellison** [OmniSharp/omnisharp-vscode#1803]
## Environment data
`dotnet --info` output:
bash: dotnet: command not found...
VS Code version:
Version 1.17.2
Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
Date 2017-10-16T13:57:00.652Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
C# Extension version: 1.12.1

## Steps to reproduce
Load project
Try to use Omnisharp.

## Expected  behavior
Omnisharp works.

## Actual behavior
See below. Omnisharp fails to load project.

Steps to Reproduce:

    load project in VSC
    try to find (say) all occurrences of a variable

Reproduces without extensions: Omnisharp does not load at all if I disable extensions

```
Starting OmniSharp server at 2017-10-24 12:16:48
Target: /path/to/project/Persist.sln

OmniSharp server started wth Mono
Path: /home/martin/.vscode/extensions/ms-vscode.csharp-1.12.1/.omnisharp/run
PID: 8783

OmniSharp: -s /path/to/project/Persist.sln --hostPID 3738 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information
﻿﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/path/to/project' on host 3738."},"Seq":1,"Type":"event"}
info: OmniSharp.DotNet.DotNetProjectSystem
Initializing in /path/to/project
info: OmniSharp.DotNet.DotNetProjectSystem
Auto package restore: False
info: OmniSharp.DotNet.DotNetProjectSystem
Update workspace context
info: OmniSharp.DotNet.DotNetProjectSystem
Resolving projects references
info: OmniSharp.MSBuild.MSBuildProjectSystem
Omnisharp will use local MSBuild.
MSBUILD_EXE_PATH: /home/martin/.vscode/extensions/ms-vscode.csharp-1.12.1/.omnisharp/omnisharp/msbuild/MSBuild.dll
MSBuildExtensionsPath: /home/martin/.vscode/extensions/ms-vscode.csharp-1.12.1/.omnisharp/omnisharp/msbuild
TargetFrameworkRootPath: /usr/lib/mono/xbuild-frameworks
RoslynTargetsPath: /home/martin/.vscode/extensions/ms-vscode.csharp-1.12.1/.omnisharp/omnisharp/msbuild/Roslyn
CscToolPath: /home/martin/.vscode/extensions/ms-vscode.csharp-1.12.1/.omnisharp/omnisharp/msbuild/Roslyn

Detecting projects in '/path/to/project/Persist.sln'.
info: OmniSharp.MSBuild.MSBuildProjectSystem
Loading project: /path/to/project/Assembly-CSharp.csproj
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" cannot be applied to the path "//mscorlib.dll". UNC paths should be of the form \server\share.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
Failed to load project file '/path/to/project/Assembly-CSharp.csproj'.
/path/to/project/Assembly-CSharp.csproj

Loading project: /path/to/project/Assembly-CSharp-Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" cannot be applied to the path "//mscorlib.dll". UNC paths should be of the form \server\share.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
Failed to load project file '/path/to/project/Assembly-CSharp-Editor.csproj'.
/path/to/project/Assembly-CSharp-Editor.csproj

Detecting CSX files in '/path/to/project'.
info: OmniSharp.Script.ScriptProjectSystem
Could not find any CSX files
info: OmniSharp.Services.WorkspaceHelper
Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
info: OmniSharp.Startup
Configuration finished.
```

**Comment by DustinCampbell** [comment]
What version of Mono do you have installed?

**Comment by martinellison** [comment]
> mono --version
Mono JIT compiler version 4.8.0 (Stable 4.8.0.520/8f6d0f6 Wed Mar 15
15:23:40 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors.
www.mono-project.com
    TLS:           __thread
    SIGSEGV:       altstack
    Notifications: epoll
    Architecture:  amd64
    Disabled:      none
    Misc:          softdebug
    LLVM:          supported, not enabled.
    GC:            sgen


Regards,
Martin

**Comment by DustinCampbell** [comment]
Thanks for the additional detail. This looks very similar to https://github.com/OmniSharp/omnisharp-vscode/issues/1276. In that case, updating Mono to the latest stable build (http://www.mono-project.com/download/) did the trick. Could you update Mono and let me know if that solves the issue for you?

**Comment by martinellison** [comment]
Dustin,

I installed Mono using Fedora's DNF installer and the Mono packages there
are at 4.8.0. I update using DNF regularly, so 4.8.0 is DNF's current
version. The Mono project (the page you linked to) appears not to be aware
of Fedora's existence, and has no instructions for installing Mono on
Fedora (it is all about Debian/Ubuntu).
https://fedoraproject.org/wiki/Packaging:Mono warns very strongly against
trying to build Mono from source ("not a trivial matter and may not even
work").

Regards,
Martin

**Comment by DustinCampbell** [comment]
In my experience, the CentOS packages at http://www.mono-project.com/download/#download-lin-centos install just fine on Fedora.

**Comment by martinellison** [comment]
Thanks, I have erased the Fedora mono packages and installed the CentOS
packages from the Mono project, and everything seems to be working now.

Regards,
Martin

**Comment by DustinCampbell** [comment]
That's great to hear @martinellison! Thanks for the update.
