### ISSUE TITLE
[C++]Uninstall cpptools extension pop up an error message

### ISSUE THREAD

**Issue by qian6** [OmniSharp/omnisharp-vscode#1804]
## Environment data
`dotnet --info` output:
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\
VS Code version: 1.17.2 
C# Extension version: **Remove internal Share **
MinGW32: gdb path: c:\mingw\mingw32\bin\gdb.exe

## Steps to reproduce

1. Open vscode as administrator and Install extensionas following:
![capturqqe](https://user-images.githubusercontent.com/20922638/31938697-d3889d1a-b8ea-11e7-9c51-78e53c3b72bd.PNG)
2. It pop up a message and click Reload now as following:
![captuffre](https://user-images.githubusercontent.com/20922638/31938716-e8e477d8-b8ea-11e7-9182-95204f976f3d.PNG)
3. It pop up a message and click Reload as following:
![captcccccure](https://user-images.githubusercontent.com/20922638/31938745-fe52f59a-b8ea-11e7-9b90-2ee616199f84.PNG)
4. Open test folder in attachments directly.
[test.zip](https://github.com/OmniSharp/omnisharp-vscode/files/1410433/test.zip)
5. Click uninstall button. 
![captggggggggure](https://user-images.githubusercontent.com/20922638/31938804-1fb59724-b8eb-11e7-974c-995771c8ace4.PNG)

## Expected  behavior
#1 It can uninstall extension and no error message.

#2 
In the step2, successfully option info should be pop up after complete installion

## Actual behavior
It pop up an error message as following:
![capture](https://user-images.githubusercontent.com/20922638/31938635-ab365db6-b8ea-11e7-84dd-93d03a84d43f.PNG)

## Investigation:
1. I found extension has been uninstalled when open vs again.

**Comment by pieandcakes** [comment]
@qian6 A couple things:
1. This is a cpp extension issue. Please file those at https://github.com/Microsoft/vscode-cpptools. That is the CPP extension GitHub page. This page is the CSharp page.
2. Please don't include internal server paths in the bug filing.
