### ISSUE TITLE
Feature request: csharp.referencesCodeLens.enabled setting

### ISSUE THREAD

**Issue by mcclure** [OmniSharp/omnisharp-vscode#1807]
## Environment data
`dotnet --info` output:

    'dotnet' is not recognized as an internal or external command,
    operable program or batch file.

VS Code version: 1.17.2
C# Extension version: 1.12.1
I am testing on Windows 10.

## Steps to reproduce

Open "user settings" with ctrl-shift-p. In the search box type "References".

A `javascript.referencesCodeLens.enabled` and `typescript.referencesCodeLens.enabled` are found. In other words, it is possible to disable the CodeLens "references" feature selectively for JS/TS only.

There is no `csharp.referencesCodeLens.enabled`, and manually setting one has no effect. The only way to disable the "N references" display in VS Code is to set `editor.codeLens` to false. I am not certain what other features (if any) I am disabling by setting `editor.codeLens` false.

## Expected behavior

- I should be able to disable the "5 references" text which is by default scattered through the code without disabling other features.
- In my opinion, there should be feature parity between the TypeScript and C# modules. If TypeScript allows you to turn off the "references" display for TypeScript only, so should C#.

**Comment by DustinCampbell** [comment]
Thanks! @rchande: Do you want to change the setting you added to match this?

**Comment by mcclure** [comment]
yay

**Comment by filipw** [comment]
@mcclure this is already available in the latest code (not yet released), but as @DustinCampbell mentioned, the names of these settings are different - `csharp.showReferencesCodeLens` and `csharp.showTestsCodeLens`. 

It would definitely make sense to standardize them to match other language ecosystems 👍

**Comment by rchande** [comment]
Sounds good. I'll update the option names today.
