### ISSUE TITLE
Debugger cannot restore with newest builds of the CLI ('coreclr.ad7Engine.json does not exist')

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#181]
C:\Users\jgabr>dotnet --info
.NET Command Line Tools (1.0.0-rc2-002370)

Product Information:
 Version:     1.0.0-rc2-002370
 Commit Sha:  482f36d26b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14316
 OS Platform: Windows
 RID:         win10-x64

Error:

C:\Users\jgabr\.vscode-insiders\extensions\ms-vscode.csharp-1.0.1-rc2\coreclr-debug\bin\Debug\netstandardapp1.5\win7-x64\dummy.pdb
publish: Renaming native host in output to create fully standalone output.
failed to resolve published host in: C:\Users\jgabr\.vscode-insiders\extensions\ms-vscode.csharp-1.0.1-rc2\coreclr-debug\debugAdapters
publish: warning: host executable not available in dependencies, using host for current platform
publish: Published to C:\Users\jgabr\.vscode-insiders\extensions\ms-vscode.csharp-1.0.1-rc2\coreclr-debug\debugAdapters
Published 1/1 projects successfully
C:\Users\jgabr\.vscode-insiders\extensions\ms-vscode.csharp-1.0.1-rc2\coreclr-debug\debugAdapters\coreclr.ad7Engine.json does not exist.

Error: The .NET CLI did not correctly restore debugger files. Ensure that you have .NET CLI version

**Comment by gregg-miskelly** [comment]
@DustinCampbell @caslan FYI, the extension is completely on the floor with newest CLIs.

**Comment by gregg-miskelly** [comment]
The problem is that .NET CLI is failing to copy our contentFiles\any\any items to the publishing directory during 'dotnet publish'

**Comment by gregg-miskelly** [comment]
**NOTES**

1. I know this is a problem on Windows. We will need to wait till tomorrow to confirm / deny if this exists on other platforms also.
2. You can replace 'latest' in the CLI build links to download an older version. For example, here is a link to an older build that I tried a while back -- https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/1.0.0-rc2-002330/dotnet-dev-win-x64.1.0.0-rc2-002330.exe

**Comment by chuckries** [comment]
@pakrym Do you know of any recent changes that would have affected contentFiles for dotnet publish? We are relying on it for a scenario that is now broken.

**Comment by davidfowl** [comment]
I was just going to file this bug.

**Comment by davidfowl** [comment]
Happens on OSX as well.

**Comment by davidfowl** [comment]
https://github.com/dotnet/cli/commit/709f7b7d146ec218cc32e3522ed92af14e578831#diff-21237ad3a7decd8d9b62b36289e2760dL146

**Comment by NotMyself** [comment]
I ran into this as well last night on a clean WINX vm on the fast ring.

**Comment by ejsmith** [comment]
Is there a work around for this issue?

**Comment by Kukkimonsuta** [comment]
@ejsmith you can rollback to older build (1.0.0-rc2-002357 seem to work fine)

https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/1.0.0-rc2-002357/dotnet-dev-win-x64.1.0.0-rc2-002357.exe

**Comment by piotrpMSFT** [comment]
I just opened CLI #2459 to track this. We're treating it as high priority and will get it fixed today. Please do open identified CLI issues in that repo to ensure they get onto the team's radar ASAP.

**Comment by gregg-miskelly** [comment]
Here is a link to the CLI issue: https://github.com/dotnet/cli/issues/2459

**Comment by scottaddie** [comment]
I can confirm that the suggested 1.0.0-rc2-002357 build works for me.

**Comment by miguellira** [comment]
@Kukkimonsuta Thanks for sharing the link, took me awhile to find the OS X version of 2357, for those looking:

https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/1.0.0-rc2-002357/dotnet-dev-osx-x64.1.0.0-rc2-002357.pkg

Also, unlike the Windows version there isn't an uninstaller for the .pkg fie so you have to manually remove it. I usually do the following:

```console
sudo rm -rf /usr/local/share/dotnet/
pkgutil --pkgs | grep com.microsoft.dotnet | while read -r line; do sudo pkgutil --forget $line; done
```

Lastly, it appears as though as long as you launch the debugger installation on VS Code or VS Code Insiders **_after_** installing 2357 you'll have a working extension and you can then upgrade to the latest CLI without issue - I'm currently on `1.0.0-rc2-002374` with working debuggable editors.

**Comment by davidfowl** [comment]
This is fixed with the latest CLI. Get version >= `1.0.0-rc2-2392`

**Comment by jeffpapp** [comment]
Can confirm this works for me on Mac 10.11.4 with `dotnet --version 1.0.0-rc2-002392`.  I'm assuming this will also fix debugging on Windows as well 😃

**Comment by NotMyself** [comment]
Confirmed resolved my issue as well.
