### ISSUE TITLE
extract variable - feature request

### ISSUE THREAD

**Issue by jaroslaw-weber** [OmniSharp/omnisharp-vscode#1810]
I used the feature a lot when I was using xamarin.  Here is a link to discussion in the original issue (at vscode):

https://github.com/Microsoft/vscode/issues/14849

**Comment by DustinCampbell** [comment]
If I'm understanding your request correctly, this already exists in C# for Visual Studio Code in the same way it does in Visual Studio.

![image](https://user-images.githubusercontent.com/116161/32092699-76168500-baae-11e7-8534-d96766092c4a.png)

**Comment by jaroslaw-weber** [comment]
@DustinCampbell 
I can extract method but there is no option to extract value. Is it just me?

**Comment by DustinCampbell** [comment]
Could you provide a screenshot? The selection can be important.

**Comment by winzig** [comment]
I cannot get this to work. I've got omnisharp 1.15.2 installed in VS Code 1.24.1 on macOS High Sierra. I've tried selecting a variety of lines of code in a .cs file, and no "Extract" options appear on the context menu. Nor can I find any C# extract commands via the command palette. 

<img width="662" alt="screen shot 2018-06-20 at 10 30 04 am" src="https://user-images.githubusercontent.com/127062/41674497-09e951e2-7475-11e8-81dc-23c64387591f.png">

**Comment by DustinCampbell** [comment]
@winzig : I don't believe context-sensitive refactorings like this will show up in the right-click menu. Try clicking the light bulb in your screenshot.

**Comment by winzig** [comment]
@DustinCampbell Thanks, that works!

**Comment by DustinCampbell** [comment]
Great! I'm going to go ahead and close this one.
