### ISSUE TITLE
Rename default namepace

### ISSUE THREAD

**Issue by kmughal** [OmniSharp/omnisharp-vscode#1818]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Steps to reproduce
if the folders are lowered case then when you try to create a new c# file the namspace will be lowered case which is fine but i want to override this by giving first character to be upper case is there a way to override this ?

**Comment by DustinCampbell** [comment]
Hi! I'm not precisely clear on your repro steps. How are you creating your C# file? In C# for VS Code, we don't automatically generate a namespace when a file is created.

**Comment by DustinCampbell** [comment]
I'm going to go ahead and close this for now. If you have more detail that'll help us understand the question, let us know.
