### ISSUE TITLE
Auto generate comment block

### ISSUE THREAD

**Issue by leitwolf** [OmniSharp/omnisharp-vscode#1819]
How to get this?
![aa](https://user-images.githubusercontent.com/1720546/32154224-324dd79c-bd6a-11e7-8d48-5255ce583b0e.gif)

**Comment by DustinCampbell** [comment]
Hi, this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/8. Some are using the https://marketplace.visualstudio.com/items?itemName=k--kato.docomment extension to generate XML documentation comments.
