### ISSUE TITLE
LINQ requests in Debug console

### ISSUE THREAD

**Issue by dps999** [OmniSharp/omnisharp-vscode#1823]
## Environment data
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

VS Code version:
C# Extension version:1.12.0

## Steps to reproduce

When i trying to use LINQ requests in Debug console 
I always get Expression not supported.

destroyingItems.Select(i=>i.falling)

## Expected  behavior
Return the value of the LINQ request

## Actual behavior
Evaluate request failed (Expression not supported.).

**Comment by gregg-miskelly** [comment]
@dps999 Can you tell me more about the type of `destroyingItems`? (ex: is it List, a database enumerator, etc).

**Comment by gregg-miskelly** [comment]
Also - is that the exact error message? I can't seem to find anything in the code that would return it.

**Comment by dps999** [comment]
Thank you for answer.
I took another example:
My breakpoint inside the loop. destroyItems is List<Item>
![2017-10-31_08-39-07](https://user-images.githubusercontent.com/1697478/32208988-f868566c-be16-11e7-9f3e-42aa87b2cb13.png)
What i got when i trying to examine this with LINQ requests
![2017-10-31_08-38-20](https://user-images.githubusercontent.com/1697478/32209042-4a7c6d12-be17-11e7-8698-031dca1422c5.png)

**Comment by gregg-miskelly** [comment]
What OS are you on?
Do you have a project you can share? 
If not --
* Is your `Item` class a plain-old-object, or is it something special (ex: something coming from a database)?
* I am assuming these work correctly for you if you add them to your program?

**Comment by gregg-miskelly** [comment]
@dps999 I just realized why you have a bunch of error strings that I can't find anywhere. Are you by chance debugging code under mono? (If you don't know, what is `type` set to in your launch.json)

**Comment by dps999** [comment]
Thank you for answer. I working in Unity and it looks like the problem related to it. I tried the console c# project haven't this problem and works fine. I also discovered the Unity has the same issue in Visual studio for mac.
Thank you for help!
