### ISSUE TITLE
VS Code C# Error Hints and Red Squiggly or Wavy Lines disappear randomly, especially on cursor move.

### ISSUE THREAD

**Issue by MikePerholtz** [OmniSharp/omnisharp-vscode#1832]
## Steps to reproduce

First created a project to run dotnet core with angular and I used a process similar to:
[Angular CLI With .NET Core](https://dustinewers.com/angular-cli-with-net-core/)

Then separated angular and dotnet core into their own directories and added another project directory that targeted .net standard 2.0.  I fixed all the path error and other minor configuration problems.  One hurdle in particular involved generating a valid .sln using dotnet sln.  I finally gave up with the CLI and switched over to VS2017 and built the solution that way.

I felt [Rick Strahl's Album Viewer ](https://github.com/RickStrahl/AlbumViewerVNext) demonstrated an excellent solution for running .net along side angular. After using Rick's tempalte as a guide, I was able to get dotnet run and ng serve working without error or problem EXCEPT the problem with red wavy lines disappearing under C# errors.  

I find this was a known issue in vscode about a year ago and was reported to be fixed.  

This behavior only occurs in this project I have just built.  It also occurs most frequently when I move the mouse and then hover over the text underscored with the red squiggly line.

## Environment data

VSCode version 1.17.2

`dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

VS Code version:
C# Extension version:
1.12.1

**Comment by DustinCampbell** [comment]
Any chance you could provide the repro project?

**Comment by MikePerholtz** [comment]
[Absolutely](https://github.com/MikePerholtz/wingman-ace/invitations)

**Comment by DustinCampbell** [comment]
@MikePerholtz : Does this issue still repro for you with the latest version of C# for VS Code (1.13) that was released the other day?

**Comment by DustinCampbell** [comment]
If not, I'd be grateful if you could provide the project that this issue reproduces for you with. I'd hate to follow along with the steps in the link you provided only to find that I did not build the project exactly as you had, only to find that the issue doesn't repro.

The issue that was fixed a year ago was deep inside VS Code. I would expect that this has a different cause.

**Comment by DustinCampbell** [comment]
@MikePerholtz : I just wanted to check in with you on a few questions:

1. Does this issue still repro for you with the latest version of C# for VS Code (1.13.1) that was released recently?
2. Does it still repro with VS Code 1.18?
3. Do you have project that you can share that reproduces the issue in C# for VS Code with specific repro steps? I was not able to follow the instructions that you provided.

**Comment by MikePerholtz** [comment]
Thanks, Dustin. Sorry, I was out last week.  I will follow your suggestions later today and report back.

**Comment by MikePerholtz** [comment]
![vscode error hints screen capture animation](https://user-images.githubusercontent.com/28655708/33079471-aa64ce26-cea3-11e7-848f-d2d476a39c73.gif)

**Comment by MikePerholtz** [comment]
In the linked post in my last comment, I go into more detail at the bottom of the post about the case sensitivity issue and ask for a way to perform some hard refresh of the list of files in the project file explorer in vscode, so it that those files and paths can be rebuilt anew.  If this is possible, then it might be a good troubleshooting step for this issue.

**Comment by MikePerholtz** [comment]
The problem persists in both VSCode for Windows and Mac (version=latest)

**Comment by cartermp** [comment]
Closing this out, this is likely a problem that needs resolving in Roslyn itself (if it is still a problem 3 years later).
