### ISSUE TITLE
Editing .csx: XML Docs of own libraries are not displayed in Intellisense popups

### ISSUE THREAD

**Issue by KarloX2** [OmniSharp/omnisharp-vscode#1858]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64

VS Code version: 1.18.0
C# Extension version: 1.13.0

## Steps to reproduce

Create a **.csx** files in VS Code and put the line

    #r "C:\Some\Folder\MyLibrary.dll"

in the first line. Make sure that, in the same folder, a .xml documentation file (crated by Visual Studio along with the .dll) exists. Assume there's a class MyClass defined in the dll and documented in the .xml. Try to declare a variable of that class type and observe that the documentation is _not_ being displayed in the IntelliSense popup.

    MyClass myVariable; //<<<--- IntelliSense will show signatures but not the docs.

## Expected  behavior

Member documentation shall be included in IntelliSense popups.

## Actual behavior

No member documentation is displayed.

**Comment by filipw** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#1026

**Comment by KarloX2** [comment]
@KarloX2
