### ISSUE TITLE
Debugger Install when you have special characters in your home path

### ISSUE THREAD

**Issue by xal1983** [OmniSharp/omnisharp-vscode#186]
Hi
I installed the latest insiders release of vscode, then RC2 for 4/8 of omnisharp.
Opened a project and vs code reported it was getting the debugger bits.
It successfully downloaded a bunch of nuget packages, but then it failed at this step (log tail):

```
Installed:
    128 package(s) to C:\Users\Andrés\.vscode-insiders\extensions\ms-vscode.csharp-1.0.1-rc2\coreclr-debug\project.json
Publishing dummy for .NETStandardApp,Version=v1.5/win7-x64
Error: Access to the path 'C:\Users\AndrÃ©s\.vscode-insiders....
```

You can see there that nuget respects the "é" character but then publishing uses a wrong encoding and fails.
Not sure if this is an omnisharp issue or a dotnet cli issue.

Let me know if you need more info!
Cheers,
Andrés

**Comment by gregg-miskelly** [comment]
When I try it with a hello world app, I am getting an error building. Do you see the same?

https://github.com/dotnet/cli/issues/2486

**Comment by gregg-miskelly** [comment]
With the CLI fix, the install now succeeds. However, clrdbg doesn't run correctly. I opened #251 to track the new issue.
