### ISSUE TITLE
Get test infrastructure working on VS Code 1.18 in Travis CI

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-vscode#1862]
Our new integration test infrastructure seems to be failing when running integration tests on VS Code 1.18 in Travis CI. Temporarily, I've pinned the VS Code version using in Travis CI to 1.17.2, but we need to get it working with 1.18.

**Comment by TheRealPiotrP** [comment]
This is being investigated by vscode team: https://github.com/Microsoft/vscode/issues/38598

**Comment by TheRealPiotrP** [comment]
Closed with #1875
