### ISSUE TITLE
'' is not a valid version string when debugging or running tests.

### ISSUE THREAD

**Issue by westonpace** [OmniSharp/omnisharp-vscode#1866]
[omnisharp-1866-log.log](https://github.com/OmniSharp/omnisharp-vscode/files/1469442/omnisharp-1866-log.log)
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

```
VS Code version:
`1.18.0`
C# Extension version:
`1.13.1`
## Steps to reproduce

Try and run test using "Debug Test" button.

## Expected  behavior

The test runs.

## Actual behavior

Immediate error pops up in toast:

```
Failed to start debugger: "System.ArgumentException: '' is not a valid version string.
Parameter name: value
 at NuGet.Versioning.SemanticVersion.Parse(String value)
 at OmniSharp.DotNetTest.TestManager.Create(Project project, DotNetCliService dotNetCli, IEventEmitter eventEmitter, ILoggerFactory loggerFactory)
 at OmniSharp.DotNetTest.Services.BaseTestService.CreateTestManager(String fileName)
 at OmniSharp.DotNetTest.Services.DebugTestService.Handle(DebugTestGetStartInfo
```

Some text is cut off, presumable because the toast can only hold so much.  Also, this was working with a pre-release version of 1.13 and failed when Omnisharp automatically updated to 1.13.1.

**Comment by DustinCampbell** [comment]
Hi, thanks for reporting this issue. Could you provide your full OmniSharp Log when this problem occurs? Just select View->Output from the VS Code menu to display the Output pane. Then, pick "OmniSharp Log" from the drop-down at the top-right corner of the Output pane.

**Comment by westonpace** [comment]
I've updated the post with an attached log

**Comment by DustinCampbell** [comment]
Did you capture the log after reproducing the error?

**Comment by DustinCampbell** [comment]
At the very bottom, I see this:

```
Failed to launch 'dotnet' with args, '--version'
```

Is `dotnet` on your PATH?

**Comment by westonpace** [comment]
Yes.  I started VSCode, waited for Omnisharp to load, attempted to run a
test, then captured the log.

**Comment by westonpace** [comment]
`dotnet` was on the PATH (I could start a new cmd window and run `dotnet --version` without issue) but I see where you were going with that.  I tried restarting VSCode and that didn't help.  I then moved the `C:\Program Files\dotnet` entry higher up the PATH and everything started working.  Something must have been obscuring it.

I believe I got into this state because I had VS2017 installed and installed the dotnet SDK.  OmniSharp was picking up VS2017's msbuild because of an earlier bug.  I then uninstalled VS2017 to avoid this and when I did I somehow lost `dotnet` on the PATH.  I had to add the entry back in manually.  I had assumed this had fixed things because the command prompt started working but something weird must be going on.  Thanks for the help.  You can close this issue.

**Comment by westonpace** [comment]
Hmm, I tried pushing it back down to the bottom of PATH and it still worked so I must just not have fully restarted VSCode or something along those lines.

**Comment by DustinCampbell** [comment]
Thanks for the update @westonpace. I think I understand the issue now. cc @livarcocc in case he has more insight into uninstall problems with VS and the .NET Core SDK.
