### ISSUE TITLE
c# namespace 

### ISSUE THREAD

**Issue by weinand** [OmniSharp/omnisharp-vscode#1868]
_From @mengwuwei on November 15, 2017 9:54_

- VSCode Version:
- OS Version:

Steps to Reproduce: NONE

Excuse me! Sorry,my english very bad. ^_^

namespace too long,debug Argument view find a variable difficulty,if variable 
count > 30??

I need look all namespace name ,and look variable name,

many time waste to find a variable

can use variable showing frist . namespace showing last? What do I need to do?

Reproduces without extensions: Yes/No

_Copied from original issue: Microsoft/vscode#38400_

**Comment by TheRealPiotrP** [comment]
@weinand do you happen to have a repro that would show the problem? Perhaps also some  screenshots of what you're seeing in the editor?

**Comment by weinand** [comment]
@mengwuwei do you happen to have a repro that would show the problem? Perhaps also some screenshots of what you're seeing in the editor?

**Comment by DustinCampbell** [comment]
From the repro. This looks like it might be a debugging issue? @mengwuwei, is that correct?

**Comment by mengwuwei** [comment]
Is it a name of the little mate?  But I read it several times that the guy is not me, I still judge according to the avatar, although I also use c #.  But I do not need vscode.  I use vs2017 ah.

**Comment by mengwuwei** [comment]
Do I use the same account with a person?  I do not know what happened, my head a bit tired

**Comment by DustinCampbell** [comment]
@mengwuwei : Did you not file https://github.com/Microsoft/vscode/issues/38400?

**Comment by mengwuwei** [comment]
@DusitinCampbell 
  Today I went to work to find out that my colleague used my account, let him reply you

**Comment by level6ascend** [comment]
close tis
