### ISSUE TITLE
Warning: could not load new.dll ... new.pdb is a Windows PDB

### ISSUE THREAD

**Issue by nicolasr75** [OmniSharp/omnisharp-vscode#187]
I do _dotnet new_ in an empty directory. _dotnet restore_ and _dotnet run_ work without errors.
Then I open the directory with VSCode.
I get asked to add required assets... I confirm with Yes.
I switch to Debug and use .NET Core Launch (console).
This gives me:

WARNING: Could not load symbols for 'new2.dll'. 'c:\Daten\Temp\dotnet\new2\bin\Debug\netcoreapp1.0\new2.pdb' is a Windows PDB. These are not supported by the cross-platform .NET Core debugger.
Hello World!
The program 'c:\Daten\Temp\dotnet\new2\bin\Debug\netcoreapp1.0\new2.dll' has exited with code 0 (0x00000000).

**Environment:**

C:\Daten\Temp\dotnet\new2>dotnet --info
.NET Command Line Tools (1.0.0-rc2-002392)

Product Information:
 Version:     1.0.0-rc2-002392
 Commit Sha:  880dcf2fc8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

VCCode 0.10.15-insider

ms-vscode.csharp-1.0.1-rc2

What could be the issue here?

**Comment by gregg-miskelly** [comment]
Portable PDBs are not used by default yet on Windows. See https://github.com/omniSharp/omnisharp-vscode/wiki/Portable-PDBs#net-cli-projects-projectjson

**Comment by gregg-miskelly** [comment]
Here is the issue: https://github.com/dotnet/cli/issues/1743
