### ISSUE TITLE
Syntax color is wrong for last argument of class constructor.

### ISSUE THREAD

**Issue by phucnt1992** [OmniSharp/omnisharp-vscode#1880]
## Environment data
`dotnet --info` output:
D:\Projects\MicroShoppe\MicroShoppeServices [master ≡ +6 ~10 -14 !]> dotnet --info
```
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```
VS Code version:
C# Extension version: 1.13.1

## Steps to reproduce
If I make the last bracket as image below, the color of last argument is wrong
![image](https://user-images.githubusercontent.com/9163435/32976542-99c0ab2c-cc4a-11e7-8525-d11bb719dc9e.png)

## Expected  behavior
The color of last argument should be like this.
![image](https://user-images.githubusercontent.com/9163435/32976546-e3cbaf64-cc4a-11e7-8e3a-b537fc8f35e1.png)

**Comment by DustinCampbell** [comment]
This issue was moved to dotnet/csharp-tmLanguage#88

**Comment by DustinCampbell** [comment]
I'm moved this issue to https://github.com/dotnet/csharp-tmLanguage, which is the repo for the C# TextMate grammar
