### ISSUE TITLE
Please ask when to update depedencies

### ISSUE THREAD

**Issue by willnode** [OmniSharp/omnisharp-vscode#1884]
## Environment data
`dotnet --info` output:
```
Product Information:
 Version:            1.1.0
 Commit SHA-1 hash:  d6f4336106

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.1.0
```
VS Code version: 1.18.0
C# Extension version: 1.13.1

## Steps to reproduce
Install or Update the extension. Then reload or restart vscode. First time to run the extension may update its dependencies.

## Expected behavior
The plugin should ask to the user whether its necessary update it now or later.

## Actual behavior
No question asked. This message just popped-up in the output...
```
Updating C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (20731 KB) ...
```

I know it's silly to have such behavior but it's also really necessary for those who have network with limited bandwidth (like me). Alternative solution is to have a configuration that disable automatic update for dependencies.

**Comment by gregg-miskelly** [comment]
@willnode is the time you want to avoid the download during extension auto-update? If so, I wonder if the best solution is for you to disable auto-update and instead update when you would like to.

For background - the extension can do just about nothing until those dependencies are downloaded. Ideally the downloaded .vsix would already contain them, but unfortunately VS Code doesn't support per-platform .vsix files.

**Comment by willnode** [comment]
@gregg-miskelly that's exactly what I looking for. Unfornatunely I can't find such configuration.

Honestly - The output message is rather confusing. Is the `Updating C# depedencies` means I don't have them installed yet or really updating the old depedencies?

If that means *update* then I need to turn it off, unless it's severely outdated. Otherwise the message should be `Installing C# depedencies` so then I'll let it go, because I believe this will always happen once.

**Comment by gregg-miskelly** [comment]
@willnode thanks for the feedback on "Updating" I sent out a [PR](https://github.com/OmniSharp/omnisharp-vscode/pull/1885) to change that message to "Installing".

To disable extension auto-updating:
1. Open your VS Code preferences file
2. Add `"extensions.autoUpdate": false`

I can't really think of anything else we can improve here. Any other suggestions or should I close this once that PR is merged?

**Comment by willnode** [comment]
thanks @gregg-miskelly for the clarification. The PR is really helpful.

I also peeked the code for depedencies mechanism and able to install without downloading by copying it out from my other computer. Now the extension won't complain :)

It's clear now. You can close the disscussion btw.
