### ISSUE TITLE
No intellisense unity3d vscode Version 1.18.1 (1.18.1)

### ISSUE THREAD

**Issue by AbhimanyuAryan** [OmniSharp/omnisharp-vscode#1888]
My VSCode updated & I don't see any Unity3d Syntax Highlighting autocomplete etc. How do I fix that?

**Comment by DustinCampbell** [comment]
Is it possible that this might be the same as one of the following issues?

* https://github.com/OmniSharp/omnisharp-vscode/issues/1867
* https://github.com/OmniSharp/omnisharp-vscode/issues/1827

**Comment by DustinCampbell** [comment]
In addition, could you provide your OmniSharp Log? You can retrieve this in VS Code by selecting View->Output from the menu and then choosing "OmniSharp Log" from the drop-down in the top-right corner of the Output pane.

**Comment by afk-mcz** [comment]
Hello I get the following error

```
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The reference assemblies for framework ".NETFramework,Version=v4.6" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
```

VSCode Version = 1.19.0
Mono Version =  5.4.1.6
I'm also using the new .net 4.6 on unity

**Comment by TheOddler** [comment]
I get the same error as @afk-mcz . Any idea how to fix this yet?

I'm also using the new .net 4.6 in Unity.

**Comment by AbhimanyuAryan** [comment]
I fixed this. Completely removed VSCode. Did a fresh Install

remove all extension & folder from Library > Application Support 
Remove from ~ .vscode folder

**Comment by TheOddler** [comment]
I'm still having the same issue. I uninstall VS Code, removed the Code folder in %appdata%, and the .vscode folder in my fole folder. Al well as the .vscode folder in my project.

Changin the TargetFrameworkVersion to 4.6.2 (from 4.6) in the csproj file fixes it however. This however gets reset when the csproj file is regenerated by Unity.

I found a thread on the Unity forum about this, but it's unclear if it was ever fixed (and now returned) or never fixed: https://forum.unity.com/threads/warnings-and-errors.458520/#post-3342264

**Comment by DustinCampbell** [comment]
@TheOddler : what version of mono do you have installed? I recommend installing the latest MDK from http://www.mono-project.com/download/

**Comment by TheOddler** [comment]
I don't have any, I'm on windows. However I managed to fix it by opening my project in Visual Studio Community Edition, that one complained about some missing .Net package, and after installing that it also worked in Visual Studio Code.

**Comment by afk-mcz** [comment]
on Mac downloading the .NET framework solved the issue https://www.microsoft.com/net/learn/get-started/macos#macos

**Comment by aaBaO** [comment]
Sorry, i reinstalled VSCode and update .Net SDK to 2.1.4.
This issue is still.
I use Mac Unity 2018.1.1f1
Here is the output i got:
```
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/ME/MyProjects/DemoRepository/Assembly-CSharp.csproj'.
/Users/ME/MyProjects/DemoRepository/Assembly-CSharp.csproj
/Users/ME/.vscode/extensions/ms-vscode.csharp-1.15.2/.omnisharp/1.30.1/omnisharp/msbuild/15.0/Bin/Microsoft.Common.CurrentVersion.targets(1140,5):  Error: The reference assemblies for framework ".NETFramework,Version=v4.6" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
```

**Comment by rchande** [comment]
@aaBaO This issue is closed--please file a new one if you're still having issues. By the way, did you install mono as described in https://github.com/OmniSharp/omnisharp-vscode/issues/1888#issuecomment-359895869 ?
