### ISSUE TITLE
Is it possible have code completion navigation et al in omnisharp-vscode without .NET framework installed?

### ISSUE THREAD

**Issue by adamstyl** [OmniSharp/omnisharp-vscode#1891]
## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   [omitted-contains personal info]

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

VS Code version:  1.18.1
C# Extension version: 1.13.1

My first question was [here](https://github.com/OmniSharp/omnisharp-vscode/issues/1887) but I think that I've asked the wrong question so I didn't get the expected answers.

My problem is described in [this](https://stackoverflow.com/questions/46936605/is-it-possible-to-use-visual-studio-code-with-c-sharp-plugin-in-windows-without) stackoverflow question. For convenience I will paste it here. The problem with .NET CLI was solved. The most important one with the "Reference Assemblies" remains.

I have a C# solution (plain ol' `sln` files) with several `csproj` projects. I just want to setup a powerful code editor that can support for example "go to declaration" navigation on computers with the following restrictions:

1. I don't have administrative rights to and
2. they don't have .NET framework SDK installed or .NET CLI

So for starters I've downloaded the portable version, I've added the C# plugin, I've added the dependencies manually after following [this excellent post](https://github.com/OmniSharp/omnisharp-vscode/issues/1028) of Dustin Campbell and now I have the following problems every time I open the project folder:

1. I get the message `The .NET CLI tools cannot be located. .NET Core debugging will not be enabled. Make sure .NET CLI tools are installed and are on the path.` I'm fine with that since I'm not interested in debugging and running; just mentioning for the sake of completeness.
2. I get a warning that `Some projects have trouble loading` and I see in the output this message:

> fail: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo 

> The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

So the first thing I tried was to hack my way around this and see if I could make it work just by dropping the correct reference assemblies into `C:\Program Files\Reference Assemblies\Microsoft\Framework\` according to [this answer](https://stackoverflow.com/a/18468523). But then Bazinga! I don't have administrative rights to do that.

So my question is, can somebody use VS code as a powerful code editor without administrator rights, or I'm just chasing windmills?

Just to make my self clear, I don't care about the error message as long as I have navigation, autocompletion and refactoring capabilities in omnisharp-vscode.

**Comment by rchande** [comment]
@adamstyl Can you share the contents of `C:\Program Files (x86)\Reference Assemblies\microsoft\Framework\.NETFramework`? It sounds like one of the projects you're trying to edit targets .NET Framework v4.0 but you don't have the targeting pack installed. If that's the case, I think you can do as suggested in this StackOverflow post (https://stackoverflow.com/questions/44006035/target-net-4-7-without-installing-the-targeting-pack) and use the FrameworkPathOverride property in your csproj to load reference assemblies from a different directory.

**Comment by DustinCampbell** [comment]
@adamstyl : @rchande is correct. C# for VS Code uses MSBuild to locate the correct reference assemblies on your machine. It's likely that you need to install the .NET Framework 4.0 developer pack in order to get them on your machine (I wouldn't go copying things around and hoping they work). Try grabbing the latest .NET Framework Developer Pack from https://www.microsoft.com/net/download/visual-studio-sdks.

**Comment by DustinCampbell** [comment]
Also, could you provide your complete OmniSharp Log? You can retrieve this by selecting View->Output from the VS Code menu and then choosing "OmniSharp Log" from the drop-down in the top-right corner of the Output pane.

**Comment by adamstyl** [comment]
Hello everyone and thanks for helping out on this.

@rchande There is no need to share them, I know that the problem is there! :D Sorry for considering it obvious. There is no `.NETFramework` subdirectory for me. Under `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework` there is only `v3.0` and `v3.5`. Obviously the 4.0 is missing :)

The FrameworkPathOverride **worked**. I tried it for one csproj and that project was loaded normally. No `fail` in output and autocomplete was working just fine. The problem is that this is cumbersome, as every time I will have to change >20 csproj files :(

@DustinCampbell unfortunately I don't have administrative access to perform any installations :( Yes I know, I could ask the administrator to do it. But what I'm trying to do is exactly that: have a powerful C# editor _without_ the need of elevated privileges. What if I have the code on _a random_ machine, I can run VS code and I am in desperate need to do it _now_? Admins might not be able to do the installation right now. They might not even be available at that day and time. So I need a "war time" solution.

Do you still need the OmniSharp Log output? It's quite big, 216 lines. I don't think it would be beneficial to add it here... The `[fail:] OmniSharp.MSBuild.ProjectFile.ProjectFileInfo` that I've quoted is from OmniSharp Log output, just imagine it repeating ~20 more times, one for every csproj I have in there :D

What I was thinking is something similar to what Jetbrains Rider does: I've extracted the EAP version from the zip, run the exe, loaded the _same_ sln on the _same_ machine and that was it. I was having autocomplete, navigation, even error reporting **without** having a .NET framework installation. I'm not saying it was perfect, it was handy though. I _guess_ this is done by leveraging Roslyn, but then I'm not sure if I have to look into other VS code plugins like for example [omnisharp-roslyn](https://github.com/OmniSharp/omnisharp-roslyn)? But as I said, I don't know since I'm just guessing how Rider works. If you have any thoughts or ideas please share.

**Comment by DustinCampbell** [comment]
@adamstyl : This is likely not done using Roslyn since JetBrains Rider doesn't use it and we do. :smile: The real issue here is around having a bit more leniency when MSBuild fails to process your project. We could add support for "limping along", but you'd see a ton of error squiggles from types not being resolved. FWIW, Visual Studio would have the same problem.

**Comment by DustinCampbell** [comment]
@adamstyl : I can't speak for Rider. It's possible that they install reference assemblies themselves, but I don't really have a way of knowing. (Full disclosure: I'm a Microsoft employee working on the C# team.)

**Comment by adamstyl** [comment]
@DustinCampbell yes I can imagine that, the question was mostly rhetorical, I guess there won't be anybody willing to answer it for obvious reasons! 😄

Is there a way to apply the FrameworkPathOverride solution wide? Otherwise I should close this issue 😃

**Comment by adamstyl** [comment]
pressed the wrong button...

**Comment by DustinCampbell** [comment]
You could try using a Directory.Build.props file. https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build

**Comment by adamstyl** [comment]
@DustinCampbell Thanks again, I will test tomorrow and post feedback.

**Comment by adamstyl** [comment]
@DustinCampbell worked like a charm. I have everything now (navigation to types works, code completion works).

There is a small hiccup though, I get a `The type 'Func<TResult>' exists in both 'System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'` message which doesn't happen (I think) on a machine with a properly installed .NET

But I guess that this is what you get when you try to make things work with hacks 😃 

Thanks again everyone for helping out, I'm now closing the issue.
