### ISSUE TITLE
.Net Core Debugger installiation issue

### ISSUE THREAD

**Issue by egamma** [OmniSharp/omnisharp-vscode#190]
_From @Abdullah2993 on April 15, 2016 10:46_

- VSCode Version: 1.0
- OS Version: Windows 10

Steps to Reproduce:
1.  Open an Asp.Net Core Application

```
Downloading and configuring the .NET Core Debugger...
Running C:\Program Files\dotnet\bin\corerun.exe "C:\Program Files\dotnet\bin\NuGet.CommandLine.XPlat.dll" "restore" "--runtime" "win7-x86" "--runtime" "win7-x64" "--configfile" "NuGet.config"
Process ID: 5880
Specify --help for a list of available options and commands.
error: Unrecognized option '--configfile'
dotnet exited with error code 1
Error while installing .NET Core Debugger.
```

_Copied from original issue: Microsoft/vscode#5328_

**Comment by pflannery** [comment]
Might related to https://github.com/OmniSharp/omnisharp-vscode/issues/80 ?

**Comment by gregg-miskelly** [comment]
What version of .NET CLI do you have installed? (run dotent --version)

**Comment by Abdullah2993** [comment]
@gregg-miskelly I'm running version `1.0.0`
```
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

**Comment by Abdullah2993** [comment]
It turned out that the issue was similar to  https://github.com/OmniSharp/omnisharp-vscode/issues/80
I have two versions of `dotnet-cli` installed. I uninstalled both and did a fresh install everything works fine now
