### ISSUE TITLE
Syntax highlighting fails for LINQ query joins with anonymous types

### ISSUE THREAD

**Issue by eeskildsen** [OmniSharp/omnisharp-vscode#1900]
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

VS Code version: 1.18.0

C# Extension version: 1.13.1

## Steps to reproduce

Write a LINQ query that joins with an anonymous type. For example:

```
from x in list1
join y in list2
    on new
    {
        x.Key1,
        x.Key2
    }
    equals new
    {
        y.Key1,
        y.Key2
    }
select x.Key1
```

## Expected  behavior

LINQ syntax highlighting will continue past `on new`, highlighting `equals new` and `select`.

## Actual behavior

LINQ syntax highlighting stops with `on new`.

![image](https://user-images.githubusercontent.com/8701531/33485309-efb89f3e-d673-11e7-8269-b20fbb1fb3d0.png)

**Comment by DustinCampbell** [comment]
This issue was moved to dotnet/csharp-tmLanguage#89

**Comment by DustinCampbell** [comment]
Thanks for the report. I've moved this issue over to the C# TextMate grammar repo.
