### ISSUE TITLE
Formatting of null conditional operator

### ISSUE THREAD

**Issue by bsell93** [OmniSharp/omnisharp-vscode#1901]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```
VS Code version: 1.18.1
C# Extension version: 1.13.1

## Steps to reproduce
1. Set vscode setting `"csharp.format.enable": false`
2. Format a C# file

## Expected  behavior
Formatted like so
`var thing = oldThing.FirstOrDefault()?.property`

## Actual behavior
`var thing = oldThing.FirstOrDefault() ? .property`

**Comment by rchande** [comment]
@akshita31 Here's another formatting bug for you.

**Comment by akshita31** [comment]
The setting requires you to restart vscode.Did you do that ?

**Comment by bsell93** [comment]
@akshita31 I thought that I had, but that might have been the issue because I no longer see it. I will close this issue for now unless I am able to reproduce it.

Thanks!

**Comment by rchande** [comment]
@bsell93 By the way, you can just restart the "omnisharp" component of the VS Code for C# extension, which is what powers formatting. You can do this by running the "restart omnisharp" command from the ctrl-shift-p menu.

**Comment by rchande** [comment]
(That way you don't have to fully restart vs code)

**Comment by bsell93** [comment]
It turns out these issue does exist, but only when the null conditional operator is after a method such as `FirstOrDefault()`. I attempted to restart omnisharp and the issue persisted.

**Comment by akshita31** [comment]
dotnet --info 

.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

VS Code Version : 1.18.1
C# Extension Version : 1.13.1

I am not getting a repro on my machine.

**Comment by akshita31** [comment]
Also, the setting requires to restart vscode. Just restarting omnisharp, still shows the formatting options on right-click.But is it the expected behavior ? @rchande

**Comment by akshita31** [comment]
@bsell93 Did you try updating your vscode version and checking whether the issue still persists ?

**Comment by bsell93** [comment]
@akshita31 I found out the problem. The C# FixFormat extension was causing the problem.
https://marketplace.visualstudio.com/items?itemName=Leopotam.csharpfixformat
