### ISSUE TITLE
Debugger launch may fail with '/usr/local/share/dotnet' does not exist'

### ISSUE THREAD

**Issue by sourcesoft** [OmniSharp/omnisharp-vscode#1902]
## Environment data
`dotnet --info` output:
```
Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

VS Code version: `Version 1.18.1 (1.18.1)`
C# Extension version: `1.13.1`

## Steps to reproduce
Use osx
Install VSC, extension.
Download dotnet core form site and use the install to setup.

## Expected  behavior
Run the debugger

## Actual behavior
having the same issue:
Displays the error after trying to debug.

```
launch: program '/usr/local/share/dotnet' does not exist.
```
<img width="1199" alt="screen shot 2017-12-01 at 6 46 10 pm" src="https://user-images.githubusercontent.com/608906/33508392-0d3710be-d6c8-11e7-835e-5c8816590255.png">

I can run `dotnet` from internal terminal or OSX terminal. It also works if I assigned the debugger to an existing process, but doesn't work debugging a new one.

**Comment by MBLHarrison** [comment]
I am having what I think is a similar problem
![image](https://user-images.githubusercontent.com/17315707/33508705-eb60aec4-d6f3-11e7-9dfa-ac0a531680a6.png)
I can dotnet run the program, I cannot debug it.

**Comment by gregg-miskelly** [comment]
@MBLHarrison your issue is NOT similar. Please open a new issue.

**Comment by gregg-miskelly** [comment]
@sourcesoft it looks like your problem is that the debugger things the path to the dotnet executable is `/usr/local/share/dotnet`, but on OSX in my experience it is actually `/usr/local/share/dotnet/dotnet` (note the extra `\dotnet'). So the debugger is pointing at a directory instead of a file.

If you look at your `PATH`, is `/usr/local/share` in it ahead of `/usr/local/share/dotnet`?

**Comment by sourcesoft** [comment]
I just ran `where dotnet` in terminal:
```
/usr/local/bin/dotnet
```
So it actually runs the one in local/bin. And I also have `/usr/local/share/dotnet` folder with with a binary `dotnet` just like you said that I can also run like `./dotnet` in there.
<img width="819" alt="screen shot 2017-12-01 at 7 24 57 pm" src="https://user-images.githubusercontent.com/608906/33509180-5e1e9ae2-d6cd-11e7-980e-676cb510c9be.png">

In the error I mentioned `launch: program '/usr/local/share/dotnet' does not exist.` it seems like it uses share folder path but I'm not sure why

**Comment by gregg-miskelly** [comment]
Is `/usr/local/share` on your PATH?

The debugger does its owns processing of PATH to find `dotnet`, and I am guessing you are running into a bug in our parsing of it.

**Comment by sourcesoft** [comment]
Yes I have it
<img width="1018" alt="screen shot 2017-12-01 at 7 32 18 pm" src="https://user-images.githubusercontent.com/608906/33509318-620cb46c-d6ce-11e7-8da5-3e81238d6090.png">

And also the one in /usr/local/bin is just a symlink to the right path of dotnet
<img width="1008" alt="screen shot 2017-12-01 at 7 30 17 pm" src="https://user-images.githubusercontent.com/608906/33509321-67eb1446-d6ce-11e7-8362-f7d274589925.png">

**Comment by gregg-miskelly** [comment]
Okay, good. I should be able to repro this then. I will try to get the debugger fixed up for our next release. In the mean time, if you can swap the order of `/usr/local/share` and `/usr/local/bin` I think this will go away.

**Comment by sourcesoft** [comment]
Oh it got worse. I just tested `Visual Studio for Mac` and it's getting me the same error text in a new solution/project, so it's not specific to VSC.

<img width="776" alt="screen shot 2017-12-01 at 7 34 52 pm" src="https://user-images.githubusercontent.com/608906/33509381-12c05f84-d6cf-11e7-9e13-ecfdbe85a8a4.png">

**Comment by gregg-miskelly** [comment]
Both VS for Mac and VS Code use the same underlying debugger. So that makes sense.

**Comment by sourcesoft** [comment]
I just swapped the order it got fixed in both of them. Thank you!
