### ISSUE TITLE
Error(update c# dependancies) Failed at stage: installPackages

### ISSUE THREAD

**Issue by Heinrichv** [OmniSharp/omnisharp-vscode#1905]
## Environment data
`dotnet --info` output:

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3

VS Code version: 1.18.1
C# Extension version: 1.13.0

## Steps to reproduce
Install c# ms-vscode.csharp package

## Expected  behavior
Succeed with updating dependencies

## Actual behavior

Getting the following error :

Updating C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' 	Retrying from 'https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.26.3.zip' Downloading package '.NET Core Debugger (Windows / x64)' 	Retrying from 'https://vsdebugger.blob.core.windows.net/coreclr-debug-1-13-0/coreclr-debug-win7-x64.zip' 
Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'
Failed at stage: installPackages
Error: end of central directory record signature not found

Finished

**Comment by Heinrichv** [comment]
got it working with 
{
"http.proxyStrictSSL": false
}
in my settings.json

**Comment by fizxmike** [comment]
VS Code (or maybe it's just the OmniSharp extension) does not honor system proxy setting, so I needed to also set "proxy":"http://some.proxy.org:1234" in my settings.json as well. Cute!
