### ISSUE TITLE
executeWorkspaceSymbolProvider returns SymbolKind.Class instead of SymbolKind.Interface for C# interfaces

### ISSUE THREAD

**Issue by craig006** [OmniSharp/omnisharp-vscode#1907]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```
VS Code version: 1.18.1
C# Extension version: 1.13.0

## Steps to reproduce
Execute 

Run this code from an extension in a C# project in VS Code:
```
commands.executeCommand('vscode.executeWorkspaceSymbolProvider', "ISomeInterface").then((result:SymbolInformation[]) => {
     console.log(result)           
})
```

## Expected  behavior
The SymbolInformation returned for symbol `ISomeInterface` has its kind property set to SymbolKind.Interface

i.e. `result[0].kind should equal SymbolKind.Interface`

## Actual behavior
The SymbolInformation returned for symbol `ISomeInterface` has its kind property set to SymbolKind.Class

i.e. `result[0].kind is set to SymbolKind.Class`

Definition of ISomeInterface
```
public interface ISomeInterface
{
    void SomeMethod();
}
```

**Comment by rchande** [comment]
@craig006 Good find--thanks for filing this.

**Comment by rchande** [comment]
@akshita31 Here's another one for you.

**Comment by craig006** [comment]
@akshita31 @rchande I created a fix here:
https://github.com/craig006/omnisharp-vscode/commit/82fd0cd90881ed3d5450dec4a70829874abbda72#diff-08c3f24b351caf5705429053d550e08a

These are all the vscode.SymbolKinds that I could reproduce. Omnisharp never returned types like "TypeParameter", "Variable" etc.

Let me know if you would like me to create a PR somewhere

**Comment by craig006** [comment]
https://github.com/OmniSharp/omnisharp-vscode/pull/1911

**Comment by rchande** [comment]
Thanks @craig006. We'll take a look.

**Comment by DustinCampbell** [comment]
Marking this as "resolved fixed", but I think there was a desire to have Delegate return SymbolKind.Method as well.

**Comment by DustinCampbell** [comment]
Actually, I don't think SymbolKind.Method is the right choice. We don't do that in the completion list either: https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/features/completionItemProvider.ts#L111. The idea is that delegates *are* types and probably shouldn't be confused with methods. @rchande, what do you think? If you agree, I think this can be closed.

**Comment by rchande** [comment]
@DustinCampbell I concur.
