### ISSUE TITLE
Enable users to download alternative copies of omnisharp

### ISSUE THREAD

**Issue by rchande** [OmniSharp/omnisharp-vscode#1909]
We should provide capabilities like the CLI does, where we enable downloading of different feeds of omnisharp.

**Comment by rchande** [comment]
Our new downloading code should also address https://github.com/OmniSharp/omnisharp-vscode/issues/1896

**Comment by DustinCampbell** [comment]
What is the end user scenario?

**Comment by rchande** [comment]
@DustinCampbell This primarily enhances dev scenarios, but I could see this benefiting users, too:

* As a dev (or user), I can start C# extension for VSCode and have it download a version of OmniSharp other than the version it has hard coded.

This will let us easily set up CI builds for testing the extension with newer/older/etc bits of OmniSharp and also improve the local dev scenario for consuming new OmniSharp in the extension. @jonsequitur also thinks we can leverage this in try.net.

**Comment by DustinCampbell** [comment]
It might be worth re-titling this issue to reflect that. :smile:

**Comment by akshita31** [comment]
This has been resolved in https://github.com/OmniSharp/omnisharp-vscode/pull/2065
