### ISSUE TITLE
Intellisense ordering of items is alphabetical

### ISSUE THREAD

**Issue by myrup** [OmniSharp/omnisharp-vscode#1915]
## Environment data
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
VS Code version:
C# Extension version:

## Steps to reproduce
Use intellisense
<img width="388" alt="screen shot 2017-12-10 at 22 55 39" src="https://user-images.githubusercontent.com/1935820/33809861-b82e3cc2-ddfd-11e7-9621-df148b27a137.png">
## Expected  behavior
Suggest most relevant results (local vars first, "args" in screenshot)

## Actual behavior
Show every possible option alphabetically, even keywords (cant remember seeing those ever in vs pro).

**Comment by rchande** [comment]
@myrup Thanks for the suggestion! I'm adding this to our backlog. BTW, this is approximately the same sorting as we have in Visual Studio.

**Comment by DustinCampbell** [comment]
@rchande : Is there already a suggestion on Roslyn that we could use to track this more generally across the VS family?

**Comment by Ermish** [comment]
+1 I would love to have the results be more relevant.

**Comment by DustinCampbell** [comment]
@jinujoseph: Is there an issue on the Roslyn side that we can use to track this?

**Comment by jinujoseph** [comment]
yes https://github.com/dotnet/roslyn/issues/24226

**Comment by DustinCampbell** [comment]
Thanks @jinujoseph! We'll track this there since C# for VS Code ultimately uses Roslyn to provide the completion list.
