### ISSUE TITLE
Get started with VS Code content archived

### ISSUE THREAD

**Issue by DickBaker** [OmniSharp/omnisharp-vscode#1922]
## Environment data
having just installed VS Code v 1.18.1 I clicked to see intro video(s) which took me to this URL https://channel9.msdn.com/Blogs/dotnet/Get-started-with-VS-Code-using-CSharp-and-NET-Core

which says "Content Archived
This content is no longer current. Our recommendation for up to date content: https://channel9.msdn.com/Blogs/dotnet/Get-started-VSCode-Csharp-NET-Core-Windows"

## Expected  behavior
any URL should be current and not rely on [series of] redirects to get to any current code/doc
![2017-12-13 1](https://user-images.githubusercontent.com/2774188/33967506-aacbbe6e-e05b-11e7-8a82-9de1aa85e7b7.png)
/video

**Comment by kendrahavens** [comment]
Yes, this is correct. It should be pointed at the new link. We should update the link on the README of this extension to https://channel9.msdn.com/Blogs/dotnet/Get-started-VSCode-Csharp-NET-Core-Windows

**Comment by kendrahavens** [comment]
Fixed in PR #1928
