### ISSUE TITLE
Remove debugger proxy code

### ISSUE THREAD

**Issue by chuckries** [OmniSharp/omnisharp-vscode#1929]
Starting in 1.9, VS Code allows an extension command to be registered that will dynamically produce the path and args to the debugger executable. [Summary](https://code.visualstudio.com/updates/v1_9#_debugger-extension-authoring). 

With this, we should be able to remove our proxy code and do the equivalent in a command. This has some benefits as we will be running in the VS Code process, have access to the VS Code APIs, and we will not need to rewrite the manifest to move from the proxy to vsdbg-ui.

**Comment by DustinCampbell** [comment]
@WardenGnaw : Should this issue be resolved as fixed and closed now?

**Comment by WardenGnaw** [comment]
Yep! Forgot to close this issue.

**Comment by DustinCampbell** [comment]
Is there a changelog update for this issue? Or, does it not affect the experience meaningfully?

**Comment by chuckries** [comment]
This _**should**_ be invisible to the user.

**Comment by DustinCampbell** [comment]
That's what I thought. I just wanted to check.

**Comment by WardenGnaw** [comment]
I believe the only issue would be if someone decides to F5 before the extension is activated and registers the command, VsCode will complain that the command is not found.

**Comment by DustinCampbell** [comment]
sure. That seems low-impact enough to leave out of the changes.
