### ISSUE TITLE
Turn off "restore" notifications?

### ISSUE THREAD

**Issue by ciel** [OmniSharp/omnisharp-vscode#193]
I love the work you guys have done, and I am thankful that the extension tries to restore my dependencies - but is there a way to ask it to ... well, not?

It's a bit obtrusive to have it keep trying that constantly. Sometimes - actually most times - I need to do a restore when I'm ready to. I've had situations where I have stacks of 10 notifications keep pouring over the top of my screen trying to force me to restore my projects when that's just not what I want to do.

The same with the debugger. Can we set it to be downloaded and installed when we ask it to - instead of it always doing it for every project, automatically, the second it is opened? It makes it very hard to rapidly move between things, copy things out of old projects, etc. It's constantly doing things I'm really not asking it to do.

**Comment by DustinCampbell** [comment]
The debugger shouldn't be downloaded for each project. Are you referring to the popup that asks if you want to add tasks.json and launch.json?

**Comment by dopare** [comment]
This is the original bug https://github.com/OmniSharp/omnisharp-roslyn/issues/504

**Comment by ciel** [comment]
Yes, that would be the bug it seems. Sorry, I guess this is a pre-existing issue. I thought I was just going crazy.

**Comment by DustinCampbell** [comment]
No worries. It's something I've heard a number of times. I'll look at improving that experience. I think we can do some things in the C# extension for VS Code to make it better, as well as improving the OmniSharp server itself.

**Comment by DustinCampbell** [comment]
Hi @ciel, is this still an issue for you with the latest C# extension?

**Comment by ciel** [comment]
Yes. It is such a huge issue that VSC is completely unusable.

**Comment by dasMulli** [comment]
+1 because this becomes pretty annoying when e.g. opening a projects that are meant to be (or just have been) restored with special arguments by a build script (e.g. dotnet/cli).
But then it's pretty handy when working on new / small projects... so being able to configure it would be awesome.
![close-all-the-infos](https://cloud.githubusercontent.com/assets/6129250/19949705/83542f80-a153-11e6-83d9-62ca0404d31c.gif)

**Comment by GuardRex** [comment]
@DustinCampbell There is some discussion on Slack about the auto-restore again. Everyone there is in agreement that VS Code should have a setting that allows us to turn off the auto-restore. I'm surprised this wouldn't be fairly easy to pull off. Isn't it just a workspace setting (bool) and an `if` block on the `dotnet restore` bits?

**Comment by DustinCampbell** [comment]
Where in Slack is this discussion happening? On the official OmniSharp Slack? I'd love to be a part of any discussion, or better yet, have the discussion here in the open.

Oh, I agree too. It's just a matter of finding the time to get this feature done at the moment, with other priorities. It's pretty high on my list, but not the highest. I have a couple of thoughts.

1. I suspect that everyone would like the restore popup quite a bit more if it didn't appear for every single change in the universe, but grouped them together into one prompt. I suspect that would be helpful.
2. It'd be great if we could be a bit smarter when someone does a normal operation like a `git clean -xdf` and not offer to restore immediately.

I don't think the change you suggest is the right one. We shouldn't be killing the event based on an option, but rather providing smarter behavior when the event fires.

**Comment by GuardRex** [comment]
It was on the aspnetcore Slack, and I mis-described it. It's was more of a "rant" among a couple of devs than a "discussion."

I'm sure it will be great when restore is smarter and better. However, I disagree with your point about not offering a way to completely disable automatic restore.

I use my extension, [Status Bar Tasks](https://marketplace.visualstudio.com/items?itemName=GuardRex.status-bar-tasks), and when I want a restore, I trigger it manually with one click in the status bar. I can't think of a single situation where I would want an automatic restore. I prefer to be able to configure Omnisharp with a workspace setting that permanently disables it.

On the other hand and as I was saying to @shaunluttin, any of us can just clone the repo and make a version of this that does whatever we like, and I thank you, the Omnisharp team, and MS for making that possible. :+1:

Based on your response, it seems like the winds are blowing in the direction of never having a permanent disable option, so let me ask this in case I decide to clone and hack: Would it be as simple as removing ...
```
public onUnresolvedDependencies(listener: (e: protocol.UnresolvedDependenciesMessage) => any, 
        thisArg?: any) {
    return this._addListener(Events.UnresolvedDependencies, listener, thisArg);
}
```
... and the `d3` bit at ... https://github.com/OmniSharp/omnisharp-vscode/blob/ffc52290366467417cc7d673e4756821d8e19827/src/features/status.ts#L245-L256
```
let d3 = server.onUnresolvedDependencies(message => {
    let info = `There are unresolved dependencies from 
        '${vscode.workspace.asRelativePath(message.FileName) }'. Please execute the restore 
        command to continue.`;

    return vscode.window.showInformationMessage(info, 'Restore').then(value => {
        if (value) {
            dotnetRestoreForProject(server, message.FileName);
        }
    });
});

return vscode.Disposable.from(d0, d1, d2, d3);
```
... from `server.ts`?

**Comment by DustinCampbell** [comment]
Oh, I didn't say that I disagreed with offering a way to disable. I specifically said that I agreed. :smile:

On disabling, yes, it's certainly possible to do it in the extension (I'm taking PRs BTW). However, I've been wondering if it's probably better done in OmniSharp itself. After all, why bother registering a bunch of FIleSystemWatchers and firing events that aren't going to get handled.

**Comment by shaunluttin** [comment]
@DustinCampbell I am the developer who started the rant about disabling the popup. Here are the things on my wish list: 

1. A way to permanently disable the `Info` popup, when I decide it no longer provides value. 
2. A keyboard shortcut to close the `Info` popup, so that I can keep my hands on the keyboard.

Right now, the `Info` popup significantly interferes my my flow during development.

**Comment by DustinCampbell** [comment]
Sounds good. :smile:

**Comment by shaunluttin** [comment]
@DustinCampbell I am also confused about why it is called "auto-restore" because it isn't auto. Rather, it is more a "restore-notification" that we can click on manually to trigger restore.

**Comment by DustinCampbell** [comment]
I'm confused too. :smile: That's what it was called when I inherited the extension.

**Comment by shaunluttin** [comment]
@DustinCampbell I deleted the comment... sorry.

**Comment by shaunluttin** [comment]
@DustinCampbell Is there an existing keyboard shortcut to close those `Info` notifications?

**Comment by shaunluttin** [comment]
It is actually almost impossible to develop in Visual Studio Code without a mouse unless we restore first.

**Comment by DustinCampbell** [comment]
I'm not sure if there's a keyboard shortcut or not. That's just the standard VS Code UI for displaying an information message.

**Comment by GuardRex** [comment]
Sorry guys ... lack of paying attention on my part when discussing: It's not auto-restore ... it's auto-notification that a restore is needed. I just don't need to be told that. Sorry again.

**Comment by shaunluttin** [comment]
@DustinCampbell Could you please invite me to the omnisharp-vscode channel on Slack. That way I can rant there instead. :trollface:

**Comment by DustinCampbell** [comment]
Link is here: https://goo.gl/Ovnqr1

**Comment by DustinCampbell** [comment]
A new (release)[https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.5-beta6] is ready which includes a `csharp.suppressDotnetRestoreNotification` option.
