### ISSUE TITLE
Environment variables in launch.json is not processing ${auto-detect-url}

### ISSUE THREAD

**Issue by weinand** [OmniSharp/omnisharp-vscode#1933]
_From @corretge on November 29, 2017 8:49_

When I try to put a launch variable in launch.json
```
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development",
                "ENV_GLOBAL_CURRENT_URL" : "${auto-detect-url}"
            }
```

I get this value:

```
"${auto-detect-url}"
```

instead

```
"http://localhost:5000"
```

- VSCode Version: 1.18.1 
- OS Version: Windows 10

Steps to Reproduce:

1. Create a C# project
2. Set environment variables for a debug configuration as explained at begin
3. Add  Environment.GetEnvironmentVariable("ENV_GLOBAL_CURRENT_URL")
4. Debug until this instruction

_Copied from original issue: Microsoft/vscode#39294_

**Comment by weinand** [comment]
I'm not aware of any VS Code variable named `auto-detect-url`.
What is this?

If this is a environment variable then you'll have prefix it with `env:`, e.g.  `${env:auto-detect-url}`

**Comment by weinand** [comment]
_From @vscodebot[bot] on December 6, 2017 14:5_

This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by weinand** [comment]
_From @corretge on December 21, 2017 7:37_

Hi @weinand, this is not an environment variable, at the end I want to convert it to one :)

I use this variable because when you add a Debug configuration, automatically is generated this configuration:

```
[...]
            "name": ".NET Core Launch (web)",
[...]
           "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
```

And ```"args": "/C start ${auto-detect-url}"``` works fine

Apologies for my delayed answer.

**Comment by weinand** [comment]
This must a C# thing. Moving issue...

**Comment by gregg-miskelly** [comment]
Are you trying to pass this to your program or the browser launch script?

**Comment by corretge** [comment]
I want to know this value in my application, and my first approach was to set as an environment variable.

**Comment by gregg-miskelly** [comment]
Thanks @corretge, this isn't something that is possible. The debugger doesn't know the value of `${auto-detect-url}` -- it watches your application run, and when it outputs the right message to stdout we grab it and start a browser. It is actually your application that does know this value. I am afraid I am not enough of an ASP.NET Core expert to tell you exactly where the framework is reading the URL from, but you could read the URL from whatever configuration file ASP.NET is getting it from.
