### ISSUE TITLE
Codelens showing "run test" even when the containing class isnt marked with the TestClassAttribute

### ISSUE THREAD

**Issue by akshita31** [OmniSharp/omnisharp-vscode#1942]
`dotnet --info`
.NET Command Line Tools (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

VSCode Version : 1.19.0
C# Extension Version : 1.13.1

## Steps to reproduce
Create a Test class without having the "TestClass" attribute with a test method in the class.

## Expected  behavior
"run test" and "debug test" codelens doesn't show up

## Actual behavior
"run test" and "debug test" codelens appear and on clicking "run test" the console shows "Total tests:0"

**Comment by akshita31** [comment]
Visual Studio does show "Run Tests" on right clicking, but gives error when we execute that command. So is the current behavior in VS Code correct ?

**Comment by rchande** [comment]
@akshita31 I think this is the right behvaior, at least for xunit where there is no testclass attribute.

**Comment by akshita31** [comment]
Ok. I didnt know about the xunit type. Thanks!
