### ISSUE TITLE
argsFile and envFile in launch.json

### ISSUE THREAD

**Issue by SebastianPfliegel** [OmniSharp/omnisharp-vscode#1944]
## Environment data
`dotnet --info` output:

```
.NET-Befehlszeilentools (2.0.2)
 
Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512
 
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

VS Code version: 1.19.1
C# Extension version: 1.13.1

## Feature request
In my launch.json I need to pass sensitive data (like passwords) as arguments (or environment variables). As the launch.json is also committed to Git it's unwise to place the arguments in there. In NodeJS it is already possible to pass a file containing all the arguments (Microsoft/vscode#14523 and Microsoft/vscode-node-debug2@b3e2e8f3).

**Comment by SebastianPfliegel** [comment]
@gregg-miskelly: I wanted to implement this feature myself. The only thing I managed so far is modifying ./src/tools/OptionsSchema.json

Can you give me a hint on where to look for the launch.json being parsed and those values being passed to the debugger? I'm a total Java/TypeScript beginner.

**Comment by gregg-miskelly** [comment]
Here is how I _think_ you could implement it: VS Code will call [`resolveDebugConfiguration`](https://github.com/OmniSharp/omnisharp-vscode/blob/b9f98acece12022763aa08e646cd415483924ce2/src/configurationProvider.ts#L106) at the start of debugging. We haven't done anything this way, but I believe you could use this as an opportunity to change the options. So you could read the argsFile/envFile and place the content into the args/env options.

The underlying .NET Cored debugger that this extension launches, isn't an open source product. So if that doesn't work this feature would need to be implemented by a Microsoft employee unfortunately.

**Comment by SebastianPfliegel** [comment]
So, vsdbg parses the launch.json. That would have been my next guess.

Sounds like it shouldn't been touched and vsdbg should be modified instead. And I don't mind if a Microsoft employee finishes the job ;-)

**Comment by gregg-miskelly** [comment]
Here is the flow: VS Code reads the launch.json file, it sends the content of the active configuration to `resolveDebugConfiguration`, `resolveDebugConfiguration` makes any changes it wants to, then VS Code sends that content onto the debug adapter.

You are certainly welcome to wait -- this seems like a fairly simple and useful feature request. That said, I don't think there is anything wrong with implementing this feature in `resolveDebugConfiguration`, and I don't know when exactly we will get to this feature. So if you are feeling like you would really like this feature, you are more than welcome to try and implement it.

**Comment by SebastianPfliegel** [comment]
My guesses turn out to be correct then.

I'll give it a try :)

**Comment by SebastianPfliegel** [comment]
@gregg-miskelly, got it working :)
Needs some polishing though before creating a PR. Can't find a way to replace the variable ${workspaceFolder}.

**Comment by gregg-miskelly** [comment]
Can't you use the value of the `folder` argument?

**Comment by SebastianPfliegel** [comment]
You mean like: if `config.envFile` contains `${workspaceFolder}` substitute it with the value of `folder.uri.path`? Is this the right approach or is there a ready-to-use function?

**Comment by gregg-miskelly** [comment]
Yes, that was my suggestion. You could certainly try searching VSCode's source code and see if they either have some code you can borrow or an API you can call. But I don't know the answer off hand.

**Comment by SebastianPfliegel** [comment]
Haven't found an API yet. Pushed PR #1951 though.
