### ISSUE TITLE
Unable to spot syntax error of C#

### ISSUE THREAD

**Issue by vjaisknit** [OmniSharp/omnisharp-vscode#1946]
i am working on project dotnetcore with angular in vscode .and my editor is unable to catch the syntax error. i  install C# extension already..

**Comment by rchande** [comment]
@vjaisknit Can you share the output of `dotnet--info` as well as your VSCode and C# extension versions?

**Comment by DustinCampbell** [comment]
@vjaisknit : Did you see @rchande's request for more information here?

**Comment by cartermp** [comment]
Closing out as no info has been given.
