### ISSUE TITLE
Extension host crash: calling js function in _layout.cshtml from another included file in _layout.cshtml

### ISSUE THREAD

**Issue by dshamim** [OmniSharp/omnisharp-vscode#1948]
## Environment data
Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff

VS Code version: Version 1.19.1 (1.19.1)
C# Extension version: Version 1.13.1

## Steps to reproduce
----------------------------------------------------------------------
NOTE: I have not tried reproducing this in an empty project as of yet
----------------------------------------------------------------------

This is happening consistently in the project that I'm working on, through the process of elimination I've been able to pin it down to the following:

Requirement:
1) we had a requirement where we have to read something from appconfig and add it as part of the js file
2) all of our js files are included in _layout.cshtml based on environment
3) because of this we needed a function directly in _layout.cshtml where I can inject IConfigurationRoot in razor and read the settings and inject directly into js

Reproduce Steps:
1) lets assume the following:
    a) script.js is a file that contains all our site wide js code, it's included in _layout.cshtml as 
        follows: <script src="~/js/site.js" asp-append-version="true"></script>
    b) a method testFunctionA exists in _layout.cshtml that just prints alert

2) put code in script.js to call testFunctionA - , as soon as the code is place F5 refuses to run and extension host crashes after a while, reload window doesn't help until the call to the function is removed and window reloaded

sample code from _layout.cshtml:
 <environment names="local,Testing">
        <script>
            function testFunction(){
                alert("test");
            }
        </script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
        <script src="~/lib/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
        <script src="~/lib/trumbowyg/dist/trumbowyg.min.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/highcharts/js/highcharts.js"></script>
    </environment>

**Comment by rchande** [comment]
@dshamim I don't think the C# extension for VS Code provides any services in cshtml files. Do you have another extension installed for working in cshtml files?

**Comment by dshamim** [comment]
I see, it must be something related to JS files , I have not narrowed it down  - 
I have the following extensions:

DotJoshJohnson.xml
EditorConfig.EditorConfig
GuardRex.status-bar-tasks
cmlewis89.vscode-togglecodelens
eamodio.gitlens
jchannon.csharpextensions
jorgeserrano.vscode-csharp-snippets
k--kato.docomment
minhthai.vscode-todo-parser
ms-vscode.csharp
nwallace.peep
pflannery.vscode-versionlens
qub.qub-xml-vscode
rahulsahay.Csharp-ASPNETCore
rbbit.typescript-hero
reflectiondm.classynaming
ryu1kn.partial-diff
wayou.vscode-todo-highlight

**Comment by rchande** [comment]
@dshamim Can you try disabling the C# extension and see what happens?

**Comment by dshamim** [comment]
I've verified - it's typescript hero that causes the crash - (rbbit.typescript-hero) - thanks !
