### ISSUE TITLE
Simple statement code coverage

### ISSUE THREAD

**Issue by neurospeech** [OmniSharp/omnisharp-vscode#1953]
I am searching for how to make code coverage for `vs-code`, as I understand currently code coverage is only offered on Windows OS with Profiler API, but I am thinking of writing an alternative (slow) way to collect code coverage by automatic stepping through debugger.

Will it be possible to do it using this project? Any help will be appreciated.

**Comment by gregg-miskelly** [comment]
You might be able to do something like that but I _really_ wouldn't recommend it.

Here are your best bets:
* If you want to be able to do instrumentation without needing to understand CIL (the intermediate representation of .NET Code) you probably best bet would be to use the Roslyn API to load up the C# project you want to instrument, add C# level instrumentation, and recompile the project.
* If you feel comfortable going a bit lower level, you can instrument the CIL. You might find the [Cecil project](http://www.mono-project.com/docs/tools+libraries/libraries/Mono.Cecil/) or [System.Reflection.Metadata](https://www.nuget.org/packages/System.Reflection.Metadata/) as good places to start.

**Comment by neurospeech** [comment]
@gregg-miskelly I am aware of `System.Reflection.Metadata`, but my question is how to create a debugger, so I can call some API and start debugging step by step, I found [DnSpy](https://github.com/0xd4d/dnSpy), but that is like building another native plugin for IDE.

I would be using Roslyn to navigate and run Tests only referencing current class. This way I will not be running all tests at once.

As currently there is no coverage tools for `vs-code`, and OpenCover runs on windows only.

**Comment by gregg-miskelly** [comment]
@neurospeech sorry for not being more clear. I understood your request, but I would strongly suggest NOT trying to use the debugging API to implement code coverage -- I think you will find that it isn't really any easier to do it that way then by instrumenting the IL/C#, but it is much slower.

If you want to try and and use the debugging API anyway, from what I can tell VS Code doesn't have any APIs you can use to drive debugging from a VS Code Extension (see `vscode.debug` namespace if you want to look more). But you could add a fake debugAdapter that say between the C# debug adapter (vsdbg-ui) and VS Code, and added/removed your own breakpoints, and listened to stopping events. Here is the protocol: https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json

**Comment by shanselman** [comment]
Getting close https://github.com/shanselman/dotnetcoreunittestingwithcoverageinvscode/blob/master/readme.md
