### ISSUE TITLE
Reformat code not work for object initialization

### ISSUE THREAD

**Issue by luktar** [OmniSharp/omnisharp-vscode#1955]
## Environment data

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

VS Code version: 1.19.1
C# Extension version: 1.13.1

## Steps to reproduce

Create following code in a function:

```
            List<Document> documents = new List<Document>
            {
                new Document { Id="Id1", FileName="Document1"},
                    new Document { Id = "Id2", FileName = "Document2" },
                new Document { Id = "Id3", FileName = "Document3" },
                new Document { Id = "Id4", FileName = "Document4" },
            };
```

Press "format code" shortcut - on windows is ALT + SHIFT + F

## Expected  behavior

All `new Document (...)` objects should have the same alignment and spaces should be fixed.

The code should looks as follow:

```
            List<Document> documents = new List<Document>
            {
                new Document { Id = "Id1", FileName = "Document1" },
                new Document { Id = "Id2", FileName = "Document2" },
                new Document { Id = "Id3", FileName = "Document3" },
                new Document { Id = "Id4", FileName = "Document4" },
            };
```

## Actual behavior

No action. Objects initialized inside documents list stay in the same position.
Also spaces in first abject `new Document { Id="Id1", FileName="Document1"},` does not change.

Alignment works for the top level of object initialization. When I move `List<Document> documents = new List<Document>` by one tabulator in the example above, code formatting works properly.

**Comment by rchande** [comment]
@akshita31 Want to take a look?

**Comment by akshita31** [comment]
This reproduces in Visual Studio as well , hence an issue with roslyn. Filed an issue :https://github.com/dotnet/roslyn/issues/24151 in Roslyn for the same.

**Comment by DustinCampbell** [comment]
FWIW, I believe it is by design that we don't format inside of initializers in C# or Roslyn. @Pilchie has always told me that this is because we didn't want to mess up code that was formatted into tables.

**Comment by Droni** [comment]
Any news? May be you add an option to force format object initializers? It will be helpful for guys who not format code as table.
