### ISSUE TITLE
Not showing codelenses for custom test adapter

### ISSUE THREAD

**Issue by firelizzard18** [OmniSharp/omnisharp-vscode#1964]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

- VSCode Version: Code 1.19.2 (490ef761b76b3f3b3832eff7a588aac891e5fe80, 2018-01-10T15:55:03.538Z)
- OS Version: Windows_NT x64 10.0.16299
- C# Extension version: 1.13.1

## Steps to reproduce
My test cases look like this:
```csharp
namespace My.Project
{
    class Harness_MyClass : ITestHarness
    {
        public void Verify(DefineTestModule Declare, ITestValueMatcher Value)
        {
            Declare("My Class", (_, Module, Shared) => {

                Module("#section", (It, __, ___) => {
                    
                    // code lens should be here
                    It("can do stuff", b => b
                        .When((MyClass x) => x.DoStuff()));
                });
            });
        }
    }
}
```

My test adapter (`ITestDiscoverer`) creates instances of `Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase`, and populates all of the fields:
```csharp
new TestCase(
    fullyQualifiedName: "My Class.#section.can do stuff",
    executorUri: euri,
    source: "My.Project.Harness_MyClass, My.Project" /* typeof(Harness_MyClass).AssemblyQualifiedName */)
{
    Id = GuidUtility.Create(GuidUtility.UrlNamespace, "My Class.#section.can do stuff"),
    DisplayName = "My Class, #section, can do stuff",
    CodeFilePath = @"C:\path\to\My.Project\Harness_MyClass.cs",
    LineNumber = 12,
}
```

Perhaps the issue is because the fully qualified name and/or source don't conform to your expectations? Or perhaps I'm doing something wrong? `dotnet test -t` returns:

```
The following Tests are available:
    My Class, #section, can do stuff
```

## Expected  behavior

OmniSharp adds code lenses to the files and locations specified by the test cases' `CodeFilePath` and `LineNumber`, which would correspond to calls to `It(...)`.

## Actual behavior

OmniSharp does not add any code lenses.

**Comment by rchande** [comment]
@firelizzard18 Would be it possible for you to give us a sample project to debug this?

**Comment by firelizzard18** [comment]
I've created a stripped down version of my framework, and a test project.

[DebuggerTest.zip](https://github.com/OmniSharp/omnisharp-vscode/files/1654246/DebuggerTest.zip)

I tried to keep the project files largely identical to the actual ones. Hence `Core` having references to packages it doesn't actually use.

Ideally, `Proj.csproj` would look like the example below. I want to embed test code within libraries, and not as separate projects. The conditional compilation below means that DEBUG code would only contain a reference to the API and RELEASE code would not contain any test references, nor any test code (as test code would live in files excluded by one of the patterns below). **This does work**, though I have to use `dotnet test -f netcoreapp2.0` to avoid warnings that the .NET Standard version isn't testable.

`Proj.csproj` alternate form:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' AND '$(Testable)' == ''">
    <Testable>True</Testable>
  </PropertyGroup>

  <Choose>
    <When Condition=" '$(Testable)' == 'True' ">
      <PropertyGroup>
        <DefineConstants>$(DefineConstants);TESTABLE</DefineConstants>
      </PropertyGroup>

      <PropertyGroup Condition=" !$(TargetFrameworks.Contains(netcoreapp2.0)) ">
        <TargetFrameworks>$(TargetFrameworks);netcoreapp2.0</TargetFrameworks>
      </PropertyGroup>

      <ItemGroup>
        <ProjectReference Include="..\API\API.csproj" />
      </ItemGroup>

      <ItemGroup Condition=" $(TargetFramework) == 'netcoreapp2.0' ">
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0" />
        <ProjectReference Include="..\Adapter\Adapter.csproj" />
      </ItemGroup>
    </When>

    <Otherwise>
      <ItemGroup>
        <Compile Remove="Tests.cs" />
        <Compile Remove="*.Tests.cs" />
        <Compile Remove="*_Tests.cs" />
      </ItemGroup>
    </Otherwise>
  </Choose>

</Project>
```

**Comment by DustinCampbell** [comment]
@firelizzard18 : The test support in C# for VS Code does not support arbitrary test adapters. It currently only handles xunit, nunit and mstest, so I wouldn't expect this to work.

**Comment by DustinCampbell** [comment]
The code lens are created in response to the test detection code in OmniSharp [here](https://github.com/OmniSharp/omnisharp-roslyn/tree/master/src/OmniSharp.DotNetTest/TestFrameworks). We do not run a test discovery pass to detect tests today.

**Comment by firelizzard18** [comment]
Makes sense. If you ever add support for arbitrary test adapters or come up with some sort of extensibility, let me know :)

My employer does not have a policy of making things open source, so my adapter will probably stay in house.
