### ISSUE TITLE
Warnings during build are treated as errors

### ISSUE THREAD

**Issue by cra0zy** [OmniSharp/omnisharp-vscode#1968]
## Steps to reproduce

- `dotnet new console`
- modify program.cs and add an unsigned variable
- add default task and launch configuration
- debug the project

## Expected  behavior

Project runs.

## Actual behavior

The preLaunchTask 'build' terminated with exit code 1. This happens because there was a warning during build. The build actually did complete successfully.

**Comment by DustinCampbell** [comment]
Thanks for filing. I can definitely reproduce this. It doesn't appear that the warning was actually elevated to an error in the build but VS Code seems to be refusing to launch the debugger due to the warning.

**Comment by ElementalWarrior** [comment]
If I comment the problemMatcher line in tasks.json I don't get stopped when building with warnings. But do when I get errors.

**Comment by lyptt** [comment]
This issue is incredibly annoying. I'm glad it's not just me.

**Comment by cra0zy** [comment]
Closing this as the issue has been fixed in the newest release.
