### ISSUE TITLE
Rename .cs file does not change <Compile Include =.../> in csproj. files; changes to .csproj not applied until vscode is reloaded.

### ISSUE THREAD

**Issue by SirIntruder** [OmniSharp/omnisharp-vscode#1970]
VS Code version: 1.19.2
C# Extension version: 1.13.0

These issues make renaming files .cs files in vscode a pain in the butt. Not sure if these are bugs/feature requests, how hard it would be to fix them or if they were reported in the past (couldn't find dup issue), but here is the situation. 
I tested the same thing in Rider and Rider smoothly handles both of them.

>Have foo.cs in bar.csproj "Compile Include=foo.cs"
>Rename foo.cs to foo2.cs
>foo2.cs is outside of the project now and c# support breaks down, OR foo2.cs is kept as if in project but without actually changing csproj file, so issue surfaces on the next reload.

Correct thing to do is to change matching Compile Include-s when renaming .cs files.

>open bar.csproj
>manually change "Compile Include=foo.cs" to "Compile Include=foo2.cs"
>change is not applied until vscode is fully reloaded

Vscode should listen to changes to csproj files and respond accordingly. Not that a lot of people would be manually changing csproj files, but 3rd party like Unity, which uses VSCode as IDE, do.

edit: after testing some more I think the second part actually works, or fails very rarely. I will add more info if I find a repro. The first part fails consistently

**Comment by rchande** [comment]
@SirIntruder you are correct that the C# extension will not update your csproj if you rename a .cs file that has a specific "Include" entry. However, OmniSharp does know how to handle files adds/deletions and should stop showing types from files that you delete.

If you change your project to use file globing, (`include = **/*.cs`), the project system will automatically update renamed files. The easiest way for you to get file addition/removal to work would be to switch to globbing.

**Comment by SirIntruder** [comment]
Thanks @rchande. Globing would be great, but unfortunately these csproj files are created by, and constantly updated by Unity3D, and messing with that would be more trouble than worth. if possible.

Anyway, do you agree changing matching includes in .csproj when renaming files is the correct action in general, and how much work is needed to achieve this? I could try my hand at this if it is not overly complex, would certainly be very useful to Unity3d developers even if not part of omnisharp-vscode, 

btw, I think I understood what is wrong with "changes to csproj not applied without reloading vscode". Apparently, when you change a csproj file, everything adjusts except for the underline error reporting. As if this system doesn't get a memo when the project is updated and goes on showing old errors, while CodeLens, GoTo symbol and etc. . adjust immediately.

**Comment by DustinCampbell** [comment]
To be clear, C# for VS Code never makes *any* changes to your project file. VS Code is a lightweight editor and not a full IDE with a project system like Visual Studio or VS for Mac.

**Comment by VergilGao** [comment]
I got the same trouble with unity.
It really broke my workflow.

**Comment by klick-barakgall** [comment]
I've had the same issues in the past. I think what I've done is used unity for the creation/deletion of files and used VSCode for the actual code-editting. It's not an optimal workflow but I learned to deal with it. Alternatively if you want full project a .csproj support, the easiest workflow would probably be to use VSCommunity as this is both supported by Unity, and has extensions to provide additional Unity support (IRC)..

I know MonoDevelop is provided out-of-the-box but I've seen a lot of really cruddy and strange behaviour when using MonoDevelop with Unity, so I would still recommend VSCode + Unity for file management or full on VSCommunity, at least until Omnisharp/VSCode decide that they want to undertake the management of .csproj files.

**Comment by akshita31** [comment]
As per OmniSharp/omnisharp-roslyn#1159 this problem should be fixed.
@SirIntruder Can you confirm if we can close this now ?
Can someone here try setting "omnisharp.path": "latest" and checking if the error still persists?

**Comment by SirIntruder** [comment]
Thanks! You can close this, sure thing
Note that there will still be errors. Difference is that they errors will go away as soon as Unity3d is focused (which regenerates .csproj files), and people shouldn't need to restart omnisharp anymore

**Comment by NTaylorMullen** [comment]
Ya I've noticed that OmniSharp doesn't run regular design time builds so it ends up missing added Compile items. My 2cents

**Comment by akshita31** [comment]
@SirIntruder Thanks 💃
