### ISSUE TITLE
Autocomplete is super frustrating

### ISSUE THREAD

**Issue by johnfn** [OmniSharp/omnisharp-vscode#1971]
**dotnet version**

```
dotnet --info
.NET Command Line Tools (2.1.3)

Product Information:
 Version:            2.1.3
 Commit SHA-1 hash:  a0ca411ca5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff
```

**vscode version**: Version 1.19.0-insider (1.19.0-insider)

**c# extension version**: 1.13.1

Problem:

For whatever reason, my autocomplete has the incredibly frustrating habit of choosing the SECOND item in the list, rather than the first. As you could imagine, this drives me insane.

Here's a picture:

![image](https://user-images.githubusercontent.com/167745/35199000-2af92df6-feac-11e7-9039-70ff500550db.png)

`depth` is a parameter; I have no idea what the other thing even is. VSCode happily selects the first thing until I type the "h" in depth, then it switches to the second option. WHY?! It makes no sense. This kind of thing happens all the time. I can't see why you would EVER want to select the second item in the dropdown!

I'm filing this bug in this repo because I have used vscode with TypeScript for ages and never had this problem, so I assume that it lies on the C# autocomplete side.

**Comment by johnfn** [comment]
![image](https://user-images.githubusercontent.com/167745/35203904-73b1b224-fedf-11e7-919a-6e49b8b060c4.png)

Here's another example.

**Comment by rchande** [comment]
Thanks for filing this @johnfn . I can't tell what we're doing to cause this so I filed a copy against vscode itself. Hopefully they can give us some advice!

**Comment by seesharper** [comment]
@rchande Do you have a link to the vscode issue so we can track this? Thanks :)

**Comment by rchande** [comment]
Ah, I can see how that would be helpful :). https://github.com/Microsoft/vscode/issues/41977

**Comment by rchande** [comment]
@johnfn @seesharper Per https://github.com/Microsoft/vscode/issues/41977, the VS Code team believes this behavior is fixed in the latest insiders build of Code. Can you try that build out, and if the behavior still bothers you, file an issues against VS Code?
