### ISSUE TITLE
Omnisharp prefers bad MSBuild installs over good

### ISSUE THREAD

**Issue by Gochida** [OmniSharp/omnisharp-vscode#1976]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```
VS Code version: 1.19.2
C# Extension version: 1.13.1

## Steps to reproduce
1. Have VS2017 Community installed in addition to VSCode.
2. Attempt to open a C# project and try to use features like Intellisense.

## Expected  behavior
VSCode features like Intellisense should work

## Actual behavior
All QOL features do not work.

Some details I gathered before ultimately solving this issue from my end:

1. Omnisharp will correctly identify multiple MSBuild installs. In my case it found VS2017's and VSCodes (via C# extension) installs.
2. A fresh install of the latest v15.5 of VS2017 Community does not include a complete MSBuild install - all but two files are missing from the Roslyn folder. I should note that I also had an earlier version of VS2017 Community installed, which was uninstalled and freshly re-installed with the latest version.
3. Installing the official VSCode C# extension includes a complete MSBuild library.
4. Omnisharp in VSCode will trust an unrelated programs install of MSBuild rather than the MSBuild installed under VSCode. If this other location turns out to have incomplete or missing files, it does not fallback to other known installs of MSBuild. I couldn't figure out a way to get Omnisharp to look elsewhere.

Here is a link to the original issue I posted to VSCode's repo. It includes the full output of Omnisharp attempting to load the project.
[https://github.com/Microsoft/vscode/issues/42016](https://github.com/Microsoft/vscode/issues/42016)

The core of the issue is that Omnisharp apparently looks at VS2017 Community's MSBuild - which doesn't have any of the necessary files. 

The solution I arrived at in the end was to manually copy every missing file from the VSCode's MSBuild over to VS2017's MSBuild folder.

**Comment by DustinCampbell** [comment]
Thanks for the report and detailed analysis!

This _should_ already be fixed within omnisharp-roslyn with https://github.com/OmniSharp/omnisharp-roslyn/commit/04d2522895716effb0a5cfd143bb2ad79738a54c#diff-37c241429399bf8c42961908becc5522. I expect this to be fixed in the next C# for VS Code release, but that change has not made yet it into a C# for VS Code beta release.

**Comment by DustinCampbell** [comment]
This should be fixed in the latest beta release on this repo. If you're interested in trying the beta, you can follow the instructions here: https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases.
