### ISSUE TITLE
mvc template app throws exception immediately on Webrequest on ARM

### ISSUE THREAD

**Issue by Buzze11** [OmniSharp/omnisharp-vscode#1978]
## Environment data
`dotnet --info` output:
Product Information:
 Version:            2.2.0-preview1-007947
 Commit SHA-1 hash:  e8f7ddd01b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.0-previe

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26116-04
  Build    : eeb3a84e2142aba791fe003564b8afd048c45ff9

VS Code version: 1.19.2
C# Extension version: 1.13.1

## Steps to reproduce
1. create example mvc app with "dotnet new mvc -n mvc"
2. publish with "dotnet publish -r linux-arm" and deploy it to the raspberry pi
2. start debug with launch on raspberry device (setup like described in https://github.com/OmniSharp/omnisharp-vscode/wiki/Remote-Debugging-On-Linux-Arm#prerequisites)
3. place a webrequest from any browser to the server

## Expected  behavior
Welcome page appears by accessing it using the browser

## Actual behavior
Exceptions get thrown. Page does not show up.

   
[Exception.log](https://github.com/OmniSharp/omnisharp-vscode/files/1665484/Exception.log)

**Comment by gregg-miskelly** [comment]
@Buzze11 this doesn't sound like an issue with the C# extension -- it sounds like an ASP.NET issue. Do you get the same problem if you run the app outside the debugger?

**Comment by Buzze11** [comment]
Hi @gregg-miskelly , thanks for your fast response. I have opened an Issue https://github.com/dotnet/cli/issues/8490 at the dotnet cli repo. 
BR Thomas
