### ISSUE TITLE
Support VS Code noDebug

### ISSUE THREAD

**Issue by DerAlbertCom** [OmniSharp/omnisharp-vscode#199]
I think this belongs here.

VS Code has now the notion of only running a command (default to Ctrl+F5), without debugging see https://github.com/Microsoft/vscode/issues/2780. See the Commit https://github.com/Microsoft/vscode/commit/e14608cd46f3bdff4d0d84254d6ab3c6300ae12f how noDebug is handled to the Service. 

If would be great if we can do this with C# also.

But maybe this don't belong here. Currently i don't know it ;)

**Comment by gregg-miskelly** [comment]
You are in the right spot.

**Comment by DerAlbertCom** [comment]
Yes. .NET Core

**Comment by wesrupert** [comment]
Fix should be available in the next release.
