### ISSUE TITLE
Extension complains about project.json files in node_modules

### ISSUE THREAD

**Issue by bdukes** [OmniSharp/omnisharp-vscode#1990]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```
VS Code version: 1.19.3
C# Extension version: 1.13.1

## Steps to reproduce
- Use Yarn or npm to install the `edge` or `edge-js` package
- Open the root folder (i.e. the folder containing `node_modules`) in VS Code

## Expected  behavior
- No warnings

## Actual behavior
- Warnings about `project.json` and requests to restore dependencies

Related to agracio/edge-js#20

**Comment by DustinCampbell** [comment]
Thanks for reporting! OmniSharp should just leave node_modules out when searching for projects.
