### ISSUE TITLE
Banner overrides .vscode settings if just added by other banner

### ISSUE THREAD

**Issue by vishrutshah** [OmniSharp/omnisharp-vscode#1993]
## Environment data
`dotnet --info` output:
```
**.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

VS Code version: `1.19.3`
C# Extension version: `1.13.1`

## Steps to reproduce
1. We are building an extension for [Connected Environment for AKS](https://review.docs.microsoft.com/en-us/visualstudio/connected-environment/visual-studio-connected-environment?branch=johnsta)
2. Setup an environment as described here for [get-started-netcore](https://review.docs.microsoft.com/en-us/visualstudio/connected-environment/get-started-netcore-01?branch=johnsta)
3. Once you see the banner like below:
![image](https://user-images.githubusercontent.com/8782776/35697084-12414d62-073e-11e8-919b-f3fcc39445eb.png)
4. Click on `Yes` for `[Connected Environment]` first to generate `tasks.json` + `launch.json` inside `.vscode`
5. Then click on `Yes` other banner.

## Expected  behavior
Banner should update existing `tasks.json` + `launch.json` with the C# debugger settings and it should contain both the settings of C# & Connected Environment. 

## Actual behavior
Banner overrides the  `tasks.json` + `launch.json` files content created by our banner.

**Comment by DustinCampbell** [comment]
We check to determine whether we need to add a tasks.json or launch.json before showing the message, but we don't check again after the user clicked our message to determine whether the environment has changed.

**Comment by vishrutshah** [comment]
@DustinCampbell Thanks for looking into it and letting me know. Would you mind it I send out an PR for the fix?

**Comment by DustinCampbell** [comment]
If you're interested in providing a fix, we'd be happy to take it! :smile:
