### ISSUE TITLE
Hover is broken for types that don't have a doc comment

### ISSUE THREAD

**Issue by srivatsn** [OmniSharp/omnisharp-vscode#1996]
## Environment data
This is using the latest sources from master

## Steps to reproduce
Hover over a normal type in source that doesn't have a doc comment

## Expected  behavior
Should show a hover tip with the name of the type

## Actual behavior
Shows nothing.

Looks like there's a missing null check for the structured doc comment.

/cc @rchande

**Comment by rchande** [comment]
@akshita31 Can you take a look? It looks like https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/features/documentation.ts#L39 needs to handle a null structured documentation getting passed in.
