### ISSUE TITLE
C# 7.2 syntax still not working?

### ISSUE THREAD

**Issue by 5argon** [OmniSharp/omnisharp-vscode#1999]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4

VS Code version: 1.19.3
C# Extension version: 1.13.1

## Steps to reproduce
Code like this should be fine

```
   private static double ASDF(in int point1, in int point2)
    {
        return 1;
    }

```
This code compiles normally.

## Actual behavior
Identifier expected; 'in' is a keyword.

**Comment by filipw** [comment]
it will be there when this PR gets in https://github.com/OmniSharp/omnisharp-vscode/pull/1995

**Comment by DustinCampbell** [comment]
This should be available in the latest beta release on this repo. You can follow the instructions [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) if you are interested in trying the beta.
