### ISSUE TITLE
VS Code - Info: Resolve Dependancies Fails if User Path contains a SPACE

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#2]
_From @sporens on January 17, 2016 20:57_

Hi,

The command executed by VS Code to install and resolve missing dependancies for an ASP.NET application fails with "Can't find path" when the path to the users' home folder includes a space. For example:
c:\users\joeblogs\ <- works
c:\users\joe blogs\ <- fails

Running procmon I see it's attempting to execute:
cmd.exe /c start /wait cmd.exe /c "C:\Users\joe blogs\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\dnu.cmd restore & pause"

Which fails.

Thanks

_Copied from original issue: Microsoft/vscode#2072_

**Comment by jrieken** [comment]
this is either omnisharp-vscode or omnisharp itself

**Comment by DustinCampbell** [comment]
Fixed for 'dotnet' with PR #238
