### ISSUE TITLE
ECONNREFUSED when starting Omnisharp

### ISSUE THREAD

**Issue by germansak** [OmniSharp/omnisharp-vscode#200]
Hi, I'm on 
* Omnisharp version: RC2 release candidate for 4/15 #2 
* Dotnet version: 1.0.0-rc2-002397
* Code insiders

When I try to open a sample (c#) it refuses to start Omnisharp with this error:

_[INFO] Starting OmniSharp at 'c:\Users\germansak\cli-samples\HelloMvcApi'...
[ERROR] Error: connect ECONNREFUSED 192.30.252.127:443_

Could it be that I'm behind a proxy?

Thanks!

**Comment by BeelzeBu** [comment]
it may be, once you install the new version it needs to connect internet and download de new debugger. 192.30.252.127 listen for api.github.com

**Comment by germansak** [comment]
Thanks BeelzeBu, is there any way to solve it? Maybe setting somewhere my proxy address (already did it on Code, but no luck)

Cheers!

**Comment by DustinCampbell** [comment]
Unfortunately, there's no way to set this today, but I've capture this issue as a feature request.

You can get this working by downloading and unpacking the appropriate OmniSharp release for your operating system from [here](https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.9-alpha13). (If you're on Linux, it's best to grab the release that matches your distro.) Then, in VS Code, select Preferences->User Settings from the menu and add the following to settings.json:

```
"csharp.omnisharp": "/path/to/the/omnisharp/executable/you/just/downloaded/and/unpacked"
```

**Comment by germansak** [comment]
Hi Dustin, thanks for the reply!
I've verified that the error is the proxy. It tested it at home (no proxy) and it worked perfectly. There's no need for me to apply this workaround because I'm just testing stuff. I can wait for it to be fixed.

Thanks again
Germán

**Comment by DustinCampbell** [comment]
Did you intend to close this issue? We won't take a look at it if there isn't an active issue.

**Comment by germansak** [comment]
Ooops!! Sorry

**Comment by DustinCampbell** [comment]
This is now fixed with this PR: https://github.com/OmniSharp/omnisharp-vscode/pull/350.
