### ISSUE TITLE
Incomplete syntax highlighting and intellisense on string interpolations, tuples, and local functions 

### ISSUE THREAD

**Issue by 5argon** [OmniSharp/omnisharp-vscode#2000]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4

VS Code version: 1.19.3
C# Extension version: 1.13.1

## Steps to reproduce

<img width="910" alt="screenshot 2018-02-02 15 05 31" src="https://user-images.githubusercontent.com/5653276/35722879-ac12bc2c-082a-11e8-817a-a00f0fa2128a.png">

1. `TimesTen` is a local function. `int` in local function return type definition should be pink
2. Things in `{}` of `$" "` string should not be colored yellow. (I remembered seeing screenshots from other editor where that is the case, and I think that is more readable)
3. When start typing after `{` with variable names I expect intellisense to pop up. (At least if `$"` is preceding) however using `.` after a valid variable names do trigger intellisense pop up. You just have to get the first one right by your own.

<img width="670" alt="screenshot 2018-02-02 16 29 31" src="https://user-images.githubusercontent.com/5653276/35726129-55cf4810-0836-11e8-8c40-93583013a15d.png">

4. Not a big deal but `ref` here should not be pink.

<img width="711" alt="screenshot 2018-02-02 18 58 33" src="https://user-images.githubusercontent.com/5653276/35732228-4077504c-084b-11e8-98b5-f729ba92f6fa.png">

5. Having tuple return type for a property like this erroneously colors the property body as white, as well as non tuple property that follows it that `get` turns white and the return type is also white. 

<img width="1221" alt="screenshot 2018-02-02 19 49 35" src="https://user-images.githubusercontent.com/5653276/35734028-42ab04e2-0852-11e8-87d1-c5ba06d70898.png">

6. `get` and `List` here are not colored. The first `foreach` is green instead of pink. `s` is blue instead of white. `return` is blue instead of pink. `orders` is blue instead of white.

**Comment by DustinCampbell** [comment]
Thanks for filing these issues. Syntax highlighting issues should be reported over at https://github.com/dotnet/csharp-tmLanguage, which is where the C# TextMate grammar lives. The fourth issue that you mentioned above is already fixed but has not merged back into VS Code yet.

FWIW, it's helpful if multiple issues are failed as different issues, since they likely won't be fixed all at once. I'll go ahead and split this into several issues.

**Comment by DustinCampbell** [comment]
The first issue mentioned (local function return type) is due to https://github.com/dotnet/csharp-tmLanguage/issues/10.

**Comment by DustinCampbell** [comment]
I think the second issue above (highlighting in interpolations) may be an artifact of the theme you're using. Here's what it looks like in VS Code's Dark+ (default dark) theme:

![image](https://user-images.githubusercontent.com/116161/35743151-81bd52ea-07f1-11e8-8387-2820f86b51a6.png)

**Comment by DustinCampbell** [comment]
I've filed https://github.com/OmniSharp/omnisharp-vscode/issues/2001 to track the third issue above.

**Comment by DustinCampbell** [comment]
I've filed https://github.com/dotnet/csharp-tmLanguage/issues/98 to track the fifth issue above.

**Comment by DustinCampbell** [comment]
I expect the sixth issue is related to the fifth one. Once the syntax highlighter has been thrown off by the tuple-returning property, the rest of the highlighting in the property is suspect.

**Comment by DustinCampbell** [comment]
I'm going to go ahead and close this now. I think I've covered everything that you reported. Let me know if that's not the case.
