### ISSUE TITLE
Completion List does not appear after first identifier is typed in string interpolation

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-vscode#2001]
Repro steps:

1. Start with the following code in a C# project (ensure OmniSharp successfully loads).

```C#
class C
{
    void M(int x)
    {
        var s = $"{}";
    }
}
```

2. Type 'x' inside the '{}'

Expected result: completion list appears
Actual result: it doesn't

**Comment by DustinCampbell** [comment]
Note: This will probably be fixed by fully using Roslyn's Completion API in omnisharp-roslyn.

**Comment by Fubuchi** [comment]
Press the key board shortcut for "toggleSugguestionDetails" after typing some character make the completion list appears, but typing itself not work.

**Comment by rchande** [comment]
@DustinCampbell @Fubuchi Apparently VS Code has its own logic to determine whether intellisense is available inside strings. You can enable trigger on typing by setting the "editor.quicksuggestions" option to show intellisense inside strings:
```
    "editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": true
    }
```

(See https://github.com/microsoft/vscode/issues/23962#issuecomment-292079416 for details)
