### ISSUE TITLE
The drop-down list in output/terminal sometimes contains bogus entries

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#2007]
## Environment data
`dotnet --info` output:
![dotnet--info](https://user-images.githubusercontent.com/20184778/35792028-e5e3468a-0a85-11e8-8b2f-f5492a7d5de2.PNG)

VS Code version: v1.19.3
C# Extension version: v1.14.0-beta3

## Steps to reproduce

1. Open a dotnet core app with VSCode
2. Check drop-down list in OUTPUT or TERMINAL window

## Expected  behavior
The drop-down list is shown correctly as shown below:
![droplist](https://user-images.githubusercontent.com/20184778/35792373-c197c844-0a87-11e8-96dd-26e39e4db0a6.PNG)

## Actual behavior
The drop-down list as shown below:
![vscode1](https://user-images.githubusercontent.com/20184778/35792358-a7ba1f08-0a87-11e8-97ae-cec53b116553.PNG)
![vscode3](https://user-images.githubusercontent.com/20184778/35792359-a7e78a60-0a87-11e8-8de1-153259a94cb5.PNG)

**Comment by DustinCampbell** [comment]
This should probably move to VS Code. It's not a C# for VS Code (or debugger) issue.

**Comment by gregg-miskelly** [comment]
Based on https://github.com/Microsoft/vscode/issues/40492, it sounds like this is something that VS Code has fixed already and will ship in 1.20.

@GraceDong can you reproduce this in 1.20 insiders builds? If so, we should probably port this over to their issues. Otherwise, it seems safe to close this one.

**Comment by GraceDong** [comment]
I tried it several times at 1.20 insiders builds and didn't reproduce this issue.

**Comment by gregg-miskelly** [comment]
@GraceDong Thanks for testing. I will close this then.
