### ISSUE TITLE
C# #if and #endif indentation is reset after formatting messing with folding of outer code

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#2008]
_From @uday0408 on February 3, 2018 1:54_

- VSCode Version: 1.19.3
- OS Version: Mac OS X, 10.13
- C# Extension version: Omnisharp 1.13.1

For C#, after formatting with Omnisharp installed, the #region and #endregion statements are indented at the same level of enclosing code. But #if and #endif are formatted to have no indentation, thus messing with folding when #if/#endif enclosing code is nested.

I don't know if this is Omnisharp or VSCode problem.

Steps to Reproduce:

1. Apply formatting to following code
```
public static class Main
{
    public static int Foo(int x)
    {
        x = 5;
        #if false
        x++;
        #endif
        return x;
    }
}
```
    
2. After formatting it looks like this:
```
public static class Main
{
    public static int Foo(int x)
    {
        x = 5;
#if false
        x++;
#endif
        return x;
    }
}
```

3. This messes with folding of entire code!!

Does this issue occur when all extensions are disabled?: Yes/No

_Copied from original issue: Microsoft/vscode#42861_

**Comment by aeschli** [comment]
_From @alexandrudima on February 5, 2018 9:37_

I believe the way Omnisharp (Roslyn) formats is the generally accepted way for formatting C# macros.

The problem is that our folding regions are currently computed in a language agnostic way, based on indentation.

**Comment by aeschli** [comment]
The request for language aware folding is https://github.com/Microsoft/vscode/issues/3422.

Moving to Omnisharp to decide whether the formatter needs to be changed or made configurable.

**Comment by uday0408** [comment]
So **#region** and **#endregion** are special case of preprocessor macros? They are not placed at the left most column, since September 2017 release.

**Comment by DustinCampbell** [comment]
Correct `#region` and `#endregion` are treated specially by the C# formatter.

**Comment by Leopotam** [comment]
@aeschli you can try [this extension](https://marketplace.visualstudio.com/items?itemName=Leopotam.csharpfixformat) with `"csharpfixformat.style.indent.preprocessorIgnored": false` setting.

**Comment by DustinCampbell** [comment]
@uday0408, please see @Leopotam's reply above for a way to add this behavior.

**Comment by uday0408** [comment]
Using **C# Fix Format** extension and `"csharpfixformat.style.indent.preprocessorIgnored": false` setting  I was able to use the **#if** / **#endif** directives without having them completely outdented. This allowed the folding to work correctly in VSCode which is what I wanted. Thanks!

**Comment by DustinCampbell** [comment]
@uday0408: FWIW, we've been asking for awhile to have an API from VS Code that languages can use to define custom folding (https://github.com/Microsoft/vscode/issues/3422). Once we have that, we'll be able to make folding work for **#if** / **#endif** correctly. Currently, I would suspect that the folding will not be accurate for nested **#if** / **#endif** when **#else** is interspersed.
