### ISSUE TITLE
Local variables are not expandable - cannot drill into the members

### ISSUE THREAD

**Issue by jeffschwMSFT** [OmniSharp/omnisharp-vscode#201]
![locals](https://cloud.githubusercontent.com/assets/9561583/14575412/850d8082-0316-11e6-9e31-e0737aaf0227.gif)

Repo:
RC2 empty web application
set break point within app.Run
try to inspect context

C# Extension: 1.0.3-rc2

**Comment by caslan** [comment]
Thanks for reporting this. How did you create the 'empty' web application? Is it just the 'context' variable or all local variables?

**Comment by gregg-miskelly** [comment]
David Fowler ran into this too. It is mostly the same problem as in #173, though I also found #178 while poking around.
