### ISSUE TITLE
Cannot create Debug directory

### ISSUE THREAD

**Issue by martinellison** [OmniSharp/omnisharp-vscode#2011]
## Environment data
`dotnet --info` output:  dotnet: command not found...
VS Code version:

Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Date 2018-01-25T10:32:23.601Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
C# Extension version: 1.13.0

## Steps to reproduce
start VSCode

## Expected  behavior
Omnisharp works

## Actual behavior
  "Unable to create directory "/Debug/". Access to the path "/Debug/" is denied."
Omnisharp does not start.

**Comment by DustinCampbell** [comment]
What operating system are you running? Also, could you provide your OmniSharp Log? You can retrieve this by select View->Output from the VS Code menu and then choosing "OmniSharp Log" from the top-right corner of the Output pane.

**Comment by martinellison** [comment]
> uname -a
Linux xiaosan 4.14.16-200.fc26.x86_64 #1 SMP Wed Jan 31 19:34:52 UTC 2018
x86_64 x86_64 x86_64 GNU/Linux

i.e. Fedora 26. I run dnf upgrade so everything should be at the current
patch levels.

Here is what I am getting from OmniSharp. Note that there is an issue with
MSBuild,which I have raised with them separately.


Starting OmniSharp server at 2018-2-7 10:28:09
Target: /home/martin/jigsaw/git/main/main/Main/Main.sln

OmniSharp server started wth Mono
Path:
/home/martin/.vscode/extensions/ms-vscode.csharp-1.13.1/.omnisharp/omnisharp/OmniSharp.exe
PID: 3734

�[info]: OmniSharp.Stdio.Host
Starting OmniSharp on fedora 26.0 (x64)
[warn]: OmniSharp.MSBuild.Discovery.Providers.MonoInstanceProvider
It looks like you have Mono 5.2.0 or greater installed but MSBuild could
not be found.
Try installing MSBuild into Mono (e.g. 'sudo apt-get install msbuild') to
enable better MSBuild support.
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
Located 1 MSBuild instance(s)
1: StandAlone 15.0 -
"/home/martin/.vscode/extensions/ms-vscode.csharp-1.13.1/.omnisharp/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
MSBUILD_EXE_PATH environment variable set to
'/home/martin/.vscode/extensions/ms-vscode.csharp-1.13.1/.omnisharp/omnisharp/msbuild/15.0/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
Registered MSBuild instance: StandAlone 15.0 -
"/home/martin/.vscode/extensions/ms-vscode.csharp-1.13.1/.omnisharp/omnisharp/msbuild/15.0/Bin"
MSBuildExtensionsPath = /usr/lib/mono/xbuild
CscToolPath =
/home/martin/.vscode/extensions/ms-vscode.csharp-1.13.1/.omnisharp/omnisharp/msbuild/15.0/Bin/Roslyn
CscToolExe = csc.exe
MSBuildToolsPath =
/home/martin/.vscode/extensions/ms-vscode.csharp-1.13.1/.omnisharp/omnisharp/msbuild/15.0/Bin
TargetFrameworkRootPath = /usr/lib/mono/xbuild-frameworks
[info]: OmniSharp.Cake.CakeProjectSystem
Detecting Cake files in '/home/martin/jigsaw/git/main/main/Main'.
[info]: OmniSharp.Cake.CakeProjectSystem
Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
Initializing in /home/martin/jigsaw/git/main/main/Main
[info]: OmniSharp.DotNet.DotNetProjectSystem
Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
Detecting projects in '/home/martin/jigsaw/git/main/main/Main/Main.sln'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
Loading project:
/home/martin/jigsaw/git/main/main/Main/Assembly-CSharp.csproj
[warn]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
Unable to create directory "/Debug/". Access to the path "/Debug/" is
denied.
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
Could not write lines to file
"/Debug/Assembly-CSharp.csproj.CoreCompileInputs.cache". Could not find a
part of the path "/Debug/Assembly-CSharp.csproj.CoreCompileInputs.cache".
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
Failed to load project file
'/home/martin/jigsaw/git/main/main/Main/Assembly-CSharp.csproj'.
/home/martin/jigsaw/git/main/main/Main/Assembly-CSharp.csproj

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
Loading project:
/home/martin/jigsaw/git/main/main/Main/Assembly-CSharp-firstpass.csproj
[warn]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
Unable to create directory "/Debug/". Access to the path "/Debug/" is
denied.
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
Could not write lines to file
"/Debug/Assembly-CSharp-firstpass.csproj.CoreCompileInputs.cache". Could
not find a part of the path
"/Debug/Assembly-CSharp-firstpass.csproj.CoreCompileInputs.cache".
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
Failed to load project file
'/home/martin/jigsaw/git/main/main/Main/Assembly-CSharp-firstpass.csproj'.
/home/martin/jigsaw/git/main/main/Main/Assembly-CSharp-firstpass.csproj

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
Loading project:
/home/martin/jigsaw/git/main/main/Main/Assembly-CSharp-Editor.csproj
[warn]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
Unable to create directory "/Debug/". Access to the path "/Debug/" is
denied.
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
Could not write lines to file
"/Debug/Assembly-CSharp-Editor.csproj.CoreCompileInputs.cache". Could not
find a part of the path
"/Debug/Assembly-CSharp-Editor.csproj.CoreCompileInputs.cache".
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
Failed to load project file
'/home/martin/jigsaw/git/main/main/Main/Assembly-CSharp-Editor.csproj'.
/home/martin/jigsaw/git/main/main/Main/Assembly-CSharp-Editor.csproj

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
Loading project:
/home/martin/jigsaw/git/main/main/Main/Assembly-CSharp-Editor-firstpass.csproj
[warn]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
Unable to create directory "/Debug/". Access to the path "/Debug/" is
denied.
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
Could not write lines to file
"/Debug/Assembly-CSharp-Editor-firstpass.csproj.CoreCompileInputs.cache".
Could not find a part of the path
"/Debug/Assembly-CSharp-Editor-firstpass.csproj.CoreCompileInputs.cache".
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
Failed to load project file
'/home/martin/jigsaw/git/main/main/Main/Assembly-CSharp-Editor-firstpass.csproj'.
/home/martin/jigsaw/git/main/main/Main/Assembly-CSharp-Editor-firstpass.csproj

[info]: OmniSharp.Script.ScriptProjectSystem
Detecting CSX files in '/home/martin/jigsaw/git/main/main/Main'.
[info]: OmniSharp.Script.ScriptProjectSystem
Could not find any CSX files
[info]: OmniSharp.Stdio.Host
Invoking Workspace Options Provider:
OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
Configuration finished.
[info]: OmniSharp.Stdio.Host
Omnisharp server running using Stdio at location
'/home/martin/jigsaw/git/main/main/Main' on host 3606.



Regards,
Martin

**Comment by DustinCampbell** [comment]
Could you try dnf installing `msbuild` and see if that addresses the problem?

**Comment by martinellison** [comment]
Thanks, the msbuild people have fixed their issue, so now I have been able
to re-install msbuild and that has fixed OmniSharp. So please close the
issue as fixed.

Regards,
Martin

**Comment by DustinCampbell** [comment]
Glad to hear it. Thanks for verifying!
