### ISSUE TITLE
Compiler Preprocessor Directives Break Intellisense Completely

### ISSUE THREAD

**Issue by leemorton** [OmniSharp/omnisharp-vscode#2012]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     debian-stretch
 OS Version:  2018.1
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : fdf361624c1087ec874615382781754392e69118

VS Code version: 1.19.3
C# Extension version: 1.13

## Steps to reproduce
dotnet new classlibrary -lang C#
Create a .cs file that is entirely wrapped by a preprocessor directive. e.g.

> #if build_for_unit_tests
using System;
using Autofac;
namespace BlahSDK
{
    public class ContextForUnitTests
    {
        public ContextForUnitTests() {
            var builder = new ContainerBuilder();
            builder.Build();
        }
    }
}
#endif

Then attempt to use intellisense.

## Expected  behavior
Intellisense works

## Actual behavior
Intellisense does not work at all. There are a bunch of errors when using "Toggle Developer Tools"
When you take away the directive wrapper intellisense works again.

Any ideas...?

**Comment by DustinCampbell** [comment]
From the repro steps that you described, it sounds like the C# editing experience is working as designed. Within disabled pre-processor blocks, C# does not provide completion (this is the same inside Visual Studio). If you add `#define build_for_unit_tests` to the top of your file, I would expect IntelliSense to appear inside the block.

Please let me know if I've misunderstood the steps you provided.

**Comment by aemxdp** [comment]
@leemorton @DustinCampbell 
This approach doesn't make much sense. For example, I'm using Unity3d, it defines preprocessor directives for C# scripts externally (so they are not lexically visible), how to get intellisense working in this case? Personally, I would be happy if it just works always even if it wastes some processor cycles, but at least having a flag "csharp.alwaysPerformIntellisenseInsidePreprocessorBlocks" would be great.

**Comment by DustinCampbell** [comment]
Closing this as working as designed.

**Comment by opl-** [comment]
In case anyone else stumbles upon this issue in the future:

One way to fix this is by creating an [`omnisharp.json` file](https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options) in your project root and make Omnisharp use a specific configuration for the editor intellisense that includes the declaration you need.

In this example I create a completely new configuration "Editor", but reusing an existing one works too. This also works for other things, such as `<Reference>`.

**omnisharp.json**
```json
{
    "msbuild": {
        "Configuration": "Editor"
    }
}
```

**Project.csproj**
```xml
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Editor|AnyCPU' ">
    <DefineConstants>build_for_unit_tests;</DefineConstants>
  </PropertyGroup>
```
