### ISSUE TITLE
Add an ignore list for Remove unnecessary usings.

### ISSUE THREAD

**Issue by cpmcgrath** [OmniSharp/omnisharp-vscode#2018]
Regardless of if they are currently used or not in the file, I always like to have 
```
using System;
using System.Linq;
```
In my list of usings. It would be fantastic if there was an option that let us specify which namespace should be ignored when the Remove unnecessary usings function is run.

**Comment by rchande** [comment]
@cpmcgrath We use the underlying Roslyn service and they would need to implement this. Filed https://github.com/dotnet/roslyn/issues/24710 for you.
