### ISSUE TITLE
Colorization mismatch when using variables

### ISSUE THREAD

**Issue by vsccarl** [OmniSharp/omnisharp-vscode#2020]
## Environment data
`dotnet --info` output:
```
CLI: 2.1.4
Commit: 5e8add2190
.NET Core 2.0.5
Build: 17373eb129b05aa18ece963f8795d65ef8ea54
Runtime: ubuntu 16.04 x64
```
VS Code version: `1.20.0`
C# Extension version: `1.14.0-beta4`

## Steps to reproduce
Add this code into a C# file
```
int num = 5;
Console.WriteLine(num);
```
## Expected  behavior
I would expect the color for `num` to be white where it is used. And on hover I would expect `int` to be dark blue and `num` to be white again, like where it is declared.

## Actual behavior
![image](https://user-images.githubusercontent.com/12900364/35949147-e6b637fc-0c24-11e8-8110-f8b4bda78c57.png)

**Comment by DustinCampbell** [comment]
This is by design. VS Code highlighting uses regular expressions rather than an AST. So, colorization is really a best guess. Any colorization issues can be moved to https://github.com/dotnet/csharp-tmLanguage, where the C# TextMate grammar lives.
