### ISSUE TITLE
Running dotnet core console application fails to read input from internal debug console

### ISSUE THREAD

**Issue by Olian04** [OmniSharp/omnisharp-vscode#2029]
## Environment data
`dotnet --info` output:
> .NET Command Line Tools (2.1.4)
> 
> Product Information:
>  Version:            2.1.4
>  Commit SHA-1 hash:  5e8add2190
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  17.10
>  OS Platform: Linux
>  RID:         linux-x64
>  Base Path:   /usr/share/dotnet/sdk/2.1.4/
> 
> Microsoft .NET Core Shared Framework Host
> 
 >  Version  : 2.0.5
 >  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

VS Code version:
> 1.20.0
> c63189deaa8e620f650cc28792b8f5f3363f2c5b
> x64

C# Extension version: 1.13.1

## Steps to reproduce

1. Follow https://code.visualstudio.com/docs/other/dotnet
2. Change Main to:
```C#
Console.Write("Name: ");
var name = Console.ReadLine();
Console.WriteLine("Hello {0}!", name);
```

## Expected  behavior
Printing `Name: ` in the debug console.
Waiting on ` Console.ReadLine`.
Printing `Hello {0}!` where `{0}` is whatever was read on the previous line. 

## Actual behavior

Prints this on starting debugging: 
```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.5/System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/olian04/Documents/Projects/Learning/dotnet-console/bin/Debug/netcoreapp2.0/dotnet-console.dll'. Symbols loaded.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.5/System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.5/System.Console.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.5/System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.5/System.Runtime.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
```

Then prints this on manually stopping debugging: 
```
Name: 
The program '[18836] dotnet-console.dll' has exited with code 0 (0x0).
```

## Possible solution: 
In `launch.json` change the default value of `console` from `internalTerminal` to `externalTerminal`.
Solution found through [this SO question](https://stackoverflow.com/questions/48721813/failing-to-read-input-from-net-core-console-application-in-vscode#48722054)

**Comment by gregg-miskelly** [comment]
Hi @Olian04, as you discovered, if you want to take console input, you need to use use either `externalTerminal` or `integratedTerminal`. There is a comment in the launch.json explaining it --

```json
            // For more information about the 'console' field, see https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#console-terminal-window
            "console": "integratedTerminal",
```

**Comment by gregg-miskelly** [comment]
And here is a link to the documentation: https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#console-terminal-window
