### ISSUE TITLE
Can I set solutiondir manually when using msbuild?

### ISSUE THREAD

**Issue by vrokolos** [OmniSharp/omnisharp-vscode#2036]
This error comes up because the solution dir passed is the folder open and the current solution is one folder up. Can I change it manually using omnisharp.json or something?

`<Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('$(SolutionDir)\.nuget\NuGet.targets')" Text="$([System.String]::Format('$(ErrorText)', '$(SolutionDir)\.nuget\NuGet.targets'))" />
  </Target>`

**Comment by DustinCampbell** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#1110

**Comment by DustinCampbell** [comment]
I moved this to the omnisharp-roslyn repo, which is more suitable since this isn't specific to C# for VS Code.
