### ISSUE TITLE
OmniSharp server doesn´t launch in VS Code insider

### ISSUE THREAD

**Issue by egamma** [OmniSharp/omnisharp-vscode#2048]
Originally reported in https://github.com/Microsoft/vscode/issues/43800

## Environment data
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

VS Code version: 1.21-insider
C# Extension version: 1.14.0

## Steps to reproduce
- open a .net folder 

## Expected  behavior
The OmniSharp server starts and its status is shown in the status bar

## Actual behavior
OmniSharp isn´t activated. I couldn´t find any logging from the c#extension.

**Comment by byroniac** [comment]
I just found out that it does work in Insiders on Linux, but not Windows, but that not might be surprising as it is a different platform. However, at work, I am on Windows constantly and that is when I noticed it with the latest update.

**Comment by DustinCampbell** [comment]
I couldn't reproduce this issue. I did the following:

1. Installed the latest VS Code Insiders (x64) on Windows
2. Installed C# for VS Code using the Extensions pane.
3. Created a new .NET Core project with `dotnet new console`
4. Open the folder containing the new .NET Core project in VS Code.

At this point, the C# for VS Code extension activated and launched OmniSharp, which successfully loaded the project. Do steps above work for you? If so, is there more detail you could provide to help us reproduce the issue?

**Comment by egamma** [comment]
These are the steps I´ve used.

This is the VS Code insiders version
![image](https://user-images.githubusercontent.com/172399/36310080-32943120-1327-11e8-8d08-7af3bc308db5.png)

I get not Intellisense. 

![image](https://user-images.githubusercontent.com/172399/36310136-5ffea0aa-1327-11e8-9b5d-94578e547677.png)

Is there some logging/tracing I can enable?

**Comment by DustinCampbell** [comment]
Looks like I have the same Insiders build.

Is the C# extension actually activating? If it does, there should at least be an OmniSharp Log in the Output pane. If there isn't, it's possible that it didn't activate for some reason. Maybe there's something in the Developer Tools?

**Comment by egamma** [comment]
The extension isn´t activating

![image](https://user-images.githubusercontent.com/172399/36310552-bb6efb28-1328-11e8-84e4-67c216c91753.png)

Could not find anything in the Developer Tools Console.

**Comment by DustinCampbell** [comment]
That's very weird, but I'm not sure it's a bug in C# for VS Code. We have changed anything in our package.json related to extension activation in a long time.

**Comment by egamma** [comment]
The extension is activating

![image](https://user-images.githubusercontent.com/172399/36310651-05c57a76-1329-11e8-8c75-7156a2538ab1.png)

There is no output channel from C#
![image](https://user-images.githubusercontent.com/172399/36310711-37df624c-1329-11e8-9e2d-4d5c11214b57.png)

Nothing in the devtools console.

**Comment by egamma** [comment]
Since it only happens in insiders I also suspect an issue in VS Code, but was hoping you can help us to track it down.

**Comment by DustinCampbell** [comment]
OK. That's a *little* better. :smile:

**Comment by DustinCampbell** [comment]
Without debugging, it's hard to know. We don't do much custom logging. I think I've replicated your repro:

![image](https://user-images.githubusercontent.com/116161/36310919-5e6c210c-12de-11e8-8ce2-33d5ff69e32a.png)

Out of curiosity, is your project located in a OneDrive folder with Files On Demand?

**Comment by egamma** [comment]
Looks like a false alarm, sorry. I´ve re-created your setup and now it works.
![image](https://user-images.githubusercontent.com/172399/36311093-6f3b15e6-132a-11e8-8b95-15b27a1afb9b.png)

**Comment by egamma** [comment]
Reading the original issue again

>Just load a C# file in VSCode-Insiders, no intellisense available, maybe Omnisharp editor never loads?

I suspect @byroniac really just opened a C# without any .csproj file

**Comment by DustinCampbell** [comment]
Thanks for the update @egamma. Glad you got it working.

@byroniac: Yes, if you just open a C# file without a C# project of some sort, you won't get meaningful IntelliSense from OmniSharp, unfortunately. This is a long-standing issue on our backlog here: https://github.com/OmniSharp/omnisharp-vscode/issues/47. If you're interested in .NET Core, it's pretty easy to create a C# project and get started. You can check out the video tutorial at https://channel9.msdn.com/Blogs/dotnet/Get-started-VSCode-Csharp-NET-Core-Windows to get going.

**Comment by byroniac** [comment]
Well, this is very strange. It is working now, and the only thing I've changed that I know of, is that I installed another update from VSCode-Insiders. I can't give out my actual project source without an NDA, but it's not very complex and it started from a "dotnet new razor" command. It had a .csproj file, but according to what you said, maybe it never saw it, or just never loaded it. How do you see the list of running extensions?

**Comment by byroniac** [comment]
I take that back. It was working a few minutes ago, and now it is not. If I hover over a symbol, I get a "Loading..." which flashes and disappears, and then nothing. However, if I start Debugging on it, and then Stop Debugging, it works. Very strange.

**Comment by byroniac** [comment]
And now it's working again, if I get out and back in, no problem now, though a few minutes ago that wasn't working. I think I should mention that I'm trying to edit these files on a corporate file server and every once in awhile network performance is an issue. When it doesn't work, I don't get any kind of Intellisense support or reference counts or anything, and it didn't seem to matter how long I waited with the file loaded in the editor. The only other consideration is that I'm running VIPRE antivirus at work, and Defender at home, both Windows 10 Pro. This may not be a real issue, but it really does not work sometimes.

**Comment by byroniac** [comment]
Oh! I didn't know I could press F1 and type "Developer: " and choose the "Developer: Show Running Extensions" that way.
