### ISSUE TITLE
Feature: Support configuring the default *.sln which is loaded when opening

### ISSUE THREAD

**Issue by janaka** [OmniSharp/omnisharp-vscode#2052]
At present, if there are multiple *.sln files in the root, the first one in alphabetical order is selected. This causes confusion to users as it results in intelli-sense not working. There is no intuitive way for users to discovering the connection between the problem and the solution.

I have a branch with a proposed solution which I will submit as a PR soon.

**Comment by rchande** [comment]
Thanks @janaka. Looking forward to your PR!

**Comment by janaka** [comment]
@rchande #2053 is the PR. Thanks.

**Comment by janaka** [comment]
Closing - this was released in 1.16.0
