### ISSUE TITLE
No syntax highlighting for .sln files

### ISSUE THREAD

**Issue by ffes** [OmniSharp/omnisharp-vscode#2056]
## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

VS Code version: 1.20.1
C# Extension version: 1.14.0

## Steps to reproduce
Open the .sln file for your project

## Expected  behavior
To see syntax highlighting

## Actual behavior
All one color

--------------------------

Not sure if this is the right place to report this, since the vscode plugin relies on many other projects to do its magic. Maybe https://github.com/rzhw/language-sln can help for this. Maybe another Omnisharp or dotnet project could/should do this.

And I didn't find any other extension in the marketplace that adds language support for .sln files.

**Comment by rchande** [comment]
@DustinCampbell Are we providing classification in csproj files? Should we extend that to .sln files?

**Comment by DustinCampbell** [comment]
No. This is not something we do. In fact, C# for VS Code doesn't even handle syntax highlighting for C#. Instead, https://github.com/dotnet/csharp-tmLanguage is checked directly into VS Code.

This request should probably be filed on VS Code. *However*, note that Visual Studio doesn't provide syntax highlighting for SLN files either. :smile:

**Comment by rchande** [comment]
@ffes I filed https://github.com/Microsoft/vscode/issues/44761 for you since this is something that would probably be addressed by VS Code itself. I'm going to close this bug. Thanks for the suggestion!
