### ISSUE TITLE
Support running tests from keyboard

### ISSUE THREAD

**Issue by savpek** [OmniSharp/omnisharp-vscode#2059]
It would be nice if current test can be invoked from keyboard instead of codelens only.

Basically context requires two options like: Run current test, Run current test class.

This https://github.com/Microsoft/vscode/issues/41579 could implement feature, but dunno when (if never) it will be implemented to vscode.

**Comment by DustinCampbell** [comment]
Thanks @savpek. We're tracking this feature with https://github.com/OmniSharp/omnisharp-vscode/issues/421.
