### ISSUE TITLE
launch.json keeps telling me there was an error in the build task - when there was no error

### ISSUE THREAD

**Issue by ciel** [OmniSharp/omnisharp-vscode#206]
I have a build task that literally outputs this;

````
Project Lightcast.Core (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project Lightcast.data.Raven (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project Lightcast.Identity (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project Lightcast.data.Lore (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project Lightcast.web.Api (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Project Lightcast.Core (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
Project Lightcast.data.Raven (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
Project Lightcast.Identity (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
Project Lightcast.data.Lore (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
Project Lightcast.web.Api (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
````

And I get the warning popup that there was an error in the build task. I'm really unsure what else to make of this one. There's also no error when the build is run from the command line outside of Visual Studio Code.

**Comment by gregg-miskelly** [comment]
VS Code will tell you that the build task failed if either --

* One of the strings written to stdout/err matched the 'problem matcher' that was declared in your tasks.json
* The exit code from the process was non-zero

Can you try running whatever build command you have configured from the command line to try and figure out which one you might be running into?

**Comment by DustinCampbell** [comment]
Hi @ciel, just wanted to ping to find out if you're still experiencing this problem. Let us know!
