### ISSUE TITLE
No Format Document

### ISSUE THREAD

**Issue by MyTechSite** [OmniSharp/omnisharp-vscode#2061]
## Environment data
`dotnet --info` output:
VS Code version: 1.20.1
C# Extension version: Latest - 1.14.0

## Steps to reproduce

Right-Click in a C# file but there is no Format Document option.  See this picture:

<https://i.imgur.com/ZI0SJ62.png>

## Expected  behavior

I expect to have a Format Document option like I do get in C++ file or HTML file

## Actual behavior
As per the image attached:

<https://i.imgur.com/ZI0SJ62.png>

**Comment by akshita31** [comment]
@MyTechSite Omnisharp doesnot work for stand alone files. Can you try opening the project the file is in?

Also, could you post the Omnisharp Log. View --> Output. In the output pane, there must a panel showing the "Tasks" channel. Please go to "Omnisharp Log" channel and post the output here.
