### ISSUE TITLE
Omnisharp unable to load a relative reference in .net core project

### ISSUE THREAD

**Issue by cannontrodder** [OmniSharp/omnisharp-vscode#2062]
## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

VS Code version: 1.20.1
C# Extension version: 1.14.0

## Steps to reproduce

I have a project with this structure:

```
root
--app
  --DotNetLambda
    --DotNetLambda.csproj
  --DotNetLambda.Test
    --DotNetLambda.Test.csproj
```

`DotNetLambda.Test.csproj` has a reference to the main project:

```
  <ItemGroup>
    <ProjectReference Include="..\..\app\DotNetLambda\DotNetLambda.csproj" />
  </ItemGroup>
```

## Expected  behavior
Intellisense works in both projects.

## Actual behavior
I get this error from OmniSharp:

```
[fail]: OmniSharp.MSBuild.ProjectLoader
        Unable to find project information for 'c:\www\tombola.infrastructure.international.dotnetlambda\app\DotNetLambda\DotNetLambda.csproj'. The project file may be invalid or missing targets required for restore.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\www\tombola.infrastructure.international.dotnetlambda\app\DotNetLambda.Test\DotNetLambda.Test.csproj'.
```

If I change the link to an obviously broken one, I get `The referenced project '..\..\adpp\DotNetLambda\DotNetLambda.csproj' does not exist.`

If I change the reference to an absolute filepath *copied from the error message*, i.e. `c:\www\tombola.infrastructure.international.dotnetlambda\app\DotNetLambda.Test\DotNetLambda.Test.csproj` - it all works.

If I then change the full path to the relative one again, it still works until I reopen the project. I can live with an absolute url for me but I seem to get these issues all the time with OmniSharp - but there is literally nothing in the error message that seems useful to me in trouble-shooting?

The only thing that guarantees it to work is deleting any bin/obj folders, setting the reference to the absolute full path and re-opening. 

I hope someone can look at this and see what obvious mistake I am making but I'm lost!

**Comment by rchande** [comment]
@cannontrodder Can you try updating to the most recent version of the .net sdk? I used the following commands to create project files with relative path references and I'm able to consume types from the console app in the test library:

```
mkdir project
mkdir test
dotnet new console -o project
dotnet new xunit -o test
dotnet add test\test.csproj reference project\project.csproj
dotnet new solution -n solution
dotnet sln solution.sln add test\test.csproj project\project.csproj
```

**Comment by cannontrodder** [comment]
@rchande that worked, I'm feeling a bit silly for not trying that but it worked perfectly! I normally run in docker so tend to pull the latest down but this week I'm relying on the version installed by VS2017. For those that follow, this configuration immediately fixes the issue, hope it saves you time like @rchande  has for me :-)

```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by rchande** [comment]
@cannontrodder Glad you got it working! I'm going to go ahead and close this bug.
