### ISSUE TITLE
Internal error in the debugger when trying to debug

### ISSUE THREAD

**Issue by JohRest** [OmniSharp/omnisharp-vscode#2074]
## Environment data
`dotnet --info` output:

```
PS D:\CloudStation\Johannes\CloudStation\Dokumente\Beruflich\Code\dotnetcore\JRITFirstConsoleApp> dotnet --info
.NET-Befehlszeilentools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

VS Code version:

Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Datum 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64

C# Extension version:
1.14.4
## Steps to reproduce

dotnet new console -o JRITNewConsoleApp

Open the Folder in vscode.
using .NET core Launch (console)
Starting Debugging session in vscode

Vscode Reports:

using System; namespace JRITFirstConsoleApp{    class Program    {        static void Main(string[] args)        {            Console.WriteLine("Hello World!");        }    }} 0 references0 references

PROBLEME
AUSGABE
DEBUGGING-KONSOLE
TERMINAL
Internal error in the debugger.
Exception = System.Runtime.InteropServices.COMException
Message = Internal error in the debugger.
Code = 80004005
   at VsDbg.NativeEntryPoint.EnsureInitialized(String[] args)
   at VsDbg.Transports.LocalTransport.<Init>b__28_0()

## Expected  behavior
Debugger stops at breakpoint

**Comment by gregg-miskelly** [comment]
@JohRest can you tell me what your OS locale is set to?

**Comment by JohRest** [comment]
Hi Gregg,

 

I’m using OS locale set to German.

 

Regards

 

Johannes

 

Von: Gregg Miskelly [mailto:notifications@github.com] 
Gesendet: Dienstag, 27. Februar 2018 18:18
An: OmniSharp/omnisharp-vscode <omnisharp-vscode@noreply.github.com>
Cc: Johannes Rest <johannes@jr-it-services.de>; Mention <mention@noreply.github.com>
Betreff: Re: [OmniSharp/omnisharp-vscode] Internal error in the debugger when trying to debug (#2074)

 

@JohRest <https://github.com/johrest>  can you tell me what your OS locale is set to?

**Comment by gregg-miskelly** [comment]
Thanks!

Can you try this, and let me know what error, if any is printed?

1. Open a command prompt
2. `cd /d "%USERPROFILE%\.vscode\extensions\ms-vscode.csharp-1.14.0\.debugger"`
3. `.\vsdbg-ui --server`
4. Go back to VS Code and open your .vscode\launch.json file
5. Add `"debugServer": 4711,` to your current configuration
6. Try and start debugging

Hopefully you will see an error printed that will give me a better idea what is failing.

Thanks!

**Comment by JohRest** [comment]
Hi Gregg,

 

did what you’d suggested.

 

Same error in vscode. On the console I see the following:

 



 

Hope that helps.

 

Regards

 

Johannes

 

Von: Gregg Miskelly [mailto:notifications@github.com] 
Gesendet: Donnerstag, 1. März 2018 01:50
An: OmniSharp/omnisharp-vscode <omnisharp-vscode@noreply.github.com>
Cc: Johannes Rest <johannes@jr-it-services.de>; Mention <mention@noreply.github.com>
Betreff: Re: [OmniSharp/omnisharp-vscode] Internal error in the debugger when trying to debug (#2074)

 

Thanks!

Can you try this, and let me know what error, if any is printed?

1.	Open a command prompt
2.	cd /d "%USERPROFILE%\.vscode\extensions\ms-vscode.csharp-1.14.0\.debugger"
3.	.\vsdbg-ui --server
4.	Go back to VS Code and open your .vscode\launch.json file
5.	Add "debugServer": 4711, to your current configuration
6.	Try and start debugging

Hopefully you will see an error printed that will give me a better idea what is failing.

Thanks!

**Comment by gregg-miskelly** [comment]
@JohRest unfortunately whatever you saw seems to have been stripped out of the email->git hub comment system. Can you try editing your comment in the web UI?

**Comment by JohRest** [comment]
it said:
accepted Connection from Client
FATAL ERROR: unable to load resource dll.
internal error in the Debugger
Client Connection closed

**Comment by JohRest** [comment]
btw: I saw you're with Microsoft; so from 2000 to 2008 we were colleagues. Best Company I've ever worked for.
Except for my own Company now. :-)

**Comment by gregg-miskelly** [comment]
:)

Thanks. What do you get from `dir "%USERPROFILE%\.vscode\extensions\ms-vscode.csharp-1.14.0\.debugger\1033`?

**Comment by JohRest** [comment]
😉

 

Output:

C:\Users\johan>dir "%USERPROFILE%\.vscode\extensions\ms-vscode.csharp-1.14.0\.debugger\1033

Datenträger in Laufwerk C: ist System

Volumeseriennummer: 92EB-4520

 

Verzeichnis von C:\Users\johan\.vscode\extensions\ms-vscode.csharp-1.14.0\.debugger\1033

 

27.02.2018  11:49    <DIR>          .

27.02.2018  11:49    <DIR>          ..

               0 Datei(en),              0 Bytes

               2 Verzeichnis(se), 160.959.684.608 Bytes frei

 

C:\Users\johan>

 

Cheers

 

Johannes

 

Von: Gregg Miskelly [mailto:notifications@github.com] 
Gesendet: Donnerstag, 1. März 2018 18:25
An: OmniSharp/omnisharp-vscode <omnisharp-vscode@noreply.github.com>
Cc: Johannes Rest <johannes@jr-it-services.de>; Mention <mention@noreply.github.com>
Betreff: Re: [OmniSharp/omnisharp-vscode] Internal error in the debugger when trying to debug (#2074)

 

:)

Thanks. What do you get from dir "%USERPROFILE%\.vscode\extensions\ms-vscode.csharp-1.14.0\.debugger\1033?

**Comment by gregg-miskelly** [comment]
Can you try removing your `.debugger` folder, and restarting VS Code? It looks like somehow some of the debugger files didn't get extracted from the download, though I have no idea how.

**Comment by JohRest** [comment]
It complains about the extension may be corrupt and needs to be reinstalled. Tried this, but the message remains 

 

☹

 

Von: Gregg Miskelly [mailto:notifications@github.com] 
Gesendet: Donnerstag, 1. März 2018 21:54
An: OmniSharp/omnisharp-vscode <omnisharp-vscode@noreply.github.com>
Cc: Johannes Rest <johannes@jr-it-services.de>; Mention <mention@noreply.github.com>
Betreff: Re: [OmniSharp/omnisharp-vscode] Internal error in the debugger when trying to debug (#2074)

 

Can you try removing your .debugger folder, and restarting VS Code? It looks like somehow some of the debugger files didn't get extracted from the download, though I have no idea how.

**Comment by gregg-miskelly** [comment]
If you manually download this zip file and extract it to the .debugger folder do you see the 1033 directory along with the below files?

Zip file: https://download.visualstudio.microsoft.com/download/pr/11522728/3d79abf5bc635c3b55ad2ee590c1eb0e/coreclr-debug-win7-x64.zip

Files you should see:
```
C:\Users\greggm>dir "%USERPROFILE%\.vscode\extensions\ms-vscode.csharp-1.14.0\.debugger\1033"
 Volume in drive C is OSDisk
 Volume Serial Number is 0CF9-3BB7

 Directory of C:\Users\greggm\.vscode\extensions\ms-vscode.csharp-1.14.0\.debugger\1033

02/14/2018  02:35 PM    <DIR>          .
02/14/2018  02:35 PM    <DIR>          ..
02/14/2018  02:35 PM            42,664 vsdbg.resources.dll
02/14/2018  02:35 PM            73,424 vsdebugeng.impl.resources.dll
02/14/2018  02:35 PM           603,304 VSDebugUI.dll
               3 File(s)        719,392 bytes
               2 Dir(s)  554,076,344,320 bytes free
```

**Comment by JohRest** [comment]
Not necessary. I removed the whole .vscode from my profile directory. Then reinstalled c# extension.

 

Now it works!

 

Thanks a lot!

 

Have a nice day in Seattle. BTW: is it raining? Still? 😉

 

Cheers

Johannes

 

Von: Gregg Miskelly [mailto:notifications@github.com] 
Gesendet: Donnerstag, 1. März 2018 23:20
An: OmniSharp/omnisharp-vscode <omnisharp-vscode@noreply.github.com>
Cc: Johannes Rest <johannes@jr-it-services.de>; Mention <mention@noreply.github.com>
Betreff: Re: [OmniSharp/omnisharp-vscode] Internal error in the debugger when trying to debug (#2074)

 

If you manually download this zip file and extract it to the .debugger folder do you see the 1033 directory along with the below files?

Zip file: https://download.visualstudio.microsoft.com/download/pr/11522728/3d79abf5bc635c3b55ad2ee590c1eb0e/coreclr-debug-win7-x64.zip

Files you should see:

C:\Users\greggm>dir "%USERPROFILE%\.vscode\extensions\ms-vscode.csharp-1.14.0\.debugger\1033"
 Volume in drive C is OSDisk
 Volume Serial Number is 0CF9-3BB7
 
 Directory of C:\Users\greggm\.vscode\extensions\ms-vscode.csharp-1.14.0\.debugger\1033
 
02/14/2018  02:35 PM    <DIR>          .
02/14/2018  02:35 PM    <DIR>          ..
02/14/2018  02:35 PM            42,664 vsdbg.resources.dll
02/14/2018  02:35 PM            73,424 vsdebugeng.impl.resources.dll
02/14/2018  02:35 PM           603,304 VSDebugUI.dll
               3 File(s)        719,392 bytes
               2 Dir(s)  554,076,344,320 bytes free

**Comment by gregg-miskelly** [comment]
Glad you solved it! It is actually a fairly nice day today. :) Have a good one.

**Comment by JohnSimon93** [comment]
Does anyone know why the VSCode user **setup** displays this whenever I open the executable file
![image](https://user-images.githubusercontent.com/106265732/170314133-27ea3570-3703-455c-b824-d7de246bfc9e.png)

**Comment by JoeRobich** [comment]
@JohnSimon93 That question would be better answered at https://github.com/microsoft/vscode/issues. Also, please don't comment on closed issues unless it is related. Always feel free to open a new issue when you are running into trouble.
