### ISSUE TITLE
Errors when editing solution which contains both C# .csproj and F# .fsproj projects

### ISSUE THREAD

**Issue by WallaceKelly** [OmniSharp/omnisharp-vscode#2075]
## Environment data
`dotnet --info` output:

    .NET Command Line Tools (2.1.4)

    Product Information:
     Version:            2.1.4
     Commit SHA-1 hash:  5e8add2190

    Runtime Environment:
     OS Name:     Windows
     OS Version:  6.1.7601
     OS Platform: Windows
     RID:         win7-x64
     Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

    Microsoft .NET Core Shared Framework Host

      Version  : 2.0.5
      Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

VS Code version: 1.20.1
C# Extension version: 1.14.0
Ionide-fsharp: 3.17.2 - 22.02.2018

## Steps to reproduce

    mkdir test-vs
    cd test-vs
    dotnet new library -lang F# -o .\ClassLibrary
    dotnet new console -lang C# -o .\MainProgram
    dotnet new sln
    dotnet sln add .\ClassLibrary\ClassLibrary.fsproj
    dotnet sln add .\MainProgram\MainProgram.csproj
    dotnet add .\MainProgram\MainProgram.csproj reference .\ClassLibrary\ClassLibrary.fsproj

_Add this line code to program.cs:_ `ClassLibrary.Say.hello("world.");`

    dotnet run -p .\MainProgram\MainProgram.csproj

_All the above succeeds without error._

In Visual Studio Code, first open the ClassLibrary folder. Building the project (Ctrl-Shift-B) succeeds.  
(_This step is based on guidance from #371._)

In Visual Studio Code, now open the solution folder (test-vs). Notice the following:

- Building the solution (Ctrl-Shift-B) succeeds, as displayed in the Terminal window. 
- However, the Problems window shows one problem. "The name ClassLibrary does not exist in the current context."
- Additionally, if you open the Program.cs file in the editor, the ClassLibrary class is underlined with the same error.
- Finally, Output window and the OmniSharp Log displays the following error:

<pre>
    fail: OmniSharp.MSBuild.ProjectLoader
    The target "GetTargetPath" does not exist in the project.
    c:\Temp\test-vs\MainProgram\MainProgram.csproj
</pre>

## Expected  behavior

- The Problem window should display no problems for the solution.
- The Editor window should display no problems for Program.cs.

## Actual behavior

- The Problem window says, "The name ClassLibrary does not exist in the current context."
- The Editor window underlines the ClassLibrary class in Program.cs, with the same error.
- An error appears in the Omnisharp Log.

**Comment by WallaceKelly** [comment]
![image](https://user-images.githubusercontent.com/698424/36735771-f07a6346-1ba4-11e8-8496-305b4033b5bc.png)

**Comment by DustinCampbell** [comment]
It's pretty clear that one of your projects isn't loading properly. Could you provide your OmniSharp Log? Select View->Output in VS Code and then choose "OmniSharp Log" from the dropdown at the top-right corner of the Output pane.

**Comment by WallaceKelly** [comment]
Starting OmniSharp server at 2/28/2018, 9:18:50 AM
    Target: c:\temp\testvs\temp.sln

OmniSharp server started
    Path: C:\Users\NB61805\.vscode\extensions\ms-vscode.csharp-1.14.0\.omnisharp\OmniSharp.exe
    PID: 13192

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.1.7601.65536 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 3 MSBuild instance(s)
            1: Visual Studio Build Tools 2017 15.3.26730.15 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            2: Visual Studio Enterprise 2017 15.5.27130.2020 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin"
            3: StandAlone 15.0 - "C:\Users\NB61805\.vscode\extensions\ms-vscode.csharp-1.14.0\.omnisharp\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2017 15.3.26730.15 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\temp\testvs'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\temp\testvs
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\temp\testvs\temp.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\temp\testvs\MainProgram\MainProgram.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\temp\testvs'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\temp\testvs\MainProgram\MainProgram.csproj
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\temp\testvs' on host 1124.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The target "GetTargetPath" does not exist in the project.
c:\temp\testvs\MainProgram\MainProgram.csproj

[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\temp\testvs\MainProgram\MainProgram.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MainProgram

**Comment by DustinCampbell** [comment]
Thanks! It looks lile the VS 2017 build tools installed on your machine are causing the problem. When OmniSharp is selecting an instance of MSBuild to use, it's picking the Build Tools. You can address this in a few ways:

- Uninstall the build tools if you don't need them.
- Update the build tools to the latest version. It appears that you have an older version installed (15.3).
- Ensure that the build tools have both C# and F# workloads installed.
- Start VS Code from a VS 2017 Developer Command Prompt, which will have environment variables set that cause OmniSharp to select the VS 2017 MSBuild.

**Comment by WallaceKelly** [comment]
I used the Visual Studio Installer to do this...

> Update the build tools to the latest version. 
> Ensure that the build tools have both C# and F# workloads installed.

![installer](https://user-images.githubusercontent.com/698424/36802665-90778f02-1c83-11e8-817f-dd64ed5568b8.PNG)

![fsharp](https://user-images.githubusercontent.com/698424/36802674-94136442-1c83-11e8-8dd4-3bf348eba1bf.PNG)


...I am no longer receiving errors.

Thank you @DustinCampbell !

**Comment by DustinCampbell** [comment]
Not a problem. I'm glad it's working for you now.
