### ISSUE TITLE
Step/continue fails with 'Unexpected CLRDBG output from command'

### ISSUE THREAD

**Issue by dopare** [OmniSharp/omnisharp-vscode#208]
Periodically getting such error when stepping over while debugging, but debugging still works.

```
error while processing request 'next' (exception: Unexpected CLRDBG output from command 
"-exec-next --thread 1283504". Unknown Error: 0x9233000b)
```

**Comment by gregg-miskelly** [comment]
Thanks for the bug report. This means that the step command is received when we are already running. We should change our code to ignore extra requests these so you don't get the annoying error pop up. But it doesn't hurt.

**Comment by jeffschwMSFT** [comment]
@gregg-miskelly I have seen this for step-in as well.  As for not hurting, about 1 out of 5 times that I see this error flydown, dotnet-cli crashes with a null ref.

error while processing request 'stepIn' (exception: Unexpected CLRDBG output from command "-exec-step --thread 1093283". Unknown Error: 0x9233000b)

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff9cf73f06 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff971184ec pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff8e75f6e7 abort + 129
3   libcoreclr.dylib              	0x000000010ab41af5 0x10aafd000 + 281333
4   libcoreclr.dylib              	0x000000010ae7b425 0x10aafd000 + 3662885
5   libcoreclr.dylib              	0x000000010ae7b5a2 0x10aafd000 + 3663266
6   libcoreclr.dylib              	0x000000010ade4a35 0x10aafd000 + 3045941

**Comment by gregg-miskelly** [comment]
Interesting. Thanks Jeff.

**Comment by jpopadak** [comment]
I have noticed this occur when clicking any of the 'Continue', 'Step Over', 'Step In', or 'Step Out' buttons quickly. So when I want to jump over a few lines but don't put down a breakpoint, I click Step Over and it will show the popup when I go to click Step Over for the second time. Or if I am in lower code and want to step out, if I click Step Out a few times in a row, it will show this error.

**Comment by chuckries** [comment]
This is fixed in OpenDebugAD7 and will be shipped post RC2.
