### ISSUE TITLE
Display order of keywords and snippets in intellisense

### ISSUE THREAD

**Issue by Actionintint** [OmniSharp/omnisharp-vscode#2085]
Is there a way to display snippets such as if, for, swicth, foreach etc. from the keyword to the top of intellisense or not display keywords?
![default](https://user-images.githubusercontent.com/20414138/36943592-3d854416-1fcf-11e8-9fe6-2be0e38f2c57.png)

**Comment by rchande** [comment]
@Actionintint the option "editor.snipppetSuggestions" lets you control where in the list snippets appear. If you set it to "top" snippets will always appear before keywords. If you set it to "bottom", they will always appear after keywords. "none" disables them. Can you try setting one of those options and see if it meets your needs?

**Comment by Actionintint** [comment]
By setting that option to "top", I was able to realize my desired behavior.

Thank you.
