### ISSUE TITLE
"Debug adapter executable 'vsdbg-ui.exe' does not exist" on Windows x86

### ISSUE THREAD

**Issue by SridharPasham** [OmniSharp/omnisharp-vscode#2086]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

VS Code version:
1.20.1

C# Extension version:
ms-vscode.csharp, version: 1.14.0
## Steps to reproduce
Created a asp.net core mvc application
Commnads:
dotnet new mvc
## Expected  behavior
When I run the application with debugger or without debugger. It should open the browser and load the application.
## Actual behavior
Showing this error message
Debug adapter executable 'C:\\Users\\Sridhar\\.vscode\extensions\\ms-vscode.csharp-1.14.0\\.debugger\\vsdbg-ui.exe' does not exist.

Tried to uninstall and reinstall C# extension but no use.

**Comment by gregg-miskelly** [comment]
@SridharPasham The first time you activate the C# extension, the C# extension will open up an output window pain and show you information about the packages that it is downloading. Are you seeing this? What does it say?

![download-dependencies](https://user-images.githubusercontent.com/11078489/36992125-d0bfeb70-205e-11e8-8a93-ac10f95f4255.png)

**Comment by SridharPasham** [comment]
@gregg-miskelly Tried to uninstall and reinstall C# extension. Did not find any output in OUTPUT window.
If I remember correctly I think it was giving x86 is not supported.

If you need exact message let me know how I can get that initial message.

**Comment by gregg-miskelly** [comment]
Ah. Got it. Yes, the root problem is that we don't support x86 Windows (https://github.com/OmniSharp/omnisharp-vscode/issues/844).

But it looks like we broke our error messages for this scenario. @WardenGnaw Do you have the cycles to try and fix the error messages here?

**Comment by WardenGnaw** [comment]
@gregg-miskelly Yes. I'll take a look.

**Comment by SridharPasham** [comment]
@gregg-miskelly @WardenGnaw Looks like we to have to wait until C# supports x86. Is there any timeline  for x86 support? or do we have to fairly assume going forward vs code only works on x64?
