### ISSUE TITLE
MVC view(.shtml) no intellisense.

### ISSUE THREAD

**Issue by crucialize** [OmniSharp/omnisharp-vscode#2087]
There's no intellisene of the ViewModel when I edit the view(.shtml). (For example: Model.UserName ) . Actually I can't find any useful intellisense when editing shtml. The code can be compile succefully.  Besides, vs2017 has intellisene.

**Comment by crucialize** [comment]
In addition, it seems that there's completely no intellisense when editng .shtml

**Comment by rchande** [comment]
We'd like to enable this at some point. It's tracked by #168.

**Comment by crucialize** [comment]
Thanks...fortunately I found another extention which is designed to solve this problem.
