### ISSUE TITLE
 This socket has been ended by the other party

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#209]
_From @vscodeerrors on February 11, 2016 9:17_

Issue Id: <b>dda9a9d9-c965-4e8f-ef83-cbd9fb4e346f</b><br /><br />*Versions* <br />- 0.10.6-release<br />-  dfc08dc9edf6607483b193bf934d3badc3fa2e11<br />-  db71ac615ddf9f33b133ff2536f5d33a77d4774e<br />*Stack* <br />Error: This socket has been ended by the other party<br />    at Socket.writeAfterFIN [as write] (net.js:268:12)<br />    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\jrieken.vscode-omnisharp\out\omnisharpServer.js:383:40 <no sourcemaps><br />    at StdioOmnisharpServer._makeNextRequest (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\jrieken.vscode-omnisharp\out\omnisharpServer.js:378:16) <no sourcemaps><br />    at StdioOmnisharpServer.OmnisharpServer._processQueue (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\jrieken.vscode-omnisharp\out\omnisharpServer.js:254:14) <no sourcemaps><br />    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\jrieken.vscode-omnisharp\out\omnisharpServer.js:227:23 <no sourcemaps><br />    at StdioOmnisharpServer.OmnisharpServer.makeRequest (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\jrieken.vscode-omnisharp\out\omnisharpServer.js:216:23) <no sourcemaps><br />    at null._onTimeout (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\jrieken.vscode-omnisharp\out\features\dia<br />

_Copied from original issue: Microsoft/vscode#2926_

**Comment by jrieken** [comment]
_From @aminroosta on April 17, 2016 7:5_

+1

**Comment by jrieken** [comment]
_From @MulderLiu on April 18, 2016 1:4_

on mac os x have this error 


[INFO] Started OmniSharp from '/Users/vsmac/.vscode/extensions/ms-vscode.csharp-0.3.7/bin/omnisharp' with process id 779...
/Users/vsmac/.vscode/extensions/ms-vscode.csharp-0.3.7/bin/omnisharp: line 11: /Users/vsmac/.vscode/extensions/ms-vscode.csharp-0.3.7/bin/packages/dnx-mono.1.0.0-beta4/bin/dnx: No such file or directory
/Users/vsmac/.vscode/extensions/ms-vscode.csharp-0.3.7/bin/omnisharp: line 11: exec: /Users/vsmac/.vscode/extensions/ms-vscode.csharp-0.3.7/bin/packages/dnx-mono.1.0.0-beta4/bin/dnx: cannot execute: No such file or directory

**Comment by DustinCampbell** [comment]
I'm not sure what to do with this @jrieken. It doesn't seem all that actionable.

**Comment by jrieken** [comment]
It seems like omnisharp disappeared without the client noticing. Subsequent requests fail and that's not handled graceful.

**Comment by DustinCampbell** [comment]
The two reports seem unrelated. The first call stack is from an old version of the extension (note the name of the extension in the stack) and the second report has a different error.

**Comment by MulderLiu** [comment]
0.10.6 version without this error
This error occurred in version 1
I think it's dnx-mono.1.0.0-beta4's problem.

**Comment by DustinCampbell** [comment]
If that's the case, it might be addressed by updated to .NET Core and the latest C# extension on this repo.

**Comment by MulderLiu** [comment]
dnvm list

Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-rc1-update1    coreclr x64          darwin          
       1.0.0-rc1-update1    mono                 linux/osx       
       1.0.0-rc1-update2    coreclr x64          darwin          
  *    1.0.0-rc1-update2    mono                 linux/osx       default
i cant't find the dnx-mono.1.0.0-beta4 .....

**Comment by DustinCampbell** [comment]
Hi @MulderLiu,

It's been awhile since our last contact and there've been several releases, including .NET Core 1.0 and multiple releases of the C# extension. Are you still experiencing similar issues as the one you described here?

**Comment by DustinCampbell** [comment]
Closing since there hasn't been any comment in three weeks. @MulderLiu, if this is still an issue, please let me know.
