### ISSUE TITLE
Activating extension `ms-vscode.csharp` failed: Cannot find module 'jsonc-parser'.

### ISSUE THREAD

**Issue by jemhuntr** [OmniSharp/omnisharp-vscode#2090]
## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

VS Code version: 1.20.1
C# Extension version: 1.14.0

---

For some reason, intellisense isn't working for me since the CSharp extension fails to load. I'm getting a devtools console error:

    [Extension Host] Activating extension `ms-vscode.csharp` failed:  Cannot find module 'jsonc-parser'

![image](https://user-images.githubusercontent.com/6434778/36986368-9831e8e6-20d4-11e8-9734-6621f3e9ff6a.png)

Other than that, there isn't much else I see. The "OmniSharp: Restart OmniSharp" and "OmniSharp: Select Project" commands show up on the palette, but when I try to run them, I get a `command 'o.restart' not found` error:

![image](https://user-images.githubusercontent.com/6434778/36986507-efe67700-20d4-11e8-89bf-e6da30280f2d.png)

The OmniSharp log doesn't show up as a menu item on the Output tab either.

Any ideas?

**Comment by rchande** [comment]
@jemhuntr Can you try removing and reinstalling the C# extension?

**Comment by jemhuntr** [comment]
@rchande Yup, have tried that with no success. Even tried disabling all extensions and installing the C# extension only. Even an entire VS Code install didn't help (perhaps I need to clean some cache/storage to completely delete and reinstall all dependencies?).

**Comment by SheGe** [comment]
@jemhuntr Had the same and these steps helped me:
* Uninstall VSCode
* Remove `.vscode` directory from user home
* Install VSCode
* Install all extensions again

**Comment by jemhuntr** [comment]
@SheGe Thanks! That did the trick for me.

**Comment by colonelchlorine** [comment]
Did the trick, sadly. Had to reinstall completely :(
