### ISSUE TITLE
When code is written in the async lambda function, the smart hints are not normal

### ISSUE THREAD

**Issue by gmono** [OmniSharp/omnisharp-vscode#2097]
## Environment data
`dotnet --info` output:
.NET 命令行工具 (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
VS Code version: 1.21.0
C# Extension version:1.14.0

Use dotnet's "Web" template to write code in "Startup.cs" in the following cases: 

app.Run(async (context) =>
            {
                context.Items.<There is not anything appear!!>
                await context.Response.WriteAsync("Hello World!");
            });
but when you writer this:
app.Run(async (context) =>
            {
                context.Items.<Add a semicolon at the end of the line beforehand,and it would be ok>;
                await context.Response.WriteAsync("Hello World!");
            });

**Comment by rchande** [comment]
@gmono Thanks for filing this. This appears to be a bug in the underlying Roslyn APIs used by the C# extension. I filed https://github.com/dotnet/roslyn/issues/25356 for you.
