### ISSUE TITLE
Omnisharp, autocomplete, etc. not working for one project

### ISSUE THREAD

**Issue by tlhinman** [OmniSharp/omnisharp-vscode#2100]
## Environment data
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```
VS Code version: 1.21.0
C# Extension version: 1.14.0

## Steps to reproduce
Open a specific project of mine in the Unity editor. Double-click a C# file to open in VS Code.

## Expected  behavior
Get Intellisense capability, and be able to use Go To Definition.

## Actual behavior
Get no project-specific autocompletion, and Go To Definition yields "No definition found for [X]" for anything. No error messages are apparent.

The strange thing is that it's only this Unity project; I have no problems with others. I've tried various restarts to clear things up, including deleting my local Github repo and cloning it anew.

I think it has something to do with a bad solution file; the flame in the lower right says "[Project].sln" for the projects that work, but simply "Switch projects" for the bad one. Clicking that yields only the current solution and no alternatives. I've tried quitting VS Code, deleting the .sln file, and opening it up again; no change.

Thanks for any assistance you can provide.

**Comment by DustinCampbell** [comment]
Hi! Could you provide your OmniSharp Log after opening the project in VS Code? You can retrieve this be selecting View->Output from the VS Code menu and then choosing "OmniSharp Log" from the top-right corner of the Output pane.

**Comment by tlhinman** [comment]
`Starting OmniSharp server at 2018-3-12 11:35:04
    Target: /Users/myname/Dev/UnityGames/MyGame/MyGame.sln

OmniSharp server started wth Mono
    Path: /Users/myname/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/OmniSharp.exe
    PID: 6985

﻿[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.12.6 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/Users/myname/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin"
            CscToolPath = /Users/myname/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/myname/Dev/UnityGames/MyGame'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /Users/myname/Dev/UnityGames/MyGame
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/myname/Dev/UnityGames/MyGame/MyGame.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/myname/Dev/UnityGames/MyGame/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/myname/Dev/UnityGames/MyGame/Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/myname/Dev/UnityGames/MyGame/Assembly-CSharp.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/myname/Dev/UnityGames/MyGame'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/myname/Dev/UnityGames/MyGame' on host 6970.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/myname/Dev/UnityGames/MyGame/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/myname/Dev/UnityGames/MyGame/Assembly-CSharp-Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/myname/Dev/UnityGames/MyGame/Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-Editor
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly '/Users/myname/Dev/UnityGames/MyGame/Temp/bin/Debug/Assembly-CSharp.dll'`

**Comment by tlhinman** [comment]
```
Starting OmniSharp server at 2018-3-12 11:35:04
    Target: /Users/myname/Dev/UnityGames/MyGame/MyGame.sln

OmniSharp server started wth Mono
    Path: /Users/myname/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/OmniSharp.exe
    PID: 6985

﻿[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.12.6 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/Users/myname/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin"
            CscToolPath = /Users/myname/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/myname/Dev/UnityGames/MyGame'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /Users/myname/Dev/UnityGames/MyGame
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/myname/Dev/UnityGames/MyGame/MyGame.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/myname/Dev/UnityGames/MyGame/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/myname/Dev/UnityGames/MyGame/Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/myname/Dev/UnityGames/MyGame/Assembly-CSharp.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/myname/Dev/UnityGames/MyGame'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/myname/Dev/UnityGames/MyGame' on host 6970.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/myname/Dev/UnityGames/MyGame/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/myname/Dev/UnityGames/MyGame/Assembly-CSharp-Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/myname/Dev/UnityGames/MyGame/Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-Editor
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly '/Users/myname/Dev/UnityGames/MyGame/Temp/bin/Debug/Assembly-CSharp.dll'
```

**Comment by tlhinman** [comment]
Update: This problem... fixed itself? I don't know what happened, but the flame now says "MyGame.sln" and things are working as expected. Advice still appreciated in the event this crops up again, but for now I think I'm good.

**Comment by DustinCampbell** [comment]
Did you happen to build your project before it fixed itself?

**Comment by tlhinman** [comment]
I think I only used the Play button in the Unity editor. Not sure if that counts.

**Comment by DustinCampbell** [comment]
I would expect that to count, yes.

**Comment by tlhinman** [comment]
Righto, then. I'm happy to close this for now.

**Comment by godevblog** [comment]
No i have this problem:(

In OmniSharp Log are ony [info].

Any CodeLeans not work.
