### ISSUE TITLE
debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by pallapo** [OmniSharp/omnisharp-vscode#2104]
## Environment data
`dotnet --info` output: 2.0
VS Code version: Version 1.22.0-insider (1.22.0-insider)
## os
Macos version 10.13.3

## EXCEPTIONS

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

## CRASHED THREAD

Thread 12 Crashed:
0   libsystem_kernel.dylib        	0x00007fff65b04e3e __pthread_kill + 10
1   libsystem_c.dylib             	0x00007fff65a61312 abort + 127
2   libcoreclr.dylib              	0x000000010f89b35e PROCAbort + 14
3   libcoreclr.dylib              	0x000000010f899ef2 PROCEndProcess(void*, unsigned int, int) + 226
4   libcoreclr.dylib              	0x000000010fb61e91 UnwindManagedExceptionPass1(PAL_SEHException&, _CONTEXT*) + 833
5   libcoreclr.dylib              	0x000000010fb62025 DispatchManagedException(PAL_SEHException&, bool) + 293
6   libcoreclr.dylib              	0x000000010facb567 IL_Throw(Object*) + 743
7   ???                           	0x000000022d611700 0 + 9351272192
8   ???                           	0x000000022d82e2b9 0 + 9353487033
9   ???                           	0x000000022d9d0160 0 + 9355198816
10  ???                           	0x000000022d82e28d 0 + 9353486989
11  ???                           	0x000000022d83a505 0 + 9353536773
12  ???                           	0x000000022d83a48d 0 + 9353536653
13  ???                           	0x000000022d98c7ef 0 + 9354921967
14  ???                           	0x000000022d98638b 0 + 9354896267
15  ???                           	0x000000022d98a8ac 0 + 9354913964
16  ???                           	0x000000022db1f681 0 + 9356572289
17  ???                           	0x0000000114f0c0c9 0 + 4646289609
18  ???                           	0x0000000114f0341f 0 + 4646253599
19  ???                           	0x0000000114f03257 0 + 4646253143
20  ???                           	0x0000000114ee7b26 0 + 4646140710
21  libcoreclr.dylib              	0x000000010fb6f9ab UMThunkStub + 273
22  libvsdebugeng.dylib           	0x000000010f448f07 dispatcher::DkmDataContainer::CollectionTermPhase2(dispatcher::XapiThreadOperation*) + 87
23  libvsdebugeng.dylib           	0x000000010f445e3b dispatcher::CXapiPhase2ObjectQueue::FlushList(dispatcher::XapiThreadOperation*, ATL::CAtlList<dispatcher::DkmDataContainer*, ATL::CElementTraits<dispatcher::DkmDataContainer*> >*) + 43
24  libvsdebugeng.dylib           	0x000000010f445ed3 dispatcher::XapiCollectionTermPhase2Task::ExecuteTask(dispatcher::XapiThreadOperation*) + 19
25  libvsdebugeng.dylib           	0x000000010f43c588 dispatcher::XapiWorkerThread::ProcessSyncTask(dispatcher::XapiWorkerThreadSyncTask*, dispatcher::XapiThreadOperation*) + 136
26  libvsdebugeng.dylib           	0x000000010f43c469 dispatcher::XapiWorkerThread::ThreadRoutine() + 377
27  libvsbaseservices.dylib       	0x000000010f77ee08 CorUnix::CPalThread::ThreadEntry(void*) + 328
28  libsystem_pthread.dylib       	0x00007fff65c406c1 _pthread_body + 340
29  libsystem_pthread.dylib       	0x00007fff65c4056d _pthread_start + 377
30  libsystem_pthread.dylib       	0x00007fff65c3fc5d thread_start + 13

**Comment by gregg-miskelly** [comment]
@pallapo sorry for not getting to this sooner. I can't tell exactly what the problem is from that stack, but I can add a try/catch in there to at least stop things from crashing and log data with more information about what the problem is. I am on vacation. I will see if someone else from the debugger team can help you, and if not, we can put out a private .vsix of the extension when I get back that saves more info.

**Comment by gregg-miskelly** [comment]
Actually, I did fix one bug in 1.15-beta1 that might fix this. Would you mind trying the latest beta and see if it still happens?

Instructions: https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases

**Comment by gregg-miskelly** [comment]
If you are still running into this let us know and we can try and help.
