### ISSUE TITLE
Remote Debugging on Linux ARM64 not Available

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#2105]
https://github.com/OmniSharp/omnisharp-vscode/issues/1562 tracks adding ARM remote debugging support, but ARM64 is still not supported. This issue tracks adding ARM64 support.

Note that currently the .NET Runtime doesn't have official builds for ARM64, and this item is unlikely to be worked on until the Runtime decides to add official support.

**Comment by bigredhdl** [comment]
Now that dotnet core 3 preview 2 has arm64 support, is there hope of getting remote debugging support?

**Comment by gregg-miskelly** [comment]
@bigredhdl This is definitely on the team's radar, but it isn't something we have started on yet.

**Comment by bigredhdl** [comment]
@gregg-miskelly Is this something the community can help with? I have an ARM64 platform (xilinx zynq) that I would like to use .net core on, but having no on target debugger is giving me pause.

**Comment by gregg-miskelly** [comment]
No, the VS/VS Code debugger is considered a part of Visual Studio and hence is closed-source. The only thing you can do is target ARM32 instead of ARM64 since there is an ARM32 debugger.

**Comment by bigredhdl** [comment]
Okay thanks.  Unfortunately, running ARM32 on Xilinx petalinux is not as straight forward as you might think, but I'll give it another try.  :cry: :panda_face:

**Comment by gregg-miskelly** [comment]
In case this is helpful - it is any easier to run an ARM32 docker container?

**Comment by bigredhdl** [comment]
Probably not because it would add a lot of complexity of getting to the hardware I need access to.  That's okay, I'm really glad more ARM64 support is on the radar.  This just might not be the right project yet for us to put .net on an embedded device.

**Comment by gregg-miskelly** [comment]
It is being actively worked on both the VS debugger team and the CLR team. Our hope would be fairly soon as time is running out to fix the runtime before it is released. But all new platforms have a stage where known feature work is done and you have a series of blocking bugs and you can't see what comes next until these are debt with, and ARM64 has been no different. So it is impossible to give an accurate ETA.

**Comment by gregg-miskelly** [comment]
With the release of .NET Core 3.0 we are declaring this feature complete. The aka.ms links for remote debugging (see [instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Attaching-to-remote-processes)) were updated a while ago to download arm64 versions.

NOTE: This will only work if the target app is running on .NET Core 3.0.
