### ISSUE TITLE
No intellisense in VS Code 1.0.0

### ISSUE THREAD

**Issue by maxonico** [OmniSharp/omnisharp-vscode#211]
Hello all.

I'm experiencing a weird problem, in which I do have intellisense when creating extensions (TS) but when trying to create C# programs, I do not. The only intellisense that I get is using the words already written in the file I opened.

Everything is installed as it should (at least, I can compile, build, publish), OS version is 1.0.1-rc2 and Mono has been installed also (4.2.3).

Almost forgot, I'm on Windows 8.1.

Btw, this also pops up in the console output:

> [ERROR] Error: connect ETIMEDOUT 192.30.252.127:443

Thanks!

**Comment by DustinCampbell** [comment]
Hi @maxonico,

You mentioned that your OS version is 1.0.1-rc2, but I think you mean the C# extension version. Is that correct?

It sounds like the C# Extension was unable to download the latest OmniSharp release from GitHub (192.30.252.127 is api.github.com). Perhaps the GitHub API was down for a bit and timed out. Do you get the same message on a restart of Visual Studio Code?

**Comment by maxonico** [comment]
Hi!, indeed it's the extension version. Yep, it tries to connect to 192.30.252.127 but fails (timeout). Restarting VSCode has no effect, also it's not a proxy error as I have already configured the proxy settings.

Could be something related to github maybe, altough this:

https://api.github.com/ has a Json as response, but,

https://192.30.252.127/ produces an error.

**Comment by DustinCampbell** [comment]
Note that this looks very similar to #200.

**Comment by maxonico** [comment]
I'm pretty positive it's not the proxy, but following the steps you gave in #200 solved the problem.
Thanks!

**Comment by DustinCampbell** [comment]
I'm pretty sure it's not the proxy either. I would have expected the same error message if it were (i.e. ECONNREFUSED).

**Comment by eByte23** [comment]
A few of us are also facing this issue.

**Comment by eByte23** [comment]
Well similar downloads and installs but as of 1.1.0 it doesnt work, unless you download the latest release and manually install it

**Comment by DustinCampbell** [comment]
I've heard a few other reports of 0.3.7 not working properly with VS Code 1.1, but I couldn't repro. We'll be releasing the most recent release very shortly though. Stay tuned.

**Comment by DustinCampbell** [comment]
I believe the proxy is should be fixed with https://github.com/OmniSharp/omnisharp-vscode/pull/350.
