### ISSUE TITLE
Extensions download / installation failure

### ISSUE THREAD

**Issue by AgileQ** [OmniSharp/omnisharp-vscode#2111]
## Environment data
`dotnet --info` output:
VS Code version:1.21
C# Extension version:latest

## Steps to reproduce:
going thru open proxy
sites white listed as par VS Code documentation
install extension, 
Reload VSCode
open project
Extensions fail to install

## Actual behavior See 2nd picture. 
![image001](https://user-images.githubusercontent.com/8042006/37412663-c1181782-277b-11e8-925d-d844d7f505b6.png)
![image001 1](https://user-images.githubusercontent.com/8042006/37412733-e5f104d8-277b-11e8-814d-fba9cf6efb6c.png)

extensions can be downloaded from the browser addresses. But Can the extensions be installed manually or is there something missing or not configured properly on my network? All other extensions have no problems
AgileQ

**Comment by gregg-miskelly** [comment]
@AgileQ usually this means that you need to configure HTTP proxy settings in your VS Code settings. Here are various other issues people have run into that might be helpful: https://github.com/OmniSharp/omnisharp-vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+central+directory+

**Comment by AgileQ** [comment]
Problem fixed. Thanks
