### ISSUE TITLE
Show Fixes -> Generate type in new file creates an empty file

### ISSUE THREAD

**Issue by brokenbacon** [OmniSharp/omnisharp-vscode#2112]
## Environment data
`dotnet --info` output:

```
$ dotnet --info
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

VS Code version:

![image](https://user-images.githubusercontent.com/31377202/37427320-0d5e7de6-2797-11e8-8e9c-3bc26287aa6c.png)

C# Extension version:

1.14.0

## Steps to reproduce

1. Open or Create a C# project.
   ```
   dotnet new mvc --auth individual
   ```
1. Open any C# file. I used `Startup.cs`.
1. Type MyClass abc
1. Click on Show Fixes, or press `Ctrl + .`
1. From the list of options, select Generate type 'MyClass' -> Generate class 'MyClass' in new file
1. Open the generated file `MyClass.cs`
1. The file contains an empty file, instead of a basic template.

![image](https://user-images.githubusercontent.com/31377202/37427600-e9a47954-2797-11e8-92d8-f09737f4fe4c.png)

![image](https://user-images.githubusercontent.com/31377202/37427603-eceb489a-2797-11e8-8d97-e814bb5f3e1a.png)

Although the screenshots show I'm using some extensions, I removed all the other extensions from VS Code when I was testing this. Plus I tested on two different machines.

## Expected  behavior

The generated class or interface file should have namespace and class name defined from templates.

## Actual behavior

The generated file has no content.

This is bothering me so much. Any helps will be appreciated!

**Comment by brokenbacon** [comment]
When I click on "Generate Class" (in the same text file), it works fine.

**Comment by brokenbacon** [comment]
I installed the current version on VS Code Insider, and on previous VS Code versions but I still had the same issue. So it looks like this issue is not coming from VS Code but more of this extension itself.

I installed v1.13.1 (https://github.com/OmniSharp/omnisharp-vscode/releases) and the issue was gone. I can generate a new type in a new file.

The version v1.14.0 appears to have introduced this issue. I did not test with other versions.

I tested with Auto Extension Update disabled. This feature is so important to me and it looks like I will have to stay with v1.13.1 for now.

**Comment by brokenbacon** [comment]
For a future note to myself and for anyone trying to reproduce:

To disable auto updating extensions:

![screen shot 2018-03-19 at 6 58 33 pm](https://user-images.githubusercontent.com/31377202/37628478-9603c5c0-2ba7-11e8-962c-4a844d2aeedb.png)

To install a specific version of Extension:

- https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

Click on the "Install from VXIS" from the above screenshot, or

```
code --install-extension myextension.vsix
```

**Comment by brokenbacon** [comment]
This issue is not fixed in the most updated beta version [v1.15.0-beta3](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.15.0-beta3)

**Comment by DustinCampbell** [comment]
Thanks for the added detail @brokenbacon! @rchande, could this have been broken with some of your code action changes in 1.14?

**Comment by rchande** [comment]
This should be fixed now.
