### ISSUE TITLE
Errors are only shown when the file has been modified

### ISSUE THREAD

**Issue by pgoral** [OmniSharp/omnisharp-vscode#2116]
Errors are only shown when the file has been modified.
Unmodified files is not processed by omnisharp. Errors are not highlighted in editor. No codelens. No records in Problems view. Files in explorer are not marked with red font.
When file is modified (added whitespace character) omnisharp starts processing this file.
Other files with errors are not processed.
You can watch it here: 
[https://prnt.sc/is2l0j](https://prnt.sc/is2l0j)
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.100)

Product Information:
 Version:            2.1.100
 Commit SHA-1 hash:  b9e74c6520

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.100\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
VS Code version: 1.21.1
C# Extension version: 1.14.0

**Comment by pgoral** [comment]
After deleting .vscode folder everything works fine.

**Comment by rchande** [comment]
@pgoral Interesting that deleting your .vscode folder fixed the issue. I wonder if you had a bad configuration in tasks.json? I'm going to close this issue, but feel free to add further comments if you find anything interesting.
