### ISSUE TITLE
Intellisense not showing some properties in `HttpClientHandler`

### ISSUE THREAD

**Issue by austincummings** [OmniSharp/omnisharp-vscode#2123]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.300-preview1-008174)

Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153
```
VS Code version: 1.21.0
C# Extension version: 1.14.0

## Steps to reproduce
1. Create a new netstandard2.0 project - `dotnet new classlib`
2. Open project in VS Code and wait for Omnisharp to start
3. Put following into `Class1.cs` file
```csharp
using System;
using System.Net.Http;

namespace ReproBug1
{
    public class Class1
    {
        public void Test() {
            using (var handler = new HttpClientHandler {
                Server
            })
        }
    }
}
```
4. Put cursor after `Server` and hit `Ctrl+space` for intellisense popup

## Expected  behavior
Expect to see `ServerCertificateCustomValidationCallback` in auto completion list when building `HttpClientHandler` using object initializer.

## Actual behavior
There is no entry in completion list for `ServerCertificateCustomValidationCallback` property.

**Comment by DustinCampbell** [comment]
FWIW, this repro has the same behavior in Visual Studio 2017 and is working as designed. The reason that `ServerCertificateCustomValidationCallback` doesn't appear in IntelliSense is because it is marked with an `[EditorBrowsable(EditorBrowsableState.Never)]`. This attribute is intended to be used by library to hide items from IntelliSense.
