### ISSUE TITLE
Intellisense in string literals

### ISSUE THREAD

**Issue by jeffschwMSFT** [OmniSharp/omnisharp-vscode#213]
![string literals](https://cloud.githubusercontent.com/assets/9561583/14620949/88f4b836-0574-11e6-8dac-c4588046daa5.gif)

Intellisense is firing in string literals. This is almost always not the behavior I am looking for.

C# extension 1.0.3-rc2

**Comment by DustinCampbell** [comment]
Dupe of #154. Note that it is a feature of VS Code to show text-based completion.
