### ISSUE TITLE
VSCode No Symbols Loaded for Full .NET Debugging With IIS

### ISSUE THREAD

**Issue by dforsyth-iit** [OmniSharp/omnisharp-vscode#2130]
## Environment data
`dotnet --info` output:
`.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.101\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d`

VS Code version: 1.21.1
C# Extension version: 1.14.0

## Steps to reproduce
Using the following launch.json:
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Attach",
            "type": "clr",
            "request": "attach",
            "processName": "w3wp"
        }
    ]
}`

And attaching to an already running IIS process, the same as I would do for full Visual Studio. 

## Expected  behavior
Can step through and debug as with full Visual Studio

## Actual behavior
No breakpoints are active, and they all say "Unverified breakpoint, No symbols have been loaded for this document."

In the debug console, I get messages saying it's skipping loading symbols for all the standard .NET libraries, but I can't find any of my libraries in the output.

**Comment by dforsyth-iit** [comment]
I have also tried adding:

`"symbolPath": [
                "${workspaceRoot}/../../bin"
            ]`

To the launch.json

**Comment by dforsyth-iit** [comment]
I've done some more digging and it looks like it's trying to use the .NET core debugger, so it's failing to load full .NET symbols.

`WARNING: Could not load symbols for 'MyLibrary.dll'. 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\46b682b8\ce6702c4\assembly\dl3\56675e51\8784d879_33c2d301\MyLibrary.pdb' is a Windows PDB. These are not supported by the cross-platform .NET Core debugger.`


[My understanding](https://github.com/OmniSharp/omnisharp-vscode/wiki/Desktop-.NET-Framework) was that this plugin supported the full .NET Framework. Is this not the case for my version?

**Comment by gregg-miskelly** [comment]
No, it does have limited support for .NET Core, but you are running into one of the two big limitations that the article you pointed to lists - this extension only supports portable PDBs.

You can configuration your project to build portable PDBs: https://github.com/OmniSharp/omnisharp-vscode/wiki/Portable-PDBs#csproj

**Comment by dforsyth-iit** [comment]
Thanks for the reply! If I replace `<DebugType>full</DebugType>` with `<DebugType>portable</DebugType>`, my project fails to build with the message `CSC : error CS1902: Invalid option 'portable' for /debug; must be full or pdbonly`. Any suggestions?

**Comment by gregg-miskelly** [comment]
This means you are using a C# compiler that is too old. Anything from the last ~2 years will 'portable' debug type. Where are you getting your C# compiler from?

**Comment by gregg-miskelly** [comment]
Sorry, what I mean is - where are you getting msbuild from? (ex: did you install some version of full Visual Studio). 

The options that I am aware of:
- You can install full VS - https://www.visualstudio.com/
- I haven't done this personally, but can install the build tools - https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15
- You can use the compilers from a NuGet package - https://www.nuget.org/packages/Microsoft.Net.Compilers/

The one downside of the last one is that the compilers will run a bit slower as they will not get pre-compiled to native code.

VS Code is a loosely-coupled tool. So you can configure the build task to do anything you want. If you have the VS 2017 build tools installed (1 or 2 from above), I think probably the easiest way to way to use the VS 2017 msbuild would be to either open VS Code from within a VS 2017 developer prompt, or set your build command that runs a batch script that runs the developer command prompt setup script (<VS-Install-Dir>\Common7\Tools\VsDevCmd.bat) followed by running msbuild on your project.

**Comment by dforsyth-iit** [comment]
Oh, sorry. I have Visual Studio 2017 installed, and I assume all the C#
compiler stuff along with it. I thought I would already be using the latest
C# compiler with that?

On 23 Mar 2018 11:39, "Gregg Miskelly" <notifications@github.com> wrote:

Sorry, what I mean is - where are you getting msbuild from? (ex: did you
install some version of full Visual Studio).

The options that I am aware of:

   - You can install full VS - https://www.visualstudio.com/
   - I haven't done this personally, but can install the build tools -
   https://www.visualstudio.com/thank-you-downloading-visual-
   studio/?sku=BuildTools&rel=15
   <https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15>
   - You can use the compilers from a NuGet package - https://www.nuget.org/
   packages/Microsoft.Net.Compilers/
   <https://www.nuget.org/packages/Microsoft.Net.Compilers/>

The one downside of the last one is that the compilers will run a bit
slower as they will not get pre-compiled to native code.

VS Code is a loosely-coupled tool. So you can configure the build task to
do anything you want. If you have the VS 2017 build tools installed (1 or 2
from above), I think probably the easiest way to way to use the VS 2017
msbuild would be to either open VS Code from within a VS 2017 developer
prompt, or set your build command that runs a batch script that runs the
developer command prompt setup script (\Common7\Tools\VsDevCmd.bat)
followed by running msbuild on your project.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OmniSharp/omnisharp-vscode/issues/2130#issuecomment-375502502>,
or mute the thread

**Comment by gregg-miskelly** [comment]
In that case, try this --
1. From the Windows Start menu, open a Developer Command Prompt for VS 2017
2. cd to the directory of your project
3. `code .` to open up VS Code (assuming you picked the default option of adding VS Code to your path, if not, you will need to add the path to VS Code here)
4. From here try your build

The issue is that in VS 2017, VS made changes so that you can install multiple instances, and way less stuff installs in a way that it changes the global state of your machine. So you are likely getting an older version of msbuild if you aren't running from within the developer command prompt.

**Comment by dforsyth-iit** [comment]
Okay, that makes sense. Is there a way to update the system version of msbuild to the latest one? I don't want to have to open VSCode from a VS2017 developer prompt every time.

**Comment by gregg-miskelly** [comment]
You are reaching the limits of my expertise. If you open a command prompt, do `set PATH="<VS-InstallRoot>\MSBuild\15.0\Bin";%PATH%`, and then run msbuild. Does that work? If so you could update your system environment to include that directory.

Another option would be to setup your build task in tasks.json to run a batch script (instead of directly executing msbuild), and from that batch script you can run VsDevCmd.bat before invoking msbuild.

**Comment by dforsyth-iit** [comment]
That specific command didn't work, but I tracked down where my msbuild 15 version was installed (`C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin`) and added that to my path. Restarted VSCode, and everything is building and debugging great. Thanks so much for your help Gregg!

**Comment by LCarlos-Rodriguez** [comment]
@dforsyth-iit great stuff, I have the same problem where I need to point the build to the iis for debugging purposes. in the end did you have to make the changes to launch.json as well?

**Comment by esobreira** [comment]
I had it working just by installing MSBuild 15.9.53 within Visual Studio 2017 Build Tools. "vs_BuildTools-15.9.exe"
