### ISSUE TITLE
Tab 1 scrolls by itself when you go to another tab(Tab2) with plugin on in VSCode

### ISSUE THREAD

**Issue by issacnitin** [OmniSharp/omnisharp-vscode#2131]
## Environment data
`dotnet --info` output:
VS Code version: 1.21.1
C# Extension version:

## Steps to reproduce
Open 2 1000 line C# code in a big project with lots of references. 
Go to line 500 in tab 1
Go to line 100 in tab 2, or click "go to definition" on tab 1
Go back to Tab 1

## Expected  behavior
Tab one should point to same line of code 

## Actual behavior
Tab one points to different line of code

PS: This is really annoying. It happens only with windows version of VSCode. I had to disable the plugin just because of this.

**Comment by rchande** [comment]
@issacnitin This sounds like a VS Code bug--please feel free to file it at https://github.com/Microsoft/vscode/issues. I'm closing this issue, feel free to add further comments if you believe this is an issue with the C# extension.

**Comment by issacnitin** [comment]
This issue happens only when using the plugin
