### ISSUE TITLE
Code lens never loads 

### ISSUE THREAD

**Issue by adragoset** [OmniSharp/omnisharp-vscode#2132]
## Environment data
```
.NET Command Line Tools (2.1.103)

Product Information:
 Version:            2.1.103
 Commit SHA-1 hash:  60218cecb5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.103\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```
VS Code version:
1.21.1
79b44aa704ce542d8ca4a3cc44cfca566e7720f1
x64

C# Extension version:
1.14.0

## Steps to reproduce
Unsure,
I have a machine with vs code and the c# extension running windows 10 professional same environment otherwise and code lens loads.
Project builds and restores correctly otherwise.

Omnisharp logs contains no errors or warnings 

## Expected  behavior
code lens should load 

## Actual behavior
code lens never loads making it extremely difficult to debug tests.

**Comment by rchande** [comment]
@adragoset Please post your omnisharp log. Are other IDE features (eg, IntelliSEnse, find all references) working?

**Comment by adragoset** [comment]
## Omnisharp log
Starting OmniSharp server at 3/26/2018, 1:27:59 PM
    Target: c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\smart_singulator_nn_interface.sln

OmniSharp server started
    Path: C:\Users\adragose\.vscode\extensions\ms-vscode.csharp-1.14.0\.omnisharp\OmniSharp.exe
    PID: 18396

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.1.7601.65536 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "C:\Users\adragose\.vscode\extensions\ms-vscode.csharp-1.14.0\.omnisharp\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Users\adragose\.vscode\extensions\ms-vscode.csharp-1.14.0\.omnisharp\msbuild\15.0\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "C:\Users\adragose\.vscode\extensions\ms-vscode.csharp-1.14.0\.omnisharp\msbuild\15.0\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Users\adragose\.vscode\extensions\ms-vscode.csharp-1.14.0\.omnisharp\msbuild\15.0\Bin\Roslyn
            MSBuildExtensionsPath = C:\Users\adragose\.vscode\extensions\ms-vscode.csharp-1.14.0\.omnisharp\msbuild
            MSBuildToolsPath = C:\Users\adragose\.vscode\extensions\ms-vscode.csharp-1.14.0\.omnisharp\msbuild\15.0\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\Users\adragose\Documents\Source\smart_singulator_nn_interface
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\smart_singulator_nn_interface.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\ClientConnectionServer\ClientConnectionServer.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\SmartSingulatorClassificationApp\SmartSingulatorClassificationApp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\SmartSingulatorCSConnectionTester\SmartSingulatorCSConnectionTester.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\DomainModels\DomainModels.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\UnitTests\UnitTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\GigECameraInterface\GigECameraInterface.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\GigECameraInterfaceTester\GigECameraInterfaceTester.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\FrameWork\FrameWork.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\ProtocolMessages\ProtocolMessages.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\TwincatInterface\TwincatInterface.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\ClientConnectionServer\ClientConnectionServer.csproj
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface' on host 10132.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\ClientConnectionServer\ClientConnectionServer.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\SmartSingulatorClassificationApp\SmartSingulatorClassificationApp.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\SmartSingulatorClassificationApp\SmartSingulatorClassificationApp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\SmartSingulatorCSConnectionTester\SmartSingulatorCSConnectionTester.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\SmartSingulatorCSConnectionTester\SmartSingulatorCSConnectionTester.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\DomainModels\DomainModels.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\DomainModels\DomainModels.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\UnitTests\UnitTests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\UnitTests\UnitTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\GigECameraInterface\GigECameraInterface.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\GigECameraInterface\GigECameraInterface.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\GigECameraInterfaceTester\GigECameraInterfaceTester.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\GigECameraInterfaceTester\GigECameraInterfaceTester.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\FrameWork\FrameWork.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\FrameWork\FrameWork.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\ProtocolMessages\ProtocolMessages.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\ProtocolMessages\ProtocolMessages.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\TwincatInterface\TwincatInterface.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\adragose\Documents\Source\smart_singulator_nn_interface\TwincatInterface\TwincatInterface.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: ClientConnectionServer
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: SmartSingulatorClassificationApp
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: SmartSingulatorCSConnectionTester
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: DomainModels
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: UnitTests
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: GigECameraInterface
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: GigECameraInterfaceTester
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: FrameWork
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: ProtocolMessages
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: TwincatInterface

**Comment by DustinCampbell** [comment]
Does the completion list work? Do you have any of the following settings set to false in your VS Code settings?

* csharp.referencesCodeLens.enabled
* csharp.testsCodeLens.enabled

**Comment by diggudg** [comment]
I have also the same problem, CodeLens is not working after enabling all settings.
     "editor.codeLens": true,
    "csharp.referencesCodeLens.enabled": true,
    "csharp.testsCodeLens.enabled": true

**Comment by sunmachine** [comment]
Suddenly started happening, unsure what prompted it. I'll try to repro from a clean slate and report back.

**Comment by natemcmaster** [comment]
@DustinCampbell I noticed this periodically, too. In my case, there were no errors in the log, and intellisense was working.

![image](https://user-images.githubusercontent.com/2696087/40397275-9d60b41a-5de6-11e8-9bd0-36f294bfa59c.png)

This problem didn't go away after issuing the `Omnisharp: Restart Omnisharp` command, but was fixed after reloading VS Code altogether.

**Comment by DustinCampbell** [comment]
@akshita31 : Do you have any ideas here?

**Comment by akshita31** [comment]
@adragoset @diggudg The latest version of the extension is 1.15.2. Could you try updating and checking if the error still persists.

**Comment by akshita31** [comment]
@natemcmaster Thanks for the information. We will look into.

**Comment by JeremyDaug** [comment]
I've also been running into this problem, but my intellisense is also not working.  Have all the newest versions and I've uninstalled and reinstalled both VSCode and the extension multiple times.

**Comment by DustinCampbell** [comment]
I suspect that's a different problem @JeremyDaug. Could you file a separate issue?

**Comment by DustinCampbell** [comment]
I think I've spotted the cause of this issue. If I'm correct, the original report is different. This would have been introduced when we add the run/debug tests in a class code lens.

**Comment by ethan-deng** [comment]
Make sure the folder name of your solution matches the the name of solution file .sln.
