### ISSUE TITLE
PackageReference could not be found

### ISSUE THREAD

**Issue by cilerler** [OmniSharp/omnisharp-vscode#2134]
## Environment data

`dotnet --info` output:
```
.NcodeET Command Line Tools (2.1.103)

Product Information:
 Version:            2.1.103
 Commit SHA-1 hash:  60218cecb5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.103\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

`code --version` output:
```
1.21.1
79b44aa704ce542d8ca4a3cc44cfca566e7720f1
x64
```
C# Extension version:
```
1.14.0 (February 14, 2017)
```

## Steps to reproduce
1. Create a new console app `dotnet new console`
2. Add a remote nupkg library via `dotnet add package Newtonsoft.Json`
3. Add a local nupkg **file** via `dotnet add package Ruya.Primitives -s "%homepath%\Source\repos\!nuget"`
4. `dotnet restore`
5. Use it in app, such as `Console.WriteLine(Ruya.Primitives.Constants.Staging);`
6. Open `*.csproj` file
7. Locate `<PackageReference Include="Newtonsoft.Json" ...` line, you will see that *depencency version indicator* says `Latest`
8. Locate `<PackageReference Include="Ruya.Primitives" ...` line, you will see that *depencency version indicator* says `Ruya.Primitives could not be found`

## Expected  behavior
Dependency Version Indicator should state `Ruya.Primitives` is `Latest`.

## Actual behavior
Dependency Version Indicator states `Ruya.Primitives could not be found`.

**Comment by rchande** [comment]
@cilerler I'm not sure what you mean by "Dependency Version Indicator". Can you post a screenshot?

**Comment by cilerler** [comment]
![image](https://user-images.githubusercontent.com/385958/37923074-3c9d46dc-30fc-11e8-9861-0de08b71d5eb.png)

**Comment by rchande** [comment]
@cilerler I think you're getting that from an extension. I don't have any "Package Reference Indicators": 
![image](https://user-images.githubusercontent.com/3751401/37923310-b3836a2e-30e3-11e8-81d4-dc63114c4c82.png)

Can you post your list of installed extensions?

**Comment by cilerler** [comment]
Ohh my bad, you are right it is [Version Lens](https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens).  Thank you for your help...
