### ISSUE TITLE
New files showing type or namespace not found but it is their

### ISSUE THREAD

**Issue by ryanzec** [OmniSharp/omnisharp-vscode#2136]
## Environment data
`dotnet --info` output:
NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

VS Code version: 1.21.1
C# Extension version: 1.14.0

## Steps to reproduce
Create a new file after loading a Unity Project

## Expected  behavior
No Error

## Actual behavior
The editor is showing red line with `type or namespace could not be found` when it is actually their. I can `go to definition` and it loads the right file, the code compiles and executes properly in Unity.

![screen shot 2018-03-25 at 9 11 31 am](https://user-images.githubusercontent.com/444206/37875603-e1271e6e-300f-11e8-8e7d-7fec26fbe693.png)

Not sure what could cause this. I know if I do:

`dotnet build Assembly-CSharp.csproj`

I get the following error (same error when I do a build on any of the Unity csproj files):

```
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Nothing to do. None of the projects specified contain packages to restore.
/usr/local/share/dotnet/sdk/2.1.4/Microsoft.Common.CurrentVersion.targets(1124,5): error 
MSB3644: The reference assemblies for framework ".NETFramework,Version=v3.5" were 
not found. To resolve this, install the SDK or Targeting Pack for this framework version or 
retarget your application to a version of the framework for which you have the SDK or 
Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly 
Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly 
may not be correctly targeted for the framework you intend. 
[/repositories/arpg-project/Assembly-CSharp.csproj]

Build FAILED.

/usr/local/share/dotnet/sdk/2.1.4/Microsoft.Common.CurrentVersion.targets(1124,5): error 
MSB3644: The reference assemblies for framework ".NETFramework,Version=v3.5" were 
not found. To resolve this, install the SDK or Targeting Pack for this framework version or 
retarget your application to a version of the framework for which you have the SDK or 
Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly 
Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly 
may not be correctly targeted for the framework you intend. 
[/repositories/arpg-project/Assembly-CSharp.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.60
```

However I don't seem to see that error in the vscode output logs (I only get this when I run `dotnet` manually). I have tried this with both 5.8.0 and 5.10.0 of Mono installed and can't figure it out.

This same code / project load fine and shows no errors in Rider.

Any help in trying to debug this would be awesome.

**Comment by rchande** [comment]
@ryanzec Can you try installing the mono mdk as disussed in this bug? https://github.com/OmniSharp/omnisharp-vscode/issues/2088#issuecomment-375222076

**Comment by ryanzec** [comment]
Well... it seems like installing visual studio for mac resolves my issue of installing mono properly so that I can now properly set VS Code as my editor in Unity, open scripts into VS Code from Unity without getting the reference assemblies not found error, and creating new files seems fine too. It is slow to remove the errors from copying and pasting into new files, but they do get removed after several seconds.

Not exactly the process I would expect to get Mono installed properly but hey, it works I guess.

**Comment by DustinCampbell** [comment]
FWIW, you can always install the latest Mono MDK from http://www.mono-project.com/download/stable/ rather than resorting to installing VS for Mac.

**Comment by ryanzec** [comment]
@DustinCampbell I first tried to install from the download on that page and it did not work.

**Comment by DustinCampbell** [comment]
The installer did not work?

**Comment by ryanzec** [comment]
The mono standalone installer worked saying it installed properly but VS Code still has the same issue after.

**Comment by SirIntruder** [comment]
This looks a lot like https://github.com/OmniSharp/omnisharp-vscode/issues/2040. Does error persist if you, after creating new file in vscode:
-Go to unity
-Wait for recompile
-Go back to vscode, reload vscode

btw I would be extremely suprised if invoking dotnet build on unity projects did anything... unity does a lot of quirky stuff behind the curtains to output script dlls from your code

**Comment by wdelvi** [comment]
I'm having the same issue. @ryanzec Did you ever find a solution?

**Comment by ryanzec** [comment]
@wdelvi Last thing that I did was install visual studio for mac first and that more or less worked.

I have since switched from Unity to C++ for my project (and also to using Visual Studio on Windows) so I can't remember anything else outside of that.

**Comment by rchande** [comment]
@ryanzec What's your output of `mono --version`?

**Comment by timminkov** [comment]
I'm having the same issue, FYI

**Comment by Hivemind9000** [comment]
I'm having the exact same issue on Windows 10. Happens when I create a new script/class from within Unity then edit it in VS Code - OmniSharp doesn't seem to dynamically update the namespace references. Unity has no problem - compiles/runs. If I create the script/class from within VS Code it produces a type mismatch warning rather than an error.

Workaround is to close and reopen VS Code. Thankfully VS Code starts up nice and quick.

Running:
Visual Studio Code 1.27.2
C# for Visual Studio Code 1.16.1
Unity 2018.2

dotnet --info

.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by timminkov** [comment]
Why did this get closed?

**Comment by mmitang** [comment]
i get same issue
it seems like vscode donot reload .csproject file after add new script(maybe)
i use "reload window" reload project ,is helps!

**Comment by lugehorsam** [comment]
I also get this issue.

**Comment by timminkov** [comment]
@DustinCampbell can this be reopened?

**Comment by Beastman632** [comment]
I also get this issue on Windows 10. Reload window didn't work. I finally worked after I reinstalled vs code.

**Comment by rchande** [comment]
For those following along here, feel free to file an issue using the command "CSharp: report an issue" from VS Code.
