### ISSUE TITLE
cant create vsix offline

### ISSUE THREAD

**Issue by ronmara** [OmniSharp/omnisharp-vscode#2137]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.101\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

VS Code version: 1.21.1
C# Extension version: 1.15.0-beta3

## Steps to reproduce

> run 
> npm i
> npm run compile

Open up gulpfile.js which is located at the root level of the repo and on line 95 change:
`throw new Error('Do not build offline packages on windows. Runtime executables will not be marked executable in *nix packages.');`

to:
`console.log('Do not build offline packages on windows. Runtime executables will not be marked executable in *nix packages.');`

now run

> node node_modules/gulp/bin/gulp.js package:offline

(followed this [guide](https://www.towfeek.se/2017/07/05/enabling-csharp-and-dotnet-core-debugging-in-vs-code-from-an-offline-environment/))

## Expected  behavior
Ill get my offline VSIX package on windows

## Actual behavior
getting exception

> TypeError: eventStream.post is not a function
> at downloadPackage (E:\omnisharp-vscode\out\src\packages.js:141:17)
> at doesPackageTestPathExist.then (E:\omnisharp-vscode\out\src\packages.js:132:20)
> at <anonymous<anonymous>>

**Comment by rchande** [comment]
@akshita31 It looks like this might have gotten regressed with your eventStream changes. Want to take a look?

**Comment by akshita31** [comment]
Yes, it seems that the downloadPackage function expects an eventStream but we are not providing it any.  This part got ignored probably while we made those changes. Will make the necessary changes now.

**Comment by rchande** [comment]
Also, we've had a couple of customers report bugs in this area (offline packaging). Should we add an "offline packaging" integration test that runs whatever scripts a user is expected to run a verifies that they work?

**Comment by akshita31** [comment]
Yes we can, but the offline packaging( similar to the OmnisharpDownloader) calls upon the PackageManager to download some packages from the internet. Mocking the download behaviour is difficult at present, so if we upload some test packages to be downloaded during the integration test then only we can do the complete end to end testing here.
