### ISSUE TITLE
'"<Path to the omnisharp executable>"' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by sebasijan** [OmniSharp/omnisharp-vscode#2139]
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.1.103)

Product Information:
 Version:            2.1.103
 Commit SHA-1 hash:  60218cecb5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.103\


Microsoft .NET Core Shared Framework Host



  Version  : 2.0.6

  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

```

VS Code version:

```
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

C# Extension version:

`1.14.0`

## Steps to reproduce

Install the extension, nothing is working

## Expected  behavior

Intellisense, navigate to errors etc etc etc

## Actual behavior

Error in bottom right of vscode, after clicking on it: 

```
Starting OmniSharp server at 2018-3-27 23:35:39
    Target: c:\Users\Bassie\Source\github\QC Core

OmniSharp server started
    Path: <Path to the omnisharp executable>
    PID: 10000

'"<Path to the omnisharp executable>"' is not recognized as an internal or external command,
operable program or batch file.
Starting OmniSharp server at 2018-3-27 23:36:03
    Target: c:\Users\Bassie\Source\github\QC Core

OmniSharp server started
    Path: <Path to the omnisharp executable>
    PID: 8636

'"<Path to the omnisharp executable>"' is not recognized as an internal or external command,
operable program or batch file.
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```

**Comment by sebasijan** [comment]
I tried reloading and reinstalling the extension several times but nothing helps

**Comment by sebasijan** [comment]
I updated my user settings

    "omnisharp.path": "C:\\Users\\Bassie\\.vscode\\extensions\\ms-vscode.csharp-1.14.0\\bin\\omnisharp\\OmniSharp.exe",

and the error went away, but the extension still does nothing..

**Comment by sebasijan** [comment]
I just did  a complete re-install of vscode, deleted my entire extensions folder, reinstalled omnisharp, and it still doesn't work.

In addition, when trying to view the source of an error I get

 > Unable to open 'GrvRepository.cs': File not found (file:///Repository/GrvRepository.cs).

Not sure if its relaed... How annoying

**Comment by sebasijan** [comment]
After the reinstall, I had to update the path to 

 > "omnisharp.path": "C:\\Users\\Bassie\\.vscode\\extensions\\ms-vscode.csharp-1.14.0\\.omnisharp\\OmniSharp.exe",

Now it appears to work..

**Comment by abdulkareemmoodys** [comment]
after installing c# extension i am getting following error and not able to proceed with code debugging. I found out that OmniSharp.exe is not present in the path its referring to. can any one help me how to get OmniSharp.exe may be the error is because this file is not copied automatically while installing the C# extension. Thanks in advance for help.

"<b>Starting OmniSharp server at 10/7/2019, 8:28:36 PM
    Target: d:\Learning\pluralsight\C#_Fundamentals\Lab\GardeKBook

OmniSharp server started.
    Path: C:\Users\kareabd\.vscode\extensions\ms-vscode.csharp-1.21.4\.omnisharp\1.34.4\OmniSharp.exe
    PID: 25720

'C:\Users\kareabd\.vscode\extensions\ms-vscode.csharp-1.21.4\.omnisharp\1.34.4\OmniSharp.exe' is not recognized as an internal or external command,
operable program or batch file.</u></b></b>"

**Comment by gopalagrawal** [comment]
Same here ... For me, it shows: 


**Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (32185 KB).**
Followed by:

**> C:\Users\myusername\.vscode\extensions\ms-vscode.csharp-1.21.6\.omnisharp\1.34.8-beta.2\OmniSharp.exe' is not recognized as an internal or external command, operable program or batch file.**
**> [ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).**

Restarted my vscode 5 times already and each time get this.  Even followed suggestions at: 
https://blog.mastykarz.nl/issues-dotnet-core-visual-studio-code/
I also have visual studio 2019 (community) installed.  Might be getting into some conflict with that.

**Comment by filipw** [comment]
please remove the "omnisharp.path": "latest" setting from your VS Code settings. this opts into downloading a new build from master branch on every merge and can be unstable (depending on CI issues)

**Comment by gopalagrawal** [comment]
Ok, in VS code settings ...Http: Proxy Strict SSL .... unchecked it.  Then the omnisharp,  .net debugger and razor ... all 3 of them got sucessfully downloaded and installed.  Restarted vs code and opened helloworld.cs.   Still gives a whole lot of squiggly red lines everywhere ... it keeps asking to restore which I do ... still no love.  This is frustrating (but haven't given up yet). .... I have spent almost 3 days on this trying all sorts of suggestions to get it to work.  A plugin should not be this hard to install.

**Comment by filipw** [comment]
as mentioned, please remove  "omnisharp.path": "latest" from your settings.

it doesn't show up in the UI view, you must switch to JSON edit mode.

**Comment by filipw** [comment]
please post your OmniSharp log

**Comment by lesscodetxm** [comment]
Same issue. I get the following in the Output tab (briefly):

```
Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' Failed to download from https://download.visualstudio.microsoft.com/download/pr/f90b2712-8f9e-4922-8c16-8b556e3de023/66b355b126f43f17270951e9d99ab8d8/omnisharp-win-x64-1.34.9.zip. Error code '400')
	Retrying from 'https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.34.9.zip' Failed to download from https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.34.9.zip. Error code '400')
Failed at stage: downloadPackage
400
```

followed by the error about the command not being recognized. I can download the zip file mentioned just fine in a browser. I extracted the zip file into 'C:\Users\<me>\.vscode\extensions\ms-vscode.csharp-1.21.9\.omnisharp\1.34.9' and the 'command not recognized' error went away. I still get the 'failed to download 400' error every time I start vscode.

**Comment by Matt11** [comment]
**sebastijan wrote:**
After the reinstall, I had to update the path to"omnisharp.path": "C:\Users\Bassie\.vscode\extensions\ms-vscode.csharp-1.14.0\.omnisharp\OmniSharp.exe",Now it appears to work..
--

How exactly did you do that? Could you provide a step by step instruction please? I am facing the same issue and don't know how to fix it.

**Comment by sebasijan** [comment]
@Matt11  

Apologies Matt I just saw this, but can confirm:

1. File -> Preferences -> Settings
2. Search `omnisharp.path`
3. Click `Edit in settings.json`
4. update the line that looks like this:
        `"omnisharp.path": ""`

**Comment by QVMaster** [comment]
I found the path:
C:\Users\[Your User Name]\.vscode\extensions\ms-dotnettools.csharp-[Version]\.omnisharp\[Version]

**Comment by ahmb** [comment]
Update vscode - settings.json : 

"omnisharp.path": "C:\\Users\\USERNAME\\.vscode\\extensions\\ms-dotnettools.csharp-1.24.0\\.omnisharp\\1.38.0\\Omnisharp.exe"

**Comment by snehalptl2626** [comment]
I am getting error command 'dotnet-test-explorer.openPanel' not found. I am getting such many error related to test explorer . So I am unable to see xunit tests in test explorer and not able to run them. I tried reinstalling omnisharp and test explorer extensions but it doesn't help.. Please suggest the solution for such issue.
