### ISSUE TITLE
VSCode No Symbols Loaded When Attaching to IIS Process

### ISSUE THREAD

**Issue by ToucanBran** [OmniSharp/omnisharp-vscode#2141]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

VS Code version: 1.21.1
C# Extension version: 1.14.0

## Steps to reproduce
- set <DebugType> in the .csproj to portable
- Using the following launch.json:
{
   // Use IntelliSense to find out which attributes exist for C# debugging
   // Use hover for the description of the existing attributes
   // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
   "version": "0.2.0",
   "configurations": [
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ,]
}

And attaching to an already running IIS process.

## Expected  behavior
Step through and debug c# as I would do in visual studio

## Actual behavior
All breakpoints show "Unverified breakpoint, No symbols have been loaded for this document." 

No output in the debug console once I attach to the process other than the normal 

-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------

**Comment by gregg-miskelly** [comment]
The debug console will show a line for every module loaded in the target process. Did symbols load for your module? 

NOTE: If symbols didn't load because you are using Windows PDBs, see https://github.com/OmniSharp/omnisharp-vscode/wiki/Portable-PDBs

**Comment by ToucanBran** [comment]
The debug console is blank except for the "You may only use the Microsoft .NET Core Debugger (vsdbg) with Visual Studio Code, Visual Studio or Visual Studio for Mac software to help you develop and test your applications." line.  I do have the DebugType set to portable though so why wouldn't it be trying to load them in? I can confirm the bin/debug directory _does_ have the pdb files in it...

**Comment by gregg-miskelly** [comment]
Is the app you are trying to debug a .NET Core app? Or a full-framework app?

If Full Framework - You need to change `type` in your launch.json. See https://github.com/OmniSharp/omnisharp-vscode/wiki/Desktop-.NET-Framework
If .NET Core - I am guessing you are attaching to the wrong process. You could have your code write out its process id somewhere so you can check.

**Comment by ToucanBran** [comment]
Yep, it was full framework and my type was coreclr. Once I changed it to clr, I was able to debug! Thanks!
