### ISSUE TITLE
Some intellisense tags still shown as XML

### ISSUE THREAD

**Issue by jeffschwMSFT** [OmniSharp/omnisharp-vscode#215]
![intellisense](https://cloud.githubusercontent.com/assets/9561583/14621225/2bc9098a-0576-11e6-838c-a9bc169ea07f.gif)

It seems that member level intelisense is displayed as XML, where as some of the top level type information is displayed in a more human readable format.

C# extension 1.0.3-rc2
Mac OS X

**Comment by DustinCampbell** [comment]
Dupe of #13
