### ISSUE TITLE
Omnisharp is not able to discover the project if it is not referenced in *.sln file

### ISSUE THREAD

**Issue by d-dizhevsky** [OmniSharp/omnisharp-vscode#2153]
## Environment data
```
.NET Command Line Tools (2.1.300-preview1-008174)

Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.300-preview1-008174/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153
```

VS Code version:
```VS Code version: 1.21.1```

C# Extension version:
```Extension version: 1.14.0```

## Steps to reproduce
In terminal do:
```
mkdir Source
cd Source
mkdir Included
cd Included
dotnet new classlib
cd ..
mkdir Excluded
cd Excluded
dotnet new classlib
cd ..
dotnet new sln 
dotnet sln add Included/Included.csproj
```
Now go to Excluded/Class1.cs and you will see that intellisense isn't showing up.
But if you go to Included/Class1.cs it works just fine.

----

[See the project tree I have here, similar to the one above](https://snag.gy/TwflH2.jpg)
Im my example Convert.Sample project is not referenced in DotNetConverter.sln and intellisense does not work for any *.cs file inside the project, *but* it works fine for others two (Core and Tests) since they are referenced in *.sln.

## Expected  behavior
I don't think it really works *as designed* and I expect the extension to work regardless to what projects are referenced in solution file. 

## Actual behavior
Extension does not work for the projects *excluded* from *.sln

**Comment by rchande** [comment]
@d-dizhevsky Omnisharp only loads one project/solution at at time. This means that if you load a solution, projects outside the solution are not loaded. To work around this, you can use the project selector button in the lower right corner to start OmniSharp for the other project. 
![image](https://user-images.githubusercontent.com/3751401/38259572-38d17d4c-371a-11e8-99f4-5f4199d90c7e.png)
