### ISSUE TITLE
When will 1.15 be released?

### ISSUE THREAD

**Issue by roterdam** [OmniSharp/omnisharp-vscode#2155]
Is there an ETA for release of 1.15?

**Comment by rchande** [comment]
@roterdam We haven't committed to a date yet. Is there a particular feature you're looking forward to that we haven't released in a beta? Note that the most recent beta was shipped 6 days ago (https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.15.0-beta4).

**Comment by roterdam** [comment]
I need the SourceLink support, and I keep updating betas from beta1 -> beta4 now :)

So looking forward to not having to update manually.

I guess is it months away? Days away? Weeks away?

**Comment by DustinCampbell** [comment]
As a policy, we don't discuss release dates. We try to ship a new official monthly release every month or two, but that's often dependent on whether there's enough critical mass to warrant a release. We're discussing this now.

**Comment by roterdam** [comment]
Thanks @DustinCampbell I get you don't want to share a date and then not make it, but for example it has almost 2 months and SourceLink is available in beta for a while so therefore I ask. Otherwise I don't ask.

**Comment by roterdam** [comment]
Any announcements to make?

**Comment by NinoFloris** [comment]
Also waiting, especially for launchSettings support (asp.net core 2.1 will also include launchSettings.json in templates by default)

**Comment by shanselman** [comment]
Are we not on 1.16.1, if so does it include SourceLink? If so, this can be closed.

**Comment by gregg-miskelly** [comment]
Yup, 1.16 is the current released version, and yes, SourceLink did ship in 1.15.
