### ISSUE TITLE
Cannot debug default/sample core console app

### ISSUE THREAD

**Issue by kvinther** [OmniSharp/omnisharp-vscode#2166]
## Environment data
`dotnet --info` output: 2.1.200-preview-007474
VS Code version: 1.221 (x64)
C# Extension version: 1.14.0

## Steps to reproduce
dotnew new console -n demo
dotnet restore
Create tasks.json and launch.json using templates
Set a breakpoint in Program.cs
Debug using .NET Core Launch (console)

## Expected  behavior
Debugger should start and my breakpoint in Program.cs should be hit.

## Actual behavior
I get the error: "command 'csharp.coreclrAdapterExecuteableCommand' not found.

![vscode-omnisharp-issue](https://user-images.githubusercontent.com/4615024/38522754-d56515fe-3c49-11e8-8116-8d61eeea0fa9.png)

## Observations and attempted resolution
* I was never able to trigger the automatic "add assests?" dialog.
![image](https://user-images.githubusercontent.com/4615024/38523022-9de5e760-3c4a-11e8-9996-172dcb6a24ef.png)
* Manually running the "Generate assesst" gave another error: command 'dotnet.generateAssets' not found.

* I have tried reinstalling vscode as well as the OmniSharp extension.
* I tried "Restart OmniSharp" but got yet another error:
![image](https://user-images.githubusercontent.com/4615024/38523397-a3aa6a44-3c4b-11e8-803a-9a9bfa18066c.png)

* I have tried enabling extended logging for OnmiSharp using https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging - but my package.json does not have those exact entries (newer version?), so I don't know where to put the arguments.

**Comment by kvinther** [comment]
Installing the beta/preview version solved this...

**Comment by gregg-miskelly** [comment]
It sounds like maybe you lost your repro, but - what OS are you on? If you can still repro, does the issue go away if you restart VS Code?

**Comment by kvinther** [comment]
I am on Win10 latest. Once I uninstalled and installed the latest "beta" as a VSIX (or what it was called). I noticed that after the manual install, it actually downloaded the debugger and one more package from MS. 

So for some reason, the download was not triggered with the 1.14.0 official release.

**Comment by gregg-miskelly** [comment]
What seems to have happened was that VS Code decided not to activate the C# extension after you initially installed 1.14, and hence none of the commands proffered from the C# extension were available. I have no idea why. If you want to try switching back to 1.14 we can try to help troubleshoot. My guess is that the problem will not repro, but I could certainly be wrong.

If you just want to keep with the beta for now, we could also just close this issue and you can come back if it ever happens again for you.

**Comment by kvinther** [comment]
Hi Gregg. Thanks for you response.

I agree with your assessment, that somehow the extension was not activated probably. I just tried installing the extension on my laptop, and the downloads started the moment I opened a .cs file.

I will keep with the beta for now, and I will close the issue.
