### ISSUE TITLE
C# output pane is always displayed with "omnisharp.path" is set to "latest"

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-vscode#2176]
I set my "omnisharp.path" to "latest" and found that this has the effect of popping the C# output every time I open VS Code, even when it doesn't need to update anything:

```
Getting latest build information...

Downloading package 'Latest version information file' (1 KB) .................... Done!
Installing Omnisharp Version = 1.29.2-beta.133...
Platform: win32, x86_64

Skipping package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.29.2-beta.133' (already downloaded).
Finished
```

It would be nice if the output pane was only shown if the extension needs to download a new OmniSharp.

**Comment by akshita31** [comment]
Seems we regressed this behavior during some of the refactorings.
