### ISSUE TITLE
Why is it still "Preview"?

### ISSUE THREAD

**Issue by Timothy-Liu** [OmniSharp/omnisharp-vscode#2182]
I'm new to VS Code and OmniSharp. I saw there is a red "Preview" tag in VS Code and the description "Welcome to the C# extension for Visual Studio Code! This preview provides the following features inside VS Code:" ...
May I ask a dummy question: if the version is already 1.14, why is it still preview?

Regards.

**Comment by gregg-miskelly** [comment]
Sorry for the delay in responding. We talked about this internally and we decided that there is no reason this extension should still be considered a "preview". For our next release (1.15), we will remove the preview branding.
