### ISSUE TITLE
Antergos Linux: OmniSharp.MSBuild.ProjectLoader  - Unable to create directory "/x86/Debug/"

### ISSUE THREAD

**Issue by heapifyman** [OmniSharp/omnisharp-vscode#2186]
## Environment data
```
.NET Command Line Tools (2.1.3)

Product Information:
 Version:            2.1.3
 Commit SHA-1 hash:  a0ca411ca5

Runtime Environment:
 OS Name:     antergos
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /opt/dotnet/sdk/2.1.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```
VS Code version: 
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Datum 2018-04-12T16:34:44.222Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64

C# Extension version: 1.14.0

## Steps to reproduce
Open legacy Visual Studio 2010 project .sln

## Expected  behavior
no error during project loading

## Actual behavior
Error message:
`Some projects have trouble loading. Please review the output for more details.`

Output shows:
```
Starting OmniSharp server at 2018-4-13 11:42:08
    Target: /home/heapifyman/projects/MyLegacyProject/MyLegacyProject.sln

OmniSharp server started wth Mono
    Path: /home/heapifyman/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/OmniSharp.exe
    PID: 27081

﻿[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on antergos 0.0 (x64)
[warn]: OmniSharp.MSBuild.Discovery.Providers.MonoInstanceProvider
        It looks like you have Mono 5.2.0 or greater installed but MSBuild could not be found.
Try installing MSBuild into Mono (e.g. 'sudo apt-get install msbuild') to enable better MSBuild support.
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "/home/heapifyman/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/heapifyman/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "/home/heapifyman/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin"
            MSBuildExtensionsPath = /usr/lib/mono/xbuild
            CscToolPath = /home/heapifyman/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/heapifyman/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin
            TargetFrameworkRootPath = /usr/lib/mono/xbuild-frameworks
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/heapifyman/projects/MyLegacyProject'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /home/heapifyman/projects/MyLegacyProject
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/heapifyman/projects/MyLegacyProject/MyLegacyProject.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/heapifyman/projects/MyLegacyProject/MyLegacyProject.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/heapifyman/projects/MyLegacyProject'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/heapifyman/projects/MyLegacyProject' on host 26989.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/heapifyman/projects/MyLegacyProject/MyLegacyProject.csproj
[warn]: OmniSharp.MSBuild.ProjectLoader
        Unable to create directory "/x86/Debug/". Access to the path "/x86" is denied.
[fail]: OmniSharp.MSBuild.ProjectLoader
        Could not write lines to file "/x86/Debug/MyLegacyProject.csproj.CoreCompileInputs.cache". Could not find a part of the path "/x86/Debug/MyLegacyProject.csproj.CoreCompileInputs.cache".
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/home/heapifyman/projects/MyLegacyProject/MyLegacyProject.csproj'.
/home/heapifyman/projects/MyLegacyProject/MyLegacyProject.csproj

```

**Comment by LungDrago** [comment]
I've had a similar problem on Solus. As the error suggests, I fixed it by resetting file permissions on the entire project folder and its files and subfolders. Is this really an Omnisharp issue?

**Comment by DustinCampbell** [comment]
Antergos is based on Arch, yes? If so, try installing newer Mono and MSBuild packages:

* https://aur.archlinux.org/packages/mono-stable/
* https://aur.archlinux.org/packages/msbuild-stable/

**Comment by heapifyman** [comment]
@LungDrago I think my project folder permissions are correct. My user is the owner and has write access. I don't know what else would be needed.

The problem seems to be the following line from omnisharp's output above:
`[warn]: OmniSharp.MSBuild.ProjectLoader
        Unable to create directory "/x86/Debug/". Access to the path "/x86" is denied.`

It seems to try to create the directory "x86" in the system's root directory, not inside the project directory.

For a test I created the directory "/x86" and gave myself write permissions. And in fact, afterwards, I don't get any more errors in omnisharp's output.

**Comment by heapifyman** [comment]
@DustinCampbell I tried your suggestion and installed "msbuild-stable" and that seems to solve the problem. The directory "x86" is now created inside "PROJECT_DIR/obj" directory.

However, I was under the impression that having dotnet-core and visual studio code plus extension "C# for Visual Studio Code (powered by OmniSharp)." installed would be sufficient to open a simple c# command line application under linux.

Maybe omnisharp bundled with the c# extension is outdated (it says version 15.0, though) and needs to be updated?

**Comment by DustinCampbell** [comment]
@heapifyman: Depending on the project, it can be an issue of the correct MSBuild toolset not being available. C# for VS Code does not include a full MSBuild toolset that supports any project, just a fallback that works for some (notably .NET Core) projects. So, when it is installed on a system that includes an MSBuild toolset it will try and use it. In your case, it found a version of Mono that contained an older XBuild, which is often compatible enough. So, it tried setting a handful of MSBuild properties to XBuild paths within your Mono install:

```
Registered MSBuild instance: StandAlone 15.0 - "/home/heapifyman/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin"
            MSBuildExtensionsPath = /usr/lib/mono/xbuild
            CscToolPath = /home/heapifyman/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/heapifyman/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin
            TargetFrameworkRootPath = /usr/lib/mono/xbuild-frameworks
```

This works on many distros, but it doesn't work on Arch for some reason. The solution is just to install a proper MSBuild toolset and everything should work.

**Comment by heapifyman** [comment]
@DustinCampbell ok. thanks for the explanation.
