### ISSUE TITLE
already exists class file,create new class file  no warning

### ISSUE THREAD

**Issue by fjqingyou** [OmniSharp/omnisharp-vscode#2190]
already exists class file,create it file no warning, vscode erase original class code file.  data lost

## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

**Comment by DustinCampbell** [comment]
Hi! Without clearer repro steps and some basic information like your VS Code and C# extension version, it's difficult to understand the issue you're reporting. Do you have more details that could help us better help you?
