### ISSUE TITLE
The type or namespace 'MySql' could not be found

### ISSUE THREAD

**Issue by KirkBushman** [OmniSharp/omnisharp-vscode#2196]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     fedora
 OS Version:  27
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /opt/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```
VS Code version:
1.22.1
950b8b0d37a9b7061b6f0d291837ccc4015f5ecd
x64
C# Extension version: 1.14.0

## Steps to reproduce
I didn't create the project, I cloned it from our repo, 
open the project, ton of errors in the console.

Intellisense gives an error to every external dependency I have, but doing `dotnet build` is ok.

## Expected  behavior
no errors in the console

Log: 
```
Starting OmniSharp server at 4/16/2018, 12:43:56 PM
    Target: /home/pcluca/Desktop/HynetProjects/NMSplus2

OmniSharp server started wth Mono
    Path: /home/pcluca/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/run
    PID: 26535

﻿[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on fedora 27.0 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "/home/pcluca/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/pcluca/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "/home/pcluca/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin"
            MSBuildExtensionsPath = /home/pcluca/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild
            CscToolPath = /home/pcluca/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/pcluca/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin
            TargetFrameworkRootPath = /usr/lib/mono/xbuild-frameworks
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/pcluca/Desktop/HynetProjects/NMSplus2'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /home/pcluca/Desktop/HynetProjects/NMSplus2
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/pcluca/Desktop/HynetProjects/NMSplus2'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/pcluca/Desktop/HynetProjects/NMSplus2/Hynet.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/pcluca/Desktop/HynetProjects/NMSplus2'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/pcluca/Desktop/HynetProjects/NMSplus2' on host 13703.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/pcluca/Desktop/HynetProjects/NMSplus2/Hynet.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/pcluca/Desktop/HynetProjects/NMSplus2/Hynet.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Hynet
```

**Comment by rchande** [comment]
@KirkBushman Can you try the steps outlined here: https://github.com/OmniSharp/omnisharp-vscode/issues/2147#issuecomment-380171885 and post your OmniSharp log?

**Comment by KirkBushman** [comment]
i see this: 

Starting OmniSharp server at 4/18/2018, 9:43:00 AM
    Target: /home/pcluca/Desktop/HynetProjects/NMSplus3

OmniSharp server started with Mono
    Path: /home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/run
    PID: 5316

﻿[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on fedora 27.0 (x64)
[dbug]: OmniSharp.MSBuild.Discovery.Providers.MonoInstanceProvider
        Can't use installed Mono because OmniSharp isn't running on it
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "/home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild/15.0/Bin"
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Resolved 'Microsoft.Build.Utilities.Core' to '/home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild/15.0/Bin/Microsoft.Build.Utilities.Core.dll'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Resolved 'Microsoft.Build.Tasks.Core' to '/home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild/15.0/Bin/Microsoft.Build.Tasks.Core.dll'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Resolved 'Microsoft.Build.Framework' to '/home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild/15.0/Bin/Microsoft.Build.Framework.dll'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Resolved 'Microsoft.Build' to '/home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild/15.0/Bin/Microsoft.Build.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild/15.0/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "/home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild/15.0/Bin"
            MSBuildExtensionsPath = /home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild
            BypassFrameworkInstallChecks = true
            CscToolPath = /home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild/15.0/Bin
            TargetFrameworkRootPath = /usr/lib/mono/xbuild-frameworks
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.CodeAnalysis.VisualBasic.Workspaces, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.CodeAnalysis.VisualBasic.Features, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/pcluca/Desktop/HynetProjects/NMSplus3'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /home/pcluca/Desktop/HynetProjects/NMSplus3
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[dbug]: OmniSharp.MSBuild.ProjectSystem
        MSBuild environment: 
Mode: Standalone
RunningTests: False
RunningInVisualStudio: False
MSBuildToolsDirectory32: /home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild/15.0/Bin
MSBuildToolsDirectory64: /home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild/15.0/Bin
MSBuildSDKsPath: /home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild/15.0/Bin/Sdks
CurrentMSBuildConfigurationFile: /home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild/15.0/Bin/MSBuild.dll.config
CurrentMSBuildExePath: /home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild/15.0/Bin/MSBuild.dll
CurrentMSBuildToolsDirectory: /home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild/15.0/Bin
VisualStudioInstallRootDirectory: 
MSBuildExtensionsPath: /home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild/15.0/Bin

[dbug]: OmniSharp.MSBuild.ProjectLoader
        'MSBuildExtensionsPath' set to '/home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild'
[dbug]: OmniSharp.MSBuild.ProjectLoader
        'TargetFrameworkRootPath' set to '/usr/lib/mono/xbuild-frameworks'
[dbug]: OmniSharp.MSBuild.ProjectLoader
        'CscToolPath' set to '/home/pcluca/.vscode/extensions/ms-vscode.csharp-1.15.0-beta4/.omnisharp/experimental/1.29.2-beta.161/omnisharp/msbuild/15.0/Bin/Roslyn'
[dbug]: OmniSharp.MSBuild.ProjectLoader
        'CscToolExe' set to 'csc.exe'
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/pcluca/Desktop/HynetProjects/NMSplus3'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/pcluca/Desktop/HynetProjects/NMSplus3/Hynet.csproj'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/pcluca/Desktop/HynetProjects/NMSplus3'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/pcluca/Desktop/HynetProjects/NMSplus3' on host 4451.
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 51,
  "Command": "/projects"
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 52,
  "Command": "/projects"
}
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/pcluca/Desktop/HynetProjects/NMSplus3/Hynet.csproj
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/home/pcluca/Desktop/HynetProjects/NMSplus3/Hynet.csproj'.
/home/pcluca/Desktop/HynetProjects/NMSplus3/Hynet.csproj(1,1)
System.TypeLoadException: Could not load type of field 'Microsoft.Build.BackEnd.Logging.LoggingService:_loggingQueue' (21) due to: Could not load file or assembly 'System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. assembly:System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:<unknown type> member:(null) signature:<none>
  at Microsoft.Build.Evaluation.ProjectCollection..ctor (System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties, System.Collections.Generic.IEnumerable`1[T] loggers, System.Collections.Generic.IEnumerable`1[T] remoteLoggers, Microsoft.Build.Evaluation.ToolsetDefinitionLocations toolsetDefinitionLocations, System.Int32 maxNodeCount, System.Boolean onlyLogCriticalEvents) [0x00112] in <61115f75067146fab35b10183e6ee379>:0 
  at Microsoft.Build.Evaluation.ProjectCollection..ctor (System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties, System.Collections.Generic.IEnumerable`1[T] loggers, Microsoft.Build.Evaluation.ToolsetDefinitionLocations toolsetDefinitionLocations) [0x00000] in <61115f75067146fab35b10183e6ee379>:0 
  at Microsoft.Build.Evaluation.ProjectCollection..ctor (System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties) [0x00000] in <61115f75067146fab35b10183e6ee379>:0 
  at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore (System.String filePath) [0x00000] in <1fe1031fc6d04e0f9d03bcda71349a9d>:0 
  at OmniSharp.MSBuild.ProjectLoader.BuildProject (System.String filePath) [0x0000d] in <1fe1031fc6d04e0f9d03bcda71349a9d>:0 
  at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load (System.String filePath, OmniSharp.MSBuild.ProjectLoader loader) [0x00014] in <1fe1031fc6d04e0f9d03bcda71349a9d>:0 
  at OmniSharp.MSBuild.ProjectManager+<>c__DisplayClass23_0.<LoadProject>b__0 () [0x00000] in <1fe1031fc6d04e0f9d03bcda71349a9d>:0 
  at (wrapper delegate-invoke) System.Func`1[System.ValueTuple`2[OmniSharp.MSBuild.ProjectFile.ProjectFileInfo,System.Collections.Immutable.ImmutableArray`1[OmniSharp.MSBuild.Logging.MSBuildDiagnostic]]].invoke_TResult()
  at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject (System.String projectFilePath, System.Func`1[TResult] loadFunc) [0x0001b] in <1fe1031fc6d04e0f9d03bcda71349a9d>:0 

[dbug]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 51,
  "Command": "/projects",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "Cake": {
      "Projects": []
    },
    "DotNet": {
      "Projects": [],
      "RuntimePath": null
    },
    "MsBuild": {
      "SolutionPath": "/home/pcluca/Desktop/HynetProjects/NMSplus3",
      "Projects": []
    },
    "Script": {
      "Projects": []
    }
  },
  "Seq": 34,
  "Type": "response"
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 52,
  "Command": "/projects",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "Cake": {
      "Projects": []
    },
    "DotNet": {
      "Projects": [],
      "RuntimePath": null
    },
    "MsBuild": {
      "SolutionPath": "/home/pcluca/Desktop/HynetProjects/NMSplus3",
      "Projects": []
    },
    "Script": {
      "Projects": []
    }
  },
  "Seq": 35,
  "Type": "response"
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 53,
  "Command": "/projects"
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 53,
  "Command": "/projects",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "Cake": {
      "Projects": []
    },
    "DotNet": {
      "Projects": [],
      "RuntimePath": null
    },
    "MsBuild": {
      "SolutionPath": "/home/pcluca/Desktop/HynetProjects/NMSplus3",
      "Projects": []
    },
    "Script": {
      "Projects": []
    }
  },
  "Seq": 44,
  "Type": "response"
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 54,
  "Command": "/v2/getcodeactions",
  "Arguments": {
    "FileName": "/home/pcluca/Desktop/HynetProjects/NMSplus3/src/managers/DbManager.cs",
    "Line": 28,
    "Column": 54
  }
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 55,
  "Command": "/currentfilemembersastree",
  "Arguments": {
    "FileName": "/home/pcluca/Desktop/HynetProjects/NMSplus3/src/managers/DbManager.cs"
  }
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 55,
  "Command": "/currentfilemembersastree",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "TopLevelTypeDefinitions": []
  },
  "Seq": 49,
  "Type": "response"
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 56,
  "Command": "/codecheck",
  "Arguments": {
    "FileName": "/home/pcluca/Desktop/HynetProjects/NMSplus3/src/managers/DbManager.cs"
  }
}
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.CodeAnalysis.Workspaces.resources, Version=2.7.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.CodeAnalysis.Workspaces.resources, Version=2.7.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.CodeAnalysis.Features.resources, Version=2.7.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.CodeAnalysis.Features.resources, Version=2.7.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35'
[dbug]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 54,
  "Command": "/v2/getcodeactions",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "CodeActions": []
  },
  "Seq": 48,
  "Type": "response"
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 56,
  "Command": "/codecheck",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "QuickFixes": []
  },
  "Seq": 52,
  "Type": "response"
}

**Comment by rchande** [comment]
@DustinCampbell Looks like MSBuild is failing to load some of its own dependencies. Is this a mono issues? 

> System.TypeLoadException: Could not load type of field 'Microsoft.Build.BackEnd.Logging.LoggingService:_loggingQueue' (21) due to: Could not load file or assembly 'System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. assembly:System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:<unknown type> member:(null) signature:<none>

**Comment by DustinCampbell** [comment]
No idea. :smile:

That particular assembly is included in both our embedded Mono (which this appears to be running on) and OmniSharp itself.

@KirkBushman: If you run `mono --version` at the command line, what do you get?

**Comment by KirkBushman** [comment]
Just notifying that updating to dotnet 2.1 preview rc1 solved the issue.

**Comment by DustinCampbell** [comment]
FWIW, this was fixed in the latest release of C# for VS Code as well. It looks like we forgot to circle back here as well. The problem was fixed with https://github.com/OmniSharp/omnisharp-roslyn/pull/1173.
