### ISSUE TITLE
[Question] [Install support needed] VS Code as SharpDevelop replacement

### ISSUE THREAD

**Issue by hellboy81** [OmniSharp/omnisharp-vscode#2201]
At the moment I am using SharpDevelop based IDE and I am trying to make my developer experience better. 

Due on some internal restrictions I have trouble with installation and setup:

- Only  `.NET Framework 4.6` target is required. No additional .NET Core should be installed
- Portable installation required. No files should be added to `AppData\Roaming`. No admin rights required.
- Seamless integration with NuGet. Installed NuGet  packages can be added to solution with GUI
- ...

**Comment by DustinCampbell** [comment]
What, exactly, is your question?

**Comment by hellboy81** [comment]
- I Think it  should help  [to install VS Code with C# without admin rights and behind firewall](https://www.codeproject.com/Tips/1209935/WebControls/),

I am still don't understand if Omnisharp philosophy allowed to use legacy .NET 4.6.x . "Use" means:

- No installed .NET Core  required 
- Can support VS 2010 solutions and build for .NET 4.6

**Comment by DustinCampbell** [comment]
Again, I'm not seeing a specific question here. C# for VS Code does not require admin rights.

**Comment by hellboy81** [comment]
I got it. As I mentioned [portable installation is still not supported](https://github.com/Microsoft/vscode/issues/329)

**Comment by DustinCampbell** [comment]
Sure, but that's a VS Code issue. There is no question here for the C# for VS Code extension.

In the future, if you have a question, please ask it and we'll do our best to answer.
