### ISSUE TITLE
C# Interface Colorizing

### ISSUE THREAD

**Issue by spraycanmansam** [OmniSharp/omnisharp-vscode#2203]
Hi guys,
Just noticed when trying to customize my VS Code theme colors that inherited interfaces don't colorize properly. I'm not sure if I'm missing a specific scope that I can define but it seems like the actual scope isn't specific enough on the inherited interface...

VS Code version:
1.22.2

C# Extension version:
1.14.0

## Steps to reproduce
Inherit any class from an interface.

## Expected  behavior
Inherited interface should be colorized uniquely according to theme colors.

## Actual behavior
Inherited interface is colorized as a general type.

![image](https://user-images.githubusercontent.com/22257783/38976995-52516e24-43f6-11e8-979e-13de41daa76c.png)

![image](https://user-images.githubusercontent.com/22257783/38977129-c245cb3a-43f6-11e8-9dbf-7d17f682aa64.png)

![image](https://user-images.githubusercontent.com/22257783/38977135-c8ca280c-43f6-11e8-8a26-27d61c245a9e.png)

**Comment by DustinCampbell** [comment]
Unfortunately VS Code, only allows system highlighting via TextMate grammars with regular expressions. Within a regular expression, it's just not possible to know whether an identifier reference represents an interface type or not. There is an issue open on VS Code (https://github.com/Microsoft/vscode/issues/585) to provide an API that would allow us to provide better highlights using semantic information.

**Comment by feafarot** [comment]
I want to check on this issue since VSCode team has released semantic color tokenization support recently.
https://github.com/microsoft/vscode/issues/86415

**Comment by bamancio-futura** [comment]
This issue should be reopened after the changes in https://github.com/microsoft/vscode/issues/86415
