### ISSUE TITLE
Update readme for omnisharp-roslyn

### ISSUE THREAD

**Issue by akshita31** [OmniSharp/omnisharp-vscode#2204]
We could update the readme here - https://github.com/OmniSharp/omnisharp-roslyn#using-the-latest-omnisharp-roslyn-with-vs-code  to add the "latest" option that we implemented.

Thoughts @rchande @TheRealPiotrP

**Comment by DustinCampbell** [comment]
Personally, I think that's worth documenting on the readme.

**Comment by akshita31** [comment]
I just realized that we haven't shipped a release which contains this option. I think we should update the readme once we have shipped one.
