### ISSUE TITLE
VS Code highlighting an error due to dependency 'downgrade' where dotnet-cli does not

### ISSUE THREAD

**Issue by jeffschwMSFT** [OmniSharp/omnisharp-vscode#221]
<img width="742" alt="screen shot 2016-04-19 at 11 17 26 am" src="https://cloud.githubusercontent.com/assets/9561583/14650368/5daefb3a-0620-11e6-93cb-424db98f479c.png">

Using the following Windows Azure blob storage APIs in a .NET Core app is showing a difference in build errors between VS Code and dotnet-cli:

Task&lt;BlobResultSegment> segtask = dir.ListBlobsSegmentedAsync(token);
Task&lt;Stream> opentask = blob.OpenReadAsync();

VS Code is highlighting an error about a dependency downgrade.

C# extension 1.0.3-rc2
dotnet --info
.NET Command Line Tools (1.0.0-rc2-002394)

Product Information:
 Version:     1.0.0-rc2-002394
 Commit Sha:  3a423b1080

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
[azurestorage.tar.gz](https://github.com/OmniSharp/omnisharp-vscode/files/226557/azurestorage.tar.gz)

**Comment by DustinCampbell** [comment]
This was due to NoWarn not being handled correctly, which should no longer be the case.
