### ISSUE TITLE
Debugger: Run to Cursor to invalid line, a Column Breakpoint appears on the next line.

### ISSUE THREAD

**Issue by WangNanN** [OmniSharp/omnisharp-vscode#2211]
## Environment data
`dotnet --info` output:

OS Name: Windows
OS Version: Win 10 RS4 ENU x64
Machine Name: [TEN10281](http://maddog/goto/MDGoto.Application?md://OrcasTS/Machine/579705)
Run ID: [5431588](http://maddog/goto/MDGoto.Application?md://OrcasTS/Run/5431588)

VS Code version: v1.22.2
C# Extension version: 1.15.0-beta5

## Steps to reproduce
1. Execute the following command to create a dotnet project
    dotnet new console -o hwapp
    cd hwapp
    dotnet restore
    dotnet run
2. Open web project in vscode.
3. Add below code in Program.cs
```
using System;

namespace hwapp
{
    class Program
    {
        static void Main()
        {
            int a=1; // *L1: Add a breakpoint;
            int b=2;
            int c=a+b;
            // *L2: Run to cursor to this line.
            if (c==3)
            {
                hello();
Console.WriteLine(" World!");
            }
            
        }
        static void hello()
        {
            for(int i=1;i<5;i++)
            {
Console.WriteLine("hello");
        }

        }
    }
}

```
4. Add breakpoint on line L1.
5. Run to cursor to line L2.

## Expected  behavior
No breakpoints appear.

## Actual behavior
A Column breakpoint appeared and the program breaks at this column breakpoint.

**Comment by chuckries** [comment]
This appears to also repro against the 1.14.0 version of the extension, meaning it is not a regression based on the .NET Core 2.1 work. I will investigate further to determine if this is a VS Code issue or a real debugger bug.

**Comment by chuckries** [comment]
Moved this issue to https://github.com/Microsoft/vscode/issues/48586.
