### ISSUE TITLE
Debugger:[Unstable]Debugger will show threads as 'Running' when they are paused on breakpoint

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#2213]
## Environment data
`dotnet --info` output:
![image](https://user-images.githubusercontent.com/20184778/39172318-fbc8fea0-47d3-11e8-87ba-3e4f69bd3687.png)
VS Code version: 1.22.2
C# Extension version: 1.15.0-beta5

## Steps to reproduce

1. Download and open attachment in VSCode: [Thread.zip](https://github.com/OmniSharp/omnisharp-vscode/files/1941406/Thread.zip)
2. Set a breakpoint at line of 34 in Program.cs
3. F5
4. Verify the work thread in Call Stack window

## Expected  behavior
All threads are listed as 'Paused'.

## Actual behavior
Sometimes, a few threads are ‘Running’.
![image](https://user-images.githubusercontent.com/20184778/39172795-6831290e-47d5-11e8-92db-3b6fd18fdf2a.png)

## Log
[log.txt](https://github.com/OmniSharp/omnisharp-vscode/files/1941624/log.txt)

**Comment by chuckries** [comment]
This repros in the 1.14.0 version of the extension and is not a regression due to the .NET Core 2.1 work.

**Comment by chuckries** [comment]
My guess is the threads are not running, but are in some initialization state and have not started running yet. We are just displaying this wrong. Adding a Thread.Sleep(2000) before the breakpoint causes this issue to go away.

**Comment by chuckries** [comment]
This appears to be a VS Code issue. I have logged https://github.com/Microsoft/vscode/issues/48600
