### ISSUE TITLE
Properties and Types inconsistently being colored

### ISSUE THREAD

**Issue by jeffschwMSFT** [OmniSharp/omnisharp-vscode#222]
<img width="487" alt="screen shot 2016-04-19 at 1 47 39 pm" src="https://cloud.githubusercontent.com/assets/9561583/14655040/58d8e8c2-0635-11e6-9795-92029c3d2e27.png">

DateTime should be 'blue-ish' and LastSyncDate should be 'yellow'

<img width="338" alt="screen shot 2016-04-19 at 1 48 48 pm" src="https://cloud.githubusercontent.com/assets/9561583/14655065/78f61544-0635-11e6-9ece-0343a3e4cbc9.png">

DateTime should be 'bluefish'

C# Extension 1.0.3-rc2
[colors.tar.gz](https://github.com/OmniSharp/omnisharp-vscode/files/226804/colors.tar.gz)

**Comment by vukovinski** [comment]
Colorizing also breaks down when using type parameters in generics. 
![capture](https://cloud.githubusercontent.com/assets/5647426/14847260/f73364c4-0c67-11e6-87a8-ec6e7c51271a.PNG)

**Comment by ivanz** [comment]
First and last screenshots are already fixed and the one about colouring variable type in variable assignment is effectively #687, so I suggest closing this issue

**Comment by DustinCampbell** [comment]
Yes, this should be much better with the [latest beta](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.4.0-beta8)
