### ISSUE TITLE
warning level

### ISSUE THREAD

**Issue by rakkarage** [OmniSharp/omnisharp-vscode#2224]
![2018-04-26 2](https://user-images.githubusercontent.com/962340/39317846-96100c20-494a-11e8-802b-99a21f9e4c6b.png)

is there a way to change warning levels?
i get a warning that x is not used but no warning that i is not used?
thanks

**Comment by rchande** [comment]
@rakkarage You can use `pragma warning disable` directives to suppress warnings that you don't want to see, as described [here](https://stackoverflow.com/questions/3820985/suppressing-is-never-used-and-is-never-assigned-to-warnings-in-c-sharp). For questions about the C# compiler behavior, I recommend that you file issues on https://github.com/dotnet/roslyn.
