### ISSUE TITLE
Create & Initialize Field Shortcut Doesn't Respect .editorconfig

### ISSUE THREAD

**Issue by mattheworres** [OmniSharp/omnisharp-vscode#2228]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.3)

Product Information:
 Version:            2.1.3
 Commit SHA-1 hash:  a0ca411ca5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff
VS Code version: 1.22.2
C# Extension version: 1.14.0

## Steps to reproduce

1. In a class constructor, introduce a new parameter in the constructor:
```
public class MyClass {
  public MyClass(string item) {}
}
```
2. In your `.editorconfig` file, ensure these settings are present:
```
[*.cs]
dotnet_naming_rule.private_members_with_underscore.symbols  = private_fields
dotnet_naming_rule.private_members_with_underscore.style    = prefix_underscore
dotnet_naming_rule.private_members_with_underscore.severity = suggestion
dotnet_naming_symbols.private_fields.applicable_kinds           = field
dotnet_naming_symbols.private_fields.applicable_accessibilities = private
dotnet_naming_style.prefix_underscore.capitalization = camel_case
dotnet_naming_style.prefix_underscore.required_prefix = _
```
3. Place cursor on `item`, then perform Intellisense shortcut (on Mac it's `CMD`+ `.`), select `Create & Initialize field 'item'`.

## Expected  behavior
Omnisharp will introduce a private member `_item` and assign it within the constructor body.

## Actual behavior
Omnisharp introduces a private member named `item` and assigns it using the `this.item = item` syntax.

I'm following along with [this bug thread on the Roslyn repo](https://github.com/dotnet/roslyn/issues/22884) as it's the closest thing I can find to describe what I'm looking for. Looked but saw no appropriate VSCode settings that I can flip on.

**Comment by DustinCampbell** [comment]
Today, C# for VS Code doesn't support editorconfig at all. We're tracking that issue with https://github.com/OmniSharp/omnisharp-vscode/issues/1726.

**Comment by paladin2005** [comment]
With the new version of omnisharp and c# extension for VSCode now you can do it... I just checked and I am very happy.
Just change:
`"omnisharp.enableEditorConfigSupport": true`
Create a .editorconfig file with:
```
[*.{cs,vb}]
dotnet_naming_rule.private_members_with_underscore.symbols  = private_fields
dotnet_naming_rule.private_members_with_underscore.style    = prefix_underscore
dotnet_naming_rule.private_members_with_underscore.severity = suggestion

dotnet_naming_symbols.private_fields.applicable_kinds           = field
dotnet_naming_symbols.private_fields.applicable_accessibilities = private

dotnet_naming_style.prefix_underscore.capitalization = camel_case
dotnet_naming_style.prefix_underscore.required_prefix = _
```

and then install the editorfile extension in vscode to force to load the file.
That's it.
Good luck.

**Comment by mattheworres** [comment]
I'm not seeing this behavior using VSCode 1.36.1 and the EditorConfig for VS Code extension (`editorconfig.editorconfig`) version 0.13.0

**Comment by paladin2005** [comment]
Check the filename, is not "editorconfig.editorconfig", just ".editorconfig" and place it in the root of your project folder.
Is working for me (macOS)
