### ISSUE TITLE
Debugger unusable on airgapped (zero internet) computer with fresh VSCode+extension install

### ISSUE THREAD

**Issue by ciaphas01** [OmniSharp/omnisharp-vscode#2258]
I downloaded VSCode today to try operating the C# debugger on some code I have on a computer that's off the grid. I manually downloaded the omnisharrp-vscode vsix extension and installed it, only to find that the debugger and related tools for my platform do not come with it! Instead, according to the README,

4: Wait for download of platform-specific files
The first time that C# code is opened in VS Code, the extension will download the platform-specific files needed for debugging and editing. Debugging and editor features will not work until these steps finish.

I see the file it is attempting to download in the log, but what steps can I follow to get the extension to use that downloaded copy to complete its setup?

**Comment by gregg-miskelly** [comment]
Here are the instructions: https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-the-C%23-extension-to-a-computer-without-internet-connectivity

**Comment by ciaphas01** [comment]
Thanks, and apologies for the spam. I discovered that literally moments after I submitted this issue. :(
