### ISSUE TITLE
Unable to locate MSBuild in C:\Windows\Microsoft.NET\Framework\v4.0.30319

### ISSUE THREAD

**Issue by hellboy81** [OmniSharp/omnisharp-vscode#2260]
Is there possible to use MSBuild for .NET 4.0 from OmniSharp VSCode to build .NET 4.6 projects?

**Comment by DustinCampbell** [comment]
No. OmniSharp requires MSBuild 15.1. Also, not that OmniSharp does ship with a version of the MSBuild engine that it will use if it can't find one. However, the tasks/targets for compiling a .NET 4.6 project must be available for it to use.

On Windows, you should be able to install the Visual Studio 2017 Build Tools with the appropriate workloads and OmniSharp will use it.
