### ISSUE TITLE
[ERROR]: C# Extension failed to install the debugger package

### ISSUE THREAD

**Issue by RandallFlagg** [OmniSharp/omnisharp-vscode#2265]
## Environment data
`dotnet --info` output:

> .NET Command Line Tools (2.1.4)
> 
> Product Information:
>  Version:            2.1.4
>  Commit SHA-1 hash:  5e8add2190
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.15063
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   E:\Programs\dotnetCore\current\sdk\2.1.4\
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.5
>   Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

VS Code version: 1.22.2
C# Extension version:
1.14.0

## Additional Info
Read the following links:
https://github.com/OmniSharp/omnisharp-vscode/issues/991
https://github.com/OmniSharp/omnisharp-vscode/issues/994
https://github.com/OmniSharp/omnisharp-vscode/issues/1712
https://github.com/dotnet/core/issues/767

The following error shows in devtools:
https://github.com/OmniSharp/omnisharp-vscode/blob/7f128dae95e3281cd49502ed095fbed53a83d6e9/src/coreclr-debug/activate.ts#L79

There should be a normal error indicating what the problem is and maybe even manual steps to fix this.
This happened to me on a few system by now. Every time fixed by luck.
I have removed the extension and reinstalled.
I removed VSCode and reinstalled.
Nothing helped.

## Steps to reproduce
Install the C# extension

## Expected  behavior
Show the steps while installing the extension

## Actual behavior
The following error is shown in the console:
[ERROR]: C# Extension failed to install the debugger package

**Comment by RandallFlagg** [comment]
This directory doesn't exists:
"%userprofile%\.vscode\extensions\ms-vscode.csharp-1.14.0\.debugger

**Comment by gregg-miskelly** [comment]
That is definitely why you are seeing this error. Now we need to try and figure out how we got into this state. 

If you delete install.Lock and restart VSCode, does the problem happen again? If so, do you get any other logging from the C# extension?

**Comment by gregg-miskelly** [comment]
@RandallFlagg are you still seeing this problem? Would you like help, or should I close this?

**Comment by ptian** [comment]
I have the same issue. I don't have the .debugger directory in  "%userprofile%\.vscode\extensions\ms-vscode.csharp-1.15.2" and install.lock does not exist in "%userprofile%\.vscode\extensions\ms-vscode.csharp-1.15.2".

**Comment by tiomke** [comment]
I have the same issue on OS X 10.11.6

**Comment by RandallFlagg** [comment]
@gregg-miskelly sorry for the delay. I have found the reasons for this. It happens on 2 different setups I have.

1. VSCode settings are not in the default location
2. VSCode settings are behind a symlink. (default location that points to somewhere else)

Can you confirm?

@ptian @tiomke is one of those your setup by any chance?

**Comment by ptian** [comment]
My vscode is installed in "C:\Program Files\Microsoft VS Code" but the settings.json is in C:\Users\<user ID>\AppData\Roaming\Code\User. How do I correct it? Thanks.

**Comment by jgfoster** [comment]
I have this issue on macOS 10.14.3, Visual Studio Code 1.31.1, C# extension version 1.17.1.

**Comment by akshita31** [comment]
@jgfoster The [beta version](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.18.0-beta8) contains some download validation and might fix the problem. You can install it by following the instructions [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases). Please let us know if this fixed the issue.

**Comment by jgfoster** [comment]
@akshita31, I no longer get an error installing the 1.18.0-beta10. Thanks!

**Comment by akshita31** [comment]
This issue is fixed in the latest beta(1.18.0-beta10) and the corresponding release(1.18.0) which is scheduled  next week. I will close this issue now.
