### ISSUE TITLE
Run tests doesn't provide any output

### ISSUE THREAD

**Issue by david-waterworth** [OmniSharp/omnisharp-vscode#2268]
We've been using mstest which works fine sa per [https://github.com/OmniSharp/omnisharp-vscode/wiki/How-to-run-and-debug-unit-tests]. However the output from the test doesn't appear to go to the terminal window. 

i.e. when I run a test all I see is

```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:13.84



Total tests: 1. Passed: 0. Failed: 1. Skipped: 0
```

If I run from from console i.e. `>dotnet test` then messages from the failed tests appear in the terminal window (and log messages as we have a console logger configured for our tests, i.e. 

```
Starting test execution, please wait...
Failed   TestReports
Error Message:
 Assert.IsNull failed. items is not null

...

Total tests: 3. Passed: 2. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 3.1644 Seconds
```

Is there a way of capturing this output when running using the code lense links?

Regards
Dave

**Comment by rchande** [comment]
It looks like O# returns the output of individual unit tests but the C# extension doesn't print the output.
@david-waterworth Thanks for filing this, we will take a look.

**Comment by rchande** [comment]
After further investigation, I'm not sure O# is actually sending along all the output.

**Comment by akshita31** [comment]
@rchande I have added some more logging around the tests in the PR: https://github.com/OmniSharp/omnisharp-vscode/pull/2337. We do need some more information from omnisharp and I have filed an issue here : https://github.com/OmniSharp/omnisharp-roslyn/issues/1198

**Comment by rchande** [comment]
@akshita31 Do we have a way to get console output produced by unit tests?

**Comment by akshita31** [comment]
@rchande I created a PR to imnisharp-roslyn to do so: https://github.com/OmniSharp/omnisharp-roslyn/pull/1203
