### ISSUE TITLE
Warning message about project.json makes it impossible to use VSCode

### ISSUE THREAD

**Issue by AlexanderSher** [OmniSharp/omnisharp-vscode#2275]
VSCode version 1.23.0, Plugin version 1.14.0
Warnings continuously pop up and can't be suspended, UI is almost paralyzed.

**Comment by akshita31** [comment]
@AlexanderSher We have recently added a the option to suppress the project.json warning using the option `csharp.suppressProjectJsonWarning`. It is included in the latest beta. Please follow these [instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases), to install the latest beta version.

**Comment by akshita31** [comment]
@AlexanderSher Did that work ?

**Comment by DustinCampbell** [comment]
FWIW, we just release 1.15 of C# for VS Code. So, if you update your extension, it should work for you.

I should also mention that project.json is officially deprecated. There may be some older tooling that still uses it, but support for project.json will be removed in the future.

This request is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1920.

**Comment by AlexanderSher** [comment]
Yep, parameter is working, thank you!

Since I'm using VSCode only for editing (mostly csproj files), I don't care about `project.json` support.
