### ISSUE TITLE
Using Resources.resx file failing but not on Visual Studio 2017 or Visual Studio for Mac

### ISSUE THREAD

**Issue by Jonatthu** [OmniSharp/omnisharp-vscode#2278]
## Environment data
dotnet --info
.NET Command Line Tools (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.200\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

## Steps to reproduce
Using a Resources.resx and a generated manager of this file, fails on finding or parsing the failing

```
Stream stream = new MemoryStream(Properties.Resources.createproject);
StreamReader reader = new StreamReader(stream);
string text = reader.ReadToEnd();
```

## Expected  behavior
To successfully execute the code before as Visual Studio 2017 and Visual Studio for Mac. 

## Actual behavior
Exception has occurred: CLR/System.InvalidCastException
An unhandled exception of type 'System.InvalidCastException' occurred in Generatthor.Core.dll: 'Unable to cast object of type 'System.String' to type 'System.Byte[]'.'
   at Generatthor.Core.Properties.Resources.get_createproject() in C:\Users\JNungaray\Documents\Visual Studio 2017\Projects\Generatthor\Generatthor.Core\Properties\Resources.Designer.cs:line 69
   at Generatthor.Core.Services.GeneratedProjectService.GenerateProject() in C:\Users\JNungaray\Documents\Visual Studio 2017\Projects\Generatthor\Generatthor.Core\Services\GeneratedProjectService.cs:line 26
   at Generatthor.Program.Main(String[] args) in C:\Users\JNungaray\Documents\Visual Studio 2017\Projects\Generatthor\Generatthor\Program.cs:line 77

Just in case I include my launch.json settings that the extension generated
```
{
   // Use IntelliSense to find out which attributes exist for C# debugging
   // Use hover for the description of the existing attributes
   // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
   "version": "0.2.0",
   "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/Generatthor/bin/Debug/netcoreapp2.0/Generatthor.dll",
            "args": [],
            "cwd": "${workspaceFolder}/Generatthor",
            // For more information about the 'console' field, see https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#console-terminal-window
            "console": "internalConsole",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart"
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ,]
}
```

and tasks.json
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/Generatthor/Generatthor.csproj"
            ],
            "problemMatcher": "$msCompile"
        }
    ]
}
```

**Comment by DustinCampbell** [comment]
Does this also fail if you `dotnet run` your application from the command line?

**Comment by Jonatthu** [comment]
Even at dotnet run

**Comment by DustinCampbell** [comment]
In that case, you should file this over at https://github.com/dotnet/cli for guidance about resources. It's not something we can address in C# for VS Code.

**Comment by cartermp** [comment]
Closing this as external.
