### ISSUE TITLE
dotnet run works, but vs code shows lots of errors

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#228]
_From @VanCoding on April 20, 2016 15:39_

Hi guys!

I use VS Code to develop my ASPNetCore application. It highlights over 50% of my code as errorous from the beginnging, even if `dotnet run` works just fine. I first thought that it's just a bug that you are aware of and are going to fix in a coming version. But when you guys released V1.0, I began to doubt that.

Also, VS Code constantly tells me that I need to restore, even if I have manually restored using `dotnet restore`. And if I let VS Code do its own restore, I cannot start my application using `dotnet run` anymore until I do `dotnet reload` manually again.

So, is this a bug or am I doing something wrong?

Thanks for your help! :)

_Copied from original issue: Microsoft/vscode#5555_

**Comment by DustinCampbell** [comment]
@VanCoding, I have a couple of questions that will help us figure out what is happening:

1. What version of the .NET CLI are you running? Could you run `dotnet --info` and dump the results here?
2. What version of the C# extension are you running? You can determine this be brining up the command palette in VS Code and running the `Extensions: Show Installed Suggestions` command.

**Comment by VanCoding** [comment]
My versions are:

.NET CLI:
```
Product Information:
 Version:     1.0.0-beta-001603
 Commit Sha:  66a4554290

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 Runtime Id:  win7-x64
```
C# Extension: `0.3.7`

What I've found out: It seems that VS Code still wants to use dnx restore, that's why it messes up my dependencies and I have to do `dotnet restore` again. I've noticed it because I've uninstalled dnx and VS Code now tells me that the command was not found when it tries to restore.

Can I somehow tell VS Code to use `dotnet restore`?
Also, can this be the reason why VS Code marks half of the code as errorous?

Here's my project.json:
```
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "compile":["*.cs"],

    "dependencies": {
        "NETStandard.Library": "1.0.0-*",
        "Microsoft.AspNetCore.Server.Kestrel":"1.0.0-*",
        "Npgsql":"3.1.0-unstable0415",
        "Dapper":"1.50.0-*",
        "Microsoft.AspNetCore.StaticFiles":"1.0.0-*",
        "Newtonsoft.Json":"8.0.2",
        "System.Runtime.Serialization.Primitives":"4.0.0-*",
        "System.Xml.XDocument":"4.0.11-*",
        "Portable.BouncyCastle":"1.8.1",
        "System.Security.Cryptography.X509Certificates":"4.0.0-*",
        "System.Text.RegularExpressions": "4.1.0-*"
    },

    "frameworks": {
        "dnxcore50": {
            "System.Linq":"4.0.1-beta-*"
        }
    }
}
```

The strange thing is, that all the "errors" are related to VS Code not finding some types, like System.Void or System.Text even if properly imported. I can't recognize a system in what types are found, and what types are unknown.

**Comment by DustinCampbell** [comment]
Thanks for the detail. I suspected that you might be in a situation like this.

The currently shipping C# extension on the VS Code marketplace still targets DNX and does not work properly with .NET CLI. Also, it looks like the version of .NET CLI you're using is not a recent build, but is still newer than the "official" one (which was 1.0.0-beta-001598).

I recommend grabbing a newer .NET CLI from https://github.com/dotnet/cli. Then, get the latest C# extension from here: https://github.com/OmniSharp/omnisharp-vscode/releases.

**Comment by DustinCampbell** [comment]
Note that if you do the things I suggested, you'll find that a lot has changed but you'll be closer to what is shipping for ASP .NET Core 1.0 in RC2.

**Comment by gregg-miskelly** [comment]
BTW here are full instructions: http://aka.ms/vscclrdogfood

**Comment by DustinCampbell** [comment]
Thank @gregg-miskelly! I keep forgetting to point to that. :smile:

**Comment by VanCoding** [comment]
@DustinCampbell wow, it works!

Thank you! :)

**Comment by DustinCampbell** [comment]
Awesome! Glad to hear it's working for you.

**Comment by daviatorstorm** [comment]
Hello guys have alot errors.
Created dotnet app with yo code generator.

dotnetcore version: `1.0.0-preview1-002702`
vscode: `1.1.1`
C# Extantion: `1.0.11`

project.json
```
{
  "userSecretsId": "aspnet-RealtorWorld-e698a016-22b4-4e1c-b856-80223a444f8d",

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    }
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    },
    "Microsoft.Extensions.SecretManager.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "gcServer": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },

  "tooling": {
    "defaultNamespace": "RealtorWorld"
  }
}
```

**Comment by cNoveron** [comment]
Errors are still happening for me but the link you shared is gone, but I see people are still dealing with this. @DustinCampbell Can you point us to the right direction to silence all this false error reporting?
