### ISSUE TITLE
Incorrect code format

### ISSUE THREAD

**Issue by dluc** [OmniSharp/omnisharp-vscode#2283]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```
VS Code version: 1.23.0 (1.23.0)
C# Extension version: 1.15.0

## Steps to reproduce
1. Open a .cs file
2. Format document, e.g. ⇧⌥F

Note: I tried placing a `omnisharp.json` file in the root folder and also under .vscode, but looks like the file is ignored.

## Expected  behavior
Curly braces are formatted correctly, e.g.

```
private static string Foo ()
{
    return "";
}
```

## Actual behavior

Curly brace in the wrong position:

```
private static string Foo () {
    return "";
}
```

**Comment by dluc** [comment]
By the way, the same issue is described in SO here: https://stackoverflow.com/questions/34407922/setting-c-sharp-formatting-options-for-omnisharp-on-visual-studio-code

**Comment by DustinCampbell** [comment]
Hi! have you included your C# file in a project? The OmniSharp server only processes files that are actually in a C# project.

**Comment by DustinCampbell** [comment]
Could you provide your full OmniSharp Log after loading this project? You can retrieve the log by selecting View->Output from the VS Code menu. Then, choose "OmniSharp Log" from the dropdown in the top-right corner of the Output pane.

**Comment by dluc** [comment]
@DustinCampbell here's the log:
```
Starting OmniSharp server at 5/11/2018, 1:58:38 PM
    Target: /Users/test/workspace/vscode-csharp/vscode-csharp.sln

OmniSharp server started with Mono 5.10.1
    Path: /Users/test/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/OmniSharp.exe
    PID: 29338

﻿[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.13.4 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/Users/test/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin"
            CscToolPath = /Users/test/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/test/workspace/vscode-csharp'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /Users/test/workspace/vscode-csharp
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/test/workspace/vscode-csharp/vscode-csharp.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/test/workspace/vscode-csharp/ConsoleApp/ConsoleApp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/test/workspace/vscode-csharp'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/test/workspace/vscode-csharp' on host 29301.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/test/workspace/vscode-csharp/ConsoleApp/ConsoleApp.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/test/workspace/vscode-csharp/ConsoleApp/ConsoleApp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: ConsoleApp
```

**Comment by DustinCampbell** [comment]
@dluc : That log looks perfect. :smile: What other VS Code extensions do you have installed? Maybe something is conflicting.

**Comment by dluc** [comment]
hmm I'l try to remove extensions and see what happens.  Here's a list

![image](https://user-images.githubusercontent.com/371009/39948538-4d20c8c8-552b-11e8-9eb8-ac8fedc41dcd.png)

**Comment by dluc** [comment]
After uninstalling C# FixFormat, Format Document stops working completely, and I get a message:

![image](https://user-images.githubusercontent.com/371009/39948683-0f0495d2-552c-11e8-8fb5-f0575aa56054.png)

**Comment by DustinCampbell** [comment]
@Leopotam, have you seen anything like this before?

**Comment by dluc** [comment]
quick update: I removed all the C# extensions, and installed only C#:

![image](https://user-images.githubusercontent.com/371009/39949698-5599c97c-5531-11e8-9bec-0c4d826c2b12.png)

after this, Omnisharp has been reinstalled, and now Format Document works fine.

Looks like some conflict due to the order I installed my extensions, or something old/stale in my system.  It would be nice to discover exactly, but it seems very hard to reproduce.  I will install the other extensions and see if there is any regression.

Thanks for pointing me on this path, at least I fixed my environment :+1:

**Comment by DustinCampbell** [comment]
Excellent! That's great to hear!

**Comment by dluc** [comment]
@Leopotam I assume you mean the message to disable code format (`"csharp.format.enable": false`) when installing CSharpFixFormat. I saw that message and applied it, but to be honest I didn't understand the implication, and I forgot about it after removing the extension.

Is it possible to show a message to revert that change when uninstalling the extension? I think other users trying the extension and later removing it, might end up in the same situation.
