### ISSUE TITLE
OmniSharp does not start after upgrading to 1.15.0

### ISSUE THREAD

**Issue by anfomin** [OmniSharp/omnisharp-vscode#2285]
## Environment data
`dotnet --info` output:
```
Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```
VS Code version: 1.23.1
C# Extension version: 1.15.0

## Steps to reproduce

1. Checkout [RaygunCore repo](https://github.com/anfomin/rayguncore)
2. Restore packages.
3. Open project in VS Code.

## Expected  behavior

OmniSharp should start normal 😄 

## Actual behavior

There is error on OmniSharp log:
[error.txt](https://github.com/OmniSharp/omnisharp-vscode/files/1994056/error.txt)

Project opens normal using OmniSharp `1.14.0` and `1.15.0-beta4` versions.

**Comment by dbogatov** [comment]
I have similar problem as well.

**Comment by gregg-miskelly** [comment]
I am not a language service guy, but I am fairly certain the issue is that the new OmniSharp requires a newer mono. So if you can, try upgrading your globally installed mono to 5.8.1. There is a PR out currently to try and detect this.

If that doesn't help, someone who knows more about OmniSharp can hopefully help in the morning.

**Comment by anfomin** [comment]
I uninstalled mono 5.4.1.6 (via brew) and installed latest 5.12 from [mono-project](https://www.mono-project.com). Error resolved, thank you @gregg-miskelly!

**Comment by DustinCampbell** [comment]
@anfomin / @dbogatov : There was a subtle bug in Mono that was exposed by Roslyn 2.7.0 that has since been fixed. Unfortunately, we forgot to update the minimum Mono version requirement in C# for VS Code. We should have a new release out shortly that addresses that problem.
