### ISSUE TITLE
OmniSharp fails to load project when adding reference to other project

### ISSUE THREAD

**Issue by LunarLambda** [OmniSharp/omnisharp-vscode#2286]
## Environment data
```
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.101\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```
VS Code version: 1.23.1
C# Extension version: 1.15.0

## Steps to reproduce
> dotnet new console
> dotnet new classlib -o mylib
> dotnet add reference mylib/mylib.csproj

## Expected  behavior
OmniSharp should load the project as normal and enable intellisense for classes inside mylib

## Actual behavior
dotnet build / dotnet run work as expected, however:

OmniSharp fails to load the project console project, doesn't load mylib.csproj at all, and intellisense is not working. OmniSharp log:
```
Starting OmniSharp server at 2018-5-11 17:40:45
    Target: c:\Users\Luna\Desktop\Test

OmniSharp server started
    Path: C:\Users\Luna\.vscode\extensions\ms-vscode.csharp-1.15.0\.omnisharp\1.30.0\OmniSharp.exe
    PID: 5276

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2017 15.7.27703.2000 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\Luna\.vscode\extensions\ms-vscode.csharp-1.15.0\.omnisharp\1.30.0\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2017 15.7.27703.2000 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Luna\Desktop\Test'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\Users\Luna\Desktop\Test
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\Luna\Desktop\Test'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Luna\Desktop\Test\Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Luna\Desktop\Test\mylib\mylib.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\Luna\Desktop\Test\Test.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Luna\Desktop\Test'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Luna\Desktop\Test' on host 5376.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin" directory.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\Luna\Desktop\Test\Test.csproj'.
c:\Users\Luna\Desktop\Test\Test.csproj
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1656,5): Error: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin" directory.
```
## Known workarounds
None, removing the reference to mylib.csproj from test.csproj and reloading the window causes omnisharp to load both projects correctly.

**Comment by DustinCampbell** [comment]
Hi! Could you provide your full OmniSharp Log after loading this project? You can find this by selecting View->Output from the VS Code menu and then selecting "OmniSharp Log" from the dropdown at the top-right corner of the Output pane.

**Comment by LunarLambda** [comment]
Starting OmniSharp server at 2018-5-11 16:58:29
    Target: c:\Users\Luna\Desktop\Test

OmniSharp server started
    Path: C:\Users\Luna\.vscode\extensions\ms-vscode.csharp-1.15.0\.omnisharp\1.30.0\OmniSharp.exe
    PID: 6660

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2017 15.6.27428.2037 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\Luna\.vscode\extensions\ms-vscode.csharp-1.15.0\.omnisharp\1.30.0\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2017 15.6.27428.2037 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Luna\Desktop\Test'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\Users\Luna\Desktop\Test
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\Luna\Desktop\Test'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Luna\Desktop\Test\Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Luna\Desktop\Test\mylib\mylib.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Luna\Desktop\Test'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Luna\Desktop\Test' on host 9552.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\Luna\Desktop\Test\Test.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\Luna\Desktop\Test\Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\Luna\Desktop\Test\mylib\mylib.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\Luna\Desktop\Test\mylib\mylib.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Test
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: mylib
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Luna\Desktop\Test\Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\Luna\Desktop\Test\Test.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin" directory.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\Luna\Desktop\Test\Test.csproj'.
c:\Users\Luna\Desktop\Test\Test.csproj
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1603,5): Error: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin" directory.

**Comment by LunarLambda** [comment]
Will do and report back asap.

**Comment by LunarLambda** [comment]
Updated Build Tools, restarted my machine, made a new folder, followed the same steps of creating and referencing the projects, and same story, omnisharp fails to load the project and intellisense doesn't load.

Starting OmniSharp server at 2018-5-11 17:14:10
    Target: c:\Users\Luna\Desktop\Test

OmniSharp server started
    Path: C:\Users\Luna\.vscode\extensions\ms-vscode.csharp-1.15.0\.omnisharp\1.30.0\OmniSharp.exe
    PID: 8764

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2017 15.6.27428.2043 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\Luna\.vscode\extensions\ms-vscode.csharp-1.15.0\.omnisharp\1.30.0\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2017 15.6.27428.2043 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Luna\Desktop\Test'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\Users\Luna\Desktop\Test
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\Luna\Desktop\Test'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Luna\Desktop\Test\Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Luna\Desktop\Test\mylib\mylib.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\Luna\Desktop\Test\Test.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Luna\Desktop\Test'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Luna\Desktop\Test' on host 7864.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin" directory.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\Luna\Desktop\Test\Test.csproj'.
c:\Users\Luna\Desktop\Test\Test.csproj
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1603,5): Error: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin" directory.

**Comment by DustinCampbell** [comment]
FWIW, the log's look identical. It doesn't appear that the VS 2017 build tools were actually updated. They have the same version numbers: `15.6.27428.2043`. I just installed the latest VS 2017 build tools locally and the version is `15.7.27703.2000`.

**Comment by LunarLambda** [comment]
My bad, it's updating a second time now, this time for 15.7.1, sorry!

**Comment by LunarLambda** [comment]
Okay, updated, version numbers match what you said, tried again, same procedure, same result.

dotnet new console
dotnet new classlib -o mylib
dotnet add reference mylib/mylib.csproj
opened Program.cs to start OmniSharp

Starting OmniSharp server at 2018-5-11 17:40:45
    Target: c:\Users\Luna\Desktop\Test

OmniSharp server started
    Path: C:\Users\Luna\.vscode\extensions\ms-vscode.csharp-1.15.0\.omnisharp\1.30.0\OmniSharp.exe
    PID: 5276

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2017 15.7.27703.2000 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\Luna\.vscode\extensions\ms-vscode.csharp-1.15.0\.omnisharp\1.30.0\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2017 15.7.27703.2000 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Luna\Desktop\Test'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\Users\Luna\Desktop\Test
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\Luna\Desktop\Test'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Luna\Desktop\Test\Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Luna\Desktop\Test\mylib\mylib.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\Luna\Desktop\Test\Test.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Luna\Desktop\Test'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Luna\Desktop\Test' on host 5376.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin" directory.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\Luna\Desktop\Test\Test.csproj'.
c:\Users\Luna\Desktop\Test\Test.csproj
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1656,5): Error: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin" directory.

**Comment by DustinCampbell** [comment]
Thanks for the update and sorry it didn't work. 😞 

Out of curiosity, do you actually have the .NET Core workload installed into the VS 2017 build tools?

**Comment by DustinCampbell** [comment]
I believe the .NET Core workload installs newer than 1.0.0 now. I would expect it to be the same tools installed with VS 2017 15.7. @andygerlicher / @rainersigwald, is that the case?

So, the problem seems to be that OmniSharp is trying to use the instance of MSBuild from the VS 2017 Build Tools, but the .NET Core workload is not installed.

**Comment by LunarLambda** [comment]
Should I try installing the .NET Core workload from the VS Build Tools installer then?

**Comment by rainersigwald** [comment]
I believe the 15.7 build tools installer .NET Core workload installs the .NET Core SDK version 2.1.200.

**Comment by rainersigwald** [comment]
(and also some other things, so I would expect it to be worth trying)

**Comment by LunarLambda** [comment]
Alright, will try

**Comment by LunarLambda** [comment]
Installing the NET Core workload worked! Thanks a lot! (Although for the future, would it be possible to make it so that it works with standalone installs too?)

![image](https://user-images.githubusercontent.com/38919842/39938976-0637abfa-5555-11e8-92f6-e70ac9a87131.png)

**Comment by DustinCampbell** [comment]
I've created https://github.com/OmniSharp/omnisharp-roslyn/issues/1186 to track adding some options.

**Comment by yuridiniz** [comment]
Estou com exatamente o mesmo problema, mesmo na versão atual continua acontecendo.

**dotnet --info**
```
Ferramentas de Linha de Comando do .NET (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.200\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```

**OmniSharp log**

```
OmniSharp server started
    Path: C:\Users\yschmitz\.vscode\extensions\ms-vscode.csharp-1.15.2\.omnisharp\1.30.1\OmniSharp.exe
    PID: 10312

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Ferramentas de Build do Visual Studio 2017 15.7.27703.2000 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\yschmitz\.vscode\extensions\ms-vscode.csharp-1.15.2\.omnisharp\1.30.1\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Ferramentas de Build do Visual Studio 2017 15.7.27703.2000 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\yschmitz\Documents\GitHub\Dev\Server'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\Users\yschmitz\Documents\GitHub\Dev\Server
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\yschmitz\Documents\GitHub\Dev\Server'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\yschmitz\Documents\GitHub\Dev\Server\Snm.Api\Snm.Api.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\yschmitz\Documents\GitHub\Dev\Server\Snm.Business\Snm.Business.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\yschmitz\Documents\GitHub\Dev\Server'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\yschmitz\Documents\GitHub\Dev\Server' on host 16580.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\yschmitz\Documents\GitHub\Dev\Server\Snm.Api\Snm.Api.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        A tarefa "GetReferenceNearestTargetFrameworkTask" não foi encontrada. Verifique se: 1.) O nome da tarefa no arquivo de projeto é o mesmo nome da classe da tarefa. 2.) A classe da tarefa é "public" e implementa a interface Microsoft.Build.Framework.ITask. 3.) A tarefa está declarada corretamente com <UsingTask> no arquivo de projeto ou nos arquivos *.tasks localizados no diretório "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin".
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\yschmitz\Documents\GitHub\Dev\Server\Snm.Api\Snm.Api.csproj'.
c:\Users\yschmitz\Documents\GitHub\Dev\Server\Snm.Api\Snm.Api.csproj
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1656,5): Error: A tarefa "GetReferenceNearestTargetFrameworkTask" não foi encontrada. Verifique se: 1.) O nome da tarefa no arquivo de projeto é o mesmo nome da classe da tarefa. 2.) A classe da tarefa é "public" e implementa a interface Microsoft.Build.Framework.ITask. 3.) A tarefa está declarada corretamente com <UsingTask> no arquivo de projeto ou nos arquivos *.tasks localizados no diretório "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
```

**VsCode**

```
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by DustinCampbell** [comment]
@yuridiniz : Could you file a new issue? The underlying problem reported here was discovered. I suspect you're experience a different problem that may look similar.
