### ISSUE TITLE
Code Hinting stopped working

### ISSUE THREAD

**Issue by mistergreen** [OmniSharp/omnisharp-vscode#2287]
## Environment data
VS Code version: 1.23.1 OS X
C# Extension version: 1.15.0

I saw the auto update to 1.15.0 yesterday and today the code hinting stopped working. It tries I think, with 'loading' appearing next to the code but nothing appears.

**Comment by gregg-miskelly** [comment]
Are you running into https://github.com/OmniSharp/omnisharp-vscode/issues/2285?

**Comment by Addyarb** [comment]
I noticed this issue in addition to many others (auto formatting, no red lines under syntax errors, etc.), posted a solution for this in #2288

**Comment by DustinCampbell** [comment]
@Addyarb : That's not a solution for making 1.15.0 work. That just rolls people back to 1.14.0.

@mistergreen : We just released 1.15.1, which should address #2285 if that's the issue you were seeing. However, if it *is* the same issue, you can fix the issue by updating Mono to the latest version from http://www.mono-project.com/download/stable/.

**Comment by mistergreen** [comment]
I'm running the lastest .NET core (OS X) instead of mono. Not sure if that's an issue.
I updated C# 1.15.1, same problem and a bunch of warning/trouble. I'm using C# for Unity btw.

> Starting OmniSharp server at 5/11/2018, 2:26:08 PM
>     Target: /Users/minh/Documents/PeeWee-Unity/PeeWee-Unity.sln
> 
> OmniSharp server started
>     Path: /Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/run
>     PID: 1769
> 
> ﻿[info]: OmniSharp.Stdio.Host
>         Starting OmniSharp on MacOS 10.12.6 (x64)
> [info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
>         Located 1 MSBuild instance(s)
>             1: StandAlone 15.0 - "/Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin"
> [info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
>         MSBUILD_EXE_PATH environment variable set to '/Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/MSBuild.dll'
> [info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
>         Registered MSBuild instance: StandAlone 15.0 - "/Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin"
>             MSBuildExtensionsPath = /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/xbuild
>             BypassFrameworkInstallChecks = true
>             CscToolPath = /Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/Roslyn
>             CscToolExe = csc.exe
>             MSBuildToolsPath = /Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin
>             TargetFrameworkRootPath = /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/xbuild-frameworks
> [info]: OmniSharp.Cake.CakeProjectSystem
>         Detecting Cake files in '/Users/minh/Documents/PeeWee-Unity'.
> [info]: OmniSharp.Cake.CakeProjectSystem
>         Could not find any Cake files
> [info]: OmniSharp.DotNet.DotNetProjectSystem
>         Initializing in /Users/minh/Documents/PeeWee-Unity
> [info]: OmniSharp.DotNet.DotNetProjectSystem
>         Auto package restore: False
> [info]: OmniSharp.DotNet.DotNetProjectSystem
>         Update workspace context
> [info]: OmniSharp.DotNet.DotNetProjectSystem
>         Resolving projects references
> [info]: OmniSharp.MSBuild.ProjectSystem
>         Detecting projects in '/Users/minh/Documents/PeeWee-Unity/PeeWee-Unity.sln'.
> [info]: OmniSharp.MSBuild.ProjectManager
>         Queue project update for '/Users/minh/Documents/PeeWee-Unity/Assembly-CSharp.csproj'
> [info]: OmniSharp.MSBuild.ProjectManager
>         Queue project update for '/Users/minh/Documents/PeeWee-Unity/Assembly-CSharp-firstpass.csproj'
> [info]: OmniSharp.MSBuild.ProjectManager
>         Queue project update for '/Users/minh/Documents/PeeWee-Unity/Assembly-CSharp-Editor.csproj'
> [info]: OmniSharp.MSBuild.ProjectManager
>         Loading project: /Users/minh/Documents/PeeWee-Unity/Assembly-CSharp.csproj
> [info]: OmniSharp.Script.ScriptProjectSystem
>         Detecting CSX files in '/Users/minh/Documents/PeeWee-Unity'.
> [info]: OmniSharp.Script.ScriptProjectSystem
>         Could not find any CSX files
> [info]: OmniSharp.Stdio.Host
>         Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
> [info]: OmniSharp.Stdio.Host
>         Configuration finished.
> [info]: OmniSharp.Stdio.Host
>         Omnisharp server running using Stdio at location '/Users/minh/Documents/PeeWee-Unity' on host 1755.
> [warn]: OmniSharp.MSBuild.ProjectLoader
>         "/Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/NuGet.targets" cannot be imported again. It was already imported at "/Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/Microsoft.Common.CurrentVersion.targets (5915,3)". This is most likely a build authoring error. This subsequent import will be ignored. [/Users/minh/Documents/PeeWee-Unity/Assembly-CSharp-firstpass.csproj]
> /Users/minh/Documents/PeeWee-Unity/Assembly-CSharp.csproj
> /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/xbuild/15.0/Microsoft.Common.targets/ImportAfter/Microsoft.NuGet.ImportAfter.targets(21,3): Error: "/Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/NuGet.targets" cannot be imported again. It was already imported at "/Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/Microsoft.Common.CurrentVersion.targets (5915,3)". This is most likely a build authoring error. This subsequent import will be ignored. [/Users/minh/Documents/PeeWee-Unity/Assembly-CSharp-firstpass.csproj]
> 
> [info]: OmniSharp.MSBuild.ProjectManager
>         Adding project '/Users/minh/Documents/PeeWee-Unity/Assembly-CSharp.csproj'
> [info]: OmniSharp.MSBuild.ProjectManager
>         Loading project: /Users/minh/Documents/PeeWee-Unity/Assembly-CSharp-firstpass.csproj
> [info]: OmniSharp.MSBuild.ProjectManager
>         Adding project '/Users/minh/Documents/PeeWee-Unity/Assembly-CSharp-firstpass.csproj'
> [info]: OmniSharp.MSBuild.ProjectManager
>         Loading project: /Users/minh/Documents/PeeWee-Unity/Assembly-CSharp-Editor.csproj
> [warn]: OmniSharp.MSBuild.ProjectLoader
>         "/Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/NuGet.targets" cannot be imported again. It was already imported at "/Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/Microsoft.Common.CurrentVersion.targets (5915,3)". This is most likely a build authoring error. This subsequent import will be ignored. [/Users/minh/Documents/PeeWee-Unity/Assembly-CSharp-firstpass.csproj]
> [warn]: OmniSharp.MSBuild.ProjectLoader
>         "/Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/NuGet.targets" cannot be imported again. It was already imported at "/Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/Microsoft.Common.CurrentVersion.targets (5915,3)". This is most likely a build authoring error. This subsequent import will be ignored. [/Users/minh/Documents/PeeWee-Unity/Assembly-CSharp.csproj]
> /Users/minh/Documents/PeeWee-Unity/Assembly-CSharp-Editor.csproj
> /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/xbuild/15.0/Microsoft.Common.targets/ImportAfter/Microsoft.NuGet.ImportAfter.targets(21,3): Error: "/Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/NuGet.targets" cannot be imported again. It was already imported at "/Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/Microsoft.Common.CurrentVersion.targets (5915,3)". This is most likely a build authoring error. This subsequent import will be ignored. [/Users/minh/Documents/PeeWee-Unity/Assembly-CSharp-firstpass.csproj]
> /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/xbuild/15.0/Microsoft.Common.targets/ImportAfter/Microsoft.NuGet.ImportAfter.targets(21,3): Error: "/Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/NuGet.targets" cannot be imported again. It was already imported at "/Users/minh/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/Microsoft.Common.CurrentVersion.targets (5915,3)". This is most likely a build authoring error. This subsequent import will be ignored. [/Users/minh/Documents/PeeWee-Unity/Assembly-CSharp.csproj]
> 
> [info]: OmniSharp.MSBuild.ProjectManager
>         Adding project '/Users/minh/Documents/PeeWee-Unity/Assembly-CSharp-Editor.csproj'
> [info]: OmniSharp.MSBuild.ProjectManager
>         Update project: Assembly-CSharp
> [warn]: OmniSharp.MSBuild.ProjectManager
>         Unable to resolve assembly '/Users/minh/Documents/PeeWee-Unity/Temp/bin/Debug/Assembly-CSharp-firstpass.dll'
> [info]: OmniSharp.MSBuild.ProjectManager
>         Update project: Assembly-CSharp-firstpass
> [info]: OmniSharp.MSBuild.ProjectManager
>         Update project: Assembly-CSharp-Editor
> [warn]: OmniSharp.MSBuild.ProjectManager
>         Unable to resolve assembly '/Users/minh/Documents/PeeWee-Unity/Temp/bin/Debug/Assembly-CSharp-firstpass.dll'
> [warn]: OmniSharp.MSBuild.ProjectManager
>         Unable to resolve assembly '/Users/minh/Documents/PeeWee-Unity/Temp/bin/Debug/Assembly-CSharp.dll'
>

**Comment by Takboy** [comment]
I have same issue. 

S Code version: 1.23.1 OS X
C# Extension version: 1.15.1

Starting OmniSharp server at 2018-5-12 04:03:18
    Target: /Users/takboy/Documents/WorkSpace/TaknFactory/Project/DPL/Deeple/Deeple.sln

OmniSharp server started
    Path: /Users/takboy/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/run
    PID: 745

﻿[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.12.6 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "/Users/takboy/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/Users/takboy/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "/Users/takboy/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin"
            MSBuildExtensionsPath = /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/xbuild
            BypassFrameworkInstallChecks = true
            CscToolPath = /Users/takboy/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /Users/takboy/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin
            TargetFrameworkRootPath = /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/xbuild-frameworks
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/takboy/Documents/WorkSpace/TaknFactory/Project/DPL/Deeple'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /Users/takboy/Documents/WorkSpace/TaknFactory/Project/DPL/Deeple
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/takboy/Documents/WorkSpace/TaknFactory/Project/DPL/Deeple/Deeple.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/takboy/Documents/WorkSpace/TaknFactory/Project/DPL/Deeple/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/takboy/Documents/WorkSpace/TaknFactory/Project/DPL/Deeple/Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/takboy/Documents/WorkSpace/TaknFactory/Project/DPL/Deeple'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/takboy/Documents/WorkSpace/TaknFactory/Project/DPL/Deeple/Assembly-CSharp.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/takboy/Documents/WorkSpace/TaknFactory/Project/DPL/Deeple' on host 726.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/takboy/Documents/WorkSpace/TaknFactory/Project/DPL/Deeple/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/takboy/Documents/WorkSpace/TaknFactory/Project/DPL/Deeple/Assembly-CSharp-Editor.csproj
[warn]: OmniSharp.MSBuild.ProjectLoader
        "/Users/takboy/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/NuGet.targets" cannot be imported again. It was already imported at "/Users/takboy/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/Microsoft.Common.CurrentVersion.targets (5915,3)". This is most likely a build authoring error. This subsequent import will be ignored. [/Users/takboy/Documents/WorkSpace/TaknFactory/Project/DPL/Deeple/Assembly-CSharp.csproj]
/Users/takboy/Documents/WorkSpace/TaknFactory/Project/DPL/Deeple/Assembly-CSharp-Editor.csproj
/Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/xbuild/15.0/Microsoft.Common.targets/ImportAfter/Microsoft.NuGet.ImportAfter.targets(21,3): Error: "/Users/takboy/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/NuGet.targets" cannot be imported again. It was already imported at "/Users/takboy/.vscode/extensions/ms-vscode.csharp-1.15.1/.omnisharp/1.30.0/omnisharp/msbuild/15.0/Bin/Microsoft.Common.CurrentVersion.targets (5915,3)". This is most likely a build authoring error. This subsequent import will be ignored. [/Users/takboy/Documents/WorkSpace/TaknFactory/Project/DPL/Deeple/Assembly-CSharp.csproj]

[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/takboy/Documents/WorkSpace/TaknFactory/Project/DPL/Deeple/Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-Editor
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly '/Users/takboy/Documents/WorkSpace/TaknFactory/Project/DPL/Deeple/Temp/bin/Debug/Assembly-CSharp.dll'

**Comment by DustinCampbell** [comment]
@mistergreen / @Takboy : OmniSharp is trying to use the 5.4.1 Mono bits that you have installed to redirect MSBuild to. You can likely address this problem by installing a newer Mono from http://www.mono-project.com/download/stable/ or by using `brew cask install mono-mdk`.

**Comment by mistergreen** [comment]
Thanks. Installing the latest mono fixed the problem. Wow, It takes up 1GB of disk space.

**Comment by DustinCampbell** [comment]
FWIW, I did try installing Mono 5.4.1.6 locally on my own Mac and could not reproduce the same problem with a Unity project. Everything worked for me, so I'm not precisely why your project could not be loaded properly.

**Comment by DustinCampbell** [comment]
Also, part of the reason the Mono MDK is so large is because it includes ahead-of-time native-compiled images for OSX. On the positive side, those make OmniSharp run noticeably faster! :smile:
