### ISSUE TITLE
Debug inspection of a dictionary shows duplicate key/value information

### ISSUE THREAD

**Issue by jeffschwMSFT** [OmniSharp/omnisharp-vscode#229]
![dictionary](https://cloud.githubusercontent.com/assets/9561583/14714199/ee899042-0798-11e6-8364-807589d3803d.gif)

Set a break point on the Console line and hover over to inspect the dictionary type.  Notice that the key/value information for the first element is shown twice:

        public static void Main(string[] args)
        {
            Dictionary<string,string> data = new Dictionary<string,string>();
            data.Add("apples", "oranges");
            
            Console.WriteLine(data["apples"]);
        }

C# extension 1.0.3-rc2
OS X

**Comment by gregg-miskelly** [comment]
So here is what is going on - KeyValuePair has a field called 'value' and a property called 'Value'. Currently the debugger is showing both. I believe this is because we aren't currently enabling the option to hide private members on framework types.

**Comment by gregg-miskelly** [comment]
This is now fixed in our internal builds, and will ship in our first post RC2 release.
