### ISSUE TITLE
Support applicationUrl of launchSettings.json

### ISSUE THREAD

**Issue by WolfspiritM** [OmniSharp/omnisharp-vscode#2296]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.101\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```
VS Code version: 1.23.1
C# Extension version: 1.15

## Steps to reproduce
1. Create a default ASP.NET Core project with VS.
2. Change Application URL in Project Settings
3. Launch it via VSCode

## Expected  behavior
Application binds to the correct Application URL defined in launchSettings.json as applicationUrl as it does when using dotnet run.

## Actual behavior
Application binds to port 5000

**Comment by dtruel** [comment]
This is still not working for me. I have 2 projects in one folder, and it ignores my launchSettings.json for both of them and tries to run them both on port 5000.

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Client",
            "type": "coreclr",
            "request": "launch",
            "program": "${workspaceFolder}/WebUI/bin/Debug/netcoreapp2.0/GidIndustrial.Gideon.WebUI.dll",
            "args": [],
            "cwd": "${workspaceRoot}/WebUI",
            "stopAtEntry": false,
            "externalConsole": false
        },
        {
            "name": "Debug Server",
            "type": "coreclr",
            "request": "launch",
            "program": "${workspaceFolder}/WebApi/bin/Debug/netcoreapp2.1/GidIndustrial.Gideon.WebApi.dll",
            "args": [],
            "cwd": "${workspaceRoot}/WebApi",
            "stopAtEntry": false,
            "externalConsole": false,
        }
    ],
    "compounds": [
        {
            "name": "Debug Server and Client",
            "configurations": [
                "Debug Server",
                "Debug Client"
            ]
        }
    ]
}
```

**Comment by gregg-miskelly** [comment]
I am happy to help investigate, but please open a new issue rather than commenting on a closed issue. Please include these three details --
1. What OS are you on
2. For the projects you are launching, what is the path to your launchSettings.json relative to the root of your workspace. The debugger should be looking in ${cwd}/Properties/launchSettings.json.
3. Please share your launchSettings.json.

**Comment by dtruel** [comment]
Ok, my apologies.
