### ISSUE TITLE
Unable to open ... File not found issue while trying to debug code inside NuGet via sourcefilemap option

### ISSUE THREAD

**Issue by preetipadalia** [OmniSharp/omnisharp-vscode#2299]
## Environment data
`dotnet --info` output:
VS Code version:1.23.1
C# Extension version: 1.15.1

## Steps to reproduce
1. Create a c# class library project and generate NuGet package which also include source files for the class library.
2. Create a nunit project add the NuGet Project and update sourceFileMap in Launch.json
 "sourceFileMap": {
                "C:\\Users\\{userid}\\.nuget\\packages\\{projectName}\\version\\src": "c:\\src"
            },

3. Try to debug the code in nunit project and access class library code. 

## Expected  behavior
VSCode should load the code from class library project from the given path in sourcefilemap

## Actual behavior
4Instead of searching in the give path mentioned in sourcefilemap , vscode is searching in the path from where NuGet package is created(The path of class library project)

Kindly Help.

**Comment by gregg-miskelly** [comment]
To be clear, is your source file map using `\\` or `\` to separate path entries? (GitHub formats it as a single backslash, but I am assuming you are using double backslashes).

Furthermore, when you say 'c:\Users\{userid}' I am assuming that '{userid}' is a replacement value in your example, and in your actual launch.json you have placed your real user id.

Lastly, when you say "VSCode should load the code from class library project" you mean that when you step into your class library (or stop in an exception), you are seeing it open up the code from there. Is that correct?

Assuming my three assumptions are right - your sourceFileMap looks correct. I am _guessing_ you have some sort of typeo there such that the two paths don't quite match. Can you double check?
