### ISSUE TITLE
"Error processing 'threads' request. Unknown Error: 0x9233000b"

### ISSUE THREAD

**Issue by jlennox** [OmniSharp/omnisharp-vscode#2300]
I am attempting to remote debug a macOS target from Windows and error shown inside the "Debug Console" is "Error processing 'threads' request. Unknown Error: 0x9233000b"

The error shown inside the VS Code UI is "Failed to attach to process: Unknown Error: 0x80131c08"

## Environment data
Remote macOS (10.12.6):

> setupAdmins-Mac:~ deviceconnect$ dotnet --info
> .NET Core SDK (reflecting any global.json):
>  Version:   2.1.300-rc1-008673
>  Commit:    f5e3ddbe73
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.12
>  OS Platform: Darwin
>  RID:         osx.10.12-x64
>  Base Path:   /usr/local/share/dotnet/sdk/2.1.300-rc1-008673/
> 
> Host (useful for support):
>   Version: 2.1.0-rc1
>   Commit:  eb9bc92051
> 
> .NET Core SDKs installed:
>   2.1.300-rc1-008673 [/usr/local/share/dotnet/sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.0-rc1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download

Also from remote macOS:

> setupAdmins-Mac:~ deviceconnect$ cat vsdbg/success.txt
> 15.7.20425.2
> setupAdmins-Mac:~ deviceconnect$ cat vsdbg/version.txt
> 15.7.20426.1 commit:91b285752d1135b8cdcdb3d74b44ca9faee48809

Local Windows:

> C:\WINDOWS\system32>dotnet --info
> .NET Core SDK (reflecting any global.json):
>  Version:   2.1.300-rc1-008673
>  Commit:    f5e3ddbe73
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.17134
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\
> 
> Host (useful for support):
>   Version: 2.1.0-rc1
>   Commit:  eb9bc92051
> 
> .NET Core SDKs installed:
>   1.0.3 [C:\Program Files\dotnet\sdk]
>   1.0.4 [C:\Program Files\dotnet\sdk]
>   1.1.0 [C:\Program Files\dotnet\sdk]
>   2.0.0 [C:\Program Files\dotnet\sdk]
>   2.0.2 [C:\Program Files\dotnet\sdk]
>   2.0.3 [C:\Program Files\dotnet\sdk]
>   2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download

VS Code version:

> Version 1.23.1
> Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
> Date 2018-05-10T17:11:17.614Z
> Shell 1.7.12
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64

C# Extension version: 1.15.1

## Steps to reproduce
I've added this entry to my launch.json
```
{
    "name": ".NET Core Remote Attach (WSL)",
    "type": "coreclr",
    "request": "attach",
    "processId": "${command:pickRemoteProcess}",
    "logging": {
        "engineLogging": true,
        "exceptions": true,
        "moduleLoad": true,
        "programOutput": true
    },
    "pipeTransport": {
        "pipeProgram": "wsl.exe",
        "pipeArgs": [ "ssh", "-T", "flashservervm" ],
        "debuggerPath": "~/vsdbg/vsdbg",
        "pipeCwd": "${workspaceRoot}",
        "quoteArgs": true
    },
    "sourceFileMap": {
        "~/ml2": "${workspaceRoot}"
    }
}
```

It successfully shows the process list. After selecting one it runs for a bit then errors as stated. The output from the "Debug Console" shows: https://gist.github.com/jlennox/c4517332a8eeb039da23b60ec945a98f

**Comment by gregg-miskelly** [comment]
This should be the important error: `"message":"Failed to attach to process: Unknown Error: 0x80131c08"`.

That error code is CORDBG_E_TIMEOUT, which means that something is going wrong in the .NET Debugger services (which is part of the CLR that your app is running on) when they try and attach.

On the Mac side, is the process you are attaching to running under the 2.1.0-rc1 runtime?

**Comment by jlennox** [comment]
My problem was the debug target I was trying to attach to is not part of the login session, it was a launchd managed process.

https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPMultipleUsers/Concepts/SystemContexts.html

To work around this, I am pointing `debuggerPath` at a script:
```#!/bin/bash
exec sudo $(dirname $0)/vsdbg $*``` and a relevant `sudoers` entry to permit passwordless elevation.
