### ISSUE TITLE
Reporting errors from custom MSBuild targets

### ISSUE THREAD

**Issue by Artemigos** [OmniSharp/omnisharp-vscode#2305]
Is there a way to report errors in MSBuild targets without breaking OmniSharp entirely? What I'm trying to achieve is run a target before the compile step, execute an external tool, the tool might report some (meaningful) errors that I would like to see in the problems view in VSCode. A (very) basic example would look like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <Target Name="MaybeFail" BeforeTargets="CoreCompile">
    <Exec Command="exit 1" />
  </Target>

</Project>
```

When I do things this way OmniSharp fails to load the project and doesn't try to reload ever again. Even when I silence the error from `Exec` and use `<Error Text="command failed" />` (which I thought exists for that very purpose) the result is the same.

So the question is, is it possible to have an error appear in the problems view like it does for invalid C# syntax and how do I do that?

**Comment by DustinCampbell** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#1187
