### ISSUE TITLE
WSL documentation should use `dotnet publish`

### ISSUE THREAD

**Issue by Spongman** [OmniSharp/omnisharp-vscode#2309]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.200\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

```
VS Code version: 1.23.1
C# Extension version: 1.15.1

## Steps to reproduce
follow the instructions on https://github.com/OmniSharp/omnisharp-vscode/wiki/Windows-Subsystem-for-Linux

## Actual behavior
```
Error from pipe program 'bash.exe': Error:
Error from pipe program 'bash.exe':   An assembly specified in the application dependencies manifest (UserTools.deps.json) was not found:
Error from pipe program 'bash.exe':     package: 'CommandLine.Options', version: '0.0.2'
Error from pipe program 'bash.exe':     path: 'lib/netstandard1.6/CommandLine.Options.dll'
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
```

**Comment by Spongman** [comment]
in WSL:

```
$ dotnet --info
.NET Command Line Tools (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.200/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```

**Comment by gregg-miskelly** [comment]
Yes, the instructions on the wiki could use some refinements. `dotnet build` alone works for apps that only depend on the .NET Framework, but obviously most real apps have other dependencies. Those instructions should probably be adjusted to do a publish instead.

As for the sourceFileMap entry - that is necessary if you build on Linux. If you are building on Windows, that isn't required. Though it certainly doesn't hurt anything, so it might be worth adding anyway.

**Comment by Spongman** [comment]
ok. but i don't think it's too much of a stretch to at least guess that paths coming back from the debuggee strarting with `/mnt/[a-z]/` are probably wsl paths.

**Comment by gregg-miskelly** [comment]
@Spongman I updated the documentation in https://github.com/OmniSharp/omnisharp-vscode/wiki/Windows-Subsystem-for-Linux. Let us know if you spot any more problems with it.
