### ISSUE TITLE
Preprocessor Directive Coloring

### ISSUE THREAD

**Issue by chrisbruno** [OmniSharp/omnisharp-vscode#2312]
Hello. I am not sure if this is possible(or the right place to ask), but my google skills are failing me :)

I'd like to have preprocessor directives matching the color of comments when they are inactive. Here's what it looks like in visual studio:
![visual_studio](https://user-images.githubusercontent.com/16906875/40125888-0193386e-58fa-11e8-9035-0ea40efc95c4.PNG)

and here's vs code:
![vs_code](https://user-images.githubusercontent.com/16906875/40125905-0807589c-58fa-11e8-903e-c5ba4c84f651.PNG)

**Comment by DustinCampbell** [comment]
Unfortunately, this is not possible to do with a VS Code extension. Syntax highlighting in VS Code is achieved with regular expressions, which doesn't have the context necessary to perform that level of highlighting.

**Comment by joemey** [comment]
The vscode-ccptools has a feature like this (https://github.com/Microsoft/vscode-cpptools/issues/1466) maybe this can be adopted for the omnisharp plugin?

**Comment by thowthoww** [comment]
> Unfortunately, this is not possible to do with a VS Code extension. Syntax highlighting in VS Code is achieved with regular expressions, which doesn't have the context necessary to perform that level of highlighting.

Can't you parse .csproj for <DefineConstants>?

**Comment by ssoher** [comment]
@DustinCampbell  C/C++ extension has this feature, how did they achieve it and can this be done for C#?

**Comment by JoeRobich** [comment]
@ssoher If you are using the latest version of the extension, then you can enable the `csharp.semanticHighlighting.enabled` flag to turn on Semantic Highlighting. You can then use one of our included Visual Studio 2019 themes or define an editor theme tweak in your settings.json for your theme to set the value of the `support.other.excluded` scope (`#808080` perhaps).

**Comment by ssoher** [comment]
@JoeRobich It works great with the included VS themes. But when I add the `support.other.excluded` scope to my theme it's not recognized. When I check the scope under cursor at the same point VS themes show that scope but my theme only shows source.cs. What am I missing? Thank you very much.

![image](https://user-images.githubusercontent.com/4283979/83446412-4a119e00-a457-11ea-96b5-ceb6e73baf6d.png)

**Comment by JoeRobich** [comment]
If you maintain your own Theme, you will need to add this line to your theme so that it will use the semantic highlighter.
```json
"semanticHighlighting": true,
```
If you are making tweaks to a community theme, you will need to add the same to your `tokenColorCustomizations` - see https://github.com/microsoft/vscode/issues/92740#issuecomment-600100176

**Comment by ssoher** [comment]
Amazing, it works now and I've learned something, thank you very much!
