### ISSUE TITLE
pipeTransport causes externalConsole to be ignored

### ISSUE THREAD

**Issue by Spongman** [OmniSharp/omnisharp-vscode#2313]
VSCode Version: 1.23.1
OS Version: win10.1803

i'm trying to debug dotnet core app on wsl from windows. here's my launch config:

```
	{
			"name": ".NET Core WSL Launch",
			"type": "coreclr",
			"request": "launch",
			"program": "/mnt/c/MyProg/MyProg.dll",
			"args": [],
			"cwd": "/mnt/c/MyProg",
			"stopAtEntry": true,
                        "console": "externalTerminal",
			"externalConsole": true,
			"pipeTransport": {
				"pipeCwd": "${workspaceRoot}",
				"pipeProgram": "bash.exe",
				"pipeArgs": [ "-c" ],
				"debuggerPath": "~/vsdbg/vsdbg"
			},
			"sourceFileMap": {
				"/mnt/c/": "c:\\"
			}
		},
```
I need to see the console of my app - it's moving the cursor around, drawing ascii art, reading console input, etc...

but the `"console": "externalTerminal"` is ignored. no console is opened.

**Comment by gregg-miskelly** [comment]
Correct. What you are doing cannot work. If your app needs to take input from the console, you have two options: attach, or update your launch configuration to take input from another terminal.

You will need to play with this a little to get it right, but you want something like this for the latter:
1. Open another bash.exe
2. type `tty` to get that terminals tty. You should get something like `/dev/pts/21`
3. Change your launch args to add something like: `"args": ["1>/dev/pts/21", "2>&1", "</dev/pts/21"]`

**Comment by Spongman** [comment]
i don't redirecting the tty will work. i'm using the `Console` api to query the buffer size.

**Comment by gregg-miskelly** [comment]
In that case you will need to launch your program outside of the debugger and attach. You can add some sort of special command line arg to your program to have it pause waiting for a debugger attach (`while (!Debugger.IsAttached) { Thread.Sleep(100); }`) if you need to also debug your startup code.

**Comment by eiximenis** [comment]
@gregg-miskelly 
Is there any possibility to this be addresses? 

I am trying to running two pipeTransport sessions simultaneously to debug two docker containers, but the second session never starts (I suspect is complaining about stdin/stdout being busy by 1st session)

**Comment by gregg-miskelly** [comment]
@eiximenis did you try manually launching `docker exec` twice against the same container? I can't claim that I have exhaustively tested this. But I have tried it before without issue.

If that is your problem - I don't think supporting externalConsole with pipeTransport would actually help as we would likely need two different instances of `docker exec` for that also.

**Comment by eiximenis** [comment]
Hi @gregg-miskelly 
I don't mind on having two "docker exec" instances. My wish would be debug a multi-container project in a similar way that Visual Studio allows to: you can set breakpoints on more than one container and start a debug session against a compose file.

I can debug one container or another, but not the two altogether because when I try to attach to the second container I recieve always an error (I suspect is because stdin/stdout is piped against the 1st container).

**Comment by gregg-miskelly** [comment]
@eiximenis what error do you get? What does the launch.json configuration that you are attempting to start look like?
