### ISSUE TITLE
Getting "Unreachable code detected warning" when using #if preprocessor directive

### ISSUE THREAD

**Issue by mattstewart1189** [OmniSharp/omnisharp-vscode#2319]
## Environment data
`dotnet --info` output:
_.NET Command Line Tools (2.1.200)_

_Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1_

_Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.200\_

_Microsoft .NET Core Shared Framework Host
Version  : 2.0.7
Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11_

VS Code version:
_1.23.1
d0182c3417d225529c6d5ad24b7572815d0de9ac
x64_

C# Extension version:
1.15.2

## Steps to reproduce
Rethrow an exception in a catch block wrapped in an if preprocessor directive.

```
            catch (Exception ex)
            {
#if DEBUG
                throw ex;
#endif
               //this line gives "Unreachable code detected" warning
                Console.WriteLine($"An unhandeled exception has occured. {ex.Message}");
                Console.ReadKey();
            }
```
## Expected  behavior
I would think that no "Unreachable code detected" warning should be given in this case. But the compiler seems to give this error as well?

## Actual behavior
Code after the rethrow will give an "Unreachable code detected" warning.

**Comment by DustinCampbell** [comment]
This is likely by design. Your project will be loaded with its default configuration, which is usually "Debug". So, the "throw ex;" statement would be included, which means that the code afterward is unreachable.
