### ISSUE TITLE
Debug Test causes this feature and intellinsense to be lost

### ISSUE THREAD

**Issue by DanielSSilva** [OmniSharp/omnisharp-vscode#2320]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  18.3
 OS Platform: Linux
 RID:         linuxmint.18.3-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

VS Code version: 1.23.1

C# Extension version: 1.15.2

## Steps to reproduce
Load a project that uses XUnit for unit testing;
Use the "Debug Test" feature;

## Expected  behavior
After debugging, everything works.

## Actual behavior
After the debug, I lose intellisense and that very same feature disapears until I restart...
This doesn't always happen, so I can't seem to find any pattern.
Any idea what might cause it? Any logs that I can share?

**Comment by DustinCampbell** [comment]
I suspect this is the same issue as https://github.com/OmniSharp/omnisharp-vscode/issues/2106. Does that look the same to you?

**Comment by DanielSSilva** [comment]
Indeed it does. Except In my case I also lose intellisense, but I'll add that info there

**Comment by DustinCampbell** [comment]
Thanks very verifying.
