### ISSUE TITLE
Intellisense not working on upper level folder

### ISSUE THREAD

**Issue by goncalo-oliveira** [OmniSharp/omnisharp-vscode#2327]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.200/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```
VS Code version:
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T16:04:33.747Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

C# Extension version:
1.15.2

## Steps to reproduce

Create a 'solution' folder named 'myproject'. Within that folder, create a console project inside a 'src' folder. Hierarchy would be as follows:

---- myproject
-------- src
------------ consoleApp
---------------- consoleApp.csproj
---------------- Program.cs

Open with Visual Studio Code, the upper level folder 'myproject'. Then, open Program.cs.

## Expected  behavior

Opening Program.cs, I would expect intellisense to work.

## Actual behavior

Intellisense doesn't seem to work. I've looked into the Omnisharp logs, but everything seems to be good. Omnisharp starts in the 'myproject' folder, it just doesn't seem to do anything.

If I open the folder at the 'consoleApp' level, intellisense works. As a workaround, I'm using workspaces instead, though, I'd expect this to work.

**Comment by DustinCampbell** [comment]
Could provide your OmniSharp Log?

**Comment by akshita31** [comment]
@goncalo-oliveira Have you added the consoleApp.csproj to your solution file ?

**Comment by goncalo-oliveira** [comment]
On further inspection, it seems that the issue is exactly as @Allesad reported. I created the solution, then the project, but didn't add the project to the solution - also, didn't expected to be necessary.
When adding the project to the solution, OmniSharp seems to be able to deal with it.

Thank you for replying.
