### ISSUE TITLE
Flat symbol list C#

### ISSUE THREAD

**Issue by rakkarage** [OmniSharp/omnisharp-vscode#2329]
https://github.com/patrys/vscode-code-outline/issues/47

the symbol tree outline shows flat for c#

> I guess C# reports symbols differently to most other languages. Unfortunately previous approach broke in many more languages so I think the best solution would be to file a bug against the C# symbol provider and have it report symbol ranges containing the entire class/method definition instead of just their names/signatures.

**Comment by DustinCampbell** [comment]
Could you clarify what the request is for C# for VS Code here? It's not clear to me.

**Comment by rakkarage** [comment]
the symbols are apparently just names not namespaces
anyone would need fully qualified type names (including namespaces etc) to build a tree instead of the list it shows for c# now in outline addon

**Comment by DustinCampbell** [comment]
> i guess there is a way to get em just reading from bug sorry

No problem. I'll dig in a bit deeper to try and sort it out.

**Comment by DustinCampbell** [comment]
FWIW, I think this may be related to https://github.com/OmniSharp/omnisharp-vscode/issues/2307.

**Comment by DustinCampbell** [comment]
Thanks for the pointer @rakkarage
