### ISSUE TITLE
Opening brace not matched with ending brace for the purpose of collapsing

### ISSUE THREAD

**Issue by jnm2** [OmniSharp/omnisharp-vscode#2334]
## To reproduce

`dotnet --info` output: SDK 2.1.200, .NET Core 2.0.7
VS Code version: 1.23.1
C# Extension version: 1.15.2

```cs
class X
{
    private readonly string Json =
@"{
   ""this should collapse when the class is collapsed"": ""fail""
}"

    // This should also collapse with the class
}
```

![image](https://user-images.githubusercontent.com/8040367/40371558-b4340dee-5db0-11e8-8292-2a335f1ddf06.png)

## Expected  behavior

![image](https://user-images.githubusercontent.com/8040367/40371697-111544d8-5db1-11e8-9d98-c5bbad85be98.png)

## Actual behavior

![image](https://user-images.githubusercontent.com/8040367/40371630-e763c812-5db0-11e8-8d7e-db8d115d041c.png)

**Comment by DustinCampbell** [comment]
Thanks for filing this issue. C# for VS Code still uses VS Code's simple default code folding support. Fortunately, VS Code has added API support for extensions to provide custom folding support, so we can fix issues like this now.

I've filed #2335 on our backlog to track adding custom folding support for C#, which will fix issues like this one. Let's track this work there.
