### ISSUE TITLE
Auto formatting breaks if an enum is present 

### ISSUE THREAD

**Issue by dogboydog** [OmniSharp/omnisharp-vscode#2340]
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.105\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```

VS Code version:

1.23.1
d0182c3417d225529c6d5ad24b7572815d0de9ac
x64

C# Extension version:

1.15.2

## Steps to reproduce

Open a .cs file with these contents: 

``` csharp
public class EnumDemo {

    /// <summary>
    /// 
    /// Here is my enum 
    /// </summary>
    public enum DEMO { One, Two, Three };

    void AFunctionHere () {
        //things are indented wrong 
        var hello = 3;
    }

    void AnotherFunction () {
        // hi
    }
}
```

Then Format Document ( Alt + Shift + F) 

## Expected  behavior

The indentation should look like this: 
![image](https://user-images.githubusercontent.com/9920963/40459506-b86a818e-5ecf-11e8-9f54-9f0f1af2b07b.png)

## Actual behavior
The indentation looks like this
![image](https://user-images.githubusercontent.com/9920963/40459492-a976f8e2-5ecf-11e8-8bf7-e7bd86062387.png)

Enjoying the plugin, thank you guys for making it and maintaining it

**Comment by DustinCampbell** [comment]
I'm unable to reproduce this problem with C# for VS Code. Is it possible that you have another extension installed that might be interfering with the formatting?

**Comment by dogboydog** [comment]
Really sorry, you're right. I guess this  was caused by C# Fixformat. Once I uninstall that, I can't auto format c# in general anymore. Sorry about that

**Comment by Leopotam** [comment]
@DustinCampbell if `C#FixFormat` was uninstalled, `"csharp.format.enable": false`, vscode restarted - `omnisharp-vscode` format feature should works without issues. If `C#FixFormat` extension not uninstalled - it will ask about disabling default formatting each time.

**Comment by Leopotam** [comment]
@DustinCampbell sounds like this if @dogboydog wanted to get only `omnisharp-vscode` formatting feature. It described at `README`, btw:
> Сoexistence with the omnisharp-vscode extension
> On each run this extension checks that omnisharp-vscode extension (if installed) will use "csharp.format.enable": false option for disabling builtin format feature. This extension will not work correctly with activated omnisharp-vscode format feature - it's why user should fix option manually or automatically with autofix suggestion.

> After removing the extension, user should manually restores this option to "onisharp-vscode": true for enabling format feature and restart editor then.

**Comment by dogboydog** [comment]
Thanks, I will try a fresh uninstall later and see if I'm able to format
then. Although if removing the semicolon fixes the issue I might keep using
FixFormat. Sorry for the confusion. Thanks for the fast replies

**Comment by DustinCampbell** [comment]
@Leopotam : You might consider changing "omnisharp-vscode" in that description since it is a reference to the repo and the extension is actually "ms-vscode.csharp", or "C# for VS Code". I expect that many (most?) users will not make the connection that "omnisharp-vscode" is the same thing.

**Comment by Leopotam** [comment]
@DustinCampbell well, I used this repo name for reference :) Maybe name should be changed, Ill think about it.

**Comment by dogboydog** [comment]
I uninstalled everything related to Unity and C# and reloaded, then edited my preferences to remove the FixFormat setting. I'm now able to format my code with just the C# plugin. thanks for the help everyone

**Comment by PorcaM** [comment]
It is because of the semicolon.
Remove semicolon at the end of ending brace.
