### ISSUE TITLE
x86 Windows is not currently supported by the .NET Core debugger. Debugging will not be available

### ISSUE THREAD

**Issue by twtyypmb** [OmniSharp/omnisharp-vscode#2341]
## Environment data
`dotnet --info` output:
Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x86
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0(still occur on 2.1.0)
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

VS Code version:
version 1.23.1
submit d0182c3417d225529c6d5ad24b7572815d0de9ac
datetime 2018-05-10T17:11:38.209Z
Shell 1.7.12
render 58.0.3029.110
Node 7.9.0
Structure ia32
C# Extension version:
1.15.2
## Steps to reproduce
open a new folder
type "dotnet new console"
set a breakpoint,and run debug

## Expected  behavior
the application is running,and stop at the breakpoint

## Actual behavior
the application did not run

**Comment by SIkebe** [comment]
@twtyypmb dup of https://github.com/OmniSharp/omnisharp-vscode/issues/844

**Comment by johnmelodyme** [comment]
> ## Environment data
> `dotnet --info` output:
> Product Information:
> Version: 2.0.0
> Commit SHA-1 hash: cdcd1928c9
> 
> Runtime Environment:
> OS Name: Windows
> OS Version: 6.1.7601
> OS Platform: Windows
> RID: win7-x86
> Base Path: C:\Program Files\dotnet\sdk\2.0.0\
> 
> Microsoft .NET Core Shared Framework Host
> 
> Version : 2.0.0(still occur on 2.1.0)
> Build : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
> 
> VS Code version:
> version 1.23.1
> submit d0182c3417d225529c6d5ad24b7572815d0de9ac
> datetime 2018-05-10T17:11:38.209Z
> Shell 1.7.12
> render 58.0.3029.110
> Node 7.9.0
> Structure ia32
> C# Extension version:
> 1.15.2
> 
> ## Steps to reproduce
> open a new folder
> type "dotnet new console"
> set a breakpoint,and run debug
> 
> ## Expected behavior
> the application is running,and stop at the breakpoint
> 
> ## Actual behavior
> the application did not run

How to ?
