### ISSUE TITLE
C# 7.3 is not supported yet

### ISSUE THREAD

**Issue by nabeelomer** [OmniSharp/omnisharp-vscode#2346]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.300-rc1-008673/

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

.NET Core SDKs installed:
  2.1.300-rc1-008673 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS Code version: `1.23.1`
C# Extension version: `1.15.0`

## Steps to reproduce
1. `dotnet new console -o P`
2. Modify the `P.csproj` and add `<LangVersion>7.3</LangVersion>` 
3. Open the project in VSCode.
4. Add `Span<int> s = stackalloc[] {1,2,3};` to `main`. 

## Expected  behavior
There should not be an error.

## Actual behavior
Get a whole array of errors.
<img width="373" alt="screen shot 2018-05-28 at 9 01 18 am" src="https://user-images.githubusercontent.com/11234616/40595995-b7a57770-6255-11e8-9629-e130d015785e.png">

**Comment by nabeelomer** [comment]
@DustinCampbell  Thanks, that solved my problem.

**Comment by DustinCampbell** [comment]
excellent! Thanks for verifying.
