### ISSUE TITLE
Selected project doesn't build/run

### ISSUE THREAD

**Issue by toptensoftware** [OmniSharp/omnisharp-vscode#235]
Not sure if this is an OmniSharp or VSCode issue, but I can't figure this out...

If open single CoreCLR CLI project (with project.json) and open the folder containing it, everything works perfectly well - build, debug, intellisense, etc...

If on the other hand I open a parent folder with say 2 or 3 folders containing projects I can switch between the projects using the picker in the bottom right, but the build command still seems to want to build from the parent folder - rather than the selected project.

I tried setting up a task on the parent folder to build/run the project in the sub-folder but couldn't get it to work.

Am I just missing something obvious?

(Running on OSX, I think latest everything as of yesterday)

**Comment by DustinCampbell** [comment]
This looks similar to #206

**Comment by toptensoftware** [comment]
Indeed it does. I'll close this one.
