### ISSUE TITLE
The SDK 'Microsoft.NET.Sdk' specified could not be found.

### ISSUE THREAD

**Issue by morganabel** [OmniSharp/omnisharp-vscode#2356]
## Environment data
`dotnet --info` output:
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.300/

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.200 [/usr/local/share/dotnet/sdk]
  2.1.300 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

VS Code version: 1.23.1
C# Extension version: 1.15.2

## Steps to reproduce
Open a folder with a C# project

## Expected  behavior
Work correctly.

## Actual behavior
VS code says .NET cli tools cannot be located. dotnet is available on path. Output shows this error: 
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/mab/workplace/Test/Test.csproj
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/mab/workplace/Test/Test.csproj'.
/Users/mab/workplace/Test/Test.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.  /Users/mab/workplace/Test/Test.csproj

**Comment by DustinCampbell** [comment]
This looks to me like a duplicate of #2330. In that report, the issue appears to have something to do with launching VS Code from the LaunchPad vs. from a Terminal window. My suspicion is that the PATH is set differently when launched from the LaunchPad, but I have no idea why that would be.

**Comment by morganabel** [comment]
I was able to solve it by installing Mono and also running from the command line with `code .`

I am going to close this issue because it looks like the same or at least a very similar problem to #2330. I think this is a bug though. Ideally I would like to avoid installing Mono when I have the .net core sdk installed.

**Comment by DustinCampbell** [comment]
FWIW, I wouldn't have expected you to have needed to install Mono if you launched from the command line with `code .`. Did it not work when you launched with `code .` before installing Mono? Or, did you only try that after installing Mono?

**Comment by morganabel** [comment]
I tried that first and it did not work until I installed Mono. Weird issue but at least it is working now.

**Comment by YasirZillow** [comment]
Did you ever figure out why you had to install mono? For me if I use `code .` it doesn't work, but if I launch VS Code from Applications it works fine.

**Comment by rchande** [comment]
@YasirZillow I believe the short answer is that the contents of PATH are slightly different when launched from terminal vs Applications, but I don't have more specific info for you at the moment.
