### ISSUE TITLE
Multiple omnisharp.json settings for one project

### ISSUE THREAD

**Issue by ypapouin** [OmniSharp/omnisharp-vscode#2357]
Currently, you can override FormattingOptions by placing an omnisharp.json file at the project root folder. 

In my projects, I'm using a lot of sub-modules (git) developed by third parties with different C# settings, but all changes made (for merge request to upstream) in these sub-modules must be formatted by hand to avoid losing original formatting.

I would be happy to be able to customize FormattingOptions for each of these sub-modules.

For each folder containing an omnisharp.json, all sub-folder would recursively apply these settings until a new omnisharp.json is found.

## Environment data
`dotnet --info` output:
Outils en ligne de commande .NET (2.1.104)

Product Information:
 Version:            2.1.104
 Commit SHA-1 hash:  48ec687460

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.104\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

VS Code version: 1.23.1
C# Extension version: 1.15.2

**Comment by filipw** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#1208
