### ISSUE TITLE
[c#] projects.json auto-completion should use NuGet.Config

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#236]
_From @Ciantic on April 6, 2016 5:12_
- VSCode Version: 0.10.11
- OS Version: Windows 10

Steps to Reproduce:
1. Open project.json e.g. one of these https://github.com/aspnet/cli-samples
2. Copy NuGet.config from the sample repo also
3. Start typing "Microsoft.AspNetCore." and try to autocomplete, it does not give you right entries.

This is maybe because VS Code uses some other way (rather than omnisharp) to autocomplete the project.json. Or the bug is in OmniSharp.

This issue has been checked by other people in here: https://github.com/OmniSharp/omnisharp-roslyn/issues/413

_Copied from original issue: Microsoft/vscode#4997_

**Comment by aeschli** [comment]
_From @thecodejunkie on April 14, 2016 19:58_

I also noticed this today

```xml
<configuration>
  <packageSources>
    <add key="AspNet CI Feed" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

and I am only getting version (probably package names as well but I've not tried) info back from the main nuget feed

![image](https://cloud.githubusercontent.com/assets/50543/14541797/065f6082-028c-11e6-8ab8-f2c82fa5f5e9.png)

**Comment by aeschli** [comment]
_From @Ciantic on April 15, 2016 10:15_

I must add that the project.json autocompletion bug may still be in OmniSharp only, and not in VS Code feature. There was some confusion at the time as it was figured out.

**Comment by aeschli** [comment]
Moving to omnisharp as the project.json completion support will be provided from there in the future.

**Comment by troydai** [comment]
+1

**Comment by zigzag95** [comment]
+1

**Comment by savpek** [comment]
+1

**Comment by rchande** [comment]
Project.json support is deprecated in OmniSharp. Closing this issue.
