### ISSUE TITLE
How to disable `just my code` debugging in vscode omnisharp ?

### ISSUE THREAD

**Issue by ashishnegi** [OmniSharp/omnisharp-vscode#2361]
Thanks for this nice debugging experience.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  eb1d5ee318

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```

VS Code version: 1.22.1
C# Extension version: Not sure how to find it. Please add instructions in template.

## Steps to reproduce
Debug any app and you will find :
`Skipped loading symbols. Module is optimized and the debugger option 'Just My Code` is enabled`.

## Expected  behavior
I want to configure to load symbols for libraries as well.

## Actual behavior
Not able to load symbols for : `Skipped loading symbols. Module is optimized and the debugger option 'Just My Code` is enabled`.

## Use Case
We ship SDK to user for creating apps. To debug the code in libraries, we need to load symbols for our assemblies.

Also, please give instructions on how to use `Debugger Console` to load symbols and set multiple symbols paths for effective debugging.

**Comment by kburtram** [comment]
@gregg-miskelly do you know if there is a way to set `justMyCode: false` when launching the process via the unit test `Debug Test` command?  I couldn't find a launch.json task to set the option in that context and setting on the Attach or Launch targets didn't seem to do the trick.  Thanks!

**Comment by kburtram** [comment]
@gregg-miskelly thanks, that's exactly what I was looking for!

**Comment by Alex2357** [comment]
> @kburtram I added some instructions to this Wiki page to show how to edit those. Let me know if you have more questions --
> 
> https://github.com/OmniSharp/omnisharp-vscode/wiki/How-to-run-and-debug-unit-tests

@gregg-miskelly Hi I've got this warning

```
Step into: Stepping over operator 'VCanopy.Functions.op_ComposeLeft'. To step into properties or operators, add '"enableStepFiltering": false' to launch.json and restart debugging.
```


How do I specify '"enableStepFiltering": false' in `"csharp.unitTestDebuggingOptions"` or where I should do this?

I tried to add this way no luck

```
    "csharp.unitTestDebuggingOptions": {
        ....
        "enableStepFiltering": false,
        ....
        ....
```

**Comment by gregg-miskelly** [comment]
@Alex2357 Assuming you are debugging a unit test from the C# CodeLens, what you are doing is something that I would expect to work. I don't have the cycles to investigate today, but if you want to open a new issue hopefully I can take a look later.

**Comment by Alex2357** [comment]
> @Alex2357 Assuming you are debugging a unit test from the C# CodeLens, what you are doing is something that I would expect to work. I don't have the cycles to investigate today, but if you want to open a new issue hopefully I can take a look later.

I was debugging NUnit test using F# Neptune plugin. I will try tomorrow to do this again on another machine to confirm that the mapping for source files worked or not and if it mapping works but `"enableStepFiltering": false` doesn't I will open new issue.

**Comment by gregg-miskelly** [comment]
@Alex2357 This extension's code to debug unit tests would only be used if your unit test is written in C#.

**Comment by AlissonRS** [comment]
@gregg-miskelly not sure if related,  but is there a way to disable the messages below without setting `justMyCode: false`?

```
Loaded '[C:\Users\siri\repos\steppwize\bolao-futebol\web\BolaoFutebol.Lambda\bin\Debug\netcoreapp3.1\Amazon.Lambda.Serialization.Json.dll]()'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '[C:\Users\siri\repos\steppwize\bolao-futebol\web\BolaoFutebol.Lambda\bin\Debug\netcoreapp3.1\Microsoft.Extensions.Configuration.UserSecrets.dll]()'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '[C:\Users\siri\repos\steppwize\bolao-futebol\web\BolaoFutebol.Lambda\bin\Debug\netcoreapp3.1\Newtonsoft.Json.dll]()'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '[C:\Program]() Files\dotnet\shared\Microsoft.NETCore.App\3.1.22\System.Runtime.Serialization.Formatters.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
```

I get lots of these warnings, how to disable them?

**Comment by AlissonRS** [comment]
Thanks for the extremely fast reply @gregg-miskelly, it worked like a charm.
