### ISSUE TITLE
OmniSharp fails to load properly

### ISSUE THREAD

**Issue by swakdaddy** [OmniSharp/omnisharp-vscode#2362]
I just did a fresh install of VSCode and extensions following this guide to the letter including reboots.
https://code.visualstudio.com/docs/other/unity
I've tried uninstalling and reinstalling C# extension several times to no avail.  Help would be great! Thanks.

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

VS Code version: 1.23.1
C# Extension version: 1.15.2

## Steps to reproduce
1) Load VSCode
2) Open a .cs file, edit it, save.
3) Wait for OmniSharp to startup and throw 130 errors.

## Expected  behavior
It won't have errors.

## Actual behavior
It has errors.
Here is the output:

Starting OmniSharp server at 6/3/2018, 6:27:56 PM
    Target: e:\dev\rsg_svn\FP1\FP1\FP1.sln

OmniSharp server started
    Path: C:\Users\David\.vscode\extensions\ms-vscode.csharp-1.15.2\.omnisharp\1.30.1\OmniSharp.exe
    PID: 2868

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2017 15.5.27130.2003 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\David\.vscode\extensions\ms-vscode.csharp-1.15.2\.omnisharp\1.30.1\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2017 15.5.27130.2003 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'e:\dev\rsg_svn\FP1\FP1'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in e:\dev\rsg_svn\FP1\FP1
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'e:\dev\rsg_svn\FP1\FP1\FP1.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\dev\rsg_svn\FP1\FP1\Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\dev\rsg_svn\FP1\FP1\Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'e:\dev\rsg_svn\FP1\FP1'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\dev\rsg_svn\FP1\FP1\Assembly-CSharp.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'e:\dev\rsg_svn\FP1\FP1' on host 9592.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'e:\dev\rsg_svn\FP1\FP1\Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\dev\rsg_svn\FP1\FP1\Assembly-CSharp-Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin" directory.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'e:\dev\rsg_svn\FP1\FP1\Assembly-CSharp-Editor.csproj'.
e:\dev\rsg_svn\FP1\FP1\Assembly-CSharp-Editor.csproj
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1601,5): Error: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin" directory.

**Comment by swakdaddy** [comment]
I also deleted all of my .sln and .csproj files and had Unity regenerate them with no luck.

**Comment by swakdaddy** [comment]
Interestingly, I updated Visual Studio Community 2017, rebooted, and on a whim tried VSCode to see if it fixed this.  It did.

**Comment by DustinCampbell** [comment]
@swakdaddy : That is actually expected. From your log above, I can see that OmniSharp is using the MSBuild toolset in VS Community:

```
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2017 15.5.27130.2003 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\David\.vscode\extensions\ms-vscode.csharp-1.15.2\.omnisharp\1.30.1\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2017 15.5.27130.2003 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
```

So, updating VS Community updated the MSBuild toolset that OmniSharp is using.
