### ISSUE TITLE
"Spawn unknown" error when trying to debug on a Windows ARM device

### ISSUE THREAD

**Issue by Depechie** [OmniSharp/omnisharp-vscode#2366]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\2.1.105\

Microsoft .NET Core Shared Framework Host
  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

VS Code version:
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:38.209Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

C# Extension version: 
1.15.2

## Steps to reproduce
Create new folder on disk
Stub out .net asp web api project with command line code "dotnet new webapi"
Open project in VS Code
Press F5 to start debugging

## Expected  behavior
Able to see debugger in VS Code and step through code while website is active in MS Edge

## Actual behavior
Getting exception "Spawn unknown" and no active debugging session

**Comment by gregg-miskelly** [comment]
@Depechie: A few questions -

Where does the 'spawn unknown' error message show up? 
Is that the full text of it?
Is anything written to the debug console?
Do you see this with all .NET project types (ex: a console app)?

**Comment by gregg-miskelly** [comment]
@Depechie you are running VS Code on a Windows on ARM device? Or you are trying to remote debug to Windows on ARM?

**Comment by Depechie** [comment]
Running everything locally on a Windows on ARM device...

**Comment by gregg-miskelly** [comment]
The C# debug adapter runs in an x64 process. So it will not run on a Windows on ARM device.

**Comment by Depechie** [comment]
Haaa. I see! This means no x86 version will be made available? Or a compiled ARM64 bit version?

**Comment by gregg-miskelly** [comment]
For the C# extension, currently the only available Windows version is x64. Today, the only Windows on ARM debugging support we have is that full VS supports remote debugging to a Windows on ARM computer. 

Its certainly possible that we will release support for other processors in the future. We generally make this determination based on usage. So far, you are the first person to request this support.

**Comment by Depechie** [comment]
Thx for the detailed clarification!
Yeah the ARM devices are not yet so common especially outside the USA.
I'll expect there will be an uptake when the snapdragon 850 chip devices will be made available.
