### ISSUE TITLE
Option to turn off snippets

### ISSUE THREAD

**Issue by Taugeshtu** [OmniSharp/omnisharp-vscode#2368]
A feature request.
It would be really cool to have an option to turn off snippets built into extension. They always get into my way, and modifying "csharp.json" file in "Snippets" folder of the extension is only working until VSCode relaunch (then extension files regenerate).

I don't know if it's possible to do though.

**Comment by SirIntruder** [comment]
Does modifying "editor.snippetSuggestions" setting works for you?

**Comment by Taugeshtu** [comment]
Unfortunately, it doesn't. I have a few of my own snippets that I do want to see "inline"-d, but C# extension's snippets get in the way.

**Comment by rchande** [comment]
@Taugeshtu I'm not sure this is something we can address from the C# extension. The extension model requires us to declare our snippets file in our package.json (https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_add-to-your-language-support-extension) which causes VS Code to always load them. I would recommend refiling this issue against https://github.com/Microsoft/vscode. 

I'm going to close this issue but feel free to add further comments if you think there's something we can do on our side. Thanks!
