### ISSUE TITLE
Object initializer

### ISSUE THREAD

**Issue by branciat** [OmniSharp/omnisharp-vscode#237]
Hi,

It would be useful to have the auto-completion properties in object initialization.

example
```
FooClass = new FooClass () {
    PropFoo <= "Here auto-complete proposition"
};

```

**Comment by DustinCampbell** [comment]
I definitely agree. Making the completion list support more faithful to what we have in Visual Studio is something we're actively working on.

Issue:
* https://github.com/OmniSharp/omnisharp-roslyn/issues/78

PRs (in progress): 
* https://github.com/dotnet/roslyn/pull/8170
* https://github.com/dotnet/roslyn/pull/10666

**Comment by branciat** [comment]
Ah ok ! sorry, i was on the wrong repository.
Thank for the link.

**Comment by DustinCampbell** [comment]
Not really. There's just several related repos.
