### ISSUE TITLE
Can't download omnisharp 1.30.1

### ISSUE THREAD

**Issue by jalcim** [OmniSharp/omnisharp-vscode#2373]
Issue Type: <b>Bug</b>

Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' 	Retrying from 'https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.30.1.zip' Failed at stage: downloadAndInstallPackages
Error: getaddrinfo ENOTFOUND download.visualstudio.microsoft.com download.visualstudio.microsoft.com:443

Extension version: 1.15.2
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (4.76GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by gregg-miskelly** [comment]
@jalcim This likely means that either you aren't connected to the internet, or your computer accesses the internet through an HTTP proxy.

If you are using an HTTP proxy, you need to configure it in your Preferences->Settings file. Here are the settings:

  // The proxy setting to use. If not set will be taken from the http_proxy and https_proxy environment variables
  "http.proxy": "",

  // Whether the proxy server certificate should be verified against the list of supplied CAs.
  "http.proxyStrictSSL": true,

  // The value to send as the 'Proxy-Authorization' header for every network request.
  "http.proxyAuthorization": null

**Comment by GabrielMariusPopescu** [comment]
Tried what @gregg-miskelly suggested step by step, but for some reason it didn't work. 
However, I found another way to fix this one: download and unzip files from https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.30.1.zip into the C:\Users\USERNAME\.vscode\extensions\ms-vscode.csharp-1.15.2\.omnisharp\1.30.1 and omnisharp server will run each time you load up a project into visual studio code.

**Comment by akshita31** [comment]
@jalcim Did it work for you ?

**Comment by breake** [comment]
@akshita31 take a look on https://vnextcoder.wordpress.com/2018/05/23/install-omnisharp-win-x64-1-30-1-zip-vs-debugger-for-vs-code-manually/

**Comment by GabrielMariusPopescu** [comment]
The issue was solved. Now, Omnisharp is working as expected

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
