### ISSUE TITLE
Not loading unity solution

### ISSUE THREAD

**Issue by tavichh** [OmniSharp/omnisharp-vscode#2375]
## Environment data
`dotnet --info` output:
 Version:            1.1.9
 Commit SHA-1 hash:  77f0268904

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.1.9
VS Code version: 1.24.0

C# Extension version: Latest on VSCode Repo

## Steps to reproduce
Re-installed Windows. Then, installed Unity and finally VSCode.
Also have tried reinstalling Unity and then VSCode and VSCode and then Unity.

## Expected  behavior
Intellisense should be loading snippets from a unity snippet extension 

## Actual behavior
Its not detecting whether or not im in a method or a class. I only have access to the basic C# functionality and the solution is not being loaded. I have tried manually choosing the solution in VSCode by pressing F1, and also deleting the .sln & .csproj files. In other words, the UnityEngine.dll is not being loaded at all. This isn't an issue tied to the snippet extension because I have tried five of them and none of them work. Also, there is no flame at the bottom as it should be to denote that I am in a solution.

**Comment by tavichh** [comment]
Also, there is no flame at the bottom as it should be to denote that I am in a solution.

**Comment by DustinCampbell** [comment]
Hi @tavichh, could you provide your OmniSharp Log after loading your project in VS Code? You can retrieve this by selecting View->Output from the VS Code main menu and then picking "OmniSharp Log" from the top-right corner of the Output Pane.

**Comment by tavichh** [comment]
**Sure thing!**

> Starting OmniSharp server at 6/12/2018, 6:33:00 PM
>     Target: d:\Projects\Submarine Game\Submarine Game.sln
> 
> [ERROR] Error: spawn cmd ENOENT
