### ISSUE TITLE
Not recognized as an internal or external command

### ISSUE THREAD

**Issue by Isatol** [OmniSharp/omnisharp-vscode#2380]
## Environment data
`dotnet --info` output:
Herramientas de la línea de comandos .NET (2.1.104)

Product Information:
 Version:            2.1.104
 Commit SHA-1 hash:  48ec687460

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.104\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
VS Code version: 2.1.104
C# Extension version: 1.15.2

## Steps to reproduce
Start Visual Studio with C# Code and my User Path not recognized as an internal or external command. Nothing more.

The server try to start but nothing more happens.

## Expected  behavior
Working with intellisense

## Actual behavior
The server is not started

**Comment by rchande** [comment]
@Isatol Please share your omnisharp log.

**Comment by Isatol** [comment]
@rchande here:
Starting OmniSharp server at 2018-6-23 00:04:46
    Target: c:\HACSYS\netcore-vuejs\MarczakIO.VueSPA.Web.sln

OmniSharp server started
    Path: C:\Users\Analista(Hacsys)\.vscode\extensions\ms-vscode.csharp-1.15.2\.omnisharp\1.30.1\OmniSharp.exe
    PID: 1100

"C:\Users\Analista" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).


My Name is based in Azure AD: Analista(Hac), i think this is the problem

**Comment by cartermp** [comment]
Yes, this seems like an upstream MSBuild problem. It can't read your project because of the pathing used on your machine.
