### ISSUE TITLE
Comment in try-catch exception parameter not highlighting

### ISSUE THREAD

**Issue by nmkataoka** [OmniSharp/omnisharp-vscode#2384]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]

VS Code version: 1.24.0
C# Extension version: 1.15.2

## Steps to reproduce
```
try { /* Stuff */ }
catch ( ExceptionType /* This comment isn't highlighted as a comment */ ) { /* stuff */ }
```

This is part of example code from the ASP.Net Core tutorials https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud?view=aspnetcore-2.1

## Expected  behavior
The comment inside the parentheses should be highlighted as a comment.

## Actual behavior
The comment inside the parentheses is highlighted as a variable name, as if it were an ExceptionType.

**Comment by rchande** [comment]
Moved to https://github.com/dotnet/csharp-tmLanguage/issues/127
