### ISSUE TITLE
Before update to DotNetCore SDK 2.1 (2.1.301) can't load my project.

### ISSUE THREAD

**Issue by guiuprado** [OmniSharp/omnisharp-vscode#2397]
Hi, if can help i will very much grateful.

## Environment data
user@vm-dev-01:~$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

user@vm-dev-01:~$ mono --version
Mono JIT compiler version 5.12.0.226 (tarball Thu May  3 09:48:32 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)

VS Code version:
C# Extension version:
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:47:35.732Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

## Steps to reproduce
I just try to open my workspace with the new update sdk of dotnet core release recently. I spend some some hours to figure out but without any progress.

## Expected  behavior
Open the workspace, and all the projects without get fails error on log.

## Actual behavior
I can't use the extension, the intellisense   not work, the go-to definitions, because the project can be load correctly.

## How the problematic project is setup.
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MathNet.Numerics.Core" Version="3.17.0" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="2.3.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="5.2.2" />
    <PackageReference Include="Microsoft.NETCore.App" Version="2.1.1" />
    <PackageReference Include="Newtonsoft.Json.Schema" Version="3.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="2.5.0" />
  </ItemGroup>
  <ItemGroup>
    <None Include="wwwroot\sample.html" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\cognatis-sharedlib\cognatis.sharedlib\cognatis.sharedlib.csproj" />
    <ProjectReference Include="..\cognatis.eventlog.backend\cognatis.eventlog.backend.csproj" />
  </ItemGroup>
</Project>

## The Log I get.

Starting OmniSharp server at 6/29/2018, 12:15:32 PM
    Target: /mnt/data/project/cognatis/dev-cognatis-ntl4-eventlog/dev-cognatis-ntl4-eventlog.sln

OmniSharp server started with Mono 5.12.0
    Path: /home/user/.vscode/extensions/ms-vscode.csharp-1.15.2/.omnisharp/1.30.1/omnisharp/OmniSharp.exe
    PID: 31022

﻿[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 16.4 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/usr/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/home/user/.vscode/extensions/ms-vscode.csharp-1.15.2/.omnisharp/1.30.1/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/usr/lib/mono/msbuild/15.0/bin"
            CscToolPath = /home/user/.vscode/extensions/ms-vscode.csharp-1.15.2/.omnisharp/1.30.1/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/mnt/data/project/cognatis/dev-cognatis-ntl4-eventlog'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /mnt/data/project/cognatis/dev-cognatis-ntl4-eventlog
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/mnt/data/project/cognatis/dev-cognatis-ntl4-eventlog/dev-cognatis-ntl4-eventlog.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mnt/data/project/cognatis/dev-cognatis-ntl4-eventlog/cognatis.eventlog.webapiend/cognatis.eventlog.webapiend.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mnt/data/project/cognatis/dev-cognatis-ntl4-eventlog/cognatis.eventlog.backend/cognatis.eventlog.backend.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mnt/data/project/cognatis/dev-cognatis-ntl4-eventlog/cognatis.eventlog.test/cognatis.eventlog.test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mnt/data/project/cognatis/dev-cognatis-ntl4-eventlog/cognatis-sharedlib/cognatis.sharedlib/cognatis.sharedlib.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/mnt/data/project/cognatis/dev-cognatis-ntl4-eventlog'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /mnt/data/project/cognatis/dev-cognatis-ntl4-eventlog/cognatis.eventlog.webapiend/cognatis.eventlog.webapiend.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/mnt/data/project/cognatis/dev-cognatis-ntl4-eventlog' on host 30907.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The project was restored using Microsoft.NETCore.App version 2.1.1, but with current settings, version 2.1.0 would be used instead.  To resolve this issue, make sure the same settings are used for restore and for subsequent operations such as build or publish.  Typically this issue can occur if the RuntimeIdentifier property is set during build or publish but not during restore.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/mnt/data/project/cognatis/dev-cognatis-ntl4-eventlog/cognatis.eventlog.webapiend/cognatis.eventlog.webapiend.csproj'.
/mnt/data/project/cognatis/dev-cognatis-ntl4-eventlog/cognatis.eventlog.webapiend/cognatis.eventlog.webapiend.csproj
/mnt/data/project/cognatis/dev-cognatis-ntl4-eventlog/cognatis.eventlog.webapiend/cognatis.eventlog.webapiend.csproj(0,0): Error: The project was restored using Microsoft.NETCore.App version 2.1.1, but with current settings, version 2.1.0 would be used instead.  To resolve this issue, make sure the same settings are used for restore and for subsequent operations such as build or publish.  Typically this issue can occur if the RuntimeIdentifier property is set during build or publish but not during restore.

**Comment by guiuprado** [comment]
Hi after post here I try to modify my project files.
I point then to Microsoft.NETCore.App version 2.1.0 instead to Microsoft.NETCore.App version 2.1.1.
After clean all bin and obj, and reload all apparently is working again.

**Comment by akshita31** [comment]
@guiuprado Glad to know it worked.

Will go ahead and close this for now. Feel free to reopen it if you happen to run into this again.
