### ISSUE TITLE
Browser doesn't launch on debug when using IntegratedTerminal or ExternalTerminal

### ISSUE THREAD

**Issue by achandlerwhite** [OmniSharp/omnisharp-vscode#2399]
Since the default in ASP.NET Core is to send logging to both console and debugger this results in all logging messages duplicated in the debugger console under default settings. I switched to use the integrated or external terminals so the console logging goes to those, but I noticed the browser no longer launches. Thanks.

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

VS Code version: 1.24.1

C# Extension version: 1.15.2

## Steps to reproduce
Create a new default ASP.NET Core web app:
`dotnet new mvc`

Open vscode and load the project. Let the default .vscode config stuff happen.

Change the launch.json config to set the console to `IntegratedTerminal` or `ExternalTerminal`

Debug the program.

## Expected  behavior

Project starts and browser is opened to the app.

## Actual behavior

Project starts, but the browser is never opened.

**Comment by gregg-miskelly** [comment]
@achandlerwhite Correct - the way the browser launch code works, it can only work when the terminal output is sent to the debugger. I believe you can use the `logging` options if you like console output from going to the terminal.

**Comment by achandlerwhite** [comment]
@gregg-miskelly Thanks for the quick response. I can use the logging options as you describe or probably just open the browser myself--it's not a major issue. Is this quirk documented either in the vscode or omnisharp-vscode docs? I thought maybe it was and I just missed it.

**Comment by gregg-miskelly** [comment]
Documentation will be fixed in https://github.com/OmniSharp/omnisharp-vscode/pull/2458
