### ISSUE TITLE
Omnisharp doesn't file watch *.props in /obj folder

### ISSUE THREAD

**Issue by forki** [OmniSharp/omnisharp-vscode#2407]
Omnisharp doesn't file watch *.props in /obj folder, but this is needed in order to update NuGet dependencies that my be put there by tools like Paket

**Comment by DustinCampbell** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#1254

**Comment by DustinCampbell** [comment]
I've moved this over to omnisharp-roslyn where the work would take place.
