### ISSUE TITLE
OmniSharp not working on linux

### ISSUE THREAD

**Issue by lucianposton** [OmniSharp/omnisharp-vscode#2413]
## Environment data
`dotnet --info` output: https://paste.pound-python.org/show/heAxiZ7vg4JUzEZ30Vzb/
VS Code version: 1.22.1 and 1.25.0
C# Extension version: 1.15.2

## Steps to reproduce
Opened https://github.com/Interkarma/daggerfall-unity in unity-editor to generate .sln and .csproj (Assets->Open C# Project). Then opened project in VSCode-1.25.0 w/ ms-vscode.csharp-1.15.2.

Also, tried simple console program. `dotnet new console`. Opened Program.cs.

## Expected  behavior
Expect omnisharp/intellisense to be enabled. No option to "Find All References" in r-click menu. Shift-f12 doesn't "Find All References". etc

## Actual behavior
No omnisharp/intellisense.

No fire icon in bottom right of status bar.
![status](https://i.imgur.com/eRvRg4O.png)

No "OmniSharp" option in pulldown of Output window.

Output of "Extensions"
![extensions](https://i.imgur.com/Ol9Ji2q.png)

Output of "Log (Extension Host)"
![LogExtensionHost](https://i.imgur.com/B8mtj5K.png)

The binary is a windows executable. See https://paste.pound-python.org/show/PuSrFzifPXwmq38GEdFQ/

**Comment by akshita31** [comment]
@lucianposton I suspect, the problem here is that your project doesnot contain a csproj and currently omnisharp doesnot support files that are not associated to a project. I am currently working on it and hope to deliver it as soon as possible.

Could you try opening the whole project when you do a dotnet new console (instead of just the Program.cs file) and seeing if the extension lights up ?

**Comment by rchande** [comment]
@akshita31 Can you take a look?

**Comment by lucianposton** [comment]
I've figured out the issue. VScode was incorrectly configured and packaged in my distro's package manager. The execute bit was missing from some secondary VScode utilities, causing silent failures. I've since fixed and updated the package.

**Comment by rchande** [comment]
@lucianposton Interesting. How did you determine that? Might be helpful to others to know...

**Comment by lucianposton** [comment]
I compared the files installed by the package manager to what was contained in the tar/deb from visualstudio.com. Some files installed on the system weren't executable like in the tar/deb.

**Comment by brogan89** [comment]
I know this has been closed now, but just in case others have issues and find them selves here. I had a similar issue on MX Linux. I solved it by installed `mono-devel` and `msbuild` packages. - Probably obvious to linux users but I'm a bit of linux noob so it wasn't so obvious at first.

**Comment by jsdev17** [comment]
@lucianposton I'm having this issue.
Can you please share steps to fix it?
