### ISSUE TITLE
Adopt improved DocumentSymbolProvider API

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#2414]
With the 1.25 release we have finalised the API for the [outline tree](https://code.visualstudio.com/updates/v1_25#_outline-view). A `DocumentSymbolProvider` should now return [document symbols](https://github.com/Microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/src/vs/vscode.d.ts#L2474) which can represent a hierarchy and that can differentiate between the full range of  a symbol and the selection range, e.g. the name of a function. 

*Note* that we synthesise trees using range-containment when a provider returns `SymbolInformation`-objects and that that isn't perfect. Adopting the new API makes the outline more robust and support features like follow-cursor and diagnostics association. 

Let me know if need more information is needed. Happy Coding!

**Comment by jrieken** [comment]
It will show with the label but only when selected. Like so: 
<img width="197" alt="screen shot 2018-09-06 at 08 53 08" src="https://user-images.githubusercontent.com/1794099/45140188-4d102980-b1b2-11e8-84eb-a49c303be6e7.png">

**Comment by akshita31** [comment]
@jrieken I adopted the new API in this PR: https://github.com/OmniSharp/omnisharp-vscode/pull/2490. However the integration test is failing. It is still returning the symbol information type and when i query on the "detail", I am getting undefined. Any idea what might be happening here ?

**Comment by jrieken** [comment]
> t is still returning the symbol information type and when i query on the "detail",

Are you using the api command in that test?

**Comment by akshita31** [comment]
@jrieken This is [the test](https://github.com/OmniSharp/omnisharp-vscode/pull/2490/files#diff-3914e9c63d0b3334f21cb14aba14f661R43). I am using : 
`<vscode.DocumentSymbol[]>await vscode.commands.executeCommand("vscode.executeDocumentSymbolProvider", fileUri);` to get the document symbols. The symbols are as expected h but they are of type SymbolInformation.

**Comment by jrieken** [comment]
Yeah, there is currently a backwards compatibility challenge. It's tracked here and will be tackled this month: https://github.com/Microsoft/vscode/issues/57984

**Comment by akshita31** [comment]
From @DustinCampbell 
> Is this still hierarchical? Do we need to populate the [`children`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2569-L2572) property on [`DocumentSymbol`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#DocumentSymbol)? Or, does that happen automatically passed on the ranges that are passed in?

@jrieken The constructor for the document symbol doesnot have a filed for specifying the children. Do we need to create the object first and then populate the children ?

**Comment by jrieken** [comment]
Yes, you need to populate the children
