### ISSUE TITLE
Intellisense in object initializers is unaware of context

### ISSUE THREAD

**Issue by masaeedu** [OmniSharp/omnisharp-vscode#2417]
## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.301 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.1.1 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

VS Code version:

```
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:47:35.732Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

C# Extension version: 1.15.2

## Steps to reproduce
Instantiate an object with an enum property and in the RHS of the property initializer for said property use `Ctrl + Space` to get intellisense suggestions.

## Expected  behavior
Enum type's name is suggested on RHS of equals expression.

## Actual behavior
Lots of things are displayed that would not type check if inserted into the current position and the enum is not in the list.

![screenshot](http://i.imgur.com/Wt6DQpV.png)

**Comment by akshita31** [comment]
@masaeedu I suspect the OmniSharp process is not running for you. Do you see any "OmniSharp" or "C#" log in the Output  pane(View--> Output --> The small drop down on the right side)

**Comment by masaeedu** [comment]
@akshita31 Seems to be running fine (from my experience the hover hint shown wouldn't appear if Omnisharp wasn't running). Go to reference, hovering types, etc. all seems to be working.
