### ISSUE TITLE
[C#] After debug shows DebugAdapter bin folder not found on path 

### ISSUE THREAD

**Issue by ChuanjenWang** [OmniSharp/omnisharp-vscode#242]
I'm a newbie of using visual studio code. I would like to try run C# console application on my Mac, but after I press debug button, it shows following error message. I passed my launch.json and task.json for reference. 

DebugAdapter bin folder not found on path /Users/ChuanJen/.vscode/extensions/ms-vscode.csharp-0.3.7/coreclr-debug/debug

**launch.json**
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": ".NET Core Launch (console)",
			"type": "coreclr",
			"request": "launch",
			"preLaunchTask": "build",
			"program": "${workspaceRoot}/Program.exe",
			"args": [],
			"cwd": "${workspaceRoot}",
			"stopAtEntry": false
		},
		{
			"name": ".NET Core Launch (web)",
			"type": "coreclr",
			"request": "launch",
			"preLaunchTask": "build",
			"program": "${workspaceRoot}/<path-to-program>",
			"args": [],
			"cwd": "${workspaceRoot}",
			"stopAtEntry": false,
			"launchBrowser": {
				"enabled": true,
				"args": "${auto-detect-url}",
				"windows": {
					"command": "cmd.exe",
					"args": "/C start ${auto-detect-url}"
				},
				"osx": {
					"command": "open"
				},
				"linux": {
					"command": "xdg-open"
				}
			}
		},
		{
			"name": ".NET Core Attach",
			"type": "coreclr",
			"request": "attach",
			"processName": "<example>"
		}
	]
}

**task.json**
{
	// See http://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "dotnet",
	"isShellCommand": true,
	"args": [],
	"tasks": [
		{
			"taskName": "build",
			"args": [ ],
			"isBuildCommand": true,
			"showOutput": "silent",
			"problemMatcher": "$msCompile"
		}
	]
}

**Comment by chuckries** [comment]
@ChuanjenWang What is the output of `dotnet --info`? It is likely you have a version of the dotnet cli that is not compatible with version 0.3.7 of the extension.

**Comment by ChuanjenWang** [comment]
my output shows "Failed to launch external program dotnet .spawn dotnet ENOENT"

I don't understand all my things are the latest version, I just got from yeomen, why I have a "not compatible" problem?

**Comment by chuckries** [comment]
If `dotnet --info` is failing, it means that your installation of the .net cli is bad. The debugger extension is dependent on the dotnet cli for full installation. The instructions [here](https://github.com/gregg-miskelly/omnisharp-vscode/blob/daily-build-docs/debugger.md) will explain how to uninstall your existing dotnet cli, install the latest cli for mac, and install the latest version of the extension from [here](https://github.com/OmniSharp/omnisharp-vscode/releases). Please let me know if that is not clear.

**Comment by ChuanjenWang** [comment]
@chuckries , it's work, however, when I debug there is another warning message. Any suggestion?


WARNING: The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use NETStandard 1.0.0-rc2-23901 or newer. This may be expected if the target process did not run .NET code.
The program '/Users/ChuanJen/LeetCode_Practice2/TestS/bin/Debug/dnx451/TestS.exe' has exited with code 1 (0x00000001).

**Comment by gregg-miskelly** [comment]
The fact that you have 'dnx451' in your path leads me to think (possibly incorrectly) that you aren't building a .NET Core RC2+-based app. Is that correct? The C# extension debugger can only debug RC2 and newer.

**Comment by ChuanjenWang** [comment]
@gregg-miskelly I use yeoman to build a Console Application, basically it's a c# console app, I guess it should be work? if I would like to execute C# on my mac what should I do?

**Comment by gregg-miskelly** [comment]
I don't have personal experience with the yeoman generators for C#, but since RC2 hasn't yet been publicly released yet, I am guessing they are still going to be RC1-based. RC2 should be out soon. So if you want a smooth path, you might want to wait. But if you want to start playing now, you can follow http://aka.ms/vscclrdogfood. Let us know if you run into problem.

**Comment by ChuanjenWang** [comment]
I guess you are right! if I build project directly without yeoman, it's works perfectly. So using yeoman to build project is incompatible with current RC2 version. Thanks!
