### ISSUE TITLE
No Intellisense without Project

### ISSUE THREAD

**Issue by MarekLg** [OmniSharp/omnisharp-vscode#2424]
## Expected  behavior
Intellisense predicting more than 'class' or 'if' on a .cs file without a project.json

## Actual behavior
Intellisense not predicting more than 'class' or 'if' on a .cs file without a project.json

## Issue
Sorry for that minimal intro..
I would be perfectly fine to live with that, but on [this issue](https://github.com/OmniSharp/omnisharp-vscode/issues/47) from Feb 2016 it is stated that single-file-Intelisense would "definitely be work[ed].. on"
So.. are there any updates yet or am I just missing something?

Thank you for your time!

**Comment by rchande** [comment]
@akshita31 Is working on this.

**Comment by DustinCampbell** [comment]
@rchande : Is there an issue tracking that work?

**Comment by akshita31** [comment]
@DustinCampbell Yes we have an issue here : https://github.com/OmniSharp/omnisharp-roslyn/issues/207.

**Comment by DustinCampbell** [comment]
OK. In that case, I'll go ahead and dupe this against https://github.com/OmniSharp/omnisharp-roslyn/issues/207 and https://github.com/OmniSharp/omnisharp-vscode/issues/47.

@MarekLg: Your question was somewhat timely. This feature is currently being worked on here: https://github.com/OmniSharp/omnisharp-roslyn/pull/1252

**Comment by shubhcosmos** [comment]
Workaround 

Uninstall extension close vs code , Delete  vscode\extensions\ms-vscode.csharp-1.16.2 

Reinstall

Even the intellisence which was not working started working.
