### ISSUE TITLE
Why only register providers for language:csharp scheme:file ?

### ISSUE THREAD

**Issue by NTaylorMullen** [OmniSharp/omnisharp-vscode#2427]
Just had a question, I've been playing around with Omnisharp recently and have been spinning up virtual C# documents. I noticed that I wasn't getting any sort of C# support for virtual documents and I found out it was related to the file:schema [document selector](https://github.com/OmniSharp/omnisharp-vscode/blob/16c554692882ce6929ab800253632a4d2d93e893/src/omnisharp/extension.ts#L44). Is there any reason why C# providers only attach to csharp files on disk?

**Comment by rchande** [comment]
I'm not even sure this has any effect: I tried the following and got intelliense.
1. Open VS Code in an empty directory
2. Use the terminal do execute `dotnet new console` in the directory but don't open any of the new .cs or .csproj files
3. Create a new .cs file and don't save it.
4. Start typing in that new file without saving
5. Extension gets activated and intellisense works.

Especially now that @akshita31 is investigating handling files without an associated project, I think we can drop this requirement.

**Comment by NTaylorMullen** [comment]
Looks like the diagnostic adapter also makes this assumption:
https://github.com/OmniSharp/omnisharp-vscode/blob/16c554692882ce6929ab800253632a4d2d93e893/src/features/diagnosticsProvider.ts#L143
and 
https://github.com/OmniSharp/omnisharp-vscode/blob/16c554692882ce6929ab800253632a4d2d93e893/src/features/diagnosticsProvider.ts#L175

**Comment by akshita31** [comment]
@NTaylorMullen Can we close this now ?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen Can we close this now ?

Done!
