### ISSUE TITLE
Modifying conditional breakpoints while debugging does not work due to VSCode change

### ISSUE THREAD

**Issue by WardenGnaw** [OmniSharp/omnisharp-vscode#2428]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.400-preview-009088
 Commit:    0ef0b3296b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.400-preview-009088\

VS Code version: 1.25.1

C# Extension version: v1.15.2 

## Steps to reproduce
Create C# project and create a conditional breakpoint that will be true. Start debugging. Once you hit the breakpoint, change it to a false statement. F5.

## Expected  behavior
Once it becomes a false statement, it should not hit the breakpoint.

## Actual behavior
It will always hit the breakpoint due to the original condition

## Issue reason:
VSCode changed how they updated breakpoints. Instead of removing then adding a new breakpoint, they use the same breakpoint id.

See: https://github.com/Microsoft/vscode/issues/42200

**Comment by menorless** [comment]
why closed this issue? 
The  conditional breakpoints doesn't work yet with c#.

**Comment by gregg-miskelly** [comment]
@menorless If you are seeing issues with conditional breakpoints, please open a new issue with details. The problem that this issue tracked was fixed in 1.16.
