### ISSUE TITLE
Partial class code navigation is messed up

### ISSUE THREAD

**Issue by WeAthFoLD** [OmniSharp/omnisharp-vscode#2433]
## Environment data
`dotnet --info` output:
```
.NET Core SDK（反映任何 global.json）:
 Version:   2.1.301
 Commit:    59524873d6

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.301\

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS Code version: `1.25.1`
C# Extension version: `1.15.2`

## Steps to reproduce

I'm working on a large Unity project with more than 100K lines. The project is private so I could not provide the problematic source. If necesary I will try to isolate a project that reproduces this problem.

## Expected  behavior

F12 would jump to correct place of function implementation, and reference counts show in correct positions.

## Actual behavior

The problem is there is a partial class `NetworkManager`, which is implemented separately in two C# files, `A` and `B`, A is ~1000lines and B is ~6000lines.

Function `Func` is implemented in `B`. When I use F12 on a `instanceOfNetworkManager.Func()` call site to jump to its implementation, it erroneously jumps to an empty line in `B`. The line number is different to the line of `Func` implementation in `B`, and I didn't find clear correspondence between wrong line numbers and actual line numbers.

The display position of function references count also look messed up:

(In file `B`)
![tim 20180725121914](https://user-images.githubusercontent.com/3516419/43179351-02a143d0-9005-11e8-9d41-5d6c880fb787.png)

(In file `B`)
![tim 20180725122157](https://user-images.githubusercontent.com/3516419/43179424-729eda26-9005-11e8-9f44-17205f86800d.png)
The function's actual implementation is here, but has no reference count:
![tim 20180725122222](https://user-images.githubusercontent.com/3516419/43179427-74f69548-9005-11e8-8e1e-f753fa962353.png)

Those problems appear particularly in file `B`, file `A` seems all normal.

**Comment by rchande** [comment]
@WeAthFoLD Thanks for taking the time to file this. Off the top of my head, this almost sounds like a VS Code editor bug with long files. I wonder if would be possible for you to break up the 6000 line file into smaller ones and see if the issue persists? There isn't really any code in omnisharp that cares about file length.

**Comment by rchande** [comment]
Ping @WeAthFoLD

**Comment by WeAthFoLD** [comment]
Sorry I am busy past few days :/ Actually when I check the same file again now, the behaviour is all correct, so even I can't reproduce the bug. I think it's best to close this issue for now, and will file another one when the same problem appears again & I can find a way to reproduce it.
