### ISSUE TITLE
Debugger crashes on Linux when debugging stops

### ISSUE THREAD

**Issue by jchand99** [OmniSharp/omnisharp-vscode#2439]
## Environment data
`dotnet --info` output:
NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/opt/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version: 1.25.1
C# Extension version: 1.15.2

## Steps to reproduce
In launch.json, set "console": to either "integratedTerminal" or "externalTerminal" and run a program like hello world.

## Expected  behavior
Close the program successfully.

## Actual behavior
 When the program finishes, it prints out this message in the terminal:

free(): invalid pointer
/usr/bin/bash: line 1: 28260 Aborted                 (core dumped) ''/home/kas/.vscode/extensions/ms-vscode.csharp-1.15.2/.debugger/vsdbg --interpreter=vscode --connection=/tmp/CoreFxPipe_vsdbg-ui-08464cdc40724bc882a7322eac8fca87

and the program does not stop running, you have to click the red square to get the program to exit.

**Comment by gregg-miskelly** [comment]
Thanks for the report. We actually knew about the issue, but we hadn't thought about the fact that using integratedTerminal/externalTerminal would show the problem (it happens even in internalConsole mode, but the crash gets ignored). 

This is a bug caused by a bad interaction between our code, and CoreCLR that we are working with the CoreCLR team on.

**Comment by KaspireFX** [comment]
Gotcha, I noticed it a while back, just never got to actually reporting it. I just started using the internalConsole to get my programs to exit correctly after running; glad to know you guys are on top of it.

**Comment by Xorcist77** [comment]
The debugger (version 1.16.2) is crashing for me as well on shutdown of any app with the following exception:

`bash: line 1: 10836 Segmentation fault      (core dumped) ''/home/maxeta/.vscode/extensions/ms-vscode.csharp-1.16.2/.debugger/vsdbg --interpreter=vscode --connection=/tmp/CoreFxPipe_vsdbg-ui-fbdba0b1cb564b9bac0c6dc9b15e23a3`

here is my dotnet --info:

`.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
`
I am using an external terminal, not the integrated one.
