### ISSUE TITLE
Initializing omnisharp fails for large workspaces

### ISSUE THREAD

**Issue by carl-tanner** [OmniSharp/omnisharp-vscode#244]
It looks like there is a hard coded timeout of 60 seconds in StdioOmnisharpServer._doConnect.  For large projects I'm developing (800+ projects) initial loading can take ~2 minutes.  Easy fix would be making this configurable per workspace.  Maybe the better fix would start the timeout clock on the last message written (i.e. it wouldn't timeout if projects were still being loaded).

**Comment by DustinCampbell** [comment]
Hi @carl-tanner: Sorry for taking so long to get back to you! Are you still struggling with this? I can definitely look at adding an option.

**Comment by wjk** [comment]
@DustinCampbell I’m running into this as well with my project (although it is much smaller than @carl-tanner's; I have only 38 csproj files). However, my project is a .NET Core project, which may have something to do with it taking longer to load.
