### ISSUE TITLE
Bug: A folded method also hides empty lines after it

### ISSUE THREAD

**Issue by lonix1** [OmniSharp/omnisharp-vscode#2442]
- VSCode Version: 1.25.1
- OS Version: Ubuntu 18.04.1 LTS

Steps to Reproduce:

1. In a c# file (or cshtml file)
2. Fold a method
3. It will be folded, along with empty lines after it

Example before folding:
````csharp
public void foo() {
  // some code...
}
                               // this empty line will be hidden when folding "foo()"
                               // this empty line will be hidden when folding "foo()"
                               // this empty line will be hidden when folding "foo()"
                               // this empty line will be hidden when folding "foo()"
public string Bar { get; set; }
````

Example after folding:
````csharp
public void foo() { ...
public string Bar { get; set; }
````

Example of what should occur:
````csharp
public void foo() { ...
                               // this empty line was not folded
                               // this empty line was not folded
                               // this empty line was not folded
                               // this empty line was not folded
public string Bar { get; set; }
````

I've marked this as a bug, rather than a request, because this is not how folding works with Visual Studio - which only folds code, not whitespace after it. And I assume you're aiming for parity with the IDEs, at least for c# anyway.

This is a really annoying problem, because when code is folded everything is bunched up together and you can't visually separate between them - which is why you'd use empty lines between them.

(The same problem exists for `.cshtml` files.)

**Comment by akshita31** [comment]
Ping @rchande

**Comment by DustinCampbell** [comment]
I wonder if VS is merging the code folding regions or something like that. In VS, we create code folding regions for blocks of comments.

**Comment by lonix1** [comment]
@DustinCampbell When I [posted the problem](https://github.com/Microsoft/vscode/issues/55304#issuecomment-409017687) on the vscode repo, I was told vscode doesn't do folding. Not sure what is the problem, but hope that helps.

**Comment by rchande** [comment]
@lonix1 This should be fixed in our next release.

**Comment by cartermp** [comment]
This is fixed - closing.

Before fold:

<img width="781" alt="image" src="https://user-images.githubusercontent.com/6309070/76369151-d0529400-62ef-11ea-825e-e1f2a1265d36.png">

After fold:

<img width="792" alt="image" src="https://user-images.githubusercontent.com/6309070/76369163-d9dbfc00-62ef-11ea-9ced-c5fb2280d30a.png">
