### ISSUE TITLE
Nonfunctioning Linter

### ISSUE THREAD

**Issue by GIimmer** [OmniSharp/omnisharp-vscode#2454]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

VS Code version: 1.25.1
C# Extension version: 1.15.0

## Steps to reproduce
I run a dotnet new mvc command; each with a unique name.
The environment is set to development mode.
These commands ARE being run from within the project folder

## Expected  behavior
I expect linter and tooltip suggestions
I expect Launch and tasks.json to be automatically generated

## Actual behavior
Linter does not work anywhere - for example I can say:
   int x = "hello"        and intellisense/omnisharp/linter will not catch this as an error.

I have to manually configure launch.json and tasks.json - esp. notice the 
\<insert-target-framework-here\>/\<insert-project-name-here\> sections which I have to overwrite with
netcoreapp2.0/mynamespace.dll

{
    "version": "0.2.0",
    "configurations": [
          {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/\<insert-target-framework-here\>/\<insert-project-name-here\>.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart"
        },
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/\<insert-target-framework-here\>/\<insert-project-name-here\>.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart",
            "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}

As well as Tasks which comes in as..
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet build",
            "type": "shell",
            "group": "build",
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$msCompile"
        }
    ]
}

**Comment by rchande** [comment]
@GIimmer Can you share your "OmniSharp log"?

**Comment by matkoniecz** [comment]
I have the same issue. Output-->OmniSharp log is empty for me.

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:                                                                                                                                                                         
 OS Name:     ubuntu                                                                                                                                                                         
 OS Version:  19.10                                                                                                                                                                          
 OS Platform: Linux                                                                                                                                                                          
 RID:         ubuntu.19.10-x64                                                                                                                                                               
 Base Path:   /snap/dotnet-sdk/66/sdk/3.1.200/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.200 [/snap/dotnet-sdk/66/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/snap/dotnet-sdk/66/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/snap/dotnet-sdk/66/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

```
## Environment information ##

**VSCode version**: 1.43.1
**C# Extension**: 1.21.15

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.10
 OS Platform: Linux
 RID:         ubuntu.19.10-x64
 Base Path:   /snap/dotnet-sdk/66/sdk/3.1.200/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.200 [/snap/dotnet-sdk/66/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/snap/dotnet-sdk/66/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/snap/dotnet-sdk/66/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.21.15|
|kotlin|fwcd|0.2.11|
|vscode-unitymeta|PTD|0.0.7|;

</details>
```

**Comment by JoeRobich** [comment]
@matkoniecz Can you please provide your complete OmniSharp log from the VS Code output pane?

**Comment by matkoniecz** [comment]
Output-->OmniSharp log is empty for me.

**Comment by matkoniecz** [comment]
"@akshita31 added the Needs More Info label on Sep 18, 2018"

What kind of additional info I should provide?

**Comment by cartermp** [comment]
This does not reproduce as written with the latest plugin.

There is however a repro for no tooling to show up when selecting a project/solution, covered here: #3694
