### ISSUE TITLE
C# Folding using directives

### ISSUE THREAD

**Issue by E4N** [OmniSharp/omnisharp-vscode#2455]
On Visual Studio you are able to collapse using directives but it's not the case on Code for some reasons. Could this be addressed please?

![43970786-fa3d027a-9cce-11e8-8659-461f9ef1611a](https://user-images.githubusercontent.com/28897199/44029047-3f9a832c-9efc-11e8-91b4-937485a541a7.png)

**Comment by rchande** [comment]
Looks like our Roslyn-based folding implementation misses usings.

**Comment by E4N** [comment]
So if I may ask, when do you think this will be fixed? 

Thank you.

**Comment by DustinCampbell** [comment]
@E4N : Could you verify what version of the C# for VS Code extension you are running?

@rchande : Have we actually shipped that in a C# for VS Code release yet? If not, perhaps we should just ship that functionality?

**Comment by E4N** [comment]
@DustinCampbell 1.15.2.

**Comment by DustinCampbell** [comment]
I just verified that this works as expected (the using directives are foldable) in the [latest 1.16 beta](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.16-beta2). If you're interested in trying it, you can follow [these instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases)
