### ISSUE TITLE
Constantly looping and checking for errors when "Problems" pane is open

### ISSUE THREAD

**Issue by skyflyer** [OmniSharp/omnisharp-vscode#2456]
Hello!

Perhaps the title is not spot on, but I couldn't find better words at the moment. Feel free to adjust the title. What is going on: When the "Problems" pane is focused and VS Code is focused, it is "looping" through problems periodically like it is trying to compile, recompile, recompile... It is hard to describe, so I recorded a video for you. This is happening on Mac OS Sierra and High Sierra.

## Environment data
`dotnet --info` output:

<details>
<summary>dotnet --info output</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  1.0.0-preview1-002702 [/usr/local/share/dotnet/sdk]
  1.0.1 [/usr/local/share/dotnet/sdk]
  2.0.3 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.301 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0-rc2-3002702 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
</details>

VS Code version: Version 1.26.0 (1.26.0) 4e9361845dc28659923a300945f84731393e210d / 2018-08-13T16:14:13.371Z

C# Extension version: 1.15.2

## Steps to reproduce
I'm using different solutions and it is evident in all of them.

1. Open a folder with solution or with projects (I'm using Orleans-Docker in the video)
1. Focus the "Problems" pane (pressing Command+Shift+M)
1. Observe the periodic updates of error messages (re-evaluation with different results)

## Expected  behavior
1. Errors are "re-evaluated" only on changes

## Actual behavior
1. Errors are "re-evaluated" constantly
1. See the video: 
![vscode-csharp-loop](https://user-images.githubusercontent.com/415535/44106755-c19e8e1e-9ff5-11e8-95bf-368743e75716.gif)

**Comment by skyflyer** [comment]
Here is the sample project, which is in the video: 
[sample-project.zip](https://github.com/OmniSharp/omnisharp-vscode/files/2287870/sample-project.zip)

**Comment by dchw** [comment]
I am seeing the same issue; its making life very difficult. This started happening when I upgraded VS Code to 1.26.

**Comment by skyflyer** [comment]
I believe this might be a VS code bug: See the issue here:
https://github.com/Microsoft/vscode/issues/56317

**Comment by rchande** [comment]
@skyflyer @dchw We haven't made any changes in our error reporting so you're probably right that this is a Code bug. I'm going to close this issue. Thanks for reporting this, and feel free to keep discussing if you like.

**Comment by GlenCFL** [comment]
I think every callback registered for `vscode.OnDidCloseTextDocument` is erroneously being invoked in some manner, so diagnostic files are removed over time. Eventually, the next project validation finishes and the diagnostics are reset.

You can fix it from within the extension by caching and restoring within that callback.

**Comment by rchande** [comment]
Sounds like there are some changes we need to make to adjust to VS Code impll changes. Reopening this to track those changes.

**Comment by GlenCFL** [comment]
This was resolved with the VSCode 1.26.1 release.
