### ISSUE TITLE
Resolve dependencies - add option to resolve/ignore all

### ISSUE THREAD

**Issue by midgetgem** [OmniSharp/omnisharp-vscode#2459]
VS Code version: 1.25.1
C# Extension version: 1.15.2

When I open a solution I get a lot of popups saying it has dependencies to resolve, but there's no resolve all or ignore all button.  I have to just keep clicking in the same place to do them all, and hope the popup doesn't change and I click the wrong button.  Please add a resolve all and ignore all button.

A way to just close all popups without any action would be really useful too as I just want to see the file without popups covering it.

**Comment by akshita31** [comment]
@midgetgem We have made these changes in the new beta version - https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.16-beta2. You can install the beta version by following the instructions [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases#installing-a-beta-release-of-the-c-extension).
