### ISSUE TITLE
.omnisharp folder is missing

### ISSUE THREAD

**Issue by ChrisRyuGS** [OmniSharp/omnisharp-vscode#2466]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.105/

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  1.0.0-preview2-1-003177 [/usr/local/share/dotnet/sdk]
  1.0.0-rc4-004599 [/usr/local/share/dotnet/sdk]
  1.0.1 [/usr/local/share/dotnet/sdk]
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.0.2 [/usr/local/share/dotnet/sdk]
  2.1.101 [/usr/local/share/dotnet/sdk]
  2.1.104 [/usr/local/share/dotnet/sdk]
  2.1.105 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.8-servicing-26407-02 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

VS Code version: 1.26.1
C# Extension version: 1.15.2

## Actual behavior
~/.vscode/extensions/ms-vscode.csharp-1.15.2/.omnisharp is missing.

~/.vscode/extensions/ms-vscode.csharp-1.15.2
❯ ls -al
total 448
drwxr-xr-x   19 test  staff     608 Jul 25 11:10 .
drwxr-xr-x   70 test  staff    2240 Aug 19 21:24 ..
drwxr-xr-x  132 test  staff    4224 May 16 19:34 .debugger
-rw-r--r--    1 test  staff    2399 May 16 11:29 .vsixmanifest
-rw-r--r--    1 test  staff   64632 May 16 11:29 CHANGELOG.md
-rw-r--r--    1 test  staff    1110 May 16 11:29 LICENSE.txt
-rw-r--r--    1 test  staff    3597 May 16 11:29 README.md
drwxr-xr-x    4 test  staff     128 May 16 11:29 RuntimeLicenses
-rw-r--r--    1 test  staff    6704 May 16 11:29 ThirdPartyNotices.txt
-rw-r--r--    1 test  staff      71 May 16 11:29 codecov.yml
-rw-r--r--    1 test  staff   14228 May 16 11:29 debugger-launchjson.md
-rw-r--r--    1 test  staff    7014 May 16 11:29 debugger.md
drwxr-xr-x    3 test  staff      96 May 16 11:29 images
-rw-r--r--    1 test  staff       0 May 16 19:34 install.Lock
drwxr-xr-x   48 test  staff    1536 May 16 11:29 node_modules
drwxr-xr-x    5 test  staff     160 May 16 11:29 out
-rw-r--r--    1 test  staff  111321 May 16 11:29 package.json
drwxr-xr-x    3 test  staff      96 May 16 11:29 scripts
drwxr-xr-x    3 test  staff      96 May 16 11:29 snippets

**Comment by filipw** [comment]
`.omnisharp` folder is located in `%USERPROFILE%/.omnisharp` not under the extension path.  So, for example on your Mac it should be `~/.omnisharp`. You can read more here https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options

**Comment by ChrisRyuGS** [comment]
@filipw My VS Code couldn't load anything about omnisharp (intellisense, context menu about C#) then I'm tring to find cause. 
I've already reinstalled several times but i got no luck.

My OmniSharp Log is following

Starting OmniSharp server at 8/19/2018, 9:27:24 PM
    Target: /Users/[username]/[project]

[ERROR] Error: spawn /Users/[username]/.vscode/extensions/ms-vscode.csharp-1.15.2/.omnisharp/1.30.1/run ENOENT

**Comment by akshita31** [comment]
@ChrisRyuGS In the output do you have a `C#` channel? Could you post the output from that ?

**Comment by ChrisRyuGS** [comment]
@akshita31 No, I don't have C# channel in the output.

**Comment by akshita31** [comment]
@ChrisRyuGS Can you try installing the latest beta - https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.16-beta2 by following [these instructions].(https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases)

**Comment by ChrisRyuGS** [comment]
@akshita31 Ok. This beta version seems to work well for me.
OmniSharp Log output shows logs about starting OmniSharp Server and the features in code editor works well.

Thank you.

**Comment by akshita31** [comment]
@ChrisRyuGS Glad to know it worked for you. This is a strange behavior and I still don't understand why that might have happened.
I will close this issue due to lack of information for further debugging. Feel free to reopen if there are any concerns.
