### ISSUE TITLE
Asking Omnisharp to add a namespace results in the change being made in a new editor pane

### ISSUE THREAD

**Issue by tdwright** [OmniSharp/omnisharp-vscode#2469]
## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

VS Code version: 1.26.1
C# Extension version: 1.15.2

## Steps to reproduce

1. Refer to a type in a namespace not yet referenced in a `using` statement
2. Open the "lightbulb" and select "using The.Namespace"

## Expected  behavior

Change is made to the file in the current editor pane

## Actual behavior
New editor opens for same file, where the using statement has been added

**Comment by rchande** [comment]
@tdwright I'm unable to reproduce this on VS Code 1.26.1 or on the latest insiders' build--would you mind sharing a video or screenshot?

**Comment by tdwright** [comment]
@rchande Not sure what's changed (perhaps an update?), but I'm not able to replicate this anymore either. Will close the issue.

**Comment by tdwright** [comment]
Aha! It started doing it again and this time I was armed with a screen recorder!

The trigger is actually slightly different (I'm correcting a typo instead of adding a namespace) but the outcome is the same - the change is made in a new editor window instead of the one I triggered it from.

https://www.youtube.com/watch?v=KZzYYDpnRAA

Hope this helps.

**Comment by cartermp** [comment]
This one no longer reproduces. Since it's been a few years, I suspect it's been fixed.
