### ISSUE TITLE
'brary/project.json' needs to be restored

### ISSUE THREAD

**Issue by jeffschwMSFT** [OmniSharp/omnisharp-vscode#247]
<img width="1061" alt="screen shot 2016-04-26 at 10 04 59 am" src="https://cloud.githubusercontent.com/assets/9561583/14827287/7d1bfeac-0b96-11e6-8247-07d09c1c097d.png">

I unfortunately do not fully understand how I got into this state, but I have an app with a library dependency called "data.library".  When they both need to be restored I got this odd truncated message.

C# Extension 1.0.3-rcs
Mac OS X

**Comment by DustinCampbell** [comment]
Hi @jeffschwMSFT, sorry that this issue has gotten so stale. Should I assume that you aren't seeing this problem anymore? (Otherwise, you'd have been knocking on my office door about it by now :smile:).
