### ISSUE TITLE
List<string> shows view of raw object in the VS Code watch window

### ISSUE THREAD

**Issue by spassvogel** [OmniSharp/omnisharp-vscode#2470]
I think the formatting of collections in the debug watch window can use a lot of improvement. Compare how visual studio code currently handles a list of `String`.

![image](https://user-images.githubusercontent.com/985892/44457696-3b505300-a604-11e8-9752-1eebc7778c8e.png)

Whereas in Visual Studio the quick watch feature was much more useful:

![image](https://user-images.githubusercontent.com/985892/44457701-40150700-a604-11e8-9fc2-5f95eea169bb.png)

In general, I am mostly interested in the values in the collection, which I have to dig down four levels of hierarchy in vscode and is quite obfuscated.

**Comment by gregg-miskelly** [comment]
@spassvogel Are you debugging Mono, .NET Core or .NET Desktop? 

If .NET Core or desktop - what version of .NET Core/Desktop are you targeting? What OS are you on? Can you reproduce this problem in 'Hello World'? If not, do you have a project you can share?

**Comment by spassvogel** [comment]
I'm on Windows 10. I'm experiencing this whilst debugging Unity3d, so that's Mono I suppose, right? I'm seeing the same in Visual Studio Code 1.25 and Visual Studio Code - Insiders 1.27


![image](https://user-images.githubusercontent.com/985892/44518859-ae70cc80-a6cb-11e8-905d-d914eeb6568f.png)

![image](https://user-images.githubusercontent.com/985892/44518856-ac0e7280-a6cb-11e8-9b2b-23ebd68d7e65.png)

Let me see if I can create an isolated Hello world. I was kind of under the impression that this was not a bug, but just the way VS code (or omnisharp?) was written...

**Comment by gregg-miskelly** [comment]
Thanks. If you were seeing this with .NET Core/Desktop - it would be a bug. Since you are seeing this in Mono debugger, this probably is a feature request. But not to this extension - the mono debugger isn't from this extension. I will see if I can find your issue a home.

**Comment by gregg-miskelly** [comment]
This issue was moved to Microsoft/vscode-mono-debug#48
