### ISSUE TITLE
Eliminate install.Lock from the download and install pipeline

### ISSUE THREAD

**Issue by akshita31** [OmniSharp/omnisharp-vscode#2478]
The extension needs a better mechanism to be able to identify whether the required dependencies are installed or not.

cc @rchande

**Comment by gregg-miskelly** [comment]
@akshita31 what don't you like about install.Lock?

**Comment by akshita31** [comment]
@gregg-miskelly install.Lock is a file, the presence of which tells us currently that the default omnisharp and the debugger packages are installed. However if the user somehow deletes these folders, until the install.Lock is present, a new download wont be triggered. Wouldn't it be better if we could somehow check the "run" file associated with the packages to ensure that those folders are present ?

**Comment by DustinCampbell** [comment]
What if we had two install.Lock files -- one for OmniSharp and one for the debugger? The files could then be written to the `.debugger` and `.omnisharp` folders respectively after extracting the archives. Then, users would just need to delete the appropriate folder to re-download.

**Comment by gregg-miskelly** [comment]
Sounds good to me
