### ISSUE TITLE
Debugger doesn't find PDBs in their original built location

### ISSUE THREAD

**Issue by ChaosCA** [OmniSharp/omnisharp-vscode#2483]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.202)

Product Information:
 Version:            2.1.202
 Commit SHA-1 hash:  281caedada

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.202\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.9
  Build    : 1632fa1589b0eee3277a8841ce1770e554ece037
```

VS Code version: Latest Stable
C# Extension version: 1.15.2

## Steps to reproduce
Opening a root workspace with a .sln and a `Source/` folder. Build into `Output/Debug`. However the launch PDB's build into `Source/PROJNAME/obj/Debug/PROJNAME.pdb` but is not detected by the extension as I believe it is looking in the `Output/Debug` folder.

## Expected  behavior
The extension should check the directory from which the source was built.

## Actual behavior
It fails to find the PDB's. 
```
Loaded 'E:\Development\Example\Output\Debug\bridge\runtime\test1.dll'. Cannot find or open the PDB file.
Loaded 'E:\Development\Example\Output\Debug\bridge\runtime\test2.dll'. Cannot find or open the PDB file.
```

PDB can be found in:
```
'E:\Development\Example\Source\test1\obj\Debug\test1.pdb
E:\Development\Example\Source\test2\obj\Debug\test2.pdb
```

I've tried to set the `symbolOptions` to:
```
        {
            "name": "Attach",
            "type": "coreclr",
            "request": "attach",
            "processName": "server.exe",
            "symbolOptions": {
                "searchPaths": ["$(workspaceRoot)/Source/../obj/Debug"],
                "searchMicrosoftSymbolServer": false
            },
        }
```

Without success.

**Comment by gregg-miskelly** [comment]
The default search locations will be: the original location where the compiler dropped the PDB and next to the dll. If you have full Visual Studio installed with the C++ work load, there is a tool called 'dumpbin' in there that will let you see what this original directory is -- from a VS developer command prompt run `dumpbin /headers <path-to-dll> | findstr RSDS`.

I am not sure why adding the directory to `searchPaths` wouldn't work though. If you explicitly add the full path (no '..') does it work?

**Comment by ChaosCA** [comment]
No, that only seems to happen in one project of mine.

The only other 'errors' are:

```
WARNING: Could not load symbols for 'test1.dll'. 'E:\Development\Example\Source\test1\obj\Debug\test1.pdb' is a Windows PDB. These are not supported by the cross-platform .NET Core debugger.
Loaded 'E:\Development\Example\Output\Debug\bridge\runtime\test1.dll'. Cannot find or open the PDB file.
Loaded 'E:\Development\Example\Output\Debug\bridge\runtime\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'E:\Development\Example\Output\Debug\bridge\runtime\test2.dll'. Cannot find or open the PDB file.
```

Appreciate the help, would really love to get this working. @gregg-miskelly

**Comment by ChaosCA** [comment]
I was able to partially solve the issue! 

Using this option:

```
            "symbolOptions": {
                "searchPaths": ["${workspaceFolder}/Source/test1/obj/Debug/netcoreapp2.0"],
                "searchMicrosoftSymbolServer": false
            },
```

It will work properly for the one. But using this option:

```
            "symbolOptions": {
                "searchPaths": ["${workspaceFolder}/Source/../obj/Debug/netcoreapp2.0"],
                "searchMicrosoftSymbolServer": false
            },
```

Results in: 
```
WARNING: Symbol search directory 'E:\Development\Example\Source\..\obj\Debug\netcoreapp2.0' does not exist and was ignored.
```

I assume this is because in my `Source/` directory there is also a client portion which does not have the `obj/Debug/netcoreapp2.0` is there anyway around this? Ideally adding every csproj path here shouldn't be required

**Comment by ChaosCA** [comment]
What's so weird is that even if I don't have the `searchPaths` set, it will still find test1's PDB to report an error.

```
WARNING: Could not load symbols for 'test1.dll'. 'E:\Development\Example\Source\test1\obj\Debug\test1.pdb' is a Windows PDB. These are not supported by the cross-platform .NET Core debugger.
Loaded 'E:\Development\Example\Output\Debug\bridge\runtime\test1.dll'. Cannot find or open the PDB file.
Loaded 'E:\Development\Example\Output\Debug\bridge\runtime\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'E:\Development\Example\Output\Debug\bridge\runtime\test2.dll'. Cannot find or open the PDB file.
```

So it KNOWS where the PDB is, but still claims it can't find them for other csproj's.

**Comment by ChaosCA** [comment]
Hey @gregg-miskelly any update on this or if it's something I can simply create an MR for?

**Comment by gregg-miskelly** [comment]
@ChaosCA sorry I didn't get back to you earlier. If you are still interested in looking at this - I would need the output of `dumpbin /headers <path-to-dll> | findstr RSDS` to tell you more.. If you could install the C++ Workload temporarily into VS, or just send me your dll then we can see if we can understand what is going wrong.

**Comment by ChaosCA** [comment]
Hey @gregg-miskelly 

Still very much interested in helping out and can do. However I don’t believe it’s an issue of my DLL, since it works properly if I add the correct directory to `searchPaths`. The issue is that the extension only looks in `obj/Debug` and does not look in `obj/Debug/netcoreapp2.0` for the project. Since our solution has many projects it’s difficult/annoying to add all of them as a search path.

If still needed I can get you that dumpbin however.

**Comment by gregg-miskelly** [comment]
@ChaosCA Yes, the dumpbin output would be helpful.

**Comment by ChaosCA** [comment]
```
E:\Development\Example\Source\test1\obj\Debug\netcoreapp2.0>dumpbin /headers test1.dll | findstr RSDS
    9B8DA32C cv            65 00006810     4A10    Format: RSDS, {1FE11D8D-CF96-4C70-ACFC-B14B549C7F97}, 1, E:\Development\Example\Source\test1\obj\Debug\netcoreapp2.0\test1.pdb
```
@gregg-miskelly

**Comment by gregg-miskelly** [comment]
Thanks. Is `E:\Development\Example\Source\test1\obj\Debug\netcoreapp2.0\test1.pdb` the path where your PDB is? (the path that you are adding to your search path)

**Comment by ChaosCA** [comment]
Yes that has the correct PDB file that works properly when manually added to the search path :)

**Comment by gregg-miskelly** [comment]
If you leave your `symbolOptions` empty, do you get any log lines in the debug console that talks about test1?

If that doesn't show anything - try this:
1. Download and run [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)
2. In process monitor, bring up the filter dialog, and add a filter for 'Process Name' is 'vsdbg-ui.exe'
3. Make sure that Filter->Drop Filtered Events is checked
4. Start collection
5. Try to debug with `symbolOptions` empty
6. Turn off collection
7. Search for 'test1.pdb' in the collected log, and see if anything interesting is happening. You can just email me the log if you like. I am 'greggm' on the microsoft.com email server.

**Comment by ChaosCA** [comment]
Nothing interesting in the debug console except for the lines I showed above how it cannot be found.

I shot you an email with the log file! @gregg-miskelly

**Comment by gregg-miskelly** [comment]
Thanks to help from @ChaosCA, I was able to find the problem. Thanks!

**Comment by ChaosCA** [comment]
Awesome! Can't wait for a fix

**Comment by ChaosCA** [comment]
Hey @gregg-miskelly anything I can do to help get this through?
Thanks!

**Comment by gregg-miskelly** [comment]
I hope to put out a new beta tomorrow that will have the fix for this.

**Comment by gregg-miskelly** [comment]
[1.17.0-beta6](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.17.0-beta6) is now on the release page. Please follow [these instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) to install.

**Comment by ChaosCA** [comment]
Works! Thanks again @gregg-miskelly
