### ISSUE TITLE
Ignores rulesets when showing problems/warnings

### ISSUE THREAD

**Issue by braunsonm** [OmniSharp/omnisharp-vscode#2485]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.202)

Product Information:
 Version:            2.1.202
 Commit SHA-1 hash:  281caedada

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.202\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.9
  Build    : 1632fa1589b0eee3277a8841ce1770e554ece037
```

VS Code version: Latest Stable
C# Extension version: 1.15.2

## Steps to reproduce
Use the official nuget for code anaylsis:
```
<PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.6.1" />
```

Add a ruleset:
```
  <PropertyGroup> 
     <CodeAnalysisRuleSet>myruleset.ruleset</CodeAnalysisRuleSet> 
     <Features>IOperation</Features> 
     <NoWarn></NoWarn>   
  </PropertyGroup> 
```

## Expected  behavior
The problems tab would hide things that were ignored in the ruleset.

## Actual behavior
The problems tab ignores the ruleset and will show warnings you might not wish to have.

**Comment by akshita31** [comment]
@ChaosCA Could you share a repro project ?

**Comment by tportNAPA** [comment]
This is still happening, and makes the .EditorConfig support borderline useless, as you can't even define ruleset seventies with it.

**Comment by filipw** [comment]
the rulesets are definitely supported

@braunsonm  the duagnostic is CS4014 not CA4014
you can't configure that in the ruleset because it comes directly from the compiler not from analyzers https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs4014

**Comment by filipw** [comment]
@tportNAPA editorconfig's support for setting analyzer severity is a relatively new thing and therefore it's not yet supported by OmniSharp, this is tracked here https://github.com/OmniSharp/omnisharp-roslyn/issues/1657
