### ISSUE TITLE
C# IntelliSense not working on Linux Ubuntu

### ISSUE THREAD

**Issue by programmer1718** [OmniSharp/omnisharp-vscode#2489]
## Environment data
`dotnet --info` output:
```
jc@JC-GB-BXi7-5775R:~$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.401/

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

VS Code version: 1.26.1
C# Extension version: 1.15.2

I am not getting basic intellisense and snippet autocompletion in VS Code for Ubuntu.
I have the C# extension installed and I'm not sure about what's happening :disappointed: 
Can someone please help?

This happens with any project I create using the dotnet CLI.

**Comment by jsdev17** [comment]
![peek 2018-09-03 17-03](https://user-images.githubusercontent.com/33580723/45001468-4d82a780-af9b-11e8-8253-4dd6eacc2778.gif)
Here's what I mean

**Comment by rchande** [comment]
@jsdev17 Can you share your OmniSharp log?

**Comment by fasmat** [comment]
@jsdev17 I had the same issue in OSX a while back.
I believe I fixed it by deleting the .omnisharp and .vscode directories in my home folder and reinstalling the extensions I need for development

**Comment by akshita31** [comment]
@jsdev17 Are you opening an entire project in vscode ot just the C# file?

**Comment by joejnke** [comment]
I had the same Issue these couple of days and I fixed it by uninstalling the already installed `c# extension` and then reinstall it again. The problem was that the extension and additional c# dependencies and packages like `OmniSharp`, `.NET Core Debugger` and `Razor Language Server` were not properly installed due to internet connection problems. So, reinstalling fixed the issue on my `Visual Studio Code` installed on `ubuntu 18.04 LTS`.

**Comment by cartermp** [comment]
Closing out as no additional info was given
