### ISSUE TITLE
OmniSharp behind Enterprise proxy

### ISSUE THREAD

**Issue by waaromikniet** [OmniSharp/omnisharp-vscode#2499]
VScode: 1.27.1
C#: 1.15.2

I can download the package OmniSharp. I have proxy system setting with a proxy pac file. I can download all extensions in VSCode and I can auto update but the OmniSharp package can't be downloaded. When I enter this url "https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.30.1.zip" in the browser I can access it.

*****************************************************
Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' 	Retrying from 'https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.30.1.zip' Failed at stage: downloadAndInstallPackages
Error: connect ETIMEDOUT 68.232.34.200:443
******************************************************

i tried adding proxy settings in code

    "http.proxy": "10.0.0.10:8080",
    "http.proxyStrictSSL": false,
is there also a https.proxy setting?
Or

    "http.proxy": "http://proxypac.domain.nl/proxy/proxy.pac",
    "http.proxyStrictSSL": false,

i also tried putting Fiddler in between but no success.

**Comment by gregg-miskelly** [comment]
The two proxy settings supported by this extension are: `http.proxy` and `http.proxyStrictSSL`. So if you are setting them to your network's settings, I don't know why they wouldn't be working.

Does your proxy require authentication? It looks like VS Code supports the following additional setting, but the C# extension doesn't currently pass along to the downloader.

```
  // The value to send as the 'Proxy-Authorization' header for every network request.
  "http.proxyAuthorization": null,
```

**Comment by gregg-miskelly** [comment]
Also, I am not sure where the IP address '68.232.34.200' would have come from. Do you always see that IP address? Is that what 'omnisharpdownload.blob.core.windows.net' resolves to on your computer? Can you ping it?

**Comment by waaromikniet** [comment]
The proxy at my workplace requires authentication indeed., But when I use Fiddler I can configure it in such a way it passes authentication. So in VS Code I configure Fiddler as the proxy and Fiddler transfers to the other proxy passing my Windows credentials. I use this also for other applications that can't go through my work proxy. 

I have to be at my workplace to see what that IP is from. When I nslookup omnisharpdownload.blob.core.windows.net from home I get 13.88.145.64

**Comment by SIkebe** [comment]
@waaromikniet  Setting `http_proxy` environmental variable to `http://<proxy id>:<proxy password>@<proxy server>:<proxy port>` work?

**Comment by waaromikniet** [comment]
I have fixed the problem by using Fiddler in between.
In Fiddler set the option "Automatically Autehticate" to true

![image](https://user-images.githubusercontent.com/16294209/45299331-968eaa80-b50b-11e8-9305-547bf71b5b14.png)

Set "Act as a system proxy"

![image](https://user-images.githubusercontent.com/16294209/45299378-ba51f080-b50b-11e8-8afa-889247aa0b5f.png)

In VSCode set settings

    "http.proxy": "http://127.0.0.1:12344",
    "http.proxyStrictSSL": false:


At first I had set:

    "http.proxy": "127.0.0.1:12344",
    "http.proxyStrictSSL": false

Without the http:// its not working
