### ISSUE TITLE
Name of built-in C# types is wrong in the tooltip

### ISSUE THREAD

**Issue by mellinoe** [OmniSharp/omnisharp-vscode#250]
For example, hovering over an `int` parameter in a method shows the name as `System.int` in the tooltip:

![image](https://cloud.githubusercontent.com/assets/8918977/14867574/038d54b2-0c7e-11e6-92e2-b86546cb4561.png)

This should be `System.Int32`. This also seems to happen even if the parameter is written as `System.Int32 index`.

Also applies to `System.Object`, `System.UInt32`, [etc.](https://msdn.microsoft.com/en-us/library/ya5y69ds.aspx)

**Comment by filipw** [comment]
This was fixed by https://github.com/OmniSharp/omnisharp-roslyn/pull/665 - can be closed.

**Comment by DustinCampbell** [comment]
Indeed it is. Thanks @filipw!

FWIW, I've created a [v1.6-beta2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.6-beta2) release of the C# extension that contains this fix, among others. See this page for information on [installing beta releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases)
