### ISSUE TITLE
Omnisharp not working on windows

### ISSUE THREAD

**Issue by sgentile** [OmniSharp/omnisharp-vscode#2502]
I have the latest visual code installed, and running in a VM.

When I try to use Omnisharp i'm not getting any intellisense, I can't do 'goto definitions' etc...

When I run Omnisharp: Restart Omnisharp

I get this error:  command 'o.restart' not found

**Comment by sgentile** [comment]
(I've tried uninstalling and reinstalling, it doesn't appear to help)

**Comment by sgentile** [comment]
e:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.400\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by sgentile** [comment]
(all my dotnet commands work great, no issues building or running the code)

**Comment by akshita31** [comment]
@sgentile Do you have a "C# log" in the output pane on the right side ?

**Comment by sgentile** [comment]
I just saw this
https://github.com/OmniSharp/omnisharp-vscode/issues/2489

I completed deleted my .omnisharp and .vscode directories and now it properly installed it and it's working

**Comment by akshita31** [comment]
@sgentile Glad you got it working.
