### ISSUE TITLE
'Error initializing the symbol reader' error when clrdbg is run from a directory with accents

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#251]
1. Create a new user account with accents in the name (example: Andrés)
2. Follow instructions on http://aka.ms/vscclrdogfood to install the C# extension
3. Try to debug

Result:
No symbols are loaded, and the following is written to the console -
ERROR: Unable to load symbols. Error initializing the symbol reader (Microsoft.DiaSymReader.PortablePdb.dll).

**Comment by gregg-miskelly** [comment]
@MattGertz FYI, we have a new RC2 bug

**Comment by gregg-miskelly** [comment]
The problem here is that the CoreCLR Unix hosting APIs are using CP_ACP, while the debugger expects them to use CP_UTF8. Need to talk with the CLR team to find out which one is correct.

https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/src/dlls/mscoree/unixinterface.cpp#L127

**Comment by MattGertz** [comment]
There's a similar bug from another component touching on this issue as well (not sure of the id) -- I'll escalate.

**Comment by MattGertz** [comment]
See https://github.com/dotnet/cli/issues/2649.  Does that address the point?

**Comment by jello-chen** [comment]
When I use vs code to debug,the console will print 'ERROR: Unable to load symbols. Error initializing the symbol reader (Microsoft.DiaSymReader.PortablePdb.dll).'.I don't know if it is for the reason that my user name contains chinese.

**Comment by gregg-miskelly** [comment]
Yes, this is the problem then. We hope to have a fix for this shortly. Sorry.

**Comment by gregg-miskelly** [comment]
@jello-chen what OS are you on?

**Comment by jello-chen** [comment]
Win 10 Professional

**Comment by gregg-miskelly** [comment]
Okay, good. Yes, my fix should address this then.
