### ISSUE TITLE
Cannot load envFile on windows

### ISSUE THREAD

**Issue by flying-sheep** [OmniSharp/omnisharp-vscode#2512]
Hi!

I have this config:

```js
{...,
"envFile": "${workspaceFolder}/src/dev.env",
...}
```

On windows, when I augment the error message with actual helpful info (#2511), I get:

> Can't parse envFile /c:/Users/Me/Dev/FG/Apps (other)/viz_scatterplot/src/dev.env
>
> because of Error: ENOENT: no such file or directory, open 'C:\c:\Users\Me\Dev\FG\Apps (other)\viz_scatterplot\src\dev.env'

something in your path handling code is wrong.

**Comment by gregg-miskelly** [comment]
I believe the problem is that `folder.uri.path` on [this line](https://github.com/OmniSharp/omnisharp-vscode/blob/a813b0de2f32759bf80c451039b0e1bc2cb0d3fc/src/configurationProvider.ts#L140) should be `folder.uri.fsPath`
