### ISSUE TITLE
Extension Not Playing Nice, unable to Debug Code

### ISSUE THREAD

**Issue by 4verage** [OmniSharp/omnisharp-vscode#2520]
## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.401\

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version: 1.27.1
C# Extension version: 1.16.1

## Steps to reproduce

VS Code installed an update upon closing. Re-opened and all of my C# code was underlined in red and showing over 10k errors. Uninstalled / Re-installed / Reloaded extension, still getting errors like "Predefined type 'System.Object' is not defined or imported".

Upon removing, all errors go away, but unable to compile code. Re-installing the C# Extension returns all of the errors. Please help, I cannot debug/compile!

## Expected  behavior

No errors showing. :)

## Actual behavior

Errors are showing. :(

I feel like the only person having this problem, haven't found any other forum entries since the VS Code update. I noticed old/new versions in the dotnet --info output, but I do not know how to manage these items or if I even need to delete the older versions.

**Comment by rchande** [comment]
@4verage please share your omnisharp log.

**Comment by 4verage** [comment]
@rchande I'm very new to VS Code (only downloaded it due to requirements for a class). Where do I retrieve the OmniSharp log?

**Comment by 4verage** [comment]
This post (unrelated software) is showing the same thing I am experiencing: (I'm beginning to get convinced this is surely an update issue.) I have un-installed completely and re-installed. Still looking at the same problems. :(

[Why are My Class name and the Void Keyword Invalid](https://forums.ghielectronics.com/t/why-are-my-class-name-and-the-void-keyword-invalid/21028)

**Comment by rchande** [comment]
@4verage View -> Output and use the selector dropdown to choose "omnisharp log"

**Comment by 4verage** [comment]
Starting OmniSharp server at 9/14/2018, 9:32:37 PM
    Target: e:\DEV258x\Module 2\Module2-Labs

OmniSharp server started.
    Path: C:\Users\style\.vscode\extensions\ms-vscode.csharp-1.16.1\.omnisharp\1.32.5\OmniSharp.exe
    PID: 7484

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2017 15.1.26403.7 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\style\.vscode\extensions\ms-vscode.csharp-1.16.1\.omnisharp\1.32.5\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2017 15.1.26403.7 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'e:\DEV258x\Module 2\Module2-Labs'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'e:\DEV258x\Module 2\Module2-Labs'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\DEV258x\Module 2\Module2-Labs\MovieApp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'e:\DEV258x\Module 2\Module2-Labs'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\DEV258x\Module 2\Module2-Labs\MovieApp.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'e:\DEV258x\Module 2\Module2-Labs' on host 17656.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'e:\DEV258x\Module 2\Module2-Labs\MovieApp.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'e:\DEV258x\Module 2\Module2-Labs\MovieApp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MovieApp
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\DEV258x\Module 2\Module2-Labs\MovieApp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\DEV258x\Module 2\Module2-Labs\MovieApp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\DEV258x\Module 2\Module2-Labs\MovieApp.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'e:\DEV258x\Module 2\Module2-Labs\MovieApp.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MovieApp

**Comment by akshita31** [comment]
@4verage Can you execute Ctrl+Shift+P --> ".NET Restore All Projects" and seeing if the error still reproduces ?

Also, if you create a new project using "dotnet new console" and open it in vscode, do you still get similar errors?

**Comment by 4verage** [comment]
Command: '.NET: Restore All Projects' resulted in an error.

I've looked around. I can't figure out where to track the error unfortunately!

I DO keep getting this in the OmniSharp log now:

[fail]: OmniSharp.MSBuild.ProjectManager :: Attempted to update project that is not loaded: d:\DEV258x\Module 2\Module2-Labs\MovieApp.csproj

Any ideas?

**Comment by akshita31** [comment]
@4verage Can you do the following : 
1. Create a directory test : mkdir test
2. cd test
3. dotnet new console

Now open the test folder in vscode. Do you still see similar errors ?

**Comment by akshita31** [comment]
Also can you navigate to the directory in which you are working in the terminal and execute "dotnet restore" ?

**Comment by danShumway** [comment]
> [fail]: OmniSharp.MSBuild.ProjectManager :: Attempted to update project that is not loaded: d:\DEV258x\Module 2\Module2-Labs\MovieApp.csproj

Is this related to #2234? Is there any way to downgrade what version of OmniSharp Visual Studio uses?

**Comment by 4verage** [comment]
I have a new laptop and a clean install of Visual Studio Code and .NET Core. I have installed the OmniSharp extension for C# and am having issues compiling on this computer as well. I will update once I am home tonight to see if we can find a relationship between the two.

**Comment by 4verage** [comment]
@akshita31 
> @4verage Can you do the following :
> 
> 1. Create a directory test : mkdir test
> 2. cd test
> 3. dotnet new console
> 
> Now open the test folder in vscode. Do you still see similar errors ?

Same errors:

`Starting OmniSharp server at 9/25/2018, 9:07:32 PM
    Target: c:\Users\style\test

OmniSharp server started.
    Path: C:\Users\style\.vscode\extensions\ms-vscode.csharp-1.16.1\.omnisharp\1.32.5\OmniSharp.exe
    PID: 8468

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2017 15.8.28010.2026 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\style\.vscode\extensions\ms-vscode.csharp-1.16.1\.omnisharp\1.32.5\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2017 15.8.28010.2026 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\style\test'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\style\test'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\style\test\test.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\style\test'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\style\test' on host 6596.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\style\test\test.csproj
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\style\test\test.csproj'.
c:\Users\style\test\test.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.  c:\Users\style\test\test.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath)
   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectLoader loader)
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader)

[fail]: OmniSharp.MSBuild.ProjectManager
        Attemped to update project that is not loaded: c:\Users\style\test\test.csproj`



> Also can you navigate to the directory in which you are working in the terminal and execute "dotnet restore" ?

`PS D:\DEV258x\Module 2\Module2-Labs> dotnet restore
  Restore completed in 54.26 ms for D:\DEV258x\Module 2\Module2-Labs\MovieApp.csproj.
  Restore completed in 75.26 ms for D:\DEV258x\Module 2\Module2-Labs\MovieApp.csproj.
PS D:\DEV258x\Module 2\Module2-Labs>`

I re-ran my program, and I keep getting an error for no "Include" method extension (supposed to be an EF Framework extension). However, if I choose to Ignore I am now getting this:

> The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.

What do I need to do to tell if everyrthing is installed/configured properly to work hand-in-hand? (EF Framework Core, .NET Core, extensions, packages?

Here is what I have:

`<PackageReference Include="ConsoleTables" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.3" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </DotNetCliToolReference>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.3" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.1.2" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Design" Version="1.1.2" />`

Any help or ideas would be GREATLY appreciated. This class is ending soon and I can't get my coding to compile. :(

**Comment by 4verage** [comment]
Okay, after reading through what feels like hundreds of issues posts, I finally have everything working on Laptop #2 (completely fresh install).

For some reason, the line `<Project Sdk="Microsoft.NET.Sdk">` does not cross to the physical directory for the SDK. I am not sure if there is a pointer file or something I am missing? However, the age-old work around of setting some mystical MSBuildSdksPath variable never worked for me -- or I didn't know how to do it right.

Eventually, I simply altered the line to read: `<Project Sdk="C:\Program Files\dotnet\sdk\2.1.402\Sdks\Microsoft.NET.Sdk">` and... viola! ...everything now works!

Unfortunately, no good on Laptop #1 still. A little disappointed that upgrading VS Code broke everything. I really wish I could just go back to using Community at this point. Silly class requirements!

Anyhow, I'm operational at this point. If you can think of _anything_ that could possibly help me with the other laptop, please let me know!

**Comment by bomeers** [comment]
> Eventually, I simply altered the line to read: `<Project Sdk="C:\Program Files\dotnet\sdk\2.1.402\Sdks\Microsoft.NET.Sdk">` and... viola! ...everything now works!

Tried this and it works. Been looking for this all day. Thank you.

**Comment by cartermp** [comment]
I suspect there were several issues related to this, as this kind of problem doesn't reproduce.
