### ISSUE TITLE
Add "Override Virtual Method" to "Quick Fix"

### ISSUE THREAD

**Issue by NemoStein** [OmniSharp/omnisharp-vscode#2522]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\nemos\scoop\apps\dotnet-sdk\current\sdk\2.1.401\

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

VS Code version: 1.27.1
C# Extension version: 1.16.1

## Steps to reproduce
```CSharp
public class SuperClass
{
	virtual public void VirtualMethod() { /* Some code */ }
}

public class ChildClass : SuperClass
{
	override VirtualMethod // Call "Quick Fix" here
}
```
## Expected  behavior
The whole method signature and (possibly) `base.VirtualMethod();` should be added.

## Actual behavior
`No code actions available`

**Comment by rchande** [comment]
Instead of implementing this as a code action, we would implement this as a special completion list that comes up after you type override (which is a behavior Visual Studio has had for a long time). https://github.com/OmniSharp/omnisharp-roslyn/pull/884 is tracking that work cc @DustinCampbell

**Comment by NemoStein** [comment]
Oh, that fits me well... I'll follow the linked issue, thanks!
