### ISSUE TITLE
Feature Request: Allow breadcrumbs to function in a no project context

### ISSUE THREAD

**Issue by Tarig0** [OmniSharp/omnisharp-vscode#2524]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
VS Code version: 1.27.1 (system setup)
C# Extension version: 1.16.1

## Steps to reproduce
Create the following file and save it.
```c#
using System;

namespace Test2
{
    public class test{
        public test(){
            Console.WriteLine("Hello World");
        }
    }
}

```
Highlight test
## Expected  behavior
Breadcrumbs would display all the way down to the test function

## Actual behavior
Breadcrumbs only display to the file level.

Behavior changes if an unrelated project system is loaded, and file is edited, to the expected behavior.
1. create file from above.
2. Open a folder containing a project
3. open original file
4. make the test file dirty
5. Highlight test
Results: Breadcrumbs display all the way down to the test function

**Comment by Tarig0** [comment]
Looks like this is because the omnisharp server is not started until a project is loaded. Would it be possible to have a default empty project loaded instead of relying on the workspace to have a csproj or sln file opened?

**Comment by akshita31** [comment]
@Tarig0 In 1.16 we enabled c# extension to give basic intellisense help for c# files that are not associated with projects. So you can open a folder in vscode with just a c# file in it and you _should_ get the correct breadcrumbs once omnisharp has started. Do you see an "omnisharp log" in the View--> Output pane ?

**Comment by Tarig0** [comment]
I do not see an omnisharp log

**Comment by akshita31** [comment]
@Tarig0 Omnisharp needs a launch target to start. Can you add the same file to a folder and try again ?

**Comment by Tarig0** [comment]
interesting, that works, odd that I can get files that are saved outside of the folder to load but I guess that's just the limitation

**Comment by akshita31** [comment]
Yeah for now OmniSharp needs atleast a folder to provide an intellisense for the file and I dont think we have any requests against that. I will close this issue for now, but feel free to discuss or reopen if there are any other concerns.
