### ISSUE TITLE
Intellisense failing - "System.ArgumentException: An item with the same key has already been added"

### ISSUE THREAD

**Issue by keithoconor** [OmniSharp/omnisharp-vscode#2533]
Issue Type: <b>Bug</b>

The whole team here has recently started to have problems with Intellisense not working for C#. It works for a minute or two, but as soon as you start navigating around files and ctrl-clicking to use Intellisense to navigate between files, it stops working.

I've noticed errors like this in the 'C#' tab in the Output window, which seem to correspond with when Intellisense stops working.

Failed to synchronize document '/c:/p4/main/AssetService.cs': "System.ArgumentException: An item with the same key has already been added.\r\n   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)\r\n   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)\r\n   at OmniSharp.Roslyn.BufferManager.TryAddTransientDocument(String fileName, String fileContent)\r\n   at OmniSharp.Roslyn.BufferManager.<UpdateBufferAsync>d__7.MoveNext()"

Extension version: 1.16.1
VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor          (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.93GB (44.37GB free)|
|Process Argv|C:\Users\keith\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rchande** [comment]
@akshita31 Can you see if this is related to your misc files work?
@keithoconor Does this happen while the OmniSharp log is still printing project loads? Does it happen if you wait for OmniSharp to load all of your projects?

**Comment by keithoconor** [comment]
@rchande I waited until all projects finish loading before trying, and it still happens.

I tried going back to v1.30.0 using the option in my usersettings.json, and it still happens. I'm guessing that version is more than a couple weeks old (when this problem started), so it's possible this issue is in vscode itself and not Omnisharp. I logged an issue stating as such in vscode, I'll update here if it goes anywhere.

**Comment by akshita31** [comment]
@keithoconor Is it possible to share a repro project ?

**Comment by akshita31** [comment]
Also, is it a unity project that you are working on which happens to have symbolic links ?

**Comment by keithoconor** [comment]
@akshita31 I can't share the project as-is, but I'll see if I can strip it down to a small repro. It is a Unity project alright... and it does actually have a symbolic link (directory junction), although there shouldn't be any C# files in there. I'll try deleting the junction to see if it makes a difference.

**Comment by akshita31** [comment]
Also, can you try setting "omnisharp.path" : "1.32.2" and Ctrl+Shift+P --> Restart OmniSharp and checking if the error still reproduces ?

**Comment by keithoconor** [comment]
I've tried without the junction and also with 1.32.2 via "omnisharp.path" (that's what I used to try v1.30.0), but the problem still occurs. I'll try and get you a repro project.

The issue I logged on vscode got closed because it's "caused by extension" - https://github.com/Microsoft/vscode/issues/58812.

**Comment by keithoconor** [comment]
In the process of trying to reproduce the problem, the first thing I did was make a copy of the entire project in a different location. When I open the copy, I can't reproduce it! When I open the original I can reproduce 100%, but I haven't been able to with the copy so far. On top of that, following symbols seems to be much more responsive than it was on the original project (before it stopped working).

Is there some sort of omnisharp cache that has problems, and is tied to the original project location?

**Comment by keithoconor** [comment]
I should add that when this problem first started happening, I followed one of the fixes in an issue here and deleted my entire C:\Users\keith\.vscode\ directory and reinstalled all extensions, including omnisharp. It didn't help.

**Comment by keithoconor** [comment]
Sorry for the multiple updates, but I've finally figured out what's causing things to break; this extension: https://github.com/stef-levesque/vscode-perforce! I've logged an issue there (https://github.com/stef-levesque/vscode-perforce/issues/142).

**Comment by akshita31** [comment]
@keithoconor Glad you got it working.
And thanks for patiently trying to investigate the issue. These things make it a lot easier for us to understand the users perspective and get ideas on helping other users who run into similar problems. I will close this issue for now. If there are any other concerns feel free to discuss further or reopen.
