### ISSUE TITLE
vs code debugging asp net core watch error

### ISSUE THREAD

**Issue by pzhxd** [OmniSharp/omnisharp-vscode#255]
•NET Core Installer      dotnet-win-x64.latest (1.0.0.2520)
•NET Core SDK Installer  dotnet-dev-win-x64.latest.exe  (1.0.0.2520)
•VSCode Version: 1.0
•VSCode Extensions:  csharp-1.0.4-rc2
•OS Version: win7 x64

Steps to Reproduce:
debug cli-samples HelloMvc, when add breakpoint watch variables "s" show error, please help !
![qq 20160428181727](https://cloud.githubusercontent.com/assets/18717913/14907007/2c457790-0df5-11e6-8823-49efd72bc881.png)

**Comment by gregg-miskelly** [comment]
This may be the same as #161 though it is hard to say 0x80131524 is COR_E_DLLNOTFOUND.

**Comment by pzhxd** [comment]
Installer  csharp-1.0.4-rc2  ,  open vs code  , find run OmniSharp error

1. vs code download and Installer  coreclr-debug
![qq 20160429135354](https://cloud.githubusercontent.com/assets/18717913/14909200/458087fe-0e13-11e6-83e3-da64cd04f10c.png)

2. run OmniSharp error
![qq 20160429135151](https://cloud.githubusercontent.com/assets/18717913/14909191/2c5548dc-0e13-11e6-8c1e-ff7d532cf7b7.png)

**Comment by gregg-miskelly** [comment]
@pzhxd would you mind creating a new issue for your new problem? It doesn't sound related to your first.

**Comment by pzhxd** [comment]
I solved the problem, from  https://github.com/OmniSharp/omnisharp-roslyn  dowload omnisharp-win-x64-netcoreapp1.0.zip , copy all files to  C:\Users\dxiang\.vscode\extensions\ms-vscode.csharp-1.0.4-rc2\.omnisharp , omnisharp can running.  but vs code debug watch error

**Comment by pzhxd** [comment]
ok, creating a new issue
