### ISSUE TITLE
CS1591 warnings still appearing despite adding to <NoWarn>

### ISSUE THREAD

**Issue by coldacid** [OmniSharp/omnisharp-vscode#2561]
## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.10 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

VS Code version: 1.27.2
C# Extension version: 1.16.1

## Steps to reproduce

1. Create new C# project.
2. Add the following to the csproj file:

   ```
     <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
      </PropertyGroup>
    ```

3. Open the Problems pane, if not already open.
4. Build the project.
3. Note that "Missing XML comment" warnings appear in the Problems pane, despite CS1591 being ignored in the csproj file.
4. Build the project and read the build log.

## Expected  behavior

"Missing XML comment" warnings do not appear, either in the Problems pane or the build log for the project.

## Actual behavior

The Problems pane lists "Missing XML comment for..." warnings, despite CS1591 being included in the NoWarn list. (Build log is as expected.)

**Comment by filipw** [comment]
Could you provide a repro project that caused you trouble or try again with the latest version? 
This is definitely supported, and I just verified this again and it works (both for the `CS1591` and `1591` syntax under `<NoWarn>`).

**Comment by STayinloves** [comment]
In my case, this issue is causing by a project level `.ruleset` configuration. It’s weird that the `<CodeAnalysisRuleSet>` isn’t overridden by `<NoWarn>`.

**Comment by coldacid** [comment]
I didn't have a ruleset configured when I encountered this problem but I do find that with the current versions of VS Code, the extension, and the dotnet SDK, the problem no longer occurs for me.

**Comment by filipw** [comment]
thanks a lot for confirming. if you have any ruleset problems, please open a new issue - it's a separate, new feature. thanks.

**Comment by ksidirop-laerdal** [comment]
Note: If you have an .editorconfig file you'll have to edit it too and set the associated codes to 'none' - otherwise you'll still get warnings.
