### ISSUE TITLE
why tacking 17 sec on startup time?!

### ISSUE THREAD

**Issue by alizeraatkar** [OmniSharp/omnisharp-vscode#2563]
- Extension Name: csharp
- Extension Version: 1.16.1
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0-insider

 We have written the needed data into your clipboard. Please paste:```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 17428,
		"activateCallTime": 62,
		"activateResolvedTime": 120,
		"activationEvent": "workspaceContains:*.csproj,*.sln,*.csx,*.cake,**/*.csproj,**/*.sln,**/*.csx,**/*.cake"
	}
}
```

**Comment by rchande** [comment]
@alizeraatkar I'm not really sure what you mean. Can you help me understand?

**Comment by cartermp** [comment]
Closing out old issue with no additional info.
