### ISSUE TITLE
Please use the latest version of vscode-extension-telemetry dependency

### ISSUE THREAD

**Issue by ramya-rao-a** [OmniSharp/omnisharp-vscode#2566]
This extension uses version 0.0.15 of `vscode-extension-telemtetry`  module.

The latest version of `vscode-extension-telemtetry` module (0.0.22) uses the latest version of `applicationinsights` module (1.0.5) which has the fix to prevent unnecessary patching of the require and other 3rd party modules. 

For more details, please see https://github.com/Microsoft/vscode-extension-telemetry/issues/16

**Comment by rchande** [comment]
@akshita31 Please take a look.
