### ISSUE TITLE
Feature Request: A workspace settings option to stop automatic dotnet restore

### ISSUE THREAD

**Issue by GuardRex** [OmniSharp/omnisharp-vscode#257]
I know when I want to perform a `dotnet restore`, and I use my [Status Bar Tasks](https://marketplace.visualstudio.com/items?itemName=GuardRex.status-bar-tasks) extension to trigger `dotnet restore` at-will. I sometimes open and close `project.json` or a project with no intention of performing a restore.

It seems that `omnisharp-vscode` is auto-restoring when opening a project and for every little change+save to the `project.json` file. Can we have an option in ~~`launch.json`~~ workspace settings to stop the automatic `dotnet restore` behavior on file open and on `project.json` save?

**Comment by GuardRex** [comment]
This isn't the same issue as https://github.com/OmniSharp/omnisharp-vscode/issues/193 (I think). I think that has to do with a fixed bug on re-loading the debugger excessively.

This is still a pain point having to constantly dismiss automatic `dotnet restore` attempts.

**Comment by DustinCampbell** [comment]
A new (release)[https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.5-beta6] is ready which includes a `csharp.suppressDotnetRestoreNotification` option.

**Comment by GuardRex** [comment]
Thanks again for providing this feature. *It's wonderful!* :smile:

**Comment by DustinCampbell** [comment]
You're welcome. :smile:
