### ISSUE TITLE
Debugger won't start/launch after build fails.

### ISSUE THREAD

**Issue by whizkidwwe1217** [OmniSharp/omnisharp-vscode#2575]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008533 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
VS Code version:
C# Extension version:

## Steps to reproduce
1. Put some error on code. Ex. Put a syntax error.
2. Run or press F5 to debug the C# project.
3. A build error dialog pops up asking you to click on any of the following: Debug Anyway, Cancel, or Show Errors.
4. Click Cancel.
5. Correct the failing code.
6. Run or press F5 again to debug.
7. **Issue: Debugger won't launch. Does not even trigger the build.**

## Expected  behavior
Should be able to build & debug after build errors.

## Actual behavior
7. **Issue: Debugger won't launch. Not even triggering the build.**

**Comment by whizkidwwe1217** [comment]
Also, the errors in the Problems panel won't go away even though the errors were already fixed.
![image](https://user-images.githubusercontent.com/1977391/46447477-93a67300-c7b4-11e8-8210-5279aa33dea0.png)

**Comment by gregg-miskelly** [comment]
@dbaeumer @rchande Does this sound like a VS Code issue? Or does the language service side of the extension have something to do in this scenario?

**Comment by dbaeumer** [comment]
Here is what I see:

- new dotnet project created with dotnet new console
- opened in VS Code
- insert an error (change `WriteLine` to `Writeline`)
- press F5
- you get

![capture](https://user-images.githubusercontent.com/1931590/46460478-5f36b500-c7bc-11e8-9c99-78d2d0d65424.png)

which IMO is correct since there is a build error

- fix the error
- press F5
- I can successfully debug

![capture](https://user-images.githubusercontent.com/1931590/46460643-d8360c80-c7bc-11e8-8103-3dae376b3ba3.png)

If you don't have auto save on please ensure that after fixing the error you save. Otherwise the error will not go away.

**Comment by dbaeumer** [comment]
@gregg-miskelly can you provide steps where the F5 fails even after fixing the error.

**Comment by dbaeumer** [comment]
@gregg-miskelly I did notice another problem. The task you run is using the $mscompile problem matcher. This matcher assumes absolute path names for the files. However the dotnet build command issues relative paths. This can be fixed using the following takss.json config:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/dotnet.csproj"
            ],
            "problemMatcher": {
                "base": "$msCompile",
                "fileLocation": "relative"
            }
        }
    ]
}
```

However this still double the errors (you see two for program.cs). This can be avoided if you use the same owner as you use for the diagnostics created by the extension itself.

And you should start thinking about using the new task API to provide these tasks instead of writing a tasks.json file. For a do please see: https://code.visualstudio.com/docs/extensions/example-tasks

Please ping if you have questions.

**Comment by gregg-miskelly** [comment]
@whizkidwwe1217 are you able to repo this problem for a basic app? Or is this something specific to a project?

@DustinCampbell @rchande in the task.json that we generate, do you think we should be setting an option to `dotnet build` to have it generate full paths in diagnostic messages? (at least I thought there was an option for this, though I am not sure what it is) Or should we set `"fileLocation": "relative"`? Do you know how to fix the 'owner' problem that Dirk mentioned?

**Comment by whizkidwwe1217** [comment]
@gregg-miskelly Yes, I was able to reproduce this problem consistently. I even created a new project fresh from start (e.g. dotnet new webapi),, and I always get same issue. I tried your suggestion but got the same result.

**Comment by whizkidwwe1217** [comment]
@gregg-miskelly  @DustinCampbell  @rchande Do you think this is a Visual Code issue? It doesn't seem to be a problem in Visual Code Insider builds.

**Comment by dbaeumer** [comment]
@whizkidwwe1217 I followed exactly your steps using that latest stable release of VS Code and it works for me. @gregg-miskelly can you reproduce this?

**Comment by Blackbaud-MitchellThomas** [comment]
I've experienced the exact same thing. I have an issue open with vscode, and they want to see the conclusion of this. @whizkidwwe1217's comment about it working in Insiders led me to investigate something. I tested this in Insiders, but I used Settings Sync to restore all the same extensions I had for my .NET Core development. So, I was experiencing the same issue as I was in the stable release. Others not seeing the issue at all and seeing it go away with a presumably fresh clean Insiders version lead me to believe that it could be a bad interaction between extensions.

I disabled all extensions except for the C# extension, which is required to run the build. I enabled extensions one at a time based on which seemed most likely to be involved and retested. If I didn't see the issue, I disabled the extension I just re-enabled and tried the next one.

My testing revealed that VS Live Share seems to be the problematic extension here. Having only it and the C# extension enabled causes this issue. And back in my primary dev environment, disabling only it resolved the issue for me.

**Comment by whizkidwwe1217** [comment]
I also tried to disable Live Share in stable build but I haven't thought of it as the issue because I didn't keep an eye on it. After that, I couldn't reproduce the issue. The fact that it worked when I tested it in insider build, which doesn't have Live Share installed, maybe you're right that the  Live Share is indeed causing the build not to work. But I have to confirm this with my other machine. I'll put a comment here after my investigation.

**Comment by jsm85** [comment]
I also had the same experience as @Blackbaud-MitchellThomas. I found that when I disabled all the extensions (apart from the C# extension) I was able to Debug as expected. I then enabled only the C# and VS Live Share code extension and the problem occured. It does feel like the issue is with the VS Live Share extension.

**Comment by Blackbaud-MitchellThomas** [comment]
My teammates have confirmed this as well.

**Comment by rodrigovaras** [comment]
This is a known problem being tracked on the live share team. We are planning on releasing a workaround on the short term. The root problem is the use of a vscode debugger API that has limitations for our scenario and so cause problems when proxing a debug session and the builds fail. We have a long term solution that will resolve the root problem by using a different architecture that will be much more robust. Apologize, and as soon as we have the fix one our team members will report.

**Comment by whizkidwwe1217** [comment]
Thanks @rodrigovaras  I just tested in my other machine and I can also confirm that Live Share is the main culprit.
