### ISSUE TITLE
Warning Messages about __virtual files in problems tab

### ISSUE THREAD

**Issue by jtsom** [OmniSharp/omnisharp-vscode#2585]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.202 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.400 [/usr/local/share/dotnet/sdk]
  2.1.401 [/usr/local/share/dotnet/sdk]
  2.1.402 [/usr/local/share/dotnet/sdk]
  2.1.403 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS Code version: Version 1.28.0-insider (1.28.0-insider)
C# Extension version: 1.17.0-beta.5

## Steps to reproduce
Open a .Net Core Razor Pages application

## Expected  behavior
With no code errors, no warnings should be displayed.

## Actual behavior
Warnings are displayed in the Problems tab:
The type or namespace name 'StatusModel' could not be found (are you missing a using directive or an assembly reference?) [TestWebApp]
Unable to open 'Status.cshtml__virtual.cs': File not found (file:///Users/johntsombakos/Projects/TestWebApp/TestWebApp/Pages/Status.cshtml__virtual.cs).

There are several of these messages. The page it is referencing is basically a stock new Razor page.

Waiting some time and the problem messages will go away, but after quitting and relaunching Code the messages will re-appear.

**Comment by rchande** [comment]
cc @NTaylorMullen

**Comment by NTaylorMullen** [comment]
@jtsom really appreciate you taking the time to report the issue. I'm unable to reprodouce the issue in a `dotnet new razor` application. Would it be possible for you to share a repro project?

![image](https://user-images.githubusercontent.com/2008729/46550868-23b6ec00-c88b-11e8-94be-bed3508c0fef.png)

**Comment by jtsom** [comment]
It's seems to come and go, have to quit and relaunch VS Code, sometimes do a dotnet clean and dotnet build.

[Extension Host] No editors associated with document: /Users/johntsombakos/Projects/TestWebApp/TestWebApp/Pages/Status.cshtml__virtual.cs (at DocumentDecoration.updateDecorations (/Users/johntsombakos/.vscode-insiders/extensions/coenraads.bracket-pair-colorizer-1.0.60/out/src/documentDecoration.js:318:21))

[TestWebApp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/2451633/TestWebApp.zip)

( and I know it's a separate issue, but the syntax highlighting seems broken in cshtml files - see lines 7 and 8 in your image, for example)

Thanks!

**Comment by NTaylorMullen** [comment]
Ahh, @jtsom I definitely see your issue, what makes it super interesting is that it happens more frequently on OSX but not always (it's a race condition). Here's what I'm seeing just to clarify what you're seeing the same thing.
- Error only shows if Razor View is already open on project open.
- Error goes away if you start typing.
- Error goes away if you wait a portion of time.

I've filed an issue over in our Razor VSCode repo https://github.com/aspnet/Razor.VSCode/issues/174.

This repo will be open sourced soon but until then i'll keep this issue up-to-date.

Again, really appreciate you taking the time to report this and provide the repro project; we weren't aware of the issue and now we can fix it 👍

**Comment by NTaylorMullen** [comment]
Oh and the coloring issue. We do know of that one. It's something we plan to fix in our next release 😄

**Comment by jtsom** [comment]
Awesome, thanks! Glad I could help!

**Comment by NTaylorMullen** [comment]
Fixed in https://github.com/aspnet/Razor.VSCode/issues/174. BTW aspnet/Razor.VSCode is now public

**Comment by NTaylorMullen** [comment]
@rchande You can close this.

**Comment by ankitmrright** [comment]
I have the same issue now, it gives me an error for a virtual cshtml file.
<img width="980" alt="Screenshot 2020-04-15 at 6 19 27 PM" src="https://user-images.githubusercontent.com/55431752/79338918-af600d00-7f45-11ea-895e-200bc458c375.png">

**Comment by JoeRobich** [comment]
@ankitmrright The C# extension doesn't generate css or html errors. You may need to update your workspace's "file.exclude" with a "**/*.cshtml__virtual.html" glob ([example](https://stackoverflow.com/a/33277809)).

**Comment by NTaylorMullen** [comment]
This is most definitely coming from the Razor extension. @ankitmrright would you mind filing an issue in https://github.com/dotnet/aspnetcore/issues/new with repro steps?

**Comment by ankitmrright** [comment]
I have done that . Thank you @NTaylorMullen
