### ISSUE TITLE
OmniSharp doesn't work if I choose 4.x .Net Runtime Version in Unity

### ISSUE THREAD

**Issue by eastwing** [OmniSharp/omnisharp-vscode#2589]
When I do so, I get 'Attemped to update project that is not loaded' error. Output log says that I don't have .NETFramework,Version=v4.7.1 installed and that's true as I have 4.7.2. If I manually change runtime version in .cproj files and then restart VS Code everything works perfect, but Unity changes it back to 4.7.1 on every build. Of course I can't install 4.7.1 because 4.7.2 includes it and installer wouldn't start. 

So seems to be a bug there.

## Environment data
`dotnet --info` output:

```
????? SDK ??? .NET Core (?????????? ????? global.json):
 Version:   2.1.401
 Commit:    91b1c13032

????? ??????????:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.401\

Host (useful for support):
  Version: 2.1.3-servicing-26724-03
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

VS Code version: 1.27.2
C# Extension version: 1.16.2

## Steps to reproduce

1. Install .NET 4.7.2 if you don't have it
2. In Unity set API Compatibility level to 4.x
3. Restart Unity
4. Restart/Run VS Code
5. Wait for OmniSharp init

## Expected  behavior
OmniSharp works

## Actual behavior
OmniSharp doesn't work

**Comment by eastwing** [comment]
Ok, maybe I was wrong about "changes it back on each build". Looks like framework version changes onky when Unity has to update the project file (e.g. when you add new file). But it's still too often.

**Comment by eastwing** [comment]
> I remember having this problem, or something along these lines. I fixed it by updating visual studio, just installing frameworks wasn't enough.

Sorry, are you speaking about VS Code or "big" VS?

**Comment by SirIntruder** [comment]
big VS

**Comment by eastwing** [comment]
Hmm, I'll try that, thank you

**Comment by eastwing** [comment]
Yeah, you can install 4.7.1 targeting pack via VS 2017 installer. Thanks, @SirIntruder

**Comment by szczygielmr** [comment]
How do you resolve this issue with VS Code?

**Comment by eastwing** [comment]
I don't know any way to do it without installing VS2017, sorry. In theory all you need is 7.1 targeting pack, but I don't know where you can get it except vs2017 installer

**Comment by rchande** [comment]
@szczygielmr @eastwing Does the SDK from https://www.microsoft.com/en-us/download/details.aspx?id=56119 not work?

**Comment by szczygielmr** [comment]
I'm sure that it would but my system currently has .NET 4.7.2 and dual
installations of .NET are not permitted to my knowledge.

v/r
Mike
