### ISSUE TITLE
How do I change the language of C# error hints?

### ISSUE THREAD

**Issue by luvjungle** [OmniSharp/omnisharp-vscode#2595]
## Environment data
 Version:   2.1.403
 Commit:    04e15494b6

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
VS Code version:
1.28.0 (user setup)

C# Extension version:
1.16.2

## Steps to reproduce
Write code that cause an error hint to appear

## Expected  behavior
Error hint language is english

## Actual behavior
Since omnisharp 1.16 update (don't know if it is the point) I have error hints in my system's language (Russian). But my VSCode locale is English. Where I can set error hints' language back to english? I don't have any localization language packs for .Net in the system.

**Comment by gregg-miskelly** [comment]
@luvjungle See workaround steps in https://github.com/OmniSharp/omnisharp-vscode/issues/2513
