### ISSUE TITLE
Slow running extension

### ISSUE THREAD

**Issue by dfgchiang** [OmniSharp/omnisharp-vscode#2597]
- Extension Name: csharp
- Extension Version: 1.16.2
- OS Version: Windows_NT x64 6.1.7601
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 9702,
		"activateCallTime": 23,
		"activateResolvedTime": 3190,
		"activationEvent": "workspaceContains:*.csproj,*.sln,*.csx,*.cake,**/*.csproj,**/*.sln,**/*.csx,**/*.cake"
	}
}
```

**Comment by rchande** [comment]
@dfgchiang Can you provide more information about the problem you are experiencing?

**Comment by dfgchiang** [comment]
It's no problem. VS Code pointed out the extension and noted it is slow and prompted me to report the issue, so I did. C# extension loads.


Thanks.

________________________________

**Comment by rchande** [comment]
@dfgchiang Thank you for taking the time to file this, but I don't believe we need to take any action at this time.
