### ISSUE TITLE
while Restart-Debugging there is build error after new update. kindly fix it

### ISSUE THREAD

**Issue by saurabhnachankar** [OmniSharp/omnisharp-vscode#2599]
- Extension Name: csharp
- Extension Version: 1.16.2
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

**Comment by gregg-miskelly** [comment]
This is a duplicate of https://github.com/Microsoft/vscode/issues/60593
