### ISSUE TITLE
Debugger-invocation command line assumes a POSIX-like shell on Unix; fails with PowerShell as the default shell

### ISSUE THREAD

**Issue by mklement0** [OmniSharp/omnisharp-vscode#2605]
## Environment data
`dotnet --info` output: 
```none
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS Code version: 1.28.1
C# Extension version: 1.16.2

## Steps to reproduce

* On a Unix-like platform with PowerShell Core installed, make the latter your default shell as follows: `chsh -s /usr/local/bin/pwsh` (macOS) or `chsh -s /usr/bin/pwsh` (Linux).

* On Linux, reboot to make the new default shell take effect (not necessary on macOS).

* Open any C# project in VS Code and debug with a `".NET Core Launch (console)"` configuration with setting `"console": "externalTerminal"`

## Expected  behavior

Debugger invocation should succeed.

## Actual behavior

Debugger invocation fails, because the command line sent to the terminal assumes POSIX-like-shell syntax (e.g., `bash`), which PowerShell doesn't support.

Sample symptom:

```powershell
PS /Users/jdoe> cd '/Users/jdoe/.vscode/extensions/ms-vscode.csharp-1.16.2/.debugger/';  '/Users/jdoe/.vscode/extensions/ms-vscode.csharp-1.16.2/.debugger/vsdbg' '--interpreter=vscode' '--connection=/var/folders/19/0lxcl7hd63d6fqd813glqppc0000gn/T/CoreFxPipe_vsdbg-ui-9bb838baf07245f591dda2adcfd2536f'
At line:1 char:155
+ ... -vscode.csharp-1.16.2/.debugger/vsdbg' '--interpreter=vscode' '--conn ...
+                                            ~~~~~~~~~~~~~~~~~~~~~~
Unexpected token ''--interpreter=vscode'' in expression or statement.
At line:1 char:178
+ ... ter=vscode' '--connection=/var/folders/19/0lxcl7hd63d6fqd813glqppc000 ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token ''--connection=/var/folders/19/0lxcl7hd63d6fqd813glqppc0000gn/T/CoreFxPipe_vsdbg-ui-9bb838baf07245f591dda2adcfd2536f'' in expression or statement.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : UnexpectedToken
```

With a _quoted_ path to `vsdbg`, the call would have to be prefixed with `& `  to make PowerShell happy.

A pragmatic workaround would be _not_ to quote the `vsdbg` path, which would make the call succeed in PowerShell too, without special-casing.

This should be safe as long as the user's `$HOME` path has no embedded spaces - something I've never seen in the Unix world.

**Comment by isidorn** [comment]
@gregg-miskelly might be, though @weinand would be better to answer here since he is the author.

**Comment by weinand** [comment]
When using an "external" terminal, VS Code assumes a POSIX-like shell on Unix platforms.

When using an "integrated" terminal, VS Code honours the VS Code setting `terminal.integrated.shell.<platform>` (but it does not respect the shell configured via `chsh` either).

I suggest that you file a feature request against VS Code.

As a workaround you can use an "integrated" terminal  and set `terminal.integrated.shell.osx` to `/usr/local/bin/pwsh`.

**Comment by mklement0** [comment]
Thanks, guys.

I've opened https://github.com/Microsoft/vscode/issues/60971, as a generalized feature request.
