### ISSUE TITLE
Make hover experience consistent with Visual Studio

### ISSUE THREAD

**Issue by akshita31** [OmniSharp/omnisharp-vscode#2610]
In the "HoverProvider" we are showing all the documentation, however, in Visual Studio we only display the "Summary Text" part of the documentation.

This is the image from Visual Studio
![vs_hover](https://user-images.githubusercontent.com/12554141/47064763-8f575e00-d195-11e8-9744-8efb9ae22b9b.PNG)

This is the image from the vscode C# extension:
![vscode_hover](https://user-images.githubusercontent.com/12554141/47064777-a302c480-d195-11e8-8621-c7bb5a2dc81b.PNG)

**Comment by SirIntruder** [comment]
This should be done by consuming this: https://github.com/dotnet/roslyn/pull/20554?
