### ISSUE TITLE
debugger - Async frames of external code can take a lot of space in callstack window

### ISSUE THREAD

**Issue by chuckries** [OmniSharp/omnisharp-vscode#262]
This is stopped in the MusicStore app after an async call. There is only one user frame but we show many alternating external code/async call frames. This takes up a large amount of space in the already limited UI and offers zero benefit to the user as far as I can tell. This is with JMC on.
![selection_001](https://cloud.githubusercontent.com/assets/6598594/14930041/ecdb7c96-0e15-11e6-81ba-12f061ba54c9.png)

**Comment by caslan** [comment]
Closing this for now as we haven't heard any more user feedback on this.
