### ISSUE TITLE
Error message for evaluated expressions with a divide by zero may be wrong

### ISSUE THREAD

**Issue by v-mengzh** [OmniSharp/omnisharp-vscode#2628]
Environment data
OS and Version: Mac Version 10.12.6
VS Code Version: 1.28.2
C# Extension Version:1.17.0-beta6

Steps to reproduce
1.Install vscode.
2.Install C# extension.
3.Open the Terminal, run as follow command to create new console project:
dotnet new console -o myapp
4.Add some code in the program.cs as below:
![image](https://user-images.githubusercontent.com/32150874/47558288-5c575c00-d945-11e8-8c05-ff9c699d64ad.png)
5. configure launch.json as following:
![image](https://user-images.githubusercontent.com/32150874/47559597-7fcfd600-d948-11e8-97a2-2f2e30542ee4.png)
6. Set a breakpoint at line contain "set a bp"
7. F5, wait for hitting the breakpoint
8. Add "a/0" in Watch window

Expected
Evaluate variable successfully.

Actual
Can not evaluate the value correctly.
![image](https://user-images.githubusercontent.com/32150874/47558665-3bdbd180-d946-11e8-9d83-dd41eb3d7505.png)

Investigation
When add another variable to refresh watch window. "a/0" could evaluate correctly as below:
![image](https://user-images.githubusercontent.com/32150874/47558995-05eb1d00-d947-11e8-8706-5ef74f40cbae.png)

**Comment by gregg-miskelly** [comment]
Windows also has a similar problem. We will address this in 1.18.
