### ISSUE TITLE
debugger - Step over property gives VS IDE specific output in debug console

### ISSUE THREAD

**Issue by chuckries** [OmniSharp/omnisharp-vscode#263]
This appears in the debug console when stepping over a property:

```
Step into: Stepping over property 'MusicStore.Models.Album.get_AlbumId'.  To step into properties, go to Tools->Options->Debugging and uncheck 'Step over properties and operators (Managed only)'.
WARNING: Your step-into request resulted in an automatic step-over of a property or operator.
This behavior can be overridden in the context menu for the line being executed by choosing 'Step Into Specific'  or by unchecking the option 'Step over properties and operators'.
Do you want to continue being notified when an automatic step-over happens?
```

**Comment by sternb0t** [comment]
I'm experiencing this too. Any known workarounds?

**Comment by gregg-miskelly** [comment]
@sternb0t if you want to stop in the property - set a breakpoint, if you are just concerned about the text -- you will need to ignore it.

**Comment by sternb0t** [comment]
Thanks @gregg-miskelly but how can I set a breakpoint in a .NET core property like the ones in `System.ComponentModel.DataAnnotations`? Those aren't defined in my code. I was hoping `justMyCode: true` in `launch.json` would allow me to step in to wherever that code lives.

**Comment by sternb0t** [comment]
Sorry I meant to say `justMyCode: false`!

**Comment by gregg-miskelly** [comment]
In the short term, it is pretty different to step into the CoreFX. Here is what you would need to do though:

1. You need a copy of CoreFX which is built using portable PDBs. @Noahfalk @StephenToub do you by chance know if there is a builtin way to do this today? Would enlisting and building on Unix work.
2. You need a copy of CoreFX sources (ex: `git clone https://github.com/dotnet/corefx.git` and checkout the right branch)
3. You need to get your project to use the CoreFX you just built.
4. If you want to step into a property, as I said, you will need to find the right source file and set a breakpoint.

**Comment by gregg-miskelly** [comment]
BTW: We have a planned feature to make this process less painful. We didn't have an issue tracking this, so I opened #373 so that you can follow progress if you are interested.

**Comment by sternb0t** [comment]
Awesome, thank you for this.

**Comment by noahfalk** [comment]
This issue has the latest status I'm aware of on CoreFX binaries producing portable PDBs:
https://github.com/dotnet/corefx/issues/5733

@dagood

**Comment by gregg-miskelly** [comment]
@chuckries I believe this is addressed with https://github.com/OmniSharp/omnisharp-vscode/pull/530. Correct? If so, can you close it?

**Comment by chuckries** [comment]
@gregg-miskelly correct, this fix is in master and will be in the next release.
