### ISSUE TITLE
Lag when using C# autocomplete in Razor

### ISSUE THREAD

**Issue by welkie** [OmniSharp/omnisharp-vscode#2637]
## Issue Description ##

When trying to use the new C# razor intellisense feature, it works but it takes a few seconds to register changes you make to the code, such as setting a new variable. Other changes like choosing to call a different method on a variable are instant intellisense. It looks like the lag is just when the variable's type is changed or the variable is first introduced.

Here is what it looks like when I first declare a variable and hit the period key to activate intellisense:

![untitled](https://user-images.githubusercontent.com/7719209/47809689-e45bae00-dd17-11e8-91ff-e3eb30b66f9c.png)

And here is what it looks like if I wait a few seconds and hit period again to reactivate intellisense:

![untitled2](https://user-images.githubusercontent.com/7719209/47809698-e887cb80-dd17-11e8-97f7-47e9cc845256.png)

## Steps to Reproduce ##

Try to use Razor intellisense with 1.17.0+ of the omnisharp extension.

## Expected Behavior ##

Immediate intellisense.

## Actual Behavior ##

Delayed intellisense.

### OmniSharp log ###
```
Starting OmniSharp server at 2018-10-31, 1:56:37 PM
    Target: /home/matt/MvcTest

OmniSharp server started.
    Path: /home/matt/.vscode/extensions/ms-vscode.csharp-1.17.0/.omnisharp/1.32.6/run
    PID: 21382

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 18.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "/home/matt/.vscode/extensions/ms-vscode.csharp-1.17.0/.omnisharp/1.32.6/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/matt/.vscode/extensions/ms-vscode.csharp-1.17.0/.omnisharp/1.32.6/omnisharp/msbuild/15.0/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "/home/matt/.vscode/extensions/ms-vscode.csharp-1.17.0/.omnisharp/1.32.6/omnisharp/msbuild/15.0/Bin"
            MSBuildExtensionsPath = /home/matt/.vscode/extensions/ms-vscode.csharp-1.17.0/.omnisharp/1.32.6/omnisharp/msbuild
            BypassFrameworkInstallChecks = true
            CscToolPath = /home/matt/.vscode/extensions/ms-vscode.csharp-1.17.0/.omnisharp/1.32.6/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/matt/.vscode/extensions/ms-vscode.csharp-1.17.0/.omnisharp/1.32.6/omnisharp/msbuild/15.0/Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/matt/MvcTest'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/matt/MvcTest'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/matt/MvcTest/MvcTest.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/matt/MvcTest'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/matt/MvcTest' on host 21218.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/matt/MvcTest/MvcTest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/matt/MvcTest/MvcTest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/matt/MvcTest/MvcTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MvcTest
```

## Environment information ##

**VSCode version**: 1.28.2
**C# Extension**: 1.17.0

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.17.0|
|docomment|k--kato|0.1.2|
|dotenv|mikestead|1.0.1|
|gitlens|eamodio|8.5.6|
|java|redhat|0.33.0|
|vscode-docker|PeterJausovec|0.3.1|
|vscode-java-debug|vscjava|0.14.0|
|vscode-java-pack|vscjava|0.4.0|
|vscode-java-test|vscjava|0.10.0|
|vscode-maven|vscjava|0.11.1|
|vscode-npm-script|eg2|0.3.5|
|xml|DotJoshJohnson|2.3.2|;

</details>

**Comment by NTaylorMullen** [comment]
Hey @welkie, thanks for testing everything out 😄 . That's currently a known issue over in the [Razor.VSCode repo](https://github.com/aspnet/Razor.VSCode/issues/215).

There's also another duplicatish like issue [here](https://github.com/aspnet/Razor.VSCode/issues/210). I've looked into it a little bit and it seems that OmniSharp is providing completions for stale data. I'll have to investigate it more as to why it's doing that.

**Comment by welkie** [comment]
@NTaylorMullen Ah that does look like a duplicate. Is this the right repo to report Razor issues with omnisharp? I used the command pallet shortcut for reporting issues.

**Comment by NTaylorMullen** [comment]
Sadly not, adding a command pallet bit to create Razor issues is something we definitely want to do though. For now we're asking people to file Razor issues over in https://github.com/aspnet/Razor.VSCode so we don't add too many issues to the OmniSharp repo 😄. OmniSharp folks have been super supportive in shipping a Razor experience so we're doing all we we can to lessen their load.

**Comment by welkie** [comment]
Sounds good. In the mean time I can just use the command pallet to start the issue and then copy paste it over to the Razor repo. Closing this issue since it's a duplicate, thanks again for your help.
