### ISSUE TITLE
Changed files are not updated in output directory

### ISSUE THREAD

**Issue by nicolasr75** [OmniSharp/omnisharp-vscode#264]
I don't know where to ask this or if I am generally misunderstanding something.
I have a dotnet cli based web app which consists of cs code and html, js... in a wwwroot folder. When I press the start button in vscode for the first time, a _dotnet build_ is triggered and all necessary files are copied to the newly generated output directory.
When I change anything to my cs files the next start will copy the newly built DLL to the output directory. When I change an html or js file, however, these changed files get not copied to the output directory, so I'll always have to do that manually or delete the entire output directory, in which case every thing is copied over.

Is this a problem of VSCode, Omnisharp or Dotnet Cli ? Or do I have to configure some tasks myself?

**Comment by gregg-miskelly** [comment]
@nicolasr75 this sounds like either a .NET CLI issue, or an issue with your project.json (and therefore the templates if you haven't customized it). Would you mind porting your issue to https://github.com/dotnet/cli/issues?

**Comment by nicolasr75** [comment]
@gregg-miskelly  Ok, thanks. Then I will ask there.
