### ISSUE TITLE
Proposal: introduce `latest-stable` switch for `omnisharp.path` configuration

### ISSUE THREAD

**Issue by filipw** [OmniSharp/omnisharp-vscode#2644]
_From @d-dizhevsky on November 1, 2018 11:33_

Here is the note from user-config section:

 > // Specifies the path to OmniSharp. This can be the absolute path to an OmniSharp executable, a specific version number, or "latest". If a version number or "latest" is specified, the appropriate version of OmniSharp will be downloaded on your behalf.
>
>  "omnisharp.path": null

It would be handy if I could also tell it to keep my local version up-to-date with the latest stable up to minor version (i.e. download 1.32.7, but ignore 1.32.7-beta.*).

With `latest`:
 - **1.32.7-beta.23 <-- this is the version it will download**
 - 1.32.7-beta.22
 - 1.32.7-alpha.1

With `latest-stable`:
 - 1.32.7-beta.23
 - 1.32.7-beta.22
 - 1.32.7-alpha.1
 - **1.32.6 <-- this is the version it will download**
 - 1.32.6.beta-123
 - 1.32.5

_Copied from original issue: OmniSharp/omnisharp-roslyn#1325_

**Comment by filipw** [comment]
_From @DustinCampbell on November 1, 2018 20:33_

I think this is meant for the omnisharp-vscode repo, correct?

**Comment by d-dizhevsky** [comment]
@filipw have you used he new github feature to move the issue between the repos? I thought it should have been kept it as is 🤔

**Comment by filipw** [comment]
no i didn't

**Comment by af4jm** [comment]
Agreed, opting into the latest version & auto-updates and opting into beta versions are 2 VERY different things... since neither the setting nor its documentation mention beta versions, this should be classified as a bug for not ignoring beta versions, and the feature-request should be to add "latest-beta"... meanwhile I'm removing "latest" from my settings since it doesn't work as documented

**Comment by rchande** [comment]
@d-dizhevsky @af4jm I'd like to clarify the purpose of the `latest` feature. We originally conceived it as a way to improve our CI testing strategy for the C# extension. C# extension and OmniSharp are built in separate repos, so prior to the `latest` feature, to build a new feature in OmniSharp and consume it in the extension, you had to check the feature into OmniSharp, create a release, and update the C# extension to consume the new build--just to make new tests in the extension pass in PR build. With the `latest` feature, the PR builds always test against the latest build of OmniSharp, which lets us turn around cross-cutting features much faster. Also, when we fix bugs in OmniSharp, `latest` makes it for users to try out new builds to test them. 

In that sense, I believe the `latest` feature behaves as we've designed it to. 

Regarding `latest-stable`, I believe you would get the same behavior by enabling extension auto-update and turning off the `latest` option: when we update the extension, you'll auto-update and get the new built in version. You'll also avoid any builds that aren't good enough to ship (we haven't included every release on [this page](https://github.com/OmniSharp/omnisharp-roslyn/releases) in a new version of the extension). 

Thoughts?

**Comment by filipw** [comment]
I agree with @rchande that it works as it was designed, which is to grab the latest build from OmniSharp server master branch. It is also documented [here](https://github.com/OmniSharp/omnisharp-roslyn#vs-code), where it explicitly says:

> The above option can also be set to:
> * "latest" - To consume the latest build from the master branch
> * A specific version number like 1.29.2-beta.60

However, I also agree that it's not immediately obvious when looking at the documentation in the user config file, which is where the text could be improved to better reflect what the user is opting into. But yeah, `latest-stable` would be really the extension auto update, since the extensions beta releases are built against what is a de facto "stable" OmniSharp server release.
