### ISSUE TITLE
Consider: Don't start razor language service when there are no razor files

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#2649]
## Environment data
C# Extension version: 1.17

## Steps to reproduce
1. Create a new C# .NET Core console app
2. Open the folder in VS Code

## Expected  behavior
Razor language service (rzls) process shouldn't start since there are no razor files

## Actual behavior
Razor language service starts

**Comment by NTaylorMullen** [comment]
This is definitely a reasonable request. @gregg-miskelly would you mind filing the issue over in https://github.com/aspnet/Razor.VSCode?

**Comment by gregg-miskelly** [comment]
I can move it using https://github-issue-mover.appspot.com

**Comment by gregg-miskelly** [comment]
This issue was moved to aspnet/Razor.VSCode#222
