### ISSUE TITLE
Cannot start Debugger after a failed compile

### ISSUE THREAD

**Issue by kevingbb** [OmniSharp/omnisharp-vscode#2651]
## Steps to Reproduce ##
mkdir csharptest
cd csharptest
dotnet new console
Start Debugger and Hello World Executes properly.
Remove the semi-colon at the end of Hello World line in Program.cs to simulate a compile-time error.
Start Debugger, compile time error is found, message box pops up
Resolve the error by adding the semi-colon back in.
Start Debugger, but nothing happens.
## Expected Behavior ##
Debugger should be able to start after correcting error.
## Actual Behavior ##
Nothing happens, Debugger does not start and no error messages are displayed with the exception of the following in the Problem windows which does not go away:
; expected [/Users/kev/repos/csharptest/csharptest.csproj]
When clicking on the problem it takes me to the compile-time error in the Program.cs file.
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Starting OmniSharp server at 11/3/2018, 11:12:50 AM
    Target: /Users/kev/repos/csharptest

OmniSharp server started.
    Path: /Users/kev/.vscode/extensions/ms-vscode.csharp-1.17.0/.omnisharp/1.32.6/run
    PID: 69274

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.13.6 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "/Users/kev/.vscode/extensions/ms-vscode.csharp-1.17.0/.omnisharp/1.32.6/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/Users/kev/.vscode/extensions/ms-vscode.csharp-1.17.0/.omnisharp/1.32.6/omnisharp/msbuild/15.0/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "/Users/kev/.vscode/extensions/ms-vscode.csharp-1.17.0/.omnisharp/1.32.6/omnisharp/msbuild/15.0/Bin"
            MSBuildExtensionsPath = /Users/kev/.vscode/extensions/ms-vscode.csharp-1.17.0/.omnisharp/1.32.6/omnisharp/msbuild
            BypassFrameworkInstallChecks = true
            CscToolPath = /Users/kev/.vscode/extensions/ms-vscode.csharp-1.17.0/.omnisharp/1.32.6/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /Users/kev/.vscode/extensions/ms-vscode.csharp-1.17.0/.omnisharp/1.32.6/omnisharp/msbuild/15.0/Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/kev/repos/csharptest'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/kev/repos/csharptest'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/kev/repos/csharptest/csharptest.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/kev/repos/csharptest'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/kev/repos/csharptest' on host 69244.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/kev/repos/csharptest/csharptest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/kev/repos/csharptest/csharptest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/kev/repos/csharptest/csharptest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: csharptest
</details>

## Environment information ##

**VSCode version**: 1.28.2
**C# Extension**: 1.17.0

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.103 [/usr/local/share/dotnet/sdk]
  2.1.400 [/usr/local/share/dotnet/sdk]
  2.1.403 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azds|azuredevspaces|0.1.120181023|
|azure-account|ms-vscode|0.4.3|
|azure-iot-edge|vsciot-vscode|1.5.1|
|azure-iot-toolkit|vsciot-vscode|1.6.0|
|azurecli|ms-vscode|0.4.2|
|chat|karigari|0.7.3|
|code-runner|formulahendry|0.9.5|
|csharp|ms-vscode|1.17.0|
|Go|ms-vscode|0.6.93|
|node-module-intellisense|leizongmin|1.5.0|
|npm-intellisense|christian-kohler|1.3.0|
|python|ms-python|2018.9.2|
|team|ms-vsts|1.142.0|
|terraform|mauve|1.3.7|
|vscode-azureappservice|ms-azuretools|0.9.1|
|vscode-azurefunctions|ms-azuretools|0.12.0|
|vscode-csproj|lucasazzola|0.7.0|
|vscode-docker|PeterJausovec|0.3.1|
|vscode-helm|technosophos|0.4.0|
|vscode-kubernetes-tools|ms-kubernetes-tools|0.1.14|
|vscode-markdownlint|DavidAnson|0.21.0|
|vscode-npm-script|eg2|0.3.5|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-yaml|redhat|0.0.17|
|vsliveshare|ms-vsliveshare|0.3.897|
|vsliveshare-audio|ms-vsliveshare|0.1.39|
|vsliveshare-pack|ms-vsliveshare|0.2.0|;

</details>

**Comment by gregg-miskelly** [comment]
I _think_ this is due to Live Share. Can you try disabling it and see if that fixes it?

**Comment by kevingbb** [comment]
I did have Live Share running. I disabled Live Share and that fixed the problem.
