### ISSUE TITLE
mniSharp.MSBuild.ProjectManager  Attemped to update project that is not loaded

### ISSUE THREAD

**Issue by cuongngoht** [OmniSharp/omnisharp-vscode#2653]
## Environment data
`dotnet --info
` output:

![image](https://user-images.githubusercontent.com/40376533/47960841-b934cf80-e033-11e8-9057-bb8a53badd03.png)

VS Code version:
C# Extension version:
![image](https://user-images.githubusercontent.com/40376533/47960775-81795800-e032-11e8-8864-cd49eaadd201.png)

## Steps to reproduce
1.Uninstall omnisharp 1.1.17
2.Install omnisharp 1.1.17

## Expected  behavior
Can debug code and reflection code C# in Visual Code

## Actual behavior
![image](https://user-images.githubusercontent.com/40376533/47960822-46c3ef80-e033-11e8-9c20-5fd94107745f.png)

**Comment by rchande** [comment]
@cuongngoht Please share full omnisharp log.

**Comment by arrebole** [comment]
Uninstall other MSBuild

**Comment by akshita31** [comment]
@cuongngoht Please post the full omnisharp log. The picture posted above doesnt show any errors, that would help us debug the problem

**Comment by cartermp** [comment]
Closing out as no additional info was added.
