### ISSUE TITLE
Fails to start debugging on Arch.

### ISSUE THREAD

**Issue by ThisDrunkDane** [OmniSharp/omnisharp-vscode#2655]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     manjaro
 OS Version:
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.1.5 [/opt/dotnet/shared/Microsoft.NETCore.App]
```
VS Code version: 1.27.2
C# Extension version: 1.16.2

## Steps to reproduce
1. Run vs code on a new console application
2. Add default VSCode launch.json for .NET Core, fix paths.
3. Press f5.

## Expected  behavior
For debugging to begin.

## Actual behavior
Debugging fails to start with a popup in the corner saying
```
Error processing 'configurationDone' request. Unknown Error: 0x89720010

**Comment by gregg-miskelly** [comment]
@ThisDrunkDane This means you are not using an official version of VS code. Only official versions from Microsoft support .NET Debugging.
