### ISSUE TITLE
The output panel is opened automatically every time a project is opened

### ISSUE THREAD

**Issue by apkd** [OmniSharp/omnisharp-vscode#2656]
## Environment data
`dotnet --info` output:
- Unlikely to be relevant but [here it is](https://gist.github.com/apkd/7410096f7f10c91b8b188c9d02df9199)

VS Code version:
- 1.28.2

C# Extension version:
- 1.17.0

## Steps to reproduce
1. Open a C# workspace

Alternatively,

1. Use the `Omnisharp: Restart Omnisharp` command

## Expected  behavior
Omnisharp doesn't open any windows or panels unless an error has occured and/or intervention is required

## Actual behavior
The output panel is **automatically** opened with the following information:

```
Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.32.7-beta.44...
Platform: win32, x86_64

Finished
```

This is obviously an anti-pattern:
- I don't need this information
- I don't want this information
- **I can't find any way to disable this**
- No other extension does this (thankfully)
- If more extensions did this, they would conflict with each other, and the latest one to open the output tab would override all others

**Comment by rchande** [comment]
@apkd I suspect you have the option `omnisharp.path` set to `latest`. If you unset the option or set it to a specific version or path this will stop happening.

**Comment by apkd** [comment]
@rchande Thanks, this helped. I think I toggled the setting to `latest` a while ago in order to get rid of the message in the first place, but now the problem appears resolved.
