### ISSUE TITLE
Extension should consider using vscode.open for browser launch

### ISSUE THREAD

**Issue by auchenberg** [OmniSharp/omnisharp-vscode#2657]
Hi Kenneth from the VS Code team here,

We noticed the `launchBrowser` attribute in the launch.json as this extension has it's own logic to launch browsers.

For future scenarios we recommend using the VS Code API `vscode.open` that can open a URL in the browser. It works on all platforms, so when the C# extension can invoke this command, then this should work.

**Comment by gregg-miskelly** [comment]
@auchenberg How could we use this? We launch the browser from the debugger.

**Comment by gregg-miskelly** [comment]
This issue is no longer needed. Support for this is handled by `serverReadyAction`.
