### ISSUE TITLE
Avoid using onDebug activationEvent

### ISSUE THREAD

**Issue by roblourens** [OmniSharp/omnisharp-vscode#2658]
I noticed that the C# extension is a bit slow to activate, and it activates using `onDebug`, which is fired for every debug session. It would be better to use one of the more fine-grained activation events, `onDebugInitialConfigurations` or `onDebugResolve:type`.

Example: https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L86

Details: https://code.visualstudio.com/updates/v1_19#_debug-contributions-in-packagejson

Otherwise, it's annoying to start debugging a node app and have a window pop up, "Installing C# dependencies...".

**Comment by gregg-miskelly** [comment]
Sounds good. We didn't notice that these were added.

**Comment by isidorn** [comment]
I just wanted to create this but @roblourens beat me to it.
Yeah it would be great that you use more specific activation events.
Example how Java is doing it https://github.com/Microsoft/vscode-java-debug/blob/14fe7d5d0d41a397eaff4f3701860653850058fb/package.json#L31
