### ISSUE TITLE
OmniSharp fails to conditionally load NuGet packages

### ISSUE THREAD

**Issue by savornicesei** [OmniSharp/omnisharp-vscode#2660]
Hi all,

I am working on updating [NDbUnit](https://github.com/savornicesei/NDbUnit2/tree/develop) to the latest and greatest in .NET environment.
My dev environment is:

- OpenSUSE Tumbleweed
- JetBrains Rider IDE 2018.2.3
- Visual Studio Code 1.28.2
- C# plugin for VS Code 1.17.0

## Environment data
simona@devrog:/data/Proiecte/Proiecte/[oss] NDbUnit2/ndbunit2> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     opensuse-tumbleweed
 OS Version:  20181029
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

simona@devrog:/data/Proiecte/Proiecte/[oss] NDbUnit2/ndbunit2> mono --version
Mono JIT compiler version 5.10.1.47 (tarball Wed Aug 29 11:06:06 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
simona@devrog:/data/Proiecte/Proiecte/[oss] NDbUnit2/ndbunit2> 

VS Code version: 1.28.2
C# Extension version: 1.17.0

## Steps to reproduce
Since it is database related, most of the projects in the solution are using certain NuGet packages based on the platform. For example, the Oracle one uses ODP.NET core if build for netstandard, uses mono Oracle when on linux dotnet 45 and the classic ODP.NET for windows dotnet 45.

The dev branch of my project builds fine on linux from both the command line (dotnet build) and from Rider IDE however errors related to NuGet packages are shown when I open the project in Visual Studio Code
![image](https://user-images.githubusercontent.com/917232/48087604-72e49980-e208-11e8-8d51-0127c2c1e558.png)

Thank you.

**Comment by rchande** [comment]
@savornicesei Can you share your project file or explain how I can construct a similar one?

**Comment by savornicesei** [comment]
Here it is https://github.com/savornicesei/NDbUnit2/tree/develop (the develop branch).

**Comment by cartermp** [comment]
The problem reported does not reproduce for me with the latest plugin. That is, the packages are restore and the projects load. There appear to be some different problems related to compilation in other projects, but that's likely because it needs to build. Simply loading the solution in VS also shows compile errors unless a build of the solution is done.
