### ISSUE TITLE
Problem with project implementation built with visual studio in vsc

### ISSUE THREAD

**Issue by chrmarti** [OmniSharp/omnisharp-vscode#2664]
_From @hamedyo99 on November 10, 2018 8:23_

Hi, I created a mvc project with a visual studio. Then with vscode that I run, intellisense has a problem but when create with vscode is good everywhere .
 i have error :  OmniSharp.MSBuild.ProjectManager
Attempted to update the project that is not loaded: c: \ Users \ Hamed \ Documents \ Visual Studio 2017 \ Projects \ TestVS \ TestVS \ TestVS.csproj.
 for this reson dont run proje

_Copied from original issue: Microsoft/vscode#62885_

**Comment by akshita31** [comment]
@hamedyo99 Any updates here.
