### ISSUE TITLE
Can't Run/Debug .NET 3.5/4.5 Project on macOS

### ISSUE THREAD

**Issue by mikedJC** [OmniSharp/omnisharp-vscode#2672]
## Environment data
`dotnet --info` output:
Jams-MacBook-Pro:~ mikedesaro$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version:
C# Extension version: Version 1.29.0 (1.29.0) 5f24c93878bd4bc645a4a17c620e2487b11005f9

## Steps to reproduce
- open any project that targets .NET 3.5 or 4.5 that contains unit tests (or any version, I just happen to have these two versions at the moment)
- attempt to run any of the unit tests by clicking the "Run Test" or "Debug Test" buttons
- check OUTPUT console

## Expected  behavior
- the unit test should run and be debuggable

## Actual behavior
- the following log gets dumped to the console:

/usr/local/share/dotnet/sdk/2.1.403/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v3.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

Note that the same project runs fine in Visual Studio on the same computer so the .NET framework versions are certainly present.

**Comment by gregg-miskelly** [comment]
@mikedJC The C# extension only supports debugging .NET Core on non-Windows platforms, so this isn't support that we can provide. When you say "note that the same project runs fine in Visual Studio on the same computer so the .NET framework versions are certainly present", do you mean it runs fine in VS For Mac?

Maybe we could do something to allow run without debugging to work under Mono.
