### ISSUE TITLE
Omnisharp Fails To Download In VS Code

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-vscode#2681]
_From @firezdog on November 13, 2018 5:0_

Everything was working fine yesterday -- then today I opened the editor and got this.  Following the link indicates that the package is not found.  Omnisharp seemed to be working when I reset the path to "1.32.7" instead of "latest."

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.32.8-beta.4' Failed to download from https://roslynomnisharp.blob.core.windows.net/releases/1.32.8-beta.4/omnisharp-win-x64.zip. Error code '404')
Failed at stage: downloadAndInstallPackages
404

_Copied from original issue: OmniSharp/omnisharp-roslyn#1336_

**Comment by firezdog** [comment]
Issue is just a broken link / missing resource as far as I can tell.

**Comment by firezdog** [comment]
Any updates on this?  Do you plan to fix the link or just change the endpoint for "latest" to a working version?

**Comment by firezdog** [comment]
ok i will check

**Comment by firezdog** [comment]
I haven't yet been able to check this myself.  I can confirm the link itself still gives this message:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:2e8f6ccb-601e-00f5-316a-86c019000000 Time:2018-11-27T15:59:17.0695565Z
</Message>
</Error>

However, if you say it's fixed I believe you.  Don't see any reason to keep this issue open.

**Comment by akshita31** [comment]
@firezdog The current latest version is "1.32.8" and I can verify that it is downloading correctly for me.

**Comment by akshita31** [comment]
I will close this issue for now. Please reopen if the problem comes up again.
