### ISSUE TITLE
Discussion: Use post install script hook for downloading necessary librariies

### ISSUE THREAD

**Issue by sandy081** [OmniSharp/omnisharp-vscode#2692]
Hi,

I am developer from VS Code team and this milestone we are planning to introduce a new feature where you can have post install scripts for extensions. I see C# extension is one of the perfect examples to use this feature as it does some post install tasks like downloading necessary libraries during activation.

After a quick glance at the code, I figured out that you also preserve some state in the extension location to check if downloading has happened or not. One flaw I see here is that you might do download every time the extension is updated because the extension location changes.

To prevent this, as part of the post install script, we are also planning to provide a unique location where you can maintain state and determine what to do and what not to do during post install. Post install script is executed every time the extension is installed (including update).

I would request to check out this [post install hook](https://github.com/Microsoft/vscode/issues/23251) feature request in VS Code repo and provide your feedback and let us know if this suffice your downloading task.

**Comment by Surendrajat** [comment]
Any update on this one? I don't see this as an option yet. Is it being considered at all?
