### ISSUE TITLE
aspnetcorerazor format error

### ISSUE THREAD

**Issue by niltor** [OmniSharp/omnisharp-vscode#2695]
## Issue Description ##
Open a .cshtml, just like _Layout.cshtml,and you'll see:

![image](https://user-images.githubusercontent.com/8222201/48603523-ab773680-e9b1-11e8-9d1a-62b042b75903.png)

I had tried reinstall vscode,but can't solve problem.
## Steps to Reproduce ##
just open a .cshtml file
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.29.1
**C# Extension**: 1.17.1

<details><summary>Dotnet Information</summary>
.NET Core SDK����ӳ�κ� global.json��:
 Version:   2.1.500
 Commit:    b68b931422

����ʱ����:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Angular-BeastCode|Mikael|7.0.16|
|csharp|ms-vscode|1.17.1|
|ng-template|Angular|0.1.10|
|tslint|eg2|1.0.40|
|vscode-angular2-files|alexiv|1.6.2|
|vscode-language-pack-zh-hans|MS-CEINTL|1.29.2|
|vscode-markdownlint|DavidAnson|0.21.0|;

</details>

**Comment by NTaylorMullen** [comment]
@niltor are you referring to the incorrect coloring of the red square brackets on the meta tags?

**Comment by niltor** [comment]
@NTaylorMullen   yes,red color ,can't understand

**Comment by NTaylorMullen** [comment]
Ah, yes we're tracking this as part of https://github.com/aspnet/Razor.VSCode/issues/75

**Comment by rchande** [comment]
@niltor @NTaylorMullen I'm going to close this because it's being tracked under the aspnet repo.
