### ISSUE TITLE
Support high intensity ansi colours in debug console

### ISSUE THREAD

**Issue by MontyBlenheim** [OmniSharp/omnisharp-vscode#2696]
This 
This issue is basically to revive one I previously found: https://github.com/Microsoft/vscode/issues/21423

The issue was closed when underlining functionality was added, but the original request, for high intensity colours, was never addressed. Any chance these could be added?

**Comment by gregg-miskelly** [comment]
@MontyBlenheim is this an issue with the C# extension? If so, could you please provide steps to reproduce whatever problem you are running into?

**Comment by gregg-miskelly** [comment]
I will close this for now. Let us know if you have more details and we can take a look.
