### ISSUE TITLE
How to hit debug break point for AspNet C# console app.

### ISSUE THREAD

**Issue by weinand** [OmniSharp/omnisharp-vscode#270]
_From @v-pavanp on May 3, 2016 3:26_

- VSCode Version: 1.1.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1.  Create aspnet C# console project using yeoman. 
2. Open project folder in VSCode.
3. Set proper .net environment and configuration for debugging.
4. Update launch.json with properties:
              "stopAtEntry": true.
               "program": "${workspaceRoot}/bin/Debug/dnx451/win7-x64/TestCSharpWithVSCode.exe",
5. Set "debugType": "portable" in project.json.
6. Build project and set the brake point at entry point under program.cs (main function).
7. Now start debugging and verify app behavior.

Actual:
1. Debug break point is not hitting.
2. Should stop at entry point as stopAtEntry set to true.

Question: Am I missing something here? What are the settings I need to add to hit debug break point? 
I am following instructions from https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md  

_Copied from original issue: Microsoft/vscode#6052_

**Comment by weinand** [comment]
@v-pavanp C# debugging is a separate extension that is not part of VS Code core. I've moved this issue over to omnisharp-vscode.

**Comment by chuckries** [comment]
@v-pavanp What version dotnet cli do you have installed? What is the output of `dotnet --info` ?

**Comment by gregg-miskelly** [comment]
@v-pavanp I believe yeoman is going to generate an RC1 based application. So you don't want to use yeoman right now.

**Comment by v-pavanp** [comment]
Find below the .Net version detail :
C:\Users\v-pavanp>dotnet --info
Unknown option: --info
.NET Command Line Tools (1.0.0-beta-001661)
Usage: dotnet [common-options] [command] [arguments]

Arguments:
  [command]     The command to execute
  [arguments]   Arguments to pass to the command

Common Options (passed before the command):
  -v|--verbose  Enable verbose output
  --version     Display .NET CLI Version Info

Common Commands:
  new           Initialize a basic .NET project
  restore       Restore dependencies specified in the .NET project
  build         Builds a .NET project
  publish       Publishes a .NET project for deployment (including the runtime)
  run           Compiles and immediately executes a .NET project
  repl          Launch an interactive session (read, eval, print, loop)
  pack          Creates a NuGet package

**Comment by gregg-miskelly** [comment]
Here are the options that should work:

1. 'RC2 LKG' -- follow the instructions from https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md. Per the instructions, you can find an example ASP.NET Core app on https://github.com/caslan/cli-samples/tree/fordebuggerpreview.
2. 'RC2 current' -- follow instructions on https://aka.ms/vscclrdogfood
3. Wait for RC2 to be officially released. I _hope_ this is sometime very soon.
