### ISSUE TITLE
No syntax highlighting under very specific circumstances

### ISSUE THREAD

**Issue by zvinless** [OmniSharp/omnisharp-vscode#2702]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.500/

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.500 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```
VS Code version: 1.29.1
C# Extension version: 1.17.1

## Steps to reproduce
Input the following into VSCode into a .cs file:
```csharp
namespace SomeNamespace
{
	class Test
	{
		void Init()
		{
			Something.listener = async args => { return true; };
		}

		void ThisFunctionHasNoSyntaxHighlighting()
		{
			var aString = "test";
		}

		void ButThisOneIsFine()
		{
			var aString = "test";
		}
	}
}
```

(it looks like GitHub's highlighting has the same issue)

## Expected  behavior
The second function should be syntax highlighted. Both the `return` and `true` keywords should also be highlighted in the delegate assigned in the first function. 

## Actual behavior
The things mentioned above should be highlighted since it's all valid C#. The `return true` highlighting issue seems to be independent but maybe related to the function highlighting issue. Here's a screenshot in my editor:
<img width="508" alt="nohighlight" src="https://user-images.githubusercontent.com/24303763/48983291-bb71d300-f0a1-11e8-8fbe-898602015f2e.png">

There are many things that fix the second function's highlighting, such as:
* Adding parens around `args` in the delegate in the first function (this also fixes the `return true` highlighting)
* Removing the `async` keyword in the delegate
* Removing the namespace

**Comment by rchande** [comment]
Ported to https://github.com/dotnet/csharp-tmLanguage/issues/142
