### ISSUE TITLE
Debugger won't start until I turn off Windows Defender Realtime Protection

### ISSUE THREAD

**Issue by whizkidwwe1217** [OmniSharp/omnisharp-vscode#2708]
## Environment data
`dotnet --info` output:
```
NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
VS Code version: both latest public & insider versions
C# Extension version: 1.17.1

## Steps to reproduce
1. Enable Windows Defender Realtime Protection
2. Open Visual Code (Public or Insider) with Omnisharp extension of course.
3. Press F5 to run in Debug mode.

## Expected  behavior
Should start debugging.

## Actual behavior
Issue: Debugger won't start building the project. It only launches the debugger toolbar with all the buttons grayed out except the stop button, which is also not working.
I noticed that after your launch the debugger, it bumps up the Antimalware service's CPU utilization to more than 50%. 
If I tried executing `dotnet run` or `dotnet build` command in the terminal, it's working fine so I think it's not an issue with the ASP.Net framework. 
The issue only happened when the Omnisharp got updated to the latest version.
If I disable the Windows Defender Realtime Protection, it's starts building and now the debugger will be running back to normal.
![image](https://user-images.githubusercontent.com/1977391/49088731-deb0a400-f294-11e8-87ed-43de8bc06064.png)

**Comment by gregg-miskelly** [comment]
@whizkidwwe1217 A few questions:

1. If you go to Windows Security Settings->Virus and Thread Protection-> Virus & threat protection updates->Check for updates, then click 'Check for updates', are there any definition updates available? If not, what definition version do you have?

2. If the first thing didn't help, if you go back to the 'Virus and Thread Protection' screen, and bring up Threat history, does it give you any information about what it didn't like?

**Comment by whizkidwwe1217** [comment]
@gregg-miskelly It has the latest threat definitions. Threat history is clean. I tried adding VS Code, rg.exe & OmniSharp.exe to Windows Defender Exclusions but to no avail. In my last test, I didn't turned off the realtime protection. It's almost 10 minutes already and the debugger hasn't fired up yet. Then after 15 minutes of waiting, the Windows Defender's Anti-malware service's CPU utilization dropped, then it starts building and debugging. Is Windows Defender blocking OmnisSharp's process? When I debug using Visual Studio 2017, it only takes 5-10 seconds to launch the debugger. Even `dotnet run` doesn't take long to startup the app.

![image](https://user-images.githubusercontent.com/1977391/49121214-a63bb500-f2ea-11e8-8bd8-dc11ced9ce51.png)

![image](https://user-images.githubusercontent.com/1977391/49121082-257cb900-f2ea-11e8-980a-8f1872d224b1.png)

![image](https://user-images.githubusercontent.com/1977391/49121170-7ee4e800-f2ea-11e8-95d7-d42646d249ef.png)

![image](https://user-images.githubusercontent.com/1977391/49121375-35e16380-f2eb-11e8-8c23-48b09c0b8375.png)

![image](https://user-images.githubusercontent.com/1977391/49121176-87d5b980-f2ea-11e8-8159-c1811d7f4c23.png)

**Comment by whizkidwwe1217** [comment]
The good thing though is that it's only happening the first time you fired up the debugger. The next time you launch the debugger, it's fast. But again, when I restart my PC, same thing happens.

**Comment by gregg-miskelly** [comment]
I am not able to repro this, and this is the only report we have of the issue, so I can't immediately give you any good advice.

A few more questions:
1. If you execute the build task without also debugging (Ctrl+Shift+B, select build) do you see the problem there also?
2. If not, if you open a command prompt and run `"%USERPROFILE%\.vscode\extensions\ms-vscode.csharp-1.17.1\.debugger\vsdbg-ui.exe" /?` does that show the problem?

**Comment by gregg-miskelly** [comment]
How about my second question?

**Comment by whizkidwwe1217** [comment]
No, the command you gave doesn't show the problem. It just displays the usage of `vsdbg-ui.exe`.

**Comment by gregg-miskelly** [comment]
I am kind of out of ideas as to what is causing the problem then. 

I think my best suggestion would be to try adding process and/or path exclusions to the defender rules (Virus & thread protection settings->Exclusions). I would probably try turning of the 'dotnet.exe' and 'vsdbg-ui.exe' processes.

Another thing you could try is disabling 'Cloud-delivered protection'. I don't know if that will help, but I have seen that setting really slow down debug launches in other scenarios.

If neither of those are helpful, you could see if anything shows up in the Windows Defender section of Event Viewer (Applications and Services Logs->Microsoft->Windows->Windows Defender Antivirus).

Lastly, you could try reporting the issue to the Windows Defender team through the Windows Feedback hub.

**Comment by whizkidwwe1217** [comment]
@gregg-miskelly Thank you for all the feedback. I really appreciate it. 
I'll take that suggestion and will try to exclude all processes related to vs code in Defender. There might be running services or something that slow down the debug launches so I might be cleaning up my PC resources a bit. For now, I can just disable real-time protection the first time I hit debug then turn it back on. We can close this issue for now.
