### ISSUE TITLE
Not getting any response while running DNX command multiple times.

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#271]
_From @v-pavanp on May 3, 2016 4:29_

- VSCode Version: 1.1.0-alpha
- OS Version: windows10

Steps to Reproduce:
1. Create Aspnet C# console app using yeoman.
2. Set proper dotnet environment and verify response using dnx restore and dnx run.
3. Launch VSCode and open project folder.
4. Configure launch.json, task.json.
5. Perform DNX restore and DNX run command and verify response.
6, Now update project.json and add "debugType": "portable" under compilationOptions.
7. Build project and verify if any error message or warning is showing up.
8. Now try to perform "DNX restore" and "DNX: run command" operation from command palette and verify app behavior.

Actual: DNX command is responding very first time only and for further dnx execution there is no response.
Expected: User should get proper response when executing DNX command from command palette.

Note: Each time user needs to reload window or restart app to get DNX response.

![dnxissuenew](https://cloud.githubusercontent.com/assets/17735796/14974661/9e5a0a30-10ac-11e6-958e-bf95d4f551e3.gif)

_Copied from original issue: Microsoft/vscode#6055_

**Comment by alexgwolff** [comment]
Dnx commands are obsolete(I guess), try using dotnet restore.
To create a new project you can use "dotnet new" in command line

**Comment by DustinCampbell** [comment]
If you're using the .NET CLI, the DNX commands definitely won't work.

**Comment by v-pavanp** [comment]
Actually, if you see in the provided gif with the bug then you will find that DNX command is working but only at every first time (when you launch an app) and each time we need to restart VSCode to make it working.

**Comment by DustinCampbell** [comment]
It's interesting that they work at all, but I can imagine them not working consistently. Could you run `dotnet --info` to show what version you have installed?

**Comment by v-pavanp** [comment]
Find the below detail:
C:\src\MyTestAppExpressForTimer\MyTestAppExpressForTimer>dotnet --info
Unknown option: --info
.NET Command Line Tools (1.0.0-beta-001661)
Usage: dotnet [common-options] [command] [arguments]

Arguments:
  [command]     The command to execute
  [arguments]   Arguments to pass to the command

Common Options (passed before the command):
  -v|--verbose  Enable verbose output
  --version     Display .NET CLI Version Info

Common Commands:
  new           Initialize a basic .NET project
  restore       Restore dependencies specified in the .NET project
  build         Builds a .NET project
  publish       Publishes a .NET project for deployment (including the runtime)
  run           Compiles and immediately executes a .NET project
  repl          Launch an interactive session (read, eval, print, loop)
  pack          Creates a NuGet package

**Comment by v-pavanp** [comment]
Also to provide you more info, from command line I am getting DNX response all the time, it is just a matter with VSCode for same project.

**Comment by DustinCampbell** [comment]
It sounds like you are living in a bit of a half-DNX/.NET CLI world, which can be a bit broken. If you're working on a .NET Core app (as opposed to the older DNX-style app), I'd recommend grabbing the latest .NET CLI from https://github.com/dotnet/cli and the most recent C# Extension for VS Code from https://github.com/OmniSharp/omnisharp-vscode/releases.

Please check out @gregg-miskelly's response to you in #270. He provided all of the information you need to get fixed up.

**Comment by v-pavanp** [comment]
I got it fixed and able to debug my code. Please close this issue as I didn't see option for closing.

**Comment by DustinCampbell** [comment]
Glad to hear it! Let us know if you have anymore trouble.
