### ISSUE TITLE
Is there a way to get hexadecimal output for watch and variables while debugging?

### ISSUE THREAD

**Issue by cgraig** [OmniSharp/omnisharp-vscode#2713]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

**Comment by gregg-miskelly** [comment]
Yes, you can evaluate an expression with `,h` (for hex) at the end. Example: `myVariable,h`

Here is the full list: https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/format-specifiers-in-csharp.md#format-specifiers

**Comment by cgraig** [comment]
Great, thank you!  Is there any way to apply the expression evaluation as a default for the "locals" variables?  I could be misunderstanding but to get a hex view I need to add the variable to my watch window and then apply the ",h" evaluation.  Was wondering/hoping there was a way to do this by default for all variables.

Thanks again!

**Comment by gregg-miskelly** [comment]
Unfortunately VS Code doesn't have any UI to toggle between hex and decimal output. There is a feature request to enable this if you want to go "+1" it -- https://github.com/Microsoft/vscode/issues/28025

The one possible work around (besides adding things you want to look at to the watch window and adding the ',h' specifier) -- if you mostly run into this with a particular variable/field/property, you could wrap that variable and a struct like below.

```C#
[DebuggerDisplay("{Value,h}")]
struct HexInt
{
    public int Value;
}
```
