### ISSUE TITLE
C# output channel steals editor focus

### ISSUE THREAD

**Issue by seraku24** [OmniSharp/omnisharp-vscode#2717]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS Code version: **1.29.1** (x64)
C# Extension version: **1.17.1**

## Steps to reproduce
1. Start with the C# extension freshly installed (i.e. without any of the packages downloaded or installed)
2. Create a new C# file (e.g. `hello.cs`)
3. Begin typing in the editor

## Expected behavior
Editor keeps focus while the C# extension downloads and installs packages.

## Actual behavior
The C# output channel steals focus from the editor.

**Comment by seraku24** [comment]
While I do appreciate the desire to keep users well-informed; at the end of the day, it must never be "by design" to steal focus from a user.

If it is not possible to preserve editor focus while showing the output panel, then it would seem an output channel is the wrong choice for surfacing this type of important information.  A notification would be far more appropriate, as it is modeless and does not steal focus.  For users that do wish to see the download/installation process, the notification ideally would provide an option to open the output channel for more details.

**Comment by rchande** [comment]
@seraku24 That's good feedback, thank you. I imagine there are a few possible improvements:
* show the channel in a way that doesn't steal focus (not sure if APIs allow this)
*  provide a notification to allow interested users to focus the channel, as you suggested
* something else, perhaps show the output less often

We'll come up with a better design.
