### ISSUE TITLE
[ERROR] Error: Command failed: cat /etc/*-release

### ISSUE THREAD

**Issue by junjiangao** [OmniSharp/omnisharp-vscode#272]
OS:Linux Mint 17.3 Rosa 
omnisharp-vscode:csharp-1.0.5-rc2.vsix
i know  #204 #207 
but vscode still show [ERROR] Error: Command failed: cat /etc/*-release

ms-vscode.csharp-1.0.5-rc2/out/utils.js is not change

**Comment by gregg-miskelly** [comment]
@junjiangao yes, unfortunately our master branch is still locked down, and so 1.0.5 doesn't contain https://github.com/OmniSharp/omnisharp-vscode/pull/207. As soon as .NET Core RC2 releases we will merge the dev branch and release a new extension that fixes this.
