### ISSUE TITLE
A workspace with a lot of CS files prevents projects from being detected

### ISSUE THREAD

**Issue by ckaczor** [OmniSharp/omnisharp-vscode#2720]
I have a workspace with 10 Visual Studio solutions and the "select project" list only shows the first project in the workspace - I can't switch to any of the others.

I did some digging and the problem is that findLaunchTargets in launcher.ts does a find for project files and CS files but limits it to maxProjectResults (250 by default) files.  This means if the first directory/project has more than 250 files it will be the only one detected.  If the projects are smaller you might get the first few projects but once the limit is reached you won't get any more projects.

It doesn't seem efficient to just raise the limit since that will require even more directory scanning.

**Comment by akshita31** [comment]
This is fixed by https://github.com/OmniSharp/omnisharp-vscode/pull/2721
