### ISSUE TITLE
Error loading OmniSharp: "Cannot read property 'toString' of undefined"

### ISSUE THREAD

**Issue by lukemorse** [OmniSharp/omnisharp-vscode#2723]
## Environment data
`dotnet --info` output:
`.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.500/

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.500 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download`
VS Code version: 1.29.1 
C# Extension version: 1.17.1

## Steps to reproduce
Open VS Code

## Expected  behavior
OmniSharp loads.

## Actual behavior
OmniSharp fails to load with error:
`Error occured in loading omnisharp from omnisharp.path
Could not start the server due to TypeError: Cannot read property 'isWindows' of undefined
`

When I add `"omnisharp.path": "latest"` to user settings and reload OmniSharp, the error in the log is now `Error occured in loading omnisharp from omnisharp.path
Could not start the server due to TypeError: Cannot read property 'toString' of undefined
`

**Comment by rchande** [comment]
@akshita31 Can you take a look?

**Comment by akshita31** [comment]
"isWindows" is a property on the PlatformInformation class, hence I suspect that vscode is having issues detecting the platform somehow.

@lukemorse Does it work if you set omnisharp.path: null, so that the default omnisharp is loaded

**Comment by lukemorse** [comment]
@akshita31 Thanks, no I still get the "Cannot read property 'isWindows' of undefined" error.

**Comment by akshita31** [comment]
@lukemorse Could you try to re-install the extension and see if the error reproduces. Also while you do that you will observe a [C# channel](https://github.com/OmniSharp/omnisharp-vscode/wiki/Reporting-Issues#omnisharp-and-c-log). Please paste the logs from that.

**Comment by lukemorse** [comment]
@akshita31 Thanks, I re-installed it and I still get the same error.  From the C# log: `[ERROR]: C# Extension failed to get platform information.
`

**Comment by akshita31** [comment]
@rchande The problem here is that the C# extension is not able to obtain the platform on which the user is on.

**Comment by lukemorse** [comment]
I reinstalled the .NET SDK, and then reinstalled the C# extension and now it seems to be working fine.

**Comment by akshita31** [comment]
@lukemorse Glad you got it working
