### ISSUE TITLE
.net CLI tools cannot be located. dotnet command does not run in VSCode but does in external cmd

### ISSUE THREAD

**Issue by joe-fenton** [OmniSharp/omnisharp-vscode#2728]
## Environment data
`dotnet --info` output: 2.1.500
VS Code version: 1.29.1
C# Extension version: 1.17.1

## Steps to reproduce
Already have VS Code installed, previously used more for Javascript work.
Also have .net framework sdk 4.5.1 and 4.6 installed.
Install .net core x64 2.1.500.
Already had C# extension installed.
Try dotnet new command. Dotnet not recognized with internal powershell or cmd.
Re-installed c# extension.
Re-installed .net core

## Expected  behavior
For the dotnet command to work on the internal terminal in both cmd and powershell. Also for .net core debugging to be enabled and working.

## Actual behavior
dotnet command is not recognized inside VS Code, yet it is on external cmd.
Always get the error in VS code that .net CLI tools cannot be located

**Comment by gregg-miskelly** [comment]
This is really a VS Code issue rather than an issue with the C# extension, but we can see if we can help a little.

You are on Windows I assume?
If you start VS Code from a command prompt with 'dotnet.exe' on your path do you see the same problem?
Can you share the value of your path environment variable?

**Comment by joe-fenton** [comment]
Sorry, I was just googling the problem and I ended up on here.
Yes, Windows 10.
It seems if I run VS code from the command prompt dotnet is on the path, whereas it isn't if I run VS code from the standard shortcut or by right-clicking on a folder to open in VSCode. 
I'm not sure why the path is missing dotnet unless it is run from the cmd?
The normal path is:
PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\zief\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\AOMEI Backupper;C:\Program Files (x86)\Brackets\command;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Users\zief\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;;C:\Users\zief\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\zief\AppData\Local\Yarn\bin;C:\Users\zief\AppData\Roaming\npm;C:\Users\zief\.dotnet\tools

**Comment by joe-fenton** [comment]
Yeah, that was it. I just restarted the computer and it is now working fine! Didn't even think of it these days. Sorry to waste your time!

**Comment by gregg-miskelly** [comment]
Excellent! Glad you solved your problem.

**Comment by ChemsoDev** [comment]
thank you very much it solved

**Comment by Jalomo1197** [comment]
Thank you

**Comment by rmpasswd** [comment]
I've had the same issue when installing '.net install tool' extension in vscode, then going about installing _donet sdk_ from their website for first time.

Then after the sdk setup, the powershell terminal inside **vscode** did not recognize `dotnet` command. But outside, **windows** cmd and powershell did.

I had to type `exit `inside the vscode terminal(powershell), then restart vscode. I didn't need to restart my entire machine.

to-whom-it-may-concern.
