### ISSUE TITLE
Install error RC2

### ISSUE THREAD

**Issue by guidefreitas** [OmniSharp/omnisharp-vscode#273]
The RC2 Release Candidate for 4/29 package is throwing this error when I try to install it:

03/05/2016 08:02:10 - Microsoft VSIX Installer
03/05/2016 08:02:10 - -------------------------------------------
03/05/2016 08:02:10 - Initializing Install...
03/05/2016 08:02:10 - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: Element 'Identity' has invalid value for attribute 'Version' ---> System.FormatException: A cadeia de caracteres de entrada não estava em um formato correto.
   em System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   em System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   em System.Version.TryParseVersion(String version, VersionResult& result)
   em System.Version.Parse(String input)
   em System.Version..ctor(String version)
   em Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.<>c.<ExtractManifestData>b__11_1(String s)
   em Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   --- Fim do rastreamento de pilha de exceções internas ---
   em Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   em Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ExtractManifestData(PackageManifest manifest)
   em Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadPackageManifest(XmlReader reader)
   em Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadManifest(Stream manifestStream, String localeRelativeRoot, Boolean localize)
   em Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream vsixStream, CultureInfo preferredCulture)
   em Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   em VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   em VSIXInstaller.App.InitializeInstall()
   em System.Threading.Tasks.Task.InnerInvoke()
   em System.Threading.Tasks.Task.Execute()

**Comment by alexgwolff** [comment]
Open Visual Studio Code > File > Open File > Select .vsix file

**Comment by chuckries** [comment]
What version of Visual Studio Code are you on? Visual Studio Code -> Help -> About.

**Comment by gregg-miskelly** [comment]
@guidefreitas I think you are double clicking the .vsix. This will **NOT** work. As @alexgwolff said, you need to File-\>Open it instead.
