### ISSUE TITLE
Extension crashes regularly for projects with many files

### ISSUE THREAD

**Issue by TheBeachMaster** [OmniSharp/omnisharp-vscode#2732]
- Extension Name: csharp
- Extension Version: 1.17.1
- OS Version: Linux x64 4.15.0-39-generic
- VSCode version: 1.29.1

Apparent cause: __Searching for `*.<glob file extension pattern>` took too long__.

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 7434,
		"activateCallTime": 21,
		"activateResolvedTime": 31856,
		"activationEvent": "workspaceContainsTimeout:*.csproj,*.sln,*.csx,*.cake,**/*.csproj,**/*.sln,**/*.csx,**/*.cake"
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Pending request cancelled: /codecheck"
		},
		{
			"name": "Error",
			"message": "Pending request cancelled: /codecheck"
		},
		{
			"name": "Error",
			"message": "Pending request cancelled: /codecheck"
		}
	]
}
```

**Comment by rchande** [comment]
@TheBeachMaster Can you try increasing the value of the VS Code option `omnisharp.projectLoadTimeout`?

**Comment by TheBeachMaster** [comment]
![screenshot from 2018-12-07 16-36-41](https://user-images.githubusercontent.com/9129843/49650743-55d8fb80-fa3e-11e8-8286-3282cdd4fa8b.png)
I have set it to `120`. I'll close this issue if it does not workout
