### ISSUE TITLE
”Debug test" starts ASP.NET Core TestHost in Production

### ISSUE THREAD

**Issue by massimilianokraus** [OmniSharp/omnisharp-vscode#2733]
## Environment data
`dotnet --info` output: 2.1.401
VS Code version: 1.29.1
C# Extension version: 1.17.1

## Steps to reproduce:

Create API project and test project.

Use ASP.NET Core version:
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.2" />

In test project add NuGet package:
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.1.1" />

Write a simple unit test with:

    var builder = WebHost
        .CreateDefaultBuilder()
        .UseContentRoot(contentRoot)
        .ConfigureAppConfiguration((hostingContext, config) =>
            {
            })
        .UseStartup<Startup>();

click on the codelens "Debug test".

## Expected  behavior
Inside `ConfigureAppConfiguration`, `hostingContext.HostingEnvironment.EnvironmentName` should be anything but `"Production"`.

## Actual behavior
`hostingContext.HostingEnvironment.EnvironmentName` is `"Production"`.

Also, how can I set the environment variables like ASPNETCORE_ENVIROMENT before the debugging takes place?

**Comment by gregg-miskelly** [comment]
Do you see the same behavior if you run the unit test outside the debugger? In other words - are you saying that it is normally not 'production' but debugging unit tests causes it to be 'production'? Or that it is always 'production' for unit tests.

To answer your second question, I don't believe there are any knobs to set environment variables prior to a test running. You best bet might by to have your code call `Environment.SetEnvironmentVariable`, or otherwise change the ASP.NET configuration through code.

**Comment by massimilianokraus** [comment]
If I:

- click "Run Test" instead of "Debug Test"
- execute "dotnet test" in terminal

again the environment is "Production".

I created this solution without setting the Environment name, neither in the terminal nor in launch.json / tasks.json / settings.json. In fact, I can't find a single file with the setting of "Production", whatsoever.

**Comment by massimilianokraus** [comment]
Nevermind, I found this documentation page:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.2#environment

It seems that the WebHost use by default "Production" as environment name.
I find this profoundly wrong and disturbing (how can you set "Production" as default?! Why can't Microsoft do one thing right! 😩).

I think we can close the issue.

In order to test different environments in my test suites, this is my solution:
- I create a non-versioned JSON file like testsettings.json, with the environment name inside,
- I load its value in the builder methods.
