### ISSUE TITLE
Can debug 2.2 apps, but not 3.0 apps on macOS and (some?) Linux

### ISSUE THREAD

**Issue by bradygaster** [OmniSharp/omnisharp-vscode#2734]
## Environment data
Mac OS (Mojave)
`dotnet --info` output:
```bash
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-009812
 Commit:    e3abf6e935

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview-009812/

Host (useful for support):
  Version: 3.0.0-preview1-27101-02
  Commit:  f1ad6079ca

.NET Core SDKs installed:
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.401 [/usr/local/share/dotnet/sdk]
  2.1.500 [/usr/local/share/dotnet/sdk]
  2.2.100-preview1-009349 [/usr/local/share/dotnet/sdk]
  2.2.100-preview2-009404 [/usr/local/share/dotnet/sdk]
  2.2.100-preview3-009430 [/usr/local/share/dotnet/sdk]
  2.2.100 [/usr/local/share/dotnet/sdk]
  3.0.100-preview-009812 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-18579-0056 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview3-27014-02 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27122-01 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS Code version:
1.29.1

C# Extension version:
1.17.1

## Steps to reproduce
```bash
mkdir consoleapp22
mkdir consoleapp30
cd consoleapp22
dotnet new global
```

* Edit the global.json file to specify the .NET Core 2.2.100 version. 

```bash
dotnet new razor
code .
```

* Open `program.cs` and put a breakpoint in `main`. 
* Press F5 to launch the debugger
* Click the "yes" button when prompted to add stuff to project
* Select ".NET Core" from the command pallette
* Press F5 to launch the debugger
* Debugger stops at breakpoint

     <img width="922" alt="worksin22" src="https://user-images.githubusercontent.com/41929050/49622669-61192200-f97f-11e8-8c4d-b21aaae4a4ce.png">

* Allow app to exit
* Close VS Code

```bash
cd ../consoleapp30
dotnet new razor
code .
```

* Open `program.cs` and put a breakpoint in `main`. 
* Press F5 to launch the debugger
* Click the "yes" button when prompted to add stuff to project
* Select ".NET Core" from the command pallette
* Press F5 to launch the debugger

## Expected  behavior

The debugger stops at the breakpoint in `main` in `program.cs`. 

## Actual behavior

Debugger never stops at breakpoint. 

<img width="985" alt="noworksin30" src="https://user-images.githubusercontent.com/41929050/49622687-6fffd480-f97f-11e8-8399-cf3000def971.png">

**Comment by gregg-miskelly** [comment]
Thanks for the report! We will have a look.

**Comment by bradygaster** [comment]
thanks @gregg-miskelly - if you want to sync up so you can see what my machine is doing let me know. was planning on re-staging this weekend so i *got my debugger back* but if you need to peek at the environment i can wait. 

this machine explodes in 24 hours. 💥

**Comment by gregg-miskelly** [comment]
I can reproduce your problem on my Mac as well. So I shouldn't need anything more from you. Thanks for opening this!

**Comment by gregg-miskelly** [comment]
I found the problem. With .NET Core 3.0 on OSX, the CoreCLR debugging APIs are behaving in a way that they haven't before, and the VS Debugger isn't happy with it. I am working with the CoreCLR team to decide if we should fix VS to be tolerant of this behavior, or if this is a CoreCLR bug.

**Comment by bradygaster** [comment]
Thanks for the update, @gregg-miskelly. Keep me posted (even if via email/teams). That explains why it worked on @glennc's computer, as he was running on Windows and I on Mac. cc @damianedwards and @davidfowl FYI.

**Comment by gregg-miskelly** [comment]
This issue is tracked with https://github.com/dotnet/coreclr/issues/21552

**Comment by gregg-miskelly** [comment]
Two notes:
1. I ran into this same problem one one of my Linux boxes (but the first one seemed to work fine?)
2. If anyone really needs to debug with .NET Core 3.0, there is one (unpleasant) work around - you can run the program outside the debugger and attach after the .NET Core runtime has initialized.

**Comment by edencorbin** [comment]
I believe I am having the same issue, create a web-api project, add some breakpoints to the controller, hit the route, they do not trigger, C# extension installed, says the breakpoints are unverified. I tried the attach process workaround but still am not having any luck.

**Comment by gregg-miskelly** [comment]
@edencorbin are you using .NET Core 3.0? If not, you aren't hitting into the same problem, please open a new issue.

**Comment by edencorbin** [comment]
@gregg-miskelly, yes should have mentioned that I'm on 3.0. So this is a known vs code issue? I tested on windows Visual Studio Full and it worked great.

**Comment by gregg-miskelly** [comment]
You tried it in full Visual Studio on Windows? This is an issue in CoreCLR, it seems to affect macOS, and some Linux distros.

**Comment by kattunga** [comment]
Same problem here:
Debugger doesn't stops at breakpoints

Ubuntu 16.04
vscode 1.33.0 (installed from snap)
C# for Visual Studio Code 1.18.0
OmniSharp "omnisharp.path": "latest"
core 3.0.0-preview3-27503-5 (installed from snap)

application created with
`dotnet new razorcomponents -o WebApplication1`

**Comment by gregg-miskelly** [comment]
@kattunga your issue is different, as this issue was resolved by the .NET team for preview-2. Please open a new issue if you would like help understanding what is happening. I will close this one.
