### ISSUE TITLE
Visual Studio Code Insiders encounters problem in downloading OmniSharp package

### ISSUE THREAD

**Issue by revolz** [OmniSharp/omnisharp-vscode#2735]
**Latest Visual Studio Code Insiders**
Version: 1.30.0-insider (user setup)
Commit: 85f805acf9436381b878cab5ab6c5146beec7893
Date: 2018-12-05T06:19:36.555Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.15063

**Error Message**
Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' 	Retrying from 'https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.32.8.zip' Failed at stage: downloadAndInstallPackages
Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:d:\buildagent\workspace\318698\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:827:

**Steps to Reproduce:**
1. Fresh Installation of Visual Studio Code Insiders
2. Open and debug any C# project
3. Visual Studio Code Insiders will install OmniSharp successfully in Extension, and then encounter the aforementioned error.
4. Should be related to Proxy Server environment

Does this issue occur when all extensions are disabled?: Yes

**Comment by revolz** [comment]
#64414

**Comment by akshita31** [comment]
@revolz If you open the link in the browser - 'https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.32.8.zip', does it download a zip. 
Is it possible that it is related to proxy configuration problems ?

**Comment by revolz** [comment]
> @revolz If you open the link in the browser - 'https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.32.8.zip', does it download a zip.
> Is it possible that it is related to proxy configuration problems ?

@akshita31 It is related to proxy server environment. My proxy configuration hasn't changed for a long while. There is some major code change around this area ([https://github.com/Microsoft/vscode-azure-account/issues/27](https://github.com/Microsoft/vscode-azure-account/issues/27)) recently.

Can you take a look?

**Comment by akshita31** [comment]
@revolz As mentioned in the [comment here](https://github.com/Microsoft/vscode-azure-account/issues/27#issuecomment-442178328), there is no need to change anything in the extension atleast until a stable version of the api is released. 

As you mentioned [here](https://github.com/Microsoft/vscode-azure-account/issues/27#issuecomment-441861709), after setting the system proxy to force, does everything work fine for you ?

**Comment by revolz** [comment]
> As you mentioned [here](https://github.com/Microsoft/vscode-azure-account/issues/27#issuecomment-441861709), after setting the system proxy to force, does everything work fine for you ?

@akshita31, No, setting system proxy to force **doesn't** work for me in the latest version stated above. It was however working fine before that version. Some change in the latest version has broken it.

Are you able to reproduce the issue on your end? It will be easier for you to troubleshoot the issue if you are able to see it on your end.

**Comment by akshita31** [comment]
@revolz I am using the following version of insiders:
Version: 1.31.0-insider (user setup)
Commit: 7ab53e6d1c7998006bc70f18230178a702598222
Date: 2018-12-13T06:20:30.449Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

And here is my C# log:

Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (31021 KB).................... Done!
Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'

Downloading package '.NET Core Debugger (Windows / x64)' (43046 KB).................... Done!
Installing package '.NET Core Debugger (Windows / x64)'

Downloading package 'Razor Language Server (Windows / x64)' (46894 KB).................... Done!
Installing package 'Razor Language Server (Windows / x64)'

Finished

Could you try updating insiders and checking if the error still reproduces ?
