### ISSUE TITLE
Debugger is laggy in VS Code 1.30

### ISSUE THREAD

**Issue by TomStary** [OmniSharp/omnisharp-vscode#2745]
## Environment data
`dotnet --info` output:
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.401/

VS Code version: 1.30.0
C# Extension version: 1.17.1 & 1.18.0 beta-2

## Steps to reproduce

Running dotnet core application in debugger (using F5).

## Expected  behavior

Running as fast as it can run.

## Actual behavior

It's lagging my VS Code, sometimes giving me message that vs code is not responding, quite heavy cpu usage for extended period of time. Overall debugger is not working properly.

## Additional info

This wasn't issue when using VS Code 1.29 maybe upgrading VS Code is causing this.

**Comment by dattk** [comment]
confirm this problem on
 Version:   2.1.500,  Commit:    b68b931422

Runtime Environment:
 OS Name:     Mac OS X, OS Version:  10.12, OS Platform: Darwin, RID:         osx.10.12-x64

After upgrade VS Code to Version 1.30.0 (1.30.0) c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
2018-12-11T22:15:00.169Z

**Comment by TomStary** [comment]
I tried to rollback to version 1.29.1 and issue is not presented in this version.

**Comment by gregg-miskelly** [comment]
Thanks for the report @TomStary and @dattk. Could you tell me a bit more about what is going on --

1. When is this laggyness happening? (ex: when debugging is being started, when stepping, when calculating the call stack/watch/variables) 
2. If you look in task manager when these problems are going on, is some process spiking the CPU? If so, which process?
3. Do you see this problem with even a 'hello world' type C# program?

If the problem is difficult to describe, a video might be useful if that is possible. It sounds like this might be a VS Code issue rather than a C# extensiion issue. But we will see.

**Comment by TomStary** [comment]
1. Issue starts when debugger console shows up and app starts running, my app is doing seeds first and during this time VS Code is just frozen. App do not might even start, because debugger output is also slow.

2. CPU and memory usage is in check with previous version.

3. I did try small app, and that is doing fine. No problem there.

**Comment by dubeg** [comment]
I've been hit by hangs while debugging as while. I think it's related to the debug console? Perhaps when it becomes too full, it struggles? VSCODE 1.30.0 as well.

**Comment by dubeg** [comment]
If, like me, the hangs are caused by having the Debug Console visible, it is a known [issue](https://github.com/Microsoft/vscode/issues/64600). 

>Should be fixed in latest vscode insiders, we are using a new console.

I tried vscode insiders, and while better, there's still perf work to be made. I'll just revert to v1.29.

**Comment by hoyosjs** [comment]
@TomStary @dubeg This sounds like it might also be related to fixes in dotnet/coreclr#20054 and dotnet/coreclr#19911 for 2.2 and 3.0 runtimes respectively. You'd need to update the SDK/Runtime to test it as this didn't make it into 2.1 yet.

**Comment by TomStary** [comment]
I do have new runtime/SDK but it didn't solve my problem :/

**Comment by TomStary** [comment]
I just tried new version of insiders version of VS Code and in this version everything works normal like in 1.29 version of VS Code.

**Comment by crkjl** [comment]
Hi, same problem here (vscode 1.30.2, omnisharp 1.17.1). Working with mac osx.

When I launch app debug all works fine, queries to SQL db are fast, but after some seconds every time my frontend request data, vscode stop responding during several seconds (+/- 40sec). If I stop debugging and launch again all works fine again during some time.

No errors appear in console, only vscode appears to stop working for several seconds, receiving sometimes the dialog asking to Keep Open or Close vscode.

Tested the same application debugged with Visual Studio for mac and it works fine without problems.
Regards
Jose
