### ISSUE TITLE
Remove "The program '<path>' has exited..." when terminating the app

### ISSUE THREAD

**Issue by v-pavanp** [OmniSharp/omnisharp-vscode#275]
VSCode Version: 1.1.0-alpha
•OS Version: Windows10 -Project Type: Aspnet console app

I observer when I am terminating debug session by clicking on stop button from debug-actions-widget then debug console is displaying some system internal message which is irrelevant to the user.

https://github.com/Microsoft/vscode/issues/6070

**Comment by gregg-miskelly** [comment]
@v-pavanp you are just referring to --

    The program '<path>' has exited with code -1 (0xffffffff).

Correct?

**Comment by v-pavanp** [comment]
Yes. My concern here is, why we are displaying this message to the user in debug console as it is internal system message when user try to terminate debug session.

**Comment by gregg-miskelly** [comment]
Thanks. I would kind of consider this expected. But we can see if anyone else feels the same.

**Comment by caslan** [comment]
Since we have not received any further feedback from others, I'm closing this item. We can reopen it if we receive similar feedback in the future.
