### ISSUE TITLE
C# intellisense not working

### ISSUE THREAD

**Issue by LucaseZLu** [OmniSharp/omnisharp-vscode#2755]
Issue Type: <b>Bug</b>

I try any way to resolve,but =^=

Extension version: 1.17.1
VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (4.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rchande** [comment]
@LucaseZLu Please share your omnisharp log.

**Comment by dcb99** [comment]
I am having a problem with this as well. Go to definition doesn't work for methods in external classes, and sometimes I can't even get project namespaces to show up. Changing the definition of a method in one class doesn't cause the little red sqiggly line to show up in the calling methods. 
Where is the omnisharp log located?

**Comment by rchande** [comment]
View -> Output
Use the selector on the right to choose `OmniSharp Log`

**Comment by dcb99** [comment]
Starting OmniSharp server at 1/7/2019, 12:42:28 PM
    Target: c:\Users\...\...\...\...\app.sln

OmniSharp server started.
    Path: C:\Users\dbarless\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\OmniSharp.exe
    PID: 20812

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Professional 2017 15.8.28010.0 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\dbarless\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Professional 2017 15.8.28010.0 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\dbarless\Desktop\...\...\app.sln"
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\dbarless\...\...\...\app.sln'.
[warn]: OmniSharp.MSBuild.ProjectSystem
        Found project that doesn't exist on disk: c:\Users\dbarless\Desktop\...\...\app.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\dbarless\Desktop\...\...'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\dbarless\Desktop\...\appFolder' on host 16948.
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\Users\...\Desktop\... added to workspace

**Comment by dcb99** [comment]
I can't share the project, there's proprietary info. Yes, the `.csproj` file is located on disk in the root of the project.

**Comment by zeihanaulia** [comment]
I have the same experience, Intellisense can't work.

### dotnet info
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.104/

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.2.104 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### omnisharp logs
```
Starting OmniSharp server at 3/2/2019, 5:29:46 PM
    Target: /Users/zeihanaulia/Programming/projects/focussolusi/focusapi

OmniSharp server started with Mono 5.18.0.
    Path: /Users/zeihanaulia/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/OmniSharp.exe
    PID: 727

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

OmniSharp:
info: OmniSharp.Startup[0]
      Omnisharp server running on port '2000' at location '/Users/zeihanaulia/Programming/projects/focussolusi/focusapi' on host -1.
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Initializing in /Users/zeihanaulia/Programming/projects/focussolusi/focusapi
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Auto package restore: True
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Update workspace context
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Resolving projects references
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      MSBUILD_EXE_PATH environment variable set to /usr/local/Cellar/omnisharp/1.19.0/libexec/msbuild/MSBuild.dll
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      MSBuildExtensionsPath environment variable set to /usr/local/Cellar/omnisharp/1.19.0/libexec/msbuild
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      MSBuild will use local OmniSharp installation.
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      No solution files found in '/Users/zeihanaulia/Programming/projects/focussolusi/focusapi'
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Loading project: /Users/zeihanaulia/Programming/projects/focussolusi/focusapi/focusapi.csproj
fail: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo[0]
      The "Microsoft.NET.Build.Tasks.ResolvePackageAssets" task could not be loaded from the assembly /usr/local/share/dotnet/sdk/2.2.104/Sdks/Microsoft.NET.Sdk/targets/../tools/netcoreapp2.0/Microsoft.NET.Build.Tasks.dll. An attempt was made to load a program with an incorrect format.
       (Exception from HRESULT: 0x8007000B) Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
warn: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      Failed to load project file '/Users/zeihanaulia/Programming/projects/focussolusi/focusapi/focusapi.csproj'.
info: OmniSharp.Script.ScriptProjectSystem[0]
      Detecting CSX files in '/Users/zeihanaulia/Programming/projects/focussolusi/focusapi'.
info: OmniSharp.Script.ScriptProjectSystem[0]
      Could not find any CSX files
info: OmniSharp.Startup[0]
      Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
info: OmniSharp.Startup[0]
      Configuration finished.
```

**Comment by rchande** [comment]
@dcb99 Sorry, I lost track of this issue--are you still having problems?

**Comment by Blizzardo1** [comment]
I'm actually having an issue with OmniSharp as well regarding Intellisense not working with External Packages. I've added HtmlAgilityPack and Flurl.Http to my project, despite them working, the intellisense is not picking up the methods.

The .csproj is at the root of the project folder, and the packages are added successfully.

```
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: f:\Code\CSharp\SavingGrace\SavingGrace.csproj
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: f:\Code\CSharp\SavingGrace\obj\Debug\netcoreapp2.1\SavingGrace.AssemblyInfo.cs added to workspace
```

This exists at the bottom of the log so I'm wondering, how is VSCode not loading the project?

**Comment by Blizzardo1** [comment]
The file is a part of the project, and the project was loaded at the time. All of the references I've added were supported for .net-core, so I'm unsure of the issue then.

**Comment by Linshiqi** [comment]
I have this problem too, my vscode version is 1.35.1,  I have created project using dotnet new classlib, and corresponding test project using dotnet new xunit. Blow is my project structure:
my_solution
      project1
      project1.test
      Utilities(this is just a folder)
           utilityProject1
           utilityProject2
     mysolutions.sln
I have using dotnet sln add all projects to mysolution.sln, including projects in utilities.
Projects in Utilities folder are treated as miscellaneous file, other projects works fine.

**Comment by DrakeLambert** [comment]
I have a standard asp net core 3 project open. I am not able to go to definition for any class/interface defined outside of my project. This includes objects provided by the framework. Interestingly, I can still see the method signature and xml documentation by using the 'hover mouse over symbol' method.

**Comment by DrakeLambert** [comment]
As an FYI, my issue is fixed with https://github.com/OmniSharp/omnisharp-roslyn/issues/1624

**Comment by cartermp** [comment]
Closing out as this appears to be resolved.
