### ISSUE TITLE
Stop forcing focus on "Output" tab when OmniSharp is logging

### ISSUE THREAD

**Issue by yhvicey** [OmniSharp/omnisharp-vscode#2756]
VS Code version: 1.30.1
C# Extension version: 1.17.1

Every time when I open a folder with lots of *proj file (like aspnet/Extensions), it keeps focusing on "Output" and the drop down list shows "OmniSharp Log". It is really annoying because it will interrupt other action, like opening a menu or opening a terminal. Please at least add a switch to disable it.

**Comment by akshita31** [comment]
@yhvicey Thanks for filing the issue. I agree that we should not focus the logs by default.

**Comment by stewartadam** [comment]
I presume this is also the cause of https://github.com/Microsoft/vscode/issues/22187, which I ran into again today. Midway through typing a Markdown document, OmniSharp started updating dependencies and grabbed focus away which is irritating.

**Comment by BrennanConroy** [comment]
This is a super annoying issue. Is there a known previous version that people can use instead until this is fixed?

**Comment by rchande** [comment]
@BrennanConroy Actually, we just created a beta that includes the fix for this. Please give it a try and let us know if you're still having issues: https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.18.0-beta5

**Comment by BrennanConroy** [comment]
Excellent! Worked for me, thanks for the good work.

**Comment by justinmchase** [comment]
It still does this... it keeps stealing focus from the terminal while I'm typing.

**Comment by hoyosjs** [comment]
@akshita31 Sorry to ping on a closed issue, but it feels like this regressed. I have to kill omnisharp to be able to use the terminal in large projects where it takes a long time to create the full dependency graph and cache setup.

**Comment by stewartadam** [comment]
@hoyosjs probably better to report a new issue if it's happening again

**Comment by JoeRobich** [comment]
Please set the "csharp.showOmnisharpLogOnError" setting to `false` if you do not want this behavior.

https://github.com/OmniSharp/omnisharp-vscode/blob/5270351278c86cb2514487ff6f6c0adf27c15a7a/package.json#L693-L697

**Comment by justinmchase** [comment]
I want omnisharp errors to be logged, but I don't want the frickin' errors to change my focus.

**Comment by filipw** [comment]
that's what the setting does 🙂

**Comment by justinmchase** [comment]
Oh 🥰 

It sounds like its saying the errors won't get logged at all but I see what you're sayin'

**Comment by TheOnlyWei** [comment]
Still getting this issue in v1.24.0 in the year 2022.

**Comment by justinmchase** [comment]
Me too, can we invert the default to false? Who ever wants this to be true?

**Comment by TheOnlyWei** [comment]
Found a new issue about this here: https://github.com/OmniSharp/omnisharp-vscode/issues/4608
