### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by SinueeHernandez** [OmniSharp/omnisharp-vscode#2757]
[ms-vscode.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/2701493/ms-vscode.csharp-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `csharp`
- Extension Version: `1.17.1`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.1`

**Comment by akshita31** [comment]
@rchande Can this be related to the similar thing that we were observing on MacOS ?

**Comment by jrieken** [comment]
@akshita31 From looking at the profile this seems to be code loading. Using webpack or rollup would certainly help here

**Comment by akshita31** [comment]
@jrieken We are working on using webpack for the C# extension. However, I had a question. how would you test that the bundle produced doesnt have any missing dependencies. I have run into cases where my integration tests and unit tests run fine but when i bundle the code and install it in vscode, I get some errors due to which the extension doesnt run

**Comment by jrieken** [comment]
> I have run into cases where my integration tests and unit tests run fine

Those test, do they use the bundled output? We have learnt that webpack is a little too relaxed with error messages and internally we treat every warning as error so that they trigger a build failure.

**Comment by akshita31** [comment]
@SinueeHernandez  Can you try upgrading to the latest mono version as suggested [here](https://github.com/OmniSharp/omnisharp-vscode/issues/2794#issuecomment-457050038) and checking if the problem still persists.
Also, we have a [beta release](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.18.0-beta7) containing major improvements on the code load times. You can install it by following the instructions [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases). Please let us know if that helps.

**Comment by akshita31** [comment]
@SinueeHernandez We havent heard from you in a while. I will close this issue now. Please feel free to reopen if the problem persists.
