### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by citizenharris** [OmniSharp/omnisharp-vscode#2758]
- Issue Type: `Performance`
- Extension Name: `csharp`
- Extension Version: `1.17.1`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.0`
[ms-vscode.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/2703964/ms-vscode.csharp-unresponsive.cpuprofile.txt)

**Comment by akshita31** [comment]
@citizenharris Can you try updating your mono version as stated [here ](https://github.com/OmniSharp/omnisharp-vscode/issues/2794#issuecomment-457050038) and checking if the issue still persists. 

Also, we have a [beta](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.18.0-beta7) that includes major performance fixes. You can install it by following the instructions [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases).

Please give it a spin and let us know if the problem still persists.

**Comment by akshita31** [comment]
@citizenharris We havent heard back from you in a while so I will close this issue now. Please feel free to repoen if the problem still persists.
