### ISSUE TITLE
Intellisense not showing constructor arguments

### ISSUE THREAD

**Issue by BrennanConroy** [OmniSharp/omnisharp-vscode#276]
![screen shot 2016-05-04 at 10 11 25 am](https://cloud.githubusercontent.com/assets/7574801/15022454/9770c864-11e0-11e6-99c7-dc4e21256c79.png)
Here is the source with the constructor it should be showing https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Console/ConsoleLogger.cs

**Comment by DustinCampbell** [comment]
Hi! Thanks for reporting this problem. This is a duplicate of #36.
