### ISSUE TITLE
how change password mail server by mvc

### ISSUE THREAD

**Issue by alirezaseif28** [OmniSharp/omnisharp-vscode#2761]
how change password mail server by mvc

**Comment by alirezaseif28** [comment]
thanks.@akshita31
I have a mail server that is related to the host. I store the info about the mail server in the app mvc. If I want to pass through my mail server passwords through my application, that is, first, change the password in the mail server and If successful, go to the application database...

**Comment by alirezaseif28** [comment]
how find sample code c# to change password roundcube mail.
how find api from change password.

**Comment by akshita31** [comment]
@rchande Do you have any ideas here ?

**Comment by akshita31** [comment]
@alirezaseif28 Please provide a sample repro project and the steps to reproduce the problem so that we can understand the problem clearly.

**Comment by alirezaseif28** [comment]
Hi @akshita31 
I found the documentation SmarterMail. I am very happy.
a Link Documentation .[SmarterMail](https://mail.smartertools.com/documentation/api#/topics/overview)

**Comment by rchande** [comment]
@alirezaseif28 Glad you figured it out. Do note that this is a repo for filing issues about the C# extension for VS Code, not a forum for general .NET development questions.

**Comment by alirezaseif28** [comment]
@rchande  .Ok .Excuse me to disturb you.
