### ISSUE TITLE
Is there an option that allows internalConsole to only output the results of the program?

### ISSUE THREAD

**Issue by jiayaoO3O** [OmniSharp/omnisharp-vscode#2762]
![image](https://user-images.githubusercontent.com/22891632/50394452-850a9f00-0798-11e9-8823-aec7e268cb07.png)
  Like the image above, I want only one word "false", but there are a lot of information in the internalConsole that is not important to me (yellow word) ), is there an option that allows me to turn off these unimportant information output and only show the results of the program?

**Comment by gregg-miskelly** [comment]
You cannot reduce the output to zero, but many of the outputs can be disabled by setting 'logging' options in launch.json.

**Comment by jiayaoO3O** [comment]
> 您不能将输出减少到零，但可以通过在 launch.json 中设置'logging'选项来禁用许多输出。

![image](https://user-images.githubusercontent.com/22891632/50418790-6542ac00-0868-11e9-847b-0ed20e7e7cf2.png)
If I only want to output the program results, what should I fill in the logging?

**Comment by gregg-miskelly** [comment]
@jiayaoO3O here is the documentation: https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#logging

VS Code will also give you intellisense if you just start typing and show you the available options.
