### ISSUE TITLE
Inline Comment on Switch Line Not Formatted Correctly

### ISSUE THREAD

**Issue by WeirdBeardDev** [OmniSharp/omnisharp-vscode#2767]
## Issue Description ##
A comment on the same line as a switch statement is not formatted as a comment.  The system ignores the comment as desired.

## Steps to Reproduce ##
1. Write the following code to test
```csharp
bool test = false;
switch (test) /* test comment */
{
	case true: /* the true case */
		ans = "test true";
		break;
	case false:
		ans = "test false";
		break;
	default:
		ans = "test default";
		break;
}
```

## Expected Behavior ##
The comment should be formatted as a comment.

## Actual Behavior ##
The comment is not formatted as a comment.  I see that even in the snippet I wrote above it isn't formatted, so recreated in VS Community 2017 (v15.7.4) and it is formatted correctly.  See the image below for a comparison.

![switch-comment](https://user-images.githubusercontent.com/26331356/50540409-39247500-0b5f-11e9-94a1-105d52553f8c.png)

## Environment information ##

**VSCode version**: 1.30.1
**C# Extension**: 1.17.1

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.4.7|
|code-runner|formulahendry|0.9.5|
|code-settings-sync|Shan|3.2.4|
|csharp|ms-vscode|1.17.1|
|debugger-for-chrome|msjsdiag|4.11.1|
|emojisense|bierner|0.4.1|
|githistory|donjayamanne|0.4.4|
|html-css-class-completion|Zignd|1.17.1|
|LiveServer|ritwickdey|5.3.1|
|markdown-all-in-one|yzhang|1.8.0|
|markdown-emoji|bierner|0.0.7|
|markdown-imsize|amoosbr|0.0.2|
|mono-snippets|zrachod|0.0.2|
|php-debug|felixfbecker|1.12.6|
|php-intellisense|felixfbecker|2.3.10|
|PowerShell|ms-vscode|1.10.2|
|setting-toggle|Ho-Wan|1.3.1|
|shader|slevesque|1.1.4|
|shaderlabvscodefree|amlovey|1.1.3|
|unity-debug|Unity|2.6.6|
|vscode-codemetrics|kisstkondoros|1.17.4|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-todo-plus|fabiospampinato|4.11.2|;

</details>

**Comment by rchande** [comment]
Moved to https://github.com/dotnet/csharp-tmLanguage/issues/145
