### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by joylogic** [OmniSharp/omnisharp-vscode#2769]
- Issue Type: `Performance`
- Extension Name: `csharp`
- Extension Version: `1.17.1`
- OS Version: `Linux x64 4.4.0-112-generic`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/joylogic/ms-vscode.csharp-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by joylogic** [comment]
part of the file /home/joylogic/ms-vscode.csharp-unresponsive.cpuprofile.txt (where to upload?)
{
    "nodes": [
        {
            "id": 1,
            "callFrame": {
                "functionName": "(root)",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 0,
            "children": [
                2,
                112,
                876
            ]
        },
        {
            "id": 2,
            "callFrame": {
                "functionName": "",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 0,
            "children": [
                3
            ]
        },
        {
            "id": 3,
            "callFrame": {
                "functionName": "s",
                "scriptId": "87",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": 123,
                "columnNumber": 178
            },
            "hitCount": 0,
            "children": [
                4
            ]
        },
        {
            "id": 4,
            "callFrame": {
                "functionName": "s.__generator.a.label",
                "scriptId": "87",
                "url": "pii_removed/extensionHostProcess.js",
                "lineNumber": 123,
                "columnNumber": 437
            },
            "hitCount": 0,
            "children": [
                5
            ]
        },

**Comment by akshita31** [comment]
@joylogic  Please upload the full file - `/home/joylogic/ms-vscode.csharp-unresponsive.cpuprofile.txt` so that we can do the further analysis

**Comment by akshita31** [comment]
@joylogic The [beta version](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.18.0-beta7) containing the fix for this issue is out. You can install it by following the instructions [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases).

We believe this would fix the issue. Please try it out.

**Comment by akshita31** [comment]
For now, I will close this issue for lack of information to do further analysis
