### ISSUE TITLE
Opening files from Warnings & Errors menu gets a FileNotFound

### ISSUE THREAD

**Issue by mpowell-imvu** [OmniSharp/omnisharp-vscode#277]
When I use ctrl-shift-m to open the warnings and errors pane, and select one of the errors from the list, I get an error message like:

Unable to open 'PostBuild.cs': File not found (\Assets\IMVUnity\Editor\PostBuild.cs).

The problem appears to be that it's adding an extra \ to the beginning, making it an absolute path. The error message includes a "Create" button, and if I press that it does indeed create a new file at \Assets\IMVUnity\Editor\PostBuild.cs, off the root.

This is a Unity project, using an sln file. The line in the project file that includes PostBuild.cs looks like:

`<Compile Include="Assets\IMVUnity\Editor\PostBuild.cs" />`

As you can see, it doesn't include the leading slash. That's presumably coming from something in the C# extension.

**Comment by DustinCampbell** [comment]
@mpowell-imvu: Sorry for the delay on this issue. I'm curious to know if this is still a problem for you with the latest C# extension?

**Comment by mpowell-imvu** [comment]
Nope. It appears to be working now. This can be considered resolved.

**Comment by DustinCampbell** [comment]
Thanks for following up!
