### ISSUE TITLE
Broken syntax highlighting when using method parentheses in new line

### ISSUE THREAD

**Issue by HitalloExiled** [OmniSharp/omnisharp-vscode#2770]
## Environment data
SDK do .NET Core (refletindo qualquer global.json):
 Version:   2.2.100
 Commit:    b9f2fa0ca8

Ambiente de tempo de execução:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.100\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

VS Code version: 1.30.1
C# Extension version: 1.17.1

## Steps to reproduce
```cs
public class Foo
{
    void Bar(
        object a,
        object b,
        object c,
        object d,
    )
    {
        // Works
       Console.WriteLine($"{a}, {b}, {c}, {d}");
    }   
}

public class Foo
{
    void Bar
    (
        object a,
        object b,
        object c,
        object d,
    )
    {
        // Don't work
       Console.WriteLine($"{a}, {b}, {c}, {d}");
    }   
}
```

## Expected  behavior
Correct highlighting

## Actual behavior
Broken highlighting

**Comment by rchande** [comment]
Moved to https://github.com/dotnet/csharp-tmLanguage/issues/144
