### ISSUE TITLE
Issue with .NET Core Debugger

### ISSUE THREAD

**Issue by EpicPants88** [OmniSharp/omnisharp-vscode#2777]
## Environment data

VS Code version:1.30.1
C# Extension version:1.17.1

## Steps to reproduce
when I open a C# script inside unity visual studio code opens and I immediately get the error that The .NET CLI tools cannot be located and .NET Core debugging will not be enabled.  I have the newest version of .NET Core SDK installed version 2.2.101.  I originally attempted to used Visual Studio Code instead of the full Visual Studio Community like I normally use because I was having a similar issue with the full Visual Studio.  I was getting an error that the proper .NET framework couldn't be located so I finally resolved that by installing the developer version of .NET framework 4.7.1 with SDK and targeting pack even though I already had 4.7.2 installed I required the older version which resolved the error message everytime I opened a script in unity but then i still didn't have intellisense autocomplete or suggestions for the majority of my code which i have always had in the past.  (BTW this is on a new PC with a new install of everything and Windows 10 is fully updated as I have checked multiple times.)  Im running out of options other then leaving microsoft behind completely to try another IDE like jetbrains rider or something else to see if i can resolve the issue that way but Im thinking even with a different IDE i will still need the .net framework to work properly which i believe thats where my issue lays.  any assistance would be super helpful.  Thanks so much in advance.

![visual studio code](https://user-images.githubusercontent.com/46350193/50643849-27671700-0f3d-11e9-863a-c46f92cfb228.png)
![net framework](https://user-images.githubusercontent.com/46350193/50643886-3d74d780-0f3d-11e9-9a23-32b2e7e446e0.png)
![installed programs](https://user-images.githubusercontent.com/46350193/50643887-41085e80-0f3d-11e9-9bc2-9a477d8d8b35.png)
![regedit](https://user-images.githubusercontent.com/46350193/50643891-42d22200-0f3d-11e9-8b7e-dfcd4f685096.png)

if any further info is required just lemme know.

**Comment by gregg-miskelly** [comment]
If you log out and log back in (or restart the computer) does the issue go away?

**Comment by EpicPants88** [comment]
sorry for the wait on my response.  idk how or why but i started a another new project (the one i was opening was a new one anyways so i didn't loose much work) and that resolved the issue.  im assuming something must have gotten corrupted or something with the actual project files themselves.  im not totally sure.  i haven't tried opening any projects in the full visual studio community ide yet but as for visual studio code it works perfectly now.  a few things still aren't picked up by intellisense for c# like certain functions like Awake, Start, Update, FixedUpdate, LateUpdate, OnCollisionEnter2D, OnTriggerEnter2D, OnCollisionExit2D, OnTriggerExit2D,.. etc.  now they may just not be recognized the same way in visual studio code cause i realize code isn't a full ide the same way visual studio community is so those may just be something that isn't included with intellisense but everything else seems to be working fine.  I can live with the minor inconvenience of typing out the functions.  thanks so much for your time and sorry it took so long for me to respond.  oh and as for the original project that had the issue even if i restarted and everything i still had that issue i think there was an issue with the project files though and not the software itself.  thanks and have a great night!
