### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by CleiberReis** [OmniSharp/omnisharp-vscode#2778]
- Issue Type: `Performance`
- Extension Name: `csharp`
- Extension Version: `1.17.1`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/cleiber/ms-vscode.csharp-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by akshita31** [comment]
@CleiberReis Please upload the file - `/home/cleiber/ms-vscode.csharp-unresponsive.cpuprofile.txt` so that we can do further analysis as to what is causing the issue.

**Comment by CleiberReis** [comment]
[ms-vscode.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/2753647/ms-vscode.csharp-unresponsive.cpuprofile.txt)

**Comment by johnnyreilly** [comment]
Seeing this too

**Comment by akshita31** [comment]
@CleiberReis Thanks for filing the issue. We are working on it.

**Comment by akshita31** [comment]
@CleiberReis @johnnyreilly Can you try upgrading to the latest mono version as suggested [here](https://github.com/OmniSharp/omnisharp-vscode/issues/2794#issuecomment-457050038) and checking if the problem still persists.
Also, we have a [beta release](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.18.0-beta7) containing major improvements on the code load times. You can install it by following the instructions [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases). Please let us know if that helps.

**Comment by akshita31** [comment]
@CleiberReis We haven't heard back from you in a while so I will close this issue for now. Please feel free to reopen if the problem still persists.
