### ISSUE TITLE
it's don't work today!! but no problem yesterday

### ISSUE THREAD

**Issue by ivanleo** [OmniSharp/omnisharp-vscode#2781]
## Environment data
![image](https://user-images.githubusercontent.com/4963100/50719224-582d8480-10d4-11e9-83c3-ea9ff407240b.png)

VS Code version:
![image](https://user-images.githubusercontent.com/4963100/50719232-611e5600-10d4-11e9-970b-29bb88a2b6bb.png)

C# Extension version:
![image](https://user-images.githubusercontent.com/4963100/50719235-74312600-10d4-11e9-9a36-a8e03ef5cd9b.png)

## Omni log
![image](https://user-images.githubusercontent.com/4963100/50719357-e2c2b380-10d5-11e9-8b16-f805ff64dcd8.png)

## Unity Build Setting
![image](https://user-images.githubusercontent.com/4963100/50719251-cb36fb00-10d4-11e9-9e8b-c51a64ae124b.png)

## Reinstall
I had reinstall it
this is install log
![image](https://user-images.githubusercontent.com/4963100/50719269-f1f53180-10d4-11e9-9a72-c53b6c1f5a32.png)

## Desc
that has no problem with open an unity project with .net 3.5
but the new project with .net 4.0 use some new features
who can save me ? 
the extension does't work now.

**Comment by rchande** [comment]
@ivanleo You need to install the targeting pack for .NET Framework 4.5

**Comment by ivanleo** [comment]
yes you are right
I had install .net framework 4.5
but I neet install the full version
include 4.5 4.5.1 4.5.2 and sdk
