### ISSUE TITLE
"Set Next Statement(.NET)" option disappeared after restarting debugging. 

### ISSUE THREAD

**Issue by v-mengzh** [OmniSharp/omnisharp-vscode#2785]
Environment data
OS and Version: Mac Version 10.12.6
VS Code Version: 1.30.1
C# Extension Version:1.18.0-beta4

Steps to reproduce
1. Install vscode and C# extension
2. Open the Terminal, run as follow command to create new console project:
dotnet new console -o myapp
3. Add some code in the program.cs and set a breakpoint
4. Configure launch.json as following:
![image](https://user-images.githubusercontent.com/32150874/50817471-e026bf00-135e-11e9-9f8e-a3bdfad64442.png)
5. F5, wait for hitting the breakpoint
6. Move your cursor to the next statement you would like to execute next, and right click "Set Next Statement(.NET)", it work normally
7. Restart debugging and repeat step6

Expected
"Set Next Statement(.NET)" option display and work normally when right click as following:
![image](https://user-images.githubusercontent.com/32150874/50817093-b9b45400-135d-11e9-836a-8518ac24146e.png)

Actual
"Set Next Statement(.NET)" option disappeared after restarting debugging as following:
![image](https://user-images.githubusercontent.com/32150874/50817103-c2a52580-135d-11e9-998f-9dfea11bc60c.png)

Investigation
When stop debugging, and start debugging again, "Set Next Statement(.NET)" displayed and worked normally.

**Comment by qian6** [comment]
This issue can also reproduce on windows/Linux platform.

**Comment by gregg-miskelly** [comment]
This is a problem with VS Code. I opened https://github.com/Microsoft/vscode/issues/66226 to track it.
