### ISSUE TITLE
Complains about existing definition in same namespace

### ISSUE THREAD

**Issue by MikaelUmaN** [OmniSharp/omnisharp-vscode#2786]
Issue Type: <b>Bug</b>

Not really sure how to reproduce unfortunately...

This happens intermittently. My best guess is that it is due to renaming. 

- Create C# project via terminal: dotnet new ...
- In file explorer, create folder MyNameSpace
- Create file with some name, e.g. an enum
- Rename symbol

Expected:
Still compiles and no warnings in editor

Actual:
Compiles, but warnings in editor:

The namespace 'BackEndWebApi.InstrumentRefData.Model' already contains a definition for 'ESeriesType' [BackEndWebApi]

![image](https://user-images.githubusercontent.com/1746060/50986786-0a67b080-1508-11e9-8dc9-9fdbc66ad47c.png)

After restart, it works without complaints. Really hard to give a good "reproduce" but I keep running into this when I am moving files, changing namespaces and what not (due to just experimenting with project structure)

Extension version: 1.17.1
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by akshita31** [comment]
@MikaelUmaN Can you share  your [OmniSharp log](https://github.com/OmniSharp/omnisharp-vscode/wiki/Reporting-Issues#omnisharp-and-c-log) when this happens.

**Comment by RononDex** [comment]
I have the same thing happening. The OmniSharp log does not show anything (no output since loading / updating the .csproj files).

I got this issue a few times after moving files. To me it looks like Onmisharp parses the moved file as a new file (and therefore thinks the class / class members are defined twice), without "removing" the parsed contents of the "old" file

**Comment by akshita31** [comment]
@RononDex What is the extension version that you are using ?

**Comment by RononDex** [comment]
@rchande have been working with the latest build of omnisharp-roslyn (compiled it myself) for a day now, so far I the bug didn't show up, so I guess thats good sign :)

Really looking forward to the roslyn-analyzers PR

**Comment by rchande** [comment]
@MikaelUmaN It sounds like this is fixed--I'm going to close the bug. Go ahead and further comments if you have any.

**Comment by teqdruid** [comment]
I've got 1.18.0-beta8 installed and I'm having the same issue as above:

![image](https://user-images.githubusercontent.com/1498080/53852883-5e2acf00-3f78-11e9-8f83-cf1a5b92ce0f.png)

OmniSharp log:
[omnisharp.log](https://github.com/OmniSharp/omnisharp-vscode/files/2934124/omnisharp.log)
