### ISSUE TITLE
OmniSharp.exe - This application could not be started.

### ISSUE THREAD

**Issue by sa0okm9ijn** [OmniSharp/omnisharp-vscode#2788]
**环境描述：**

.NET Core SDK（反映任何 global.json）:
 Version:   2.2.101
 Commit:    236713b0b7

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   E:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.2.101 [E:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [E:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [E:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [E:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**The phenomenon of**
open vscode the suffix .cs file
message info:
This application requires one of the following versions of the .NET Framework:  .NETFramework,Version=v4.6.1  Do you want to install this .NET Framework version now? 

**Temporary solution*

After modifying the omnisharp configuration file to remove the property sku=".NETFramework,Version=v4.6", it is available
My computer has never installed the. Netframework

Excuse me everybody this is computer environment does not match bring about

**Comment by akshita31** [comment]
@sa0okm9ijn Does installing the .NET Framework as suggested in the warning make OmniSharp work for you?

**Comment by sa0okm9ijn** [comment]
I use the. Netcore platform vsCode automatically download omnisharpe

**Comment by sa0okm9ijn** [comment]
@akshita31  我用。Netcore平台vsCode自动下载omnisharpe

**Comment by akshita31** [comment]
@sa0okm9ijn  Can you try installing the https://dotnet.microsoft.com/download/thank-you/net472 .Net framework and restarting vscode

**Comment by akshita31** [comment]
@sa0okm9ijn Any updates here ?

**Comment by rchande** [comment]
@sa0okm9ijn We haven't from you in a long time, so I'm going to close this issue. Feel free to file a new one if you're still having problems.
