### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by marvelperseus** [OmniSharp/omnisharp-vscode#2794]
- Issue Type: `Performance`
- Extension Name: `csharp`
- Extension Version: `1.17.1`
- OS Version: `Linux x64 4.8.0-36-generic`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/david/ms-vscode.csharp-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by akshita31** [comment]
@marvelperseus Can you update the version of mono as @James-E-Adams stated and see if the problem still persists?

**Comment by akshita31** [comment]
@marvelperseus As per @James-E-Adams suggestion, upgrading to the latest mono would fix the issue.

I will close the issue for now. Please feel free to reopen if it still persists.
