### ISSUE TITLE
"references" gray text section in vscode jiggles when typing

### ISSUE THREAD

**Issue by Ashtonian** [OmniSharp/omnisharp-vscode#2798]
## Environment data
`dotnet --info` output:
```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.103/

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.2.103 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
``` 

VS Code version: `1.30.2`
C# Extension version: `1.17.1`

## Steps to reproduce
Type somewhere.
![jan-17-2019 17-52-22](https://user-images.githubusercontent.com/4212452/51356599-b8330c00-1a80-11e9-9679-2a161736386c.gif)

## Expected  behavior
The text to be still. 

## Actual behavior
It jiggles.

**Comment by worming004** [comment]
Not related to Editor-Unnecessary usings label

**Comment by rchande** [comment]
I'm not seeing this on recent versions of VS Code:
Version: 1.37.0-insider (user setup)
Commit: 3802a986823977ec472fc993854e1a753037fc8f
Date: 2019-07-29T05:30:35.768Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18956

**Comment by jjanzer** [comment]
This issue occurs when the zoom level is less then 0. @Ashtonian you can sort of work around this by setting your zoom level to 0 and reducing the font size.
