### ISSUE TITLE
when file contains chinese characters ，intellisense will not work

### ISSUE THREAD

**Issue by 717009629** [OmniSharp/omnisharp-vscode#280]
# when file does not contains chinese characters ，intellisense works well 。
![f tg7qgyic yx1p1w _k w](https://cloud.githubusercontent.com/assets/16289643/15064316/6b37d836-1385-11e6-83d3-ac635c354633.png)
# then i change “hello” to "你好"，intellisense does not work
![1rlu 48pj_lw1 5b2h 71](https://cloud.githubusercontent.com/assets/16289643/15064331/9ff33e58-1385-11e6-93ce-71477f986dec.png)

**Comment by 717009629** [comment]
After I update it to 1.0.12 ，My problem   is resolved。 thanks！

**Comment by DustinCampbell** [comment]
I suspect this will be better addressed with https://github.com/OmniSharp/omnisharp-roslyn/pull/598

**Comment by DustinCampbell** [comment]
This was fixed in https://github.com/OmniSharp/omnisharp-vscode/pull/726 and should be working properly in 1.4.0 of the C# extension for VS Code.
