### ISSUE TITLE
Debug not shutting off kestrel

### ISSUE THREAD

**Issue by nvrnight** [OmniSharp/omnisharp-vscode#2801]
## Environment data
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-009812
 Commit:    e3abf6e935

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-009812\

Host (useful for support):
  Version: 3.0.0-preview-27122-01
  Commit:  00c5c8bc40

.NET Core SDKs installed:
  2.2.100 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-009812 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-18579-0056 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27122-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-alpha-27128-4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
VS Code version: 1.30.2
C# Extension version: 1.17.1

## Steps to reproduce
Create a new Blazor project, press F5, generate launch and tasks files. Modify launch to point to your csproj file. Press F5 to debug. Click the red square to stop debugging, press F5 again to start debugging.

## Expected  behavior
Debugging to start successfully with no errors.

## Actual behavior
You will get a message saying Kestrel can't launch because port 5000 is already in use.

In the mean time I am getting around the problem by creating a task called "kill project" that gets ran on every build/startup(F5) which executes a powershell command to look for any process using port 5000 and killing it, inconvenient because it requires VS Code running as administrator to execute.

launch.json:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "dotnet",
            "args": ["run", "${workspaceFolder}"],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart",
            "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": { 
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}
```

**Comment by akshita31** [comment]
cc @gregg-miskelly

**Comment by gregg-miskelly** [comment]
@nvrnight This is NOT what you want:

```
            "program": "dotnet",
            "args": ["run", "${workspaceFolder}"],
```

Change that to:
```
            "program": "${workspaceFolder}/bin/Debug/netcoreapp3.0/<insert-your-project-name-here>.dll",
            "args": [],
```

**Comment by nvrnight** [comment]
Ah, I had originally changed it to what I have now because of "program": "${workspaceFolder}/bin/Debug/netcoreapp3.0/<insert-your-project-name-here>.dll" not working at all, complains about hostpolicy.dll required, which after working with dotnet core a bit more recently I now know that that is usually because of runtimeconfig.json not being present.

"dotnet run" works fine in the shell and is what the guide says to use to launch blazor, but I guess the debugger doesn't know how to handle shutting it off so I guess this ticket can be closed if it's not supposed to work with dotnet run. I'm guessing the root cause issue at this point is probably something specific to the blazor project.

**Comment by gregg-miskelly** [comment]
What `dotnet run` does is to start a `dotnet` process which will handle coordinating (ex: kicking off the build, finding the build output, etc), and then it spawns a child process to actually run the app. If you tell the debugger to debug a `dotnet run` process then what you are telling it to do is debug this coordination process, and NOT the app itself. When you stop debugging then this coordination process gets killed, but the app itself stays running.
