### ISSUE TITLE
There are several Msbuilds and there may be errors

### ISSUE THREAD

**Issue by arrebole** [OmniSharp/omnisharp-vscode#2802]
## Environment data
`dotnet --info` output:

OmniSharp server started.
    Path: C:\Users\root\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\OmniSharp.exe
    PID: 128

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
           
            Located 2 MSBuild instance(s)
            1: Visual Studio Community 2017 15.9.28307.280 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\root\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2017 15.9.28307.280 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"

C# Extension version:
ms-vscode.csharp-1.17.1

Since visual studio only installed vc++, the plugin has an error.

**Comment by akshita31** [comment]
@arrebole Does the path - `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"` exist for you ? If so this is probably not an error

**Comment by akshita31** [comment]
@arrebole Any updates here ?

**Comment by arrebole** [comment]
> @arrebole Any updates here ?

No, only Rename folder "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin" ，Everything will become ok。It's just staring at msbuild for Visual Studio

**Comment by arrebole** [comment]
@akshita31 It always gives priority to using Visual Studio's msbuild。There is no c# environment in Visual Studio, I am installing dotnet core independently.

**Comment by akshita31** [comment]
Can you try installing .Net Core Build Tools as described [here](https://github.com/OmniSharp/omnisharp-roslyn/issues/1311#issuecomment-428361674)

**Comment by arrebole** [comment]
@JoeRobich 
Thank you very much, but I think there is a more important issue is that the msbuild of visual studio cannot recognize the dotnetcore installed by independently(not use visual studio)
