### ISSUE TITLE
C# extension not appearing to function properly

### ISSUE THREAD

**Issue by Vandermerwer** [OmniSharp/omnisharp-vscode#2812]
Issue Type: <b>Bug</b>

Well, my extensions do not seem to be functioning properly. Nothing in my workspace is functioning as it should and I have no idea why. I have re-installed everything 4 times but the problems still persist.

Please help.

Extension version: 1.17.1
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (10.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by akshita31** [comment]
@Vandermerwer Do you have dotnet installed? Could you post the output of dotnet --info ?

Also, in your output window do you see any [OmniSharp log](https://github.com/OmniSharp/omnisharp-vscode/wiki/Reporting-Issues#omnisharp-and-c-log). If so please paste the output from that.

**Comment by Vandermerwer** [comment]
Ok, please tell me how to do that. I have no idea (sorry)

**Comment by akshita31** [comment]
Oen the terminal in vscode and execute `dotnet --info` and paste the output here. Also could you share the project you are working with ?

**Comment by akshita31** [comment]
@Vandermerwer any updates here ?

**Comment by rchande** [comment]
@Vandermerwer We haven't heard from you in a while so I'm going to close this issue. Feel free to respond if you are able to answer @akshita31 's question.

**Comment by Vandermerwer** [comment]
High, yeah, it's me again.

Sorry that I took so long to respond, and I don't even know if you are going to see this. But the problem is still there and it is making me worry a lot. Only one of the add-ons I have are functioning properly, the rest does not seem to work at all and I still have no idea how to fix it. 

If you can help me, that would be really kind.

**Comment by rchande** [comment]
@Vandermerwer You haven't given us enough information to be able to help you:
* What are you trying to do?
* What is "not functioning properly"?

**Comment by Vandermerwer** [comment]
- I'm just trying to program efficiently, because at the moment VS Code is not even showing errors in the code line. So I have to go to the corresponding software (Unity) then wait for the scripts to compile for Unity to tell me there's an error... VS Code used to show the error by underlining the line with a red "squiggly" line. But it doesn't do that anymore

- The Error detection thingy (sorry for the bad descriptions) isn't working. 
- The other thing that isn't working is the "Shortcut" thingy, when one presses Ctrl + Space it usually displays an array of code options.

Sorry for the terrible descriptions, but I don't know how to put it any other way

**Comment by akshita31** [comment]
@Vandermerwer We would need some information from your system in order to be ablt to diagnose further. In vscode can you do F1 --> `Csharp: Start authoring a new issue on github` and the paste the output from that here.

Also, please paste the output from your [OmniSharp log](https://github.com/OmniSharp/omnisharp-vscode/wiki/Reporting-Issues#omnisharp-and-c-log)

**Comment by Vandermerwer** [comment]
## Issue Description ##
## Steps to Reproduce ##

## Expected Behavior ##

## Actual Behavior ##

## Logs ##

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.31.0
**C# Extension**: 1.17.1


<details><summary>Dotnet Information</summary>
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.101\


Microsoft .NET Core Shared Framework Host



  Version  : 2.0.6

  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d



</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.17.1|
|csharpfixformat|Leopotam|0.0.78|
|docomment|k--kato|0.1.3|
|shader|slevesque|1.1.4|
|shaderlabvscodefree|amlovey|1.1.3|
|sublime-keybindings|ms-vscode|4.0.0|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-debug|Unity|2.6.6|
|unity-tools|Tobiah|1.1.0|
|unity3d-pack|dimasalmaz|1.0.0|
|vscode-csharp-snippets|jorgeserrano|0.3.1|;

</details>

**Comment by Vandermerwer** [comment]
Wow, I'm so sorry for this

**Comment by Vandermerwer** [comment]
The OmniSharp log isn't displaying anything. What should I do?

**Comment by akshita31** [comment]
Is it possible to share the project with us ?

**Comment by akshita31** [comment]
Alternatively, can you try uninstalling and then reinstalling the extension?

**Comment by Vandermerwer** [comment]
It's an entire Game that I'm building, what should I share exactly?

**Comment by Vandermerwer** [comment]
I have uninstalled and re-installed everything completely 5 times already. This is why I really need help

**Comment by akshita31** [comment]
Do you have any `C# log` in the same place you were looking for the "OmniSharp log" ?

**Comment by Vandermerwer** [comment]
Yes, but it's also not showing anything

**Comment by akshita31** [comment]
Can you try installing the latest [beta version](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.18.0-beta7). You can install it by following the instructions [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases).

**Comment by akshita31** [comment]
Also, do you have ".Net Core" installed ? 
I am asking because on my machine the dotnet info looks different:

``` .NET Core SDK (reflecting any global.json):
 Version:   2.2.102
 Commit:    96ff75a873

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.102\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100-preview-007326 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.400-preview-009063 [C:\Program Files\dotnet\sdk]
  2.1.400-preview-009197 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.500-preview-009335 [C:\Program Files\dotnet\sdk]
  2.1.500-preview-009398 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

If not can you try installing .Net Core sdk from https://aka.ms/dotnet-download

**Comment by Vandermerwer** [comment]
Well I just did all that, and it still seems to be broken

**Comment by akshita31** [comment]
That is really awkward.
Usually when the extension is able to start, we have an "Omnisharp log" channel in the output pane, with the output similar as shown below:

![image](https://user-images.githubusercontent.com/12554141/52588927-76cd1c80-2df2-11e9-97ec-218b9e28598d.png)

Are you saying that there is a pane with the OmniSharp log but it doesnt have anything in the output ?

**Comment by Vandermerwer** [comment]
Well, mine doesn't do that. I guess i'l have to completely re-install everything. If it's still not working than I'll come back to you

**Comment by Vandermerwer** [comment]
Well, unfortunately it did not work. I completely romoved VS Code from my
computer and did a complete re-install twice. And now it’s still broken,
and I have no idea ho to fix it.

**Comment by akshita31** [comment]
@Vandermerwer When did the problem start? Did you recently update the extension or vscode that triggered the problem

**Comment by rchande** [comment]
@Vandermerwer I'm sorry you're having difficulty "getting things to work", but we still don't have enough information to help you. Can you share a screenshot of what you're seeing and make sure the VS Code "Output" window is visible?

**Comment by Vandermerwer** [comment]
It started after I created a new user profile on my computer. I experienced
some severe problems with Microsoft Family features, but I managaed to fix
that. VS Code than started acting up, I did a complete re-install and it
worked fine again, then. VS Code then prompted a notification that the
OmniSharp extension isn’t working correctly (but it was) and that I need to
reload in order for it to function properly. After I reloaded, none of the
extensions worked anymore. And now I’m here

**Comment by Vandermerwer** [comment]
Please help me, I'm really getting desperate, my classes have started and I'm going to fall behind if I can't manage to fix the problem soon.

**Comment by akshita31** [comment]
@Vandermerwer Please share your project and some screenshots of vscode with your [OmniSharp log](https://github.com/OmniSharp/omnisharp-vscode/wiki/Reporting-Issues#omnisharp-and-c-log)

**Comment by Vandermerwer** [comment]
Ok, please just clarify what you mean with "Share your project". What exactly should I upload?

**Comment by akshita31** [comment]
The folder you are opening in vscode and trying to get intellisense

**Comment by Vandermerwer** [comment]
Well, I did another complete re-install. And the OmniSharp Log is showing text again. So I do think that it is all functioning again. 

I'm so sorry that I was so much trouble, It's just that I had no idea why it was broken or why it seems to be working again. Guess I just had to re-install it 11 times.

Thanks for the help and sorry for the inconvenience.

**Comment by akshita31** [comment]
@Vandermerwer Glad you got it working. I will close this issue now.
