### ISSUE TITLE
Add Go To Declaration

### ISSUE THREAD

**Issue by akshita31** [OmniSharp/omnisharp-vscode#2813]
Visual Studio Code has added support for "Go to definition". We should leverage that to add the option for the extension as well
https://code.visualstudio.com/updates/v1_30#_go-to-declaration

**Comment by rchande** [comment]
@akshita31 What do we need to do here that's not already covered by our `Go To Definition` and `Go To Implementation` features?

**Comment by akshita31** [comment]
@rchande You are right. I thought there was a separate "Go to Declaration" in VS, but just checked that my assumption was wrong. I will close this now
