### ISSUE TITLE
Not able to hit breakpoint

### ISSUE THREAD

**Issue by subramn** [OmniSharp/omnisharp-vscode#2824]
I have installed Omnisharp C# Extension in VSCode, created a console app and trying to hit a breakpoint.

getting the message

You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.

My configuration

   "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/bin/Debug/netcoreapp2.1/ConsoleApp1.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            // For more information about the 'console' field, see https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#console-terminal-window
            "console": "internalConsole",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart"

is there anything i am missing

**Comment by gregg-miskelly** [comment]
Can you follow the steps in here? https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshoot-Breakpoints

**Comment by subramn** [comment]
I tried it doesn't hit at all.

**Comment by gregg-miskelly** [comment]
Yes, that guide is designed to help troubleshoot when breakpoints don't hit. In case your problem was that you couldn't read the breakpoint message because the app immediately exits, I just added this line to the guide:

> NOTE: If you have an app that exits immediately so that you cannot read the message in time, you can add a call to `System.Threading.Thread.Sleep(-1);` in your Main method.

**Comment by subramn** [comment]
same no change.

**Comment by gregg-miskelly** [comment]
Can you tell me what you tried and what you are seeing?

**Comment by subramn** [comment]
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.

**Comment by subramn** [comment]
I tried to add debugger statement and sleep statement. how can i make sure the omnisharp is installed correctly.not sure if there is an issue there

**Comment by gregg-miskelly** [comment]
The debugger is a single zip file. So if you aren't seeing any error messages and your project is running when you hit F5, I don't think it will be an install issue. If you do think it might be, you can uninstall the extension, hit the reload button in VS Code, and then install it again.

If it isn't an install issue, can you grab a log -- https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging#quick-method

**Comment by subramn** [comment]
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"launch"}

<- (E) {"seq":5,"type":"event","event":"initialized","body":{}}

-> (C) {"command":"setBreakpoints","arguments":{"source":{"name":"Program.cs","path":"d:\\Projects\\ConsoleApp1\\ConsoleApp1\\Program.cs","checksums":[{"algorithm":"SHA1","checksum":"51d73b3315025d1e7ba325681f259755d3e469b1"},{"algorithm":"SHA256","checksum":"087ba92a25c60eb8df21fe340788e8b05070d1726c540b88c30051f083708124"},{"algorithm":"SHA1","checksum":"0f98265776e3d2f2a5c82ee76e53402513d86e22"},{"algorithm":"SHA256","checksum":"e64c77d0587e21cb1c60bd1c1492c27f755fe56f69eceb14f267508faf0fc1ef"}]},"lines":[1,10,11],"breakpoints":[{"line":1},{"line":10},{"line":11}],"sourceModified":false},"type":"request","seq":4}

<- (R) {"seq":6,"type":"response","request_seq":4,"success":true,"command":"setBreakpoints","message":"","body":{"breakpoints":[{"id":1,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":1},{"id":2,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":10},{"id":3,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":11}]}}

-> (C) {"command":"setExceptionBreakpoints","arguments":{"filters":["user-unhandled"]},"type":"request","seq":5}

<- (R) {"seq":7,"type":"response","request_seq":5,"success":true,"command":"setExceptionBreakpoints"}

-> (C) {"command":"configurationDone","type":"request","seq":6}

<- (E) {"seq":8,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/LaunchFailed","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.0.11026.1 commit:87122b596f240c8c819a194d8f57eb6c749483b9","VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"6.2.9200","VS.Diagnostics.Debugger.vsdbg.ErrorCode":-2147220965}}}

<- (R) {"seq":9,"type":"response","request_seq":6,"success":false,"command":"configurationDone","message":"Only 64-bit processes can be debugged."}

-> (C) {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":7}

<- (E) {"seq":10,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/DebugCompleted","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.0.11026.1 commit:87122b596f240c8c819a194d8f57eb6c749483b9","VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"6.2.9200","VS.Diagnostics.Debugger.vsdbg.DebugCompleted.BreakCounter":0,"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr"}}}

<- (R) {"seq":11,"type":"response","request_seq":7,"success":true,"command":"disconnect"}

**Comment by subramn** [comment]
I tried the following uninstalled the .net core and reinstalled the latest version of core 64 bit and got rid of all other versions and tried and it worked. thanks
