### ISSUE TITLE
C# debugger UTF8 encoding misbehave

### ISSUE THREAD

**Issue by guylando** [OmniSharp/omnisharp-vscode#2831]
dotnet version: 2.1.503 windows 10.0.17763 rid win10-x64
VS Code version: 1.30.2
C# Extension version: 1.17.1

Running: System.Text.Encoding.UTF8.GetString(new byte[] { 220,109,108,48,242,190,156,151 }) in vscode debugger watch window produces: "�ml0\U000be717" even though c# unicode encoding should use \u and not \U.
Then using this string inside a json produces an invalid json as seen when validated here: https://jsonlint.com/

Is it a bug? Why does it happen?

originally posted in vscode and they said it is caused by extension: https://github.com/Microsoft/vscode/issues/67507

**Comment by gregg-miskelly** [comment]
Everything seems to be working correctly as far as I can tell -- comparing the value one gets in the watch window to the result from running in the program both strings have the same value.

Here is the documentation on `\U` and `\u` -- https://msdn.microsoft.com/en-us/data/aa664669(v=vs.85). I believe the EE will use `\U` in cases where the character cannot be represented by a single UTF-16 character. In this case `\U000be717` is a single UTF-32. See 'U+010000 to U+10FFFF' in https://en.wikipedia.org/wiki/UTF-16

This character could also be represented by the following two UTF-16 characters:
```
  | [4] | 55993 '\udab9' | char
  | [5] | 57111 '\udf17' | char
```
