### ISSUE TITLE
Setting omnisharp.path to latest results in 404 error

### ISSUE THREAD

**Issue by hmobius** [OmniSharp/omnisharp-vscode#2833]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

VS Code version: 1.30.2 (user)
C# Extension version: 1.17.1

## Steps to reproduce
Added     "omnisharp.path": "latest" to my user settings file
Watched output window

## Expected  behavior
Latest beta of omnisharp plugin to download and be installed in VS Code

## Actual behavior
New version of omnisharp fails to download.
Output window reports as follows.

Error occured in loading omnisharp from omnisharp.path
Could not start the server due to Error: 404

**Comment by akshita31** [comment]
I just tried "latest" and it works now.
Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.32.11-beta.1...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.32.11-beta.1' (30604 KB).................... Done!
Installing package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.32.11-beta.1'

Finished

I will close this issue now

**Comment by edespong** [comment]
I have the same issue:

The following flashes by in the output window:

> Getting latest OmniSharp version information
> Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
> Installing OmniSharp Version = 1.32.12-beta.51...
> Platform: win32, x86_64
> 
> Downloading package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.32.12-beta.51' Failed to download from https://roslynomnisharp.blob.core.windows.net/releases/1.32.12-beta.51/omnisharp-win-x64.zip. Error code '404')
> Failed at stage: downloadAndInstallPackages
> 404

Followed by:
> Error occured in loading omnisharp from omnisharp.path
> Could not start the server due to Error: 404

vscode environment:

> Version: 1.32.3 (user setup)
> Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
> Date: 2019-03-14T23:43:35.476Z
> Electron: 3.1.6
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.17134

**Comment by Ziming9811** [comment]
I have the same issue:

Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.32.12-beta.53...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.32.12-beta.53' Failed to download from https://roslynomnisharp.blob.core.windows.net/releases/1.32.12-beta.53/omnisharp-win-x64.zip. Error code '404')
Failed at stage: downloadAndInstallPackages
404

**Comment by euangPriv** [comment]
I have the same problem , uninstalling VS2017 Ent fixed it. I suspect that OmniSharp is getting confused by different build versions across .NetCore 3.0 Preview and that installed by VS.;

C:\dev\src\scratch\NetCore\myApp>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview3-010431
 Commit:    d72abce213

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview3-27504-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Fubuchi** [comment]
on my laptop, it say `1.32.12-beta.57`

```
Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.32.12-beta.57...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.32.12-beta.57' Failed to download from https://roslynomnisharp.blob.core.windows.net/releases/1.32.12-beta.57/omnisharp-win-x64.zip. Error code '404')
Failed at stage: downloadAndInstallPackages
404
```

```
> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview3-010431
 Commit:    d72abce213

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537

.NET Core SDKs installed:
  3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview3-27504-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by vijayveluri03** [comment]
> ## Environment data
> 
> `dotnet --info` output:
> .NET Core SDK (reflecting any global.json):
> Version: 2.2.101
> Commit: 236713b0b7
> 
> Runtime Environment:
> OS Name: Windows
> OS Version: 6.1.7601
> OS Platform: Windows
> RID: win7-x64
> Base Path: C:\Program Files\dotnet\sdk\2.2.101\
> 
> Host (useful for support):
> Version: 2.2.0
> Commit: 1249f08fed
> 
> .NET Core SDKs installed:
> 2.1.500 [C:\Program Files\dotnet\sdk]
> 2.2.100 [C:\Program Files\dotnet\sdk]
> 2.2.101 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
> Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
> Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
> Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
> Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
> Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> 
> VS Code version: 1.30.2 (user)
> C# Extension version: 1.17.1
> ## Steps to reproduce
> 
> Added "omnisharp.path": "latest" to my user settings file
> Watched output window
> ## Expected behavior
> 
> Latest beta of omnisharp plugin to download and be installed in VS Code
> ## Actual behavior
> 
> New version of omnisharp fails to download.
> Output window reports as follows.
> 
> Error occured in loading omnisharp from omnisharp.path
> Could not start the server due to Error: 404

I was getting this issue too. For now i have commented out //"omnisharp.path": "latest", 
Hopefully theres a fix for this soon. i will enable it then.

**Comment by nczsl** [comment]
i have same problem
https://github.com/OmniSharp/omnisharp-vscode/issues/2949
