### ISSUE TITLE
Debugging Typescript works in VS but not in VS Code

### ISSUE THREAD

**Issue by Hypenate** [OmniSharp/omnisharp-vscode#2838]
##The Issue
As described in https://github.com/Microsoft/vscode/issues/67130 I want to debug my SPA application created with Visual Studio 2017 in Visual Studio Code, but I'm unable to set it up.
I have the chrome debugging extension installed.

## Environment data
VS Code version: 1.30.2
C# Extension version: 1.17.1

## Steps to reproduce
1. Create a new ASP.NET Core Web Application in Visual Studio
1. Choose Angular as your project Template
1. Start your application in Visual Studio and try to debug (this works)
1. Open Visual Studio Code > Open folder <your folder for the SPA app)
1. Start your application in Visual Studio Code and try to debug (this does not work)

## Expected  behavior
I want to debug my application in Visual Studio Code when creating a new Web Application in Visual Studio

## Actual behavior
I can only debug using Visual Studio.

**Comment by gregg-miskelly** [comment]
@Hypenate To be clear, you are talking about client side type script, right? What web browser are you using?

This isn't actually the right place for this question -- this extension only supports server-side debugging. But we can see if we can redirect you.

**Comment by Hypenate** [comment]
Hi @gregg-miskelly I'm also in doubt this is the right place but the VsCode team referred me to here.

What I need (I think) is a way to say to my browser "this is the URL where Angular is hosted" and "this is the URL where the server is (so you can get data from my API).

I'm using Chrome, it's all in the other ticket.

**Comment by gregg-miskelly** [comment]
@Hypenate Sorry if I am telling you things you already know, but here is roughly what you want to do:

1. Install the ['Debugger for Chrome'](https://github.com/Microsoft/vscode-chrome-debug) extension into VS Code, and reload with the new extension
2. Open a terminal and `cd` to your ASP.NET project, and execute `dotnet run`
3. Open your .vscode/launch.json file and click the 'Add Configuration' button in the bottom right
4. Select 'Chrome Launch'
5. Change the URL to the URL you want to hit in Chrome
6. Switch to the debug tab in VS Code by clicking the debug icon on the left
7. In the drop down at the top, change the active debug configuration to your new Chrome launch configuration
8. F5

**Comment by gregg-miskelly** [comment]
Closing for now, let us know if you need more assistance

**Comment by Hypenate** [comment]
When I do  `dotnet run` the servers starts and my browsers starts up
I closed that
I added the configuration like you said and spun op the debugger

When I now hover over my breakpoints, it still states: "Unverified Breakpoint"

**Comment by Hypenate** [comment]
I made a quick repo here: https://github.com/Hypenate/DemoAppForVsCodeDebugIssue
