### ISSUE TITLE
Support for Nullable Reference Types

### ISSUE THREAD

**Issue by 0xADD1E** [OmniSharp/omnisharp-vscode#2839]
## Environment data
`dotnet --info` output: N/A
VS Code version: N/A
C# Extension version: 1.17.1

## Steps to reproduce
Enable nullable reference types in the csproj file

## Expected  behavior
Behavior enabled nullable reference types option is respected (warnings displayed where appropriate, string is a valid T for Nullable<T>, etc)

## Actual behavior
Warnings are not present, OmniSharp believes string is invalid T for Nullable<T>, etc

**Comment by filipw** [comment]
Thanks for logging the issue. 

This is already available in the latest beta, you can install it from here - https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.18.0-beta6
Alternatively, you could switch to latest OmniSharp build using `"omnisharp.path": "latest"`.

Hope this helps.
