### ISSUE TITLE
OmniSharp shows errors in Problem panel of not built projects

### ISSUE THREAD

**Issue by AOne-T** [OmniSharp/omnisharp-vscode#2842]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.103/

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.503 [/usr/share/dotnet/sdk]
  2.2.103 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

VS Code version:
1.31.0

C# Extension version:
1.17.1

## Steps to reproduce
1. Create solution with multiple projects
2. The main (app) project should reference other projects except one (it should not be relevant to build it)
3. Open solution in VSCode 
4. Build it
5. Wait for OmniSharp to load it

## Expected  behavior
0 errors in problems Problems panel. Files in excluded project not showing any errors

## Actual behavior
Tons of errors in Problems panel. All code in *.cs files is "red".
Most problems say something like: "Predefined type 'System.Object' is not defined or imported [ExcludedProjectName]"

OmniSharp floods Problems panel with these "errors" making it of no use (as I see 1000+ errors in it).
They dissapear only if I make build of this project manually (`dotnet build ExcludedProjectName.csproj`). I suspect it creates "obj" and "bin" folders which OmniSharp uses.

**Comment by rchande** [comment]
@AOne-T You can use the folder icon in the lower left to choose the active project/solution. If you have an active solution, OmniSharp will not perform dotnet restore on other projects. You're correct that you'll need to manually restore projects that omnisharp is not tracking.

**Comment by AOne-T** [comment]
As you can see on the screenshot, the solution is loaded. Also using the "vscode-solution-explorer" extension I show that the problematic project exists in solution. But for now it is not referenced by any other project. And the main application project (that is configured to build and start) doesn't reference it either. So it is not build. And `dotnet restore` doesn't help: it reduces the number of errors (obvious errors about System.Object), but leaves a lot of others.
![vs_code_omni_bug_scr](https://user-images.githubusercontent.com/2842078/52501596-c1cc1180-2bf1-11e9-8285-d7d9a28598ef.png)

**Comment by rchande** [comment]
@AOne-T Can you share your OmniSharp log? Output -> OmniSharp log? It would also be helpful if you could share the csproj that isn't loading or at least describe it.

**Comment by AOne-T** [comment]
I managed to create sample solution for you. It reflect what we use. And we use `$(SolutionDir)` environment variable throughout our projects because we extensively use git submodules and it really helps, but it does bad for OmniSharp as we experience some strange problems and cannot test and debug tests using "Test lens" (or how they are called) - see https://github.com/OmniSharp/omnisharp-vscode/issues/2435
