### ISSUE TITLE
Offline package tries to download Razor Language Server

### ISSUE THREAD

**Issue by Herohtar** [OmniSharp/omnisharp-vscode#2843]
## Environment data
VS Code version: 1.31.0
C# Extension version: 1.17.1 (offline build)

## Steps to reproduce
1. Follow the [steps to build an offline VSIX package](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-the-C%23-extension-to-a-computer-without-internet-connectivity)
2. Install the resulting VSIX in VS Code on a computer with no internet connection
3. Open VS Code
4. Open a C# file

## Expected  behavior
VS Code should load the C# file without trying to download any packages.

## Actual behavior
C# output opens with the following output:
```
Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'Razor Language Server (Windows / x64)' Failed at stage: downloadAndInstallPackages
Error: getaddrinfo ENOTFOUND download.visualstudio.microsoft.com download.visualstudio.microsoft.com:443
```

## Other info
I've tried changing the `Razor: Disabled` setting to `true`, but even then it still tries to download Razor when VS Code opens a C# file.

**Comment by rchande** [comment]
@Herohtar Thanks for filing, we'll take a look.

**Comment by akshita31** [comment]
@Herohtar Can you navigate to the extension folder under C:\Users\..\.vscode\extensions\ms-vscode-csharp and checking if the .razor folder exists?
Somehow the .razor packages are not being added to the vsix.

**Comment by akshita31** [comment]
@Herohtar We merged a change #2848 that might fix this. Can you try again with the latest clone of master ?

**Comment by Herohtar** [comment]
@akshita31 The .razor folder exists under the extension folder, and it looks like it contains the files for that package.

I tried to test using the master branch, but unfortunately, I get an error during the `node node_modules/gulp/bin/gulp.js package:offline` process. (Will update with error shortly)

**Comment by akshita31** [comment]
@Herohtar For me it succeeds

Can you try the following:
1. git clean -xfd
2. Update to the latest version of node
3. npm i -g gulp
4. gulp vsix:offline:package

Here are the logs that I have 
```[14:10:37] Requiring external module ts-node/register
[14:10:39] Using gulpfile ~\vscode\extension\omnisharp-vscode\gulpfile.ts
[14:10:39] Starting 'vsix:offline:package'...
Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (30604 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'

Downloading package '.NET Core Debugger (Windows / x64)' (43127 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (Windows / x64)'

Downloading package 'Razor Language Server (Windows / x64)' (46894 KB).................... Done!
Installing package 'Razor Language Server (Windows / x64)'

starting node C:\Users\akagarw\vscode\extension\omnisharp-vscode\node_modules\vsce\out\vsce package -o C:\Users\akagarw\vscode\extension\omnisharp-vscode\csharp.1.18.0-beta7-win32-x86_64.vsix
Executing prepublish script 'npm run vscode:prepublish'...

> csharp@1.18.0-beta7 vscode:prepublish C:\Users\akagarw\vscode\extension\omnisharp-vscode
> tsc -p ./ && webpack --mode production

Hash: 1a9ed62e17e56865a331
Version: webpack 4.29.0
Time: 9861ms
Built at: 02/08/2019 2:11:11 PM
           Asset      Size  Chunks             Chunk Names
    extension.js   858 KiB       0  [emitted]  main
extension.js.map  3.67 MiB       0  [emitted]  main
Entrypoint main = extension.js extension.js.map
  [3] external "vscode" 42 bytes {0} [built]
 [22] ./src/common.ts 14 KiB {0} [built]
 [24] ./src/omnisharp/loggingEvents.ts 29.6 KiB {0} [built]
[147] ./src/packageManager/downloadAndInstallPackages.ts 6.89 KiB {0} [built]
[158] ./src/packageManager/isValidDownload.ts 2.45 KiB {0} [built]
[159] ./src/platform.ts 14.6 KiB {0} [built]
[160] ./src/coreclr-debug/activate.ts 14.6 KiB {0} [built]
[161] ./src/constants/CSharpExtensionId.ts 790 bytes {0} [built]
[180] ./src/main.ts 17.7 KiB {0} [built]
[181] ./src/omnisharp/extension.ts 21 KiB {0} [built]
[267] ./src/observers/WarningMessageObserver.ts 4.15 KiB {0} [built]
[269] ./src/observers/CsharpChannelObserver.ts 2.14 KiB {0} [built]
[270] ./src/observers/CsharpLoggerObserver.ts 12.1 KiB {0} [built]
[272] ./src/observers/DotnetChannelObserver.ts 1.66 KiB {0} [built]
[273] ./src/observers/DotnetLoggerObserver.ts 2.19 KiB {0} [built]
    + 396 hidden modules

WARNING in ./node_modules/microsoft.aspnetcore.razor.vscode/dist/RazorLogger.js 70:11-35
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/microsoft.aspnetcore.razor.vscode/dist/extension.js
 @ ./src/razor/razor.ts
 @ ./src/main.ts
 DONE  Packaged: C:\Users\akagarw\vscode\extension\omnisharp-vscode\csharp.1.18.0-beta7-win32-x86_64.vsix (1250 files, 118.1MB)`

**Comment by Herohtar** [comment]
@akshita31 Thanks, that fixed the build error.

And it looks like the changes in master fixed the attempted download issue.

**Comment by akshita31** [comment]
@Herohtar Glad you got it working 🍡

**Comment by breadnone** [comment]
This is still happening, I've been trying to get passed this process for two days to no avail. smh

**Comment by cristian2422** [comment]
Those commands did not work for us:
1.	git clean -xfd
2.	Update to the latest version of node
3.	npm i -g gulp
4.	gulp vsix:offline:package


we uninstalled the C# extensions packaged and then re-installing we get this failure:

Downloading package 'Razor Language Server (Windows / x64)' Failed at stage: downloadPackage
Error: unable to get local issuer certificate

When we try to run debug, we get a prompt to Select the process to attach to with a long list, what we should select?.

just to make clear, the main error here is :

Couldn't find a debug adapter descriptor for debug type 'coreclr' (extension might have failed to activate).
Downloading package 'Razor Language Server (Windows / x64)' Failed at stage: downloadPackage
Error: unable to get local issuer certificate

and the issue started right as we upgraded VSCode to latest version 1.56.2  



just in case; we do not have this folder: C:\Users...vscode\extensions\ms-vscode-csharp not even the .razor directory.
we have the folder: ms-dotnettools.csharp-1.23.11. And inside this there is a .razor folder.

is this a bug on latest VCode Version as it did not happens in previous ones?
your help please_

**Comment by cepera-one** [comment]
I had the same problems. Then I restarted VSCode with admin rights and Razor Language Server was downloaded successfully.

**Comment by stfujnkk** [comment]
This is my error log
```log
Downloading package 'Razor Language Server (Windows / x64)' Failed at stage: downloadPackage
Error: read ECONNRESET
```
---
I checked the `~\extensions\ms-dotnettools.csharp-1.23.15\package.json` . 
The following is a file fragment
```json
{
    "id": "Razor",
    "description": "Razor Language Server (Windows / x64)",
    "url": "https://download.visualstudio.microsoft.com/download/pr/b8678010-2cd7-4201-a5e7-ba57920607d5/a654aaa3c8090ca1751d7f7646a7b000/razorlanguageserver-win-x64-6.0.0-preview.5.21358.6.zip",
    "installPath": ".razor",
    "platforms": [
        "win32"
    ],
    "architectures": [
        "x86_64"
    ]
}
```
I use the connection in the file to download it manually. But it failed. 
**Can you check the link ?** 
`https://download.visualstudio.microsoft.com/download/pr/b8678010-2cd7-4201-a5e7-ba57920607d5/a654aaa3c8090ca1751d7f7646a7b000/razorlanguageserver-win-x64-6.0.0-preview.5.21358.6.zip`

**Comment by tongpeifu-yh** [comment]
At least the link in my package.json works, but I have to create an empty file named install.Lock in .razortelemetry folder to make vscode recognise the extracted files.
