### ISSUE TITLE
Allow a custom path to a dotnet executable

### ISSUE THREAD

**Issue by kirbyfan64** [OmniSharp/omnisharp-vscode#2844]
Currently, omnisharp assumes dotnet is in the PATH. However, it would be nice if we could pass a path to a dotnet SDK, e.g. to use a different version or one not globally available. If this seems plausible, I can work on it myself.

I'm guessing this would either involve:

1. Using the full dotnet path wherever the CLI is called (more elegant but more difficult version).
2. Modify the PATH from the extension (uglier but likely easier).

I *personally* prefer 1, but if the maintainers prefer I could do 2 instead.

## Steps to reproduce

- Try to use a dotnet SDK without putting it in your PATH.

## Expected behavior

- Should be able to pass a custom path to the dotnet executable.

## Actual behavior

- Cannot set a custom dotnet path without setting the PATH environment variable first.

**Comment by gregg-miskelly** [comment]
There isn't a good way to do this -- its not just this extension that needs to launch `dotnet` but also other parts of VS code. You can open up a terminal/command prompt, add dotnet to some local version of PATH, and start VS Code from there.

**Comment by rchande** [comment]
@kirbyfan64 As @gregg-miskelly says and you've alluded to, the most reliable way to do this would be to change your path. I'm curious--what is your scenario where you need to specify a specific dotnet.exe but global.json isn't sufficient?

**Comment by AlexQwertus** [comment]
I would like to be as much independent from the environment as possible because I want to use vscode in a portable version.

**Comment by gregg-miskelly** [comment]
For debugging, I believe you can make things work if you --

1. The first time you install a new version of the C# extension: launch VS Code with a terminal that has `dotnet` on the path
2. Change your launch.json to instead of `"program": "${workspaceFolder}/bin/Debug/netcoreapp2.1/clicon.dll", "args": []` you have `"program": "insert-part-to-dotnet", "args": [ "${workspaceFolder}/bin/Debug/netcoreapp2.1/clicon.dll" ]`
3. Change your task.json so that you replace `dotnet` with something fully pathed.

I don't know if there are good ways to do this the language service.
I don't see any good way to make a more 'on road' experience, except for maybe the first-time-launch part.

**Comment by kirbyfan64** [comment]
Hmm okay, I guess this isn't an option then, I'll just close!

@rchande Basically I'm working with the VS Code Flatpak, the dotnet sdk is in `/usr/lib/sdk/dotnet` which isn't in the path by default, so I was just trying to see if there's a good way of generically being able to call into it...

**Comment by mehmet0zen** [comment]
Hey! I just figured it out! Your VS Code has no idea where is the dotnet PATH!
I submitted the solution on [https://stackoverflow.com/a/71388977/15285942](Stackoverflow).
Hope it helps!

**Comment by RossBugginsNHS** [comment]
Workaround I use is to create a command prompt with custom environment variable (this overwrites both system and user env vars) and then load vs code from there. Useful if had to install dotnet by manually extracting binaries with no admin permissions and an old dotnet framework exists elsewhere on system.

Run, or create shortcut to:

PATH=C:\Users\[UserHomeDirectory]\dotnet;C:\Users\[UserHomeDirectory]\.dotnet\tools;C:\Users\[UserHomeDirectory]\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\[UserHomeDirectory]\AppData\Local\GitHubDesktop\bin;C:\Program Files\Git\cmd"

Can then use omnisharp with git and debugging in vscode no problem.
