### ISSUE TITLE
Ubuntu Debug Issue : You may only use the Microsoft .NET Core Debugger (vsdbg) with Visual Studio Code, Visual Studio or Visual Studio for Mac software

### ISSUE THREAD

**Issue by dbrimley** [OmniSharp/omnisharp-vscode#2846]
## Environment data
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.103/

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.2.103 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

VS Code version: Version: 1.31.0
C# Extension version: 1.17.1

## Steps to reproduce
Attempt to Debug a C# program

## Expected  behaviour
Debug.

## Actual behaviour
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------

**Comment by gregg-miskelly** [comment]
@dbrimley are you using the official Microsoft build of VS Code? (Ex: what you get from https://code.visualstudio.com/)

**Comment by dbrimley** [comment]
It's provided via Ubuntu SNAP...

```snap list                                                                                                                                                                                                                                                Fri 08 Feb 2019 16:32:25 GMT
Name                     Version                    Rev   Tracking  Publisher     Notes
vscode                   1.31.0-1549443364          77    stable    snapcrafters  classic
```

**Comment by gregg-miskelly** [comment]
Thanks! Unfortunately VS Code has recently broken their error reporting so the error message doesn't show up, but the issue is that debugging is only supported in the official version of VS Code. So if you want debugging to work you will need to uninstall that copy and reinstall the official version instead.

The .NET Debugger used by the C# extension is considered a part of Visual Studio, and hence is only licensed to work in official Microsoft products.

**Comment by dbrimley** [comment]
I've removed the snap install visual studio code.
I've cleaned up .vscode
I've downloaded and installed the .deb file on the code.visualstudio.com website
run vscode and it pulled in the C# extension again downloading the debugger etc.
ran the same code
afraid I get the same error.

![screenshot from 2019-02-08 17-01-08](https://user-images.githubusercontent.com/1588244/52493445-5e2aef80-2bc3-11e9-977f-40821d4d1ac5.png)

**Comment by gregg-miskelly** [comment]
@dbrimley

**Comment by gregg-miskelly** [comment]
@dbrimley Actually, from your screen shot it looks like things are now working. What are you expecting to have happen that isn't?

**Comment by dbrimley** [comment]
I'm still getting the message about the debugger only working with Mac?  Debugging isnt working for me.

**Comment by gregg-miskelly** [comment]
You mean the license banner text (see below) correct? If so, that doesn't look to be related to your problem, at least anymore. Can you tell me more about what isn't working?

License banner text:
```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
```

**Comment by dbrimley** [comment]
You're right it appears to be working now, I'll close this.

Thanks so much for your help Greg.

**Comment by SiamakShams** [comment]
I got the same message on Ubuntu 18.04 - official installation of MS VS Code from .deb package downloaded from MS Website. But while I have the amber warning message, debug runs happily in the VS Code terminal. So, regardless of the message, try the debug and see if it works.
