### ISSUE TITLE
Leaking razor process

### ISSUE THREAD

**Issue by koliyo** [OmniSharp/omnisharp-vscode#2851]
The csharp extension is leaking processes.
```
  501  2957     1   0  8:22AM ??         0:01.65 /Users/nils/.vscode/extensions/ms-vscode.csharp-1.17.1/.razor/rzls -lsp --logLevel None
```
Note: VS code is not running

## Environment data
`dotnet --info` output: Version:   2.2.103
VS Code version: 1.31.1 
C# Extension version: 1.17.1

Mac OS Mojave

## Expected  behavior
Proper cleanup of internal processes

**Comment by NTaylorMullen** [comment]
@dbaeumer Razor [uses ](https://github.com/aspnet/Razor.VSCode/blob/master/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorLanguageServerClient.ts)the `LanguageClient` to turn on/off its LanguageServer. What's the best usage of LanguageClient to ensure that we dispose of the process when VSCode exits?

**Comment by dbaeumer** [comment]
@NTaylorMullen the `LanguageClient` offers a stop method. When called it send the `exit` notification to the server to tell the server process to shutdown.

**Comment by NTaylorMullen** [comment]
Hmm, interesting. The server should definitely be handling that exit notification successfully then. @koliyo does it leak every time?

FYI @david-driscoll

**Comment by koliyo** [comment]
I don't think it happens every time.

A general suggestion would be not to rely completely on shutdown callbacks/notifications. You should also look at the POSIX `setpgid` functionality, and how this can be used to bind child processes to the parent

See this snippet I am using in another project
https://github.com/Microsoft/vscode-python/issues/3331#issuecomment-459278663

And from `setpgid` man page
http://man7.org/linux/man-pages/man2/setpgid.2.html
```
       If the termination of a process causes a process group to become
       orphaned, and if any member of the newly orphaned process group is
       stopped, then a SIGHUP signal followed by a SIGCONT signal will be
       sent to each process in the newly orphaned process group.  An
       orphaned process group is one in which the parent of every member of
       process group is either itself also a member of the process group or
       is a member of a process group in a different session (see also
       credentials(7)).
```

Not sure about similar functionality in Windows.

**Comment by koliyo** [comment]
This is not isolated to any extension, such as `omnisharp` and `python`, but should be addressed systematically in VS Code. Which it does to some extent I guess.

**Comment by dbaeumer** [comment]
For server's written in node this is addressed by passing the process id of the extension host to the server. Here we do this generically since we know how to start node. The Razor server uses a command to start the server. You could do the same and simply add an argument to the command that passes the process id. Our servers then check from time to time of that process still exists and if not exit themselves. This works under Linux, Mac and Windows.

**Comment by NTaylorMullen** [comment]
@rchande / @akshita31 how do you guys ensure OmniSharp exits?

**Comment by rchande** [comment]
@NTaylorMullen We include it in our list of things to dispose when the extension is deactivated: https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/omnisharp/extension.ts#L171

**Comment by jonathan-vouch** [comment]
Also faced this today randomly. I'm not even trying to use Razor or C#!

**Comment by ThomasNigro** [comment]
Same here! Will try to provide more info if this becomes a regular issue.

**Comment by awyl** [comment]
On mac m1.  Every time omnisharp start, it leaves behind a `rzls` process.  So if I restart omnisharp or reload vscode window or completely closed vscode, it leaves behind one `rzls` each time.

This has been happening quite a while.

Currently on `1.38.3-beta.87-net6.0`.


Currently on

**Comment by jtsom** [comment]
This is a big issue. See the screenshot below - there are over a dozen of these abandoned `rzls` processes running - even for older versions of the extension. This is with the latest version of the C# extension, and latest Insider version of VS Code (as of today):

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/13488/173709731-6e5e46dc-abee-4d12-bc0c-89bb632568ec.png">

**Comment by jtsom** [comment]
A Month and a half later and nothing.....

**Comment by akonyer** [comment]
I'm seeing this all the time. Most of the time I open and close VS Code I have rzls processes spun up and they hang out indefinitely, even after completely closing VSCode.

**Comment by amplicity** [comment]
I'm experiencing this today (mac m1 monterey 12.3.1). VS code 1.71.2

**Comment by mikes-gh** [comment]
My processes today.
macOS 12.6

![Screenshot 2022-10-18 at 00 36 15](https://user-images.githubusercontent.com/16208742/196302980-716818a9-aa15-4e84-842b-0891f07c8316.png)

Really slows down intelisense too.

**Comment by allisonchou** [comment]
Hi all! C# extension v1.25.4 was released earlier today which should address this problem. Please let us know if you continue to run into issues. Thanks, and happy coding!

@dibarbet Could you help close out this issue? (I don't have permissions.)

**Comment by mikes-gh** [comment]
@allisonchou vscode doesn't appear to recognise this update yet.  Is this a main stream release?

**Comment by dibarbet** [comment]
> @allisonchou vscode doesn't appear to recognise this update yet. Is this a main stream release?

@mikes-gh 
Yeah v1.25.4 was uploaded as the latest release to the [gallery](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) yesterday.  
If VSCode isn't automatically updating for you, you could try explicitly requesting another version here
<img width="495" alt="image" src="https://user-images.githubusercontent.com/5749229/214657073-d76d001a-40d2-472c-8770-623d93e5c43b.png">
