### ISSUE TITLE
Go To File (Cmd+P) doesn't find files in projects listed in .sln file

### ISSUE THREAD

**Issue by prime31** [OmniSharp/omnisharp-vscode#2854]
## Issue Description ##
This is similar to #2853. When you have a .sln file that references projects that are in folders outside of the one opened by Code, Go To File won't find the files.

## Steps to Reproduce ##
- Setup two projects, MainProj and LinkedProj with the directory structure listed below (two folders next to each other).

[MainProj]
     - MainProj.csproj
     - MainProj.sln (references MainProj.csproj and ../LinkedProj.csproj)
[LinkedProj]
     - LinkedProj.csproj

- open MainProj.sln
- Cmd+P and attempt to find a file that is in LinkedProj

## Expected Behavior ##
The expected behaviour is that files in other csproj projects will be found since they are listed in the .sln file.

## Actual Behavior ##
Files in LinkedProj.csproj cannot be searched for

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

```Starting OmniSharp server at 2/14/2019, 6:09:43 PM
    Target: /Users/desaro/Desktop/Folders/Nugget/Nugget.sln

OmniSharp server started with Mono 5.16.0.
    Path: /Users/desaro/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.11-beta.10/omnisharp/OmniSharp.exe
    PID: 84477

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.14.3 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/Users/desaro/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.11-beta.10/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin"
            CscToolPath = /Users/desaro/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.11-beta.10/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/desaro/Desktop/Folders/Nugget'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/desaro/Desktop/Folders/Nugget/Nugget.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/desaro/Desktop/Folders/Nugget/Nugget.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/desaro/Desktop/Folders/FNA/FNA.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/desaro/Desktop/Folders/Nez.FNA/Nez.FNA/Nez.FNA.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/desaro/Desktop/Folders/Nugget'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/desaro/Desktop/Folders/Nugget/Nugget.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/desaro/Desktop/Folders/Nugget' on host 84437.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/desaro/Desktop/Folders/Nugget/Nugget.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/desaro/Desktop/Folders/Nugget/Nugget.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/desaro/Desktop/Folders/FNA/FNA.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/desaro/Desktop/Folders/FNA/FNA.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/desaro/Desktop/Folders/FNA/FNA.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/desaro/Desktop/Folders/Nez.FNA/Nez.FNA/Nez.FNA.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/desaro/Desktop/Folders/Nez.FNA/Nez.FNA/Nez.FNA.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/desaro/Desktop/Folders/Nez.FNA/Nez.FNA/Nez.FNA.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Nugget
[info]: OmniSharp.MSBuild.ProjectManager
        Found referenced project outside root directory: /Users/desaro/Desktop/Folders/ImGui.NET/src/ImGui.NET/ImGui.NET.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/desaro/Desktop/Folders/ImGui.NET/src/ImGui.NET/ImGui.NET.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/desaro/Desktop/Folders/ImGui.NET/src/ImGui.NET/ImGui.NET.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: FNA
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Nez.FNA
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/desaro/Desktop/Folders/ImGui.NET/src/ImGui.NET/ImGui.NET.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/desaro/Desktop/Folders/ImGui.NET/src/ImGui.NET/ImGui.NET.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: ImGui.NET
```

### C# log ###
<details>Post the output from Output-->C# here</details>

```Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.32.11-beta.10...
Platform: darwin, x86_64

Finished

Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.32.11-beta.10...
Platform: darwin, x86_64

Finished
```

## Environment information ##

**VSCode version**: 1.31.1
**C# Extension**: 1.17.1

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.16.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  1.0.0-preview2-1-003177 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|ayu|teabyii|0.18.0|
|code-settings-sync|Shan|3.2.4|
|csharp|ms-vscode|1.17.1|
|docomment|k--kato|0.1.3|
|make-hidden|devine-davies|2.3.3|
|mono-debug|ms-vscode|0.15.8|
|theme-tinacious-contrast|sugarpirate|0.0.2|
|unity-debug|Unity|2.6.6|
|vscode-duplicate|mrmlnc|1.2.1|
|vscode-icons|robertohuertasm|8.1.0|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-solution-explorer|fernandoescolar|0.3.1|;

</details>

**Comment by rchande** [comment]
@prime31 Ctrl-p is the VS Code command to locate files. It searches files, not symbols, so it only searches files that are available in your VS Code workspace. If your workspace doesn't include the linkedproj folder, Ctrl-P won't be able to find it. You can make it available by opening the parent of both mainproj and linked proj, or by adding the linkedproj folder to your workspace.

Note that ctrl-T, which is the "Find Symbol" command does find symbols declared in linkedproj.
