### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by nickmits** [OmniSharp/omnisharp-vscode#2855]
- Issue Type: `Bug`
- Extension Name: `csharp`
- Extension Version: `1.17.1`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.31.1`
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 775,
		"activateCallTime": 30,
		"activateResolvedTime": 3952,
		"activationEvent": "workspaceContains:*.csproj,*.sln,*.csx,*.cake,**/*.csproj,**/*.sln,**/*.csx,**/*.cake"
	}
}
The extension never starts on my pc even after I set the waiting time to 3000s in the package.json

**Comment by akshita31** [comment]
@nickmits What is the project that you are trying to open in your workspace ?

**Comment by nickmits** [comment]
a project web api core2.2

Στις Παρ, 15 Φεβ 2019 στις 8:30 μ.μ., ο/η Akshita Agarwal <
notifications@github.com> έγραψε:

**Comment by nickmits** [comment]
can you help me ?cause its kind difficult to debug without omnisharp..

Στις Σάβ, 16 Φεβ 2019 στις 2:11 μ.μ., ο/η Νικόλαος Μητσέλος <
nick.mitselos@gmail.com> έγραψε:

**Comment by akshita31** [comment]
@nickmits Does the extension activate for you for a simple `dotnet new console` project ? Do you see any 
[OmniSharp log](https://github.com/OmniSharp/omnisharp-vscode/wiki/Reporting-Issues#omnisharp-and-c-log)

**Comment by akshita31** [comment]
@nickmits Any updates here ?

**Comment by nickmits** [comment]
Yes it works!! Thanks

Στις Παρ, 1 Μαρ 2019, 8:45 μ.μ. ο χρήστης Akshita Agarwal <
notifications@github.com> έγραψε:

**Comment by akshita31** [comment]
@nickmits Glad you got it working. Please let us know if the problem reappears.
