### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bryanzavala** [OmniSharp/omnisharp-vscode#2856]
- Issue Type: `Performance`
- Extension Name: `csharp`
- Extension Version: `1.17.1`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/bryan/ms-vscode.csharp-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by akshita31** [comment]
@bryanzavala Can you try upgrading to the latest mono version as suggested [here](https://github.com/OmniSharp/omnisharp-vscode/issues/2794#issuecomment-457050038) and checking if the problem still persists.
Also, we have a [beta release](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.18.0-beta7) containing major improvements on the code load times. You can install it by following the instructions [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases). Please let us know if that helps.

**Comment by akshita31** [comment]
@bryanzavala We haven't heard back from you in a while so I will close this issue now. Please feel free to reopen if the problem still persists with the latest version(1.18.0).
