### ISSUE TITLE
Command '.NET: Generate Assets for Build and Debug' resulted in an error.

### ISSUE THREAD

**Issue by derviskiratli** [OmniSharp/omnisharp-vscode#2865]
## Issue Description ##
Error message when running the '.NET: Generate Assets for Build and Debug command
## Steps to Reproduce ##
1. Create a new asp dotnet core project.
2. Open it with Visual Studio.
3. Run the '.NET: Generate Assets for Build and Debug command.
## Expected Behavior ##
Creation of the necessary JSON files.
## Actual Behavior ##
Error message: Command '.NET: Generate Assets for Build and Debug' resulted in an error.
![image](https://user-images.githubusercontent.com/26737510/53121082-a77c2700-3553-11e9-95ab-5d7267181aca.png)

## Environment information ##

**VSCode version**: 1.31.1
**C# Extension**: 1.17.1

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.104\

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.17.1|
|npm-intellisense|christian-kohler|1.3.0|
|vetur|octref|0.16.1|
|vscode-npm-script|eg2|0.3.5|
|vue-inline-template|faisalhakim47|1.0.1|;

</details>

**Comment by rchande** [comment]
@derviskiratli I wasn't able to reproduce this with a project created via `dotnet new web`--would you mind sharing your omnisharp log?

**Comment by derviskiratli** [comment]
Where can I find the logs?

**Comment by yonasayfu** [comment]
Just Uninstall C# Extension and Re Install again, this worked for me.

**Comment by Rajkumar777108** [comment]
Adding PATH variable to C:\Windows\System32, worked for me..

**Comment by ThijmenLTH** [comment]
How can you add PATH variable @Rajkumar777108 ??

**Comment by f2calv** [comment]
I had to add
```json
"omnisharp.useGlobalMono": "never"
```
to my vscode settings.json see https://github.com/OmniSharp/omnisharp-vscode/issues/4219 for more info.

**Comment by Sahira22** [comment]
I just uninstalled it and Install a old version. It worked for me

**Comment by GoodGuyGregory** [comment]
> I had to add
> 
> ```json
> "omnisharp.useGlobalMono": "never"
> ```
> 
> to my vscode settings.json see #4219 for more info.

Where in VSCode did you add this? in your `launchsettings.json`? or somewhere else?

**Comment by GoodGuyGregory** [comment]
I also reinstalled the C# extension and everything appears to be working. but I dont see this as a healthy alternative to writing C# code and debugging on a mac

**Comment by vimalra** [comment]
For Windows
Show all Commands   Ctrl +Shift + p,  then search for assets then choose
NET: Generate Assets for Build and Debug
Little prompt on your right bottom -> Say Yes.
