### ISSUE TITLE
CSharp: Report an issue doesn't show and Start an Issue on GitHub is blank page

### ISSUE THREAD

**Issue by DanJ210** [OmniSharp/omnisharp-vscode#2866]
## Environment data
`dotnet --info` output: 3.0.100-preview-010184
VS Code version: 1.31.1
C# Extension version: 1.17.1

## Steps to reproduce

1. Open Visual Studio Code
2. Bring up the command palette (press <kbd>F1</kbd>)
3. Type `CSharp: Report an issue`
4. Note that it doesn't exist
5. Backspace to `CSharp:`
6. Select `CSharp: Start authoring a new issue on GitHub`
7. Blank page is opened

## Expected  behavior
To prefill this information:
1. Open Visual Studio Code
2. Bring up the command palette (press <kbd>F1</kbd>)
3. Type `CSharp: Report an issue`

## Actual behavior

1. `CSharp: Report an issue` does not exist
2. `CSharp: Start authoring a new issue on GitHub` opens a blank page

**Comment by rchande** [comment]
@akshita31

**Comment by akshita31** [comment]
@DanJ210 Could you try the [latest beta](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.18.0-beta7) containing the fix for this issue is out. You can install it by following the instructions [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases). Please let us know if this fixed the issue.

**Comment by DanJ210** [comment]
@akshita31 I don't mind. If I install the beta will I get the next production update when it comes out? Or will I have to remove the beta and install the extension from the extension store when I want the next version?

**Comment by akshita31** [comment]
@DanJ210 You will get the production update whenever it is available.

**Comment by DanJ210** [comment]
Ok I've installed beta 8 and tied, it is fixed now.
