### ISSUE TITLE
C# syntax highlight does not work properly

### ISSUE THREAD

**Issue by xcap2000** [OmniSharp/omnisharp-vscode#2871]
- VSCode Version: 1.31.1
- C# Extension: 1.17.1
- OS Version: Debian 9 (Stretch)

Steps to Reproduce:

1. Create C# Contact class accepting string name and int phone.
2. Put its contructor's parentheses and parameters on its own lines.

Working Scenario:
![image](https://user-images.githubusercontent.com/620133/53216711-411b0580-3634-11e9-8657-b7aa40d7c88a.png)

Problematic Scenario:
![image](https://user-images.githubusercontent.com/620133/53216771-6f98e080-3634-11e9-88a9-3650028d2f54.png)

**Comment by ljsnogard** [comment]
Reproducible in:
* VSCode Version: 1.31.1
* C# Extension: 1.17.1
* OS Version: macOS Mojave (10.14.3)

**Comment by akshita31** [comment]
Moved to https://github.com/dotnet/csharp-tmLanguage/issues/150
