### ISSUE TITLE
Highlight delimited documentation comments /** */

### ISSUE THREAD

**Issue by lmmarsano** [OmniSharp/omnisharp-vscode#2872]
Issue Type: <b>Feature Request</b>

According to the C♯ specification, there's a [delimited documentation comment syntax](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments#introduction), and VS Code supports this (eg, Intellisense).
However, the XML in delimited documentation comments such as
```C#
/**
<summary>
	Filler
</summary>
*/
```
is not getting syntax highlighting that single line comment syntax such as
```C#
/// <summary>
/// 	Filler
/// </summary>
```
is getting.
Can this be added?

Extension version: 1.18.0-beta7
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

**Comment by akshita31** [comment]
Moved to https://github.com/dotnet/csharp-tmLanguage/issues/151
