### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by VincentGrice** [OmniSharp/omnisharp-vscode#2883]
- Issue Type: `Performance`
- Extension Name: `csharp`
- Extension Version: `1.17.1`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\vince\ms-vscode.csharp-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by akshita31** [comment]
@VincentGrice C# extension 1.18.0 is out with major performance improvements. Can you try installing the latest version and checking if the problem still persists? If yes please upload the cpu profile so that we can analyse the problem.

**Comment by akshita31** [comment]
@VincentGrice We havent heard from you in a while. I will close this issue now. Please feel free to reopen if the problem persists.
