### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AdityaMehtaIn** [OmniSharp/omnisharp-vscode#2885]
- Issue Type: `Performance`
- Extension Name: `csharp`
- Extension Version: `1.17.1`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/adityamehta/ms-vscode.csharp-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by akshita31** [comment]
@AdityaMehtaIn C# extension 1.18.0 is out with major performance improvements. Can you try installing the latest version and checking if the problem still persists?

**Comment by akshita31** [comment]
@AdityaMehtaIn We havent heard from you in a while. I will close this issue now. Please feel free to reopen if the problem persists.
