### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ghost** [OmniSharp/omnisharp-vscode#2894]
- Issue Type: `Performance`
- Extension Name: `csharp`
- Extension Version: `1.17.1`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.32.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\grigo\ms-vscode.csharp-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by akshita31** [comment]
@LinuxDevelop Please try the [beta version](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.18.0-beta8) and see if the problem still reproduces. You can install it by following the instructions [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases). Please let us know if this fixed the issue.

**Comment by JesseTG** [comment]
For the benefit of whoever else has this issue: I have this issue (though on Linux), but I can confirm that the beta you link to resolves it.  Also, for Unity users, the current version of the Unity debugger extension (2.7.2) *does* work as expected with the linked beta.

**Comment by JesseTG** [comment]
Actually, I think the beta might have made it worse.

**Comment by akshita31** [comment]
@JesseTG Could you upload the cpu profile(with the latest release version, ie, 1.18.0)? That would help us analyse the issue better.

**Comment by akshita31** [comment]
@ghost @JesseTG We havent heard back from you in a while so I will close this issue now. Please reopen if the problem persists.
