### ISSUE TITLE
`go to definition` doesn't go to source but metadata 

### ISSUE THREAD

**Issue by fatfatson** [OmniSharp/omnisharp-vscode#2895]
## Environment data
`dotnet --info` output:

> .NET Core SDK (reflecting any global.json):
>  Version:   2.2.100
>  Commit:    51868761f2
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.13
>  OS Platform: Darwin
>  RID:         osx.10.13-x64
>  Base Path:   /usr/local/share/dotnet/sdk/2.2.100/
> 
> Host (useful for support):
>   Version: 2.2.0
>   Commit:  1249f08fed
> 
> .NET Core SDKs installed:
>   2.2.100 [/usr/local/share/dotnet/sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

VS Code version:

> 1.31.1 (1.31.1)

C# Extension version:

> 1.31.1 (1.31.1)

## Steps to reproduce
in a multi projects(csproj) solution workspace(only one root), press a hotkey to send the `go to definition` command for a type defined in other assembly.

## Expected  behavior
it should go to the source file containing the implementation of the symbol.

## Actual behavior
it open a `metadata` view instead of its source file.

**Comment by SIkebe** [comment]
？

**Comment by fatfatson** [comment]
BTW, maybe its mechanism is parsing the binary file instead of the source, so any changes in the file of  the dependent assembly won't take effect until execute the `Restart Omnisharp` command, it's slow and annoying. 
could this been configuration for using the source file, just as the visual studio does.

**Comment by rchande** [comment]
@fatfatson This happens because the Go To Definition subsystem thinks that the type you're inspecting is coming from an _assembly reference_ instead of a _project reference_. It's hard to say exactly why that's happening. Can you share your OmniSharp log and csproj?

**Comment by fatfatson** [comment]
@rchande thank you for pointing out the problem, indeed I'm referencing that assembly by file instead of project, it's a xamarin related issue, its main(app) project could not be referenced `by project`.

**Comment by cartermp** [comment]
This would be by design. Unless it is a project reference, there's no way for the tools to know that you intend on that assembly reference to actually be a project reference.
