### ISSUE TITLE
"Go to Definition" does not work for locating types & methods external to project folder structure

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#29]
_From @BrandonClapp on February 3, 2016 16:21_

For classes and methods found outside of my project's folder structure, I am unable to go to definition. The editor knows how to pull in the excerpt for the description, however, upon clicking the "Go to Definition" button, it does nothing.

For ASP.NET 5, all framework references have been moved into nuget packages, so they are all external to my project's folder structure.

How should I go about figuring out what particular types and methods look like in ASP.NET 5 that are located in nuget packages? Is there an easier way to figure out which nuget package a particular class or method comes from?

_Copied from original issue: Microsoft/vscode#2677_

**Comment by jrieken** [comment]
for started here actually: https://github.com/OmniSharp/omnisharp-vscode/tree/joh/useNewApi

**Comment by v-pavanp** [comment]
I am facing the same issue no action while performing "Go to Definition" or "Peek Definition" for .Net native API.

**Comment by DustinCampbell** [comment]
This should be addressed once 1.4.0 of the C# extension is released, which includes support for "Metadata as Source" like Visual Studio has. See #671 for details.
