### ISSUE TITLE
Breakpoint on the StopAsync method of a HostedService is not hit

### ISSUE THREAD

**Issue by BrightSoul** [OmniSharp/omnisharp-vscode#2904]
Hello,
I'm using ASP.NET Core 2.2, extension v1.17.1 and Visual Studio Code v1.32.1.

I made a simple hosted service like this one. As you can see, I log a line of text in both the `StartAsync` and `StopAsync` methods.
```C#
public class MyHostedService : IHostedService
{
  private readonly ILogger<MyHostedService> logger;
  
  public MyHostedService(ILogger<MyHostedService> logger) {
    this.logger = logger;
  }
  public async Task StartAsync(CancellationToken cancellationToken)
  {
    logger.LogInformation("Starting");
  }
  public async Task StopAsync(CancellationToken cancellationToken)
  {
    logger.LogInformation("Stopping");
  }
}
}
```
I've set a breakpoint inside the `StartAsync` method, and it gets hit as soon as I start the debugging session, as it should be. I've also set another breakpoint inside `StopAsync` but that's not hit when I stop the execution with the red Stop button or by pressing Shift+F5. Is this the intended behavior? It thought that maybe the application process is just killed forcefully and the `StopAsync` method doesn't even get the chance of being invoked.

Can you clarify? Thanks in advance.

**Comment by gregg-miskelly** [comment]
Yes, that is correct - the stop debugging button will forcefully terminate the target process.

**Comment by BrightSoul** [comment]
Ok, thanks for the clarification. Then I think I'll just run the application with `dotnet run` and then attach the debugger to the `dotnet` process. This way the breakpoint in `StopAsync` gets hit after I press CTRL+C in the console.
