### ISSUE TITLE
VS Code Extensions Marketplace: C# extension should be in Languages category

### ISSUE THREAD

**Issue by dougbu** [OmniSharp/omnisharp-vscode#292]
###### VS Code experience
The VS Code extension is currently listed in the unhelpful "Other" category.
![marketplace](https://cloud.githubusercontent.com/assets/6431421/15132141/547ab216-160b-11e6-8fd6-ed88f0f2b17b.png)

**Comment by dougbu** [comment]
See https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

**Comment by DustinCampbell** [comment]
This was already done with #94. The categories will appear the next time we ship on the marketplace.
