### ISSUE TITLE
unity向けのコード補完が効かない

### ISSUE THREAD

**Issue by shoupeace** [OmniSharp/omnisharp-vscode#2929]
Issue Type: <b>Bug</b>

期待する結果
Unityで提供されている関数を入力しようとした際オートコンプリートされる
例)”Ge” と入力すると予測変換に"GetCompornent"が出る
実際の結果
C#向けの関数しかコード補完されず、Unity向けの関数が補完されない

Extension version: 1.17.1
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 6.1.7600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.98GB (4.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by akshita31** [comment]
@shoupeace Can you be clearer on what is the issue here ?
