### ISSUE TITLE
VS Code extension: Suggest adding support for Mono and perhaps full desktop CLR

### ISSUE THREAD

**Issue by dougbu** [OmniSharp/omnisharp-vscode#293]
The OmniSharp extension for VS Code has the general name "C# for Visual Studio Code (powered by OmniSharp)" but actually supports only the .NET Core project system. Rather than narrowing the name, I suggest expanding the extension to support Mono on all platforms and perhaps the full desktop CLR on Windows.

**Comment by DustinCampbell** [comment]
Hi, this is implemented with the latest release, (v1.3.0](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.3.0)
