### ISSUE TITLE
vscode omnisharp latest 404

### ISSUE THREAD

**Issue by divinebovine** [OmniSharp/omnisharp-vscode#2930]
## Issue Description ##
Using the latest omnisharp setting in vscode fails to fetch the latest omnisharp release.

## Steps to Reproduce ##
Set "omnisharp.path": "latest" in user settings
Open an existing project c# project
Watch C# output window

## Expected Behavior ##
Successfully pull the latest omnisharp for windows.

## Actual Behavior ##
```
Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.32.12-beta.57...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.32.12-beta.57' Failed to download from https://roslynomnisharp.blob.core.windows.net/releases/1.32.12-beta.57/omnisharp-win-x64.zip. Error code '404')
Failed at stage: downloadAndInstallPackages
404
```
## Environment information ##

**VSCode version**: 1.32.3
**C# Extension**: 1.17.1

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.104\

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  1.1.9 [C:\Program Files\dotnet\sdk]
  1.1.11 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|autofilename|JerryHong|0.1.3|
|cpptools|ms-vscode|0.22.0|
|csharp|ms-vscode|1.17.1|
|csharpextensions|jchannon|1.3.0|
|debugger-for-chrome|msjsdiag|4.11.3|
|docomment|k--kato|0.1.6|
|dotenv|mikestead|1.0.1|
|dotnet-test-explorer|formulahendry|0.6.5|
|EditorConfig|EditorConfig|0.13.0|
|gitignore|codezombiech|0.6.0|
|gitlens|eamodio|9.5.1|
|jenkinsfile-support|secanis|0.1.0|
|PowerShell|ms-vscode|1.11.0|
|prettier-vscode|esbenp|1.8.1|
|python|ms-python|2019.2.5558|
|quicktype|quicktype|12.0.46|
|tslint|eg2|1.0.43|
|vscode-coverage-gutters|ryanluker|2.3.1|
|vscode-docker|PeterJausovec|0.6.1|
|vscode-eslint|dbaeumer|1.8.2|
|vscode-icons|vscode-icons-team|8.3.0|
|vscode-markdownlint|DavidAnson|0.25.0|
|vscode-react-native|vsmobile|0.9.0|
|vsliveshare|ms-vsliveshare|0.3.1326|
|vsliveshare-audio|ms-vsliveshare|0.1.48|
|webpack|jeremyrajan|2.1.3|;

</details>

**Comment by sunflowr** [comment]
Same issue here as well but osx

Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.32.12-beta.59...
Platform: darwin, x86_64

Downloading package 'OmniSharp for OSX, Version = 1.32.12-beta.59' Failed to download from https://roslynomnisharp.blob.core.windows.net/releases/1.32.12-beta.59/omnisharp-osx.zip. Error code '404')
Failed at stage: downloadAndInstallPackages
404

**Comment by Fubuchi** [comment]
#2834

**Comment by akshita31** [comment]
This is fixed now.
