### ISSUE TITLE
launchSettings.json is not being respected for ASP.NET Core Web API project

### ISSUE THREAD

**Issue by TAGC** [OmniSharp/omnisharp-vscode#2935]
## Issue Description ##

I'm cross-posting Microsoft/vscode#71007 to here as this may be a better place for it. To avoid duplication, I'll refer back to that issue instead of copy-pasting the text here. To summarise the problem: whenever I try to debug an ASP.NET Core web project in VS Code, the default launch settings are always used regardless of the changes I make under `Properties/launchSettings.json`.

## Steps to Reproduce ##

Refer to linked issue.

## Expected Behavior ##

Changes made under `launchSettings.json` are picked up when launching a debug session.

## Actual Behavior ##

On running the debug session, all the default launch settings are used regardless of what's configured in `launchSettings.json`.

### OmniSharp log ###

```
Starting OmniSharp server at 3/23/2019, 10:53:09 AM
    Target: /Users/davidfallah/Documents/VSCode/temp

OmniSharp server started with Mono 5.18.0.
    Path: /Users/davidfallah/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/OmniSharp.exe
    PID: 15505

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.14.3 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/usr/local/Cellar/mono/5.18.0.268/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/Users/davidfallah/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/usr/local/Cellar/mono/5.18.0.268/lib/mono/msbuild/15.0/bin"
            CscToolPath = /Users/davidfallah/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/davidfallah/Documents/VSCode/temp'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/davidfallah/Documents/VSCode/temp'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/davidfallah/Documents/VSCode/temp/temp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/davidfallah/Documents/VSCode/temp'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/davidfallah/Documents/VSCode/temp/temp.csproj
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/davidfallah/Documents/VSCode/temp' on host 15484.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/davidfallah/Documents/VSCode/temp/temp.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/davidfallah/Documents/VSCode/temp/temp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: temp
```

### C# log ###

No logs.

## Environment information ##

**VSCode version**: 1.32.3
**C# Extension**: 1.17.1

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.18.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.105/

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.200 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.500 [/usr/local/share/dotnet/sdk]
  2.2.103 [/usr/local/share/dotnet/sdk]
  2.2.105 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|better-toml|bungcip|0.3.2|
|code-runner|formulahendry|0.9.7|
|code-settings-sync|Shan|3.2.7|
|code-spell-checker|streetsidesoftware|1.6.10|
|cpptools|ms-vscode|0.22.1|
|csharp|ms-vscode|1.17.1|
|docomment|k--kato|0.1.6|
|gc-excelviewer|GrapeCity|2.1.29|
|gitlens|eamodio|9.5.1|
|gradle-language|naco-siren|0.2.3|
|Kotlin|mathiasfrohlich|1.7.0|
|language-julia|julialang|0.11.4|
|latex-workshop|James-Yu|6.2.2|
|linecount|yycalm|0.1.7|
|markdown-all-in-one|yzhang|2.1.1|
|plantuml|jebbs|2.10.7|
|python|ms-python|2019.2.5558|
|scala-lsp|dragos|0.2.3|
|sharppad|jmazouri|1.0.5|
|tslint|eg2|1.0.43|
|tslint-vue|prograhammer|1.5.6|
|vetur|octref|0.17.0|
|vscode-docker|PeterJausovec|0.6.1|
|vscode-icons|vscode-icons-team|8.3.0|
|vscode-markdownlint|DavidAnson|0.25.1|
|vsliveshare|ms-vsliveshare|0.3.1326|;

</details>

**Comment by gregg-miskelly** [comment]
@TAGC What part of launchSettings.json are you expecting to transfer over? Currently the only thing that the C# extension uses from launchSettings.json is `environmentVariables` and `applicationUrl`.

**Comment by TAGC** [comment]
Ah sorry, I was assuming that VS Code supported everything in that file, including `launchUrl` and `launchBrowser`.

What's the standard way to control the URL that the browser directs to when launched then? To modify the `.vscode/launch.json` file and change `launchBrowser.args` from `${auto-detect-url}` to something else e.g. `${auto-detect-url}/swagger`?

**Comment by gregg-miskelly** [comment]
Yup

**Comment by TAGC** [comment]
Fair enough, cheers.

**Comment by StevenLiekens** [comment]
So what's the equivalent now that `"launchBrowser"` is superseded by `"serverReadyAction"`? I can't get this to work at all. I tried `"serverReadyAction": { "uriFormat": "http://localhost:%s/swagger" }`.
