### ISSUE TITLE
Build error during preLaunchTask 'build'.

### ISSUE THREAD

**Issue by liamdawson** [OmniSharp/omnisharp-vscode#294]
Whenever I press F5 to debug an RC2 ASP.Net app, I get the following error in a bar along the top:

```
Build error has been detected during preLaunchTask 'build'.
```

with a 'Debug Anyway' and 'Close' option.

I encounter the issue every time.

Build outputs associated with this:

```
Project Project.Omega (.NETCoreApp,Version=v1.0) will be compiled because Input items removed from last build
Compiling Project.Omega for .NETCoreApp,Version=v1.0
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.3013499
```

```
Project Project.Omega (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
```

VS Code:

```
[Window Title]
Visual Studio Code - Insiders

[Main Instruction]
Visual Studio Code - Insiders

[Content]

Version 1.1.0-insider
Commit c212f0908f3d29933317bbc3233568fbca7944b1
Date 2016-05-09T13:09:51.092Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```

omnisharp-vscode package: `csharp-1.0.5-rc2.vsix`

In the project, I'm using `Microsoft.NETCore.App` version `1.0.0-rc2-3002700`.

Debug Anyway works, but it's a pain to have to click that every time.

**Comment by liamdawson** [comment]
Strangely enough, the issue stopped when I selected the (web) configuration in the debug tab, and I haven't been able to replicate it since.

**Comment by caslan** [comment]
I just ran into this myself. Changing the launch configuration didn't help for me though, restarting VS Code made the issue go away.

**Comment by gregg-miskelly** [comment]
If you run into this on Windows, please try using Process Monitor to check the exit from dotnet.exe. Then we can know if this is a bug in VS Code (they are claiming the task failed for no reason), or a bug in the .NET CLI (they are exiting with non-zero exit code on success).

**Comment by mellinoe** [comment]
I'm hitting the same issue. dotnet.exe is returning with exit code 0 according to Process Monitor.

![image](https://cloud.githubusercontent.com/assets/8918977/15158612/98e4de32-16a5-11e6-8361-d05c84d446cb.png)

![image](https://cloud.githubusercontent.com/assets/8918977/15158624/a37a5444-16a5-11e6-80fd-d43682fc9839.png)

![image](https://cloud.githubusercontent.com/assets/8918977/15158628/ab630142-16a5-11e6-8a99-ca1a5d4d4ce8.png)

**Comment by gregg-miskelly** [comment]
@mellinoe if you go to 'View->Errors and Warnings' does VS Code show you any errors?

This sounds like it might be -
https://github.com/Microsoft/vscode/issues/4987

**Comment by gregg-miskelly** [comment]
Looks like there is another active issue that also sounds the same: https://github.com/Microsoft/vscode/issues/4070

**Comment by mellinoe** [comment]
Hm, I'm not able to get a repro at this exact moment. If I hit this again i will check that panel.

**Comment by jchannon** [comment]
I had the same issue on OSX. Restarted after updating C# extension and the asset installtion and it went away

**Comment by DustinCampbell** [comment]
Has anyone seen this in awhile? It feels like this issue might be a bit stale.

**Comment by rajkumar42** [comment]
I have seen this issue with this repro https://github.com/OmniSharp/omnisharp-vscode/issues/352

**Comment by gregg-miskelly** [comment]
@rajkumar42 this bug tracks the scenario where VS Code claims that the build fails, but it actually succeeded. Is that what you saw?

**Comment by rajkumar42** [comment]
This behavior shows up on Windows only. In my case the build actually failed, it did not update the dlls. 

Its quiet different on mac, where it somehow creates a zero sized file.

**Comment by DustinCampbell** [comment]
Is this still a problem?

**Comment by damtur** [comment]
I'm having the exact same problem with version `1.10.2` ;(

**Comment by cihadsevim** [comment]
Same goes here.

**Comment by gregg-miskelly** [comment]
@damtur and @cihadsevim what OSs are you guys on? What version of VS Code do you have?

**Comment by cihadsevim** [comment]
@gregg-miskelly Windows 8

**Comment by gregg-miskelly** [comment]
@cihadsevim can you repro this problem regularly? If so, could you try running procmon to verify that indeed `dotnet` (or whatever process you are using to build with if you have something else configured) is returning a non-zero exit code? You should be able to get back speed by disabling almost all events in procmon and enabling the option to drop filtered out events.

**Comment by cihadsevim** [comment]
@gregg-miskelly still same mate.

**Comment by gregg-miskelly** [comment]
@cihadsevim sorry, I didn't mean to imply that procmon would fix the problem. I just wanted to confirm if the dotnet process was exiting with a zero exit code (meaning we should get the VS Code folks involved since this sounds like a VS Code bug) or a non-zero exit code (meaning we should get the .NET CLI folks involved). What was the exit code you saw?

**Comment by jajajames** [comment]
I got this error using Code for Mac today. I restarted Code as recommended above and ran Debug. I got a message about configuration not being setup correctly. Clicking yes, setup config, fixed it. Debugging now works.

**Comment by TheRealPiotrP** [comment]
Thanks @jajajames. I’m glad the extension fixed this for you. I’m closing the issue. If folks see similar symptoms then please open a new issue so we can see what’s happening on latest bits.
