### ISSUE TITLE
Add .NET tags to the C# extension

### ISSUE THREAD

**Issue by metoly** [OmniSharp/omnisharp-vscode#2942]
The C# extension name is not indicative for ASP.NET developers. When they search for: ASP.NET, .NET, .NET Core and dotnet, they get a bunch of other 3rd party extensions, but the C# extension doesn't appear in the first few pages in the list. We need to add tags for .NET Core and ASP.NET, so that it appears at the top of the list in these searches.

**Comment by rchande** [comment]
The tags have been added as of 1.18: https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp&ssr=true
