### ISSUE TITLE
Support dotnet watch as a launch target

### ISSUE THREAD

**Issue by metoly** [OmniSharp/omnisharp-vscode#2944]
Have tasks.json configured to use "dotnet watch" when a user initiates a "Start without debugging".

**Comment by gregg-miskelly** [comment]
Hi @metoly, in VS Code, start without debugging still involves the debugger, and aren't setup to start the app a completely different way.

**Comment by gregg-miskelly** [comment]
I should add - as of 1.18, the C# extension will automatically add a tasks.json task for starting "dotnet watch". So there is now an easy way to kick that off.
