### ISSUE TITLE
Error occured in loading omnisharp from omnisharp.path Could not start the server due to Error: The system could not find the specified path

### ISSUE THREAD

**Issue by nczsl** [OmniSharp/omnisharp-vscode#2949]
PS D:\work\netcorework> dotnet --info
.NET Core SDK（反映任何 global.json）:
 Version:   2.2.103
 Commit:    8edbc2570a

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.103\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.2.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

omnisharp  1.18.0

**Comment by nczsl** [comment]
when i installed other version (1.17.1)  then this issues is nothing

**Comment by rchande** [comment]
@nczsl Can you share your "C#" log?

**Comment by nczsl** [comment]
omnisharp log only show:
Error occured in loading omnisharp from omnisharp.path
Could not start the server due to Error: The system could not find the specified path
when vscode start time, or use omnisharp command in command board

**Comment by rchande** [comment]
@nczsl *C# log* please: 
![image](https://user-images.githubusercontent.com/3751401/55106076-46cc9680-508b-11e9-8ae0-d07db1b62154.png)

**Comment by nczsl** [comment]
that is empty, not exist any info

**Comment by akshita31** [comment]
@nczsl Could you try uninstalling and then reinstalling the extension. When you reinstall you should see a C# log

**Comment by nczsl** [comment]
that's no different, uninstall and install omnisharp C# log still no info

**Comment by akshita31** [comment]
@nczsl Does the .omnisharp folder exists in your .vscode/extensions/ms-vscode.csharp folder?

Could you try setting "omnisharp.path": "latest" and restarting vscode ?

**Comment by nczsl** [comment]
![新建位图图像 (5)](https://user-images.githubusercontent.com/5241693/56074814-3e928c00-5deb-11e9-87a6-8b896b98a2ac.jpg)

**Comment by nczsl** [comment]
![新建位图图像 (6)](https://user-images.githubusercontent.com/5241693/56074825-76013880-5deb-11e9-8c0b-c035d7fc5138.jpg)

**Comment by ponik** [comment]
@nczsl Same issue, In my case because I was setted Omnisharp.Path="absolute path" in vscode.
remove it the issue fixed.
VSCode->File->Preferences->Settings, Or press [Ctrl + ,] open settings panel, 
search omnisharp.path, click [Edit in settings.json] edit json directly, remove "Omnisharp.Path":"xxx" if it exists. Or correct it.

**Comment by nczsl** [comment]
> @nczsl Same issue, In my case because I was setted Omnisharp.Path="absolute path" in vscode.
> The problem was fixed after remove it.
> VSCode->File->Preferences->Settings, Or press [Ctrl + ,] open settings panel,
> search omnisharp.path, click [Edit in settings.json] edit json directly, remove "Omnisharp.Path":"xxx" if it exists. Or correct it.

![image](https://user-images.githubusercontent.com/5241693/58763173-1a9d2c80-858a-11e9-8a2f-7ee6c0fb506c.png)
no use

**Comment by Apollodotnet** [comment]
hello can someone help me please im having this same issue

**Comment by nczsl** [comment]
> hello can someone help me please im having this same issue

I don't know how to solve this problem. Later, I didn't care about it, I didn't use vscode for C# development, and I didn't care about this problem ，because  i use vs 2019. Now I've reinstalled the system for many times.I don't know if this problem still exists in my vscode, As a digression, I use vscode to do typescript, which is really great, very good :)

**Comment by Apollodotnet** [comment]
well i fixed my issue my going to extensions and actually enabling the c# extension and then boom everything started working lol

**Comment by AlexandrVD** [comment]
I spent a lot of time trying to solve this problem, and the solution for me turned out to be simple - revert C# latest update:
1.  Open "Extensions" (Ctrl+Shift+X);
2. Click on "gear" icon for the "C#" extension;
3. Select "Install Another Version..."
4. Select previous version ("1.23.2" - works for me)
<img width="677" alt="3" src="https://user-images.githubusercontent.com/1384331/96355330-1e7f0f80-10e9-11eb-8e6f-0772039eb94e.png">

**Comment by calincorcotoi** [comment]
> I spent a lot of time trying to solve this problem, and the solution for me turned out to be simple - revert _C#_ latest update:
> 
> 1. Open "Extensions" (_Ctrl+Shift+X_);
> 2. Click on "gear" icon for the "_C#_" extension;
> 3. Select "_Install Another Version..._"
> 4. Select previous version ("_1.23.2_" - works for me)
> 
> <img alt="3" width="677" src="https://user-images.githubusercontent.com/1384331/96355330-1e7f0f80-10e9-11eb-8e6f-0772039eb94e.png">

not working... :/

**Comment by hansusername** [comment]
I recently started coding in VSCode and had the same problem. I had the same problem but when I left path empty it works for me. Then omnisharp chooses the folder i have open in VSCode. 
cut from settings.json --> "omnisharp.path": "",
