### ISSUE TITLE
VS Code extension: Add support for Function Breakpoints

### ISSUE THREAD

**Issue by dougbu** [OmniSharp/omnisharp-vscode#295]
The VS Code "function breakpoints" feature does not seem to work when using the OmniSharp-based C# extension ([v1.0.5-rc2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.0.5-rc2)). Or, if the feature works, the obvious syntax doesn't. This might be a fine feature gap except the failure is silent -- no warning is shown that the enabled breakpoint is invalid. For example none of the `Main` breakpoints are hit with the setup below. Same thing goes for non-`static` methods.
![main](https://cloud.githubusercontent.com/assets/6431421/15133329/9c4da1a6-1616-11e6-9e94-984085422284.png)

**Comment by gregg-miskelly** [comment]
I opened #296 to track the lack of warning. We can use this to track the feature request for function breakpoint support.

**Comment by dougbu** [comment]
:+1: wfm

**Comment by loligans** [comment]
Any updates on this functionality? I'm curious and might try my hand at it. How difficult would it be to implement this functionality?

**Comment by gregg-miskelly** [comment]
@loligans [Sorry for the delay, I am returning from parental leave] the debug adapter used by this extension isn't open source, and this feature can't really be implemented outside of it. So this can only be implemented by a Microsoft engineer.

**Comment by azydevelopment** [comment]
I just ran into this issue. Kinda annoying if I want to break on a function that isn't my own as well like you can in WinDbg.

**Comment by gregg-miskelly** [comment]
Fixed by https://github.com/OmniSharp/omnisharp-vscode/pull/4091

**Comment by dougbu** [comment]
Thanks @WardenGnaw and @gregg-miskelly❕
