### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mkt** [OmniSharp/omnisharp-vscode#2951]
- Issue Type: `Performance`
- Extension Name: `csharp`
- Extension Version: `1.17.1`
- OS Version: `Linux x64 4.4.0-142-generic`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/mkt/ms-vscode.csharp-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mkt** [comment]
#2946 seemds same issue.

**Comment by akshita31** [comment]
@mkt Does this issue come up with the version 1.18.0 as well ?

**Comment by mkt** [comment]
After updating ms-vscode.csharp 1.18.0, this issue has not occurred. 
Thanks.

**Comment by mkt** [comment]
@akshita31 After updating ms-vscode.csharp 1.18.0, this issue has not occurred. Thanks.

**Comment by akshita31** [comment]
@mkt Gald you got it working. Thanks!
