### ISSUE TITLE
The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?) [Blazor] [14, 30]

### ISSUE THREAD

**Issue by mammadkoma** [OmniSharp/omnisharp-vscode#2955]
I have installed these dotnet cores :
2.1.505 [C:\Program Files\dotnet\sdk]
2.2.101 [C:\Program Files\dotnet\sdk]
2.2.105 [C:\Program Files\dotnet\sdk]
3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]

I created a blazor project named Blazor. project builds and run by command or powershell correctly. but when open project folder by vs code it shows an error in PROBLEMS window :
The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?) [Blazor] [14, 30]
![image](https://user-images.githubusercontent.com/17564001/55254764-6542b580-5276-11e9-9e87-046086e110d3.png)
vs code version : 1.32.3
c# version : 1.18.0

OUTPUT window : 

Starting OmniSharp server at 3/29/2019, 10:37:20 PM
    Target: d:\MyProjects\Core\Blazor

OmniSharp server started.
    Path: C:\Users\mammadkoma\.vscode\extensions\ms-vscode.csharp-1.18.0\.omnisharp\1.32.11\OmniSharp.exe
    PID: 5272

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Enterprise 2017 15.9.28307.557 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\mammadkoma\.vscode\extensions\ms-vscode.csharp-1.18.0\.omnisharp\1.32.11\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Enterprise 2017 15.9.28307.557 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\MyProjects\Core\Blazor'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'd:\MyProjects\Core\Blazor'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\MyProjects\Core\Blazor\Blazor.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\MyProjects\Core\Blazor'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\MyProjects\Core\Blazor\Blazor.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\MyProjects\Core\Blazor' on host 4292.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\MyProjects\Core\Blazor\Blazor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\MyProjects\Core\Blazor\Blazor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Blazor

**Comment by akshita31** [comment]
@NTaylorMullen Is this something related to razor extension ?

**Comment by NTaylorMullen** [comment]
Yup, absolutely is, thanks @akshita31!

@mammadkoma that's a current limitation of the VSCode Razor experience. We're adding support for Blazor in the next release which should be this month. Stay tuned!

**Comment by mammadkoma** [comment]
Flutter from google works and run with microsoft vscode correctly.
But blazor from microsoft don't work and run (f5) with microsoft vscode.

**Comment by mammadkoma** [comment]
This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the marketplace for VS Code. See also our issue reporting guidelines.

Happy Coding!

https://github.com/Microsoft/vscode/issues/72701#event-2290677751

**Comment by smjltd** [comment]
same issue anyone know how to resolve it?

**Comment by noamichael** [comment]
@smjltd I was having the same issue. It turns out that my `dotnet` cli was outdated. I grabbed the [latest preview build from here](https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview4-download.md) and the app worked after installation when I ran `dotnet run` in the project's root directory.

**Comment by moboer** [comment]
@noamichael thank you

**Comment by elishnevsky** [comment]
2 years later and I still have this issue with .NET 5.0 and the latest version of VS Code and C# extension. Is there a solution?
