### ISSUE TITLE
Omnisharp suddenly stopped working (can't download or start?)

### ISSUE THREAD

**Issue by davidlfox** [OmniSharp/omnisharp-vscode#2956]
## Issue Description ##
OmniSharp doesn't load/start correctly. Pretty sure I haven't changed anything recently.

## Steps to Reproduce ##
dotnet new console -o newconsole
cd newconsole
code .
attempt to run console
I've tried reinstalling after deleting the ms-vscode.csharp extension path

## Expected Behavior ##
hit f5, print "Hello, world"

## Actual Behavior ##
see logs below. doesn't seem like VS Code can download Omnisharp and/or start it.

### OmniSharp log ###
<details>Starting OmniSharp server at 4/1/2019, 1:19:08 AM
    Target: /Users/david/Repos/newconsole

OmniSharp server started with Mono 5.16.0.
    Path: /Users/david/.vscode/extensions/ms-vscode.csharp-1.18.0/.omnisharp/1.32.12-beta.59/omnisharp/OmniSharp.exe
    PID: 58810

Cannot open assembly '/Users/david/.vscode/extensions/ms-vscode.csharp-1.18.0/.omnisharp/1.32.12-beta.59/omnisharp/OmniSharp.exe': No such file or directory.
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).</details>

### C# log ###
<details>Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.32.12-beta.59...
Platform: darwin, x86_64

Downloading package 'OmniSharp for OSX, Version = 1.32.12-beta.59' Failed to download from https://roslynomnisharp.blob.core.windows.net/releases/1.32.12-beta.59/omnisharp-osx.zip. Error code '404')
Failed at stage: downloadPackage
404</details>

## Environment information ##

**VSCode version**: 1.32.3
**C# Extension**: 1.18.0

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.16.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.101/

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  1.0.0-preview2-1-003177 [/usr/local/share/dotnet/sdk]
  1.0.3 [/usr/local/share/dotnet/sdk]
  1.1.11 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.403 [/usr/local/share/dotnet/sdk]
  2.1.503 [/usr/local/share/dotnet/sdk]
  2.2.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.0|
|csharp|ms-vscode|1.18.0|
|githistory|donjayamanne|0.4.6|
|gitignore|codezombiech|0.6.0|
|htmltagwrap|bradgashler|0.0.7|
|mssql|ms-mssql|1.5.0|
|python|ms-python|2019.3.6215|
|vscode-azureappservice|ms-azuretools|0.13.0|
|vscode-azurefunctions|ms-azuretools|0.16.0|
|vscode-peacock|johnpapa|2.0.0|;

</details>

**Comment by davidlfox** [comment]
update:
- updated mono to 5.18.1.0 and restarted **no change**
- downloaded omnisharp manually and extracted to ~/Downloads/omnisharp, then set vs code settings `omnitsharp.path` to `/Users/david/Downloads/omnisharp-osx/omnisharp/Omnisharp.exe` and dotnet'ed a new console **worked but why? not a permanent solution, im sure**

something like this (not sure of exact logs) has happened several times on my box. sometimes it's a different behavior when i run `code .` from terminal and when i use launchpad. **what are the core path requirements to check when i run into these kinds of issues???**

**Comment by akshita31** [comment]
@davidlfox From your logs it seems that the download of omnisharp.latest failed hence it was not able to start omnisharp. Could you try unsetting "omnisharp.path" so that the default omnisharp version is used ?

**Comment by davidlfox** [comment]
@akshita31 before i modified it to the path, it was set to "latest" but i didn't make that change. removing that line altogether seems to have worked. how did it get set to "latest"?

**Comment by akshita31** [comment]
@davidlfox, As far as I know, there is no code to set that config option automatically

**Comment by akshita31** [comment]
@davidlfox Since the problem seems resolved I will close this issue now. Please reopen if the problem reoccurs.
