### ISSUE TITLE
Support for Nullable Reference Types

### ISSUE THREAD

**Issue by trampster** [OmniSharp/omnisharp-vscode#2957]
Issue Type: <b>Bug</b>

Add 

     <NullableReferenceTypes>true</NullableReferenceTypes> 

to project file.

1. Use a object without initliazing it. 
2. Build using dotnet build.
-> Expected a build warning
Instead got Build succeeded
    0 Warning(s)
    0 Errors(s)

This closed issue https://github.com/OmniSharp/omnisharp-vscode/issues/2839, says it was available in the beta but I now have the release and it is either missing, or not working.

Extension version: 1.18.0
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 2910)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.77GB (1.36GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by shoe-diamente** [comment]
I have the same problem. Even specifying:

```
"omnisharp.path": "latest",
```

in the extension settings in VS Code I'm unable to get nullable reference types to work.

**Comment by filipw** [comment]
it was closed because it was shipped and verified 😀

can you please provide a repro project?

**Comment by shoe-diamente** [comment]
Sure, just do:

```
dotnet new webapi -o Test
cd Test
```

then make sure you have the latest .NET Core 3 preview installed.
Then go in the project settings and make sure they look like this:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

</Project>
```

Finally add anywhere in the code (I've tried in the controller's actions):

```c#
string? x = null;
```

You'll see this:

![Screen Shot 2019-07-31 at 16 45 45](https://user-images.githubusercontent.com/40760781/62221866-ac6ebd80-b3b2-11e9-8351-2abdb23fd538.png)

**Comment by filipw** [comment]
Ah I see. The `<Nullable>enable</Nullable>` is new only from Visual Studio 16.2 onwards. 
In OmniSharp for now you still need to use the "old" (VS 16.0-16.2) syntax `<NullableContextOptions>enable</NullableContextOptions>`

**Comment by shoe-diamente** [comment]
Adding that seems to fix it, thanks.

**Comment by imba-tjd** [comment]
@filipw How about adding this to backlog and known issues?
