### ISSUE TITLE
Could not find the task 'build'

### ISSUE THREAD

**Issue by 0xAlex** [OmniSharp/omnisharp-vscode#2959]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.105\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.2.105 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

VS Code version: 1.32.3
C# Extension version: 1.18.0

## Steps to reproduce
1 Open up the terminal
2 type in "dotnet new console"
3 Press F5, and the launch.json will pop up
4 Press F5 again

## Expected  behavior
Terminal displaying "Hello World!"

## Actual behavior
The dialog box "Could not find the task 'build'" pops up and when I click Configure Task, a message on the right above the VSCode status bar saying "this.runConfigureTasks" is not a function

![Screenshot 1](https://user-images.githubusercontent.com/49193469/55404661-fffb0700-558a-11e9-98f3-0ec0a2d122de.png)

![Screenshot2](https://user-images.githubusercontent.com/49193469/55404732-215bf300-558b-11e9-86c3-17067cb59f8a.png)

**Comment by gregg-miskelly** [comment]
The bug you are running into is a VS Code problem: https://github.com/Microsoft/vscode/issues/70292

However, you also should use the C# extension's generator for launch.json and tasks.json. You can run ' .NET: Generate Assets for Build and Debug' from the VS Code command pallet to force the generator to run. See [here](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md#3-add-vs-code-configuration-files-to-the-workspace) for more information.

**Comment by Designizm** [comment]
**I have like it the problem.. When i click start it F5  :( I cant it install flutter emulator.. .Thanks.**
![Hata](https://user-images.githubusercontent.com/60859619/80843298-9c6b5f00-8c0c-11ea-84b9-11ef92ca66f0.png)

**Comment by JoeRobich** [comment]
@Designizm Sorry you are running into issues with VS Code. This repo and issues are for the C# extension. It looks like you are having trouble working with Dart without having Node installed. I think you should install Node or if it is already installed then ensure that the install folder is listed in your PATH environment variable. If you still have issues or questions then this project might be a better repo to ask in https://github.com/Dart-Code/Dart-Code. Good Luck!

**Comment by Designizm** [comment]
Thanks for all. God bless you.Respects.

Joey Robichaud <notifications@github.com>, 5 May 2020 Sal, 00:04 tarihinde
şunu yazdı:
