### ISSUE TITLE
Debugger should warn if function breakpoints are set

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#296]
This is copied from #295 -- when setting a function breakpoint, there is no good indication that these aren't supported.

**Comment by wesrupert** [comment]
There's no actionable event on our side. Looks like VS Code respects our `supportsFunctionBreakpoints: false` only on the protocol-level, not in the UI. Created [Issue #9099](https://github.com/Microsoft/vscode/issues/9099) on their side, closing here.
