### ISSUE TITLE
Failed at stage: downloadPackage

### ISSUE THREAD

**Issue by manojbavikati** [OmniSharp/omnisharp-vscode#2960]
Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' 	Retrying from 'https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.32.11.zip' Failed at stage: downloadPackage
Error: write EPROTO 10912:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:d:\_vsts\3\s\vendor\node\deps\openssl\openssl\ssl\record\ssl3_record.c:252:

I was able to download the zip file at URL without any issues.. so i am sure its not firewall issue or proxy issue. Any other help is appreciated. 

Thank you.

**Comment by akshita31** [comment]
@manojbavikati I am not sure what the error is here. Could you download the package and unzip the binaries in the \.vscode\extensions\ms-vscode.csharp-1.18.0\.omnisharp\1.32.11 folder and see if it works?

**Comment by manojbavikati** [comment]
Yes, i already did that and still it will try again to download the package for some reason and fails. 

I have also updated the Ominisharp.path in my VS Code to where the ominisharp.exe exist.

**Comment by akshita31** [comment]
@manojbavikati I can explain what might be happening here. When we download a dependency, if the download and install succeed, we place a file named install.Lock  in the package folder and on all subsequent activations of the extension, we check if that file is present and if not we try to download it.
So I think your problem will be resolved if you place an install.Lock file in the .omnisharp/1.32.11 folder.

**Comment by akshita31** [comment]
@manojbavikati Since we havent heard back from you I will close this issue now. Please feel free to reopen if the problem persists

**Comment by manojbavikati** [comment]
I can copy the files manually but then it tries to download the .debugger and .razor and other folders that have the same issue

**Comment by akshita31** [comment]
You just need to create an empty file called install.Lock in the folder where you are putting the payloads.
