### ISSUE TITLE
Unity: The msbuild is pointed to the wrong place and the Assembly files aren't being updated

### ISSUE THREAD

**Issue by MattTheCrow** [OmniSharp/omnisharp-vscode#2964]
Starting OmniSharp server at 4/4/2019, 3:37:41 PM
    Target: e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Covens.sln

OmniSharp server started.
    Path: C:\Users\Sol\.vscode\extensions\ms-vscode.csharp-1.18.0\.omnisharp\1.32.11\OmniSharp.exe
    PID: 8292

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2017 15.9.28307.586 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\Sol\.vscode\extensions\ms-vscode.csharp-1.18.0\.omnisharp\1.32.11\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2017 15.9.28307.586 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Covens.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp-firstpass.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp-Editor-firstpass.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens' on host 17900.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin" directory.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp.csproj'.
e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp.csproj
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1657,5): Error: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin" directory.

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp-firstpass.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp-firstpass.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp-firstpass.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp-Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin" directory.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp-Editor.csproj'.
e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp-Editor.csproj
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1657,5): Error: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin" directory.

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp-Editor-firstpass.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin" directory.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp-Editor-firstpass.csproj'.
e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp-Editor-firstpass.csproj
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1657,5): Error: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin" directory.

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-firstpass
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp-Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: e:\RainCrowStuff\Covens\ReleaseCovensNOW\CovensUnity\Covens\Assembly-CSharp-Editor-firstpass.csproj

**Comment by akshita31** [comment]
This is the main error I think:

> The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin" directory.
[warn]: OmniSharp.MSBuild.ProjectManager


We recently hit this bug and a fix https://github.com/OmniSharp/omnisharp-roslyn/pull/1457 has been merged. Could you try setting "omnisharp.path" : "1.32.17" and restarting omnisharp ?

**Comment by cartermp** [comment]
The fix to this is merged.
