### ISSUE TITLE
Segfault when debugging netcore3 preview 4 on macOS

### ISSUE THREAD

**Issue by tn-5** [OmniSharp/omnisharp-vscode#2968]
Developing using VSCode with netcore3 (preview versions) worked ok up to preview 3. 

With the current  nighly builds of preview 4 omnisharp debugger crashes on startup with "Segmentation fault: 11"

## Steps to Reproduce ##

Install nightly netcore3 preview 4. Create new project from template "dotnet new razorcomponent". Open in VSCode, add debug configuration and select "start debugging".

## Expected Behavior ##

Build & start debugging

## Actual Behavior ##

Build ok, but immediately exists. Runing vsdbg-ui with console logging and setting debug server to 4711 shows up segmentation fault on startup.

### OmniSharp log ###
>> accepted connection from client
-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-gb"},"type":"request","seq":1}
<- (R) {"seq":0,"type":"response","request_seq":1,"success":true,"command":"initialize","message":"","body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":false,"supportsConditionalBreakpoints":true,"supportsHitConditionalBreakpoints":true,"supportsEvaluateForHovers":true,"exceptionBreakpointFilters":[{"filter":"all","label":"All Exceptions","default":false},{"filter":"user-unhandled","label":"User-Unhandled Exceptions","default":true}],"supportsSetVariable":true,"supportsGotoTargetsRequest":true,"supportsModulesRequest":true,"additionalModuleColumns":[],"supportedChecksumAlgorithms":["MD5","SHA1","SHA256"],"supportsExceptionOptions":true,"supportsValueFormattingOptions":true,"supportsExceptionInfoRequest":true,"supportTerminateDebuggee":true,"supportsSetExpression":true,"supportsExceptionConditions":true,"supportsDebuggerProperties":true,"supportsSetSymbolOptions":true}}
-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-gb"},"type":"request","seq":1}
-> (C) {"command":"launch","arguments":{"debugServer":4711,"logging":{"engineLogging":false},"name":".NET Core Launch (web)","type":"coreclr","request":"launch","preLaunchTask":"build","program":"/Users/thysnel/Documents/Projects/PRP/x3/bin/Debug/netcoreapp3.0/x3.dll","args":[],"cwd":"/Users/thysnel/Documents/Projects/PRP/x3","stopAtEntry":false,"launchBrowser":{"enabled":true},"env":{"ASPNETCORE_ENVIRONMENT":"Development","ASPNETCORE_URLS":"https://localhost:5001;http://localhost:5000"},"sourceFileMap":{"/Views":"/Users/thysnel/Documents/Projects/PRP/x3/Views"},"internalConsoleOptions":"openOnSessionStart","__sessionId":"5735cefd-8040-424e-9ff2-f080722c1942"},"type":"request","seq":2}
<- (E) {"seq":3,"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n"}}
<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"launch"}
<- (E) {"seq":5,"type":"event","event":"initialized","body":{}}
-> (C) {"command":"setExceptionBreakpoints","arguments":{"filters":["user-unhandled"]},"type":"request","seq":4}
<- (R) {"seq":6,"type":"response","request_seq":4,"success":true,"command":"setExceptionBreakpoints"}
-> (C) {"command":"configurationDone","type":"request","seq":5}
<- (E) {"seq":7,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/ProcessCreate","data":{"VS.Diagnostics.Debugger.vsdbg.Distribution.Version":"18.5.0","VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"Darwin","VS.Diagnostics.Debugger.vsdbg.Version":"16.0.20314.3 commit:3802a5f17cc32370f3dd7a5feb53b3238404221b","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Darwin"}}}
<- (E) {"seq":8,"type":"event","event":"process","body":{"name":"/Users/thysnel/Documents/Projects/PRP/x3/bin/Debug/netcoreapp3.0/x3.dll","systemProcessId":64442,"isLocalProcess":true,"startMethod":"launch"}}
<- (E) {"seq":9,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/Launch","data":{"VS.Diagnostics.Debugger.vsdbg.Launch.Duration":105,"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr","VS.Diagnostics.Debugger.vsdbg.SourceFileMappings":1,"VS.Diagnostics.Debugger.vsdbg.Version":"16.0.20314.3 commit:3802a5f17cc32370f3dd7a5feb53b3238404221b","VS.Diagnostics.Debugger.vsdbg.VisualizerFileUsed":false,"VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"Darwin","VS.Diagnostics.Debugger.vsdbg.Distribution.Version":"18.5.0","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Darwin"}}}
<- (R) {"seq":10,"type":"response","request_seq":5,"success":true,"command":"configurationDone"}
-> (C) {"command":"threads","type":"request","seq":6}
<- (R) {"seq":11,"type":"response","request_seq":6,"success":true,"command":"threads","message":"","body":{"threads":[]}}
Segmentation fault: 11

## Environment information ##

**VSCode version**: 1.33.0
**C# Extension**: 1.18.0

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.18.1</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-011070
 Commit:    219089e762

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview4-011070/

Host (useful for support):
  Version: 3.0.0-preview4-27604-05
  Commit:  681b17c849

.NET Core SDKs installed:
  2.1.504 [/usr/local/share/dotnet/sdk]
  2.2.105 [/usr/local/share/dotnet/sdk]
  3.0.100-preview3-010431 [/usr/local/share/dotnet/sdk]
  3.0.100-preview4-011031 [/usr/local/share/dotnet/sdk]
  3.0.100-preview4-011070 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19180-01 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19202-03 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19204-02 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27601-05 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27602-07 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27604-05 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cortex-debug|marus25|0.2.3|
|cpptools|ms-vscode|0.22.1|
|csharp|ms-vscode|1.18.0|
|gitlens|eamodio|9.5.1|
|hex-fmt|keroc|1.0.0|
|java|redhat|0.42.1|
|mssql|ms-mssql|1.5.0|
|plantuml|jebbs|2.10.9|
|python|ms-python|2019.3.6352|
|svn-scm|johnstoncode|1.47.12|
|vscode-eslint|dbaeumer|1.8.2|
|vscode-html-css|ecmel|0.2.0|
|vscode-java-debug|vscjava|0.17.0|
|vscode-java-dependency|vscjava|0.4.0|
|vscode-java-pack|vscjava|0.6.0|
|vscode-java-test|vscjava|0.15.1|
|vscode-maven|vscjava|0.16.0|
|vscodeintellicode|VisualStudioExptTeam|1.1.5|
|xml|DotJoshJohnson|2.4.0|;

</details>

**Comment by gregg-miskelly** [comment]
I will try to debug this tomorrow. If you have time can you see if there is additional information in OS crash log? -- https://github.com/OmniSharp/omnisharp-vscode/wiki/Diagnosting-%27Debug-adapter-process-has-terminated-unexpectedly%27#macos

**Comment by tn-5** [comment]
Info from os log:

Crashed Thread:        16

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY


Thread 16 Crashed:
0   libsystem_kernel.dylib        	0x00007fff6f30b23e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff6f3c1c1c pthread_kill + 285
2   libsystem_c.dylib             	0x00007fff6f2741c9 abort + 127
3   libsystem_malloc.dylib        	0x00007fff6f3836e2 malloc_vreport + 545
4   libsystem_malloc.dylib        	0x00007fff6f3834a3 malloc_report + 152
5   libvsdbg.dylib                	0x0000000105e5a501 CProtocolMainLoop::Release() + 33
6   libvsdbg.dylib                	0x0000000105e5c9b5 ATL::CComPtr<CProtocolMainLoop>::~CComPtr() + 21
7   libsystem_c.dylib             	0x00007fff6f274ef2 __cxa_finalize_ranges + 351
8   libsystem_c.dylib             	0x00007fff6f2751de exit + 55
9   libcoreclr.dylib              	0x000000010352459d PROCEndProcess(void*, unsigned int, int) + 221
10  libcoreclr.dylib              	0x00000001035244af ExitProcess + 143
11  libcoreclr.dylib              	0x0000000103719879 EEPolicy::ExitProcessViaShim(unsigned int) + 9
12  libcoreclr.dylib              	0x0000000103719841 SafeExitProcess(unsigned int, int, ShutdownCompleteAction) + 497
13  libcoreclr.dylib              	0x000000010351ed52 CorUnix::TerminationRequestHandlingRoutine(void*) + 18
14  libcoreclr.dylib              	0x00000001035274c8 CorUnix::CPalThread::ThreadEntry(void*) + 328
15  libsystem_pthread.dylib       	0x00007fff6f3bf305 _pthread_body + 126
16  libsystem_pthread.dylib       	0x00007fff6f3c226f _pthread_start + 70
17  libsystem_pthread.dylib       	0x00007fff6f3be415 thread_start + 13

Thread 16 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000070000edd8000  rcx: 0x000070000edd7ab8  rdx: 0x0000000000000000
  rdi: 0x0000000000001f0b  rsi: 0x0000000000000006  rbp: 0x000070000edd7af0  rsp: 0x000070000edd7ab8
   r8: 0x0000000000000000   r9: 0x000070000edd7a10  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x0000000000001f0b  r13: 0x0000000103415000  r14: 0x0000000000000006  r15: 0x000000000000002d
  rip: 0x00007fff6f30b23e  rfl: 0x0000000000000206  cr2: 0x0000000103592000
  
Logical CPU:     0
Error Code:      0x02000005
Trap Number:     133

**Comment by gregg-miskelly** [comment]
Unfortunately that is crash is part of shutdown, so while it is a bug, it isn't the bug you are running into.

I am trying to see if I can reproduce this problem on my machine. What build of .NET Core are you using?

**Comment by gregg-miskelly** [comment]
I was able to reproduce this with 3.0.100-preview4-011077.

**Comment by gregg-miskelly** [comment]
Here is the problem:
```
 * frame #0: 0x000000019c7d4eb3 libmscordaccore.dylib`CorUnix::InternalCreateEvent(CorUnix::CPalThread*, _SECURITY_ATTRIBUTES*, int, int, char16_t const*, void**) + 115
    frame #1: 0x000000019c7d4ff4 libmscordaccore.dylib`CreateEventW + 84
    frame #2: 0x000000019c408051 libmscordbi.dylib`CordbRCEventThread::Init() + 33
    frame #3: 0x000000019c41cd0a libmscordbi.dylib`Cordb::Initialize() + 106
    frame #4: 0x000000019bdea629 libvsdebugeng.impl.dylib`ManagedDM::CCoreClrAttachRequest::AttachToCoreClrProcessImpl(this=0x0000000100d180d0, pCorDebug=0x0000000100b30638) + 953 at CoreClrAttachRequest.h:155
    frame #5: 0x000000019bddaa0e libvsdebugeng.impl.dylib`ManagedDM::CCoreClrAttachRequest::AttachToCoreClrProcess(pCordb=0x0000000100b30638, pArg=0x0000000100d180d0, hrRuntimeLoaded=0) + 286 at CoreClrAttachRequest.h:87
    frame #6: 0x000000019c2cf438 libdbgshim.dylib`RuntimeStartupHelper::InvokeStartupCallback(char*, void*) + 712
    frame #7: 0x000000019c329355 libdbgshim.dylib`PAL_RuntimeStartupHelper::InvokeStartupCallback() + 229
    frame #8: 0x000000019c32910c libdbgshim.dylib`PAL_RuntimeStartupHelper::StartupHelperThread() + 140
    frame #9: 0x000000019c32904e libdbgshim.dylib`StartupHelperThread(void*) + 14
    frame #10: 0x000000019c32a5f8 libdbgshim.dylib`CorUnix::CPalThread::ThreadEntry(void*) + 328
    frame #11: 0x00007fff5f2ea6c1 libsystem_pthread.dylib`_pthread_body + 340
    frame #12: 0x00007fff5f2ea56d libsystem_pthread.dylib`_pthread_start + 377
    frame #13: 0x00007fff5f2e9c5d libsystem_pthread.dylib`thread_start + 13
```

I will port this issue to the CoreCLR repo

**Comment by gregg-miskelly** [comment]
This is now tracked with https://github.com/dotnet/coreclr/issues/23773
