### ISSUE TITLE
Improve the cshtml editor

### ISSUE THREAD

**Issue by idarous** [OmniSharp/omnisharp-vscode#297]
Hello,

I've tried visual studio code on an ASP.net 5 project and when editing a view file (cshtml), I don't find how to have autocompletion, refactoring, find reference, ect on static typed variable. However, these features are available on Visual Studio 2015.

Please, can you improve the support for cshtm file.

Thank you :)

**Comment by DustinCampbell** [comment]
We would definitely like to add editing for Razor files at some point. We're tracking that with #168.
