### ISSUE TITLE
Custom NuGet package sources ignored during C# project load

### ISSUE THREAD

**Issue by emuslor** [OmniSharp/omnisharp-vscode#2971]
## Issue Description ##
I can't figure out how to get OmniSharp to look in all of my currently configured machine-wide NuGet sources.  I'm not sure if this is a bug or just something I have not done properly.  I have seen other logs online where customized sources ARE checked for dependencies, so I expect there's a way to make it work.

## Steps to Reproduce ##
Added a third, on-premise package source via Visual Studio's Options->NuGet Package Manager Settings, in addition to the existing Microsoft Visual Studio Offline Packages and nuget.org sources.  All 3 are available, and Visual Studio is able to use the new source (let's call it "privatenuget").

## Expected Behavior ##
When I open a directory in VS Code containing C# projects, I expect all 3 sources (Microsoft Visual Studio Offline Packages, nuget.org, and privatenuget) to be searched for loading NuGet dependencies.

## Actual Behavior ##
Only the original two sources (Microsoft Visual Studio Offline Packages and nuget.org) are searched, so private packages are not found.  I have reloaded VS Code, rebooted the system, and also uninstalled/cleaned/reinstalled the OmniSharp Extension.

### OmniSharp log ###
<details>c:\Workspaces\PrivateRepo\Private.Project\Private.Project.csproj(0,0): Error: Unable to find package Private.Common. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org</details>

### C# log ###
<details>Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (31766 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'

Downloading package '.NET Core Debugger (Windows / x64)' (47921 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (Windows / x64)'

Downloading package 'Razor Language Server (Windows / x64)' (47276 KB).................... Done!
Installing package 'Razor Language Server (Windows / x64)'

Finished</details>

## Environment information ##

**VSCode version**: 1.33.0
**C# Extension**: 1.18.0

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.1.602
 Commit:    04475eb7cf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.602\

Host (useful for support):
  Version: 2.1.9
  Commit:  dcedc87d22

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azurecli|ms-vscode|0.4.4|
|code-settings-sync|Shan|3.2.8|
|cpptools|ms-vscode|0.22.1|
|csharp|ms-vscode|1.18.0|
|language-x86-64-assembly|13xforever|2.2.11|
|powershell|ms-vscode|1.12.0|
|python|ms-python|2019.3.6352|
|vscode-docker|PeterJausovec|0.6.1|;

</details>

**Comment by rchande** [comment]
@emuslor What happens if you `dotnet restore` your project before you open it in vs code?

**Comment by emuslor** [comment]
@rchande Restore completes successfully.  Then when I re-open vs code, there are no errors from omnisharp.  I would simply do this all the time, but I'm dealing with a source tree containing a lot of directories full of project with frequently changing dependencies, so the ability to auto-traverse that tree and successfully restore deps with omnisharp when I open vs code would be quite useful.

**Comment by rchande** [comment]
@emuslor The C# extension has 2 commands ".NET: Restore All Projects" and ".NET Restore Project" (which will let you select a project) that should do what you need---they'll invoke `dotnet restore` on your behalf for the requested projects.

**Comment by emuslor** [comment]
@rchande Thanks.  Is there a way to make that happen recursively for all projects in a tree?  It seems like it tries to do that, but it stops at the first subdirectory that it finds projects in.  For example, say my repo tree looks like this:

Myproject/
-- Projdir1/
---- a/
------ a.csproj
---- b/
------ b.csproj
-- Projdir2/
---- c/
------ c.cspoj
---- d/
------ d.csproj

If I open the Myproject directory in VS Code and then do a .NET: Restore All Projects, it restores for a.csproj and b.csproj.  Those are also the only choices when I do a .NET: Restore Project.  c and d are ignored.

**Comment by rchande** [comment]
@emuslor Do you have a .sln file that only includes some of the projects? You can choose what the target sln/csproj is using the selector next to the green flame icon in the lower left.

**Comment by emuslor** [comment]
@rchande Indeed.  So I guess I just need to select each sln and do the restore all for each.  Any way to do them all at once without combining into an uber sln?

**Comment by rchande** [comment]
@emuslor We don't provide a way to do that. Out of curiosity, why do you have solutions that don't contain all of the projects in the project reference dependency graph?

**Comment by emuslor** [comment]
@rchande That's a fine question.  I'm claiming innocence on that one, as it is an existing project I am now helping more with. :)  But this helps a good bit.  Thanks for assiting the omnisharp n00b!
