### ISSUE TITLE
Alternative debugger using

### ISSUE THREAD

**Issue by AndreyZWorkAccount** [OmniSharp/omnisharp-vscode#2973]
Hi guys,

I want to try [the debugger](https://github.com/Samsung/netcoredbg) using VS Code. The debugger supports VS Code Debug Adapter Protocol, so I'm wondering if there is a way to use the debugger through your extension ( sorry if I said something wrong ).

Is it possible to use my own Debug Adapter Protocol implementation instead of 'vsdbg-ui.exe'?

Best regards,
Andrey.

**Comment by rchande** [comment]
cc @gregg-miskelly ?

**Comment by gregg-miskelly** [comment]
The way debug adapters work in VS Code is that the `type` property in your .vscode/launch.json file tells VS Code what debug adapter to use when you hit F5. So if someone provided an alternative debug adapter that worked with .NET Code, you could modify the `type` property in your launch.json to use that debug adapter. I am not familiar enough with Samsung's debug adapter to know if it is a candidate to be such a debug adapter. But the [.NET Core debugging APIs](https://github.com/dotnet/coreclr/blob/master/src/inc/cordebug.idl) are available for anyone who wants to try and right an alternative.

**Comment by AndreyZWorkAccount** [comment]
@ExceptionGit, @gregg-miskelly Thank you for help! I've reached my goal.
