### ISSUE TITLE
'?' in code breaks code highlighting

### ISSUE THREAD

**Issue by RononDex** [OmniSharp/omnisharp-vscode#2976]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.103\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**VSCode version**: 1.33.0
**C# Extension**: 1.18.0

## Steps to reproduce
Following minimal code snippet can reproduce the issue on my pc:
```csharp
using System.Runtime.InteropServices.ComTypes;
using System;

namespace dev
{
    class Program
    {
        static int Main(string[] args)
        {
            var someNullable = (int?)25;
            return (someNullable ? / 5);
        }

        public static void test()
        {

        }
    }
}
```
How it looks like with broken highlighting:
![grafik](https://user-images.githubusercontent.com/2249071/55863189-5911fe80-5b7a-11e9-970a-65f655526075.png)

After removing the '?' it highlighting it correctly:
![grafik](https://user-images.githubusercontent.com/2249071/55863216-662eed80-5b7a-11e9-824c-e2bab971531d.png)

## Expected  behavior
Code after the part `return (someNullable ? / 5);` is correctly highlighted

## Actual behavior
Code formatting is broken after the '?'

**Comment by RononDex** [comment]
Some additional info:
It only happens if the '?' is used as a conditional on nullables.
Like doing ```someNullable?.ToString()```

**Comment by rchande** [comment]
moved to https://github.com/dotnet/csharp-tmLanguage/issues/153
