### ISSUE TITLE
VS Code extension: Stop using DNX DesignTimeHost

### ISSUE THREAD

**Issue by dougbu** [OmniSharp/omnisharp-vscode#298]
In a project using the .NET CLI i.e. `netcoreapp1.0` is one of the targeted frameworks, the VS Code extension still fires up the DNX DesignTimeHost. This results in numerous incorrect errors and warnings
![errors](https://cloud.githubusercontent.com/assets/6431421/15154032/7c5a45aa-1690-11e6-973a-ddf199932bc7.png)

Can this be worked around? For example, the `global.json` file above projects I've used so far contain only a `projects` setting.

From the OmniSharp log:
![designtimehost](https://cloud.githubusercontent.com/assets/6431421/15154044/8a616840-1690-11e6-8c24-53ff0296537e.png)

Side note: This issue is related to #253 but the described symptom there no longer occurs. The squiggly lines aren't valuable but at least .NET CLI projects open.

**Comment by dougbu** [comment]
This issue also degrades the debugging experience. Though the build task encounters no errors or warnings, the C# extension pays attention to the incorrect messages from the `DesignTimeHost`. This results in an extra step after hitting F5:
![debug anyway](https://cloud.githubusercontent.com/assets/6431421/15157456/9731bb0a-16a0-11e6-9180-9deaa6a3d85e.png)

**Comment by DustinCampbell** [comment]
Are you using the shipping C# extension from the marketplace (i.e. 0.3.7)? Because ASP .NET Core RC 1 release was still DNX-based, the C# extension still uses DNX based. That is, we can't ship a VS Code extension that targets bits that are still not-shipped, like .NET CLI. You should be using the latest extension from https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.0.5-rc2 if you want to use it with .NET CLI.

**Comment by dougbu** [comment]
@DustinCampbell I am using `v1.0.5-rc2`, not the much older bits.

**Comment by DustinCampbell** [comment]
It looks like it's using an older version of OmniSharp. The version of OmniSharp targeted by 1.0.5-rc2 doesn't even have the DnxProjectSystem in it. Have you set your "csharp.omnsharp" setting to target a different OmniSharp release?

**Comment by dougbu** [comment]
Looks like VS Code was in a weird state -- was seeing some behaviours described as specific to the latest bits but still had the DNX stuff. Now switched over completely to `1.0.5-rc2` and the extraneous warnings have gone away. Lovely.

**Comment by DustinCampbell** [comment]
Great to hear!
