### ISSUE TITLE
VS Code debian C# autocomletion error. Bug

### ISSUE THREAD

**Issue by svdemir** [OmniSharp/omnisharp-vscode#2985]
Debian and ubuntu vs code c# auto completion error. Please help..

Razor.VSCode version 1.0.0-alpha2.1-20190322.5
Razor's trace level is currently set to 'Off'

To log issues with the Razor experience in VSCode you can file issues at https://github.com/aspnet/Razor.VSCode
To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
Failed to load H&�, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/mehmet/.vscode/extensions/ms-vscode.csharp-1.18.0/.razor/libcoreclr.so'
[Info - 16:14:51] Connection to server got closed. Server will restart.
Failed to load H��, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/mehmet/.vscode/extensions/ms-vscode.csharp-1.18.0/.razor/libcoreclr.so'
[Info - 16:14:51] Connection to server got closed. Server will restart.
Failed to load H���, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/mehmet/.vscode/extensions/ms-vscode.csharp-1.18.0/.razor/libcoreclr.so'
[Info - 16:14:52] Connection to server got closed. Server will restart.
Failed to load H�N�, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/mehmet/.vscode/extensions/ms-vscode.csharp-1.18.0/.razor/libcoreclr.so'
[Info - 16:14:52] Connection to server got closed. Server will restart.
Failed to load Hf�, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/mehmet/.vscode/extensions/ms-vscode.csharp-1.18.0/.razor/libcoreclr.so'
[Error - 16:14:52] Connection to server got closed. Server will not be restarted.

**Comment by NTaylorMullen** [comment]
This if fixed in the alpha3 release of VSCode/next release of C# extension. It should be available this month, stay tuned!

**Comment by svdemir** [comment]
Please fast please. 1 month ago there was no error.
i am use Razor.VSCode version 1.0.0-alpha1-20181019.5
