### ISSUE TITLE
"CSharp: Report an issue" causes results in command 'csharp.reportIssue' not found

### ISSUE THREAD

**Issue by hughbe** [OmniSharp/omnisharp-vscode#2998]
![Screenshot 2019-04-17 at 15 19 30](https://user-images.githubusercontent.com/1275900/56295149-39537b00-6124-11e9-932e-33491b38193f.png)

Then
![Screenshot 2019-04-17 at 15 19 35](https://user-images.githubusercontent.com/1275900/56295156-3bb5d500-6124-11e9-80d5-5ad63037d7ac.png)

**Comment by rchande** [comment]
cc @akshita31

**Comment by filipw** [comment]
This works on my machine, could it be that somehow the installation of the extension is corrupt and need to be reinstalled?

**Comment by akshita31** [comment]
@hughbe The C# extension is activated only when there is some c# folder/file opened in the workspace. Ideally vscode should not show the C# extension commands in the command palette. I think if you try openeing a C# project and the extension gets activated then the feature would be available.

**Comment by akshita31** [comment]
@hughbe I will close this issue now. Please get back to us if it repros
