### ISSUE TITLE
Allow terminal configuration on Linux (currently hard-coded to gnome-terminal).

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#3]
_From @Xorcist77 on December 17, 2015 15:10_

I don't use gnome, and thus don't use gnome-terminal, but VSCode REALLY wants me to. I scaffolded out a new asp.net web project and can run it just fine from my terminal using 'dnx web', but trying to use 'dnx: web' from the command palette inside VSCode tries to launch gnome-terminal, which obviously fails, with the following error:

Error: spawn /usr/bin/gnome-terminal ENOENT

Note that I located workbench.main.js which appears to be the file that is referenced to open the terminal, however changing "usr/bin/gnome-terminal" to "usr/bin/x-terminal-emulator" didn't help. I didn't get any errors, but no terminal opened either... I would have expected it to use whatever terminal I configured in Linux at that point, instead of the hard coded gnome terminal.

I also tried "usr/bin/lxterminal" but that didn't work either...

_Copied from original issue: Microsoft/vscode#1421_

**Comment by jrieken** [comment]
_From @mosamy on January 5, 2016 21:5_

I solved this by a simple sudo apt-get install gnome-terminal. It is only 11 mb and the seamless experience is worth it

**Comment by jrieken** [comment]
_From @Xorcist77 on January 6, 2016 0:10_

@mosamy: That is more of a work around for the poorly designed, hard-coded, implementation currently provided by VSCode.

A configurable option would be much more appropriate. The fact something like this was hard-coded at all makes me wonder what other hidden gems l'm bound to uncover.

**Comment by jrieken** [comment]
_From @PeterBocan on January 16, 2016 13:8_

It's that hard adding one key into the config? :-1:  Okay.

**Comment by DustinCampbell** [comment]
This seems more like a VS Code issue that a C# extension issue.
