### ISSUE TITLE
Cannot get member parameters on parameter help properly

### ISSUE THREAD

**Issue by alexandrudima** [OmniSharp/omnisharp-vscode#30]
Moved from microsoft/vscode#2807
From @tugberkugurlu

Not sure why, here is the screenshot.

![image](https://cloud.githubusercontent.com/assets/328122/12904532/f59b925e-cec7-11e5-93f8-be71c0807a48.png)

 * On Windows 8.1
 * ASP.NET 5 application is on `1.0.0-rc1-update1`
 * `GitHubClient` class I am using here is available on `Octokit v0.16.0`
 * VS Code about:

    ![image](https://cloud.githubusercontent.com/assets/328122/12904559/1e064702-cec8-11e5-8744-6d5f007806b5.png)

**Comment by Pilchie** [comment]
I hit this over the weekend too.  (With Octokit no less :))

**Comment by DustinCampbell** [comment]
Dupe of #13 as well
