### ISSUE TITLE
VS Code extension: Add horizontal scroll bar for build messages and in debugger windows

### ISSUE THREAD

**Issue by dougbu** [OmniSharp/omnisharp-vscode#300]
Highlighting on hover only goes so far...

###### Build messages
Note these messages can only be seen in full affter opening the offending file.
![unwrappederrors](https://cloud.githubusercontent.com/assets/6431421/15157544/f99d0ce0-16a0-11e6-8edc-19a2742ea2c6.png)

###### Call stack at breakpoint
This particular view might be improved if the stack showed `{method}, {namespace-qualified class}` or `{class.method}, {namespace}`.
![unwrappedcallstack](https://cloud.githubusercontent.com/assets/6431421/15157553/0354c8d6-16a1-11e6-93e5-9da3a69f4365.png)

###### Deeply nested variables
![unwrappedvariables](https://cloud.githubusercontent.com/assets/6431421/15157557/06ce53ec-16a1-11e6-9ad2-d5f8bd6c529a.png)

**Comment by DustinCampbell** [comment]
It'd be great if you could file this over at https://github.com/Microsoft/vscode. The extension itself can't add scroll bars.

**Comment by dougbu** [comment]
Microsoft/vscode#6260

**Comment by DustinCampbell** [comment]
Thanks!
