### ISSUE TITLE
Increase mandatory mono version

### ISSUE THREAD

**Issue by rchande** [OmniSharp/omnisharp-vscode#3000]
We should probably raise it to 5.18 to match the version we depend on...

**Comment by rchande** [comment]
see: https://github.com/OmniSharp/omnisharp-vscode/issues/2991#event-2283368717

**Comment by rchande** [comment]
cc @akshita31

**Comment by filipw** [comment]
yes definitely, not to mention 5.20.1 is already available too.

**Comment by filipw** [comment]
related: https://github.com/OmniSharp/omnisharp-roslyn/pull/1466

**Comment by filipw** [comment]
This was done, 6.4.0 is the lowest that will be picked up
