### ISSUE TITLE
Support Windows ARM64

### ISSUE THREAD

**Issue by richlander** [OmniSharp/omnisharp-vscode#3006]
## Environment data

Windows ARM64
Install Windows **ARM64** .NET Core SDK (**NOT** x86)

## Steps to reproduce

* Create console app
* Insert a ReadLine in it, to hault execution so we can wait on the debugger being attached
* Build console app at CLI
* Launch app, and make sure it is waiting at the ReadLine
* Attach to the right PID

## Expected  behavior

* Debugger shows threads and any other appropriate data
* breaks at breakpoint after the ReadLine once I hit enter

## Actual behavior

* Debugger doesn't appear to do anything

Tried same steps launching the app with both .NET Core 3.0 x86 runtime and .NET Core 3.0 ARM64 runtime. Same experience.

## My App

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            var pid = System.Diagnostics.Process.GetCurrentProcess().Id;
            Console.WriteLine("Hello World!");
            Console.WriteLine($"Process: {pid}");
            Console.WriteLine("Press enter to exit.");
            Console.ReadLine();
            Console.WriteLine(System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription);
        }
    }
```

**Comment by gregg-miskelly** [comment]
It is probably a VS Code bug that it doesn't show you an error - the C# extension only ships the x64 version of the debugger, which will not run on a Windows ARM64 machine.

As we discussed a while back - we aren't planning to support x86 in the VS Code debugger. I can leave this active if you want to eventually support ARM64 target processes.

**Comment by richlander** [comment]
Thanks for the info. Yes, my goal is ARM64 not x86. I tried both to see if there was any difference.

Can we make this issue the request for an ARM64 debugger, and not by design as a result?

**Comment by richlander** [comment]
One small nit ... The ARM64 SDK isn't currently yet available, just the Runtime. So everything is correct above, but to go through the flow today, you need the x86 SDK to build the product. In future, we'll have an ARM64 SDK.

**Comment by MikeyMCZ** [comment]
Hello. It seems that we might get build of Visual Studio Code for Windows ARM in "near future" - [Iteration Plan for April 2020](https://github.com/microsoft/vscode/issues/95168) and we are getting Windows ARM64 builds of .NET 5.0 SDK - [Nightly SDK builds](https://github.com/dotnet/installer/blob/master/README.md#installers-and-binaries).
Any plans to support .NET debugging on Windows ARM devices?

**Comment by gregg-miskelly** [comment]
Supporting .NET debugging on Windows ARM64 is definitely something on our radar. But we haven't yet decided for sure what form that will take or when it will be released.

**Comment by turowicz** [comment]
I need it so bad. Any rough estimates?

**Comment by gregg-miskelly** [comment]
@turowicz can you talk more about what your scenario is?

**Comment by turowicz** [comment]
I am porting my dotnet core 3.1 AI system (surveily.com) to run on Nvidia Jetson. There are many problems with libraries that I use (nuget and cpp) that need debugging so I must resort to Console.Writeline right now... Also cannot debug failing unit tests.

**Comment by gregg-miskelly** [comment]
@turowicz to make sure I understand - you are running Windows on this Nvidia Jetson board?

**Comment by turowicz** [comment]
@gregg-miskelly Jetson only supports Jetpack OS, which is a Ubuntu image made by Nvidia.

**Comment by gregg-miskelly** [comment]
@turowicz Than this issue has nothing to do with your scenario. ARM64 remote Linux debugging has been supported for quite some time. See the Wiki for instructions.

**Comment by turowicz** [comment]
Is it possible to remote debug a docker container? I don't see that kind of hybrid in the documentation.

**Comment by turowicz** [comment]
ie. a docker container running on the remote ARM machine

**Comment by gregg-miskelly** [comment]
Yes. There is a docker example [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Attaching-to-remote-processes#configuring-docker-attach-with-launchjson). Since your container is remote, yours might be a bit different. But you could -
1. Use local the `docker` executable to run commands on a remote host
-or-
2. SSH into the target host and run docker commands there.
-or-
3. Run an SSH server inside your container

For attach, full Visual Studio (NOT Code) has support for attach in all these cases through the Attach To Process dialog, though no support for launch. Visual Studio Code can stitch anything together that you have the patience to do, but you will need to manually configure everything....

**Comment by turowicz** [comment]
This is what I meant, there isn't an "official" way to do it in Code (ssh through to docker).

**Comment by gregg-miskelly** [comment]
I wouldn't really say that - the nice thing about remote debugging in VS Code is that everything is supported, and you can make everything work. The downside of remote debugging in VS Code is that nothing is trivial. SSH + Docker is a bit tricker maybe since we don't have an example, but I am happy to add an example if you have a launch.json block to share.

**Comment by turowicz** [comment]
Thanks for stating the obvious.

**Comment by turowicz** [comment]
> I wouldn't really say that 

If you can point me to a documentation explaining how it's done then I will definitely agree with you.

**Comment by BigBandit** [comment]
Hello, just wanted to bump this, was wondering if this would be coming anytime in the near future. I use a Surface Pro X for developing.

**Comment by Alovchin91** [comment]
Hi @gregg-miskelly, what's the status of this? Now that stable Visual Studio Code is officially supported on Windows on Arm and .NET 5 supports Arm64 and is approaching the release, it would be nice to get some kind of a timeline for C# extension to support Windows on Arm. Thanks!

**Comment by gregg-miskelly** [comment]
It is something fairly high on our priority list, but we don't have a committed release yet.

**Comment by visschersm** [comment]
I currently use the dotnet CLI on my surface pro x to develop some net5. 
Though I'm very much looking forward to full support for the arm64 processors.

**Comment by jamesthurley** [comment]
Another vote for the scenario of doing .NET Core development using a Surface Pro X with VSCode.

**Comment by tbonham** [comment]
Another vote for this. I'm waiting to get a surface pro x for this to work.

**Comment by Alovchin91** [comment]
@gregg-miskelly  Hi, do you have any updates on this? Maybe there is something we could help with.

**Comment by turowicz** [comment]
.NET 5.0 runs pretty smooth on ARM64

**Comment by gregg-miskelly** [comment]
> @gregg-miskelly Hi, do you have any updates on this? Maybe there is something we could help with?

The debugger part of the extension is what I work on. Most of the debugger is closed source, so this needs to be done by my team.

The rest of the extension (C# language service and Razor language service) is open source, so there may be opportunities for community help. 

For the C# language service -- that currently runs on Desktop CLR, so in theory it _should_ work on Windows ARM64, but it would be x86 emulated, I am not sure if the language team has a good read on how well that works (example: how does it work with a native SDK). The language service team might appreciate feedback. @cartermp might be able to better comment. In the long term there is a desire to run on .NET Core, but I don't know if that needs to happen for this work item to really be done.

**Comment by Alovchin91** [comment]
Hi, any updates on this? [.NET 5.0 RC 2 landed](https://devblogs.microsoft.com/dotnet/announcing-net-5-0-rc-2/) today, with an official SDK installer for Windows on Arm64 and a go-live license.

**Comment by aidapsibr** [comment]
Now that mono is under the NET5 umbrella, how much work is left here?

**Comment by tbonham** [comment]
Hello,

Is there any update on this? With dotnet 5 having the official installer this plugin is the only thing keeping me from getting a surface x pro.

**Comment by LinuxDoku** [comment]
FYI, since omnisharp 1.37.1 they publish native windows arm64 assemblies (https://github.com/OmniSharp/omnisharp-roslyn/releases).

You can download them and point the omnisharp path in your visual studio code settings to the OmniSharp executable.
```json
"omnisharp.path": "C:\\Temp\\omnisharp-win-arm64\\OmniSharp.exe",
```

With this you get intellisense, file error checking, etc. Only the debugger is still incompatible. To debug your code, you have to open the x86 emulated visual studio 2019.

**Comment by kotha16** [comment]
When is the official support for Windows 10 ARM64 coming.....Why is this taking so long......Not having an ARM64 is really sad especially people buying surface pro x.....Am not sure why msft is not looking into this

**Comment by ap3rus** [comment]
As a (kind of) workaround, arm64 build of windbg from Windows SDK supports .NET5's sos.dll, makes it a viable (although a bit complicated) option for debugging.

**Comment by laultman** [comment]
We need this too, using Windows Surface Pro X as a dev tool for our HoloLens2 development. Unity is no fun either. Getting all the stuff to work feels like 1984.

**Comment by Alovchin91** [comment]
Hi, can somebody please descend upon us and provide an update on this issue? Thanks!

**Comment by Alovchin91** [comment]
I can imagine that this is still blocked by the transition to .NET 5 and an arm64-version of vsdbg, but @richlander could you please provide any bit of information on this issue?

**Comment by Alovchin91** [comment]
Do we have any chance to see some roadmap? At least a very, very high level?

**Comment by Alovchin91** [comment]
Would [ARM64EC](https://blogs.windows.com/windowsdeveloper/2021/06/28/announcing-arm64ec-building-native-and-interoperable-apps-for-windows-11-on-arm/) make it simpler? @gregg-miskelly Could you please provide any bit of info on this?

**Comment by gregg-miskelly** [comment]
The debugger side of this work is currently in progress.

ARM64EC isn't an option for the debugger, it also wouldn't make it simpler.

**Comment by Alovchin91** [comment]
@gregg-miskelly Thanks a lot for the update! 😊

Would it be possible to have IntelliSense support in the meantime? Just like what C++ Extension did:
https://devblogs.microsoft.com/cppblog/visual-studio-code-c-extension-arm-and-arm64-support/

**Comment by Alovchin91** [comment]
@gregg-miskelly @JoeRobich Hi, I've noticed that OmniSharp is being built for Windows arm64 since v1.37.1: https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.37.11

I also see that the extension is not being blocked from installing on Windows arm64: https://github.com/OmniSharp/omnisharp-vscode/blob/69711c277fe3b79a6b73bf8420390238f0eff4dd/src/main.ts#L217

Unfortunately, it doesn't seem to install the OmniSharp package on Windows arm64 as I'm seeing a "File not found" error:

```
Starting OmniSharp server at 04/07/2021, 09:42:43
    Target: c:\Projects\dotnet_app

OmniSharp server started.
    Path: c:\Users\alovchin\.vscode\extensions\ms-dotnettools.csharp-1.23.12\.omnisharp\1.37.10\OmniSharp.exe
    PID: 4088

The system cannot find the path specified.
```

Would it be possible to enable OmniSharp download for Windows arm64, please? 🙂

**Comment by Alovchin91** [comment]
Hi @gregg-miskelly  It turns out vsdbg.exe now supports Windows arm64! 🥳 https://github.com/microsoft/vscode-cpptools/issues/6392#issuecomment-876812638  Is this something that unblocks C# Extension for arm64? 😊

**Comment by gregg-miskelly** [comment]
@Alovchin91 Yes, as I said, we are actively working on this. I would expect a PR to enable this sometime fairly soon.

**Comment by Alovchin91** [comment]
Thanks a lot for the update, that's fantastic news! 😊 Do you have a roadmap in which version you _expect_ it to be available (like in the linked C++ extension issue)? 🙂

**Comment by gregg-miskelly** [comment]
The language service team has been trying to address a blocking bug for the 1.23.13 for a little while now, so I am not sure. Depending on how fast that issue is resolved, and if we find issues when inserting the new debugger it will either be in 1.23.13 or the release after that (1.23.14 I assume?).

**Comment by Alovchin91** [comment]
Wow, that's super great to hear! 🚀 Thanks again for the update!

**Comment by gboder** [comment]
👍🏻👍🏻👍🏻 So great ! I’m looking forward for this update.

Envoyé depuis un mobile
________________________________
De : Alexander Ovchinnikov ***@***.***>
Envoyé : Friday, July 9, 2021 9:46:23 PM
À : OmniSharp/omnisharp-vscode ***@***.***>
Cc : Gautier Boder ***@***.***>; Manual ***@***.***>
Objet : Re: [OmniSharp/omnisharp-vscode] Support Windows ARM64 (#3006)


Wow, that's super great to hear! 🚀 Thanks again for the update!

**Comment by Alovchin91** [comment]
So great to see this merged! 🎉

@gregg-miskelly  There seems to be a small typo in package.json, could you please have a look? https://github.com/OmniSharp/omnisharp-vscode/pull/4675

**Comment by BigBandit** [comment]
To those that have a SPX specifically, Microsoft has released an x64
emulator that bypasses all of this:
https://blogs.windows.com/windows-insider/2020/12/10/introducing-x64-emulation-in-preview-for-windows-10-on-arm-pcs-to-the-windows-insider-program/

**Comment by gregg-miskelly** [comment]
To be clear: x64 emulation is only useful for this feature if you want to install x64 versions of BOTH the .NET Core SDK and VS Code. I would NOT recommend this approach unless you for some reason need to run in an x64 process.

Instead, if you want this feature now you should install arm64 versions of the .NET Core SDK (See installer link [here](https://dotnet.microsoft.com/download/dotnet/5.0)), VS Code, and install the C# extension 1.23.14 beta release ([instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases)). If you are reading this after 1.23.14 has been released to the marketplace you can ignore the last part.
