### ISSUE TITLE
Wildcard used in RuntimeFrameworkVersion causes loss of references intellisence 

### ISSUE THREAD

**Issue by tmjwid** [OmniSharp/omnisharp-vscode#3014]
## Environment data
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.104\

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.2 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
VS Code version: 1.33.1
C# Extension version: 1.19

## Steps to reproduce
In the RuntimeFrameworkVersion tag, use a wildcard for the versioning e.g
```
<PropertyGroup>
    <RuntimeFrameworkVersion>2.*</RuntimeFrameworkVersion>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <DebugType>portable</DebugType>
</PropertyGroup>
```
Perform a dotnet clean, dotnet restore and close Code. Try and use external reference methods. 

## Expected behaviour
Intellisense to work as before, for all references both project and library dependencies.
![image](https://user-images.githubusercontent.com/3685703/56461619-d9700500-63ad-11e9-8c7d-301cc4001ebb.png)

## Actual behavior
External reference Intellisense has gone, leaving random file references as code completion. 
![image](https://user-images.githubusercontent.com/3685703/56461643-1f2ccd80-63ae-11e9-9de8-0346eabe2e60.png)

## Notes
To be honest, I'm not 100% certain I should be wildcarding the RuntimeFrameworkVersion, so if this is known issue and can't be fixed then maybe some documentation should be wrote as I could find nothing about this issue and just fixed by playing wack a mole with the csproj.

**Comment by tmjwid** [comment]
My apologies, it's been a long day and I missed a report from 2 days ago with the exact same issue  #[https://github.com/OmniSharp/omnisharp-vscode/issues/3009](url)

**Comment by filipw** [comment]
@tmjwid thanks, could you please try this solution? it should be fixed already https://github.com/OmniSharp/omnisharp-vscode/issues/3009#issuecomment-484772057
