### ISSUE TITLE
[ERROR]: C# Extension failed to get platform information.

### ISSUE THREAD

**Issue by brian-themaven** [OmniSharp/omnisharp-vscode#3015]
## Environment data
VSCode installed:
1.33.1 for MacOS

`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.103/

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.2.103 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version:
C# Extension version: 1.19.0

## Steps to reproduce
Install C# ms-vscode.csharp

## Expected  behavior
Omnisharp working.

## Actual behavior
[ERROR]: C# Extension failed to get platform information.
Omnisharp not working.

**Comment by brian-themaven** [comment]
I had only downloaded the .NET Core SDK and not the runtime.  After downloading the Runtime it worked.

**Comment by brian-themaven** [comment]
This now repros again.  I re-installed .NET Core SDK and Runtime from here https://dotnet.microsoft.com but this time it did not fix my issue.

**Comment by brian-themaven** [comment]
Some more info after turning on Help | Developer Tools.

extensionService.ts:800 Activating extension 'ms-vscode.csharp' failed: Cannot read property 'architecture' of undefined.

**Comment by ramanaptr** [comment]
@brian-themaven how do you fix this issue? please to remind to us, thanks 🙏

**Comment by brian-themaven** [comment]
Sorry it's been a few years since I've used this now.  Good luck!

**Comment by ramanaptr** [comment]
Ok, thanks @brian-themaven , I got an answer for the solved problem and I just did install a new Mono 6.x package on my Mac.
