### ISSUE TITLE
Question: How to customize the code analysis rulesets for C#?

### ISSUE THREAD

**Issue by icewindq** [OmniSharp/omnisharp-vscode#3017]
Hi guys,
I use the latest VS Code(1.32.3) with ms-vscode.csharp-1.19.0. I got a lot of warnings in the Problems Panel when I open an ASP.NET MVC project, like this:

> Missing XML comment for publicly visible type or member 'WebApiConfig' (CS1591) [EVCPlatform.Chat.Api.Host]

So I want to disable those warnings via customizing the code analysis rulesets. My questions are:
1. Where do the global rulesets of code analysis load from? 
2. How to customize the code analysis rulesets globally for all C# projects?

Thanks.

**Comment by savpek** [comment]
Sadly there isn't support for user specific (derived from vscode eg.) rulesets yet. However you can configure them per solution / projects with .ruleset files https://roslyn-analyzers.readthedocs.io/en/latest/config-analyzer.html

Ruleset support requires `omnisharp.enableRoslynAnalyzers` set true.

**Comment by icewindq** [comment]
@savpek Thanks for your answer.  It works after using .ruleset files.

**Comment by shmink** [comment]
@savpek My team is using Sonar. We've picked and chosen our ruleset. I've exported them into an XML file that matches the structure shown in the examples you link. Same tags and that. I created `sonar.ruleset` file with that XML export.

    I've then gone into `.csproj` file and pointed to that sonar file as per [this guide](https://roslyn-analyzers.readthedocs.io/en/latest/config-analyzer.html#net-core-and-net-standard-projects). Testing by removing some rules expecting a warning or lack thereof doesn't seem to change anything. Is there anything else? The `omnisharp.enableRoslynAnalyzers` is set true.

**Comment by filipw** [comment]
can you please provide a repro project - thanks

**Comment by shmink** [comment]
@filipw 
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <CodeAnalysisRuleSet>sonar.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="3.0.0-preview-010560002-1165" />
    <PackageReference Include="SonarAnalyzer.CSharp" Version="8.1.0.13383">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.0.0-rc5" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.5.1" />
  </ItemGroup>

</Project>
```

`sonar.ruleset` is at the same level as this project file.

**Comment by shmink** [comment]
@filipw  also the trimmed down version of the aforementioned `sonar.ruleset`

```
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="Rules for SonarLint" Description="This rule set was automatically generated from SonarQube." ToolsVersion="14.0">
  <Rules AnalyzerId="SonarAnalyzer.CSharp" RuleNamespace="SonarAnalyzer.CSharp">
    <Rule Id="S121" Action="Warning" />
    <Rule Id="S1067" Action="Warning" />
    <Rule Id="S1479" Action="Warning" />
    <Rule Id="S1116" Action="Warning" />
  </Rules>
</RuleSet>
```

**Comment by shmink** [comment]
Bump please. I still very much would want to get this working.
