### ISSUE TITLE
The “launch.json” file generator hasn't updated the parts in <> when debugging in VSCode. 

### ISSUE THREAD

**Issue by YunWeiaa** [OmniSharp/omnisharp-vscode#3025]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011555
 Commit:    50184f3f6c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview5-011555/

Host (useful for support):
  Version: 3.0.0-preview5-27623-11
  Commit:  0090de2841

.NET Core SDKs installed:
  3.0.100-preview5-011555 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview5-19223-06 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27623-11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS Code version: 1.33.1
C# Extension version: 1.19 (v1.19.0)

## Steps to reproduce
•	Create new .NET Core 3.0 console application(con30) with reference to a .NET Standard 2.1 class library(cla21) via CLI,
•	Open it via VSCode
![image](https://user-images.githubusercontent.com/33921754/56779288-df7e3f80-680c-11e9-8996-34c143ca8f97.png)
•	Debug the app – Put breakpoint in the code and press F5, it shows a prompt message of “launch.json”:
![image](https://user-images.githubusercontent.com/33921754/56779812-456bc680-680f-11e9-807a-e49c49eee688.png)
•	Then open “launch.json”, press “Add Configuration…” :
![image](https://user-images.githubusercontent.com/33921754/56780043-4e10cc80-6810-11e9-9def-f7f1970d8354.png)
•	Choose “.NET: Launch .NET Core Console App”
![image](https://user-images.githubusercontent.com/33921754/56780090-857f7900-6810-11e9-998b-4d96baa343c9.png)

## Expected  behavior
The file generator should have updated the parts in <>.

## Actual behavior
•	Need to manually modify “launch.json”
Before change
```
…
"program": "${workspaceFolder}/bin/Debug/<target-framework>/<project-name.dll>",
…
```

After change
```
…
"program": "${workspaceFolder}/bin/Debug/netcoreapp3.0/con30",
…
```
•	Press F5 again, basic debugging can be succeeded.
[launch.json.txt](https://github.com/OmniSharp/omnisharp-vscode/files/3119529/launch.json.txt)

**Comment by gregg-miskelly** [comment]
@YunWeiaa You ran right past the big warning about how OmniSharp was unable to understand your project, and that is why you are getting a super generic launch.json file.

If you run the '.NET: Generate Assets for Build and Debug' command from command pallet, do you get a functional launch.json? If not, are you getting any problems indicated in the OmniSharp log? Is completion working?

**Comment by YunWeiaa** [comment]
Not repro on **CLI\SDK: 3.0.100-preview5-011566 (runtime- 3.0.0-preview5-27626-15)**, the “launch.json” file generator can update automatically the parts in <> when debugging in VSCode.
![image](https://user-images.githubusercontent.com/33921754/56860004-4134da00-69c4-11e9-823e-fb590a2dc8fb.png)
