### ISSUE TITLE
Newly added project files not "watched"

### ISSUE THREAD

**Issue by YunWeiaa** [OmniSharp/omnisharp-vscode#3026]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011560
 Commit:    13c0a5fdb5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview5-011560/

Host (useful for support):
  Version: 3.0.0-preview5-27624-11
  Commit:  7b5103a1f6

.NET Core SDKs installed:
  3.0.100-preview5-011560 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview5-19225-01 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27624-11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS Code version: 1.33.1
C# Extension version: 1.19 (v1.19.0)

## Steps to reproduce
1. Create a Class Library project.(C#)
Place some sample test code into your test method
Ex: 
```
public static bool NS(int i)
        {
            if (i > 10)
                return true;
            else
                return false;
        }
```
2. Build the project
3. Add a new Unit Test Project into the solution
5. Refer the above class library into this project in code editor via VSCode.
Put below sample code in the Test Method
` Assert.IsFalse(Class1.NS(33));`
## Expected  behavior
IntelliSense works well while adding a project reference in code editor.

## Actual behavior
No corresponding method name is displayed.
![image](https://user-images.githubusercontent.com/33921754/56801401-ee3a1600-684f-11e9-9182-8a981087d1ab.png)

**Comment by chetanthambad** [comment]
Facing the same issue

**Comment by rchande** [comment]
I think what's happening here is that project files added after omnisharp starts aren't "watched" for changes. You can work around this by:
* using the "restart omnisharp" command to restart omnisharp after adding the second project file
* using the "restart omnisharp" command after adding the reference

When I do this, I get intellisense from the referenced project.

**Comment by YunWeiaa** [comment]
@rchande thanks a lot. Intellisense can work well by the workaround.

**Comment by YunWeiaa** [comment]
Not repro on
VS Code version: 1.33.1
C# Extension version: 1.19 (v1.19.1)
