### ISSUE TITLE
VS Code extension: Improve experience when choosing process to attach

### ISSUE THREAD

**Issue by dougbu** [OmniSharp/omnisharp-vscode#303]
The `processName` `launch.json` property is too general e.g. many `dotnet` processes may be running on the system. And the `processId` property is too specific i.e. should never need to be saved to a file. Suggest discriminating using command-line arguments. In the `dotnet` case (even when using `dotnet run`), these arguments include the relative path to the DLL of interest.

Failing that, suggest bringing up a dialogue to choose between processes that match the discriminators provided in `launch.json`. Even better if that dialogue shows the full command line of the potential matches.

**Comment by gregg-miskelly** [comment]
I don't think there are ways to obtain the command line reliable across all platforms.

**Comment by gregg-miskelly** [comment]
@rajkumar42 can you resolve this when you enable the new attach to process chooser?

@dougbu we are enabling a new experience with our next version of the extension which doesn't quite match your original request, but hopefully you will find this much better.

**Comment by rajkumar42** [comment]
merged. it'll be in the upcoming release.
