### ISSUE TITLE
Namespaces and types don't exist in netcoreapp3.0

### ISSUE THREAD

**Issue by Ryhon0** [OmniSharp/omnisharp-vscode#3036]
## Issue Description ##
When I open a C# project with `TargetFramework` being `netcoreapp3.0` the extension says all of the namespaces and types don't exist. When I run `dotnet build` the program compiles with no erros
## Steps to Reproduce ##
Create a dotnet core project and change `TargetFramework` to `netcoreapp3.0` in the .csproj file
## Expected Behavior ##
Extensions doesn't show any problems
## Actual Behavior ##
Extension says all of the namespaces and types don't exist
### OmniSharp log ###
<details>Starting OmniSharp server at 5/2/2019, 1:38:52 PM
    Target: /home/ryhon/AvalonStudio/Projects/ImageSplitter/ImageSplitter.sln

OmniSharp server started with Mono 5.20.1.
    Path: /home/ryhon/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/OmniSharp.exe
    PID: 2864

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on manjaro 0.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/usr/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/home/ryhon/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/usr/lib/mono/msbuild/15.0/bin"
            CscToolExe = csc.exe
            CscToolPath = /home/ryhon/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/ryhon/AvalonStudio/Projects/ImageSplitter'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/ryhon/AvalonStudio/Projects/ImageSplitter/ImageSplitter.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/ryhon/AvalonStudio/Projects/ImageSplitter/ImageSplitter/ImageSplitter.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/ryhon/AvalonStudio/Projects/ImageSplitter/ImageSplitter.Avalonia/ImageSplitter.Avalonia.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/ryhon/AvalonStudio/Projects/ImageSplitter'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/ryhon/AvalonStudio/Projects/ImageSplitter/ImageSplitter/ImageSplitter.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/ryhon/AvalonStudio/Projects/ImageSplitter' on host 2735.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/ryhon/AvalonStudio/Projects/ImageSplitter/ImageSplitter/ImageSplitter.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/ryhon/AvalonStudio/Projects/ImageSplitter/ImageSplitter/ImageSplitter.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/ryhon/AvalonStudio/Projects/ImageSplitter/ImageSplitter.Avalonia/ImageSplitter.Avalonia.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The project was restored using Microsoft.NETCore.App version 1.0.5, but with current settings, version 3.0.0 would be used instead.  To resolve this issue, make sure the same settings are used for restore and for subsequent operations such as build or publish.  Typically this issue can occur if the RuntimeIdentifier property is set during build or publish but not during restore.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/home/ryhon/AvalonStudio/Projects/ImageSplitter/ImageSplitter.Avalonia/ImageSplitter.Avalonia.csproj'.
/home/ryhon/AvalonStudio/Projects/ImageSplitter/ImageSplitter.Avalonia/ImageSplitter.Avalonia.csproj
/home/ryhon/AvalonStudio/Projects/ImageSplitter/ImageSplitter.Avalonia/ImageSplitter.Avalonia.csproj(0,0): Error: The project was restored using Microsoft.NETCore.App version 1.0.5, but with current settings, version 3.0.0 would be used instead.  To resolve this issue, make sure the same settings are used for restore and for subsequent operations such as build or publish.  Typically this issue can occur if the RuntimeIdentifier property is set during build or publish but not during restore.

[info]: OmniSharp.MSBuild.ProjectManager
        Update project: ImageSplitter
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /home/ryhon/AvalonStudio/Projects/ImageSplitter/ImageSplitter.Avalonia/ImageSplitter.Avalonia.csproj
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        ImageSplitter: Did not find 'Microsoft.NETCore.App' in lock file.
</details>

## Environment information ##

**VSCode version**: 1.33.1
**C# Extension**: 1.19.0

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.20.1</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-011223
 Commit:    118dd862c8

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /opt/dotnet/sdk/3.0.100-preview4-011223/

Host (useful for support):
  Version: 3.0.0-preview4-27615-11
  Commit:  ee54d4cbd2

.NET Core SDKs installed:
  2.2.105 [/opt/dotnet/sdk]
  3.0.100-preview4-011223 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [/opt/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.19.0|
|csharp-colors|logerfo|0.1.2|
|csharpextensions|jchannon|1.3.0|
|discord-vscode|icrawl|3.5.1|
|docomment|k--kato|0.1.6|
|extbundles-csharp|FelschR|2.0.0|
|msbuild-project-tools|tintoy|0.2.54|
|vscode-versionlens|pflannery|0.23.0|;

</details>

**Comment by rchande** [comment]
@Ryhon0 Can you try setting the option "omnisharp.useglobalmono" to "never" and see if that helps? If it does, it means that your machine's mono installation is missing some MSBuild components.

**Comment by Ryhon0** [comment]
Thanks, setting `omnisharp.useglobalmono` to `never` fixed the issue
