### ISSUE TITLE
Breakpoints kill debugger

### ISSUE THREAD

**Issue by seanmccay** [OmniSharp/omnisharp-vscode#3039]
Issue Type: <b>Bug</b>

Setting a breakpoint kills or prevents debugger from running.

scenario 1:
1. set breakpoint in a file
2. start debugging 
3. watch preLaunchTask run successfully
4. once preLaunchTask completes, debug console comes into focus
5. debugger stops.

scenario 2:
1. have no breakpoints set
2. start debugging
3. debugger starts successfully, api is running
4. set breakpoint
5. debugger stops

Extension I think is in question: Omnisharp C#
Extension version: 1.19.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 5.0.0-13-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor (16 x 1501)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 2, 1|
|Memory (System)|31.40GB (24.15GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by gregg-miskelly** [comment]
@seanmccay I see that you are on Linux. Are you on Ubuntu 19.04 (or a downstream OS)? If so, I am guessing you are running into https://github.com/OmniSharp/omnisharp-vscode/issues/3010 and you should [install the latest beta](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) which has a fix.

Otherwise, can you try [enabling logging](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging)?

**Comment by seanmccay** [comment]
@gregg-miskelly I am on Pop!_OS 19.04. I installed the beta and my problem has been resoved :). I was having all kinds of weird problems before, but I'm not seeing them now. Thanks.

**Comment by spiko-md** [comment]
I get something like issue #1 on windows 11. setting focus to another window, (alt tab) and then back to vs code will make omnisharp debugger work again for this debugging session.
