### ISSUE TITLE
VS Code extension, debugging: `.cshtml` files not found when at breakpoint

### ISSUE THREAD

**Issue by dougbu** [OmniSharp/omnisharp-vscode#304]
An `Exception` thrown within a view (or the code a view calls) correctly breaks execution. But the display shows neither the Razor-generated C# code nor the `.cshtml` source. It seems the C# extension does not support the project directory being the virtual root used in generated `#line` pragmas. The same code works fine in Visual Studio.
![cshtml filenotfound](https://cloud.githubusercontent.com/assets/6431421/15159569/260e0f8c-16aa-11e6-9788-c2237b9b01b1.png)

The above image is from a Windows system. The behaviour is the same on a Linux (Ubuntu 14.04 LTS) system except the slashes go in the opposite direction.

**Comment by gregg-miskelly** [comment]
@wesrupert FYI I am assigning this to you

**Comment by wesrupert** [comment]
This is a bug in Razor ([#803](https://github.com/aspnet/Razor/issues/803)) that we don't really have a good way to work around on our side. To work around it per-project in the meantime, please add a sourceFileMap to your launch.json configuration to redirect relative .cshtml paths to their absolute counterparts.

### Windows:
```json
"name": ".NET Core Launch (web)",
...
"sourceFileMap": {
    "/Views": "${workspaceRoot}\\Views"
}
```

### macOS/Linux
```json
"name": ".NET Core Launch (web)",
...
"sourceFileMap": {
    "/Views": "${workspaceRoot}/Views"
}
```

The next version of the extension will add this to projects automatically, as well as let you set breakpoints and view/set variables and watch expressions in .cshtml files.

**Comment by gregg-miskelly** [comment]
@wesrupert can we use the forward slash version on Windows also? If not, we should fix it so that you can.

**Comment by wesrupert** [comment]
@gregg-miskelly in the next version of the C# extension, yes. In the meantime, windows needs the backslash.
