### ISSUE TITLE
System.IO.IOException: kqueue() error at init, error code = '24'

### ISSUE THREAD

**Issue by yufeih** [OmniSharp/omnisharp-vscode#3041]
## Issue Description ##

Throws `System.IO.IOException` when opening a C# solution on a Mac

## Steps to Reproduce ##

Open https://github.com/dotnet/docfx with vscode on Mac

## Expected Behavior ##

Code compiles

## Actual Behavior ##

System.IO.IOException

### OmniSharp log ###

<details>

Starting OmniSharp server at 5/3/2019, 1:56:32 PM
    Target: /Users/yufeih/docfx/docfx.sln

OmniSharp server started with Mono 5.10.1.
    Path: /Users/yufeih/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/OmniSharp.exe
    PID: 572

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.14 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/Users/yufeih/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin"
            CscToolPath = /Users/yufeih/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/yufeih/docfx'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/yufeih/docfx/docfx.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/yufeih/docfx/src/docfx/docfx.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/yufeih/docfx/test/docfx.Test/docfx.Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/yufeih/docfx/src/Microsoft.Docs.Template/Microsoft.Docs.Template.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/yufeih/docfx'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/yufeih/docfx/src/docfx/docfx.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/yufeih/docfx' on host 542.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/yufeih/docfx/src/docfx/docfx.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/yufeih/docfx/src/docfx/docfx.csproj'
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.CodeFixes.ApplyDiagnosticAnalyzerAttributeFix' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.QualityGuidelines.MarkMembersAsStaticFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.QualityGuidelines.PreferJaggedArraysOverMultidimensionalFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.QualityGuidelines.ReviewVisibleEventHandlersFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.QualityGuidelines.UseLiteralsWhereAppropriateFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.Maintainability.AvoidUninstantiatedInternalClassesFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.Maintainability.ReviewUnusedParametersFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.Maintainability.UseNameOfInPlaceOfStringFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.Maintainability.VariableNamesShouldNotMatchFieldNamesFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.Documentation.AvoidUsingCrefTagsWithAPrefixFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiReview.AvoidCallingProblematicMethodsFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.AsyncMethodNamesShouldEndInAsyncFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.AvoidAsyncVoidFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.AvoidEmptyInterfacesFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.CollectionsShouldImplementGenericInterfaceFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.DeclareTypesInNamespacesFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.DoNotHideBaseClassMethodsFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.DoNotMixBlockingAndAsyncFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.DoNotPassAsyncLambdasAsVoidReturningDelegateTypesFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.DoNotStoreAsyncLambdasAsVoidReturningDelegateTypesFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.EnumsShouldHavePluralNamesFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.EnumsShouldHaveZeroValueFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.EnumStorageShouldBeInt32Fixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.IdentifiersShouldHaveCorrectPrefixFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.IdentifiersShouldHaveCorrectSuffixFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.IdentifiersShouldNotContainUnderscoresFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.IdentifiersShouldNotHaveIncorrectSuffixFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.IdentifiersShouldNotMatchKeywordsFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.ImplementIDisposableCorrectlyFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.MarkAssembliesWithAssemblyVersionFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.MarkAssembliesWithClsCompliantFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.MarkAssembliesWithComVisibleFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.MovePInvokesToNativeMethodsClassFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.NonConstantFieldsShouldNotBeVisibleFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.OverrideEqualsAndOperatorEqualsOnValueTypesFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.OverrideEqualsOnOverloadingOperatorEqualsFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.OverrideGetHashCodeOnOverridingEqualsFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.PropagateCancellationTokensWhenPossibleFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.PropertiesShouldNotBeWriteOnlyFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.PropertyNamesShouldNotMatchGetMethodsFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.TypeNamesShouldNotMatchNamespacesFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.UseEventsWhereAppropriateFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.UseGenericEventHandlerInstancesFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.UsePreferredTermsFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.UsePropertiesWhereAppropriateFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.Tasks.DoNotCreateTasksWithoutPassingATaskSchedulerFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.Runtime.CallGCSuppressFinalizeCorrectlyFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.Runtime.DisposableTypesShouldDeclareFinalizerFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.Runtime.DisposeMethodsShouldCallBaseClassDisposeFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.Runtime.DoNotLockOnObjectsWithWeakIdentityFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.Runtime.DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.Runtime.DoNotUseTimersThatPreventPowerStateChangesFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.Runtime.InitializeStaticFieldsInlineFixer`1[TLanguageKindEnum]' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.Runtime.InstantiateArgumentExceptionsCorrectlyFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.Runtime.NormalizeStringsToUppercaseFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.Runtime.SpecifyCultureInfoFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.Runtime.SpecifyIFormatProviderFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.Runtime.SpecifyStringComparisonFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.Runtime.TestForEmptyStringsUsingStringLengthFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.Runtime.TestForNaNCorrectlyFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.Runtime.UseOrdinalStringComparisonFixerBase' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.InteropServices.MarkBooleanPInvokeArgumentsWithMarshalAsFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.InteropServices.SpecifyMarshalingForPInvokeStringArgumentsFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.InteropServices.UseManagedEquivalentsOfWin32ApiFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetCore.Analyzers.ImmutableCollections.DoNotCallToImmutableCollectionOnAnImmutableCollectionValueFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetFramework.Analyzers.AvoidDuplicateAcceleratorsFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetFramework.Analyzers.CallBaseClassMethodsOnISerializableTypesFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetFramework.Analyzers.DoNotMarkServicedComponentsWithWebMethodFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetFramework.Analyzers.ImplementISerializableCorrectlyFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetFramework.Analyzers.ImplementSerializationMethodsCorrectlyFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetFramework.Analyzers.MarkAllNonSerializableFieldsFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetFramework.Analyzers.MarkWindowsFormsEntryPointsWithStaThreadFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetFramework.Analyzers.ProvideDeserializationMethodsForOptionalFieldsFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetFramework.Analyzers.SetLocaleForDataTypesFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetFramework.Analyzers.SpecifyMessageBoxOptionsFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.NetFramework.Analyzers.TypesShouldNotExtendCertainBaseTypesFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'StyleCop.Analyzers.OrderingRules.ElementOrderCodeFixProvider' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Text.Analyzers.IdentifiersShouldBeSpelledCorrectlyFixer' because it's language doesn't match 'C#'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/yufeih/docfx/test/docfx.Test/docfx.Test.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/yufeih/docfx/test/docfx.Test/docfx.Test.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/yufeih/docfx/test/docfx.Test/docfx.Test.csproj'
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.CodeFixes.ApplyDiagnosticAnalyzerAttributeFix' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Xunit.Analyzers.FixProviders.MemberFixBase' because it's language doesn't match 'C#'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/yufeih/docfx/src/Microsoft.Docs.Template/Microsoft.Docs.Template.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/yufeih/docfx/src/Microsoft.Docs.Template/Microsoft.Docs.Template.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/yufeih/docfx/src/Microsoft.Docs.Template/Microsoft.Docs.Template.csproj'
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.CodeFixes.ApplyDiagnosticAnalyzerAttributeFix' because it's language doesn't match 'C#'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: docfx
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: docfx.Test
[fail]: OmniSharp.MSBuild.ProjectManager
        Exception thrown while calling event sinks
System.IO.IOException: kqueue() error at init, error code = '24'
  at System.IO.KqueueMonitor.Start () [0x00046] in <f8bb3922e51744d9ace1aa6aedc374ea>:0 
  at System.IO.KeventWatcher.StartDispatching (System.IO.FileSystemWatcher fsw) [0x00033] in <f8bb3922e51744d9ace1aa6aedc374ea>:0 
  at System.IO.FileSystemWatcher.Start () [0x00000] in <f8bb3922e51744d9ace1aa6aedc374ea>:0 
  at System.IO.FileSystemWatcher.set_EnableRaisingEvents (System.Boolean value) [0x00014] in <f8bb3922e51744d9ace1aa6aedc374ea>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileSystemWatcher.set_EnableRaisingEvents(bool)
  at Microsoft.AspNetCore.Razor.OmniSharpPlugin.MSBuildProjectDocumentChangeDetector.ProjectLoaded (OmniSharp.MSBuild.Notification.ProjectLoadedEventArgs loadedArgs) [0x0026e] in <093cbf5c963a4aedba1c75ce31b806d6>:0 
  at OmniSharp.MSBuild.ProjectManager.ProcessQueue (System.Threading.CancellationToken cancellationToken) [0x00198] in <e3558be052b6471090d5ea13b15463f3>:0 
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Microsoft.Docs.Template
</details>

## Environment information ##

**VSCode version**: 1.33.1
**C# Extension**: 1.19.0

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.10.1</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.104/

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.1.101 [/usr/local/share/dotnet/sdk]
  2.1.300 [/usr/local/share/dotnet/sdk]
  2.2.101 [/usr/local/share/dotnet/sdk]
  2.2.103 [/usr/local/share/dotnet/sdk]
  2.2.104 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.22.1|
|csharp|ms-vscode|1.19.0|
|markdown-all-in-one|yzhang|2.3.1|
|mustache|dawhite|1.1.1|
|vetur|octref|0.19.4|
|vscode-eslint|dbaeumer|1.8.2|
|vscode-npm-script|eg2|0.3.5|
|vscode-proto3|zxh404|0.2.2|
|vscode-yaml|redhat|0.4.0|
|vscodeintellicode|VisualStudioExptTeam|1.1.5|
|vsliveshare|ms-vsliveshare|1.0.125|;

</details>

**Comment by filipw** [comment]
According to the log, OmniSharp picks your global Mono which is 5.10.1 - however since 1.19.0 version of the extension, Mono 5.18.1 is the minimum required (#3000)

Could you please update to the latest Mono from here https://www.mono-project.com/download/stable/ (there is 5.20.1 already) - and see if it helps?

This looks like the same problem as in #3034

**Comment by SzeNowy** [comment]
I had the same problem. After installation _Mono 5.18.1 (Visual Studio channel*)_ from the page above, like filipw commented all works.

**Comment by yufeih** [comment]
Thank you @filipw , this is resolved.
