### ISSUE TITLE
[Feature Request] Configure folding "levels"

### ISSUE THREAD

**Issue by lonix1** [OmniSharp/omnisharp-vscode#3045]
VSCode: 1.33.1
C# Extension: 1.19.0

Now that vscode has a [folding API](https://github.com/OmniSharp/omnisharp-vscode/issues/2335) it would be nice to be able to configure the folding "level" or hierarchy.

Suppose I fold the document, which has this:

````cs
public void foo() {
  if (true) {
  }
  else {
  }
}
````

That control block is also folded, which is VERY annoying. When I expand, I expect everything therein to be expanded too - but the way it works now is I need to expand multiple times.

This could be controlled with a config option that would not auto-fold anything within some level... I would set it to `1` - only fold methods, not their contents.

**Comment by rchande** [comment]
@lonix1 Do you mean that use use the "Fold Document" command and then have to manually re-expand nodes? The C# extension only provides the set of folding ranges to VS Code. All of the commands to fold/unfold regions are owned by VS Code as far as I know--I'd recommend filing this issue against VS Code itself. 

I'm going to close this issue, but feel free to comment if I've misunderstood you.

**Comment by lonix1** [comment]
So omnisharp provides the details for folding in the way I've explained, but it's up to vscode to actually use that data?

In other words, omnisharp already provides this level of granularity, but vscode ignores it?
