### ISSUE TITLE
"Cannot find or open the PDB file" pops up after debugging 

### ISSUE THREAD

**Issue by Jepson109** [OmniSharp/omnisharp-vscode#3052]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-011799
 Commit:    3816213dde

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview6-011799/

Host (useful for support):
  Version: 3.0.0-preview6-27707-07
  Commit:  c9e7f134dc

.NET Core SDKs installed:
  3.0.100-preview6-011799 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview6-19257-04 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27707-07 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
VS Code version: 1.33.1
C# Extension version: 1.19 (v1.19.1)
## Steps to reproduce
1. Create a new ASP.NET Razor project by doing
 
 
	mkdir razor
	cd razor
	dotnet new razor

2. Open razor with VScode
3. It may ask at the bottom right to install assets to build and debug, say yes.  
4. After it has done this it will have created a .vscode directory in the ‘razor’ directory and a ‘launch.json’ file in that directory.   Open the ‘.vscode’ directory, and double click on the ‘launch.json to edit it. 
5. Add the following lines after the “name” line of the “Configurations” object.   (This allows debugging through the framework.  
	 
		"justMyCode": false,
		"symbolOptions": {
		      "searchMicrosoftSymbolServer": true
		},
		"suppressJITOptimizations": true,
 
 
6. Double click on the ‘Startup.cs’ file in the ‘Explorer’ pane to bring up that source code. 
7.  Add the following line to the Startup.cs file at the beginning of the ‘Configure’ method (at the bottom of the file).  
	Console.WriteLine("x " + 3);
 
8. Place a breakpoint on that line (F9). 
9. Run the application until it hit that breakpoint (F5).   

## Expected  behavior
It will load symbols from the Microsoft symbol server successfully.

## Actual behavior
1. Cannot find or open the PDB file
![image](https://user-images.githubusercontent.com/38854445/57361109-4e18b100-71ae-11e9-808b-a6fa36c71a1b.png)

**Comment by gregg-miskelly** [comment]
@Jepson109 Is that one module the only one where symbols can't be found?

**Comment by gregg-miskelly** [comment]
@davidfowl do you know what repo produces Microsoft.AspNetCore.Routing.Abstractions? It looks like that assembly creates a PDB file, but doesn't publish it to symbol server. So it should either stop creating the PDB, or it should publish it.

**Comment by gregg-miskelly** [comment]
Nevermind. Found it.

**Comment by gregg-miskelly** [comment]
I moved this issue to https://github.com/aspnet/AspNetCore/issues/10113
