### ISSUE TITLE
netcoreapp3.0  console app doesn't recognize files/references correctly

### ISSUE THREAD

**Issue by mariusmathisen** [OmniSharp/omnisharp-vscode#3053]
## Issue Description ##
A simple 'dotnet new console' app targeting 'netcoreapp3.0' doesn't reference files correctly. If I switch back to 'netcoreapp2.2' it works as expected. 'dotnet restore' doesn't help.

![image](https://user-images.githubusercontent.com/6330828/57361558-f4e45980-717c-11e9-8420-9f094eb2e49a.png)

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
</Project>
```

I have tried setting omnisharp.useglobalmono to never - but it doesn't make any difference.

The OmniSharp log says this at the end after restore:
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        TestNetCoreIssue: Did not find 'Microsoft.NETCore.App' in lock file.

### OmniSharp log ###
<details>
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Dev\eco\TestNetCoreIssue\TestNetCoreIssue.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Dev\eco\TestNetCoreIssue\TestNetCoreIssue.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Dev\eco\TestNetCoreIssue\TestNetCoreIssue.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Dev\eco\TestNetCoreIssue\TestNetCoreIssue.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: TestNetCoreIssue
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        TestNetCoreIssue: Did not find 'Microsoft.NETCore.App' in lock file.
</details>

## Environment information ##

**VSCode version**: 1.33.1
**C# Extension**: 1.19.1

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-011223
 Commit:    118dd862c8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\

Host (useful for support):
  Version: 3.0.0-preview4-27615-11
  Commit:  ee54d4cbd2

.NET Core SDKs installed:
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-011223 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27613-28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.19.1|
|debugger-for-chrome|msjsdiag|4.11.3|
|es7-react-js-snippets|dsznajder|2.2.2|
|hex-fmt|keroc|1.0.0|
|python|ms-python|2019.4.12954|
|sftp|liximomo|1.12.4|
|team|ms-vsts|1.149.2|
|vscode-deploy-reloaded|mkloubert|0.87.2|
|vscode-docker|PeterJausovec|0.6.2|
|vscode-hexdump|slevesque|1.7.2|
|vscode-nuget-package-manager|jmrog|1.1.6|;

</details>

**Comment by filipw** [comment]
> [warn]: OmniSharp.MSBuild.PackageDependencyChecker
> TestNetCoreIssue: Did not find 'Microsoft.NETCore.App' in lock file.

this is a "false positive". 

The real issue is likely that OmniSharp selects msbuild from Visual Studio 2017 instead of the new msbuild 16 that ships with OmniSharp or with VS 2019.
The workaround would be to either install latest VS 2019 on that machine, that will allow Omnisharp to use its msbuild. This is the "better" workaround.
The "worse" workaround would be that you could... uninstall VS 2017 - this way OmniSharp would be forced to use its own msbuild 16.

**Comment by mariusmathisen** [comment]
Thank you very much @filipw ! Installing VS 2019 fixed it!
