### ISSUE TITLE
Razor syntax coloring breaks if code placed withing a sting                                         

### ISSUE THREAD

**Issue by anganti** [OmniSharp/omnisharp-vscode#3054]
Please paste the output from your clipboard

**Comment by anganti** [comment]
![image](https://user-images.githubusercontent.com/42851022/57404864-e2284f80-7191-11e9-9ffa-a74110e66c97.png)

**Comment by anganti** [comment]
In visual studio 
![image](https://user-images.githubusercontent.com/42851022/57405942-87442780-7194-11e9-8c7f-165e7560d6bb.png)

**Comment by rchande** [comment]
cc @NTaylorMullen

**Comment by NTaylorMullen** [comment]
@anganti thanks for the report! We're looking to fix this in a future release, for now we're tracking that work over at: https://github.com/aspnet/Razor.VSCode/issues/75. Stay tuned!

**Comment by anganti** [comment]
Thank you
