### ISSUE TITLE
.NET Core C# Intellisense not working on Windows, full of errors everywhere

### ISSUE THREAD

**Issue by cloudrex** [OmniSharp/omnisharp-vscode#3056]
## Issue Description ##
Intellisense not working on Windows 10 (latest update as of now), at all! Even after successful build of project.

![image](https://user-images.githubusercontent.com/41349879/57476092-e1f88480-7263-11e9-9d2a-e12ec5ae3a1b.png)
## Expected Behavior ##
Intellisense to be working.
## Actual Behavior ##
Not working, everything has an error squiggly line below it.
### OmniSharp log ###
<details>Starting OmniSharp server at 5/9/2019, 2:01:37 PM
    Target: d:\apps\Ion\Ion.Tests

OmniSharp server started.
    Path: C:\Users\Atlas\.vscode-insiders\extensions\ms-vscode.csharp-1.19.1\.omnisharp\1.32.19\OmniSharp.exe
    PID: 24996

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "C:\Users\Atlas\.vscode-insiders\extensions\ms-vscode.csharp-1.19.1\.omnisharp\1.32.19\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Users\Atlas\.vscode-insiders\extensions\ms-vscode.csharp-1.19.1\.omnisharp\1.32.19\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "C:\Users\Atlas\.vscode-insiders\extensions\ms-vscode.csharp-1.19.1\.omnisharp\1.32.19\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Users\Atlas\.vscode-insiders\extensions\ms-vscode.csharp-1.19.1\.omnisharp\1.32.19\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = C:\Users\Atlas\.vscode-insiders\extensions\ms-vscode.csharp-1.19.1\.omnisharp\1.32.19\.msbuild
            MSBuildToolsPath = C:\Users\Atlas\.vscode-insiders\extensions\ms-vscode.csharp-1.19.1\.omnisharp\1.32.19\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\apps\Ion\Ion.Tests'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'd:\apps\Ion\Ion.Tests'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\apps\Ion\Ion.Tests\IonTests.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\apps\Ion\Ion.Tests'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\apps\Ion\Ion.Tests\IonTests.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\apps\Ion\Ion.Tests' on host 19960.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\apps\Ion\Ion.Tests\IonTests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\apps\Ion\Ion.Tests\IonTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: IonTests
[info]: OmniSharp.MSBuild.ProjectManager
        Found referenced project outside root directory: d:\apps\Ion\Ion\Ion.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\apps\Ion\Ion\Ion.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\apps\Ion\Ion\Ion.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\apps\Ion\Ion\Ion.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\apps\Ion\Ion\Ion.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Ion
</details>

### C# log ###
<details>*Empty*</details>

## Environment information ##

**VSCode version**: 1.34.0-insider
**C# Extension**: 1.19.1

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.203
 Commit:    e5bab63eca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.203\

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.2.203 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|comment-anchors|ExodiusStudios|1.6.1|
|cpptools|ms-vscode|0.23.0|
|csharp|ms-vscode|1.19.1|
|dotenv|mikestead|1.0.1|
|Go|ms-vscode|0.10.2|
|lex-flex-yacc-bison|faustinoaq|0.0.3|
|llvm|RReverser|0.0.3|
|Material-theme|zhuangtongfa|2.22.1|
|one-monokai|azemoh|0.3.7|
|path-intellisense|christian-kohler|1.4.2|
|powershell|ms-vscode|1.12.1|
|tslint|eg2|1.0.43|
|vsc-material-theme|Equinusocio|2.8.2|
|vscode-docker|PeterJausovec|0.6.2|
|vscode-docker-syntax|dunstontc|0.1.5|
|vscode-icons|vscode-icons-team|8.6.0|
|vscode-npm-script|eg2|0.3.7|
|vscode-test-explorer|hbenl|2.10.0|
|vscodeintellicode|VisualStudioExptTeam|1.1.6|
|vsliveshare|ms-vsliveshare|1.0.125|;

</details>

**Comment by jcreek** [comment]
Similar issue on Ubuntu 18.04 here too.

**Comment by rchande** [comment]
@cloudrex Can you set the option "omnisharp.logginglevel" to "debug" and share your omnisharp log again?

**Comment by cloudrex** [comment]
Funny. This was actually happening because I was building using WSL on Windows, dumb move.
