### ISSUE TITLE
Building C# code requires a project or solution file, but VS code won't create project files.

### ISSUE THREAD

**Issue by LarryOsterman** [OmniSharp/omnisharp-vscode#3059]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Installed VS code and then the C# extension and the .Net SDK as per the workflow. When building, I get: 
Microsoft (R) Build Engine version 16.0.450+ga8dc7f1d34 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

I tried using View/Palette... to create .Net build artifacts, but that failed with:
Could not locate .NET Core project. Assets were not generated.

Not a great User experience :(.

Extension version: 1.19.1
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.97GB (19.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rchande** [comment]
@LarryOsterman What workflow did you follow? You should be creating a project file using the command `dotnet new <project type>`
