### ISSUE TITLE
Razor not copied to folder on change.

### ISSUE THREAD

**Issue by BeelzeBu** [OmniSharp/omnisharp-vscode#306]
When I change only a razor (cshtml) page and build/rebuild the solution I do not see the changes applied, files dont get copied to build folder. need to remove bin folder or change a controller to copy all new razor content.

**Comment by gregg-miskelly** [comment]
@BeelzeBu VS Code doesn't have a build system. Are you using 'dotnet build'? If so, can you reopen this in https://github.com/dotnet/cli/issues.

**Comment by BeelzeBu** [comment]
Create issue [issue](https://github.com/dotnet/cli/issues/2989) don't know how to reference

**Comment by gregg-miskelly** [comment]
Just add the URL in the comment: https://github.com/dotnet/cli/issues/2989

**Comment by gregg-miskelly** [comment]
Anyway, thank you!

**Comment by BeelzeBu** [comment]
Thx
