### ISSUE TITLE
Prompt to download updates?

### ISSUE THREAD

**Issue by greggman** [OmniSharp/omnisharp-vscode#3061]
## Issue Description ##

Plugin auto-downloads updates when I'm on a slow, costly, constrained internet connection.

## Steps to Reproduce ##

Just a guess that it happens when you release a new version

## Expected Behavior ##

It's awesome that you keep me up to date. I just wish there was a way to let me say "not a good time. I'm on my international sim at the moment"

## Actual Behavior ##

It downloads updates to OmniSharp and other dependencies without prompting with no way to stop. It even does this if I open a project that has absolutely no C# in it.

## Logs ##

Sorry, I switched projects and don't have a log of the 3 or 4 dependencies it downloaded.

### OmniSharp log ###

N/A

### C# log ###

N/A

## Environment information ##

**VSCode version**: 1.33.1
**C# Extension**: 1.19.1

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.16.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.103/

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.2.103 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|code-spell-checker|streetsidesoftware|1.7.10|
|csharp|ms-vscode|1.19.1|
|debugger-for-chrome|msjsdiag|4.11.3|
|rainbow-brackets|2gua|0.0.6|
|rewrap|stkb|1.9.1|
|shader|slevesque|1.1.4|
|unity-debug|Unity|2.7.2|
|vscode-eslint|dbaeumer|1.8.2|;

</details>

**Comment by rchande** [comment]
@greggman The C# extension will only attempt to update omnisharp if you have the option `omnisharp.path` set to `latest`. Otherwise we'll use whatever version is explicitly part of the extension. Separately, there's a VS Code setting you can set to disable extension auto-update. Finally, if you are seeing the C# extension activate where "no C#" is present, that would be a bug. Can you provide a more specific description of when that happens?

**Comment by blyaloc** [comment]
im trying to do this instead of always downloading the files:

https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-the-C%23-extension-to-a-computer-without-internet-connectivity

**Comment by Tschrock** [comment]
I'm also having this issue. It seems like every other day, I'm opening VS Code and have to wait for dependencies to download over my slow LTE connection. I have unlimited data so I'm not concerned about hitting a cap, but I'd like to be able to use the extension without waiting for hours for it to finish downloading something it already downloaded a few days ago. From what I can tell there hasn't been an extension update recently, it just somehow decides it needs to re-download it?? Like, it had been working, and then I reloaded the VS Code window and now it's downloading it again?  A config option to say "always prompt before downloading" would be great.

```
Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (35884 KB)...............
```

**Comment by filipw** [comment]
there is an extension release only about once every 2-4 weeks. is your configuration set to "omnisharp.path": "latest"?

**Comment by Tschrock** [comment]
I don't have any omnisharp settings set, so 'omnisharp.path' should be whatever it's default is.

I dug around a bit and it looks like the extension did update - though it's a bit weird. VS Code says the extension was updated 3 days ago, but if I look at the logs from when I opened it today, it loaded with the previous version - until I restarted VS Code and it switched to the new version (which caused it to start trying to download all the dependencies again). I was able to find both versions of the extension in the extensions folder, and copied the `.razor`/`.omnisharp`/`.razor` folders to the new version (and renamed the omnisharp version folder to the right version) and was able to skip the download for now.

**Comment by jmarolf** [comment]
If you do not have VS Code update the extension automatically then it will not attempt to download and install updated omnisharp binaries.  Add These settings to you VS Code settings file and manually update the extension when it makes most sense to you.

```json
{
  "extensions.autoCheckUpdates": false,
  "extensions.autoUpdate": false
}
```
