### ISSUE TITLE
How to enable native code debugging like Visual Studio?

### ISSUE THREAD

**Issue by elishateng** [OmniSharp/omnisharp-vscode#3068]
## Environment data
`dotnet --info` output: 2.1.500
VS Code version: 1.33.1
C# Extension version: 1.19.1

## Steps to reproduce
none.

## Expected  behavior
I want to debug c# codes into c++ codes, Visual Studio can make it through enable native code debugging, but Visual Studio Code seems can't.

## Actual behavior
Just can debug c# codes.

**Comment by gregg-miskelly** [comment]
Hi @elishateng,

If you are trying to switch back and forth between debugging native code and .NET Core, you can use the debugger from the C++ extension (debug type = `cppvsdbg'). In other words you can launch the process (or attach) using the native debugger. If you determine that you actually need to be managed debugging, you stop debugging and relaunch (or attach) using the  .NET debugger.

If you really want to debug both at the same time ('Mixed' or 'Interop' debugging) -- that feature is only available in full Visual Studio.

**Comment by elishateng** [comment]
Hi, @gregg-miskelly ,
Thank you for your response.
