### ISSUE TITLE
Poor performance while expanding variables in debug view

### ISSUE THREAD

**Issue by gaudigde** [OmniSharp/omnisharp-vscode#3069]
Issue Type: <b>Performance Issue</b>

## Steps

1. Open the project [SlowDebugger.zip](https://github.com/OmniSharp/omnisharp-vscode/files/3186190/SlowDebugger.zip).
2. Set a breakpoint in line 17 (end of the main method).
3. Hit F5.
4. When the breakpoint is hit, expand the `foobar` variable in the debug view.

## Result

The expansion of the variable `foobar` takes several seconds.

## Expectations

Same speed as when debugging in Windows.

Extension version: 1.19.1
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.18.0-13-generic (Linux Mint 19.1)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.64GB (6.10GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|100%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   144	 19419	code main
    0	    32	 19422	   zygote
    0	   304	 19472	     window (SlowDebugger - Program.cs - Visual Studio Code)
    0	   224	 19496	       extensionHost
    0	   144	 19606	         electron_node server.js 
    0	   288	 19653	         mono --assembly-loader=strict 
/home/xxx/.vscode/extensions/ms-vscode.csharp-1.19.1/.omnisharp/1.32.19/omnisharp/OmniSharp.exe -s /home/xxx/Development/SlowDebugger --hostPID 19496 DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin /home/xxx/.vscode/extensions/ms-vscode.csharp-1.19.1/.razor/OmniSharpPlugin/Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
    0	    64	 19785	         electron_node server.js 
    0	   112	 20254	         /home/xxx/.vscode/extensions/ms-vscode.csharp-1.19.1/.debugger/vsdbg-ui
    0	    32	 20270	           /usr/bin/dotnet /home/xxx/Development/SlowDebugger/bin/Debug/netcoreapp2.2/SlowDebugger.dll
    0	    48	 19511	       watcherService
    0	    48	 19554	       searchService
    0	    48	 19935	       /usr/share/code/code /usr/share/code/resources/app/out/bootstrap-fork ms-vscode.coreclr {"common.vscodemachineid":"b682d5e1d8a0ac304bf7651b96b661321d56abfdf90088ed84244448cad0dc52","common.vscodesessionid":"1165e534-1084-4948-bded-1008832b2c8b1557993090473"} AIF-d9b70cd4-b9f9-4d70-929b-a071c400b217
    0	   128	 19532	     shared-process
    1	    96	 20363	     window (Issue Reporter)
    0	   112	 19457	   gpu-process
    0	     0	 20386	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 20387	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (SlowDebugger - Program.cs - Visual Studio Code)
|    Folder (SlowDebugger): 22 files
|      File types: json(7) cache(5) cs(2) dll(2) pdb(2) csproj(1) props(1)
|                  targets(1) txt(1)
|      Conf files: csproj(1) launch.json(1) tasks.json(1);
```

</details>

**Comment by gregg-miskelly** [comment]
Yes, the root cause (or at last the primary root cause) is https://github.com/dotnet/coreclr/issues/22315. The CLR team is looking to address this. Hopefully for .NET Core 3.0.

**Comment by gaudigde** [comment]
I can confirm that this issue no longer exists when using .NET Core 3.0. Thanks a lot for fixing this!
