### ISSUE TITLE
netcoreapp3.0 project does not start browser

### ISSUE THREAD

**Issue by mikes-gh** [OmniSharp/omnisharp-vscode#3073]
## Issue Description ##

When starting Server Side Blazor project in debug mode browser does not start even though it is set to in the launch.json

Browser starts OK  in VS 2019 ok (it uses launchSettings.json)

App does start correctly its just you have to copy url from startup log into browser address bar

## Steps to Reproduce ##

git clone https://github.com/mikes-gh/WebApplication1.git
F5

## Expected Behavior ##

Browser Starts with URL of app

## Actual Behavior ##

Browser does not start.  Have to start browser manually and copy and paste URL.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.33.1
**C# Extension**: 1.19.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview5-011568/

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  2.2.105 [/usr/local/share/dotnet/sdk]
  3.0.100-preview5-011568 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.19.1|
|debugger-for-chrome|msjsdiag|4.11.3|
|gitlens|eamodio|9.7.3|
|mssql|ms-mssql|1.6.0|
|vscode-eslint|dbaeumer|1.8.2|;

</details>

**Comment by gregg-miskelly** [comment]
@mikes-gh I believe I resolved this already in internal builds. If you look through the debug console, you should see a line like `Now listening on: <some-url-here>`. Do you have that? Does it start with white space?

**Comment by mikes-gh** [comment]
On netcore 2.2

```
Launching browser (cmd.exe /C start http://localhost:5000)
Now listening on: http://localhost:5000
Now listening on: https://localhost:5001
Application started. Press Ctrl+C to shut down.
```

On netcore 3
```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
Microsoft.Hosting.Lifetime: Information: Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
Microsoft.Hosting.Lifetime: Information: Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
Microsoft.Hosting.Lifetime: Information: Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\mikes\Repos\WebApplication1
Microsoft.Hosting.Lifetime: Information: Hosting environment: Development
```

usinf the new

```
"serverReadyAction": {
        "action": "openExternally",
        "pattern": "^\\s*Now listening on:\\s+(https?://\\S+)"
    }
```
One comment with the new config is not immediately obvious that it launches the browser

What is the meaning of openExternally?

**Comment by mikes-gh** [comment]
Just tried 1.34 and note the problem is still there.  Is the new config for launch.json generated in a later build?

**Comment by mikes-gh** [comment]
Just tried 1.20 and this is now fixed for me with the new serverReadyAction config
