### ISSUE TITLE
VS Code extension, debugging: Suggest stopping debugging if browser or browser tab exits

### ISSUE THREAD

**Issue by dougbu** [OmniSharp/omnisharp-vscode#308]
Not quite sure how VS does this but it seems to end debugging sessions when you close the browser tab it opened. Seems nice to have for VS Code as well (if possible x-plat).

Suggest controlling this with a new configuration property in `launch.json`. Should probably be enabled in the default `.NET Core Launch (web)` configuration.

**Comment by gregg-miskelly** [comment]
We actually only do this for IE. For all other browsers, we have no way of tracking their lifetime. Sorry, can't fix this.
