### ISSUE TITLE
Property inspector hides properties

### ISSUE THREAD

**Issue by richlander** [OmniSharp/omnisharp-vscode#3081]
The property inspector is hard to use when only one property is shown.

This is what I see by default:

![image](https://user-images.githubusercontent.com/2608468/58190950-71456500-7c72-11e9-80fd-e2ab2021681c.png)

I can mouse-wheel to make it easier to use, but it is still hard to use:

![image](https://user-images.githubusercontent.com/2608468/58190976-80c4ae00-7c72-11e9-9b61-d714d179bd21.png)

This is latest VS Code and Omnisharp extension. It has been bad for a while, but it is worse now. I think Windows 10 1903 is now making it worse.

**Comment by rchande** [comment]
cc @gregg-miskelly, but I think this is probably VS Code issue (they control the presentation).

**Comment by gregg-miskelly** [comment]
@richlander To make sure I understand, the issue you are seeing is with the size of the window being too small to be useful?

**Comment by richlander** [comment]
@gregg-miskelly ... yes. The experience is different (better) on macOS. The Windows experience is markedly worse for this.

**Comment by gregg-miskelly** [comment]
@richlander this is definitely a VS Code issue. Do you want us to port the problem over there for you, or do you want to open a new issue yourself? I am guessing this is DPI related, so it is probably useful to provide the DPI settings for your various monitors.

**Comment by rchande** [comment]
@richlander As Gregg mentioned, it will be more useful for you to file this against VS Code yourself along with version/DPI info. I'm going to close this copyl
