### ISSUE TITLE
Disable notification on projects failing to load

### ISSUE THREAD

**Issue by zivcaspi** [OmniSharp/omnisharp-vscode#3086]
Issue Type: <b>Bug</b>

Open VSCode with the C# extension on a folder with hundreds of projects but with some systemic issue around project loading. --> The toast message "Some projects have trouble loading. Please review the output for more details." will pop up hundreds of times (I guess once per such project) until one gives up and opens another editor instead.

Extension version: 1.19.1
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:53.881Z)
OS version: Windows_NT ia32 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (15.29GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rchande** [comment]
@zivcaspi You should able to suppress those by setting `"omnisharp.disableMSBuildDiagnosticWarning": false`
