### ISSUE TITLE
Debugging failed that "Could not locate .NET Core project. Assets were not generated.".

### ISSUE THREAD

**Issue by YunWeiaa** [OmniSharp/omnisharp-vscode#3087]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012103
 Commit:    d0d02f6552

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview6-012103/

Host (useful for support):
  Version: 3.0.0-preview6-27728-04
  Commit:  b2f8fc281d

.NET Core SDKs installed:
  2.1.505 [/usr/local/share/dotnet/sdk]
  3.0.100-preview6-012103 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6-19278-02 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27728-04 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

VS Code version: 1.34
C# Extension version: 1.19 (v1.19.1)

## Steps to reproduce
• Create new .NET Core 3.0 console application(con30) with reference to a .NET Standard 2.1 class library(cla21) via CLI,
![image](https://user-images.githubusercontent.com/33921754/58545033-4d74a880-81b7-11e9-90dd-3dd0d87222ed.png)
• Open it via VSCode
• Debug the app – Put breakpoint in the code and press F5, it shows a prompt message that “Could not find the task 'build'”:
![image](https://user-images.githubusercontent.com/33921754/58544756-c6273500-81b6-11e9-8df2-ed1fd6b10d4f.png)
• Then open “launch.json”, press “Add Configuration…”, the “launch.json” file generator hasn't updated the parts in <>.
![image](https://user-images.githubusercontent.com/33921754/58545234-b0fed600-81b7-11e9-93a2-5a8fe5fed5e0.png)
• Run the '.NET: Generate Assets for Build and Debug' command from command pallet, 
![image](https://user-images.githubusercontent.com/33921754/58545384-fde2ac80-81b7-11e9-8cad-82058494a05d.png)
## Expected  behavior
Get a functional launch.json
## Actual behavior
Could not locate .NET Core project. Assets were not generated.
![image](https://user-images.githubusercontent.com/33921754/58545528-4a2dec80-81b8-11e9-9776-836314cf17b5.png)

**Comment by niranjanbohra** [comment]
Facing the same issue

**Comment by Elrouille** [comment]
Facing similar issue when creating a new MVC project.

**Comment by YunWeiaa** [comment]
Not repro on 3.0.100-preview6-012234 (runtime-3.0.0-preview6-27730-01)(https://github.com/dotnet/core-sdk)

**Comment by omarfq** [comment]
Im facing the exact same issue.

**Comment by gregg-miskelly** [comment]
@omarfq can you copy/paste your OmniSharp log or open a new issue with it?

**Comment by omarfq** [comment]
@gregg-miskelly sure. Just so you know, I created a console app using `dotnet new console`. When I open the folder where the project is located using the command `code .` I get this notification as soon as VSCode opens: 
<img width="548" alt="Screen Shot 2019-07-18 at 7 06 46 PM" src="https://user-images.githubusercontent.com/43190119/61498620-fa86c880-a991-11e9-9a6c-9ad8c689e4d0.png">

Here's the OmniSharp Log (not sure if this is the one you are asking for):

![Screen Shot 2019-07-18 at 7 33 50 PM](https://user-images.githubusercontent.com/43190119/61498901-2d7d8c00-a993-11e9-8cf6-c5216b14a8b3.png)
![Screen Shot 2019-07-18 at 7 34 17 PM](https://user-images.githubusercontent.com/43190119/61498913-39694e00-a993-11e9-8d2f-b830ff458e7d.png)

**Comment by omarfq** [comment]
I managed to solve the issue by following the steps from this comment:
https://github.com/OmniSharp/omnisharp-vscode/issues/2509#issuecomment-420318250

As far as I can tell, the root cause of this problem has to do with the OmniSharp.MSBuild.ProjectManager. By attempting to fix the following error I managed to solve all the other subsequent errors:

![Screen Shot 2019-07-18 at 9 41 24 PM](https://user-images.githubusercontent.com/43190119/61503270-1e9fd500-a9a5-11e9-9948-e0937b626f9a.png)

**Comment by YunWeiaa** [comment]
Not repro on the latest build.

**Comment by spottedmahn** [comment]
>Not repro on the latest build

What build is that?  I'm on 1.21.10 and came across this problem today.

**Comment by danumpaquec** [comment]
Same problem
VS Code 1.43.2
C# Extension 1.21.16
If you are looking for a solution like i was, install **MSBuild project tools** as sugested in the changelog of C# Extension (I noticed it when i was looking for the Ext version ¯\_(ツ)_/¯ )
Link to the MSBuild project tools Extension: https://marketplace.visualstudio.com/items?itemName=tintoy.msbuild-project-tools

**Comment by billjacobi** [comment]
Same problem on 1.21.18 and .net core 3.1.201.

**Comment by markusmo** [comment]
just occured to me too...

**Comment by KitsuneShan** [comment]
I am having the same issue and I can't find any solution that works.
I just started learning so I am not aware of every possibility that I can try.
I just installed VSC today followed by the .Net Core SDK 3.1 and the C# extension.
I simply write "don't new console" on the terminal to generate the hello world project.
Then I click F5 which prompts me to select from a list of different environments.
I selected .Net Core one and all I get are errors that .NET Core project couldn't be located and assets were not generated.
If I use ".NET Generate Assets for Build and Debug" all I get it's that same error.
It's there a way of fixing this, please? I am too new to dig deeper into this. I looked and researched all around Google but no solution found yet or the mentioned methods are beyond my limited knowledge about the subject.
I would share my OmniSharp logs but I have no idea how to collect these, sorry.

**Comment by xpoftik** [comment]
If you are working in remote-container just set correct path to your workspace folder. In my case all projects are in "src" folder, so I just changed path to "workspaceFolder": "/workspace/src".

**Comment by JoeRobich** [comment]
@KitsuneShan When you ran `dotnet new console` did it also create a .csproj file along side the Program.cs file? If you reopen the folder that contains the .csproj, are you able to generate launch assets?

**Comment by BlueMax15** [comment]
So..how do I "Create new .NET Core 3.0 console application(con30) with reference to a .NET Standard 2.1 class library(cla21) via CLI"?

**Comment by atom0s** [comment]
Just ran into this as well, but was able to fix it via:

  * Close all instances of Visual Studio Code.
  * Open the folder that contains the project you are trying to compile/use.
  * Delete the `.vscode` folder. (Make a backup if needed of any important files/configurations made already.)
  * Open the folder in VSCode now.
  * Open VSCode Command Palette and choose `> .NET: Generate Assets For Build and Debug`.

For me, this fixes it and it's able to generate the assets properly at this point. I can then run and debug my test project.

_(This expects a valid project to be created already, such as with `dotnet new console` or similar.)_

**Comment by raviarora1209** [comment]
Hey, I was able to find the issue causing this...If your folder has a spacebar, hash or any such symbol, you can see it causes a problem in the root namespace in the CSProj folder. For example, I named my folder :- "C# Try"(stupid mistake). I opened the CSProj file and noticed the weird naming as it read "C__Try". 
![image](https://user-images.githubusercontent.com/46346108/94356166-e582ea80-00a8-11eb-8c85-5bcb200ac88e.png)
After diagnosing this, I was able to fix it by closing VSCode, renaming the folder and reopening it, and changing the <RootNamespace> attribute in the CSProj. Hope it can help some people.

**Comment by MokshHaria** [comment]
> Just ran into this as well, but was able to fix it via:
> 
> * Close all instances of Visual Studio Code.
> * Open the folder that contains the project you are trying to compile/use.
> * Delete the `.vscode` folder. (Make a backup if needed of any important files/configurations made already.)
> * Open the folder in VSCode now.
> * Open VSCode Command Palette and choose `> .NET: Generate Assets For Build and Debug`.
> 
> For me, this fixes it and it's able to generate the assets properly at this point. I can then run and debug my test project.
> 
> _(This expects a valid project to be created already, such as with `dotnet new console` or similar.)_

I tried this but it was still not working

**Comment by amid0u** [comment]
> @omarfq can you copy/paste your OmniSharp log or open a new issue with it?

Thank You 🙏🙏🙏🙏

**Comment by Asthnesis** [comment]
For anyone still facing the same issue. You can try uninstalling the C# extension and reinstalling it. That fixed it for me

**Comment by meofiscoding** [comment]
> For anyone still facing the same issue. You can try uninstalling the C# extension and reinstalling it. That fixed it for me

no thats not work :(

**Comment by farzanemaleki** [comment]
same issues :(

**Comment by ifde** [comment]
Same Issue on MacOs
