### ISSUE TITLE
Inline Helper do not work

### ISSUE THREAD

**Issue by felixgerdes** [OmniSharp/omnisharp-vscode#3092]
## Issue Description ##
Hello,

in  my different C# projects i get two helpers. But one of them do nothing. There are no hints or fixtures. Is there a way to disable the broken one. Please see my attachments. The bulb works great, but the inline feature never suggest anything. 

Im note sure, weither it coud be an issue caused by some extensionens. 

This is just minimal disturbing. Thanks for you work and normally an awesome omnisharp!
## Expected Behavior ##
Same hints of both helpers.
## Actual Behavior ##
One never suggest anything. The other on works perfect.
<img width="628" alt="Bildschirmfoto 2019-06-02 um 16 07 16" src="https://user-images.githubusercontent.com/6943462/58762463-8a8ec100-8550-11e9-802c-c76e5a01a55c.png">
<img width="590" alt="Bildschirmfoto 2019-06-02 um 15 53 43" src="https://user-images.githubusercontent.com/6943462/58762467-95e1ec80-8550-11e9-90f5-41e2b1226fce.png">

### OmniSharp log ###
<details>Starting OmniSharp server at 6/2/2019, 3:51:28 PM
    Target: /Users/felixgerdes/Desktop/Programmieren/person

OmniSharp server started.
    Path: /Users/felixgerdes/.vscode/extensions/ms-vscode.csharp-1.19.1/.omnisharp/1.32.19/run
    PID: 97687

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.13 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "/Users/felixgerdes/.vscode/extensions/ms-vscode.csharp-1.19.1/.omnisharp/1.32.19/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/Users/felixgerdes/.vscode/extensions/ms-vscode.csharp-1.19.1/.omnisharp/1.32.19/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "/Users/felixgerdes/.vscode/extensions/ms-vscode.csharp-1.19.1/.omnisharp/1.32.19/omnisharp/.msbuild/Current/Bin"
            MSBuildExtensionsPath = /Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/xbuild
            BypassFrameworkInstallChecks = true
            CscToolPath = /Users/felixgerdes/.vscode/extensions/ms-vscode.csharp-1.19.1/.omnisharp/1.32.19/omnisharp/.msbuild/Current/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /Users/felixgerdes/.vscode/extensions/ms-vscode.csharp-1.19.1/.omnisharp/1.32.19/omnisharp/.msbuild/Current/Bin
            TargetFrameworkRootPath = /Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/xbuild-frameworks
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/felixgerdes/Desktop/Programmieren/person'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/felixgerdes/Desktop/Programmieren/person'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/felixgerdes/Desktop/Programmieren/person/person.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/felixgerdes/Desktop/Programmieren/person'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/felixgerdes/Desktop/Programmieren/person/person.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/felixgerdes/Desktop/Programmieren/person' on host 97655.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/felixgerdes/Desktop/Programmieren/person/person.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/felixgerdes/Desktop/Programmieren/person/person.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: person
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.CodeFixes.ApplyDiagnosticAnalyzerAttributeFix' because it's language doesn't match 'C#'.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: System.DateTime
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: using System;
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: using person.Context;
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: Implement interface
</details>

### C# log ###
<details>Its empty</details>

## Environment information ##

**VSCode version**: 1.34.0
**C# Extension**: 1.19.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.19.1|
|csharpextensions|jchannon|1.3.0|
|debugger-for-chrome|msjsdiag|4.11.3|
|git-add-remote|samschneller|0.0.2|
|html-css-class-completion|Zignd|1.19.0|
|html-snippets|abusaidm|0.2.1|
|javascript-typescript|sourcegraph|0.0.7|
|jquerysnippets|donjayamanne|0.0.1|
|open-html-in-browser|coderfee|0.1.21|
|react-beautify|taichi|0.3.0|
|react-native-react-redux-snippets-for-es6-es7-version-standard|EQuimper|1.0.3|
|simple-react-snippets|burkeholland|1.2.2|
|vetur|octref|0.21.0|
|vscode-boot-dev-pack|Pivotal|0.0.8|
|vscode-docker|PeterJausovec|0.6.2|
|vscode-language-pack-de|MS-CEINTL|1.34.2|
|vscode-react-native|msjsdiag|0.9.3|
|vscode-spring-boot|Pivotal|1.7.0|
|vscode-spring-boot-dashboard|vscjava|0.1.5|
|vscode-spring-initializr|vscjava|0.4.5|;

</details>

**Comment by rchande** [comment]
@felixgerdes Can you try disabling extensions of the than the C# extension and see if this still happens?

**Comment by felixgerdes** [comment]
@rchande I just disabled all Extensions except the Omnisharp Extension and and restarted my VSCode. The behavior is still the same. The bulb gives hints and shortcuts. The Mouseover says "No Codeaction is avaible". (It´s my translation from the german sentence). 

Is my expactation right, that the option should contain some actions for me? Or do i have a wrong understanding of the feature?

**Comment by rchande** [comment]
@felixgerdes I'm speculating (need to confirm) but the new popup view you see is a relatively new VS Code feature and we may need to do some work to fill in the suggestions. Thanks for reporting.

**Comment by felixgerdes** [comment]
@rchande no problem! Thanks for your awesome IDE. I think i was struggeling with this, cause im used to enjoy such a great quality!
