### ISSUE TITLE
.NET CLI tools cannot be located

### ISSUE THREAD

**Issue by siddjain** [OmniSharp/omnisharp-vscode#3094]
## Environment data
`dotnet --info` output:

```
$ dotnet --info
-bash: dotnet: command not found
```

VS Code version: Version 1.31.1 (1.31.1)
C# Extension version: Version 1.31.1 (1.31.1)

## Steps to reproduce
Install extension. 

## Expected  behavior
No error

## Actual behavior
displays a message .NET CLI tools cannot be located . 
https://imagebin.ca/v/4jMFsy5m9XN6
and prompts to install .NET CLI tools - but I do have mono installed (I think .NET CLI tools come with mono)

I have mono installed
```
$ mono --version
Mono JIT compiler version 5.18.1.3 (2018-08/fdb26b0a445 Wed Mar 20 10:02:02 EDT 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       preemptive
	GC:            sgen (concurrent by default)
```

https://imagebin.ca/v/4jMHnbwv0XVU says mono debugging is not supported. Does that mean this extension does not work on mac?

**Comment by gregg-miskelly** [comment]
@siddjain The .NET CLI doesn't come with mono.

What type of project are you working on? (ex: .NET Core, Unity, some other mono scenario, etc)

**Comment by siddjain** [comment]
I am developing C# applications on Mac. To do that, I installed Mono as well as VS Code and C# Extension. So should I click on the prompt to install .NET CLI? What about the warning here: https://imagebin.ca/v/4jMHnbwv0XVU
Mono debugging is not supported. Does that mean I won't be able to debug my C# code in VS Code? Thanks

________________________________

**Comment by gregg-miskelly** [comment]
Can you better define "C# applications" -- are you talking about an application running on Mono?

If yes -
* You don't need to install the .NET CLI. You can disable the prompt by turning on 'csharp.suppressDotnetRestoreNotification' in VS Code preferences.
* You will need the Mono Debug extension to debug your code in VS Code

**Comment by siddjain** [comment]
I am developing a C# application to run on Mac. So I think the answer to the question is Yes

________________________________

**Comment by gregg-miskelly** [comment]
Okay, I will close this then. Let us know if you need more help.
