### ISSUE TITLE
Unable to generate assets to build and debug

### ISSUE THREAD

**Issue by perfmlin** [OmniSharp/omnisharp-vscode#3098]
## Issue Description ##
Unable to generate assets to build and debug
### OmniSharp log ###
<details>Starting OmniSharp server at 2019/6/6 上午9:44:38
    Target: e:\x-netcore\hello

OmniSharp server started.
    Path: C:\Users\Administrator\.vscode\extensions\ms-vscode.csharp-1.19.1\.omnisharp\1.32.19\OmniSharp.exe
    PID: 9552

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).</details>

### C# log ###
<details></details>

## Environment information ##

**VSCode version**: 1.35.0
**C# Extension**: 1.19.1

<details><summary>Dotnet Information</summary>
.NET Core SDK����ӳ�κ� global.json��:
 Version:   2.2.107
 Commit:    2212cac826

����ʱ����:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.107\

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.2.107 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|android-dev-ext|adelphes|0.6.2|
|auto-close-tag|formulahendry|0.5.6|
|auto-rename-tag|formulahendry|0.1.0|
|autorest|ms-vscode|2.0.1|
|beautify|HookyQR|1.5.0|
|code-spell-checker|streetsidesoftware|1.7.16|
|color-highlight|naumovs|2.3.0|
|cpptools|ms-vscode|0.23.1|
|csharp|ms-vscode|1.19.1|
|dart-code|Dart-Code|3.1.0|
|docthis|joelday|0.7.1|
|gitlens|eamodio|9.8.1|
|Go|ms-vscode|0.10.2|
|java|redhat|0.46.0|
|JavaScriptSnippets|xabikos|1.7.2|
|LiveServer|ritwickdey|5.6.1|
|logcat|abhiagr|0.0.7|
|mq4|nervtech|1.0.4|
|nunjucks|ronnidc|0.2.3|
|partial-diff|ryu1kn|1.4.0|
|path-intellisense|christian-kohler|1.4.2|
|php-intellisense|felixfbecker|2.3.10|
|propertylist|zhouronghui|0.0.2|
|python|ms-python|2019.5.18678|
|react-beautify|taichi|0.3.0|
|react-redux-es6-snippets|timothymclane|2.1.0|
|ReactSnippets|xabikos|2.3.0|
|ReactSnippetsStandard|TimonVS|1.1.0|
|rest-client|humao|0.21.3|
|rxjs-snippets|pkosta2006|0.0.2|
|sass-indented|robinbentley|1.5.1|
|swagger-viewer|Arjun|2.2.2|
|tslint|eg2|1.0.43|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-color|anseki|0.4.5|
|vscode-eslint|dbaeumer|1.9.0|
|vscode-extension-auto-import|moppitz|1.3.3|
|vscode-generate-getter-setter|DSKWRK|0.5.0|
|vscode-icons|vscode-icons-team|8.7.0|
|vscode-instant-markdown|dbankier|1.4.4|
|vscode-java-debug|vscjava|0.19.0|
|vscode-java-dependency|vscjava|0.4.0|
|vscode-java-pack|vscjava|0.7.1|
|vscode-java-test|vscjava|0.17.0|
|vscode-markdownlint|DavidAnson|0.27.0|
|vscode-maven|vscjava|0.17.0|
|vscode-todo-parser|minhthai|1.9.1|
|vscodeintellicode|VisualStudioExptTeam|1.1.6|;

</details>

**Comment by rchande** [comment]
@perfmlin It sounds like something is wrong with your installation. I would recommend uninstalling and reinstalling, if you're still having issues.
