### ISSUE TITLE
C# project - search for symbol or search for file regularly takes forever and needs to compile

### ISSUE THREAD

**Issue by alexandrudima** [OmniSharp/omnisharp-vscode#31]
Moved from microsoft/vscode#2820
From @rsunkabam

unity3d project workspace.  Using cmd-T or cmd-P more often than not results in a very long wait time before completion results appear.  If the file in question was recently opened it's nearly immediate, but if not, it could take 15+ seconds.  This makes it severely limited in usefulness for larger projects.

Can't seem to find option that pre-compiles everything to cache symbols, or continues parsing/compiling while working until it's all consumed.

suggest an option that does just that, such that symbol navigation works more like monodevelop, and any symbol I care about is ready to find at any moment.

**Comment by DustinCampbell** [comment]
@rsunkabam: I'm curious to know if this is still an issue for you with the latest version of the C# extension. Thanks!

**Comment by RogueRocketGames** [comment]
@DustinCampbell it seems to be a little better than before (vscode 1.4) but on full product scope projects it's still painfully delayed looking for symbols.  It works a lot better on smaller projects.
My understanding is that vscode isn't storing any kind of symbol db like full visual studio does, so in large projects it takes forever to process symbols.

**Comment by DustinCampbell** [comment]
This may be improved in the latest release (1.5.2). The extension's communication with the OmniSharp server worked in such a way that it would often block on requests before allowing other requests through. This has been changed in the new releases and could help this scenario greatly.

**Comment by rchande** [comment]
@rsunkabam @RogueRocketGames We haven't heard back from you in a *long* time so I'm closing this issue. Feel free to file a new one if you're still experiencing problems.
