### ISSUE TITLE
the C# plugin output error, showing:Error: connect ECONNREFUSED 127.0.0.1:10803

### ISSUE THREAD

**Issue by jiayaoO3O** [OmniSharp/omnisharp-vscode#3101]
## Issue Description ##
I tried to debug dotnet core in the server using **vscode remote mode**, but the the C# plugin output error, showing:
```
Installing C# dependencies...
Platform: linux, x86_64, name=ubuntu, version=18.04

Downloading package 'OmniSharp for Linux (x64)' 	Retrying from 'https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-linux-x64-1.32.19.zip' Failed at stage: downloadPackage
Error: connect ECONNREFUSED 127.0.0.1:10803
```
## Steps to Reproduce ##
1. Connect to ubuntu18.04 using vscode remote mode
2. Use **add configuration** for an dotnet core project.
## Expected Behavior ##
Download Downloading package 'OmniSharp for Linux (x64)' successfully
## Actual Behavior ##
```
Installing C# dependencies...
Platform: linux, x86_64, name=ubuntu, version=18.04

Downloading package 'OmniSharp for Linux (x64)' 	Retrying from 'https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-linux-x64-1.32.19.zip' Failed at stage: downloadPackage
Error: connect ECONNREFUSED 127.0.0.1:10803
```
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

```
Starting OmniSharp server at 2019-6-7 17:37:11
    Target: /home/ubuntu/code/leetcode

[ERROR] Error: spawn /home/ubuntu/.vscode-server/extensions/ms-vscode.csharp-1.19.1/.omnisharp/1.32.19/run ENOENT
```
### C# log ###
<details>Post the output from Output-->C# here</details>

```
Installing C# dependencies...
Platform: linux, x86_64, name=ubuntu, version=18.04

Downloading package 'OmniSharp for Linux (x64)' 	Retrying from 'https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-linux-x64-1.32.19.zip' Failed at stage: downloadPackage
Error: connect ECONNREFUSED 127.0.0.1:10803
```

## Environment information ##

**VSCode version**: 1.35.0
**C# Extension**: 1.19.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.300/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.2.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.19.1|
|vscode-docker|PeterJausovec|0.6.2|
|vscodeintellicode|VisualStudioExptTeam|1.1.6|;

</details>

**Comment by jiayaoO3O** [comment]
I found the problem!!!
After I shut down my v2ray agent software, vscode can install the plugin normally!!!
But I can't understand, isn't the plugin I installed using remote mode installed on a remote ubuntu server? Why does my own client computer use the proxy software that causes the installation to fail?

**Comment by akshita31** [comment]
@jiayaoO3O You can try configuring vscode to use the proxy https://code.visualstudio.com/docs/setup/network

**Comment by jiayaoO3O** [comment]
@akshita31 I just don't understand why the local computer's proxy service software affects the remote server installation plugin.

**Comment by gregg-miskelly** [comment]
@sandy081 since you commented on another issue about [machine-scoped options](https://code.visualstudio.com/updates/v1_34#_machinespecific-settings), have the proxy server options been fixed to be machine-scoped?

**Comment by sandy081** [comment]
@gregg-miskelly Good point, they are not. We will look into making them into machine scope.

**Comment by gregg-miskelly** [comment]
@sandy081 should we move this issue over to the VS Code repo?

**Comment by sandy081** [comment]
I have not read this issue and I just answered to the question you asked. I have already filed an issue in VS Code and you can link to it if related,

https://github.com/microsoft/vscode/issues/75616
