### ISSUE TITLE
Omnisharp not find the program

### ISSUE THREAD

**Issue by felixgerdes** [OmniSharp/omnisharp-vscode#3104]
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.35.0
**C# Extension**: 1.19.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.19.1|;

</details>

## Environment data
`dotnet --info` output: 2.1.105
VS Code version: 1.35.0
C# Extension version: 1.19.1

## Steps to reproduce
I add an Workspace to the Programm. 
Create an console app with "dotnet new console"
Than i edited to "program" paramter in the launch.json
Then i try it with "dotnet run" it works.
Then i try to start the debugging proccces with F5.
This process fails.
Error Message "launch: Program "/Path/toFile/test.dll" does not exist.
I checked the path twice. its correct 

## Expected  behavior
I should be able to use the debugger

## Actual behavior
This process fails.
Error Message "launch: Program "/Path/toFile/test.dll" does not exist.
<img width="590" alt="Bildschirmfoto 2019-06-07 um 19 51 18" src="https://user-images.githubusercontent.com/6943462/59123711-3aec3300-895e-11e9-885b-de9d614d7149.png">
<img width="608" alt="Bildschirmfoto 2019-06-07 um 19 53 53" src="https://user-images.githubusercontent.com/6943462/59123718-3de72380-895e-11e9-9d73-f7a8f46de546.png">

**Comment by gregg-miskelly** [comment]
@felixgerdes you have a `>` character after `test.dll`.
