### ISSUE TITLE
Net cli tools cannot be located when using Snap VSCODE installation

### ISSUE THREAD

**Issue by Chicopower** [OmniSharp/omnisharp-vscode#3115]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

VS Code version:
1.35.1

C# Extension version:
1.20.0

OS: Debian Buster

## Steps to reproduce
- Install VSCODE with Snap (sudo snap install --classic code)
- Install .Net Core SDK with Microsoft Debian recommended way (manual way, not by snap, described [here](https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-preview6-linux-x64-binaries))
- Install Omnisharp C# VSCODE extension throught VSCODE extensions tab

## Expected  behavior
Omnisharp install fine without startup error and we can open an existing Net Core project without error.

## Actual behavior
Omnisharp extension got startup error:
the .net cli tools cannot be located
&
failed to spawn dotnet --info
&
Omnisharp error when trying to open a Net Core project "The SDK 'Microsoft.NET.Sdk.Web' specified could not be found"

## Workaround
Uninstall C# omnisharp extension, uninstall VSCODE from Snap.
Install VSCODE without using Snap (manual way documented by Microsoft [here](https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions)) & install Omnisharp C# VSCODE extension throught VSCODE extensions tab.

**Comment by gregg-miskelly** [comment]
This is tracked with #3077
