### ISSUE TITLE
how to autocomplete suggestions method with brackets?

### ISSUE THREAD

**Issue by wtksana** [OmniSharp/omnisharp-vscode#3118]
when i have a method
void foo(){}

now when i select  IntelliSense it will print 'foo'
wish to be 'foo()'
autocomplete with '()'

**Comment by wtksana** [comment]
sorry for my bad English, hope you can understand

**Comment by rchande** [comment]
@wtksana IntelliSense does not insert the parentheses for you. You will need to type them.

**Comment by manojbaishya** [comment]
Can we please reopen this issue? The python extension already has this feature: https://code.visualstudio.com/docs/python/settings-reference#_autocomplete-settings

It will save a lot of keystrokes !
