### ISSUE TITLE
omnisharp not work when a folder contains chinese characters

### ISSUE THREAD

**Issue by John0King** [OmniSharp/omnisharp-vscode#312]
this is the output  
```

[INFO] Starting OmniSharp at 'e:\DotNet\WebProjects\新建文件夹'...
[INFO] Started OmniSharp from 'C:\Users\<UserName>\.vscode\extensions\ms-vscode.csharp-1.0.5-rc2\.omnisharp\OmniSharp.exe' with process id 9948...
OmniSharp: -s e:\DotNet\WebProjects\�½��ļ��� --hostPID 9572 dnx:enablePackageRestore=false --stdio
[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location 'e:\DotNet\WebProjects\�½��ļ���' on host 9572.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in e:\DotNet\WebProjects\�½��ļ���
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: True
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update project e:\DotNet\WebProjects\�½��ļ���
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Add project e:\DotNet\WebProjects\�½��ļ���\project.json => 5fe4f6ba-3070-4ad7-abde-f23df3ec362d
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] �½��ļ���/.NETCoreApp,Version=v1.0
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 74 and removed 0 file references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 1 and removed 0 documents.
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] No solution files found in 'e:\DotNet\WebProjects\�½��ļ���'
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in 'e:\DotNet\WebProjects\�½��ļ���'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Configuration finished.

```

**Comment by DustinCampbell** [comment]
In the log above, it appears that OmniSharp is working, but is badly displayed. There is a known issue around IntelliSense not working when a file contains chinese characters. Is that what you're seeing? #280.

**Comment by John0King** [comment]
It's a little different, when the project's folder contains Chinese characters ,the omnisharp only "running",but not finish running.from the output ,my guess is that omnisharp can not match the code and file path because the Unicode and ANSI problem.

**Comment by DustinCampbell** [comment]
@John0King -- the log shows OmniSharp successfully locating and processing a .NET CLI project. Am I missing something?

**Comment by John0King** [comment]
@DustinCampbell -- the omnisharp is running ,   **but it can not actually do the work**    !
I'm not sure about  how omnisharp work, my guess is  that  editor send some keyword ( might contains the file Path ) to omnisharp, and omnisharp search the codebase then response IntelliSense information. 
when a folder contains some chinese characters or other Non-english  characters , and  windows OS use ANSI encoding not utf-8 encoding , omnisharp will just do nothing .

**Comment by DustinCampbell** [comment]
Yup! That's why I suspect it's related to #280.
