### ISSUE TITLE
Intellisense malfunctions when the C# extension is enabled.

### ISSUE THREAD

**Issue by DanJ210** [OmniSharp/omnisharp-vscode#3125]
Issue Type: <b>Bug</b>

Hello, so I've had an issue where I'm trying to type `Log.Information()` lines. Logging basically, except when I type `Lo...` which usually comes up with `Log` in intellisense and then after the `.` it will show information and debug and all that, it no longer shows this stuff. Just thinks I'm wanting to type `long`. This started happening within the last couple of days to week.

I've disabled all extensions and then everything goes back to normal. When I type `Lo...` or anything else I'll see the proper intellisense come up. Everything is working the way it always was. So I went down my list one by one to find the issue and when I enabled the C# plugin, that's when the issue came back. I've taken a screenshot to show what I mean because I don't know what to call it but pretty much intellisense is malfunctioning when the C# plugin is enabled. It seems to lose a lot of its knowledge. Second screenshot shows when I disable the C# plugin right after, all intellisense functions come back.

![Screenshot (21)](https://user-images.githubusercontent.com/16159685/59696428-f6f8f980-91b9-11e9-8372-b298cd18c844.png)
![Screenshot (32)](https://user-images.githubusercontent.com/16159685/59696662-7090e780-91ba-11e9-9b57-c2ef15b8e1fc.png)

Extension version: 1.20.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rchande** [comment]
@DanJ210 Can you set the option "omnisharp.logginglevel" to "debug" and share your OmniSharp log when this happens?

**Comment by DanJ210** [comment]
@rchande Sure, where do I get the logs from? Just copy and paste all from the output window?

**Comment by akshita31** [comment]
@DanJ210 Please paste the full output from your [OmniSharp log](https://github.com/OmniSharp/omnisharp-vscode/wiki/Reporting-Issues#omnisharp-and-c-log)

**Comment by DanJ210** [comment]
@akshita31 Give me a week or so to try and create the same scenario. I'm no longer with that company, I literally started a new position just last week so I don't have the same machine with access to the projects that I had. But I'll create some of the same projects and try to replicate the same scenario. I really have no idea of the cause but there wasn't anything drastically different. I've worked on that project the entire time I was at that company without an issue like that.

**Comment by rchande** [comment]
@DanJ210 We haven't heard from you in a while so I'm going to close this issue. Feel free to file a new one, including your OmniSharp log, if you're still having problems.
