### ISSUE TITLE
Tasks.json example is out of date

### ISSUE THREAD

**Issue by Calkines** [OmniSharp/omnisharp-vscode#3126]
## Environment data

`dotnet --info` output:
SDK do .NET Core (refletindo qualquer global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Ambiente de tempo de execução:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.300\

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version: 1.35.1
C# Extension version: 1.19.1

## Steps to reproduce
Start a new project using cli `dotnet new webapi -o src/WebAPI -n Name.Of.YourProject`. Open it
with Visual Studio Code.
Ignore the popup asking to create assets to build.
Try to use this documentation: 

[Check debbuger.md ](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md)

When article talks about 'Creating configuration files manually'

It is using an out of date json file.

[Check json exemple](https://raw.githubusercontent.com/wiki/OmniSharp/omnisharp-vscode/ExampleCode/tasks.json)

After create a file in vscode, actual version, a message says: 

> Task version 0.1.0 is deprecated. Please use 2.0.0

## Expected  behavior

Use the correct exemple file to configure vscode.

## Actual behavior

The example is not adequated to version 2.0.0 or above.

**Comment by gregg-miskelly** [comment]
Thanks for taking the time to report this! I updated the example.
