### ISSUE TITLE
Outline not work if...

### ISSUE THREAD

**Issue by jaxxtrend** [OmniSharp/omnisharp-vscode#3129]
Issue Type: <b>Bug</b>

VsCode not outlined C# file, but outlined if i change anything in file.

Extension version: 1.20.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

**Comment by dejaybe87** [comment]
I'm seeing this as well, but with C++ files.  If I have tabs open when I launch VS Code, only the tab active at launch will have an outline.  All other tabs will show "No symbols found in document[...]".  Modifying a file does regenerate the outline for that file though.

Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:27:31.086Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-52-generic snap

**Comment by rchande** [comment]
@jaxxtrend I don't see this on 1.37-0-insiders, so I'm guessing this is a VS Code bug that's being fixed. My version (for your reference):

Version: 1.37.0-insider (user setup)
Commit: 3802a986823977ec472fc993854e1a753037fc8f
Date: 2019-07-29T05:30:35.768Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18945

**Comment by APerricone** [comment]
I just tryied on:

Versione: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Data: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

[noOutline.zip](https://github.com/OmniSharp/omnisharp-vscode/files/4255299/noOutline.zip)
