### ISSUE TITLE
Newline formatting options

### ISSUE THREAD

**Issue by CuddleBunny** [OmniSharp/omnisharp-vscode#313]
Looking for a way to configure auto-format for newlines. I'm a fan of this structure:

```
void foo() {
    if (something) {
        bar();
    } else {
        baz();
    }
}
```

However the current auto-format will place all my curly braces on a new line. I've noticed that both TypeScript and JavaScript have the options `placeOpenBraceOnNewLineForControlBlocks` and `placeOpenBraceOnNewLineForFunctions`.

**Comment by MGillson** [comment]
I agree.  I have found the forced formatting annoying.  Is there any plans for configuring how the formatting works?

**Comment by unalone** [comment]
Agree+1

We need rights to format code as what we need, not the fixed role!

**Comment by Fillipoman** [comment]
I am struggling to figure out how to configure formatting as well. Has anyone made progress?

**Comment by koppert** [comment]
+1

**Comment by Thaina** [comment]
In the meantimes we could create `omnisharp.json` which contains many property about omnisharp, and then restart omnisharp

This is what I use

```json
{
	"FormattingOptions": {
		"NewLinesForBracesInLambdaExpressionBody": false,
		"NewLinesForBracesInAnonymousMethods": false,
		"NewLinesForBracesInAnonymousTypes": false,
		"NewLinesForBracesInControlBlocks": true,
		"SpaceAfterControlFlowStatementKeyword": false,
		"SpaceAfterComma": false
	}
}
```

However I would also support that omnisharp should also add vscode config contribution point

**Comment by bbugh** [comment]
If you're like me (and I know I am) you want the brackets on the same line for everything, not just control blocks. Here's the full listing for all of the common squirrely bracket cases. 

1. Put this in the base of your project as `omnisharp.json` 
2. open the command palette and run `Omnisharp: Restart Omnisharp`. 

```json
{
	"FormattingOptions": {
		"NewLinesForBracesInLambdaExpressionBody": false,
		"NewLinesForBracesInAnonymousMethods": false,
		"NewLinesForBracesInAnonymousTypes": false,
		"NewLinesForBracesInControlBlocks": false,
		"NewLinesForBracesInTypes": false,
		"NewLinesForBracesInMethods": false,
		"NewLineForElse": false,
		"NewLineForCatch": false,
		"NewLineForFinally": false
	}
}
```

**Omnisharp doesn't presently reload the `omnisharp.json` files automatically, so if you make changes while you're in the editor, you'll have to restart Omnisharp again.**

It's possible that I missed a couple of NewLine settings for edge cases. The formatting options don't seem to be documented anywhere, but you can see them all in the code: http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.CSharp.Workspaces/Formatting/CSharpFormattingOptions.cs,dac739b7b8a53984 

HURRAY! This was the only thing left that was still bugging me about vscode. Thanks @Thaina for the PROTIP.

**Comment by filipw** [comment]
> Omnisharp doesn't presently reload the omnisharp.json files automatically, so if you make changes while you're in the editor, you'll have to restart Omnisharp again.

that's correct, this is planned to change though, the config file will be watched. it's tracked here https://github.com/OmniSharp/omnisharp-roslyn/issues/366#issuecomment-268984041

> The formatting options don't seem to be documented anywhere, but you can see them all in the code:

I wrote a wiki page about dealing with omnisharp config here https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration%20Options but indeed, the individual options are just picked up from Roslyn directly.

**Comment by unalone** [comment]
I’ve tried this, but nothing happened, when I try to format code, it still places every braces in new line, shit….

**Comment by Thaina** [comment]
@unalone Have you restart omnisharp?

**Comment by unalone** [comment]
Sure, I have created a new file named “omnisharp.json”, and placed this file under my root path of project, also, I added a line in my settings.json file like this:

"omnisharp.json": “/path/to/omnisharp.json”

And then I restart the vs code and nothing happened….. what’s wrong?

**Comment by Thaina** [comment]
First, I think you should not put that line in settings.json
Second, you may need to restart omnisharp too in addition to restart vscode

**Comment by unalone** [comment]
First, this file is under the root path of my project.

Second, I both tried to restart the OmniSharp and VS Code, nothin happened...

**Comment by unalone** [comment]
Ok, the reason is my C# plugin was out of date, everything goes well after update them, thank you :)

**Comment by filipw** [comment]
one more thing, regarding documentation - you can also use `omnisharp.json` from schemastore.org here http://json.schemastore.org/omnisharp

@DustinCampbell I think this issue can be closed as it seems everything needed here has been explained/addressed.

Omnisharp.json auto-reload is tracked in the omnisharp repo https://github.com/OmniSharp/omnisharp-roslyn/issues/366#issuecomment-268984041

**Comment by unalone** [comment]
so, why won't the omnisharp.json file be configured globally?

**Comment by filipw** [comment]
it will - this is tracked in separate issue already https://github.com/OmniSharp/omnisharp-roslyn/issues/717

**Comment by DustinCampbell** [comment]
Sounds good @filipw. Closing this issue.

**Comment by Thaina** [comment]
@filipw Have you include `schemastore/omnisharp` into jsonvalidator contribution point of vscode extension yet?

**Comment by DustinCampbell** [comment]
Nope. That's my fault. I've commented on the PR.
