### ISSUE TITLE
OmniSharp does not detect typos

### ISSUE THREAD

**Issue by MarkOstis** [OmniSharp/omnisharp-vscode#3134]
Hi Guys!
I've just started using the VS Code for .NetCore C# and found one issue.
I use Windows 10, but C# project is built and debuged on WSL. For me the debug works well, projects  are built, IntelliSense works etc.

**Issue:**
But VS Code and OmniSharp does not detect typos in code. I mean, I can simply write any word and VS Code will not underline it in red. 

The errors detect only on build step. This very inconvenience to rebuild project each time you fix something.

**VS Code:** 
Version: 1.35.1 (system setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**C# Extensions:**
Name: C#
Id: ms-vscode.csharp
Description: C# for Visual Studio Code (powered by OmniSharp).
Version: 1.20.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

How to fix this issue? Does OmniCSharp support this capability? Do I need to install any extra extensions? 

Please help, because without this future it is to hard to coding.

**Comment by akshita31** [comment]
@MarkOstis Could you share a repro project and also the exact repro steps. I am not too familiar with debugging on WSL so repro steps would help to lock down the issue here.

**Comment by rchande** [comment]
@MarkOstis We haven't heard from you in a while so I'm going to close this. Do note that VS Code Remote (https://code.visualstudio.com/docs/remote/remote-overview) against WSL may be what you want.
