### ISSUE TITLE
Why is the "OmniSharp server is running" status bar icon green?

### ISSUE THREAD

**Issue by Tyriar** [OmniSharp/omnisharp-vscode#3138]
![image](https://user-images.githubusercontent.com/2193314/60122847-f244c000-973a-11e9-95dd-d579e7147fba.png)

Extensions typically shouldn't do this, red makes sense for a failure state but if everything is working as intended it should just be white so as to not draw the eye to it.

**Comment by rchande** [comment]
cc @akshita31

**Comment by Tyriar** [comment]
Thanks @akshita31 😃

**Comment by ihodev** [comment]
Hello, @akshita31! Can I somehow change that color?

![image](https://user-images.githubusercontent.com/9801624/61533710-530fa180-aa36-11e9-948c-d58fecd91ba1.png)

**Comment by mario-d-s** [comment]
This actually confused me - I was used to the icon being green and now I though something was wrong...

Anyway: now the icon is white regardless of theme, and as @ihodev illustrates this doesn't make much sense on light themes. Can it please be changed to have the dark grey of other status bar indicators on light themes?

**Comment by v-zubritsky** [comment]
I could relate to this, icon doesn't look very attractive http://tinyimg.io/i/zgW8qOr.png

**Comment by Tyriar** [comment]
@v-zubritsky created https://github.com/OmniSharp/omnisharp-vscode/issues/4384
