### ISSUE TITLE
Upgrade from blazor preview 5 to 6

### ISSUE THREAD

**Issue by roboriaan** [OmniSharp/omnisharp-vscode#3139]
## Issue Description ##

Not a major issue. Just some tooling wonkeyness I guess.

After the upgrade from prev 5 to 6 I notice that members and functions that are defined in the @code { } block displays as plain text. As in. No colouring. With red squigglies all over. This worked fine before when we used @functions { } but that has been renamed.

Are you guys also getting the same issue?

To reproduce just create a starter blazor, client-side proj using sdk : 3.0.100-preview6-012264

I should mention the project builds fine
Let me know if you need more info.
TIA

## Environment information ##

**VSCode version**: 1.35.1
**C# Extension**: 1.20.0

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /home/riaan/dotnet/sdk/3.0.100-preview6-012264/

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.2.203 [/home/riaan/dotnet/sdk]
  3.0.100-preview4-011223 [/home/riaan/dotnet/sdk]
  3.0.100-preview5-011568 [/home/riaan/dotnet/sdk]
  3.0.100-preview6-012264 [/home/riaan/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [/home/riaan/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [/home/riaan/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [/home/riaan/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [/home/riaan/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [/home/riaan/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [/home/riaan/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [/home/riaan/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [/home/riaan/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [/home/riaan/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer-2|CoenraadS|0.0.28|
|code-settings-sync|Shan|3.3.1|
|csharp|ms-vscode|1.20.0|
|gruvbox|jdinhlife|1.3.11|
|html-css-class-completion|Zignd|1.19.0|
|material-icon-theme|PKief|3.8.0|
|sqltools|mtxr|0.19.6|
|vsc-material-theme|Equinusocio|2.9.0|
|vscode-icons|vscode-icons-team|8.8.0|
|vscode-nuget-package-manager|jmrog|1.1.6|
|winteriscoming|johnpapa|1.1.1|;

</details>

**Comment by NTaylorMullen** [comment]
Hey @roboriaan thanks for the report! This is a known issue and is currently being tracked over at https://github.com/aspnet/Razor.VSCode/issues/75.

I even went one step further and fixed this particular issue [here](https://github.com/aspnet/Razor.VSCode/pull/371) but the VSCode team recommended we don't piecemail a fix and work on owning the grammar entirely. That work will be done in a future release 😄

**Comment by roboriaan** [comment]
Awesome! Will keep an eye out for that. Let me know if I can help with testing.
