### ISSUE TITLE
Extension issue - I uncaught errors - showing up in 'Running Extensions"

### ISSUE THREAD

**Issue by rbadapanda** [OmniSharp/omnisharp-vscode#3146]
- Issue Type: `Bug`
- Extension Name: `csharp`
- Extension Version: `1.20.0`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.36.0-insider`

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 43,
		"activateCallTime": 5,
		"activateResolvedTime": 14,
		"activationEvent": "workspaceContains:*.csproj,*.sln,*.csx,*.cake,**/*.csproj,**/*.sln,**/*.csx,**/*.cake"
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property '0' of null"
		}
	]
}
```

**Comment by akshita31** [comment]
@rbadapanda Can you elaborate more on what you are trying to achieve, like what files are you trying to edit and what is the issue that you are facing like intellisense not working, unable to debug, etc
