### ISSUE TITLE
Support nuget.org symbol server

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#3150]
The debugger should provide support for downloading symbols from nuget.org.

For more context: https://devblogs.microsoft.com/nuget/improved-package-debugging-experience-with-the-nuget-org-symbol-server/

**Comment by gregg-miskelly** [comment]
The first step towards supporting this is to implement support in the .NET symbol downloader. There is currently a PR out for this: https://github.com/dotnet/symstore/pull/103

**Comment by loligans** [comment]
Looks like the PR you referenced @gregg-miskelly is completed. Perhaps the `Debugger-FixedPendingInsertion` label could be removed?

**Comment by gregg-miskelly** [comment]
No. That PR was the building block for this, but actual support requires a new debugger. We intend to insert this new debugger soon, but we haven't done so yet as we have been pretty slammed.

**Comment by loligans** [comment]
Is there somewhere I can learn about the project and provide some help? Maybe creating a new debugger is over my head, but I may be able to help with some of the smaller or easier stuff. @gregg-miskelly

**Comment by gregg-miskelly** [comment]
Fixed in 1.21.
