### ISSUE TITLE
OmniSharp Server won't run on the next VS Code Instance

### ISSUE THREAD

**Issue by deanrih** [OmniSharp/omnisharp-vscode#3151]
## Issue Description ##
The Omnisharp Server won't run / re initialize the project on the next VS Code instance open.

## Steps to Reproduce ##
1. Open C# Project (Unity or standard project)
2. Open the Output Panel
3. Switch to OmniSharp Log output
4. Wait till the OmniSharp loaded and displaying some output
5. Try code something to check if the OmniSharp DID work, like Autocomplete
6. Close the VS Code
7. Open the VS Code again, either with the same step or different one
8. Repeat step 2
9. Repeat step 3
10. Repeat step 4
11. Repeat step 5

## Expected Behavior ##
The OmniSharp server should run / initialized again so the Intellisense, Autocomplete, and all the features works.

## Actual Behavior ##
The OmniSharp server doesn't even looked like it executed, no Error, No Output, No Error/Exception on Developer Tools' Console

## Logs ##
-

### OmniSharp log ###
- First time open
Starting OmniSharp server at 2019-7-3 13:15:36
    Target: d:\Workspaces\Personal\dotNet\testOne

OmniSharp server started.
    Path: C:\Users\Username\\.vscode\extensions\ms-vscode.csharp-1.20.0\\.omnisharp\1.32.20\OmniSharp.exe
    PID: 15236

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 3 MSBuild instance(s)
            1: Visual Studio Community 2017 15.9.28307.718 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            2: Visual Studio Community 2019 16.1.29020.237 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            3: StandAlone 15.0 - "C:\Users\<username>\.vscode\extensions\ms-vscode.csharp-1.20.0\.omnisharp\1.32.20\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.1.29020.237 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\Workspaces\Personal\dotNet\testOne'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'd:\Workspaces\Personal\dotNet\testOne'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Workspaces\Personal\dotNet\testOne\testOne.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\Workspaces\Personal\dotNet\testOne'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Workspaces\Personal\dotNet\testOne\testOne.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\Workspaces\Personal\dotNet\testOne' on host 5112.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\Workspaces\Personal\dotNet\testOne\testOne.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\Workspaces\Personal\dotNet\testOne\testOne.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: testOne
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 3.

- Second time
(NOTHING)

## Environment information ##

**VSCode version**: 1.35.1
**C# Extension**: 1.20.0

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.105\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer-2|CoenraadS|0.0.28|
|code-settings-sync|Shan|3.3.1|
|csharp|ms-vscode|1.20.0|
|indent-rainbow|oderwat|7.4.0|
|sublime-keybindings|ms-vscode|4.0.3|;

</details>

**Comment by deanrih** [comment]
To note here, the `>OmniSharp: Restart Omnisharp` do nothing.


And if you use Windows 8/8.1/10 with Fast Startup enabled, the server won't be able to start unless you Shutdown while pressing `SHIFT` key before pressing the Shutdown button on the Start Menu

**Comment by rchande** [comment]
@deanrih I'm having trouble reproducing this. I can close/open VS Code an arbitrary number of times and OmniSharp starts each time. I also confirmed that the process goes away when VS Code exists...
