### ISSUE TITLE
Reuse launchBrowser window tab

### ISSUE THREAD

**Issue by steveoh** [OmniSharp/omnisharp-vscode#3152]
It is really nice that we can F5 debug and launch our web applications. A nice improvement would be to reuse the window if you debug more than once. Currently, a new duplicate tab will be created every time you launch. 

The only current solution that I know of is a little silly and involves having two almost duplicate launch tasks, one to open the window and one to skip doing that. I still have to remember to refresh the tab when the building is complete.

Other tools like react will reuse the same tab and refresh the content. This is a really nice developer feature and a productivity boost. 

Can we add this functionality?

**Comment by rchande** [comment]
@gregg-miskelly @NTaylorMullen Any way to accomplish this for Asp.NET Core?

**Comment by NTaylorMullen** [comment]
> @gregg-miskelly @NTaylorMullen Any way to accomplish this for Asp.NET Core?

I'm not familiar enough with the capabilities of VSCode on how to accomplish this honestly 😢

**Comment by gregg-miskelly** [comment]
Sorry, should have responded earlier - this extension isn't really responsible for starting the browser moving forward. The template now defaults to using `serverReadyAction`, which means that the VS Code team now owns starting the web browser. So I would suggest opening this issue there: https://github.com/microsoft/vscode/issues
