### ISSUE TITLE
End of life for .NET Core 1.0 / 1.1 (project.json)

### ISSUE THREAD

**Issue by filipw** [OmniSharp/omnisharp-vscode#3158]
.NET Core 1.0/1.1 reached end of life and went out of support on 27 June 2019.
Support for `project.json` should be removed.

We would like to remove it from [OmniSharp](https://github.com/OmniSharp/omnisharp-roslyn/pull/1539)

cc @akshita31 @rchande

**Comment by gregg-miskelly** [comment]
project.json is also used by old school PCL projects along with a .csproj file. Do we want to remove both?

**Comment by filipw** [comment]
we never did anything special to support that in OmniSharp, has it ever really worked?

**Comment by gregg-miskelly** [comment]
I don't know. I only brought it up because back when Dustin added the 'project.json is deprecated' message, we got complaints from folks with PCL projects since those are not deprecated. For this new effort maybe they can be ignored.

**Comment by filipw** [comment]
Could you guys look at the telemetry to determine how much project.json is used?

An alternative approach would be to extract it from OmniSharp and make it a plugin (ala Razor) that users can opt into.

**Comment by rchande** [comment]
We only keep telemetry going back a couple of months, but in that time I see 0 instances of projects targeting .NETCore 1.0. I think it's safe to remove support.

**Comment by richlander** [comment]
I am also OK with removing project.json support.

**Comment by rchande** [comment]
This is done.
