### ISSUE TITLE
C# syntax highlighting broken around literal strings @"..."

### ISSUE THREAD

**Issue by af4jm** [OmniSharp/omnisharp-vscode#316]
Not sure what the heck it's doing, but sometimes it ignores @" and sometimes it doesn't.
Attached is screen shot showing bogus highlighting and .cs source file used to create that screen shot (extension changed to .txt to enable upload).

Not sure if this belongs here or in VS Code.  It's issue 6325 over there, duplicating it here by suggestion.

[SharedConstants.cs.txt](https://github.com/OmniSharp/omnisharp-vscode/files/262184/SharedConstants.cs.txt)
![vscodeissue-csliteralstrings](https://cloud.githubusercontent.com/assets/849948/15228959/98a23880-185c-11e6-97bb-7815e4f1e43f.png)

Note that it highlights correct in both VS15 & VS13

**Comment by bonza** [comment]
I'm not sure it is the same one, but looks pretty similar

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.4|
|csharp|ms-vscode|1.6.2|
|Spell|seanmcbreen|0.9.1|

---

Steps to Reproduce:

1. Create cs file
2. Paste following code:
```csharp
public class Name
{
    private readonly string initSportMessageFormatString = "line1"
        + "F;line2";
    private int key;
    public int MyProperty { get; set; }
}
```
Result:
![vscode csharpsyntaxhighlighter](https://cloud.githubusercontent.com/assets/225150/21564042/332776d2-ce91-11e6-98ba-fbb84a6b5db7.gif)

**Comment by DustinCampbell** [comment]
This should look much better in the next release:

![image](https://cloud.githubusercontent.com/assets/116161/21817971/e999dd60-d71a-11e6-950a-e12ba2f63d03.png)

![image](https://cloud.githubusercontent.com/assets/116161/21818038/295d6534-d71b-11e6-9803-aa4be4251e2e.png)

![image](https://cloud.githubusercontent.com/assets/116161/21818044/313b91e0-d71b-11e6-945f-4385385e05fb.png)

![image](https://cloud.githubusercontent.com/assets/116161/21818058/3c9239e0-d71b-11e6-9ee8-582d1f083aae.png)
