### ISSUE TITLE
.NET Debugging is supported only in Microsoft versions of VS Code error in VS Code 1.36.0

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#3161]
After updating to VS Code 1.36.0 (current released version) to users are running into the following error when they start debugging -

".NET Debugging is supported only in Microsoft versions of VS Code. See https://aka.ms/VSCode-DotNet-DbgLicense for more information."

**Comment by gregg-miskelly** [comment]
@sborkowski @guardrex are you both on Windows? if not, what OS are you on?

**Comment by guardrex** [comment]
Win10 here

**Comment by sborkowski** [comment]
Win10 also.

**Comment by dan-maxwell** [comment]
I have a fresh installation of the Microsoft VS Code version 1.36.1.  I am receiving the warning in the console.

![image](https://user-images.githubusercontent.com/5944525/61422305-b67fbf00-a8d0-11e9-8f77-35e467e43945.png)

**Comment by gregg-miskelly** [comment]
@dan-maxwell That isn't a warning. It is just the license text. Unless you are seeing ".NET Debugging is supported only in Microsoft versions of VS Code. See https://aka.ms/VSCode-DotNet-DbgLicense for more information." you are all good.

**Comment by dan-maxwell** [comment]
Got it.  Thanks.  Wish I could hide it though.

**Comment by torquerrr** [comment]
Just run into this issue with 1.36.0 on Manjaro (Arch) and SDK 2.2. Not sure I can try Insider build.

**Comment by gregg-miskelly** [comment]
@torquerrr Are you using a distribution of VS Code from Microsoft? Note that an insiders build wouldn't help here.

**Comment by torquerrr** [comment]
@gregg-miskelly 
I believe mine is Community-OSS version from Manjaro community repo.

**Comment by gregg-miskelly** [comment]
@torquerrr what you are running into is expected -- only Microsoft official distributions of VS Code are supported. See https://aka.ms/VSCode-DotNet-DbgLicense for more information.

**Comment by torquerrr** [comment]
@gregg-miskelly 
Oh, my bad! 
Sorry for wasting your time on this and thanks for pointing me in the right direction. I will try to install the MS-distributed version now and see how it goes.
I have updated the aforementioned document, please, take a look.

**Comment by Weijee** [comment]
Hi, I also ran into this issue in my code-server. Any ideas?
OS: Windows10 20H2  WSL2 Ubuntu2004 
![image](https://user-images.githubusercontent.com/13539500/120335011-b69dd200-c323-11eb-8bd1-a111c3000b20.png)
![image](https://user-images.githubusercontent.com/13539500/120335104-c87f7500-c323-11eb-8d05-648f6ae1c65d.png)

**Comment by gregg-miskelly** [comment]
@Weijee what you are running into is expected -- only Microsoft official distributions of VS Code are supported. See https://aka.ms/VSCode-DotNet-DbgLicense for more information.
