### ISSUE TITLE
Latest omnisharp BadImageFormatException on Omnisharp.Abstractions

### ISSUE THREAD

**Issue by divinebovine** [OmniSharp/omnisharp-vscode#3162]
## Issue Description ##
Using the latest version of omnisharp in vscode throws a System.BadImageFormatException on the Omnisharp.Abstractions library.

## Steps to Reproduce ##
Set `"omnisharp.path": "latest"` in the settings.json file and restart omnisharp

## Expected Behavior ##
Omnisharp loads without error

## Actual Behavior ##
Omnisharp throws an exception

### OmniSharp log ###
<Details>
Starting OmniSharp server at 7/9/2019, 11:14:14 AM
    Target: c:\dev\test\some-test.sln

OmniSharp server started.
    Path: C:\Users\daniel\.vscode\extensions\ms-vscode.csharp-1.20.0\.omnisharp\1.33.1-beta.7\OmniSharp.exe
    PID: 12352

System.BadImageFormatException: Could not load file or assembly 'OmniSharp.Abstractions, Version=1.33.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'OmniSharp.Abstractions, Version=1.33.0.0, Culture=neutral, PublicKeyToken=null'
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1()
   at OmniSharp.HostHelpers.Start(Func`1 action) in D:\a\1\s\src\OmniSharp.Host\HostHelpers.cs:line 29

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
</Details>

### C# log ###
<details>Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
</details>

## Environment information ##

**VSCode version**: 1.36.0
**C# Extension**: 1.20.0

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.202\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  1.1.9 [C:\Program Files\dotnet\sdk]
  1.1.11 [C:\Program Files\dotnet\sdk]
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|autofilename|JerryHong|0.1.3|
|cloudcode|googlecloudtools|0.0.9|
|code-settings-sync|Shan|3.3.1|
|cpptools|ms-vscode|0.24.0|
|csharp|ms-vscode|1.20.0|
|csharpextensions|jchannon|1.3.0|
|debugger-for-chrome|msjsdiag|4.11.6|
|docomment|k--kato|0.1.8|
|dotenv|mikestead|1.0.1|
|dotnet-test-explorer|formulahendry|0.7.1|
|EditorConfig|EditorConfig|0.13.0|
|gitignore|codezombiech|0.6.0|
|gitlens|eamodio|9.8.2|
|graphviz-preview|EFanZh|1.3.3|
|jenkinsfile-support|ivory-lab|0.4.4|
|jshint|dbaeumer|0.10.20|
|markdown-preview-enhanced|shd101wyy|0.4.3|
|msbuild-project-tools|tintoy|0.2.55|
|powershell|ms-vscode|2019.5.0|
|prettier-vscode|esbenp|1.9.0|
|python|ms-python|2019.6.22090|
|quicktype|quicktype|12.0.46|
|vscode-coverage-gutters|ryanluker|2.4.0|
|vscode-docker|ms-azuretools|0.6.4|
|vscode-eslint|dbaeumer|1.9.0|
|vscode-icons|vscode-icons-team|8.8.0|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.0.1|
|vscode-markdownlint|DavidAnson|0.28.0|
|vscode-react-native|msjsdiag|0.10.1|
|vscode-solution-explorer|fernandoescolar|0.3.4|
|vscode-yaml|redhat|0.4.1|
|vsliveshare|ms-vsliveshare|1.0.488|
|vsliveshare-audio|ms-vsliveshare|0.1.56|
|webpack|jeremyrajan|2.1.3|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by filipw** [comment]
it looks like it didn't download correctly for you?

the C# log should say:

```
Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.33.1-beta.7...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.33.1-beta.7' (33676 KB).................... Done!
Installing package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.33.1-beta.7'

Finished
```

Can you please remove the `C:\Users\daniel.vscode\extensions\ms-vscode.csharp-1.20.0.omnisharp\1.33.1-beta.7` folder and try again?

**Comment by divinebovine** [comment]
@filipw thank you, that did the trick. I'll try to remember this if I encounter this issue again.
