### ISSUE TITLE
how do I retrieve the previous version of vsdbg

### ISSUE THREAD

**Issue by allevyMS** [OmniSharp/omnisharp-vscode#3166]
my current flow requires an older version of vsdbg which supports interpreter type mi and the --attach flag

in my current flow I download https://aka.ms/getvsdbgsh and then run:
 vsdbg root/getvsdbg.sh -v latest -l /vsdbg 

In the latest version 16.2.10709.2 the features I need are already deprecated

I have tried finding a list of previous versions so I could fix the version (till I upgrade to the latest debugging flow) but I couldn't find one

I tried specifying version 'vs2017u5' but that retrieves the same version as latest 

vs2017u1 seems to be a very old version

How can I retrieve the previous version that support these deprecated features?

**Comment by gregg-miskelly** [comment]
What are you using to connect to vsdbg that still worked?

**Comment by gregg-miskelly** [comment]
Actually, we talk about this in https://github.com/microsoft/MIEngine/issues/892 since that is probably a more appropriate repo.
