### ISSUE TITLE
Null not highlighted when casted to type

### ISSUE THREAD

**Issue by thomasfdm** [OmniSharp/omnisharp-vscode#3169]
## Issue Description ##
When passing `null`, casted to a type, as an argument into a function with a space between the Cast operation and the `null` literal, the null literal isn't highlighted as a keyword.

## Steps to Reproduce ##
Paste the following code into VSCode:
```C#
public class Test
    {
        void test(Test t)
        {
            //Do something
            return;
        }

        void callTest()
        {
            test((Test) null);
            test((Test)null);
            test(null);
        }
    }
```
Notice how the first call the `null` is not highlighted as a keyword. (Only just noticed but this also seems to be the case for GitHub as well).

## Expected Behavior ##
`null` to be highlighted as keyword, as it is in the other two calls above.

## Actual Behavior ##
`null` is highlighted as if it were a variable.

## Environment information ##

**VSCode version**: 1.36.1
**C# Extension**: 1.20.0

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.16.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.300/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.2.300 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|aspnet-helper|schneiderpat|0.6.4|
|better-comments|aaron-bond|2.0.5|
|code-spell-checker|streetsidesoftware|1.7.17|
|color-highlight|naumovs|2.3.0|
|csharp|ms-vscode|1.20.0|
|csharpextensions|jchannon|1.3.0|
|docomment|k--kato|0.1.8|
|dotnet|formulahendry|0.0.4|
|dotnet-test-explorer|formulahendry|0.7.1|
|gitignore|codezombiech|0.6.0|
|html-css-class-completion|Zignd|1.19.0|
|json-schema-validator|tberman|0.1.0|
|live-sass|ritwickdey|3.0.0|
|LiveServer|ritwickdey|5.6.1|
|material-icon-theme|PKief|3.8.0|
|msbuild-project-tools|tintoy|0.2.55|
|mustache|dawhite|1.1.1|
|netcore-extension-pack|doggy8088|0.8.0|
|netcore-snippets|doggy8088|0.2.4|
|nuget-reverse-package-search|jesschadwick|0.1.68|
|path-intellisense|christian-kohler|1.4.2|
|prettier-vscode|esbenp|1.9.0|
|python|ms-python|2019.6.22090|
|quicktype|quicktype|12.0.46|
|react-proptypes-intellisense|OfHumanBondage|1.0.3|
|sass-indented|robinbentley|1.5.1|
|sass-lint|glen-84|1.0.5|
|stylelint|shinnn|0.51.0|
|supersharp|craigthomas|0.1.4|
|svgeditor|henoc|2.9.0|
|todo-tree|Gruntfuggly|0.0.138|
|unity-debug|Unity|2.7.2|
|unity-tools|Tobiah|1.1.1|
|vscode-concourse|Pivotal|1.8.1|
|vscode-csharp-snippets|jorgeserrano|0.3.1|
|vscode-docker|ms-azuretools|0.6.4|
|vscode-eslint|dbaeumer|1.9.0|
|vscode-extension-auto-import|NuclleaR|1.4.3|
|vscode-html-css|ecmel|0.2.0|
|vscode-icons|vscode-icons-team|8.8.0|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-react-native|msjsdiag|0.10.0|
|vscode-todo-highlight|wayou|1.0.4|
|vscode-versionlens|pflannery|0.24.0|
|vsliveshare|ms-vsliveshare|1.0.488|;

</details>

**Comment by rchande** [comment]
Moved to https://github.com/dotnet/csharp-tmLanguage/issues/159
