### ISSUE TITLE
Unable to launch debugger worker process

### ISSUE THREAD

**Issue by mdx0111** [OmniSharp/omnisharp-vscode#3178]
## Issue Description ##
Unable to launch an external console under Fedora 30 and KDE desktop. This works fine on the same machine in gnome but not KDE. Both Konsole and gnome Terminal are installed. 
More than happy to run any test and post any log on your request.

Your help is much appreciated.

Many thanks. 

## Steps to Reproduce ##
1- Create a dotnet core console app
2- Set "console" to "externalTerminal" in launch.json
3- Save the launch.json file
4- Try to run the app 

## Expected Behavior ##
A new terminal should open to allow output from app and input from the user.

## Actual Behavior ##
A dialog is displayed stating the following message:
Unable to launch debugger worker process (vsdebug) through the terminal. can't find terminal application 'dumb'

### OmniSharp log ###
<details>
Starting OmniSharp server at 16/07/2019, 05:22:12
    Target: /media/workspace/Projects/CSharp/DDD/VendingMachine

OmniSharp server started.
    Path: /home/masoud/.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/run
    PID: 10384

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on fedora 30.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "/home/masoud/.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/masoud/.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "/home/masoud/.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/.msbuild/Current/Bin"
            MSBuildExtensionsPath = /home/masoud/.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/.msbuild
            BypassFrameworkInstallChecks = true
            CscToolPath = /home/masoud/.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/.msbuild/Current/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/masoud/.vscode/extensions/ms-vscode.csharp-1.20.0/.omnisharp/1.32.20/omnisharp/.msbuild/Current/Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/media/workspace/Projects/CSharp/DDD/VendingMachine'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/media/workspace/Projects/CSharp/DDD/VendingMachine'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/media/workspace/Projects/CSharp/DDD/VendingMachine/VM.Logic/VM.Logic.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/media/workspace/Projects/CSharp/DDD/VendingMachine/VM.UI/VM.UI.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/media/workspace/Projects/CSharp/DDD/VendingMachine'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /media/workspace/Projects/CSharp/DDD/VendingMachine/VM.Logic/VM.Logic.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/media/workspace/Projects/CSharp/DDD/VendingMachine' on host 10244.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/media/workspace/Projects/CSharp/DDD/VendingMachine/VM.Logic/VM.Logic.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/media/workspace/Projects/CSharp/DDD/VendingMachine/VM.Logic/VM.Logic.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /media/workspace/Projects/CSharp/DDD/VendingMachine/VM.UI/VM.UI.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/media/workspace/Projects/CSharp/DDD/VendingMachine/VM.UI/VM.UI.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/media/workspace/Projects/CSharp/DDD/VendingMachine/VM.UI/VM.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: VM.Logic
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: VM.UI
</details>

### C# log ###
<details>Looked for output from Output-->C# but it's empty</details>

## Environment information ##

**VSCode version**: 1.36.1
**C# Extension**: 1.20.0

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.301
 Commit:    70d6be0814

Runtime Environment:
 OS Name:     fedora
 OS Version:  30
 OS Platform: Linux
 RID:         fedora.30-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.301/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.5.0|
|cpptools|ms-vscode|0.24.0|
|csharp|ms-vscode|1.20.0|
|csharpextensions|jchannon|1.3.0|
|debugger-for-chrome|msjsdiag|4.11.6|
|docomment|k--kato|0.1.8|
|gitlens|eamodio|9.8.5|
|html-css-class-completion|Zignd|1.19.0|
|ng-template|Angular|0.800.0|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|vs-keybindings|ms-vscode|0.2.0|
|vscode-html-css|ecmel|0.2.0|
|vscode-icons|vscode-icons-team|8.8.0|
|vsliveshare|ms-vsliveshare|1.0.509|
|vsliveshare-audio|ms-vsliveshare|0.1.59|;

</details>

**Comment by mdx0111** [comment]
Please see below my launch.json file:

```js
{
    // Use IntelliSense to find out which attributes exist for C# debugging
    // Use hover for the description of the existing attributes
    // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
    "version": "0.2.0",
    "configurations": [{
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/VM.UI/bin/Debug/netcoreapp2.2/VM.UI.dll",
            "args": [],
            "cwd": "${workspaceFolder}/VM.UI",
            // For more information about the 'console' field, see https://aka.ms/VSCode-CS-LaunchJson-Console
            "console": "externalTerminal",
            "stopAtEntry": false
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}
```

Many many thanks.

**Comment by gregg-miskelly** [comment]
Hi @mdx0111 the code that is failing is actually in VS Code rather than this extension. The C# extension is just reporting the error message that VS Code returns -- `can't find terminal application 'dumb'`.

I may need to pass you off to the VS Code repo for more help, but one thing to check is that in VS Code preferences you can set what external terminal you want to use. So you might see what that is configured to and if you can change it to something that works.

**Comment by mdx0111** [comment]
Hi Gregg,

You were absolutely right. It was VS Code that couldn't find the right terminal to use. For some reason that I don't understand, it was set to 'dumb'! I just changed it to KDE Konsole and the problem is resolved.

Many many thanks for your help.
