### ISSUE TITLE
Automatically prompt to create and trust ASP.NET Core HTTPS development certificate

### ISSUE THREAD

**Issue by bwateratmsft** [OmniSharp/omnisharp-vscode#3187]
Currently, ASP.NET Core web apps created with "dotnet new" have HTTPS enabled by default. The very first time you debug (or, after `dotnet dev-certs https --clean`), when no cert is created, debugging will fail, telling the user to run `dotnet dev-certs https`, optionally with `--trust` on Mac/Windows.

Similarly to how this extension suggests to create the tasks.json/launch.json when opening a C# project, I think it should prompt to do the above `dotnet dev-certs https [--trust]` when opening an ASP.NET Core project when HTTPS is enabled on it, if no cert is already trusted.

On Windows, a popup asks if the user wants to trust the certificate; on Mac it requires password input, so it is still user-interactive, and the user needs to know to expect the popup if they say "Yes" to creating/trusting the cert. (On Linux there's no centralized store for trusted certs, so this is moot there.)

**Comment by gregg-miskelly** [comment]
It looks like the extension could use `dotnet dev-certs https --check` to detect if it is installed...

**Comment by bwateratmsft** [comment]
@gregg-miskelly That's right. Playing around with them I've noticed that `dotnet dev-certs https --check` checks to see if it's been created, and `dotnet dev-certs https --check --trust` checks if it's created _and_ trusted.

**Comment by rchande** [comment]
@NTaylorMullen @danroth27 Thoughts on prioritization for this?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen @danroth27 Thoughts on prioritization for this?

Seems like a pretty easy addition to me. That being said, time is not infinite 😆, will leave it up to @danroth27

**Comment by gregg-miskelly** [comment]
A bit more detailed proposal on how I think we want to make this work:
1. Add a new launch.json option to enable/disable the dev-certs check. Something like `checkForDevCert: bool?`. If unspecified, it will be enabled when `serverReadyAction` is set.
2. The first time a project is launched in a VS Code session the extension will run through the following checks:
     A. Is the OS Linux or are we in VS Code remote, VS Code running in a browser, or is it a remote debugging scenario ([`pipeTransport`](https://github.com/OmniSharp/omnisharp-vscode/blob/09b09bc069e4eefea65ef6d9bb436a0809e5ded5/src/tools/OptionsSchema.json#L372) is set)? If so, do nothing.
     B. Run `dotnet dev-certs https --check`, and check the exit code to determine success. If this returns zero, we are done.
     C. If `dotnet dev-cert fails` then prompt the user to ask if they want to install the development cert. We should be able to use similar language to what Visual Studio currently uses (though not quite the same, more details below). We want to have a prompt since if the user hits "yes" this will result in a security prompt, and we want to make sure the user understands what this is from.
     D. If the user hits "yes" run `dotnet dev-certs https --trust`. If this succeeds (zero exit code) mark this as successful so that we will not try again in this VS Code session

Implementation notes:
1. The prompt message needs two changes:
    * Instead of the "Don't ask me again", we should indicate that the user can set the launch.json option
    * We will not know if the project is configured to use SSL or not, so maybe instead say "The selected launch configuration is configured to launch a web browser."
2. We want to do this work in [src/coreclr-debug/debugConfigurationProvider.ts](https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/coreclr-debug/debugConfigurationProvider.ts)
3. Launch.json options are added in [src/tools/OptionsSchema.json]()https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/tools/OptionsSchema.json. Then run `npm run gulp generateOptionsSchema` to update package.json. They must also be documented in debugger-launchjson.md
4. I am hoping we can just spawn `dotnet` as a child process, but if not, maybe we could use [`tasks.executeTask`](https://github.com/microsoft/vscode/blob/c83eff40dd2c2115f5fd5e67a6ce304fbc6fdefa/src/vscode-dts/vscode.d.ts#L7928) to run it as something that would be user-visible in the VS Code terminal window.
5. I hope we can use [`env.remoteName`](https://github.com/microsoft/vscode/blob/c83eff40dd2c2115f5fd5e67a6ce304fbc6fdefa/src/vscode-dts/vscode.d.ts#L9268) and [`env.uiKind`](https://github.com/microsoft/vscode/blob/c83eff40dd2c2115f5fd5e67a6ce304fbc6fdefa/src/vscode-dts/vscode.d.ts#L9282) to detect if we are running remotely.

Prompt in Visual Studio:
![image](https://user-images.githubusercontent.com/11078489/214454803-e9af2b30-6366-4fb4-b011-5cddd3f00f17.png)

**Comment by danroth27** [comment]
@DamianEdwards @javiercn Should any details from @gregg-miskelly's proposal be adjusted given the HTTPS changes we made in .NET 7?

**Comment by DamianEdwards** [comment]
The proposal seems reasonable but we should confirm what the flow ends up looking like on macOS as the OS prompts there can be a little more intense (e.g. asking for passwords, etc.). Also the first launch profile in launchsettings.json now is one that doesn't use https so we may want to consider how the https-enabled profile gets selected, e.g. in VS it finds the first https enabled profile and launches that.

**Comment by gregg-miskelly** [comment]
@DamianEdwards I reopened #5417 to track selecting the 'https' profile by default (on Mac and Windows only) if no launch profile is selected.

**Comment by sayedihashimi** [comment]
Looks good to me, this seems like it would be a great addition.

**Comment by javiercn** [comment]
I think if we can enable this in VS Code it would be great. We need to just check what @DamianEdwards mentions here.
