### ISSUE TITLE
Is there any way to customise the "vsdbg.exe" path?

### ISSUE THREAD

**Issue by drk-mtr** [OmniSharp/omnisharp-vscode#3196]
## Use case

- Debugging using the `integratedTerminal` setting
- Using the ZSH shell via WSL on Windows
- Using the Windows instance of `vsdbg` - but calling it from WSL

## Current behaviour

When debugging a dotnet core application and using the integrated terminal option in `launch.json`, the following is sent to the terminal:

> `C:\\Users\\{myuser}\\.vscode-insiders\\extensions\\ms-vscode.csharp-1.21.0\\.debugger\\vsdbg.exe --interpreter=vscode --connection=2d1e685322624ffead8027433d49c520`

Naturally this fails while using WSL for the shell as it's a windows path.

## Workaround

If I manually type the following command in the shell, the debugger attaches fine:

> `/mnt/c/Users/{myuser}/.vscode-insiders/extensions/ms-vscode.csharp-1.21.0/.debugger/vsdbg.exe  --interpreter=vscode --connection=2d1e685322624ffead8027433d49c520`

## Feature request

It would be great if we were able to customise the path to `vsdbg`. Maybe this is already a feature and I've missed it in the docs - or maybe what I'm trying to do here is very silly - apologies if so.

While I'm here, thanks for the brilliant software!

**Comment by gregg-miskelly** [comment]
@drk-mtr here is what you want to do: https://github.com/OmniSharp/omnisharp-vscode/wiki/Windows-Subsystem-for-Linux

**Comment by gregg-miskelly** [comment]
Oh wait, maybe I am misunderstanding your scenario. Are you trying to run your program as a Windows program? Or in Linux?

**Comment by drk-mtr** [comment]
Cheers for taking a look. I can see that this will allow me to run it as a Linux program and attach a debugger from Windows. However what I'm trying to understand is whether I can run the Windows debugger but output to the WSL shell.

It may well be that what I'm trying to do here is not recommended and will lead to issues - in which case I'll shut up! From what I could tell though, running the following command from WSL seems to work fine:

> `/mnt/c/Users/{myuser}/.vscode-insiders/extensions/ms-vscode.csharp-1.21.0/.debugger/vsdbg.exe --interpreter=vscode --connection=2d1e685322624ffead8027433d49c520`

Because of this, I assumed it's probably technically feasible and just requires that we have the ability to override the `vsdbg` path that is passed to the terminal as an argument. Just because it works doesn't mean it should be done of course... however it would be great if we're able to set this if only just to have a play.

My use case is essentially that I like using the zsh (on WSL) shell in vscode; I have no particular need to run the program itself from Linux (although it's brilliant that you offer the functionality to do this too, really opens up cloud dev possibilities).

**Comment by gregg-miskelly** [comment]
The C# extension asks VS Code to execute `C:\\Users\\{myuser}\\.vscode-insiders\\extensions\\ms-vscode.csharp-1.21.0\\.debugger\\vsdbg.exe ...` -- it doesn't know what the current terminal is, or what VS code might do to run it. I think the right place for this feature request (or question, maybe they have this feature already) is in VS Code so that they could change the text that the send to the terminal in order to execute the command if WSL zsh is configured as the default terminal. Or maybe just an option to specify a prefix for all commands, and you could set that to be some bash script that rewrites the path.

**Comment by drk-mtr** [comment]
Ah ok, makes sense. I think I had assumed that since this is a string sent by the C# extension, the correct place to override this would be `omnisharp.json`, rather than it being handled externally.

I think that approach still seems "right" to me to be honest, however I can certainly understand the opposition to this since:

- My use case is very esoteric
- It could lead to a scenario where people customise it, forget to amend it when the extension updates, then file loads of false bug reports when things inevitably break
- Allowing it to be customised is more "moving parts" for the Omnisharp team to manage

More than happy to close this if that's the decision, but I just wanted to double check that this is what we're saying?

I'll file a request with the VS Code team if so - a prefix option would work fine as you say (in fact I've already thrown together a script to parse the terminal output and convert it, I just couldn't figure out a nice way to get it to pipe in the previous command automatically!).

Thanks again for the help on this.

**Comment by gregg-miskelly** [comment]
Yes, I feel like this isn't the only place where a tool is trying to launch something in the terminal, and if we are going to fix it, there should really be a holistic fix, especially because of your second bullet.

**Comment by drk-mtr** [comment]
Makes sense - cheers!
