### ISSUE TITLE
Cannot Start Omnisharp [ERROR] Error: spawn cmd ENOENT

### ISSUE THREAD

**Issue by alexandrudima** [OmniSharp/omnisharp-vscode#32]
Moved from microsoft/vscode#2841
From @sorab2142

Trying to open a Unity3d solution (sln). One that works fine on another machine with VSCode but does'nt start on another.

**Comment by trendoid** [comment]
I have the same error when I open a C# file.  I'm not using Unity3d, it's just my web application.

**Comment by DustinCampbell** [comment]
@sorab2142, @trenoid: Are either of you still experiencing this problem with the C# Extension for VS Code? This issue is pretty stale, so I'm going to go ahead and close it, but please let me know if you're still experiencing this problem.

**Comment by sorab2142** [comment]
@DustinCampbell yes this problem still persists. Is there something I could do to help find out why this is happening?

**Comment by trendoid** [comment]
@sorab2142 I'm not seeing this since I have upgraded to the latest VS Code and .NET Core.  I also updated the C# extension in VS Code.  I'm on Windows 10.  My version of the C# extension is 1.3.0, VS Code 1.3.1 and .NET 1.0.0-preview2-003121

I don't know if that will help you but I'm not seeing this anymore.

**Comment by matthewreily** [comment]
I'm seeing the issue on my machine using Windows 10, C# extension 1.3.0 and vs code 1.3.1 and .NET 1.0.0-preview2-003121.  Is there any other information I can send that would be helpful in resolving this?

**Comment by DustinCampbell** [comment]
@matthewreily: Could you provide your OmniSharp log output?

**Comment by matthewreily** [comment]
I would love to, unfortunately I nuked my machine and reinstalled everything from the OS up.  I had a tight deadline with a presentation I was doing on cross platform dev and .net core.  I'll see if I can't recreate in my new environment and send the log if  so. Thank you so much for following up!

**Comment by sorab2142** [comment]
The only thing i see in the vs code panel for Omnisharp Log is that one line (Cannot Start Omnisharp [ERROR] Error: spawn cmd ENOENT), is there some file that has more info?

**Comment by ChristianoKiss** [comment]
I had this problem using Windows 10 and solved it by adding "C:\Windows\System32\" in the PATH variable.

**Comment by sorab2142** [comment]
@ChristianoKiss thank you that worked.

**Comment by DustinCampbell** [comment]
I suspect that this may be addressed with the latest version of the extension (1.5.2). We've recently made a lot of changes under the hood to how OmniSharp is packaged and runs that should fix these issues. Please let me know if you run into these problems on the new release.

**Comment by Gazenvagin** [comment]
Hi, 
>
Starting OmniSharp server at 2018-2-11 11:48:38
    Target: c:\inWORK\UNITY Projects\Visockiy\Visockiy.sln
[ERROR] Error: spawn cmd ENOENT
_____
VSC ver. 1.20.00 x64
ext: Unity Debugger, OmiSharp
Unity 2017.3.1f3

**Comment by barnagit** [comment]
Starting OmniSharp server at 2018-5-9 23:25:14
    Target: /Users/barnabas.hajzer/Desktop/Codewards-Projects/Sum_Strings_as_Numbers

[ERROR] Error: spawn /Users/barnabas.hajzer/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/run ENOENT

for opening a C# file

**Comment by BedmanGit** [comment]
Add path to environment works
http://reddyinfosoft.blogspot.com/2017/07/cannot-start-omnisharp-error-error.html

**Comment by genesis-1** [comment]
thank you so much at @ChristianoKiss

**Comment by thisisgreat23** [comment]
thanks, @ChristianoKiss :D

**Comment by connormulcahey** [comment]
On Linux adding ~/.vscode/extensions to my path fixed it.

e.g. in your .bashrc

`export PATH=$HOME/.vscode/extensions:$PATH`
