### ISSUE TITLE
How do I install the C# extension on linux?

### ISSUE THREAD

**Issue by NewGuy11** [OmniSharp/omnisharp-vscode#3202]
The command on the app page doesn't work.

**Comment by gregg-miskelly** [comment]
@NewGuy11 If you are asking how to install the extension -- extensions in VS Code from the extensions panel -- click the square icon on the left side bar (see [here](https://code.visualstudio.com/docs/editor/extension-gallery) for more info). Then search for 'C#' in the marketplace.

**Comment by NewGuy11** [comment]
@gregg-miskelly Thanks! Turns out I already had it installed, just didn't know where to look.
