### ISSUE TITLE
discontinuousness  of indent guide lines 

### ISSUE THREAD

**Issue by kzhui125** [OmniSharp/omnisharp-vscode#3204]
<img width="414" alt="1" src="https://user-images.githubusercontent.com/11925432/62274582-bfe15d80-b472-11e9-9840-28536fdd4522.png">

**Comment by kzhui125** [comment]
this is C# extension enabled:


<img width="309" alt="1" src="https://user-images.githubusercontent.com/11925432/62275548-cb358880-b474-11e9-9649-43c221b19160.png">

the discontinuousness is ugly

**Comment by rchande** [comment]
@kzhui125 This is likely a VS Code editor bug. Please feel free to file this directly against VS Code.

**Comment by rchande** [comment]
(Specifically, the connector lines are not drawn in the space occupied by the CodeLens indicator)
