### ISSUE TITLE
Getting MSBuild solution structure and MSBuild properties from VS code extensions

### ISSUE THREAD

**Issue by kekekeks** [OmniSharp/omnisharp-vscode#3208]
I'm trying to port an extension for the "full" visual studio and I kinda need the dependency tree and some MSBuild property values. Is it possible to somehow get those? OmniSharp plugin seems to be the only place with that information.

**Comment by akshita31** [comment]
@kekekeks The C# extension uses omnisharp-roslyn to do all the MSBuild related stuff. In your extension you can create an omnisharp process and try to get the relevant MSBuild information. You can llok at the Omnisharp.MSBuild project here https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.MSBuild/MSBuildHelpers.cs

**Comment by kekekeks** [comment]
>you can create an omnisharp process 

I might as well just parse `.sln` file and run MSBuild manually, but I'm looking for a way to reuse the existing infrastructure and to avoid spawning any extra processes.

Right now from the perspective of a full VS extension developer, VSCode isn't an IDE, because of the lack of "Integrated" part of the acronym. I think providing project system services would bring VS Code closer to the full Visual Studio.

**Comment by akshita31** [comment]
@kekekeks The C# extension is just a thin wrapper around omnisharp-roslyn and intended to 
1. Collect information about your workspace
2. Pass it to omnisharp and get all relevant information like signature help, references
3. Format the information received from omnisharp into vscode types so that they can be displayed appropriately.

I am not sure what is the api surface you are expecting from the extension and how you are planning to consume it. Could you provide a more detailed description of what api you are expecting and how will it be consumed?

**Comment by kekekeks** [comment]
With the full Visual Studio one can enumerate configurations, projects, TFM confugurations (aka ConfiguredProject), get project dependency tree, resolve msbuild properties, etc.

For my extension in particular I need to:

1) get the list of projects a particular file (not `.cs` one, from a custom ItemGroup) belongs to
2) get the list of project depependencies
3) get values of MSBuild properties like `OutputPath` and some custom properties set by nuget package build items

I can get those by parsing `.sln` file manually and using MSBuild evaluation API, but I'd rather use services provided by the IDE. Basically I need something like https://github.com/microsoft/VSProjectSystem from the full visual studio.


Is that something the current client-server architecture of VSCode can't deal with?

**Comment by stevenbrix** [comment]
> Right now from the perspective of a full VS extension developer, VSCode isn't an IDE, because of the lack of "Integrated" part of the acronym. I think providing project system services would bring VS Code closer to the full Visual Studio.

> I can get those by parsing .sln file manually and using MSBuild evaluation API, but I'd rather use services provided by the IDE. 

@kekekeks I think this is a pretty intentional design decision of VS Code. It doesn't want any of the extra "fluff" that comes with Visual Studio.

**Comment by cartermp** [comment]
Closing old issue
