### ISSUE TITLE
Failed at stage: downloadPackage

### ISSUE THREAD

**Issue by pvt900** [OmniSharp/omnisharp-vscode#3209]
## Issue Description ##
I've installed the extension, hunted down the dependencies because my Company Proxy/Firewall prevents the dependencies from properly downloading and I still get this error. 
I've manually installed .omnisharp, .debugger and .razor according to my Windows 10 64bit packages. I've placed omnisharp both in .omnisharp/1.34.0/omnisharp.exe and in .omnisharp/OmniSharp.exe neither made a difference
## Expected Behavior ##
The Package to have the files and dependencies installed so that when the checks are made they don't erro?
### OmniSharp log ###
Starting OmniSharp server at 8/2/2019, 1:37:10 PM
    Target: c:\Users\UFJUDFM\Documents\cpp\csharp

OmniSharp server started.
    Path: C:\Users\UFJUDFM\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\OmniSharp.exe
    PID: 15404

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.0 - "C:\Users\UFJUDFM\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Users\UFJUDFM\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.0 - "C:\Users\UFJUDFM\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Users\UFJUDFM\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = C:\Users\UFJUDFM\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\.msbuild
            MSBuildToolsPath = C:\Users\UFJUDFM\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\UFJUDFM\Documents\cpp\csharp'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\UFJUDFM\Documents\cpp\csharp'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\UFJUDFM\Documents\cpp\csharp'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\UFJUDFM\Documents\cpp\csharp' on host 14024.

### C# log ###
Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' 	Retrying from 'https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.34.0.zip' Failed at stage: downloadPackage
Error: unable to get local issuer certificate
## Environment information ##

**VSCode version**: 1.36.1
**C# Extension**: 1.21.0

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.401\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|2077-theme|Endormi|1.3.0|
|code-gnu-global|austin|0.2.2|
|code-runner|formulahendry|0.9.12|
|cpptools|ms-vscode|0.24.1|
|csharp|ms-vscode|1.21.0|
|debugger-for-chrome|msjsdiag|4.11.7|
|java|redhat|0.47.0|
|jinja|wholroyd|0.0.8|
|jinja2-snippet-kit|WyattFerguson|1.1.2|
|jinjahtml|samuelcolvin|0.10.5|
|MagicPython|magicstack|1.1.0|
|material-icon-theme|PKief|3.8.1|
|Material-theme|zhuangtongfa|2.26.0|
|npm-intellisense|christian-kohler|1.3.0|
|python|ms-python|2019.6.24221|
|python|tht13|0.2.3|
|python-extension-pack|donjayamanne|1.6.0|
|quicktype|quicktype|12.0.46|
|scriptcsRunner|filipw|0.1.0|
|vscode-django|batisteo|0.19.0|
|vscode-icons|vscode-icons-team|9.2.0|
|vscode-install-vsix|fabiospampinato|1.4.0|
|vscode-java-debug|vscjava|0.20.0|
|vscode-java-dependency|vscjava|0.5.1|
|vscode-java-pack|vscjava|0.7.1|
|vscode-java-test|vscjava|0.18.2|
|vscode-maven|vscjava|0.18.1|
|vscode-npm-script|eg2|0.3.8|
|vscodeintellicode|VisualStudioExptTeam|1.1.8|;

</details>

**Comment by akshita31** [comment]
@pvt900 The installer looks for a "install.Lock" file to check if the downloads have successfully downloaded and unzipped. Could you try placing an install.Lock file in the .omnisharp/1.34.0 folder and checking if the problem still perists ?

**Comment by pvt900** [comment]
I placed a Install.Lock file and it seems it no longer errors looking to install the omnisharp.exe, However now I'm trying to execute a simple Fibonacci program as a test file and I'm unable to get that to run.  I hit F5 and a launch.json get created with a warning message about being a Placeholder? This is unfortunately the first time I've tried getting C# to run so pardon the inexperience. I'm use to python and just running the files.

**Comment by akshita31** [comment]
@pvt900 Can you provide some screenshot of the issue you are facing. Also can you provide the output from your [OmniSharp log](https://github.com/OmniSharp/omnisharp-vscode/wiki/Reporting-Issues#omnisharp-and-c-log)

**Comment by govindakatkamwar** [comment]
I am also a similar issue 

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' 	Retrying from 'https://roslynomnisharp.blob.core.windows.net/releases/1.35.2/omnisharp-win-x64-1.35.2.zip' Failed at stage: downloadPackage
Error: write EPROTO 2956726360:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

Does anyone know how to fix this?

**Comment by cartermp** [comment]
Closing old issue - we have a larger overall problem with asset acquisition that isn't really solvable without rethinking how we do things
