### ISSUE TITLE
No quick fixes shown when editorconfig is not in project root folder

### ISSUE THREAD

**Issue by FunkMonkey** [OmniSharp/omnisharp-vscode#3212]
## Issue Description ##

After enabling editorconfig support, problems are correctly reported, but there are no quick fixes shown. 

Also sometimes there are actually quick fixes for formatting that don't respect the settings in `.editorconfig` (probably because these are the standard C# quick fixes).

## Steps to Reproduce ##

I enabled editorconfig support as described [here](https://www.strathweb.com/2019/07/editorconfig-support-in-omnisharp-and-c-extension-vs-code/):
```
"omnisharp.enableEditorConfigSupport": true,
"omnisharp.enableRoslynAnalyzers": true
```

Open a CS file (from a Unity project) and see the problems highlighted in the editor, but no quick fixes.

## Expected Behavior ##

See a list of quick fixes that can be applied.

## Actual Behavior ##

No list of quick fixes presented.

### OmniSharp log ###
<details>
Starting OmniSharp server at 3.8.2019, 14:34:10
    Target: f:\Projekte\UnityLibs\RxStateMachine\workspace\workspace.sln

OmniSharp server started.
    Path: C:\Users\Andre\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\OmniSharp.exe
    PID: 2376

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 3 MSBuild instance(s)
            1: Visual Studio Build Tools 2017 15.9.28307.222 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            2: Visual Studio Community 2017 15.9.28307.222 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            3: StandAlone 16.0 - "C:\Users\Andre\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Users\Andre\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.0 - "C:\Users\Andre\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Users\Andre\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = C:\Users\Andre\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\.msbuild
            MSBuildToolsPath = C:\Users\Andre\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'f:\Projekte\UnityLibs\RxStateMachine\workspace'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'f:\Projekte\UnityLibs\RxStateMachine\workspace\workspace.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'f:\Projekte\UnityLibs\RxStateMachine\workspace\Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'f:\Projekte\UnityLibs\RxStateMachine\workspace\Assembly-CSharp-firstpass.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'f:\Projekte\UnityLibs\RxStateMachine\workspace'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: f:\Projekte\UnityLibs\RxStateMachine\workspace\Assembly-CSharp.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'f:\Projekte\UnityLibs\RxStateMachine\workspace' on host 7748.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'f:\Projekte\UnityLibs\RxStateMachine\workspace\Assembly-CSharp.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'f:\Projekte\UnityLibs\RxStateMachine\workspace\Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: f:\Projekte\UnityLibs\RxStateMachine\workspace\Assembly-CSharp-firstpass.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'f:\Projekte\UnityLibs\RxStateMachine\workspace\Assembly-CSharp-firstpass.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'f:\Projekte\UnityLibs\RxStateMachine\workspace\Assembly-CSharp-firstpass.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly 'f:\Projekte\UnityLibs\RxStateMachine\workspace\Temp\bin\Debug\Assembly-CSharp-firstpass.dll'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-firstpass
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 8.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: Formatierung beheben
</details>

Last code action is one of the wrong formatting quick fixes.

## Environment information ##

**VSCode version**: 1.36.1
**C# Extension**: 1.21.0

<details><summary>Dotnet Information</summary>
A valid dotnet installation could not be found.</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|atom-keybindings|ms-vscode|3.0.6|
|csharp|ms-vscode|1.21.0|
|node-module-intellisense|leizongmin|1.5.0|
|python|ms-python|2019.6.24221|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-debug|Unity|2.7.2|
|unity-tools|Tobiah|1.1.1|
|vscode-eslint|dbaeumer|1.9.0|
|workspacesort|iciclesoft|1.5.7|;
</details>

### C# log ###
Where's that?

**Comment by filipw** [comment]
thanks - unfortunately at the moment it is not very clear what is not working here.

could you please:
- share your editorconfig file and explain which settings are not working for you? 
- show a sample of code that gets an analyzer but doesn't get a code fix (not every analyzer must have a code fix)
- set "omnisharp.loglevel" to debug or trace and share the output of the log again

I noticed you have your system in german, does the same happen when the os language is set to English? also, is it possible for you to share the repro (have you tried on a normal .NET core project, instead of unity?)

**Comment by FunkMonkey** [comment]
Thanks for the quick answer, @filipw !

It seems I have misinterpreted the problem due to a couple of reasons:
1. the `Quick Fix...` button, when hovering, doesn't work (no code actions available), but quick fixes using the keyboard shortcut or the yellow bulb *do* work in normal C# projects (non-Unity)
2. my `.editorconfig` is simply ignored in projects created by Unity (I thought it worked, because I had similar rules).
  - it seems Unity-specific rules are used (e.g. a naming rule for starting methods with a capital letter), but I have no idea where they come from

I think 1. may be a bug in `omnisharp-vscode`. For 2. I have no idea where the problem comes from. Do you?

**Comment by filipw** [comment]
would you be able to provide a repro for this project somewhere on github? that would be very helpful - thanks

**Comment by FunkMonkey** [comment]
Sure thing, here it is:
https://github.com/FunkMonkey/omnisharp-vscode-issue-3212

Normally the `sln` and `csproj` are excluded from the git repo, but I provided them for reference. The Project was created using Unity 2019.2.0f

Here the difference between VS Code and VS Community 2017:
![vscode](https://user-images.githubusercontent.com/181654/62971064-2ff7c800-be11-11e9-86b0-e281426cd278.png)
![vscommunity2017](https://user-images.githubusercontent.com/181654/62971074-34bc7c00-be11-11e9-8a53-3d398366efdf.png)

Thanks for the help!

**Comment by FunkMonkey** [comment]
Oh, I just saw how many absolute paths are in the `csproj`. Maybe you better delete both files and let them get recreated by Unity.

**Comment by FunkMonkey** [comment]
Any update on this?

Thanks a lot!

**Comment by FunkMonkey** [comment]
@filipw I did some more tests and it seems I misinterpreted the reasons once again.

It has nothing to do with Unity projects! The omnisharp extension simply ignores the `.editorconfig` if it is in a subfolder. (e.g. `Assets/scripts` as in my Unity project).

It would be nice, if the location of the `.editorconfig` file didn't matter. For my case putting the `.editorconfig` in the root folder would mean that other cs files in my repository (e.g. Unity plugins) will be reformatted or throw formatting errors.

Thanks a lot!

**Comment by cartermp** [comment]
This appears to have been fixed with the latest plugin, at least as far as I can tell:

![image](https://user-images.githubusercontent.com/6309070/84211931-645c0500-aa71-11ea-928e-44d7b689729c.png)

Please do ping back if you don't see similar behavior.
