### ISSUE TITLE
C# IntelliSense failing to load

### ISSUE THREAD

**Issue by hamhub7** [OmniSharp/omnisharp-vscode#3224]
## Issue Description ##
When I launch a C# script, there is a pop-up in the bottom right that says "Some projects have trouble loading. Please review the output for more details." I'm using this with Unity and I'm unable to see any autocomplete things besides words that I have already typed in the document.

## Steps to Reproduce ##
This happens all the time, whenever I boot up VS Code.

## Expected Behavior ##
Autocompletion of functions and variables from Unity.
## Actual Behavior ##
No autocompletion or suggestions at all besides built in functionality.
### OmniSharp log ###
Starting OmniSharp server at 8/11/2019, 12:12:46 PM
    Target: d:\Udemy RPG\Udemy RPG.sln

OmniSharp server started.
    Path: C:\Users\Aaron\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\OmniSharp.exe
    PID: 9380

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 4 MSBuild instance(s)
            1: Visual Studio Build Tools 2017 15.9.28307.770 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            2: Visual Studio Community 2019 16.2.29123.88 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            3: Visual Studio Community 2017 15.9.28307.770 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            4: StandAlone 16.0 - "C:\Users\Aaron\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.2.29123.88 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\Udemy RPG'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'd:\Udemy RPG\Udemy RPG.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Udemy RPG\Assembly-CSharp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\Udemy RPG'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Udemy RPG\Assembly-CSharp.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\Udemy RPG' on host 19688.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\Udemy RPG\Assembly-CSharp.csproj'.
d:\Udemy RPG\Assembly-CSharp.csproj
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1175,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: d:\Udemy RPG\Assembly-CSharp.csproj

### C# log ###
Nothing shows in this tab

## Environment information ##

**VSCode version**: 1.37.0
**C# Extension**: 1.21.0

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.401\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|cpptools|ms-vscode|0.25.0-insiders|
|csharp|ms-vscode|1.21.0|
|discord-vscode|icrawl|3.8.1|
|python|ms-python|2019.8.29288|
|remote-wsl|ms-vscode-remote|0.39.2|
|team|ms-vsts|1.149.2|
|vscode-markdownlint|DavidAnson|0.30.1|;

</details>

**Comment by rchande** [comment]
@hamhub7 Your log includes the error `The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks`. Can you try installing the 4.7.1 developer pack from the link?

**Comment by gtoto007** [comment]
Hi @rchande, Suddenly I have same issue. For my case, the problem that ".NET Framework 4.7.1" for mac don't exist.

**Comment by andsynchrony** [comment]
Installing Mono helped me. Seen [here](https://github.com/OmniSharp/omnisharp-vscode/issues/2808#issuecomment-456999050)

**Comment by cartermp** [comment]
@rchande is correct here. Mono can also help if it's the right version and brings along the appropriate reference assemblies. Once this is installed, there shouldn't be any issues.
