### ISSUE TITLE
Folding should only be expanded by double-clicking the end

### ISSUE THREAD

**Issue by larryw3i** [OmniSharp/omnisharp-vscode#3225]
Folding should only be expanded by double-clicking the end, 😭 I often expand it when I click inadvertently    

<img src='https://raw.githubusercontent.com/larryw3i/tomato/master/Screenshot%20from%202019-08-14%2000-08-06.webp'/>

**Comment by rchande** [comment]
@larryw3i This UI is controlled by VS Code--feel free to file this issue against it.
