### ISSUE TITLE
 Remote - Containers : No HTML or RAZOR Intellisense in .cshtml file for Dotnet MVC project

### ISSUE THREAD

**Issue by HoTKreeZy** [OmniSharp/omnisharp-vscode#3227]
## Environment data
- `dotnet --info` output: 
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.401/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App] 
```
- C# Extension version: 1.21.0
- VSCode Version: 1.37.0
- Local OS Version: macOs Mojave v10.14.6
- Remote OS Version: Linux debian 9
- Remote Extension/Connection Type: Docker

## Steps to reproduce
1. Create a folder on my local machine that will contains my project
2. Open this folder inside vs code
3. Use the remote-container extension : 
    - Add Development Configuration file : `C# (.NET Core Latest)`( mcr.microsoft.com/dotnet/core/sdk:latest )
    - Reopen folder in container
4. Create project inside the container : dotnet new mvc
5. Open any CS file and wait for Omnisharp installation
6. Open any CSHTML file and try to write some html but got no intellisense for both html or razor syntax

## Expected  behavior
Have html and razor intellisense for `.cshtml` file

## Actual behavior
Don't have any intellisense 

## Project repository
I created a public repo with the full project to run in a remote container with the extension  : https://github.com/HoTKreeZy/TryAspCore

**Comment by rchande** [comment]
cc @NTaylorMullen

**Comment by NTaylorMullen** [comment]
@HoTKreeZy thanks for the report! Would you mind filing this issue over at https://github.com/aspnet/Razor.VSCode? Adding remote development support to Razor is definitely something we want to add.

**Comment by HoTKreeZy** [comment]
@NTaylorMullen Ok, so it is not a bug ? It is a feature request ?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen Ok, so it is not a bug ? It is a feature request ? Do I have to close this issue ?

Feature request and ya closing this issue would be best 😄

**Comment by HoTKreeZy** [comment]
Ok, thanks :)
