### ISSUE TITLE
VER 1.38 Intellisense doesn't work on one of c# projects in Visual Studio Code

### ISSUE THREAD

**Issue by kinglionsz** [OmniSharp/omnisharp-vscode#3229]
Issue Type: <b>Bug</b>

Step by step:

1,building a new file new.cs
2,type using System;
3,type Console.WriteLine();

Intellisense doesn't work,

VS CODE:August 2019 (version 1.38)
Remote	WSL: Ubuntu-18.04
Extension version: 1.21.0
VS Code version: Code - Insiders 1.38.0-insider (ba69d8dcccaebbfaa94906503728eb7c3e45b9c1, 2019-08-14T07:18:43.039Z)
OS version: Windows_NT x64 10.0.18956
Remote OS version: Linux x64 4.4.0-18956-Microsoft

**Comment by SIkebe** [comment]
>2,type using system;

Try `using System;`

**Comment by kinglionsz** [comment]
> > 2,type using system;
> 
> Try `using System;`

Yes, using System;

the issues is only for the new building  .cs files,

**Comment by rchande** [comment]
@kinglionsz Can you share the full text of your file? You can't write expressions at the top level, so something
```C#
using System;
Console.WriteLine();
```

will not have good intellisense.

**Comment by kinglionsz** [comment]
> @kinglionsz Can you share the full text of your file? You can't write expressions at the top level, so something
> 
> ```cs
> using System;
> Console.WriteLine();
> ```
> 
> will not have good intellisense.

yes,I see. here is the file.
<img width="448" alt="It sees that there is no any IntelliSense" src="https://user-images.githubusercontent.com/51827261/63135728-7875d800-c001-11e9-95fe-8aa92c6d0164.png">



`using Internal;
using System;
using System.Collections.Generic;

namespace list_tutorial
{
    class Program
    {
        static void Main(string[] args)
        {
            var names = new List<string> {"kinglion","Ana","Felipe"};
            foreach (var name in names)
            {
                Console.WriteLine($"Hello {name.ToUpper()}!") ; 
                Console.W
            }
        }
    }
}
`

It sees that there is no any IntelliSense
<img width="448" alt="It sees that there is no any IntelliSense" src="https://user-images.githubusercontent.com/51827261/63135621-3187e280-c001-11e9-8b17-ccdf6d9e3cec.png">
 ,for example ,type "using S  ",should see "using System" ext.
or type "name.C" ,we should see "name.Counter", type "Console.W",we should see "Console.WriteLine" ...,in fact ,there's no anything we expect.

**Comment by kinglionsz** [comment]
> @kinglionsz Can you include your omnisharp log?

Starting OmniSharp server at 9/10/2019, 2:40:56 PM
    Target: /mnt/e/CodeSources/learn/wsl_dotnet/LetClause/LetClause.sln

[ERROR] TypeError: Cannot read property 'on' of undefined
Starting OmniSharp server at 9/10/2019, 3:29:33 PM
    Target: /mnt/e/CodeSources/learn/wsl_dotnet/LetClause/LetClause.sln

[ERROR] TypeError: Cannot read property 'on' of undefined

**Comment by kinglionsz** [comment]
> Issue Type: Bug
> 
> Step by step:
> 
> 1,building a new file new.cs
> 2,type using System;
> 3,type Console.WriteLine();
> 
> Intellisense doesn't work,
> 
> VS CODE:August 2019 (version 1.38)
> Remote WSL: Ubuntu-18.04
> Extension version: 1.21.0
> VS Code version: Code - Insiders 1.38.0-insider (ba69d8dcccaebbfaa94906503728eb7c3e45b9c1, 2019-08-14T07:18:43.039Z)
> OS version: Windows_NT x64 10.0.18956
> Remote OS version: Linux x64 4.4.0-18956-Microsoft

 **Hello @rchande , I'm very glad to tell you that the C# Intellisense works good👌now on the following version.Thank you very much for your time👍☕**

Extension version: 1.21.2
VS Code version: Code - Insiders 1.39.0-insider (bdd1971f2cd9d08a8a90e02740f1850afe03da66, 2019-09-17T06:02:08.670Z)
OS version: Windows_NT x64 10.0.18980
Remote OS version: Linux x64 4.4.0-18980-Microsoft

**Comment by kinglionsz** [comment]
Hello @rchande , I'm very glad to tell you that the C# Intellisense works good👌now on the following version.Thank you very much for your time👍☕
Yes.There's always a version that's okay.

```
Version: 1.39.0-insider (system setup)
Commit: a655c0836de8b8e06f4d56fa4e581b0ced53f56f
Date: 2019-10-03T05:36:55.111Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18995

Remote | WSL: Ubuntu-18.04
-- | --
OS | Linux x64 4.4.0-18995-Microsoft

.vscode-server-insiders/extensions/ms-vscode.csharp-1.21.4/.omnisharp/1.34.4/omnisharp/.msbuild/Current/Bin
.vscode-server-insiders/extensions/ms-vscode.csharp-1.21.4/.omnisharp/1.34.4/omnisharp/.msbuild/Current/Bin/Roslyn
.vscode-server-insiders/extensions/ms-vscode.csharp-1.21.4/.omnisharp/1.34.4/omnisharp/.msbuild/Current/Bin

:/mnt/e/CodeSources/cpptest/crayon$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /home/kinglion/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/home/kinglion/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/home/kinglion/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/home/kinglion/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

=================================================================

OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Professional 2019 16.4.29319.158 - "e:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin"
            2: StandAlone 16.0 - "...\.vscode-insiders\extensions\ms-vscode.csharp-1.21.4\.omnisharp\1.34.4\.msbuild\Current\Bin"

MINGW64 /e/CodeSources/cpptest/crayon (master)
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18995
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by kinglionsz** [comment]
C# editing IntelliSense is ok now.
Thanks.
Close.
