### ISSUE TITLE
There are too many 'problems' list with the project.

### ISSUE THREAD

**Issue by s2quake** [OmniSharp/omnisharp-vscode#3233]
Hello. 

I am using Visual Studio Code and .NET Core to create server and client libraries.

My project uses shared projects for source code sharing and some expressions such as #if are used.

Builds work well, but too many 'problems' lists occur.

Because of this, intelisense is not working well and it is difficult to create a library.

It's not a typical solution configuration, but because it builds well, I don't think I've configured the solution by expedient.

Sometimes the 'Restart Omni Sharp' command resolves it, but more often than not.

The source of the problem is as follows.

    https://github.com/s2quake/JSSoft.Communication

    git clone https://github.com/s2quake/JSSoft.Communication --recursive

![image](https://user-images.githubusercontent.com/887680/63163673-0f25b180-c061-11e9-9315-5377ed6eedb3.png)

### `dotnet --info` output:

.NET Core SDK(global.json 반영):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

런타임 환경:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://<span></span>aka.ms/dotnet-download

### VS Code version

Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

### C# Extension version
1.21.0

## Steps to reproduce

    git clone https://github.com/s2quake/JSSoft.Communication.git --recursive
    cd JSSoft.Communication
    code .

## Expected  behavior

build and intellisense work well, and no 'problems' list

## Actual behavior

build work well, but too many 'problems' lists occur. and intellisense does not work

**Comment by s2quake** [comment]
I found the cause of that problem.

i think the problem is TargetFramework`s`

the settings below are in the csproj file.

    <TargetFrameworks Condition="'$(MSBuildRuntimeType)'=='Full'">net45</TargetFrameworks>
    <TargetFrameworks Condition="'$(MSBuildRuntimeType)'=='Core' And '$(NETCoreAppMaximumVersion)'=='3.0'">netcoreapp3.0</TargetFrameworks>

I wanted to set configuration differently by IDE

Visual Studio 2019 -> net45

Visual Studio Code -> netcoreapp3.0

after replacing 'TargetFramework`s`' with 'TargetFramework', there is no problems in problems panel.

**Comment by s2quake** [comment]
condition below doesn't seem to be working.

    <PropertyGroup Condition="'$(MSBuildRuntimeType)'=='Core' And '$(NETCoreAppMaximumVersion)'=='3.0'">
        <TargetFramework>netcoreapp3.0</TargetFramework>
    </PropertyGroup>

**Comment by cartermp** [comment]
Hello @s2quake - the condition you mention will not work. It's not possible to conditionally set the TFM for a project. For example, this will not work in Visual Studio either. If you're looking to specify multiple target frameworks, you can use the `<TargetFrameworks>` node.

Separately, if you can share the codebase we can take a look and see if there's anything else causing this to misbehave.

**Comment by s2quake** [comment]
Thank you.
I've already changed it to `<TargetFrameworks>`.
