### ISSUE TITLE
Disposable XUnit tests cause cpu to spin

### ISSUE THREAD

**Issue by sudsy** [OmniSharp/omnisharp-vscode#3243]
## Issue Description ##
When editing an XUnit class that inherits from IDisposable, the mono process chews up all cpu on all available cores.

I also notice there are a number of errors relating to a missing Microsoft.VisualBasic.Mono.targets file. The actual file on my system is Microsoft.VisualBasic.targets

## Steps to Reproduce ##

Create an Xunit test project. 
Make a new test class that inherits from IDisposable
Create a new test method
Editing content within that method makes the cpu spike

## Expected Behavior ##

Editing should not cause the cpu to spike so dramatically

## Actual Behavior ##

mono uses all of the cpu

### OmniSharp log ###
Starting OmniSharp server at 22/08/2019, 3:38:54 pm
    Target: /Users/bensudbury/Development/gen3/PVL.sln

OmniSharp server started.
    Path: /Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/run
    PID: 32909

[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for framework ".NETFramework,Version=v4.7.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
/Users/bensudbury/Development/gen3/PVL.UserSettings/PVL.UserSettings.csproj
/Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1195,5): Error: The reference assemblies for framework ".NETFramework,Version=v4.7.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for framework ".NETFramework,Version=v4.7.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
/Users/bensudbury/Development/gen3/PVL.AuthServer/PVL.AuthServer.csproj
/Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1195,5): Error: The reference assemblies for framework ".NETFramework,Version=v4.7.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
/Users/bensudbury/Development/gen3/PVL.IdMgr/PVL.IdMgr.csproj
/Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1195,5): Error: The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for framework ".NETFramework,Version=v4.7.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
/Users/bensudbury/Development/gen3/PVL.UserSettings.Tests/PVL.UserSettings.Tests.csproj
/Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1195,5): Error: The reference assemblies for framework ".NETFramework,Version=v4.7.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
/Users/bensudbury/Development/gen3/PVL.Utilities/PVL.Utilities.csproj
/Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1195,5): Error: The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

[fail]: OmniSharp.MSBuild.ProjectLoader
        The imported project "/Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Microsoft.VisualBasic.Mono.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
/Users/bensudbury/Development/gen3/PVL.WebService.Tests/PVL.WebService.Tests.csproj
/Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Microsoft.VisualBasic.CurrentVersion.targets(55,5): Error: The imported project "/Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Microsoft.VisualBasic.Mono.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

[fail]: OmniSharp.MSBuild.ProjectLoader
        The imported project "/Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Microsoft.VisualBasic.Mono.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
/Users/bensudbury/Development/gen3/PVL.WebService.Core/PVL.WebService.Core.csproj
/Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Microsoft.VisualBasic.CurrentVersion.targets(55,5): Error: The imported project "/Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Microsoft.VisualBasic.Mono.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

[fail]: OmniSharp.MSBuild.ProjectLoader
        The imported project "/Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Microsoft.VisualBasic.Mono.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
/Users/bensudbury/Development/gen3/PVL.Orl.Integration.XUnit/PVL.Orl.Integration.XUnit.csproj
/Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Microsoft.VisualBasic.CurrentVersion.targets(55,5): Error: The imported project "/Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Microsoft.VisualBasic.Mono.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

[fail]: OmniSharp.MSBuild.ProjectLoader
        The imported project "/Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Microsoft.VisualBasic.Mono.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
/Users/bensudbury/Development/gen3/PVL.Proto.WorkerClient/PVL.Proto.WorkerClient.csproj
/Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Microsoft.VisualBasic.CurrentVersion.targets(55,5): Error: The imported project "/Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.0/.omnisharp/1.34.0/omnisharp/.msbuild/Current/Bin/Microsoft.VisualBasic.Mono.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/bensudbury/Development/gen3/PVL.UserSettings/PVL.UserSettings.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/bensudbury/Development/gen3/PVL.AuthServer/PVL.AuthServer.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/bensudbury/Development/gen3/PVL.IdMgr/PVL.IdMgr.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/bensudbury/Development/gen3/PVL.UserSettings.Tests/PVL.UserSettings.Tests.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/bensudbury/Development/gen3/PVL.Utilities/PVL.Utilities.csproj

### C# log ###
Empty

## Environment information ##

**VSCode version**: 1.37.1
**C# Extension**: 1.21.0

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.401/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  1.0.4 [/usr/local/share/dotnet/sdk]
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.500 [/usr/local/share/dotnet/sdk]
  2.2.401 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|atlascode|atlassian|1.4.3|
|cform|aws-scripting-guy|0.0.23|
|csharp|ms-vscode|1.21.0|
|csharpextensions|jchannon|1.3.0|
|debugger-for-chrome|msjsdiag|4.11.7|
|EditorConfig|EditorConfig|0.13.0|
|favorites|kdcro101|2.4.5|
|githistory|donjayamanne|0.4.6|
|knockoutjs|furstenberg|0.1.0|
|sass-indented|robinbentley|1.5.1|
|vetur|octref|0.22.2|
|vscode-cfn-lint|kddejong|0.8.1|
|vscode-docker|ms-azuretools|0.7.0|
|vscode-eslint|dbaeumer|1.9.1|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-proto3|zxh404|0.3.0|
|vscode-solution-explorer|fernandoescolar|0.3.4|
|vscode-yaml|redhat|0.5.1|
|vsliveshare|ms-vsliveshare|1.0.721|;

</details>

**Comment by sudsy** [comment]
I noticed an update of the extension to 1.21.1 and also made some changes to my project to clean up my Omnisharp log.

It now shows just:

Starting OmniSharp server at 8/23/2019, 11:26:47 AM
    Target: /Users/bensudbury/Development/gen3/PVL.sln

OmniSharp server started with Mono 6.0.0.
    Path: /Users/bensudbury/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/OmniSharp.exe
    PID: 54067

The VisualBasic.dll issue is gone but the issue with disposable tests remains.

**Comment by akshita31** [comment]
@sudsy In your error log it says

> The reference assemblies for framework ".NETFramework,Version=v4.7.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed.

Do you have the appropriate framework version installed ?

**Comment by sudsy** [comment]
There were some issues with my project configuration for mono. I have
resolved those and re-tested as mentioned in my previous comment and the
problem  still persists.

**Comment by sudsy** [comment]
It seems that this issue occurs for any class that implements IDisposable. I just encountered the same issue on a different file class that implements IEnumerator<string> which is an IDisposable.

If I comment out the Dispose method the problem goes away, but of course I can't implement the interface without the Dispose method.

**Comment by cartermp** [comment]
This may be related to how CodeLens and Find References is being used by OmniSharp - @sudsy are you still seeing this with the latest extension?

**Comment by sudsy** [comment]
@cartermp  It's still present. Each individual edit of either a test method or the Dispose method spins all 4 cpus on my machine for 10 - 20 seconds.

**Comment by cartermp** [comment]
Thanks, good to know

**Comment by JoeRobich** [comment]
@sudsy If you set `csharp.referencesCodeLens.enabled` to false, does the experience improve?

**Comment by sudsy** [comment]
@JoeRobich changing that setting does make the problem go away.

**Comment by JoeRobich** [comment]
@sudsy Ah, I'll open a PR to add `Dispose` to our list of methods that we filter out of reference codelens. This is related to https://github.com/dotnet/roslyn/issues/38223
