### ISSUE TITLE
omnisharp server not found

### ISSUE THREAD

**Issue by zev-deutsch** [OmniSharp/omnisharp-vscode#3251]
Starting OmniSharp server at 2019-08-27, 6:28:37 p.m.
    Target: c:\Users\\*******\\Desktop\classes\HelloWorld

OmniSharp server started.
    Path: c:\Users\\*******\\.vscode\extensions\ms-vscode.csharp-1.21.1\.omnisharp\1.34.2\OmniSharp.exe
    PID: 16120

'"c:\Users\\*******\\.vscode\extensions\ms-vscode.csharp-1.21.1\.omnisharp\1.34.2\OmniSharp.exe"' is not recognized as an internal or external command,
operable program or batch file.
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

**Comment by akshita31** [comment]
@zev-deutsch Has omnisharp ever worked for you before? Also can you check if the "Omnisharp.exe" exists at the specified path ?

**Comment by actionthomas** [comment]
Hello
I have the same problem, and the Omnisharp.exe file is not there. I tried to uninstall and reinstall the extension, only the ".vscode\extensions\ms-vscode.csharp-1.21.3\.omnisharp\1.34.3\" folder is created, but empty.

**Comment by akshita31** [comment]
@actionthomas The problem I think here is that omnisharp is unable to download for you. You can try downloading omnisharp manually from https://download.visualstudio.microsoft.com/download/pr/7ae0ec86-b4ac-40fd-808d-86fad5d8c215/ab492c720755c41254ec31108c63edac/omnisharp-linux-x86-1.34.3.zip and unzip and put in that folder. You will also need to set executable permissions on all the binaries in the folder

**Comment by actionthomas** [comment]
@akshita31 Thanks for the link, but I'm using Windows 🙂 is there a zip file for this platform?

**Comment by Stabledog** [comment]
Same problem here:
```
Starting OmniSharp server at 2/17/2020, 5:11:28 PM
    Target: d:\unity_projects\roll_a_ball\roll_a_ball.sln

OmniSharp server started.
    Path: C:\Users\lesma\.vscode\extensions\ms-vscode.csharp-1.21.11\.omnisharp\1.34.11\OmniSharp.exe
    PID: 13616

'C:\Users\lesma\.vscode\extensions\ms-vscode.csharp-1.21.11\.omnisharp\1.34.11\OmniSharp.exe' is not recognized as an internal or external command,
operable program or batch file.
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute)
```

**Comment by JMorgado99** [comment]
> 
> 
> @akshita31 Thanks for the link, but I'm using Windows 🙂 is there a zip file for this platform?

https://omnisharpdownload.blob.core.windows.net/ext/omnisharp-win-x64-1.34.4.zip 

Download it and copy all the content from the .zip to the path of the issue (c:\Users\*******\.vscode\extensions\ms-vscode.csharp-1.21.1.omnisharp\1.34.2\)

it worked for me...  🙂

**Comment by cartermp** [comment]
Hey folks, has this reproduced for you yet? Specifically, OmniSharp downloads successfully, but cannot be found on your machine.

**Comment by cartermp** [comment]
Closing out as no additional info was added.
