### ISSUE TITLE
Target process crashes while running under the debugger on macOS

### ISSUE THREAD

**Issue by dfdumaresq** [OmniSharp/omnisharp-vscode#3252]
## Issue Description ##

dotnet quits unexpectedly when running under debug.

## Steps to Reproduce ##

- clean and build project
- start debugging 
- open project in browser.

## Expected Behavior ##

- Project should run normally. Web page should load and allow navigating to page that communicates with the client-middleware (C#) code.
- This works as expected when debugging is not started.

## Actual Behavior ##

- A network error is thrown and reported by the browser.
- Apple throws a Problem report for dotnet 

### OmniSharp log ###
<details>Starting OmniSharp server at 8/28/2019, 9:56:01 AM
    Target: /Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-ui/EPBC.PSAS.sln

OmniSharp server started.
    Path: /Users/ddumaresq/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/run
    PID: 60235

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.14.6 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.0 - "/Users/ddumaresq/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/Users/ddumaresq/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.0 - "/Users/ddumaresq/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/.msbuild/Current/Bin"
            MSBuildExtensionsPath = /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/xbuild
            BypassFrameworkInstallChecks = true
            CscToolPath = /Users/ddumaresq/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/.msbuild/Current/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /Users/ddumaresq/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/.msbuild/Current/Bin
            TargetFrameworkRootPath = /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/xbuild-frameworks
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-ui'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-ui/EPBC.PSAS.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-ui/EPBC.PSAS.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-middleware-client/EPBC.BusinessMiddleware.Client/EPBC.BusinessMiddleware.Client.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-ui'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-ui/EPBC.PSAS.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-ui' on host 60046.
[warn]: OmniSharp.MSBuild.ProjectLoader
        "/Users/ddumaresq/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/.msbuild/Current/Bin/NuGet.targets" cannot be imported again. It was already imported at "/Users/ddumaresq/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets (6060,3)". This is most likely a build authoring error. This subsequent import will be ignored. [/Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-middleware-client/EPBC.BusinessMiddleware.Client/EPBC.BusinessMiddleware.Client.csproj]
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-ui/EPBC.PSAS.csproj'.
/Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-ui/EPBC.PSAS.csproj
/Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/xbuild/15.0/Microsoft.Common.targets/ImportAfter/Microsoft.NuGet.ImportAfter.targets(21,3): Error: "/Users/ddumaresq/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/.msbuild/Current/Bin/NuGet.targets" cannot be imported again. It was already imported at "/Users/ddumaresq/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets (6060,3)". This is most likely a build authoring error. This subsequent import will be ignored. [/Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-middleware-client/EPBC.BusinessMiddleware.Client/EPBC.BusinessMiddleware.Client.csproj]

[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-ui/EPBC.PSAS.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-middleware-client/EPBC.BusinessMiddleware.Client/EPBC.BusinessMiddleware.Client.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-middleware-client/EPBC.BusinessMiddleware.Client/EPBC.BusinessMiddleware.Client.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/ddumaresq/EducationPlannerBC/Dockerize/EPAS/sources/develop-branch/epbc-middleware-client/EPBC.BusinessMiddleware.Client/EPBC.BusinessMiddleware.Client.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: EPBC.PSAS
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: EPBC.BusinessMiddleware.Client
</details>

### C# log ###
<details>
No C# output
</details>

## Environment information ##

**VSCode version**: 1.37.1
**C# Extension**: 1.21.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.401/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  1.1.14 [/usr/local/share/dotnet/sdk]
  2.2.401 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-close-tag|formulahendry|0.5.6|
|auto-rename-tag|formulahendry|0.1.0|
|autoimport|steoates|1.5.3|
|beautify|HookyQR|1.5.0|
|Bookmarks|alefragnani|10.5.0|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|chai-snippets|nwhatt|0.1.0|
|change-case|wmaurer|1.0.0|
|code-runner|formulahendry|0.9.14|
|cpptools|ms-vscode|0.25.0|
|csharp|ms-vscode|1.21.1|
|csharpextensions|jchannon|1.3.0|
|csharpfixformat|Leopotam|0.0.84|
|debugger-for-chrome|msjsdiag|4.11.7|
|debugger-for-ios-web|msjsdiag|0.1.2|
|docker-explorer|formulahendry|0.1.6|
|docker-extension-pack|formulahendry|0.0.1|
|dotnet-core-commands|matijarmk|1.0.6|
|EditorConfig|EditorConfig|0.13.0|
|es6-mocha-snippets|spoonscen|0.2.2|
|git-graph|mhutchie|1.13.0|
|git-merger|shaharkazaz|0.4.1|
|git-project-manager|felipecaputo|1.7.1|
|git-tree-compare|letmaik|1.7.0|
|gitblame|waderyan|3.0.1|
|githistory|donjayamanne|0.4.6|
|gitlens|eamodio|9.9.3|
|Go|ms-vscode|0.11.4|
|html-snippets|abusaidm|0.2.1|
|json-tools|eriklynd|1.0.2|
|live-html-previewer|hdg|0.3.0|
|macros|geddski|1.2.1|
|material-icon-theme|PKief|3.8.1|
|Material-theme|zhuangtongfa|2.27.1|
|msbuild-project-tools|tintoy|0.2.55|
|mssql|ms-mssql|1.6.0|
|mustache|dawhite|1.1.1|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|pdf|tomoki1207|0.5.0|
|quick-html-previewer|daiyy|1.0.0|
|remotehub|eamodio|0.5.0|
|restore-editors|eamodio|0.2.1|
|sublime-keybindings|ms-vscode|4.0.3|
|tslint|eg2|1.0.44|
|typelens|kisstkondoros|1.9.1|
|typescript-hero|rbbit|3.0.0|
|vetur|octref|0.22.2|
|vscode-code-outline|patrys|0.2.1|
|vscode-css-peek|pranaygp|3.0.2|
|vscode-docker|ms-azuretools|0.7.0|
|vscode-eslint|dbaeumer|1.9.1|
|vscode-firefox-debug|firefox-devtools|2.0.0|
|vscode-generate-getter-setter|DSKWRK|0.5.0|
|vscode-html-css|ecmel|0.2.3|
|vscode-multi-line-tricks|bigous|0.0.3|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-nupkg|eridem|1.0.1|
|vscode-raml|blzjns|3.0.1|
|vscode-surround|Sword|1.0.1|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.2|
|vscode-versionlens|pflannery|0.24.0|;

</details>

**Comment by gregg-miskelly** [comment]
@dfdumaresq Can you include the output from the crash report? Did this suddenly start happening? Does it happen for all projects for you or just one?

**Comment by dfdumaresq** [comment]
I have 
- removed the ~/.vscode/extension folder 
- re-installed the C# extension
and the problem has not reappeared.

**Comment by gregg-miskelly** [comment]
Okay, thanks. I will close the issue for now, but let us know if it comes back.

**Comment by dfdumaresq** [comment]
will do. thanks!
