### ISSUE TITLE
Intellisense are not working for inner level child

### ISSUE THREAD

**Issue by Saranya13** [OmniSharp/omnisharp-vscode#3256]
## Environment data
`dotnet --info` output: 3.0.0-preview8-28405-07
VS Code version: 1.37.1
C# Extension version: 1.21.1

## Issue

I have created the asp.net core project in visual studio code. I installed our dll in this application. Parent intellisense are working. But this is not working for inner level child. Please find the below image

For Parent Element

![Screenshot (33)](https://user-images.githubusercontent.com/38315832/64176495-2fd07280-ce7b-11e9-8fb8-0e44915b04d4.png)

Inner level child

![Screenshot (34)](https://user-images.githubusercontent.com/38315832/64176631-77ef9500-ce7b-11e9-8361-ce334ddc9fc6.png)

**Comment by rchande** [comment]
cc @NTaylorMullen -- is this Razor or something else?

**Comment by Saranya13** [comment]
Hi @rchande ,

Yes. this is Razor 

Regards,
Saranya M

**Comment by NTaylorMullen** [comment]
@Saranya13 thanks for the report! Would you mind moving your issue over to https://github.com/aspnet/Razor.VSCode? Also, as part of the move would you mind elaborating a little bit more on what type of completion you'd expect and what those TagHelpers look like?

**Comment by NTaylorMullen** [comment]
@Saranya13 thanks for moving the issue over. https://github.com/aspnet/Razor.VSCode/issues/405
