### ISSUE TITLE
Hide process listing commands

### ISSUE THREAD

**Issue by scabana** [OmniSharp/omnisharp-vscode#3262]
## Issue Description ##
```csharp.listProcess``` and ```csharp.listRemoteProcess``` should not show up in the command palette. Triggering any of those two commands directly from the command palette serves no purposes.
## Steps to Reproduce ##
1. Ctrl-Shift+P
1. Write ```List process for attach```
1. Processes shows up
1. Select 1
1. Nothing happens

or

1. Ctrl-Shift+P
1. Write ```List processes on remote connection for attach```
1. Error shows up at the bottom (Name not defined in current configuration)
## Expected Behavior ##
The two commands should not show up in the command palette.
## Actual Behavior ##
They show up, first lists but then nothing happens, seconds display an error message at the bottom.

## Environment information ##

**VSCode version**: 1.37.1
**C# Extension**: 1.21.1

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.4|
|azure-pipelines|ms-azure-devops|1.157.1|
|code-settings-sync|Shan|3.4.2|
|csharp|ms-vscode|1.21.1|
|debugger-for-chrome|msjsdiag|4.11.7|
|dotnet-test-explorer|formulahendry|0.7.1|
|githistory|donjayamanne|0.4.6|
|markdown-all-in-one|yzhang|2.4.2|
|powershell|ms-vscode|2019.5.0|
|remote-wsl|ms-vscode-remote|0.39.2|
|vscode-docker|ms-azuretools|0.7.0|
|vscode-icons|vscode-icons-team|9.3.0|
|vscode-yaml|redhat|0.5.2|
|vscodeintellicode|VisualStudioExptTeam|1.1.9|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by rchande** [comment]
cc @gregg-miskelly
