### ISSUE TITLE
Linux (Debian 10): System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.

### ISSUE THREAD

**Issue by Grovespaz** [OmniSharp/omnisharp-vscode#3265]
## Issue Description ##
When starting Visual Studio Code, the following message appears in the log:
```System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.```

I'm using Debian 10, which I realize is not yet officially supported. If you feel like that might be the cause and don't have the resources to investigate I understand.

## Steps to Reproduce ##
Open a folder with a C# Solution in Visual Studio Code on an updated instance of Debian 10.

## Expected Behavior ##
Omnisharp and thus Intellisense work.

## Actual Behavior ##
Omnisharp server fails to start

### OmniSharp log ###
<details>
Starting OmniSharp server at 9/6/2019, 8:49:43 PM
    Target: /home/lufix/src/emu/8080

OmniSharp server started with Mono 5.18.0.
    Path: /home/lufix/.vscode/extensions/ms-vscode.csharp-1.21.1/.omnisharp/1.34.2/omnisharp/OmniSharp.exe
    PID: 31312

System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
  at OmniSharp.CommandLineApplication+<>c__DisplayClass11_0.<OnExecute>b__0 () [0x0000b] in <150636dc45ea41d3a8efdf330bb7b52f>:0 
  at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute (System.String[] args) [0x00039] in <344a1e8cd6594b17b1e01f8df6ae8827>:0 
  at OmniSharp.CommandLineApplication.Execute (System.Collections.Generic.IEnumerable`1[T] args) [0x00042] in <150636dc45ea41d3a8efdf330bb7b52f>:0 
  at OmniSharp.Stdio.Driver.Program+<>c__DisplayClass0_0.<Main>b__0 () [0x00028] in <ef67332970734dbbb15e5d0e9b13d144>:0 
  at OmniSharp.HostHelpers.Start (System.Func`1[TResult] action) [0x0001c] in <150636dc45ea41d3a8efdf330bb7b52f>:0 
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
</details>

### C# log ###
(blank)

## Environment information ##

**VSCode version**: 1.38.0
**C# Extension**: 1.21.1

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.18.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.401/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.25.1|
|csharp|ms-vscode|1.21.1|
|Go|ms-vscode|0.11.4|
|mssql|ms-mssql|1.6.0|
|vetur|octref|0.22.2|
|vscode-wasm|dtsvet|1.2.1|;

</details>

**Comment by dogguts** [comment]
I have(/**had**) exactly the same issue, with pretty much the same setup (safe for the extensions).
## Fix (option 1)
Change settings to:
 ```json   
  "omnisharp.useGlobalMono": "never"
```
Forces omnisharp to use the mono version packaged with omnisharp.  Worked for me.
## Fix (option 2) 
Install the latest (stable) mono version from [www.mono-project.com](https://www.mono-project.com/download/stable/#download-lin-debian)
and keep 
 ```json   
  "omnisharp.useGlobalMono": "always"
```
or
 ```json
 "omnisharp.useGlobalMono": "auto" 
```
Also verified working (for me).
## Possible(?) cause 
According to [github.com/OmniSharp/omnisharp-roslyn](https://github.com/OmniSharp/omnisharp-roslyn) :

>  If Mono is globally installed on the system, OmniSharp will prefer it over the embedded version, however version >=**5.18.0** is required.

However; [package.json](https://github.com/OmniSharp/omnisharp-vscode/blob/v1.21.3/package.json) states:
> * Automatically launch OmniSharp with "mono" if version **5.8.1** or greater is available on the PATH.",
> * Always launch OmniSharp with "mono". If version **5.8.1** or greater is not available on the PATH, an error will be printed.",
> * Never launch OmniSharp on a globally-installed Mono."

Could be just an documentation inconsistency though.
Or there's something wrong with the debian 10 mono package(s), but I didn't look any further into that.

<details>
  <summary>Debian 10: (default) mono 5.18.0.240</summary>

> Mono JIT compiler version **5.18.0.240** (Debian 5.18.0.240+dfsg-3 Wed Apr 17 16:37:36 UTC 2019)
> Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
> 	TLS:           __thread
> 	SIGSEGV:       altstack
> 	Notifications: epoll
> 	Architecture:  amd64
> 	Disabled:      none
> 	Misc:          softdebug 
> 	Interpreter:   yes
> 	LLVM:          supported, not enabled.
> 	Suspend:       preemptive
> 	GC:            sgen (concurrent by default)

</details>
<details>
<summary>C# extension 1.21.3 / omnisharp 1.34.4-beta.6: mono 5.18.1.0</summary>

> Mono JIT compiler version **5.18.1.0** (tarball Fri Mar 15 20:45:47 UTC 2019)
> Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
> 	TLS:           __thread
> 	SIGSEGV:       altstack
> 	Notifications: epoll
> 	Architecture:  amd64
> 	Disabled:      none
> 	Misc:          softdebug 
> 	Interpreter:   yes
> 	LLVM:          yes(600)
> 	Suspend:       preemptive
> 	GC:            sgen (concurrent by default)
> 

</details>

<details>
<summary>mono-project.com: mono 6.0.0.334</summary>

> Mono JIT compiler version **6.0.0.334** (tarball Thu Sep 12 21:35:31 UTC 2019)
> Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
> 	TLS:           __thread
> 	SIGSEGV:       altstack
> 	Notifications: epoll
> 	Architecture:  amd64
> 	Disabled:      none
> 	Misc:          softdebug 
> 	Interpreter:   yes
> 	LLVM:          yes(600)
> 	Suspend:       hybrid
> 	GC:            sgen (concurrent by default)

</details>

**Comment by kmvbatista** [comment]
Thank you so much. I finally got this!

**Comment by filipw** [comment]
@dogguts installing the latest stable Mono is always the best idea as OmniSharp will automatically try to use it.
since latest extension release (1.21.4) with OmniSharp 1.34.4 the minimum Mono version is actually 6.4.0 already - because this is the only version that supports .NET Core 3.0.

**Comment by VincentRichard555** [comment]
Thanks a lot this worked. If you can't find settings.json here is a link showing you the file locations:

https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations

**Comment by filipw** [comment]
This has been resolved and the lowest supported Mono version is 6.4.0. The relevant docs have been updated too.
