### ISSUE TITLE
Failed to load project that references LanguageExt.CodeGen from solution folder in WSL

### ISSUE THREAD

**Issue by wawaforya** [OmniSharp/omnisharp-vscode#3266]
## Environment data:
WSL distro: [Arch](https://github.com/yuk7/ArchWSL)
VS Code version: 1.38.0
C# Extension version: 1.21.1

`dotnet --info` output in Windows:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.401\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

`dotnet --info` output in WSL:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/wawa/.dotnet/sdk/2.2.401/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.1.701 [/home/wawa/.dotnet/sdk]
  2.2.301 [/home/wawa/.dotnet/sdk]
  2.2.401 [/home/wawa/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [/home/wawa/.dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [/home/wawa/.dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [/home/wawa/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [/home/wawa/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [/home/wawa/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [/home/wawa/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

## Steps to reproduce
1. `git clone https://github.com/wawaforya/loading-failure.git` in WSL
2. Open folder `loading-failure` in VS Code in WSL
3. VS Code shows that `Some projects have trouble loading...` with output in this [pastiebin](https://www.pastiebin.com/5d73809a2cc75).

## Expected  behavior
VS Code should load the project successfully as in Windows (Yes, the project successfully loaded in Windows.)

## Actual behavior
Failed to load the project which references to dotnet-codegen.

## What I've found
It seems that the issue is related to the command `dotnet codegen --version`.
This command returns the same result in both Windows and WSL:
* In the folder `loading-failure` it shows `No executable found matching command "dotnet-codegen"`
* In the folder `loading-failure/APIService` it shows `0.6.1+2b937a442a`

**Comment by cartermp** [comment]
Closing this as external; there's some odd ways that targets are getting loaded here that might need to get worked out here: https://github.com/AArnott/CodeGeneration.Roslyn

It could also be that an explicit call to `dotnet restore` is required.

Separately, the DotNetCliToolReference is considered out of date now, and local tools are the preferred way to use .NET tools that are local to a project. This also requires a `dotnet tool restore` command to allow use of them.
