### ISSUE TITLE
Every keypress uses hard disk [linux?]

### ISSUE THREAD

**Issue by cyraid** [OmniSharp/omnisharp-vscode#3269]
## Environment data
`dotnet --info` output:

> .NET Core SDK (reflecting any global.json):
>  Version:   2.2.401
>  Commit:    729b316c13
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  19.04
>  OS Platform: Linux
>  RID:         ubuntu.19.04-x64
>  Base Path:   /usr/share/dotnet/sdk/2.2.401/
> 
> Host (useful for support):
>   Version: 2.2.6
>   Commit:  7dac9b1b51
> 
> .NET Core SDKs installed:
>   2.2.401 [/usr/share/dotnet/sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download
> 

VS Code version: 1.38.0
C# Extension version: 1.21.1

## Steps to reproduce
1. Install extension
2. Create C# project
3. Make sure omnisharp is running
4. Start typing
5. Witness your IDE light go wild on every keypress.
6. Open system monitor and check out mono using much disk write.

## Expected  behavior
Use RAM. Every keypress without even saving the file, should not be using HD at all. There are other options if you absolutely need to use files or every keypress.

## Actual behavior
Mono ends up writing things to disk.

**Comment by rchande** [comment]
@cyraid That's odd...OmniSharp doesn't write to disk on every keystroke.

**Comment by cyraid** [comment]
Really? Hmm.. Then that is quite odd.. Though that was the local mono omnisharp provided. I'm back on Windows for a bit for a project, but when I installed dotnet sdk from microsoft's repository, and mono-devel from the repository and chose 'global' for mono path, I don't *think* I saw the same disk usage.. I'll see if I can verify when I can. Did someone else wanna try that specific scenario and verify?

**Comment by rchande** [comment]
@cyraid Seems like this is resolved? I'm going to close this issue but feel free to file a new one if you see this happen again.

**Comment by yokljo** [comment]
Hi @rchande, I have noticed this problem for a long time and finally thought to Google it. Lo and behold, here's a ticket for it.
It at the very least occurs on Linux/VSCode 1.53.2 with Omnisharp 1.23.0 and 1.23.11. Here's a video showing mono writing to the disk:
https://www.youtube.com/watch?v=OcXs9BCKAfk
My HDD also spins a little each time I type an "f" which makes a fun noise.
Let me know if I can help with diagnosing the problem :)
