### ISSUE TITLE
Exception handler when running `dotnet --info` should _use_, not discard, the exception being caught (log or show in user msg)

### ISSUE THREAD

**Issue by metaleap** [OmniSharp/omnisharp-vscode#3270]
Here's the offending `catch` handler: https://github.com/OmniSharp/omnisharp-vscode/blob/a3f12cfadf9d23edd4913239b210019e5e5415a6/src/coreclr-debug/util.ts#L101

The `error` being passed isn't utilized. At my end (Linux) `dotnet` is in the `PATH` env-var and generally accessible from any terminal/shell/process, and the env-vars `DOTNET_ROOT` and `MSBuildSDKsPath` are also both set correctly and available system-wide. If you still cannot run `dotnet --info` when even my own ad-hoc one-off prototypical nodejs `child_process`-using throwaway code _can_ --- then we should be able to inspect whatever details `error` might hide?!

**Comment by gregg-miskelly** [comment]
Have you tried debugging this code?

We have seen this issue pop up many times before, and thus far `error` has never been helpful. VS Code attempts to figure out what its environment should be, and that has almost always been the problem. We have also seen once or twice where dotnet could be found, but didn't start. I don't think that `error` will have anything interesting in either case.

**Comment by metaleap** [comment]
Fair game then.
