### ISSUE TITLE
Great C# editing  IntelliSense,need the file omnisharp.json

### ISSUE THREAD

**Issue by kinglionsz** [OmniSharp/omnisharp-vscode#3273]
It's really distressing for C# in WSL. After each upgrade (perhaps WSL maybe VS CODE INSIDERS, etc.) sometimes the IntelliSense of C#  is not responding. There's always no reason to find it, because sometimes it's okay. 
There is a solution now to the problem. That is to add a file omnisharp.json to the project .
The file contains the following:

```
{
    "MsBuild": {
        "UseLegacySdkResolver": true
    }
}
```

If I have installed Git Bash and use it , the IntelliSense of C# has no any problem and not need  the file omnisharp.json. @rchande

**Comment by rchande** [comment]
@kinglionsz Can you provide more information?

**Comment by kinglionsz** [comment]
> @kinglionsz Can you provide more information?

Hello, @rchande :

Great C# editing IntelliSense deed the file,
omnisharp.json:

`{
    "MsBuild": {
        "UseLegacySdkResolver": true
    }
}`

Please explain why? Thank you for your time.☕

**Comment by kinglionsz** [comment]
https://github.com/OmniSharp/omnisharp-vscode/issues/3229#issuecomment-538610385


Hello @rchande , I'm very glad to tell you that the C# Intellisense works good👌now on the following version.Thank you very much for your time👍☕
the IntelliSense of C# has no any problem and not need the file omnisharp.json.

Yes.There's always a version that's okay.

Version: 1.39.0-insider (system setup)
Commit: a655c0836de8b8e06f4d56fa4e581b0ced53f56f
Date: 2019-10-03T05:36:55.111Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18995

Remote | WSL: Ubuntu-18.04
-- | --
OS | Linux x64 4.4.0-18995-Microsoft

.vscode-server-insiders/extensions/ms-vscode.csharp-1.21.4/.omnisharp/1.34.4/omnisharp/.msbuild/Current/Bin
.vscode-server-insiders/extensions/ms-vscode.csharp-1.21.4/.omnisharp/1.34.4/omnisharp/.msbuild/Current/Bin/Roslyn
.vscode-server-insiders/extensions/ms-vscode.csharp-1.21.4/.omnisharp/1.34.4/omnisharp/.msbuild/Current/Bin

:/mnt/e/CodeSources/cpptest/crayon$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /home/kinglion/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/home/kinglion/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/home/kinglion/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/home/kinglion/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

=================================================================

OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Professional 2019 16.4.29319.158 - "e:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin"
            2: StandAlone 16.0 - "...\.vscode-insiders\extensions\ms-vscode.csharp-1.21.4\.omnisharp\1.34.4\.msbuild\Current\Bin"

MINGW64 /e/CodeSources/cpptest/crayon (master)
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18995
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by kinglionsz** [comment]
C# editing IntelliSense is OK now.
Thanks.
Closed 🔐 .
