### ISSUE TITLE
Getting Error: Unable to create directory "/Debug/". Access to the path '/Debug/' is denied. on Linux

### ISSUE THREAD

**Issue by vladipus** [OmniSharp/omnisharp-vscode#3276]
## Issue Description ##

Failing to open a Unity C# project on Linux.

## Steps to Reproduce ## 

Open a Unity C# project on Linux.

## Expected Behavior ##

To open a Unity C# project on Linux.

## Actual Behavior ##

Failes to open a Unity C# project on Linux.

### OmniSharp log ###

Error: Unable to create directory "/Debug/". Access to the path '/Debug/' is denied.

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.38.1
**C# Extension**: 1.21.2

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.0.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.402
 Commit:    c7f2f96116

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  19.2
 OS Platform: Linux
 RID:         linuxmint.19.2-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.402/

Host (useful for support):
  Version: 2.2.7
  Commit:  b1e29ae826

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|3.4.2|
|csharp|ms-vscode|1.21.2|
|csharpextensions|jchannon|1.3.0|
|docomment|k--kato|0.1.8|
|doxdocgen|cschlosser|0.5.0|
|Doxygen|bbenoist|1.0.0|
|electron-debug|kodetech|18.11.1|
|gc-excelviewer|GrapeCity|2.1.32|
|git-easy|bibhasdn|1.11.0|
|git-merger|shaharkazaz|0.4.1|
|git-project-manager|felipecaputo|1.7.1|
|gitblame|waderyan|3.0.1|
|gitconfig|sidneys1|2.0.1|
|gitflow|vector-of-bool|1.2.1|
|githd|huizhou|2.1.0|
|githistory|donjayamanne|0.4.6|
|gitlens|eamodio|9.9.3|
|haxe-hl|HaxeFoundation|0.7.1|
|html-css-class-completion|Zignd|1.19.0|
|java|redhat|0.48.0|
|JavaScriptSnippets|xabikos|1.7.2|
|jinja|wholroyd|0.0.8|
|MagicPython|magicstack|1.1.0|
|mono-debug|ms-vscode|0.15.8|
|node-module-intellisense|leizongmin|1.5.0|
|nodejs-extension-pack|waderyan|0.1.9|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|prettier-vscode-standard|bysabi|0.22.1|
|psi-header|psioniq|1.8.0|
|search-node-modules|jasonnutter|1.3.0|
|vscode-eslint|dbaeumer|1.9.1|
|vscode-npm-script|eg2|0.3.9|;

</details>

**Comment by vladipus** [comment]
Issuing `sudo apt install msbuild` has fixed this issue for me, which is strange. I can't remember that I did this command before.

**Comment by rchande** [comment]
@vladipus Glad you got it figured out!
