### ISSUE TITLE
Feature Request: Go to Implementation in Context Menu

### ISSUE THREAD

**Issue by johnrom** [OmniSharp/omnisharp-vscode#3282]
Is there a way to add Go to Implementation to the Right-Click context menu?

Related: #37

**Comment by loligans** [comment]
Yes please, I was just wondering about this!

**Comment by cartermp** [comment]
This is implemented in the context menu now.

![image](https://user-images.githubusercontent.com/6309070/80547951-585b2e80-896e-11ea-8382-cdbc45acfcc8.png)

(this will navigate to the implementer of `I`)
