### ISSUE TITLE
Feature Request: NewLinesForBracesInMethodsWithMultilineParameters

### ISSUE THREAD

**Issue by johnrom** [OmniSharp/omnisharp-vscode#3283]
The default formatting for C# in VS Code is pretty good with this extension, but with the prevalence of .net core and dependency injection I do have one complaint. I like my constructors formatted like this:

```
public MyClass()
{
}
public MyClass(
    MyClass2 myClass2,
    MyClass3 myClass3
) {
    _myClass2 = myClass2;
    _myClass3 = myClass3;
}
```

However, the best I can do (that I know of) with the options given is:

```
public MyClass(
    MyClass2 myClass2,
    MyClass3 myClass3
) 
{ // gross
    _myClass2 = myClass2;
    _myClass3 = myClass3;
}
```

Is it possible to add a special option for that case? I'd still like a child constructor to appear like this:

```
public MyClass(
    MyClass2 myClass2,
    MyClass3 myClass3
) : base(myClass2, myClass3)
{
    _myClass2 = myClass2;
    _myClass3 = myClass3;
}
```

**Comment by filipw** [comment]
OmniSharp offers up formatting options from Roslyn - therefore you should open this issue in the Roslyn repo https://github.com/dotnet/roslyn.
Once it's implemented there, it will be available (almost) automatically in OmniSharp.

Thanks.

**Comment by filipw** [comment]
this is where formatting options for C# are stored in Roslyn, by the way https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Formatting/CSharpFormattingOptions.cs

**Comment by johnrom** [comment]
Thanks, opened!
