### ISSUE TITLE
Setting up a ".NET Core Docker Attach" debugger when there's a space in the workspaceRoot/workspaceFolder variable is impossible

### ISSUE THREAD

**Issue by JulioPablo** [OmniSharp/omnisharp-vscode#3285]
I've got a ASP.NET Core project which I need to debug, so I've added the following configuration to the `launch.json`

```
{
    "name": ".NET Core Docker Attach",
    "type": "coreclr",
    "request": "attach",
    "processId": "${command:pickRemoteProcess}",
    "pipeTransport": {
        "pipeProgram": "docker",
        "pipeArgs": [
            "exec",
            "-i",
            "container_name"
        ],
        "debuggerPath": "/vsdbg/vsdbg/",
        "pipeCwd": "${workspaceFolder}",
        "quoteArgs": false
    },
    "sourceFileMap": {
        "/app": "${workspaceFolder}/src"
    },
}
```

Trying to run the debugger with this configuration yields the following results:

```
Executing: docker exec -i container_name sh -s < C:\Users\Julio Pablo\.vscode\extensions\ms-vscode.csharp-1.21.3\scripts\remoteProcessPickerScript
stderr: The system cannot find the file specified.
Error Message: Command failed: docker exec -i container_name sh -s < C:\Users\Julio Pablo\.vscode\extensions\ms-vscode.csharp-1.21.3\scripts\remoteProcessPickerScript
The system cannot find the file specified.
```

So I tested running the same command on the windows CMD and wrapping the filepath around quotes

`docker exec -i container_name sh -s < "C:\Users\Julio Pablo\.vscode\extensions\ms-vscode.csharp-1.21.3\scripts\remoteProcessPickerScript"`

This seemed to work, as it returned the `remoteProcessPickerScript` output, the running processes in the container, so I tried to add quotes around `${workspaceFolder}`

```
{
    "name": ".NET Core Docker Attach",
    "type": "coreclr",
    "request": "attach",
    "processId": "\"${command:pickRemoteProcess}\"",
    "pipeTransport": {
        "pipeProgram": "docker",
        "pipeArgs": [
            "exec",
            "-i",
            "container_name"
        ],
        "debuggerPath": "/vsdbg/vsdbg/",
        "pipeCwd": "\"${workspaceFolder}\"",
        "quoteArgs": false
    },
    "sourceFileMap": {
        "/app": "${workspaceFolder}/src"
    },
}
```
This only changed the error message being displayed
```
Executing: docker exec -i container_name sh -s < C:\Users\Julio Pablo\.vscode\extensions\ms-vscode.csharp-1.21.3\scripts\remoteProcessPickerScript
Error Message: spawn C:\Windows\system32\cmd.exe ENOENT
```

After searching around, the `spawn C:\Windows\system32\cmd.exe ENOENT` appears to be mostly caused by either having `;` at the end of the ComSpec env variable or not having the path to `cmd.exe` in the PATH variable. I do not have the `;` in the ComSpec var and I do have the path in the PATH variable, so I'm not sure what could be causing this error.

**Comment by AnthonyZavala** [comment]
https://github.com/OmniSharp/omnisharp-vscode/blob/a5c34f12eb00467ef404ad92e78da8c65833e828/src/features/processPicker.ts#L241

Putting quotes around `${scriptPath}` will fix it.

```return execChildProcessAndOutputErrorToChannel(`${pipeCmd} < "${scriptPath}"`, pipeCwd, RemoteAttachPicker._channel, platformInfo).then(output => {```
