### ISSUE TITLE
On non-Windows, the debug command line expects a `sh` compliant shell

### ISSUE THREAD

**Issue by SteveL-MSFT** [OmniSharp/omnisharp-vscode#3291]
## Steps to Reproduce ##

Steps to Reproduce:

- Install PowerShell 7 Preview 4
- chsh your default shell to pwsh-preview
- try to debug c# exe launched in VSCode

VSCode uses a command line like:

```
cd '/Users/steve/.vscode/extensions/ms-vscode.csharp-1.21.3/.debugger/';  '/Users/steve/.vscode/extensions/ms-vscode.csharp-1.21.3/.debugger/vsdbg' '--interpreter=vscode' '--connection=/var/folders/1h/96n_hpk92332gjn6pcz0mvxr0000gn/T/CoreFxPipe_vsdbg-ui-452b151b0eb847fba759ea7337b5af33'
```

The problem is when using PowerShell as the default shell, the vsdbg command being in single quotes is treated as a string so that command fails. Since cd is already used to go to that location, there's no need to have the full path to vsdbg, if this command line was changed to:

```
cd '/Users/steve/.vscode/extensions/ms-vscode.csharp-1.21.3/.debugger/'; ./vsdbg '--interpreter=vscode' '--connection=/var/folders/1h/96n_hpk92332gjn6pcz0mvxr0000gn/T/CoreFxPipe_vsdbg-ui-452b151b0eb847fba759ea7337b5af33'
```

Then it would continue to work with sh, bash, etc... and would also work with PowerShell since it's already changing to working directory to the location of the debugger.

## Environment information ##

**VSCode version**: 1.38.1
**C# Extension**: 1.21.3

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview1-014004
 Commit:    26adf27477

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /Users/steve/.dotnet/sdk/3.1.100-preview1-014004/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100-preview9-014004 [/Users/steve/.dotnet/sdk]
  3.0.100-rc1-014190 [/Users/steve/.dotnet/sdk]
  3.0.100 [/Users/steve/.dotnet/sdk]
  3.1.100-preview1-014004 [/Users/steve/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19172-03 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-rc1.19422.2 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-rc1.19457.4 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27525-12 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-rc1-19420-08 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-rc1-19456-20 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.4|
|azure-pipelines|ms-azure-devops|1.157.3|
|cmake|twxs|0.0.17|
|code-gnu-global|austin|0.2.2|
|code-spell-checker|streetsidesoftware|1.7.18|
|cpptools|ms-vscode|0.25.1|
|csharp|ms-vscode|1.21.3|
|docs-article-templates|docsmsft|0.2.7|
|docs-authoring-pack|docsmsft|0.1.2|
|docs-markdown|docsmsft|0.2.19|
|docs-preview|docsmsft|0.3.30|
|docs-yaml|docsmsft|0.2.4|
|githistory|donjayamanne|0.4.6|
|gitlens|eamodio|10.0.0|
|markdown-preview-github-styles|bierner|0.1.6|
|markdown-table-prettify|darkriszty|2.4.0|
|powershell|ms-vscode|2019.5.0|
|reflow-markdown|marvhen|2.0.0|
|rust|rust-lang|0.6.3|
|synthwave-vscode|RobbOwen|0.0.7|
|team|ms-vsts|1.149.2|
|vscode-azurefunctions|ms-azuretools|0.18.1|
|vscode-docker|ms-azuretools|0.8.1|
|vscode-icons|vscode-icons-team|9.3.0|
|vscode-markdownlint|DavidAnson|0.30.2|
|vscode-sidebar|Acrolinx|1.1.2|
|vscode-svg-previewer|vitaliymaz|0.5.1|
|vscode-yaml|redhat|0.5.3|;

</details>

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview1-014004
 Commit:    26adf27477

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /Users/steve/.dotnet/sdk/3.1.100-preview1-014004/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100-preview9-014004 [/Users/steve/.dotnet/sdk]
  3.0.100-rc1-014190 [/Users/steve/.dotnet/sdk]
  3.0.100 [/Users/steve/.dotnet/sdk]
  3.1.100-preview1-014004 [/Users/steve/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19172-03 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-rc1.19422.2 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-rc1.19457.4 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/Users/steve/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27525-12 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-rc1-19420-08 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-rc1-19456-20 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/Users/steve/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS Code version:
```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```
C# Extension version: 1.21.3

**Comment by gregg-miskelly** [comment]
@SteveL-MSFT what does your launch.json look like?

**Comment by SteveL-MSFT** [comment]
```json
        {
            "name": ".NET Core Launch",
            "type": "coreclr",
            "request": "launch",
            "justMyCode": false,
            "stopAtEntry": true,
            "program": "${workspaceRoot}/debug/pwsh",
            "preLaunchTask": "Build",
            "externalConsole": true,
            "cwd": "${workspaceRoot}"
        }
```

**Comment by gregg-miskelly** [comment]
Thanks. You actually had this in the right place originally -- you are asking for a VS Code feature -- the C# debug adapter makes a request back to VS Code to start a terminal ('RunInTerminalRequest'), and that code would need to be aware that it is launching PowerShell and do something different.
