### ISSUE TITLE
Razor file formatting (.cshtml)

### ISSUE THREAD

**Issue by MeTaLiKiD** [OmniSharp/omnisharp-vscode#3293]
## Issue Description ##

I can't auto format a .cshtml file

## Steps to Reproduce ##

Open a .cshtml file
`Ctrl + Alt + F` shortcut to format the file

## Expected Behavior ##

Formatting the file with Razor syntax and HTML

## Actual Behavior ##

> There is no formatter for 'aspnetcorerazor'-files installed.

## Attemps to make it working #

In VSCode settings:
`
  "emmet.includeLanguages": {
    "aspnetcorerazor": "html",
    "razor": "html"
  },
`

And also:
`"razor.devmode": true,`

## Environment information ##

**VSCode version**: 1.38.1
**C# Extension**: 1.21.3

.NET Core SDK:
 Version:   2.2.402
 Commit:    c7f2f96116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.3|

**Comment by juandelacruz23** [comment]
Is it possible to format C#? For me it seems to only fix the identation...

**Comment by NTaylorMullen** [comment]
Sadly we haven't done any work yet to enable Razor formatting. We are however tracking that work over at https://github.com/aspnet/AspNetCore/issues/14271.

For now closing this as a duplicate 😄

**Comment by woeterman94** [comment]
For those of you stumbling here from Google. To format CSHTML in Visual Studio use
`Ctrl+k, Ctrl+D`
