### ISSUE TITLE
Method return type syntax highlighting issues

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#33]
_From @TheColorRed on February 6, 2016 3:18_

Theme: Colorful Default Themes (Dark)

There is still a small issue when syntax highlighting generators, as you can see from this screenshot:

![screenshot from 2016-02-05 21-15-55](https://cloud.githubusercontent.com/assets/1571806/12864356/b47a6542-cc4d-11e5-812b-117e9e6b036b.png)

When using a generator, everything becomes white. Also the class definition in the foreach is also white.

_Copied from original issue: Microsoft/vscode#2756_

**Comment by aeschli** [comment]
@TheColorRed Thanks for reporting this. Can you paste the code snippet as well, to speed up the instigations?

**Comment by aeschli** [comment]
_From @TheColorRed on February 9, 2016 16:48_

Here is the code:

```c#
public GameObject[] GetItems(string name){
    List<GameObject> items = new List<GameObject>();
    foreach(InventoryItem i in inventoryItems){
        if(i.itemName == name){
            items.Add(i.gameObject);
        }
    }
    return items.ToArray();
}

public GameObject[] GetItems<T>(){
    List<GameObject> items = new List<GameObject>();
    foreach(var i in inventoryItems){
        if(i.GetType() == typeof(T)){
            items.Add(i.gameObject);
        }
    }
    return items.ToArray();
}
```

**Note:** the type hinting in the foreach also isn't highlighted.

**Comment by ivanz** [comment]
![image](https://cloud.githubusercontent.com/assets/79742/17788917/be45ea0a-6587-11e6-85b1-923d526b37c7.png)

**Comment by ivanz** [comment]
@DustinCampbell Can you please label this with "Syntax highlighting", so that when I come back to looking at this I can potentially look at fixing it. Or maybe @seraku24 will beat me to it ;)

**Comment by ivanz** [comment]
Also change the title to "Method return type syntax highlighting issues" or something 👍
