### ISSUE TITLE
Configure Omnisharp to Always Put Usings Inside of Namespace

### ISSUE THREAD

**Issue by CodeSteele** [OmniSharp/omnisharp-vscode#3300]
## Issue Description ##
Using statements are put outside of the namespace by default, and there is no way to configure this in the workspace to change it on a per-project basis.

## Steps to Reproduce ##

- Create a new C# class
- Add code that requires an external namespace
- Autocomplete "add missing usings"

## Expected Behavior ##

- Usings should be able to be configured inside of the namesapce

## Actual Behavior ##

- Usings are outside of namespace by default
- Omnisharp will totally obey wherever they're put manually though, so Omnisharp is good about determining what method we're using, just not on new files
- Would be nice to configure a default

## Environment information ##

**VSCode version**: 1.38.1
**C# Extension**: 1.21.3

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.301
 Commit:    70d6be0814

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18985
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.301\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.107 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.3|
|dotnet-test-explorer|formulahendry|0.7.1|
|remote-wsl|ms-vscode-remote|0.39.5|
|vetur|octref|0.22.3|
|vscode-docker|ms-azuretools|0.8.1|;

</details>

**Comment by rchande** [comment]
@CodeSteele We rely on [Roslyn](https://github.com/dotnet/roslyn ) for this functionality and I don't believe they have implemented this. Feel free to file a feature request against Roslyn. Thanks!
