### ISSUE TITLE
ASP.NET Core auto import does not work

### ISSUE THREAD

**Issue by olfek** [OmniSharp/omnisharp-vscode#3304]
With this code

```
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContactManager.Pages
{
    [AllowAnonymous]
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}
```

I typed `[AllowAnonymous]` but it did not auto import `Microsoft.AspNetCore.Authorization`.

Is this intentional or should this work?

**Comment by larryw3i** [comment]
use "Ctrl+." to  trigger "import",  it doesn't work if your input method not in English(en)

**Comment by Gameghostify** [comment]
Auto imports would be a great thing to have. Cycling through auto suggestions feels great (waiting and pressing `ctrl + .` in this case is not)

**Comment by Gameghostify** [comment]
Any movement on this? What has to be done to make this work?

**Comment by cartermp** [comment]
Closing as a duplicate of #3730
