### ISSUE TITLE
Release 1.21.4 has wrong binary name

### ISSUE THREAD

**Issue by tverboon** [OmniSharp/omnisharp-vscode#3307]
@rchande 
Release binary has the old name:

![image](https://user-images.githubusercontent.com/6871049/65936526-340d9280-e41d-11e9-9d64-b994545ae5d9.png)

It's the right directory.
https://github.com/OmniSharp/omnisharp-vscode/releases/download/v1.21.4/csharp-1.21.3.vsix

@filipw: I can confirm that this version is working on my Mac. I uninstalled Mono before installing this new extension.

**Comment by filipw** [comment]
cc @rchande 
also - #3308

**Comment by jtsom** [comment]
So is this, or is this not going to be released to the VSCode marketplace? (with a correct name)

**Comment by rchande** [comment]
@tverboon Thanks, fixed the name.

**Comment by jtsom** [comment]
So, again, is this going to be actually released? Not available on the marketplace, no vsix available...

**Comment by filipw** [comment]
it was released yesterday, yes
