### ISSUE TITLE
1.21.4 breaks OmniSharp on Arch

### ISSUE THREAD

**Issue by thatcosmonaut** [OmniSharp/omnisharp-vscode#3316]
## Issue Description ##
When the extension updated to 1.21.4, OmniSharp became unable to find my installed SDKs. Rolling back to 1.21.3 resolved the issue. dotnet-core-preview is installed from AUR. I do not have mono installed and I am not using the legacy resolver workaround.

## Steps to Reproduce ##
Update to 1.21.4. 

## Expected Behavior ##
OmniSharp loads correctly.

## Actual Behavior ##
OmniSharp log shows several "Could not find installed SDK" errors.

### OmniSharp log ###
Starting OmniSharp server at 10/3/2019, 5:36:56 PM
    Target: /home/cosmonaut/programming/games/SamuraiGunn2/SamuraiGunn2.sln

OmniSharp server started.
    Path: /home/cosmonaut/.vscode/extensions/ms-vscode.csharp-1.21.4/.omnisharp/1.34.4/run
    PID: 22218

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on manjaro 0.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.0 - "/home/cosmonaut/.vscode/extensions/ms-vscode.csharp-1.21.4/.omnisharp/1.34.4/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/cosmonaut/.vscode/extensions/ms-vscode.csharp-1.21.4/.omnisharp/1.34.4/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.0 - "/home/cosmonaut/.vscode/extensions/ms-vscode.csharp-1.21.4/.omnisharp/1.34.4/omnisharp/.msbuild/Current/Bin"
            MSBuildExtensionsPath = /home/cosmonaut/.vscode/extensions/ms-vscode.csharp-1.21.4/.omnisharp/1.34.4/omnisharp/.msbuild
            BypassFrameworkInstallChecks = true
            CscToolPath = /home/cosmonaut/.vscode/extensions/ms-vscode.csharp-1.21.4/.omnisharp/1.34.4/omnisharp/.msbuild/Current/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/cosmonaut/.vscode/extensions/ms-vscode.csharp-1.21.4/.omnisharp/1.34.4/omnisharp/.msbuild/Current/Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/cosmonaut/programming/games/SamuraiGunn2'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/cosmonaut/programming/games/SamuraiGunn2/SamuraiGunn2.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/cosmonaut/programming/games/SamuraiGunn2/SamuraiGunn2/SamuraiGunn2.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/cosmonaut/programming/games/SamuraiGunn2/Tests/SamuraiGunn2Tests.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/cosmonaut/programming/games/SamuraiGunn2'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/cosmonaut/programming/games/SamuraiGunn2/SamuraiGunn2/SamuraiGunn2.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/cosmonaut/programming/games/SamuraiGunn2' on host 22067.
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/cosmonaut/programming/games/SamuraiGunn2/SamuraiGunn2/SamuraiGunn2.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/cosmonaut/programming/games/SamuraiGunn2/SamuraiGunn2/SamuraiGunn2.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/cosmonaut/programming/games/SamuraiGunn2/Tests/SamuraiGunn2Tests.csproj
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/cosmonaut/programming/games/SamuraiGunn2/Tests/SamuraiGunn2Tests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/cosmonaut/programming/games/SamuraiGunn2/Tests/SamuraiGunn2Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: SamuraiGunn2
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: SamuraiGunn2Tests
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        SamuraiGunn2: Did not find 'Microsoft.NETCore.App.Runtime.win-x64' in lock file.
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        SamuraiGunn2: Did not find 'Microsoft.NETCore.App.Runtime.osx-x64' in lock file.
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        SamuraiGunn2: Did not find 'Microsoft.NETCore.App.Runtime.linux-x64' in lock file.
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        SamuraiGunn2: Did not find 'Microsoft.AspNetCore.App.Runtime.win-x64' in lock file.
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        SamuraiGunn2: Did not find 'Microsoft.AspNetCore.App.Runtime.osx-x64' in lock file.
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        SamuraiGunn2: Did not find 'Microsoft.AspNetCore.App.Runtime.linux-x64' in lock file.
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        SamuraiGunn2: Did not find 'Microsoft.NETCore.App.Host.win-x64' in lock file.
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        SamuraiGunn2: Did not find 'Microsoft.NETCore.App.Host.osx-x64' in lock file.

## Environment information ##

**VSCode version**: 1.38.1
**C# Extension**: 1.21.3

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-rc1-014190
 Commit:    c4d43f672d

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /opt/dotnet/sdk/3.0.100-rc1-014190/

Host (useful for support):
  Version: 3.0.0-rc1-19456-20
  Commit:  8f5d7b1ba4

.NET Core SDKs installed:
  3.0.100-rc1-014190 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-rc1.19457.4 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-rc1-19456-20 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.3|
|dotnet-test-explorer|formulahendry|0.7.1|
|EditorConfig|EditorConfig|0.13.0|
|prettier-now|remimarsal|1.4.9|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-theme-tragedy-and-geometry|MoonsideGames|1.2.0|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.2|;

</details>

**Comment by thatcosmonaut** [comment]
Ignore the "C# Extension: 1.21.3" above, I pasted it in after I rolled back

**Comment by filipw** [comment]
thanks this was already reported in https://github.com/OmniSharp/omnisharp-roslyn/issues/1610

This is a bit unfortunate but the only change from 1.21.3 -> 1.21.4 is the move from MSBuild 16.0 to 16.3, which is required for .NET Core 3.0 RTM. 
It looks like the dotnet SDK tooling (msbuild and the resolver in this case) regressed in Arch Linux support.

Probably the only workaround for you now would be to install Mono 6.4.0 (a package for which may not even exist in Arch landscape at the moment?).
I think the real issue regarding MSBuild 16.3 and .NET core resolver support for Arch should be asked on https://github.com/dotnet/toolset or perhaps https://github.com/dotnet/core-sdk 

cc @livarcocc @nguerrera

**Comment by thatcosmonaut** [comment]
Can confirm that we only have Mono 6.0 in Arch world right now.

**Comment by thatcosmonaut** [comment]
It looks like there are updated MSBuild-related packages in AUR, so I will try those later and report back.

**Comment by Lgmrszd** [comment]
I've encountered same issue on my system. Installed packages mono-nightly and msbuild-16-bin from AUR. As far as I know, mono-nightly is the only aur package which ships Mono with version > 6.4.0 (It is latest 6.7.0 builds). After installing both packages everything works correct!

**Comment by thatcosmonaut** [comment]
Confirmed fixed after installing `msbuild-16-bin` from AUR and `mono` 6.0 from extras.

**Comment by masaeedu** [comment]
@filipw Could you explain why installing mono is necessary here? I don't have mono installed on my system and would rather not randomly add it without understanding exactly what purpose it's serving.
