### ISSUE TITLE
VSCode Insiders and RC3

### ISSUE THREAD

**Issue by rhires** [OmniSharp/omnisharp-vscode#332]
Moved from VSCode repo b/c they said so...

    VSCode Version:1.1.1-Insider
    OS Version: Mac 10.10.5

Steps to Reproduce:

* Upgrade to RC2 from RC1-Updatesomething, using the instructions provided for .Net Core
* Upgrade VSCode, see lots of log messages about how it's installing RC3 ... which I don't get, given that I just installed RC2 - did I miss the memo about Insiders using RC3 when RC2 comes out? But then, clicking on the release notes, leads me to 1.2.0 release notes, for May 2016, and looks like an empty template...And finally, it looks like 10.10.x64 is getting left behind...and I must have not seen it, because the logs are saying that "The project does not list one of 'osx.10.10-x64' in the 'runtimes' section." And it suggests that I run dotnet restore, which I do, but then it downloads rc-1 stuff, which I no longer want...Actually, here's the full set of errors which came at the end:

Error: Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'osx.10.10-x64'. Possible causes:
1. The project has not been restored or restore failed - run dotnet restore
2. The project does not list one of 'osx.10.10-x64' in the 'runtimes' section.
Error:

System.InvalidOperationException: Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'osx.10.10-x64'. Possible causes:
1. The project has not been restored or restore failed - run dotnet restore
2. The project does not list one of 'osx.10.10-x64' in the 'runtimes' section.
at Microsoft.DotNet.ProjectModel.BuildWorkspace.GetRuntimeContext(ProjectContext context, IEnumerable1 runtimeIdentifiers) at System.Linq.Enumerable.WhereSelectListIterator2.MoveNext()
at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
at System.Linq.Enumerable.ToListTSource
at Microsoft.DotNet.Tools.Publish.PublishCommand.TryPrepareForPublish()
at Microsoft.DotNet.Tools.Publish.PublishCommand.<>c__DisplayClass0_0.b__0()
at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
at Microsoft.DotNet.Tools.Publish.PublishCommand.Run(String[] args)
dotnet exited with error code 1
Error while installing .NET Core Debugger.

So lots going on here.

**Comment by DustinCampbell** [comment]
Hi, thanks for reaching out! What version of the C# extension are you running? You can check this in VS Code by pressing F1 to show the command palette and then running the Extensions:Show Installed Extensions command.

**Comment by rhires** [comment]
The F1 button doesn't work on my Mac Keyboard, as Apple decided that it should adjust the screen brightness instead. However, using cmd-shift-p and doing the extensions thing, I get version 0.3.7 for C#. Maybe there is confusion between what VSCode wants to run, what it sees in my project.json file for the project I'm in (I haven't gone through the conversion/upgrade process for that yet), and what I installed.

**Comment by rhires** [comment]
Of course, when I tell it to look for outdated extensions, it says for me to upgrade to C# for VSCode...so I do...and now I have 1.0.10, and the .NET Core debugger downloads...and installs with no problems, but then VSCode again decides that my project.json needs help (I haven't converted yet!) and I get errors elsewhere that stuff doesn't work. But I'll ignore those errors because I uninstalled RC1 stuff and will be dismantling my project.json and ~~remantling it~~ putting it back together with RC2 stuff. Still not understanding the RC3 stuff...didn't realize there was an RC3 already! That was quite a surprise.

**Comment by rhires** [comment]
By the way, I would think the Omnisharp log would want to list at least once what version it is...

**Comment by DustinCampbell** [comment]
Sorry -- Function+F1 is what I meant (at least, that's what works on my MacBook Pro).

I don't understand your reference to RC 3 either. I wonder if it's just a typo somewhere. Where are you seeing that?

I'm glad you were able to get the latest C# extension. Yes, you will need to move your project.json forward to continue development.

Thanks for the request to add the version to the OmniSharp log. This has been on my personal TODO list for a long while but I keep forgetting to do it. :smile: Since you mentioned it, I went ahead and filed #346 to track the work.

Do let me know if you have any more issues.
