### ISSUE TITLE
can't use extension when a new version released

### ISSUE THREAD

**Issue by guftall** [OmniSharp/omnisharp-vscode#3321]
hi. every time a new version of this extension released and vscode tries to download that one, if my connection get lost i can't use the old one anymore. it seams that a file named `run` removed before update and i should wait for new version to download. is it vscode extensions behavior or omnisharp problem?

**Comment by gregg-miskelly** [comment]
To solve this problem, VS Code needs to support platform-specific extension files so that there could be different .zip files for the C# extension for all platforms. This is tracked with https://github.com/microsoft/vscode/issues/23251
