### ISSUE TITLE
C# Intellisense partially broken

### ISSUE THREAD

**Issue by bradwilson** [OmniSharp/omnisharp-vscode#3329]
## Issue Description ##

At some point, Intellisense partially stopped working properly in VS Code.

## Steps to Reproduce ##

Unknown.

This is only broken on a single box. It is Windows 10 Insiders Fast Ring build 18990, with WSL 2 enabled, running the Ubuntu image.

The problem exists in all 3 forms:

1. Editing source via "Remote: WSL" (i.e., `code` launched from WSL shell)
2. Editing source without Remote extension, via the `\\wsl$\Ubuntu` share
3. Editing source via a local copy (purely Windows)

The logs here are provided from scenario 1, but the behavior seems identical across all 3.

## Expected Behavior ##

Correct Intellisense behavior. /shrug

## Actual Behavior ##

Currently broken behaviors include:

- No support for F12 anywhere into any linked assemblies (always returns "No definition found")
- No parameter information when calling methods in linked assemblies
- Incorrect behavior with new C# features; for example, with `<Nullable>enable</Nullable>` in the CSPROJ, it will continue to issue CS8632 in-editor whenever using the nullable type decoration, and will not show in-editor errors for nullable issues (compilation required)

There may be others I'm not aware of.

### OmniSharp log ###
<details>
Starting OmniSharp server at 10/8/2019, 9:00:36 AM
    Target: /home/brwilso/dev/appcenter/lib/telemetry-netcore/AppCenter.Telemetry.sln

OmniSharp server started with Mono 6.4.0.
    Path: /home/brwilso/.vscode-server/extensions/ms-vscode.csharp-1.21.4/.omnisharp/1.34.4/omnisharp/OmniSharp.exe
    PID: 1843
</details>

### C# log ###
<details>
This is empty.
</details>

## Environment information ##

**VSCode version**: 1.38.1
**C# Extension**: 1.21.4

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.4.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  2.1.802 [/usr/share/dotnet/sdk]
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.4|
|azure-pipelines|ms-azure-devops|1.157.4|
|chat|karigari|0.22.1|
|code-spell-checker|streetsidesoftware|1.7.18|
|csharp|ms-vscode|1.21.4|
|docomment|k--kato|0.1.8|
|dotnet-test-explorer|formulahendry|0.7.1|
|EditorConfig|EditorConfig|0.13.0|
|gitlens|eamodio|10.1.0|
|Go|ms-vscode|0.11.7|
|powershell|ms-vscode|2019.9.0|
|python|ms-python|2019.9.34911|
|quokka-vscode|WallabyJs|1.0.254|
|ruby|rebornix|0.25.3|
|toggle-excluded-files|eamodio|1.6.0|
|vscode-docker|ms-azuretools|0.8.1|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.0.4|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.2|
|vscode-yaml|redhat|0.5.3|
|vsliveshare|ms-vsliveshare|1.0.905|
|vsliveshare-audio|ms-vsliveshare|0.1.66|
|vsliveshare-pack|ms-vsliveshare|0.3.3|;

</details>

**Comment by bradwilson** [comment]
I also tried deleting all extensions, and then re-installing just the C# extension, and the behavior persists.

**Comment by filipw** [comment]
> * No support for F12 anywhere into any linked assemblies (always returns "No definition found")

this is an unfortunate regression in 1.21.4 (see https://github.com/OmniSharp/omnisharp-roslyn/pull/1624)
It is already fixed here https://github.com/OmniSharp/omnisharp-roslyn/pull/1625
There is a pre-release OmniSharp that can be used as workaround.

`"omnisharp.path": "1.34.5-beta.28"`

**Comment by filipw** [comment]
> * Incorrect behavior with new C# features; for example, with `<Nullable>enable</Nullable>` in the CSPROJ, it will continue to issue CS8632 in-editor whenever using the nullable type decoration, and will not show in-editor errors for nullable issues (compilation required)

could you upload a repro or sample project for this somewhere? and post the full OmniSharp log (with `"omnisharp.logginglevel": "debug"`)?
I am unable to reproduce this, we also have integration tests in OmniSharp that pass on this, so there must be something unusual that is breaking this.

This is what I see:

<img width="1211" alt="Screenshot 2019-10-08 18 51 06" src="https://user-images.githubusercontent.com/1710369/66415879-e7b5ea00-e9fc-11e9-874b-60da9ff73064.png">

**Comment by bradwilson** [comment]
I'm thus far unable to put together a simple repro for the CS8632 issue, so it must be something environmental. Unfortunately I can't share the project as it's closed source.

**Comment by bradwilson** [comment]
>"omnisharp.path": "1.34.5-beta.28"

I'm not sure how to make this work. I added that to my VS Code config, then restarted VS Code, but it shows as a "grayed out" option in config, and didn't cause it to load a new version of Omnisharp's dependencies.

![image](https://user-images.githubusercontent.com/16944/66418461-02fe0680-e9b7-11e9-91e4-d296631480f1.png)

**Comment by bradwilson** [comment]
I think I see the problem. "omnisharp.path" requires reinstalling of the C# extension, and on the Windows side will load the beta version, but on WSL Remote side, reinstall just brings back the RTM version and not the beta version. My suspicion is that whatever logic you're using to peek around for this undocumented flag doesn't work remotely.

**Comment by bradwilson** [comment]
When is this fix coming out of beta? Being broken with WSL Remoting is pretty painful, as that's the place I live. Or any suggestion on how to poke it to download this beta version when doing Remote WSL?

**Comment by bradwilson** [comment]
(I tried a `.vscode/settings.json` setting in the remote project, and that didn't help, either.)

**Comment by filipw** [comment]
sorry I missed the part where you mentioned you are inside WSL remoting.
In that case, once you are inside VS Code in WSL Remote you can go to `~/.vscode-server/data/Machine/settings.json` (or create it if it doesn't exist) and add the `"omnisharp.path": "1.34.5-beta.28"` there. Then it will prompt you to restart OmniSharp and upon restart it will download the prerelease build for Ubuntu. I just tested this on my WSL and it worked fine, so hopefully this works for you too.

another secret undocumented feature is that you could put `"omnisharp.path": "latest"` there and that will always pull latest build from master (if you feel adventurous) 

> When is this fix coming out of beta?

I have just published the new OmniSharp (1.34.5) stable https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.34.5, but it still needs to be consumed into the C# extension and published as either pre-release VISX or stable 1.21.5. 

This is done by @rchande

**Comment by bradwilson** [comment]
Thanks, that gets me working for now. 👍 

If I can come up with a publishable repro for the nullable issues, I'll open a new bug.

**Comment by filipw** [comment]
ah that's great to hear, thanks!
I'd recommend removing the setting once the extension is updated - otherwise you'll be pinned to the old stale build.

**Comment by code1line** [comment]
> > * No support for F12 anywhere into any linked assemblies (always returns "No definition found")
> 
> this is an unfortunate regression in 1.21.4 (see [OmniSharp/omnisharp-roslyn#1624](https://github.com/OmniSharp/omnisharp-roslyn/issues/1624))
> It is already fixed here [OmniSharp/omnisharp-roslyn#1625](https://github.com/OmniSharp/omnisharp-roslyn/pull/1625)
> There is a pre-release OmniSharp that can be used as workaround.
> 
> `"omnisharp.path": "1.34.5-beta.28"`

Works on Mac and Win 10! Thx!
