### ISSUE TITLE
C# extension not working with .NET Core 3.0.100

### ISSUE THREAD

**Issue by PraveenGajjalaTR** [OmniSharp/omnisharp-vscode#3335]
Not sure why extension is not picking the installed .NET Core 3.0.100 version. 

OmniSharp.MSBuild.ProjectLoader not picking the latest installed .NET Core 3.0?

Below is the OmniSharp Log: 

Please paste the output from yoStarting OmniSharp server at 10/9/2019, 1:32:46 PM
    Target: c:\code\samples\abc

OmniSharp server started.
    Path: C:\Users\xxxx\.vscode\extensions\ms-vscode.csharp-1.21.4\.omnisharp\1.34.4\OmniSharp.exe
    PID: 11288

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.1.7601.65536 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 4 MSBuild instance(s)
            1: Visual Studio Professional 2017 15.9.28307.770 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin"
            2: Visual Studio Professional 2019 16.2.29215.179 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"
            3: Visual Studio Build Tools 2017 15.9.28307.586 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            4: StandAlone 16.0 - "C:\Users\U0159381\.vscode\extensions\ms-vscode.csharp-1.21.4\.omnisharp\1.34.4\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Professional 2019 16.2.29215.179 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\code\samples\translates\translation-apis'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\code\samples\translates\translation-apis'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\code\samples\translates\translation-apis\TranslateService\TranslateService.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\code\samples\translates\translation-apis'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\code\samples\translates\translation-apis\TranslateService\TranslateService.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\code\samples\translates\translation-apis' on host 18112.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\code\samples\translates\translation-apis\TranslateService\TranslateService.csproj'.
c:\code\samples\translates\translation-apis\TranslateService\TranslateService.csproj
C:\Program Files\dotnet\sdk\2.2.107\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): Error: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0.

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\code\samples\translates\translation-apis\TranslateService\TranslateService.csproj
ur clipboard

**Comment by filipw** [comment]
OmniSharp uses MSBuild from Visual Studio 2019 when it's installed on your machine. In your case, you have Visual Studio Professional 2019 16.2.29215.179 which doesn't support .NET Core 3.0. You should uninstall it (then OmniSharp will use its built in MSBuild) or upgrade to 16.3.x, which is required by .NET Core 3.0.
