### ISSUE TITLE
Omnisharp and IDisposable bug

### ISSUE THREAD

**Issue by turowicz** [OmniSharp/omnisharp-vscode#3336]
Guys, it seems to me that Omnisharp gets stuck when the user is editing a class that implements `IDisposable`. It is most likely due to it trying to count references and there are many of them. One time I had a crazy number displayed above the method name. 

Is there a way to tell Omnisharp to not analyze a specific method or a code block?

**Comment by nathansoz** [comment]
Also hitting this issue on windows and Linux. 

(version info)
Name: C#
Id: ms-vscode.csharp
Description: C# for Visual Studio Code (powered by OmniSharp).
Version: 1.21.6
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

**Comment by turowicz** [comment]
This setting helps:
```
"csharp.referencesCodeLens.enabled": false
```
