### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by joylogic** [OmniSharp/omnisharp-vscode#3343]
- Issue Type: `Performance`
- Extension Name: `csharp`
- Extension Version: `1.17.1`
- OS Version: `Linux x64 4.4.0-141-generic`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/joylogic/ms-vscode.csharp-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by JoeRobich** [comment]
Hi @joylogic,
It seems you are on an old version of the extension. Please update because we think this has already been fixed.
-Joey
