### ISSUE TITLE
Symbols that in metadata can't "go to definition".

### ISSUE THREAD

**Issue by DFVSQY** [OmniSharp/omnisharp-vscode#3344]
## Environment data
`dotnet --info` output:
![image](https://user-images.githubusercontent.com/8075421/66704654-8ff6e600-ed50-11e9-800c-babca84dd4bc.png)

VS Code version:
![image](https://user-images.githubusercontent.com/8075421/66704659-9e450200-ed50-11e9-8467-22791ec55f84.png)

C# Extension version:1.21.4

![image](https://user-images.githubusercontent.com/8075421/66704672-e106da00-ed50-11e9-9666-587f49a53a27.png)

It shows "cant find any definition"

**Comment by filipw** [comment]
This is a regression in extension 1.21.4.
See here for a workaround https://github.com/OmniSharp/omnisharp-vscode/issues/3326#issuecomment-539322963

you could also install 1.21.5 VSIX from https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.5 (it's not yet available on the marketplace)
