### ISSUE TITLE
Omnisharp updates without permission

### ISSUE THREAD

**Issue by ndotb** [OmniSharp/omnisharp-vscode#3346]
## Issue Description ##
the C# extension ignores extension update rules set elsewhere and updates automatically.  For those globally who lack access to broadband, this is an impediment to work as the server is shut down during the long download process.

## Steps to Reproduce ##
1. Open VS Code
2. Watch the slow progression of dots in the C# output window

## Expected Behavior ##
Obey global settings for VS Code extension updates

## Actual Behavior ##
Non-compliance

## Logs ##
```
Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.34.6-beta.17...
Platform: linux, x86_64, name=ubuntu, version=19.04

Downloading package 'OmniSharp for Linux (x64), Version = 1.34.6-beta.17' (42216 KB)..................
```

### OmniSharp log ###
[empty]

### C# log ###
```
Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.34.6-beta.17...
Platform: linux, x86_64, name=ubuntu, version=19.04

Downloading package 'OmniSharp for Linux (x64), Version = 1.34.6-beta.17' (42216 KB)..................
```

## Environment information ##

**VSCode version**: 1.39.1
**C# Extension**: 1.21.4

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.04
 OS Platform: Linux
 RID:         ubuntu.19.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-using|Fudge|0.7.9|
|clang-format|xaver|1.9.0|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|1.1.3|
|cmake-tools-helper|maddouri|0.2.1|
|cpptools|ms-vscode|0.25.1|
|csharp|ms-vscode|1.21.4|
|dark-plus-material|vangware|2.1.1|
|EditorConfig|EditorConfig|0.14.1|
|python|ms-python|2019.10.41019|
|rainbow-csv|mechatroner|1.3.1|
|restructuredtext|lextudio|114.0.0|
|vscode-icons|vscode-icons-team|9.4.0|
|vscode-postgresql|ms-ossdata|0.2.0|;

</details>

**Comment by filipw** [comment]
It's not the extension that updates, but the OmniSharp server bundled with it. I presume you have "omnisharp.path": "latest" in your settings which means you have explicitly opted into pulling the latest OmniSharp prerelease build from master branch.

You should remove that, then the OmniSharp version will stay pinned to that which ships with the extension (and extension will obey the update settings as you mentioned).

**Comment by scottpage** [comment]
I rolled back to using 1.21.4 and then 1.21.3.
No change, same issue.
