### ISSUE TITLE
Omnisharp older version

### ISSUE THREAD

**Issue by OLUWAMUYIWA** [OmniSharp/omnisharp-vscode#3351]
How do I get an older version of omnisharp for my vs code please?
Vs Code isn't allowing me to install an older version and I need to know where to get it manually.
My windows version won't support the latest version, so I really need to go don to 1.18.0
Thank you.

**Comment by filipw** [comment]
you should:

1) remove the extension from VS Code
2) disable extension autoupdate in VS Code
3) download 1.18.0 VSIX from https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.18.0
4) install the extension from VSIX using these instructions https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases#installing-a-beta-release-of-the-c-extension

**Comment by DanielLSM** [comment]
how is this closed if it still is failing right now in 2021???
