### ISSUE TITLE
Jump to define(F12) failed on Funtoo

### ISSUE THREAD

**Issue by buzzlu** [OmniSharp/omnisharp-vscode#3363]
- Sample code as below:

     public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

Highlight ErrorViewModel and press F12, nothing happens. It should jump to definition of ErrorViewModel.

- dotnet --info

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     funtoo
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/buzz.lu/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.2.402 [/home/buzz.lu/dotnet/sdk]
  3.0.100 [/home/buzz.lu/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [/home/buzz.lu/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [/home/buzz.lu/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/home/buzz.lu/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [/home/buzz.lu/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/home/buzz.lu/dotnet/shared/Microsoft.NETCore.App]

- OminiSharp Log

Starting OmniSharp server at 10/20/2019, 8:52:57 PM
    Target: /home/buzz.lu/repos/f12Test

Razor dev mode active. Suppressing built-in OmniSharp Razor support.

OmniSharp server started with Mono 6.4.0.
    Path: /home/buzz.lu/.vscode/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.5/omnisharp/OmniSharp.exe
    PID: 25263

**Comment by filipw** [comment]
please post the full OmniSharp log (also, please set ` "omnisharp.loggingLevel": "debug"`, thanks

**Comment by caiocsgomes** [comment]
This is also happening to me on Ubuntu 18.04. Omnisharp is not able to recognize any package or classes from other projects, even though all the references are added on the .csproj

**Comment by buzzlu** [comment]
**OmniSharp Log :**

[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 134,
  "Command": "/typelookup",
  "Arguments": {
    "FileName": "/home/buzz.lu/repos/f12Test/Controllers/HomeController.cs",
    "Line": 34,
    "Column": 34,
    "IncludeDocumentation": true
  }
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 134,
  "Command": "/typelookup",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "Type": null,
    "Documentation": null,
    "StructuredDocumentation": null
  },
  "Seq": 448,
  "Type": "response"
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 135,
  "Command": "/gotoDefinition",
  "Arguments": {
    "FileName": "/home/buzz.lu/repos/f12Test/Controllers/HomeController.cs",
    "Line": 34,
    "Column": 37,
    "WantMetadata": true
  }
}
[dbug]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 135,
  "Command": "/gotoDefinition",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": null,
  "Seq": 451,
  "Type": "response"
}

**Comment by filipw** [comment]
@buzzlu you should uninstall the mono you have or install the newest mono (6.4.0) to solve the problem

**Comment by buzzlu** [comment]
F12 is function now after upgrade to the latest mono.
