### ISSUE TITLE
OmniSharp server fails to initialise on NixOS

### ISSUE THREAD

**Issue by FelschR** [OmniSharp/omnisharp-vscode#3365]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     nixos
 OS Version:  19.09.840.8bf142e001b
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /nix/store/hmzz1c5qz5z8s4i3jwavfrnp386g0gl9-dotnet-sdk-3.0.100/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/nix/store/hmzz1c5qz5z8s4i3jwavfrnp386g0gl9-dotnet-sdk-3.0.100/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/nix/store/hmzz1c5qz5z8s4i3jwavfrnp386g0gl9-dotnet-sdk-3.0.100/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/nix/store/hmzz1c5qz5z8s4i3jwavfrnp386g0gl9-dotnet-sdk-3.0.100/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS Code version: 1.39.1
C# Extension version: 1.21.5

## Steps to reproduce
Install VSCode on NixOS, install the C# extension and open a .NET Core project.
Have the default setting `"omnisharp.path": "latest"`.

## Expected  behavior
The OmniSharp server loads successfully.

## Actual behavior
OmniSharp log states:
```sh
Starting OmniSharp server at 21/10/2019, 13:39:35
    Target: /home/felschr/Documents/projects/MyProject/MyProject.sln

OmniSharp server started.
    Path: /home/felschr/.vscode/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.6-beta.34/run
    PID: 23523

/home/felschr/.vscode/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.6-beta.34/run: line 27: /home/felschr/.vscode/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.6-beta.34/bin/mono: No such file or director
```

**Comment by filipw** [comment]
is the folder there? `/home/felschr/.vscode/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.6-beta.34/` does it contain OmniSharp?
Normally, OmniSharp should be downloaded at extension startup into that folder. Did the extension try to download it? the log of that operation should be in C# log.

Also, please note that `"omnisharp.path": "latest"` is an undocumented and unsupported feature, that only exists to provide the ability to pull the latest build of OmniSharp from master as a means for checking new features or bug fixes and therefore it will be, by its nature, inherently unstable.

**Comment by FelschR** [comment]
The folder and the file `/home/felschr/.vscode/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.6-beta.34/bin/mono` exit and the file is marked executable.
It looks to be some kind of 32-bit support issue.

**Comment by filipw** [comment]
you could try downloading OmniSharp manually from here https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.34.5 and replace the build you have

**Comment by david-nordvall** [comment]
I can report the exact same error on Alpine Linux 3.9 running in a docker container with .NET Core SDK 3.0.100 using VS Code Remote Containers extension. Host is Windows 10 1903.

**Comment by stanipintjuk** [comment]
@FelschR You can't execute arbitrary binaries in NixOS. You have to use PatchELF on them first https://nixos.org/patchelf.html

**Comment by stanipintjuk** [comment]
@FelschR you can check out this https://github.com/NixOS/nixpkgs/pull/57205 to see how to use omnisharp with vscode in NixOS
