### ISSUE TITLE
Is it possible to sort suggestion base on type hierarchy?

### ISSUE THREAD

**Issue by Thaina** [OmniSharp/omnisharp-vscode#337]
I would like vscode in C# could have this feature from monodevelop. To sort members of an object by the class it defined

![image](https://cloud.githubusercontent.com/assets/1042507/15347193/65abbb7c-1ce9-11e6-8f69-68e4ec247936.png)

It quite useful for class with a load of member from hierarchy. Such as monobehaviour in unity

**Comment by DustinCampbell** [comment]
This issue was moved to dotnet/roslyn#16996
