### ISSUE TITLE
VS Code 1.35.1 on Windows 10 C# 1.19.1, OmniSharp 1.32.19 error: [fail]: OmniSharp.MSBuild.ProjectLoader Unable to find package Microsoft.VisualStudio.CodingConventions

### ISSUE THREAD

**Issue by seanwmc1-swm** [OmniSharp/omnisharp-vscode#3380]
Please paste the output from your clipboardStarting OmniSharp server at 10/29/2019, 9:05:08 AM
    Target: c:\Projects\Git\Repos\HscbApi\Hscb.API

OmniSharp server started.
    Path: C:\Users\smccarthy\.vscode\extensions\ms-vscode.csharp-1.19.1\.omnisharp\1.32.19\OmniSharp.exe
    PID: 15368

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2017 15.9.28307.905 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\smccarthy\.vscode\extensions\ms-vscode.csharp-1.19.1\.omnisharp\1.32.19\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2017 15.9.28307.905 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Projects\Git\Repos\HscbApi\Hscb.API'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Projects\Git\Repos\HscbApi\Hscb.API'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Projects\Git\Repos\HscbApi\Hscb.API'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Projects\Git\Repos\HscbApi\Hscb.API' on host 1968.
[fail]: OmniSharp.MSBuild.ProjectLoader
        Unable to find package Microsoft.VisualStudio.CodingConventions. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
[fail]: OmniSharp.MSBuild.ProjectLoader
        Detected package downgrade: Microsoft.CodeAnalysis.CSharp from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> Microsoft.CodeAnalysis.CSharp (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.CSharp (>= 3.4.0-beta2-final)
[fail]: OmniSharp.MSBuild.ProjectLoader
        Detected package downgrade: Microsoft.CodeAnalysis.CSharp.Features from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> Microsoft.CodeAnalysis.CSharp.Features (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.CSharp.Features (>= 3.4.0-beta2-final)
[fail]: OmniSharp.MSBuild.ProjectLoader
        Detected package downgrade: Microsoft.CodeAnalysis.CSharp.Workspaces from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> Microsoft.CodeAnalysis.CSharp.Workspaces (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.CSharp.Workspaces (>= 3.4.0-beta2-final)
[fail]: OmniSharp.MSBuild.ProjectLoader
        Detected package downgrade: Microsoft.CodeAnalysis.Common from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> OmniSharp.Roslyn 1.34.6 -> Microsoft.CodeAnalysis.Common (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.Common (>= 3.4.0-beta2-final)
[fail]: OmniSharp.MSBuild.ProjectLoader
        Detected package downgrade: Microsoft.CodeAnalysis.Workspaces.Common from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> OmniSharp.Roslyn 1.34.6 -> Microsoft.CodeAnalysis.Workspaces.Common (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.Workspaces.Common (>= 3.4.0-beta2-final)
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj'.
c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj
c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj(0,0): Error: Unable to find package Microsoft.VisualStudio.CodingConventions. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj(0,0): Error: Detected package downgrade: Microsoft.CodeAnalysis.CSharp from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> Microsoft.CodeAnalysis.CSharp (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.CSharp (>= 3.4.0-beta2-final)
c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj(0,0): Error: Detected package downgrade: Microsoft.CodeAnalysis.CSharp.Features from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> Microsoft.CodeAnalysis.CSharp.Features (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.CSharp.Features (>= 3.4.0-beta2-final)
c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj(0,0): Error: Detected package downgrade: Microsoft.CodeAnalysis.CSharp.Workspaces from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> Microsoft.CodeAnalysis.CSharp.Workspaces (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.CSharp.Workspaces (>= 3.4.0-beta2-final)
c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj(0,0): Error: Detected package downgrade: Microsoft.CodeAnalysis.Common from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> OmniSharp.Roslyn 1.34.6 -> Microsoft.CodeAnalysis.Common (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.Common (>= 3.4.0-beta2-final)
c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj(0,0): Error: Detected package downgrade: Microsoft.CodeAnalysis.Workspaces.Common from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> OmniSharp.Roslyn 1.34.6 -> Microsoft.CodeAnalysis.Workspaces.Common (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.Workspaces.Common (>= 3.4.0-beta2-final)

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj

**Comment by filipw** [comment]
please update the extension to the latest version

**Comment by seanwmc1-swm** [comment]
@filipw Thanks for responding so quickly. I've been down this road a few dozen times. 
I've also tried updating the build tools to no avail. 
I searched for Microsoft.VisualStudio.CodingConventions and couldn't find anything on it.

Updated the extension again gets the following:

Starting OmniSharp server at 10/29/2019, 9:58:44 AM
    Target: c:\Projects\Git\Repos\HscbApi\Hscb.API

OmniSharp server started.
    Path: C:\Users\smccarthy\.vscode\extensions\ms-vscode.csharp-**1.21.5**\.omnisharp\\**1.34.5**\OmniSharp.exe
    PID: 2564

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2017 15.9.28307.905 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            2: StandAlone 16.0 - "C:\Users\smccarthy\.vscode\extensions\ms-vscode.csharp-1.21.5\.omnisharp\1.34.5\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Users\smccarthy\.vscode\extensions\ms-vscode.csharp-1.21.5\.omnisharp\1.34.5\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.0 - "C:\Users\smccarthy\.vscode\extensions\ms-vscode.csharp-1.21.5\.omnisharp\1.34.5\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Users\smccarthy\.vscode\extensions\ms-vscode.csharp-1.21.5\.omnisharp\1.34.5\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = C:\Users\smccarthy\.vscode\extensions\ms-vscode.csharp-1.21.5\.omnisharp\1.34.5\.msbuild
            MSBuildToolsPath = C:\Users\smccarthy\.vscode\extensions\ms-vscode.csharp-1.21.5\.omnisharp\1.34.5\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Projects\Git\Repos\HscbApi\Hscb.API'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Projects\Git\Repos\HscbApi\Hscb.API'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Projects\Git\Repos\HscbApi\Hscb.API'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Projects\Git\Repos\HscbApi\Hscb.API' on host 13364.
[fail]: OmniSharp.MSBuild.ProjectLoader
        Unable to find package Microsoft.VisualStudio.CodingConventions. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
[fail]: OmniSharp.MSBuild.ProjectLoader
        Detected package downgrade: Microsoft.CodeAnalysis.CSharp from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> Microsoft.CodeAnalysis.CSharp (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.CSharp (>= 3.4.0-beta2-final)
[fail]: OmniSharp.MSBuild.ProjectLoader
        Detected package downgrade: Microsoft.CodeAnalysis.CSharp.Features from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> Microsoft.CodeAnalysis.CSharp.Features (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.CSharp.Features (>= 3.4.0-beta2-final)
[fail]: OmniSharp.MSBuild.ProjectLoader
        Detected package downgrade: Microsoft.CodeAnalysis.CSharp.Workspaces from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> Microsoft.CodeAnalysis.CSharp.Workspaces (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.CSharp.Workspaces (>= 3.4.0-beta2-final)
[fail]: OmniSharp.MSBuild.ProjectLoader
        Detected package downgrade: Microsoft.CodeAnalysis.Common from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> OmniSharp.Roslyn 1.34.6 -> Microsoft.CodeAnalysis.Common (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.Common (>= 3.4.0-beta2-final)
[fail]: OmniSharp.MSBuild.ProjectLoader
        Detected package downgrade: Microsoft.CodeAnalysis.Workspaces.Common from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> OmniSharp.Roslyn 1.34.6 -> Microsoft.CodeAnalysis.Workspaces.Common (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.Workspaces.Common (>= 3.4.0-beta2-final)
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj'.
c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj
c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj(0,0): Error: Unable to find package Microsoft.VisualStudio.CodingConventions. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj(0,0): Error: Detected package downgrade: Microsoft.CodeAnalysis.CSharp from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> Microsoft.CodeAnalysis.CSharp (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.CSharp (>= 3.4.0-beta2-final)
c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj(0,0): Error: Detected package downgrade: Microsoft.CodeAnalysis.CSharp.Features from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> Microsoft.CodeAnalysis.CSharp.Features (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.CSharp.Features (>= 3.4.0-beta2-final)
c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj(0,0): Error: Detected package downgrade: Microsoft.CodeAnalysis.CSharp.Workspaces from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> Microsoft.CodeAnalysis.CSharp.Workspaces (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.CSharp.Workspaces (>= 3.4.0-beta2-final)
c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj(0,0): Error: Detected package downgrade: Microsoft.CodeAnalysis.Common from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> OmniSharp.Roslyn 1.34.6 -> Microsoft.CodeAnalysis.Common (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.Common (>= 3.4.0-beta2-final)
c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj(0,0): Error: Detected package downgrade: Microsoft.CodeAnalysis.Workspaces.Common from 3.4.0-beta3-19516-01 to 3.4.0-beta2-final. Reference the package directly from the project to select a different version. 
 Hscb.API -> OmniSharp.Roslyn.CSharp 1.34.6 -> OmniSharp.Roslyn 1.34.6 -> Microsoft.CodeAnalysis.Workspaces.Common (>= 3.4.0-beta3-19516-01) 
 Hscb.API -> Microsoft.CodeAnalysis.Workspaces.Common (>= 3.4.0-beta2-final)

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Projects\Git\Repos\HscbApi\Hscb.API\Hscb.API.csproj

**Comment by filipw** [comment]
OK I see now. it looks like your project references ` OmniSharp.Roslyn.CSharp` from nuget. why is that the case? that is not needed to make any language services to work. are you trying to build something on top of OmniSharp?

OmniSharp nuget packages require custom nuget sources to work correctly.

**Comment by seanwmc1-swm** [comment]
@filipw I removed the OmniSharp.Roslyn.CSharp nuget, upgraded C# extension, updated VS Code and I'm back in business. Thanks for your help!
I'm embarrassed to say how long that hung me up. Couldn't tell you how the reference for Roslyn got in there either.

**Comment by filipw** [comment]
thanks for confirming 👍
