### ISSUE TITLE
Debugger fails to download CoreCLR source file

### ISSUE THREAD

**Issue by Jepson109** [OmniSharp/omnisharp-vscode#3382]
**Environment data**：
MacOS: High sierra (10.13)

VScode version [1.39.2](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fupdate.code.visualstudio.com%2F1.39.2%2Fdarwin%2Fstable&data=02%7C01%7Cv-pejian%40microsoft.com%7Cce8365a1e3204c8cbfa508d75d1cf64f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637080251412827961&sdata=pak%2FXgFaaDVKdi3p1pTyUYM8O36Tn2hD4tP3pUNmdEg%3D&reserved=0) + C# extension [1.21.6](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOmniSharp%2Fomnisharp-vscode%2Freleases%2Fdownload%2Fv1.21.6%2Fcsharp-1.21.6.vsix&data=02%7C01%7Cv-pejian%40microsoft.com%7Cce8365a1e3204c8cbfa508d75d1cf64f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637080251412917912&sdata=VtdVdVUfWKmG%2BuAfnS77p5yWvI9zq%2FGpnG4%2BZHuvUKU%3D&reserved=0) + CLI\SDK:  3.1.100-preview2-014569

Dotnet –info:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview2-014569
 Commit:    4bd5d24d87
 
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.100-preview2-014569/
 
Host (useful for support):
  Version: 3.1.0-preview2.19525.6
  Commit:  5672978d91
 
.NET Core SDKs installed:
  3.1.100-preview2-014569 [/usr/local/share/dotnet/sdk]
 
.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0-preview2.19528.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0-preview2.19525.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
 
To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Steps to reproduce**:
1.	Create a new ASP.NET Razor project by doing 
mkdir razor
cd razor
dotnet new razor
2.	Edit ‘launch.json’ file. 
Add the following lines after the “name” line of the “Configurations” object.   (This allows debugging through the framework.  
 
"justMyCode": false,
"symbolOptions": {
      "searchMicrosoftSymbolServer": true
},
"suppressJITOptimizations": true,
 
 
3.	Double click on the ‘Startup.cs’ file in the ‘Explorer’ pane to bring up that source code. 
4.	 Add the following line to the Startup.cs file at the beginning of the ‘Configure’ method (at the bottom of the file).  
Console.WriteLine("x " + 3);
 
5.	Place a breakpoint on that line (F9). 
6.	Run the application until it hit that breakpoint (F5). 
7.	Step into the concatination method (F11).

**Expected behavior**:
Step into the concatination method (F11) succeeded.

**Actual behavior**:
Step into the concatination method (F11) failed with Could not load source 'https://raw.githubusercontent.com/dotnet/coreclr/30583ce8b3816f6855b14f6f855db604db23cfc4/src/System.Private.CoreLib/shared/System/Int32.cs': Internal error in the debugger. The operation was canceled..
![image](https://user-images.githubusercontent.com/38854445/67846724-abc5fe80-fb3c-11e9-9f6e-e4a78d807452.png)

**Comment by JoeRobich** [comment]
@WardenGnaw & @gregg-miskelly

**Comment by JoeRobich** [comment]
I was unable to reproduce. The likely cause was a network issue. Not sure the expected behavior when source can't be loaded for the method being stepped into.

**Comment by gregg-miskelly** [comment]
I also cannot repro this. @Jepson109 do you use a proxy server? Do you always hit into this problem? Can you hit that link in a browser?

**Comment by Jepson109** [comment]
Thanks all.

**Comment by gregg-miskelly** [comment]
Thanks. Let us know if this comes back.
