### ISSUE TITLE
VS Code Razor syntax highlighting and intellisense not working

### ISSUE THREAD

**Issue by pheuter** [OmniSharp/omnisharp-vscode#3383]
### Screenshot
![Annotation 2019-10-30 130044](https://user-images.githubusercontent.com/92698/67880818-c638b180-fb15-11e9-8c52-731f0a550720.png)

### Versions
* Visual Studio Code:
```
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.6|
|azure-pipelines|ms-azure-devops|1.157.4|
|csharp|ms-vscode|1.21.5|
|docomment|k--kato|0.1.8|
|rest-client|humao|0.22.2|
|vscode-html-css|ecmel|0.2.3|
|vscodeintellicode|VisualStudioExptTeam|1.2.0|;

</details>

### Additional Context
The app is being developed inside a container using Visual Studio Code Remote - Containers.

This same ASP.NET Core Blazor Server app works fine with proper Razor syntax highlighting and intellisense in Visual Studio 2019 v16.3.7

**Comment by JoeRobich** [comment]
@pheuter Thanks for the report. There have been improvements to the Razor support since you logged this issue that I think should cover these problems. Let me know if you are still seeing these problems and we can investigate further.
