### ISSUE TITLE
OmniSharp Intellisense not working 1.21.5 Version: 1.40.0-insider

### ISSUE THREAD

**Issue by buckstephenh** [OmniSharp/omnisharp-vscode#3387]
Version: 1.40.0-insider
Commit: 37d34176a6ecf1d09b16a0cad11bb619f3b1e48f
Date: 2019-11-01T10:17:22.357Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

Not sure where to begin the troubleshooting process.  "Go to Definition" and "Find All References" do not work.

**Comment by filipw** [comment]
Please provide your Omnisharp log - thanks.

**Comment by filipw** [comment]
I will close this due to lack of response. Please install the latest extension which normally fixes all issues 😀
