### ISSUE TITLE
OmniSharp did not start(v1.0.10)

### ISSUE THREAD

**Issue by itn3000** [OmniSharp/omnisharp-vscode#339]
When I opened the csharp project generated by `dotnet new`,OmniSharp did not boot.Only the following line was displayed in OmniSharp log.
```
[INFO] Starting OmniSharp at 'c:\src\vscode-test'...
```
I tested another version,then 1.0.8 or previous were ok,but 1.0.9 or later were not working.
my environment is:
* windows 8.1(64bit)
* vscode 1.1.1
* having http proxy
    * set http_proxy and https_proxy

**Comment by DustinCampbell** [comment]
@itn3000, does the latest (1.0.11) work for you?

**Comment by itn3000** [comment]
@DustinCampbell I'm afraid it was not worked(same as 1.0.10).
I ran the extension from source,then I get the following error:
```
'C:\Program Files (x86)\Microsoft VS Code\Code.exe' --debugBrkPluginHost=46392 --extensionDevelopmentPath=g:\src\gitrepos\omnisharp-vscode

Loading development extension at g:/src/gitrepos/omnisharp-vscode
[g:/src/gitrepos/omnisharp-vscode]: Overwriting extension C:/Users/ito/.vscode/extensions/ms-vscode.csharp-1.0.11 with g:/src/gitrepos/omnisharp-vscode.
[OmniSharp]: Installing to g:\src\gitrepos\omnisharp-vscode\.omnisharp
[OmniSharp] Attempting to download omnisharp-win-x64-net451.zip...
Uncaught Exception: Error: connect ETIMEDOUT 13.88.144.248:443
Error: connect ETIMEDOUT 13.88.144.248:443
at Object.exports._errnoException (util.js:890:11)
at exports._exceptionWithHostPort (util.js:913:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
Uncaught Exception: Error: socket hang up
Error: socket hang up
at createHangUpError (_http_client.js:239:15)
at TLSSocket.socketCloseListener (_http_client.js:271:23)
at emitOne (events.js:95:20)
at TLSSocket.emit (events.js:182:7)
at TCP._onclose (net.js:477:12)
ApplicationInsights:Sender
Array[1]
0:Object
```

I guess the nodejs's 'http' module does not support proxy?

**Comment by itn3000** [comment]
I think using [request](https://www.npmjs.com/package/request) module is better than use 'https' module.
'github-releases' module also uses it.

**Comment by DustinCampbell** [comment]
I believe this should be fixed with this PR: https://github.com/OmniSharp/omnisharp-vscode/pull/350
