### ISSUE TITLE
OmniSharp detects System as not found after dotnet core upgrade to 3.0

### ISSUE THREAD

**Issue by matiaso11** [OmniSharp/omnisharp-vscode#3390]
Issue Type: <b>Bug</b>

After upgrade dotnet core to 3.0 (installed from msdn webside) OmniSharp do not recognize System, void, string and Console in basic dotnet new console Hello World app.

Extension version: 1.21.5
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (0.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by filipw** [comment]
please post your OmniSharp log - thanks

**Comment by matiaso11** [comment]
Hello filipw, thanks for answer. Please find log below.

Starting OmniSharp server at 2.11.2019, 23:03:58
    Target: d:\Dev\c#\MyAttribute

OmniSharp server started.
    Path: C:\Users\macie\.vscode\extensions\ms-vscode.csharp-1.21.5\.omnisharp\1.34.5\OmniSharp.exe
    PID: 23156

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.2.29201.188 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.0 - "C:\Users\macie\.vscode\extensions\ms-vscode.csharp-1.21.5\.omnisharp\1.34.5\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.2.29201.188 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\Dev\c#\MyAttribute'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'd:\Dev\c#\MyAttribute'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Dev\c#\MyAttribute\MyAttribute.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\Dev\c#\MyAttribute'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Dev\c#\MyAttribute\MyAttribute.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\Dev\c#\MyAttribute' on host 17852.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\Dev\c#\MyAttribute\MyAttribute.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\Dev\c#\MyAttribute\MyAttribute.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MyAttribute
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        MyAttribute: Did not find 'Microsoft.NETCore.App' in lock file.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Dev\c#\MyAttribute\MyAttribute.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Dev\c#\MyAttribute\MyAttribute.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\Dev\c#\MyAttribute\MyAttribute.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MyAttribute
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        MyAttribute: Did not find 'Microsoft.NETCore.App' in lock file.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Dev\c#\MyAttribute\MyAttribute.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Dev\c#\MyAttribute\MyAttribute.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\Dev\c#\MyAttribute\MyAttribute.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MyAttribute
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        MyAttribute: Did not find 'Microsoft.NETCore.App' in lock file.
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: Generuj typ „MyImportant” -> Generuj element class „MyImportant” w nowym pliku
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Dev\c#\MyAttribute\MyAttribute.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Dev\c#\MyAttribute\MyAttribute.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\Dev\c#\MyAttribute\MyAttribute.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MyAttribute
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        MyAttribute: Did not find 'Microsoft.NETCore.App' in lock file.

**Comment by filipw** [comment]
@matiaso11 the minimum VS 2019 version to work with .NET Core 3.0 is 16.3. according to your log you have 16.2.29201.188

since OmniSharp prefers msbuild from VS2019 over it's bundled one, please update it

**Comment by matiaso11** [comment]
Thank you for your help. I do not need VS 2019, I use VS Code version: Code 1.39.2.
Does It mean that when I want just use omnisharp in VS Code I have to install VS 2019 ?

**Comment by filipw** [comment]
OmniSharp will use msbuild from Visual Studio if an installation is found on your machine. since you have an out of date VS2019 on your machine (not supporting .NET Core 3.0) you get an error.

please update it or uninstall it if you don't want to update it (then OmniSharp will use its bundled msbuild)

**Comment by matiaso11** [comment]
Thanks for help.
