### ISSUE TITLE
Not updating to v1.21.6

### ISSUE THREAD

**Issue by jtsom** [OmniSharp/omnisharp-vscode#3392]
## Issue Description ## 
VSCode is not seeing the update to v1.21.6. It was released 5 days ago but the extension is not updating.

Yes, I can download the vsix file and manually install, but I shouldn't have to. If there is an issue with the extension so it's not on the marketplace, it should be removed from the released list.

## Steps to Reproduce ##
Open VSCode with v1.21.5 installed. Check for Extension updates. No updates.
## Expected Behavior ##
v.1.21.6 to be installed
## Actual Behavior ##
v1.21.6 not installed.
### OmniSharp log ###
<details>
Starting OmniSharp server at 11/4/2019, 6:19:58 AM
    Target: /Users/john/Dev/TimeTrackerApi/TimeTrackerAPI.sln

OmniSharp server started.
    Path: /Users/john/.vscode-insiders/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.5/run
    PID: 34930

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.15.1 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.0 - "/Users/john/.vscode-insiders/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.5/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/Users/john/.vscode-insiders/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.5/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.0 - "/Users/john/.vscode-insiders/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.5/omnisharp/.msbuild/Current/Bin"
            MSBuildExtensionsPath = /Users/john/.vscode-insiders/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.5/omnisharp/.msbuild
            BypassFrameworkInstallChecks = true
            CscToolPath = /Users/john/.vscode-insiders/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.5/omnisharp/.msbuild/Current/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /Users/john/.vscode-insiders/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.5/omnisharp/.msbuild/Current/Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/john/Dev/TimeTrackerApi'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/john/Dev/TimeTrackerApi/TimeTrackerAPI.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/john/Dev/TimeTrackerApi/TimeTrackerAPI/TimeTrackerAPI.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/john/Dev/TimeTrackerApi'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/john/Dev/TimeTrackerApi/TimeTrackerAPI/TimeTrackerAPI.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/john/Dev/TimeTrackerApi' on host 34907.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/john/Dev/TimeTrackerApi/TimeTrackerAPI/TimeTrackerAPI.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/john/Dev/TimeTrackerApi/TimeTrackerAPI/TimeTrackerAPI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: TimeTrackerAPI
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 61.

</details>

### C# log ###
Empty

## Environment information ##

**VSCode version**: 1.40.0-insider
**C# Extension**: 1.21.5

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.2.100 [/usr/local/share/dotnet/sdk]
  2.2.104 [/usr/local/share/dotnet/sdk]
  2.2.107 [/usr/local/share/dotnet/sdk]
  2.2.300 [/usr/local/share/dotnet/sdk]
  2.2.401 [/usr/local/share/dotnet/sdk]
  2.2.402 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Angular2|johnpapa|8.1.1|
|csharp|ms-vscode|1.21.5|
|debugger-for-chrome|msjsdiag|4.12.1|
|githistory|donjayamanne|0.4.6|
|json-to-ts|MariusAlchimavicius|1.5.5|
|material-icon-theme|PKief|3.9.1|
|msbuild-project-tools|tintoy|0.3.2|
|ng-template|Angular|0.802.3|
|night-owl|sdras|1.1.3|
|open-in-browser|techer|2.0.0|
|path-intellisense|christian-kohler|1.4.2|
|remote-ssh|ms-vscode-remote|0.47.2|
|remote-ssh-edit|ms-vscode-remote|0.47.2|
|Theme-1337|ms-vscode|0.1.4|
|vscode-docker|ms-azuretools|0.8.2|
|vscode-eslint|dbaeumer|1.9.1|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.2|
|vscodeintellicode|VisualStudioExptTeam|1.2.0|
|winteriscoming|johnpapa|1.3.0|;

</details>

**Comment by filipw** [comment]
The release was created on github but the extension was not published to the marketplace https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

cc @JoeRobich

**Comment by filipw** [comment]
the extension 1.21.6 is now in the marketplace
