### ISSUE TITLE
Completion list is incomplete for aspnetcorerazor (blazor)

### ISSUE THREAD

**Issue by vsccarl** [OmniSharp/omnisharp-vscode#3400]
## Environment data
`dotnet --info` output: 
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview2-014569
 Commit:    4bd5d24d87

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview2-014569 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview2.19528.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

VS Code version: 
Version: 1.40.0 (system setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

C# Extension version:
1.21.7

## Steps to reproduce

1. Create a new blazor server app `dotnet new blazorserver`
2. Open the folder in VS Code, open Pages.Index.razor
3. At the top type `@SetPar` or `@Date`

## Expected  behavior
C# completion should suggest `@SetParametersAsync`
For `@Date`, it does eventually find `@DateTime` but is appending `DateTime` onto whatever you have already typed.

## Actual behavior
Both `@SetParametersAsync` and `@DateTime` should be in the completion list

**Comment by JoeRobich** [comment]
Fixed by https://github.com/OmniSharp/omnisharp-vscode/pull/3406
