### ISSUE TITLE
The .NET Core SDK cannot be located

### ISSUE THREAD

**Issue by GhostShot3** [OmniSharp/omnisharp-vscode#3401]
## Environment data
`dotnet --info` output:
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version:
1.40

C# Extension version:
1.21.6

## Expected  behavior
VScode find .net core sdk

## Actual behavior
VScode can't find .net core sdk but i installed it
![11](https://user-images.githubusercontent.com/18537420/68538608-1dc8ef80-0356-11ea-9b80-00aad50db102.png)

**Comment by ThibautNijsPXL** [comment]
Same thing when using 1.21.7

**Comment by FlyingWraptor** [comment]
Same thing when using 1.21.7

**Comment by FlyingWraptor** [comment]
The net core 3.0-rc1 sdk works perfectly fine: https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-rc1-windows-x64-installer

**Comment by GhostShot3** [comment]
Failed to install

**Comment by gregg-miskelly** [comment]
Please, don't install the 3.0-rc1 SDK -- that is an outdated release candidate.

@GhostShot3 the output you have from above indicates that the C# extension is working correctly - you don't have a .NET SDK installed, just a .NET runtime. Did you install an SDK? Here is the current [install link](https://download.visualstudio.microsoft.com/download/pr/8a382be6-d34e-4a15-92a1-e49fe2fa54d6/0038e8d5447470750098f8db5d836561/dotnet-sdk-3.0.100-win-gs-x64.exe) from https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install

**Comment by GhostShot3** [comment]
Yes i install i tryed and say already installed

**Comment by gregg-miskelly** [comment]
Can you try uninstalling it and reinstalling it? I suspect something went wrong with the first install.

**Comment by GhostShot3** [comment]
Worked, thank you

**Comment by nightblade9** [comment]
Just wanted to chime in and say I saw the same problem, with the same resolution.

In my case, I uninstalled several things (.NET Core 2.2.7, .NET Core 3.0, NuGet, Mono) and reinstalled just the .NET Core 3.0. That seemed to resolve the problem.

It looks like VSCode was picking up the MSBuild/etc. from the Mono folder (mine was Mono 6.0 for some reason), but anyway, reinstall for the win.

(I'm on Linux if that matters)

**Comment by MikaelElkiaer** [comment]
I have this problem when starting VSCodium with drun.
Starting VSCodium from zsh and it works as expected.

Can anyone explain what the different in these two methods could be? Something related to paths I imagine.

**Comment by newVincentFong** [comment]
# Environment
* .NET Core SDK `3.1`
* VSCode C# Extension `1.21.9`
* Mac
# Reference
[OmniSharp/omnisharp-vscode](https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshooting:-'The-.NET-Core-SDK-cannot-be-located.'-errors) Wiki

`If you had Visual Studio Code open at the time you installed the .NET SDK, and you haven't restarted it, you should do so.`
# My Solution
Exit VSCode and open it...
# Reason
I try not to exit vscode on my mac when it's connected to a monitor because vscode has some 
GPU rendering problem in this circumstances. This habbit leads to the problems.

**Comment by twoco** [comment]
In my case solved by adding the enviroment variable:

```text
DOTNET_ROOT=C:\Program Files\dotnet\
```

In the `PATH` variable it seems that the path is already set to `C:\Program Files\dotnet\` by the setup. But check it.

**Comment by agawasare** [comment]
Please see https://dotnetresolutions.wordpress.com/2020/05/21/making-net-core-binaries-work-with-visual-studio-code

**Comment by JoeRobich** [comment]
Also note, if you are installing .net sdk on a platform where we do not provide an installer or where you want to automate the installation. The dotnet-install script should configure everything necessary. https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script

**Comment by JackTiber** [comment]
This issue pops up on Ubuntu 20.04 following both links above, when installing using APT, snap or the script cited. I can run `which dotnet` and verify the sdk binary is in PATH, but when opening vs code from the same terminal session using `code .` it still throws the errors around the missing SDK.

**Comment by gregg-miskelly** [comment]
@JackTiber In case you haven't already read this: https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshooting:-'The-.NET-Core-SDK-cannot-be-located.'-errors

This issue isn't a problem with this extension -- this is either a problem with VS Code, or with your shell. There is instructions in there on debugging VS Code if you are so inclined.

**Comment by JackTiber** [comment]
@gregg-miskelly thanks for the link! So oddly, that did help with VS Code popup regarding a missing SDK, but then in the actual output logs of the Omnisharp plugin's language server, it still fails to find an SDK binary to use. Originally, I had the sdk installed via APT, but most recently used SNAP to see if that worked.

At this point, I am going to do a full wipe of the machine and start from scratch, to also support  a couple of hardware updates I am making. Will check back in either way, but definitely a lot of issues installing it on LTS versions of Ubuntu.

**Comment by Cabola** [comment]
If there's still people having this issue then try this:

1. From start menu search for "this pc", right click and select properties.
2. Click Advanced system settings
3. Click on "Environment Variables..."
4. Select either the Users or Systems "Path" variable and click Edit...
5. In either of them you should find the path to your "dotnet" folder

now in my case I had 2 `C:\Program Files (x86)\dotnet\` and `C:\Program Files\dotnet\` if you actually go to the folders you'll notice that there's no sdk folder within the `C:\Program Files (x86)\dotnet\` folder. So simply select `C:\Program Files\dotnet\` and click the "move up" button. Then click OK all the way out of there, now try and see if things are working..

**Comment by visuallization** [comment]
I basically just had to restart my pc after installing the .NET sdk. Then it all worked! I guess some changes (env variables?) needed a reboot.

**Comment by Drexlin** [comment]
@JackTiber Where you able to solve your issue? I'm having the same problem and wondering if going nuclear is my only option at this point. Thanks.

**Comment by JackTiber** [comment]
@Drexlin I did. At the end of the day, the best method I found was to remove any trace of the SDK (snap especially which can have even more issues than installing via APT in the docs) and then re-installing using APT. Once it is installed, verify that you can get the binary on your path with `which dotnet`, but do not try to use it yet. Restart your machine, which I recommend actually shutting down completely and then bringing it back up. At that point, it started working for me.

The link @gregg-miskelly provided is pretty helpful in detailing the troubleshooting steps. 

Honestly, if I had to guess this probably has something to do with where the binary is installed on Debian based systems and the spawned shell for the extension / VS Code, which is somehow why the restart makes a difference. Some environment variable that isn't set after installation is probably set during startup and fixes the issue. Recently worked with a Fedora 32 machine and had all of 0 problems getting the SDK installed and working with the extension and code.

**Comment by Drexlin** [comment]
@JackTiber Thanks, I will try that. If I can't get it to work, maybe I'll give CentOS a try.

**Comment by gp200918** [comment]
@Drexlin @JackTiber 

I had mentioned this post already [here](https://github.com/dotnet/sdk/issues/10403#issuecomment-694782843) and [here](https://github.com/OmniSharp/omnisharp-vscode/pull/3508#issuecomment-694786180).
But @gregg-miskelly does not seem to care and does not update the documentation.


On Ubuntu 20.04.1, the problem is the snap alias. Do not install it.

Instead do this:

sudo snap install dotnet-sdk --channel=5.0/beta --classic

DO NOT install the alias because it makes Omnisharp not find the SDK.
sudo snap alias dotnet-sdk.dotnet dotnet

It can be removed with:
sudo snap unalias dotnet

Start VSCode with a script file with this content:
export PATH=$PATH:/snap/dotnet-sdk/current/
/home/XXX/Downloads/VSCode/code-insiders

You have to adapt the second line, that starts VSCode insiders, to your case.

**Comment by sophin123** [comment]
I was having the same problem. I changed the path of dotnet from the environment variables. After that, i restart the visual studio it works,
To do that,
Open My Computer
Right Click and go to properties
Go to Advanced System Properties
Go to Environment Variables
Find the path and select edit
Add  new path if not exist,
C:\Program FIles\dotnet
If it's already their, then it might be other problems.

**Comment by radiantone** [comment]
On linux, I have dotnet in my path and in common path /usr/bin/dotnet and the extension cannot find it.

**Comment by mayconvs** [comment]
Cara, uso Windows... No meu, lá nas Variáveis de Ambiente, por algum motivo estava vindo um ";" no inicio do diretório do dotnet... Retirei, reiniciei o Visual S. C. e funcionou.

**Comment by ozgurtezel89** [comment]
I had to uninstall the dotnet-sdk (5.0), which I had previously installed via snap
Then I have installed it again with the below command, and it worked for me.
`sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-5.0`

**Comment by random-pixels** [comment]
This morning my VSCode updated (on Linux Mint 21). When it updated, several packages were updated also including the SDK. (I am using apt, not snap). After opening VSCode, the command `dotnet build` no longer works. I see an error that there is no SDK installed. `dotnet --info` confirms that it doesn't think there is an SDK. I uninstalled and reinstalled the `dotnet-sdk-6.0` package, restarted my computer, but still get the error. The link provided above did not offer any solutions. It worked fine yesterday before the update. I now have 1.70.1, released yesterday. Starting from command line or menu makes no difference.

How do I get VSCode to recognize the SDK? Or, if I have to, roll back the update?

**Comment by irvanherz** [comment]
For me, in linux system, moving these variables from `.bashrc` to `/etc/profile` can solve the problem.
```
export DOTNET_ROOT=$HOME/.dotnet
export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools
```
It looks like vscode doesn't load variables from `.bashrc`

**Comment by mikeyjoel** [comment]
For anyone running into issues, do the following instead of installing via your package manager:

If you run into dependencies issues, please check your distribution required dependencies here: 
https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#dependencies
https://github.com/dotnet/core/blob/main/release-notes/8.0/linux-packages.md

`sh -c "$(curl -fsSL https://dot.net/v1/dotnet-install.sh)"`
Follow the prompts until the installation is complete. This will be installed on your home path.

Now, depending on where your are using zsh or bash, you will add an alias instead of an export so that vscode can call the dotnet:

Check which shell you have active
`echo $SHELL`

BASH
```
code .bashrc
# Append line
alias dotnet="$HOME/.dotnet/dotnet"
# Save file and source it
source .bashrc
```

ZSH
```
code .zshrc
# Append line
alias dotnet="$HOME/.dotnet/dotnet"
# Save file and source it
source .zshrc
```


**.Net Uninstall Tool**
If you are like me and have to manage various versions of .Net, you will want to have the uninstall tool, it will make it easier to manage versions not wanted in the future.

https://github.com/dotnet/cli-lab/releases

**Comment by tensorflow-serving** [comment]
Glance at this reply https://stackdev.space/questions/how-can-a-net-program-read-files-in-linux
