### ISSUE TITLE
Omnisharp not working on Mac

### ISSUE THREAD

**Issue by gerjandev** [OmniSharp/omnisharp-vscode#3407]
After installing all new versions (.NET Core, Mono, VS Code, Blazor template), omnisharp does not work anymore.

## Logs ##

![image](https://user-images.githubusercontent.com/7427231/68899975-24c77780-0733-11ea-925b-9e67e5fda15a.png)

### OmniSharp log ###
<details>
Starting OmniSharp server at 11/14/2019, 10:59:46 PM
    Target: /Users/gerjan/Development/BlazorPortfolio

OmniSharp server started with Mono 6.4.0.
    Path: /Users/gerjan/.vscode/extensions/ms-vscode.csharp-1.21.7/.omnisharp/1.34.7/omnisharp/OmniSharp.exe
    PID: 81837

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.15.1 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.3 - "/usr/local/Cellar/mono/6.4.0.198/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.3 - "/Users/gerjan/.vscode/extensions/ms-vscode.csharp-1.21.7/.omnisharp/1.34.7/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.3 - "/usr/local/Cellar/mono/6.4.0.198/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /Users/gerjan/.vscode/extensions/ms-vscode.csharp-1.21.7/.omnisharp/1.34.7/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/gerjan/Development/BlazorPortfolio'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/gerjan/Development/BlazorPortfolio'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/gerjan/Development/BlazorPortfolio/BlazorPortfolio.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/gerjan/Development/BlazorPortfolio'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/gerjan/Development/BlazorPortfolio/BlazorPortfolio.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/gerjan/Development/BlazorPortfolio' on host 81814.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/gerjan/Development/BlazorPortfolio/BlazorPortfolio.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/gerjan/Development/BlazorPortfolio/BlazorPortfolio.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: BlazorPortfolio
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        BlazorPortfolio: Did not find 'Microsoft.NETCore.App' in lock file.

</details>

### C# log ###
<details>This one is empty</details>

## Environment information ##

**VSCode version**: 1.40.1
**C# Extension**: 1.21.7

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.4.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview3-014645
 Commit:    b32d27f4b3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.100-preview3-014645/

Host (useful for support):
  Version: 3.1.0-preview3.19553.2
  Commit:  13f35c3d86

.NET Core SDKs installed:
  3.1.100-preview3-014645 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0-preview3.19555.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0-preview3.19553.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer-2|CoenraadS|0.0.28|
|csharp|ms-vscode|1.21.7|
|haskelly|UCL|0.5.5|
|Ionide-FAKE|Ionide|1.2.3|
|Ionide-fsharp|Ionide|4.3.1|
|Ionide-Paket|Ionide|1.12.0|
|language-haskell|justusadam|2.6.0|
|material-icon-theme|PKief|3.9.1|
|Material-theme|zhuangtongfa|2.28.3|
|nord-visual-studio-code|arcticicestudio|0.12.0|
|python|ms-python|2019.10.44104|
|rest-client|humao|0.22.2|
|rust|rust-lang|0.7.0|
|theme-dracula|dracula-theme|2.18.1|
|Theme-MaterialKit|ms-vscode|0.1.4|
|vscode-icons|vscode-icons-team|9.5.0|
|vscode-theme-onedark|akamud|2.1.0|
|vsliveshare|ms-vsliveshare|1.0.1245|;

</details>

**Comment by gerjandev** [comment]
![image](https://user-images.githubusercontent.com/7427231/68900531-54c34a80-0734-11ea-8e0d-79bf38703b02.png)

**Comment by gerjandev** [comment]
One error that stands out:

```
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
BlazorPortfolio: Did not find 'Microsoft.NETCore.App' in lock file.
```

**Comment by gerjandev** [comment]
Looks similar to #3314

**Comment by gerjandev** [comment]
I have installed mono with brew

`brew install mono`
`mono --version`

gives

```
Mono JIT compiler version 6.4.0.198 (tarball Mon Sep 30 16:34:14 BST 2019)
```

and `msbuild `

```
Microsoft (R) Build Engine version 16.1.85+gad9c9926a7 for Mono
```

**Comment by gerjandev** [comment]
After uninstalling mono with brew (`brew uninstall mono`), and installing it via https://www.mono-project.com/download/stable/, everything works.

`mono --version`
```
Mono JIT compiler version 6.4.0.198 (2019-06/fe64a4765e6 Wed Sep 18 14:14:51 EDT 2019)
```

`msbuild`
```
Microsoft (R) Build Engine version 16.3.0-ci for Mono
```

**Comment by gerjandev** [comment]
So the problem is (I think), mono via brew ships an older version of msbuild (16.1 vs 16.3)

**Comment by JoeRobich** [comment]
Hi @gerjandev,

Glad things are working for you now. We definitely prefer the mono installer over a brew install.

-Joey
