### ISSUE TITLE
Infinite DateTime Tree When debuging simple program.

### ISSUE THREAD

**Issue by dyzav** [OmniSharp/omnisharp-vscode#3418]
VSCode Version: 1.40
OS Version: LXQt 0.14.1
C# extension Version: 1.21.7
Steps to Reproduce:
1.Net Core 101 from microsoft learn program.
2.Debug on working program
3.Expand DateTime on Transactions.
4.Then Expand DateTime inside and so on.
 ![dotnetDateIssue](https://user-images.githubusercontent.com/25512886/69344146-cd5f6500-0c66-11ea-81c1-86cbc91a66a9.png)

**Comment by gregg-miskelly** [comment]
Hi @dyzav this is expected - all DateTime objects have a property called `Date` which is of type `DateTime`. So you are free to expand them forever.
