### ISSUE TITLE
[1.12.8 / macOS] OmniSharp.MSBuild.ProjectLoader - Unable to create directory "/Debug/"

### ISSUE THREAD

**Issue by bitinn** [OmniSharp/omnisharp-vscode#3423]
## Issue Description ##

```
[warn]: OmniSharp.MSBuild.ProjectLoader
        Unable to create directory "/Debug/". Access to the path "/Debug/" is denied.
[warn]: OmniSharp.MSBuild.ProjectLoader
        Could not write state file "/Debug/Assembly-CSharp.csprojAssemblyReference.cache". Could not find a part of the path "/Debug/Assembly-CSharp.csprojAssemblyReference.cache".
...
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly '/Users/df/git/experiment/Temp/bin/Debug/Assembly-CSharp-Editor-firstpass.dll'
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly '/Users/df/git/experiment/Temp/bin/Debug/Assembly-CSharp.dll'

```

## Steps to Reproduce ##

- Omnisharp: Select Project
- Issue reproduced on all my Unity projects, even the ones that were working.
- I do no see any file permission issues in my working folder

### OmniSharp log ###

```
[warn]: OmniSharp.MSBuild.ProjectLoader
        Unable to create directory "/Debug/". Access to the path "/Debug/" is denied.
[warn]: OmniSharp.MSBuild.ProjectLoader
        Could not write state file "/Debug/Assembly-CSharp.csprojAssemblyReference.cache". Could not find a part of the path "/Debug/Assembly-CSharp.csprojAssemblyReference.cache".
...
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly '/Users/df/git/experiment/Temp/bin/Debug/Assembly-CSharp-Editor-firstpass.dll'
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly '/Users/df/git/experiment/Temp/bin/Debug/Assembly-CSharp.dll'

```

### C# log ###

No output

## Environment information ##

**VSCode version**: 1.40.1
**C# Extension**: 1.21.8

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.18.1</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.105/

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.2.105 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|applescript|idleberg|0.18.1|
|cpptools|ms-vscode|0.26.1|
|csharp|ms-vscode|1.21.8|
|mel|sator-imaging|0.1.2|
|python|ms-python|2019.10.44104|
|shader|slevesque|1.1.4|
|unity-debug|Unity|2.7.2|
|vscode-jade-snippets|mrmlnc|1.0.1|;

</details>

**Comment by cartermp** [comment]
@bitinn Thanks for reporting. Does this reproduce for you with the latest plugin?

OmniSharp and this plugin don't require anything specific with respect to permissions. However, it could be the case that your project's folder was created with different permissions, and you're seeing an issue related to that when used with user-level permissions.

**Comment by cartermp** [comment]
Closing out as no additional info was added.
