### ISSUE TITLE
Missing intellisense / autocomplete for POCO

### ISSUE THREAD

**Issue by rsouthgate** [OmniSharp/omnisharp-vscode#3424]
## Issue Description ##

When referencing a poco without a constructor in Code there is no auto-suggested value. In Visual Studio it will prompt for the class name just as other classes.

## Steps to Reproduce ##

Create a Plain constructorless class.
Try and reference it from another class

Now add an empty constructor to the class and it will start appearing in suggestions.

## Expected Behavior ##

I would expect to be able to type the first few letters and get this class name in a list like as normal.

## Actual Behavior ##

No prompt

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.40.1
**C# Extension**: 1.21.7

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.16.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.106
 Commit:    aa79b139a8

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.106/

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.403 [/usr/local/share/dotnet/sdk]
  2.2.102 [/usr/local/share/dotnet/sdk]
  2.2.106 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|atlascode|atlassian|2.1.5|
|code-coverage|markis|1.1.0|
|csharp|ms-vscode|1.21.7|
|debugger-for-chrome|msjsdiag|4.12.1|
|docker-explorer|formulahendry|0.1.6|
|dotnet-test-explorer|formulahendry|0.7.1|
|ginfuru-vscode-jekyll-syntax|ginfuru|0.1.0|
|gitlens|eamodio|10.2.0|
|java|redhat|0.53.1|
|language-liquid|neilding|0.1.1|
|mssql|ms-mssql|1.7.1|
|php-debug|felixfbecker|1.13.0|
|powershell|ms-vscode|2019.11.0|
|propertylist|zhouronghui|0.0.2|
|python|ms-python|2019.10.44104|
|vscode-commitizen|KnisterPeter|0.8.4|
|vscode-docker|ms-azuretools|0.8.2|
|vscode-eslint|dbaeumer|1.9.1|
|vscode-extension-auto-import|moppitz|1.3.3|
|vscode-intelephense-client|bmewburn|1.2.3|
|vscode-java-debug|vscjava|0.23.0|
|vscode-java-dependency|vscjava|0.6.0|
|vscode-java-pack|vscjava|0.8.0|
|vscode-java-test|vscjava|0.21.0|
|vscode-jekyll-snippets|ginfuru|0.9.1|
|vscode-jest-test-adapter|rtbenfield|0.2.0|
|vscode-maven|vscjava|0.19.1|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-react-native|msjsdiag|0.13.1|
|vscode-solution-explorer|fernandoescolar|0.3.5|
|vscode-styled-components|jpoissonnier|0.0.27|
|vscode-test-explorer|hbenl|2.14.6|
|vscode-todo-highlight|wayou|1.0.4|
|vscode-yaml|redhat|0.6.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.0|;

</details>

**Comment by cyberyaga** [comment]
I can confirm this is also happening in Linux as well... It stopped working on the last update.

**Comment by cyberyaga** [comment]
I have a small update... 

I looked at the Omnisharp log, and saw that it had no reference to one of my projects. To give you some background, I have two projects in a workspace. The MainBlazorProject (Blazor server side) references the BlazorGoogleMaps project via a ProjectReference line in the csproj file:

- BlazorGoogleMaps
- MainBlazorProject

Both of these project compile without any issues. So, I opened the MainBlazorProject by itself. I notice that this problem goes away. I am able to reference my POCOs, intellisense works and I can (F12) to the class as expected.

If I open the workspace with the two projects, the log displays as shown above, and Omnisharp just doesn't do anything with the main project.

Hope this helps.

**Comment by filipw** [comment]
are you able to provide the project that reproduces this issue?

**Comment by cartermp** [comment]
@rsouthgate could you share a repro of this with the latest plugin version? Trying this with a new console app does not reproduce; a constructorless POCO is shown in IntelliSense when typing the first few characters of it.

**Comment by cartermp** [comment]
Closing out as no additional info was added.
