### ISSUE TITLE
Improve error message when the C# extension is run on unsupported processors

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#3425]
## Steps to reproduce
Configure VS Code to remotely connect to an ARM device using VS Code extension remoting.

## Expected  behavior
Either the extension should work, or it should fail telling users to use the C# extension locally and remote debug.

## Actual behavior
Extension doesn't work, and doesn't provide a good error message.

**Comment by cartermp** [comment]
Thanks @WardenGnaw for the PR, we'll see if we can get this in
