### ISSUE TITLE
"Installing packages..." stays in the status bar after installing OmniSharp and its dependencies

### ISSUE THREAD

**Issue by SalvatoreMeschini** [OmniSharp/omnisharp-vscode#3428]
This is a follow-up of https://github.com/microsoft/vscode/issues/85584 

## Issue Description ##
- VSCode Version: 1.40.1
- OS Version: Windows 10, Version 1903 (OS Build 18362.476)

Steps to Reproduce:

1. I opened a .cs file and Visual Studio Code started downloading the C# dependencies 
2. Despite the fact that the installation process finished (?), the status bar is stuck with "Installing packages...". Hovering that item, it displays the following tooltip: Installing package 'Razor Language Server (Windows / x64).

![Installing packages](https://user-images.githubusercontent.com/11814081/69608621-2133ca80-1028-11ea-9b04-7cb45a3914b8.png)

Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (32059 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'

Downloading package '.NET Core Debugger (Windows / x64)' (47489 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (Windows / x64)'

Downloading package 'Razor Language Server (Windows / x64)' (50372 KB).................... Done!
Installing package 'Razor Language Server (Windows / x64)'

Finished

## Expected Behavior ##
"Installing packages..." should disappear when the installation finishes.

## Actual Behavior ##
It stays there in the status bar, despite the fact that the installation is over. 

## Environment information ##

**VSCode version**: 1.40.1
**C# Extension**: 1.21.8

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.204 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Angular-BeastCode|Mikael|8.1.2|
|angular-bootstrap|herrherrmann|4.0.9|
|angular-essentials|johnpapa|0.6.3|
|Angular1|johnpapa|0.2.1|
|angular1-code-snippets|alexandersage|0.0.3|
|Angular2|johnpapa|8.2.0|
|angular2-inline|natewallace|0.0.17|
|angular2-snippets|danwahlin|1.0.21|
|auto-close-tag|formulahendry|0.5.6|
|auto-rename-tag|formulahendry|0.1.1|
|autoimport|steoates|1.5.3|
|autorest|ms-vscode|2.0.1|
|beautify|HookyQR|1.5.0|
|Bookmarks|alefragnani|10.6.0|
|bootstrap-3-snippets|wcwhitehead|0.1.0|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|change-case|wmaurer|1.0.0|
|ci-snippets|secato|0.0.2|
|code-runner|formulahendry|0.9.15|
|code-settings-sync|Shan|3.4.3|
|color-highlight|naumovs|2.3.0|
|color-info|bierner|0.5.1|
|cpptools|ms-vscode|0.26.1|
|crane|HvyIndustries|0.3.8|
|csharp|ms-vscode|1.21.8|
|csharpextensions|jchannon|1.3.1|
|csharpfixformat|Leopotam|0.0.84|
|debugger-for-chrome|msjsdiag|4.12.1|
|EditorConfig|EditorConfig|0.14.2|
|eml|leighlondon|0.3.2|
|gc-excelviewer|GrapeCity|2.1.32|
|highlight-matching-tag|vincaslt|0.9.5|
|highlight-words|rsbondi|0.1.4|
|html-snippets|abusaidm|0.2.1|
|html5-boilerplate|sidthesloth|1.0.3|
|HTMLHint|mkaufman|0.6.0|
|JavaScriptSnippets|xabikos|1.7.2|
|jshint|dbaeumer|0.10.21|
|json-to-ts|MariusAlchimavicius|1.5.5|
|json-tools|eriklynd|1.0.2|
|json2csv|khaeransori|0.0.1|
|json2ts|GregorBiswanger|0.0.6|
|lintlens|ghmcadams|2.7.0|
|material-icon-theme|PKief|3.9.2|
|material-palenight-theme|whizkydee|1.9.7|
|mssql|ms-mssql|1.7.1|
|nativescript-ng2-snippets|wwwalkerrun|2.0.1|
|ng-template|Angular|0.900.0|
|npm-intellisense|christian-kohler|1.3.0|
|output-colorizer|IBM|0.1.2|
|pascal-formatter|alefragnani|2.2.0|
|pascal-language-basics|AnsonYeung|0.1.8|
|path-intellisense|christian-kohler|1.4.2|
|php-ci|small|0.3.3|
|php-debug|felixfbecker|1.13.0|
|php-intellisense|felixfbecker|2.3.13|
|php-symbols|linyang95|2.1.0|
|powershell|ms-vscode|2019.11.0|
|prettier-vscode|esbenp|3.9.0|
|prettify-json|mohsen1|0.0.3|
|project-manager|alefragnani|10.9.1|
|python|ms-python|2019.11.50794|
|qub-xml-vscode|qub|1.2.8|
|quicktype|quicktype|12.0.46|
|rainbow-csv|mechatroner|1.3.1|
|regex|chrmarti|0.2.0|
|remote-wsl|ms-vscode-remote|0.40.3|
|seito-openfile|Fr43nk|1.8.5|
|sepaswitch|Futureglobe|1.0.2|
|slncode|bigonazzi|0.2.1|
|sort-lines|Tyriar|1.9.0|
|sort-typescript-imports|miclo|1.4.1|
|stack-trace-formatter|RadwanFaci|1.0.6|
|stuck-overflow|dgerrard|0.2.1|
|team|ms-vsts|1.161.0|
|theme-darker-monokai|Salvatore Meschini|1.0.0|
|theme-darktooth|Poorchop|0.0.2|
|theme-dracula|dracula-theme|2.18.1|
|theme-dracula-at-night|bceskavich|2.6.0|
|theme-hop-light|bubersson|0.0.4|
|theme-material-theme|jprestidge|1.0.1|
|Theme-monokai-best|gerane|0.0.5|
|transformer|dakara|1.6.0|
|tsimporter|pmneo|2.0.1|
|tslint|eg2|1.0.44|
|tsqllint|tsqllint|1.2.0|
|vetur|octref|0.22.6|
|vs-code-xml-format|fabianlauer|0.1.5|
|vscode-caniuse|agauniyal|0.5.0|
|vscode-color|anseki|0.4.5|
|vscode-css-peek|pranaygp|3.0.2|
|vscode-edit-csv|janisdd|0.2.5|
|vscode-eslint|dbaeumer|1.9.1|
|vscode-essentials-snippets|robertoachar|2.0.0|
|vscode-generate-getter-setter|DSKWRK|0.5.0|
|vscode-great-icons|emmanuelbeziat|2.1.47|
|vscode-hexdump|slevesque|1.7.2|
|vscode-html-css|ecmel|0.2.3|
|vscode-icons|vscode-icons-team|9.6.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|vscode-language-pack-it|MS-CEINTL|1.40.2|
|vscode-markdownlint|DavidAnson|0.32.0|
|vscode-npm-script|eg2|0.3.9|
|vscode-phpfmt|kokororin|1.0.30|
|vscode-random|jrebocho|1.6.1|
|vscode-solution-explorer|fernandoescolar|0.3.5|
|vscode-sort-json|richie5um2|1.18.0|
|vscode-status-bar-format-toggle|tombonnike|2.0.0|
|vscode-todo-highlight|wayou|1.0.4|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|
|vscode-yaml|redhat|0.6.1|
|vue-peek|dariofuzinato|1.0.2|
|vue-snippets|hollowtree|0.1.11|
|vue-vscode-snippets|sdras|1.8.0|
|vuejs-extension-pack|mubaidr|1.1.5|
|winteriscoming|johnpapa|1.3.0|
|xml|DotJoshJohnson|2.5.0|
|xml-format|mikeburgh|1.0.2|
|xml2json|buianhthang|1.2.2|
|yo|samverschueren|0.9.3|;

</details>

**Comment by SalvatoreMeschini** [comment]
Same behaviour of a different PC running on Windows 10 build 1909 and Visual Studio Code 1.40.2:

![Immagine](https://user-images.githubusercontent.com/11814081/69755003-889c6800-1157-11ea-8727-5b004cbeb349.png)

**Comment by JoeRobich** [comment]
When this happened did OmniSharp actually startup and provide language services? I would have expected the statusbar to update when OmniSharp started.

**Comment by cartermp** [comment]
@SalvatoreMeschini Do you still see this? If so, do you have mulitple VSCode windows open? The issue could be that one is installing dependencies but the other isn't and there's something odd going on here.

**Comment by SalvatoreMeschini** [comment]
@cartermp Unfortunately yes, I just:

1. Uninstalled the extension
2. Closed and re-opened Visual Studio Code (now updated to 1.43.2)
3) Re-installed the extension
4) Left Visual Studio Code open for about 1 hour (waiting for that message to disappear)

but it's still there:

![2020-04-08 09_46_01-Window](https://user-images.githubusercontent.com/11814081/78758245-1b5ad800-797e-11ea-8c71-8dec4ecd7b4e.png)

I use only 1 instance of Visual Studio Code, no more than 1 VSCode window open.

The only way to get rid of that message is closing&re-opening VSCode.
It looks like just a cosmetic issue.

**Comment by cartermp** [comment]
Thanks for confirming @SalvatoreMeschini
