### ISSUE TITLE
How to use vscode intillisense for the razor templates with the c# extension and remote development

### ISSUE THREAD

**Issue by lgund** [OmniSharp/omnisharp-vscode#3430]
Decription
=====================
I want to use Visual Studio Code (Version 1.40.2) to develop a dotnet mvc app on my VServer. To realize that I am using the full package of the Remote Development (Version 0.17.0) and the C# (Version 1-21-8) extension. The remote connection works very well and in all C# (.cs) files I´ve also my intellisense. But if I open a razor (.cshtml) page I dont have any intellisense.

I am looking for a solution for 2 weeks now but I can´t find a solution. Did anyone had the same problem and can help me here?

Full list of installed packages
=====================

 - ASP.NET Core Switcher 1.0.4
 - ASP.NET Helper 0.6.4
 - Auto-Using for C# 0.7.9
 - C# 1.21.8
 - Class autocomplete 0.1.0
 - Remote Development 0.17.0 (with Remove - SSH, Remote - Containers...)

Server system
============
 - Linux CentOS 7
 - dotnet 3.0.100
 - mono 6.6.0.157

Example Picture
=====================
Thats how my razor template look like now

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/1W9Rs.png

**Comment by NTaylorMullen** [comment]
@lgund having remote development support is definitely on our radar but it's not something we've done yet for Razor files. We're tracking that work over here if you want to share your interest/track its progress: https://github.com/aspnet/AspNetCore/issues/14331
