### ISSUE TITLE
XML comments do not show up for the array operator

### ISSUE THREAD

**Issue by aaronfranke** [OmniSharp/omnisharp-vscode#3434]
## Issue Description ##

It seems that XML comments placed on the array operator do not ever show up outside of the source file. The summary shows up when hovering over "this" and parameters in the source file, but not the generated file, and not when it's used.

## Steps to Reproduce ##

Source:
```cs
        /// <summary>
        /// Access matrix elements.
        /// </summary>
        /// <param name="column">The column.</param>
        /// <param name="row">The row.</param>
        public float this[int column, int row] // not shown: the body of this operator
```
Generated "[metadata] File.cs" from "Go to Definition":
```cs
        //
        // Summary:
        //     Access matrix elements.
        //
        // Parameters:
        //   column:
        //     The column.
        //
        //   row:
        //     The row.
        public float this[int column, int row] { get; set; }
```

## Expected Behavior ##

With methods, fields, and classes, if there's a summary, you can hover over them to view it, and it shows up in the intellisense context menu when you are writing code. I would expect to be able to do the same with the array operator.

I can tell that the XML summary is recognized by C# itself in Mono 6.4 because it shows up in the "[metadata]" as shown above, and shows up when viewing the source file with VS Code and this extension and hovering. 

## Actual Behavior ##

For this code snippet, where `b` is an instance of the structure with the above operator:

```cs
b[0, 0] = 5.0f;
```

Nothing shows up when writing code, and I am not able to hover over the `[]` to see the summary, nor can I hover over the numbers to view the parameter documentation.

The only way to see the summary is if you hover over the word `this` in the source file, which is hardly useful since the summary is right there already anyway. Likewise for the parameters.

### OmniSharp log ###
<details>
Starting OmniSharp server at 11/29/2019, 1:40:39 AM
    Target: /home/aaronfranke/workspace/TestingGodot/TestingGodot.sln

OmniSharp server started with Mono 6.4.0.
    Path: /home/aaronfranke/.vscode/extensions/ms-vscode.csharp-1.21.8/.omnisharp/1.34.8/omnisharp/OmniSharp.exe
    PID: 10382

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 18.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.3 - "/usr/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.3 - "/home/aaronfranke/.vscode/extensions/ms-vscode.csharp-1.21.8/.omnisharp/1.34.8/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.3 - "/usr/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /home/aaronfranke/.vscode/extensions/ms-vscode.csharp-1.21.8/.omnisharp/1.34.8/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/aaronfranke/workspace/TestingGodot'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/aaronfranke/workspace/TestingGodot/TestingGodot.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/aaronfranke/workspace/TestingGodot/TestingGodot.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/aaronfranke/workspace/TestingGodot'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/aaronfranke/workspace/TestingGodot/TestingGodot.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/aaronfranke/workspace/TestingGodot' on host 10273.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/aaronfranke/workspace/TestingGodot/TestingGodot.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/aaronfranke/workspace/TestingGodot/TestingGodot.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: TestingGodot
</details>

### C# log ###
The log was empty.

## Environment information ##

**VSCode version**: 1.40.1
**C# Extension**: 1.21.8

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.4.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.402
 Commit:    c7f2f96116

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.402/

Host (useful for support):
  Version: 2.2.8
  Commit:  b9aa1abc51

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.26.1|
|csharp|ms-vscode|1.21.8|
|discord-vscode|icrawl|3.13.0|
|docomment|k--kato|0.1.8|
|file-icons|file-icons|1.0.19|
|flow-for-vscode|flowtype|1.5.0|
|godot-tools|geequlim|0.3.7|
|jbockle-format-files|jbockle|3.0.0|
|prettier-vscode|esbenp|3.11.0|
|python|ms-python|2019.11.50794|
|rst-vscode|tht13|3.0.1|
|unity-debug|Unity|2.7.2|
|unity-tools|Tobiah|1.1.1|
|vscode-eslint|dbaeumer|1.9.1|
|vscode-intelephense-client|bmewburn|1.2.3|
|vscode-rust|kalitaalexey|0.4.2|
|vsliveshare|ms-vsliveshare|1.0.1293|;

</details>

**Comment by cartermp** [comment]
Thanks for the suggestion. Could you file this issue here? https://github.com/dotnet/roslyn

This would be a core language tooling suggestion because it does not work in VS either.
