### ISSUE TITLE
OmniSharp.MSBuild.ProjectManager, Attemped to update project that is not loaded

### ISSUE THREAD

**Issue by notslimboy** [OmniSharp/omnisharp-vscode#3435]
## Environment data
E:\GitLab\get-the-key\Get The Key>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.402     
 Commit:    c7f2f96116  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.18362
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.402\

Host (useful for support):
  Version: 2.2.7
  Commit:  b1e29ae826

.NET Core SDKs installed:
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

## Steps to reproduce
Omnisharp its update itself

## Expected  behavior
Project to be working

## Actual behavior
OmniSharp Log

Starting OmniSharp server at 11/29/2019, 11:31:46 PM
    Target: e:\GitLab\get-the-key\Get The Key\Get The Key.sln

OmniSharp server started.
    Path: C:\Users\Raka\.vscode\extensions\ms-vscode.csharp-1.21.7\.omnisharp\1.34.9-beta.10\OmniSharp.exe
    PID: 6228

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2017 15.9.28307.905 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            2: StandAlone 16.3 - "C:\Users\Raka\.vscode\extensions\ms-vscode.csharp-1.21.7\.omnisharp\1.34.9-beta.10\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Users\Raka\.vscode\extensions\ms-vscode.csharp-1.21.7\.omnisharp\1.34.9-beta.10\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.3 - "C:\Users\Raka\.vscode\extensions\ms-vscode.csharp-1.21.7\.omnisharp\1.34.9-beta.10\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Users\Raka\.vscode\extensions\ms-vscode.csharp-1.21.7\.omnisharp\1.34.9-beta.10\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = C:\Users\Raka\.vscode\extensions\ms-vscode.csharp-1.21.7\.omnisharp\1.34.9-beta.10\.msbuild
            MSBuildToolsPath = C:\Users\Raka\.vscode\extensions\ms-vscode.csharp-1.21.7\.omnisharp\1.34.9-beta.10\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'e:\GitLab\get-the-key\Get The Key'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'e:\GitLab\get-the-key\Get The Key\Get The Key.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\GitLab\get-the-key\Get The Key\Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\GitLab\get-the-key\Get The Key\Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'e:\GitLab\get-the-key\Get The Key'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\GitLab\get-the-key\Get The Key\Assembly-CSharp.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'e:\GitLab\get-the-key\Get The Key' on host 20212.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'e:\GitLab\get-the-key\Get The Key\Assembly-CSharp.csproj'.
e:\GitLab\get-the-key\Get The Key\Assembly-CSharp.csproj
C:\Users\Raka\.vscode\extensions\ms-vscode.csharp-1.21.7\.omnisharp\1.34.9-beta.10\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1175,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\GitLab\get-the-key\Get The Key\Assembly-CSharp-Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'e:\GitLab\get-the-key\Get The Key\Assembly-CSharp-Editor.csproj'.
e:\GitLab\get-the-key\Get The Key\Assembly-CSharp-Editor.csproj
C:\Users\Raka\.vscode\extensions\ms-vscode.csharp-1.21.7\.omnisharp\1.34.9-beta.10\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1175,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: e:\GitLab\get-the-key\Get The Key\Assembly-CSharp.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: e:\GitLab\get-the-key\Get The Key\Assembly-CSharp-Editor.csproj

**Comment by filipw** [comment]
as the log mentions, you are trying to run a .NET 4.7.1 project without having the Developer Pack installed

```
The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
```

you can install it here https://dotnet.microsoft.com/download/dotnet-framework/net471
