### ISSUE TITLE
OmniSharp Exception

### ISSUE THREAD

**Issue by coolforest** [OmniSharp/omnisharp-vscode#3436]
Issue Type: <b>Bug</b>

If solution folder name or path include "=", OmniSharp throw an exception.

Please fix it . Thank you.

Extension version: 1.21.8
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.70GB free)|
|Process Argv|C:\Users\Administrator\Desktop\temp\cs|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by filipw** [comment]
Thanks for reporting, this is a bug which will be fixed in https://github.com/OmniSharp/omnisharp-roslyn/pull/1661
