### ISSUE TITLE
.Net Test Log output shows messy code for Chinese characters

### ISSUE THREAD

**Issue by DongchengWang** [OmniSharp/omnisharp-vscode#3437]
## Environment data
`dotnet --info` output:

```
.NET Core SDK（反映任何 global.json）:
 Version:   3.0.100     
 Commit:    04339c3a26  

运行时环境:
 OS Name:     Windows   
 OS Version:  10.0.18362
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

VS Code version: 1.40.2
C# Extension version: 1.21.8

## Steps to reproduce

1. Write a test and cilck run test/debug test
2. Look at .Net Test Log output

## Expected  behavior

shows Chinese characters normally like OmniSharp Log output

## Actual behavior

![image](https://user-images.githubusercontent.com/29004603/70017332-ca953600-15bd-11ea-93d1-a2dbe1efaa0e.png)

I have tried many workarounds but failed.

**Comment by gregg-miskelly** [comment]
I believe the fix here would be in OmniSharp. It needs to either expect the console encoding from the output of the unit test runner, or set the console code path to UTF-8 before spawning the unit test runner process (P/Invoke [`SetConsoleOutputCP(CP_UTF8)`](https://docs.microsoft.com/en-us/windows/console/setconsoleoutputcp) on Windows) or maybe the runner has a way to specify the encoding.

**Comment by heartacker** [comment]
wait for solution

**Comment by filipw** [comment]
this is the same issue as https://github.com/OmniSharp/omnisharp-roslyn/issues/1763
I think we should close this since it's internal Omnisharp server issue

**Comment by DongchengWang** [comment]
Closed since the fix should be in omnisharp-roslyn.

**Comment by wswind** [comment]
Up, same issue.

**Comment by TakiGuan** [comment]
Here is a workable solution to solve this issue if you are using windows. Please check the option "Use Unicode UTF-8 for worldwide language support"

You can see this option by going to Settings and then: All Settings -> Time & Language -> Language -> "Administrative Language Settings"

This is what it looks like:

[![enter image description here](https://i.stack.imgur.com/dv0tU.png)](https://i.stack.imgur.com/dv0tU.png)

Restart the system and then the output view will be fine.
