### ISSUE TITLE
Intellisense not working in C# extension of VS Code

### ISSUE THREAD

**Issue by sshankhdhar** [OmniSharp/omnisharp-vscode#3443]
Intellisense not working in C# extension of VS Code.
Every time I'll have to restart the VS Code and wait.
Sometimes Intellisense works and sometimes not.

**Comment by peterblazejewicz** [comment]
@sshankhdhar 
Could you please provide a log from the Output window for `Omnisharp Log` target from your VSCode? It would help tremendously.
Thanks!

**Comment by sshankhdhar** [comment]
Ho Peter,

Please find attached omnisharp logs.

![0](https://user-images.githubusercontent.com/49192655/70505192-62120000-1b4d-11ea-96e6-84c4364aae46.jpg)

**Comment by benitazz** [comment]
Hi,

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Professional 2019 16.1.29009.5 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"
            2: StandAlone 16.3 - "c:\Users\Ben.Baloyi\.vscode\extensions\ms-vscode.csharp-1.21.8\.omnisharp\1.34.8\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Professional 2019 16.1.29009.5 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Sandbox\NetworkManagerServices'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Skip loading projects listed in solution file or under target directory because MsBuild:LoadProjectsOnDemand is true.
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Sandbox\NetworkManagerServices'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Sandbox\NetworkManagerServices' on host 856.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Sandbox\NetworkManagerServices\NetworkManagerServices.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Sandbox\NetworkManagerServices\NetworkManagerServices.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Sandbox\NetworkManagerServices\NetworkManagerServices.csproj'.
c:\Sandbox\NetworkManagerServices\NetworkManagerServices.csproj
C:\Program Files\dotnet\sdk\2.1.700\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): Error: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Sandbox\NetworkManagerServices\NetworkManagerServices.csproj

**Comment by sshankhdhar** [comment]
Hi,

Mentioned path not found.
Below is the screenshot.

[cid:d8ae9876-7401-434b-adf3-f7d1d153356b]


________________________________

**Comment by JoeRobich** [comment]
@benitazz It appears your project is targeting .NET Core 3.1 but you are trying to run against .NET Core 2.1. Try running `dotnet --info` and installing the .NET Core 3.1 SDK if it isn't already.

**Comment by JoeRobich** [comment]
@sshankhdhar I see that OmniSharp is trying to run against the minimal MSBuild that we deploy with. This MSBuild wouldn't necessarily support all project types.

You can try installing the VS2019 Build Tools from https://visualstudio.microsoft.com/downloads/. Expand 'Tools for Visual Studio 2019' and download 'Build Tools for Visual Studio 2019'

**Comment by benitazz** [comment]
I forgot to close the tickect, I figured it out that it was the wrong SDK that was installed on my machine. Thanks for your contribution.

**Comment by benitazz** [comment]
I was able to resolve my issue by installing the correct SDK of .net core

**Comment by cartermp** [comment]
@sshankhdhar Thanks for filing this issue. Are you still seeing this problem? If so, could you share the following information:

* The kind of project(s) you're attempting to use (.NET Framework, .NET Core, how many projects, etc.)
* Any sharable repository

Thanks!

**Comment by cartermp** [comment]
Closing out as no additional info was added.

**Comment by drhhusain** [comment]
I am not getting any intellisense for C# or dotnet project in visual studio code

dotnet version : 3.1.409
visual studio code : 1.56.2 (latest version)

I installed C# extension too.

But program is executing successfully

![dotnet_ex](https://user-images.githubusercontent.com/54940714/120518909-b1a65480-c3ef-11eb-8d5b-74b7c7b37e65.png)

Typing "Console" here says "no suggestion"

![dotnet_ex2](https://user-images.githubusercontent.com/54940714/120519108-e5817a00-c3ef-11eb-90c1-aaac4229655b.png)
