### ISSUE TITLE
Error with nullable ref types with netcoreapp3.1

### ISSUE THREAD

**Issue by dseefeld** [OmniSharp/omnisharp-vscode#3444]
## Issue Description ##
Issues found with nullable ref types when TargetFramework is netcoreapp3.1
## Steps to Reproduce ##
1. Create a new .NET Core console app
2. Add the following code to Program.cs:
```
            string? testString  = "Hi";
            Console.WriteLine(testString);
```
3. Add `<Nullable>enable</Nullable>` to the project file.
4. Build - Note: Builds and runs fine.
5. Open in vscode
6. Build

## Expected Behavior ##
No error shown
## Actual Behavior ##
* Red underline on the "?" with an error: Feature 'nullable reference types' is not available in C# 7.3. Please use language version 8.0 or greater.
* The project is defaulted to netcoreapp3.1.  If I try the same steps, but set the TargetFramework to netcoreapp3.0, there is no issue.
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.40.2
**C# Extension**: 1.21.8

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  3.0.101 [/usr/share/dotnet/sdk]
  3.1.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.8|;

</details>

**Comment by elfaraorigo** [comment]
@dseefeld I was able to get the "red underline" to go away in my netcoreapp3.1 project

In the .csproj I added <LangVersion /> to the <PropertyGroup />
```
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
```
[Configure language version](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version)

Not sure if that is a permanent solution but at least the warning disappeared
Could probably set this to "3.1" also to get the same effect

**Comment by bas-jansen** [comment]
Same error appears using Visual Studio 2019 (16.3.6)

I upgraded my netcoreapp3.0 to netcoreapp3.1
This same error appears at lines like: `var value = null!;`

Adding `<LangVersion>latest</LangVersion>` fixed the issues. Thanks for the suggestion.

**Comment by Benzidrine** [comment]
Same fix worked for me. Happened after upgrade to 3.1. .Net Core is one buggy ecosystem to develop in.

**Comment by filipw** [comment]
if `LangVersion` is not found, then OmniSharp will use default language version which is C# 8.0.
if you encounter this problem, it could be that something else (i.e. Directory.Build.props file) is resetting the language version to something different or you are using an older version of the extension.

In either case, please submit your OmniSharp log when you encounter this.

**Comment by stijnherreman** [comment]
For me the cause was an outdated Visual Studio installation. 16.4 is required for .NET Core 3.1 and I was on 16.3.9

```
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.3.29509.3 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.3 - "C:\Users\stijn\.vscode\extensions\ms-vscode.csharp-1.21.9\.omnisharp\1.34.9\.msbuild\Current\Bin"
[...]
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.3.29509.3 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[...]
[dbug]: OmniSharp.MSBuild.ProjectSystem
        MSBuild environment: 
Mode: VisualStudio
RunningTests: False
RunningInVisualStudio: False
MSBuildToolsDirectory32: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin
MSBuildToolsDirectory64: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\amd64
MSBuildSDKsPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Sdks
CurrentMSBuildConfigurationFile: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe.config
CurrentMSBuildExePath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
CurrentMSBuildToolsDirectory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin
VisualStudioInstallRootDirectory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
MSBuildExtensionsPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild
```

After updating to 16.4 the `<Nullable>` feature works as expected.
```
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.4.29728.190 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.3 - "C:\Users\stijn\.vscode\extensions\ms-vscode.csharp-1.21.9\.omnisharp\1.34.9\.msbuild\Current\Bin"
[...]
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.4.29728.190 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
```

Without Visual Studio installed, I assume the extension falls back on its internal instance. But the internal instance seems to be running 16.3, even though https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.9 mentions updating to 16.4 on Windows. Likely other users are experiencing this issue due to the outdated internal version.

**Comment by cartermp** [comment]
Thanks for the report. There was a bug in the C# targets in the lead up to the full release of .NET Core 3.1 where the implicit default LangVersion was 7.3 instead of 8.0. This might be the source of the issue. I just tried this with the .NET 5 preview SDK and latest OmniSharp and everything worked as expected. If you don't see this working, please let us know and we can take a look.
