### ISSUE TITLE
dotnet build error: execvp(3) failed.: No such file or directory

### ISSUE THREAD

**Issue by mark-feeney-sage** [OmniSharp/omnisharp-vscode#3447]
## Issue Description ##
When trying to build and debug using C# extension tasks on a mac (Mojave, 10.14.6) I keep getting 
`execvp(3) failed.: No such file or directory` for a `dotnet build` command that runs fine in Terminal.

(Edit)
Note: replacing the `dotnet` command in tasks with `/usr/local/share/dotnet/dotnet` helped work around this, for this mac environment.

## Steps to Reproduce ##
1. Use `dotnet new webapi -n MyService` to create an ASP.NET web API project.
2. Shift + Command + P and run `.NET Generate Assets for Build and Debug`.
3. Shift + Command + P and run `Task: Run Build Task` and `build`.

## Expected Behavior ##
Task to run `dotnet build` successfully.

## Actual Behavior ##
Error:
```
execvp(3) failed.: No such file or directory
The terminal process terminated with exit code: 1
```

### OmniSharp log ###
None.

### C# log ###
None

## Environment information ##

**VSCode version**: 1.40.0
**C# Extension**: 1.21.8

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.0.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.701 [/usr/local/share/dotnet/sdk]
  3.1.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|bash-debug|rogalmic|0.3.6|
|csharp|ms-vscode|1.21.8|
|java|redhat|0.53.1|
|markdown-preview-enhanced|shd101wyy|0.5.0|
|plantuml|jebbs|2.13.5|
|powershell|ms-vscode|2019.11.0|
|python|ms-python|2019.11.50794|
|salesforcedx-vscode|salesforce|47.9.0|
|salesforcedx-vscode-apex|salesforce|47.9.0|
|salesforcedx-vscode-apex-debugger|salesforce|47.9.0|
|salesforcedx-vscode-apex-replay-debugger|salesforce|47.9.0|
|salesforcedx-vscode-core|salesforce|47.9.0|
|salesforcedx-vscode-lightning|salesforce|47.9.0|
|salesforcedx-vscode-lwc|salesforce|47.9.0|
|salesforcedx-vscode-visualforce|salesforce|47.9.0|
|typescript-javascript-grammar|ms-vscode|0.0.53|
|vscode-eslint|dbaeumer|1.9.1|
|vscode-java-debug|vscjava|0.23.0|
|vscode-java-dependency|vscjava|0.6.0|
|vscode-java-pack|vscjava|0.8.1|
|vscode-java-test|vscjava|0.21.0|
|vscode-maven|vscjava|0.20.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.0|;

</details>

**Comment by gregg-miskelly** [comment]
@mark-feeney-sage this isn't a problem with this extension. I believe what is going on is that VS Code isn't able to scrape your shell configuration files to figure out what the PATH should be, and so `dotnet` cannot be found. You may want to reopen your issue in the [VS Code repo](https://github.com/microsoft/vscode/issues). Alternatively, if you want to debug it yourself, I **think** this is VS Code's code for scraping the environment: [getUnixShellEnvironment](https://github.com/microsoft/vscode/search?q=getUnixShellEnvironment&unscoped_q=getUnixShellEnvironment)

**Comment by Meligy** [comment]
Have you been able to fix this or reported it elsewhere? It started for me out of nowhere after months of unaffected use. I don't want to modify the tasks file as it's checked in and no one else reported a similar issue.

**Comment by Meligy** [comment]
Sorry, I found my own issue. I had this setting and it seems to break things:

```
"terminal.integrated.inheritEnv": false,
```

It was weird because when I modified the task to just print current shell and PATH it printed the expected values.

Anyway, sorry again.

**Comment by jenksguo** [comment]
@Meligy thank you for posting the solution here. This has been bothering me for weeks now!

**Comment by yifan97** [comment]
"replacing the dotnet command in tasks with /usr/local/share/dotnet/dotnet helped work around this, for this mac environment."

This works! But anyone knows how to avoid this for the future or do we have to do every time we have a project?

**Comment by gregg-miskelly** [comment]
In case you haven't read this: https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshooting:-'The-.NET-Core-SDK-cannot-be-located.'-errors

**Comment by yifan97** [comment]
> In case you haven't read this: https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshooting:-'The-.NET-Core-SDK-cannot-be-located.'-errors

Gregg thank you for providing this. My case was "VS Code isn't picking it up". I just played around and tried launching VS Code from the terminal and it still gave me the same error.  Do you happen to know what further I can do or did I miss something? Thanks!

**Comment by gregg-miskelly** [comment]
To make sure I understand: you can run `dotnet` from the terminal, but if you launch VS Code from the terminal, then build tasks cannot find `dotnet` correct? If so, you could still try debugging the code that the Wiki article points at. If that isn't the issue, you could also try opening an issue against VS Code and see if someone from their team can help you troubleshoot.

**Comment by yifan97** [comment]
Sure I will try debugging VS code. BTW I can also run dotnet from VS code tho, it's just when I debug my c# code I got dotnet build error

**Comment by gregg-miskelly** [comment]
Can you better clarify when VS Code can start `dotnet` and when it cannot?

**Comment by yifan97** [comment]
Sorry if I confused you. In VS Code terminal, I can run dotnet run or dotnet new console, etc. However, when I want to debug my c# code, I got "The preLaunchTask 'build' terminated with exit code 1.", which particularly is because build cannot find path for dotnet. I replace dotnet in task.json with its full path, i.e /usr/local/share/dotnet/dotnet. The error's gone.

**Comment by SaintGimp** [comment]
> Sorry, I found my own issue. I had this setting and it seems to break things:
> 
> ```
> "terminal.integrated.inheritEnv": false,
> ```
Just a note to say that I was seeing the same problem and Meligy's solution solved it for me.

**Comment by deus42** [comment]
> Sorry, I found my own issue. I had this setting and it seems to break things:
> 
> ```
> "terminal.integrated.inheritEnv": false,
> ```
> 
> It was weird because when I modified the task to just print current shell and PATH it printed the expected values.
> 
> Anyway, sorry again.

For me worked vice versa setting it to true

**Comment by realdanielbyrne** [comment]
This problem consistently happens after the following sequence of events.
1.   Create a new dotnet application from command line 
2. Edit and debug application in "Visual Studio Code" for Mac.
3. Sometime in the future, opening the same application in "Visual Studio" for mac.
4. Opening up the project in Visual Studio Code for Mac, and then debugging does not work anymore.

"Visual Studio" is doing something to the application that breaks debugging in "Visual Studio Code".
smh

**Comment by adamal** [comment]
> Sorry, I found my own issue. I had this setting and it seems to break things:
> 
> ```
> "terminal.integrated.inheritEnv": false,
> ```

This is awesome! 

It is also likely the cause of a completely unrelated issue with a certain `task` (docker-compose not found) that I have worked around for about 6 months.

I don't recall ever having set this variable. But it was off. I wonder if it's new-ish parameter that came with a poor default.
