### ISSUE TITLE
not abel to debug .netcore api in visual studio code for windows

### ISSUE THREAD

**Issue by yogighanshyam** [OmniSharp/omnisharp-vscode#3452]
i am trying to debug my web api developed using dot net core 3.0 and got this message as 
"-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
"

& then after debugging is stopped

i had installed VS Code with this configuration

Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.14393

**Comment by gregg-miskelly** [comment]
Hi @yogighanshyam can you include your launch.json and your [debugger logs](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging).

**Comment by iaraf** [comment]
Hi, 

I'm having this same issue and I can't seem to pinpoint the problem. I set-up the application using `dotnet new angular` which used a template  to create an asp.net core 3.1 with an angular 8 front-end web application.

I said yes to allowing the C# extension to create the launch,json file when prompted but the debugger instantly exits and give the message that it can only run in vs code or vs.

I have tried re-installing vs code to no avail.

### Here is the output of my debugger logs:

-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"},"type":"request","seq":1}
-> (C) {"command":"launch","arguments":{"logging":{"engineLogging":false},"name":".NET Core Launch (web)","type":"coreclr","request":"launch","preLaunchTask":"build","program":"C:\\Repos/vega/bin/Debug/netcoreapp3.1/vega.dll","args":[],"cwd":"C:\\Repos/vega","stopAtEntry":false,"serverReadyAction":{"action":"openExternally","pattern":"^\\s*Now listening on:\\s+(https?://\\S+)"},"env":{"ASPNETCORE_ENVIRONMENT":"Development","ASPNETCORE_URLS":"https://localhost:5001;http://localhost:5000"},"sourceFileMap":{"/Views":"C:\\Repos/Views"},"internalConsoleOptions":"openOnSessionStart","__sessionId":"406cc353-50ad-40d2-838a-11feb9561fcd"},"type":"request","seq":2}
<- (E) {"seq":3,"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n"}}
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"launch"}
<- (E) {"seq":5,"type":"event","event":"initialized","body":{}}
-> (C) {"command":"setExceptionBreakpoints","arguments":{"filters":["user-unhandled"]},"type":"request","seq":3}
<- (R) {"seq":6,"type":"response","request_seq":3,"success":true,"command":"setExceptionBreakpoints"}
-> (C) {"command":"configurationDone","type":"request","seq":4}
<- (E) {"seq":7,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/LaunchFailed","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.2.10703.1 commit:d18411016e7da314dd58c44a4828778b19665cc3","VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"6.2.9200","VS.Diagnostics.Debugger.vsdbg.ErrorCode":-2147220965}}}
<- (R) {"seq":8,"type":"response","request_seq":4,"success":false,"command":"configurationDone","message":"Only 64-bit processes can be debugged."}
-> (C) {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":5}
<- (E) {"seq":9,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/DebugCompleted","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.2.10703.1 commit:d18411016e7da314dd58c44a4828778b19665cc3","VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"6.2.9200","VS.Diagnostics.Debugger.vsdbg.DebugCompleted.BreakCounter":0,"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr"}}}
<- (R) {"seq":10,"type":"response","request_seq":5,"success":true,"command":"disconnect"}

### Here is my launch.json:

`{
   // Use IntelliSense to find out which attributes exist for C# debugging
   // Use hover for the description of the existing attributes
   // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
   "version": "0.2.0",
   "configurations": [
        {
            "logging": {
                "engineLogging": true
            },
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/vega/bin/Debug/netcoreapp3.1/vega.dll",
            "args": [],
            "cwd": "${workspaceFolder}/vega",
            "stopAtEntry": false,
            // Enable launching a web browser when ASP.NET Core starts. For more information: https://aka.ms/VSCode-CS-LaunchJson-WebBrowser
            "serverReadyAction": {
                "action": "openExternally",
                "pattern": "^\\s*Now listening on:\\s+(https?://\\S+)"                
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}`

**Comment by gregg-miskelly** [comment]
Hi @iaraf do you wind up seeing any error message? 

The problem here is you are trying to launch a 32-bit process, and vsdbg only supports debugging 64-bit processes (currently at least). If you aren't trying to make a 32-bit process, my guess is the issue is that your path is somehow pointing at the 32-bit dotnet.exe instead of the 64-bit one. Did you install an x86 .NET SDK?

**Comment by iaraf** [comment]
Hi Gregg,

Thanks for the swift reply!

I've literally just uninstalled my x86 SDK and debugging is now working as expected. I had installed a 32bit SDK for some reason and as you rightly pointed out, my path was picking this up rather than the 64bit. 

Thanks for your help!

**Comment by gregg-miskelly** [comment]
I opened https://github.com/microsoft/vscode/issues/87745 for the VS Code problem where error messages are not being shown.
