### ISSUE TITLE
Error accessing cshtml files opened via a UNC path "Could not find a part of the path"

### ISSUE THREAD

**Issue by jeestirlingdev** [OmniSharp/omnisharp-vscode#3463]
## Issue Description ##
When opening a repo from a remote machine using a UNC path the extension crashes with an error 
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '\\ewds-d\d$\GitRoot\razor\d$\GitRoot\razor\scripts\_CreditNoteBalanceAdminView.cshtml'.

The full UNC path of the file is 
\\ewds-d\d$\GitRoot\razor\scripts\_CreditNoteBalanceAdminView.cshtml

## Steps to Reproduce ##
This happens on every repo that I try to access via a UNC path

## Expected Behavior ##
The extension should be able to interpret the path correctly

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.41.0
**C# Extension**: 1.21.9

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|atlascode|atlassian|2.2.1|
|auto-close-tag|formulahendry|0.5.6|
|auto-rename-tag|formulahendry|0.1.1|
|beautify|HookyQR|1.5.0|
|Bookmarks|alefragnani|10.6.0|
|csharp|ms-vscode|1.21.9|
|debugger-for-chrome|msjsdiag|4.12.3|
|dnn-theming-snippets|theleewise|0.0.6|
|html-css-class-completion|Zignd|1.19.0|
|JavaScriptSnippets|xabikos|1.7.2|
|jshint|dbaeumer|0.10.21|
|markdown-shortcuts|mdickin|0.12.0|
|mssql|ms-mssql|1.8.0|
|notepadplusplus-keybindings|ms-vscode|1.0.5|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|powershell|ms-vscode|2019.11.0|
|prettier-vscode|esbenp|3.14.0|
|remote-wsl|ms-vscode-remote|0.41.6|
|rest-client|humao|0.23.0|
|sass-indented|robinbentley|1.5.1|
|team|ms-vsts|1.161.0|
|vetur|octref|0.22.6|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-eslint|dbaeumer|2.0.5|
|vscode-essentials-snippets|robertoachar|2.0.0|
|vscode-gitignore-generator|piotrpalarz|1.0.1|
|vscode-json|andyyaldoo|1.5.0|
|vscode-mjml|mjmlio|1.0.0|
|vscode-npm-script|eg2|0.3.9|
|vscode-status-bar-format-toggle|tombonnike|2.0.0|
|vscode-yaml|redhat|0.6.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.0|
|vue-peek|dariofuzinato|1.0.2|
|vuejs-extension-pack|mubaidr|1.1.5|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by NTaylorMullen** [comment]
This looks to be a dup with the network sharing investigation issue we have in AspNetCore: https://github.com/aspnet/AspNetCore/issues/14317

Closing since the work will be tracked there.
