### ISSUE TITLE
build task no longer stops on errors with latest version

### ISSUE THREAD

**Issue by JohnGalt1717** [OmniSharp/omnisharp-vscode#3467]
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.41.0
**C# Extension**: 1.21.9

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|angular-console|nrwl|10.0.0|
|angular-essentials|johnpapa|0.6.3|
|Angular2|johnpapa|8.2.0|
|angular2-inline|natewallace|0.0.17|
|application-insights|VisualStudioOnlineApplicationInsights|0.4.2|
|auto-using|Fudge|0.7.9|
|autorest|ms-vscode|2.0.1|
|azds|azuredevspaces|2.0.220191204|
|azure-account|ms-vscode|0.8.7|
|azure-pipelines|ms-azure-devops|1.157.4|
|azurecli|ms-vscode|0.4.6|
|csharp|ms-vscode|1.21.9|
|dart-code|Dart-Code|3.7.1|
|debugger-for-chrome|msjsdiag|4.12.3|
|debugger-for-edge|msjsdiag|1.0.13|
|docomment|k--kato|0.1.8|
|dotnet-test-explorer|formulahendry|0.7.1|
|EditorConfig|EditorConfig|0.14.3|
|flutter|Dart-Code|3.7.1|
|githistory|donjayamanne|0.4.11|
|material-icon-theme|PKief|3.9.2|
|msbuild-project-tools|tintoy|0.3.2|
|ng-template|Angular|0.900.2|
|powershell|ms-vscode|2019.11.0|
|prettier-vscode|esbenp|3.14.0|
|python|ms-python|2019.11.50794|
|remote-containers|ms-vscode-remote|0.94.0|
|remote-ssh|ms-vscode-remote|0.48.0|
|remote-ssh-edit|ms-vscode-remote|0.48.0|
|remote-wsl|ms-vscode-remote|0.41.6|
|team|ms-vsts|1.161.0|
|vs-sharper|eservice-online|0.2.0|
|vscode-ai|ms-toolsai|0.6.8|
|vscode-aks-tools|ms-kubernetes-tools|0.0.4|
|vscode-angular2-files|alexiv|1.6.2|
|vscode-azureappservice|ms-azuretools|0.16.2|
|vscode-azureeventgrid|ms-azuretools|0.1.1|
|vscode-azurefunctions|ms-azuretools|0.20.1|
|vscode-azurestorage|ms-azuretools|0.7.2|
|vscode-cosmosdb|ms-azuretools|0.11.0|
|vscode-docker|ms-azuretools|0.9.0|
|vscode-firefox-debug|firefox-devtools|2.6.0|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.0.9|
|vscode-npm-script|eg2|0.3.10|
|vscode-peacock|johnpapa|3.2.0|
|vscode-remote-extensionpack|ms-vscode-remote|0.19.0|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|
|vscode-versionlens|pflannery|0.24.0|
|vscode-yaml|redhat|0.6.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.0|
|vsliveshare|ms-vsliveshare|1.0.1377|
|winteriscoming|johnpapa|1.3.0|
|xml|DotJoshJohnson|2.5.0|;

</details>
I have the following task:

``		{
			"label": "build",
			"command": "dotnet",
			"type": "process",
			"args": [
				"build",
				"${workspaceFolder}/xxx.csproj",
				"-c",
				"Debug"
			],
			"problemMatcher": "$msCompile",
			"group": {
				"kind": "build",
				"isDefault": true
			}
		},
``

This used to work and would fail on build errors and report them in problems. Now that doesn't happen, they scroll by but never stops the debug session.

**Comment by gregg-miskelly** [comment]
So this extension doesn't actually have anything to do with this behavior, so if you are having problems with this you will need to [report it to the VS Code team](https://github.com/microsoft/vscode/issues/).

That said, here is my **guess** as to what is going on -- VS Code has a setting to ignore task errors and continue debugging. I am guessing you have that set. To check, open your preferences file and see if you have `"debug.onTaskErrors"` configured. If so, remove your customization, or set it to `showErrors`.

BTW: it looks like your tasks.json is a somewhat old format. I would suggest either regenerating it, or adding these two args which will make it work a bit better:
```
            "args": [ 
                "build", 
                "${workspaceFolder}/xxx.csproj", 
                 "/property:GenerateFullPaths=true",
                 "/consoleloggerparameters:NoSummary",          
                "-c", 
                "Debug" 
            ],
```
