### ISSUE TITLE
Cannot add the C# extension on a machine that does NOT have internet access.

### ISSUE THREAD

**Issue by mkamoski** [OmniSharp/omnisharp-vscode#3473]
Problem...
Cannot add the C# extension on a machine that does NOT have internet access.
Solution...
Create an offline installer.
Thanks...
Mark Kamoski

**Comment by mkamoski** [comment]
Maybe this works...

https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

...download extension?

....trying it now...

**Comment by mkamoski** [comment]
All set, as above.

**Comment by mkamoski** [comment]
...update...

...I spoke too early in my comments above.... this is NOT closed...

...and install from vsix, the extension then tries some kind of initialization...

...it tries to download these...

....when, IMHO, a default version of these should be packaged in the vsix...

...and, BTW, the Windows 2012 Server already has VS 2019 Pro installed on it, so it begs the question-- what does this extension need to download all that carp when it VS 2019 is already installed???

....so the offline install is still broken (IMHO) so please try to fix, etc....

Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (32146 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'

Downloading package '.NET Core Debugger (Windows / x64)' (47489 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (Windows / x64)'

Downloading package 'Razor Language Server (Windows / x64)' (50022 KB).................... Done!
Installing package 'Razor Language Server (Windows / x64)'

...if somebody has a fix for this offline install issue that I have described, such as maybe getting all these dependencies, bundling them into a vsix, and then install THAT vsix in the VS Code as a extension from a vsix, to satisfy its dependencies, etc...

...HTH...

Thanks.

-- Mark Kamoski

**Comment by JoeRobich** [comment]
Hi @mkamoski, You can find instructions for building fully offline packages in our wiki - https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-the-C%23-extension-to-a-computer-without-internet-connectivity

**Comment by mkamoski** [comment]
> Hi @mkamoski, You can find instructions for building fully offline packages in our wiki - https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-the-C%23-extension-to-a-computer-without-internet-connectivity

Joe, I appreciate that, kinda hoped there was an all-in-one vsix somewhere here, and then one can just use that... but I am going to have to dust off the green-screen it seems... 

...forgive me, but I am skeptical at this point, and less than thrilled about this workaround, and so I will try what you say (if I can make time), but even still would strongly suggest an all-in-one vsix (updated every month or two would be sufficient IMHO) and it should be available for those with more time needed for coding (and less time available for  tool config), so anyway, would like to keep this open for now...

Thanks.

-- Mark Kamoski

**Comment by gregg-miskelly** [comment]
Mark, we do expect to eventually address this problem. But we need a feature from VS Code to do this right: https://github.com/microsoft/vscode/issues/23251. Until then, those instructions are what we have.
