### ISSUE TITLE
Debugging with Omnisharp in vscode running in Ubuntu 16.04 AWS not working

### ISSUE THREAD

**Issue by somuamit** [OmniSharp/omnisharp-vscode#3476]
Hi,
I have installed vscode on Ubuntu 16.04 AWS instance and running VSCode in the browser. Dotnet run is working fine and I am able to view the application output in the browser. I installed Omnisharp extension for debugging. But when I start debugging, it do open debug and show call stack,Watch etc.. but does not stop at the breakpoints. And it shows the below message whenever I start debugging:
"You may only use the Microsoft .NET Core Debugger (vsdbg) with
 Visual Studio Code, Visual Studio or Visual Studio for Mac software
 to help you develop and test your applications."

Please suggest what to do. 
![debug](https://user-images.githubusercontent.com/12642147/71231533-5d4f0800-2314-11ea-98eb-4f798aa9fda4.PNG)

**Comment by gregg-miskelly** [comment]
I am on vacation now, so I will try to give you some steps to figure this out. VS Code seems to have a bug in their current release where they aren't showing error messages returned from debug adapters. Look at the steps I suggested in https://github.com/OmniSharp/omnisharp-vscode/issues/3452. You can probably find the error message if you look at the response from `configurationDone`.

**Comment by somuamit** [comment]
Thanks for the update, but please let me know the steps to get the detailed error log. Or Do I need to c check the version of DotNet installed. I have installed dotnet by executing the command "sudo snap install dotnet-sdk --classic".Sorry if I am not able to explain the problem.

**Comment by gregg-miskelly** [comment]
@somuamit can you include your launch.json and your [debugger logs](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging).

**Comment by cartermp** [comment]
Closing out as no additional info was added.
