### ISSUE TITLE
VSCode v1.1.1 with omnisharp v1.0.10 which needs install dotnet cli tools Unable to load service

### ISSUE THREAD

**Issue by con-ssc** [OmniSharp/omnisharp-vscode#348]
I updated VSCode and the C# plugin and also installed the CLI tool.
After that I get the following error message when opening .cs files
```
Telemetry is: Enabled
log  : Restoring packages for %USERPROFILE%\.vscode\extensions\ms-vscode.csharp-1.0.10\coreclr-debug\project.json...
error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
error:   An error occurred while sending the request.
error:   Die Serververbindung konnte nicht hergestellt werden
dotnet exited with error code 1
```

**Comment by DustinCampbell** [comment]
This looks like an issue with acquiring the debugger bits via NuGet. Tagging @gregg-miskelly and @chuckries

**Comment by gregg-miskelly** [comment]
@con-ssc this looks like a problem with .NET CLI and/or nuget. What does `dotnet --info` return?

**Comment by con-ssc** [comment]
It returns
`
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
`

**Comment by gregg-miskelly** [comment]
@con-ssc can you try this and see if it works:

    cd /d %USERPROFILE%
    mkdir RestoreTest
    cd RestoreTest
    dotnet new
    dotnet restore

**Comment by con-ssc** [comment]
dotnet new works, dotnet restore gives the same error

**Comment by gregg-miskelly** [comment]
@con-ssc Would you mind opening your bug in https://github.com/dotnet/cli? This is there issue, and so they would be better at helping to troubleshoot.

**Comment by DustinCampbell** [comment]
@con-ssc, @gregg-miskelly: Now that .NET Core 1.0 is out, I'm curious to know if this issue is still relevant. Does this still happen with [.NET Core 1.0](https://dot.net)?

**Comment by con-ssc** [comment]
With the preview 2 of the CLI it seems to work
![image](https://cloud.githubusercontent.com/assets/8189808/16479339/edc2b8bc-3e9f-11e6-83ba-4363d390659f.png)

**Comment by DustinCampbell** [comment]
Excellent!
