### ISSUE TITLE
.NET Core 3.1 OmniSharp don't autocomplete with dependencies

### ISSUE THREAD

**Issue by TheDeaX-Lab** [OmniSharp/omnisharp-vscode#3480]
## Omnisharp log:
Starting OmniSharp server at 21.12.2019, 11:46:23
    Target: /home/deax/NetProjects/test/test.sln

OmniSharp server started with Mono 6.4.0.
    Path: /home/deax/.vscode-oss/extensions/ms-vscode.csharp-1.21.9/.omnisharp/1.34.9/omnisharp/OmniSharp.exe
    PID: 3104

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on arch 0.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[warn]: OmniSharp.MSBuild.Discovery.Providers.MonoInstanceProvider
        It looks like you have Mono 6.4.0 or greater installed but MSBuild could not be found.
Try installing MSBuild into Mono (e.g. 'sudo apt-get install msbuild') to enable better MSBuild support, or upgrade to latest Mono: https://www.mono-project.com/download/stable/.
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.3 - "/home/deax/.vscode-oss/extensions/ms-vscode.csharp-1.21.9/.omnisharp/1.34.9/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/deax/.vscode-oss/extensions/ms-vscode.csharp-1.21.9/.omnisharp/1.34.9/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.3 - "/home/deax/.vscode-oss/extensions/ms-vscode.csharp-1.21.9/.omnisharp/1.34.9/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/deax/.vscode-oss/extensions/ms-vscode.csharp-1.21.9/.omnisharp/1.34.9/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/deax/.vscode-oss/extensions/ms-vscode.csharp-1.21.9/.omnisharp/1.34.9/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/deax/.vscode-oss/extensions/ms-vscode.csharp-1.21.9/.omnisharp/1.34.9/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/deax/NetProjects/test'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/deax/NetProjects/test/test.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/deax/NetProjects/test/test.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/deax/NetProjects/test'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/deax/NetProjects/test/test.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/deax/NetProjects/test' on host 2830.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The target "Compile" does not exist in the project.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/home/deax/NetProjects/test/test.csproj'.
/home/deax/NetProjects/test/test.csproj
/home/deax/NetProjects/test/test.csproj(0,0): Error: The target "Compile" does not exist in the project.

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /home/deax/NetProjects/test/test.csproj
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 0.
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: /home/deax/NetProjects/test/Program.cs added to workspace

## dotnet --info
[deax@TheDeaX test]$ LANG=en_US.UTF8 dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview3-014645
 Commit:    b32d27f4b3

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /opt/dotnet/sdk/3.1.100-preview3-014645/

Host (useful for support):
  Version: 3.1.0-preview3.19553.2
  Commit:  13f35c3d86

.NET Core SDKs installed:
  2.2.108 [/opt/dotnet/sdk]
  3.1.100-preview3-014645 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.6 [/opt/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview3.19553.2 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

## Screenshot
https://ibb.co/mvCV0RM

## Steps to reproduce
1) Create a project using: dotnet new console test
2) Trying to add a dependency: dotnet add package System.Net.Http
3) We try to write code and we see that autocompletion: using System.Net.H - Does not work

## Expected  behavior
Auto completion required

## Actual behavior
Auto completion is not working properly

**Comment by filipw** [comment]
as the log says:

```
[warn]: OmniSharp.MSBuild.Discovery.Providers.MonoInstanceProvider
It looks like you have Mono 6.4.0 or greater installed but MSBuild could not be found.
Try installing MSBuild into Mono (e.g. 'sudo apt-get install msbuild') to enable better MSBuild support, or upgrade to latest Mono: https://www.mono-project.com/download/stable/.
```

did you try installing Mono again? see instructions https://github.com/OmniSharp/omnisharp-vscode/issues/3316#issuecomment-538807803

**Comment by djsell** [comment]
I had this same problem when using Mono installed via Homebrew.  I fixed it by removing that version of Mono and installing the official version.

One of the problems with Homebrew's Mono is that it packages an old version of msbuild with Mono 6.8.0.96:
```
% msbuild -version
Microsoft (R) Build Engine version 16.1.85+gad9c9926a7 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

16.1.85.40109%
```

People ignore this line when bumping Mono: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mono.rb#L35

Installing the official version of Mono 6.8.0.96, I get:
```
% msbuild -version 
Microsoft (R) Build Engine version 16.5.0-ci for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

16.5.0.6201%
```

Everything works now.

**Comment by cartermp** [comment]
Thanks for confirming that an updated mono resolves this @djsell. It looks like homebrew also has an updated mono distribution, so that is the likely fix.
