### ISSUE TITLE
Omnisharp Mac does not use Dotnet 3.1 templates for Azure Functions in Editor

### ISSUE THREAD

**Issue by barde** [OmniSharp/omnisharp-vscode#3486]
## Issue Description ##

Default installation on Mac with Azure Functions V3 with Dotnet 3.1 throws a lot of red squiggly lines:

"The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [testfunc]"

[Screenshot](https://imgur.com/a/vA5lQWw)

## Steps to Reproduce ##

- Create Func V3 project with default templates: 
```bash
dotnet new http
dotnet new func -A V3
```
- open folder in VSCode with Omnisharp enabled

## Expected Behavior ##

Being able to view the project without the error messages and squiggles.

## Actual Behavior ##

Red squiggles disturb me. The project is runnable, tough.

## Environment information ##

**VSCode version**: 1.41.1
**C# Extension**: 1.21.9

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.6.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /Users/debar/.dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [/Users/debar/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/Users/debar/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/Users/debar/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.7|
|azurerm-vscode-tools|msazurermtools|0.8.3|
|code-settings-sync|Shan|3.4.3|
|cpptools|ms-vscode|0.26.2|
|csharp|ms-vscode|1.21.9|
|platformio-ide|platformio|1.10.0|
|vscode-azurefunctions|ms-azuretools|0.20.1|
|vscode-docker|ms-azuretools|0.9.0|;

</details>

**Comment by filipw** [comment]
please post your OmniSharp log, thanks

**Comment by barde** [comment]
[OmniSharp log](https://gist.github.com/barde/b577c584f234ad01b4770095b6a52374)

[Example project](https://github.com/barde/omniSharpFunc3)

The dotnet commands are from the Dotnet CLI in the SDK. They are useful for scaffolding.
https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates

**Comment by filipw** [comment]
according to your log, there is a problem with your Cellar Mono installation 

see https://github.com/OmniSharp/omnisharp-vscode/issues/3477#issuecomment-567861540 for a solution
