### ISSUE TITLE
Debugger not working for azure functions

### ISSUE THREAD

**Issue by mshinnie** [OmniSharp/omnisharp-vscode#3499]
Issue Type: <b>Bug</b>

The debugger is not stopping at the breakpoints when i try to run azure functions locally in C#

Extension version: 1.21.9
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gregg-miskelly** [comment]
How are you attempting to run the Azure Function -- How is your launch.json configured? Is there an additional VS Code extension to enable Azure Function development?

**Comment by mshinnie** [comment]
I have the Azure Storage extension, and Azure functions as well as the as well as the C# OmniSharp extension.  My launch json is as follows 

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to .NET Functions",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:azureFunctions.pickProcess}"
        }
    ]
}

I have just used the template azure function that is created by the extension.  I run it by clicking f5 and then clicking the link that appears in the terminal.

**Comment by gregg-miskelly** [comment]
We may need to work with the Azure Storage team then, but before we do that, a few bits of troubleshooting:

1. Can you grab [debugger logs](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging)?
2. Can you follow the steps in the [breakpoint troublshooting doc](https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshoot-Breakpoints) and report what you tried?

**Comment by mshinnie** [comment]
This is the result of the debugger logs after I ran it 

-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"},"type":"request","seq":1}
-> (C) {"command":"attach","arguments":{"name":"Attach to .NET Functions","type":"coreclr","request":"attach","logging":{"engineLogging":false},"processId":"1296","__sessionId":"056b21cc-c467-4709-bc42-5174d4d403e5"},"type":"request","seq":2}
<- (E) {"seq":3,"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n"}}
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"attach"}
<- (E) {"seq":5,"type":"event","event":"initialized","body":{}}
-> (C) {"command":"setBreakpoints","arguments":{"source":{"name":"HttpTriggerCSharp.cs","path":"c:\\Users\\mshinnie\\Desktop\\Programming\\test3\\HttpTriggerCSharp.cs","checksums":[{"algorithm":"SHA1","checksum":"3d77df0fd39821ce0b61f195ba4d02a3240130bc"},{"algorithm":"SHA256","checksum":"2df2c82836cd3e0908743f0855e97b803409a5a66c96658db72bdaed9cb47deb"},{"algorithm":"SHA1","checksum":"d91c4b9bdb05a9b80febc1ae082d441f312faa46"},{"algorithm":"SHA256","checksum":"dd2854a3df3024b6bd5e269506287b22d17b8a3f101187db6b9384d340ae990e"}]},"lines":[16,17,18,19,21,22,23],"breakpoints":[{"line":16},{"line":17},{"line":18},{"line":19},{"line":21},{"line":22},{"line":23}],"sourceModified":false},"type":"request","seq":3}
<- (R) {"seq":6,"type":"response","request_seq":3,"success":true,"command":"setBreakpoints","message":"","body":{"breakpoints":[{"id":1,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":16},{"id":2,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":17},{"id":3,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":18},{"id":4,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":19},{"id":5,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":21},{"id":6,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":22},{"id":7,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts.","line":23}]}}
-> (C) {"command":"setExceptionBreakpoints","arguments":{"filters":["user-unhandled"]},"type":"request","seq":4}
<- (R) {"seq":7,"type":"response","request_seq":4,"success":true,"command":"setExceptionBreakpoints"}
-> (C) {"command":"configurationDone","type":"request","seq":5}
<- (E) {"seq":8,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/AttachFailed","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.2.10703.1 commit:d18411016e7da314dd58c44a4828778b19665cc3","VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"6.2.9200","VS.Diagnostics.Debugger.vsdbg.ErrorCode":-2147220965}}}
<- (R) {"seq":9,"type":"response","request_seq":5,"success":false,"command":"configurationDone","message":"Failed to attach to process: Only 64-bit processes can be debugged."}
-> (C) {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":6}
<- (E) {"seq":10,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/DebugCompleted","data":{"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"16.2.10703.1 commit:d18411016e7da314dd58c44a4828778b19665cc3","VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"6.2.9200","VS.Diagnostics.Debugger.vsdbg.DebugCompleted.BreakCounter":0,"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr"}}}
<- (R) {"seq":11,"type":"response","request_seq":6,"success":true,"command":"disconnect"}


The solutions on the other breakpoint troubleshooting doc were not successful

**Comment by gregg-miskelly** [comment]
Thanks! This is your problem:
"message":"Failed to attach to process: Only 64-bit processes can be debugged."

I don't know if there are options to control what type of process to use for Azure Functions, but this extension currently only supports debugging 64-bit processes.

BTW: There is a bug in the current version of VS Code (fixed in insiders) that this message isn't getting shown. Normally VS Code should be showing you this so we don't need logs to understand what is going on.

**Comment by mshinnie** [comment]
Ok great I will see if I can get that fixed.
