### ISSUE TITLE
Contribute to debug start experience

### ISSUE THREAD

**Issue by isidorn** [OmniSharp/omnisharp-vscode#3506]
Hi VS Code dev here :wave:

Last milestone we have introduced a Start View for debugging. More about this can be found here https://github.com/microsoft/vscode/issues/84677
So when the user has no `launch.json` file this view should help him start debugging.

This view is currently language agnostic and not very cluttered thus we are slowly looking in opening it up to extensions. We have two options:

1) Allow extensions to contribute commands / text to the current view. Those commands would be rendered as additional blue buttons or as some menu
2) Allow extensions to contribute a whole view which would be below the start view. The C# extension could choose what to render in that view and it would give a bit more control to the extension. Using context keys this view would only be visible in the "start" experience

What I would be interested in is what C# would like to contribute to improve the start experience. If it is only commands, than I think it makes sense to show those commands in the start view (for example with additional blue buttons). If it is much more then it makes more sense that C# contributes the whole view. 
What are the biggest pain points that C# users hit when setting up debugging?

Related python discussion: https://github.com/microsoft/vscode-python/issues/9268

Let me know what you think and how you envision the C# debug start experience.
Thanks!

fyi @gregg-miskelly 
Current look of debug start view

![Screenshot 2020-01-13 at 11 27 54](https://user-images.githubusercontent.com/1926584/72248554-c2d2a380-35f7-11ea-9a8b-07433034b9c4.png)

**Comment by gregg-miskelly** [comment]
Thanks for looping us in.

The only immediate idea I would have for improving the experience is that we have custom code for generating both launch.json and tasks.json which produces slightly better results than what comes out of the standard VS Code 'new launch.json' work flow -- we get to add comments if we generate it, where as if we are going through the API those get dropped. So **maybe** it would make sense to add a nice big button to make it super obvious that that is what you want to run to setup your workspace for .NET Core development.

But I will forward this issue on the to PM team to see if they have anything to add.

**Comment by isidorn** [comment]
@gregg-miskelly thanks for coming back. So a big button would be helpful for your scenario. 
Let me know if the PM team has something to add.
Thanks a lot!

**Comment by gregg-miskelly** [comment]
The debugger PM team didn't provide any further feedback to me. So I am going to close this.
