### ISSUE TITLE
[omnisharp-1.0.11]  C# suggestions or intellisense do not work with .sln project

### ISSUE THREAD

**Issue by ChongWangUBI** [OmniSharp/omnisharp-vscode#351]
os: osx
vscode:1.1.1
omnisharp:1.0.11

/Users/wangchong/__project/Program/Client  is a Unity3D Project and Have a Client.sln Project File.
But, When I update the new version omnisharp 1.0.11, suggestions or intellisense do not work.

follow is the detail info:

[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location '/Users/wangchong/__project/Program/Client' on host 2675.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /Users/wangchong/__project/Program/Client
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: True
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp.Startup] Configuration finished.

**Comment by DustinCampbell** [comment]
Hi,

.csproj projects are temporarily disabled in the latest release of the C# extension. Here's the notice that is on our readme for reference:

### **Important!** Breaking Changes as of 1.0.10

* The C# extension now only supports [.NET Core RC2](https://blogs.msdn.microsoft.com/dotnet/2016/05/16/announcing-net-core-rc2/). It no longer supports .NET Core RC1 or ASP .NET 5 RC1.
* **Support for .csproj projects has been temporarily disabled on OS X and Linux.** This will impact anyone doing .csproj development on OS X or Linux (e.g. Unity, Xamarin, etc.). Rest assured that this will be restored in the near future. However, for now, you can use the [Legacy C# Support extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.omnisharp).

**Comment by ChongWangUBI** [comment]
thx!
got it!

**Comment by ChongWangUBI** [comment]
thx!
got it!

**Comment by DustinCampbell** [comment]
Excellent! Let me know if you have any trouble getting up and running again.

**Comment by ChongWangUBI** [comment]
which version will support Unity,Xamarin in the plan.

**Comment by DustinCampbell** [comment]
We don't currently have a roadmap published. However, this is very high on our priority list.

**Comment by mdouglass** [comment]
Is there a github issue we can watch to track progress on this?
