### ISSUE TITLE
Adding ,h or ,b postfix to a watched variable does not show the hex or binary of the watched variable

### ISSUE THREAD

**Issue by 7sharp9** [OmniSharp/omnisharp-vscode#3513]
## Issue Description ##
Adding ,h or ,b to a watch doesn't not show the hex or binary in the watched variable in the debugger.

## Steps to Reproduce ##
Add ,h or ,b to a watched variable

## Expected Behavior ##
variable is shown with binary or hex

## Actual Behavior ##
variable is shown in decimal

## Environment information ##

**VSCode version**: 1.41.1
**C# Extension**: 1.21.9

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.4.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.401 [/usr/local/share/dotnet/sdk]
  2.1.508 [/usr/local/share/dotnet/sdk]
  2.1.802 [/usr/local/share/dotnet/sdk]
  2.2.106 [/usr/local/share/dotnet/sdk]
  2.2.203 [/usr/local/share/dotnet/sdk]
  2.2.401 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|better-toml|bungcip|0.3.2|
|code-spell-checker|streetsidesoftware|1.7.20|
|codedox|wiggin77|1.3.1|
|cpptools|ms-vscode|0.26.2|
|crates|serayuzgur|0.4.7|
|csharp|ms-vscode|1.21.9|
|debugger-for-chrome|msjsdiag|4.12.5|
|gruvbox-themes|tomphilbin|1.0.0|
|haxe-extension-pack|vshaxe|1.3.0|
|haxe-hl|HaxeFoundation|0.9.2|
|hxcpp-debugger|vshaxe|1.2.4|
|indent-rainbow|oderwat|7.4.0|
|Ionide-FAKE|Ionide|1.2.3|
|Ionide-fsharp|Ionide|4.4.4|
|Ionide-Paket|Ionide|1.12.0|
|markdown-all-in-one|yzhang|2.7.0|
|markdown-preview-enhanced|shd101wyy|0.5.1|
|mono-debug|ms-vscode|0.15.8|
|phantypist|paulofallon|1.0.3|
|rainbow-brackets|2gua|0.0.6|
|read-time|johnpapa|0.2.0|
|reason-vscode|jaredly|1.7.5|
|rust|rust-lang|0.7.0|
|rust-pack|Swellaby|0.2.23|
|Theme-FlatlandMonokai|gerane|0.0.6|
|theme-oceanicnext|naumovs|0.0.4|
|Theme-TomorrowKit|ms-vscode|0.1.4|
|tomorrow-and-tomorrow-night-operator-mono-theme|chiragpat|0.0.6|
|vscode-custom-css|be5invis|3.0.9|
|vscode-lldb|vadimcn|1.4.5|
|vscode-nupkg|eridem|1.0.1|
|vscode-wasm|dtsvet|1.2.1|
|vshaxe|nadako|2.17.0|
|wordcount|rido3|0.1.33|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by gregg-miskelly** [comment]
@7sharp9 You are debugging C# running under .NET Core?

`,h` is a valid format specifier for the C# Expression Evaluator (EE). It works for me.
',b` is NOT something that the C# EE supports. The full list is here: https://docs.microsoft.com/en-us/visualstudio/debugger/format-specifiers-in-csharp?view=vs-2019

**Comment by 7sharp9** [comment]
Ah ok, x is used most common for hex.  Pity there is no bit debug supported.
