### ISSUE TITLE
Debugging .Net app in docker fails with 'ps: not found'

### ISSUE THREAD

**Issue by cslovell** [OmniSharp/omnisharp-vscode#3514]
## Steps to Reproduce ##
(1) Setup a docker-compose file with a asp.net core 3.1 hello world application in the container. As follows:
```
--docker-compose.yml----
version: "3.2" 
services:
  app: 
    build: 
      context: ./netcore
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
  db: 
    image: "microsoft/mssql-server-linux"
    volumes: 
      - mssql-server-dev-linux-data:/var/opt/mssql/data
    restart: always
    environment:
      SA_PASSWORD: "Abcd1234!"
      ACCEPT_EULA: "Y"
    expose: 
      - "1433"
      - "1434"
    ports:
      - "1433:1433"
      - "1434:1434"
volumes:
  mssql-server-dev-linux-data:
```
(2) Setup the dockerfile in netcore folder:

---netcore/Dockerfile:
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers

COPY ./ ./
WORKDIR /app/HelloWorld
RUN dotnet restore

# Copy everything else and build

WORKDIR /app
COPY . ./
ADD entrypoint.sh /app/HelloWorld/.
RUN chmod +x /app/HelloWorld/entrypoint.sh
CMD /bin/bash /app/HelloWorld/entrypoint.sh
WORKDIR /app/HelloWorld

RUN dotnet publish -c Debug -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/HelloWorld/out .

ENTRYPOINT ["dotnet", "HelloWorld.dll"]
```
(3) Run the application using docker-compose up. Wait for services to be ready. 
(4) verify that your application is running as expected with the hello world whatever showing.
(5) Identify the name of the container by running "docker ps"
(6) Create a .vscode/launch.json file containing the following, replacing the variable in square brackets with the name of the container found in 5: 
```
{
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": ".NET Core Docker Attach",
            "type": "coreclr",
            "request": "attach",
            "preLaunchTask": "preDockerDebug",
            "processId": "${command:pickRemoteProcess}",
            "sourceFileMap": {
                "/app": "${workspaceFolder}/netcore"
            },
            "pipeTransport": {
                "pipeProgram": "docker",
                "pipeArgs": [ "exec", "-i", "[name of hello world container]" ],
                "debuggerPath": "/publish/vsdbg/vsdbg",
                "pipeCwd": "${workspaceFolder}/netcore",
                "quoteArgs": false
            }
        }
    ]
}
```
(7) Create a file called ./.vscode/tasks.json with the following:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "publishApp",
            "command": "dotnet",
            "type": "shell",
            "args": [
                "publish", "-c", "Debug", "--no-restore"
            ],
            "group": "none",
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$msCompile"
        },
        {
            "label": "restartAppContainer",
            "command": "docker-compose",
            "type": "shell",
            "args": [
                "restart", "app"
            ],
            "group": "none",
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$msCompile"
        },
        {
            "label": "preDockerDebug",
            "type": "shell",
            "command": "echo Starting pre docker debug scripts...",
            "dependsOrder": "sequence",
            "dependsOn": ["publishApp", "restartAppContainer"],
            "group": "none"
        }
    ],
    "options": {
        "cwd": "${workspaceRoot}/netcore/HelloWorld"
    }
}
```
(8) With the applicaiton still running, attempt to attach the debugger by clicking on the VS Code green debugger icon.

## Expected Behavior ##

When I click the debugger button in (8), the application rebuilds the application and restarts the container, and then attaches the debugger. This allows me to enter break points, etc. 

## Actual Behavior ##

When I click the debugger icon, the remote-attach process fails with the following error text: 

```
Executing: docker exec -i hello-world_app_1 sh -s < C:\Users\My.User\.vscode\extensions\ms-vscode.csharp-1.21.9\scripts\remoteProcessPickerScript
Linux
stderr: sh: 1: ps: not found
Error Message: Command failed: docker exec -i hello-world_app_1 sh -s < C:\Users\My.User\.vscode\extensions\ms-vscode.csharp-1.21.9\scripts\remoteProcessPickerScript
sh: 1: ps: not found
```

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.41.1
**C# Extension**: 1.21.9

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|angular-console|nrwl|10.0.0|
|angular-essentials|johnpapa|0.6.3|
|Angular2|johnpapa|8.3.0|
|angular2-inline|natewallace|0.0.17|
|beautify|HookyQR|1.5.0|
|cloudcode|googlecloudtools|1.0.1|
|code-eol|sohamkamani|0.3.3|
|code-runner|formulahendry|0.9.15|
|code-settings-sync|Shan|3.4.3|
|csharp|ms-vscode|1.21.9|
|cypher-query-language|jakeboone02|1.0.2|
|debugger-for-chrome|msjsdiag|4.12.3|
|dotenv|mikestead|1.0.1|
|dotnet-test-explorer|formulahendry|0.7.1|
|EditorConfig|EditorConfig|0.14.4|
|gc-excelviewer|GrapeCity|2.1.32|
|gitlens|eamodio|10.2.0|
|intellij-idea-keybindings|k--kato|0.2.37|
|java|redhat|0.54.2|
|MagicPython|magicstack|1.1.0|
|material-icon-theme|PKief|3.9.2|
|mono-debug|ms-vscode|0.15.8|
|mssql|ms-mssql|1.8.0|
|ng-template|Angular|0.900.3|
|npm-intellisense|christian-kohler|1.3.0|
|pip-packages|etmoffat|0.4.3|
|prettier-vscode|esbenp|3.16.1|
|python|ms-python|2019.11.50794|
|remote-containers|ms-vscode-remote|0.94.0|
|remote-ssh|ms-vscode-remote|0.48.0|
|remote-ssh-edit|ms-vscode-remote|0.48.0|
|remote-ssh-explorer|ms-vscode-remote|0.48.0|
|remote-wsl|ms-vscode-remote|0.41.6|
|Spell|seanmcbreen|1.0.0|
|vscode-docker|ms-azuretools|0.9.0|
|vscode-java-debug|vscjava|0.23.0|
|vscode-java-dependency|vscjava|0.6.0|
|vscode-java-pack|vscjava|0.8.1|
|vscode-java-test|vscjava|0.22.0|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.0.9|
|vscode-markdownlint|DavidAnson|0.33.0|
|vscode-maven|vscjava|0.20.1|
|vscode-npm-script|eg2|0.3.10|
|vscode-remote-extensionpack|ms-vscode-remote|0.19.0|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|
|vscode-yaml|redhat|0.6.1|
|vscode-zipexplorer|slevesque|0.3.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.0|
|winteriscoming|johnpapa|1.3.0|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by gregg-miskelly** [comment]
Hi @cslovell I am guessing that previously you used an image that had `ps` in it, as this extension's process picker has always relied on `ps`. You can add it by installing the `procps` package. Alternatively, you can work out the process id yourself and manually edit your launch.json to contain it. Here are the instructions as an FYI: https://github.com/OmniSharp/omnisharp-vscode/wiki/Attaching-to-remote-processes#configuring-docker-attach-with-launchjson
