### ISSUE TITLE
Type parameters XML doc tags not shown properly in Intellisense

### ISSUE THREAD

**Issue by ChrRubin** [OmniSharp/omnisharp-vscode#3516]
## Issue Description ##
When using the `<typeparam>` XML doc tag, its description is shown without preceding with a new-line nor its name.

## Steps to Reproduce ##
Add the `<typeparam>` tag to the XML doc comment of a class or method that accepts generic types.

## Expected Behavior ##
Type parameters should be shown just like normal parameters with the `<param>` tag, each on a new line with their name followed by its description.

## Actual Behavior ##
Only the description of `<typeparam>` is shown on the same line with `<param>`.
![image](https://user-images.githubusercontent.com/20059164/72665673-98dd0f00-3a45-11ea-8e40-4163fd974a1f.png)

If multiple `<typeparam>` tags are used they are all shown on the same line.
![image](https://user-images.githubusercontent.com/20059164/72665682-b7dba100-3a45-11ea-81c7-ad2174b8a008.png)

## Environment information ##

**VSCode version**: 1.41.1
**C# Extension**: 1.21.9

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.101
 Commit:    bc5f8df0f5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.101\

Host (useful for support):
  Version: 3.0.1
  Commit:  32085cbc72

.NET Core SDKs installed:
  3.0.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

**Comment by ChrRubin** [comment]
Also it is worth noting that `<typeparamref>` is completely ignored:
![image](https://user-images.githubusercontent.com/20059164/72665928-20c41880-3a48-11ea-84cb-b448489ad57c.png)

**Comment by DanielLidstromTicket** [comment]
I am seeing other problems with xml comments. I am not sure if there are other issues for those, but I am seeing <list type="bullet"> showing up garbled in intellisense. Please let me know if there is an issue already or if I should create a new, or amend this. Thanks!

**Comment by JoeRobich** [comment]
@DanielLidstromTicket Can you please open an issue for the intellisense issues you are seeing?

**Comment by DanielLidstromTicket** [comment]
I did here: https://github.com/OmniSharp/omnisharp-vscode/issues/3693

**Comment by JoeRobich** [comment]
This issue is fixed in 1.21.17
