### ISSUE TITLE
Defer downloading dependencies until needed, not during activation

### ISSUE THREAD

**Issue by firelizzard18** [OmniSharp/omnisharp-vscode#3517]
##  Issue Description ##

When a user executes the `workbench.action.debug.configure` command, all extensions that contribute a debugger are activated, to provide entries for the quick pick list*. When OmniSharp is activated, it starts downloading its dependencies and does not provide entries for the quick pick list until those downloads are complete. Thus, OmniSharp considerably delays completion of the command. This is a serious UX issue when I am working in any other language.

*Activating extensions like this is expected behavior: https://github.com/microsoft/vscode-python/issues/9557#issuecomment-574259357, https://github.com/microsoft/vscode-node-debug/issues/170#issuecomment-368344394.

## Steps to Reproduce ##

  1. Open Windows Sandbox
  2. Install Visual Studio Code
  3. Install OmniSharp and immediately exit VSCode (otherwise OmniSharp immediately installs dependencies)
  4. Reopen VSCode, open a folder
  5. Open the command dialog, execute "Debug: Open launch.json"

## Expected Behavior ##

The "Select Environment" quick pick shows up immediately.

## Actual Behavior ##

Nothing visibly happens (except in the logs) until OmniSharp is finished downloading everything, then the quick pick shows up.

### OmniSharp log ###
(empty)

### C# log ###
<details>
Installing C# dependencies...
Platform: win32, x86_64

Downloading package '.NET Core Debugger (Windows / x64)' (47489 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (Windows / x64)'

Downloading package 'Razor Language Server (Windows / x64)' (50022 KB).................... Done!
Installing package 'Razor Language Server (Windows / x64)'

Finished

Failed to spawn 'dotnet --info'
</details>

## Environment information ##

**VSCode version**: 1.41.1
**C# Extension**: 1.21.9

<details><summary>Dotnet Information</summary>
A valid dotnet installation could not be found.</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.9|;

</details>

**Comment by gregg-miskelly** [comment]
The ultimate fix for this extension is https://github.com/Microsoft/vscode/issues/23251, which will eliminate the need for extensions (or at least this extension) to download all of its dependencies on first activation. Until then, this is not something we are planning to change.

**Comment by NTaylorMullen** [comment]
https://github.com/dotnet/vscode-dotnetcore will also help minimize the downloader dependency download duration/size as well.
