### ISSUE TITLE
Debugger doesn't work when some thread enters an infinite loop

### ISSUE THREAD

**Issue by webczat** [OmniSharp/omnisharp-vscode#3520]
I have c# extension 1.21.9 with dotnet core version 3.1, running on linux.
I tried to debug a program that in Main method runs an infinite loop, for t

esting purposes. The problem was that after I started debugging, even though it was shown that program has started, I didn't see any info about it incl. list of threads in call stack view.

Actually, when I have tried to pause the program to inspect stack traces it didn't really work. After a try to pause, even the stop command stopped working. It was also impossible to kill the dotnet process unless doing it forcibly.
The example program is:

```
﻿using System;

class Program
{
    static void Main()
    {
        while (true) { }
    }
}
```

**Comment by gregg-miskelly** [comment]
I am not sure if CoreCLR has a bug on this, but this is a limitation in CoreCLR.

I am not sure if you did this accidentally, or if you were inserting a spot where you were intentionally trying to break in. If the later: add a `Thread.Sleep` in the body of your while loop and this will work great.

**Comment by gregg-miskelly** [comment]
Here is the CoreCLR bug: https://github.com/dotnet/coreclr/issues/4623

**Comment by webczat** [comment]
It's a kind of both. I was trying to trigger some deadlock or something like that and accidentally caused this, but I figured out this should not be happening in the first place.

**Comment by JoeRobich** [comment]
Closing this as resolved external since this is a CoreCLR bug.
