### ISSUE TITLE
Debugging on Raspberry Pi3 with Remote-SSH extension

### ISSUE THREAD

**Issue by DBarzo** [OmniSharp/omnisharp-vscode#3522]
## Issue Description ##
I'm trying to write, build and debug .net core app directly on a Raspy using Remote-SSH extension.
The build process succeed but the debugger do not run it, and VS give me this error:

![image](https://user-images.githubusercontent.com/6357293/72891297-3e2d0700-3d14-11ea-938f-d659124377f1.png)

Which seems to be here : https://github.com/OmniSharp/omnisharp-vscode/blob/4b4295e620d0b178cd4bb1caed885924c8a8fcc6/src/coreclr-debug/activate.ts#L135

**task.json** is:
![image](https://user-images.githubusercontent.com/6357293/72891725-302bb600-3d15-11ea-9d51-5ec587225a36.png)

**launch.json** is:
![image](https://user-images.githubusercontent.com/6357293/72891731-34f06a00-3d15-11ea-9519-42dd45dbdb6f.png)

Its output:
> > Executing task: dotnet build /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <
> > 
> > Microsoft (R) Build Engine versione 16.4.0+e901037fe per .NET Core
> > Copyright (C) Microsoft Corporation. Tutti i diritti sono riservati.
> > 
> >   Il ripristino in 202 ms è stato completato per /home/pi/projects/GpioTest/GpioTest.csproj.
> >   GpioTest -> /home/pi/projects/GpioTest/bin/Debug/netcoreapp3.1/GpioTest.dll
> > 
> > Terminal will be reused by tasks, press any key to close it.

### OmniSharp log ###
No log.

### C# log ###
No log.

## Environment information ##

**VSCode version**: 1.42.0-insider
**C# Extension**: 1.21.9

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (che rispecchia un qualsiasi file global.json):
 Version:   3.1.101
 Commit:    b377529961

Ambiente di runtime:
 OS Name:     raspbian
 OS Version:  10
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /usr/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.26.2|
|csharp|ms-vscode|1.21.9|
|python|ms-python|2020.1.58038|;

</details>

**Comment by gregg-miskelly** [comment]
@DBarzo the way to develop C# code with this extension to run on a Pi is to build/develop it locally, and then publish+remote debug. You can find instructions here: https://github.com/OmniSharp/omnisharp-vscode/wiki/Remote-Debugging-On-Linux-Arm

**Comment by DBarzo** [comment]
Hi @gregg-miskelly ,

thanks for your reply.
Yes, I'm doing exactly this right now.
I thought the two extensions could be used in conjunction.
