### ISSUE TITLE
Auto generated launch.json does not have fill in path to binary

### ISSUE THREAD

**Issue by jeffschwMSFT** [OmniSharp/omnisharp-vscode#353]
![launch json](https://cloud.githubusercontent.com/assets/9561583/15404858/515ccc44-1db4-11e6-830e-3d00f5f4f20a.gif)

Somewhere close to the end of RC2 the auto-generated launch.json no longer had a full path to the built binary.

Repro:
dotnet new
open VS Code
Choose to auto-generate the launch.json and task.json

Expected:
"program": "${workspaceRoot}/bin/Debug/netcoreapp1.0/app.dll",

Actual:
"program": "${workspaceRoot}/bin/Debug/<target-framework>/<project-name.dll>",

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code - 1.0.3-rc2

**Comment by chuckries** [comment]
I am trying this on OSX 10.11 with VS Code 1.1.1 and C# extension 1.0.11. I have the same version of the .NET CLI. What version of the extension do you have installed? Extensions: Show Installed Extensions from the command palette will show you this.

**Comment by jeffschwMSFT** [comment]
1.0.3-rc2.  I see I am likely behind the times, I will update to 10 or 11.

**Comment by jeffschwMSFT** [comment]
My extension must have been crusty... 11 is working as expected.

**Comment by chuckries** [comment]
Excellent!
