### ISSUE TITLE
Invalid uninstall of VS2019 cause Microsoft.Build.Exceptions.InvalidProjectFileException

### ISSUE THREAD

**Issue by seongwon-kang** [OmniSharp/omnisharp-vscode#3530]
## Issue Description ##
Invalid uninstall of VS2019 cause crashes with `Microsoft.Build.Exceptions.InvalidProjectFileException`
(when I renamed MSBuild directory, omnisharp extension works)

## Steps to Reproduce ##
1. Install .NET Core
2. Install VS Community 2019 with .NET SDK, and uninstall (in my case, `Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin` was not removed, but I have no idea why) 
3. Install C# Extension
4. make dotnet project with `dotnet new sln`
5. make some project with `dotnet new classlib`, `dotnet new nunit`
6. Restart extension with `Omnisharp: Restart Omnisharp`
7. Project not loaded

## Expected Behavior ##
Loads project , and show information

## Actual Behavior ##
Project Not loaded, so no tooltip available

### OmniSharp log ###
Starting OmniSharp server at 2020. 1. 28. 오후 5:43:11
    Target: c:\Users\user\Documents\repo\project\Model\Model.sln

OmniSharp server started.
    Path: C:\Users\user\.vscode\extensions\ms-vscode.csharp-1.21.9\.omnisharp\1.34.9\OmniSharp.exe
    PID: 17532

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.4.29519.181 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.3 - "C:\Users\user\.vscode\extensions\ms-vscode.csharp-1.21.9\.omnisharp\1.34.9\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.4.29519.181 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\user\Documents\repo\project\Model'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\user\Documents\repo\project\Model\Model.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\user\Documents\repo\project\Model\src\src.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\user\Documents\repo\project\Model\test\test.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\user\Documents\repo\project\Model'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\user\Documents\repo\project\Model\src\src.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\user\Documents\repo\project\Model' on host 21296.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\user\Documents\repo\project\Model\src\src.csproj'.
c:\Users\user\Documents\repo\project\Model\src\src.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: 지정된 'Microsoft.NET.Sdk' SDK를 찾을 수 없습니다.  c:\Users\user\Documents\repo\project\Model\src\src.csproj
   위치: Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   위치: Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   위치: Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   위치: Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   위치: Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   위치: Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   위치: Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   위치: Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   위치: Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   위치: Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   위치: Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   위치: Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   위치: OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath) 파일 D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:줄 129
   위치: OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath) 파일 D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:줄 72
   위치: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectIdInfo projectIdInfo, ProjectLoader loader) 파일 D:\a\1\s\src\OmniSharp.MSBuild\ProjectFile\ProjectFileInfo.cs:줄 98
   위치: OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader) 파일 D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:줄 308

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\user\Documents\repo\project\Model\test\test.csproj
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\user\Documents\repo\project\Model\test\test.csproj'.
c:\Users\user\Documents\repo\project\Model\test\test.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: 지정된 'Microsoft.NET.Sdk' SDK를 찾을 수 없습니다.  c:\Users\user\Documents\repo\project\Model\test\test.csproj
   위치: Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   위치: Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   위치: Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   위치: Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   위치: Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   위치: Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   위치: Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   위치: Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   위치: Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   위치: Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   위치: Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   위치: Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   위치: OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath) 파일 D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:줄 129
   위치: OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath) 파일 D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:줄 72
   위치: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectIdInfo projectIdInfo, ProjectLoader loader) 파일 D:\a\1\s\src\OmniSharp.MSBuild\ProjectFile\ProjectFileInfo.cs:줄 98
   위치: OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader) 파일 D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:줄 308

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\user\Documents\repo\project\Model\src\src.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\user\Documents\repo\project\Model\test\test.csproj

## Environment information ##

**VSCode version**: 1.41.1
**C# Extension**: 1.21.9

<details><summary>Dotnet Information</summary>
.NET Core SDK(global.json �ݿ�):
 Version:   3.1.101
 Commit:    b377529961

��Ÿ�� ȯ��:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|autodocstring|njpwerner|0.4.0|
|cloudcode|googlecloudtools|1.0.1|
|csharp|ms-vscode|1.21.9|
|csharpextensions|jchannon|1.3.1|
|dotnet-test-explorer|formulahendry|0.7.1|
|increment-selection|albymor|0.2.0|
|java|redhat|0.55.1|
|jenkinsfile-support|ivory-lab|0.4.4|
|python|ms-python|2020.1.58038|
|remote-wsl|ms-vscode-remote|0.41.7|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-snippets|YclepticStudios|0.1.2|
|vsc-mybatis|niko|1.2.0|
|vsc-travis-ci-status|felixrieseberg|1.1.0|
|vscode-java-debug|vscjava|0.24.0|
|vscode-java-dependency|vscjava|0.8.0|
|vscode-java-pack|vscjava|0.8.1|
|vscode-java-test|vscjava|0.22.1|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.0.9|
|vscode-maven|vscjava|0.20.2|
|vscode-openapi|42Crunch|2.1.0|
|vscode-position|jtr|1.0.1|
|vscode-postman|eridem|1.0.2|
|vscode-yaml|redhat|0.6.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.4|
|white|arthurwhite|1.3.6|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by cartermp** [comment]
Thanks for the report @seongwon-kang . Unfortunately, this (and related issues) will always happen since the C# plugin currently doesn't have its own self-contained way to manage MSBuild and will rely on system installations. When those go bad in some way, it will affect the plugin. Eventually we'll have to get things into better shape for the plugin, but that would be a more fundamental design change.
