### ISSUE TITLE
Omnisharp gives out 26 errors in Hello world template & keeps on suggesting I restore the project

### ISSUE THREAD

**Issue by piperun** [OmniSharp/omnisharp-vscode#3531]
## Issue Description ##
Can build just fine and run the program, however, vscode gives out way too many errors & gives me a notification that "There are unresolved dependencies. Please execute the restore command to continue."

## Steps to Reproduce ##
Install latest .NET.Core version (3.1) with SDK
use the latest stable VSCode version
Generate console template.

```
dotnet new console -o "MyProgram"
cd MyProgram
Code .
```

## Expected Behavior ##
Omnisharp not giving out "false positives"
## Actual Behavior ##
Gives out 26 errors.
### OmniSharp log ###
```
Starting OmniSharp server at 2020-01-28 10:48:40
    Target: z:\Programming\C#\MyProgram

OmniSharp server started.
    Path: C:\Users\MyUser\.vscode\extensions\ms-vscode.csharp-1.21.9\.omnisharp\1.34.9\OmniSharp.exe
    PID: 72448

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2019 16.1.29102.190 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
            2: StandAlone 16.3 - "C:\Users\MyUser\.vscode\extensions\ms-vscode.csharp-1.21.9\.omnisharp\1.34.9\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2019 16.1.29102.190 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'z:\Programming\C#\MyProgram'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'z:\Programming\C#\MyProgram'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'z:\Programming\C#\MyProgram\MyProgram.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'z:\Programming\C#\MyProgram'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: z:\Programming\C#\MyProgram\MyProgram.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'z:\Programming\C#\MyProgram' on host 50516.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'z:\Programming\C#\MyProgram\MyProgram.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'z:\Programming\C#\MyProgram\MyProgram.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MyProgram
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        MyProgram: Did not find 'Microsoft.NETCore.App' in lock file.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'z:\Programming\C#\MyProgram\MyProgram.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: z:\Programming\C#\MyProgram\MyProgram.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'z:\Programming\C#\MyProgram\MyProgram.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MyProgram
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        MyProgram: Did not find 'Microsoft.NETCore.App' in lock file.
```

### C# log ###
Nothing 

Error log:

```
The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?) [MyProgram]
Predefined type 'System.String' is not defined or imported [MyProgram]
The type or namespace name 'FrameworkDisplayName' could not be found (are you missing a using directive or an assembly reference?) [MyProgram]
Predefined type 'System.String' is not defined or imported [MyProgram]

```
## Environment information ##

**VSCode version**: 1.41.1
**C# Extension**: 1.21.9

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.9|
|git-project-manager|felipecaputo|1.7.1|
|Go|ms-vscode|0.12.0|
|go-outliner|766b|0.1.20|
|go-prof|MaxMedia|0.0.4|
|msbuild-project-tools|tintoy|0.3.3|
|vscode-fileutils|sleistner|3.0.1|
|vscode-versionlens|pflannery|0.24.0|;

</details>

**Comment by filipw** [comment]
it's because you have ` 1: Visual Studio Build Tools 2019 16.1.29102.190` installed, which doesn't support .NET Core 3.1
Please update it to latest version or uninstall completely.

**Comment by piperun** [comment]
Oh dang, silly me.
Thanks for the quick help!

**Comment by thecount12** [comment]
Well I'm stuck

.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.102/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.102 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by JoeRobich** [comment]
@thecount12 Sorry you are having trouble. Can you open a new issue and provide the requested logs as well as a description of the issues you are experiencing?
