### ISSUE TITLE
launch.json is generated with the wrong `program` path in projects that define `RuntimeIdentifier`

### ISSUE THREAD

**Issue by mayconbj15** [OmniSharp/omnisharp-vscode#3535]
**Edit by @gregg-miskelly: See [this comment](https://github.com/OmniSharp/omnisharp-vscode/issues/3535#issuecomment-854172590) for more detailed steps to reproduce this problem.**

When my Project has a <RuntimeIdentifier> tag in my .csproj file the .launch.json of VS Code don't recognize the correctly path of the .dll of project.

For example:
The correct path is: "${workspaceFolder}/MyProject/bin/Debug/netcoreapp3.1/win-x86/MyProject.dll"

But the .launch.json has this path
"${workspaceFolder}/MyProject/bin/Debug/netcoreapp3.1/MyProject.dll"

I need to change this manually to work

**Comment by gregg-miskelly** [comment]
How did you create your launch.json? 

There is no magic in the launch.json handling for `program`: It needs to be the path to the dll you want to launch. So if you had `<RuntimeIdentifier>` in it -- that is just a placeholder which you need to manually update.

**Comment by mayconbj15** [comment]
I created with the VS Code automatically. When i run the project in debug mode.

I know that i need to change the path manually, but i guess that extension could build this path automatically according with the directory created in build of project.

**Comment by gregg-miskelly** [comment]
If you remember, how did you create it automatically? (What buttons did you press)

This extension does try to create a launch.json for you automatically which would have that filled in. So either this extension couldn't understand your project (which should result in a big warning) or you went down one of the 'not-so-automatic' paths to creating a launch.json file.

**Comment by mayconbj15** [comment]
I pressed the key F5 and selected the enviroment of .NET Core, then VS Code created the launch.json.

**Comment by gregg-miskelly** [comment]
That should produce a launch.json with runtime filled in. Can you still repo? What does your launch.json look like?

**Comment by cartermp** [comment]
@mayconbj15 do you have a sharable project that we can take a look at to verify this?

**Comment by cartermp** [comment]
Closing out as no additional info was added.

**Comment by mvadu** [comment]
I can recreate this issue.. 
Steps to follow:
1. Use the code from here : https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service
2. Per instruction add the blow to csproj
```xml
  <OutputType>exe</OutputType>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
```
3. Delete bin/obj/.vscode folders if present
4. Reload the vscode window (`Developer : Reload Window`)
5. wait for the popup ("Required assets to build and debug are missing from 'tempWorker'. Add them?")
![image](https://user-images.githubusercontent.com/8618235/120710320-05667b80-c48c-11eb-8980-5559fc453869.png)

6. Try to launch
![image](https://user-images.githubusercontent.com/8618235/120710478-2dee7580-c48c-11eb-81d7-e734fd6b9a64.png)
Actual artifacts are under `${workspaceFolder}\bin\Debug\net5.0\win-x64`

7. In launch.json it does not consider the run time identifier. 
```
// If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/bin/Debug/net5.0/tempWorker.dll",
```

**Comment by jboarman** [comment]
@cartermp Can we re-open this issue?  This is an ongoing issue, and @mvadu's description provides the steps needed to repro this issue.  With increasing use of single file publishing and trimmed publishing, this issue becomes a growing problem.

**Comment by gregg-miskelly** [comment]
cartermp has left Microsoft, so I will reopen the issue.
