### ISSUE TITLE
Unable to launch coreclr debugger with attached Alpine container

### ISSUE THREAD

**Issue by JerryJoyce** [OmniSharp/omnisharp-vscode#3540]
## Issue Description ##
I've created an Alpine based docker Docker image.  VSCode successfully attaches to the container and installs the C# extension, but I am unable to launch coreclr debugger.
## Steps to Reproduce ##
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID


ARG INSTALL_ZSH="true"


ARG COMMON_SCRIPT_SOURCE="https://raw.githubusercontent.com/microsoft/vscode-dev-containers/master/script-library/common-alpine.sh"
ARG COMMON_SCRIPT_SHA="dev-mode"


RUN apk update \
    && apk add --no-cache wget coreutils ca-certificates procps \
    #
    # Verify git, common tools / libs installed, add/modify non-root user, optionally install zsh
    && wget -q -O /tmp/common-setup.sh $COMMON_SCRIPT_SOURCE \
    && if [ "$COMMON_SCRIPT_SHA" != "dev-mode" ]; then echo "$COMMON_SCRIPT_SHA /tmp/common-setup.sh" | sha256sum -c - ; fi \
    && /bin/ash /tmp/common-setup.sh "$INSTALL_ZSH" "$USERNAME" "$USER_UID" "$USER_GID" \
    && rm /tmp/common-setup.sh

RUN curl -sSL https://aka.ms/getvsdbgsh | sh /dev/stdin -v latest -l /vsdbg
```

Build the Docker image and start a container, map in a local volume containing a csproj.
Attach to the container from VSCode
Install the C# extension into the attached container.
Add a debug configuration in launch.json.
Attempt to launch the debugger.
## Expected Behavior ##
Debugger launches
## Actual Behavior ##
Debugger exits immediately with no output or error messages.
### OmniSharp log ###
<details></details>

### C# log ###
<details>Starting OmniSharp server at 1/30/2020, 7:33:54 PM
    Target: /RaaS.PerceptionEngine.Backend/src/rtcv.sln

OmniSharp server started.
    Path: /root/.vscode-server/extensions/ms-vscode.csharp-1.21.9/.omnisharp/1.34.9/run
    PID: 532

/root/.vscode-server/extensions/ms-vscode.csharp-1.21.9/.omnisharp/1.34.9/run: line 27: /root/.vscode-server/extensions/ms-vscode.csharp-1.21.9/.omnisharp/1.34.9/bin/mono: No such file or directory
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
</details>

## Environment information ##

**VSCode version**: 1.41.1
**C# Extension**: 1.21.9

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     alpine
 OS Version:  3.10
 OS Platform: Linux
 RID:         alpine.3.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.9|;

</details>

**Comment by gregg-miskelly** [comment]
This extension doesn't support running on Alpine. But you can use the remote debugger, which does support Alpine: https://github.com/OmniSharp/omnisharp-vscode/wiki/Attaching-to-remote-processes
