### ISSUE TITLE
IntelliSense not working with Unity, since omnisharp can't start up / Ubuntu 18.04

### ISSUE THREAD

**Issue by RipplB** [OmniSharp/omnisharp-vscode#3542]
## Environment data
`dotnet --info` output:

 .NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version: 1.41.1
C# Extension version: 1.21.9

### 1. Having Mono installed
`$apt show mono-devel `
Package: mono-devel
Version: 4.6.2.7+dfsg-1ubuntu1
Priority: optional
Section: universe/devel
Source: mono
Origin: Ubuntu

`$mono hello.exe`
Hello Mono World

### 3. Try opening one, I even tried in Unity `Assets -> Open C# project`
Now my file structure also has alll the .csproj and even a .sln files

## Expected  behavior
Working all right?

### OmniSharp log in VScode be like:
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file: *my project path*/Assembly-CSharp.csproj // I actually have that

/.vscode/extensions/ms-vscode.csharp-1.21.9/.omnisharp/1.34.11-beta.7/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1191,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

After these it tries again and fails the same way

**Comment by JoeRobich** [comment]
Hi @RipplB, The minimal version of Mono included with the extension does not work with all project types. It is recommended to install the stable version of Mono for your platform. https://www.mono-project.com/download/stable/#download-lin

**Comment by RipplB** [comment]
@JoeRobich  Oh yeah sorry i have written an old thing. I have also did `apt install mono-complete`

**Comment by RipplB** [comment]
I also have a tip, what might go wrong. So as omnisharp server starts setting up, it has a long log, and theres an info line:
`Registered MSBuild instance: StandAlone 16.3 - "/home/balazs/.vscode/extensions/ms-vscode.csharp-1.21.9/.omnisharp/1.34.11-beta.7/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/balazs/.vscode/extensions/ms-vscode.csharp-1.21.9/.omnisharp/1.34.11-beta.7/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/balazs/.vscode/extensions/ms-vscode.csharp-1.21.9/.omnisharp/1.34.11-beta.7/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/balazs/.vscode/extensions/ms-vscode.csharp-1.21.9/.omnisharp/1.34.11-beta.7/omnisharp/.msbuild
`
This thing: `CscToolExe = csc.exe`
 csc is unavailable for me on command line too, i can only use msc. But i dont know how to tell to use msc instead of csc.

**Comment by JoeRobich** [comment]
@RipplB, What is confusing is that we are falling back to the built-in Mono instead of your local install. Can you run `mono --version` and report which version installed? If it is under 6.4.0 can you install the latest stable build?

**Comment by RipplB** [comment]
Oh yes it was 4.6 or something. Uninstalled everything i could find, then installed it again. Might've missed a key registration or something. Now it's 6.8. Thank you very much for your help!

**Comment by aryan29** [comment]
Hello can someone help me I am facing same issue
Ubuntu - 18.04
mono version -> 6.10.0.104
Unity Version -> 2019.4.2f1
Code verison -> 1.46.1

Please help

**Comment by JoeRobich** [comment]
@aryan29 Can you open a new issue for the problem you are experiencing? Be sure to include the OmniSharp log from the output pane. Thanks!

**Comment by sanjay-ashok** [comment]
> Ubuntu - 18.04
> mono version -> 6.10.0.104
> Dotnet verison -> 3.1.301
> Unity Version -> 2019.4.2f1
> Code verison -> 1.46.1

Hi @aryan29, even i face the same issue did it resolve for you?
