### ISSUE TITLE
Debugger no longer working

### ISSUE THREAD

**Issue by RononDex** [OmniSharp/omnisharp-vscode#3544]
## Issue Description ##
The debugger keeps stopping instantly everytime I try to start a debugging session, with this output in the "Debug Console":
```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
```

Note, I am using the official, closed source release from vscode from microsoft (no vscodium or similiar):
![image](https://user-images.githubusercontent.com/2249071/73549995-16405080-4444-11ea-8896-abf6ab8b3697.png)

## Steps to Reproduce ##
Try to debug anything

## Expected Behavior ##
Debugger works

## Actual Behavior ##
Debugger stops instantly

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.41.1
**C# Extension**: 1.21.9

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|1987|annliu|0.3.1|
|2077-theme|Endormi|1.4.2|
|add-reference|adrianwilczynski|1.0.2|
|auto-using|Fudge|0.7.9|
|better-align|wwm|1.1.6|
|Bookmarks|alefragnani|10.7.0|
|calmness-vsc-theme|azamuddin|1.1.1|
|city-lights-theme|yummygum|1.1.5|
|cloudcode|googlecloudtools|1.0.1|
|code-settings-sync|Shan|3.4.3|
|code-spell-checker|streetsidesoftware|1.7.22|
|codesnap|adpyke|1.0.27|
|csharp|ms-vscode|1.21.9|
|csharp-grammar-extended|dannymcgee|1.1.1|
|csharp-model-to-builder|frasercrosbie|0.1.2|
|csharpextensions|jchannon|1.3.1|
|Cyberpunk|max-SS|1.2.5|
|docomment|k--kato|0.1.8|
|dotnet|formulahendry|0.0.4|
|dotnet-core-essentials|KishoreIthadi|0.0.8|
|dotnet-test-explorer|formulahendry|0.7.1|
|EditorConfig|EditorConfig|0.14.4|
|eva-theme|fisheva|0.7.9|
|git-graph|mhutchie|1.21.0|
|git-tree-compare|letmaik|1.7.1|
|gitlens|eamodio|10.2.0|
|graphql-for-vscode|kumar-harsh|1.15.3|
|gruvbox|jdinhlife|1.4.0|
|horizon-theme-vscode|jolaleye|2.0.2|
|ilspy-vscode|icsharpcode|0.7.10|
|jinja|wholroyd|0.0.8|
|jira-plugin|gioboa|0.19.0|
|latex-utilities|tecosaur|0.3.4|
|latex-workshop|James-Yu|8.7.1|
|material-icon-theme|PKief|3.9.2|
|material-theme|zhuangtongfa|3.2.1|
|mdx|silvenon|0.1.0|
|midnight-city|dillonchanis|0.5.0|
|msbuild-project-tools|tintoy|0.3.3|
|mssql|ms-mssql|1.8.0|
|namespace|adrianwilczynski|1.1.2|
|noctis|liviuschera|10.26.0|
|output-colorizer|IBM|0.1.2|
|prettier-vscode|esbenp|3.20.0|
|python|ms-python|2020.1.58038|
|python-extension-pack|donjayamanne|1.6.0|
|rainbow-brackets|2gua|0.0.6|
|slime|smlombardi|3.2.1|
|sqltools|mtxr|0.21.6|
|stylelint|shinnn|0.51.0|
|supersharp|craigthomas|0.1.4|
|synthwave-vscode|RobbOwen|0.0.7|
|team|ms-vsts|1.161.0|
|theme-onedark|azemoh|0.5.3|
|theme-panda|tinkertrain|1.3.0|
|todo-tree|Gruntfuggly|0.0.167|
|vim|vscodevim|1.12.4|
|vscode-csharp-snippets|jorgeserrano|0.3.1|
|vscode-custom-css|be5invis|3.0.9|
|vscode-django|batisteo|0.19.0|
|vscode-docker|ms-azuretools|0.10.0|
|vscode-kanban|mkloubert|1.26.2|
|vscode-mdx-preview|xyc|0.2.2|
|vscode-nxunit-test-adapter|wghats|0.1.3|
|vscode-peacock|johnpapa|3.3.1|
|vscode-test-explorer|hbenl|2.15.0|
|vscode-theme-hydra|juanmnl|3.1.0|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|
|vscode-versionlens|pflannery|0.24.0|
|vscode-wakatime|WakaTime|2.2.1|
|vscodeilviewer|josephwoodward|0.0.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.4|
|vsliveshare|ms-vsliveshare|1.0.1510|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by gregg-miskelly** [comment]
Can you [enable logging](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging) and post your log?

**Comment by RononDex** [comment]
It is now working again, no idea why it suddenly stopped working and now works again 😕

**Comment by gregg-miskelly** [comment]
Okay, I will close this for now. Feel free to ping or open a new issue with just the logs if this comes back.
