### ISSUE TITLE
Omnisharp fails to load

### ISSUE THREAD

**Issue by steveoh** [OmniSharp/omnisharp-vscode#3545]
## Issue Description ##

Omnisharp fails to load

## Steps to Reproduce ##

Open dotnet project and look at log

## Expected Behavior ##

omnisharp should start

## Actual Behavior ##

image not found and the server times out when trying to load

## Logs ##

<details><summary>OmniSharp log</summary>

```sh
Starting OmniSharp server at 2/3/2020, 3:56:00 PM
    Target: /Users/-/dev/app

OmniSharp server started.
    Path: /Users/-/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.11-beta.9/run
    PID: 56441

dyld: Library not loaded: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/libintl.8.dylib
  Referenced from: /Users/-/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.11-beta.9/bin/mono
  Reason: image not found
/Users/-/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.11-beta.9/run: line 28: 56446 Abort trap: 6           "${mono_cmd}" "${omnisharp_cmd}" "$@"
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute)
```
</details>

<details><summary>C# log</summary>

```sh
Downloading package 'OmniSharp for OSX' (44823 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for OSX'

Downloading package '.NET Core Debugger (macOS / x64)' (41849 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (macOS / x64)'

Downloading package 'Razor Language Server (macOS / x64)' (50424 KB).................... Done!
Installing package 'Razor Language Server (macOS / x64)'

Finished

Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.34.11-beta.9...
Platform: darwin, x86_64

Downloading package 'OmniSharp for OSX, Version = 1.34.11-beta.9' (44823 KB).................... Done!
Installing package 'OmniSharp for OSX, Version = 1.34.11-beta.9'

Finished
```
</details>

## Environment information ##

**VSCode version**: 1.41.1
**C# Extension**: 1.21.10

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.2.207 [/usr/local/share/dotnet/sdk]
  2.2.300 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|alexa-skills-kit-toolkit|ask-toolkit|1.0.2|
|amvim|auiworks|1.30.0|
|ariake-dark|wart|0.2.2|
|bracket-pair-colorizer-2|CoenraadS|0.0.29|
|code-settings-sync|Shan|3.4.3|
|code-spell-checker|streetsidesoftware|1.7.22|
|colonize|vmsynkov|2.2.2|
|csharp|ms-vscode|1.21.10|
|debugger-for-chrome|msjsdiag|4.12.6|
|dotenv|mikestead|1.0.1|
|dotnet-test-explorer|formulahendry|0.7.1|
|EditorConfig|EditorConfig|0.14.4|
|folderize|ee92|0.0.5|
|gc-excelviewer|GrapeCity|2.1.32|
|ginfuru-vscode-jekyll-syntax|ginfuru|0.1.0|
|git-project-manager|felipecaputo|1.7.1|
|gitlens|eamodio|10.2.0|
|language-stylus|sysoev|1.11.0|
|mssql|ms-mssql|1.8.0|
|npm-intellisense|christian-kohler|1.3.0|
|output-colorizer|IBM|0.1.2|
|partial-diff|ryu1kn|1.4.1|
|pdf|tomoki1207|0.5.1|
|poor-mans-t-sql-formatter-vscode|TaoKlerks|1.6.10|
|powershell|ms-vscode|2020.1.0|
|python|ms-python|2020.1.58038|
|regex|chrmarti|0.2.0|
|slack-theme|felipe-mendes|1.9.11|
|terraform|mauve|1.4.0|
|turndown-vscode|kurre|1.0.2|
|vsc-community-material-theme|Equinusocio|1.4.0|
|vsc-material-theme|Equinusocio|32.4.0|
|vsc-material-theme-icons|equinusocio|1.1.3|
|vscode-coverage-gutters|ryanluker|2.4.3|
|vscode-css-formatter|aeschli|1.0.1|
|vscode-docker|ms-azuretools|0.10.0|
|vscode-eslint|dbaeumer|2.0.15|
|vscode-fileutils|sleistner|3.0.1|
|vscode-github-notifications-bell|fabiospampinato|2.3.1|
|vscode-icons|vscode-icons-team|9.7.0|
|vscode-jekyll-snippets|ginfuru|0.9.1|
|vscode-markdownlint|DavidAnson|0.34.0|
|vscode-npm-script|eg2|0.3.11|
|vscode-pull-request-github|GitHub|0.14.0|
|vscode-sort-json|richie5um2|1.18.0|
|vscode-stylint|HaaLeo|0.1.3|
|vscode-zipexplorer|slevesque|0.3.1|
|vsliveshare|ms-vsliveshare|1.0.1510|
|vsliveshare-audio|ms-vsliveshare|0.1.80|
|wordcount|ms-vscode|0.1.0|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by TopGuo** [comment]
the same question!
```
Starting OmniSharp server at 2020/2/4 上午11:37:01
    Target: /Users/topbrids/Desktop/yoyoService

OmniSharp server started.
    Path: /Users/topbrids/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/run
    PID: 1632

dyld: Library not loaded: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/libintl.8.dylib
  Referenced from: /Users/topbrids/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/bin/mono
  Reason: image not found
/Users/topbrids/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/run: line 28:  1637 Abort trap: 6           "${mono_cmd}" "${omnisharp_cmd}" "$@"
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```
### why image not found?

**Comment by TopGuo** [comment]
> the same question!
> 
> ```
> Starting OmniSharp server at 2020/2/4 上午11:37:01
>     Target: /Users/topbrids/Desktop/yoyoService
> 
> OmniSharp server started.
>     Path: /Users/topbrids/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/run
>     PID: 1632
> 
> dyld: Library not loaded: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/libintl.8.dylib
>   Referenced from: /Users/topbrids/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/bin/mono
>   Reason: image not found
> /Users/topbrids/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/run: line 28:  1637 Abort trap: 6           "${mono_cmd}" "${omnisharp_cmd}" "$@"
> [ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
> ```
> 
> ### why image not found?

## ENV
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.300/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.2.107 [/usr/local/share/dotnet/sdk]
  2.2.300 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
## November 2019 (version 1.41)

**Comment by TopGuo** [comment]
> the same question!
> 
> ```
> Starting OmniSharp server at 2020/2/4 上午11:37:01
>     Target: /Users/topbrids/Desktop/yoyoService
> 
> OmniSharp server started.
>     Path: /Users/topbrids/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/run
>     PID: 1632
> 
> dyld: Library not loaded: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/libintl.8.dylib
>   Referenced from: /Users/topbrids/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/bin/mono
>   Reason: image not found
> /Users/topbrids/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/run: line 28:  1637 Abort trap: 6           "${mono_cmd}" "${omnisharp_cmd}" "$@"
> [ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
> ```
> 
> ### why image not found?

i create a console pro,open with vs code,the problem still ...
![image](https://user-images.githubusercontent.com/30146744/73712301-a7653f00-4744-11ea-9ab4-f83a0a24414e.png)

**Comment by andrew-myob** [comment]
I'm getting this same issue. I've worked around it by setting `"omnisharp.useGlobalMono": "always"` and installing Mono via homebrew.

**Comment by TopGuo** [comment]
> I'm getting this same issue. I've worked around it by setting `"omnisharp.useGlobalMono": "always"` and installing Mono via homebrew.

the “Intelligent prompt” are you ok?

**Comment by TopGuo** [comment]
> I'm getting this same issue. I've worked around it by setting `"omnisharp.useGlobalMono": "always"` and installing Mono via homebrew.

`i only update mono the problem have sloved,but "omnisharp.useGlobalMono" still is default!`

#### brew update && brew install mono

```
Mono JIT compiler version 6.8.0.96 (tarball Thu Jan 16 04:16:52 GMT 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

**Comment by andrew-myob** [comment]
> > I'm getting this same issue. I've worked around it by setting `"omnisharp.useGlobalMono": "always"` and installing Mono via homebrew.
> 
> `i only update mono the problem have sloved,but "omnisharp.useGlobalMono" still is default!`
> 
> #### brew update && brew install mono
> ```
> Mono JIT compiler version 6.8.0.96 (tarball Thu Jan 16 04:16:52 GMT 2020)
> Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
> 	TLS:           
> 	SIGSEGV:       altstack
> 	Notification:  kqueue
> 	Architecture:  amd64
> 	Disabled:      none
> 	Misc:          softdebug 
> 	Interpreter:   yes
> 	LLVM:          supported, not enabled.
> 	Suspend:       hybrid
> 	GC:            sgen (concurrent by default)
> ```

True, I just removed my setting and it's still working.

**Comment by jeremysu0131** [comment]
Downgrade to ver 1.21.9 can prevent the problem temporary...

**Comment by filipw** [comment]
@JoeRobich would you mind looking into this? looks like it's related to https://github.com/OmniSharp/omnisharp-roslyn/pull/1679 - thanks!

**Comment by JoeRobich** [comment]
Looks like it was caused by this Mono issue - https://github.com/mono/mono/pull/18531. 

6.6.0.161 which is what we packaged seems to be the last 6.6.0 build. We need to revert back to 6.4.0 or bump to 6.8.0.

**Comment by filipw** [comment]
ouch. I reckon we could bump the bundled runtime to 6.8.0 that's also stable already.

**Comment by filipw** [comment]
The current workaround - if you are affected - would be to one of the following:

 - downgrade back to 1.21.9
 - install Mono 6.6.0 

I would personally recommend the latter since the MSBuild behavior with global Mono install on your machine would be better.

**Comment by steveoh** [comment]
Looks like i need a mono upgrade...

```sh
$ mono --version
Mono JIT compiler version 5.12.0.301 (2018-02/4fe3280bba1 Fri Jul 20 08:25:42 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)
```

**Comment by filipw** [comment]
I think it should stay open until we patch this

**Comment by tverboon** [comment]
What is the reason mono is being used and not .Net Core?

**Comment by filipw** [comment]
not all MSBuild tasks would work on .NET Core which would impact non-.NET Core projects.

**Comment by steveoh** [comment]
so i am safe to install mono from homebrew and have it stay current now?

**Comment by steveoh** [comment]
@filipw am I safe to install mono from homebrew and have it stay current now?

**Comment by Bio-Tvorogok** [comment]
> I'm getting this same issue. I've worked around it by setting `"omnisharp.useGlobalMono": "always"` and installing Mono via homebrew.


God, man, you're my savior, I almost got to the point of removing the system))

**Comment by brnhensley** [comment]
I was having the same issue for a few months now and my problem was solved by changing `"omnisharp.waitForDebugger": true` to `false`. I'm not sure what the original cause was but finally the omnisharp server stopped timing out.

**Comment by MrDave1999** [comment]
> I'm getting this same issue. I've worked around it by setting "omnisharp.useGlobalMono": "always" and installing Mono via homebrew.

This solved my problem, thank you!

**Comment by steveoh** [comment]
isn't there a dotnet core implementation now that does not need mono at all?

**Comment by JoeRobich** [comment]
Mono and MSBuild are no longer included with nightly builds of O#. See the announcement at https://github.com/OmniSharp/omnisharp-vscode/issues/5120
