### ISSUE TITLE
OmniSharp failed integrity check

### ISSUE THREAD

**Issue by dwolf4** [OmniSharp/omnisharp-vscode#3548]
## Issue Description ##
OmniSharp failed integrity check
## Steps to Reproduce ##
Open VS code.   Tried Installing the previous version and I am now getting the same integrity  failure.  I have also rebooted.
## Expected Behavior ##
Omnisharp Starts and able to debug code.

## Actual Behavior ##
Given error message stating that C# extension failed to load. 

### OmniSharp log ###
Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (31901 KB).................... Done!
Validating download...
Package OmniSharp for Windows (.NET 4.6 / x64) failed integrity check. Retrying..
Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (31901 KB).................... Done!
Validating download...
Package OmniSharp for Windows (.NET 4.6 / x64) download from https://download.visualstudio.microsoft.com/download/pr/b146ec31-8d19-45ca-96ff-d04a8b436b25/24bc14b24a159bd155a0a82560a9bbb4/omnisharp-win-x64-1.34.10.zip failed integrity check. Some features may not work as expected. Please restart Visual Studio Code to retrigger the download.
Downloading package '.NET Core Debugger (Windows / x64)' (41930 KB).................... Done!
Validating download...
Package .NET Core Debugger (Windows / x64) failed integrity check. Retrying..
Downloading package '.NET Core Debugger (Windows / x64)' (41930 KB)............

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.41.1
**C# Extension**: 1.21.10

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.10|
|Go|ms-vscode|0.13.0|
|remote-wsl|ms-vscode-remote|0.41.9|
|vscode-docker|ms-azuretools|0.10.0|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.0.9|
|vscode-yaml|redhat|0.6.1|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by barticus** [comment]
I'm seeing a similar, but maybe separate, issue on Mac OSX
```
Starting OmniSharp server at 2/5/2020, 10:49:58 AM
    Target: /Users/me/git/billd/billd-server/service/service.sln

OmniSharp server started.
    Path: /Users/me/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.11-beta.9/run
    PID: 2725

dyld: Library not loaded: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/libintl.8.dylib
  Referenced from: /Users/me/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.11-beta.9/bin/mono
  Reason: image not found
/Users/me/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.11-beta.9/run: line 28:  2730 Abort trap: 6           "${mono_cmd}" "${omnisharp_cmd}" "$@"
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```
Or, removing the `"omnisharp.path": "latest"` setting:
```
Starting OmniSharp server at 2/5/2020, 10:56:21 AM
    Target: /Users/me/git/billd/billd-server/service/service.sln

OmniSharp server started.
    Path: /Users/me/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/run
    PID: 2753

dyld: Library not loaded: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/libintl.8.dylib
  Referenced from: /Users/me/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/bin/mono
  Reason: image not found
/Users/me/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/run: line 28:  2758 Abort trap: 6           "${mono_cmd}" "${omnisharp_cmd}" "$@"
```

**Comment by dwolf4** [comment]
@barticus I think that is a Mono releated I noticed in issue   #3545 
I have done some more digging and belive this is related to an update in my companies Anti-Virus/Web Filtering. While It does not block the actual download, it is intefering in the integrity check workflow.

I am closing this since I do not belive this is correct place and instead its a VS Code behavoir with the integeteirty checks.
