### ISSUE TITLE
The .NET CLI did not correctly restore debugger files.

### ISSUE THREAD

**Issue by asadsahi** [OmniSharp/omnisharp-vscode#355]
## Steps to reproduce
1) Installed latest version of vscode

![image](https://cloud.githubusercontent.com/assets/3470892/15423149/1bb655c2-1e74-11e6-818a-df50f7d910c1.png)

2) Install latest version of c# extension
![image](https://cloud.githubusercontent.com/assets/3470892/15423286/a0fca90c-1e74-11e6-9a17-9d51d92a6a3b.png)

3) When opening an aspnet core project, vscode tries to install .net core debugger, but failing:
![image](https://cloud.githubusercontent.com/assets/3470892/15423194/488fed6a-1e74-11e6-9321-e3a04703e36c.png)

## Expected  behavior
Debugger should be installed successfully.

## Actual behavior
Debugger not installing on windows 7

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002374)

Product Information:
 Version:     1.0.0-rc2-002374
 Commit Sha:  f82da07fc4

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

**Comment by chuckries** [comment]
Your version of the .NET CLI is out of date. Please uninstall your current CLI through Add/Remove programs and install the RC2 CLI from [here](https://www.microsoft.com/net/core#windows).

**Comment by asadsahi** [comment]
I have installed from the same location, but the version isn't being updated. I have removed the dotnet cli from add/remove programs and then did a fresh install. After I have uninstalled it doesn't recognize the dotnet in the command prompt anymore, and when I install it again, it doesn't upgrade the version. Even strange thing is that from same installer location I have instaled on windows 10 machine and it show sthe correct version as below:

![image](https://cloud.githubusercontent.com/assets/3470892/15444352/822c77dc-1ee7-11e6-9f34-50b7dc57d410.png)

The only other existence on windows 7 machine is that I have updated the visual studio tooling to RC2 as well.

How can I cleanly install to reflect the correct cli version on windows 7 where I am having issue?

Thanks

**Comment by gregg-miskelly** [comment]
@asadsahi I might suggest asking on https://github.com/dotnet/cli

**Comment by asadsahi** [comment]
Thanks @gregg-miskelly & @chuckries 

![image](https://cloud.githubusercontent.com/assets/3470892/15444452/cd83d3e6-1ee8-11e6-9ee6-6ae50f29551b.png)

this was causing the issue. Old version keeps itself even removed using add/remove programs and dotnet command line was picking up old version, manually deleted the old version directory and it works as expected.
