### ISSUE TITLE
Cannot suppress code analysis rules with code actions

### ISSUE THREAD

**Issue by webczat** [OmniSharp/omnisharp-vscode#3550]
From what I know, code analyzer rules can be suppressed in many ways incl. editorconfig (doesn't seem to work here). The documentation of vs talks about the fact that there is a code action for suppressing code analyser rules, however it does not show in vscode when invoking code action list for rule violations. I got the info that this is implemented in roslyn, so is not vs specific.

**Comment by filipw** [comment]
Editorconfig *is* supported in OmniSharp - see https://www.strathweb.com/2019/07/editorconfig-support-in-omnisharp-and-c-extension-vs-code/

however, the way to control analyzer severity via editorconfig is currently not supported (this is a fairly new feature in Roslyn that only came in VS 16.3).
it is tracked by https://github.com/OmniSharp/omnisharp-roslyn/issues/1657 so I will close this as duplicate.

As a workaround you can still use rulesets and those will be supported in OmniSharp.
