### ISSUE TITLE
Omnisharp on macos crashing after update to 1.21.10

### ISSUE THREAD

**Issue by rleopold** [OmniSharp/omnisharp-vscode#3551]
## Issue Description ##
When opening any C# file Omnisharp crashes. This started happening as soon as Omnisharp updated to 1.21.10. 

## Steps to Reproduce ##
Update Omnishrap VS code plugin to 1.21.10. Open any C# file. Was able to recreate this on two machines so far.

## Expected Behavior ##
Omnisharp loads as normal

## Actual Behavior ##
Omnisharp crashes

### OmniSharp log ###
<details>Starting OmniSharp server at 2/5/2020, 10:10:36 AM
    Target: /Users/richard.leopold/code/match/MatchEvents/api/api.sln

OmniSharp server started.
    Path: /Users/richard.leopold/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/run
    PID: 19386

dyld: Library not loaded: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/libintl.8.dylib
  Referenced from: /Users/richard.leopold/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/bin/mono
  Reason: image not found
/Users/richard.leopold/.vscode/extensions/ms-vscode.csharp-1.21.10/.omnisharp/1.34.10/run: line 28: 19391 Abort trap: 6           "${mono_cmd}" "${omnisharp_cmd}" "$@"
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).</details>

### C# log ###
none

## Environment information ##

**VSCode version**: 1.41.1
**C# Extension**: 1.21.10

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.2.301 [/usr/local/share/dotnet/sdk]
  2.2.402 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.10|
|debugger-for-chrome|msjsdiag|4.12.6|
|dotnet-test-explorer|formulahendry|0.7.1|
|vscode-docker|ms-azuretools|0.10.0|;

</details>

**Comment by filipw** [comment]
this is a duplicate, see https://github.com/OmniSharp/omnisharp-vscode/issues/3545#issuecomment-581890589

it's already fixed on the master branch too, release should follow soon hopefully cc @JoeRobich

**Comment by rleopold** [comment]
Thanks. I'll close this one.
