### ISSUE TITLE
Work Offline

### ISSUE THREAD

**Issue by Gwom** [OmniSharp/omnisharp-vscode#3556]
Could you cache the last version you download and if offline, use the cached version (after trying to get the new version for say 5 seconds)?

I often try to do coding in an offline environment, and if I boot up VS Code when offline, i cant really code well as don't have your awesome plugin. I have seen some steps to do a work around, but they are not intuitive and it would be amazing if you could handle this situation. 

Thanks!

## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Steps to reproduce
Boot up VS Code offline, if it cant get the latest version it doesn't use an older cached version, it just doesn't work.

## Expected  behavior
Use a cached version

## Actual behavior
It doesn't load and therefore cannot be used.

**Comment by gregg-miskelly** [comment]
Hi @Gwom what you are suggesting isn't possible - there is no cached version. However, the VS Code team is planning to support platform-specific extension downloads (see https://github.com/microsoft/vscode/issues/23251). Once that support is added, and this extension has a chance to adopt that work, then the whole dependency download problem will go away.
