### ISSUE TITLE
[Support decompiled sources with Go to Definition] - Is there any way to quickly jump to the corresponding point of the source file?

### ISSUE THREAD

**Issue by HeebeLee** [OmniSharp/omnisharp-vscode#3559]
Thank you to all the developers.

I use Mac to develop .Net Core. I need to understand .Net Core. So I think when I look at a library class, I can see the source code.

My idea is that when I click the corresponding method name by holding command, I can jump to the corresponding location of the source code of the .Net Core that I have downloaded? So I can see the implementation.

**Comment by cartermp** [comment]
Renaming the issue for clarity - this is tracked as a feature request. Today you can Go to Definition and get metadata as source in a new window, but we don't have what Visual Studio (Windows) has where it uses ILSpy to decompile that metadata and let you see the decompiled source. That should be a feature.

**Comment by filipw** [comment]
@cartermp this should be moved to omnisharp roslyn repo as it's entirely a server side issue.
we have a feature branch underway to add that https://github.com/filipw/omnisharp-roslyn/tree/feature/decompile

**Comment by filipw** [comment]
WIP

 ![](http://g.recordit.co/IEWQ1pah5p.gif)

**Comment by cartermp** [comment]
@filipw awesome. Is there a tracking issue on the omnisharp side?

**Comment by filipw** [comment]
no, we can move this one or if you want to keep it here to track the feature on the extension side too, I will create a new one

**Comment by cartermp** [comment]
This repo seems to get the most activity, so keeping it here seems reasonable enough.

**Comment by HeebeLee** [comment]
@filipw @cartermp 
This is really great. I am looking forward.
thx.

**Comment by filipw** [comment]
the feature branch is here https://github.com/OmniSharp/omnisharp-roslyn/tree/feature/decompile

**Comment by filipw** [comment]
This is now implemented in OmniSharp 1.35.0 and extension 1.21.7

**Comment by cartermp** [comment]
Thanks, closing!

**Comment by ssoher** [comment]
I'm still seeing metadata when I "Go to Definition" into a symbol in a dll. 
Below is what vscode with C# extension shows vs what Resharper shows when I go to a definition in UnityEngine dll. Is there an option or something I have to toggle to enable the decompiler?

**Resharper**
![resharper](https://user-images.githubusercontent.com/4283979/80982210-ac18bc80-8e33-11ea-89f5-f43e1efb34c1.jpg)
**VSCode**
![vscode](https://user-images.githubusercontent.com/4283979/80982213-ad49e980-8e33-11ea-81ae-65376624c86f.jpg)

**Comment by JoeRobich** [comment]
@ssoher There is an option you can apply to your omnisharp.json to enable decompilation. We plan to add a setting in the C# extension to enable this, but have to work out a disclaimer for the legal side of things. From the omnisharp changelog:

* Added support for decompilation based on ILSpy (similar to VS). The feature is currently opt-into and needs to be enabled using OmniSharp configuration (PR: #1751)
```json
    {
        "RoslynExtensionsOptions": {
            "enableDecompilationSupport": true
        }
    }
```
