### ISSUE TITLE
"Sdk" is not a valid attribute for a "Project" element.

### ISSUE THREAD

**Issue by Frefreak** [OmniSharp/omnisharp-vscode#3564]
## Issue Description ##

omnisharp-vscode doesn't seem to recognize this attr. The content of my csproj has this at the beginning, which is generated by `dotnet new classlib`. The project can be built using `dotnet build`
without issue, but when opened in vscode it gives the error (see title).

```
<Project Sdk="Microsoft.NET.Sdk">
```

## Steps to Reproduce ##

`dotnet new classlib -o asdf` to generate a new project

## Expected Behavior ##
All files should be "clean" (no error) in vscode

## Actual Behavior ##
csproj file goes red and has error **"Sdk" is not a valid attribute for a "Project" element.**

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.42.0
**C# Extension**: 1.21.11

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.403 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|code-runner|formulahendry|0.9.15|
|cpptools|ms-vscode|0.26.3|
|csharp|ms-vscode|1.21.11|
|csharpextensions|jchannon|1.3.1|
|csharpfixformat|Leopotam|0.0.84|
|dotnet|formulahendry|0.0.4|
|dotnet-core-commands|matijarmk|1.0.6|
|dotnet-core-essentials|KishoreIthadi|0.0.8|
|ilspy-vscode|icsharpcode|0.7.10|
|msbuild-tools|sterin|0.0.9|
|python|ms-python|2020.1.58038|
|qub-msbuild|qub|0.6.3|
|vim|vscodevim|1.12.4|
|vscode-csproj|lucasazzola|0.7.0|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-solution-explorer|fernandoescolar|0.3.7|
|vscodeilviewer|josephwoodward|0.0.1|;

</details>

**Comment by filipw** [comment]
I don't think this is caused by this extension since we don't report any errors for csproj file.
Check the other extensions you have installed for example vscode-csproj or qub-msbuild.

**Comment by Frefreak** [comment]
Thanks, qub-msbuild is the one to blame. It seems the last time it updated is 2017 :(
