### ISSUE TITLE
[Request] Provide tokens for VS Code semantic syntax highlighting

### ISSUE THREAD

**Issue by dannymcgee** [OmniSharp/omnisharp-vscode#3565]
[Semantic highlighting](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview) is finally in preview as of VS Code 1.42.0. C# is an ideal candidate for taking advantage of this feature, as the available TextMate grammar is pretty lacking, and the syntax of C# is such that it's impossible to accurately classify many tokens with a simple line-by-line regex parser.

- [SemanticTokensProvider API (proposed)](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview)
- [Basic extension sample](https://github.com/microsoft/vscode-extension-samples/tree/master/semantic-tokens-sample)
- [VS Code's implementation of semantic tokens for JavaScript](https://github.com/microsoft/vscode/blob/master/extensions/html-language-features/server/src/modes/javascriptSemanticTokens.ts)

I'd love to help out with this, but I'm not at all familiar with the codebase here. If this is a feature you would like to support, I'd be more than happy to open a PR if someone would be willing to provide some guidance or a push in the right direction.

**Comment by JoeRobich** [comment]
@dannymcgee Please try out the [1.21.19-beta1 prerelease](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.19-beta1)

**Comment by JoeRobich** [comment]
Closing as SemanticHighlighting is available in the 1.22.0 release.
