### ISSUE TITLE
Omnisharp displays errors of source files in obj folder

### ISSUE THREAD

**Issue by ThadHouse** [OmniSharp/omnisharp-vscode#3568]
## Issue Description ##
I am using a .NET Standard 2.0 project, and adding the `Nullable` package in order to get the new nullable attributes (https://github.com/manuelroemer/Nullable). It does this by adding source files to the build, which then get included. However, after the first build, omnisharp picks up these attributes as being available to the build, in addition to error checking those source files. This causes multiple duplicate class errors, because the engine sees the same classes twice in the same compilation unit. A screenshot of this can be seen below, with many more errors as well.

![Capture](https://user-images.githubusercontent.com/7727148/74204758-50baa200-4c29-11ea-9adb-edf429238c98.PNG)

## Steps to Reproduce ##

1. Create a .NET Standard 2.0 project (Can be classlib or console).
2. Add `Nullable` `dotnet add package Nullable`
4. Run a build

## Expected Behavior ##

Multiple definition errors will be displayed

## Actual Behavior ##

No errors

### OmniSharp log ###

There is nothing in the omnisharp log but project loading logs

### C# log ###

C# log is empty.

## Environment information ##

**VSCode version**: 1.42.0
**C# Extension**: 1.21.11

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.26.3|
|csharp|ms-vscode|1.21.11|
|debugger-for-chrome|msjsdiag|4.12.6|
|java|redhat|0.55.1|
|powershell|ms-vscode|2020.1.0|
|remote-wsl|ms-vscode-remote|0.42.3|
|vscode-coverage-gutters|ryanluker|2.4.3|
|vscode-express|Compulim|0.0.5|
|vscode-hexdump|slevesque|1.7.2|
|vscode-icons|vscode-icons-team|9.7.0|
|vscode-java-debug|vscjava|0.24.0|
|vscode-java-dependency|vscjava|0.8.0|
|vscode-java-pack|vscjava|0.8.1|
|vscode-java-test|vscjava|0.22.1|
|vscode-javap|gmr|0.0.2|
|vscode-maven|vscjava|0.21.0|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|
|vscode-wpilib|wpilibsuite|2020.2.2|;

</details>

**Comment by cartermp** [comment]
Hello, I can't reproduce this with the latest .NET 5 preview, your repro steps, and an added `<LangVersion>` set to 8 or higher. Do you have a project where this occurs that you can share? FWIW this isn't considered a supported scenario, so other issues related to nullable reference types and .NET Standard 2.0 are unlikely to be fixed.
