### ISSUE TITLE
In .NET Core solution (C#), F12 does not move the cursor to the method declaration

### ISSUE THREAD

**Issue by BurstX** [OmniSharp/omnisharp-vscode#3571]
Issue Type: <b>Bug</b>

1. Download the [dotnet/sdk](https://github.com/dotnet/sdk) repo as of commit 5969952bbad327f92157665ebe6fe5ae4d35f425 (I just did "Clone or download"=>"Download ZIP" at 2020-02-12 14:16:58 GMT+3)
1. Open file src\Cli\Microsoft.DotNet.Cli.Utils\Command.cs
1. Set cursor on the method identifier in line 35 (i.e. inside the word 'Execute'):
```csharp
return Execute(_ => { });
```
4. Press F12

**Expected result:**
the cursor goes to the line 37 where the method Execute(Action\<Process\>) is defined

**Actual result:**
the cursor goes to the line 33 where the method Execute() is defined

Extension version: 1.21.11
VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (4.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by JoeRobich** [comment]
Hi @BurstX, Can you post the OmniSharp log from the VS Code Output pane? It contains information that will let us know if the project loaded successfully.

**Comment by BurstX** [comment]
Well, today I tried to open the project folder again and noticed the popups:
![image](https://user-images.githubusercontent.com/3790231/74411352-0cf3b280-4e4c-11ea-833d-41aa21398d34.png)
After clicking (1) and then (2) and waiting for all the corresponding actions to finish, it all became good.
