### ISSUE TITLE
Remote attach to process doesn't support input variables in `pipeArgs`

### ISSUE THREAD

**Issue by maxd** [OmniSharp/omnisharp-vscode#3575]
## Issue Description ##

Looks like `pipeArgs` doesn't support VSCode [input variables](https://code.visualstudio.com/docs/editor/variables-reference#_input-variables). For example the following configuration:

```
        "pipeArgs": [
          "-f", "Development.yml", "exec", "-T", "${input:serviceName}"
        ]

...

  "inputs": [
    {
      "type": "pickString",
      "id": "serviceName",
      "description": "Service to Debug",
      "options": [
        "service1",
        "service2"
      ],
      "default": "service1"
    }
  ]


```

return the following output:

```
Executing: docker-compose -f Development.yml exec -T ${input:serviceName} sh -s < /Users/xxx/.vscode/extensions/ms-vscode.csharp-1.21.11/scripts/remoteProcessPickerScript
```

When I run debug in VSCode it doesn't show pop-up dialog to configure input variables and just run debug command.

## Steps to Reproduce ##

1. Create `launch.json` with input variable in `pipeArgs` option
1. Run debug

## Expected Behavior ##

VSCode should show popup-dialog to choose input variable.

## Actual Behavior ##

VSCode doesn't show popup-dialog to choose input variable.

### OmniSharp log ###
```
Executing: docker-compose -f Development.yml exec -T ${input:serviceName} sh -s < /Users/xxx/.vscode/extensions/ms-vscode.csharp-1.21.11/scripts/remoteProcessPickerScript
stderr: No such service: sh
```

## Environment information ##

**VSCode version**: 1.41.1
**C# Extension**: 1.21.11

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.100 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.11|
|intellij-idea-keybindings|k--kato|0.2.37|
|vscode-docker|ms-azuretools|0.10.0|;

</details>

**Comment by maxd** [comment]
So, how do you think is it real to implement support of input variables in this extension? It can significantly simplify debug configuration.

**Comment by Soarex16** [comment]
Any progress on this feature?

**Comment by gregg-miskelly** [comment]
@Soarex16 to make sure, you are also asking for this in cases where the attach to process dialog is used?

The only way I can think to fix this is to change how the attach dialog is hooked up in these cases so that instead of working as part of the command, instead the extension will implement resolveDebugConfigurationWithSubstitutedVariables (see https://github.com/microsoft/vscode/issues/87450 for more info) and if configuration is of some new special form it will put up the attach to process quick pick that way.

**Comment by Soarex16** [comment]
> @Soarex16 to make sure, you are also asking for this in cases where the attach to process dialog is used?
> 
> The only way I can think to fix this is to change how the attach dialog is hooked up in these cases so that instead of working as part of the command, instead the extension will implement resolveDebugConfigurationWithSubstitutedVariables (see [microsoft/vscode#87450](https://github.com/microsoft/vscode/issues/87450) for more info) and if configuration is of some new special form it will put up the attach to process quick pick that way.

Yes, that's will solve the problem

**Comment by gregg-miskelly** [comment]
I believe this will be addressed by https://github.com/OmniSharp/omnisharp-vscode/pull/4509

**Comment by gregg-miskelly** [comment]
@WardenGnaw Should this issue be resolved?

**Comment by WardenGnaw** [comment]
Yep. Tested with a `promptString` input.
