### ISSUE TITLE
Blazor Components not found when working in multi-root workspace

### ISSUE THREAD

**Issue by thomasrea0113** [OmniSharp/omnisharp-vscode#3576]
## Issue Description ##

When a Blazor application is added to a multi-root workspace, the `.razor` pages no longer find existing components.

## Steps to Reproduce ##

1. scaffold blazor server project with `dotnet new blazorserver`
2. open folder by itself in VSCode
3. Ctrl-Shift-P -> Workspaces: Add folder to workspace
4. Add any folder (even an empty folder)

## Expected Behavior ##

![image](https://user-images.githubusercontent.com/14018447/74459877-08ce9180-4e5a-11ea-977b-51f95b192574.png)

## Actual Behavior ##

![image](https://user-images.githubusercontent.com/14018447/74459947-1f74e880-4e5a-11ea-9743-eeeb2f2f89c9.png)

### OmniSharp log ###
<details>Starting OmniSharp server at 2/13/2020, 12:12:17 PM
    Target: c:\Users\reat\Documents\Personal\repos\pr-leaderboard\BlazorTest

OmniSharp server started.
    Path: C:\Users\reat\.vscode\extensions\ms-vscode.csharp-1.21.11\.omnisharp\1.34.11\OmniSharp.exe
    PID: 12140

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 3 MSBuild instance(s)
            1: Visual Studio Enterprise 2019 16.4.29709.97 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
            2: Visual Studio Build Tools 2017 15.9.28307.960 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            3: StandAlone 16.3 - "C:\Users\reat\.vscode\extensions\ms-vscode.csharp-1.21.11\.omnisharp\1.34.11\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Enterprise 2019 16.4.29709.97 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\reat\Documents\Personal\repos\pr-leaderboard\BlazorTest'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\reat\Documents\Personal\repos\pr-leaderboard\BlazorTest'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\reat\Documents\Personal\repos\pr-leaderboard\BlazorTest\BlazorTest.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\reat\Documents\Personal\repos\pr-leaderboard\BlazorTest'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\reat\Documents\Personal\repos\pr-leaderboard\BlazorTest\BlazorTest.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\reat\Documents\Personal\repos\pr-leaderboard\BlazorTest' on host 3568.
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\Users\reat\Documents\Personal\repos\pr-leaderboard\BlazorTest\App.razor__virtual.cs added to workspace
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\reat\Documents\Personal\repos\pr-leaderboard\BlazorTest\BlazorTest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\reat\Documents\Personal\repos\pr-leaderboard\BlazorTest\BlazorTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: BlazorTest
</details>

### C# log ###
<details>EMTPY</details>

## Environment information ##

**VSCode version**: 1.42.0
**C# Extension**: 1.21.11

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.11|
|csharpextensions|jchannon|1.3.1|
|docomment|k--kato|0.1.8|
|dotnet-test-explorer|formulahendry|0.7.1|
|prettier-vscode|esbenp|3.20.0|
|sqltools|mtxr|0.21.6|
|todo-tree|Gruntfuggly|0.0.167|
|vscode-jest|Orta|3.1.1|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by NTaylorMullen** [comment]
@thomasrea0113 this is a great issue! Would you mind moving it over in https://github.com/dotnet/aspnetcore/issues so we can fix it appropriately?

**Comment by thomasrea0113** [comment]
https://github.com/dotnet/aspnetcore/issues/19013

moved
