### ISSUE TITLE
Quick Fix: Rename Type with Filename replaces class name not related with error

### ISSUE THREAD

**Issue by seongwon-kang** [OmniSharp/omnisharp-vscode#3589]
## Issue Description ##
![20-13-20 03 13 12](https://user-images.githubusercontent.com/56567660/74906169-89aa0200-53f3-11ea-93d8-d7295aed35ec.gif)

## Steps to Reproduce ##
1. create new csproj `dotnet new nunit`
2. create an arbitrary folder
3. copy `UnitTest1.cs` (auto-created) to folder
4. rename copied file with name (ex: `UnitTest2.cs`)
5. open `Quick Fix`, and select `Rename Type with Filename` (I don't know it's original name)
## Expected Behavior ##
Only classname of copied file will change
## Actual Behavior ##
Class name of original file changed

### OmniSharp log ###
(no log available)

### C# log ###
(no log available)

## Environment information ##

**VSCode version**: 1.42.1
**C# Extension**: 1.21.11

<details><summary>Dotnet Information</summary>
.NET Core SDK(global.json �ݿ�):
 Version:   3.1.101
 Commit:    b377529961

��Ÿ�� ȯ��:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|autodocstring|njpwerner|0.4.0|
|cloudcode|googlecloudtools|1.1.2|
|csharp|ms-vscode|1.21.11|
|csharpextensions|jchannon|1.3.1|
|docomment|k--kato|0.1.8|
|dotnet-test-explorer|formulahendry|0.7.1|
|ftp-simple|humy2833|0.7.5|
|increment-selection|albymor|0.2.0|
|java|redhat|0.56.0|
|jenkinsfile-support|ivory-lab|0.4.4|
|python|ms-python|2020.2.63072|
|remote-wsl|ms-vscode-remote|0.42.3|
|testfile-generator-for-junit|marcoLee|0.0.7|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-snippets|YclepticStudios|0.1.2|
|vsc-mybatis|niko|1.2.0|
|vsc-travis-ci-status|felixrieseberg|1.1.0|
|vscode-docker|ms-azuretools|0.10.0|
|vscode-java-debug|vscjava|0.24.0|
|vscode-java-dependency|vscjava|0.8.0|
|vscode-java-pack|vscjava|0.8.1|
|vscode-java-test|vscjava|0.22.1|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.0.9|
|vscode-lombok|GabrielBB|1.0.1|
|vscode-maven|vscjava|0.21.0|
|vscode-openapi|42Crunch|2.1.0|
|vscode-position|jtr|1.0.1|
|vscode-postman|eridem|1.0.2|
|vscode-yaml|redhat|0.7.2|
|vscodeintellicode|VisualStudioExptTeam|1.2.5|
|white|arthurwhite|1.3.6|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by JoeRobich** [comment]
@seongwon-kang Sorry this is causing problems. The issue is that both classes have the same name and namespace. When a rename is performed the Project is searched for matching symbols that need to be updated. Roslyn says this behavior is by design https://github.com/dotnet/roslyn/issues/40779#issuecomment-575750899

**Comment by seongwon-kang** [comment]
@JoeRobich Well, There are no explaination that rename will processes in project-wide. I want to add another menu that changes class name only in that file, is it bad idea?

**Comment by ryzngard** [comment]
@seongwon-kang  adding another menu for "only that file" is wrong in most cases, and would result in undesired behavior for this feature. There's only so much the editor should do for you, and this is a case where I believe you're using the wrong tool for the job. Find+replace does exactly what you want, and would be about as accurate.

**Comment by seongwon-kang** [comment]
![20-56-21 09 56 18](https://user-images.githubusercontent.com/56567660/74994087-6f723180-5490-11ea-9a31-c2681eb913a8.gif)

@ryzngard I expected that quick fix will refactor classname to match with filename. error message is, "the definition of {classname} is already in {namespace}", so changes all classname in project doesn't resolve error in this case.

if he/she renames filename that just copied class first, he/she may want add new class with that file template, not intent to replace existing class.

by the way, the recommendation of this quick fix(Rename class to {filename}) calls "Rename Symbol"? I didn't knew it.

**Comment by ryzngard** [comment]
Rename operations for VS and VS Code generally do symbol renames, so this aligns with that behavior. I understand what you're saying that you may want to rename only this "instance", but there are pretty valid reasons that's not the behavior. 

Thanks for filing :) I agree that it may not be the easiest behavior to understand, but hopefully you understand why I believe it's still correct.

**Comment by seongwon-kang** [comment]
@ryzngard I can't get valid reasons to not fix this case.. can you give me an example that can occurs undesired behavior? simply applying rename symbol doesn't fix any case if there are two same class in same namespace, so quick fix should not recommend rename symbol (project-side).

**Comment by ryzngard** [comment]
Indeed, the fix just checks that the class and file are mismatched. 

I think we can make improvements in this area, but adding another menu option is likely not the right path. 

If you have more input, I would suggest taking the discussion to https://github.com/dotnet/roslyn/issues/40779#issuecomment-575750899 and we can talk about ways to improve the experience if needed. It's exposing the internals, but all of this behavior is controlled by roslyn directly and applies to VS Code, VS for Mac, and VS for Windows.
