### ISSUE TITLE
Extern aliases are not recognized

### ISSUE THREAD

**Issue by jaredpar** [OmniSharp/omnisharp-vscode#3591]
## Issue Description ##
Extern aliases specified in the project file are not recognized. This leads to both error squiggles in the editor as well as errors in the "Problems" tab.

## Steps to Reproduce ##

1. Clone https://github.com/dotnet/roslyn
1. Sync to https://github.com/dotnet/roslyn/commit/b92b63b9a8f5ba3d942dfc60da6a87cb80106693
1. Run `Restore.cmd`
1. Open VS Code in this directory

## Expected Behavior ##
No errors

## Actual Behavior ##
Errors for many of our `extern` alias uses. Specifically open `FormattingCodeFixProvider.cs` and not that the following line (line 19) has an error squiggle

```c#
    extern alias CodeStyle;
```

This error also shows up in the "Problems" tab.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.42.0
**C# Extension**: 1.21.11

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.11|
|powershell|ms-vscode|2020.1.0|
|vim|vscodevim|1.12.4|;

</details>

**Comment by filipw** [comment]
it should be fixed here https://github.com/OmniSharp/omnisharp-roslyn/blob/master/CHANGELOG.md#13412---2020-02-18

this will ship in the next release

**Comment by JoeRobich** [comment]
You can try the pre-release build and let us know if it is resolved for you. https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.12

**Comment by jaredpar** [comment]
How do I use that locally

**Comment by filipw** [comment]
https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases

**Comment by JoeRobich** [comment]
It is now the public release. 🎉

**Comment by cartermp** [comment]
Closing as fixed and released
