### ISSUE TITLE
C# constructors - argument hints not displaying

### ISSUE THREAD

**Issue by egamma** [OmniSharp/omnisharp-vscode#36]
_From @sinclairzx81 on February 15, 2016 12:47_

Hi there,

I have noticed that code hints for C# class constructors are not displaying correctly. The issue seems specific to constructors only.

![hint](https://cloud.githubusercontent.com/assets/3048342/13049047/fcfc76d0-d44e-11e5-9954-466961e8aa2e.PNG)

It seems that vscode is pulling from generated XML metadata for the class if its available. In all other cases, it displays no argument information at all.

![hint2](https://cloud.githubusercontent.com/assets/3048342/13048853/a997928c-d44d-11e5-93d3-b2432d9ec81b.png)

Many Thanks

_Copied from original issue: Microsoft/vscode#3024_

**Comment by DustinCampbell** [comment]
This is probably a bug in https://github.com/OmniSharp/omnisharp-roslyn. Will take a look over there.

**Comment by bitwise-github** [comment]
Any news on this?

**Comment by sinclairzx81** [comment]
Is there any news on this?

Its been several months now, and this issue is causing much confusion among developers using vscode for C# development. It would be good to get some feedback on the progress of this bug. 

Many thanks

**Comment by sinclairzx81** [comment]
Any news on this?

**Comment by sinclairzx81** [comment]
Any news on this?

**Comment by DustinCampbell** [comment]
This will be fixed in the 1.6 release of the C# extension. Thanks @filipw!

**Comment by filipw** [comment]
great 👍 cc @sinclairzx81

**Comment by sinclairzx81** [comment]
This is awesome news. Great work @filipw, champion!!  👍 :)
