### ISSUE TITLE
Failed to spawn 'dotnet --info' on macOS Catalina 10.15.3 (Intellisense not working)

### ISSUE THREAD

**Issue by alejandrofloresm** [OmniSharp/omnisharp-vscode#3603]
## Issue Description ##

When I try to open a file from Unity I get the error "The .Net Core SDK cannot be located". The problem is that I have already installed .Net Core and I can run "dotnet --info" from the shell without a problem.

The Unity project contains the files of:

* Assembly-CSharp.csproj
* {name-of-project}.sln

Result of `dotnet --info`:
```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

## Steps to Reproduce ##

1. Open Unity
2. Click a .cs file
3. Unity will open Visual Studio Code
4. VS Code will show a message saying that .Net Core SDK cannot be located.
5. Intellisense doesn't work

## Expected Behavior ##

Intellisense works

## Actual Behavior ##

Intellisense doesn't work and it appears that C# cannot find dotnet.

### OmniSharp log ###
<details>
Starting OmniSharp server at 2/23/2020, 8:55:44 PM
    Target: /Users/NOT_A_REAL_USER/my-workspaces/unity-workspace/hello-world/hello-world.sln

OmniSharp server started.
    Path: /Users/NOT_A_REAL_USER/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/run
    PID: 93192

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.15.3 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.4 - "/Users/NOT_A_REAL_USER/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/Users/NOT_A_REAL_USER/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "/Users/NOT_A_REAL_USER/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /Users/NOT_A_REAL_USER/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/omnisharp/.msbuild/Current/Bin
            CscToolPath = /Users/NOT_A_REAL_USER/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /Users/NOT_A_REAL_USER/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/NOT_A_REAL_USER/my-workspaces/unity-workspace/hello-world'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/NOT_A_REAL_USER/my-workspaces/unity-workspace/hello-world/hello-world.sln'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/NOT_A_REAL_USER/my-workspaces/unity-workspace/hello-world'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/NOT_A_REAL_USER/my-workspaces/unity-workspace/hello-world' on host 93165.
</details>

### C# log ###
<details>
Failed to spawn 'dotnet --info'
</details>

## Environment information ##

**VSCode version**: 1.42.1
**C# Extension**: 1.21.12

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
A valid dotnet installation could not be found.</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|activitusbar|Gruntfuggly|0.0.25|
|an-old-hope-theme-vscode|dustinsanders|4.3.0|
|beautify|HookyQR|1.5.0|
|best-light-themes-pack|thegeoffstevens|1.0.2|
|bracket-pair-colorizer-2|CoenraadS|0.0.29|
|brackets-light-pro|eryouhao|0.4.3|
|composer|ikappas|0.7.1|
|copy-relative-path|alexdima|0.0.2|
|copy-syntax|atian25|0.5.1|
|copywithline|diigu|0.0.2|
|cpptools|ms-vscode|0.26.3|
|csharp|ms-vscode|1.21.12|
|debugger-for-chrome|msjsdiag|4.12.6|
|docomment|k--kato|0.1.8|
|dotenv|mikestead|1.0.1|
|EditorConfig|EditorConfig|0.14.4|
|gitconfig|sidneys1|2.0.1|
|github-plus-theme|thenikso|1.2.1|
|gitignore|codezombiech|0.6.0|
|gitlens|eamodio|10.2.1|
|highlight-matching-tag|vincaslt|0.9.6|
|indent-rainbow|oderwat|7.4.0|
|java|redhat|0.57.0|
|jquerysnippets|donjayamanne|0.0.1|
|laravel-artisan|ryannaddy|0.0.27|
|laravel-blade|onecentlin|1.20.0|
|material-theme|zhuangtongfa|3.2.3|
|monokai-plusplus|dcasella|1.7.0|
|monokai-vibrant|s3gf4ult|0.5.0|
|netbeans-light-theme|obrejla|2.0.2|
|one-monokai|azemoh|0.4.6|
|php-docblocker|neilbrayfield|2.1.0|
|python|ms-python|2020.2.64397|
|rainbow-csv|mechatroner|1.5.0|
|sftp|liximomo|1.12.9|
|sort-lines|Tyriar|1.9.0|
|theme-bluloco-light|uloco|2.9.3|
|theme-dracula|dracula-theme|2.20.0|
|theme-github|thomaspink|1.0.1|
|theme-hop-light|bubersson|0.0.4|
|theme-notepadplusplusremixed|sh4dow|1.0.3|
|theme-panda|tinkertrain|1.3.0|
|theme-quietlight-vsc|onecrayon|1.1.0|
|theme-ysgrifennwr|xaver|1.0.0|
|transformer|dakara|1.6.0|
|unity-code-snippets|kleber-swf|1.3.0|
|vetur|octref|0.23.0|
|vsc-community-material-theme|Equinusocio|1.4.1|
|vsc-material-theme|Equinusocio|32.5.0|
|vsc-material-theme-icons|equinusocio|1.1.4|
|vscode-docker|ms-azuretools|0.10.0|
|vscode-gitignore-syntax|dunstontc|0.1.2|
|vscode-icons|vscode-icons-team|10.0.0|
|vscode-intelephense-client|bmewburn|1.2.3|
|vscode-java-debug|vscjava|0.25.0|
|vscode-java-dependency|vscjava|0.9.0|
|vscode-java-pack|vscjava|0.8.1|
|vscode-java-test|vscjava|0.22.1|
|vscode-maven|vscjava|0.21.0|
|vscode-quick-select|dbankier|0.2.8|
|vscode-theme-github-light|Hyzeta|7.10.1|
|vscode-theme-onelight|akamud|2.1.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.5|;

</details>

**Comment by alejandrofloresm** [comment]
Update:

There was an error with Electron and my VSCode, the error was making Electron crash whenever I open VSCode. I fixed the error and got rid of the C# error: `Failed to spawn 'dotnet --info'`. But intellisense is still not working.

**Comment by alejandrofloresm** [comment]
For now Intellisense only works when I right-click over the assets folder in Unity and select Open C# project.

**Comment by sidferreira** [comment]
@alejandrofloresm how did you fix?
