### ISSUE TITLE
VS Installer warns: "We need to close the following process: OmniSharp"

### ISSUE THREAD

**Issue by rrelyea** [OmniSharp/omnisharp-vscode#3604]
When updating Visual Studio, sometimes the VS Installer warns:

"We need to close the following process: OmniSharp"

OmniSharp is the C# extension that runs inside of VS Code. 

For best results:
- Close VS Code instances - this will also shut down the OmniSharp process
- Click retry

I've opened this issue to help people find the right solution to this problem. It likely should be closed, after it is tweaked as necessary.

This dialog is necessary because OmniSharp loads msbuild and nuget assemblies from Visual Studio locations. If omnisharp is left running while the setup completes, VS won't be able to properly update msbuild and nuget assemblies...and may require a restart of VS or Windows.

[feel free to edit this top post as necessary, if you would like]

**Comment by JoeRobich** [comment]
@rrelyea Thanks for opening this issue! To provide a bit more detail, the C# extension does not ship with a complete set of build tools and for many scenarios it requires an installation of VS Build Tools or Mono depending on platform. If the C# extension detects that the a more complete set of build tools are installed it will make use of them to provide a better experience. This means that part of a user's VS install may be in use while trying to upgrade and the VS installer will now warn users to close OmniSharp which is run inside VS Code by the C# extension.
