### ISSUE TITLE
Option to disable Razor tag helper search for Blazor

### ISSUE THREAD

**Issue by ndotb** [OmniSharp/omnisharp-vscode#3605]
## Issue Description ##
Per official documentation at: https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#tag-helpers-arent-supported-in-components

Tag helpers are not supported at all in Blazor components.  Blazor projects need a csharp extension option to disable tag helper discovery to speed up language services.

This process is pretty slow.  Like you might want to go grab a snack slow.

## Steps to Reproduce ##
1) open blazor project with miscellaneous razor files
2) wait upwards of 5 minutes for squiggles and erroneous entries in the problem list to go away
3) if you haven't suffered long enough, recompile and do it all again

## Expected Behavior ##
1) get to work, fast

## Actual Behavior ##
2) coffee break

## Logs ##
--------------------------------------------------------------------------------
Razor.VSCode version 1.0.0-alpha3-5.0.0-alpha.1.20073.7
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Verbose'
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
 - To report issues invoke the 'Report a Razor issue' command via the command palette.
-----------------------------------------------------------------------------------------------------------------------------
.
.
*snip*
.
.
[Info  - 1:06:51 PM] Updating project 'any.csproj' TagHelpers (514) and C# Language Version (CSharp8).
[Info  - 1:06:51 PM] Updating project 'any.csproj'. The project is already using configuration 'MVC-3.0' and root namespace 'any'.
[Info  - 1:06:51 PM] Updating project 'any.csproj' TagHelpers (514) and C# Language Version (CSharp8).
[Info  - 1:06:51 PM] Updating project 'any.csproj'. The project is already using configuration 'MVC-3.0' and root namespace 'any'.
[Info  - 1:06:51 PM] Updating project 'any.csproj' TagHelpers (514) and C# Language Version (CSharp8).
[Info  - 1:06:51 PM] Updating project 'any.csproj'. The project is already using configuration 'MVC-3.0' and root namespace 'any'.
[Info  - 1:06:51 PM] Updating project 'any.csproj' TagHelpers (514) and C# Language Version (CSharp8).
[Info  - 1:06:51 PM] Updating project 'any.csproj'. The project is already using configuration 'MVC-3.0' and root namespace 'any'.
[Info  - 1:06:52 PM] Updating project 'any.csproj' TagHelpers (514) and C# Language Version (CSharp8).
[Info  - 1:06:52 PM] Updating project 'any.csproj'. The project is already using configuration 'MVC-3.0' and root namespace 'any'.
.
.
(and it goes on forever)

### OmniSharp log ###
<details>Starting OmniSharp server at 2/25/2020, 1:06:31 PM
    Target: /mysln/project3.sln

OmniSharp server started.
    Path: /snip/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/run
    PID: 6775

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 19.10 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.4 - "/snip/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/snip/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "/snip/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /snip/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/omnisharp/.msbuild/Current/Bin
            CscToolPath = /snip/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /snip/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/mysln'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/mysln/project3.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mysln/project1/project1.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mysln/project2/project2.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/mysln/project3/project3.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/mysln'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /mysln/project1/project1.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/mysln' on host 6546.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/mysln/project1/project1.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/mysln/project1/project1.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /mysln/project2/project2.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/mysln/project2/project2.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/mysln/project2/project2.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /mysln/project3/project3.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/mysln/project3/project3.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/mysln/project3/project3.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: project1
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: project2
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: project3
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers</details>

### C# log ###
<details>empty</details>

## Environment information ##

**VSCode version**: 1.42.1
**C# Extension**: 1.21.12

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.10
 OS Platform: Linux
 RID:         ubuntu.19.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.102/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.102 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|asp-net-core-switcher|adrianwilczynski|2.0.2|
|auto-using|Fudge|0.7.9|
|cmake|twxs|0.0.17|
|cmake-tools|ms-vscode|1.3.1|
|cmake-tools-helper|maddouri|0.2.1|
|cpptools|ms-vscode|0.26.3|
|csharp|ms-vscode|1.21.12|
|dark-plus-material|vangware|2.2.3|
|debugger-for-chrome|msjsdiag|4.12.6|
|dotnet-test-explorer|formulahendry|0.7.1|
|EditorConfig|EditorConfig|0.14.4|
|es7-react-js-snippets|dsznajder|2.6.0|
|formate|MikeBovenlander|1.1.4|
|git-graph|mhutchie|1.21.0|
|gitlens|eamodio|10.2.1|
|Go|ms-vscode|0.13.0|
|jbockle-format-files|jbockle|3.0.0|
|msbuild-project-tools|tintoy|0.3.3|
|python|ms-python|2020.2.64397|
|rainbow-csv|mechatroner|1.5.0|
|restructuredtext|lextudio|118.0.0|
|typescript-hero|rbbit|3.0.0|
|vscode-docker|ms-azuretools|0.10.0|
|vscode-firefox-debug|firefox-devtools|2.6.1|
|vscode-icons|vscode-icons-team|10.0.0|
|vscode-postgresql|ms-ossdata|0.2.0|
|vscode-react-native|msjsdiag|0.14.1|
|vscode-sort-json|richie5um2|1.18.0|
|vscode-taskexplorer|spmeesseman|1.24.4|
|vscode-test-explorer|hbenl|2.17.0|
|xml|DotJoshJohnson|2.5.0|
|yarn-ui|xqchen|0.1.2|;

</details>

**Comment by NTaylorMullen** [comment]
> * wait upwards of 5 minutes for squiggles and erroneous entries in the problem list to go away
> * if you haven't suffered long enough, recompile and do it all again

So sadly hosted Blazor projects still make use of TagHelpers. As for the speed of discovery, a lot of this is typically tied to the functionality of OmniSharp being "loaded". Would you mind sharing a repro project so we can investigate further?

**Comment by ndotb** [comment]
Public test repo: https://github.com/ndotb/omnisharp-blazor-taghelpers

There's a bash file in the ComponentLibrary project that will generate an arbitrary number of components for you, all dumped in one .cs file.  I pushed it with 500, since mature projects do grow to that seemingly unnecessary amount.

**Comment by NTaylorMullen** [comment]
@ndotb what type of slowness are you seeing? I added 500 components with your script and here's what I'm seeing (goes too fast for me to even tell the difference of 1 or 500 components):

![image](https://i.imgur.com/bU8F7tK.gif)

**Comment by ndotb** [comment]
In highest respects for all of the help desk workers out there who were sent animated gifs of IE spinning wheels, I'll spare the timelapse of it loading, but here's the gist:

still image of what I saw during this fresh vscode load, from 3:12:20pm to 3:15:11pm (~3 minutes):
![image](https://user-images.githubusercontent.com/20463809/75383908-32040e80-58ab-11ea-8ce3-10dd480ed6bc.png)

The "server started and ready" timestamp:
```[Client - 3:12:23 PM] Server started and ready!```

The head -n 5 for taghelpers:
```[Info  - 3:12:28 PM] Updating project '/src/dotnet/OmniTest/Client/OmniTest.Client.csproj' TagHelpers (169) and C# Language Version (CSharp8).
[Info  - 3:12:29 PM] Updating project '/src/dotnet/OmniTest/Client/OmniTest.Client.csproj' TagHelpers (169) and C# Language Version (CSharp8).
[Info  - 3:12:29 PM] Updating project '/src/dotnet/OmniTest/Client/OmniTest.Client.csproj' TagHelpers (169) and C# Language Version (CSharp8).
[Info  - 3:12:29 PM] Updating project '/src/dotnet/OmniTest/Client/OmniTest.Client.csproj' TagHelpers (169) and C# Language Version (CSharp8).
[Info  - 3:12:29 PM] Updating project '/src/dotnet/OmniTest/Client/OmniTest.Client.csproj' TagHelpers (169) and C# Language Version (CSharp8).
```

the tail -n 5:
```
[Info  - 3:15:10 PM] Updating project '/src/dotnet/OmniTest/ComponentLibrary/ComponentLibrary.csproj' TagHelpers (1169) and C# Language Version (CSharp7_3).
[Info  - 3:15:10 PM] Updating project '/src/dotnet/OmniTest/ComponentLibrary/ComponentLibrary.csproj' TagHelpers (1169) and C# Language Version (CSharp7_3).
[Info  - 3:15:10 PM] Updating project '/src/dotnet/OmniTest/ComponentLibrary/ComponentLibrary.csproj' TagHelpers (1169) and C# Language Version (CSharp7_3).
[Info  - 3:15:11 PM] Updating project '/src/dotnet/OmniTest/ComponentLibrary/ComponentLibrary.csproj' TagHelpers (1169) and C# Language Version (CSharp7_3).
[Info  - 3:15:11 PM] Updating project '/src/dotnet/OmniTest/ComponentLibrary/ComponentLibrary.csproj' TagHelpers (1169) and C# Language Version (CSharp7_3).
```

As a side note, I just discovered today through your image that the extension helps with parameter autocompletion!

Turning off log events to make sure there's no fighting for kernel time doesn't seem to make a difference.

Is there any way to change the configuration?
```
[Info  - 3:12:28 PM] Updating project '/src/dotnet/OmniTest/Client/OmniTest.Client.csproj' to use Razor's default configuration ('MVC-3.0')'.
```

**Comment by NTaylorMullen** [comment]
Hmm, ya that's nuts that it's taking so long on your box. On application start it takes max 30s to initialize the world. Does OmniSharp take that long to spin up as well? Also, what OS are you trying this out on?



> Is there any way to change the configuration?

Configuration is an internal Razor concept where we map your project to a specific way to parse your Razor files. For instance, if you open a netcoreapp2.2 project we'll map that to our MVC2.X configuration. Not something you typically want to change.

**Comment by ndotb** [comment]
I did stumble across the rzls code in the microsoft jungle and saw that the options were "default", "mvc 2_x" and "mvc 1_x" (or approximate).

It's on a i7-4820k (passmark score 9719) with an evo ssd, running ubuntu 19.10 on metal with private mono, since global mono seems to mess with dotnet.  Omnisharp by itself comes up pretty fast, maybe 5 seconds and I imagine that's mostly node and typescript.  I stuck to webapi and react while mvc was king, so I didn't even notice rzls until I started messing with Blazor.

A quick check of the cpu graph shows that it's threading on all cores.

**Comment by NTaylorMullen** [comment]
There must be an issue with Mono when using Roslyn/reflection.... @JoeRobich is there any Roslyn performance issues cross-plat that could be to blame here?

**Comment by JoeRobich** [comment]
@ndotb By private mono do you mean the minimal mono that is shipped with omnisharp? We've gotten reports of high CPU in general with mono, but no one has pinned it down.

**Comment by ndotb** [comment]
Yeah, the packaged one (private mono in settings) since ubuntu only ships with v5.18 right now.

I took an exploratory route and downloaded mono 6.8 from their repo directly, using the instructions at https://www.mono-project.com/download/stable/#download-lin-ubuntu
```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
sudo apt update
sudo apt install mono-complete
```
As a side note, it compiled with LLVM since I have clang-9 installed.

double-checked version
```
$ mono --version
Mono JIT compiler version 6.8.0.105 (tarball Tue Feb  4 21:20:20 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

then set `"omnisharp.useGlobalMono"` to `"always"` and restarted vscode

with similar results for time:
```
[Client - 10:53:44 PM] Server started and ready!
[Info  - 10:53:44 PM] Opening document '/src/dotnet/OmniTest/Client/Pages/Index.razor' in project '/src/dotnet/OmniTest/Client/OmniTest.Client.csproj'.
.
.
.
[Info  - 10:56:35 PM] Updating project '/src/dotnet/OmniTest/ComponentLibrary/ComponentLibrary.csproj' TagHelpers (1169) and C# Language Version (CSharp7_3).
```

attempting to do AOT compilation for rzls got the following:
```
$ mono --aot rzls
Can not open image rzls
```

**Comment by NTaylorMullen** [comment]
Reproduced the issue! We're going to take a look and track the work over here: https://github.com/dotnet/aspnetcore/issues/19455

**Comment by NTaylorMullen** [comment]
Oh and if you want to try and disable Blazor search you'll have to disable the entire project understanding of the project sadly. You can do that by setting `"razor.plugin.path": "something that doesn't exist"` It's a hack but [this](https://github.com/OmniSharp/omnisharp-vscode/blob/70b37a67d8f1c3985b7aa110ba5f827b8eed7da8/src/omnisharp/server.ts#L327) check will fail because of it resulting in the Razor project system not booting.

**Comment by ndotb** [comment]
Thanks guys!
