### ISSUE TITLE
VS Code / OmniSharp - how to set path to dotnet SDK / CLI tools explicitly -CLOSE!

### ISSUE THREAD

**Issue by jegasape** [OmniSharp/omnisharp-vscode#3607]
I'm using the binary file of the project, I'm trying to specify a visual studio to use the SDK of the file where the binary file is, But I have not found a way to do it, someone who can help me solve it

I would appreciate any help to make the visual studio code intelligence works!

![Capture](https://user-images.githubusercontent.com/44595343/75364303-e3964600-5891-11ea-8124-e54d88def6c3.PNG)

**Comment by JoeRobich** [comment]
Hi @jegasape, Can you share the OmniSharp logging from the VS Code Output pane?

**Comment by jegasape** [comment]
Starting OmniSharp server at 2/26/2020, 3:42:50 PM
    Target: c:\$Recycle.Bin\S-1-5-21-4234495868-3908348368-3363237933-10793\$IWEQWERTY\250b29b51b9d7770172bfcb6d6e526bc\Api

OmniSharp server started.
    Path: c:\Users\happyfriend\.vscode\extensions\ms-vscode.csharp-1.21.12\.omnisharp\1.34.13\OmniSharp.exe
    PID: 11068

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2017 15.9.28307.718 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            2: StandAlone 16.4 - "c:\Users\happyfriend\.vscode\extensions\ms-vscode.csharp-1.21.12\.omnisharp\1.34.13\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\happyfriend\.vscode\extensions\ms-vscode.csharp-1.21.12\.omnisharp\1.34.13\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "c:\Users\happyfriend\.vscode\extensions\ms-vscode.csharp-1.21.12\.omnisharp\1.34.13\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\happyfriend\.vscode\extensions\ms-vscode.csharp-1.21.12\.omnisharp\1.34.13\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\happyfriend\.vscode\extensions\ms-vscode.csharp-1.21.12\.omnisharp\1.34.13\.msbuild
            MSBuildToolsPath = c:\Users\happyfriend\.vscode\extensions\ms-vscode.csharp-1.21.12\.omnisharp\1.34.13\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\$Recycle.Bin\S-1-5-21-4234495868-3908348368-3363237933-10793\$IWEQWERTY\250b29b51b9d7770172bfcb6d6e526bc\Api'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\$Recycle.Bin\S-1-5-21-4234495868-3908348368-3363237933-10793\$IWEQWERTY\250b29b51b9d7770172bfcb6d6e526bc\Api'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\$Recycle.Bin\S-1-5-21-4234495868-3908348368-3363237933-10793\$IWEQWERTY\250b29b51b9d7770172bfcb6d6e526bc\Api\Api.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\$Recycle.Bin\S-1-5-21-4234495868-3908348368-3363237933-10793\$IWEQWERTY\250b29b51b9d7770172bfcb6d6e526bc\Api'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\$Recycle.Bin\S-1-5-21-4234495868-3908348368-3363237933-10793\$IWEQWERTY\250b29b51b9d7770172bfcb6d6e526bc\Api\Api.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\$Recycle.Bin\S-1-5-21-4234495868-3908348368-3363237933-10793\$IWEQWERTY\250b29b51b9d7770172bfcb6d6e526bc\Api' on host 8876.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\$Recycle.Bin\S-1-5-21-4234495868-3908348368-3363237933-10793\$IWEQWERTY\250b29b51b9d7770172bfcb6d6e526bc\Api\Api.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\$Recycle.Bin\S-1-5-21-4234495868-3908348368-3363237933-10793\$IWEQWERTY\250b29b51b9d7770172bfcb6d6e526bc\Api\Api.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Api
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        Api: Did not find 'Microsoft.NETCore.App' in lock file.
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 6.

**Comment by jegasape** [comment]
Starting OmniSharp server at 2/26/2020, 6:04:42 PM
    Target: c:\Users\happyfriend\Desktop\Api

OmniSharp server started.
    Path: C:\Users\happyfriend\.vscode\extensions\ms-vscode.csharp-1.21.12\.omnisharp\1.34.13\OmniSharp.exe
    PID: 6044

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2017 15.9.28307.718 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            2: StandAlone 16.4 - "c:\Users\happyfriend\.vscode\extensions\ms-vscode.csharp-1.21.12\.omnisharp\1.34.13\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\happyfriend\.vscode\extensions\ms-vscode.csharp-1.21.12\.omnisharp\1.34.13\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "c:\Users\happyfriend\.vscode\extensions\ms-vscode.csharp-1.21.12\.omnisharp\1.34.13\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\happyfriend\.vscode\extensions\ms-vscode.csharp-1.21.12\.omnisharp\1.34.13\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\happyfriend\.vscode\extensions\ms-vscode.csharp-1.21.12\.omnisharp\1.34.13\.msbuild
            MSBuildToolsPath = c:\Users\happyfriend\.vscode\extensions\ms-vscode.csharp-1.21.12\.omnisharp\1.34.13\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\happyfriend\Desktop\Api'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\happyfriend\Desktop\Api'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\happyfriend\Desktop\Api\Api.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\happyfriend\Desktop\Api'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\happyfriend\Desktop\Api\Api.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\happyfriend\Desktop\Api' on host 6076.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\happyfriend\Desktop\Api\Api.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\happyfriend\Desktop\Api\Api.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Api
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        Api: Did not find 'Microsoft.NETCore.App' in lock file.
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 6.

Can I change DotNetPath to another path?

**Comment by jegasape** [comment]
I have SDK dotnet 3.1 in this path : c:/dotnet/dotnet

Issue: 

C:\Program Files\dotnet\sdk\2.2.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1. Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.1

How can i fix?
