### ISSUE TITLE
Omnisharp fails to start spaces in path to VS Code extension dir

### ISSUE THREAD

**Issue by JeremySkinner** [OmniSharp/omnisharp-vscode#3608]
## Issue Description ##

Hi, I'm seeing an issue when running OmniSharp in VS Code on my mac. Omnisharp fails to start up as the full path to the extension contains a space (the space is in my home directory name, which was done by a migration from a previous mac). 

See omnisharp log for the full output, but on startup it looks like it's trying to run `chmod /Users/JSkinner 1/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/run` without quoting the path, causing the command to fail (note "JSkinner 1" is the home dir, with the space). 

Is there any way I can work around this? 

Thanks!

### OmniSharp log ###
<details>Starting OmniSharp server at 26/02/2020, 17:30:24
    Target: /Users/JSkinner 1/Code/FluentValidation/FluentValidation.sln

OmniSharp server started.
    Path: /Users/JSkinner 1/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/run
    PID: 9647

chmod: /Users/JSkinner: No such file or directory
chmod: 1/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/bin/mono: No such file or directory
/Users/JSkinner 1/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/run: line 27: /Users/JSkinner 1/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/bin/mono: Permission denied
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).</details>

## Environment information ##

**VSCode version**: 1.42.1
**C# Extension**: 1.21.12

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /Users/JSkinner 1/.dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.2.202 [/Users/JSkinner 1/.dotnet/sdk]
  3.1.101 [/Users/JSkinner 1/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [/Users/JSkinner 1/.dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [/Users/JSkinner 1/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/Users/JSkinner 1/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [/Users/JSkinner 1/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/Users/JSkinner 1/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.12|
|EditorConfig|EditorConfig|0.14.4|
|php-docblocker|neilbrayfield|2.1.0|
|php-intellisense|felixfbecker|2.3.14|
|phpcs|ikappas|1.0.5|
|powershell|ms-vscode|2020.1.0|
|sftp|liximomo|1.12.9|
|twig|whatwedo|1.0.2|
|VS-code-drupal|marcostazi|0.0.12|;

</details>

**Comment by filipw** [comment]
fix was merged

**Comment by jramorris** [comment]
It looks like I'm running into the same issue on Omnisharp server start:

`OmniSharp server started.
    Path: /Users/James 1 2/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.6/run
    PID: 8889

Cannot open assembly '1': No such file or directory.`

In VSCode Version: 1.55.1, C# extension v1.23.9, using the built-in omnisharp.
