### ISSUE TITLE
The type check cannot run!

### ISSUE THREAD

**Issue by yearn2012** [OmniSharp/omnisharp-vscode#3612]
VSCode Version: 1.42.1	OS Version: win-nt x64 10.0.19041
Steps to Reproduce:

I Declared a class and then set a value int type,not report wrong.
    IndicatorDataSeries MacdOtherFrameSeries { get; set; }
 private void IndicatorArea_MouseUp(ChartMouseEventArgs obj)
        {
        
           ###  MacdOtherFrameSeries = 2;
            fxMacd.GetMacd_OtherFrame();
            Print("good");
        }

**Comment by JoeRobich** [comment]
Hi @yearn2012, Thanks for the report. Can you provide a more complete set of steps to reproduce the issue that you are seeing?

**Comment by cartermp** [comment]
Closing out report with no info.
