### ISSUE TITLE
Assemblies targeting .Net Framework 4.7.1 fail to load on Mac, plugin v1.21.11 

### ISSUE THREAD

**Issue by edwardrowe** [OmniSharp/omnisharp-vscode#3613]
## Issue Description ##
When loading my Unity (v2018.4.2f) project in Visual Studio Code, the assemblies fail to load and intellisense doesn't work. This seems to have been introduced in version 1.21.11, as rolling back to v1.21.10 works fine.

## Steps to Reproduce ##
1. Create a project in Unity, v2018.4.2
2. Target .Net Framework 4.7.1 by setting Scripting Runtime Version to .Net 4.x Equivalent in Edit/Project Settings/Player/Scripting Runtime Version
![image](https://user-images.githubusercontent.com/398377/75486781-2bdd6300-597b-11ea-991a-5dbfb7d761b3.png)
3. Open up the project in Visual Studio Code
4. Observe the plugin fails to load the assemblies

## Expected Behavior ##
The assemblies should load, allowing me to see function references and Go To implementations and definitions.

## Actual Behavior ##
Intellisense and 
![image](https://user-images.githubusercontent.com/398377/75487342-46640c00-597c-11ea-8186-40b43225636b.png)

### OmniSharp log ###
Starting OmniSharp server at 2/27/2020, 3:58:25 PM
    Target: /Users/erowe/Development/sparklite/sparklite.sln

OmniSharp server started.
    Path: /Users/erowe/.vscode/extensions/ms-vscode.csharp-1.21.11/.omnisharp/1.34.11/run
    PID: 26956

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.14.6 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.3 - "/Users/erowe/.vscode/extensions/ms-vscode.csharp-1.21.11/.omnisharp/1.34.11/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/Users/erowe/.vscode/extensions/ms-vscode.csharp-1.21.11/.omnisharp/1.34.11/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.3 - "/Users/erowe/.vscode/extensions/ms-vscode.csharp-1.21.11/.omnisharp/1.34.11/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /Users/erowe/.vscode/extensions/ms-vscode.csharp-1.21.11/.omnisharp/1.34.11/omnisharp/.msbuild/Current/Bin
            CscToolPath = /Users/erowe/.vscode/extensions/ms-vscode.csharp-1.21.11/.omnisharp/1.34.11/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /Users/erowe/.vscode/extensions/ms-vscode.csharp-1.21.11/.omnisharp/1.34.11/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/erowe/Development/sparklite'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/erowe/Development/sparklite/sparklite.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/erowe/Development/sparklite/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/erowe/Development/sparklite/Assembly-CSharp-firstpass.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/erowe/Development/sparklite/Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/erowe/Development/sparklite/Assembly-CSharp-Editor-firstpass.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/erowe/Development/sparklite/RBG.Mulligan.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/erowe/Development/sparklite'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/erowe/Development/sparklite/Assembly-CSharp.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/erowe/Development/sparklite' on host 26922.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/erowe/Development/sparklite/Assembly-CSharp.csproj'.
/Users/erowe/Development/sparklite/Assembly-CSharp.csproj
/Users/erowe/.vscode/extensions/ms-vscode.csharp-1.21.11/.omnisharp/1.34.11/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1193,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/erowe/Development/sparklite/Assembly-CSharp-firstpass.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/erowe/Development/sparklite/Assembly-CSharp-firstpass.csproj'.
/Users/erowe/Development/sparklite/Assembly-CSharp-firstpass.csproj
/Users/erowe/.vscode/extensions/ms-vscode.csharp-1.21.11/.omnisharp/1.34.11/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1193,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/erowe/Development/sparklite/Assembly-CSharp-Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/erowe/Development/sparklite/Assembly-CSharp-Editor.csproj'.
/Users/erowe/Development/sparklite/Assembly-CSharp-Editor.csproj
/Users/erowe/.vscode/extensions/ms-vscode.csharp-1.21.11/.omnisharp/1.34.11/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1193,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/erowe/Development/sparklite/Assembly-CSharp-Editor-firstpass.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/erowe/Development/sparklite/Assembly-CSharp-Editor-firstpass.csproj'.
/Users/erowe/Development/sparklite/Assembly-CSharp-Editor-firstpass.csproj
/Users/erowe/.vscode/extensions/ms-vscode.csharp-1.21.11/.omnisharp/1.34.11/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1193,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/erowe/Development/sparklite/RBG.Mulligan.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/erowe/Development/sparklite/RBG.Mulligan.csproj'.
/Users/erowe/Development/sparklite/RBG.Mulligan.csproj
/Users/erowe/.vscode/extensions/ms-vscode.csharp-1.21.11/.omnisharp/1.34.11/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1193,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/erowe/Development/sparklite/Assembly-CSharp.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/erowe/Development/sparklite/Assembly-CSharp-firstpass.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/erowe/Development/sparklite/Assembly-CSharp-Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/erowe/Development/sparklite/Assembly-CSharp-Editor-firstpass.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/erowe/Development/sparklite/RBG.Mulligan.csproj

### C# log ###
Installing C# dependencies...
Platform: darwin, x86_64

Downloading package 'OmniSharp for OSX' (46346 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for OSX'

Downloading package '.NET Core Debugger (macOS / x64)' (41849 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (macOS / x64)'

Downloading package 'Razor Language Server (macOS / x64)' (50424 KB).................... Done!
Installing package 'Razor Language Server (macOS / x64)'

Finished

## Environment information ##

**VSCode version**: 1.42.1
**C# Extension**: 1.21.11

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.401/

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.401 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.11|
|docomment|k--kato|0.1.8|
|gitlens|eamodio|10.2.1|
|rainbow-csv|mechatroner|1.5.0|
|theme-dracula|dracula-theme|2.20.0|
|unity-debug|Unity|2.7.2|
|vscode-emacs|hiro-sun|0.1.1|;

</details>

**Comment by JoeRobich** [comment]
@edwardrowe The built-in mono does not contain reference assemblies. To fix this problem you should install the stable mono - https://www.mono-project.com/download/stable/#download-mac

**Comment by edwardrowe** [comment]
This worked. Thanks so much for the help and quick feedback.

**Comment by DTX-92** [comment]
> To fix this problem you should install the stable mono

I did, but it didn't help.
How should I reference installed Mono, so Unity can find missing Net Framerowrk?

**Comment by JoeRobich** [comment]
@DTX-92 Can you share the omnisharp log from the Output pane?

**Comment by DTX-92** [comment]
I was able to fix a problem by modifying my ~/.bash_profile to contain `export FrameworkPathOverride` 
thx

**Comment by giangchau92** [comment]
In my case, I have reinstalled the previous version of omnisharp plugin then it worked

<img width="604" alt="image" src="https://user-images.githubusercontent.com/5353860/90736043-d06faa80-e2f7-11ea-930e-f5a3e832df7e.png">

<img width="605" alt="image" src="https://user-images.githubusercontent.com/5353860/90735499-afa75500-e2f7-11ea-986c-7e523b922307.png">

**Comment by filipw** [comment]
you don;'t need to revert - see https://github.com/OmniSharp/omnisharp-vscode/issues/4007#issuecomment-677405332

**Comment by findnew2000** [comment]
> In my case, I have reinstalled the previous version of omnisharp plugin then it worked
> 
> <img alt="image" width="604" src="https://user-images.githubusercontent.com/5353860/90736043-d06faa80-e2f7-11ea-930e-f5a3e832df7e.png">
> 
> <img alt="image" width="605" src="https://user-images.githubusercontent.com/5353860/90735499-afa75500-e2f7-11ea-986c-7e523b922307.png">

it's ok

**Comment by russellinho** [comment]
For anyone who can't find the Use Global Mono setting, go to Extension Settings at the bottom of the cog on the C# extension
![image](https://user-images.githubusercontent.com/10291604/90986662-7e769100-e552-11ea-9ef0-d02340600ff8.png)

**Comment by egorovsa** [comment]
**giangchau92** Mine god man! Thank you.. 
> <img alt="image" width="604" src="https://user-images.githubusercontent.com/5353860/90736043-d06faa80-e2f7-11ea-930e-f5a3e832df7e.png">

So summary I did:
Error: The reference assemblies for .NETFramework,Version=v4.7.1
Unity 2019.4.9f1  Macos

Downgrade to 
c# extension v1.23.0 as described above 

**Removed all csproj and regenerated it**
- Go to Unity -> Edit -> Preferences -> External Tools
- Look for the section near the top called "Generate .csproj files for:" and click "Regenerate Project Files" with everything unchecked.
 - Then in VSCode I press "Cmd + Shift + P" and run the action for "Developer: Reload Window"

**Comment by hypeofpipe** [comment]
Unity 2020.1.9f1 Personal, MacOS Catalina 10.15.7 (19H2) and the problem persists on versions >1.23.0 :/

**Comment by JoeRobich** [comment]
@hypeofpipe Sorry you are running into issues. The minimal Mono shipped with the C# extension does not contain 4.7.1 reference assemblies. Install the latest stable Mono 6.12.0 from https://www.mono-project.com/download/stable/ and set the `omnisharp.useGlobalMono` setting to "always". Also, ensure you are using the 1.2.3 VSCode Editor package in Unity.

**Comment by rstecca** [comment]
@giangchau92 's [solution](https://github.com/OmniSharp/omnisharp-vscode/issues/3613#issuecomment-677451385) worked for me. Using homebrew I installed dotnet-sdk and mono, then I installed the C# extension in VSCode and had the error in the thread's title. The plugin was at version 1.23.5, I installed version 1.23.4 and now I get no errors in the OmniSharp's log and intellisense works.

**Comment by otri** [comment]
> @hypeofpipe Sorry you are running into issues. The minimal Mono shipped with the C# extension does not contain 4.7.1 reference assemblies. Install the latest stable Mono 6.12.0 from https://www.mono-project.com/download/stable/ and set the `omnisharp.useGlobalMono` setting to "always". Also, ensure you are using the 1.2.3 VSCode Editor package in Unity.

Using Unity 2019.4.14f1, I noticed the package for "VSCode Editor" was on older version 1.2.2.  Upgrading to 1.2.3 fixed it.

Dang.. Unity needs to do some sanity checking for developer work environments.  Something really smart for Mac developers that checks and suggests what are working configurations.   OmniSharp' debug message is also not terribly helpful because AFAIK there is no .Net Framework 4.7.1 built for Mac.  So what would help me debug this issue is knowing what are the responsible parties for this framework version determination.  Is it Unity?  Is it VSCode Editor?  Is it maybe a solution misconfiguration with a default resolving to 4.7.1?

I know OmniSharp package isn't directly in charge of these other projects, and it's important to maintain some idempotency between them.  However the reality is 99.9% of users encountering this major error are coming from a Unity on Mac environment.   Some from Unity on Linux too.   Therefore, some awareness of how Unity interoperates with OmniSharp and VSCode would all be very much more helpful.  Maybe even provide a URL tip to a OmniSharp wiki page with up-to-date information on this common issue.

**Comment by Revolunk** [comment]
> In my case, I have reinstalled the previous version of omnisharp plugin then it worked
> 
> <img alt="image" width="604" src="https://user-images.githubusercontent.com/5353860/90736043-d06faa80-e2f7-11ea-930e-f5a3e832df7e.png">
> 
> <img alt="image" width="605" src="https://user-images.githubusercontent.com/5353860/90735499-afa75500-e2f7-11ea-986c-7e523b922307.png">
> 
> Another way to fix the issue without downgrade omnisharp plugin is to update the latest mono (https://www.mono-project.com/download/stable/).
> Set **Use Global Mono** to **always**
> <img alt="image" width="774" src="https://user-images.githubusercontent.com/5353860/90771332-50f4d200-e31d-11ea-8504-c5ce8983a6b6.png">

Man.. i want to hug you! I've been fighting 3 days with it and just changed to use mono always. IT'S WORKING

**Comment by matschaffer** [comment]
That "Global Mono to always" setting in VS Code was the thing I missed on the first try. Just installing the latest mono alone didn't do it. Thanks @giangchau92 !

**Comment by steowens** [comment]
This does not work if you install the .Net Runtimes 5.x.  Basically now this omnisharp no longer performs syntax checking on C# files, and now way to fix.

**Comment by filipw** [comment]
@steowens OmniSharp's built-in Mono supports .NET 5.0, however the global Mono doesn't (there is no official Mono release that ships with MSBuild 16.8 which is required for .NET 5.0). We are waiting already several months for the relevant official Mono release https://github.com/mono/mono/issues/20250

**Comment by squio** [comment]
> @hypeofpipe Sorry you are running into issues. The minimal Mono shipped with the C# extension does not contain 4.7.1 reference assemblies. Install the latest stable Mono 6.12.0 from https://www.mono-project.com/download/stable/ and set the `omnisharp.useGlobalMono` setting to "always". Also, ensure you are using the 1.2.3 VSCode Editor package in Unity.

At first I couldn't find this setting in vscode - it is not in Workspace settings but only in the User tab. Works lie a charm though!

**Comment by alejodeiuliis** [comment]
> In my case, I have reinstalled the previous version of omnisharp plugin then it worked
> 
> <img alt="image" width="604" src="https://user-images.githubusercontent.com/5353860/90736043-d06faa80-e2f7-11ea-930e-f5a3e832df7e.png">
> 
> <img alt="image" width="605" src="https://user-images.githubusercontent.com/5353860/90735499-afa75500-e2f7-11ea-986c-7e523b922307.png">
> 
> Another way to fix the issue without downgrade omnisharp plugin is to update the latest mono (https://www.mono-project.com/download/stable/).
> Set **Use Global Mono** to **always**
> <img alt="image" width="774" src="https://user-images.githubusercontent.com/5353860/90771332-50f4d200-e31d-11ea-8504-c5ce8983a6b6.png">

This worked for me ! Thanks!

**Comment by filipw** [comment]
Please use the solution described here https://github.com/OmniSharp/omnisharp-vscode/issues/3613#issuecomment-723336286, otherwise - please open a new issue, thanks.
