### ISSUE TITLE
Add Autocomplete for Common Method (Start(), Update(), etc) in VSCode C# Unity

### ISSUE THREAD

**Issue by komputerboy** [OmniSharp/omnisharp-vscode#3619]
Hi,

Well, i think this is not issue. I have C# extension for my Unity project. 

I just want to ask question, why there is no auto complete / intellisense for common method like, Start(), Awake(), FixedUpdate(), etc?
Well, but now i use other extension which is _unity-code-snippets_  in order to do that.

I guess it will be very great if this extension also has that feature.

Thanks

#Environment information ##

**VSCode version**: 1.42.1
**C# Extension**: 1.21.12

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.102\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.12|
|dart-code|Dart-Code|3.8.1|
|flutter|Dart-Code|3.8.1|
|unity-code-snippets|kleber-swf|1.3.0|;

</details>

**Comment by JoeRobich** [comment]
Hi @komputerboy, Thanks for the suggestion. The C# extension is intended to just provide general support for the core .NET frameworks. This allows extensions such as *unity-code-snippets* to provide this type of framework specific support.
