### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by hansse** [OmniSharp/omnisharp-vscode#3626]
- Issue Type: `Bug`
- Extension Name: `csharp`
- Extension Version: `1.21.13`
- OS Version: `Darwin x64 19.3.0`
- VSCode version: `1.42.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by cartermp** [comment]
Thanks for the report. Unfortunately, there isn't any information available here for us to know about the issue. If you have a reproduction that shows your problem, we'll take a look at re-open.
