### ISSUE TITLE
Issue with c# extension

### ISSUE THREAD

**Issue by SDJedi** [OmniSharp/omnisharp-vscode#3632]
- Issue Type: Performance Issue
- Extension Name: `csharp`
- Extension Version: `1.21.13`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.42.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 71,
		"activateCallTime": 7,
		"activateResolvedTime": 44,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-dotnettools.csharp",
				"_lower": "ms-dotnettools.csharp"
			},
			"activationEvent": "onLanguage:csharp"
		}
	},
	"runtimeErrors": []
}
```

**Comment by cartermp** [comment]
Hey there, thanks for the report. Unfortunately, this report doesn't contain any information we can take action on. If you have a reproduction of the performance problem that you're seeing, please let us know and we can re-open this to investigate further.
