### ISSUE TITLE
#3610 broke dependencies

### ISSUE THREAD

**Issue by PCoelho** [OmniSharp/omnisharp-vscode#3633]
On #3610 you changed the package name from ms-vscode.csharp to ms-dotnettools.csharp. This is causing all the packages that depend on this to fail. 

Is this change here to stay or are you changing your mind again soon?

In the mean time if you're having this issue, uninstall the one you're using and get this one: https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.12

**Comment by cartermp** [comment]
Thanks for the report. The extension name change is final, and we're very sorry for the issues caused with various upstream dependencies.
