### ISSUE TITLE
Visual Studio 2019 relaunch infinitely

### ISSUE THREAD

**Issue by dsalodki** [OmniSharp/omnisharp-vscode#3637]
Issue Type: <b>Bug</b>

when I open big solution with enought RAM VS 2019 relaunch infinitely.

Extension version: 1.21.13
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (20.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by JoeRobich** [comment]
Hi @dsalodki, If you are having issue with Visual Studio 2019 you can report them from within the app with the Send Feedback button. This repo is for the C# extension for VS Code.
![image](https://user-images.githubusercontent.com/611219/76266614-46d68f80-6225-11ea-8831-e66722e86a49.png)
