### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by samson7s** [OmniSharp/omnisharp-vscode#3638]
- Issue Type: `Bug`
- Extension Name: `csharp`
- Extension Version: `1.21.13`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.42.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 152,
		"activateCallTime": 12,
		"activateResolvedTime": 99,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-dotnettools.csharp",
				"_lower": "ms-dotnettools.csharp"
			},
			"activationEvent": "onLanguage:csharp"
		}
	},
	"runtimeErrors": []
}
```

**Comment by cartermp** [comment]
Thanks for the report. Unfortunately, there isn't sufficient information in this report for us to take action on. Please include reproduction steps for the issue you're seeing and we can re-open this.

**Comment by samson7s** [comment]
Already see related questions, the answer is downgraded, so no more feedback was written

**Comment by samson7s** [comment]
> 
> 
> Thanks for the report. Unfortunately, there isn't sufficient information in this report for us to take action on. Please include reproduction steps for the issue you're seeing and we can re-open this.

Already see related questions, the answer is downgraded, so no more feedback was written.
