### ISSUE TITLE
Getting wrong message in output window while building C# project in VSCode.

### ISSUE THREAD

**Issue by v-pavanp** [OmniSharp/omnisharp-vscode#364]
VSCOde version: 1.1.0-alpha
OS: Windows10
Steps:
1. Create new C# project using >dotnet new command.
2. Launch VSCode and configure for build task.
3. Create task and build project.
5. Now add some invalid syntax in program.cs and build the project.
6. Verify message in output window.

Actual: Getting message like "Couldn't find 'project.json' in current directory"
Expected: Should show message related to syntax error.

![image](https://cloud.githubusercontent.com/assets/17735796/15457197/c27c643e-2039-11e6-9a6f-5d0526fbdf8a.png)

![image](https://cloud.githubusercontent.com/assets/17735796/15457212/f5f35a0c-2039-11e6-8bdc-02c80dd14e25.png)

Tasks.json:
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "dotnet",
    "isShellCommand": true,
    "args": [],
    "cwd":"${workspaceRoot}/TestCSharpWithVSCode",
    "tasks": [
        {
            "taskName": "build",
            "args": [],
            "isBuildCommand": true,
            "showOutput": "always",
            "problemMatcher": "$msCompile"               
        }
    ]
}

**Comment by DustinCampbell** [comment]
This issue is quite stale. Is it still a problem?
