### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by groundsquirrel** [OmniSharp/omnisharp-vscode#3645]
<ul>
<li>Issue Type: <code>Performance</code></li>
<li>Extension Name: <code>csharp</code></li>
<li>Extension Version: <code>1.21.13</code></li>
<li>OS Version: <code>Windows_NT x64 10.0.16299</code></li>
<li>VSCode version: <code>1.42.1</code></li>
</ul>

[ms-dotnettools.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4308130/ms-dotnettools.csharp-unresponsive.cpuprofile.txt)

**Comment by jenskalusniak** [comment]
Same here:
Extension: ms-dotnettools.csharp
VSCode version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:44:52.965Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-7629-generic

**Comment by Grandizer** [comment]
Yes.

- Issue Type: `Bug`
- Extension Name: `csharp`
- Extension Version: `1.21.13`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.42.1`

**Comment by juhoheikkilae** [comment]
Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

[ms-dotnettools.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4314330/ms-dotnettools.csharp-unresponsive.cpuprofile.txt)

**Comment by ahuertabhg** [comment]
- Issue Type: `Bug`
- Extension Name: `csharp`
- Extension Version: `1.21.13`
- OS Version: `Windows_NT x64 10.0.16299`
- VSCode version: `1.43.0`

[ms-dotnettools.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4318492/ms-dotnettools.csharp-unresponsive.cpuprofile.txt)

The extension is completely unresponsive and useless at the moment.

**Comment by XeonG** [comment]
Latest version really does seem to tank vscode and break a number of other extensions like gitlens just isn't responsive at all, and vscode cpu% is chewing cores, it also breaks a few other extensions that relied on the old extension name.  I've rolled back to the previous version.

**Comment by marioquercafe** [comment]
- Issue Type: Bug
- Extension Name: csharp
- Extension Version: 1.21.14

vscode:
- Version: 1.43.0 (user setup)
- Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
- Date: 2020-03-09T19:47:57.235Z
- Electron: 7.1.11
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Windows_NT x64 10.0.18362

**Comment by springbov** [comment]
Same issue as reported by the OP

## Logs ##
[ms-dotnettools.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4326909/ms-dotnettools.csharp-unresponsive.cpuprofile.txt)

## Environment information ##

**VSCode version**: 1.44.0
**C# Extension**: 1.21.14

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.21.14|
|team|ms-vsts|1.161.0|
|vim|vscodevim|1.13.0|
|vscode-icons|vscode-icons-team|10.0.0|
|vscode-jest|Orta|3.1.1|;

</details>

**Comment by Grandizer** [comment]
[ms-dotnettools.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4329212/ms-dotnettools.csharp-unresponsive.cpuprofile.txt)

VSCode version: 1.44.0
C# Extension: 1.21.14

**Comment by qidydl** [comment]
[ms-dotnettools.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4330899/ms-dotnettools.csharp-unresponsive.cpuprofile.txt)

VSCode version: 1.42.1
OS: Windows_NT x64 10.0.17763
C# Extension: 1.21.14

**Comment by frankyjuang** [comment]
[ms-dotnettools.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4331404/ms-dotnettools.csharp-unresponsive.cpuprofile.txt)

ms-dotnettools.csharp-1.21.14

Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by FomTarro** [comment]
[ms-dotnettools.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4332889/ms-dotnettools.csharp-unresponsive.cpuprofile.txt)

Same issue. In addition to spiking the CPU, OmniSharp fails to load. This means C# intellisense is currently broken.

VSCode Version: 1.43.0

**Comment by zendu** [comment]
Same issue:
Version: 1.44.0-insider (user setup)
Commit: b7bfce30be3c30aa2c33fbe94fe82b81d4105668
Date: 2020-03-17T07:17:39.113Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19587

[ms-dotnettools.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4345122/ms-dotnettools.csharp-unresponsive.cpuprofile.txt)

**Comment by jonaspm** [comment]
[ms-dotnettools.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4350306/ms-dotnettools.csharp-unresponsive.cpuprofile.txt)
Same issue here.

`OmniSharp server started with Mono 6.4.0.
    Path: /Users/pc/.vscode/extensions/ms-dotnettools.csharp-1.21.14/.omnisharp/1.34.14/omnisharp/OmniSharp.exe`

Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by JoeRobich** [comment]
Please try the [v1.21.15](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.15) prerelease and let us know if it resolves your performance issue.

**Comment by jonaspm** [comment]
> Please try the [v1.21.15](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.15) prerelease and let us know if it resolves your performance issue.

I confirm that the performance issues are gone. 🎉

**Comment by juhoheikkilae** [comment]
> I confirm that the performance issues are gone. 🎉

Same here.

**Comment by Grandizer** [comment]
Great that it is working.  However, I am not sure how to install a pre-release extension.  The .visix file is failing, even after uninstall of current .14 version and a restart.

**Comment by JoeRobich** [comment]
@groundsquirrel   Thanks for the report. Closing this now that 1.21.15 has been published.
