### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by br3aker** [OmniSharp/omnisharp-vscode#3646]
Fresh VS Code setup, C#/Unity project.

- Issue Type: `Bug`
- Extension Name: `csharp`
- Extension Version: `1.21.13`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.42.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 74,
		"activateCallTime": 6,
		"activateResolvedTime": 55,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-dotnettools.csharp",
				"_lower": "ms-dotnettools.csharp"
			},
			"activationEvent": "onLanguage:csharp"
		}
	},
	"runtimeErrors": []
}
```

**Comment by JoeRobich** [comment]
This will be resolved once Unity publishes a new release containing this fix https://github.com/Unity-Technologies/vscode-unity-debug/pull/152

**Comment by cartermp** [comment]
Since the PR is merged on the unity side I'll close this out.
