### ISSUE TITLE
inheritdoc + cref

### ISSUE THREAD

**Issue by ZacharyPatten** [OmniSharp/omnisharp-vscode#3652]
The `inheritdoc` feature in C# let's you use `cref` to specify the member you want to inherit documentation from.

It doesn't look like the C# extension for Visual Studio Code supports this functionality yet (but it is supported in Visual Studio). For example, when you hover over members of code that use `inheritdoc`+`cref` the documentation is blank (not populating).

It was also recently added to ms docs: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/inheritdoc

If this feature could be added to the C# Visual Studio Code extension it would be really nice. :)

Example:
```cs
class Program
{
	/// <summary>Hello World</summary>
	public static void A() { }

	/// <inheritdoc cref="A"/>
	public static void B() { }

	public static void Main()
	{
		A(); // <- Documentation Populated In UI
		B(); // <- Documentation Not Populated In UI
	}
}
```

**Comment by cartermp** [comment]
Might be because OmniSharp doesn't have the most recent Roslyn; if not, then some feature work is needed. @JoeRobich to investigate the update

**Comment by dietermijle** [comment]
+1

**Comment by 333fred** [comment]
This will be fixed by https://github.com/OmniSharp/omnisharp-roslyn/pull/1860.
