### ISSUE TITLE
OmniSharp.MSBuild.ProjectManager Support to .NET 5

### ISSUE THREAD

**Issue by mauriliofilho** [OmniSharp/omnisharp-vscode#3653]
## Environment data
SDK do .NET Core (refletindo qualquer global.json):
 Version:   5.0.100-preview.3.20161.4
 Commit:    dfe6198dc5

Ambiente de runtime:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.3.20161.4\

Host (useful for support):
  Version: 5.0.0-preview.2.20155.1
  Commit:  e2881ae96b

.NET Core SDKs installed:
  2.1.804 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.3.20161.4 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.3.20156.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.2.20155.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.3.20161.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

# VS Code version:
1.44.0 Insider
# C# Extension version:
1.21.13
## Steps to reproduce
Install SDK of .NET 5 preview on 
[.NET 5 PReview](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe)
run dotnet new mvc -n MyApp
genarate app with verssion default dotnet .Net 5 Preview, see in file genarate .csproj targetframework netcoreapp5.

run cd/dir MyApp

run code-insider .
(Already C# Extenssion installed)

## Expected  behavior
Loaded .csproj correctly
## Actual behavior
receiving messa on console Failed to load project file 'c:\Users\username\MyApp01\MyApp2\MyApp.csproj'.

Seeing message to install .NET Core 3.1 or older

**Comment by filipw** [comment]
we need to update MsBuild 16.5, it's the minimum for .NET 5
