### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by pogo575** [OmniSharp/omnisharp-vscode#3659]
- Issue Type: `Bug`
- Extension Name: `csharp`
- Extension Version: `1.21.14`
- OS Version: `Darwin x64 16.4.0`
- VSCode version: `1.43.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by cartermp** [comment]
Closing this as there is no information in the report. If you have a more detailed problem, please ping back here and we can re-open it.
