### ISSUE TITLE
Intellisense taking minutes to be available

### ISSUE THREAD

**Issue by andymads** [OmniSharp/omnisharp-vscode#3661]
## Issue Description ##
I have several projects that now take several minutes for the intellisense information to appear, and for the functionality to be available. This seems to be a recent change.

During most of this time a process named Code Helper (Renderer) is using pretty much 100% of the CPU.

A colleague was on an older version of Code and didn't have this issue until updating to 1.43.0. I have tried 1.42.1 and 1.41.1 but I still get the issue.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.43.0
**C# Extension**: 1.21.14

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.6.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.2.104 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.8|
|csharp|ms-dotnettools|1.21.14|
|playfab-explorer|Playfab|0.1.7|
|unity-debug|Unity|2.7.2|
|vscode-azurefunctions|ms-azuretools|0.21.0|;

</details>

**Comment by JoeRobich** [comment]
@zvinless Can you provide a complete OmniSharp log? And is the code that this reproduces on available for us to test against?

**Comment by JoeRobich** [comment]
Please try the [v1.21.15](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.15) prerelease and let us know if it resolves your performance issue.

**Comment by andymads** [comment]
Thanks.

Yes, that's better. Probably takes 20 seconds for intellisense to be ready
now. Is that the expected wait?

**Comment by JoeRobich** [comment]
@andymads It all depends on the size of your workspace (Number of projects, number of references, etc...). 20 seconds is actually pretty good compared to larger solutions like the Rolsyn repo. =)

**Comment by zvinless** [comment]
@JoeRobich the code is not available, but the v1.21.15 prerelease is a huge improvement over the previous version. I haven't done a precise comparison but I think the delay before intellisense is in the same ballpark as v1.21.12. Let me know if a log would still be helpful.

**Comment by JoeRobich** [comment]
@zvinless We made an additional improvement in the release build of 1.21.15 where we remove any file searching. I would hope it matches performance with 1.21.12 at this point. If you have any issue with the new release please open an issue and we will look into it.
