### ISSUE TITLE
[Bug] Self-closing tag inside an if statement

### ISSUE THREAD

**Issue by ofrades** [OmniSharp/omnisharp-vscode#3662]
VS Code version: latest
C# Extension version: latest

## Steps to reproduce
In the index page inside an if statement add a component with self-closing tag.

## Expected  behavior
Self-closing tag should behave as closed and not as still open.

## Actual behavior
![image](https://user-images.githubusercontent.com/31070771/76647784-5f141a80-6555-11ea-97de-4a2b45324b11.png)

![image](https://user-images.githubusercontent.com/31070771/76647825-6b987300-6555-11ea-97bb-691c7fa0d114.png)

**Comment by NTaylorMullen** [comment]
oo is this a colorization issue?

**Comment by ofrades** [comment]
Yes, I think so.

**Comment by NTaylorMullen** [comment]
Moved to https://github.com/dotnet/aspnetcore/issues/19839 to track the work. Thanks for the report @ofrades!
