### ISSUE TITLE
C# plugin hangs and cause high CPU usage while opening a big project 

### ISSUE THREAD

**Issue by heshuimu** [OmniSharp/omnisharp-vscode#3664]
## Issue Description ##
Since C# plugin 1.21.13, the C# plugin seems to hang when I open a project with more than 700 files. There is also a side effect that causes `extensionHosts` to max out a single CPU core. It can be reproduced 100% of the time and I have not experience the hang to finish at any point. 

**EDIT: ** My project is a Unity project

1.21.12 was the last version that was working properly for me. 

## Steps to Reproduce ##
1. Open my project with C# plugin 1.21.13 or 1.21.14 installed
2. Observe OmniSharp log to stop at a point
3. Observe `extensionHosts` using nearly 100 unit of CPU
![image](https://user-images.githubusercontent.com/7824592/76670500-d5694a80-655e-11ea-92b9-3fec00089d53.png)

## Expected Behavior ##
Project loads properly (Omnisharp prints "solution initialized") in about a minute, Code Lens and jump to declaration works properly. 

## Actual Behavior ##
Project does not finish loading, Reference Code Lens does not appear and jump to declaration does not work.

### OmniSharp log ###
The log contains file names to an already-live project, so I am hesitant to share. 
In summary, the log stops at the same line of text every time when the issue occurs.

### C# log ###
None

## Environment information ##

**VSCode version**: 1.43.0
**C# Extension**: 1.21.13

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.8.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.101
 Commit:    bc5f8df0f5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.101/

Host (useful for support):
  Version: 3.0.1
  Commit:  32085cbc72

.NET Core SDKs installed:
  2.1.103 [/usr/local/share/dotnet/sdk]
  2.1.505 [/usr/local/share/dotnet/sdk]
  3.0.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0-rc2-3002702 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.26.3|
|csharp|ms-dotnettools|1.21.13|
|FlatUI|lkytal|1.4.9|
|theme-bluloco-light|uloco|3.0.1|
|theme-flatui|danibram|3.1.0|
|theme-karyfoundation-themes|karyfoundation|20.0.3|
|vscode-antlr4|mike-lischke|2.2.3|
|vscode-clang|mitaki28|0.2.3|
|vscode-icons|vscode-icons-team|10.0.0|
|xcode-default-theme|smockle|2.0.21|;

</details>

**Comment by zvinless** [comment]
I'm experiencing similar issues with a nearly identical environment. This sounds similar to #3661, but it might be that large projects take a really, really long time until code lens and other features are available. I left my project open for a long time (like, did some housework and came back) and the extension features did eventually start working.

**Comment by Bzucko** [comment]
+1
For me 1.21.12 is also last working ver. (9sec. takes to load solution file and another 4sec. to drop CPU@0%).
1.21.14...2min. takes to load solution file(code.exe utilize one core@100%) and another~1min. to drop CPU usage to 0%

My project...562 C# files ~5.45MB

**Comment by mmoore99** [comment]
I am experiencing similar issues.

**Comment by manuel999999** [comment]
I had to migrate to Visual Studio, couldn't work in vs code anymore </3 just gonna wait for next update

**Comment by JoeRobich** [comment]
@savpek Not sure if it is related to this, but I noticed this bit in omnisharp-roslyn where we seem to queue all solution files for analysis despite solution size - https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorkerWithAnalyzers.cs#L81. Should the client be responsible for queueing this initial bit of analysis?

**Comment by savpek** [comment]
It probably could be. It actually doesn't even need new API from omnisharp-roslyn side even since `ReAnalyzeRequest` can trigger same routine.

However i don't think this is realeated to this behavior 🤔 When i open solution with 2500+ files omnisharp takes only 1 core worth of cpu since analysis isn't concurrent and it works immediatly (codelens etc) after projects are loaded (analysis happens at background).

@heshuimu test set `omnisharp.enableRoslynAnalyzers` false and true to check difference, if its not enabled solution wide analysis after startup isn't made at all. Does that affect startup speed in any way?

**Comment by filipw** [comment]
also, the common theme in all those high CPU issues was that 1.21.12 works fine and 1.21.13 not. there were no server side changes bettween 12->13 I believe, only client side changes

**Comment by mdowais** [comment]
I am facing this issue, and so far i have noted one thing.

My Project is of ASP.NET CORE + Angular, everything was working fine before an Auto Update screwed it up. 

My Findings :

1) Revo Uninstalled VSCode, No Fix
2) VsCode Insider also faces this isssue.
3) No issue with a blank MVC or webapi template 
4) Not causing issue when creating a new dotnet core + angular project `dotnet new angular` 
node_modules installed, and all is well

Notable Findings:
5) Removed node_modules folder inside the angular client folder in my project, **works**
6) Ran npm i, restarted IDE **SCREWED UP Again** (Note: yes my project depends on alot of npm which should not be related to omnisharp correct?)

So node_modules maybe causing trouble, and i don't have much idea about Unity Engine, but does it use node_modules?

and is there a hack to make omnisharp completely ignore the node_modules or angular client folder which _may_ make it work??

**Comment by JoeRobich** [comment]
@mdowais Thank you so much for your investigation. I was looking through the changes in 1.21.13 and I think you hit on it being the node_modules folder.

@NTaylorMullen I believe this glob is chewing up the CPU for users with large node_modules. https://github.com/OmniSharp/omnisharp-vscode/pull/3593/files#diff-8c9691b11e7b8efdf4865f5653a295c5R175

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen I believe this glob is chewing up the CPU for users with large node_modules. https://github.com/OmniSharp/omnisharp-vscode/pull/3593/files#diff-8c9691b11e7b8efdf4865f5653a295c5R175

Oh goodness! Wow that's awful, i'll absolutely take a stab at making that code more targeted instead of diving the whole directory.

**Comment by mdowais** [comment]
> @mdowais Thank you so much for your investigation. I was looking through the changes in 1.21.13 and I think you hit on it being the node_modules folder.
> 
> @NTaylorMullen I believe this glob is chewing up the CPU for users with large node_modules. https://github.com/OmniSharp/omnisharp-vscode/pull/3593/files#diff-8c9691b11e7b8efdf4865f5653a295c5R175
> 
> We've had several users share .cpuprofiles which showed a large amount of time in the glob package, but I didn't give it much weight since I know the heavy lifting is done in .NET.

That was fast...  Happy to help the community! GodSpeed @JoeRobich @NTaylorMullen

**Comment by heshuimu** [comment]
> @heshuimu test set `omnisharp.enableRoslynAnalyzers` false and true to check difference, if its not enabled solution wide analysis after startup isn't made at all. Does that affect startup speed in any way?

I did try this before posting as suggested in other previous issues. It did not make a difference.

**Comment by JoeRobich** [comment]
Please try the [v1.21.15](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.15) prerelease and let us know if it resolves your performance issue.

**Comment by heshuimu** [comment]
> Please try the [v1.21.15](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.15) prerelease and let us know if it resolves your performance issue.

This version resolves my issue.

**Comment by heshuimu** [comment]
> Please try the [v1.21.15](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.15) prerelease and let us know if it resolves your performance issue.

This version resolves my issue.

**Comment by mdowais** [comment]
> Please try the [v1.21.15](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.15) prerelease and let us know if it resolves your performance issue.

Confirming that 1.21.15 solves the issue! That was real Quick, Thanks..  I guess this should be moved to release, many of my friends are in trouble because of this @JoeRobich

**Comment by JoeRobich** [comment]
@mdowais It'll be published soon. Right now it is in validation testing.

**Comment by Bzucko** [comment]
works as expected ;-)

**Comment by JoeRobich** [comment]
@heshuimu Thanks for the report. Closing this now that 1.21.15 has been published.
