### ISSUE TITLE
OmniSharp doesn't show build errors anymore

### ISSUE THREAD

**Issue by gmarokov** [OmniSharp/omnisharp-vscode#3669]
## Issue Description ##
After recent update, Omnisharp no longer shows build errors or warnings.
I have to make edit to a file to see the highlighted problems. Also when build error is fixed, again have to reedit the file to clear the error notifications. 

## Expected Behavior ##
OmniSharp used to highlight build errors and warnings before save or build.

### OmniSharp log ###
<details>Starting OmniSharp server at 3/14/2020, 6:24:37 PM
    Target: /home/georgi/Projects/autohub

OmniSharp server started.
    Path: /home/georgi/.vscode/extensions/ms-dotnettools.csharp-1.21.14/.omnisharp/1.34.14/run
    PID: 16544

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on fedora 31.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.4 - "/home/georgi/.vscode/extensions/ms-dotnettools.csharp-1.21.14/.omnisharp/1.34.14/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/georgi/.vscode/extensions/ms-dotnettools.csharp-1.21.14/.omnisharp/1.34.14/omnisharp/.msbuild/Current/Bin/MSBuild.dll'</details>

### C# log ###
<details>Installing C# dependencies...
Platform: linux, x86_64, name=fedora, version=31

Downloading package 'OmniSharp for Linux (x64)' (43753 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Linux (x64)'</details>

## Environment information ##

**VSCode version**: 1.43.0
**C# Extension**: 1.21.14

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.1.801
 Commit:    c404ee777a

Runtime Environment:
 OS Name:     fedora
 OS Version:  31
 OS Platform: Linux
 RID:         fedora.31-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.801/

Host (useful for support):
  Version: 2.1.12
  Commit:  ccea2e606d

.NET Core SDKs installed:
  2.1.801 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-close-tag|formulahendry|0.5.6|
|auto-rename-tag|formulahendry|0.1.1|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|code-settings-sync|Shan|3.4.3|
|code-spell-checker|streetsidesoftware|1.8.0|
|csharp|ms-dotnettools|1.21.14|
|csharpextensions|jchannon|1.3.1|
|debugger-for-chrome|msjsdiag|4.12.6|
|docomment|k--kato|0.1.8|
|dotnet-test-explorer|formulahendry|0.7.1|
|githistory|donjayamanne|0.6.2|
|gitignore|codezombiech|0.6.0|
|gitlens|eamodio|10.2.1|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|php-intellisense|felixfbecker|2.3.14|
|project-manager|alefragnani|10.11.0|
|remote-wsl|ms-vscode-remote|0.42.3|
|theme-cobalt2|wesbos|2.1.6|
|todo-tree|Gruntfuggly|0.0.169|
|vscode-coverage-gutters|ryanluker|2.4.3|
|vscode-diff|fabiospampinato|1.4.0|
|vscode-docker|ms-azuretools|1.0.0|
|vscode-eslint|dbaeumer|2.1.1|
|vscode-great-icons|emmanuelbeziat|2.1.47|
|vscode-language-babel|mgmcdermott|0.0.26|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-todo-highlight|wayou|1.0.4|
|vscode-yaml|redhat|0.7.2|
|vscodeintellicode|VisualStudioExptTeam|1.2.6|;

</details>

**Comment by JoeRobich** [comment]
@gmarokov Can you provide the complete OmniSharp and C# logs? If what you provided is complete then, it could be an install error. try reinstalling.

**Comment by gmarokov** [comment]
> @gmarokov Can you provide the complete OmniSharp and C# logs? If what you provided is complete then, it could be an install error. try reinstalling.

That's the whole log. I just reinstalled it, and the issue persists. There are no logs in C# and in OmniSharp I see that last entry `[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 218.` but I don't have a .sln file, can that be the issue? 
I just deleted one file and as you can see on build I get the errors, but don't see them highlighted in the file explorer.
![Screenshot from 2020-03-18 15-49-06](https://user-images.githubusercontent.com/12663998/76967516-3f536c80-6930-11ea-9a51-5087c48437f4.png)

**Comment by gmarokov** [comment]
Thanks for the support guys, but suddenly was fixed with the latest release.
