### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by HRYooba** [OmniSharp/omnisharp-vscode#3671]
- Issue Type: `Bug`
- Extension Name: `csharp`
- Extension Version: `1.21.14`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.43.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by cartermp** [comment]
Hello, closing this as there is no data in the report. If you have a reproduction to share for the issue you're seeing, we can re-open this and go from there.
