### ISSUE TITLE
is:issue state:open "Extension causes high cpu load" 

### ISSUE THREAD

**Issue by jxnczyp** [OmniSharp/omnisharp-vscode#3674]
When I use unity-deubg, C#, VIM at the same time, I can't input it

**Comment by jxnczyp** [comment]
C#1.21.14
Debugger for unity 2.7.3
vim 1.13.0

**Comment by JoeRobich** [comment]
Closed as duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3660
