### ISSUE TITLE
Errors not shown, codeactions called all the time when I have all code analysis turned off.

### ISSUE THREAD

**Issue by numbelvis** [OmniSharp/omnisharp-vscode#3686]
##Issue Description ##
All code analysis is turned off and /codeactions continually is called.
Actual errors in my code are not reported until you actually open the file with the error in it.
Reinstall and it works for anywhere from a few minutes to a few days until it breaks again.

## Steps to Reproduce ##
Wish I could, but this has happened for the last year happens on multiple machines we use
We have a solution setup properly and omni is using the solution.

## Expected Behavior ##
Don't call /codeactions constantly all the time
Show me the correct set of errors in the problems tab always without having to browse to files.

## Actual Behavior ##
/codeactions called all the time

### OmniSharp log ###
[dbug]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 2072,
  "Command": "/v2/getcodeactions",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "CodeActions": [
      {
        "Identifier": "Wrap every parameter -> Align wrapped parameters",
        "Name": "Wrap every parameter -> Align wrapped parameters"
      },
      {
        "Identifier": "Wrap every parameter -> Indent all parameters",
        "Name": "Wrap every parameter -> Indent all parameters"
      },
      {
        "Identifier": "Wrap every parameter -> Indent wrapped parameters",
        "Name": "Wrap every parameter -> Indent wrapped parameters"
      },
      {
        "Identifier": "Unwrap and indent all parameters",
        "Name": "Unwrap and indent all parameters"
      },
      {
        "Identifier": "Pull 'Validate(string moleculePrimaryKeyID, T t)' up -> Pull 'Validate' up to 'IValidationRuleDefinition'",
        "Name": "Pull 'Validate(string moleculePrimaryKeyID, T t)' up -> Pull 'Validate' up to 'IValidationRuleDefinition'"
      }
    ]
  },
  "Seq": 8437,
  "Type": "response"
}

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.43.0
**C# Extension**: 1.21.15

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.102\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.21.15|
|rest-client|humao|0.23.1|
|vscode-guid|heaths|1.4.19|
|vscode-icon-theme|jtlowe|1.6.5|
|vsliveshare|ms-vsliveshare|1.0.1711|;

</details>
 clipboard

**Comment by cartermp** [comment]
Thanks for filing the issue @numbelvis. This is arguably not a well-design option, of which there isn't really an analogue in VS either. So adjusting this would imply a more holistic design, since there's different levels of suggestions people may want to see.

**Comment by numbelvis** [comment]
Ahh ok, I thought may be that was the case.  Thanks for taking time!
