### ISSUE TITLE
launch.json: Start multi-target debugging in one launch configuration not working

### ISSUE THREAD

**Issue by adymorz** [OmniSharp/omnisharp-vscode#3695]
Issue Type: <b>Bug</b>

```
{
	"name": "Debug server and client",
	"type": "coreclr",
	"request": "launch",
	"preLaunchTask": "build",
	"program": "${workspaceFolder}/build/myTool.dll",
	"args": [],
	"cwd": "${workspaceFolder}",
LaunchJson-Console
	"console": "internalConsole",
	"stopAtEntry": false,
	"requireExactSource": true,
	"serverReadyAction": {
		"pattern": "Now listening on: http://[^0-9]*(.+)",
		"uriFormat": "http://localhost:%s",
		"action": "debugWithChrome"
	}
},
```

1. Use the configuration above to start debugging the server and client at once
2. Two debug session are started, but only the youngest session is shown in the debug toolbar. I expcted to see both sessions in the debug toolbar.

VS Code version: Code - Insiders 1.44.0-insider (e62c4302b0e4f3e28bbcb0f3b6e46bb00e39679c, 2020-03-26T05:51:24.240Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (6.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.21.15

</details>

**Comment by adymorz** [comment]
Issue hast been first created in vscode project: https://github.com/microsoft/vscode/issues/93523

**Comment by JoeRobich** [comment]
@adymorz We don't have any influence over how the session are displayed in the debug toolbar. I know when using compound configurations you will see a dropdown in the toolbar. However, I think VS Code treats using the "debugWithChrome" action differently.

I do see that you can access the step into/over controls when hovering over the Chrome debug session in the Call Stack panel.
![image](https://user-images.githubusercontent.com/611219/77808265-d793d480-7047-11ea-9dd8-b4a7ab4a055b.png)

**Comment by JoeRobich** [comment]
@adymorz I hope that is a sufficient workaround. Otherwise, you'll need to open a feature request on VS Code to handle the "debugWithChrome" action differently.
