### ISSUE TITLE
Add Go To Implementation

### ISSUE THREAD

**Issue by AhmedAzzabi** [OmniSharp/omnisharp-vscode#37]
Go to implementaiton is more useful in most cases than going to definition, is there a way to add to VScode

**Comment by DustinCampbell** [comment]
There isn't a way to add this yet, but we'll definitely get to it.

**Comment by CarlosTorrecillas** [comment]
Do you guys have an ETA on this yet?

**Comment by ivanz** [comment]
There is now a way to add this in vscode 1.9 (need to implement `ImplementationProvider` and register it via `vscode.languages.registerImplementationProvider`)

**Comment by DustinCampbell** [comment]
Yup -- I noticed this as well.

**Comment by jchannon** [comment]
Awesome!
