### ISSUE TITLE
C# extension loading forever

### ISSUE THREAD

**Issue by iouzzrj** [OmniSharp/omnisharp-vscode#3701]
## Issue Description ##
I found if I use OmniSharp: select current project too fast, the IntelliSense will not working.

## Steps to Reproduce ##
Steps to Reproduce:

1. Open an existing C# project folder
2. View->Command Palette->OmniSharp: select project->select current project
3. In Explorer->Outline tab, you can see "Loading document symbols for 'Program.cs'"
4. Do not wait this Loading procedure to complete, just go back to step 2, selecting this project again
5. You can see in Outline tab, the "Loading document symbols for 'Program.cs'" will last forever, you will lost IntelliSense function as a result.

## Expected Behavior ##
IntelliSense works normally.

## Actual Behavior ##
IntelliSense does not work.

### OmniSharp log ###
<details>Starting OmniSharp server at 2020/3/31 下午8:06:47
    Target: c:\Users\iouzz\Documents\Code\Chapter02\NullHandling

OmniSharp server started.
    Path: C:\Users\iouzz\.vscode\extensions\ms-dotnettools.csharp-1.21.15\.omnisharp\1.34.14\OmniSharp.exe
    PID: 17168

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.5.29911.84 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.4 - "C:\Users\iouzz\.vscode\extensions\ms-dotnettools.csharp-1.21.15\.omnisharp\1.34.14\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.5.29911.84 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\iouzz\Documents\Code\Chapter02\NullHandling'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\iouzz\Documents\Code\Chapter02\NullHandling'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\iouzz\Documents\Code\Chapter02\NullHandling\NullHandling.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\iouzz\Documents\Code\Chapter02\NullHandling'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\iouzz\Documents\Code\Chapter02\NullHandling\NullHandling.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\iouzz\Documents\Code\Chapter02\NullHandling' on host 2156.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\iouzz\Documents\Code\Chapter02\NullHandling\NullHandling.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\iouzz\Documents\Code\Chapter02\NullHandling\NullHandling.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: NullHandling</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.43.2
**C# Extension**: 1.21.15

<details><summary>Dotnet Information</summary>
.NET Core SDK����ӳ�κ� global.json��:
 Version:   3.1.201
 Commit:    b1768b4ae7

����ʱ����:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.21.15|
|csharpextensions|jchannon|1.3.1|;

</details>

**Comment by iouzzrj** [comment]
I compare the log with a normal log, I think they are the same. So the bug is not recorded in OmniSharp log.

**Comment by cartermp** [comment]
Thanks for reporting. @iouzzrj, do you have a repro to share where you consistently see this? Or do you see it with any existing project?

**Comment by iouzzrj** [comment]
> Thanks for reporting. @iouzzrj, do you have a repro to share where you consistently see this? Or do you see it with any existing project?

@cartermp Sorry for the late reply.
I don't have a repo, but I think every new project can reproduce this bug by using my steps, can you give a try?

**Comment by cartermp** [comment]
I cannot reproduce this with several projects. I picked a nontrivial one like Tye to no avail: https://github.com/dotnet/tye

Note that the extension does say that things are finished loading. But there is no tooling that will light up. So there is a separate issue here, which I'll tentatively track in #3694
