### ISSUE TITLE
Syntax Highlighting issues with async foreach

### ISSUE THREAD

**Issue by mshinnie** [OmniSharp/omnisharp-vscode#3709]
Issue Type: <b>Bug</b>

So I have async yield function and when I call this function inside using await foreach all of the syntax highlighting goes away as it does not highlight keywords such as 'if' 'try' 'catch' or 'for'.  Is this a known issue?
![image](https://user-images.githubusercontent.com/59614964/78815365-c9be4780-7995-11ea-95c3-95a8ef1b4b89.png)

Extension version: 1.21.16
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (7.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by JoeRobich** [comment]
@mshinnie Please try out the semantic highlighting in our [1.21.19-beta1](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.19-beta1) release.

**Comment by haysch** [comment]
@JoeRobich It works with version 1.21.19-beta and above.
Thanks a lot, it was driving me crazy!

**Comment by filipw** [comment]
this is fixed with semantic highlighitng
