### ISSUE TITLE
Errors when building solution which contains both C# .csproj and F# .fsproj projects.

### ISSUE THREAD

**Issue by jpierson** [OmniSharp/omnisharp-vscode#371]
I see the following error for each .fsproj project referenced by another C# .csproj project.

> Unable to resolve project reference

**Comment by DustinCampbell** [comment]
Hi @jpierson, how are you building the project within VS Code?

**Comment by jpierson** [comment]
Default msbuild task. I'll try to post the content when I have a chance.

**Comment by DustinCampbell** [comment]
Sorry, I'm not sure I understand. Do you have a tasks.json set up to build your project within VS Code? Could I see the content of that?

**Comment by jp7677** [comment]
I'm not sure if this is the same problem that the original author describes, but I'm seeing that intellisense/omnisharp within VS Code doesn't know how to handle a references F# project. 

Please see my sample project here: https://github.com/jp7677/hellocoreclr. Within src I have a c# and an f# project. When opening the c# class that uses the referenced f# project (https://github.com/jp7677/hellocoreclr/blob/master/src/app/GetHelloWorldAction.cs) omnisharp gets to work, but can't resolve the f#. The project builds and runs just fine using "dotnet build"/"dotnet run".

**Comment by DustinCampbell** [comment]
@jp7677: That's generally expected (at least if the project isn't built yet), since neither OmniSharp nor the C# Extension for VS Code have any notion of F#.

**Comment by jp7677** [comment]
Hi @DustinCampbell, thanks for your answer. What do mean by "at least if the project isn't built yet"? Is there a way to give a hint to Omnisharp/C# Extension how to resolve references or to point it to an assembly? Even after building VS Code can't resolve the types coming from the f# project.

**Comment by DustinCampbell** [comment]
Sorry for not being clear @jp7677. My point was that the C# Extension for VS Code _should_ be able to resolve types from the F# project if it's output is built and on disk. If it doesn't, that's definitely a bug. However, it will not be able to resolve types if the F# project's assembly is not built, like it can with other C# projects. Does that make sense?

**Comment by jp7677** [comment]
Makes totally sense, thanks @DustinCampbell ;)
Unfortunately, I still got the "The name '[f# module]' does not exist in the current context [netcoreapp1.0]" error in VS Code after building and writing to disk and some VS Code restarts or omnisharp project switches. Should I enter a new issue? Where/for which project should I do that?

**Comment by zgramana** [comment]
In my case, my C# project references two bin-wrapped libraries, one is an F# library and the other is a C# library. Same results as above. Compiles and executes fine via `dotnet`, but OmniSharp reports type and namespace resolution errors.

**Comment by luisrudge** [comment]
@DustinCampbell anything we can do to help you nail this issue?

**Comment by jp7677** [comment]
@luisrudge No, unfortunately not, my VS Code still complains with above message. Though would also love to help to get this resolved.

**Comment by luisrudge** [comment]
@DustinCampbell what we can do to help fix this?

**Comment by haf** [comment]
Me too.

Repro: open Logary https://github.com/logary/logary and navigate to `Program.cs` in `CSharpExample`.

**Comment by haf** [comment]
@luisrudge 

> Somebody needs to set a breakpoint and start debugging to be able to figure out what to do here. I don't know what change needs to be made.

**Comment by DustinCampbell** [comment]
I have a pretty good idea what's causing this. I have a plan to fix it, but it'll need to wait until 1.11.

**Comment by DustinCampbell** [comment]
I'll leave this open until there's a new C# for VS Code beta with this fix.

**Comment by DustinCampbell** [comment]
I just wanted to let everyone here know that I just released on a new beta of C# for VS Code that should fix this issue: [1.3.0-beta5](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.13.0-beta5). You can following [these instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) if you're interested in trying it out.

**Comment by ntwilson** [comment]
So excited for this fix!  Just tried it out and works perfectly.  Thank you so much!

**Comment by DustinCampbell** [comment]
Awesome! Thanks for confirming.

**Comment by cbioley** [comment]
@DustinCampbell It works for me too, which is veeeeery cool, thanks!

**Comment by mrgleba** [comment]
Is there a chance to get intelisense from referenced f# projects as well?
Right now I get "The type or namespace name 'XXXX' does not exist in the namespace 'YYYY' (are you missing an assembly reference?)" error for every type from a F# lib (everything builds/runs fine).

**Comment by DustinCampbell** [comment]
You will need to build the F# projects first.

**Comment by DustinCampbell** [comment]
That is, build the project and then restart OmniSharp or VS Code. There's future work to watch the metadata output of now C# projects and reload it.

**Comment by DustinCampbell** [comment]
I just noticed that we didn't have a work item tracking this, so I added https://github.com/OmniSharp/omnisharp-roslyn/issues/1008.

**Comment by WallaceKelly** [comment]
I am still seeing this behavior -- even with 1.14.0. and after "build the F# projects first."

Here is how I reproduce... 

    dotnet new library -lang F# -o .\ClassLibrary
    dotnet new console -lang C# -o .\MainProgram
    dotnet new sln
    dotnet sln add .\ClassLibrary\ClassLibrary.fsproj
    dotnet sln add .\MainProgram\MainProgram.csproj
    dotnet add .\MainProgram\MainProgram.csproj reference .\ClassLibrary\ClassLibrary.fsproj

_add this line code to program.cs:_ `ClassLibrary.Say.hello("world.");`

    dotnet run -p .\MainProgram\MainProgram.csproj

All the above succeeds on the command line. However, opening in VS Code shows these errors:

    The name 'ClassLibrary' does not exist in the current context [MainProgram]

    [fail]: OmniSharp.MSBuild.ProjectLoader
        The target "GetTargetPath" does not exist in the project.
    c:\Temp\vstest\MainProgram\MainProgram.csproj

I only see the "GetTargetPath" error when I am referencing an F# library from a C# project. I do not see it on a C#-only project.

**Comment by DustinCampbell** [comment]
Hey @WallaceKelly : Sorry for the delay. Could you file a new issue rather than necro-ing a closed issue? Thanks!
