### ISSUE TITLE
OmniSharp server

### ISSUE THREAD

**Issue by Aimedcresent00** [OmniSharp/omnisharp-vscode#3710]
Issue Type: <b>Bug</b>

Ive been looking up on this issue and im new to using VS Code and its the only editor I had to work successfully using C# on my chromebook before the error that is the server failing to load repeatedly if theres no way around the problem it would be so kind of you to point me in the direction of another tool as great as this is to use that is supported by linux 

Extension version: 1.21.16
VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T11:22:13.689Z)
OS version: Linux x64 4.19.98-08076-g24ab33fb8e14

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/5c (2 x 1094)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|2.73GB (0.56GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|100%|
</details>

**Comment by cartermp** [comment]
Thanks for filing @Aimedcresent00 - could you share your OmniSharp log? Without it we can't tell what is going on. Thanks!
