### ISSUE TITLE
Cant debug Asp.NetCore mvc app VSCode Arch Linux

### ISSUE THREAD

**Issue by dcruz1990** [OmniSharp/omnisharp-vscode#3711]
## Environment dat
SDK de .NET Core (reflejando cualquier global.json):
 Version:   3.0.103
 Commit:    b7ef045669

Entorno de tiempo de ejecución:
 OS Name:     arcolinux
 OS Version:  v20.1.4
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/dennisqc/.dotnet/sdk/3.0.103/

Host (useful for support):
  Version: 3.0.3
  Commit:  c03f2fe626

.NET Core SDKs installed:
  3.0.103 [/home/dennisqc/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [/home/dennisqc/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [/home/dennisqc/.dotnet/shared/Microsoft.NETCore.App]

VS Code version:
C# Extension version:
1.21.16

## Steps to reproduce
Clone a project, restore, install omnisharp, install debuger and the other packages that comes with. Configure attach debug, set a breakpoint, run the debugger.. 

## Expected  behavior
Fully load debugger, stop when reaches breakpoint.

## Actual behavior
Doesnt fully load debugger, nothing happens when reach breakpoint.

**Comment by WardenGnaw** [comment]
In your `launch.json`, can you add the following:

```
"logging": {
   "engineLogging": true
}
```

and share the output from the debug console?

**Comment by dcruz1990** [comment]
It works when i set to "launch" instead of "attach".
