### ISSUE TITLE
VS Debugger warning in VS Code for C#

### ISSUE THREAD

**Issue by shivshanks** [OmniSharp/omnisharp-vscode#3715]
Issue Type: <b>Bug</b>

I have downloaded and installed VS Code from the official Microsoft site but I keep getting the following warning while debugging with C# -
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------

Extension version: 1.21.16
VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (0.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by WardenGnaw** [comment]
This is not a debugger warning, this is the legal banner for using the Microsoft .NET Core Debugger (vsdbg).

**Comment by shivshanks** [comment]
But I am using it with the Microsoft distributed version of VS Code and it being printed in Orange/Yellow Color does seem like a sort of out of the ordinary to me.  

While searching for this issue, I saw various posts that said that one should not see this in the Microsoft distributed version of VS Code. I am technically running it in VS Code, so I don't see a reason for it to show the banner. I'm sorry but to me personally it looks very distracting. I also don't understand why it should show when I run the program without debugging.

Please let me know if this a problem with vsdbg as opposed to some misconfig here, where it can't identify as being run within VS Code, and I can look into filing an issue against them.

**Comment by WardenGnaw** [comment]
At the moment, this banner will appear for any Visual Studio product that uses vsdbg. 

You may be interested in https://github.com/OmniSharp/omnisharp-vscode/issues/3706
