### ISSUE TITLE
Wrong value of watched variable is copied if it has format specifier

### ISSUE THREAD

**Issue by deitry** [OmniSharp/omnisharp-vscode#3719]
## Issue Description ##
If there is variable in Watch section of debugger and it has format specifier, then wrong value will be copied to clipboard on `Copy Value`

## Steps to Reproduce ##
- Have any program that has `int a = -1`
- Set breakpoint on the next step
- Launch
- Add `a` to Watch. `-1` will be displayed
- Specifiy format, like `a,h` to display `a` as hex. Result will be something like `0xffffffff`
- Right-click on it and then `Copy Value`
- Paste value somewhere. 

## Expected Behavior ##
- `0xffffffff` is pasted

## Actual Behavior ##
- `4294967295` is pasted in my case

## Environment information ##

**VSCode version**: 1.44.0
**C# Extension**: 1.21.16

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|11.1.0|
|bracket-pair-colorizer-2|CoenraadS|0.0.29|
|cpptools|ms-vscode|0.27.0|
|csharp|ms-dotnettools|1.21.16|
|gitlens|eamodio|10.2.1|
|indent-rainbow|oderwat|7.4.0|
|vscode-checkpoints|micnil|1.3.0|
|vscode-language-pack-ru|MS-CEINTL|1.44.2|
|vscode-todo-highlight|wayou|1.0.4|
|vscode-todo-plus|fabiospampinato|4.16.0|;

</details>

**Comment by cartermp** [comment]
@WardenGnaw is this a debugger component issue, or is this more in what data we're passing to it?

**Comment by WardenGnaw** [comment]
Just tried the scenario and I could not reproduce the issue.
![image](https://user-images.githubusercontent.com/3953714/79273275-95480100-7e57-11ea-8903-0ad45b1dbf34.png)

My copy buffer gets `0xffffffff`

From the debug logs, 
```
-> (C) {"command":"evaluate","arguments":{"expression":"a,h","frameId":1000,"context":"watch"},"type":"request","seq":20}
<- (R) {"seq":54,"type":"response","request_seq":20,"success":true,"command":"evaluate","message":"","body":{"result":"0xffffffff","type":"int","presentationHint":{"kind":"data","attributes":[]},"variablesReference":0,"memoryReference":"0xFFFFFFFFFFFFFFFF"}}
```
the only string that should exist in the watch window is `0xffffffff`

@deitry Can you enable logs by adding the following to your `launch.json` configuration:
```
"logging" {
   "engineLogging": true
}
```
and share the output from the debug console?

**Comment by deitry** [comment]
`int a = -1;`:
```
-> (C) {"command":"evaluate","arguments":{"expression":"0xffffffff","frameId":1000,"context":"watch"},"type":"request","seq":45}
<- (R) {"seq":84,"type":"response","request_seq":45,"success":true,"command":"evaluate","message":"","body":{"result":"4294967295","type":"uint","presentationHint":{"kind":"data","attributes":["readOnly","constant"]},"variablesReference":0,"memoryReference":"0x00000000FFFFFFFF"}}
```
See responce > body > result


`int a = -1;` without hex specifier:
```
-> (C) {"command":"evaluate","arguments":{"expression":"-1","frameId":1000,"context":"watch"},"type":"request","seq":83}
<- (R) {"seq":143,"type":"response","request_seq":83,"success":true,"command":"evaluate","message":"","body":{"result":"-1","type":"int","presentationHint":{"kind":"data","attributes":["readOnly","constant"]},"variablesReference":0,"memoryReference":"0xFFFFFFFFFFFFFFFF"}}
```
Note that response > body > type is `int` now, though was `uint` with hex specifier.

Same for `long b = -1L`;
```
-> (C) {"command":"evaluate","arguments":{"expression":"0xffffffffffffffff","frameId":1000,"context":"watch"},"type":"request","seq":48}
<- (R) {"seq":86,"type":"response","request_seq":48,"success":true,"command":"evaluate","message":"","body":{"result":"18446744073709551615","type":"ulong","presentationHint":{"kind":"data","attributes":["readOnly","constant"]},"variablesReference":0,"memoryReference":"0xFFFFFFFFFFFFFFFF"}}
```

Just added `-1L,h` to watch
```
-> (C) {"command":"evaluate","arguments":{"expression":"0xffffffffffffffff","frameId":1000,"context":"watch"},"type":"request","seq":156}
<- (R) {"seq":261,"type":"response","request_seq":156,"success":true,"command":"evaluate","message":"","body":{"result":"18446744073709551615","type":"ulong","presentationHint":{"kind":"data","attributes":["readOnly","constant"]},"variablesReference":0,"memoryReference":"0xFFFFFFFFFFFFFFFF"}}
```

**Comment by deitry** [comment]
Oh, in your case request asks for the _variable_ evaluation and in my case request goes with _actual value_.

Here is full log when I try to add watch `a,h`
```
-> (C) {"command":"evaluate","arguments":{"expression":"a,h","frameId":1000,"context":"watch"},"type":"request","seq":13}
-> (C) {"command":"scopes","arguments":{"frameId":1000},"type":"request","seq":14}
<- (R) {"seq":29,"type":"response","request_seq":14,"success":true,"command":"scopes","message":"","body":{"scopes":[{"name":"Locals","variablesReference":1001,"expensive":false}]}}
-> (C) {"command":"variables","arguments":{"variablesReference":1001},"type":"request","seq":15}
<- (R) {"seq":30,"type":"response","request_seq":13,"success":true,"command":"evaluate","message":"","body":{"result":"0xffffffffffffffff","type":"long","presentationHint":{"kind":"data","attributes":[]},"variablesReference":0,"memoryReference":"0xFFFFFFFFFFFFFFFF"}}
<- (R) {"seq":31,"type":"response","request_seq":15,"success":true,"command":"variables","message":"","body":{"variables":[{"name":"args [string[]]","value":"{string[0]}","type":"string[]","presentationHint":{"kind":"data","attributes":["canHaveObjectId"]},"evaluateName":"args","variablesReference":0,"memoryReference":"0x00000206B3199BE8"},{"name":"a [long]","value":"-1","type":"long","presentationHint":{"kind":"data","attributes":[]},"evaluateName":"a","variablesReference":0,"memoryReference":"0xFFFFFFFFFFFFFFFF"},{"name":"b [ulong]","value":"18446744073709551615","type":"ulong","presentationHint":{"kind":"data","attributes":[]},"evaluateName":"b","variablesReference":0,"memoryReference":"0xFFFFFFFFFFFFFFFF"},{"name":"bits [ArrayStates]","value":"null","type":"sharp_test.ArrayStates","presentationHint":{"kind":"data","attributes":[]},"evaluateName":"bits","variablesReference":0}]}}
```
You can see that response with seq == 30 do it correctly and evaluates an expression.

But when I hit `Copy Value`:
```
-> (C) {"command":"evaluate","arguments":{"expression":"0xffffffffffffffff","frameId":1000,"context":"watch"},"type":"request","seq":20}
<- (R) {"seq":36,"type":"response","request_seq":20,"success":true,"command":"evaluate","message":"","body":{"result":"18446744073709551615","type":"ulong","presentationHint":{"kind":"data","attributes":["readOnly","constant"]},"variablesReference":0,"memoryReference":"0xFFFFFFFFFFFFFFFF"}}
```
it evaluates not expression but actual value.

**Comment by WardenGnaw** [comment]
@deitry Sorry for the delay in response. The incorrect `expression` being sent was an issue with VSCode, they have fixed the Evaluate Request in https://github.com/microsoft/vscode/commit/de3e5a4bf4beaf404d06d4375f6b5d3cd24c3ef8

If you try this with the latest vscode-insiders, do you still experience this issue?

**Comment by deitry** [comment]
It's working correctly even in the latest stable.
Thanks!
