### ISSUE TITLE
Create VSIXs for each targeted OS/distro for offline installation

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-vscode#372]
We need separate VSIXs that target each OS/distro that we support for the purpose of offline installation:

* Windows
* OS X
* Linux (Ubuntu, Debian, RHEL, CentOS)

These will include the appropriate debugger and OmniSharp bits so that they don't need to be downloaded.

**Comment by DustinCampbell** [comment]
@chuckries, I just heard you're looking at this.

**Comment by chuckries** [comment]
@DustinCampbell yes, I am about to submit a PR that adds a gulp task to do the debuggers installation up front.
