### ISSUE TITLE
Feature request: string interpolation auto fill suggestion

### ISSUE THREAD

**Issue by alexzms** [OmniSharp/omnisharp-vscode#3726]
## Description ##
while using string interpolation there should be suggestions while typing variables in {}
## Example ##
int exampleVar = 5;
Console.WriteLine($"{exampleVar}");
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
i want an auto suggestion while i'm typing this 
## Expected Behavior ##
when i type an "e" in "{}", it auto suggest me that exampleVar is capable for this and i can
press tab to auto fill it inside

## Environment information ##

**VSCode version**: 1.44.1
**C# Extension**: 1.21.17

**Comment by filipw** [comment]
it's already there, just disabled by default. you need to add the following setting to VS Code settings:

```
    "editor.quickSuggestions": {
        "strings": true
    }
```

Altenratively, you can always press ctrl+space to manually trigger autocomplete.

**Comment by alexzms** [comment]
> it's already there, just disabled by default. you need to add the following setting to VS Code settings:
> 
> ```
>     "editor.quickSuggestions": {
>         "strings": true
>     }
> ```
> 
> Alternatively, you can always press ctrl+space to manually trigger autocomplete.

got it thanks!
