### ISSUE TITLE
Intellisense VsCode Unity dont work

### ISSUE THREAD

**Issue by Ucalmeida** [OmniSharp/omnisharp-vscode#3727]
Starting OmniSharp server at 16/04/2020 14:42:37
    Target: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Galaxy Shooter.sln

OmniSharp server started.
    Path: C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\OmniSharp.exe
    PID: 10484

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.4 - "C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild
            MSBuildToolsPath = C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Galaxy Shooter.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEngine.TestRunner.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEngine.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.TextMeshPro.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.Timeline.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.TextMeshPro.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.Timeline.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEditor.TestRunner.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEditor.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.Rider.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.CollabProxy.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.VSCode.Editor.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEngine.TestRunner.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter' on host 844.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEngine.TestRunner.csproj'.
d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEngine.TestRunner.csproj
C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1177,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEngine.UI.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEngine.UI.csproj'.
d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEngine.UI.csproj
C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1177,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.TextMeshPro.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.TextMeshPro.csproj'.
d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.TextMeshPro.csproj
C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1177,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.Timeline.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.Timeline.csproj'.
d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.Timeline.csproj
C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1177,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Assembly-CSharp.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Assembly-CSharp.csproj'.
d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Assembly-CSharp.csproj
C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1177,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.TextMeshPro.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.TextMeshPro.Editor.csproj'.
d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.TextMeshPro.Editor.csproj
C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1177,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.Timeline.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.Timeline.Editor.csproj'.
d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.Timeline.Editor.csproj
C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1177,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEditor.TestRunner.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEditor.TestRunner.csproj'.
d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEditor.TestRunner.csproj
C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1177,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEditor.UI.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEditor.UI.csproj'.
d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEditor.UI.csproj
C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1177,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.Rider.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.Rider.Editor.csproj'.
d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.Rider.Editor.csproj
C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1177,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.CollabProxy.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.CollabProxy.Editor.csproj'.
d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.CollabProxy.Editor.csproj
C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1177,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.VSCode.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.VSCode.Editor.csproj'.
d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.VSCode.Editor.csproj
C:\Users\UrianAlmeida\.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1177,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEngine.TestRunner.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEngine.UI.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.TextMeshPro.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.Timeline.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Assembly-CSharp.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.TextMeshPro.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.Timeline.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEditor.TestRunner.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\UnityEditor.UI.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.Rider.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.CollabProxy.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: d:\Desenvolvimento Jogos\Galaxy Shooter\Galaxy Shooter\Unity.VSCode.Editor.csproj

**Comment by cartermp** [comment]
Hey @Ucalmeida, it seems like you don't have .NET Framework 4.7.1 developers tools installed on your machine. This is required to do Unity or other work that required .NET Framework. You can follow the links in your log or go here to download and install the developer pack: https://dotnet.microsoft.com/download/dotnet-framework

Once that is installed, things should work.

**Comment by Elnahas** [comment]
I think have same Error :
.vscode\extensions\ms-dotnettools.csharp-1.21.17\.omnisharp\1.35.0\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1177,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

I Solve this problem , so I install .NETFramework,Version=v4.7.1  ^^ ...

**Comment by Ucalmeida** [comment]
Thanks guys, but I solved this problem in a simpler way. I just gave the command 'dotnet build' and intellisense went back to work. Of course, I need to do this every time I start the project, then I'll create a sln to see if it solves this, but it's working!
