### ISSUE TITLE
How can I change the version of C#?

### ISSUE THREAD

**Issue by LuckJmg** [OmniSharp/omnisharp-vscode#3728]
## Issue Description ##
Apparently the predefined version of c# is version 4, and no matter how much I have searched I have not found how to change it since I need to use c# 7.
So this is my last resource, could you help me?
Thank you for your attention, I hope you are well

## Environment information ##

**VSCode version**: 1.44.2
**C# Extension**: 1.21.17

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.5.0|
|better-comments|aaron-bond|2.0.5|
|Bookmarks|alefragnani|11.1.0|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|code-settings-sync|Shan|3.4.3|
|code-spell-checker|streetsidesoftware|1.8.0|
|cs-script|oleg-shilo|1.6.4|
|csharp|ms-dotnettools|1.21.17|
|csharpextensions|jchannon|1.3.1|
|ecdc|mitchdenny|1.3.0|
|EditorConfig|EditorConfig|0.14.5|
|gitlens|eamodio|10.2.1|
|guides|spywhere|0.9.3|
|minify|HookyQR|0.4.3|
|path-intellisense|christian-kohler|1.4.2|
|prettier-vscode|esbenp|4.4.0|
|python|ms-python|2020.3.71659|
|rescuetime|RescueTime|1.0.1|
|swdc-vscode|softwaredotcom|2.1.56|
|vscode-fileutils|sleistner|3.0.1|
|vscode-icons|vscode-icons-team|10.1.1|
|vscode-markdownlint|DavidAnson|0.34.0|
|vscode-taskexplorer|spmeesseman|1.26.3|
|vscode-versionlens|pflannery|0.25.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.6|;

</details>

**Comment by JoeRobich** [comment]
In case others find this issue and are looking for an answer. In your .csproj file you can add `<LanguageVersion>7.3</LanguageVersion>` to the `<PropertyGroup>` at the top of the file.
