### ISSUE TITLE
Last loaded section OmniSharp.MSBuild.ProjectManager, from there it doesn't loads anymore. 

### ISSUE THREAD

**Issue by ChristopherMiranda00** [OmniSharp/omnisharp-vscode#3740]
## Environment data
`dotnet --info` output:
VS Code version: 1.44.2
C# Extension version: 1.21.17

.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.200/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.200 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

## Steps to reproduce
Open VScode and click on the OUTPUT section in the terminal. I downloaded MONO 6.6.0 (VS channel) so the intellisense work with Unity because I had the problem where the .NET FRAMWORK 4.71 was need but it is only for windows. 

## Expected  behavior
The full output of the OMNISHARP. 

## Actual behavior
It stops in OmniSharp.MSBuild.ProjectManager
![Captura de Pantalla 2020-04-22 a la(s) 13 55 36](https://user-images.githubusercontent.com/42215186/80024981-85f33400-84a5-11ea-9de7-b0d562295e28.png)

**Comment by JoeRobich** [comment]
@ChristopherMiranda00 Sorry you are running into this issue. Can you try stable channel Mono 6.8.0 and let us know if that resolves your problem loading? I know the 6.6.0 download says Visual Studio channel but that is in reference to VS for Mac and it may not work well with C# extension for VS Code.

**Comment by ChristopherMiranda00** [comment]
@JoeRobich Thank for the quick response. I have already uninstall the previous mono version and installed mono 6.8.0, but the same problem appears. 
![Captura de Pantalla 2020-04-22 a la(s) 18 06 55](https://user-images.githubusercontent.com/42215186/80042349-5ef82a80-84c4-11ea-8c31-0dd8e5f97f07.png)

**Comment by ChristopherMiranda00** [comment]
@JoeRobich Thanks! It works now, owe you one.
