### ISSUE TITLE
C# extension remotly on RPi 4

### ISSUE THREAD

**Issue by mfertala** [OmniSharp/omnisharp-vscode#3741]
## Environment data
`dotnet --info` output:
Zestaw .NET Core SDK (odzwierciedlenie dowolnego pliku global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Środowisko uruchomieniowe:
 OS Name:     raspbian
 OS Version:  10
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /home/pi/dotnet/sdk/3.1.200/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.200 [/home/pi/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/home/pi/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/home/pi/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version:
Version: 1.44.2 (system setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.3.9600

C# Extension version:
1.21.17 - Extension is enabled on 'SSH: myRaspberryPiIP'

## Steps to reproduce
walk thru instructions:
https://github.com/OmniSharp/omnisharp-vscode/wiki/Remote-Debugging-On-Linux-Arm

Open VS Code with project folder

## Expected  behavior
C# extension working properly

## Actual behavior
Got error info:
The C# extension for Visual Studio Code (powered by OmniSharp) is incompatiable on linux armv7l with the VS Code Remote Extensions. To see avaliable workarounds, click on 'How to setup Remote Debugging'.
![cs_extension](https://user-images.githubusercontent.com/15068794/80087344-3ff8a780-855b-11ea-8847-481274634b19.JPG)

**Comment by gregg-miskelly** [comment]
Hi @mfertala, you are references the correct wiki page (https://github.com/OmniSharp/omnisharp-vscode/wiki/Remote-Debugging-On-Linux-Arm), but you aren't quite following the instructions as they do NOT tell you to use the VS Code remote extension feature. This extension doesn't support running on ARM (see #2771). Up to you of course, but if ARM support is added to this extension I would recommend against using it in remote scenarios -- the language service can be quite compute intensive, so you are better off building locally and copying than trying to do everything on the Pi.

**Comment by Aemilivs** [comment]
When was it broken? I remember it working perfectly fine not this much time ago 🤔

**Comment by gregg-miskelly** [comment]
@Aemilivs If you are asking about running this extension on ARM (not remote debugging): no, it has never been supported.
