### ISSUE TITLE
Omnisharp fails to install extensions: libmono-native.so not found

### ISSUE THREAD

**Issue by surafel911** [OmniSharp/omnisharp-vscode#3747]
## Issue Description ##
OmniSharp appears to fails to fully install the extensions properly. VSCode says that they are installed, but Omnisharp fails to start.

## Steps to Reproduce ##
This was a clean installation straight from xbps. I added the C#, C# Extensions, and Auto-Using for C# extensions, but Omnisharp fails. I'm unsure if Omnisharp was still failing before I attempted to install extensions. I have uninstalled/reinstalled, and restarted VSCode several times and got the same behavior.

## Expected Behavior ##
That the extensions should be installed and working. I have the same combination of extensions on Windows, and it works fine there.

## Actual Behavior ##
None of the extensions are working and I get the following output log.

### OmniSharp log ###
Starting OmniSharp server at 4/27/2020, 2:27:20 PM
    Target: /home/surafel/coding/pizza-shop-webservice/PizzaShopWebService

OmniSharp server started.
    Path: /home/surafel/.vscode-oss/extensions/ms-dotnettools.csharp-1.21.17/.omnisharp/1.35.0/run
    PID: 1864

System.TypeInitializationException: The type initializer for 'System.ComponentModel.TypeDescriptor' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Sys' threw an exception. ---> System.DllNotFoundException: /home/surafel/.vscode-oss/extensions/ms-dotnettools.csharp-1.21.17/.omnisharp/1.35.0/lib/../lib/libmono-native.so assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Interop+Sys.LChflagsCanSetHiddenFlag()
  at Interop+Sys..cctor () [0x00000] in <a1ae6166591d4020b810288d19af38d4>:0 
   --- End of inner exception stack trace ---
  at Interop.GetRandomBytes (System.Byte* buffer, System.Int32 length) [0x00000] in <a1ae6166591d4020b810288d19af38d4>:0 
  at System.Guid.NewGuid () [0x00000] in <a1ae6166591d4020b810288d19af38d4>:0 
  at System.ComponentModel.TypeDescriptor..cctor () [0x00034] in <4bf78e13a6ea4494a3898e6a836a77f4>:0 
   --- End of inner exception stack trace ---
  at OmniSharp.Internal.CommandOptionExtensions.GetValueOrDefault[T] (McMaster.Extensions.CommandLineUtils.CommandOption opt, T defaultValue) [0x00008] in <65b65aa47dd84527b66fbba929d6fb42>:0 
  at OmniSharp.Stdio.StdioCommandLineApplication.get_Encoding () [0x00000] in <37764013d46e4991957fbb61092f4a0f>:0 
  at OmniSharp.Stdio.Driver.Program+<>c__DisplayClass0_1.<Main>b__1 () [0x00000] in <39c041771cd1431b86cfe218e1a00ebe>:0 
  at OmniSharp.CommandLineApplication+<>c__DisplayClass11_0.<OnExecute>b__0 () [0x0000b] in <65b65aa47dd84527b66fbba929d6fb42>:0 
  at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute (System.String[] args) [0x00039] in <344a1e8cd6594b17b1e01f8df6ae8827>:0 
  at OmniSharp.CommandLineApplication.Execute (System.String[] args) [0x00081] in <65b65aa47dd84527b66fbba929d6fb42>:0 
  at OmniSharp.Stdio.Driver.Program+<>c__DisplayClass0_0.<Main>b__0 () [0x00028] in <39c041771cd1431b86cfe218e1a00ebe>:0 
  at OmniSharp.HostHelpers.Start (System.Func`1[TResult] action) [0x0001c] in <65b65aa47dd84527b66fbba929d6fb42>:0 
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

## Environment information ##
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     void
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/surafel/.dotnet/sdk/3.1.201/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [/home/surafel/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/home/surafel/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/home/surafel/.dotnet/shared/Microsoft.NETCore.App]

**VSCode version**: 1.44.2
**C# Extension**: 1.21.17

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     void
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/surafel/.dotnet/sdk/3.1.201/

**NOTE: I don't have any environment variable paths set up for dotnet or VSCode. Not sure if I needed any.

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [/home/surafel/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/home/surafel/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/home/surafel/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-using|Fudge|0.7.15|
|csharp|ms-dotnettools|1.21.17|
|csharpextensions|jchannon|1.3.1|;

</details>

**Comment by JoeRobich** [comment]
@surafel911 Sorry you are running into issues. This certainly sounds like an installation issue of some sort as we package and ship the missing file as part of OmniSharp. Would it be possible for you to share the full OmniSharp output log?  

Until we get this sorted you could try installing Mono 6.8.0 from the official feed (https://www.mono-project.com/download/stable/) as a workaround.

**Comment by surafel911** [comment]
How exactly do I get the full log? The log that I posted is everything that shows in the output tab of the console in VSCode.

**Comment by JoeRobich** [comment]
@surafel911 I don't currently see any OmniSharp log output in the issue description. It looks like the `dotnet --info` output was accidentally pasted as the OmniSharp Log and the Environment Info sections above. 

![image](https://user-images.githubusercontent.com/611219/80420989-8d914f00-8890-11ea-8df8-92e42d84b25e.png)

**Comment by surafel911** [comment]
Oh, didn't notice. Fixed it.

**Comment by JoeRobich** [comment]
@surafel911 I tried to investigate a bit and apparently Void Linux doesn't like to install on Hyper-V. I'm wonder if there is some mono pre-requisite that isn't in a default Void Linux installation. Have you tried installing mono using xbps to see if you have better luck?

**Comment by surafel911** [comment]
That seems to have done the trick. I need to install both `mono` and `msbuild-bin` packages in Void. I will leave this issue open if you need anything from me.
