### ISSUE TITLE
Feature: Provide a setting to pause automatic restoring while running a build task

### ISSUE THREAD

**Issue by jfalameda** [OmniSharp/omnisharp-vscode#3748]
In our project we have a special build talk for service fabric on Linux, that means that we execute a bash script that performs quite peculiar tasks. Our issue is that while we are doing it VS c# tries to restore our project resulting in a build failure.

It would be great to have some way to disable this functionality while executing VS talks.

**Comment by JoeRobich** [comment]
@jfalameda Sorry you are running into issues. Can you help me understand how this build tasks is being run? Is it VS Code build task in your tasks.json file or a custom MSBuild task? If it is a VS Code build task, can you share the tasks.json configuration for it?

**Comment by jfalameda** [comment]
Thanks for the quick reply. In my case it is a custom build task defined in tasks.json

`{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build",
            "command": "bash ./build.sh -m -r",
            "type": "shell",
            "problemMatcher": "$tsc"
        },
...
`

**Comment by JoeRobich** [comment]
@jfalameda When you say the C# extension tries to restore your project, is it by the "Some projects failed to load. Would you like to restore?" dialog?  Also, to help me understand how the script might trigger a restore, does the bash script invoke a `dotnet build` or change the contents of your project folder?

**Comment by jfalameda** [comment]
Hi, yes, that is correct. Our script does a dotnet build and a dotnet
publish and copies the contents to a build folder that later on will be
uploaded to service fabric.

Yes, during that process we get that error "Some projects failed to load."
I am not sure why, but maybe because we publish for another platform Linux
while running VS on a mac.

**Comment by JoeRobich** [comment]
@jfalameda For a run that causes the "Some projects failed to load.", could you share the contents of your OmniSharp Log from the VS Code Output panel?

**Comment by cartermp** [comment]
Closing out as no additional info was given
