### ISSUE TITLE
Is OpenDebugAD7.dll open source?

### ISSUE THREAD

**Issue by DavidKarlas** [OmniSharp/omnisharp-vscode#375]
Hi,

I'm wondering if https://www.nuget.org/packages/Microsoft.VisualStudio.OpenDebugAD7 is open source or if there is plan to open source it?

Thank you,
David

**Comment by gregg-miskelly** [comment]
It is currently not open sourced. There isn't any reason why it can't be -- it just hasn't been a priority. Are there specific reasons you would like it to be?

**Comment by DavidKarlas** [comment]
As my side project I'm writing MonoDevelop/Xamarin Studio AddIn for debugging .Net Core...  Makes more sense to implement VSCode debugging protocol, since we also get TypeScript and all other protocols you guys make(maybe even mono)

Would be nice to be able to build all code needed, so I can fix some bugs if I run into...
Not super high priority...
