### ISSUE TITLE
Auto created launch.json has wrong project output path

### ISSUE THREAD

**Issue by RIPRoyale** [OmniSharp/omnisharp-vscode#3750]
Latest stable VScode, c# extension, and .NET SDK. Just downloaded.

## Steps to reproduce
Open a new workspace, run dotnet new console to create Hello world project
Press yes on the omnisharp recommendation to add the build and debug assets.
Try to run the program.

## Expected  behavior
At that point the program will run, and output will show.

## Actual behavior
Error appears that
"launch: program
'File location .dll' Does not exist"

**Comment by cartermp** [comment]
@RIPRoyale I can't reproduce this as written on my machine. Can you share your `tasks.json` and `launch.json` file that was generated?

**Comment by RIPRoyale** [comment]
I should probably add I'm on Windows 10.

tasks.json
`
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/helloworld.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "publish",
            "command": "dotnet",
            "type": "process",
            "args": [
                "publish",
                "${workspaceFolder}/helloworld.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "watch",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "run",
                "${workspaceFolder}/helloworld.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        }
    ]
}
`
launch.json
`
{
   // Use IntelliSense to find out which attributes exist for C# debugging
   // Use hover for the description of the existing attributes
   // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
   "version": "0.2.0",
   "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/bin/Debug/netcoreapp3.1/helloworld.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            // For more information about the 'console' field, see https://aka.ms/VSCode-CS-LaunchJson-Console
            "console": "internalConsole",
            "stopAtEntry": false
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}`

I think I found the error. It's in launch.json.
It say's "program": "${workspaceFolder}/bin/Debug/netcoreapp3.1/helloworld.dll",
However the output file is in "${workspaceFolder}/bin/MCD/Debug/netcoreapp3.1/helloworld.dll",

I know that I can just change it myself, however in the beginner tutorial at https://code.visualstudio.com/docs/languages/csharp
It doesn't give instructions to do that, which can be confusing for beginners.

**Comment by gregg-miskelly** [comment]
Do you know what 'MCD' is? Normally there is not an extra directory between 'bin' and 'Debug'. If you don't know either, can you open a command prompt and run `set | findstr MCD` to see if it the value of some environment variable?

**Comment by gregg-miskelly** [comment]
Ah. I bet this is your problem: https://stackoverflow.com/questions/18795530/error-invalid-platform-variable-mcd

Delete the 'Platform' environment variable from your computer, and all should work.

**Comment by RIPRoyale** [comment]
Yes, this was the problem. I think the variable has something to do with HP Notebooks. Thanks!
