### ISSUE TITLE
omnisharp-vscode

### ISSUE THREAD

**Issue by trungkien047** [OmniSharp/omnisharp-vscode#3756]
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.44.2
**C# Extension**: 1.21.17

<details><summary>Dotnet Information</summary>
A valid dotnet installation could not be found.</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.21.17|;

</details>

**Comment by JoeRobich** [comment]
@trungkien047 Please open a new issue if you are experiencing trouble with the extension. Please include information so that we can assist. Closing this one. =)
