### ISSUE TITLE
Unable to fold C# code when this extension is installed.

### ISSUE THREAD

**Issue by chengkiang** [OmniSharp/omnisharp-vscode#3757]
## Issue Description ##
With this extension installed as recommended by VSCode, I can no longer fold code blocks like if/else, for loops, functions, etc. Code folding only works for *.cs files if I uninstall this extension.

## Steps to Reproduce ##
1. Install this extension.
2. Open a C# file.
3. The if/else blocks, function blocks, etc can no longer be folded.

## Expected Behavior ##
* The if/else blocks, etc should be foldable.

<img width="364" alt="without extension" src="https://user-images.githubusercontent.com/24908779/81143023-9d511780-8fa3-11ea-8b53-31c84c6c392f.png">

## Actual Behavior ##
* The if/else blocks, function blocks, etc cannot be folded with this extension installed. This happens on both macOS and Windows.

<img width="373" alt="with extension" src="https://user-images.githubusercontent.com/24908779/81143028-a0e49e80-8fa3-11ea-90f2-fe3db8d834b4.png">

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.44.2
**C# Extension**: 1.21.18

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.201/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|code-runner|formulahendry|0.10.0|
|csharp|ms-dotnettools|1.21.18|
|permute-lines|earshinov|1.1.0|
|python|ms-python|2020.4.76186|
|vetur|octref|0.24.0|
|vscode-css-formatter|aeschli|1.0.1|
|vscode-docker|ms-azuretools|1.1.0|
|vscode-yaml|redhat|0.7.2|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by adnanshussain** [comment]
Exactly the same problem.

**Comment by KrisNie** [comment]
Exactly the same problem.

**Comment by ZhaoZhitao** [comment]
Exactly the same problem.

**Comment by pbischoff** [comment]
Same problem here

**Comment by AntonioRedondo** [comment]
Folding is gone with the [C#](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) 1.23.16 extension installed. 😥

**Comment by JoeRobich** [comment]
@AntonioRedondo Please open a new issue and include the requested logs, especially the Omnisharp Log from the output pane.
