### ISSUE TITLE
My Omnisharp is giving .net version error how to fix it?

### ISSUE THREAD

**Issue by GeneralPY101** [OmniSharp/omnisharp-vscode#3758]
My omnisharp is giving net framework 4.7.2 required error as net framework 4.6 is installed on my pc. Below is my _dotnet --info_
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
As my PC is running on windows build 10240 I cannot install net framework 4.7.2. So I cannot run C# on VSCode. Is there any way out? Will it work if I install older version of omnisharp?

**Comment by cartermp** [comment]
@GeneralPY101 You can install .NET Framework 4.7.2 and its targeting pack here: https://dotnet.microsoft.com/download/dotnet-framework/net472

If your project depends on .NET Framework 4.7.2, then you'll need to install it on your machine to be able to use that project.

**Comment by GeneralPY101** [comment]
But I get operating system not supported error on .net 4.7.2

**Comment by cartermp** [comment]
You'll need to update your Windows machine. That's an old build of Windows that is also out of support now.
