### ISSUE TITLE
Debugger licensing errors are not reported to the UI

### ISSUE THREAD

**Issue by Iron-E** [OmniSharp/omnisharp-vscode#3759]
## Issue Description ##
When attempting to debug a program using step-debugging, VSCode will compile the program, but no code will execute.

## Steps to Reproduce ##

1. Take a simple `Program.cs`, such as this:
	```cs
	namespace Foo
	{
		internal static class Program
		{
			internal static void Main()
			{
				var foobar = "Hello World!";
				System.Console.WriteLine(foobar);
			}
		}
	}
	```
2. Follow the instructions [here](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md).
3. Add a breakpoint to the `System.Console…` line.
4. Press F5 to begin debugging.
5. Notice that the program will never finish executing, nor will it allow you to step-in or view values of any code.
	![Screenshot](https://user-images.githubusercontent.com/36409591/81217577-5deaf100-8fcc-11ea-88bb-5cf3440a90a5.png)
	* The debug navigator. Notice that the options are mostly greyed-out and pressing "Pause" does nothing.

## Expected Behavior ##

The debugger will allow me to step-debug code, and also will allow me to finish execution of code that has no errors.

## Actual Behavior ##

The debugger does not allow me to step-debug code, and does not appear to execute any code.

### OmniSharp log ###

<details><summary>Log</summary>
<code>
Starting OmniSharp server at 5/6/2020, 2:52:04 PM
    Target: /home/iron-e/Programming/Issues/Omnisharp/Debugger/Test.sln

OmniSharp server started with Mono 6.4.0.
    Path: /home/iron-e/.vscode-oss/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/OmniSharp.exe
    PID: 3567

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on arch 0.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[warn]: OmniSharp.MSBuild.Discovery.Providers.MonoInstanceProvider
        It looks like you have Mono 6.4.0 or greater installed but MSBuild could not be found.
Try installing MSBuild into Mono (e.g. 'sudo apt-get install msbuild') to enable better MSBuild support, or upgrade to latest Mono: https://www.mono-project.com/download/stable/.
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.4 - "/home/iron-e/.vscode-oss/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/iron-e/.vscode-oss/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "/home/iron-e/.vscode-oss/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/iron-e/.vscode-oss/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/iron-e/.vscode-oss/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/iron-e/.vscode-oss/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild
[fail]: OmniSharp.Services.AssemblyLoader
        An error occurred when attempting to access '/home/iron-e/Programming/Issues/Omnisharp/Debugger/~/.omnisharp/Roslynator/src/Core/bin/Debug/netstandard2.0/Roslynator.Core.dll'.
System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/iron-e/Programming/Issues/Omnisharp/Debugger/~/.omnisharp/Roslynator/src/Core/bin/Debug/netstandard2.0/Roslynator.Core.dll'.
  at System.IO.Enumeration.FileSystemEnumerator`1[TResult].CreateDirectoryHandle (System.String path, System.Boolean ignoreNotFound) [0x00032] in <c4bddbfe864a4b8191bb818d6b204e9d>:0
  at System.IO.Enumeration.FileSystemEnumerator`1[TResult]..ctor (System.String directory, System.IO.EnumerationOptions options) [0x00048] in <c4bddbfe864a4b8191bb818d6b204e9d>:0
  at System.IO.Enumeration.FileSystemEnumerable`1+DelegateEnumerator[TResult]..ctor (System.IO.Enumeration.FileSystemEnumerable`1[TResult] enumerable) [0x00000] in <c4bddbfe864a4b8191bb818d6b204e9d>:0
  at System.IO.Enumeration.FileSystemEnumerable`1[TResult]..ctor (System.String directory, System.IO.Enumeration.FileSystemEnumerable`1+FindTransform[TResult] transform, System.IO.EnumerationOptions options) [0x00042] in <c4bddbfe864a4b8191bb818d6b204e9d>:0
  at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles (System.String directory, System.String expression, System.IO.EnumerationOptions options) [0x00014] in <c4bddbfe864a4b8191bb818d6b204e9d>:0
  at System.IO.Directory.InternalEnumeratePaths (System.String path, System.String searchPattern, System.IO.SearchTarget searchTarget, System.IO.EnumerationOptions options) [0x0003c] in <c4bddbfe864a4b8191bb818d6b204e9d>:0
  at System.IO.Directory.EnumerateFiles (System.String path, System.String searchPattern, System.IO.EnumerationOptions enumerationOptions) [0x00000] in <c4bddbfe864a4b8191bb818d6b204e9d>:0
  at System.IO.Directory.EnumerateFiles (System.String path, System.String searchPattern) [0x00007] in <c4bddbfe864a4b8191bb818d6b204e9d>:0
  at OmniSharp.Services.AssemblyLoader.LoadAllFrom (System.String folderPath) [0x00015] in <af73e6dd2119447d987570341b94877c>:0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/iron-e/Programming/Issues/Omnisharp/Debugger'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/iron-e/Programming/Issues/Omnisharp/Debugger/Test.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/iron-e/Programming/Issues/Omnisharp/Debugger/Test/Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/iron-e/Programming/Issues/Omnisharp/Debugger'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/iron-e/Programming/Issues/Omnisharp/Debugger/Test/Test.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/iron-e/Programming/Issues/Omnisharp/Debugger' on host 3450.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/iron-e/Programming/Issues/Omnisharp/Debugger/Test/Test.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/iron-e/Programming/Issues/Omnisharp/Debugger/Test/Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
[info]: OmniSharp.MSBuild.ProjectManager
[info]: OmniSharp.MSBuild.ProjectManager
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Test
[info]: OmniSharp.MSBuild.ProjectManager
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 3.
</code>
</details>

### C# log ###

There is nothing in the log.

## Environment information ##

**VSCode version**: 1.44.2
**C# Extension**: 1.21.18

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.4.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.103
 Commit:    6f74c4a1dd

Runtime Environment:
 OS Name:     arch
 OS Version:
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.103/

Host (useful for support):
  Version: 3.1.3
  Commit:  ed88943d24

.NET Core SDKs installed:
  3.1.103 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|csharp|ms-dotnettools|1.21.18|
|csharp-to-plantuml|pierre3|1.2.1|
|dart-code|Dart-Code|3.10.1|
|debug|webfreak|0.24.0|
|EditorConfig|EditorConfig|0.14.5|
|flutter|Dart-Code|3.10.1|
|json|ZainChen|1.0.4|
|material-icon-theme|PKief|4.1.0|
|plantuml|jebbs|2.13.8|
|prettier-vscode|esbenp|4.5.0|
|quicktype|quicktype|12.0.46|
|roslynator|josefpihrt-vscode|2.9.0|
|spacemacs|cometeer|1.1.1|
|tabnine-vscode|TabNine|2.8.2|
|viml|dunstontc|0.1.7|
|vscode-neovim|asvetliakov|0.0.50|
|vscodeintellicode|VisualStudioExptTeam|1.2.6|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by gregg-miskelly** [comment]
Can you grab a debugger log? Since you are on arch, I am going to guess that this is a problem with native dependencies, so I would probably suggest the [full method](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging#full-method).

**Comment by Iron-E** [comment]
Sure thing! Here's the log:

<details><summary>Log</summary>

```log
Waiting for communication on port 4711...
>> accepted connection from client
-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Code - OSS","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true},"type":"request","seq":1}
<- (R) {"seq":0,"type":"response","request_seq":1,"success":true,"command":"initialize","message":"","body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":false,"supportsConditionalBreakpoints":true,"supportsHitConditionalBreakpoints":true,"supportsEvaluateForHovers":true,"exceptionBreakpointFilters":[{"filter":"all","label":"All Exceptions","default":false},{"filter":"user-unhandled","label":"User-Unhandled Exceptions","default":true}],"supportsSetVariable":true,"supportsGotoTargetsRequest":true,"supportsModulesRequest":true,"additionalModuleColumns":[],"supportedChecksumAlgorithms":["MD5","SHA1","SHA256"],"supportsExceptionOptions":true,"supportsValueFormattingOptions":true,"supportsExceptionInfoRequest":true,"supportTerminateDebuggee":true,"supportsSetExpression":true,"supportsReadMemoryRequest":true,"supportsExceptionConditions":true,"supportsLoadSymbolsRequest":true,"supportsModuleSymbolSearchLog":true,"supportsDebuggerProperties":true,"supportsSetSymbolOptions":true}}
-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Code - OSS","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true},"type":"request","seq":1}
-> (C) {"command":"launch","arguments":{"debugServer":4711,"name":".NET Core Launch (console)","type":"coreclr","request":"launch","preLaunchTask":"build","program":"/home/adamz/Programming/ACTIVE/Clue/Sleuth/bin/Debug/netcoreapp3.1/Sleuth.dll","args":[],"cwd":"/home/adamz/Programming/ACTIVE/Clue/Sleuth","console":"internalConsole","stopAtEntry":false,"internalConsoleOptions":"openOnSessionStart","__sessionId":"253515dd-0a52-4b78-bcdb-e8e4b4e27f12"},"type":"request","seq":2}
<- (E) {"seq":3,"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n"}}
<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"launch"}
<- (E) {"seq":5,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/CommandFailed","data":{"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr","VS.Diagnostics.Debugger.vsdbg.ErrorCode":-1989017584,"VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"arch","VS.Diagnostics.Debugger.vsdbg.Command":"handshake","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Linux","VS.Diagnostics.Debugger.vsdbg.Version":"16.6.20415.1 commit:0184bb70e1ed40656c0dfa53125805036207007b"}}}
<- (R) {"seq":6,"type":"response","request_seq":1,"success":false,"command":"handshake","message":"Error processing 'handshake' request. Unknown Error: 0x89720010"}
-> (C) {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":3}
<- (E) {"seq":7,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/DebugCompleted","data":{"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr","VS.Diagnostics.Debugger.vsdbg.DebugCompleted.BreakCounter":0,"VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"arch","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Linux","VS.Diagnostics.Debugger.vsdbg.Version":"16.6.20415.1 commit:0184bb70e1ed40656c0dfa53125805036207007b"}}}
<- (R) {"seq":8,"type":"response","request_seq":3,"success":true,"command":"disconnect"}
>> client connection closed
```

</details>

**Comment by Iron-E** [comment]
Sure thing! Here's the log:

<details><summary>Log</summary>

```log
Waiting for communication on port 4711...
>> accepted connection from client
-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Code - OSS","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true},"type":"request","seq":1}
<- (R) {"seq":0,"type":"response","request_seq":1,"success":true,"command":"initialize","message":"","body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":false,"supportsConditionalBreakpoints":true,"supportsHitConditionalBreakpoints":true,"supportsEvaluateForHovers":true,"exceptionBreakpointFilters":[{"filter":"all","label":"All Exceptions","default":false},{"filter":"user-unhandled","label":"User-Unhandled Exceptions","default":true}],"supportsSetVariable":true,"supportsGotoTargetsRequest":true,"supportsModulesRequest":true,"additionalModuleColumns":[],"supportedChecksumAlgorithms":["MD5","SHA1","SHA256"],"supportsExceptionOptions":true,"supportsValueFormattingOptions":true,"supportsExceptionInfoRequest":true,"supportTerminateDebuggee":true,"supportsSetExpression":true,"supportsReadMemoryRequest":true,"supportsExceptionConditions":true,"supportsLoadSymbolsRequest":true,"supportsModuleSymbolSearchLog":true,"supportsDebuggerProperties":true,"supportsSetSymbolOptions":true}}
-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Code - OSS","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true},"type":"request","seq":1}
-> (C) {"command":"launch","arguments":{"debugServer":4711,"name":".NET Core Launch (console)","type":"coreclr","request":"launch","preLaunchTask":"build","program":"/home/iron-e/Programming/Issues/Omnisharp/Debugger/bin/Debug/netcoreapp3.1/Debugger.dll","args":[],"cwd":"/home/iron-e/Programming/Issues/Omnisharp/Debugger","console":"internalConsole","stopAtEntry":false,"internalConsoleOptions":"openOnSessionStart","__sessionId":"253515dd-0a52-4b78-bcdb-e8e4b4e27f12"},"type":"request","seq":2}
<- (E) {"seq":3,"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n"}}
<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"launch"}
<- (E) {"seq":5,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/CommandFailed","data":{"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr","VS.Diagnostics.Debugger.vsdbg.ErrorCode":-1989017584,"VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"arch","VS.Diagnostics.Debugger.vsdbg.Command":"handshake","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Linux","VS.Diagnostics.Debugger.vsdbg.Version":"16.6.20415.1 commit:0184bb70e1ed40656c0dfa53125805036207007b"}}}
<- (R) {"seq":6,"type":"response","request_seq":1,"success":false,"command":"handshake","message":"Error processing 'handshake' request. Unknown Error: 0x89720010"}
-> (C) {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":3}
<- (E) {"seq":7,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/DebugCompleted","data":{"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr","VS.Diagnostics.Debugger.vsdbg.DebugCompleted.BreakCounter":0,"VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"arch","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Linux","VS.Diagnostics.Debugger.vsdbg.Version":"16.6.20415.1 commit:0184bb70e1ed40656c0dfa53125805036207007b"}}}
<- (R) {"seq":8,"type":"response","request_seq":3,"success":true,"command":"disconnect"}
>> client connection closed
```

</details>

**Comment by gregg-miskelly** [comment]
The problem is that you are using the OSS version of Visual Studio Code. But the debugger is only licensed to be used with the official Microsoft version. I am not sure if the official Microsoft version is available for Arch. But you would need to use it is order to use the Microsoft debugger.

There is also another problem that your version VS Code isn't showing the failure message that is being returned there. VS Code has broken error reporting before, so I am not sure if they just broke it again, or if you just have one of the older versions where this is broken.

**Comment by Iron-E** [comment]
Ah— the open source build of VSCode is what ships in the Arch repos. To get the official version, you must get it from the AUR. I'll grab that version and report back.

About the failure message: I'm using a version shipped by Arch from a week ago (`1.44.2-1`) so it's possible that build had broken reporting, or the OSS build might have issues detecting this problem altogether (I wouldn't know enough about VSCode to tell).

**Comment by gregg-miskelly** [comment]
Thanks. 1.44.2 is the latest release, so that sounds good. I will try to dig in what is going wrong there.

**Comment by Iron-E** [comment]
The official version from Microsoft, (`visual-studio-code-bin` on the AUR) works as expected. Thanks for helping me track this down! 

I'm not sure if I should close this, seeing as the error messages issue is still up in the air

**Comment by gregg-miskelly** [comment]
I opened VS Code issue 97110 for the error reporting problem. There however, is also an issue with the way vsdbg is generating this error. I will leave this bug open to track that.

**Comment by jansse78** [comment]
> 
> 
> Ah— the open source build of VSCode is what ships in the Arch repos. To get the official version, you must get it from the AUR. I'll grab that version and report back.
> 
> About the failure message: I'm using a version shipped by Arch from a week ago (`1.44.2-1`) so it's possible that build had broken reporting, or the OSS build might have issues detecting this problem altogether (I wouldn't know enough about VSCode to tell).

As I am new to vsCode and studying C# and feeling that I could also have this same issue?

Question: As I am new to this, what does arch-pero and AUR mean? Could my problem be soved with this?

pasted a question on my problem to stackOverflow: https://stackoverflow.com/questions/61709211/visual-studio-code-doesnt-stop-at-breakpoints-on-debugging

**Comment by gregg-miskelly** [comment]
@jansse78 You are on Windows 10, so this issue probably doesn't apply to you. Please open a new issue. In your new issue, please include a debugger log ([instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging).

**Comment by jansse78** [comment]
Embarassed I have to admit that I just noticed that in the old laptop had 32bit SDK and this new one needed apparently 64bit. When installed 64bit it works. Sorry for confusing with this kind of basic stuff... :(

**Comment by gregg-miskelly** [comment]
https://github.com/OmniSharp/omnisharp-vscode/pull/4091 resolves the issue with error reporting in vsdbg.
