### ISSUE TITLE
Extension tries to modify extension directory

### ISSUE THREAD

**Issue by poscat0x04** [OmniSharp/omnisharp-vscode#3761]
This extension tries to modify the extension directory upon starting. But the directory is read-only on NixOS so it fails:
```
Installing C# dependencies...
Platform: linux, x86_64, name=nixos, version=20.03beta1155.29eddfc36d7

Failed at stage: touchBeginFile
Error: EROFS: read-only file system, mkdir '/nix/store/bxxrl6hrh3zqixrsijpyaz8c20p3ka0k-vscode-extensions/ms-dotnettools.csharp/.omnisharp'
```
I think the extension should be able to use existing omnisharp-roslyn installed on the system instead of trying to download it's own.

## Steps to reproduce
1. install this extension using nix
2. open any solution

**Comment by filipw** [comment]
This is as expected, the extension bundles it's own OmniSharp. OmniSharp has currently no concept of "being installed on the system"

**Comment by poscat0x04** [comment]
I don't think I understand what you mean. omnisharp-roslyn can be compiled into an executable and there's a config option (`omnisharp.path`) for configuring the path to that executable

**Comment by filipw** [comment]
yes but that config option is not *really supported*. it exists only so that different OmniSharp builds could be *tested* against certain OmniSharp builds containing bug fixes or changes, not really as recommended way of running the extension with OmniSharp.
The main reason is that more often than not, there is a tight coupling between the OmniSharp and the extension in terms of payload structure, available endpoints, changes made, configuration option handling and so on.

**Comment by poscat0x04** [comment]
I see, the CodeLLDB extension is facing a similar situation but they provided a version of vsix package that doesn't require anything to be downloaded into the extension directory upon installing.
Would it be possible to release a vsix package with omnisharp bundled in somewhere?

**Comment by JoeRobich** [comment]
@poscat0x04 You can [build an offline installer](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-the-C%23-extension-to-a-computer-without-internet-connectivity) that will have all the dependencies packaged together for your platform.

**Comment by poscat0x04** [comment]
That worked! Thanks.

**Comment by dustinlacewell** [comment]
@poscat0x04 If you remember, can you provide some information on how you got this working on NixOS? Did you get the Razor Language Server working too?
