### ISSUE TITLE
How it work for linux user ?

### ISSUE THREAD

**Issue by PrakTech** [OmniSharp/omnisharp-vscode#3763]
Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

This is the error i face in Vs code  in Ubuntu. I could not download .NETFramework v4.7.1 . only avaialble for window.

**Comment by PrakTech** [comment]
Full detail : 
Starting OmniSharp server at 5/7/2020, 7:12:33 PM
    Target: /home/prakash/Documents/Unity_Projects/test18422/test18422.sln

OmniSharp server started.
    Path: /home/prakash/.vscode/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/run
    PID: 29575

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 19.10 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.4 - "/home/prakash/.vscode/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/prakash/.vscode/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "/home/prakash/.vscode/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/prakash/.vscode/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/prakash/.vscode/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/prakash/.vscode/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/prakash/Documents/Unity_Projects/test18422'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/prakash/Documents/Unity_Projects/test18422/test18422.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/prakash/Documents/Unity_Projects/test18422/Assembly-CSharp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/prakash/Documents/Unity_Projects/test18422'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/prakash/Documents/Unity_Projects/test18422/Assembly-CSharp.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/prakash/Documents/Unity_Projects/test18422' on host 29421.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/home/prakash/Documents/Unity_Projects/test18422/Assembly-CSharp.csproj'.
/home/prakash/Documents/Unity_Projects/test18422/Assembly-CSharp.csproj
/home/prakash/.vscode/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1193,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /home/prakash/Documents/Unity_Projects/test18422/Assembly-CSharp.csproj

**Comment by JoeRobich** [comment]
@PrakTech You make a good point. This isn't a helpful error message when on MacOS or Linux. For these platforms you can install the stable release of Mono (6.8.0 from https://www.mono-project.com/download/stable/#download-lin) to install the .NET 4.7.1 reference assemblies that Unity projects require.

@cartermp Can we update this error or the linked website to include instructions for non-Windows platforms?

**Comment by PrakTech** [comment]
@JoeRobich  you are right . Linux needs mono install along with dotnet core sdk to work out . Thanks for solution.

**Comment by RussiSunni** [comment]
@JoeRobich Thanks!

**Comment by v6ak** [comment]
This issue is not yet fixed – the message on Linux is still unhelpful.


My VS Code version:
```
% snap list code
Name  Version   Rev  Tracking       Publisher  Notes
code  ea3859d4  52   latest/stable  vscode✓    classic
```

**Comment by AlexFolland** [comment]
Installing mono 6.12.0.107-1 on Manjaro did not fix my issue, so I really don't know what to do.

**Comment by Morganb816** [comment]
Think i found a solution,

1. Install latest stable mono from above.
2. In the bottom right of VS Code you should see a little c# symbol (The language setting VS Code detects for your project). Click that and open the "Configure C# Language based settings".
3. Add the following line to your settings `"omnisharp.useGlobalMono": "always"`. 
4: restart your omni server. (There should be a little pop up in bottom right with a button that says restart omni server)

This caused the error to go away and for intellisense to kick in.
Hope it helps

**Comment by metou3** [comment]
> Think i found a solution,
> 
>     1. Install latest stable mono from above.
> 
>     2. In the bottom right of VS Code you should see a little c# symbol (The language setting VS Code detects for your project). Click that and open the "Configure C# Language based settings".
> 
>     3. Add the following line to your settings `"omnisharp.useGlobalMono": "always"`.
>        4: restart your omni server. (There should be a little pop up in bottom right with a button that says restart omni server)
> 
> 
> This caused the error to go away and for intellisense to kick in.
> Hope it helps

Thanks a lot, I search all over the internet and found only your solution working.

**Comment by mrmcdobrotny** [comment]
wow! Thank you very much, @Morganb816! I was trying to find the solution for days!  this is definitely the only thing that worked

**Comment by AlexFolland** [comment]
This solution seems so janky because literally every C# dev in Linux will encounter this.  Can `omnisharp.useGlobalMono` be set to `always` by default on Linux oslt?

**Comment by PPLong222** [comment]
> Think i found a solution,
> 
> 1. Install latest stable mono from above.
> 2. In the bottom right of VS Code you should see a little c# symbol (The language setting VS Code detects for your project). Click that and open the "Configure C# Language based settings".
> 3. Add the following line to your settings `"omnisharp.useGlobalMono": "always"`.
>    4: restart your omni server. (There should be a little pop up in bottom right with a button that says restart omni server)
> 
> This caused the error to go away and for intellisense to kick in. Hope it helps

Wow! That just perfectly solved my problem! Thanks.
