### ISSUE TITLE
Inconsistent Coloring

### ISSUE THREAD

**Issue by Banyc** [OmniSharp/omnisharp-vscode#3767]
## Environment data
`dotnet --info` output: sdk 3.1.201
VS Code version: 1.44.2
C# Extension version: 1.21.18

## Steps to reproduce

Paste the code below to vscode:

```csharp
public override object VisitDropStatement()
{
    DropStatement ret;
    if (context.dropIndex() != null)
        ret = (DropStatement)Visit(context.dropIndex());
    else
        ret = (DropStatement)Visit(context.dropTable());
    return ret;
}
```

## Expected  behavior

Same Coloring on `(DropStatement)`

## Actual behavior

Different Coloring on `(DropStatement)`

**Comment by cartermp** [comment]
@Banyc This should be resolved with the latest re-release of the extension, which adds proper semantic highlighting. You can try it out here, or wait until it is fully released: https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.19-beta1

https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases
