### ISSUE TITLE
Parameter Hints Not Rendering Properly

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#377]
_From @robbpriestley on May 25, 2016 21:49_

- VSCode Version: 1.1.1
- OS Version: OSX El Capitan 10.11.4

Steps to Reproduce:

1. Write the code to create a new object

Expected: Intellisense parameter hints show different signatures with available parameter names.

Actual: blank area shows (see screenshot)

![image](https://cloud.githubusercontent.com/assets/16694050/15557436/d408c008-2287-11e6-8756-100f6061a67d.png)

_Copied from original issue: Microsoft/vscode#6895_

**Comment by robbpriestley** [comment]
Further observation seems to confirm that this is an issue with constructors, i.e. the method call after a `new` operator.

**Comment by DustinCampbell** [comment]
Hi, thanks for reporting the problem! We're tracking this issue with https://github.com/OmniSharp/omnisharp-vscode/issues/36.
