### ISSUE TITLE
Debugging of .NET 5 apps doesn't work 

### ISSUE THREAD

**Issue by nZeus** [OmniSharp/omnisharp-vscode#3773]
## Issue Description ##
I have.net 5 (5.0.100-preview.3.20216.6) installed.
When I try to debug the .net console app, breakpoints work, but cannot watch any variables. 

## Steps to Reproduce ##
dotnet new console
code .
...set a breakpoint
F5

## Expected Behavior ##
Variables panel should show variables 

## Actual Behavior ##
`Error processing 'variables' request. Unknown Error: 0x8000211d`

### OmniSharp log ###
<details>Starting OmniSharp server at 5/10/2020, 6:48:34 PM
    Target: /media/ilia/Shared/Projects/Test

OmniSharp server started.
    Path: /home/ilia/.vscode/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/run
    PID: 10340

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 20.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.4 - "/home/ilia/.vscode/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/ilia/.vscode/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "/home/ilia/.vscode/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/ilia/.vscode/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/ilia/.vscode/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/ilia/.vscode/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.1/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/media/ilia/Shared/Projects/Test'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/media/ilia/Shared/Projects/Test'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/media/ilia/Shared/Projects/Test/Test.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/media/ilia/Shared/Projects/Test'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /media/ilia/Shared/Projects/Test/Test.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/media/ilia/Shared/Projects/Test' on host 10069.
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/media/ilia/Shared/Projects/Test/Test.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/media/ilia/Shared/Projects/Test/Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Test
</details>

### C# log ###
<details>Failed to spawn 'dotnet --info'
</details>

## Environment information ##

**VSCode version**: 1.45.0
**C# Extension**: 1.21.18

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
A valid dotnet installation could not be found.</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|11.2.0|
|code-settings-sync|Shan|3.4.3|
|contextualduplicate|lafe|0.2.0|
|csharp|ms-dotnettools|1.21.18|
|debugger-for-chrome|msjsdiag|4.12.6|
|dotnet-test-explorer|formulahendry|0.7.1|
|EditorConfig|EditorConfig|0.14.5|
|elm|sbrink|0.26.0|
|firebase-explorer|jsayol|0.3.3|
|git-graph|mhutchie|1.22.0|
|githistory|donjayamanne|0.6.5|
|gitlens|eamodio|10.2.1|
|graphql-for-vscode|kumar-harsh|1.15.3|
|macros|geddski|1.2.1|
|markdown-shortcuts|mdickin|0.12.0|
|mssql|ms-mssql|1.9.0|
|npm-dependency-links|herrmannplatz|1.1.0|
|pdf|tomoki1207|0.6.0|
|powershell|ms-vscode|2020.4.0|
|prettify-json|mohsen1|0.0.3|
|rainbow-csv|mechatroner|1.7.0|
|remote-wsl|ms-vscode-remote|0.44.2|
|terraform|mauve|1.4.0|
|tgit-cmds|mbinic|1.3.0|
|toggle-excluded-files|eamodio|1.7.0|
|vetur|octref|0.24.0|
|vscode-eslint|dbaeumer|2.1.5|
|vscode-icons|vscode-icons-team|10.1.1|
|vscode-markdownlint|DavidAnson|0.35.1|
|vscode-pull-request-github|GitHub|0.16.0|
|vscode-taskexplorer|spmeesseman|1.26.3|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|
|vscode-versionlens|pflannery|0.27.0|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by gregg-miskelly** [comment]
What OS are you on?

**Comment by xtqqczze** [comment]
@nZeus What is the output of `dotnet --info`?

**Comment by gregg-miskelly** [comment]
Also, please include a [debugger log](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging).

**Comment by gregg-miskelly** [comment]
@nZeus I am resolving the issue for now as we haven't been able to reproduce your issue on our machines, and we need more information to investigate. If you have time to tell us more, I would be very happy to help investigate further.
