### ISSUE TITLE
 OmniSharp does not discover *.cs files in obj\ folder at startup time

### ISSUE THREAD

**Issue by iSazonov** [OmniSharp/omnisharp-vscode#3781]
## Issue Description ##

The issue comes from https://github.com/PowerShell/PowerShell/pull/12355#discussion_r424875759 (You can see screenshots there)

MSBuild allows to create strong typed resources. By default it generates the new *.cs files in obj\ folder where *.resource files is placed.

Issue is that OmniSharp does not discover *.cs files in obj\ folder at startup time. As result we see reds in VS Code editor window. But if then we do `dotnet build` OmniSharp finds the files and all works well in VS Code editor.

## Steps to Reproduce ##
- Create a project with strong typed resources (or maybe simply put a cs file in obj\ folder)
- Build the project with `dotnet build`
- now *.cs are in obj\ folder
- Run VS Code 

## Expected Behavior ##

OmniSharp finds *.cs files in obj\ folder at startup time, all intellisense functionality works well.

## Actual Behavior ##

VS Code shows reds for references to files in obj\ folder.
OmniSharp finds *.cs files in obj\ folder only after executing `dotnet build`

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.45.0
**C# Extension**: 1.21.18

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.4.20258.7
 Commit:    65f0fc2cad

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\1\AppData\Local\Microsoft\dotnet\sdk\5.0.100-preview.4.20258.7\

Host (useful for support):
  Version: 5.0.0-preview.4.20251.6
  Commit:  47ec733ba7

.NET SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015135 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.3.20216.6 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.4.20229.10 [C:\Users\1\AppData\Local\Microsoft\dotnet\sdk]
  5.0.100-preview.4.20258.7 [C:\Users\1\AppData\Local\Microsoft\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.3.20215.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.4.20257.10 [C:\Users\1\AppData\Local\Microsoft\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.3.20214.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.4.20251.6 [C:\Users\1\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.3.20214.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.4.20251.1 [C:\Users\1\AppData\Local\Microsoft\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.21.18|
|gitlens|eamodio|10.2.1|
|powershell|ms-vscode|2020.4.0|
|vscode-markdownlint|DavidAnson|0.35.1|;

</details>

**Comment by JoeRobich** [comment]
@iSazonov Sorry you are running into issues. In most cases Omnisharp shouldn't be pulling files in from the obj/ folder. Omnisharp performs a "design-time" build when the projects are loaded. Files generated at during compilation are then added to the workspace (This is what happens with .resx files which generate Resource classes) . If you are seeing build errors, then we would need the Omnisharp Log from the Output pane to investigate issues loading the project or performing the build.

**Comment by iSazonov** [comment]
> In most cases Omnisharp shouldn't be pulling files in from the obj/ folder.

I think it is root cause of the issue.
.Net SDK target defines default search pattern as `<projectroot>\**\*.cs`. If OmniSharp follows csproj files it should discover cs-files in `obj` folder tree.

Notice, starting with .Net Core 3.1 ResGen was integrated in targets and now resource generation is not performed during design time but during build time.

**Comment by JoeRobich** [comment]
@iSazonov I would like to better understand what is happening during your design time builds.

If you could add an omnisharp.json to your user's home folder or workspace folder that contains the following:

```json
{
    "MSBuild": {
        "GenerateBinaryLogs": true
    }
}
```

This should generate a binary log next to your .csproj file which will give us additional insights into what is happening with you resource file.

If you could generate a .binlog for the project containing the resource file and share it with us, we could investigate further.

**Comment by iSazonov** [comment]
I build PowerShell and then start VS Code in the root folder. `powershell-win-core` is a root project.
[src.zip](https://github.com/OmniSharp/omnisharp-vscode/files/4638817/src.zip)

**Comment by JoeRobich** [comment]
@iSazonov I believe the root cause of your issue is with the target you are adding. See [my comment on your PowerShell PR](https://github.com/PowerShell/PowerShell/pull/12355#discussion_r425988857).

**Comment by iSazonov** [comment]
@JoeRobich I excluded the project with the target from build process but OmniSharp behavior did not change. So I think the target is not a root case of the issue.

**Comment by JoeRobich** [comment]
@iSazonov Our project system uses MSBuild to process the project file, run a build, and inform us of which source files are used in the compilation. 

I pulled your branch and got this warning:
```
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Volumes/Data/Source/PowerShell/src/Microsoft.Management.UI.Internal/Microsoft.PowerShell.GraphicalHost.csproj'.
/Volumes/Data/Source/PowerShell/src/Microsoft.Management.UI.Internal/Microsoft.PowerShell.GraphicalHost.csproj
/usr/local/share/dotnet/sdk/5.0.100-preview.4.20258.7/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(59,5): Error: Windows is required to build Windows desktop applications.
```

**Comment by iSazonov** [comment]
@JoeRobich To build PowerShell you should import module Build.psm1 in PowerShell and run Start-PSBuild.

Now after I explicitly added `<Compile Update="**\*.cs" />` in one project OmniSharp discover generated files for the project.
I found that `DefaultItemExcludes` value in `Microsoft.NET.Sdk.DefaultItems.targets` is `";bin\Debug\/**;obj\Debug\/**;bin\/**;obj\/**"` - it seems all files in `obj\` folder are excluded.

**Comment by JoeRobich** [comment]
@iSazonov I followed the build steps to build it from the commandline, but that does not resolve the issue that the project which contains the resources does not build on non-windows platforms. If you are expecting completion and intellisense for those resource classes on MacOS or Linux the SDK error will have to be worked around.

I did pull everything down on my Windows box and it works fine, I get completion and intellisense for the Resource classes in that project.

**Comment by iSazonov** [comment]
> that does not resolve the issue that the project which contains the resources does not build on non-windows platforms.

If you say about Microsoft.PowerShell.GraphicalHost.csproj it is Windows only project (WinForm/WPF) and it is skipped on Unix.

> I did pull everything down on my Windows box and it works fine, I get completion and intellisense for the Resource classes in that project.

Do you say that after VS Code starting it discover cs files in `obj\` folder?

**Comment by JoeRobich** [comment]
> Do you say that after VS Code starting it discover cs files in obj\ folder?

@iSazonov Because the project builds on windows it is part of the compilation and is added to the workspace. On non-windows platforms this project is skipped and isn't considered part of the compilation or workspace. This is the root of the problem.

**Comment by iSazonov** [comment]
I removed `Microsoft.PowerShell.GraphicalHost.csproj` from disk and VS Code behavior is not changed.

Also I created simple application used strongly typed resources and I see the same issue.

**Comment by JoeRobich** [comment]
@iSazonov  Just so I am certain, the problem you are seeing if that the resource classes that are generated at build time are not being included in your completion/intellisense?

Can you share your simple application source? We can start troubleshooting from there.

**Comment by iSazonov** [comment]
> Just so I am certain, the problem you are seeing if that the resource classes that are generated at build time are not being included in your completion/intellisense?

Yes.

Test application https://github.com/iSazonov/OmniSharpTest

**Comment by JoeRobich** [comment]
@iSazonov The issue is that resources were being generated as part of the Build and not as part of the Compile. I added the following target to the .props file and it resolved the issue for me.

```xml
  <!--
    Note: Targets that generate Compile items are expected to run before BeforeCompile targets (common targets convention).
  -->
  <Target Name="_GenerateResxSource"
          BeforeTargets="BeforeCompile;CoreCompile"
          DependsOnTargets="PrepareResources">
  </Target>
```

**Comment by cartermp** [comment]
This is more of an issue with the .NET SDK for resource files. We don't want to really be in the business of looking for source files in the obj directory.
