### ISSUE TITLE
justMyCode:false in launch.json still fails to allow debugging 3rd-party code.

### ISSUE THREAD

**Issue by LBensman** [OmniSharp/omnisharp-vscode#3784]
## Issue Description ##
Per https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#just-my-code, `"justMyCode":false` should allow debugging into 3rd-party libraries.  I configured as such on my project, and attempted to step-into .NET Core's `System.IO.Stream.WriteAsync()`, but debugger simply stepped over it.  Seems like the feature to disable just my code is not actually working?

## Steps to Reproduce ##
Create a small program that simply calls into some .NET Core's function, like the one mentioned above.

## Expected Behavior ##
Debugger steps-in to 3rd-party function, and at least shows control flow (if optimizations prevent variable inspection), or if available, variable values as well.

## Actual Behavior ##
Step-into simply results in step-over.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.45.1
**C# Extension**: 1.21.18

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.1.607
 Commit:    cad4fbe2d5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.607/

Host (useful for support):
  Version: 2.1.14
  Commit:  57273284ef

.NET Core SDKs installed:
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.300 [/usr/local/share/dotnet/sdk]
  2.1.607 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|atlascode|atlassian|2.6.0|
|c-cpp-flylint|jbenden|1.4.4|
|cmake|twxs|0.0.17|
|cmake-clangd-helper|Harikrishnan|0.4.0|
|cmake-tools|ms-vscode|1.3.1|
|cmake-tools-helper|maddouri|0.2.1|
|code-gnu-global|austin|0.2.2|
|code-spell-checker|streetsidesoftware|1.8.0|
|cpptools|ms-vscode|0.28.0|
|csharp|ms-dotnettools|1.21.18|
|debug|webfreak|0.24.0|
|gc-excelviewer|GrapeCity|2.1.34|
|meson|asabil|1.2.0|
|ninja|surajbarkale|0.0.1|
|Nix|bbenoist|1.0.1|
|puppet-vscode|puppet|0.26.1|
|python|ms-python|2020.5.78807|
|restore-editors|eamodio|0.2.1|
|svgeditor|henoc|2.9.0|
|trailing-spaces|shardulm94|0.3.1|
|vs-keybindings|ms-vscode|0.2.0|
|vscode-clang|mitaki28|0.2.3|
|vscode-database|bajdzis|2.2.0|
|vscode-docker|ms-azuretools|1.2.0|
|vscode-hexdump|slevesque|1.7.2|
|vscode-icons|vscode-icons-team|10.1.1|
|vscode-markdownlint|DavidAnson|0.35.1|
|vscode-yaml|redhat|0.8.0|;

</details>

**Comment by gregg-miskelly** [comment]
Hi @LBensman, see https://github.com/OmniSharp/omnisharp-vscode/wiki/Debugging-into-the-.NET-Framework-itself for instructions on debugging into the Framework.

**Comment by LBensman** [comment]
Thank you for the link.  It didn't come up in my google searches.  I'm past my current need to debug into .NET Core code, but I've noted it for future reference and will try next time I need it.
