### ISSUE TITLE
'AssemblyName.Exe' modification date after compile with computer date changed.

### ISSUE THREAD

**Issue by fischer-ti** [OmniSharp/omnisharp-vscode#3786]
## Issue Description ##
If you change your computer date forward (let's say 1 day), than compile your c# worker/aspnet  program, when you get your date back to the current date the next time you compile some code the output exe file will get the last "most forward" date.
My personal sample, now is 2020-05-15 at 13:48.
Compile exe file get modification date: 2020-05-16 00:25
Why I did that?
Answer: Just for fun! =D
And because I needed to see if my software behaves as expected when the computer current date changes.
## Steps to Reproduce ##
1. Change computer date forward.
2. Compile your software.
3. Change computer date back to current date.
4. Compile your software.
## Expected Behavior ##
Compiler should get that the date changed and the output exe should be the most recent one, even that the date is backwards.
## Actual Behavior ##
Exe is coming with the last most forward date, even with current date set ok.
5. Can't get some modifications at output, such as ICO changing.
## Logs ##
Compilation log:
Microsoft(R) Build Engine versão 16.5.0+d4cbfca49 para .NET Core
Copyright (C) Microsoft Corporation. Todos os direitos reservados.
...restores...references...
Compilação com êxito.
    0 Aviso(s)
    0 Erro(s)
### OmniSharp log ###
<details>Post the output from Output--></details>

## Environment information ##

**VSCode version**: 1.45.1
**C# Extension**: 1.21.18

<details><summary>Dotnet Information</summary>
SDK do .NET Core (refletindo qualquer global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Ambiente de runtime:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.21.18|
|docomment|k--kato|0.1.9|
|material-icon-theme|PKief|4.1.0|
|mssql|ms-mssql|1.9.0|
|rocketseatreactjs|rocketseat|3.0.2|
|rocketseatreactnative|rocketseat|3.0.1|
|theme-dracula|dracula-theme|2.22.0|
|todo-tree|Gruntfuggly|0.0.175|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-proto3|zxh404|0.4.2|;

</details>

**Comment by cartermp** [comment]
By default, builds in .NET Core use determinism, so this is what you're running up against. If you disable that, then this should work.
