### ISSUE TITLE
vsdbg-ui fails to start with status code 0xC0000022

### ISSUE THREAD

**Issue by johnfoll** [OmniSharp/omnisharp-vscode#3791]
I eventually found this error in Log(Window):
[renderer1] [error] Problem invoking 'GetCodeActions' on OmniSharp server: Error: Pending request cancelled: /v2/getcodeactions
and:
[renderer1] [error] timeout after 1000 ms: Error: timeout after 1000 ms
t t.RawDebugSession.handleErrorResponse (file:///C:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3061:355)
    at file:///C:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3060:679
    at async t.RawDebugSession.shutdown (file:///C:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3058:772)

This is an utterly simple "Hello World" example that it fails in, in addition to my actual source code and a simpler program that is even simpler than "Hello World".

Could this be a permissions problem? I am running in a special environment. Maybe something is not allowed? I do not have administrator rites on this computer currently. But previously I think I had administrator rights. I don't think I ever ran VSCode on this computer "with Administrator" either. I can't now.

I have created several C# test project, and doing "dotnet new console" etc. After building then going to start debug it looks like it is doing something - it builds, puts the breakpoint windows up, then stops - no apparent error visible. I dug and eventually saw the above error message.  I have tried uninstalling VSCode and C Sharpe (OminSharp) several times with the same results, yet on my home laptop VSCode works perfectly with C# programs and compiles and debugs them fine. I think I have tried several different versions of the OmniSharp C# plugin with it not working. I didn't check to see if it had the same exact error message with the older versions of it - because I hadn't seen the actual error message at the time.

VSCode 1.340 (user setup)
Date: 2020-05-07T16:18:48.860Z (week week ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

I also have .NET Core SDK 3.1.200 (x64) installed too. (Same version I think that works with VSCode # C# OmniSharp on my personal computer.

**Comment by gregg-miskelly** [comment]
Can you grab a [debugger log](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging)?

**Comment by johnfoll** [comment]
What do you need? Do you mean copying a log file?

 I included the two different errors I got previously. I just ran it again, and am now only getting the error in the Log (Window):
[2020-05-18 16:18:07.390] [renderer1] [error] timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///C:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3061:355)
    at file:///C:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3060:679
    at async t.RawDebugSession.shutdown (file:///C:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3058:772)

But there are no actual errors in the debugger window. I think the other error will come back too if I keep trying. It was showing up every time I ran it today, except just a bit ago when I tried it twice. The other times a week or several weeks ago when I tried it - I don't know that it reported, because I didn't find where the error message was being displayed until today. It is perplexing because it works on my personal computer but not my work computer.

**Comment by gregg-miskelly** [comment]
Those errors aren't related to debugging issues. Please read the wiki page that I linked.

**Comment by johnfoll** [comment]
Its the only error I could find so far. The debugger looks like it's going to do something - puts the watch window stuff up, after doing the build then just stops. Then I saw that error in the Log (Window) after that. Where is the wiki page? The wiki for this project is empty for me so far.

**Comment by gregg-miskelly** [comment]
I gave you the link in my first reply, but I will repeat it again here: https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging

**Comment by johnfoll** [comment]
OK, I enabled C$ debugger logging, and did rebuild, then started a new debug session. Where is the debugger log that you need? I didn't see anything different in the output window including for C#, OmniSharp or for Log (Window).

**Comment by gregg-miskelly** [comment]
If you used the "quick method" it will be dumped to the debug console.

**Comment by johnfoll** [comment]
The quick method didn't work, maybe because the debugger never ran? I tried the full method, but:

**Comment by gregg-miskelly** [comment]
I think you may have slightly miscopied that error code (missed a 0 -- should have been 0xC0000022). If so, that is `STATUS_ACCESS_DENIED`. 

I am not sure why VS Code doesn't output a message when creating a debug adapter fails, but this is the root of your problem - vsdbg-ui cannot start on your computer. 

As to why vsdbg-ui cannot start on your computer, assuming I guessed correctly what status code you are getting, I don't have any great answers. Some possible causes that occur to me:
1. You have some sort of security software on your computer that blocks programs. You could check your Windows Event Log. Also, If you have any third-party security software, you could check their log also.
2. You have some sort of hard drive corruption. You could try removing the C# extension and reinstalling to see if that fixes it. Make sure the `extensions\ms-dotnettools.csharp-1.21.18` directory gets deleted before you reinstall it.

**Comment by johnfoll** [comment]
OK, I will try to see if one of our SA knows if certain debuggers like vsdbg-ui.exe are blocked. I am able to run Visual Studio 2019 Enterprise on the same application, same folder and debug it correctly.

 

Thanks for your help.

**Comment by gregg-miskelly** [comment]
Cool. To be clear - vsdbg-ui is failing immediately on startup. So at that point it doesn't know anything about your project, and whatever is causing this failure wouldn't even know that vsdbg-ui is a debugger.

**Comment by johnfoll** [comment]
I uninstalled it, and the uninstall removed the folder it was installed in. Then reinstalled it. It still blows up the same way. It is not a corruption issue. Its not a folder permission issue if it runs under my logged in user account - which has full access to this folder and subfolders. C:\Users\FollJR\.vscode\extensions\ms-dotnettools.csharp-1.21.18.

It could be an anti-virus program running on this laptop.

**Comment by johnfoll** [comment]
It was McAfee that was blocking it. I got 'em to stop blocking it.

**Comment by gregg-miskelly** [comment]
Glad you got to the bottom of it!
