### ISSUE TITLE
Omnisharp stuck at "Starting..."

### ISSUE THREAD

**Issue by Sharpiro** [OmniSharp/omnisharp-vscode#380]
I'm following these steps to use a new c# app in VS Code.
1. install VS Code
2. ext install c#
3. mkdir dotnetnew
4. cd dotnetnew
5. dotnet new
6. dotnet restore
7. Open the project in VS Code

But at this point Omnisharp in the bottom right gets stuck on "Starting.." and never changes.  The only thing I see in the Omnisharp Log window is:
```
[INFO] Starting OmniSharp at 'c:\Users\...\dotnetnew'...
```
Notes
- This issue only occurs on my work machine; my personal machine works fine.
- I've tried reinstalling VS Code and omnisharp
- If I press ```F5``` the application begins to debug with no messages, and then just hangs as well.
- If i open a command prompt in my project.json root I can execute ```dotnet run``` and the application will run correctly.

**Comment by germansak** [comment]
The same is happening to me too. 
Strange is that it's working at home but not on my work machine.
Could it be a proxy issue? That's the only difference between work and home machines

**Comment by Sharpiro** [comment]
I too have vs code setup through a proxy at work.

**Comment by Platzer** [comment]
Same issue here with VS Code Insider and C# `v1.0.11`, i think issue #339 is not resolved yet?

**Comment by DustinCampbell** [comment]
Hi, could you try the latest extension on the marketplace (1.1.5)? This should work much better and that version should properly support proxies when downloading OmniSharp.

**Comment by Sharpiro** [comment]
This does look like it fixed my issue, thanks.

**Comment by DustinCampbell** [comment]
Awesome! Thanks for verifying!

**Comment by germansak** [comment]
Sorry for the delay! It's working for me too. Awesome!
Thanks!!
