### ISSUE TITLE
Add ability to Set Next Statement when debugging

### ISSUE THREAD

**Issue by loligans** [OmniSharp/omnisharp-vscode#3804]
The ability to modify the instruction pointer to a different location without running any code is an extremely useful debugging feature in C#. I'd like to request this feature be added into the toolset.

Visual Studio has an implementation of this, referred to as "Set Next Statement" in the UI. It is normally done by either dragging the yellow arrow indicating the currently executing line of code or by right clicking a line and choosing "Set Next Statement".

It appears the protocol for this is already implemented in VS Code.
**Issue**: https://github.com/microsoft/vscode-debugadapter-node/issues/28
**PR**: https://github.com/microsoft/vscode-debugadapter-node/pull/45

**Comment by gregg-miskelly** [comment]
This feature exists already.

**Comment by loligans** [comment]
Is it possible to drag the arrow or is that something the VSCode team would have to implement?

**Comment by gregg-miskelly** [comment]
The VS Code team would need to implement that.

**Comment by b-gonzalez** [comment]
> This feature exists already. Right click on the line you want to go to and invoke "Jump to Cursor".

Just to clarify, Jump to Cursor will only show as available if it's implemented in the debugger that you are using. e.g. Jump to Cursor is available when debugging python but not when debugging JavaScript with Node.
