### ISSUE TITLE
one time installer or every time?

### ISSUE THREAD

**Issue by maestrowilliam** [OmniSharp/omnisharp-vscode#3813]
This extension is installed only once or installed in every project I create?

**Comment by gregg-miskelly** [comment]
VS Code extensions are installed only once.

**Comment by JoeRobich** [comment]
@maestrowilliam In the unlikely case that you've configured the `omnisharp.path` settings to be `"latest"` then you will see frequent updates. Unless there is something compelling it is better to leave that settings defaulted.

**Comment by cartermp** [comment]
Closing as this question is answered.
