### ISSUE TITLE
Colons are not supported in files

### ISSUE THREAD

**Issue by nianwu** [OmniSharp/omnisharp-vscode#3814]
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.45.1
**C# Extension**: 1.21.18

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.8.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.202
 Commit:    6ea70c8dca

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.202/

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  2.2.207 [/usr/local/share/dotnet/sdk]
  3.0.101 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]
  3.1.200 [/usr/local/share/dotnet/sdk]
  3.1.202 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-using|Fudge|0.7.15|
|csharp|ms-dotnettools|1.21.18|
|csharpextensions|jchannon|1.3.1|
|docomment|k--kato|0.1.11|
|githistory|donjayamanne|0.6.5|
|github-plus-theme|thenikso|1.2.1|
|jinja|wholroyd|0.0.8|
|LiveServer|ritwickdey|5.6.1|
|markdown-all-in-one|yzhang|3.0.0|
|markdown-mermaid|bierner|1.5.1|
|prettier-vscode|esbenp|4.7.0|
|python|ms-python|2020.5.80290|
|remote-containers|ms-vscode-remote|0.117.1|
|remote-ssh|ms-vscode-remote|0.51.0|
|remote-ssh-edit|ms-vscode-remote|0.51.0|
|remote-wsl|ms-vscode-remote|0.44.2|
|svn-scm|johnstoncode|2.11.1|
|vetur|octref|0.24.0|
|vscode-docker|ms-azuretools|1.2.1|
|vscode-eslint|dbaeumer|2.1.5|
|vscode-language-pack-zh-hans|MS-CEINTL|1.45.1|
|vscode-markdown-table-sort|simonguo|1.0.4|
|vscode-nginx|william-voyek|0.7.2|
|vscode-remote-extensionpack|ms-vscode-remote|0.20.0|
|vscode-solution-explorer|fernandoescolar|0.3.10|
|vscode-sqlite|alexcvzz|0.8.2|
|vscode-terminal-themes|ctf0|0.1.0|
|vscode-test-explorer|hbenl|2.19.0|
|xml|DotJoshJohnson|2.5.0|;

</details>

Ignoring non-parseable lines in envFile .../.env: "DOTNET_CONNECTIONSTRINGS:REDIS=", "DOTNET_CONNECTIONSTRINGS:MONGO=...".

**Comment by cartermp** [comment]
@nianwu do you have a repro you could share? As it stands, there's nothing in this issue that is actionable.

**Comment by nianwu** [comment]
I want to write the connection string in the environment variable, but the variable name of envfile does not support colons. I can only write the environment variable launch.json Medium.

however launch.json Every time I regenerate, the environment variables I write are replaced

**Comment by nianwu** [comment]
Use double underscores instead of colons

https://docs.microsoft.com/zh-cn/aspnet/core/security/app-secrets?view=aspnetcore-3.1&tabs=windows#enable-secret-storage
