### ISSUE TITLE
Razor support not working

### ISSUE THREAD

**Issue by bra0** [OmniSharp/omnisharp-vscode#3826]
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.45.1
**C# Extension**: 1.22.0

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.402
 Commit:    c7f2f96116

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.402/

Host (useful for support):
  Version: 2.2.8
  Commit:  b9aa1abc51

.NET Core SDKs installed:
  2.1.806 [/usr/share/dotnet/sdk]
  2.2.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-close-tag|formulahendry|0.5.7|
|auto-rename-tag|formulahendry|0.1.3|
|bootstrap-3-snippets|wcwhitehead|0.1.0|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|code-settings-sync|Shan|3.4.3|
|csharp|ms-dotnettools|1.22.0|
|csharpextensions|jchannon|1.3.1|
|csharpfixformat|Leopotam|0.0.84|
|docomment|k--kato|0.1.11|
|node-module-intellisense|leizongmin|1.5.0|
|razor-snippets-for-asp-net-core|aledev29|0.0.3|
|remote-wsl|ms-vscode-remote|0.44.2|
|todo-tree|Gruntfuggly|0.0.176|
|vscode-csharp-snippets|jorgeserrano|0.3.1|
|vscode-docker|ms-azuretools|1.2.1|
|vscode-eslint|dbaeumer|2.1.5|
|vscode-google-translate|funkyremi|1.4.5|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vue|jcbuisson|0.1.5|;

</details>

**Comment by cartermp** [comment]
@NTaylorMullen unfortunately not much to go on in this issue, but would you happen to know if maybe the Razor language support has an assumption about a newer .NET SDK?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen unfortunately not much to go on in this issue, but would you happen to know if maybe the Razor language support has an assumption about a newer .NET SDK?

It doesn't have any dependencies. @bra0 would you mind sharing your OmniSharp/Razor Log output?

**Comment by bra0** [comment]
> > @NTaylorMullen unfortunately not much to go on in this issue, but would you happen to know if maybe the Razor language support has an assumption about a newer .NET SDK?
> 
> It doesn't have any dependencies. @bra0 would you mind sharing your OmniSharp/Razor Log output?

Sorry. This problem was solved after removing all extensions.

**Comment by bra0** [comment]
Sorry. This problem was solved after removing all extensions.
