### ISSUE TITLE
Incompatible with VS Code on ARM64 Devices

### ISSUE THREAD

**Issue by bebauke** [OmniSharp/omnisharp-vscode#3836]
Now, that Visual Studio Code is availible for ARM-Devices (in Preview) i would love to see this AddOn being compatible. In my case i get notified "The C# extension for Visual Studio Code (powered by OmniSharp) is incompatiable on win32 ARM64" after installing the AddOn.

**Comment by gregg-miskelly** [comment]
We are using https://github.com/OmniSharp/omnisharp-vscode/issues/3006 to track Windows ARM64 support.
