### ISSUE TITLE
Missing all of these "C# editing support, including Syntax Highlighting, IntelliSense, Go to Definition, Find All References"

### ISSUE THREAD

**Issue by mahadreamz** [OmniSharp/omnisharp-vscode#3843]
I don't see the C# editing support, including Syntax Highlighting, IntelliSense, Go to Definition, Find All References.

![image](https://user-images.githubusercontent.com/48503274/84437723-78d00700-ac03-11ea-863e-ec23c6063df5.png)

**Comment by JoeRobich** [comment]
@mahadreamz Sorry you are having trouble. Can you please share the OmniSharp Log from the Output pane?

**Comment by mahadreamz** [comment]
Thanks for the reply. I don't see any log in there. I have installed this extension for my C# project. When I expected this language support such as Go to definition, Find all references, e.t.c they all not appearing when I right the code area or even thru the command palette. I'm not sure what I'm missing.

**Comment by JoeRobich** [comment]
@mahadreamz This seems odd. There should be a log in the OmniSharp output window. Have you opened a folder that contains a C# project or solution?

**Comment by mahadreamz** [comment]
@JoeRobich It has nothing.. Just to make sure I'm giving you correct info.. I did not try to work on omnisharp project.. I'm saying the issue I see is while using this extension in my c# solution.

**Comment by JoeRobich** [comment]
@mahadreamz I would have expected there to be logging such as this:
 
![image](https://user-images.githubusercontent.com/611219/84542148-aec9c580-acad-11ea-9958-15ee044a2c6c.png)

Since you have opened a folder containing your C# solution but do not see any logging for OmniSharp in the Output pane, I can only assume it might be an installation failure. Could you try reinstalling the extension to see if that resolves the issue?

**Comment by mahadreamz** [comment]
Thank you.. I see this.. 

![image](https://user-images.githubusercontent.com/48503274/84547116-d67e5500-acd0-11ea-8dc9-bbdfeb54646e.png)

**Comment by mahadreamz** [comment]
@JoeRobich  I updated the path variable (https://github.com/OmniSharp/omnisharp-vscode/issues/32#issuecomment-241223579) and it worked. Omnisharp started successfully. Please correct me if you think otherwise. 

![image](https://user-images.githubusercontent.com/48503274/84548923-c5cfde00-acd4-11ea-9d97-9a5622fdaa82.png)

**Comment by JoeRobich** [comment]
@mahadreamz  Very odd that you would have to manually set the omnisharp.path. Did your solution load properly with your change?

**Comment by mahadreamz** [comment]
@JoeRobich  yes it did.
