### ISSUE TITLE
Refactorings opens a new editor with the modified file, leaving the active unchanged.

### ISSUE THREAD

**Issue by the-exodus** [OmniSharp/omnisharp-vscode#3847]
When running refactorings such as "Extract to new file", atleast for public enums and classes, the changes aren't applied to the currently active editor. The content doesn't change, the modified-indicator isn't set, but instead a new editor gets created, with the modified version of the file.

Same seems to happen when quick-fixing missing Usings under some circumstances, such as the target-class, unintentionally, not having a parent namespace or something. 

The new editor also doesn't get focus and iis easy to miss, which has lead to some instances of me hacking away in the "stale" editor and getting out of sync :]

**Comment by cartermp** [comment]
Thanks for reporting. I can't reproduce this with a new project on the latest extension version. Do you have a codebase you can share where you see this on the latest version? Thanks!
