### ISSUE TITLE
[ERROR:OmniSharp.Dnx.DnxProjectSystem] TODO: unknown keyword platform

### ISSUE THREAD

**Issue by z2xlong** [OmniSharp/omnisharp-vscode#385]
VSCode Version:1.1.1
OS Version:Mac OSX El Capitan 10.11.5
Symptom: The formatting code & intelligent functions does not work.

Steps to Reproduce:

Create new ASPNET project via yeoman, the contents of project.json as follows:
{
"version": "1.0.0-*",
"buildOptions": {
"emitEntryPoint": true
},

"dependencies": {
"Microsoft.NETCore.App": {
"type": "platform",
"version": "1.0.0-rc2-3002702"
},
"protobuf-net": "2.1.0-alpha-1",
"System.Collections": "4.0.10"
},

"frameworks": {
"netcoreapp1.0": {
"imports": "dnxcore50"
}
},

"tooling": {
"defaultNamespace": "Demo"
}
}

The Omnisharp log like this:
[INFO] Starting OmniSharp at '/Users/zzx/Projects/DesignSmell/Demo'...
[INFO] Started OmniSharp from '/Users/zzx/.vscode/extensions/ms-vscode.csharp-0.3.7/bin/omnisharp' with process id 9572...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location '/Users/zzx/Projects/DesignSmell/Demo' on host 9561.
[INFORMATION:OmniSharp.Dnx.DnxPaths] Using runtime '/Users/zzx/.k/runtimes/kre-mono.1.0.0-beta3'.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning '/Users/zzx/Projects/DesignSmell/Demo' for DNX projects
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Found project '/Users/zzx/Projects/DesignSmell/Demo/project.json'.
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Listening on port 58705
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Running DesignTimeHost on port 58705, with PID 9579
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Connected
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Client accepted 127.0.0.1:58705
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Client accepted 127.0.0.1:58705
[ERROR:OmniSharp.Dnx.DnxProjectSystem] TODO: unknown keyword platform
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] No solution files found in '/Users/zzx/Projects/DesignSmell/Demo'
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in '/Users/zzx/Projects/DesignSmell/Demo'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Solution has finished loading

**Comment by DustinCampbell** [comment]
Hi, it looks like you're using an old version of the C# Extension, which won't work with .NET Core RC2. You should upgrade your extension as follows:

1. Open Visual Studio Code
2. Select View->Command Palette... from the menu
3. Execute the "Extensions: Show Outdated Extensions" command
4. Choose "C#"

**Comment by DustinCampbell** [comment]
Did the steps above correct the problem for you?

**Comment by z2xlong** [comment]
sorry for the reply too late, now it’s work fine, thanks

 

-- 

Best Regards

Joe

 

发件人: Dustin Campbell <notifications@github.com>
答复: OmniSharp/omnisharp-vscode <reply@reply.github.com>
日期: 2016年6月8日 星期三 下午9:29
至: OmniSharp/omnisharp-vscode <omnisharp-vscode@noreply.github.com>
抄送: Joe Zhu <zxz823@msn.com>, Author <author@noreply.github.com>
主题: Re: [OmniSharp/omnisharp-vscode] [ERROR:OmniSharp.Dnx.DnxProjectSystem] TODO: unknown keyword platform (#385)

 

Did the steps above correct the problem for you?

**Comment by DustinCampbell** [comment]
Excellent! Thanks for confirming.
