### ISSUE TITLE
Error with Simplified parameter null validation code when i used net5.0 preview.5

### ISSUE THREAD

**Issue by dreamMoli** [OmniSharp/omnisharp-vscode#3850]
## Environment data
`dotnet --info` output:
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.5.20279.10
 Commit:    8139f1b74e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100-preview.5.20279.10/

Host (useful for support):
  Version: 5.0.0-preview.5.20278.1
  Commit:  4ae4e2fe08

.NET SDKs installed:
  5.0.100-preview.5.20279.10 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.5.20279.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20278.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
VS Code version:1.47.0-insider
omnisharp version 1.35.4-beta.2

## OmniSharp log
OmniSharp server started.
    Path: /Users/gtl/.vscode-insiders/extensions/ms-dotnettools.csharp-1.22.0/.omnisharp/1.35.4-beta.2/run
    PID: 5772

## Steps to reproduce
1.Create a new .NET Core console app
2.Add the following code to Program.cs:
public static DateTime GetSysDateTimeNow(string timezone!)
{
       Instant now = SystemClock.Instance.GetCurrentInstant();
       var defaultZone = DateTimeZoneProviders.Tzdb[timezone];
        return now.InZone(defaultZone).ToDateTimeUnspecified();
}

var a = GetSysDateTimeNow("Etc/GMT");
3.Add <LangVersion>9.0</LangVersion> or <LangVersion>preview</LangVersion> to the project file.
4.build

## Expected  behavior
No error shown

## Actual behavior
1. when I used this tag "<LangVersion>9.0</LangVersion>" with an error:CSC : error CS1617: Invalid option '9.0' for /langversion. Use '/langversion:?' to list supported values
2. when I used this tag <LangVersion>preview</LangVersion> whis an error:error CS1003: Syntax error, ',' expected

**Comment by filipw** [comment]
The compiler currently doesn't expose `9.0` https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/LanguageVersion.cs#L131-L137, you should use `preview`.

Also, this syntax `public static DateTime GetSysDateTimeNow(string timezone!)` is incorrect - what is the purpose of `!`?

**Comment by dreamMoli** [comment]
so what is the correct sample?

**Comment by dreamMoli** [comment]
Would you show me  a correct example of Simplified parameter null validation code?

**Comment by filipw** [comment]
you can find the documentation here https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types and here https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving

**Comment by dreamMoli** [comment]
THANKS
