### ISSUE TITLE
Publish extensions to open-vsx

### ISSUE THREAD

**Issue by orblazer** [OmniSharp/omnisharp-vscode#3853]
I'm a [VS Codium](https://github.com/VSCodium/vscodium) user, a FLOSS version of VS Code, it's the same code but without the Microsoft's telemetry and branding.
I want to request if possible to add the _C#_ extension on the [open-vsx.org](https://open-vsx.org/) market to us doesn't need to works with the Microsoft marketplace as is unclear if it's legal to use it on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

Additional info:

- This is [how to](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) publish a new extension.

**Comment by cartermp** [comment]
We're not likely to do this. However, binaries are on the release page of this repo and we encourage you to use them however you see fit.

**Comment by rkttu** [comment]
I also felt uncomfortable with this part, so I created an automatic build workflow using Github Actions to automatically build and publish the VSX package to the OpenVSX registry whenever a new version tag is registered. I hope this helps.

https://github.com/rkttu/vscode-csharp-autobuild

https://open-vsx.org/extension/dotnetdev-kr-custom/csharp
