### ISSUE TITLE
Intellisence problem while NET Core scrpting

### ISSUE THREAD

**Issue by Alvin-Seville** [OmniSharp/omnisharp-vscode#3879]
Follow [this](https://www.hanselman.com/blog/CAndNETCoreScriptingWithTheDotnetscriptGlobalTool.aspx) instruction to run your first script. Try to include some NuGet package, for instace [this](https://www.nuget.org/packages/NETMouseProjectsOrganization.ABCNET/) one:

```C#
#r "nuget: NETMouseProjectsOrganization.ABCNET, 0.0.5"

using ABCNET.Extensions;

"Hello world!".Println();
1.Println();
```

Program will run normally bot Intellisence will not - it willl say that there is no `ABCNET` namespace available and `Println` extension method respectvely:

![image](https://user-images.githubusercontent.com/42812113/85637127-f6eecd80-b647-11ea-93cf-36dcc3a6f724.png)

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (10.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
LogFileHighlighter|emi|2.8.0
vscode-firefox-debug|fir|2.9.0
vscode-test-explorer|hbe|2.19.1
roslynator|jos|3.0.0
bash-ide-vscode|mad|1.10.2
csharp|ms-|1.22.1
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.8
vscode-nxunit-test-adapter|wgh|0.1.3
markdown-all-in-one|yzh|3.1.0

</details>

**Comment by filipw** [comment]
you have to activate the dotnet-script compatible mode in OmniSharp as it defaults to CSI mode (jo nuget support). you need to add omnisharp.json file at the root of your workspace. you can also add it globally using these instructions https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#global-omnisharpjson

```
{
  "script": {
    "enableScriptNuGetReferences": true,
    "defaultTargetFramework": "netcoreapp3.1"
  }
}
```

dotnet script init also generates the relevant omnisharp.json

**Comment by Alvin-Seville** [comment]
[Scripting.zip](https://github.com/OmniSharp/omnisharp-vscode/files/4833953/Scripting.zip)

There is omnisharp.json at the root.

**Comment by filipw** [comment]
yes and I can run your sample without any problems 
<img width="575" alt="Screenshot 2020-06-25 23 53 56" src="https://user-images.githubusercontent.com/1710369/85799218-2a605380-b73f-11ea-96ea-5c610e0f22ef.png">

if you have any issues, please post your OmniSharp log

**Comment by Alvin-Seville** [comment]
Log is here:
```
Starting OmniSharp server at 6/25/2020, 3:26:01 PM
    Target: c:\Users\Alvin Seville\Documents\Self development\Scripting

OmniSharp server started.
    Path: c:\Users\Alvin Seville\.vscode\extensions\ms-dotnettools.csharp-1.22.1\.omnisharp\1.35.3\OmniSharp.exe
    PID: 3704

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.6.30204.135 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.4 - "c:\Users\Alvin Seville\.vscode\extensions\ms-dotnettools.csharp-1.22.1\.omnisharp\1.35.3\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.6.30204.135 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Alvin Seville\Documents\Self development\Scripting'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\Alvin Seville\Documents\Self development\Scripting'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Alvin Seville\Documents\Self development\Scripting'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Found 1 CSX files.
[info]: OmniSharp.Script.ScriptContextProvider
        Searching for compilation dependencies with the fallback framework of 'netcoreapp3.1'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Added CSX project 'c:\Users\Alvin Seville\Documents\Self development\Scripting\main.csx' to the workspace.
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Alvin Seville\Documents\Self development\Scripting' on host 1832.
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 1.
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
```

**Comment by filipw** [comment]
this log shows no errors though 😀

**Comment by Alvin-Seville** [comment]
It is Roslynator extension problem.

**Comment by filipw** [comment]
OK let's close this one then - thanks
