### ISSUE TITLE
Code Lense actions result in "actual command NOT FOUND" vscode alert

### ISSUE THREAD

**Issue by AndrewTriesToCode** [OmniSharp/omnisharp-vscode#3883]
##Issue Description ##
Sometimes when trying to run or debug test from the code lense area it doesn't do anything an VS Code shows "actual command NOT FOUND" in an alert window in the bottom right. This usually occurs after an exception has occurred in a test or after debugging a test. Only fix is to restart omnisharp or vscode.

## Steps to Reproduce ##
It's intermittent. Create some tests that cause exceptions. Keep trying to "run tests" until this occurs. Sometimes stopping debugger in the middle of debugging a test seems to cause this. Then any code lense action like references, run test, or debug test result with the error.

## Expected Behavior ##
Test runs.

## Actual Behavior ##
Test doesn't run and "actual command NOT FOUND" error in vscode alert box in lower right corner.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.46.1
**C# Extension**: 1.22.1

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.10.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.300/

Host (useful for support):
  Version: 5.0.0-preview.5.20278.1
  Commit:  4ae4e2fe08

.NET SDKs installed:
  2.1.806 [/usr/local/share/dotnet/sdk]
  3.1.300 [/usr/local/share/dotnet/sdk]
  5.0.100-preview.5.20279.10 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.5.20279.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20278.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.22.1|
|docomment|k--kato|0.1.13|
|dotnet|formulahendry|0.0.4|
|msbuild-project-tools|tintoy|0.3.6|
|vscode-guid|heaths|1.4.20|
|vscode-icons|vscode-icons-team|10.1.1|;

</details>

**Comment by SirIntruder** [comment]
https://github.com/microsoft/vscode/issues/96783

Unfortunately it's a vscode issue rather than a c# extension issue.

**Comment by jmarolf** [comment]
closing as external
