### ISSUE TITLE
The type or namespace name 'Drawing' does not exist in the namespace 'System'

### ISSUE THREAD

**Issue by minhducsun2002** [OmniSharp/omnisharp-vscode#3888]
## Issue Description ##
Error (`The type or namespace name 'Drawing' does not exist in the namespace 'System' (are you missing an assembly reference?)`)
## Steps to Reproduce ##
- Create a project with `dotnet new console`
- Open the project with Visual Studio Code.
## Expected Behavior ##
- No error happens.
## Actual Behavior ##
Lots of error like `The type or namespace name 'Drawing' does not exist in the namespace 'System' (are you missing an assembly reference?)` though `dotnet publish` works well.
![image](https://user-images.githubusercontent.com/32769878/86389068-fdbcb680-bcbf-11ea-89d7-40266be0d00c.png)
![image](https://user-images.githubusercontent.com/32769878/86389166-1f1da280-bcc0-11ea-9d41-b09e1327eb7c.png)

### OmniSharp log ###
<details>

```
Starting OmniSharp server at 7/2/2020, 11:49:46 PM
    Target: /home/cipher/Projects/sunshine

OmniSharp server started with Mono 6.4.0.
    Path: /home/cipher/.vscode/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/OmniSharp.exe
    PID: 9085

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on arch 0.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.4 - "/usr/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.4 - "/home/cipher/.vscode/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.4 - "/usr/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /home/cipher/.vscode/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/cipher/Projects/sunshine'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/cipher/Projects/sunshine'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/cipher/Projects/sunshine/src/sunshine.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/cipher/Projects/sunshine'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/cipher/Projects/sunshine/src/sunshine.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/cipher/Projects/sunshine' on host 8947.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/cipher/Projects/sunshine/src/sunshine.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/cipher/Projects/sunshine/src/sunshine.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: sunshine
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 23.
```

</details>

### C# log ###
(No output.)

## Environment information ##

**VSCode version**: 1.46.0
**C# Extension**: 1.22.1

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.4.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.103
 Commit:    6f74c4a1dd

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.103/

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.103 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.28.3|
|csharp|ms-dotnettools|1.22.1|
|discord-vscode|icrawl|3.14.0|
|gitlens|eamodio|10.2.2|
|go|golang|0.15.0|
|python|ms-python|2020.6.91350|
|vscode-docker|ms-azuretools|1.3.1|
|vscode-firefox-debug|firefox-devtools|2.9.0|
|vscode-github|KnisterPeter|0.30.3|
|vscode-wakatime|WakaTime|4.0.0|;
</details>

**Comment by JoeRobich** [comment]
@minhducsun2002 Sorry you are having issues. This might be a case where the msbuild in the mono package isn't complete. There is a msbuild-stable package you could install that may resolve this issue. If you find things just work better with the included mono, you can also set `omnisharp.useGlobalMono` to `never` and it will only use the included mono.

**Comment by minhducsun2002** [comment]
Thank you, ignoring the global Mono installation fixed the issue.
