### ISSUE TITLE
[question] Razor runtime dependency license

### ISSUE THREAD

**Issue by muhammadsammy** [OmniSharp/omnisharp-vscode#3894]
Hello!
Could you please clarify the license of the "Razor" runtime dependency of the extension?
Thank you!

**Comment by JoeRobich** [comment]
cc: @NTaylorMullen

**Comment by NTaylorMullen** [comment]
https://github.com/dotnet/aspnetcore-tooling/blob/master/LICENSE.txt

😄

**Comment by cartermp** [comment]
Closing as per the link to the license

**Comment by muhammadsammy** [comment]
Thank you!
