### ISSUE TITLE
"Run without Debugging" breaks future debug sessions

### ISSUE THREAD

**Issue by toptensoftware** [OmniSharp/omnisharp-vscode#3899]
## Issue Description ##

After using the "Run without Debugging" command breakpoints in subsequent "Start Debugging" sessions don't trigger.

Not sure if this is a C# extension issues, VS code issue, or .NET Core issue.

## Steps to Reproduce ##

1. Open a Hello World C# netcoreapp3.1 console application (or any other application)
2. Set a break point anywhere
3. Use the "Start Debugging" command and confirm the break point works
4. Use the "Run without Debugging" command.  Breakpoint won't be hit - as expected
5. Use the "Start Debugging" command... breakpoint is no longer hit
6. Restart VS Code
7. Use the "Start Debugging" command... breakpoints work again.

I've also created quick screen cast showing the issue here: https://www.dropbox.com/s/alvycxhwiosqovk/VSCodeCSharpDebugIssue.mp4?dl=0

## Expected Behavior ##

Shouldn't need to restart VS Code after using "Run without Debugging" command

## Actual Behavior ##

Breakpoints don't work after having used the "Run without Debugging" commands

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

Starting OmniSharp server at 09/07/2020, 10:59:38 am
    Target: c:\Users\Brad\Projects\debugtest

OmniSharp server started.
    Path: c:\Users\Brad\.vscode\extensions\ms-dotnettools.csharp-1.22.1\.omnisharp\1.35.3\OmniSharp.exe
    PID: 7132

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.6.30204.135 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.4 - "c:\Users\Brad\.vscode\extensions\ms-dotnettools.csharp-1.22.1\.omnisharp\1.35.3\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.6.30204.135 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Brad\Projects\debugtest'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\Brad\Projects\debugtest'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Brad\Projects\debugtest\debugtest.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Brad\Projects\debugtest'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\Brad\Projects\debugtest\debugtest.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Brad\Projects\debugtest' on host 6792.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\Brad\Projects\debugtest\debugtest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\Brad\Projects\debugtest\debugtest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: debugtest

### C# log ###
<details>Post the output from Output-->C# here</details>

Empty!

## Environment information ##

**VSCode version**: 1.46.1
**C# Extension**: 1.22.1

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.202
 Commit:    6ea70c8dca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.202\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.22.1|
|docomment|k--kato|0.1.13|
|dotnet-test-explorer|formulahendry|0.7.3|;

</details>

**Comment by gregg-miskelly** [comment]
Thanks for the excellent bug report. It looks like you are running into https://github.com/microsoft/vscode/issues/99576. It is fixed in VS Code insiders, so I will double check that this addresses the issue.

**Comment by gregg-miskelly** [comment]
Yes, it works for me in VS Code Insiders. So if you are really bothered by this, you can switch to Insiders until they ship a new version with the fix. Thanks again for the detailed bug report!

**Comment by toptensoftware** [comment]
Hi @gregg-miskelly - thanks for fast response.  Switched to insiders and can confirm seems to be fixed there.
