### ISSUE TITLE
Extension not suggesting to use explicit type instead of var

### ISSUE THREAD

**Issue by jffaust** [OmniSharp/omnisharp-vscode#3907]
## Issue Description ##
I have a couple of variables declaration using `var` instead of the explicit type. In [Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/convert-var-to-explicit-type?view=vs-2019), Omnisharp would suggest me to use the explicit type instead and I could make the change automatically by using the keyboard shortcut (`Ctrl+.`).

This was super useful and I can't figure out how to make it work inside VS Code. I was not able to find any documentation, issues or articles related to this so I'm creating a new issue.

In this specific case I was doing a LINQ group by and I wanted to be able to use the explicit type and then go look at the type definition for IGrouping.

## Steps to Reproduce ##
`var myCustomObject = new CustomObject();`

## Expected Behavior ##
Suggest the option to use the explicit type when using the code actions keyboard shortcut.

## Actual Behavior ##
Missing suggestion:
![image](https://user-images.githubusercontent.com/4367222/87233471-a1c7f100-c395-11ea-9e2d-ad305f0b67b5.png)
![image](https://user-images.githubusercontent.com/4367222/87233476-a9879580-c395-11ea-82ce-7b2949f60eac.png)

## Environment information ##

**VSCode version**: 1.46.1
**C# Extension**: 1.22.1

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-run-command|gabrielgrinberg|1.6.0|
|azure-account|ms-vscode|0.8.11|
|csharp|ms-dotnettools|1.22.1|
|githistory|donjayamanne|0.6.5|
|powershell-preview|ms-vscode|2020.6.1|
|prettier-vscode|esbenp|5.1.3|
|vscode-azurefunctions|ms-azuretools|0.23.0|
|vscode-icons|vscode-icons-team|10.1.1|
|vscode-nuget-package-manager|jmrog|1.1.6|;

</details>

**Comment by cartermp** [comment]
This is driven from a `.editorconfig` where conventions for `var` vs. explicit types are configured. Roslyn uses that to determine when to suggest style changes. Is `.editorconfig` in use for your codebase?
![image](https://user-images.githubusercontent.com/6309070/87486189-9839c580-c5ef-11ea-9166-28be07d43fac.png)

**Comment by jffaust** [comment]
That's exactly what I was looking for :)

Thanks a lot :)

**Comment by rom5jp** [comment]
> This is driven from a `.editorconfig` where conventions for `var` vs. explicit types are configured. Roslyn uses that to determine when to suggest style changes. Is `.editorconfig` in use for your codebase?
> ![image](https://user-images.githubusercontent.com/6309070/87486189-9839c580-c5ef-11ea-9166-28be07d43fac.png)
> 
> You can get started here: https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions?view=vs-2019#implicit-and-explicit-types

Didn't work for me =/

**Comment by JoeRobich** [comment]
@rom5jp You need to also set "omnisharp.enableRoslynAnalyzers" to "true" in the VS Code preferences if you haven't already.
