### ISSUE TITLE
Possible wrong color coding for nested function return type

### ISSUE THREAD

**Issue by gsscoder** [OmniSharp/omnisharp-vscode#3911]
To be honest I'm not sure this is the right place to post this issue.

Anyway I think this is wrong (more easy if I attach a screenshot):
![colorcoding-nestedreturn](https://user-images.githubusercontent.com/1194228/87387597-508d4c80-c5a3-11ea-854e-4bf0733d84aa.PNG)

Regards,
Giacomo S. S.

**Comment by JoeRobich** [comment]
@gsscoder  To workaround some of the limitations of our C# textmate theme, you can enable `editor.semanticHighlighting.enabled` and `csharp.semanticHighlighting.enabled`. It required using a theme that supports semantic highlight. You can try our Visual Studio 2019 Dark theme if you like, or you can tell VS Code that you current theme supports semanticHighlighting by following the instructions here (https://github.com/microsoft/vscode/issues/92740#issuecomment-600100176) to update your "editor.tokenColorCustomizations".

**Comment by cartermp** [comment]
Closing out - this is ultimately controlled at the VSCode platform level where each theme needs to opt in to semantic colorization.

**Comment by gsscoder** [comment]
OK, @JoeRobich, @cartermp! Thanks for suggestions and explanations.
