### ISSUE TITLE
Breakpoints are removed after setting up a new breakpoint in debugging session

### ISSUE THREAD

**Issue by cateyes99** [OmniSharp/omnisharp-vscode#3921]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
VS Code version: **1.47.2**
C# Extension version: **1.22.1**

## Steps to reproduce
Create a .NET Core 3.1 Web API project. Set up some breakpoints before starting a debugging session. Observe that those breakpoints persist after closing the VSCode and re-opening the project in VSCode.

Start a debugging session, the execution pauses when it hits a breakpoint. Now set up another breakpoint somewhere while in the debugging session. Then just stop debugging, and close VSCode. Now re-open the project in VSCode, observe all breakpoints are gone (I also observed sometimes breakpoints are gone right after stopping debugging without the need of closing VSCode).

## Expected  behavior
Breakpoints should still be there.

## Actual behavior
They are gone.

**Comment by gregg-miskelly** [comment]
I can reproduce this as well. I opened https://github.com/microsoft/vscode/issues/103111 for the VS Code team to have a look.
