### ISSUE TITLE
How to discover available C# Extension methods for and object

### ISSUE THREAD

**Issue by wayneforrest** [OmniSharp/omnisharp-vscode#3923]
How does one discover the available extension methods for a particular object using VSCode?
Autocomplete does not show me the extension methods.

**Comment by wayneforrest** [comment]
I found another plugin, that might help with this - I have not tested it yet though...
Called Auto Using...
https://marketplace.visualstudio.com/items?itemName=Fudge.auto-using

**Comment by jmarolf** [comment]
I believe @333fred is working on getting completion for unimported types in.

**Comment by filipw** [comment]
yes it's already merged, the option is `omnisharp.enableImportCompletion` to enable it.

**Comment by wayneforrest** [comment]
Thanks FillipW, 

I just checked my version of `ms-dotnettools.csharp ` and it is `V1.23.1` , I do not see the `omnisharp.enableImportCompletion`
when I navigate to Settings.  Also by configuring my setttings.josn file to this did not work for me.

`   "omnisharp.enableImportCompletion": true `

Wondering if that merge is part of my version, has it been released yet?

**Comment by filipw** [comment]
it has not been officially released yet - it will be in the next release.
There is however a beta to try out https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.2-beta1

instructions to install the beta are here https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases

**Comment by wayneforrest** [comment]
Thank you for the update Filip.

**Comment by jmarolf** [comment]
closing as fixed in 1.23.2
