### ISSUE TITLE
Using C# 9 features shows a lot squiggly lines in VS Code, while VS is fine with C# 9 features

### ISSUE THREAD

**Issue by saint4eva** [OmniSharp/omnisharp-vscode#3925]
Using the C# 9 features, Visual Studio Code shows a lot of squiggly lines, although the code compiled and ran. While in Visual Studio 2019 preview everything is okay - no squiggly lines.

## Environment data
`dotnet --info` output:  
![Annotation 2020-07-23 075240](https://user-images.githubusercontent.com/3264826/88259136-9a6be600-ccb9-11ea-964c-960533186afd.png)

VS Code version: 1.48.0- insider (user setup)
C# Extension version: v1.22.1

## Expected  behavior
![VS- C9](https://user-images.githubusercontent.com/3264826/88258855-013ccf80-ccb9-11ea-91f5-ef7870f8abd8.png)

## Actual behavior
![VSCode-C9](https://user-images.githubusercontent.com/3264826/88258861-069a1a00-ccb9-11ea-8eb6-e8062f253e87.png)

**Comment by filipw** [comment]
this will be supported in the next prerelease

try setting "omnisharp.path": "latest" in the meantime to opt into CI build of omnisharp

**Comment by jmarolf** [comment]
fixed in 1.23.1
