### ISSUE TITLE
Improve Attribute Usage Handling

### ISSUE THREAD

**Issue by wjk** [OmniSharp/omnisharp-vscode#393]
Would it be possible to improve how Visual Studio Code handles handling of `Attribute` usage in C# code? My request is divided into two main changes:
1. When I tab-complete the usage of a hypothetical `FooAttribute` class, VSCode produces `[FooAttribute]`. “Full” Visual Studio on Windows produces just `[Foo]`. Can we harmonize the two? (This causes not-inconsequential project churn when switching back and forth between IDEs.)
2. VSCode recognizes and provides IntelliSense for required formal parameters in the attribute’s constructor, but does not recognize named arguments. (This means that IntelliSense does not know what to do with the `AllowMultiple` part of `[AttributeUsageAttribute(AttributeTargets.Class, AllowMultiple = true)]`. Note that the syntax-error-detection parser handles this correctly.

**Comment by jtillman** [comment]
I use Attributes heavily and attempting to fight against the current inteliisense/autocorrect from appending of "Attribute" is a huge pain.

**Comment by dmccaffery** [comment]
I've been hitting this constantly as well... might try to add a PR if work on this has not been ongoing... let me know.
