### ISSUE TITLE
Add proper & tracking scope for instance field variables

### ISSUE THREAD

**Issue by Kein** [OmniSharp/omnisharp-vscode#3933]
## Environment data
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
VS Code version: 1.47.2
C# Extension version: 1.22.1

## Summary
`Instance` or `field` variables are not tracked properly and thus it is impossible to have proper syntax color for them.

## To reproduce
1. Define your custom field variable color for scope `"entity.name.variable.field.cs"`
2. Observe field variable color being applied on theme reload.
3. Write a instance method that sets or gets said variable.
4. Observe that variable now uses default scope `"entity.name.variable.field.cs"` and uses default or local variable color.
5. There is no way to override or fix that without proper scope being applied.

![image](https://user-images.githubusercontent.com/623756/88546380-f8cff600-d024-11ea-9863-d72854ba71d5.png)

![image](https://user-images.githubusercontent.com/623756/88546387-fbcae680-d024-11ea-92eb-50076e087471.png)

Thus, it is impossible to have proper and **consistent** syntax coloration for field variables.

## Additional info
MS Visual Studio has `User members - Field` that is used for field variables and can be tracked properly across whole project. Same for Rider and his `Field` entry for the Color Theme. I find it extremely lacking that VSCode and Omnisharp, which extends its csharp capabilities, cant track instance field properly, in my opinion this really diminishes code raadability *"at a glance"*.

Is there any chance this feature can be added so we can have more agile syntax colorization?

**Comment by JoeRobich** [comment]
@Kein To workaround some of the limitations of our C# textmate theme, you can enable `editor.semanticHighlighting.enabled` and `csharp.semanticHighlighting.enabled`. It required using a theme that supports semantic highlight. You can try our Visual Studio 2019 Dark theme if you like, or you can tell VS Code that you current theme supports semanticHighlighting by following the instructions here (https://github.com/microsoft/vscode/issues/92740#issuecomment-600100176) to update your "editor.tokenColorCustomizations".

**Comment by Kein** [comment]
Thanks, `semanticHighlighting` somewhat works. Question: is this a limitation or I'm missing something:
![image](https://user-images.githubusercontent.com/623756/88594497-f479fc00-d069-11ea-959f-8543c7f08c56.png)

**Comment by JoeRobich** [comment]
This is currently a limitation of VS Code, the quick info popups are rendered with the languages textmate syntax highlighting.

**Comment by Kein** [comment]
@JoeRobich 
Thanks Joe, I'm closing the issue since there does not seems to be anything that wasnt covered. Appreciate all the help and sorry for taking your time.

**Comment by JoeRobich** [comment]
@Kein Thanks for reporting the issue. We still consider our semantic highlight support to be experimental. There are issues with diff rendering that we need to address. Hoping we can make it the default in the near future. =)
