### ISSUE TITLE
your 131072x1 screen size is bogus, expect trouble

### ISSUE THREAD

**Issue by Alirezanet** [OmniSharp/omnisharp-vscode#3936]
debugger Attach not working. 
looks like it's caused by the c# extension. ([#100563](https://github.com/microsoft/vscode/issues/100563))

## Environment information ##

**VSCode version**: 1.47.3
**C# Extension**: 1.22.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.302/

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
</details>

**Comment by ms-jasondel** [comment]
Same issue for me:

Version: 1.48.0-insider (user setup)
Commit: 4c23fc22ced6d0c1f58215ce91ccd08d0c8a0006
Date: 2020-08-11T10:15:36.363Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by JoeRobich** [comment]
@Alirezanet @ms-jasondel Please try the 1.23.0 prerelease and let me know if it resolves your issue https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.0

**Comment by ms-jasondel** [comment]
> @Alirezanet @ms-jasondel Please try the 1.23.0 prerelease and let me know if it resolves your issue https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.0. see https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases

Pre-release v1.23.0 works! Thank you! I set this up with code-insiders and I was able to attach to a process with C# debugger using remote WSL2.

**Comment by Alirezanet** [comment]
> @Alirezanet @ms-jasondel Please try the 1.23.0 prerelease and let me know if it resolves your issue https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.0. see https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases

Yes, It's working with normal vscode (not insiders) too. thank you

**Comment by Mistic92** [comment]
I have the same issue with 1.23.2

```
Starting OmniSharp server at 9/29/2020, 4:40:38 PM
    Target: /root/projects/clientapi/solution/xxxxxxxxxx.Messenger.sln

OmniSharp server started.
    Path: /root/.vscode-server/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/run
    PID: 29768

your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

```
