### ISSUE TITLE
Can not peek definition or implementation even within existing .cs file

### ISSUE THREAD

**Issue by Jeevesy** [OmniSharp/omnisharp-vscode#3937]
VSCode Version: 1.47.3
C# extension 1.22.1

**Comment by cartermp** [comment]
Closing as no actionable info, please reply back with logs if you see this with the latest version of the extension.

**Comment by fpsantos86** [comment]
Hello,

I'm using VS Code in Kubuntu 20.04 with .net Core c# version 2.1.814.

But the command Ctrl+. (about peek definition) does not working.

What should I do? Is there any solution about that?

Regards,

Felipe.

**Comment by JoeRobich** [comment]
@fpsantos86 Sorry you are not seeing completion. Please open a new issue and provide the requested logs. It will allow up to better understand the cause of your issue. Thanks!
