### ISSUE TITLE
Nested Class Support

### ISSUE THREAD

**Issue by wjk** [OmniSharp/omnisharp-vscode#394]
I am currently working on porting [Eto](https://github.com/picoe/Eto) to .NET Core, and the Eto codebase uses a large number of nested types. However, I notice that the VSCode IntelliSense parser does not handle nested types correctly. For example, when I move the mouse over the declaration of `Eto.EtoEnvironment.IHandler`, the tooltip displays `Eto.IHandler`. This may cause problems, as by this logic Eto will have dozens of interfaces called `IHandler`, each of them appearing to be in the same namespace. Note that the C# compiler parses this code properly.

**Comment by DustinCampbell** [comment]
This will be fixed in the next release. Thanks @filipw!

**Comment by DustinCampbell** [comment]
I've created a [v1.6-beta2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.6-beta2) release of the C# extension that contains this fix, among others. See this page for information on [installing beta releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases)
