### ISSUE TITLE
Add "Make Object ID"-ish functionality to debugger

### ISSUE THREAD

**Issue by WebFreak001** [OmniSharp/omnisharp-vscode#3940]
## Issue Description ##

While debugging I wanted to access an object I have after it goes out of scope (see https://dailydotnettips.com/you-can-track-out-of-scope-objects-by-assigning-an-object-id-during-debugging-in-visual-studio/)

Intuitively I tried
```
var x = <expr>
```
in the debugger but it would just give me a CS0726 error.

I think it would be very useful if the "Make Object ID" functionality or a similar functionality by defining variables in the debug console could be added to the debugger.

## Environment information ##

**VSCode version**: 1.47.3
**C# Extension**: 1.22.1

<details><summary>Dotnet Information</summary>
.NET Core SDK:
 Version:   3.1.301
 Commit:    7feb845744

Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
</details>

**Comment by gregg-miskelly** [comment]
What you are trying to do works - you just need to add a semicolon at the end: `var x = <expr>;`

**Comment by WebFreak001** [comment]
you are right, my bad, thanks!

It's a little bit confusing how the semicolon drastically changes the message though: (manually translated from German)
```
var x = resources
error CS0726: "x" is not a valid format identifier.
var x = resources;
The expression was evaluated and produced no result.
```

maybe the debugger input line could be made a bit leaner so you don't need to end this statement with a semicolon?

**Comment by cartermp** [comment]
Closing as this has been answered.

**Comment by gregg-miskelly** [comment]
For the improved error message part of this: I opened https://github.com/dotnet/roslyn/issues/46736
