### ISSUE TITLE
Typo in supressBuildAssetsNotification setting name should be fixed

### ISSUE THREAD

**Issue by tamasvajk** [OmniSharp/omnisharp-vscode#3941]
`csharp.supressBuildAssetsNotification` setting should be spelled `suppressBuildAssetsNotification`. This should be a trivial change, but I'm unsure how to do it in a backwards compatible way. 

Can someone give me some guidance?

**Comment by filipw** [comment]
you can compare how we did backcompat for some options here https://github.com/OmniSharp/omnisharp-vscode/blob/4b249d11b9978bdcc38ed3ccbb578f2226801360/src/omnisharp/options.ts#L155-L191

you'd need a similar fallback here https://github.com/OmniSharp/omnisharp-vscode/blob/9dd0b0f12f391110520d7b56b9d7f7414b051d8d/src/assets.ts#L521
