### ISSUE TITLE
Debugger support for Windows ARM 64?

### ISSUE THREAD

**Issue by b2af** [OmniSharp/omnisharp-vscode#3946]
Are there plans to add Dubugger support for ARM 64 devices?

Thanks,

**Comment by gregg-miskelly** [comment]
There are definitely plans, but we don't have an exact date/release that we are targeting yet. This is tracked with #3006.

**Comment by tbonham** [comment]
This is good news. I'm waiting to get a surface pro x on this plugin to work in VSCode ARM.
