### ISSUE TITLE
Extension 'ms-dotnettools.csharp cannot use PROPOSED API

### ISSUE THREAD

**Issue by sweetliquid** [OmniSharp/omnisharp-vscode#3949]
Issue Type: <b>Bug</b>

After installing the C# plugin in vscode-insiders, the console will throw the following error every time I start it. (It does not  seem to affect the use)

Error:

```
Extension 'ms-dotnettools.csharp cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
```

Log:

```
abstractExtensionService.ts:500 Extension 'ms-dotnettools.csharp cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ abstractExtensionService.ts:500
_checkEnableProposedApi @ abstractExtensionService.ts:285
_deltaExtensions @ extensionService.ts:238
async function (async)
_deltaExtensions @ extensionService.ts:198
_handleDeltaExtensions @ extensionService.ts:178
(anonymous) @ extensionService.ts:117
fire @ event.ts:587
(anonymous) @ event.ts:763
fire @ event.ts:587
(anonymous) @ event.ts:56
fire @ event.ts:587
fire @ event.ts:589
(anonymous) @ ipc.ts:636
onResponse @ ipc.ts:715
onBuffer @ ipc.ts:701
(anonymous) @ ipc.ts:519
fire @ event.ts:587
(anonymous) @ ipc.net.ts:374
fire @ event.ts:587
acceptChunk @ ipc.net.ts:240
(anonymous) @ ipc.net.ts:201
t @ ipc.net.ts:29
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
```

Extension version: 1.22.1
VS Code version: Code - Insiders 1.48.0-insider (5696babbc1dce41788bae04b1a04ad35140bebfb, 2020-08-03T05:51:31.732Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sweetliquid** [comment]
Duplicate of #3872

**Comment by cartermp** [comment]
Thanks, closing as duplicate. @JoeRobich mentioned seeing this as well
