### ISSUE TITLE
Debugger for C# doesn't work; Hangs in infinite loop

### ISSUE THREAD

**Issue by transtrike** [OmniSharp/omnisharp-vscode#3973]
# Copied from the original report:

The debugging doesn't work at all. When running 'dotnet run' from an external terminal, the app runs with no problems(builds and runs properly). But when going to the "Run" tab in the "Activity Bar" and launching the ".NET Core Launch (console)" option, nothing happens. It doesn't run the program at all. It is like it hangs in a infinite loop. No breakpoints hit, not even the Main method is executed(tested with my application and with a "Hello World" example). I tried changing the "console" in launch.json to "integratedTerminal", "externalTerminal" and "internalConsole". None work. "ExternalTerminal" goes further then the others, but still nothing show. No print statements show, no cursor movement, no action. Just hangs and nothing. With this option, when i stop the debugger from the vscode itself, it does print "Click any key to continue...". In the end i tried with the ".NET Core Attach", but no success there too. I need to debug my application, because it's essential for my work. Please, I can use some assistance. Haven't had this problem before.

Note: I haven't tested with other languages
Note: Creating a new project and debugging it doesn't fix the issue. It still persists with default debug settings and default launch.json file.
Note: When using "console": "externalTerminal" in launch.json, the settings option "Terminal › External: Linux Exec" is set to "konsole". Tried with "gnome-terminal", but no success.

#### `dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   3.1.106
 Commit:    0f94483edc

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.106/

Host (useful for support):
  Version: 3.1.6
  Commit:  47a41ad866

.NET Core SDKs installed:
  3.1.106 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

## OmniSharp log
Nothing changes when debugger starts.

#### Log(Linux username replaced with $USER!):
Starting OmniSharp server at 8/12/2020, 10:30:15 PM
Target: /home/$USER/Documents/Programming/Projects/C#/Binary Search

OmniSharp server started.
    Path: /home/$USER/.vscode-oss/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/run
    PID: 18932

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on arch 0.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.4 - "/home/$USER/.vscode-oss/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/$USER/.vscode-oss/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "/home/$USER/.vscode-oss/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/$USER/.vscode-oss/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/$USER/.vscode-oss/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/$USER/.vscode-oss/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/$USER/Documents/Programming/Projects/C#/Binary Search'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/$USER/Documents/Programming/Projects/C#/Binary Search'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/$USER/Documents/Programming/Projects/C#/Binary Search/Binary Search.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/$USER/Documents/Programming/Projects/C#/Binary Search'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/$USER/Documents/Programming/Projects/C#/Binary Search/Binary Search.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/$USER/Documents/Programming/Projects/C#/Binary Search' on host 18409.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/$USER/Documents/Programming/Projects/C#/Binary Search/Binary Search.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/$USER/Documents/Programming/Projects/C#/Binary Search/Binary Search.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Binary Search
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 4.

## Steps to reproduce
I. Open VSCode and a '"Hello world" C# example
II. Place breakpoint in the Main method
III. Start debugger

## Expected  behavior
Hitting the breakpoint

## Actual behavior
Nothing. No print statements and console hangs in non-existant in the code infinite loop

**Comment by gregg-miskelly** [comment]
Can you add a debugger log? Here are instructions: https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging

**Comment by transtrike** [comment]
Debug Console:

-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Code - OSS","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true},"type":"request","seq":1}
-> (C) {"command":"launch","arguments":{"name":".NET Core Launch (console)","type":"coreclr","request":"launch","preLaunchTask":"build","program":"/home/$USER/Documents/Programming/Projects/C#/Binary Search/bin/Debug/netcoreapp3.1/Binary Search.dll","args":[],"cwd":"/home/$USER/Documents/Programming/Projects/C#/Binary Search","console":"internalConsole","stopAtEntry":false,"logging":{"engineLogging":false},"internalConsoleOptions":"openOnSessionStart","__sessionId":"4a51e22f-07a1-499e-855c-db9ec875c0ce"},"type":"request","seq":2}
<- (E) {"seq":3,"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n"}}
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"launch"}
<- (E) {"seq":5,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/CommandFailed","data":{"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr","VS.Diagnostics.Debugger.vsdbg.ErrorCode":-1989017584,"VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"arch","VS.Diagnostics.Debugger.vsdbg.Command":"handshake","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Linux","VS.Diagnostics.Debugger.vsdbg.Version":"16.6.20415.1 commit:0184bb70e1ed40656c0dfa53125805036207007b"}}}
<- (R) {"seq":6,"type":"response","request_seq":1,"success":false,"command":"handshake","message":"Error processing 'handshake' request. Unknown Error: 0x89720010"}

**Comment by gregg-miskelly** [comment]
I am not sure why you aren't seeing a better error message (I will take a look), but the problem you are running into is because you are using the OSS version of Visual Studio code. If you want C# debugging, you need to install the official version of VS Code from Microsoft.
