### ISSUE TITLE
CS8780 wrong warning

### ISSUE THREAD

**Issue by iSazonov** [OmniSharp/omnisharp-vscode#3979]
Comes from PowerShell repository.

New C# 9.0 pattern `if (o is not int x6) { }` is compiled well but reported as wrong CS8780 in VS Code.
See Roslyn test https://github.com/dotnet/roslyn/blob/06c2acecbc9771e8e0cf96d7cf07aa7d76dc7dac/src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs#L1953

![image](https://user-images.githubusercontent.com/22290914/90265090-81df8d80-de6b-11ea-98ea-b658b1bcc91a.png)

## Environment information ##

**VSCode version**: 1.48.0
**C# Extension**: 1.22.1

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.7.20366.15
 Commit:    6799b1b5ee

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\1\AppData\Local\Microsoft\dotnet\sdk\5.0.100-preview.7.20366.15\

Host (useful for support):
  Version: 5.0.0-preview.7.20364.11
  Commit:  53976d38b1

.NET SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015203 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.3.20216.6 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.7.20366.15 [C:\Users\1\AppData\Local\Microsoft\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.3.20215.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.7.20365.19 [C:\Users\1\AppData\Local\Microsoft\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.3.20214.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [C:\Users\1\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.3.20214.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.7.20366.1 [C:\Users\1\AppData\Local\Microsoft\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.22.1|
|gitlens|eamodio|10.2.2|
|powershell|ms-vscode|2020.6.0|
|vscode-markdownlint|DavidAnson|0.36.3|;

</details>

**Comment by filipw** [comment]
This should be resolved in 1.23.1 where we upgraded Roslyn and MSBuild to align with .NET 5 Preview 7. Feel free to reopen if you still encounter this.
