### ISSUE TITLE
The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.

### ISSUE THREAD

**Issue by armandjordaan-inovo** [OmniSharp/omnisharp-vscode#3980]
Hi,

I am using Ubuntu 18.04. After a recent update of Visual Studio Code I get: "The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.". How can I resolve this problem, as it prevents Omnisharp from loading the project file correctly.

**Comment by raaraya** [comment]
I had the same  issue, it seems that there is an update to omnisharp that this extension haven't yet publish or using. As a workaround I had to configure omnisharp to use the legacy SDK resolver. There should be a hidden folder on your HOME folder; named ".omnisharp", inside create or modify a file named omnisharp.json and include the following:

{
	"MSBuild": {
		"UseLegacySdkResolver": true
	}
}

This worked for me in the meantime the extension is updated to use the latest omnisharp.

**Comment by armandjordaan-inovo** [comment]
I see the problem was resolved in the latest update. Many thanks to the OmniSharrp team!
