### ISSUE TITLE
C# extension fails because it runs "dotnet", not "dotnet.exe"

### ISSUE THREAD

**Issue by BobSchnatt** [OmniSharp/omnisharp-vscode#3981]
## Issue Description ##
I can run the dotnet command from the built-in terminal in VS Code (Insiders) if I include the ".exe" extension on the end of it (i.e., "dotnet.exe --info"), but not if I leave the ".exe" extension off (i.e., "dotnet --info"). If I attempt the latter, I get the following error:

dotnet: Command not found

The C# extension fails because it's not including the ".exe" extension (and I'm assuming it shouldn't need to).

I have confirmed that I have a valid SDK installed (3.1.401). I get the same behavior from the WSL terminal (outside of VS Code), which is why I'm not sure if this is an OmniSharp problem or a WSL problem or whatnot...

## Steps to Reproduce ##
1) Put /mnt/c/Program File/dotnet in path (I did this in .bash_profile)
2) Close the WSL terminal and reopen it
3) Type "echo $PATH$" (the path is set up correctly)
4) run "code-insiders ." (minus the quotes) from the WSL terminal
## Expected Behavior ##
I expect VS Code (Insiders) to run, and for the extensions to load without error

## Actual Behavior ##
When the C# extension runs, I get the following error:
"The .NET Core SDK cannot be located. .NET Core debugging cannot be enabled. Make sure the .NET Core SDK is installed and is on the path"
### OmniSharp log ###
<details>Starting OmniSharp server at 8/14/2020, 6:39:43 PM
    Target: /home/bob

OmniSharp server started.
    Path: /home/bob/.vscode-server-insiders/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/run
    PID: 11663

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 18.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.4 - "/home/bob/.vscode-server-insiders/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/bob/.vscode-server-insiders/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "/home/bob/.vscode-server-insiders/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/bob/.vscode-server-insiders/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/bob/.vscode-server-insiders/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/bob/.vscode-server-insiders/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/bob'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/bob'
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
</details>

### C# log ###
<details>Failed to spawn 'dotnet --info'</details>

## Environment information ##

**VSCode version**: 1.49.0-insider
**C# Extension**: 1.22.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
A valid dotnet installation could not be found.</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|11.3.1|
|csharp|ms-dotnettools|1.22.1|
|githistory|donjayamanne|0.6.9|
|gitlens|eamodio|10.2.2|
|go|golang|0.16.1|
|js-debug-nightly|ms-vscode|2020.8.1317|
|LiveServer|ritwickdey|5.6.1|
|npm-intellisense|christian-kohler|1.3.0|
|rest-client|humao|0.24.1|
|vscode-eslint|dbaeumer|2.1.8|
|vscode-html-css|ecmel|0.2.3|
|vscode-npm-script|eg2|0.3.13|
|vscodeintellicode|VisualStudioExptTeam|1.2.10|;

</details>

**Comment by gregg-miskelly** [comment]
It sounds like you are using the Linux version of the extension but you want to use the Windows version of the .NET SDK?
If so what are you trying to accomplish? Do you want your code to run on Linux or on Windows?

**Comment by BobSchnatt** [comment]
> It sounds like you are using the Linux version of the extension but you want to use the Windows version of the .NET SDK?
> If so what are you trying to accomplish? Do you want your code to run on Linux or on Windows?

I'm attempting to use the Uno platform to code an app to target Web Assembly. I was following their instructions to set up VS Code for this when I ran into this problem.  The extension is installed on the WSL side, which, now that I'm thinking about it, might be wrong. Unfortunately, the Uno people just said (basically) "Install the C# and JavaScript Debugger (Nightly) extensions" but don't say where to install them.

Since I'm getting the error in the WSL terminal (typing "dotnet --info") even before starting VS Code, is there something misconfigured in WSL?  I'm afraid I know enough about Linux, WSL and VS Code to be dangerous ;)   Any help to direct me in the right direction would be appreciated...

**Comment by BobSchnatt** [comment]
Here's what I get from the WSL terminal to demonstrate...
![dotnet_dump](https://user-images.githubusercontent.com/33637106/90300256-9457c800-de67-11ea-8519-b036885906c0.png)

**Comment by gregg-miskelly** [comment]
So you will need to install the extension on the same platform as the .NET SDK and runtime. So if you want to run the extension through WSL, you need to install the Linux .NET SDK into your WSL distro. If you want to run the extension on Windows, then you want the .NET SDK on Windows.

**Comment by BobSchnatt** [comment]
> So you will need to install the extension on the same platform as the .NET SDK and runtime. So if you want to run the extension through WSL, you need to install the Linux .NET SDK into your WSL distro. If you want to run the extension on Windows, then you want the .NET SDK on Windows. Instructions to install .NET Core on Linux can be found here: https://docs.microsoft.com/en-us/dotnet/core/install/linux

Thanks. I'll take a look at that

**Comment by BobSchnatt** [comment]
I just found this, but it doesn't say anything about VS Code (and it's a bit dated):
https://platform.uno/blog/how-to-build-webassembly-c-apps-with-the-mono-aot-and-windows-subsystem-for-linux/

And this is the original guide I was trying to follow, but it doesn't say anything about WSL. Sigh. I'll dig a bit deeper.
https://platform.uno/docs/articles/get-started-vscode-wasm.html

Note to administrator: Can you keep this thread open for about a week? I'll probably follow up with a solution or further questions.  Thanks...

**Comment by BobSchnatt** [comment]
Interesting. When I restarted VS Code, the C# extension went through some additional gyrations (see below), but the problem remains. I have to type "dotnet.exe" to invoke it (and the C# extension doesn't).  I'll keep digging...
-----
Installing C# dependencies...
Platform: linux, x86_64, name=ubuntu, version=18.04

Downloading package 'OmniSharp for Linux (x64)' (46786 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Linux (x64)'

Downloading package '.NET Core Debugger (linux / x64)' (54671 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (linux / x64)'

Downloading package 'Razor Language Server (Linux / x64)' (52554 KB).................... Done!
Installing package 'Razor Language Server (Linux / x64)'

Finished

Failed to spawn 'dotnet --info'

**Comment by BobSchnatt** [comment]
Ok, I resolved the error by installing .NET Core 3.1 directly in / on WSL (Ubuntu).  Gregg, I followed the link you provided to this one ==> https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu, and it worked.

Thank you!
