### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by SluttySlug77** [OmniSharp/omnisharp-vscode#3983]
## Expected  behavior
For intellesense to work.

## Actual behavior
Intellesense not working, there are no errors or anything, I tried using an older version of the c# extension but it still doesnt work.I dont know what is stopping it from working because it was working properly this morning and then randomly stopped.

**Comment by JoeRobich** [comment]
@SluttySlug77 Can you please share the OmniSharp Log from the Output pane?

**Comment by SluttySlug77** [comment]
Starting OmniSharp server at 16/08/2020, 20:09:54
    Target: c:\Users\mishk\shooter\shooter.sln

OmniSharp server started.
    Path: c:\Users\mishk\.vscode\extensions\ms-dotnettools.csharp-1.23.0\.omnisharp\1.36.1\OmniSharp.exe
    PID: 9440

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2019 16.7.30406.217 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
            2: StandAlone 16.8.0 - "c:\Users\mishk\.vscode\extensions\ms-dotnettools.csharp-1.23.0\.omnisharp\1.36.1\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2019 16.7.30406.217 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\mishk\shooter'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\mishk\shooter\shooter.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\shooter\UnityEngine.TestRunner.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\shooter\UnityEngine.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\shooter\Unity.TextMeshPro.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\shooter\Unity.Timeline.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\shooter\Unity.TextMeshPro.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\shooter\Unity.Timeline.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\shooter\UnityEditor.TestRunner.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\shooter\UnityEditor.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\shooter\Unity.Rider.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\shooter\Unity.CollabProxy.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\mishk\shooter\Unity.VSCode.Editor.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\mishk\shooter'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\shooter\UnityEngine.TestRunner.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\mishk\shooter' on host 13256.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\shooter\UnityEngine.TestRunner.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\shooter\UnityEngine.TestRunner.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\shooter\UnityEngine.UI.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\shooter\UnityEngine.UI.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\shooter\UnityEngine.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\shooter\Unity.TextMeshPro.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\shooter\Unity.TextMeshPro.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\shooter\Unity.TextMeshPro.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\shooter\Unity.Timeline.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\shooter\Unity.Timeline.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\shooter\Unity.Timeline.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\shooter\Unity.TextMeshPro.Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\shooter\Unity.TextMeshPro.Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\shooter\Unity.TextMeshPro.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\shooter\Unity.Timeline.Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\shooter\Unity.Timeline.Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\shooter\Unity.Timeline.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\shooter\UnityEditor.TestRunner.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\shooter\UnityEditor.TestRunner.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\shooter\UnityEditor.TestRunner.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\shooter\UnityEditor.UI.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\shooter\UnityEditor.UI.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\shooter\UnityEditor.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\shooter\Unity.Rider.Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\shooter\Unity.Rider.Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\shooter\Unity.Rider.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\shooter\Unity.CollabProxy.Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\shooter\Unity.CollabProxy.Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\shooter\Unity.CollabProxy.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\mishk\shooter\Unity.VSCode.Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\mishk\shooter\Unity.VSCode.Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\mishk\shooter\Unity.VSCode.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: UnityEngine.TestRunner
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: UnityEngine.UI
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.TextMeshPro
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.Timeline
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.TextMeshPro.Editor
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.Timeline.Editor
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: UnityEditor.TestRunner
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: UnityEditor.UI
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.Rider.Editor
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.CollabProxy.Editor
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.VSCode.Editor

**Comment by SluttySlug77** [comment]
Dont know how or why but my intellesense is working again.
