### ISSUE TITLE
silent warning in .editorconfig is not working

### ISSUE THREAD

**Issue by duongphuhiep** [OmniSharp/omnisharp-vscode#3991]
Issue Type: <b>Bug</b>

Here is the .editor.config (which works in Visual Studio)

```
[*.cs]
# CS1591: Missing XML comment for publicly visible type or member
dotnet_diagnostic.CS1591.severity = silent
```

but I can't get rid of these warnings in the Visual Studio Code

Extension version: 1.23.0
VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.61GB (6.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by filipw** [comment]
did you enable editorconfig support? it's off by default https://www.strathweb.com/2019/07/editorconfig-support-in-omnisharp-and-c-extension-vs-code/

**Comment by duongphuhiep** [comment]
thanks, 

the option works! (I didn't know it is there)
