### ISSUE TITLE
Standard namespaces/classes/types are not found anymore

### ISSUE THREAD

**Issue by bkragl** [OmniSharp/omnisharp-vscode#4003]
## Issue Description ##

After an upgrade of the .NET Core SDK package on Ubuntu, VS Code shows many errors for standard namespaces and classes, like `System`, `System.Object`, etc.

Exactly the same happens on my Ubuntu 18.04 machine (where the logs below come from), and another Ubuntu 16.04 machine I have.

## Steps to Reproduce ##
```
dotnet new console --name Test
code Test/
```

## Expected Behavior ##

VS Code opens the C# project without any errors.

## Actual Behavior ##

VS Code shows many errors, like:
```
The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [Test]
Predefined type 'System.Object' is not defined or imported [Test]
'object' does not contain a constructor that takes 0 arguments [Test]
...
```

See screenshot:
![Screenshot](https://user-images.githubusercontent.com/6729391/90640158-ed40ab00-e22f-11ea-95bb-0a79e9397766.png)

**Note:** `dotnet run` on the command line works fine.

### OmniSharp log ###
```
Starting OmniSharp server at 8/19/2020, 3:00:02 PM
    Target: /home/bkragl/Code/Test

OmniSharp server started with Mono 6.10.0.
    Path: /home/bkragl/.vscode/extensions/ms-dotnettools.csharp-1.23.0/.omnisharp/1.36.1/omnisharp/OmniSharp.exe
    PID: 31238

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 18.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.8.0 - "/usr/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.8.0 - "/home/bkragl/.vscode/extensions/ms-dotnettools.csharp-1.23.0/.omnisharp/1.36.1/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.8.0 - "/usr/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /home/bkragl/.vscode/extensions/ms-dotnettools.csharp-1.23.0/.omnisharp/1.36.1/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/bkragl/Code/Test'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/bkragl/Code/Test'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/bkragl/Code/Test/Test.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/bkragl/Code/Test'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/bkragl/Code/Test' on host 31126.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/bkragl/Code/Test/Test.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/bkragl/Code/Test/Test.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/bkragl/Code/Test/Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Test
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        Test: Did not find 'Microsoft.NETCore.App' in lock file.
```

### C# log ###
Empty

## Environment information ##

**VSCode version**: 1.48.0
**C# Extension**: 1.23.0

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.10.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    39d17847db

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.401/

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]
  3.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.29.0|
|csharp|ms-dotnettools|1.23.0|
|latex-workshop|James-Yu|8.11.1|
|python|ms-python|2020.8.101144|
|selectline-statusbar|tomoki1207|0.0.2|;

</details>

**Comment by kidtsunami** [comment]
I'm experiencing this as well with the exact same logs/results.

**Comment by filipw** [comment]
Please check on 1.23.1 which was released yesterday. I believe it should be resolved there

**Comment by bkragl** [comment]
> Please check on 1.23.1 which was released yesterday. I believe it should be resolved there

Yes, the problem seems to be resolved. Thanks!
