### ISSUE TITLE
Fix spelling for supressBuildAssetsNotification in Preferences

### ISSUE THREAD

**Issue by pieandcakes** [OmniSharp/omnisharp-vscode#4004]
Fix spelling for supressBuildAssetsNotification in Preferences
![image](https://user-images.githubusercontent.com/17558378/90663794-f8c7ae00-e1fe-11ea-8b10-677de4744275.png)

#3941 Fixes the handling but its still wrong in package.json

**Comment by filipw** [comment]
yes indeed.. 😫
