### ISSUE TITLE
" Insert Space After Opening And Before Closing Nonempty *" nonfunctional.

### ISSUE THREAD

**Issue by JonathanDotCel** [OmniSharp/omnisharp-vscode#4006]
## Issue Description ##

"Insert Space After Opening And Before Closing Nonempty Parenthesis"
This family of settings works fine on e.g. .JS files, but appears to be ignored even with omnisharp set to inherit editor settings.

Any workaround here?
Thanks, J

## Steps to Reproduce ##
DoSomething(a,b,c);
Ctrl+K,F

## Expected Behavior ##
DoSomething( a, b, c );

## Actual Behavior ##
DoSomething(a,b,c);

## Logs ##
works for .js
didn't work before or after "spaces in braces" extension, so that's not interfering.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.48.0
**C# Extension**: 1.23.1

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-header|DanielLin|1.0.1|
|cpptools|ms-vscode|0.29.0|
|csharp|ms-dotnettools|1.23.1|
|csharpfixformat|Leopotam|0.0.84|
|debug|webfreak|0.25.0|
|format-all-files|xykong|0.2.0|
|logcat|abhiagr|0.0.7|
|mips|kdarkhan|0.0.5|
|remote-wsl|ms-vscode-remote|0.44.4|
|spaces-inside-braces|AiryShift|0.4.0|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-debug|Unity|2.7.5|
|unity-tools|Tobiah|1.2.3|
|unityrefactor|blep|0.0.4|
|vscode-browser-preview|auchenberg|0.6.7|;

</details>

**Comment by filipw** [comment]
Omnisharp has its own formatting settings https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#formatting-options

Also, you can use editorconfig - https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019

**Comment by JonathanDotCel** [comment]
> Omnisharp has its own formatting settings https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#formatting-options
> 
> Also, you can use editorconfig - https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019

Hi,yeah I've tried 
c:\Users\Amber\.omnisharp\omnisharp.json

with the following:
{
    "FormattingOptions": {
      "SpaceWithinMethodDeclarationParenthesis": false,
      "SpaceWithinMethodCallParentheses": false,
      "SpaceWithinExpressionParentheses": false,
      "SpaceWithinOtherParentheses": false,
      "SpaceWithinSquareBrackets": false      
    }
  }

I also tried 

"omnisharp.path": "C:/Users/Amber/.omnisharp/omnisharp.json"
and
"omnisharp.path": "C://Users//Amber//.omnisharp//omnisharp.json"
in the settings.json

Both seem to work (as messing up leaves a message to that effect in the output panel).

Neither fixes formatting.
Additionally, when applying the settings to the settings.json, it attempts to open visual studio proper.
What on earth is going on there? 

It's also never made clear what's happening here:
https://i.imgur.com/l570pVR.png

Will it use the omnisharp settings *in addition* to the basic editor settings, or completely default to the order specified here?
https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#formatting-options

E.g. if I check "Use Editor Formatting Settings"
...Ctrl+K,F a chunk of text.
...And the parens(formatting,fails);
Is that omnisharp doing the formatting? partial formatting? or is that all on VSCode's end?

It's not made explicitly clear,
Thanks,
J

**Comment by filipw** [comment]
`Use Editor Formatting Settings` only inherits indent size and tabs/spaces from VS Code. Everything else is controlled via `omnisharp.json` or editorconfig.

`"omnisharp.path"` is a setting for the path to the Omnisharp server executable, it has nothing to do with `omnisharp.json` settings file. you should not set it `omnisharp.json` as nothing would work then.

just place `omnisharp.json` in `%USERPROFILE%/.omnisharp/` or in the working directory which was opened in VS Code and it gets picked up automatically.

**Comment by JonathanDotCel** [comment]
Edit:


> `Use Editor Formatting Settings` only inherits indent size and tabs/spaces from VS Code. Everything else is controlled via `omnisharp.json` or editorconfig.
Could this be made clear?
There's no indication that it inherits *some* settings.
Thannks.

> 
> `"omnisharp.path"` is a setting for the path to the Omnisharp server executable, it has nothing to do with `omnisharp.json` settings file. you should not set it `omnisharp.json` as nothing would work then.
> 
That's not made terribly clear either.
omnisharp.executablePath?
omnisharp.workingDirectory?
something like that would make sense.

> just place `omnisharp.json` in `%USERPROFILE%/.omnisharp/` or in the working directory which was opened in VS Code and it gets picked up automatically.

No joy with this either, even after
 - removing the the above issue
 - toggling ""omnisharp.useEditorFormattingSettings": false" on/off and restarting
 - and letting omnisharp rebuild + cache each time
 - in a .CS file where formatting and intellisense is otherwise functional

Still converting Thing( a ); to Thing(a);

The relevant javascript version are also set to true:
https://i.imgur.com/sHJogm9.png

Any ideas?

Thanks,
J

**Comment by JonathanDotCel** [comment]
> just place `omnisharp.json` in `%USERPROFILE%/.omnisharp/` or in the working directory which was opened in VS Code and it gets picked up automatically.

Hi, please excuse the double post, but I'd prefer to keep it as a record of my thought process and patterns while trying to work this out, should it be useful for anyone else with similar issues or trying to reduce confusion.

It is working now though, thanks for your help.

Might I suggest a slight edit for this part?
https://imgur.com/l570pVR

```
"Omnisharp: Use Editor Formatting Settings
[ ] Specifies whether OmniSharp should use VS Code's editor settings for "use of tabs" & "indentation size" when formatting C#.
Other formatting operations will be handled by OmniSharp's own settings.
Documentation for those may be found here: https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#formatting-options
```

Thanks again for your time,
J

**Comment by filipw** [comment]
yes, good idea, that would make it more obvious - sorry for your trouble.

cc @JoeRobich looks like we can make the description a bit more... descriptive 😄
