### ISSUE TITLE
Intellisense no longer working with Unity projects

### ISSUE THREAD

**Issue by andymads** [OmniSharp/omnisharp-vscode#4015]
## Issue Description ##

Intellisense has stopped working on my Unity projects. It was ok last week. I now get the error message popup in the bottom right about how projects could not be loaded. I've tried deleting my project files and downgrading all the way down to Visual Studio Code Editor package 1.1.3 but no success. Problem occurs on every project I've tried so far today.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.48.1
**C# Extension**: 1.23.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.2.104 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.9.2|
|binary-plist|dnicolson|0.4.0|
|csharp|ms-dotnettools|1.23.1|
|playfab-explorer|Playfab|0.1.11|
|quicktype|quicktype|12.0.46|
|syntax-project-pbxproj|mariomatheu|0.1.3|
|unity-debug|Unity|2.7.5|
|vscode-azurefunctions|ms-azuretools|0.23.0|;

</details>

**Comment by JasonRTBond** [comment]
Can confirm. Version 1.23.1 no longer works on my system, very similar to that above. Error list begins thusly:
`[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks`

It then proceeds to fail at loading all of the csprojs in the solution.

Work-around: Downgrade to 1.23.0.

Additional note: This is like the third time something similar has happened on an automatic update to this plugin. Is there something automated tests are skipping? Perhaps they are not complete for Mac?

**Comment by andymads** [comment]
> Work-around: Downgrade to 1.23.0.

@JasonRTBond how do you downgrade?

**Comment by JasonRTBond** [comment]
When looking at the extensions list, use the little gear next to the C# extension.

<img width="530" alt="Screen Shot 2020-08-24 at 13 00 23" src="https://user-images.githubusercontent.com/2727461/91073933-d1f7e600-e609-11ea-8712-2e5f98569908.png">

**Comment by filipw** [comment]
I will close this as a duplicate 
see https://github.com/OmniSharp/omnisharp-vscode/issues/4007#issuecomment-677405332 for discussion ans a workaround 

thanks
