### ISSUE TITLE
Errors/Warnings popup and underlines get "stuck" while making changes

### ISSUE THREAD

**Issue by eamodio** [OmniSharp/omnisharp-vscode#402]
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

VS Code version:

```
Version 1.2.0-insider (1.2.0-insider)
7ccb21d7e7256a7d42f3dda8b2d3721b8e59724f
```

C# Extension version:

```
1.1.2 (pulled from https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.1.2)
```
## Steps to reproduce

I don't have any great steps to repro - but this happens to me extremely often. I can start with 0 errors via omnisharp and actual build, then start coding/refactoring and as expected errors will come and go but at some point (and it usually doesn't take that long) the errors will get stuck even when they no longer exist. Sometimes I can still have omnisharp report 100s of errors on a working build. If I use the project selector in the bottom right to "kick" things it will fix it.

Please let me know if there is any other information I can provide. I experienced the same issue with the "released" version of the C# extension and tried the preview one to see if it helped any (it didn't)
## Expected  behavior

Errors come and go as they truly exist
## Actual behavior

Errors get stuck

**Comment by eamodio** [comment]
With the latest VSCode (insiders) and 1.1.5 of the C# extension, I am still seeing behavior - Errors will persist in the list until clicked on manually. FWIW, I have seen a similar issue in VS 2015 as well.

Also with the latest version of VSCode moving the errors/warnings to a panel (which is much nicer) I am see UI lagging once that panel is open -- it isn't nearly as severe as a few nightlies ago, but it is still an issue.

**Comment by DustinCampbell** [comment]
@eamodio: I'm betting this is working now. Is it?

**Comment by eamodio** [comment]
@DustinCampbell yup this looks good now. Closing...
