### ISSUE TITLE
Incorrect error reports

### ISSUE THREAD

**Issue by RussKie** [OmniSharp/omnisharp-vscode#4027]
## Issue Description ##

OmniSharp incorrectly reports errors, and fails builds despite suppressions.

## Steps to Reproduce ##

1. Clone https://github.com/dotnet/winforms/
2. Update global.json replacing "5.0.100-preview.6.20310.4" with "5.0.100-preview.8.20417.9"
3. Run `start-code.cmd`
3. Run `build.cmd`
4. Observe build failing with several errors like this:
    ```
    C:\Development\winforms\src\System.Windows.Forms\src\System\Resources\ResXDataNode.cs(355,25): error CS0618: 'IFormatter.Serialize(Stream, object)' is obsolete:
    'BinaryFormatter serialization is obsolete and should not be used. See https://aka.ms/binaryformatter for more information.' [C:\Development\winforms\src\System.Windows.Forms\src\System.Windows.Forms.csproj]
    ```
5. Run `start-vs.cmd` and build the solution in VS
6. Observe different output:
    ```
    5>C:\Development\winforms\src\System.Windows.Forms\src\System\Resources\ResXDataNode.cs(355,25,355,62): warning SYSLIB0011: 'IFormatter.Serialize(Stream, object)' is obsolete:
    'BinaryFormatter serialization is obsolete and should not be used. See https://aka.ms/binaryformatter for more information.'
    ```

Also CS0618 is suppressed so it mustn't be reported as error, and thus fail the build:
https://github.com/dotnet/winforms/blob/e5d66e46fdb14e1ebecdd3d70d7f7b04bb221ad6/src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs#L352-L358

## Expected Behavior ##

1. Correct output is reported as per https://aka.ms/binaryformatter#alternative-resolution-suppressing-the-warning, the same as emitted by VS
2. Build mustn't fail, the warning must be correctly reported as such, not as an error. The suppression must be correctly observed.

### OmniSharp log ###
<details>

Starting OmniSharp server at 31/08/2020, 8:03:59 pm
    Target: c:\Development\winforms\Winforms.sln

OmniSharp server started.
    Path: c:\Users\igveliko\.vscode\extensions\ms-dotnettools.csharp-1.23.1\.omnisharp\1.37.0\OmniSharp.exe
    PID: 30712

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 3 MSBuild instance(s)
            1: Visual Studio Enterprise 2019 16.8.30428.280 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin"
            2: Visual Studio Professional 2019 16.7.30406.217 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"
            3: StandAlone 16.8.0 - "c:\Users\igveliko\.vscode\extensions\ms-dotnettools.csharp-1.23.1\.omnisharp\1.37.0\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Enterprise 2019 16.8.30428.280 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin"

</details>

### C# log ###
<details> N/A </details>

## Environment information ##

**VSCode version**: 1.47.2
**C# Extension**: 1.23.1

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.6.20310.4
 Commit:    16d29b9349

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Development\winforms\.dotnet\sdk\5.0.100-preview.6.20310.4\

Host (useful for support):
  Version: 6.0.0-alpha.1.20428.2
  Commit:  e6b9b48f34

.NET SDKs installed:
  5.0.100-alpha1-013788 [C:\Development\winforms\.dotnet\sdk]
  5.0.100-alpha1-015536 [C:\Development\winforms\.dotnet\sdk]
  5.0.100-preview.4.20202.8 [C:\Development\winforms\.dotnet\sdk]
  5.0.100-preview.5.20251.2 [C:\Development\winforms\.dotnet\sdk]
  5.0.100-preview.6.20266.3 [C:\Development\winforms\.dotnet\sdk]
  5.0.100-preview.6.20310.4 [C:\Development\winforms\.dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-alpha1.19415.8 [C:\Development\winforms\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-alpha1.19531.6 [C:\Development\winforms\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.3.20170.2 [C:\Development\winforms\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.5.20228.19 [C:\Development\winforms\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.6.20266.2 [C:\Development\winforms\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.6.20309.8 [C:\Development\winforms\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-alpha.1.19530.10 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-alpha.1.19551.1 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-alpha.1.19559.5 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-alpha.1.19561.10 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-alpha.1.19562.8 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-alpha.1.19564.1 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-alpha1.19415.3 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-alpha1.19514.1 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-alpha1.19526.2 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.3.20169.1 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.4.20205.13 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.4.20210.10 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.4.20213.10 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.4.20215.6 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.4.20216.4 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.4.20218.3 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.4.20220.15 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20226.4 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20226.8 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20228.3 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20229.5 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20230.9 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20253.6 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20253.7 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20259.5 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20260.5 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20261.9 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20262.14 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20263.7 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20264.1 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20270.12 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20271.10 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20280.5 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20281.6 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20305.6 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20302.1 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20303.1 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20303.11 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20306.3 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20307.4 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20308.8 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20311.2 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20318.2 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20320.5 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20325.1 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20328.6 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20352.6 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20357.14 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20358.9 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20363.2 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20370.4 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20371.13 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20380.1 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20401.1 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20405.17 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20415.1 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20416.7 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20417.14 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20423.4 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20423.8 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20427.12 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-alpha.1.20420.3 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-alpha.1.20428.2 [C:\Development\winforms\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-alpha1.19415.3 [C:\Development\winforms\.dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-alpha1.19551.2 [C:\Development\winforms\.dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.4.20180.8 [C:\Development\winforms\.dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.5.20227.2 [C:\Development\winforms\.dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.6.20265.2 [C:\Development\winforms\.dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.6.20308.1 [C:\Development\winforms\.dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.1|
|dotnet-test-explorer|formulahendry|0.7.4|
|powershell|ms-vscode|2020.6.0|
|prettier-plus|svipas|4.2.2|
|quick-html-previewer|daiyy|1.0.1|;

</details>

**Comment by filipw** [comment]
can you set `"omnisharp.loggingLevel":"debug"` and post the full output?

I am unable to reproduce this problem, this is what I see:
<img width="1255" alt="Bildschirmfoto 2020-08-31 um 14 46 50" src="https://user-images.githubusercontent.com/1710369/91721334-e05d7900-eb98-11ea-88d5-371b912d462a.png">

**Comment by RussKie** [comment]
Thank you @filipw. How bizarre, I have never seen the "Problems" tab to show these.

Anyway it looks like my dev box may be messed up, as I'm now getting the same issue building outside VS Code.
Closing now, I will re-open if I get more info that point to OmniSharp specifically.
