### ISSUE TITLE
Code Completion in xml comments

### ISSUE THREAD

**Issue by osterhoutan** [OmniSharp/omnisharp-vscode#4034]
XML tag Code Completion in XML Comments
===============================
_**Feature Request!**_
 
Add some code completion/intellisense for the supported XML tags inside of the `///` comment blocks.
Hopefully also in other multi-line comment blocks the C# compiler recognizes as valid a XML documentation comment block
_([supported comment blocks according to the documentation](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/delimiters-for-documentation-tags))_, but with the variability in what those can be & the infrequent usage they get I can understand skipping out on those.

Right now the intellisense only comes up with suggestions when in a `cref=".."` attribute or the like when you start typing out the name of a namespace/class/method/attribute/_etc._.

In fact the default code user-snippets in vscode seem to be disabled when in a comment line all together, which is odd since most language extensions still allow for user defined snippets to work in comments, but it's all in the implementation I suppose.

 I have yet to see a request for this, the closest being: #8 .

**Comment by 333fred** [comment]
This should already be implemented and fixed when the next version of the extension is published. For example, [this](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/tests/OmniSharp.Roslyn.CSharp.Tests/CompletionFacts.cs#L1012) test shows what will be available.

**Comment by 333fred** [comment]
This is what it will look like:
![image](https://user-images.githubusercontent.com/2371880/92037726-0f095a00-ed27-11ea-929a-cc625792be63.png)

You can try it out by installing the beta version of the extension and setting your omnisharp-path to latest: https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases

**Comment by ygoe** [comment]
Has this been released by now? It's still not there.

**Comment by 333fred** [comment]
Yes, this was released several years ago.

**Comment by ygoe** [comment]
Okay, so I'll have to create a new bug for this as it somehow got lost again.

**Comment by davidcorbin-atmosera** [comment]
Followup Question [this seems a place to anchor it... if it is already done, and I just mussed it in my search, perhaps an answer here will help others.... If not, then I can certainly create and appropriate issue...

If there any way for CoPilot to detect INCORRECT XML code comments... For example..

1. Create a Property with Getter; Setter;
2. Generate XML Doc Comments
3. Remove the Setter.

The summary comment is now wrong...
