### ISSUE TITLE
Debugger sometimes shows incorrect values with structs

### ISSUE THREAD

**Issue by eamodio** [OmniSharp/omnisharp-vscode#404]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```
VS Code version:
```
Version 1.2.0-insider (1.2.0-insider)
7ccb21d7e7256a7d42f3dda8b2d3721b8e59724f
```
C# Extension version:
```
1.1.2 (pulled from https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.1.2)
```
## Steps to reproduce

I don't have this boiled down to a reproducible sample, but in the involved case I have it happens 100% of the time on OS X (I've tried on Windows and it works fine).

Basically in my scenario I had a `Dictionary<Guid, MyStruct>` and my struct has a `Guid`, an a couple if `int`s. While debugging I was inspecting things in the dictionary and one of the `int`s was consistently wrong (it was a huge number rather than between 1-3 which was the data I was testing with). This persisted even after restarts etc. I believe this was a debugging only issue, but I'm not 100% sure.

Please let me know if there is any other information I can provide.

## Expected  behavior

Struct `int`s should contain the proper value

## Actual behavior

Struct `int`s show a seemingly random large number

**Comment by chuckries** [comment]
Thank you for reporting this issue. I tried to repro it based on your description. Here is my code:
```C#
using System;
using System.Collections.Generic;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Dictionary<Guid, MyStruct> dictionary = new Dictionary<Guid, MyStruct>();

            Random random = new Random();
            foreach (var item in new MyStruct[] {
                new MyStruct(Guid.NewGuid(), random.Next(1, 4), random.Next(1, 4), random.Next(1, 4)),
                new MyStruct(Guid.NewGuid(), random.Next(1, 4), random.Next(1, 4), random.Next(1, 4)),
                new MyStruct(Guid.NewGuid(), random.Next(1, 4), random.Next(1, 4), random.Next(1, 4))
            })
            {
                dictionary.Add(Guid.NewGuid(), item);
            }

            System.Diagnostics.Debugger.Break();
        }
    }

    public struct MyStruct
    {
        public Guid Guid;
        public int Int1;
        public int Int2;
        public int Int3;

        public MyStruct(Guid guid, int int1, int int2, int int3)
        {
            Guid = guid;
            Int1 = int1;
            Int2 = int2;
            Int3 = int3;
        }
    }
}
```

None of my variables are appearing strangely.
![image](https://cloud.githubusercontent.com/assets/6598594/15813352/1ccbdb88-2b73-11e6-96e3-3e66c2b3b976.png)

Are there any obvious differences between my repro code and your code? I have the same environment as you.

**Comment by chuckries** [comment]
@eamodio are you still able to reproduce this with our latest release (1.1.5)?

**Comment by eamodio** [comment]
@chuckries I can't seem to repro it with the latest -- though our project is going through major refactors and updates, so I can't say it is 100% because of the updated release.

**Comment by chuckries** [comment]
Thanks! I'm going to close this for now, please reopen if you come across this issue again.
