### ISSUE TITLE
Documentation output missing sections, lacking formatting, lacking newlines.

### ISSUE THREAD

**Issue by erichiller** [OmniSharp/omnisharp-vscode#4040]
## Issue Description ##
Documentation output for my own code is lacking sections and formatting, I've tried in several different (new) projects and it always only shows the `summary` block and never properly formats newlines. I thought this was just a long standing bug that everyone experienced, but after looking through some issues, I saw that many others seem to have much more detailed and well formatted output. Is my output the expected documentation output?

## Steps to Reproduce ##
Create any documentation.

## Expected Behavior ##
Something like https://github.com/OmniSharp/omnisharp-vscode/pull/1918#issuecomment-350863070

## Actual Behavior ##
![image](https://user-images.githubusercontent.com/5379325/92292482-a9f66580-eeda-11ea-8046-5253c1a70795.png)

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.48.2
**C# Extension**: 1.23.2

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    39d17847db

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.401\

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|better-align|wwm|1.1.6|
|csharp|ms-dotnettools|1.23.2|
|docomment|k--kato|0.1.18|
|errorlens|usernamehw|3.2.1|
|gitignore|codezombiech|0.6.0|
|graphql-for-vscode|kumar-harsh|1.15.3|
|hexeditor|ms-vscode|1.2.1|
|jsdoc-markdown-highlighting|bierner|0.0.1|
|markdown-all-in-one|yzhang|3.3.0|
|msbuild-project-tools|tintoy|0.3.8|
|path-intellisense|christian-kohler|2.2.1|
|powershell-preview|ms-vscode|2020.7.0|
|rainbow-csv|mechatroner|1.7.1|
|remote-ssh-edit|ms-vscode-remote|0.51.0|
|selected-lines-count|gurumukhi|1.4.0|
|sqltools|mtxr|0.23.0|
|svg|jock|1.3.9|
|theme-karyfoundation-themes|karyfoundation|20.0.3|
|todo-tree|Gruntfuggly|0.0.178|
|vscode-docker|ms-azuretools|1.5.0|
|vscode-eslint|dbaeumer|2.1.8|
|vscode-great-icons|emmanuelbeziat|2.1.52|
|vscode-json5|mrmlnc|1.0.0|
|vscode-scss|mrmlnc|0.9.0|
|vscode-scss-formatter|sibiraj-s|2.0.2|
|vscode-solution-explorer|fernandoescolar|0.3.11|
|vscode-yaml|redhat|0.10.1|;

</details>

**Comment by jmarolf** [comment]
@333fred do you think this is related to the changes you made recently?

**Comment by 333fred** [comment]
It's likely related. The formatting I implemented was best-effort, I have no doubt there is room for improvement in the tagged-text->markdown implementation.

**Comment by 333fred** [comment]
In particular, the issues with the newlines are a translation issue: VSCode uses markdown to render the documentation, and single newlines in markdown do not actually signal the start of a new line. There's no particularly great solution here: inserting an extra newline in the text during translation will often end up looking terrible itself, as it introduces a large amount of whitespace inbetween each line. The reason line 5 isn't . As to parameters being displayed in quickinfo, this is not what VS does, as Dustin [showed](https://github.com/OmniSharp/omnisharp-vscode/pull/1918#issuecomment-351114109). The hover implementation in omnisharp now just calls into roslyn, so if you want parameter info to be displayed that would need to be a roslyn feature request, not an omnisharp feature request.

**Comment by 333fred** [comment]
And actually, it looks like the newline thing is a roslyn issue as well. This is what VS shows for newlines in doc comments:
![image](https://user-images.githubusercontent.com/2371880/94646122-6b1dba80-02a2-11eb-9cc2-91cb26ea1d76.png)

**Comment by gregg-miskelly** [comment]
This is not my area of expertise, but I think this is "by design". If you want line breaks, you need to use `<para>`. Example:

```C#
        /// <summary>
        /// Line1
        /// <para>Line2</para>
        /// </summary>
```

**Comment by erichiller** [comment]
To add to the markdown double newline required to output a single newline, there is an alternative - [double space at the end of the line](https://spec.commonmark.org/0.29/#hard-line-breaks). So that would be a more aesthetically pleasing option. VSCode obeys this rule, so a simple solution to newlines could be replace all `<content>\r?\n` with `<content>  \n`.

The second part of the issue, outside of lacking newlines, is that there are no section headings as I've seen in past issues/comments ( https://github.com/OmniSharp/omnisharp-vscode/pull/1918#issuecomment-350863070 and https://github.com/OmniSharp/omnisharp-vscode/issues/1057#issue-196350833 )

**Comment by erichiller** [comment]
I see now (I'm not sure if it was like this in prior versions), that when completing the parameters for a function, the output is displayed "correctly" with line breaks, and the parameter list.
![image](https://user-images.githubusercontent.com/5379325/97801985-a7c03700-1bfd-11eb-8072-7a00f1e2b6b2.png)

When mousing over the method however (or Ctrl+space):
![image](https://user-images.githubusercontent.com/5379325/97802002-c292ab80-1bfd-11eb-868c-f3f51d4efb98.png)

Here is the actual comment/code doc:
![image](https://user-images.githubusercontent.com/5379325/97802018-d6d6a880-1bfd-11eb-9242-21626db9f09c.png)

**Comment by 333fred** [comment]
As mentioned, the latter behavior is the correct behavior. Omnisharp now uses roslyn's built-in handling for quick info. In xml comments in general, if you want a newline you should use a `para` tag.
