### ISSUE TITLE
When debugging non-C# projects, this plugin updates before the proper debugging begins

### ISSUE THREAD

**Issue by coreyog** [OmniSharp/omnisharp-vscode#4044]
## Issue Description ##
When I debug most other languages, this plugin decides it's a fine time to update.

## Steps to Reproduce ##
1. Have out of date stuff for this plugin.
1. Have a project where there's no C#, happens a lot with Go for me.
1. Press F5 (without a launch.json), read C#'s logs as what you actually wanted to do is put on hold...

## Expected Behavior ##
I debug Go. I can't believe I'm submitting this issue.

## Actual Behavior ##
Go is put on hold while OmniSharp downloads 35MB + 42MB + 50MB of things I couldn't care less about.

## Logs ##
Empty

### OmniSharp log ###
Empty

### C# log ###
<details>
Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (35884 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'

Downloading package '.NET Core Debugger (Windows / x64)' (42010 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (Windows / x64)'

Downloading package 'Razor Language Server (Windows / x64)' (50489 KB).................... Done!
Installing package 'Razor Language Server (Windows / x64)'

Finished
</details>

## Environment information ##

**VSCode version**: 1.48.2
**C# Extension**: 1.23.2

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer-2|CoenraadS|0.2.0|
|csharp|ms-dotnettools|1.23.2|
|debugger-for-chrome|msjsdiag|4.12.10|
|EditorConfig|EditorConfig|0.15.1|
|gitlens|eamodio|10.2.2|
|go|golang|0.16.2|
|hexeditor|ms-vscode|1.2.1|
|jq-preview|ldd-vs-code|0.4.1|
|markdown-extended|jebbs|1.0.17|
|remote-wsl|ms-vscode-remote|0.44.5|
|rewrap|stkb|1.13.0|
|sqltools|mtxr|0.23.0|
|sqltools-driver-pg|mtxr|0.2.0|
|todo-tree|Gruntfuggly|0.0.178|
|trailing-spaces|shardulm94|0.3.1|
|unity-debug|Unity|2.7.5|
|vscode-docker|ms-azuretools|1.5.0|
|vscode-icons|vscode-icons-team|10.2.0|
|vscode-proto3|zxh404|0.4.2|;

</details>

**Comment by gregg-miskelly** [comment]
Unfortunately with the current design of extension deployment in VS Code, there is no good way to avoid this. Hopefully some day we will have microsoft/vscode#23251 and the issue will get fixed.

**Comment by coreyog** [comment]
I'm going to uninstall until the extension respects my time.
