### ISSUE TITLE
Nullability warning

### ISSUE THREAD

**Issue by JeroenBos** [OmniSharp/omnisharp-vscode#4048]
## Issue Description ##
vscode gives a nullability warning whereas `dotnet build` does not.

## Steps to Reproduce ##
Create two files in an empty folder:
Insert into `Program.cs`:
```csharp
#nullable enable
using System.Collections.Generic;
using System.Linq;
class Program
{
	public static void Main(string[] args)
	{
		IDictionary<string, object?> dict = default!; // imagine some value	 
		IEnumerable<(string, object?)>? x = dict?.Select(pair => (pair.Key, pair.Value));
	}
}
```
The csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
```

Navigate to that folder.
Do a `dotnet build` and observe no warning there. But when program.cs is opened in vscode, a warning is issued.

## Expected Behavior ##
No warning in vscode.

## Actual Behavior ##

A warning is observed: 
`Nullability of reference types in value of type 'IEnumerable<(string Key, object Value)>' doesn't match target type 'IEnumerable<(string, object?)>'.`

<details>
json
{
	"resource": "/home/jeroen/git/null/Program.cs",
	"owner": "csharp",
	"code": "CS8619",
	"severity": 4,
	"message": "Nullability of reference types in value of type 'IEnumerable<(string Key, object Value)>' doesn't match target type 'IEnumerable<(string, object?)>'. [null]",
	"source": "csharp",
	"startLineNumber": 9,
	"startColumn": 39,
	"endLineNumber": 9,
	"endColumn": 83
}

</details>

### OmniSharp log ###
<details>

Starting OmniSharp server at 9/8/2020, 10:07:23 PM
    Target: /home/jeroen/git/null

OmniSharp server started.
    Path: /home/jeroen/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/run
    PID: 28554

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 18.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.8.0 - "/home/jeroen/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/jeroen/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.8.0 - "/home/jeroen/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/jeroen/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/jeroen/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/jeroen/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/jeroen/git/null'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/jeroen/git/null'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/jeroen/git/null/null.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/jeroen/git/null'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/jeroen/git/null/null.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/jeroen/git/null' on host 26129.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/jeroen/git/null/null.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/jeroen/git/null/null.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: null
</details>

### C# log ###

Empty log.

## Environment information ##

**VSCode version**: 1.48.2
**C# Extension**: 1.23.2

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    39d17847db

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.401/

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  2.1.809 [/usr/share/dotnet/sdk]
  2.2.402 [/usr/share/dotnet/sdk]
  3.1.101 [/usr/share/dotnet/sdk]
  3.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|bash-ide-vscode|mads-hartmann|1.11.0|
|csharp|ms-dotnettools|1.23.2|
|dotnet-test-explorer|formulahendry|0.7.4|
|githistory|donjayamanne|0.6.9|
|js-debug-nightly|ms-vscode|2020.6.617|
|LiveServer|ritwickdey|5.6.1|
|multi-command|ryuta46|1.4.0|
|powershell|ms-vscode|2020.6.0|
|python|ms-python|2020.8.106424|
|vscode-command-runner|edonet|0.0.116|
|vscode-docker|ms-azuretools|1.5.0|
|vscode-eslint|dbaeumer|2.1.8|
|vscode-nuget-gallery|patcx|0.0.22|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-pylance|ms-python|2020.9.0|
|vscode-python-test-adapter|littlefoxteam|0.4.6|
|vscode-test-explorer|hbenl|2.19.1|;

</details>

**Comment by nohwnd** [comment]
I can reproduce this whenmy project and **my global json** is targetting  3.1.401. Then the build in console will use 3.1 SDK and I get no warning, but I still see the warning in VSCode.  `dotnet new globaljson --sdk-version 3.1.401`. 

@JeroenBos could you check if you project has global.json (next to the csproj or more likely next to the .sln file) and post it's content?

Setting the language from latest to 8.0 as suggested here https://github.com/OmniSharp/omnisharp-roslyn/issues/1604 does not help, this seems like a difference between the analyzer version that we use and the one that 3.1 SDK packs. Trying to find if there is an option that can be specified.

**Comment by JeroenBos** [comment]
@nohwnd I don't have a global.json file next to the csproj file, and I don't even have a .sln file, just an empty folder with the steps described as above

**Comment by nohwnd** [comment]
Thanks, in that case it would be just me forcing my environment to replicate yours where your latest version of dotnet is 3.1.401 (based on the Dotnet Information section). The problem is still the same, the SDK you use for build uses its own version of Roslyn while OmniSharp packs a newer version of Roslyn which gives that warning.

**Comment by JoeRobich** [comment]
> vscode gives a nullability warning whereas `dotnet build` does not.

The reason for this discrepency is that the language services driving the IDE warnings is using a newer version of the C# compiler. As the nullability feature develops in preview, the compiler will improve and provide better information.

**Comment by JeroenBos** [comment]
Okay, thank you. Although unexpected, the explanation makes sense.
