### ISSUE TITLE
Intellisense interfering when typing a string

### ISSUE THREAD

**Issue by pflannery** [OmniSharp/omnisharp-vscode#405]
Couldn't find an existing issue for this.

## Environment data
`dotnet --info` output: .NET Command Line Tools (1.0.0-beta-001598)
VS Code version: 1.1.1
C# Extension version: 1.0.11

## Steps to reproduce
![image](https://cloud.githubusercontent.com/assets/1727302/15808642/74e3cc30-2b74-11e6-8aec-28e76a1bb3d1.png)

## Expected behavior
No intellisense should show\interfere when typing within a string

**Comment by DustinCampbell** [comment]
Is it actually interfering? It's by design that VS Code shows word-based completion inside strings and comments. From your screenshot, it appears that snippets do as well.

**Comment by DustinCampbell** [comment]
ping?

**Comment by DustinCampbell** [comment]
I'm going to close this issue as it's grown quite stale. However, these items are provided by VS Code. With the latest releases of VS Code, there are a couple of settings that can be used to control this behavior:

1. Word-based completion items (like 'string' in the code pictured) can be controlled with the `"editor.snippetSuggestions"` setting.
2. Snippet completion items (like 'sim' in the code pictured) can be controlled with the "editor.quickSuggestions" setting.
