### ISSUE TITLE
The type or namespace name 'System' could not be found

### ISSUE THREAD

**Issue by jkyeung** [OmniSharp/omnisharp-vscode#4053]
## Issue Description ##

Seems a lot like several other issues, such as #2147 and #3532, but unfortunately, I haven't found the solution to my own situation.

## Steps to Reproduce ##

Start VS Code on a new project created using `dotnet new console`.

## Expected Behavior ##

Clean hello-world program.

## Actual Behavior ##

Lots of red squiggly underlines.

### OmniSharp log ###

Sorry, I couldn't figure out how to make code fencing work within details, but here it is anyway:

<details>Starting OmniSharp server at 9/10/2020, 4:24:13 PM
    Target: c:\Users\jkyeu\Documents\Pluralsight\C#\gradebook

OmniSharp server started.
    Path: c:\Users\jkyeu\.vscode\extensions\ms-dotnettools.csharp-1.23.2\.omnisharp\1.37.1\OmniSharp.exe
    PID: 17360

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2019 16.3.29318.209 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
            2: StandAlone 16.8.0 - "c:\Users\jkyeu\.vscode\extensions\ms-dotnettools.csharp-1.23.2\.omnisharp\1.37.1\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2019 16.3.29318.209 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\jkyeu\Documents\Pluralsight\C#\gradebook'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\jkyeu\Documents\Pluralsight\C#\gradebook'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\jkyeu\Documents\Pluralsight\C#\gradebook\src\GradeBook\GradeBook.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\jkyeu\Documents\Pluralsight\C#\gradebook'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\jkyeu\Documents\Pluralsight\C#\gradebook\src\GradeBook\GradeBook.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\jkyeu\Documents\Pluralsight\C#\gradebook' on host 11500.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\jkyeu\Documents\Pluralsight\C#\gradebook\src\GradeBook\GradeBook.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\jkyeu\Documents\Pluralsight\C#\gradebook\src\GradeBook\GradeBook.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: GradeBook
</details>

### C# log ###

This is empty.

## Environment information ##

**VSCode version**: 1.49.0
**C# Extension**: 1.23.2

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    39d17847db

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.401\

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer-2|CoenraadS|0.2.0|
|csharp|ms-dotnettools|1.23.2|
|language-julia|julialang|1.0.7|
|python|ms-python|2020.8.108011|
|vsc-python-indent|KevinRose|1.11.0|
|vscode-autohotkey|slevesque|0.2.2|;

</details>

**Comment by JoeRobich** [comment]
@jkyeung Sorry the MSBuild Build tools 16.3 doesn't support .NET SDK 3.1.401. You will need to install the 16.8 Preview BuildTools from https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16&ch=pre

**Comment by jkyeung** [comment]
@JoeRobich - I installed 16.8, and now OmniSharp sees all three (16.3, 16.8, and the standalone), but still picks 16.3, even after rebooting my machine. Do I have to uninstall 16.3? Would it work if I upgraded to 16.7?

**Comment by JoeRobich** [comment]
@jkyeung Can you share your OmniSharp log from the Ouput pane? and when you installed 16.8 did you include the .NET Core tooling?

**Comment by jkyeung** [comment]
Hmm. I didn't specifically include .NET Core tooling. I just clicked "Install". I will try doing the installer again, and then report back.

**Comment by jkyeung** [comment]
OK, I modified the installation so that it includes the .NET Core tooling for 16.8, and now VS Code doesn't seem to be complaining anymore. So I guess that answers that.

Just incidentally, is the reason to use the 16.8 preview rather than the 16.7 release just so that the build tools become obsolete later? If I am reading [this](https://versionsof.net/core/3.1/3.1.7/) correctly, 16.7 should work with the SDK that I have.

**Comment by JoeRobich** [comment]
> I don't know how long it would have taken for me to figure it out on my own

There should be a warning for MSBuild / SDK version mismatch. I will verify this is logging on Windows platforms.

> Just incidentally, is the reason to use the 16.8 preview just so that the build tools become obsolete later? If I am reading [this](https://versionsof.net/core/3.1/3.1.7/) correctly, 16.7 should work for the SDK that I have.

No, you are right. I've been answering this same question so often for users who are trying out the .NET 5 Preview 8 (which does require 16.8) that my mind went into autopilot. On the plus side though, you could try out .NET 5 now. =)

**Comment by jkyeung** [comment]
I am completely new to the .NET ecosystem, so I wasn't aware of the .NET 5 "grand unification" project. Sounds great! Maybe I will try it out!
