### ISSUE TITLE
Blazor debug error: Terminal process terminated with exit code 1

### ISSUE THREAD

**Issue by AntonOnyshch** [OmniSharp/omnisharp-vscode#4056]
## Environment data

.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

VSCode: 1.49.0
Omnisharp: 1.23.2

## OmniSharp log

Starting OmniSharp server at 9/11/2020, 11:30:59 PM
    Target: c:\Users\***\source\repos\MyProject\MyProject

OmniSharp server started.
    Path: c:\Users\***\.vscode\extensions\ms-dotnettools.csharp-1.23.2\.omnisharp\1.37.1\OmniSharp.exe
    PID: 4648

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.8.0 - "c:\Users\***\.vscode\extensions\ms-dotnettools.csharp-1.23.2\.omnisharp\1.37.1\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\***\.vscode\extensions\ms-dotnettools.csharp-1.23.2\.omnisharp\1.37.1\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.8.0 - "c:\Users\***\.vscode\extensions\ms-dotnettools.csharp-1.23.2\.omnisharp\1.37.1\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\***\.vscode\extensions\ms-dotnettools.csharp-1.23.2\.omnisharp\1.37.1\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\***\.vscode\extensions\ms-dotnettools.csharp-1.23.2\.omnisharp\1.37.1\.msbuild
            MSBuildToolsPath = c:\Users\***\.vscode\extensions\ms-dotnettools.csharp-1.23.2\.omnisharp\1.37.1\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\***\source\repos\MyProject\MyProject'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\***\source\repos\MyProject\MyProject'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\***\source\repos\MyProject\MyProject\MyProject.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\***\source\repos\MyProject\MyProject'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\***\source\repos\MyProject\MyProject\MyProject.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\***\source\repos\MyProject\MyProject' on host 644.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\***\source\repos\MyProject\MyProject\MyProject.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\***\source\repos\MyProject\MyProject\MyProject.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MyProject
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\***\source\repos\MyProject\MyProject\MyProject.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\***\source\repos\MyProject\MyProject\MyProject.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\***\source\repos\MyProject\MyProject\MyProject.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\***\source\repos\MyProject\MyProject\MyProject.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\***\source\repos\MyProject\MyProject\MyProject.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MyProject
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: C:\Users\***\.nuget\packages\microsoft.aspnetcore.components.analyzers\3.1.6\analyzers\dotnet\cs\Microsoft.AspNetCore.Components.Analyzers.dll
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\Users\***\source\repos\MyProject\MyProject\obj\Debug\netstandard2.1\RazorDeclaration\App.razor.g.cs added to workspace
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\Users\***\source\repos\MyProject\MyProject\obj\Debug\netstandard2.1\RazorDeclaration\Shared\MainLayout.razor.g.cs added to workspace
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\Users\***\source\repos\MyProject\MyProject\obj\Debug\netstandard2.1\RazorDeclaration\CapabilityItem.razor.g.cs added to workspace
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\Users\***\source\repos\MyProject\MyProject\obj\Debug\netstandard2.1\RazorDeclaration\TariffItem.razor.g.cs added to workspace
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\Users\***\source\repos\MyProject\MyProject\obj\Debug\netstandard2.1\RazorDeclaration\Pages\Index.razor.g.cs added to workspace
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\Users\***\source\repos\MyProject\MyProject\obj\Debug\netstandard2.1\RazorDeclaration\_Imports.razor.g.cs added to workspace
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\Users\***\source\repos\MyProject\MyProject\obj\Debug\netstandard2.1\Razor\App.razor.g.cs added to workspace
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\Users\***\source\repos\MyProject\MyProject\obj\Debug\netstandard2.1\Razor\Pages\Index.razor.g.cs added to workspace
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\Users\***\source\repos\MyProject\MyProject\obj\Debug\netstandard2.1\Razor\_Imports.razor.g.cs added to workspace
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\Users\***\source\repos\MyProject\MyProject\obj\Debug\netstandard2.1\Razor\TariffItem.razor.g.cs added to workspace
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\Users\***\source\repos\MyProject\MyProject\obj\Debug\netstandard2.1\Razor\CapabilityItem.razor.g.cs added to workspace
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\Users\***\source\repos\MyProject\MyProject\obj\Debug\netstandard2.1\Razor\Shared\MainLayout.razor.g.cs added to workspace

## Steps to reproduce

1. Blazor webassembly project
2. Start debugging
3. Press stop button results in error message **"The terminal process "cmd.exe '/c', 'chcp 65001 >NUL & dotnet run'" terminated with exit code: 1."**

**Comment by gregg-miskelly** [comment]
CC @captainsafia

**Comment by captainsafia** [comment]
Thanks for the bug report! Will work on a fix for this soon.

**Comment by jmarolf** [comment]
PR has been merged, closing

**Comment by sedat-eyuboglu** [comment]
I till have this problem. VS Code gives this error message.

Start a blazorwasm debug
Stop the debug
VS Code gives
The terminal process "cmd.exe '/c', 'chcp 65001 >NUL & dotnet run'" terminated with exit code: 1.

Omni Sharp version = 1.23.9
VSCode:
Version: 1.53.0 (user setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

Can someone show me a way to stop this error message? I couldn't find any clear info.

**Comment by NTaylorMullen** [comment]
@captainsafia this isn't Razor's debug proxy or anything is it?

**Comment by captainsafia** [comment]
@NTaylorMullen It is -- although we've removed the code that does this in the latest release.

@sedat-eyuboglu Can you open a new issue over on the dotnet/aspnetcore repo with the details you provided and the version of .NET you are using?

**Comment by sedat-eyuboglu** [comment]
> 
> 
> @NTaylorMullen It is -- although we've removed the code that does this in the latest release.
> 
> @sedat-eyuboglu Can you open a new issue over on the dotnet/aspnetcore repo with the details you provided and the version of .NET you are using?

done.
