### ISSUE TITLE
Unity 2019.4.10f1: Unity core classes not recognized anymore

### ISSUE THREAD

**Issue by derwaldgeist** [OmniSharp/omnisharp-vscode#4061]
I opened up VSCode today without doing any changes to my code-base, but suddenly none of the Unity classes are recognized anymore. All are underlined in red, e.g. "MonoBehaviour", and all my files are marked as erroneous (over 10k errors). This renders working with Unity projects literally impossible. A pure nightmare... Was there any change recently in either Omnisharp or VSCode that might have caused this?

EDIT: I installed Unity 2019.4.10f1 yesterday. The problem goes away (sort of) if I re-install Unity 2019.4.9f1 and open the project with it. But not for all classes. I have libraries (UTNotifcations) where some files are still marked as erroneous. Interestingly, this only happens in my Android project (I maintain 2 separate copies of the same Unity project, one set to the iOS target, the other to the Android target). In the iOS project, it works.

**Comment by filipw** [comment]
There was no change in Omnisharp.
Sounds to me more like a Unity issue. You may want to check if you have latest Mono installed.

**Comment by derwaldgeist** [comment]
Thanks for the fast response. Closing this, as it doesn't seem to be an Omnisharp issue. I also noted that my iOS project even works if opened with Unity 2019.4.10f1, only the Android platforms shows these issues.

**Comment by derwaldgeist** [comment]
After some switching back and forth between 2019.4.9f1 and 2019.4.10f1, it now also works with Android. This is very, very strange.

**Comment by derwaldgeist** [comment]
I could resolve the problem by removing all .sln and .csproj files from the Unity project folder and then starting Unity 2019.4.10f1. It recreated all the files and now it's working again.
