### ISSUE TITLE
Question: How to get Warnings for Unused `using`s?

### ISSUE THREAD

**Issue by FloatingSunfish** [OmniSharp/omnisharp-vscode#4062]
I saw **_[this issue](https://github.com/OmniSharp/omnisharp-vscode/issues/315)_** where previously, unused `using`s were being presented as warnings.
The solution was to no longer show them as warnings and instead fade the unused `using`s.

However, I like getting warnings for unused `using`s as I want to remove all of them from my project.

Is there an option to make OmniSharp flag them as warnings so I can see them?

**_Note:_** I have also seen **_[this feature request](https://github.com/OmniSharp/omnisharp-vscode/issues/1245)_** to remove unused `using`s, but because it has not yet been implemented, I would like to know how to get warnings about them in the meantime.

**Comment by JoeRobich** [comment]
Set `omnisharp.enableRoslynAnalyzers = true` and `omnisharp.enableEditorConfigSupport = true` in settings, then in your .editorconfig you can set the severity as you like.

```ini
root = true

[*.cs]

# IDE0005: Using directive is unnecessary
dotnet_diagnostic.IDE0005.severity = warning
```

**Comment by FloatingSunfish** [comment]
Noted, @JoeRobich! Thanks! :)
