### ISSUE TITLE
Question: How to Get Warnings for All Uses of `public`

### ISSUE THREAD

**Issue by FloatingSunfish** [OmniSharp/omnisharp-vscode#4066]
Because I'm not creating a library, I want to replace all uses of `public` inside my project to `internal`.

While I can do this with Find and Replace, is there a configuration that I can add to `.editorconfig` that will give me warnings about all uses of `public` so I automatically know if there's something I want to replace?

**Comment by jmarolf** [comment]
you can't by default. You could write an analyzer to do this (see [here](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/))

**Comment by FloatingSunfish** [comment]
@jmarolf Noted, thanks! :)
