### ISSUE TITLE
Enable "logging": "engineLogging" for blazorwasm debug type

### ISSUE THREAD

**Issue by ar0311** [OmniSharp/omnisharp-vscode#4070]
To enable debugging debug engine while debugging a hosted Blazor WASM project with VS Code.

## Steps to reproduce
Create new hosted blazorwasm project.
Cannot add "logging" to configuration as it's not supported.

## Expected  behavior
Can add "logging" stanza.

## Actual behavior
Can't add "logging" stanza.

**Comment by gregg-miskelly** [comment]
CC @captainsafia

**Comment by captainsafia** [comment]
Thanks, @gregg-miskelly!

I'll be making some changes to the Razor extension soon and will try to batch this in.

**Comment by captainsafia** [comment]
@jmarolf You can probably close this one too since the above PR was merged. This change will ship in the next version of O#.
