### ISSUE TITLE
IntelliSense for Godot project not working anymore

### ISSUE THREAD

**Issue by kutoman** [OmniSharp/omnisharp-vscode#4075]
## Issue Description ##
C# IntelliSense is not working anymore for my godot c# scripts

## Steps to Reproduce ##
no idea.. I've also tried older versions of the omnisharp extension but the issue still remained.
## Expected Behavior ##
a working IntelliSense as I was used to until a few days ago.
## Actual Behavior ##
IntelliSense is not working anymore.
### OmniSharp log ###
<details>Starting OmniSharp server at 19.9.2020, 21:04:36
    Target: ***\Development\GodotProjects\MySurpriseGame\My Surprise Game.sln

OmniSharp server started.
    Path: ***\.vscode\extensions\ms-dotnettools.csharp-1.23.2\.omnisharp\1.37.1\OmniSharp.exe
    PID: 3232

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 3 MSBuild instance(s)
            1: Visual Studio Build Tools 2019 16.7.30503.244 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
            2: Visual Studio Build Tools 2017 15.9.28307.1259 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            3: StandAlone 16.8.0 - "***\.vscode\extensions\ms-dotnettools.csharp-1.23.2\.omnisharp\1.37.1\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2019 16.7.30503.244 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '***\Development\GodotProjects\MySurpriseGame'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '***\Development\GodotProjects\MySurpriseGame\My Surprise Game.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '***\Development\GodotProjects\MySurpriseGame\My Surprise Game.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '***\Development\GodotProjects\MySurpriseGame'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: ***\Development\GodotProjects\MySurpriseGame\My Surprise Game.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '***\Development\GodotProjects\MySurpriseGame' on host 9916.
[fail]: OmniSharp.MSBuild.ProjectLoader
        Das Ziel "Compile" ist im Projekt nicht vorhanden.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '***\Development\GodotProjects\MySurpriseGame\My Surprise Game.csproj'.
***\Development\GodotProjects\MySurpriseGame\My Surprise Game.csproj
***\Development\GodotProjects\MySurpriseGame\My Surprise Game.csproj(0,0): Error: The target "Compile" does not exist in the project.

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: ***\Development\GodotProjects\MySurpriseGame\My Surprise Game.csproj</details>

### Godot Project csproj ###
<details>

```
<Project Sdk="Godot.NET.Sdk/3.2.3">
  <PropertyGroup>
    <ProjectGuid>{5X85BDCX-84E4-X49F-9148-0FDD8FA6C908}</ProjectGuid>
    <OutputType>Library</OutputType>
    <RootNamespace>MySurpriseGame</RootNamespace>
    <AssemblyName>My Surprise Game</AssemblyName>
    <GodotProjectGeneratorVersion>1.0.0.0</GodotProjectGeneratorVersion>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <!--<TargetFramework>net472</TargetFramework>-->
    <!--The following properties were overriden during migration to prevent errors.
    Enabling them may require other manual changes to the project and its files.-->
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="objects\enemy\Enemy.cs" />
    <Compile Include="objects\gem\Gem.cs" />
    <Compile Include="objects\gui\HUD.cs" />
    <Compile Include="objects\misc\ChestTrigger.cs" />
    <Compile Include="objects\misc\MsgTrigger.cs" />
    <Compile Include="objects\player\BonesPolygons.cs" />
    <Compile Include="objects\player\Player.cs" />
    <Compile Include="objects\player\PlayerHead.cs" />
    <Compile Include="objects\singletons\DDUtils.cs" />
    <Compile Include="objects\singletons\Main.cs" />
    <Compile Include="objects\singletons\SettingOptions.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
</Project>
```

</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.49.1
**C# Extension**: 1.23.2

<details><summary>Dotnet Information</summary>
.NET Core SDK (gem�� "global.json"):
 Version:   3.1.402
 Commit:    9b5de826fd

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  2.1.518 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|batch-replacer|angelomollame|1.2.1|
|cocos-creator|Chukong Technologies|0.0.1|
|cocos-debug|Chukong Technology|0.0.1|
|csharp|ms-dotnettools|1.23.2|
|githd|huizhou|2.2.4|
|godot-csharp-vscode|neikeq|0.1.3|
|language-gettext|mrorz|0.2.0|
|live-sass|ritwickdey|3.0.0|
|LiveServer|ritwickdey|5.6.1|
|mono-debug|ms-vscode|0.15.8|
|open-in-browser|techer|2.0.0|
|php-debug|felixfbecker|1.13.0|
|php-intellisense|felixfbecker|2.3.14|
|sftp|liximomo|1.12.9|
|syncing|nonoroazoro|3.0.13|
|twig|whatwedo|1.0.2|
|vetur|octref|0.27.3|;

</details>

**Comment by jmarolf** [comment]
@kutoman does this project build with `msbuild "My Surprise Game.csproj"`? Either way this sounds like a Godot sdk bug not an omnisharp one
