### ISSUE TITLE
.NET 5.0 .csproj false error

### ISSUE THREAD

**Issue by ar0311** [OmniSharp/omnisharp-vscode#4077]
When viewing a .csproj file with .NET 5.0 SDK installed, a red squiggle marker appears below the last </Project> element (so at the end of the file) with the following error:

_Invalid static method invocation syntax: "[MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)')". Method '[MSBuild]::GetTargetFrameworkIdentifier' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)). Check that all parameters are defined, are of the correct type, and are specified in the right order._

## Environment data
`dotnet --info` output: .NET SDK RC2 5.0.100-rc.2.20468.17
VS Code version: 1.49.1
C# Extension version: 1.23.3

## Steps to reproduce

Install .NET SDK RC1 or RC2
dotnet new console
Open folder in VS Code

## Expected  behavior

No error.

## Actual behavior

Error appears as above.
![Screen Shot 2020-09-20 at 9 48 49 am](https://user-images.githubusercontent.com/832109/93691331-3a61b680-fb27-11ea-80b0-0c971f602751.png)

**Comment by filipw** [comment]
please post your Omnisharp log. I would guess you have an outdated Visual Studio installation that doesn't support .NET 5.0 RC1. Omnisharp uses MSBuild from VS if installed on your machine

**Comment by filipw** [comment]
Also please disable all other extensions and try to reproduce it. Omnisharp normally doesn't provide diagnostics for csproj files so it is also possible  that this error comes from a different extension.

**Comment by ar0311** [comment]
Correct, after disabling all other extensions it appears to be caused by MSBuild project tools extension.

Will post the issue there.
