### ISSUE TITLE
Unable to install extension 'ms-dotnettools.csharp-1.23.2' as it is not compatible with VS Code '1.30.0'

### ISSUE THREAD

**Issue by TheRoadhog** [OmniSharp/omnisharp-vscode#4085]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

**Comment by gregg-miskelly** [comment]
@TheRoadhog The current version of VS Code is 1.49. Are you really trying to use 1.30.0? If so, this is probably "by design".

**Comment by jmarolf** [comment]
by design
