### ISSUE TITLE
Autocompletion on Generic adds angle-brackets

### ISSUE THREAD

**Issue by nonsensation** [OmniSharp/omnisharp-vscode#4094]
## Issue Description ##
When using autocompletion for generics, angle brackets are inserted after the type. This way the cursor jumps behind the generic's angle brackets:
`public Dict|` and hitting Tab becomes `public Dictionary<>|`  
`arr = list.ToArr|` and hitting Tab becomes `arr = list.ToArray<>|` 
This seems to be new behaviour, as only as of today I found it unusually distracting.  
I checked against Visual Studio 2019 (16.5.4), there autocompletion ommits the angle brackets entirely:  
`public Dict|` and hitting Tab becomes `public Dictionary|`  
I suspect this was also the way VSCode did it up until recently.

## Expected Behaviour ##
* Place the cursor inside the angle brackets:  
`public Dict|` and hitting Tab becomes `public Dictionary<|>`
 Having the cursor outside of the brackets one must step 1 character back to include the generic type.
* Better solution: having it the old way (without insterting angle brackets at all): after autocompletion of the variablename, one types in `<` and autocompletion adds in the closing bracket `>` while the cursor is inside the brackets.
Also, this would solve the issue with deduced generic types:
`arr = list.ToArr|` and hitting Tab becomes `arr = list.ToArray|` and we can continue typing with `()`

## Environment information ##

**VSCode version**: 1.49.2
**C# Extension**: 1.23.2

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    39d17847db

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.401\

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.2.204 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.2|;

</details>

**Comment by jmarolf** [comment]
@333fred I think this was broken by your change

**Comment by 333fred** [comment]
Likely. I'll take a look.

**Comment by 333fred** [comment]
@nonsensation do what version of the omnisharp host are you using? Can you see if the issue still reproduces with https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.3-beta3?

**Comment by 333fred** [comment]
I suspect this is due to using a beta version of the omnisharp host, which switched from sending the insertion text in the `insertText` property, without using the corresponding beta version of the vscode extension that was updated to support this. Separately, @jmarolf if you're looking for things to add to the bug report info, we should get the omnisharp host verison.

**Comment by nonsensation** [comment]
Thank you for your fast response :-)

Upon opening VSCode this morning (with `"omnisharp.path": "latest"` in the settings) I got this:
```
Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.37.2-beta.73...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.37.2-beta.73' (35885 KB).................... Done!
Installing package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.37.2-beta.73'

Finished
``` 
Guess this is what the OmniSharp Host is?

I installed 1.23.3-beta3 and it seems to be fixed.

Thank you very much :-)

**Comment by 333fred** [comment]
Yep, that's what I was expecting to hear. Thanks :).
