### ISSUE TITLE
Scripts in "Editor" folder cannot access the classes in Unity project

### ISSUE THREAD

**Issue by ailuropoda0** [OmniSharp/omnisharp-vscode#4100]
## Expected Behavior ##
No error. Unity Editor compiles my project without any problem.

## Actual Behavior ##
Omnisharp cannot access classes in my Unity project from the "Editor" folder.
"The type or namespace name '[class_name_in_the_project]" could not be found" kind of errors occur
in the script files in ~/Editor/ folder which calls the classes in the Unity project.
There is no error on other script files not in ~/Editor/ folder.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.49.3
**C# Extension**: 1.23.2

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.2|
|gc-excelviewer|GrapeCity|3.0.40|
|python|ms-python|2020.9.112786|
|unity-debug|Unity|2.7.5|
|unity-tools|Tobiah|1.2.12|;

</details>

**Comment by ailuropoda0** [comment]
@JoeRobich I have opened VS code by clicking the script in Unity Editor, which would work as opening my Unity project's root folder in VS code. So there are .sln file and the generated .csproj files in the root path in VS code.

But anyway, now it has been fixed even though I am not sure what was changed. Thanks.

**Comment by yullm** [comment]
I'm experiencing the exact same issue across multiple projects.

**Comment by ChacAndMeese** [comment]
I am also experiencing this issue in my own project since today.

**Comment by yullm** [comment]
I downgraded the c# extension to version 1.23 to fix it.

**Comment by eytienne** [comment]
@yullm proceeding in a dichotomous way, I found out it is broken from v1.23.3

**Comment by filipw** [comment]
This is a duplicate of #4113 and it is not an OmniSharp bug, but rather OmniSharp's change to fix incorrect project handling unveiled a bug in Unity's VSCode package.

You need to make sure that your Unity VSCode package is updated to at least 1.2.3 https://github.com/OmniSharp/omnisharp-vscode/issues/4113#issuecomment-718006809 and that `"omnisharp.useGlobalMono":"always"` is set. After this upgrade, the Unity projects need to be regenerated too.
