### ISSUE TITLE
Spiritous SEHException thrown when debugging a program using ClangSharp

### ISSUE THREAD

**Issue by DCNick3** [OmniSharp/omnisharp-vscode#4101]
## Issue Description ##
(Also tracked at microsoft/ClangSharp#167)
Running a program as simple as

```
using ClangSharp.Interop;
class Program
{
    static void Main(string[] args)
    {
        var index = CXIndex.Create();
    }
}
```

with debugger attached results in a `System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.` popping out in different places (depends on where do I put a breakpoint). If I put no breakpoint it shows up somewhere in standard library internals.

Program without a debugger runs just fine (which makes think that this is debugger specific issue).

Does not seem to depend on ClangSharp version.

It is reproducible with both Rider and vs code debugger on arch linux and with rider remote debugging on debian.

## Steps to Reproduce ##

1. Create a dotnet core app project
2. Put 
```c#
using ClangSharp.Interop;
class Program
{
    static void Main(string[] args)
    {
        var index = CXIndex.Create();
    }
}
```
into `Program.cs`
3. Debug the program

## Expected Behavior ##

Program terminates successfully, like without the debugger

## Actual Behavior ##

`System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.` pops up

### OmniSharp log ###
<details>Starting OmniSharp server at 10/7/2020, 8:55:27 AM
    Target: /home/dcnick3/RiderProjects/LibclangTest/LibclangTest.sln

OmniSharp server started.
    Path: /home/dcnick3/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.2-beta.100/run
    PID: 532038

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on arch 0.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.8.0 - "/home/dcnick3/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.2-beta.100/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/dcnick3/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.2-beta.100/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.8.0 - "/home/dcnick3/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.2-beta.100/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/dcnick3/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.2-beta.100/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/dcnick3/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.2-beta.100/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/dcnick3/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.2-beta.100/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/dcnick3/RiderProjects/LibclangTest'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/dcnick3/RiderProjects/LibclangTest/LibclangTest.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/dcnick3/RiderProjects/LibclangTest/LibclangTest.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/dcnick3/RiderProjects/LibclangTest'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/dcnick3/RiderProjects/LibclangTest/LibclangTest.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/dcnick3/RiderProjects/LibclangTest' on host 531565.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/dcnick3/RiderProjects/LibclangTest/LibclangTest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/dcnick3/RiderProjects/LibclangTest/LibclangTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: LibclangTest
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/dcnick3/RiderProjects/LibclangTest/LibclangTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/dcnick3/RiderProjects/LibclangTest/LibclangTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/dcnick3/RiderProjects/LibclangTest/LibclangTest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/dcnick3/RiderProjects/LibclangTest/LibclangTest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: LibclangTest
</details>

### C# log ###
<details>Installing C# dependencies...
Platform: linux, x86_64, name=arch, version=unknown

Downloading package 'OmniSharp for Linux (x64)' (47203 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Linux (x64)'

Downloading package '.NET Core Debugger (linux / x64)' (54671 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (linux / x64)'

Downloading package 'Razor Language Server (Linux / x64)' (52580 KB).................... Done!
Installing package 'Razor Language Server (Linux / x64)'

Finished

Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.37.2-beta.100...
Platform: linux, x86_64, name=arch, version=unknown

Downloading package 'OmniSharp for Linux (x64), Version = 1.37.2-beta.100' (47335 KB).................... Done!
Installing package 'OmniSharp for Linux (x64), Version = 1.37.2-beta.100'

Finished</details>

## Environment information ##

**VSCode version**: 1.49.2
**C# Extension**: 1.23.2

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.108
 Commit:    c423b556b5

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.108/

Host (useful for support):
  Version: 3.1.8
  Commit:  05a0c8f6b1

.NET Core SDKs installed:
  3.1.108 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.2|;

</details>

**Comment by gregg-miskelly** [comment]
If you are seeing the same problem with both VS Code and Rider this isn't a problem with either product. It could be an issue with the .NET debugging services, but it is more likely an issue with the interop signatures being generated not matching what libClang actually does.
