### ISSUE TITLE
Output window keeps hijacking focus from Terminal

### ISSUE THREAD

**Issue by RussKie** [OmniSharp/omnisharp-vscode#4102]
Issue Type: <b>Bug</b>

Quite often when I switch between branches or start building a .NET project and have Terminal window focus Output window hijacks the focus and switches away from the Terminal window.

I have 100% reliable repro, but here's an animation of this:
![vscode-output](https://user-images.githubusercontent.com/4403806/95540746-5200d080-0a3d-11eb-915b-a3307ea27b4e.gif)

Extension version: 1.23.2
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz (12 x 3402)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.94GB (9.92GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rjgotten** [comment]
This happens whenever the output window for C# or Omnisharp logs an exception, afaik.
It's been doing that for a long time.

The recent 1.23.3 version just puts it at the forefront because it has some very annoying bugs where part of the analyzer hangs/crashes.

**Comment by ponchautf** [comment]
I'm having that too.
is there a way to avoid losing focus from terminal (very annoying)

**Comment by RussKie** [comment]
Still see it intermittently. Today it was particularly nasty.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

Extension|Author (truncated)|Version
---|---|---
quick-html-previewer|dai|1.0.1
dotnet-test-explorer|for|0.7.5
csharp|ms-|1.23.9
cpptools|ms-|1.2.2
powershell|ms-|2021.2.2
prettier-plus|svi|4.2.2

**Comment by JoeRobich** [comment]
@RussKie You are still seeing this with the "csharp.showOmnisharpLogOnError" setting set to false?

**Comment by RussKie** [comment]
Didn't know there was such a thing! Disabled it now, will ping back if it doesn't help.
Thank you
