### ISSUE TITLE
Default DotNet console project full of errors.

### ISSUE THREAD

**Issue by RGFTheCoder** [OmniSharp/omnisharp-vscode#4106]
## Issue Description ##
Making the default `dotnet new console` project throws everything as an error, but running the project works fine.

## Steps to Reproduce ##
run `dotnet new console`
run `dotnet restore`
open `Program.cs`

## Expected Behavior ##
No errors are shown and itellisense works properly.

## Actual Behavior ##
Every reference is thrown as an error and VSCode reports 26 problems.
Ex:
![Screenshot_20201011_151644](https://user-images.githubusercontent.com/24970643/95687986-ed787980-0bd4-11eb-909a-696de100366d.png)

### OmniSharp log ###
```
Starting OmniSharp server at 10/11/2020, 3:13:21 PM
    Target: /media/linx/Data/code/csharp/diploidEvo

OmniSharp server started with Mono 6.12.0 (/usr/bin/mono).
    Path: /home/linx/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/omnisharp/OmniSharp.exe
    PID: 623753

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 20.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.8.0 - "/usr/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.8.0 - "/home/linx/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.8.0 - "/usr/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /home/linx/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/media/linx/Data/code/csharp/diploidEvo'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/media/linx/Data/code/csharp/diploidEvo'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/media/linx/Data/code/csharp/diploidEvo/diploidEvo.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/media/linx/Data/code/csharp/diploidEvo'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /media/linx/Data/code/csharp/diploidEvo/diploidEvo.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/media/linx/Data/code/csharp/diploidEvo' on host 620358.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/media/linx/Data/code/csharp/diploidEvo/diploidEvo.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/media/linx/Data/code/csharp/diploidEvo/diploidEvo.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: diploidEvo
```

### C# log ###
```
```

## Environment information ##

**VSCode version**: 1.50.0
**C# Extension**: 1.23.2

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.402/

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|angelscript|renesackers|1.0.1|
|bash-ide-vscode|mads-hartmann|1.11.0|
|better-c-syntax|jeff-hykin|1.13.0|
|better-cpp-syntax|jeff-hykin|1.15.0|
|better-dockerfile-syntax|jeff-hykin|1.0.2|
|better-go-syntax|jeff-hykin|1.1.0|
|better-perl-syntax|jeff-hykin|1.0.12|
|better-shellscript-syntax|jeff-hykin|1.1.0|
|better-toml|bungcip|0.3.2|
|brainfuck-syntax|attilabuti|0.0.1|
|cmake-tools|ms-vscode|1.4.2|
|CobaltNext|dline|0.3.1|
|code-eol|jeff-hykin|1.0.11|
|code-runner|formulahendry|0.11.1|
|color-highlight|naumovs|2.3.0|
|CppSnippets|hars|0.0.14|
|cpptools|ms-vscode|1.0.1|
|crystal-lang|faustinoaq|0.4.0|
|csharp|ms-dotnettools|1.23.2|
|datapack-language-server|SPGoding|3.0.7|
|discord-vscode|icrawl|4.0.0|
|docomment|k--kato|0.1.18|
|githd|huizhou|2.2.4|
|gitignore|codezombiech|0.6.0|
|gitlens|eamodio|10.2.2|
|hex-hover-converter|maziac|1.0.1|
|hexeditor|ms-vscode|1.3.0|
|language-gas-x86|basdp|0.0.2|
|language-haskell|justusadam|3.3.0|
|language-mcfunction|arcensoth|0.17.0|
|language-pde|Tobiah|1.4.6|
|language-x86-64-assembly|13xforever|2.3.0|
|latex-utilities|tecosaur|0.3.7|
|latex-workshop|James-Yu|8.13.2|
|linkerscript|ZixuanWang|1.0.1|
|MagicPython|magicstack|1.1.0|
|markdown-all-in-one|yzhang|3.3.0|
|material-theme|zhuangtongfa|3.9.3|
|mcscript|Stevertus|0.0.3|
|nearley|karyfoundation|1.0.3|
|noctis|liviuschera|10.39.0|
|path-intellisense|christian-kohler|2.3.0|
|pdf|tomoki1207|1.1.0|
|polacode-2019|jeff-hykin|0.5.2|
|prettier-vscode|esbenp|5.7.1|
|project-manager|alefragnani|11.3.0|
|python|ms-python|2020.9.114305|
|quokka-vscode|WallabyJs|1.0.323|
|rainbow-csv|mechatroner|1.7.1|
|run-on-save|pucelle|1.3.1|
|rust|rust-lang|0.7.8|
|shader|slevesque|1.1.4|
|shaderlabformatter|litefeel|0.4.0|
|shell-format|foxundermoon|7.0.1|
|swe-starter-pack|jeff-hykin|0.0.3|
|Theme-MaterialKit|ms-vscode|0.1.4|
|todo-tree|Gruntfuggly|0.0.183|
|unity-code-snippets|kleber-swf|1.3.0|
|vsc-community-material-theme|Equinusocio|1.4.2|
|vsc-material-theme|Equinusocio|33.0.0|
|vsc-material-theme-icons|equinusocio|1.2.0|
|vscode-css-formatter|aeschli|1.0.1|
|vscode-fish|bmalehorn|1.0.20|
|vscode-glsllint|CADENAS|1.2.0|
|vscode-icon-theme|jtlowe|1.6.6|
|vscode-icons|vscode-icons-team|11.0.0|
|vscode-markdown-code-runner|jeepshen|0.1.1|
|vscode-npm-script|eg2|0.3.13|
|vscode-open-in-github|ziyasal|1.3.6|
|vscode-pull-request-github|GitHub|0.20.1|
|vscode-terminal-here|Tyriar|0.2.4|
|vscode-theme-onedark|akamud|2.2.2|
|vscode-wasm|dtsvet|1.3.1|
|vscode-xml|redhat|0.13.0|
|vshaxe|nadako|2.21.4|
|vsliveshare|ms-vsliveshare|1.0.2902|
|vsliveshare-audio|ms-vsliveshare|0.1.91|
|vsliveshare-pack|ms-vsliveshare|0.4.0|
|xd-theme|jeff-hykin|0.1.148|;

</details>

**Comment by RGFTheCoder** [comment]
Not using global mono seems to fix all the errors, but it shouldn't make a difference...

**Comment by filipw** [comment]
This is by design. You are using latest dotnet SDK 3.1.402 which requires msbuild 16.8 - there is no Mono released yet  with that msbuild version. This is why the latest extension release switched to not use global Mono by default (it's an opt in now).

See https://github.com/mono/mono/issues/20250 for the issue tracking Mono release with msbuild 16.7+

**Comment by JotaRata** [comment]
I just reverted back to C# extension v1.22.0 and it worked
