### ISSUE TITLE
OmniSharp stopped working after update to 1.1.4

### ISSUE THREAD

**Issue by sec** [OmniSharp/omnisharp-vscode#411]
## Environment data
`dotnet --info` output:

> .NET Command Line Tools (1.0.0-preview1-002702)
> 
> Product Information:
>  Version:     1.0.0-preview1-002702
>  Commit Sha:  6cde21225e
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.10586
>  OS Platform: Windows
>  RID:         win10-x64

VS Code version: 1.2.0
C# Extension version: 1.1.4

## Steps to reproduce
dotnet new
dotnet restore
code .
Start typeing some code for autocomplete

## Expected  behavior
Autocomplete work.

## Actual behavior
No autocomplete, exception in omnisharp log:

> [INFO] Starting OmniSharp at 'c:\Users\user\Desktop\Nowy folder'...
> [INFO] Started OmniSharp from 'C:\Users\user\.vscode\extensions\ms-vscode.csharp-1.1.4\.omnisharp\OmniSharp.exe' with process id 8628...
> OmniSharp: -s c:\Users\user\Desktop\Nowy folder --hostPID 4980 dnx:enablePackageRestore=false --stdio
> [INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location 'c:\Users\user\Desktop\Nowy folder' on host 4980.
> [INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in c:\Users\user\Desktop\Nowy folder
> [INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: True
> [INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
> [INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update project c:\Users\user\Desktop\Nowy folder
> [INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Add project c:\Users\user\Desktop\Nowy folder\project.json => dfcbe7ac-86d0-45c7-87d3-30ecdd58ed53
> [INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
> [INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] Nowy folder/.NETCoreApp,Version=v1.0
> [INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 74 and removed 0 file references
> [INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 1 and removed 0 documents.
> [INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] No solution files found in 'c:\Users\user\Desktop\Nowy folder'
> [INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in 'c:\Users\user\Desktop\Nowy folder'.
> [INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
> [INFORMATION:OmniSharp.Startup] Configuration finished.
> [ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: The type initializer for 'OmniSharp.CSharpSyntaxContext' threw an exception.
> [INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 67ms
> [ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: The type initializer for 'OmniSharp.CSharpSyntaxContext' threw an exception.
> [INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 12ms
> [INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 824ms

It was working yesterday before update to 1.1.4 (1.0.11 if I remember right).

**Comment by PiterGoCompany** [comment]
The same for me.

**Comment by DustinCampbell** [comment]
@troydai -- do you know anything about the exception being thrown in the log above?

**Comment by DustinCampbell** [comment]
FYI -- I can reproduce the problem. Thanks for the heads up!

**Comment by troydai** [comment]
I have no idea now. But I can take a look now.

**Comment by troydai** [comment]
Can't repo on mac. But the original repo is on Windows.

**Comment by DustinCampbell** [comment]
No worries. I'm looking too.

**Comment by DustinCampbell** [comment]
@troydai, note that the extension is using v1.9-beta4 of OmniSharp.

**Comment by DustinCampbell** [comment]
I can't repro on OSX either. One other thing @troydai, it's using the net451 build of v1.9-beta4 on Windows.

**Comment by troydai** [comment]
I can repo it. I suspect it is caused unmatched dotnet and project model.

**Comment by DustinCampbell** [comment]
Looks like the problem's been there awhile, but got fixed at some point. I sync'd back to v1.9-beta4 and rebuilt OmniSharp and can repro. I can't repro with the latest dev branch though.

**Comment by DustinCampbell** [comment]
I'll take a look at updating OmniSharp in the extension

**Comment by DustinCampbell** [comment]
FWIW, it looks like the class in question, `CSharpSyntaxContext` does a bunch of reflection calls in its static constructor.

**Comment by DustinCampbell** [comment]
Yup -- it fails right here: https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.Roslyn.CSharp/Workers/Intellisense/CSharpSyntaxContext.cs#L438

**Comment by DustinCampbell** [comment]
OK. I've pushed a new release (1.1.5) to the marketplace that fixes the problem. @sec and @PiterGoCompany, could you update the C# extension from within Visual Studio Code and let me know if you're up and running again? Thanks!

**Comment by Schnigle** [comment]
The new release seems to work for me.

**Comment by sec** [comment]
Also working here. Thanks.

**Comment by alexgwolff** [comment]
1.1.5 also working here

**Comment by troydai** [comment]
I think we can close this one then.

**Comment by DustinCampbell** [comment]
Yup! Thanks all for reporting this so quickly and helping us get this fixed.
