### ISSUE TITLE
Intelisense works partially in VS Code with Unity under Linux

### ISSUE THREAD

**Issue by fmeneuhe** [OmniSharp/omnisharp-vscode#4112]
## Issue Description ##
Intelisense works partially in VS Code with Unity. The Unity events like "OnMouseDown" for example are not found. I mean partially because if I type "this." intellisense works. 

## Steps to Reproduce ##
Create any C# script with Unity. Type a Unity Event method, for example "OnMouse", and you can see that Intellisense does not work because cannot find "OnMouseDown, OnMouseUp,...."

## Expected Behavior ##
Should find all the unity events with the name "OnMouse"

## Actual Behavior ##
It is not found.

### OmniSharp log ###
<details>Starting OmniSharp server at 13/10/2020 22:24:32
    Target: /home/fran/Unity Cloud Projects/FruitAdventure2D/FruitAdventure2D.sln

OmniSharp server started with Mono 6.12.0.
    Path: /home/fran/.vscode/extensions/ms-dotnettools.csharp-1.23.3/.omnisharp/1.37.2/omnisharp/OmniSharp.exe
    PID: 13519

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on linuxmint 20.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.8.0 - "/usr/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.8.0 - "/home/fran/.vscode/extensions/ms-dotnettools.csharp-1.23.3/.omnisharp/1.37.2/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.8.0 - "/usr/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /home/fran/.vscode/extensions/ms-dotnettools.csharp-1.23.3/.omnisharp/1.37.2/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/fran/Unity Cloud Projects/FruitAdventure2D'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/fran/Unity Cloud Projects/FruitAdventure2D/FruitAdventure2D.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/fran/Unity Cloud Projects/FruitAdventure2D/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/fran/Unity Cloud Projects/FruitAdventure2D/Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/fran/Unity Cloud Projects/FruitAdventure2D'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/fran/Unity Cloud Projects/FruitAdventure2D' on host 13367.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/fran/Unity Cloud Projects/FruitAdventure2D/Assembly-CSharp.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/fran/Unity Cloud Projects/FruitAdventure2D/Assembly-CSharp.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/fran/Unity Cloud Projects/FruitAdventure2D/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/fran/Unity Cloud Projects/FruitAdventure2D/Assembly-CSharp-Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/fran/Unity Cloud Projects/FruitAdventure2D/Assembly-CSharp-Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/fran/Unity Cloud Projects/FruitAdventure2D/Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-Editor
</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.50.0
**C# Extension**: 1.23.3

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.12.0</details>
<details><summary>Dotnet Information</summary>
SDK de .NET Core (reflejando cualquier global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Entorno de tiempo de ejecución:
 OS Name:     linuxmint
 OS Version:  20
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.403/

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  3.1.403 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.3|;

</details>

**Comment by JoeRobich** [comment]
@fmeneuhe Sorry you are running into issues. Could you set the omnisharp loglevel to debug, reload your folder, and share the OmniSharp log from the output pane?

**Comment by fmeneuhe** [comment]
I attached log.txt
[log.txt](https://github.com/OmniSharp/omnisharp-vscode/files/5374013/log.txt)

**Comment by sbaranov** [comment]
This could be related - as of this morning, VSCode suddenly can't find names in one of the Unity specific assemblies:

- 'foo' does not contain a definition for 'foo' [Assembly-CSharp-Editor]
- The name 'foo' does not exist in the current context [Assembly-CSharp-Editor]
- The type or namespace name 'foo' does not exist in the namespace 'foo' (are you missing an assembly reference?) [Assembly-CSharp-Editor]
- The type or namespace name 'foo' could not be found (are you missing a using directive or an assembly reference?) [Assembly-CSharp-Editor]

**Comment by fmeneuhe** [comment]
I think this is not actually a bug of Omnisharp, maybe more an enhanced feature for Unity. 
It is solved by installing this VS Code extension:
https://marketplace.visualstudio.com/items?itemName=YclepticStudios.unity-snippets

**Comment by JoeRobich** [comment]
@fmeneuhe Thanks for sharing your log with me. From investigating this new Unity problem from a repro shared in a different issue. It seems that a recent change to make project loading more correct broke some Unity scenarios because Unity is configuring ProjectReferences to not be referenced. See my comment at https://github.com/OmniSharp/omnisharp-vscode/issues/4113#issuecomment-714726062

**Comment by JoeRobich** [comment]
As the maintainer of Unity's VSCode package has [indicated they are working on a fix](https://github.com/OmniSharp/omnisharp-vscode/issues/4113#issuecomment-715121265) in the comments for #4113. I'm going to mark this as a duplicate and allow #4113 to track this issue.
