### ISSUE TITLE
The .NET Core SDK cannot be located. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path.

### ISSUE THREAD

**Issue by GreatLandmark** [OmniSharp/omnisharp-vscode#4120]
Issue Type: <b>Bug</b>

The .NET Core SDK cannot be located. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path.

But， I have install .Net Core SDK. And cmd: ` where dotnet`  , then:
`C:\Program Files\dotnet\dotnet.exe`

Extension version: 1.23.3
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.89GB (10.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by gregg-miskelly** [comment]
@GreatLandmark You can find more information about this error here: https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshooting:-'The-.NET-Core-SDK-cannot-be-located.'-errors

**Comment by GreatLandmark** [comment]
> @GreatLandmark You can find more information about this error here: https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshooting:-'The-.NET-Core-SDK-cannot-be-located.'-errors

I find the resolution，I need install .Net framework dev pack. After doing that， it goes well. Thank you!

**Comment by irvanherz** [comment]
For me, in linux system, moving these variables from `.bashrc` to `/etc/profile` can solve the problem.
```
export DOTNET_ROOT=$HOME/.dotnet
export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools
```
It looks like vscode doesn't load variables from `.bashrc`
