### ISSUE TITLE
1.23.4 raises error when debugging: 'couldn't find a debug adapter descriptor for debug type 'coreclr''

### ISSUE THREAD

**Issue by ludwigdn** [OmniSharp/omnisharp-vscode#4126]
## Environment data
`dotnet --info` output:

> 
> SDK .NET Core (reflétant tous les global.json) :
>  Version:   3.1.402
>  Commit:    9b5de826fd
> 
> Environnement d'exécution :
>  OS Name:     Windows
>  OS Version:  10.0.18363
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.1.402\
> 
> Host (useful for support):
>   Version: 3.1.8
>   Commit:  9c1330dedd
> 
> .NET Core SDKs installed:
>   3.1.402 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

> VS Code version: 1.50.1
> C# Extension version: 1.23.4

## Steps to reproduce

- Install C# extension for VS Code
- Start a debug session
- The message will pop up

## Actual behavior

**NB: Project build correctly with a "dotnet build".**

Launching a debug session worked when I was working on my project for the past two weeks, but not since today.

I didn't see which version of C# extension I had at that time, but apparently the changelog updated yesterday... so maybe the new version was installed locally when I opened my laptop one hour ago.

![image](https://user-images.githubusercontent.com/11355187/96618174-e5bb8200-1304-11eb-9a70-8baf6e374744.png)

## Log

[  None ]

**Comment by gregg-miskelly** [comment]
Base on your problem here and in the other issue you opened I think you may have a corrupt install of the C# extension and/or VS Code. This error means that the C# extension didn't activate.

Also BTW: the `program` value that you have in your launch.json is bogus. So you probably want to delete the file and have the C# extension regenerate it if you can get it to activate.

**Comment by ludwigdn** [comment]
@gregg-miskelly I've already tried a couple of times to remove/add the extension of course. 

But after your message, I tried another time (just for the sake of it)... and now it works. Sorry for the inconvenience. 

As we say, _Windows works in mysterious ways_
