### ISSUE TITLE
The reference assemblies for .NETFramework,Version=v5.0 were not found

### ISSUE THREAD

**Issue by gtodd876** [OmniSharp/omnisharp-vscode#4136]
## Steps to Reproduce ##
Open .net5 project in vs code
## Expected Behavior ##
omnisharp locates reference assemblies for .NETFramework,Version=v5.0
## Actual Behavior ##
omnisharp can not find reference assemblies for .NETFramework,Version=v5.0
## Logs ##
[exthost] [error] [ms-dotnettools.csharp] provider FAILED
[exthost] [error] Problem invoking 'GetCodeActions' on OmniSharp server: Error: Pending request cancelled: /v2/getcodeactions
### OmniSharp log ###
<details>Starting OmniSharp server at 10/22/2020, 6:22:11 AM
    Target: /Users/todd/projects/dating-app/dating-app.sln

OmniSharp server started with Mono 6.12.0.
    Path: /Users/todd/.vscode/extensions/ms-dotnettools.csharp-1.23.4/.omnisharp/1.37.3/omnisharp/OmniSharp.exe
    PID: 84514

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 11.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.8.0 - "/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.8.0 - "/Users/todd/.vscode/extensions/ms-dotnettools.csharp-1.23.4/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.8.0 - "/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /Users/todd/.vscode/extensions/ms-dotnettools.csharp-1.23.4/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/todd/projects/dating-app'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/todd/projects/dating-app/dating-app.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/todd/projects/dating-app/API/API.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/todd/projects/dating-app'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/todd/projects/dating-app/API/API.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/todd/projects/dating-app' on host 84381.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/todd/projects/dating-app/API/API.csproj'.
/Users/todd/projects/dating-app/API/API.csproj
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1193,5): Error: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/todd/projects/dating-app/API/API.csproj
</details>

### C# log ###
<details>n/a (blank window)</details>

## Environment information ##

**VSCode version**: 1.50.1
**C# Extension**: 1.23.4

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100-rc.2.20479.15/

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  2.1.700 [/usr/local/share/dotnet/sdk]
  2.2.300 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.100 [/usr/local/share/dotnet/sdk]
  3.1.300 [/usr/local/share/dotnet/sdk]
  5.0.100-rc.1.20452.10 [/usr/local/share/dotnet/sdk]
  5.0.100-rc.2.20479.15 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Angular2|johnpapa|9.1.2|
|auto-rename-tag|formulahendry|0.1.5|
|azure-account|ms-vscode|0.9.3|
|better-toml|bungcip|0.3.2|
|bracket-pair-colorizer-2|CoenraadS|0.2.0|
|cloudcode|googlecloudtools|1.6.1|
|code-spell-checker|streetsidesoftware|1.9.2|
|csharp|ms-dotnettools|1.23.4|
|csharpextensions|kreativ-software|1.3.6|
|debugger-for-chrome|msjsdiag|4.12.11|
|docomment|k--kato|0.1.18|
|EditorConfig|EditorConfig|0.15.1|
|FreeMarker|dcortes92|0.0.9|
|githistory|donjayamanne|0.6.12|
|gitignore|michelemelluso|1.0.1|
|gitlens|eamodio|10.2.2|
|go|golang|0.17.2|
|graphql-for-vscode|kumar-harsh|1.15.3|
|html-css-class-completion|Zignd|1.19.0|
|JavaScriptSnippets|xabikos|1.8.0|
|LiveServer|ritwickdey|5.6.1|
|markdown-preview-enhanced|shd101wyy|0.5.13|
|material-icon-theme|PKief|4.3.0|
|ng-template|Angular|0.1001.0|
|night-owl|sdras|2.0.0|
|open-in-browser|techer|2.0.0|
|path-intellisense|christian-kohler|2.3.0|
|powershell|ms-vscode|2020.6.0|
|prettier-vscode|esbenp|5.7.1|
|prisma|Prisma|2.9.0|
|project-manager|alefragnani|11.3.1|
|quicktype|quicktype|12.0.46|
|remote-containers|ms-vscode-remote|0.145.1|
|remote-vscode|rafaelmaiolla|1.1.0|
|search-node-modules|jasonnutter|1.3.0|
|sqltools|mtxr|0.23.0|
|theme-hop-light|bubersson|0.0.4|
|todo-tree|Gruntfuggly|0.0.183|
|vetur|octref|0.28.0|
|vscode-azureappservice|ms-azuretools|0.19.0|
|vscode-azurefunctions|ms-azuretools|1.0.0|
|vscode-csharp-snippets|jorgeserrano|0.5.0|
|vscode-docker|ms-azuretools|1.7.0|
|vscode-eslint|dbaeumer|2.1.13|
|vscode-firefox-debug|firefox-devtools|2.9.1|
|vscode-language-babel|mgmcdermott|0.0.30|
|vscode-nuget-gallery|patcx|0.0.22|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-peacock|johnpapa|3.8.0|
|vscode-sqlite|alexcvzz|0.9.0|
|vscode-todo-highlight|wayou|1.0.4|
|vscode-versionlens|pflannery|1.0.8|
|vscode-yaml|redhat|0.11.1|
|vsliveshare|ms-vsliveshare|1.0.3046|
|vue-vscode-snippets|sdras|2.1.5|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by filipw** [comment]
This is a duplicate. Please see here for a solution https://github.com/OmniSharp/omnisharp-vscode/issues/4134#issuecomment-714326240
