### ISSUE TITLE
Omnisharp fails to Start with NetCore 5.0 RC2

### ISSUE THREAD

**Issue by mdmoura** [OmniSharp/omnisharp-vscode#4137]
## Issue Description ##

When working on an NetCore 5.0 class library Omnisharp fails to load. The project file is:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
</Project>
```
### OmniSharp log ###
<details>
Starting OmniSharp server at 10/22/2020, 12:04:45 PM
    Target: /Users/mky/mky.Project/mky.Project.mky.Core/src/mky.Core

OmniSharp server started with Mono 6.12.0.
    Path: /Users/mky/.vscode/extensions/ms-dotnettools.csharp-1.23.4/.omnisharp/1.37.4-beta.2/omnisharp/OmniSharp.exe
    PID: 4228

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.15.7 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.6.0 - "/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.8.0 - "/Users/mky/.vscode/extensions/ms-dotnettools.csharp-1.23.4/.omnisharp/1.37.4-beta.2/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.6.0 - "/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /Users/mky/.vscode/extensions/ms-dotnettools.csharp-1.23.4/.omnisharp/1.37.4-beta.2/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/mky/mky.Project/mky.Project.mky.Core/src/mky.Core'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/mky/mky.Project/mky.Project.mky.Core/src/mky.Core'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/mky/mky.Project/mky.Project.mky.Core/src/mky.Core/mky.Core.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/mky/mky.Project/mky.Project.mky.Core/src/mky.Core'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/mky/mky.Project/mky.Project.mky.Core/src/mky.Core/mky.Core.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/mky/mky.Project/mky.Project.mky.Core/src/mky.Core' on host 3828.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/mky/mky.Project/mky.Project.mky.Core/src/mky.Core/mky.Core.csproj'.
/Users/mky/mky.Project/mky.Project.mky.Core/src/mky.Core/mky.Core.csproj
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1193,5): Error: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/mky/mky.Project/mky.Project.mky.Core/src/mky.Core/mky.Core.csproj
</details>

## Environment information ##

**VSCode version**: 1.50.1
**C# Extension**: 1.23.4

<details>
  <summary>Mono Information</summary>
  OmniSharp using global mono :6.12.0
</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100-rc.2.20479.15/

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  5.0.100-rc.2.20479.15 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Angular2|johnpapa|9.1.2|
|azure-account|ms-vscode|0.9.3|
|azure-pipelines|ms-azure-devops|1.177.0|
|csharp|ms-dotnettools|1.23.4|
|markdown-preview-enhanced|shd101wyy|0.5.13|
|mdmath|goessner|2.5.1|
|ml-net-model-builder|franzssilva|0.1.1|
|mssql|ms-mssql|1.9.0|
|remote-containers|ms-vscode-remote|0.145.1|
|typescript-hero|rbbit|3.0.0|
|vetur|octref|0.28.0|
|vscode-docker|ms-azuretools|1.7.0|
|vscode-mjml|attilabuti|1.6.0|
|vscode-sqlite|alexcvzz|0.9.0|
|vscode-yaml|redhat|0.11.1|;

</details>

**Comment by filipw** [comment]
sorry for the trouble. This is a duplicate. Please see here for a solution https://github.com/OmniSharp/omnisharp-vscode/issues/4134#issuecomment-714326240
