### ISSUE TITLE
omnisharp broken on the mac :/

### ISSUE THREAD

**Issue by leozhang1** [OmniSharp/omnisharp-vscode#4139]
Command 'OmniSharp: Restart OmniSharp' resulted in an error (command 'o.restart' not found)
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/43508492/96929200-c862f100-1487-11eb-9b33-57b4b51addca.png">

**Comment by JoeRobich** [comment]
@leozhang1 Sorry you are running into this issue. Looks like this may be an incomplete installation. Could you try uninstalling the C# extension and reinstalling it?

**Comment by leozhang1** [comment]
> @leozhang1 Sorry you are running into this issue. Looks like this may be an incomplete installation. Could you try uninstalling the C# extension and reinstalling it?

Hello Joe. I did that but it didn't work :/

**Comment by JoeRobich** [comment]
@leozhang1 After reinstalling, is there any logs in the Output pane for C#, .NET, or OmniSharp? Could you share them?

**Comment by leozhang1** [comment]
> @leozhang1 After reinstalling, is there any logs in the Output pane for C#, .NET, or OmniSharp? Could you share them?

yeah so restarting it works like before, but there are no "references" at the top of my functions....

<img width="983" alt="image" src="https://user-images.githubusercontent.com/43508492/96933132-eb909f00-148d-11eb-8e74-d986d2bac672.png">

**Comment by JoeRobich** [comment]
@leozhang1 Looking good so far. Can you share the OmniSharp logging from the Output pane? It will have details about project loading that can point us at what is going on.

**Comment by leozhang1** [comment]
> @leozhang1 Looking good so far. Can you share the OmniSharp logging from the Output pane? It will have details about project loading that can point us at what is going on.

oh my bad. I thought the first image from before was it. Is this it?

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/43508492/96934084-a0778b80-148f-11eb-8003-7018a054fcdb.png">

**Comment by JoeRobich** [comment]
@leozhang1 Oh, the 1.15.2 version of the C# extension is very old. Could you install the latest version from the Extension panel or manually update to the latest release available here - https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.4

**Comment by leozhang1** [comment]
thats the vs code extension for C# tho

**Comment by leozhang1** [comment]
> @leozhang1 Oh, the 1.15.2 version of the C# extension is very old. Could you install the latest version from the Extension panel or manually update to the latest release available here - https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.4
What I had was the C# vs code extension by microsoft though? Do I just uninstall that extension?
Also I downloaded the zip file from your link. what do I do with it next?

**Comment by leozhang1** [comment]
> @leozhang1 Oh, the 1.15.2 version of the C# extension is very old. Could you install the latest version from the Extension panel or manually update to the latest release available here - https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.4

What I had was the C# vs code extension by microsoft though? Do I just uninstall that extension?
Also I downloaded the zip file from your link. what do I do with it next?

**Comment by JoeRobich** [comment]
@leozhang1 I'm not sure why it was installing such an old (May 2018) release for you. First uninstall the old C# extension and then you can either drag the .vsix into the extension panel or you can use this dropdown to Install from .VSIX. 
![image](https://user-images.githubusercontent.com/611219/96940652-28a46380-1485-11eb-8812-30026f4799a7.png)

**Comment by leozhang1** [comment]
> @leozhang1 I'm not sure why it was installing such an old (May 2018) release for you. First uninstall the old C# extension and then you can either drag the .vsix into the extension panel or you can use this dropdown to Install from .VSIX.
> ![image](https://user-images.githubusercontent.com/611219/96940652-28a46380-1485-11eb-8812-30026f4799a7.png)

@JoeRobich Okay. This last one is taking forever to download tho. Is that normal?

<img width="717" alt="image" src="https://user-images.githubusercontent.com/43508492/96941439-6bc00000-14a0-11eb-8e0f-a9f359f36f16.png">

**Comment by leozhang1** [comment]
@JoeRobich 
So...it didn't work 😭
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/43508492/96944756-bb56f980-14a9-11eb-9d19-93c43f90167c.png">

**Comment by JoeRobich** [comment]
@leozhang1 Can you remove your configuration for "omnisharp.monoPath" it should be able to locate it on its own and that is one less potential issue, also remove "omnisharp.waitForDebugger" which may have caused the timeout, and "omnisharp.autostart" as the default value is already true.

**Comment by leozhang1** [comment]
@JoeRobich Okay. Removing those, now this:

<img width="931" alt="image" src="https://user-images.githubusercontent.com/43508492/96945220-14735d00-14ab-11eb-87f3-9f3dacc927c6.png">

**Comment by JoeRobich** [comment]
@leozhang1 I've only seen that error when there are multiple VS Code windows open. One is running C# extension and the other installed and upgraded C# extension causing there two be two instances running. If you have multiple VS Code instances running close them all and start a single instance.

**Comment by leozhang1** [comment]
> @leozhang1 I've only seen that error when there are multiple VS Code windows open. One is running C# extension and the other installed and upgraded C# extension causing there two be two instances running. If you have multiple VS Code instances running close them all and start a single instance.

Okay. @JoeRobich  Yup. I had another one open, but now, with these settings
<img width="424" alt="image" src="https://user-images.githubusercontent.com/43508492/96952351-a2a40f00-14bc-11eb-8ed0-5f85923415ba.png">

I have this problem. I think we're getting closer though. Thank you so far :)
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/43508492/96952441-ded76f80-14bc-11eb-8426-6c724d879eb4.png">

**Comment by royshouvik** [comment]
I had the same problem and it seemed to have been fixed with
```
 "omnisharp.path": "latest",
 "omnisharp.useGlobalMono": "never"
```

**Comment by leozhang1** [comment]
> I had the same problem and it seemed to have been fixed with
> ```
>  "omnisharp.path": "latest",
>  "omnisharp.useGlobalMono": "never"
> ```

Hey @royshouvik ! That did it! How did you know that we should never use global mono? If we set the value to "never", then which mono are we using?

**Comment by JoeRobich** [comment]
I have updated the Readme with instruction for developing against the .NET Core 3.1.40x and .NET 5 SDKs - https://github.com/OmniSharp/omnisharp-vscode#note-about-using-net-core-3140x-sdks

Unfortunately Mono 6.12.0 still ships with an older version of MSBuild that does not support these SDKS.

**Comment by JoeRobich** [comment]
@leozhang1 Glad things are working for you now. Going to close this one.
