### ISSUE TITLE
C# Language Grammar not recognizing value or default contextual keywords

### ISSUE THREAD

**Issue by TanakaDev** [OmniSharp/omnisharp-vscode#4146]
Contextual keywords such as default (without type parameter) or value (in property setters) are not recognized as keywords by the grammar engine. I expected that they would get special grammar scopes such as this and base do, but currently they are just marked under the scope of "variable.other.readwrite.cs" which is not ideal for custom color themes. Visual Studio has special syntax highlighting for value but it currently isn't possible emulate this behavior in VS Code.  Here I am using the default dark+ color theme, bracket colorizer v2 and the OmniSharp extension.

![value-keyword](https://user-images.githubusercontent.com/71856931/97096476-b3ba6080-1621-11eb-8c41-049f6311d223.png)
![default-keyword](https://user-images.githubusercontent.com/71856931/97096477-c3d24000-1621-11eb-9570-ea76e6e4a9b2.png)

**Comment by 333fred** [comment]
Have you turned on semantic colorization? That should enable contextual keyword colorization based on actual usage.

**Comment by TanakaDev** [comment]
Oh your right, thank you very much! I missed this option. It should really be on be default.

**Comment by 333fred** [comment]
The vscode api itself is still in preview, so we don't want to turn it on by default until it's for sure finalized, but it's been solid for me for the past few months.

**Comment by TanakaDev** [comment]
Yeah it seems like it works pretty well.
