### ISSUE TITLE
Getting 26 errors along types and namespaces not found, not imported nor defined when creating a Console App. 

### ISSUE THREAD

**Issue by ky3l0** [OmniSharp/omnisharp-vscode#4154]
## Issue Description ##

Getting 26 errors along types and namespaces not found, not imported nor defined when creating a Console App and using the C# extension at the same time.

## Steps to Reproduce ##

`dotnet new console`
Installing the extension

## Expected Behavior ##

No errors, it's a Console Application template.

## Actual Behavior ##

26 errors.
![issueVScode](https://user-images.githubusercontent.com/73456668/97315342-3f084180-182e-11eb-9551-ae0b0400eaf3.png)

### OmniSharp log ###

Starting OmniSharp server at 10/27/2020, 7:51:39 AM
    Target: /home/kyel0/Documents/C#/HelloWorld

OmniSharp server started with Mono 6.10.0.
    Path: /home/kyel0/.vscode/extensions/ms-dotnettools.csharp-1.23.4/.omnisharp/1.37.3/omnisharp/OmniSharp.exe
    PID: 6631

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 20.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.8.0 - "/usr/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.8.0 - "/home/kyel0/.vscode/extensions/ms-dotnettools.csharp-1.23.4/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.8.0 - "/usr/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /home/kyel0/.vscode/extensions/ms-dotnettools.csharp-1.23.4/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/kyel0/Documents/C#/HelloWorld'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/kyel0/Documents/C#/HelloWorld'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/kyel0/Documents/C#/HelloWorld/HelloWorld.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/kyel0/Documents/C#/HelloWorld'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/kyel0/Documents/C#/HelloWorld/HelloWorld.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/kyel0/Documents/C#/HelloWorld' on host 6537.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/kyel0/Documents/C#/HelloWorld/HelloWorld.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/kyel0/Documents/C#/HelloWorld/HelloWorld.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: HelloWorld

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.50.1
**C# Extension**: 1.23.4

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.10.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.403/

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  3.1.403 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.4|
|vscode-solution-explorer|fernandoescolar|0.3.11|
|vscodeintellicode|VisualStudioExptTeam|1.2.10|;

</details>

**Comment by JoeRobich** [comment]
@ky3l0 Sorry you are running into issues. Please see this note about using the .NET 3.1.40x SDKs with the C# extension - https://github.com/OmniSharp/omnisharp-vscode#note-about-using-net-core-3140x-sdks

**Comment by ky3l0** [comment]
@JoeRobich Thanks! that fixed it.
