### ISSUE TITLE
Debugging variable popup misbehaves when expanding if it is near the top of the screen.

### ISSUE THREAD

**Issue by HubKing** [OmniSharp/omnisharp-vscode#4157]
## Issue Description ##

When the debugging variable popup is near the top of the screen, expanding the first item moves the popup to a new location. At this point, it is impossible to expand the second entry, because it gets closed when trying to do so. I think this screen recording explains all.

![28-October](https://user-images.githubusercontent.com/10900489/97376626-32085280-1901-11eb-9d6b-383e9570e48e.gif)

I am not sure if this is a problem of VS Code itself or the C# extension, so I will to post it here first. If it is VS Code's problem, please let me know. 
## Steps to Reproduce ##
1. Use the following code.

```
        static void Main(string[] args)
        {
            var l = new Dictionary<int, string>();
            for(var i=0; i<10; i++)
            {
                l.Add(i, $"Value of {i}");
            }
            var a = l.Count;
        }
```

2. Scroll down the code a little bit so that ` static void Main(string[] args)` will the first visible line.
3. Break and the dictionary and place the mouse over `l`.
4. Try to expand the first entry in the variable popup.

## Expected Behavior ##
The first item should be expanded pushing the items below further to the bottom.

## Actual Behavior ##
The first item tries to expand pushing itself to the top. Since there is no space there, the whole popup moves down. Now when I move the mouse to expand other entries, the popup gets closed.

## Environment information ##

**VSCode version**: 1.50.1
**C# Extension**: 1.23.4

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.403\

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9
</details>

**Comment by gregg-miskelly** [comment]
Hi @HubKing, this sounds like an issue with VS Code. Can you create an issue there? https://github.com/microsoft/vscode/issues

**Comment by HubKing** [comment]
I see. I will post it there. Thanks.
