### ISSUE TITLE
Cannot debug via launch or attach  with .NET 5 rc2 

### ISSUE THREAD

**Issue by mgutz** [OmniSharp/omnisharp-vscode#4167]
## Issue Description ##

Cannot debug on freshly installed .NET 5 in linux (debian) and windows 10. I downloaded the binary tarballs and set environment variables PATH and DOTNET_ROOT.

## Steps to Reproduce ##

As per the tutorial

```sh
dotnet new webapi -o TodoApi
dotnet run
```

Browsing to `localhost:5000/WeatherForecast` works so .NET 5 is installed correctly.

Added to `launch.json`

```json
      "logging": {
        "engineLogging": true,
        "moduleLoad": true
      },
      "debugServer": 4711
```

Ran ` .\vsdbg-ui.exe --server --consoleLogging` per another issue troubleshooting steps. VScode does not connect to that port when I click launch. I tested if port 4711 is open manually with powershell `test-connection` successfully.

Also tried using attach to process. Attach seems to do something but symbols are not loaded so no breakpoints.

## Expected Behavior ##

Be able to debug.

## Actual Behavior ##

Cannot debug.

### OmniSharp log ###

<details><pre>
Starting OmniSharp server at 10/31/2020, 3:41:48 AM
    Target: d:\projects\TodoApi

OmniSharp server started.
    Path: c:\Users\mgutz\.vscode\extensions\ms-dotnettools.csharp-1.23.4\.omnisharp\1.37.3\OmniSharp.exe
    PID: 21248

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.8.0 - "c:\Users\mgutz\.vscode\extensions\ms-dotnettools.csharp-1.23.4\.omnisharp\1.37.3\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\mgutz\.vscode\extensions\ms-dotnettools.csharp-1.23.4\.omnisharp\1.37.3\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.8.0 - "c:\Users\mgutz\.vscode\extensions\ms-dotnettools.csharp-1.23.4\.omnisharp\1.37.3\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\mgutz\.vscode\extensions\ms-dotnettools.csharp-1.23.4\.omnisharp\1.37.3\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\mgutz\.vscode\extensions\ms-dotnettools.csharp-1.23.4\.omnisharp\1.37.3\.msbuild
            MSBuildToolsPath = c:\Users\mgutz\.vscode\extensions\ms-dotnettools.csharp-1.23.4\.omnisharp\1.37.3\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\projects\TodoApi'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'd:\projects\TodoApi'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\projects\TodoApi\TodoApi.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\projects\TodoApi'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\projects\TodoApi\TodoApi.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\projects\TodoApi' on host 7984.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\projects\TodoApi\TodoApi.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\projects\TodoApi\TodoApi.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: TodoApi
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: d:\projects\TodoApi\obj\Debug\net5.0\TodoApi.MvcApplicationPartsAssemblyInfo.cs added to workspace
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\projects\TodoApi\TodoApi.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\projects\TodoApi\TodoApi.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\projects\TodoApi\TodoApi.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: TodoApi
</pre></details>

### C# log ###

<details><pre>
D:/projects/TodoApi •NET v5.0.100-rc.2.20479.15 🎯 net5.0 took 8m38s ❯ dotnet run  
Building...
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to http://localhost:5000 on the IPv4 loopback interface: 'An attempt was made to access a socket in a way forbidden by its access permissions.'.       
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\projects\TodoApi
</pre></debug>

## Environment information ##

**VSCode version**: 1.50.1
**C# Extension**: 1.23.4

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   d:\dotnet\sdk\5.0.100-rc.2.20479.15\

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  5.0.100-rc.2.20479.15 [d:\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [d:\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [d:\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [d:\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-close-tag|formulahendry|0.5.9|
|avro|streetsidesoftware|0.4.0|
|awesome-flutter-snippets|Nash|2.0.4|
|ayu|teabyii|0.20.1|
|brackets-light-pro|eryouhao|0.4.4|
|code-spell-checker|streetsidesoftware|1.9.2|
|csharp|ms-dotnettools|1.23.4|
|dart-code|Dart-Code|3.16.0|
|debugger-for-chrome|msjsdiag|4.12.11|
|EditorConfig|EditorConfig|0.15.1|
|flutter|Dart-Code|3.16.0|
|github-plus-theme|thenikso|1.2.1|
|go|golang|0.18.0|
|gotemplate|casualjim|0.4.0|
|graphql-for-vscode|kumar-harsh|1.15.3|
|grueling-hare|pureux|1.1.3|
|horla-light-theme|Horla|0.0.3|
|html-css-class-completion|Zignd|1.19.0|
|import-sorter|mike-co|3.3.1|
|java|redhat|0.69.0|
|javascript-ejs-support|DigitalBrainstem|1.3.1|
|jinjahtml|samuelcolvin|0.15.0|
|just|skellock|2.0.0|
|markdown-all-in-one|yzhang|3.3.0|
|material-theme|zhuangtongfa|3.9.3|
|mdx|silvenon|0.1.0|
|multi-command|ryuta46|1.4.0|
|night-light|YVKTechologies|1.1.3|
|powershell|ms-vscode|2020.6.0|
|prettier-vscode|esbenp|5.7.1|
|python|ms-python|2020.10.332292344|
|ra-autumn|rahmanyerli|2.2.0|
|razor-plus|austincummings|0.1.4|
|remote-containers|ms-vscode-remote|0.145.1|
|remote-ssh|ms-vscode-remote|0.55.0|
|remote-ssh-edit|ms-vscode-remote|0.55.0|
|remote-wsl|ms-vscode-remote|0.50.1|
|svelte-vscode|svelte|102.4.0|
|vsc-community-material-theme|Equinusocio|1.4.2|
|vsc-material-theme|Equinusocio|33.0.0|
|vsc-material-theme-icons|equinusocio|1.2.0|
|vscode-docker|ms-azuretools|1.7.0|
|vscode-eslint|dbaeumer|2.1.13|
|vscode-field-lights|sveggiani|0.0.11|
|vscode-java-debug|vscjava|0.29.0|
|vscode-java-dependency|vscjava|0.14.0|
|vscode-java-test|vscjava|0.25.0|
|vscode-markdownlint|DavidAnson|0.37.2|
|vscode-maven|vscjava|0.25.0|
|vscode-proto3|zxh404|0.5.2|
|vscode-remote-extensionpack|ms-vscode-remote|0.20.0|
|vscode-taskfile|paulvarache|0.0.3|
|vscode-theme-github-light|Hyzeta|7.14.2|
|vscode-theme-onelight|akamud|2.2.2|
|vscode-yaml|redhat|0.12.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.10|;

</details>

**Comment by gregg-miskelly** [comment]
Can you try removing `"debugServer": 4711`, but leaving in logging.engineLogging, and launching. What do you see?

**Comment by mgutz** [comment]
I should have mentioned I tried that first.  Same result. Progress bar infinitely moves but no action. C# log is empty.  There are no entries appended to Omnisharp Log.

To be thorough, here is the generted launch.json stanza with my changes

```json
    {
      "name": ".NET Core Launch (web)",
      "type": "coreclr",
      "request": "launch",
      "preLaunchTask": "build",
      "program": "${workspaceFolder}/bin/Debug/net5.0/TodoApi.dll",
      "args": [],
      "cwd": "${workspaceFolder}",
      "stopAtEntry": false,
      "serverReadyAction": {
        "action": "openExternally",
        "pattern": "\\bNow listening on:\\s+(https?://\\S+)"
      },
      "env": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "DOTNET_ROOT": "d:\\dotnet"
      },
      "sourceFileMap": {
        "/Views": "${workspaceFolder}/Views"
      },
      "logging": {
        "engineLogging": true
        //"moduleLoad": true
      }
      //"debugServer": 4711
    }
```

Is the plugin known to work with latest .NET 5 RC?

**Comment by mgutz** [comment]
FYI as soon I posted that, I thought to myself "What about removing `preLaunchTask`, maybe it's not building". Sure enough it seems to work using the previous build. I need to figure how to create the build task.

**Comment by mgutz** [comment]
The issue is `preLaunchTask` was failing because of another extension. Pressing Ctrl+Shift+B resulted in status bar showing "Fetching build tasks..." and nothing else. I disabled extensions related to debugger and tasks one by one and found the culprit. In my case it was the cross platform taskfile.dev extension.
