### ISSUE TITLE
I can't hit the break point in VS code

### ISSUE THREAD

**Issue by BingyuLiu** [OmniSharp/omnisharp-vscode#417]
## Environment data----Ubuntu OS
`dotnet --info` output:

VS Code version:
Version 1.1.1
Commit def9e32467ad6e4f48787d38caf190acbfee5880
Date 2016-05-13T13:38:00.094Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

C# Extension version: latest one

## Steps to reproduce
I have launch my progress, but I can hit the breakpoints

**Comment by BingyuLiu** [comment]
WARNING: The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use NETStandard 1.0.0-rc2-23901 or newer. This may be expected if the target process did not run .NET code.
The program '/home/john/dev/MMI/test/Microsoft.Management.Infrastructure.Tests/bin/Linux/netcoreapp1.0/Microsoft.Management.Infrastructure.Tests.dll' has exited with code 131 (0x00000083).

**Comment by DustinCampbell** [comment]
It'd be great if you could provide the requested information from the bug template. The output of `dotnet --info` is actually kind of critical, as is the version number of the C# extension that you're using.

**Comment by BingyuLiu** [comment]
WARNING: The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use NETStandard 1.0.0-rc2-23901 or newer. This may be expected if the target process did not run .NET code.
 The program '/home/john/dev/...../Tests.dll' has exited with code 131 (0x00000083).

**Comment by gregg-miskelly** [comment]
@BingyuLiu the console output tells us a whole lot more than your first report, but we still need the output from 'dotnet --info' to be able to make suggestions.

**Comment by BingyuLiu** [comment]
could we set up a meeting, I'd like to share my screen to debug easily?

**Comment by DustinCampbell** [comment]
@BingyuLiu, we *could* set up a meeting, but we could also understand a great deal without a meeting if you paste the output of `dotnet --info` from the command line into this bug report as requested.

**Comment by BingyuLiu** [comment]
Thanks Dustin. 

john@john-Virtual-Machine:~/dev/MMI$ dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
john@john-Virtual-Machine:~/dev/MMI$

**Comment by gregg-miskelly** [comment]
@BingyuLiu is your scenario that you are trying to run a unit test class library (one which is supposed to be run by `dotnet test`?)

If so, the fact that your project can't be launched under a debugger is expected - your dll doesn't have an entry point, so `dotnet` doesn't know what to do with your dll. What you want to do is invoke the test method via the link added above the method (see video in https://github.com/OmniSharp/omnisharp-vscode/pull/382).

**Comment by andschwa** [comment]
@gregg-miskelly Yes, we have xUnit tests that we need to debug with VS Code, as implemented in #382, for this exact reason, you cannot attach to dotnet test.

We are (were) running the latest VS Code nightly with the latest plugin nightly, but the feature where the xUnit tests would have a button to debug the individual tests does not appear.

**Comment by andschwa** [comment]
@BingyuLiu can you try out the newest VS Code and plugin nightly and see if this has since been resolved?

**Comment by BingyuLiu** [comment]
yes, I will have a try.

**Comment by BingyuLiu** [comment]
@andschwa, @gregg-miskelly  I have install a latest insiders VS code, but I can't see the 'run test' or 'debug test' button still. 

Version 1.2.0
Commit 809e7b30e928e0c430141b3e6abf1f63aaf55589
Date 2016-06-06T13:34:34.143Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

**Comment by troydai** [comment]
I'll close this one.

Talked with @BingyuLiu offline. The project he's using is not a valid .NET core test project.

**Comment by troydai** [comment]
Reopen. John provided a repo: https://github.com/BingyuLiu/MyDotNetApplicatoin.

**Comment by BingyuLiu** [comment]
Thank you Troy. :)

**Comment by troydai** [comment]
The test links shows up correctly.
![screen shot 2016-06-22 at 11 49 14 am](https://cloud.githubusercontent.com/assets/1329240/16279327/630ad2ee-386f-11e6-9e96-c79255e20875.png)

@BingyuLiu did you select project in VS Code? One the bottom right corner of the VS Code there is button to click to select project. You need to pick up at least the test project in the drop down:
![screen shot 2016-06-22 at 11 51 27 am](https://cloud.githubusercontent.com/assets/1329240/16279406/adc1ba46-386f-11e6-888f-1f3a50f3b1f3.png)

**Comment by troydai** [comment]
The test discovery is fine. The actual issue here really is: https://github.com/OmniSharp/omnisharp-vscode/issues/453

After moving the test file to the same level as project.json both run and debug works fine for me:
![screen shot 2016-06-22 at 11 57 05 am](https://cloud.githubusercontent.com/assets/1329240/16279587/77734080-3870-11e6-9d09-30a8b4d9085e.png)

**Comment by troydai** [comment]
@BingyuLiu please check my test project here: https://github.com/troydai/MyDotNetApplicatoin/tree/fix

I'll close this issue for now since it is partial duplicate, partial no repo. Please keep tracking issue #453, which I'm currently working on.
