### ISSUE TITLE
CSharp incompatible on aarch64

### ISSUE THREAD

**Issue by jmlisowski** [OmniSharp/omnisharp-vscode#4171]
I installed C# extension on vscode for aarch64 and I installed the C# extension. Unfortunately, it was incompatible and I cannot use it. Will there be support soon?

**Comment by gregg-miskelly** [comment]
Sorry, we don't have any date/release to announce for when Linux ARM or ARM64 will be supported. But we are tracking this feature request in https://github.com/OmniSharp/omnisharp-vscode/issues/2771.
