### ISSUE TITLE
Create launch.json thorws errer

### ISSUE THREAD

**Issue by rustedwizard** [OmniSharp/omnisharp-vscode#4172]
I am attempt to launch a debug session of my F# project (dotnet core). After press F5 and select .Net core for launch.json. following error message appear: 
<img width="342" alt="Capture" src="https://user-images.githubusercontent.com/6314177/97935824-8743ca00-1d2e-11eb-948b-29ab9d66cca9.PNG">
Seems this only appear in F# project, when I am in C# project, things works all right. 
Any suggestions (or F# project is just not supported)

**Comment by gregg-miskelly** [comment]
F# projects are not officially supported by this extension -- this extension tries to be smart about the launch.json that it generates, but being smart requires project understanding, and OmniSharp only understands C# projects. So definitely the best option would be for the F# extension (which I think the most popular one is [Ionide-fsharp](https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-fsharp)) to provide smart templates for launch.json based on understanding the project, or even just really basic templates. So if Ionide-fsharp doesn't, you may want to log an issue or follow up. 

If the Ionide-fsharp team would like to leverage parts of this repo for that, here are a few references:
* [OptionsSchema.json](https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/tools/OptionsSchema.json): Source of truth for debugger options
* C# 'dumb' (non-project based) [snippets](https://github.com/OmniSharp/omnisharp-vscode/blob/f2ea93f7a5dd6ddb2252dd6f713901cbb1610a05/package.json#L2031)
* Code to generate launch.json and tasks.json: [assets.ts](https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/assets.ts)

All that said, you could try dropping in an empty C# file into your repo and maybe you would get *something*. You could also use the `Add Configuration...' button if you already have a blank launch.json, as those templates are using the 'dumb' (non-project-based) snipits.

**Comment by rustedwizard** [comment]
Thank you for make it clear.

>  You could also use the `Add Configuration...' button if you already have a blank launch.json, as those templates are using the 'dumb' (non-project-based) snipits. 

Actually, this is how I create launch.json for now. I will close this ticket and create an feature request on F# plugin repo.
