### ISSUE TITLE
blazorwasm debug task does not honor PreLaunchTask setting

### ISSUE THREAD

**Issue by JustinGrote** [OmniSharp/omnisharp-vscode#4173]
## Issue Description ##
I am trying to start Azure Functions and the Azurite Storage emulator before starting blazorwasm launch debug task. I have both defined as tasks and want to start them with the `preLaunchTask` directive in launch.json.

This is using the blazor starter template for Static Web Apps
https://github.com/staticwebdev/blazor-starter

## Steps to Reproduce ##
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Start Blazor",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}/Client",
            "browser": "edge",
            "preLaunchTask": "func start"
        }
    ]
}
```
## Expected Behavior ##
Func start task will be run before blazorwasm debug launch
## Actual Behavior ##
blazorwasm just starts without running the prelaunch task

## Environment information ##

**VSCode version**: 1.51.0-insider
**C# Extension**: 1.23.4

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    39d17847db

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\jgrote\AppData\Local\Microsoft\dotnet\sdk\3.1.401\

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  2.1.803 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\sdk]
  3.1.101 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\sdk]
  3.1.102 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\sdk]
  3.1.200 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\sdk]
  3.1.201 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\sdk]
  3.1.401 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Users\jgrote\AppData\Local\Microsoft\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.9.3|
|azurite|Azurite|3.9.0|
|better-align|wwm|1.1.6|
|bracket-pair-colorizer-2|CoenraadS|0.2.0|
|csharp|ms-dotnettools|1.23.4|
|errorlens|usernamehw|3.2.3|
|git-graph|mhutchie|1.27.0|
|gitlens|eamodio|10.2.2|
|indent-rainbow|oderwat|7.4.0|
|markdown-all-in-one|yzhang|3.3.0|
|powershell-preview|ms-vscode|2020.9.0|
|regexp-preview|LouisWT|0.1.5|
|remote-containers|ms-vscode-remote|0.148.0|
|remote-ssh-edit-nightly|ms-vscode-remote|2020.10.29700|
|remote-ssh-nightly|ms-vscode-remote|2020.10.29700|
|rest-client|humao|0.24.3|
|todo-tree|Gruntfuggly|0.0.186|
|vscode-azurefunctions|ms-azuretools|1.0.0|
|vscode-dotnet-runtime|ms-dotnettools|0.1.2|
|vscode-icons|vscode-icons-team|11.0.0|
|vscode-opennewinstance|chrisdias|0.0.7|
|vscode-peacock|johnpapa|3.8.0|
|vscode-sort-json|richie5um2|1.18.1|
|vscode-zipexplorer|slevesque|0.3.1|;

</details>

**Comment by gregg-miskelly** [comment]
CC @captainsafia

**Comment by JustinGrote** [comment]
I worked around this by making a compoundtask
```json
{
  "version": "0.2.0",
  "compounds": [
    {
      "name": "Static Web App",
      "configurations": [
        "AzureFunctions",
        "BlazorClient"
      ],
      "preLaunchTask": "azurite"
    }
  ],
  "configurations": [
    {
      "name": "AzureFunctions",
      "type": "coreclr",
      "request": "attach",
      "processId": "${command:azureFunctions.pickProcess}"
    },
    {
      "name": "BlazorClient",
      "type": "blazorwasm",
      "request": "launch",
      "cwd": "${workspaceFolder}/Client",
      "browser": "edge"
    }
  ]
}
```

**Comment by captainsafia** [comment]
@JustinGrote Nope, we don't support that option.

This issue and #4108 makes me think that we should modify the `blazorwasm` config to take a `childConfig` option which is an object that contains the options that get passed to the .NET and pwa-* debuggers.
