### ISSUE TITLE
Stuck at downloading dependencies

### ISSUE THREAD

**Issue by breadnone** [OmniSharp/omnisharp-vscode#4175]
Stuck at downloading dependencies, and no, my internet does not have issues for anything else except this cursed extension

![omnisuck](https://user-images.githubusercontent.com/64100867/98115985-3a045b80-1eda-11eb-950f-ad0e44c5e8e3.PNG)

**Comment by breadnone** [comment]
Also, this behavior causes Intelisense not working

**Comment by gxtaillon** [comment]
Might be related to #4168

**Comment by breadnone** [comment]
Switched to rider, closing this
