### ISSUE TITLE
No intellisense when consuming a F# project in C# on linux

### ISSUE THREAD

**Issue by mastoj** [OmniSharp/omnisharp-vscode#4179]
I want to use F# to define my types for various reasons. I've just switched to linux and I think what I wants worked on both Windows and also OSX.

What I've done is create one classlib in F#, then one console in C#. In the console app I reference the F# project and it builds and runs, but in VS Code I get no intellisense of the F# types I've defined. I can see that the F# class lib dll is built and copied to the bin folder, but for some reason I don't get intellisense.

* I'm on linux (pop_os)
* Dotnet 3.1.403
* C# extension 1.23.5

Should this work or do I also need to install mono?

**Comment by mastoj** [comment]
I have now also installed mono but that didn't change anything as I see it.

What is interesting is that a colleague of mine had the same issue, but it is working for him on OSX he says.

**Comment by mastoj** [comment]
As a temporary workaround I added the project as a regular reference, but that is somewhat "hacky":

So adding this to my C# project fixes the intellisense issue:

```
  <ItemGroup>
    <Reference Include="Api.Types">
      <HintPath>..\Api.Types\obj\Debug\netstandard2.1\Api.Types.dll</HintPath>
    </Reference>
  </ItemGroup>
```

This works for small set of applicaiton, but it isn't viable in the long term. Is there anything I can do myself or is this a bug in omnisharp?

**Comment by knocte** [comment]
Just did a quick search for previous issues and it seems this is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1623 (whose last comment hints about a possible solution)

**Comment by mastoj** [comment]
you might be right. The possible solution doesn't work using `brew` since I'm on linux. I did install `mono-complete` though but that didn't help. I'll continue the discussion in the longer one and closing this once since it is a duplicate.
