### ISSUE TITLE
Debugger shows wrong value for some parts of an expression

### ISSUE THREAD

**Issue by mellinoe** [OmniSharp/omnisharp-vscode#418]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-002983)

Product Information:
 Version:            1.0.0-preview2-002983
 Commit SHA-1 hash:  90fbc3bb53

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  15.04
 OS Platform: Linux
 RID:         ubuntu.15.04-x64
```
VS Code version: 1.0.0
C# Extension version: 1.0.3-rc2
## Steps to reproduce
Consider this statement:

```CSharp
Matrix4x4.CreatePerspectiveFieldOfView(
    _fieldOfView,
    (float)Window.Width / Window.Height,
    _nearPlane,
    _farPlane);
```

When I debug this statement, Window.Width is equal to 960, and Window.Height is equal to 540. Both are `Int32`.

## Expected  behavior
Width should display 960 when hovered, and Height should display 540.

## Actual behavior
When I hover over "Width", 960 is displayed, as expected. When I hover over "Height", 1.77777779 is displayed. This is actually the result of the entire expression, 960 / 540. Ideally, I would expect that value to be displayed if I hovered over the `/` operator, like in Visual Studio Full.

**Comment by gregg-miskelly** [comment]
@mellinoe do I correctly understand that when you evaluate "Width" in the watch window, you get the correct result? If so, this is a VS Code issue. My guess would be https://github.com/Microsoft/vscode/issues/4059, but it could be something new.

**Comment by mellinoe** [comment]
Yes, that is correct. I can manually evaluate Width in the "Debug Console" pane, and it prints out "540" as expected. I didn't check the watch pane, but it's probably the same. Your other issue sounds like it's the same thing. Feel free to close this one if it's definitely a VS Code issue.
