### ISSUE TITLE
Unity C# intellisense not working properly

### ISSUE THREAD

**Issue by leozhang1** [OmniSharp/omnisharp-vscode#4180]
Hello friends!

My C# vs code intellisense for Unity is not working. For example, I cannot view meta data csharp files when I try cmd + left click on a Unity reference, such as Rigidbody.

I am using a Mac and am on the latest version of omnisharp. And here are my settings:

<img width="494" alt="image" src="https://user-images.githubusercontent.com/43508492/98197305-65943f80-1ef4-11eb-8312-70938fcb6025.png">

omnisharp version:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/43508492/98197328-793fa600-1ef4-11eb-9a59-55641ae2cdca.png">

**Comment by JoeRobich** [comment]
Ensure that you have updated your VSCode Editor package in Unity to version 1.2.3. See the comments in this issue for more details - https://github.com/OmniSharp/omnisharp-vscode/issues/4113#issuecomment-718006809

**Comment by leozhang1** [comment]
Oh I see. Thank you! 🤝

**Comment by JoeRobich** [comment]
@leozhang1 Closing this issue. If you run in to any issues, please let us know.
