### ISSUE TITLE
Add option to specify type for exception breakpoints

### ISSUE THREAD

**Issue by markusroessler** [OmniSharp/omnisharp-vscode#4206]
Version: 1.23.5

Currently it is only possible to break on all (or no) exception types. Please add an option to break on specific exception types.  E.g. I would like to break on System.InvalidOperationException only.
vscode-mono-debug already has an option for this - although it is only possible to filter on some predefined types. see https://github.com/microsoft/vscode/issues/11552#issuecomment-291793725
From my point of view it would be sufficient to be able to enter the exception types in vscode settings.json.

**Comment by gregg-miskelly** [comment]
This supported was added earlier this year. See [documentation](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md#exception-settings) for more information.
