### ISSUE TITLE
Installing the C# extension on musl based linux installs a glibc version of mono

### ISSUE THREAD

**Issue by dev-kittens** [OmniSharp/omnisharp-vscode#4213]
## Environment data
`dotnet --info` output: 
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     alpine
 OS Version:  3.13
 OS Platform: Linux
 RID:         linux-musl-x64
 Base Path:   /root/.dotnet/sdk/3.1.403/

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  3.1.403 [/root/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [/root/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [/root/.dotnet/shared/Microsoft.NETCore.App]
```

VS Code version: cdr/code-server 3.7.1 2bf91ff6a6d1f29a8a93f97684177ccf5388cf34
C# Extension version: v1.23.5

## OmniSharp log

```
Starting OmniSharp server at 11/17/2020, 10:05:12 AM
    Target: /root/git/pluralkit/PluralKit.sln

OmniSharp server started.
    Path: /root/.local/share/code-server/extensions/ms-dotnettools.csharp-1.23.5/.omnisharp/1.37.3/run
    PID: 30810

/root/.local/share/code-server/extensions/ms-dotnettools.csharp-1.23.5/.omnisharp/1.37.3/run: line 27: /root/.local/share/code-server/extensions/ms-dotnettools.csharp-1.23.5/.omnisharp/1.37.3/bin/mono: No such file or directory
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```

## Steps to reproduce

Install VSCode and this extension on a musl-based (non-glibc) OS.

## Expected  behavior

The extension installs a musl version of mono.

## Actual behavior

The extension installs a glibc version of mono, which does not work.

## Notes

- The "No such file or directory" error is just alpine's dumb behaviour. The file does actually exist.
- This can be solved by the user by installing the `gcompat` (glibc compatibility) package on the host, but the extension should not assume this has been done.
- I mentioned my issue in the dotnet server, and @rootwyrm asked me to mention him in this issue.

**Comment by gregg-miskelly** [comment]
This is tracked with #3621

**Comment by dev-kittens** [comment]
i see, thank you. would it be possible to update the title of that issue to reflect that it's related to musl? so it's more easily findable~

**Comment by gregg-miskelly** [comment]
Done.
