### ISSUE TITLE
Enable editorconfig support by default

### ISSUE THREAD

**Issue by ffMathy** [OmniSharp/omnisharp-vscode#4216]
Why is it off? I see issues being opened constantly because it's off per default. Why not just enable it per default, like Visual Studio does?

**Comment by JoeRobich** [comment]
@ffMathy That has been on the backlog for a while now. We will enable it in the next release.

**Comment by JoeRobich** [comment]
EditorConfig is enabled by default in the newly published 1.23.7 release.
