### ISSUE TITLE
Command '.NET: Generate Assets for Build and Debug' resulted in an error.

### ISSUE THREAD

**Issue by Verustus** [OmniSharp/omnisharp-vscode#4219]
## Issue Description ##
Unable to generate assets to build and debug. OmniSharp server is not running.

## Steps to Reproduce ##
1. Create a new console dotnet project.
2. Open it with Visual Studio.
3. Run the '.NET: Generate Assets for Build and Debug command.

## Expected Behavior ##
Creation of the necessary JSON files.

## Actual Behavior ##
Error message:"Unable to generate assets to build and debug. OmniSharp server is not running."

## Environment information ##

**VSCode version**: 1.51.1
**C# Extension**: 1.23.6

<details><summary>Dotnet Information</summary>
Sada .NET SDK (s ohledem na libovoln� soubor global.json):
 Version:   5.0.100
 Commit:    5044b93829

B�hov� prost�ed�:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|angular-console|nrwl|14.0.1|
|angular-essentials|johnpapa|9.0.1|
|Angular2|johnpapa|9.1.2|
|cpptools|ms-vscode|1.1.2|
|csharp|ms-dotnettools|1.23.6|
|debugger-for-chrome|msjsdiag|4.12.11|
|debugger-for-edge|msjsdiag|1.0.15|
|EditorConfig|EditorConfig|0.15.1|
|java|redhat|0.70.0|
|material-icon-theme|PKief|4.4.0|
|ng-template|Angular|0.1100.1|
|prettier-vscode|esbenp|5.7.2|
|vscode-eslint|dbaeumer|2.1.13|
|vscode-icons|vscode-icons-team|11.0.0|
|vscode-npm-script|eg2|0.3.13|
|vscode-peacock|johnpapa|3.8.0|
|vscode-yaml|redhat|0.12.0|
|winteriscoming|johnpapa|1.4.3|;

</details>

**Comment by graememeyer** [comment]
+1 I'm also experiencing this. I've yet to find a combination  of dotnet new project under .NET 5 that works with vscode and the C#/Omnisharp extension

**Comment by gregg-miskelly** [comment]
In case you didn't see this: https://github.com/omnisharp/omnisharp-vscode#note-about-using-net-5-sdks

If that isn't it --
1. Do you otherwise get intellisense in your project?
2. Please add your OmniSharp log

**Comment by Verustus** [comment]
Oh thantks for all, but i open my VS code now and I don't know why but it works now. Before i post this issue I reinstall VS code and do soo many things.
