### ISSUE TITLE
VsCode/Omnisharp doesn't respect excluded folders from project.json

### ISSUE THREAD

**Issue by savpek** [OmniSharp/omnisharp-vscode#422]
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

VS Code version:
1.2

C# Extension version:
1.1.5
## Steps to reproduce

Download either protractor or create .cs file under folder that is excluded in Project.json from compile.

```
  "buildOptions": {
    "emitEntryPoint": true,
    "warningsAsErrors": true,
    "preserveCompilationContext": true,
    "compile": {
      "exclude": [
        "node_modules", 
        "obj", 
        "bower_components", 
        "wwwroot",
        "typings",
        "bin"
        ]
    }
```
## Expected  behavior

Vscode doesn't show errors in "!" menu from excluded files.
## Actual behavior

All errors are shown in files at excluded folders. Protractor in node_modules folder is pain because it contains lots of .cs files.

**Comment by Hunter21007** [comment]
I confirm on vscode 1.2.0 and omnisharp 1.1.5

**Comment by DustinCampbell** [comment]
Hmmm... I'm betting this is coming from the OmniSharp itself. @troydai, did we recently regress this, or did it never work properly?

**Comment by troydai** [comment]
I'll take a look. Assign to myself.

**Comment by code1line** [comment]
Workaround: exclude on top-level...
`
"exclude": ["node_modules","..."],
  "dependencies": {
`

**Comment by Hunter21007** [comment]
Yes, that's what I did.
The only thing is the schema warning
About project.json :)

Jurij Zahn
Sent from mobile device

Am 24.09.2016 11:51 schrieb "Michael Csitkovics" <notifications@github.com>:

**Comment by zeptio** [comment]
I've encountered this issue as well. Been running C# projects in vscode for a long time now, but today (after upgrading to 1.6.1) it throws errors from node_modules. Adding the "exclude" on top-level removes the errors, but now I get a warning when running "dotnet build", which I guess is fine but not ideal.

Has any action been taken on this issue? I'm running version 1.4.1.

**Comment by DustinCampbell** [comment]
I don't think we're going to be addressing this issue for project.json-based .NET Core projects. Our focus has moved to better support for .csproj-based .NET Core porjects.
