### ISSUE TITLE
Incorrect syntax highlighting for contextual when keyword

### ISSUE THREAD

**Issue by zanmato** [OmniSharp/omnisharp-vscode#4229]
## Issue Description ##
Syntax highlighting seems to be incorrect for the contextual `when` keyword when used in a `switch` statement.

## Steps to Reproduce ##
Try writing the following,
```csharp
var a = 1;
var b = 2;
switch (a) {
  case 1 when b == 2:
  // Hello world
  break;
}
```

## Expected Behavior ##
`when` should be highlighted as a keyword.

## Actual Behavior ##
[MS docs highlights `when` as a keyword](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/when) but VSCode highlights when as a variable.  
*Sidenote: It seems like GitHub cannot highlight it correctly either.*  

Adding parentheses seems to highlight `when` as a method name. 
```csharp
var a = 1;
var b = 2;
switch (a) {
  case (1) when (b == 2):
  // Hello world
  break;
}
```

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.51.1
**C# Extension**: 1.23.6

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    39d17847db

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.401/

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  3.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|1.1.2|
|csharp|ms-dotnettools|1.23.6|
|dotnet-test-explorer|formulahendry|0.7.4|
|go|golang|0.18.1|
|hexeditor|ms-vscode|1.3.0|
|php-intellisense|felixfbecker|2.3.14|
|prettier-vscode|esbenp|5.7.2|
|rust|rust-lang|0.7.8|
|vetur|octref|0.30.2|
|vscode-eslint|dbaeumer|2.1.13|
|vscode-intelephense-client|bmewburn|1.5.4|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by filipw** [comment]
this is implemented in semantic highlighting, you can set: 

```
     "editor.semanticHighlighting.enabled": true,
     "csharp.semanticHighlighting.enabled": true,
```

**Comment by zanmato** [comment]
Thanks for the swift reply! TIL about the semantic highlighting option
