### ISSUE TITLE
Versions After 1.23.0 incompatible with Unity Project.

### ISSUE THREAD

**Issue by go3k** [OmniSharp/omnisharp-vscode#4235]
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.51.1
**C# Extension**: 1.23.0

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.0|
|emmylua|tangzx|0.3.49|;

</details>

After install v1.23.6 I got a lot (3K+) errors, and all of these are simply correct codes, I installed .net 4.7.1 dev pack and tried to make this extension work, but can't resolve this problem.

But when i downgrade to v1.23.0 all of these errors disappeared, so need help about this issue.

**Comment by JoeRobich** [comment]
Make sure you updated VSCode Editor package in Unity to version 1.2.3 and regenerate all solution files. The earlier version generated incorrect project files with <ReferenceOutputAssembly>false</ReferenceOutputAssembly> in them.

The older OmniSharp didn't actually respect that setting so it was (accidentally) working fine. However, once we implemented correct handling for ReferenceOutputAssembly MSBuild property, that exposed the problem in VSCode Editor package in Unity, which was only fixed in version 1.2.3.

**Comment by go3k** [comment]
> Make sure you updated VSCode Editor package in Unity to version 1.2.3 and regenerate all solution files. The earlier version generated incorrect project files with false in them.
> 
> The older OmniSharp didn't actually respect that setting so it was (accidentally) working fine. However, once we implemented correct handling for ReferenceOutputAssembly MSBuild property, that exposed the problem in VSCode Editor package in Unity, which was only fixed in version 1.2.3.

Thanks... It works after I upgrade VSCode Editor package to version 1.2.3. My problem.
