### ISSUE TITLE
Machine x64 x86

### ISSUE THREAD

**Issue by sique976** [OmniSharp/omnisharp-vscode#4237]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## OmniSharp log
[WARNING]: x86 Windows is not currently supported by the .NET Core debugger. Debugging will not be available.

**Comment by sique976** [comment]
Well, that´s the second time I tried to finish one of my classes and I have this message telling me that the debugger won´t work. I would like to know what version of Visual Studio Code I could install on my machine so I do not have this kind of issue.

**Comment by gregg-miskelly** [comment]
@sique976 This is because you have an x86 version of Window. You could install [Visual Studio Community](https://visualstudio.microsoft.com/downloads/) (or any other edition of full Visual Studio). Alternatively, if you really want debugging and you want Visual Studio Code you would need to either reinstall an x64 version of Windows if your computer supports it, or buy a new computer which is already running x64 Windows.

**Comment by sique976** [comment]
Hail Mr. Miskelly! That´s it! You´re right! If I´m already a developer certainly I´d buy a new one. With all due respect of your reply. By the way, good evening! Here in Brazil is 11:25PM. You know what? Of course you Know! I can debug using the developer tools (I just discover  today) and I have just finished downloading Visual Studio 2019.
I really appreciate your reply. Thanks a lot ´bout it. And please excuse any miswritten English words.
Tears!!

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Gregg Miskelly<mailto:notifications@github.com>
Enviado:segunda-feira, 30 de novembro de 2020 21:03
Para: OmniSharp/omnisharp-vscode<mailto:omnisharp-vscode@noreply.github.com>
Cc:San Barbosa<mailto:saludematt@outlook.com>; Mention<mailto:mention@noreply.github.com>
Assunto: Re: [OmniSharp/omnisharp-vscode] Machine x64 x86 (#4237)


@sique976<https://github.com/sique976> This is because you have an x86 version of Window. You could install Visual Studio Community<https://visualstudio.microsoft.com/downloads/> (or any other edition of full Visual Studio). Alternatively, if you really want debugging and you want Visual Studio Code you would need to either reinstall an x64 version of Windows if your computer supports it, or buy a new computer which is already running x64 Windows.
