### ISSUE TITLE
Question regarding formatting

### ISSUE THREAD

**Issue by adamfriedland** [OmniSharp/omnisharp-vscode#4239]
Just a quick question. Has `Omnisharp` at some point from it's inception until now ever enforced braces on the same line by default?

i.e. 
```
void foo() {
    if (something) {
        bar();
    } else {
        baz();
    }
}
```

as opposed to the standard prescribed by the C# team:
```
void foo() 
{
    if (something) 
    {
        bar();
    } 
    else 
    {
        baz();
    }
}
```

**Comment by chestermjr** [comment]
Here's how to fix that. Don't forget step 3.

1. Create file named `omnisharp.json` in the root of your repo.
2. In the file, enter:
```
{
    "FormattingOptions": {
        "NewLinesForBracesInLambdaExpressionBody": false,
        "NewLinesForBracesInAnonymousMethods": false,
        "NewLinesForBracesInAnonymousTypes": false,
        "NewLinesForBracesInControlBlocks": false,
        "NewLinesForBracesInTypes": false,
        "NewLinesForBracesInMethods": false,
        "NewLinesForBracesInProperties": false,
        "NewLinesForBracesInObjectCollectionArrayInitializers": false,
        "NewLinesForBracesInAccessors": false,
        "NewLineForElse": false,
        "NewLineForCatch": false,
        "NewLineForFinally": false
    }
}
```

3. Restart VSCode

Source: https://nosuchstudio.medium.com/formatting-curly-braces-on-the-same-line-in-c-in-vscode-c4937e1c215f

**Comment by adamfriedland** [comment]
Hi @chestermjr,

That's not what I was actually asking. Just wanted to know if historically, Omnisharp has ever enforced Javascript-esque formatting.

**Comment by filipw** [comment]
No it was always using default Roslyn settings as its defaults which are C# specific.
