### ISSUE TITLE
"Type or namespace name ... could not be found" for some symbols

### ISSUE THREAD

**Issue by mr** [OmniSharp/omnisharp-vscode#4242]
## Issue Description ##
Opened a Unity project that previously worked and now some symbols are not recognized.
## Steps to Reproduce ##
Open project
## Expected Behavior ##
No errors
## Actual Behavior ##
Several erroneous errors about missing symbols. In the logs there a System.ArgumentOutOfRangeException as a response.
### OmniSharp log ###
<details>
Starting OmniSharp server at 11/26/2020, 9:44:34 AM
    Target: /home/megan/w/CVTest/CVTest.sln

OmniSharp server started with Mono 6.8.0.
    Path: /home/megan/.vscode/extensions/ms-dotnettools.csharp-1.23.6/.omnisharp/1.37.3/omnisharp/OmniSharp.exe
    PID: 2983

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on fedora 33.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.8.0 - "/home/megan/.vscode/extensions/ms-dotnettools.csharp-1.23.6/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/megan/.vscode/extensions/ms-dotnettools.csharp-1.23.6/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.8.0 - "/home/megan/.vscode/extensions/ms-dotnettools.csharp-1.23.6/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/megan/.vscode/extensions/ms-dotnettools.csharp-1.23.6/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/megan/.vscode/extensions/ms-dotnettools.csharp-1.23.6/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/megan/.vscode/extensions/ms-dotnettools.csharp-1.23.6/.omnisharp/1.37.3/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/megan/w/CVTest'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/megan/w/CVTest/CVTest.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/megan/w/CVTest/UnityEngine.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/megan/w/CVTest/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/megan/w/CVTest/Unity.2D.Sprite.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/megan/w/CVTest/UnityEditor.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/megan/w/CVTest/Unity.2D.Tilemap.Editor.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/megan/w/CVTest'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/megan/w/CVTest/UnityEngine.UI.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/megan/w/CVTest' on host 2831.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/megan/w/CVTest/UnityEngine.UI.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/megan/w/CVTest/UnityEngine.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/megan/w/CVTest/Assembly-CSharp.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/megan/w/CVTest/Assembly-CSharp.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/megan/w/CVTest/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/megan/w/CVTest/Unity.2D.Sprite.Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/megan/w/CVTest/Unity.2D.Sprite.Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/megan/w/CVTest/Unity.2D.Sprite.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/megan/w/CVTest/UnityEditor.UI.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/megan/w/CVTest/UnityEditor.UI.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/megan/w/CVTest/UnityEditor.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/megan/w/CVTest/Unity.2D.Tilemap.Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/megan/w/CVTest/Unity.2D.Tilemap.Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/megan/w/CVTest/Unity.2D.Tilemap.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: UnityEngine.UI
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.2D.Sprite.Editor
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: UnityEditor.UI
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.2D.Tilemap.Editor
[fail]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 8,
  "Command": "/v2/highlight",
  "Running": true,
  "Success": false,
  "Message": "\"System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.\\nParameter name: line\\n  at Microsoft.CodeAnalysis.Text.LinePosition..ctor (System.Int32 line, System.Int32 character) [0x00004] in <74e762f007514b0991a005183ec8dcb2>:0 \\n  at OmniSharp.Roslyn.CSharp.Services.SemanticHighlight.SemanticHighlightService.Handle (OmniSharp.Models.SemanticHighlight.SemanticHighlightRequest request) [0x00146] in <8ca5e445b15640a0986680e5a0180b25>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].GetFirstNotEmptyResponseFromHandlers (OmniSharp.Endpoint.Exports.ExportHandler`2[TRequest,TResponse][] handlers, TRequest request) [0x00099] in <9e06207949b04d41ac60c7c691c8ecbb>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].HandleRequestForLanguage (System.String language, TRequest request, OmniSharp.Protocol.RequestPacket packet) [0x00163] in <9e06207949b04d41ac60c7c691c8ecbb>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].Process (OmniSharp.Protocol.RequestPacket packet, OmniSharp.Endpoint.LanguageModel model, Newtonsoft.Json.Linq.JToken requestObject) [0x0024b] in <9e06207949b04d41ac60c7c691c8ecbb>:0 \\n  at OmniSharp.Stdio.Host.HandleRequest (System.String json, Microsoft.Extensions.Logging.ILogger logger) [0x000e7] in <add5f40a6e784fcca3e930b59965388b>:0 \"",
  "Body": null,
  "Seq": 66,
  "Type": "response"
}
[fail]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 14,
  "Command": "/v2/highlight",
  "Running": true,
  "Success": false,
  "Message": "\"System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.\\nParameter name: line\\n  at Microsoft.CodeAnalysis.Text.LinePosition..ctor (System.Int32 line, System.Int32 character) [0x00004] in <74e762f007514b0991a005183ec8dcb2>:0 \\n  at OmniSharp.Roslyn.CSharp.Services.SemanticHighlight.SemanticHighlightService.Handle (OmniSharp.Models.SemanticHighlight.SemanticHighlightRequest request) [0x00146] in <8ca5e445b15640a0986680e5a0180b25>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].GetFirstNotEmptyResponseFromHandlers (OmniSharp.Endpoint.Exports.ExportHandler`2[TRequest,TResponse][] handlers, TRequest request) [0x00099] in <9e06207949b04d41ac60c7c691c8ecbb>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].HandleRequestForLanguage (System.String language, TRequest request, OmniSharp.Protocol.RequestPacket packet) [0x00163] in <9e06207949b04d41ac60c7c691c8ecbb>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].Process (OmniSharp.Protocol.RequestPacket packet, OmniSharp.Endpoint.LanguageModel model, Newtonsoft.Json.Linq.JToken requestObject) [0x0024b] in <9e06207949b04d41ac60c7c691c8ecbb>:0 \\n  at OmniSharp.Stdio.Host.HandleRequest (System.String json, Microsoft.Extensions.Logging.ILogger logger) [0x000e7] in <add5f40a6e784fcca3e930b59965388b>:0 \"",
  "Body": null,
  "Seq": 83,
  "Type": "response"
}
</details>

### C# log ###
<details>empty</details>

## Environment information ##

**VSCode version**: 1.51.1
**C# Extension**: 1.23.6

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.8.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.109
 Commit:    32ced2d411

Runtime Environment:
 OS Name:     fedora
 OS Version:  33
 OS Platform: Linux
 RID:         fedora.33-x64
 Base Path:   /usr/lib64/dotnet/sdk/3.1.109/

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  3.1.109 [/usr/lib64/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|ayu|teabyii|0.20.1|
|csharp|ms-dotnettools|1.23.6|
|haskell|haskell|1.2.0|
|language-haskell|justusadam|3.3.0|
|material-icon-theme|PKief|4.4.0|
|material-palenight-theme|whizkydee|2.0.1|
|material-theme|zhuangtongfa|3.9.11|
|monokai-operator-theme|markfknight|4.0.0|
|night-owl|sdras|2.0.0|
|nord-operator-theme|Chad|1.0.0|
|one-monokai|azemoh|0.5.0|
|one-monokai-italics|iamkd|0.4.0|
|operatormonodarktheme|Valiantsin|1.0.1|
|snazzy-operator-plus|bsides|1.2.1|
|theme-dracula|dracula-theme|2.22.3|
|tomorrow-and-tomorrow-night-operator-mono-theme|chiragpat|0.0.6|
|tomorrow-and-tomorrow-night-operator-mono-theme-tweaked|stonebuddha|0.1.1|
|twilight-operator|stevemcgrath|0.0.1|
|unity-debug|Unity|3.0.2|
|vim|vscodevim|1.17.1|
|vsc-community-material-theme|Equinusocio|1.4.2|
|vsc-material-theme-icons|equinusocio|1.2.0|
|vscode-great-icons|emmanuelbeziat|2.1.61|
|vscode-simple-icons|LaurentTreguier|1.13.5|
|vscode-theme-onedark|akamud|2.2.2|
|winteriscoming|johnpapa|1.4.3|;

</details>

**Comment by filipw** [comment]
For Mono-based development (e.g. Unity) that requires full .NET framework, you need to set `"omnisharp.useGlobalMono": "always"` in VS Code settings.

This is mentioned in the known issues in release notes - https://github.com/OmniSharp/omnisharp-vscode/blob/8f7b3d21b5cdb04d6cf725302503d91099d95164/CHANGELOG.md#known-issues-in-1236

**Comment by mr** [comment]
I am using global mono. it was in my output above: "OmniSharp using global mono :6.8.0". It looks like it's having problems importing Unity symbols specifically.

**Comment by filipw** [comment]
according to your log:

```
Located 1 MSBuild instance(s)
1: StandAlone 16.8.0 - "/home/megan/.vscode/extensions/ms-dotnettools.csharp-1.23.6/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin"
```

Only the standalone Mono is discovered by OmniSharp - it doesn't see the global Mono. This could happen when you have a non-standard Mono installation location (though I am not too familiar with Fedora). Could you try reinstalling global Mono using the official installer https://www.mono-project.com/download/stable/#download-lin-fedora?

Additionally make sure you updated VSCode Editor package in Unity to version 1.2.3 and regenerate all solution files. The earlier version generated invalid project files which causes load issues in new OmniSharp builds.

**Comment by mr** [comment]
The error has changed slightly
```
Starting OmniSharp server at 11/26/2020, 11:03:25 AM
    Target: /home/megan/w/CVTest/CVTest.sln

OmniSharp server started with Mono 6.12.0.
    Path: /home/megan/.vscode/extensions/ms-dotnettools.csharp-1.23.6/.omnisharp/1.37.3/omnisharp/OmniSharp.exe
    PID: 15674

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on fedora 33.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.8.0 - "/usr/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.8.0 - "/home/megan/.vscode/extensions/ms-dotnettools.csharp-1.23.6/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.8.0 - "/usr/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /home/megan/.vscode/extensions/ms-dotnettools.csharp-1.23.6/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/megan/w/CVTest'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/megan/w/CVTest/CVTest.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/megan/w/CVTest/UnityEngine.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/megan/w/CVTest/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/megan/w/CVTest/Unity.2D.Sprite.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/megan/w/CVTest/UnityEditor.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/megan/w/CVTest/Unity.2D.Tilemap.Editor.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/megan/w/CVTest'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/megan/w/CVTest' on host 15518.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/megan/w/CVTest/UnityEngine.UI.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/megan/w/CVTest/UnityEngine.UI.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/megan/w/CVTest/UnityEngine.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/megan/w/CVTest/Assembly-CSharp.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/megan/w/CVTest/Assembly-CSharp.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/megan/w/CVTest/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/megan/w/CVTest/Unity.2D.Sprite.Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/megan/w/CVTest/Unity.2D.Sprite.Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/megan/w/CVTest/Unity.2D.Sprite.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/megan/w/CVTest/UnityEditor.UI.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/megan/w/CVTest/UnityEditor.UI.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/megan/w/CVTest/UnityEditor.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/megan/w/CVTest/Unity.2D.Tilemap.Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/megan/w/CVTest/Unity.2D.Tilemap.Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/megan/w/CVTest/Unity.2D.Tilemap.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: UnityEngine.UI
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.2D.Sprite.Editor
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: UnityEditor.UI
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Unity.2D.Tilemap.Editor
[fail]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 14,
  "Command": "/v2/highlight",
  "Running": true,
  "Success": false,
  "Message": "\"System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.\\nParameter name: line\\n  at Microsoft.CodeAnalysis.Text.LinePosition..ctor (System.Int32 line, System.Int32 character) [0x00004] in <74e762f007514b0991a005183ec8dcb2>:0 \\n  at OmniSharp.Roslyn.CSharp.Services.SemanticHighlight.SemanticHighlightService.Handle (OmniSharp.Models.SemanticHighlight.SemanticHighlightRequest request) [0x00146] in <8ca5e445b15640a0986680e5a0180b25>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].GetFirstNotEmptyResponseFromHandlers (OmniSharp.Endpoint.Exports.ExportHandler`2[TRequest,TResponse][] handlers, TRequest request) [0x00099] in <9e06207949b04d41ac60c7c691c8ecbb>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].HandleRequestForLanguage (System.String language, TRequest request, OmniSharp.Protocol.RequestPacket packet) [0x00163] in <9e06207949b04d41ac60c7c691c8ecbb>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].Process (OmniSharp.Protocol.RequestPacket packet, OmniSharp.Endpoint.LanguageModel model, Newtonsoft.Json.Linq.JToken requestObject) [0x0024b] in <9e06207949b04d41ac60c7c691c8ecbb>:0 \\n  at OmniSharp.Stdio.Host.HandleRequest (System.String json, Microsoft.Extensions.Logging.ILogger logger) [0x000e7] in <add5f40a6e784fcca3e930b59965388b>:0 \"",
  "Body": null,
  "Seq": 76,
  "Type": "response"
}
[fail]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 28,
  "Command": "/v2/highlight",
  "Running": true,
  "Success": false,
  "Message": "\"System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.\\nParameter name: line\\n  at Microsoft.CodeAnalysis.Text.LinePosition..ctor (System.Int32 line, System.Int32 character) [0x00004] in <74e762f007514b0991a005183ec8dcb2>:0 \\n  at OmniSharp.Roslyn.CSharp.Services.SemanticHighlight.SemanticHighlightService.Handle (OmniSharp.Models.SemanticHighlight.SemanticHighlightRequest request) [0x00146] in <8ca5e445b15640a0986680e5a0180b25>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].GetFirstNotEmptyResponseFromHandlers (OmniSharp.Endpoint.Exports.ExportHandler`2[TRequest,TResponse][] handlers, TRequest request) [0x00099] in <9e06207949b04d41ac60c7c691c8ecbb>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].HandleRequestForLanguage (System.String language, TRequest request, OmniSharp.Protocol.RequestPacket packet) [0x00163] in <9e06207949b04d41ac60c7c691c8ecbb>:0 \\n  at OmniSharp.Endpoint.EndpointHandler`2[TRequest,TResponse].Process (OmniSharp.Protocol.RequestPacket packet, OmniSharp.Endpoint.LanguageModel model, Newtonsoft.Json.Linq.JToken requestObject) [0x0024b] in <9e06207949b04d41ac60c7c691c8ecbb>:0 \\n  at OmniSharp.Stdio.Host.HandleRequest (System.String json, Microsoft.Extensions.Logging.ILogger logger) [0x000e7] in <add5f40a6e784fcca3e930b59965388b>:0 \"",
  "Body": null,
  "Seq": 92,
  "Type": "response"
}
```

**Comment by mr** [comment]
Oh after also regenerating files it looks like it figured everything out! Thanks!

**Comment by filipw** [comment]
thanks for confirming! 👏
