### ISSUE TITLE
`new` with specified type, double `as`, and `??`  breaks syntax highlighting

### ISSUE THREAD

**Issue by Ghostbird** [OmniSharp/omnisharp-vscode#4243]
## Issue Description ##

Syntax highlighting breaks in an oddly specific case. Once it breaks, it's broken to the EOF. I ran into this in a real piece of code and managed to distill it to the examples shown below.

As I write this, I see that Github's syntax highlighting breaks in _exactly_ the same way.

### TL;DR; Workaround ###

Wrap the part that breaks in parentheses as shown below

## Steps to Reproduce ##

Try these code fragments

List
```csharp
new List<string> {
  "a" as string ?? "b" as string,
};
```
`new` with known type. (Ignore the fact that `Example` doesn't actually exist, it does not affect the example)
```csharp
new Example {
  Name = "a" as string ?? "b" as string,
};
```
Anonymous type
```csharp
new {
  Name = "a" as string ?? "b" as string,
};
```
List without comma
```csharp
new List<string> {
  "a" as string ?? "b" as string
};
```
**Workaround** with parentheses
```csharp
new List<string> {
  "a" as string ?? ("b" as string),
};
```
## Expected Behavior ##

The syntax highlighting works in all cases

## Actual Behavior ##

In the first two snippets, the final `as string` breaks.
The next two snippets illustrate that it is at least somewhat related to the Type specified before the `{`, and the comma at the end of the line.
The last snippet illustrates the workaround I'm using, wrap the part that breaks in parentheses.

## Logs ##
No relevant logging found

## Environment information ##

**VSCode version**: 1.51.1
**C# Extension**: 1.23.6

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.404
 Commit:    470f6754b3

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.404/

Host (useful for support):
  Version: 3.1.10
  Commit:  1721e39439

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]
  3.1.404 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|atlascode|atlassian|2.8.5|
|clipboard-history|Anjali|1.0.7|
|csharp|ms-dotnettools|1.23.6|
|docomment|k--kato|0.1.19|
|dotnet-test-explorer|formulahendry|0.7.4|
|git-graph|mhutchie|1.27.0|
|gitlens|eamodio|11.0.5|
|markdown-all-in-one|yzhang|3.4.0|
|swap-selection-with-clipboard|LukaszPolowczyk|1.2.3|
|sync-scroll|dqisme|1.3.0|
|todo-tree|Gruntfuggly|0.0.188|
|vscode-markdownlint|DavidAnson|0.37.2|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-pull-request-github|GitHub|0.21.2|
|vscode-yaml|redhat|0.13.0|;

</details>

**Comment by filipw** [comment]
Both Github and the C# extension for VS Code use static textmate grammar for syntax highlighting out of the box. It doesn't have semantic understanding of the C# language and is quite limited.

However, VS Code now has semantic highlighting support and OmniSharp supports that by using C# compiler powered highlighting (like Visual Studio does). This is by far superior and you can enable it by setting:

```
    "editor.semanticHighlighting.enabled": true,
    "csharp.semanticHighlighting.enabled": true
```

**Comment by Ghostbird** [comment]
Ah, thanks a lot. When I enable the semantic syntax highlighting, it works correctly.

**Comment by Ghostbird** [comment]
> Both Github and the C# extension for VS Code use static textmate grammar for syntax highlighting out of the box. It doesn't have semantic understanding of the C# language and is quite limited.
> 
> However, VS Code now has semantic highlighting support and OmniSharp supports that by using C# compiler powered highlighting (like Visual Studio does). This is by far superior and you can enable it by setting:
> 
> ```
>     "editor.semanticHighlighting.enabled": true,
>     "csharp.semanticHighlighting.enabled": true
> ```

My Omnisharp had becom **maddeningly** slow. Just opening vscode would hang for a while and then fire 400-500 `TaskCanceledException`s. Almost every interaction with Omnisharp would hang for tens of seconds and then fire `TaskCanceledException`s. And then still not show the tooltip/completion. It drove me _insane_!

One day I found out it worked normally again when I disabled semantic syntax highlighting. So now I'm stuck with broken syntax highlighting in my source again, but at least I can work again.

Alas using semantic syntax highlighting is no longer an option.
