### ISSUE TITLE
Support max_line_length from editor config

### ISSUE THREAD

**Issue by mateuszlewko** [OmniSharp/omnisharp-vscode#4248]
This is a feature request for supporting `max_line_length` property from the `.editorconfig` file. 

Currently this is not enforced in any way. `max_line_length` property determines line length and should enforce wrapping lines that exceed `max_line_length` characters.

**Comment by filipw** [comment]
This is tracked by https://github.com/dotnet/roslyn/issues/15406
OmniSharp uses .editorconfig implementation from the Roslyn repo.

Once it's implemented there, it will work in OmniSharp too.

**Comment by filipw** [comment]
I will close this as duplicate - we already have one issue like this for OmniSharp in https://github.com/OmniSharp/omnisharp-roslyn/issues/1478
