### ISSUE TITLE
Intellisense for Constructors missing critical information

### ISSUE THREAD

**Issue by sokket** [OmniSharp/omnisharp-vscode#425]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003024)

Product Information:
 Version:            1.0.0-preview2-003024
 Commit SHA-1 hash:  ef4a8e85ef

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version: 1.3.0-insider (1.3.0-insider)
C# Extension version: 1.1.5

## Steps to reproduce
1) Create a new C# project
2) Add ```using System.Net.Sockets```
3) Add ```Socket listen = new Socket(```

## Expected  behavior
Intellisense shows the constructors with the parameter options and order

## Actual behavior
Intellisense tells that there are multiple constructors but without what the parameters are or what order or types

**Comment by DustinCampbell** [comment]
Hi! Thanks for contacting us about this issue. We're tracking this particular bug with https://github.com/OmniSharp/omnisharp-vscode/issues/36.
