### ISSUE TITLE
Integrating with debugging capabilities?

### ISSUE THREAD

**Issue by ffMathy** [OmniSharp/omnisharp-vscode#4253]
I'd love to be able to write an extension like Ozcode or something similar for VS Code, or show a specific UI when a breakpoint has been hit. Is that possible?

I haven't been able to find it in the documentation. I'd love if that was possible somehow, so that we (as extension devs) could enrich the Omnisharp experience.

**Comment by gregg-miskelly** [comment]
If you are talking about the UI extensions that Ozcode adds: that is really more of a question for the VS Code team, but here are some links.
* General extension documentation: https://code.visualstudio.com/api
* Example of using the `vscode.debug` API: https://github.com/OmniSharp/omnisharp-vscode/pull/2775

**Comment by ffMathy** [comment]
@gregg-miskelly can I somehow "hook in to" an event that triggers once VS Code enters debug mode (hitting a breakpoint)?

**Comment by gregg-miskelly** [comment]
Here is there API: https://github.com/microsoft/vscode/blob/c96643feab09926d21cc0559579dcffe71017d54/src/vs/vscode.d.ts#L11676

I don't see an event like that, but maybe I am missing something.

**Comment by ffMathy** [comment]
Can I get the stack trace of a session created by Omnisharp, from another extension?

**Comment by gregg-miskelly** [comment]
Yes. See the PR that I linked to as an example of sending [Debug Adapter Protocol](https://github.com/Microsoft/debug-adapter-protocol/blob/gh-pages/debugAdapterProtocol.json) requests.
