### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by ffMathy** [OmniSharp/omnisharp-vscode#4255]
> {
>   "Request_seq": 35,
>   "Command": "/v2/highlight",
>   "Running": true,
>   "Success": false,
>   "Message": "\"System.ArgumentOutOfRangeException: Det angivne argument lå uden for det gyldige værdiområde.\\r\\nParameternavn: line\\r\\n   ved Microsoft.CodeAnalysis.Text.LinePosition..ctor(Int32 line, Int32 character)\\r\\n   ved OmniSharp.Roslyn.CSharp.Services.SemanticHighlight.SemanticHighlightService.<Handle>d__1.MoveNext() i D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn.CSharp\\\\Services\\\\SemanticHighlight\\\\SemanticHighlightService.cs:linje 36\\r\\n--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---\\r\\n   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   ved OmniSharp.Endpoint.EndpointHandler`2.<GetFirstNotEmptyResponseFromHandlers>d__19.MoveNext()\\r\\n--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---\\r\\n   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   ved OmniSharp.Endpoint.EndpointHandler`2.<HandleRequestForLanguage>d__20.MoveNext() i D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:linje 230\\r\\n--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---\\r\\n   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   ved OmniSharp.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() i D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:linje 131\\r\\n--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---\\r\\n   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   ved OmniSharp.Stdio.Host.<HandleRequest>d__13.MoveNext() i D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Stdio\\\\Host.cs:linje 215\"",
>   "Body": null,
>   "Seq": 133,
>   "Type": "response"
> }

**Comment by filipw** [comment]
duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/4255
