### ISSUE TITLE
Doesn't do anything.

### ISSUE THREAD

**Issue by DaMammoth** [OmniSharp/omnisharp-vscode#4256]
VS Code version: 1.51.1 
C# Extension v1.23.6

What I would like:
I would like it do do ANY of the things advertised in the extension, but it does literally NOTHING.

What happens:
A waste of time. I'm not sure whats _supposed_ to happen, but whatever it is, doesn't work at all.

**Comment by JoeRobich** [comment]
@DaMammoth Sorry you are having issue with the extension. Can you share the OmniSharp log from the Output pane of VS Code so that we can try to help resolve the issues you are seeing?

**Comment by DaMammoth** [comment]
There was no log. The extension does nothing for me.

**Comment by DaMammoth** [comment]
Also, I'm sorry if my issue came out as aggressive. I am having a really hard time with Visual Studio Code, and this problem hasn't helped.

**Comment by JoeRobich** [comment]
Can you describe how you are using the extension? The extension works best when opening a folder that contains your .csproj or .sln files.

**Comment by JoeRobich** [comment]
If you are new to using C# with VS Code, this tutorial and see if it works better https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code

**Comment by JoeRobich** [comment]
> Also, I'm sorry if my issue came out as aggressive. I am having a really hard time with Visual Studio Code, and this problem hasn't helped.

No worries. I think we've all been frustrated with technology before =)

**Comment by DaMammoth** [comment]
Thanks so much, I'll make sure to check out the tutorial.
