### ISSUE TITLE
Visual Studio Code on exit kills a external .exe process to which a C# debugger is attached

### ISSUE THREAD

**Issue by artur170dx** [OmniSharp/omnisharp-vscode#4264]
## Issue Description ##
Hello. I am using vs code and ms-dotnettools.csharp extension to debug an external .exe process written in C# .NET 4.6 Framework. I am attaching to this process with below configuration

```
"configurations": [
     {
         "name": "Attach to ConsoleApp",
         "type":"clr",
         "request": "attach",
         "processName": "ConsoleApp",
     }]
```
This works pretty fine to the point when I close Visual Studio Code after a breakpoint is hit and make some debug steps. The application to which the process was attached crashes without any information, even the windows Event viewer is empty of any information. However, stopping the debugger, without closing the VSCode works very fine, this is why I assume this could be a vscode issue, not the C# extension itself. Although this crash is not happening each time, for example, I more often reproduce it on a slower VM than on a faster local system.

It looks like the extension is not properly reacting to vscode exit action. I already tried manually disconnect the debugger on vscode closing. In custom vscode extension I executed `workbench.action.debug.disconnect` command in the `deactivate` method, which is executed on vscode closing, but it changed nothing. Made the same issue on vscode github repo [here](https://github.com/microsoft/vscode/issues/111891), but was closed and advised to create the issue here.

## Steps to Reproduce ##

1. Build a .NET x64 exe application with DebugType portable
2. Run the exe.
3. Open VSCode with C# extension.
4. Run the debugger that will attach to the running exe.
5. Place a breakpoint.
6. Breakpoint is hit.
7. Make some debug steps.
8. Close Visual Studio Code.

## Expected Behavior ##
The .exe to which the debugger was attached is NOT crushing and continues to run.

## Actual Behavior ##
The .exe to which the debugger was attached crash without any information.

## Logs ##
No logs are availabe.

## Environment information ##

**VSCode version**: 1.51.1
**C# Extension**: 1.23.6

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.6|;

</details>

**Comment by gregg-miskelly** [comment]
If you stop debugging build you close VS Code to you see this same behavior?

**Comment by artur170dx** [comment]
> 
> If you stop debugging build you close VS Code to you see this same behavior?

No, when I stop the debugger with `workbench.action.debug.disconnect` (red square) and then close the VS Code, the process, to which the debugger was attached, continues to run as it suppose to. The application process only crashes when I close the VSCode while the debugger is running or it is stopped on a breakpoint.

**Comment by gregg-miskelly** [comment]
I believe what is going on is that if you hit the `disconnect` button then VS Code will wait for the debugger to successfully complete the `disconnect` DAP request, but in the case of shutdown VS Code will send a `disconnect` DAP request and then either not wait at all or wait only a very short amount of time before it terminates the debug adapter process. If so, there is nothing this extension can do about this. I think VS Code would need to change their behavior if you close the IDE while debugging is happening to address this.
