### ISSUE TITLE
About Intellisense for unity scripts in visualcode

### ISSUE THREAD

**Issue by grpnpraveen** [OmniSharp/omnisharp-vscode#4268]
Issue Type: <b>Bug</b>

I have installed all the latest required .NET and other requirements but the omnisharp is not loading the project files to the vscode.Its not only mine and other users also.I didn,t find answers in reddit,stackoverflow and even unityform.

please take it into consideration
 It still asking  .NET 4.7.1
but latest is 5

Extension version: 1.23.6
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

**Comment by filipw** [comment]
> It still asking .NET 4.7.1

This is a Unity issue not VS Code issue. Unity projects are .NET Framework projects.
.NET 5 is not a continuation of .NET Framework 4.7.1 but instead a continuation of .NET Core 3.1.

You should install .NET Framework 4.7.1 Developer Pack as mentioned in the error.
