### ISSUE TITLE
OmniSharp Stop Working with Odd Multi-Byte characters

### ISSUE THREAD

**Issue by nabychan** [OmniSharp/omnisharp-vscode#427]
## Environment data
`dotnet --info` output:NET Command Line Tools (1.0.0-preview2-002864)/windows 10-10586-x64
VS Code version:1.20
C# Extension version:1.0.11

## Steps to reproduce
1. open a solution
2. type some code like below, with odd Chinese characters
``` C#
ExceptionHelper.ThrowIfTrue(userId==entity.uid, "uid", "不存在");
```
3. reopen the solution, it works(showing references, definitions ...)
4. in the same file, OmniSharp will not work when you type any code
## Expected  behavior
OmniSharp works well with any characters

## Actual behavior
OmniSharp stop working

**Comment by DustinCampbell** [comment]
I suspect this will be addressed with https://github.com/OmniSharp/omnisharp-roslyn/pull/598.
