### ISSUE TITLE
What is Runtime Licenses?

### ISSUE THREAD

**Issue by Maniues** [OmniSharp/omnisharp-vscode#4273]
What is this Runtime Licenses directory? Does it need proprietary software to build an extension?

**Comment by gregg-miskelly** [comment]
> What is this Runtime Licenses directory?

It is the folder where we have put the licenses for the official release of the C# extension (the one that comes from the VS Code Marketplace).

> Does it need proprietary software to build an extension?

I am assuming what you are asking is - "Is proprietary software needed to build the code in this repo?" If I have your question correct, then I believe the answer is "no". Here is the [ThirdPartyNotices.txt](https://github.com/OmniSharp/omnisharp-vscode/blob/master/ThirdPartyNotices.txt) file which should have any third party software used in this repo.

**Comment by Maniues** [comment]
Thanks for explaining it to me.

> I am assuming what you are asking is - "Is proprietary software needed to build the code in this repo?" If I have your question correct, then I believe the answer is "no". Here is the [ThirdPartyNotices.txt](https://github.com/OmniSharp/omnisharp-vscode/blob/master/ThirdPartyNotices.txt) file which should have any third party software used in this repo.
Yes, that's a good interpretation. Thank you
