### ISSUE TITLE
System.Text.RegularExpressions does not exist in .csx files

### ISSUE THREAD

**Issue by hitochan777** [OmniSharp/omnisharp-vscode#4274]
## Issue Description ##
`using System.Text.RegularExpressions` gives me the error as shown in the screenshot below.
I guess this issue is the same as an issue #1581 resolved almost two years ago, but I am still seeing this error in the latest version.

![image](https://user-images.githubusercontent.com/6002787/101412470-0461f080-3926-11eb-934b-c33404f7a09e.png)

## Steps to Reproduce ##

Put `using System.Text.RegularExpressions;` at the top of csx file

## Expected Behavior ##
It should not give any error.

## Actual Behavior ##
As described in the issue description above.

## Environment information ##

**VSCode version**: 1.51.1
**C# Extension**: 1.23.6

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.100/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.9.4|
|csharp|ms-dotnettools|1.23.6|
|go|golang|0.19.0|
|iceberg|harg|1.2.0|
|jupyter|ms-toolsai|2020.11.399280825|
|prettier-vscode|esbenp|5.8.0|
|prisma|Prisma|2.12.1|
|python|ms-python|2020.11.371526539|
|remote-wsl|ms-vscode-remote|0.51.4|
|vetur|octref|0.30.3|
|vim|vscodevim|1.18.0|
|vscode-azurefunctions|ms-azuretools|1.0.1|
|vscode-cosmosdb|ms-azuretools|0.15.1|
|vscode-docker|ms-azuretools|1.8.1|
|vscode-eslint|dbaeumer|2.1.13|
|vscode-react-snippet|NicholasHsiang|0.0.6|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|;

</details>

**Comment by filipw** [comment]
this is by design. `System.Text.RegularExpressions.dll` is not loaded by default, because [it is not loaded by default by CSI too](https://github.com/dotnet/roslyn/blob/master/src/Interactive/csi/csi.desktop.rsp).

However you can just reference it manually using `#r "System.Text.RegularExpressions"` (this is what the linked bug fixed).

<img width="988" alt="Screenshot 2020-12-07 at 23 34 19" src="https://user-images.githubusercontent.com/1710369/101413712-048dcc00-38e5-11eb-85e5-d50c56bdbb33.png">

**Comment by hitochan777** [comment]
Oh I see. Thank you so much for the info.
