### ISSUE TITLE
How do I use version 16.8 of MSBuild for .NET 5 SDK?

### ISSUE THREAD

**Issue by cdacones** [OmniSharp/omnisharp-vscode#4276]
The documentation states .NET 5 SDK requires version 16.8 of MSBuild. I don't know how to set or install this particular version. I'm trying to create a razor application.

Is there anything else I have to install other than the SDK and C# Extension? What do I have to do next?

**Comment by JoeRobich** [comment]
@cdacones The extension does ship with a 16.8 MSBuild. If you do not have Visual Studio or Mono installed, the extension should use the included MSBuild. Let me know if you run into any issues.

**Comment by cdacones** [comment]
@JoeRobich Thanks for letting me know. I'll notify you if I run into any problems in the future. BTW, you're the first person I've seen on GitHub who's also from Washington!

**Comment by cdacones** [comment]
@JoeRobich After installing VS Code, the C# extension, and .NET 5 SDK I tried to create a console app in Windows Powershell using the command 'dotnet new console -o myapp' then received the error below:

C:\Program Files\dotnet\sdk\5.0.101\NuGet.targets(131,5): error : The local source 'C:\Microsoft\Xamarin\NuGet\' doesn't exist.

**Comment by JoeRobich** [comment]
@cdacones It seems that your environment has previously been configured with a custom NuGet source (see https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior). Unfortunately, when NuGet is unable to reach a source it can fail processes like `dotnet new`. You could either create an empty folder at the path that is failing or remove the path from the NuGet configuration files. For Windows, you would want to look at both the `%appdata%\NuGet\NuGet.Config` and `%ProgramFiles(x86)%\NuGet\Config` files.

**Comment by cdacones** [comment]
@JoeRobich Thanks for the instructions. I not only was able to run a console application in VS Code, but I'm now able to run razor pages.

**Comment by JoeRobich** [comment]
@cdacones :tada: Glad things are working for you now. I am going to close this issue out.
