### ISSUE TITLE
Find All References highlight not working

### ISSUE THREAD

**Issue by coeyes** [OmniSharp/omnisharp-vscode#428]
## Environment data

OS X 10.11.5
Mono JIT compiler version 4.4.0 
VS Code version: 1.2
C# Extension version: Legacy C# Support 0.33
## Steps to reproduce
1. locate cursor on any variable.
2. `Find All References` (Shift + F12)
## Expected  behavior

highlight on variables
## Actual behavior

not highlight.
![gamemanager cs - test2d 2016-06-13 14-33-21](https://cloud.githubusercontent.com/assets/260646/15997905/40dbe3ea-3174-11e6-806d-ed68e7c85bbc.jpg)

Other language project (eg. JavaScript) works correctly. but c# project doesn't working.

**Comment by DustinCampbell** [comment]
If I understand correctly, the issue is that the references are not highlighted within the peek window. Is that correct?

**Comment by coeyes** [comment]
yes, this issue is related to the peek window highlight.

I expected below. (from vscode offical homepage)
![unity_peekreferences](https://cloud.githubusercontent.com/assets/260646/16067177/efa4ebd4-32f4-11e6-9b34-ca8452fd0cf6.png)

**Comment by DustinCampbell** [comment]
Looks like an issue here: https://github.com/OmniSharp/omnisharp-vscode/blob/v1.7.0-beta5/src/features/referenceProvider.ts#L24. We're only passing the start line and column rather than the full range. Should be an easy fix.
