### ISSUE TITLE
"12 References" text jumps up and down by a few pixels whenever I'm typing

### ISSUE THREAD

**Issue by corneliusroemer** [OmniSharp/omnisharp-vscode#4293]
## Issue Description ##
`References` text jumps up and down by a few pixels whenever I'm typing in text.
![Jumpy](https://user-images.githubusercontent.com/25161793/102014056-61a9d780-3d54-11eb-85a9-5adc9ea1e23c.gif)

Somewhat related maybe to https://github.com/OmniSharp/omnisharp-vscode/issues/1173 but not entirely. It's not clear to me what exactly #1173 talks about since there's no Gif/animation showing the undesired behaviour.

## Steps to Reproduce ##
Unsure as to when this behaviour occurs. Not all of the `References` are jumpy - doesn't seem to be a trivial relationship. It's not necessarily the `References` closest to the cursor, `References` inside classes seem to be more jumpy than references outside of it.

## Expected Behavior ##
The `References` text doesn't jump up and down.

## Actual Behavior ##
The `References` text jumps up and down.

### OmniSharp log ###
<details>Starting OmniSharp server at 12.12.2020, 21:19:42
    Target: c:\Users\roemerco\Exercism\csharp\dominoes

OmniSharp server started.
    Path: c:\Users\roemerco\.vscode\extensions\ms-dotnettools.csharp-1.23.7\.omnisharp\1.37.4\OmniSharp.exe
    PID: 7424

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 3 MSBuild instance(s)
            1: Visual Studio Community 2019 16.7.30523.141 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: Visual Studio Build Tools 2017 15.9.28307.1259 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            3: StandAlone 16.8.0 - "c:\Users\roemerco\.vscode\extensions\ms-dotnettools.csharp-1.23.7\.omnisharp\1.37.4\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.7.30523.141 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\roemerco\Exercism\csharp\dominoes'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\roemerco\Exercism\csharp\dominoes'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\roemerco\Exercism\csharp\dominoes\Dominoes.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\roemerco\Exercism\csharp\dominoes'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\roemerco\Exercism\csharp\dominoes\Dominoes.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\roemerco\Exercism\csharp\dominoes' on host 9428.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\roemerco\Exercism\csharp\dominoes\Dominoes.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\roemerco\Exercism\csharp\dominoes\Dominoes.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Dominoes
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\roemerco\Exercism\csharp\dominoes\Dominoes.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\roemerco\Exercism\csharp\dominoes\Dominoes.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\roemerco\Exercism\csharp\dominoes\Dominoes.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\roemerco\Exercism\csharp\dominoes\Dominoes.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\roemerco\Exercism\csharp\dominoes\Dominoes.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Dominoes
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: C:\Users\roemerco\.nuget\packages\xunit.analyzers\0.10.0\analyzers\dotnet\cs\xunit.analyzers.dll</details>

### C# log ###
No logs written

## Environment information ##

**VSCode version**: 1.52.0
**C# Extension**: 1.23.7

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.7|
|jupyter|ms-toolsai|2020.12.414227025|
|python|ms-python|2020.11.371526539|
|rainbow-csv|mechatroner|1.8.0|
|remote-wsl|ms-vscode-remote|0.52.0|
|sqltools|mtxr|0.23.0|
|sqltools-driver-sqlite|mtxr|0.2.0|
|TabOut|albert|0.2.0|
|vim|vscodevim|1.18.5|
|vscode-docker|ms-azuretools|1.8.1|
|vscode-pull-request-github|GitHub|0.22.0|
|vscode-pylance|ms-python|2020.12.2|
|vscode-sqlite|alexcvzz|0.10.1|;

</details>

**Comment by filipw** [comment]
@jrieken hey, do you have any idea what is going on here? have you seen this before? should this be moved to the VS Code repo?

**Comment by jrieken** [comment]
Yeah, definitely nothing that you can influence. We have seen this in past but actually don't know what's casing this 🤷

**Comment by corneliusroemer** [comment]
Next time I snatch it, do you want me to do any particular investigation?
Should it not be possible to check why things are moving by logging
anything related to the element's view/rendering? VScode uses web
technologies after all and surely with the equivalent of browser dev tools
one could figure it out.

**Comment by jrieken** [comment]
That would be great @corneliusroemer. You can try to inspect the element of the code lens and see if any of its DOM properties change.

**Comment by corneliusroemer** [comment]
> That would be great @corneliusroemer. You can try to inspect the element of the code lens and see if any of its DOM properties change.

Anything specific you'd like me to look out for? Could I record some sort of log that would help?

I'm not sure I can figure it out on my own.

After restarting the program the issue is gone - so it is fickly for sure, that's why some sort of plan in case it reappears would be good.

**Comment by jrieken** [comment]
> After restarting the program the issue is gone - so it is fickly for sure, that's why some sort of plan in case it reappears would be good

That's what I am afraid off...

For inspecting, try to find the codelens-decoration span. It should have the `top`-style set and that shouldn't change while typing

<img width="965" alt="Screenshot 2020-12-15 at 13 24 22" src="https://user-images.githubusercontent.com/1794099/102214652-e58ccc80-3ed8-11eb-94a9-df5d8422b64b.png">

**Comment by corneliusroemer** [comment]
It's occurring again, after hibernation - that could be a clue.

The top value does change. I did a "break on attribute changed" and it's triggered by something to do with "Light Bulb" in codeAction. See screenshot. There are two changes, one to move it up by a pixel, one to move it down. The movement up is probably the culprit.

![image](https://user-images.githubusercontent.com/25161793/103015543-eb218c80-4540-11eb-81c7-d65643d93b29.png)

**Comment by jrieken** [comment]
I have created https://github.com/microsoft/vscode/issues/113384 to continue the investigation on our side

**Comment by filipw** [comment]
thanks, I will close this one as it's not related to OmniSharp
