### ISSUE TITLE
Omnisharp always downloading new update , even in none C# projects.

### ISSUE THREAD

**Issue by B-Esmaili** [OmniSharp/omnisharp-vscode#4295]
It's been 2-3 years I first saw this issue in issue list , but still this issue exists. When I fire up vscode to do react project omnisharp installation message pops up and starts downloading. I couldn't find any way to disable update , this is driving me crazy. Please do something about it.

**Comment by gregg-miskelly** [comment]
Unfortunately we are still waiting on https://github.com/microsoft/vscode/issues/23251 to be fixed. There is nothing this extension can reasonably do without it.
