### ISSUE TITLE
[features] Support Top-level programming

### ISSUE THREAD

**Issue by Banyc** [OmniSharp/omnisharp-vscode#4297]
Please support top-level programming code suggestions.

Here is the announcement of .NET 5.0 features -> <https://devblogs.microsoft.com/dotnet/announcing-net-5-0/#top-level-programs>.

However, currently, omnisharp does not support this.

**Comment by filipw** [comment]
this is aready supported. can you please provide the repro steps of the problem you are seeing along with the Omnisharp log?

**Comment by Banyc** [comment]
Update: the problem is solved by restarting omnisharp server:

1. ctrl + P.
1. `> omnisharp restart`.
1. Select the only choice on the suggestion bar and run it.

**Comment by Banyc** [comment]
I believe it could also be an issue to some extent since it requires a restart to solve.

**Comment by filipw** [comment]
please use the issue template to describe the repro steps, actual and expected results as well aa attach an Omnisharp log. Otherwise there is no way to provide any help or act on anything. Thanks.

**Comment by Banyc** [comment]
I thought it was a minor problem... Anyway, thanks for the speedy response! Really appreciate it! I will close this issue.

**Comment by filipw** [comment]
thanks - I am always happy to help, just please provide as much details as possible 😀
