### ISSUE TITLE
Debug .net core app failed if the configurations[x].program contains space

### ISSUE THREAD

**Issue by weinand** [OmniSharp/omnisharp-vscode#430]
_From @Crazy7 on June 12, 2016 9:49_

- VSCode Version:1.2.0
- OS Version:Windows 10

Steps to Reproduce:

1. Create a .net core project in a path contains space, such as C:\Users\XX\Documents\Visual Studio 2015\Projects\
2. Open the project in vs code, fill the lanch.json and start to debug

_Copied from original issue: Microsoft/vscode#7575_

**Comment by weinand** [comment]
_From @JimiC on June 12, 2016 13:39_

Start debug from the debugger window. I suppose you are referring to a known issue #7291.

**Comment by weinand** [comment]
_From @isidorn on June 13, 2016 8:5_

Dup of #7291

**Comment by weinand** [comment]
_From @isidorn on June 13, 2016 8:18_

@Crazy7 works for me for debugging node applications that have a program that has whitespace in the path. 
Can you please share a screenshot of how vscode failed to start debug?

**Comment by weinand** [comment]
This issue is about .net and not node.js. I'll move it over...

**Comment by gregg-miskelly** [comment]
@Crazy7 what version of the C# extension do you have installed? We fixed some issues with spaces, so if you aren't on 1.1.x, please upgrade to the latest.

**Comment by caslan** [comment]
The new version of the CSharp extension to the marketplace has the fix.
