### ISSUE TITLE
OmniSharp fails to load projects because it ignored a custom NuGet source

### ISSUE THREAD

**Issue by crose-varde** [OmniSharp/omnisharp-vscode#4301]
## Issue Description ##
**This is almost exactly a copy of #2971, but the conversation there did not resolve it for me.**

When opening a new solution that has never had a package restore successfully completed, OmniSharp is not using my user-level custom package sources. It consequently fails to locate some dependencies and then cannot load the projects that need them.

#2971 was resolved by running `dotnet restore` before opening the solution in OmniSharp for the first time. When I try that, I get an error:
```
C:\Program Files\dotnet\sdk\5.0.101\NuGet.targets(131,5): error : Object reference not set to an instance of an object. [c:\path\to\my\Project.csproj]
```
I assume this is a _different_ problem, but I don't understand why OmniSharp isn't respecting my user-level NuGet.config in the first place.

## Steps to Reproduce ##

1. Create a [user-level NuGet.config file](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior) containing a custom package source.
2. Verify that NuGet sees this custom package source by running `nuget sources list`.
3. Open a solution directory in VS Code that contains projects that reference a package found only in this custom source.

## Expected Behavior ##

OmniSharp locates all referenced packages and successfully loads the projects.

## Actual Behavior ##

OmniSharp does not consult the custom source, fails to locate the referenced packages it contains, and consequently fails to load projects.

### OmniSharp log ###
<details>

```
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\path\to\my\Project.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        Unable to find package MyDependentPackage1. No packages exist with this id in source(s): nuget.org
[fail]: OmniSharp.MSBuild.ProjectLoader
        Unable to find package MyDependentPackage2. No packages exist with this id in source(s): nuget.org
```
</details>

### C# log ###
<details>

```
```
</details>

## Environment information ##

**VSCode version**: 1.52.0
**C# Extension**: 1.23.7

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.7|
|Ionide-fsharp|Ionide|4.17.0|
|powershell|ms-vscode|2020.6.0|
|terraform|hashicorp|2.3.0|
|vscode-eslint|dbaeumer|2.1.14|
|vscode-html-css|ecmel|1.1.6|
|vscode-yaml|redhat|0.13.0|;

</details>

**Comment by PraJaL55** [comment]
Can this issue be prioritized?

**Comment by JoeRobich** [comment]
@PraJaL55 Do you have better luck when you place the nuget.config with your solution file?

**Comment by JoeRobich** [comment]
@PraJaL55 Does your solution restore and build properly using the dotnet CLI?

**Comment by PraJaL55** [comment]
Hi @JoeRobich , the problem has been resolved. I am guessing it was because I had installed dotnet in devcontainer at `/usr/share/dotnet` and Omnisharp was looking at `/usr/local/share/dotnet`. Fixing this fixed the issue.
