### ISSUE TITLE
.cs file highlight notwork after a multiline Tuple

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [OmniSharp/omnisharp-vscode#4303]
Reported before on https://github.com/microsoft/vscode/issues/111484

## Environment data
`dotnet --info` output:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS Code version: 1.51.1
C# Extension version: ms-dotnettools.csharp v1.23.6

## Steps to reproduce
The image shows how a multi line tuple broke the highlight

![image](https://user-images.githubusercontent.com/10773245/100573567-14207a00-3313-11eb-9c0c-cfcbc119ded9.png)

The image shows if turn this multi line into one line then 2nd Tuple hightlight wrong

![image](https://user-images.githubusercontent.com/10773245/100573586-1da9e200-3313-11eb-940c-8621f9dba2eb.png)

## Expected  behavior
They are fine colored on Visual Studio 2019.

**Comment by filipw** [comment]
This should work with semantic highlighting. 
To enable set:

`csharp.semanticHighlighting.enabled` and `editor.semanticHighlighting.enabled` to `true`.

**Comment by filipw** [comment]
<img width="279" alt="Bildschirmfoto 2020-12-28 um 16 45 25" src="https://user-images.githubusercontent.com/1710369/103226299-184cb100-492c-11eb-8fef-ec8d2dd22a16.png">

closing as this is supported in semantic highlighting
