### ISSUE TITLE
Add a setting to override path to .NET debugger

### ISSUE THREAD

**Issue by Saancreed** [OmniSharp/omnisharp-vscode#4306]
## Issue Description ##

The VSCode extension by default downloads `vsdbg` and uses that to debug .NET applications. However, `vsdbg` is a proprietary program and its license forbids usage in certain environments and the only way to specify alternative debugger path seems to be dedicated for use in remote debugging only _and_ has to be configured for each project separately (because it's a `launch.json` option). To help remedy this situation, some configuration option could be introduced to override path to _local_ debugger in a machine–wide manner.

Or it could just be used to specify another, already existing local installation of `vsdbg` :smile:

## Expected Behavior ##

There should be a way to use other debugger than `vsdbg` downloaded by `omnisharp-vscode`.

## Actual Behavior ##

There is none.

## Environment information ##

**VSCode version**: 1.51.1
**C# Extension**: 1.23.8

<details><summary>Mono Information</summary>

```
$ mono --version
Mono JIT compiler version 6.12.0.107 (tarball Thu Dec 10 12:48:21 AM CET 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

$ msbuild -version
Microsoft (R) Build Engine version 16.8.0-ci-20618-01 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

16.8.0.61801
```

</details>

<details><summary>Dotnet Information</summary>

```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.1.811 [/usr/share/dotnet/sdk]
  2.2.207 [/usr/share/dotnet/sdk]
  3.0.103 [/usr/share/dotnet/sdk]
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

**Comment by WardenGnaw** [comment]
The way that VS Code designed Extensions is that you can have multiple extensions installed. Each extension can provide its own extension commands, add in a language service, or a debugging service. 

The omnisharp-vscode extension provides the Omnisharp-Roslyn language service and the Microsoft C# Debugger for .NET Core. 

If there is another C# debugger that works with the [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/), they should create a VSCode extension that contributes a debugger.

For example, you can see this extension contributes two debuggers types `coreclr` and `clr`.
https://github.com/OmniSharp/omnisharp-vscode/blob/3117b4e9e053b4928ec979f360f93b39ab697c11/package.json#L1039-L1042

**Comment by Saancreed** [comment]
> If there is another C# debugger that works with the Debug Adapter Protocol, they should create a VSCode extension that contributes a debugger.

So, if I understand this correctly, another extension can be created to provide a separate .NET debugger for users to choose when debugging .NET applications. Which is nice, but it doesn't solve the entire issue, as this would require changes to each `launch.json` to include a launch option using another debugger. Which is still quite far from more user–friendly solution like allowing developers to configure path to debugger to use in machine–wide `settings.json`, like `omnisharp.monoPath` allows for Mono and `omnisharp.path` does for `omnisharp-roslyn`.

To be clear, I'm not asking for support for debuggers other than `vsdbg` here, even if they happen to be DAP–compatible, just feature parity in configuration options for integrations with external components. Being able to actually use a different debugger would only be a nice side effect.

**Comment by WardenGnaw** [comment]
I agree that it would be nice to switch between different debuggers, the issue is that each debugger could have different launch/attach configurations. The only two required fields are `noDebug` and `__restart`. The rest is up to the debugger's implementation. 
Reference: https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Launch

For example, lets say we want to switch from the Windows .NET Core Debugger to the Mono Debugger.
Their launch configuration expects only the keys: program, args, cwd, runtimeExecutable, runtimeArgs, passDebugOptionsViaEnvironmentVariable, env, externalConsole, console. 

From https://github.com/microsoft/vscode-mono-debug/blob/488eff1234a6d5be291b89dc30cba3f2d08de2c5/package.json#L143

However, this extension's debugger has a much larger list that is not included in the mono one. E.g. justMyCode, pipeTransport, etc...
From https://github.com/OmniSharp/omnisharp-vscode/blob/3117b4e9e053b4928ec979f360f93b39ab697c11/package.json#L1048

The way it was designed by VS Code it was if you needed to switch to a different debugger, you would use a different debug configuration. 

If you have values that are shared across the configurations, you could use [VS Code input variables](https://code.visualstudio.com/docs/editor/variables-reference#_input-variables) or set environment variables and reference them by `${env:<NAME>}`.

**Comment by Saancreed** [comment]
> The way it was designed by VS Code it was if you needed to switch to a different debugger, you would use a different debug configuration.

Understood, thank you for the explanation. So, the only thing that remains is my request to add a setting for overriding path to `vsdbg`, as I said before:

> To be clear, I'm not asking for support for debuggers other than `vsdbg` here, […], just feature parity in configuration options for integrations with external components.

Considering it's a very niche use case, I'll understand if you guys decide that it's unlikely to be implemented anytime soon. If so, feel free to close this issue.
