### ISSUE TITLE
Debugger vsdbg on aspnet core projects on Mac m1 crashes

### ISSUE THREAD

**Issue by JasperRev** [OmniSharp/omnisharp-vscode#4315]
Hello. I believe this is the proper spot for an issue I filed initially under vscode issues.  I am on 1.23.8 of omnisharp and 1.52.1 of vscode on a Mac m1.  

[https://github.com/dotnet/runtime/issues/46226](url)

On console apps, I appear to be able to launch the debugger, but when starting an aspnet core project as simple as dotnet new webapi, the program exits.

Although I see other debugger issues, I did not see one with this behavior.  There is no output, nothing about prime numbers, etc.

Thoughts or insight would be appreciated.

Here is the last bit of the crash report on the Mac....

Thread 19 Crashed:
0   ???                           	0x00007ffe9634aa30 ???
1   libsystem_kernel.dylib        	0x00007fff20347462 __pthread_kill + 10
2   libsystem_c.dylib             	0x00007fff202c8720 abort + 120
3   libsystem_malloc.dylib        	0x00007fff201a8430 malloc_vreport + 548
4   libsystem_malloc.dylib        	0x00007fff201ab4c8 malloc_report + 151
5   libvsdbg.dylib                	0x00000001115f2c61 CClassFactory<CRefCount>::Release() + 33
6   libvsdbg.dylib                	0x00000001115f1995 ATL::CComPtr<CProtocolMainLoop>::~CComPtr() + 21
7   libsystem_c.dylib             	0x00007fff202a2ca7 __cxa_finalize_ranges + 316
8   libsystem_c.dylib             	0x00007fff202a2f92 exit + 53
9   libcoreclr.dylib              	0x000000010dc996f2 PROCEndProcess(void*, unsigned int, int) + 210
10  libcoreclr.dylib              	0x000000010dc99606 ExitProcess + 150
11  libcoreclr.dylib              	0x000000010de0804c SafeExitProcess(unsigned int, int, ShutdownCompleteAction) + 476
12  libcoreclr.dylib              	0x000000010dc93d07 CorUnix::TerminationRequestHandlingRoutine(void*) + 23
13  libcoreclr.dylib              	0x000000010dc9ceaa CorUnix::CPalThread::ThreadEntry(void*) + 426
14  libsystem_pthread.dylib       	0x00007fff20375950 _pthread_start + 224
15  libsystem_pthread.dylib       	0x00007fff2037147b thread_start + 15

Thread 19 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000000030e5cc000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x00000001135be028  rsi: 0x0000000000000003  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x000000030e5cbbb0   r9: 0x0000000000000000  r10: 0x000000030e5cc000  r11: 0x00000000000000f3
  r12: 0x0000000000003153  r13: 0x0000000000000050  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: <unavailable>  rfl: 0x0000000000000283

Here is the output of starting and exiting the app.
Loaded '/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/3.1.10/Microsoft.Extensions.Configuration.CommandLine.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/3.1.10/Microsoft.Extensions.FileProviders.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/3.1.10/Microsoft.Extensions.FileProviders.Physical.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Memory.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/3.1.10/Microsoft.Extensions.Configuration.FileExtensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/3.1.10/Microsoft.Extensions.Configuration.Json.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/3.1.10/Microsoft.Extensions.Configuration.UserSecrets.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/3.1.10/Microsoft.Extensions.Configuration.Binder.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Private.Uri.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Buffers.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.IO.FileSystem.Watcher.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.ComponentModel.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Collections.Concurrent.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/3.1.10/Microsoft.Extensions.FileSystemGlobbing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Threading.Timer.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Threading.Thread.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[5420] webapi.dll' has exited with code 0 (0x0).

**Comment by JasperRev** [comment]
Additional Info ...


Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000001111f5748
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [7115]

VM Regions Near 0x1111f5748:
    Rosetta Return Stack        10cca7000-10ccab000    [   16K] rw-/rwx SM=PRV  
--> 
    VM_ALLOCATE                 1117b1000-1117d0000    [  124K] ---/rwx SM=NUL

**Comment by gregg-miskelly** [comment]
All of these similar issues are problems with Rosetta. From https://github.com/dotnet/runtime/issues/46226 sounds like this is hopefully addressed in the latest macOS.
