### ISSUE TITLE
Bug: Unbound breakpoint in .net5.0

### ISSUE THREAD

**Issue by Banyc** [OmniSharp/omnisharp-vscode#4319]
## Environment data
`dotnet --info` output:

```
.NET SDKs installed:
  3.1.401 [***]
  5.0.100 [***]
```

VS Code version: 1.52.1

C# Extension version: 1.23.8

## OmniSharp log

A lot of lines like this:

```
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: d:\****r\obj\Debug\net5.0\Razor\*****\SurveyPrompt.razor.g.cs added to workspace
```

## Steps to reproduce

1. Build a .NET5.0 APP based on the blazorserver template.
1. Set a breakpoint somewhere.
1. Debug and wait.
1. The breakpoint is hit.
1. Then, add a new line above the hit line.
1. End the debug session.
1. Start the debug session.
1. The breakpoint is an unbound breakpoint. In other words, the breakpoint sign is hollow and the breakpoint will not be hit.

## Expected  behavior

The breakpoint should never be an unbound breakpoint.

## Actual behavior

The breakpoint happens to be an unbound breakpoint.

## Additional Issues

I reckon that, although not 10/10 for sure, this issue is also relative:

<https://github.com/unoplatform/uno/issues/4672>

If any additional context and information are needed, I will more than happy to provide for this issue.

**Comment by Banyc** [comment]
Additional context:

I have tried restarting omnisharp server. Nothing changed.

I have also relaunched vscode. Nothing changed either.

I have also change the sdk back to `<TargetFramework>netcoreapp3.1</TargetFramework>` and attempt to reproduce the issue above but works perfectly fine. It must be a .net5.0 relevant problem.

**Comment by mallenswe** [comment]
I had this same problem just now. Because I am making a Console app I can see in the Terminal that the output is the same as my previous code. 

To fix this I stop the debugger and run either of these commands: 
`dotnet run
`

`dotnet build`

It seems the debugger might not actually execute the "preLaunchTask" ?

**Comment by JoeRobich** [comment]
@gregg-miskelly have you experienced the preLaunchTask not executing?

**Comment by gregg-miskelly** [comment]
VS Code owns the code for this, so I don't know if there are interesting special cases to test. But I just tried this with 'hello world' and I could see VS Code execute the prelaunch task and wait for it to finish before starting debugging.

**Comment by Banyc** [comment]
Here is a small project to reproduce the issue: <https://github.com/Banyc/Sharer>.

If any additional context is omitted here, I will be glad to provide it as soon as possible.

## Reproduction

1. Clone the repository. It is small in size and soon to complete the download.
1. Checkout branch `575a68fbee62031279ebf99fb1cc11b35232263a`.
1. Set a breakpoint [here](https://github.com/Banyc/Sharer/blob/575a68fbee62031279ebf99fb1cc11b35232263a/src/SharerBlazorServer/Pages/Download.razor#L43) in VS Code.
1. Debug project `SharerBlazorServer` in VS Code. A web page will pop up.
1. Click here 
![image](https://user-images.githubusercontent.com/36535895/104946312-ccee6580-59f4-11eb-9863-23192112bd00.png) and wait for a breakpoint. The breakpoint was fired.
1. And then stop the debug by pressing the square sign in VS Code.
1. Add a newline at the head of the line with the breakpoint.
1. Debug project `SharerBlazorServer` in VS Code. A web page will pop up.
1. Click here 
![image](https://user-images.githubusercontent.com/36535895/104946312-ccee6580-59f4-11eb-9863-23192112bd00.png) and wait for a breakpoint. The breakpoint has NOT been fired.

## Expected Behavior

At the last step, the breakpoint has been fired.

## Actual Behavior

At the last step, the breakpoint has NOT been fired.

**Comment by Banyc** [comment]
A workaround is found. Add this line to `launch.json`:

```
"requireExactSource": false,
```

`"requireExactSource"` means:

> Optional flag to require current source code to match the pdb.

Although not clear what magic it has done, it somehow works.

**Comment by Banyc** [comment]
It turns out that it is not omnisharp...

I forgot to update the program path from `netcoreapp3.1` to `net5.0` in `launch.json`. Sorry for this issue...
