### ISSUE TITLE
Merge master branch to release branch to enable pipe launch support needed for Docker debugging

### ISSUE THREAD

**Issue by caslan** [OmniSharp/omnisharp-vscode#433]
Need to merge dev branch to master to include the work for pipe launch options support (https://github.com/OmniSharp/omnisharp-vscode/pull/415)  in official release. This is needed for docker debugging support.

**Comment by caslan** [comment]
Updated title as we now release CSharp extension from release branch...

**Comment by gregg-miskelly** [comment]
This is now complete.
