### ISSUE TITLE
"a\r\nb".IndexOf("\n") return -1

### ISSUE THREAD

**Issue by zhoujit** [OmniSharp/omnisharp-vscode#4337]
int idx3 = "a\r\nb".IndexOf("\n");

Above statement returns -1.

OS: Ubuntu/WSL2
Version: .NET 5

**Comment by JoeRobich** [comment]
@zhoujit Sorry you are running into this strange return value. This repo is for the VS Code C# extension. Could you open an issue against https://github.com/dotnet/runtime, since this looks .NET runtime related?

**Comment by zhoujit** [comment]
Close it. I will submit another ticket in dotnet runtime.
