### ISSUE TITLE
Could not find document for file, Omnisharp not working

### ISSUE THREAD

**Issue by CapClumsy** [OmniSharp/omnisharp-vscode#4340]
## Issue Description ##
I recently started a new Unity project, and for the first few days of me working on it, the C# extension had no issues. However, a few days after, all Omnisharp functions stopped working, like reference counters and autocomplete. I checked the logs and found that any time I was typing something, this was showing up:
```
[info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
        Could not find document for file e:\Games\UnityProjects\Protista\Assets\Scripts\Board.cs
```
I've tried restarting the server via the command palette multiple times and it hasn't worked.  
I tried looking online for solutions and came across this: https://github.com/OmniSharp/omnisharp-vscode/issues/4181#issuecomment-742668376 so I set the path to latest in my settings, which is why I have the beta. (Having the beta didn't fix it and it didn't work before I had the beta too.) I also saw this in the changelog on the extension store:
> For Mono-based development (e.g. Unity) that requires full .NET framework, you need to set "omnisharp.useGlobalMono": "always". The current value of "auto" will remain "never" until Mono upgrades their bundled MSBuild version.  

So I tried setting the `"useGlobalMono"` to `"always"`, but that didn't work either. I've [asked some people on Reddit for help](https://www.reddit.com/r/vscode/comments/ks0t2o/omnisharp_server_from_c_extension_not_working/), but nothing worked there either. I've tried uninstalling and reinstalling the extension, also to no avail.  

Note: for the most part I am new to development in C#, and this may be a stupid question, but is there supposed to be a .csproj or .sln file somewhere in the directory created by Unity, because I can't find any, and that may be the problem, but I've tried and I can't find anything about it.
## Steps to Reproduce ##
Unknown, Omnisharp was working fine one day then stopped working the next day without any warning.
## Expected Behavior ##
When typing, suggestions that are related to my variables and methods show up, red underlining when there is a syntax error, reference counters, go to definition would do something, etc.
## Actual Behavior ##
None of the above show up, I get no red lines from syntax errors, no reference counters, go to definition does nothing, and the only suggestions I get when typing is based on words that have already appeared in my script.
### OmniSharp log ###
<details>
Starting OmniSharp server at 1/10/2021, 2:40:37 PM
    Target: e:\Games\UnityProjects\Protista

OmniSharp server started.
    Path: c:\Users\jagsh\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.23\OmniSharp.exe
    PID: 4092

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.8.0 - "c:\Users\jagsh\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.23\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\jagsh\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.23\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.8.0 - "c:\Users\jagsh\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.23\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\jagsh\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.23\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\jagsh\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.23\.msbuild
            MSBuildToolsPath = c:\Users\jagsh\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.23\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'e:\Games\UnityProjects\Protista'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'e:\Games\UnityProjects\Protista'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'e:\Games\UnityProjects\Protista'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'e:\Games\UnityProjects\Protista' on host 22020.
[info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
        Could not find document for file e:\Games\UnityProjects\Protista\Assets\Scripts\Board.cs
</details>

### C# log ###
<details>Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!  
In this case, even though I'd done it before, I tried uninstalling and reinstalling the C# extension as a last-ditch effort.</details>

## Environment information ##

**VSCode version**: 1.52.1
**C# Extension**: 1.23.8

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|anaconda-extension-pack|ms-python|1.0.1|
|csharp|ms-dotnettools|1.23.8|
|debugger-for-chrome|msjsdiag|4.12.11|
|discord-vscode|icrawl|4.1.0|
|java|redhat|0.73.0|
|jupyter|ms-toolsai|2020.12.414227025|
|python|ms-python|2020.12.424452561|
|remote-containers|ms-vscode-remote|0.154.2|
|remote-ssh|ms-vscode-remote|0.62.0|
|remote-ssh-edit|ms-vscode-remote|0.62.0|
|remote-wsl|ms-vscode-remote|0.52.0|
|unity-debug|Unity|3.0.2|
|unity-tools|Tobiah|1.2.12|
|vscode-java-debug|vscjava|0.30.0|
|vscode-java-dependency|vscjava|0.16.0|
|vscode-java-pack|vscjava|0.12.1|
|vscode-java-test|vscjava|0.27.0|
|vscode-maven|vscjava|0.27.1|
|vscode-pull-request-github|GitHub|0.22.0|
|vscode-pylance|ms-python|2021.1.0|
|vscode-remote-extensionpack|ms-vscode-remote|0.20.0|
|vscode-yaml|redhat|0.13.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.10|;

</details>

**Comment by lugehorsam** [comment]
I resolved this issue in Unity by downloading Unity's VSCode Package via the package manager and then regenerating the csproj fles from Unity's External Tools menu: (https://docs.unity3d.com/Packages/com.unity.ide.vscode@1.2/manual/index.html)

**Comment by CapClumsy** [comment]
Okay, I tried doing that, and the .csproj and .sln files were generated, but then I got this in the logs: 
```
Starting OmniSharp server at 1/11/2021, 8:16:33 AM
    Target: e:\Games\UnityProjects\Protista\Protista.sln

OmniSharp server started.
    Path: c:\Users\jagsh\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.23\OmniSharp.exe
    PID: 636

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.8.0 - "c:\Users\jagsh\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.23\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\jagsh\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.23\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.8.0 - "c:\Users\jagsh\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.23\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\jagsh\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.23\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\jagsh\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.23\.msbuild
            MSBuildToolsPath = c:\Users\jagsh\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.23\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'e:\Games\UnityProjects\Protista'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'e:\Games\UnityProjects\Protista\Protista.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\Games\UnityProjects\Protista\Assembly-CSharp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'e:\Games\UnityProjects\Protista'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\Games\UnityProjects\Protista\Assembly-CSharp.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'e:\Games\UnityProjects\Protista' on host 16504.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'e:\Games\UnityProjects\Protista\Assembly-CSharp.csproj'.
e:\Games\UnityProjects\Protista\Assembly-CSharp.csproj
c:\Users\jagsh\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.23\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1180,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: e:\Games\UnityProjects\Protista\Assembly-CSharp.csproj
```
Does this mean I just need to update my version of the .NET framework? How would I do that?

**Comment by filipw** [comment]
you need to set `omnisharp.useGlobalMono`:`always`. The bundled Mono ships without the .NETFramework,Version=v4.7.1 reference assemblies.

**Comment by CapClumsy** [comment]
It is set to `"always"`. I've tried putting it back to `"auto"` and then changing it to `"always"`, and it still came out with the same logs.

**Comment by filipw** [comment]
oh, I did not notice that you are on Windows. Then Mono has no effect.

You need to install VS 2019 Build Tools https://visualstudio.microsoft.com/de/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16 or VS 2019 https://visualstudio.microsoft.com/de/thank-you-downloading-visual-studio/?sku=Community&rel=16

Then Omnisharp will pick up the MSBuild that comes with that.

**Comment by CapClumsy** [comment]
I installed the VS 2019 Build Tools, still getting the same logs. :(

**Comment by filipw** [comment]
please post the log after the installation

**Comment by CapClumsy** [comment]
Here they are:
```
Starting OmniSharp server at 1/11/2021, 12:06:14 PM
    Target: e:\Games\UnityProjects\Protista\Protista.sln

OmniSharp server started.
    Path: c:\Users\jagsh\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.23\OmniSharp.exe
    PID: 15412

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2019 16.8.30804.86 - "E:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
            2: StandAlone 16.8.0 - "c:\Users\jagsh\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.23\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2019 16.8.30804.86 - "E:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'e:\Games\UnityProjects\Protista'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'e:\Games\UnityProjects\Protista\Protista.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\Games\UnityProjects\Protista\Assembly-CSharp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'e:\Games\UnityProjects\Protista'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\Games\UnityProjects\Protista\Assembly-CSharp.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'e:\Games\UnityProjects\Protista' on host 27032.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'e:\Games\UnityProjects\Protista\Assembly-CSharp.csproj'.
e:\Games\UnityProjects\Protista\Assembly-CSharp.csproj
E:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1180,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: e:\Games\UnityProjects\Protista\Assembly-CSharp.csproj
```
I'm pretty sure it's the same.

**Comment by filipw** [comment]
yeah but now it picks up the correct MSBuild which is good

```
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2019 16.8.30804.86 - "E:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
```

so what you need to do now, is follow the link in the error and install .NET 4.7.1 developer pack (https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net471-developer-pack-offline-installer)

**Comment by CapClumsy** [comment]
Thank you so much! It works now!

**Comment by Diegoav87** [comment]
Hi I followed these steps but this is still not working. Anyone knows anything I can do? I have tried everything but I just doesn't work.

**Comment by nixon-voxell** [comment]
@Diegoav87 use Unity hub and make sure to check this box when installing

![Uploading image.png…]()

**Comment by nixon-voxell** [comment]
@gputhread hi, it's not installing the visual studio editor in your computer. It's installing the necessary dev tools. You can use vscode if you want to.

**Comment by gputhread** [comment]
> @gputhread hi, it's not installing the visual studio editor in your computer. It's installing the necessary dev tools. You can use vscode if you want to.

ok i didnt knew there are tools separately available to install. Thanks. I know this fix that if vscode and vs both are installed it works fine but i use this fix " upgrade downgrade(1.1.3) vs plugin in unity package manager retarst unity or vs code and delete cs files " then it works again

**Comment by mostafaosivand** [comment]
Hi, i install vs 2019 build tools and .NET SDK 5 but intellisense not working in vs code !
this is omnisharp logs :

`Starting OmniSharp server at 9/28/2021, 7:54:29 AM
    Target: d:\test

OmniSharp server started.
    Path: c:\Users\Padra System\.vscode\extensions\ms-dotnettools.csharp-1.23.15\.omnisharp\1.37.15\OmniSharp.exe
    PID: 1056

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2019 16.11.31702.278 16.11.0 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
            2: StandAlone 17.0.0 - "c:\Users\Padra System\.vscode\extensions\ms-dotnettools.csharp-1.23.15\.omnisharp\1.37.15\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2019 16.11.31702.278 16.11.0 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\test'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'd:\test\test.sln'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\test'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\test' on host 860.`

**Comment by twizz24** [comment]
Hi i have very similar situation.

I remember it works better before update of Visual Studio Code installation.
when i tried for example to show existing definition ( in existing file ) there is an warning 'no document found' displayed ( altought the file exist )

`Starting OmniSharp server at 29.09.2021, 14:25:30
    Target: c:\WORK\projects\VSC\NET\newProjTst\newProjTst.sln

OmniSharp server started.
    Path: c:\Users\szkn28\.vscode\extensions\ms-dotnettools.csharp-1.23.15\.omnisharp\1.37.15\OmniSharp.exe
    PID: 2480

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2019 16.11.31702.278 16.11.0 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
            2: StandAlone 17.0.0 - "c:\Users\szkn28\.vscode\extensions\ms-dotnettools.csharp-1.23.15\.omnisharp\1.37.15\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2019 16.11.31702.278 16.11.0 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\WORK\projects\VSC\NET\newProjTst'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\WORK\projects\VSC\NET\newProjTst\newProjTst.sln'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\WORK\projects\VSC\NET\newProjTst'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\WORK\projects\VSC\NET\newProjTst' on host 19300.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No document found. File: c:\WORK\projects\VSC\NET\newProjTst\gui\MainWindow.xaml.cs.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No document found. File: c:\WORK\projects\VSC\NET\newProjTst\gui\MainWindow.xaml.cs.`

**Comment by twizz24** [comment]
ok i restored default configuration for settings.json and it looks like it work...

<
{
  // Controls if quick suggestions should show up while typing
  "editor.quickSuggestions": {
      "other": true,
      "comments": false,
      "strings": false
  },

   // Controls whether suggestions should be accepted on commit characters. For example, in JavaScript, the semi-colon (`;`) can be a commit character that accepts a suggestion and types that character.
  "editor.acceptSuggestionOnCommitCharacter": true,

  // Controls if suggestions should be accepted on 'Enter' - in addition to 'Tab'. Helps to avoid ambiguity between inserting new lines or accepting suggestions. The value 'smart' means only accept a suggestion with Enter when it makes a textual change
  "editor.acceptSuggestionOnEnter": "on",

  // Controls the delay in ms after which quick suggestions will show up.
  "editor.quickSuggestionsDelay": 10,

  // Controls if suggestions should automatically show up when typing trigger characters
  "editor.suggestOnTriggerCharacters": true,

  // Controls if pressing tab inserts the best suggestion and if tab cycles through other suggestions
  "editor.tabCompletion": "off",

  // Controls whether sorting favours words that appear close to the cursor
  "editor.suggest.localityBonus": true,

  // Controls how suggestions are pre-selected when showing the suggest list
  "editor.suggestSelection": "recentlyUsed",

  // Enable word based suggestions
  "editor.wordBasedSuggestions": true,

  // Enable parameter hints
  "editor.parameterHints.enabled": true,
}>

**Comment by tej-rana** [comment]
Running into this. @twizz24 I applied the settings and restarted.

**Comment by denovyar** [comment]
> ## Issue Description
> I recently started a new Unity project, and for the first few days of me working on it, the C# extension had no issues. However, a few days after, all Omnisharp functions stopped working, like reference counters and autocomplete. I checked the logs and found that any time I was typing something, this was showing up:
> 
> ```
> [info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
>         Could not find document for file e:\Games\UnityProjects\Protista\Assets\Scripts\Board.cs
> ```
> 
> I've tried restarting the server via the command palette multiple times and it hasn't worked. I tried looking online for solutions and came across this: [#4181 (comment)](https://github.com/OmniSharp/omnisharp-vscode/issues/4181#issuecomment-742668376) so I set the path to latest in my settings, which is why I have the beta. (Having the beta didn't fix it and it didn't work before I had the beta too.) I also saw this in the changelog on the extension store:
> 
> > For Mono-based development (e.g. Unity) that requires full .NET framework, you need to set "omnisharp.useGlobalMono": "always". The current value of "auto" will remain "never" until Mono upgrades their bundled MSBuild version.
> 
> So I tried setting the `"useGlobalMono"` to `"always"`, but that didn't work either. I've [asked some people on Reddit for help](https://www.reddit.com/r/vscode/comments/ks0t2o/omnisharp_server_from_c_extension_not_working/), but nothing worked there either. I've tried uninstalling and reinstalling the extension, also to no avail.
> 
> Note: for the most part I am new to development in C#, and this may be a stupid question, but is there supposed to be a .csproj or .sln file somewhere in the directory created by Unity, because I can't find any, and that may be the problem, but I've tried and I can't find anything about it.
> 
> ## Steps to Reproduce
> Unknown, Omnisharp was working fine one day then stopped working the next day without any warning.
> 
> ## Expected Behavior
> When typing, suggestions that are related to my variables and methods show up, red underlining when there is a syntax error, reference counters, go to definition would do something, etc.
> 
> ## Actual Behavior
> None of the above show up, I get no red lines from syntax errors, no reference counters, go to definition does nothing, and the only suggestions I get when typing is based on words that have already appeared in my script.
> 


> ## Logs
> ### OmniSharp log
> ### C# log
> ## Environment information
> **VSCode version**: 1.52.1 **C# Extension**: 1.23.8
> 
> Dotnet Information
> Visual Studio Code Extensions


you just have to downgrade your vscode to this version 
![Capture](https://user-images.githubusercontent.com/101503770/181797590-e0a20056-c8fa-4878-b785-18f15f5d8509.PNG)

**Comment by twizz24** [comment]
No need to make downgrade just look at the Omnisharp console - minumum dotnet version since last updates are increased to 6.0.100 and probably you still have lower version  - you need to install recent dotnet core package

![image](https://user-images.githubusercontent.com/91608902/181801268-8a611521-c34e-4fe6-8ae5-8417d5e81533.png)

**Comment by denovyar** [comment]
However, there is a suggestion that I have to use normal visual studio
which is very difficult run on my laptop, that's why my suggestion is to
use vscode version 3 months ago, which is not a lot of issues like this,
and dont forget never to update in vscode

Pada tanggal Jum, 29 Jul 2022 23.16, twizz24 ***@***.***>
menulis:
