### ISSUE TITLE
Intellisense inconsistent (doesn't always auto start)

### ISSUE THREAD

**Issue by hichemfantar** [OmniSharp/omnisharp-vscode#4342]
## Issue Description ##
Many times i have to bring up intellisense manually using ctrl+space

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.52.1
**C# Extension**: 1.23.8

<details><summary>Dotnet Information</summary>
A valid dotnet installation could not be found.</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.9.4|
|better-cpp-syntax|jeff-hykin|1.15.5|
|bracket-pair-colorizer-2|CoenraadS|0.2.0|
|color-highlight|naumovs|2.3.0|
|cpptools|ms-vscode|1.1.3|
|cpptools-extension-pack|ms-vscode|1.0.0|
|cpptools-themes|ms-vscode|1.0.0|
|csharp|ms-dotnettools|1.23.8|
|debugger-for-chrome|msjsdiag|4.12.11|
|discord-vscode|icrawl|4.1.0|
|dotenv|mikestead|1.0.1|
|doxdocgen|cschlosser|1.1.0|
|es7-react-js-snippets|dsznajder|3.1.0|
|halcyon-vscode|brittanychiang|0.2.19|
|hexeditor|ms-vscode|1.3.0|
|java|redhat|0.73.0|
|JavaScriptSnippets|xabikos|1.8.0|
|jupyter|ms-toolsai|2020.12.414227025|
|linux-themes|SolarLiner|1.0.1|
|LiveServer|ritwickdey|5.6.1|
|material-icon-theme|PKief|4.5.0|
|night-owl|sdras|2.0.0|
|noctis|liviuschera|10.39.1|
|pdf|tomoki1207|1.1.0|
|prettier-vscode|esbenp|5.8.0|
|python|ms-python|2020.12.424452561|
|quicktype|quicktype|12.0.46|
|reg|ionutvmi|1.0.2|
|remote-containers|ms-vscode-remote|0.154.2|
|remote-ssh|ms-vscode-remote|0.62.0|
|remote-ssh-edit|ms-vscode-remote|0.62.0|
|remote-wsl|ms-vscode-remote|0.52.0|
|Theme-1337|ms-vscode|0.1.4|
|Theme-MaterialKit|ms-vscode|0.1.4|
|vsc-community-material-theme|Equinusocio|1.4.2|
|vsc-material-theme|Equinusocio|33.1.2|
|vsc-material-theme-icons|equinusocio|1.2.2|
|vscode-css-peek|pranaygp|4.0.2|
|vscode-docker|ms-azuretools|1.9.0|
|vscode-eslint|dbaeumer|2.1.14|
|vscode-graphql|GraphQL|0.3.13|
|vscode-java-debug|vscjava|0.30.0|
|vscode-java-dependency|vscjava|0.16.0|
|vscode-java-pack|vscjava|0.12.1|
|vscode-java-test|vscjava|0.27.0|
|vscode-maven|vscjava|0.27.1|
|vscode-postgresql|ms-ossdata|0.3.0|
|vscode-pull-request-github|GitHub|0.22.0|
|vscode-pylance|ms-python|2021.1.0|
|vscode-react-native|msjsdiag|1.2.0|
|vscode-remote-extensionpack|ms-vscode-remote|0.20.0|
|vscode-theme-onedark|akamud|2.2.3|
|vscode-yaml|redhat|0.13.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.10|
|vsliveshare|ms-vsliveshare|1.0.3449|
|vsliveshare-audio|ms-vsliveshare|0.1.91|
|vsliveshare-pack|ms-vsliveshare|0.4.0|
|vsonline|ms-vsonline|1.0.3076|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by JoeRobich** [comment]
@hichemfantar Sorry your ran into this issue. Can you reopen the folder you were working with in VS Code and share the OmniSharp Log from the Output pane? This will give us some information to troubleshoot your issue with.
