### ISSUE TITLE
Visual Studio Code for Unity: "The reference assemblies for .NETFramework,Version=v4.7.1 were not found. ... "

### ISSUE THREAD

**Issue by simonrober** [OmniSharp/omnisharp-vscode#4347]
## Environment data
`dotnet --info` output:

.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.102/

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.102 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version: 1.52.1
C# Extension version: v1.23.8

## OmniSharp log
Starting OmniSharp server at 1/15/2021, 4:21:50 PM
    Target: /home/simon_rober/CS02 - Introduction to Unity/CS02 - Introduction to Unity.sln

OmniSharp server started.
    Path: /home/simon_rober/.vscode/extensions/ms-dotnettools.csharp-1.23.8/.omnisharp/1.37.5/run
    PID: 38730

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 20.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.8.0 - "/home/simon_rober/.vscode/extensions/ms-dotnettools.csharp-1.23.8/.omnisharp/1.37.5/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/simon_rober/.vscode/extensions/ms-dotnettools.csharp-1.23.8/.omnisharp/1.37.5/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.8.0 - "/home/simon_rober/.vscode/extensions/ms-dotnettools.csharp-1.23.8/.omnisharp/1.37.5/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/simon_rober/.vscode/extensions/ms-dotnettools.csharp-1.23.8/.omnisharp/1.37.5/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/simon_rober/.vscode/extensions/ms-dotnettools.csharp-1.23.8/.omnisharp/1.37.5/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/simon_rober/.vscode/extensions/ms-dotnettools.csharp-1.23.8/.omnisharp/1.37.5/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/simon_rober/CS02 - Introduction to Unity'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/simon_rober/CS02 - Introduction to Unity/CS02 - Introduction to Unity.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/simon_rober/CS02 - Introduction to Unity/Assembly-CSharp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/simon_rober/CS02 - Introduction to Unity'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/simon_rober/CS02 - Introduction to Unity/Assembly-CSharp.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/simon_rober/CS02 - Introduction to Unity' on host 38583.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/home/simon_rober/CS02 - Introduction to Unity/Assembly-CSharp.csproj'.
/home/simon_rober/CS02 - Introduction to Unity/Assembly-CSharp.csproj
/home/simon_rober/.vscode/extensions/ms-dotnettools.csharp-1.23.8/.omnisharp/1.37.5/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1180,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /home/simon_rober/CS02 - Introduction to Unity/Assembly-CSharp.csproj
## Steps to reproduce
I desire to use unity and want to edit the C# files with VS Code on Ubuntu 20.04, hence I took a look at this tutorial: 
https://code.visualstudio.com/docs/other/unity

I installed .Net:
dotnet --info:
".NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.102/

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.102 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download"

Further I installed the C# extension to VS Code and managed to succesfully alter the External Script Editor to VS Code.
By double clicking on the script in Unity, VS Code automatically openend with the script and the extra files as expected.

## Expected  behavior
intellisense should work and the extension should not fail.

## Actual behavior
When I started to program I noticed that Intellisence for Unity does not work. There also appeared a the above error output.

## Already tried:
I already tried to change "    <TargetFrameworkVersion>v4.7.1</TargetFrameworkVersion>" to "    <TargetFrameworkVersion>v5.0.2</TargetFrameworkVersion>" in the Assembly-CSharp.csproj file. This did not alter the behavior.

**Comment by Amogh-Mittal** [comment]
I am also a unity User and the solution is pretty simple. Omnisharp is asking you to download the .net Framework Developers pack so that You can develop apps in C#.
[Here is the link to download it.](https://www.microsoft.com/en-us/download/details.aspx?id=56119)

**Comment by simonrober** [comment]
Thanks for responding!
I tried to install one of these before, but since it is only available in .exe file for windows, I don't know how to proceed. Is there a version for Linux or should start tampering around with wine?

**Comment by JoeRobich** [comment]
@simonrober For Linux you will want to install the stable Mono and set "omnisharp.useGlobalMono" to "always". https://www.mono-project.com/download/stable/#download-lin

**Comment by simonrober** [comment]
@JoeRobich It seems to have done the job. Many thank!!!

**Comment by DominicTobias** [comment]
Hi does anyone know how to install it for Mac? Same issue with the link being .exe. I installed the latest .NET Mac package but not sure how to check version (4.8.0 I believe) but changing Unity .csproj to that and it still can't be found :/

**Comment by devviktoria** [comment]
With Unity 2020.3 on Ubuntu 18.04 I also had to select in Unity: Edit/Preferences/External Tools Generate csproj files for Embedded Packages, Local Packages and Registry packages. Without the last one I got similar message to this:
Could not find method '.ctor' due to a type load error: Could not set up parent class, due to: Could not set up parent class, due to:  assembly:Unity/Hub/Editor/2020.3.2f1/Editor/Data/NetStandard/ref/2.0.0/netstandard.dll

**Comment by PGgit08** [comment]
Thank you so much @Amogh-Mittal

**Comment by FransHuntink** [comment]
Thx @DominicTobias and @JoeRobich - Couldn't get intellisense to work on my Mac using vscode despite having installed Mono. I now set it up to always use global mono and that fixed my issue.

**Comment by Alej-P** [comment]
> For lost travelllers you need to set `"omnisharp.useGlobalMono": "always"` in VSCode settings otherwise it doesn't work in Mac... seems like kind of an important thing but it's tucked away in a Changelog.
> 
> And for Mac users you need to correct the version in `.csproj`, at the time of writing change it to `4.8` instead of `4.7.1`.

on top of that, I was seeing 2 versions of omnisharp in ~/.vscode/extensions/ms-dotnettools.csharp-1.23.13
VSCode was downloading the latest one but failing to update the omnisharp.path entry in ~/Library/Application Support/Code/User/settings.json to point to the latest version

**Comment by francisLee777** [comment]
> I am also a unity User and the solution is pretty simple. Omnisharp is asking you to download the .net Framework Developers pack so that You can develop apps in C#.
> [Here is the link to download it.](https://www.microsoft.com/en-us/download/details.aspx?id=56119)
> 
> Hope this helps.😀

the link has discarded.

**Comment by JoeRobich** [comment]
You can find the .NET Framework 4.7.1 developer pack at https://dotnet.microsoft.com/download/dotnet-framework/net471

**Comment by mehmet0zen** [comment]
> For lost travelllers you need to set `"omnisharp.useGlobalMono": "always"` in VSCode settings otherwise it doesn't work in Mac... seems like kind of an important thing but it's tucked away in a Changelog.
> 
> And for Mac users you need to correct the version in `.csproj`, at the time of writing change it to `4.8` instead of `4.7.1`.

OMG Thank GOD!!!!!! You are a really TIME SAVER, its been ages. I was like what the hack am I doing wrong but thanks to you I only had to change it to always... WAS IT THAT SIMPLE??? I wanna cry thanks a lot.

**Comment by chandujr** [comment]
I am on Linux. What I did to solve the issue was:
1. Uninstalled VS Code C# extension
2. Updated mono and mono-msbuild
3. Reinstalled C# extension
4. Set `omnisharp.useModernNet` to `false` in VS Code Settings
5. Restart VS Code

**Comment by hsmkp4** [comment]
@JoeRobich to be more specific that is link for [.NET Framework 4.7.1 developer pack](https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net471-developer-pack-offline-installer)

**Comment by BugzTheBunny** [comment]
> You can find the .NET Framework 4.7.1 developer pack at https://dotnet.microsoft.com/download/dotnet-framework/net471

Sheesh, i've installed everything besides this one, after installing this, everything works.
(Windows 11)
Thanks.

**Comment by wow64cpu** [comment]
> I am on Linux. What I did to solve the issue was:
> 
>     1. Uninstalled VS Code C# extension
> 
>     2. Updated mono and mono-msbuild
> 
>     3. Reinstalled C# extension
> 
>     4. Set `omnisharp.useModernNet` to `false` in VS Code Settings
> 
>     5. Restart VS Code

Thank you very much! I tried to set up VSCode for Unity under Ubuntu 22, your instructions helped me.

In the second paragraph, I performed a reinstallation of mono and mono-msbuild as stated here - https://gist.github.com/petergloor/39ba915d3a66d138448ed57be6fe93ca
