### ISSUE TITLE
[Feature Request]: Add support of exception filters 

### ISSUE THREAD

**Issue by vchirikov** [OmniSharp/omnisharp-vscode#4356]
Hi, it's really huge feature for any developer and I miss it so much in vs code.

**Comment by gregg-miskelly** [comment]
We are currently waiting on https://github.com/microsoft/debug-adapter-protocol/issues/164, but agreed that this would be a very useful feature to add.

**Comment by vchirikov** [comment]
https://github.com/microsoft/debug-adapter-protocol/issues/164 is merged 🎉

**Comment by gregg-miskelly** [comment]
This is fixed in 1.23.12

**Comment by vchirikov** [comment]
@gregg-miskelly Recently I tried to use few exception filters, but seems that the only one negative filter can be applied.
So, for example:
* `!System.Threading.Tasks.TaskCanceledException,!Confluent.Kafka.Admin.CreateTopicsException` doesn't work
* `!Confluent.Kafka.Admin.CreateTopicsException` works fine.

I think we need something to exclude several types of exceptions.

**Comment by gregg-miskelly** [comment]
Your entire filter is either an include list or an exclude list. So the exclamation mark just goes at the start.

**Comment by vchirikov** [comment]
@gregg-miskelly thank you and sorry for distraction, it was not obvious to me

**Comment by gregg-miskelly** [comment]
@vchirikov No problem. Thanks for asking the question. If it was confusing to you the documentation should probably be improved.
