### ISSUE TITLE
How to use .NET 5 SDK without upgrade Visual Studio to 16.8

### ISSUE THREAD

**Issue by superbull** [OmniSharp/omnisharp-vscode#4358]
I have both **Visual Studio 16.6.2** and vscode installed on my Win10. Dotnet 5.0 sdk is installed.

My net5.0 project can build successfully but there is no IntelliSense in vscode.
For company reason I cannot upgrade to Visual Studio 16.8 for now.

Is there a way to configure some settings to let the IntelliSense work in vscode?

**Comment by superbull** [comment]
I downloaded the latest omnisharp, and manually set the `omnisharp.path`, but the `MSBuilderLocator `still choose to use the MSBuild comes from Visual Studio:

```
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 4 MSBuild instance(s)
            1: Visual Studio Professional 2017 15.9.28307.905 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin"
            2: Visual Studio Build Tools 2017 15.9.28307.905 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            3: Visual Studio Professional 2019 16.6.30204.135 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"
            4: StandAlone 16.8.0 - "D:\software\portable\omnisharp-win-x64\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Professional 2019 16.6.30204.135 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"
```

**Comment by filipw** [comment]
you can add `omnisharp.json` to the root of your workspace with the following content

```
{
   "msbuild": {
       "useBundledOnly": true
   }
}
```

For global effect, the file can be put into `%USERPROFILE%/.omnisharp/`

**Comment by superbull** [comment]
Thanks a lot!

**Comment by YaseenYo** [comment]
> {
>    "msbuild": {
>        "useBundledOnly": true
>    }
> }

Thanks a Lot, Brother...

**Comment by tngmrk77** [comment]
Hi @YaseenYo, where I must add ? 
{
"msbuild": {
"useBundledOnly": true
}
}

**Comment by JoeRobich** [comment]
OmniSharp is removing their bundled MSBuild, see announcement https://github.com/OmniSharp/omnisharp-vscode/issues/5120

It is recommended to set "omnisharp.useModernNet" to "true" and have a .NET 6 SDK installed when working with .NET (Core) projects.

**Comment by tngmrk77** [comment]
I don t know where set omnisharp.useModernNet to true ☹


Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows

________________________________
Da: Joey Robichaud ***@***.***>
Inviato: Thursday, April 21, 2022 7:36:39 PM
A: OmniSharp/omnisharp-vscode ***@***.***>
Cc: tngmrk77 ***@***.***>; Comment ***@***.***>
Oggetto: Re: [OmniSharp/omnisharp-vscode] How to use .NET 5 SDK without upgrade Visual Studio to 16.8 (#4358)


OmniSharp is removing their bundled MSBuild, see announcement #5120<https://github.com/OmniSharp/omnisharp-vscode/issues/5120>

It is recommended to set "omnisharp.useModernNet" to "true" and have a .NET 6 SDK installed when working with .NET (Core) projects.

**Comment by tngmrk77** [comment]
Estension is downloaded but…
Can you please help me? If you connect remotely on my pc can you solve the problem?



***@***.***

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows

**Comment by JoeRobich** [comment]
@tngmrk77 Can you open a new issue describing the issues that you are seeing, please provide all the requested logs. The OmniSharp Log  & C# logs from the VS Code Output Pane will be most useful.
