### ISSUE TITLE
Reference counter is jittering

### ISSUE THREAD

**Issue by paolord** [OmniSharp/omnisharp-vscode#4367]
## Issue Description ##
The reference counter jitters every time I type.
I have a gif of what is happening [here](https://imgur.com/M4xF3se)
## Steps to Reproduce ##
I installed C# extension on vscode, and from the start it jittered like that.
## Expected Behavior ##
not jitter
## Actual Behavior ##
the reference counter moves up and down
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.52.1
**C# Extension**: 1.23.8

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.8|
|git-graph|mhutchie|1.28.0|
|identical-sublime-monokai-csharp-theme-colorizer|maximetinu|0.11.1|
|remote-wsl|ms-vscode-remote|0.52.0|
|scala|scala-lang|0.5.1|
|unity-debug|Unity|3.0.2|
|unity-tools|Tobiah|1.2.12|;

</details>

**Comment by filipw** [comment]
Thanks for capturing the GIF. However, this is a VS Code issue not a C# extension issue.
It is tracked here https://github.com/microsoft/vscode/issues/113384. Perhaps you can attach your information to that issue. Thanks.
