### ISSUE TITLE
Couldn't load ASP.NET website automatically

### ISSUE THREAD

**Issue by NTaylorMullen** [OmniSharp/omnisharp-vscode#4375]
**Azure DevOps work item:** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1265977

**Testcases Affected**
All scenarios via debug with VSCode.

**Repro Steps**

1. Create a folder and create a new console app. :
```
mkdir Angular
cd Angular
dotnet new angular 
```
2. Open the folder with VSCode.
```
code .
```
3. Install C# extension.
4. Add required assets manually.
a. Open the Visual Studio Code command palette (View->Command Palette)Open the Visual Studio Code command palette (View->Command Palette)
b. run the command: '.NET: Generate Assets for Build and Debug'.
5. Press F5 and select '.NET Core'.
6. Update the argument of 'Program'.
![image](https://user-images.githubusercontent.com/70516076/104573418-d479db80-568f-11eb-9199-09769eb0763d.png)
Update:
![image](https://user-images.githubusercontent.com/70516076/104573388-ca57dd00-568f-11eb-9143-03594470c47b.png)
7. Press F5 to start debugging. 

**ACTUAL**
Couldn't load the website automatically.

**EXPECTED**
The program running correctly and load web site automatically.

**INVESTIGATION**
The web site display correctly when I tried to open it manually with listening URL in debug console window:
![image](https://user-images.githubusercontent.com/70516076/104573683-228edf00-5690-11eb-8dc9-87a76f98a041.png)

**Comment by gregg-miskelly** [comment]
@NTaylorMullen: This sounds like it is by design. What is your full launch.json?

**Comment by gregg-miskelly** [comment]
@NTaylorMullen: <ping>

**Comment by NTaylorMullen** [comment]
@gregg-miskelly sorry for the delay. I wasn't able to reproduce so I pinged the CTI team who originally filed the issue. I'll close this for now until there's a follow up on the other side.

**Comment by submodify** [comment]
Had this issue today working through an Microsoft ASP.NET tutorial. Browser fails to launch automatically when debugging. Found the issue to be "serverReadyAction" in auto generated launch.json. It had the pattern as:
`                "pattern": "\\\\bNow listening on:\\\\s+(https?://\\\\S+)"
`
too many backslashes?.... It work after changing it to:
`                "pattern": "\\bNow listening on:\\s+(https?://\\S+)"
`
for reference:
https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#starting-a-web-browser

**Comment by gregg-miskelly** [comment]
@submodify do you have repro steps?

**Comment by submodify** [comment]
Was following this tutorial:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-5.0&tabs=visual-studio-code

Basically this (from the VS Code terminal):
`dotnet new webapp -o RazorPagesMovie`
`code -r RazorPagesMovie`

then hitting CTRL-F5 to debug. This doesn't launch the browser automatically as expected.

Looking at the generated launch.json , the "serverReadyAction" pattern is showing:
`"pattern": "\\\\bNow listening on:\\\\s+(https?://\\\\S+)"`

changing it to this works as expected:
`                "pattern": "\\bNow listening on:\\s+(https?://\\S+)"`


Windows 10
VS Code: 1.53.2
.NET 5.0.103
C# Extension 1.23.9
