### ISSUE TITLE
OmniSharp refuses to start with unreadable message (Russian locale)

### ISSUE THREAD

**Issue by victorlapin** [OmniSharp/omnisharp-vscode#4381]
## Issue Description ##
When I open my Unity solution, OmniSharp started to error out, suddenly. Problem is, my system locale is Russian, I cannot read the error message and find the culprit. Installing older versions of VS Code and/or C# extension didn't help. Regenerating project files from Unity didn't help. I'm stuck.

## Steps to Reproduce ##
I can't point my finger at anything, just the usual Unity solution with latest VS Code package.

## Expected Behavior ##
Working OmniSharp

## Actual Behavior ##
OmniSharp not starting

### OmniSharp log ###
<details>Starting OmniSharp server at 05.02.2021, 11:02:02
    Target: d:\Unity\project-name

OmniSharp server started.
    Path: c:\Users\username\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.6\OmniSharp.exe
    PID: 12740

���誮� ������� ��������� ��ப�.
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).</details>

### C# log ###
<details>Empty</details>

## Environment information ##

**VSCode version**: 1.53.0
**C# Extension**: 1.23.9

<details><summary>Dotnet Information</summary>
����� SDK ��� .NET (��ࠦ��騩 �� global.json):
 Version:   5.0.102
 Commit:    71365b4d42

�।� �믮������:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.9|
|csharp-auto-formatter|bilal-arikan|0.1.0|
|hide-gitignored|npxms|1.1.0|
|ignore-files|ldez|0.1.0|
|unity-code-snippets|cemuka|0.1.0|
|unity-debug|Unity|3.0.2|
|vscode-icontheme-nomo-dark-macos|Gaulomatic|1.0.3|
|vscode-theme-onedark|akamud|2.2.3|;

</details>

**Comment by victorlapin** [comment]
Please disregard this... The issue was caused by hide-gitignored extension. OmniSharp is working now.

**Comment by filipw** [comment]
thanks!
