### ISSUE TITLE
[ERROR] Error: spawn cmd ENOENT

### ISSUE THREAD

**Issue by CepheidVariable** [OmniSharp/omnisharp-vscode#4388]
## Issue Description ##
No Intellisense features present
[ERROR] Error: spawn cmd ENOENT in the OmniSharp output log

I've tried adding "C:\Windows\System32" to environment path, but then I get an error in VSCode that OmniSharp needs .NET framework 4.7.2.

I tried adding "C:\Program Files\dotnet\sdk" to my path so OmniSharp would see my path to the .NET framework, but it has no effect.

## Steps to Reproduce ##
open any C# project folder within VSCode from the File > Open Folder option.

## Expected Behavior ##
Intellisense features present with no errors in output.

## Actual Behavior ##
Intellisense features missing, error in output.

### OmniSharp log ###
<details>Starting OmniSharp server at 2/8/2021, 3:15:15 PM
    Target: d:\Users\Cepheid Variable\Documents\c_sharp\test

[ERROR] Error: spawn cmd ENOENT
</details>

### C# log ###
<details>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.2.9200
 OS Platform: Windows
 RID:         win8-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download</details>

## Environment information ##

**VSCode version**: 1.53.0
**C# Extension**: 1.23.9

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.2.9200
 OS Platform: Windows
 RID:         win8-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|code-runner|formulahendry|0.11.2|
|csharp|ms-dotnettools|1.23.9|
|indent-rainbow|oderwat|7.5.0|
|jupyter|ms-toolsai|2020.12.414227025|
|material-icon-theme|PKief|4.5.0|
|path-intellisense|christian-kohler|2.3.0|
|powershell|ms-vscode|2020.6.0|
|python|ms-python|2021.1.502429796|
|rainbow-brackets|2gua|0.0.6|
|rainbow-csv|mechatroner|1.8.1|
|vscode-color|anseki|0.4.5|;

</details>

**Comment by CepheidVariable** [comment]
After further reading it looks like it may have to do with OmniSharp being built for .NET framework 4.7.2, while the latest support version for Windows 8 is only .NET framework 4.6.

Is there a version of OmniSharp that works with .NET 4.6 that I can verify this with?

**Comment by JoeRobich** [comment]
@CepheidVariable Sorry you are running into this. Windows 8 is well outside of support. Also, OmniSharp depends on Roslyn which has also upgraded their packages to NET 4.7.2. 

> Do I have any other options?

Windows 10 may still allow [a free upgrade](https://duckduckgo.com/?q=upgrade+to+windows+10+for+free&ia=web) from Windows 8.  Or perhaps dual booting a linux partition could be a good solution.

**Comment by CepheidVariable** [comment]
Thank you for the additional info.  Unfortunately, I'm unable to change my development environment at this time.
