### ISSUE TITLE
Not working on Raspberry Pi 4

### ISSUE THREAD

**Issue by Khhs167** [OmniSharp/omnisharp-vscode#4395]
Well, I am not suprised it does not work, but it would really help if a Raspberry PI build was made. Or at least an alternative. I am using a raspberry pi and want to develop C# apps on it, but the extension(C#) is not supported, any ideas.

This text is awful, excuse me.

**Comment by lokinfey** [comment]
I think this is the same problem in arm device (including Surface Pro X , Apple Silicon , Raspberry ............)

**Comment by Khhs167** [comment]
> I think this is the same problem in arm device (including Surface Pro X , Apple Silicon , Raspberry ............)

Raspberry PI has an ARM processor

**Comment by gregg-miskelly** [comment]
Duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/2771
