### ISSUE TITLE
Debug Console output contains ? missing glyph chars

### ISSUE THREAD

**Issue by AdrianJMartin** [OmniSharp/omnisharp-vscode#4398]
Issue Type: <b>Bug</b>

Issue Type: Bug

using something like the code below to output symbols ( above ascii 128 )

   static void Main(string[] args)
{
    Console.WriteLine( "Using PadRight" );

    for( var i = 0 ; i < 5 ; i ++ )
        Console.WriteLine("├".PadRight(79, '─') + "┤");

    Console.WriteLine( "");

    Console.WriteLine( "Using Literal");
    for( var i = 0 ; i < 5 ; i ++ )
        Console.WriteLine("├──────────────────────────────────────────────────────────────────────────────┤");
    
    Console.WriteLine( "");

    Console.WriteLine( "Using StringBuilder");
    var sb = new System.Text.StringBuilder();
    for( var i = 0 ; i < 5 ; i ++ )
        sb.AppendLine( "├".PadRight(79, '─') + "┤" );
    Console.Write( sb.ToString() );
    
}
???? characters appear in the Debug Console output ( assume its unmapped unicode chars)

Using PadRight
2 <--- dupe row indicator
├──────────────────────────────────────────────────────────────────────────────┤
├───��──────────────────────────────────────────────────────────────────────────┤
├────────���─────────────────────────────────────────────────────────────────────┤
├──────────────────────────────────────────────────────────────────────────────┤

Using Literal
├──────────────────────────────────────────────────────────────────────────────┤
├────────────────��─────────────────────────────────────────────────────────────┤
├─────────────────────���────────────────────────────────────────────────────────┤
├──────────────────────────────────────────────────────────────────────────────┤
├──────────────────────────────��───────────────────────────────────────────────┤

Using StringBuilder
├──────────────────────────────────────────────────────────────────────────────┤
├───��──────────────────────────────────────────────────────────────────────────┤
├────────���─────────────────────────────────────────────────────────────────────┤
├──────────────────────────────────────────────────────────────────────────────┤
├─────────────────��────────────────────────────────────────────────────────────┤

I tried different fonts etc - but the ? still appears

Running the same code in an C#/Notebook cell produces the correct output.
Equivalent Javascript produces the correct output

I also notice there is somesort of pattern to gliches, almost like a number of bytes read anomaly 

Extension version: 1.23.9
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.95GB free)|
|Process Argv|--crash-reporter-id 2fac746e-77c4-4c8f-abeb-9cc10d2b0ecb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by gregg-miskelly** [comment]
This is fixed in 1.23.12
