### ISSUE TITLE
Syntax highlight color of struct types not being used everywhere

### ISSUE THREAD

**Issue by bjornmp** [OmniSharp/omnisharp-vscode#4400]
## Environment data
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  2.2.300 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

VS Code: Version: 1.53.2
Extension: v1.23.9

## Expected  behavior
Expected behavior is that of Visual Studio 2019, with same color being used everywhere
![image](https://user-images.githubusercontent.com/8940144/108093702-4b830500-707e-11eb-9931-1e879e89c957.png)

## Actual behavior
Struct type color is not being used everywhere
![image](https://user-images.githubusercontent.com/8940144/108093536-1d9dc080-707e-11eb-8cd9-f9b0c7605440.png)

**Comment by JoeRobich** [comment]
@bjornmp You can enable semantic highlighting by setting both `csharp.semanticHighlighing.enabled: true` and `editor.semanticHighlighing.enabled: true` in your vs code settings. It works great with the included Visual Studio 2019 Dark theme.

**Comment by bjornmp** [comment]
> @bjornmp You can enable semantic highlighting by setting both `csharp.semanticHighlighing.enabled: true` and `editor.semanticHighlighing.enabled: true` in your vs code settings. It works great with the included Visual Studio 2019 Dark theme.

OMG, thank you! I wonder why this is disabled by default. Contrary to C++, in C# it's so important to know when a type is a class or a struct.

**Comment by JoeRobich** [comment]
> I wonder why this is disabled by default.

Initially there were concerns about performance. Also, in some scenarios, such as viewing diffs, where the output isn't ideal. Once these issues are addressed, we would turn it on by default. =)
