### ISSUE TITLE
It was not possible to find any installed .NET SDKs.

### ISSUE THREAD

**Issue by dstpierre** [OmniSharp/omnisharp-vscode#4409]
I'm trying to work on dotnet 5 project from my Debian Linux OS.

Here's the error I'm getting from Omnisharp log:

```
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/dstpierre/src/labs/ProfilNav/ProfilNav.csproj
It was not possible to find any installed .NET SDKs.
Install a .NET SDK from:
  https://aka.ms/dotnet-download
```

I have one dotnet SDK installed:

```sh
$ which dotnet
/snap/bin/dotnet
$ dotnet --version
5.0.103
```

I suppose the extension has some kind of preset to search for `dotnet` SDK, like in `/usr/local/bin` for instance.

I've tried to find a setting I could change and could not find anything related to the path of the `dotnet` installed.

What can I do from here? How can I tell the extension where to look for the installed `dotnet`?

Thanks

**Comment by JoeRobich** [comment]
@dstpierre The dotnet SDK resolver has issues with Snap installs. I found this comment on the dotnet/sdk snap issue that may resolve your issue - https://github.com/dotnet/sdk/issues/10403#issuecomment-621463370

**Comment by JoeRobich** [comment]
Please let me know if those instructions work for you and I'll add them to the Wiki.

**Comment by dstpierre** [comment]
I linked the snap version, in my case was:

```sh
# ln -s /snap/bin/dotnet /usr/local/bin/dotnet
```

Now doing a:

```sh
$ which dotnet
/usr/local/bin/dotnet
```

Reloaded the vs code sample project and it's still saying no SDK version found.

Feel free to close this, as I'm not going to pursue trying further.

**Comment by JoeRobich** [comment]
@dstpierre If you are able, installing the SDK from Apt should work.

**Comment by JoeRobich** [comment]
Also, there is another workaround listed [on our Wiki](https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshooting:-'The-.NET-Core-SDK-cannot-be-located.'-errors#linux-snap-instructions).

**Comment by rhyek** [comment]
> ```shell
> # ln -s /snap/bin/dotnet /usr/local/bin/dotnet
> ```
This worked for me on Ubuntu 20.10 using ms-dotnettools.csharp version v1.23.9 with no additional setup.

**Comment by dstpierre** [comment]
I've decided to regive another try, this time I installed dotnet-core SDK via asdf, I've create the symlink like @rhyek said it was working for them, here's my link

```sh
$ ls -al /usr/local/bin/dotnet
lrwxrwxrwx 1 root root 34 May 11 14:52 /usr/local/bin/dotnet -> /home/dstpierre/.asdf/shims/dotnet
$ which dotnet
/home/dstpierre/.asdf/shims/dotnet
```

I've added with the `omnisharp.json` workaround that @JoeRobich mentioned.

I've always the same issue. I just re-installed the extension and all dotnet since last February, but still the same issues.

Any pointer? We have old .NET 4.5 ASP.NET code bases that I'd like to migrate, but can't figure how to have the extension to find the damn .NET core version.

**Comment by dstpierre** [comment]
nevermind, the version 5 is now available via `apt` I followed those instructions which worked for me: https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian

**Comment by shahidriaz** [comment]
> > ```shell
> > # ln -s /snap/bin/dotnet /usr/local/bin/dotnet
> > ```
> 
> This worked for me on Ubuntu 20.10 using ms-dotnettools.csharp version v1.23.9 with no additional setup.

It did not worked for me - Unfortunately

**Comment by attairsilva** [comment]
> > > ```shell
> > > # ln -s /snap/bin/dotnet /usr/local/bin/dotnet
> > > ```
> > 
> > 
> > Isso funcionou para mim no Ubuntu 20.10 usando ms-dotnettools.csharp versão v1.23.9 sem configuração adicional.
> 
> Não funcionou para mim - Infelizmente

Também não funcinou para mim

**Comment by attairsilva** [comment]
Para dar certo no meu caro, eu removi a instalação que fiz via snap, e como @dstpierre sugeriu fiz pelo apt:

# sudo snap remove dotnet-sdk

Instalação pelo APT:

# wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
# sudo dpkg -i packages-microsoft-prod.deb
# sudo apt-get update; 
# sudo apt-get install -y apt-transport-https
# sudo apt-get update 
# sudo apt-get install -y dotnet-sdk-6.0

Em seguida configurei o path

# sudo nano ~/.bashrc
Inclui no final os caminhos (para o meu Ubuntu 20.04, foi colocado dentro do usr/share o dotnet):
DOTNET_ROOT=/usr/share/dotnet/sdk/6.0.102
export PATH=$PATH:$DOTNET_ROOT/current

No final carreguei as variaveis de ambiente com

# source ~/.bashrc
