### ISSUE TITLE
Debugging fails when using PathMap in dotnet5 csproj

### ISSUE THREAD

**Issue by lonix1** [OmniSharp/omnisharp-vscode#4412]
Issue moved from [dotnet/msbuild repo](https://github.com/dotnet/msbuild/issues/6167). Confirmed not an msbuild bug.

## Environment data
latest of everything
.NET SDK 5.0.103
Linux
VSCode 1.53.2
Extension 1.23.9

## Issue Description
I want to conceal the original paths from my assembly and from its stack traces. So I use this in my `.csproj` ([source1](https://www.codementor.io/@rowlandbanks/cleaner-stacktraces-13q3hbv2s7)) ([source2](https://stackoverflow.com/a/66221592/9971404)):
````xml
<PropertyGroup>
  <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>
</PropertyGroup>
````
This works when building and running. It does not work when debugging in vscode.

When I set any breakpoint, it fails. For example any breakpoint I set in `Program.cs` gives this error when the debug session starts:
> Could not load source './Program.cs': Incorrect format of 'source' message..

I also tried:
````xml
<PropertyGroup Condition="'$(Configuration)' != 'Debug'">
````
## Steps to Reproduce
- `dotnet new webapp`
- generate default `tasks.json` and `launch.json`
- add above code to `MyProject.csproj`
- add breakpoint in any `.cs` file
- start debugging

**Comment by gregg-miskelly** [comment]
You need to add a sourceFileMap (see [instructions](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#source-file-map)) to teach the debugger how to map your source files.

You will probably also want to use something more distinct than `./`. Ex: maybe `/Name-of-your-project/`
