### ISSUE TITLE
[Feature Request] Cursor placement within doc comment created by triple-slash

### ISSUE THREAD

**Issue by lonix1** [OmniSharp/omnisharp-vscode#4413]
## Environment data
latest of everything
extension 1.23.9

## Steps to reproduce
Enter triple slash before method to generate xml doc comment.

## Expected  behavior
The cursor should be placed within the summary block

## Actual behavior
The cursor should be placed after the entire comment

Example:

````cs
/// <summary>
/// *                                           <--- cursor should be placed here
/// </summary>
/// <param name="bar"></param>*                 <--- cursor is placed here
public void Foo(string bar) {
````

**Comment by 333fred** [comment]
This is a known limitation. There's not much we can do about it unless vscode adds a new lsp api that supports this type of edit with position.

**Comment by lonix1** [comment]
So this is different from the snippets stuff, which allows you to choose where to place the cursor?

**Comment by 333fred** [comment]
> So this is different from the snippets stuff, which allows you to choose where to place the cursor?

Correct. That's completion, where the user is presented with a list of things to insert. This is automatically inserted, which doesn't have an API for moving the cursor today. We're using on-type formatting to insert the text as a workaround.

**Comment by lonix1** [comment]
Ok I understand now thanks. I suppose you can close this then if there's nothing you can do about it.
