### ISSUE TITLE
Intellisense dialogue for signature help is smaller then the text

### ISSUE THREAD

**Issue by Abdullah2993** [OmniSharp/omnisharp-vscode#443]
## Environment data
`dotnet --info` output:
```
Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```
VS Code version: 1.2.1 
C# Extension version: 1.1.6

intellisense dialogue is smaller then the text and isn't scrollable so you can't see the text i.e arguments and options

![Prove](http://i.imgur.com/9628D34.png)

**Comment by DustinCampbell** [comment]
I just looked through the various bugs tracking this issue over in the VS Code repo. It looks like this on VS Code's current schedule and the conversation around the bug is happening here: https://github.com/Microsoft/vscode/issues/2465.
