### ISSUE TITLE
There is no formatter for 'csharp' files installed.

### ISSUE THREAD

**Issue by ChrisClaude** [OmniSharp/omnisharp-vscode#4434]
I have installed ms-dotnettools.csharp in vscode in the hope to get code formating and intellicense. I am coming from using Visual Studio to VScode. But now the extension is not delivering what it promised that it should. 

## Environment data
.NET SDK (reflecting any global.json):               
 Version:   5.0.104                                  
 Commit:    ca6b6acadb                               
                                                     
Runtime Environment:                                 
 OS Name:     Windows                                
 OS Version:  10.0.18363                             
 OS Platform: Windows                                
 RID:         win10-x64                              
 Base Path:   C:\Program Files\dotnet\sdk\5.0.104\   
                                                     
Host (useful for support):                           
  Version: 5.0.4                                     
  Commit:  f27d337295                                
                                                     
.NET SDKs installed:                                 
  3.1.407 [C:\Program Files\dotnet\sdk]              
  5.0.102 [C:\Program Files\dotnet\sdk]              
  5.0.104 [C:\Program Files\dotnet\sdk]              
                                                     
 
VS Code version: 1.54.1
f30a9b73e8ffc278e71575118b6bf568f04587c8
x64

C# Extension version: v1.23.9

## Steps to reproduce
Install extension and press alt + shift + F

## Expected  behavior
Should format .cs files and provide intellicence in those files

## Actual behavior
Does not format files and does not provide intellicense

**Comment by wjagodfrey** [comment]
Same issue, probably after upgrading to macOS Big Sur
