### ISSUE TITLE
could not locate .net core project assets were not generated

### ISSUE THREAD

**Issue by OfficialTeme** [OmniSharp/omnisharp-vscode#4438]
Please paste the output from your cliStarting OmniSharp server at 14.3.2021 klo 10.36.20
    Target: c:\Users\Teemu\Desktop\testi

OmniSharp server started.
    Path: c:\Users\Teemu\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.6\OmniSharp.exe
    PID: 7920

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.4.29519.181 - "F:\zulul\MSBuild\Current\Bin"
            2: StandAlone 16.8.0 - "c:\Users\Teemu\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.6\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.4.29519.181 - "F:\zulul\MSBuild\Current\Bin"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Teemu\Desktop\testi'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\Teemu\Desktop\testi'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Teemu\Desktop\testi\testi.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Teemu\Desktop\testi'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Teemu\Desktop\testi' on host 10260.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\Teemu\Desktop\testi\testi.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\Teemu\Desktop\testi\testi.csproj'.
c:\Users\Teemu\Desktop\testi\testi.csproj
F:\zulul\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1175,5): Error: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\Teemu\Desktop\testi\testi.csproj
pboard

**Comment by OfficialTeme** [comment]
I am new to coding and im getting this error when im trying to generate assets for build & debug
I have installed 5.0 version of .NET framework and verified it using cmd and typing "dotnet"

**Comment by JoeRobich** [comment]
@OfficialTeme Sorry you are running into issues. OmniSharp is picking up that you have an install of Visual Studio and trying to use the more complete build tools that are part of Visual Studio. However the tools provided by your install of Visual Studio do not support .NET 5. You could update your install of VS Community or add an `omnisharp.json` in the root folder of your project (or your users home directory) that will tell OmniSharp to use the included build tools.

```
{ 
  "msbuild": { 
       "useBundledOnly": true 
   } 
}
```

**Comment by OfficialTeme** [comment]
Yeah i figured that out, now it works fine and i can continue learning coding on c# @JoeRobich 
Thanks for the answer!
