### ISSUE TITLE
Invoking 'dotnet restore' hangs during omnisharp startup

### ISSUE THREAD

**Issue by natemcmaster** [OmniSharp/omnisharp-vscode#444]
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-002990)

Product Information:
 Version:            1.0.0-preview2-002990
 Commit SHA-1 hash:  54cd31b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

VS Code version: 1.2.1
C# Extension version: 1.1.6
## Steps to reproduce
1. Clear nuget caches.
2. Download and open an ASP.NET Core application (example https://github.com/aspnet/MusicStore/archive/release.zip)
3. `Command Palette > Omnisharp: Select Project > (your project)`
4. Omnisharp begins to auto-restore project (log shows `[INFORMATION:OmniSharp.DotNet.Tools.PackagesRestoreTool] Begin restoring project`)
5. Before this is finished, do `Command Pallet > dotnet: Restore Packages`
## Expected  behavior

Should immediately show available projects to restore, or at least indicate a restore is currently underway.
## Actual behavior

The next dialog box does not appear until OmniSharp has finished its initial restore on the project(s), which may be minutes later. Then the next command palatte option with available projects appears (`dotnet restore - (your project)`)

**Comment by DustinCampbell** [comment]
This is a great bug. Thanks for reporting!

**Comment by natemcmaster** [comment]
This doesn't reproduce anymore. VS Code shows an error right away if omnisharp hasn't started.
