### ISSUE TITLE
Development: npm i - authentication issue

### ISSUE THREAD

**Issue by kscott5** [OmniSharp/omnisharp-vscode#4441]
## Development
Azure DevOps allows the creation of a Personal Access Token (PAT) on my account. Share development instruction with linux and npm auth token access.

### First install:

- [x]    Node.js (8.11.1 or later)
- [x]    Npm (5.6.0 or later)

### To run and develop do the following:

- [ ]    Run npm i **authentication error _(suprised!!! msazure.pkgs.visualstudio.com)_**
- [ ]    Run npm run compile 
- [ ]   Open in Visual Studio Code (code .)
- [ ]    Optional: run npm run watch, make code changes
- [ ]    Press F5 to debug

![Screenshot from 2021-03-16 12-04-49](https://user-images.githubusercontent.com/132991/111359313-5ae37700-8659-11eb-8e09-f038c14d23e7.png)
![Screenshot from 2021-03-16 12-34-29](https://user-images.githubusercontent.com/132991/111359320-5dde6780-8659-11eb-8217-511a287afa1a.png)

**Comment by JoeRobich** [comment]
Hi @kscott5, thanks for reporting this issue. I opened a PR to fix the resolved url for those packages.
