### ISSUE TITLE
Missing build without launch configuration.

### ISSUE THREAD

**Issue by fairking** [OmniSharp/omnisharp-vscode#4443]
## Issue Description ##
How can I compile the project without launching it?

The default configuration created from .csproj file `.NET Core Launch (web)` is for launching the app.
But there is no configuration to just compile the project to check if there any compile errors.
I used to compile (F6 in VS) very often when I work.

I tried to remove `"request": "launch",` but it throws the following error: "_Attribute 'request' is missing from the chosen debug configuration._".

I think it must be explained in the documentation or added as an additional config.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.54.3
**C# Extension**: 1.23.9

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  2.1.814 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.113 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-close-tag|formulahendry|0.5.10|
|auto-complete-tag|formulahendry|0.1.0|
|auto-rename-tag|formulahendry|0.1.6|
|Bookmarks|alefragnani|13.0.4|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|csharp|ms-dotnettools|1.23.9|
|JavaScriptSnippets|xabikos|1.8.0|
|nativescript|NativeScript|0.12.1|
|nativescript-vue-extend|nuochong|0.0.2|
|night-owl|sdras|2.0.0|
|npm-intellisense|christian-kohler|1.3.1|
|powershell|ms-vscode|2021.2.2|
|prettier-vscode|esbenp|6.3.1|
|vetur|octref|0.33.1|
|vscode-eslint|dbaeumer|2.1.19|
|vscode-jumpy|wmaurer|0.3.1|
|vscode-status-bar-format-toggle|tombonnike|2.0.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.11|
|vue-vscode-extensionpack|sdras|0.2.0|
|vue-vscode-snippets|sdras|2.2.0|
|vuejs-extension-pack|mubaidr|1.2.1|;

</details>

**Comment by gregg-miskelly** [comment]
In VS Code, launch.json is about launching, not building. You can press `Ctrl`+`Shift`+`B` to bring up the 'Task Runner' selection, and then select the build task. You can also use 'Configure Default Build Task' from the command pallet, and then `Ctrl`+`Shift`+`B` will automatically build your project. If you would rather use a different shortcut key for build, you can also edit the VS Code shortcut keys to do so.
