### ISSUE TITLE
OmniSharp unable to load project with Razor?

### ISSUE THREAD

**Issue by ThomasAunvik** [OmniSharp/omnisharp-vscode#4446]
## Environment data
`dotnet --info` output:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.104
 Commit:    ca6b6acadb

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.104/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.112 [/usr/share/dotnet/sdk]
  5.0.104 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
VS Code version: 1.54.3
C# Extension version: 1.23.9

## OmniSharp log
https://gist.github.com/ThomasAunvik/e4bb57c12445136458908ce370445096

## Steps to reproduce

I am not sure, but my it seems like my project is using Razor library from netstandard2.0 which fails to load the project that is running on core 3.1.

## Expected  behavior

To omnisharp to load the project correctly.

## Actual behavior

Intellisense and other stuff like autocomplete stops working at all, and failes to load the main project.

```
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/home/thaun/Documents/Projects/orkel-pi/ProductionInsight/Api/Api.csproj'.
/home/thaun/Documents/Projects/orkel-pi/ProductionInsight/Api/Api.csproj
/usr/share/dotnet/sdk/5.0.104/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.ScopedCss.targets(118,3): Error: The "Microsoft.AspNetCore.Razor.Tasks.DiscoverDefaultScopedCssItems" task could not be loaded from the assembly /usr/share/dotnet/sdk/5.0.104/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/../../tasks/net46/Microsoft.NET.Sdk.Razor.Tasks.dll. Invalid Image Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /home/thaun/Documents/Projects/orkel-pi/ProductionInsight/Api/Api.csproj```

**Comment by ThomasAunvik** [comment]
Seems to be a Linux issue? Tried on Windows, and the project loaded fine, i should test this on an another linux system to see if i can reproduce the problem.

**Comment by nohwnd** [comment]
This looks like a problem in omnisharp-roslyn where incorrect Symbol is passed and ultimately fails in 
```
  "Message": "\"System.InvalidOperationException: Unexpected null
  at Roslyn.Utilities.Contract.Fail (System.String message) [0x00000] in <1b72cf009970430282a46c2931a92a23>:0 
  at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.MapToAppropriateSymbol (Microsoft.CodeAnalysis.ISymbol symbol) [0x0003a] in <1b72cf009970430282a46c2931a92a23>:0 
...
at OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService.Handle (OmniSharp.Models.FindUsages.FindUsagesRequest request)
```

**Comment by JoeRobich** [comment]
@ThomasAunvik It looks like this issue fixed in the version of OmniSharp (https://github.com/OmniSharp/omnisharp-roslyn/issues/2054) that ships with the latest version of the C# extension. Are you still seeing this issue with the latest version?

**Comment by ThomasAunvik** [comment]
Unfortunately yes, i am now at v.1.23.11, and i have still the same issue.

**Comment by ThomasAunvik** [comment]
I have created a test project with the similar functionality that i have in my own project, and can reproduce the project error.
Though it seems like it is something with the cshtml file that messes things up.

Here is the project: https://github.com/ThomasAunvik/RazorFailTest

![image](https://user-images.githubusercontent.com/9968151/116558705-02fa8a00-a900-11eb-937e-4aa6e15a3333.png)

When closing VSCode and then reloading the project, then i get the same error as the one in the original issue.

**Comment by ThomasAunvik** [comment]
Ok, so i haven't been able to reproduce the issue on an ubuntu vm for some reason, but i did manage to reproduce it in an Arch Linux vm.

Here is the virtual machine: [Download VM](https://drive.google.com/file/d/1Hf3Qo-_9Gd5GaZTyqfhFRDsOGrZ8me6z/view?usp=sharing)
User and root password: password.

And then open Visual Studio Code at `/home/thaun/Documents/RazorFaiLTest`, though by opening visual studio code should already open the project since it was open from before.

Though, there might be this other related issue i am having now since the RID of this dotnet is incorrectly set to `arch-x64` instead of `linux-x64` for some reason, which is also reproduced in this vm, related forum post: https://bbs.archlinux.org/viewtopic.php?id=265923

**Comment by JoeRobich** [comment]
@ThomasAunvik Thanks for all the great resources that you've provided. 

This issue is a packaging issue with Arch's dotnet-sdk package where the net46 Razor build tasks are missing from the Razor SDK. This file `/usr/share/dotnet/sdk/5.0.104/Sdks/Microsoft.NET.Sdk.Razor/tasks/net46/Microsoft.NET.Sdk.Razor.Tasks.dll` is missing from the package file listing https://archlinux.pkgs.org/rolling/archlinux-community-x86_64/dotnet-sdk-5.0.5.sdk202-1-x86_64.pkg.tar.zst.html.

Your project builds fine using `dotnet build` because it looks for the net5 build tasks which are available. Because the C# extension relies on Mono to support .NET Full Framework projects, we look for the Full Framework net46 build tasks which are missing.

This comment provides a work around https://github.com/OmniSharp/omnisharp-vscode/issues/4360#issuecomment-801181468 or you can try installing the dotnet-sdk-bin package which appears to have the necessary file https://archlinux.pkgs.org/rolling/chaotic-aur-x86_64/dotnet-sdk-bin-5.0.3.sdk200-1-x86_64.pkg.tar.zst.html.

@NTaylorMullen just a fyi

**Comment by NTaylorMullen** [comment]
@pranavkm @captainsafia is the SDK bit intentional or known?

**Comment by JoeRobich** [comment]
Wonder if this is a result of the Arch package being generated from source-build - https://github.com/archlinux/svntogit-community/blob/75fbd7b1a57ef88c5696a2e57fc8dd7ca910f21e/trunk/PKGBUILD#L91-L104. I don't imagine that it would build the full framework assemblies.

**Comment by ThomasAunvik** [comment]
It would seem downloading the -bin version fixed the problem 👍 
Closing this issue since #4360 already exists.
