### ISSUE TITLE
executable called when "format document" is run

### ISSUE THREAD

**Issue by jamesrobb** [OmniSharp/omnisharp-vscode#4449]
## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.404
 Commit:    470f6754b3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.404\

Host (useful for support):
  Version: 3.1.10
  Commit:  1721e39439

.NET Core SDKs installed:
  3.1.404 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
VS Code version: 1.54.3
C# Extension version: 1.23.9

## OmniSharp log

Accessing the log for the information I'd like is the purpose of this "issue"

## Steps to reproduce

N/A

## Expected  behavior

N/A

## Actual behavior

N/A

---

I'm sorry to report this as an issue but I was unable to find where I would ask such a question. I have the C# extensions installed for VScode (on Windows 10), and it has a format document feature that works quite nicely. However, I seem to be completely incapable of figuring out what actual command is run on a file when I run "format document".

How can I go about seeing what command the extension actually runs when I format the document? I went through all of the logs present on the output window, but I suppose it is possible I missed something.

The reason I would like this information is so that I can format a file from the command line using the same settings present in my VScode environment. It's not just the flags I need, I really just have no idea what executable is called nor what logs I would find such information in.

**Comment by filipw** [comment]
There is no executable invoked, the extension uses the OmniSharp language server (https://github.com/OmniSharp/omnisharp-roslyn) to process and track the state changes to your project.

Formatting is one of the endpoints on the language server that can be invoked.

**Comment by jamesrobb** [comment]
Are there some logs somewhere where I can see what endpoints VScode is invoking on the language server?
