### ISSUE TITLE
logs of interactions with language server

### ISSUE THREAD

**Issue by jamesrobb** [OmniSharp/omnisharp-vscode#4456]
## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.404
 Commit:    470f6754b3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.404\

Host (useful for support):
  Version: 3.1.10
  Commit:  1721e39439

.NET Core SDKs installed:
  3.1.404 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
VS Code version: 1.54.3
C# Extension version: 1.23.9

## OmniSharp log

Accessing the log for the information I'd like is the purpose of this "issue"

## Steps to reproduce

N/A

## Expected  behavior

N/A

## Actual behavior

N/A

---

Hello I opened another issue recently (https://github.com/OmniSharp/omnisharp-vscode/issues/4449) about how code is formatted using the extension. I learned that it is done via the language server and not via some executable. However, I am unable to find the logs of the extensions interactions with the language server. Are these visible somewhere so I can actually see what is going on?

P.S. Is there someone I should be reaching out to for support questions instead of creating issues (which I feel quite guilty about)?

**Comment by filipw** [comment]
you can set `"omnisharp.loggingLevel":"debug"` in the VS Code settings and then the logs (including all requests/responses) are captured in the `View > Output > OmniSharp` panel.
