### ISSUE TITLE
C# syntax not working as expected

### ISSUE THREAD

**Issue by githubhero** [OmniSharp/omnisharp-vscode#446]
VSCode Version: 1.2.1
OS Version: Mac OS X 10.11.5

Steps to Reproduce:

   - Download and install the onnisharp extension;
   - Just try to copy and paste some C# code;
   - Look at the source;

The code is not properly highlighted.

![csharp](https://cloud.githubusercontent.com/assets/1677287/16108982/af91a020-33a6-11e6-9485-6dd18bfad591.png)
![csharp2](https://cloud.githubusercontent.com/assets/1677287/16108986/b6c41576-33a6-11e6-973e-2309dd14129d.png)

The theme is Monokai

**Comment by DustinCampbell** [comment]
Hi! Which bits are not properly highlighted? It looks to me like all syntactic highlighting in your screenshots is correct. It's true that semantic highlighting of type names (e.g. "Console", "Person", etc.) is not supported yet. We're tracking that with #222.

Please feel free to re-open if I missed something obvious in your screenshots.

**Comment by githubhero** [comment]
Ok, I haven't previously seen #222
