### ISSUE TITLE
Not support 'await foreach'

### ISSUE THREAD

**Issue by nianwu** [OmniSharp/omnisharp-vscode#4464]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Actual behavior
![image](https://user-images.githubusercontent.com/31959790/112932394-64d4a200-9150-11eb-994e-ef229e3f3942.png)

**Comment by JoeRobich** [comment]
@nianwu You can set `csharp.semanticHighlighting.enabled` to `true` to enable more robust highlighting than the textmate grammar supports. It also works great with our included Visual Studio 2019 Light theme.

**Comment by nianwu** [comment]
Visual Studio 2019 Light theme
![image](https://user-images.githubusercontent.com/31959790/114963878-4553ae00-9ea0-11eb-95ff-dea52694581a.png)

**Comment by nianwu** [comment]
@JoeRobich
