### ISSUE TITLE
Refactor namespace to match folder and class to match filename

### ISSUE THREAD

**Issue by robrich** [OmniSharp/omnisharp-vscode#4466]
Feature request: refactor namespace & class name.

As a C# developer, how do I keep namespaces in sync with folders and class names in sync with filenames? This is the only feature blocking me from using VS Code as my full-time C# editor.

**Comment by filipw** [comment]
OmniSharp uses refactoring that are built into the Roslyn compiler (https://github.com/dotnet/roslyn).

There are already code actions for syncing the file name to the type name and vice versa (triggered via `ctrl+.`):
<img width="759" alt="Bildschirmfoto 2021-04-05 um 17 01 20" src="https://user-images.githubusercontent.com/1710369/113588696-c6a17a00-9630-11eb-9385-a79df8eb8b28.png">


There is also one for syncing the namespace to the folder:
<img width="703" alt="Bildschirmfoto 2021-04-05 um 17 01 31" src="https://user-images.githubusercontent.com/1710369/113588714-cacd9780-9630-11eb-91c7-d988dd5a8a73.png">

This is done on a case-by-case (file-by-file) basis, if you would like to have a sweeping change support, it's tracked by https://github.com/dotnet/roslyn/issues/14340
