### ISSUE TITLE
C# Debugger stuck while starting

### ISSUE THREAD

**Issue by AkhileshShahare** [OmniSharp/omnisharp-vscode#4473]
Issue Type: <b>Bug</b>

1. Press F5 to run the .NET app
2. Debugger stuck now....

Edit: The app launches fine w/o getting stuck if I restart my PC

Extension version: 1.23.9
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (6.84GB free)|
|Process Argv|--crash-reporter-id c72d8da3-24ef-486f-9bd7-b6d9c7da8a9d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30283811
openwslfolder:30282073
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30276952
pythondataviewer:30283453

```

</details>

**Comment by AkhileshShahare** [comment]
This does not seem to occur anymore.

**Comment by JoeRobich** [comment]
@AkhileshShahare  Closing this issue since it is no longer occuring. Please reopen or file a new issue if it returns.
