### ISSUE TITLE
Omnisharp Current State

### ISSUE THREAD

**Issue by Lobosque** [OmniSharp/omnisharp-vscode#4475]
I'm not sure whether this is the right place to raise this issue, but I think it is more appropriate than non-official forums, but please let me know if I should discuss this elsewhere.

I feel that the current state of Omnisharp is a complicated one... Development with VSCode + Omnisharp is very slow and can get very frustrating due to the amount of bugs that range from wrong syntax highlighting to random crashes, and performance is awful, sometimes taking anywhere from 15 to 30 minutes to parse 100kloc to 200kloc multi-project solutions, sometimes crashing halfway. Also, the support for Razor is bad.

I am not ranting or pointing fingers to the developers that spend their time and energy to make this project happen, and I ask other users to behave in a respectful way. But I would like to know if other Omnisharp users have had the same productivity problems, and are thinking of dropping or have dropped Omnisharp for other solutions.

If possible, I would like to know from the repository maintainers what the current state of the project is. Specially if there internal  consensus/awareness that the current software is instable, if there is a plan to make it better, and how the community can help.

Also, I've been asking myself lately if Omnisharp is actively supported and/or developed by Microsoft or is 100% driven by the community developers. Does anybody know?

It turns out that it is not making sense for us to double down on VS Code + Omnisharp + Linux anymore... Which is a shame because other options like  VS Studio or ReShaper IDE lags behind in portability, extensibility  and customization features, specially setting up the development environment with containers, which we rely heavily on.

**Comment by floyd-may** [comment]
100% echo these sentiments, and would be glad to try preview builds and contribute in any way I can. I had some really good successes with O# over the past few years, and I really love it. Unfortunately, in the past 8-9 months things have gotten much worse, and it's to the point that I'm having trouble estimating timelines and consistently delivering features in a modest (<100K LOC) codebase.

There's a community here that wants this to succeed! How can we help?

**Comment by BradBarnich** [comment]
It's sad that the c# support is vs code is so poor compared to other languages. I try it in earnest once or twice a year, and the experience is just frustrating for anything beyond 'hello world'. In contrast, the experience for c++, java, and golang is quite good when I've used it.

I highly recommend Rider, it is fast on even our largest c# code base, where VS + ReSharper is unusably slow.

There are definitely some unique capabilities that keep my coming back to VS Code (git UI, remote development). I wish Microsoft considered C# support to be important enough to support, seems like it would be a funnel of new C# users that the developer relations folks keep talking about trying to reach.

**Comment by chickenSandwich** [comment]
My organization is actively pursuing alternatives to Omnisharp due to the lack of direction and continuing bugs in this project.  These issues with false bugs being reported and extremely slow response times are slowing down our teams.  As for myself, I would prefer to echo @floyd-may: 

> There's a community here that wants this to succeed!  How can we help?

**Comment by floyd-may** [comment]
According to #4307 many of the issues we've been seeing have to do with a change that got introduced around August of last year. There was a new release cut a couple weeks ago that should make things... better... However, if I understand correctly, most of the effort in this project is headed towards converting it to use the language server protocol (LSP) to communicate with the Omnisharp server instead of the current custom protocol. That effort is still ongoing, and I'm probably going to wait to retry Omnisharp until it's complete.

_When that day does come_, I will be glad to try it again and dig in with the community, but it seems like right now we just need to step away and let them finish.

**Comment by dodyg** [comment]
> There was a new release cut a couple weeks ago that should make things... better

Apparently not https://github.com/OmniSharp/omnisharp-vscode/issues/4527

**Comment by Mithras** [comment]
For me Omnisharp does one of the following:

- Crashes for no reason (40% of the time)
- Eats all available CPU and Memory (40% of the time)
- Works (10% of the time)

At the current state of things I don't even know if it's helping or hurting my productivity. And I have no idea why the hell does it use Mono in 2021. I tried to build it for .NET Core but it doesn't work and nobody seems to care https://github.com/OmniSharp/omnisharp-roslyn/issues/1703#issuecomment-837710970

**Comment by Lobosque** [comment]
@JoeRobich would you mind giving us some feedback on these matters?

**Comment by Lobosque** [comment]
@filipw Hi, would you mind giving us some feedback on the project stability?

**Comment by BrightSoul** [comment]
I'm also having a rough time, expecially with multi-project solutions. For instance, squigglies stay on their line instead of following their line of code and I often need to rebuild for them to go away.
I'd also like to ping @filipw to know how's the project doing.

**Comment by Lobosque** [comment]
@BrightSoul @Mithras @floyd-may @BradBarnich et al

Although we never had any reply or feedback from the Omnisharp team, apparently the issue is fixed with the new `net6` based version.

If you haven't tested, all you have to do is upload to the latest version  of omnisharp-vscode (1.24) and add the following configuration to your vs code settings:

```
		"omnisharp.useModernNet": true,
		"omnisharp.useGlobalMono": "never",
		"omnisharp.path": "latest",
```

Please let me know if this fixes the issue for your too so we can close this issue.

**Comment by Mithras** [comment]
Yep, it works flawlessly for me. Momo was the only reason OmniSharp was unusable on Linux.

**Comment by filipw** [comment]
`"omnisharp.path": "latest",` is not needed and should be avoided because it will download a new build every single time there is a merge to omnisharp-roslyn repo. This is likely to be slow and destabilize the extension, or in extreme cases may even cause the extension to stop working if new OmniSharp Roslyn requires changes on the extension side.

Now that 1.24.0 is released the only settings to opt into .NET 6 build are

```
"omnisharp.useModernNet": true,
"omnisharp.useGlobalMono": "never", // the current default behavior is never anyway, though it may change
```

**Comment by Lobosque** [comment]
@filipw thanks for point that out, and for the effort on moving the omnisharp compilation to .net6

**Comment by lonix1** [comment]
@filipw If we are still stuck on net5, can we nonetheless install/use the new version of the extension? And if so, will all the updates not apply to us (because it seems like everything is behind a feature flag)?

**Comment by filipw** [comment]
OmniSharp requires .NET 6.x.x SDK to be present.
The old variant based on Mono is still maintained (for now).

**Comment by lonix1** [comment]
@filipw Thanks. Just to confirm I understand - I have net6 *Runtime* installed as a number of extensions need it. But my projects target net5, and the SDK installed is net5. Are you implying that is not good enough for this extension - it must have the v6 SDK rather than the Runtime?

**Comment by filipw** [comment]
Yes the .NET 6 SDK is necessary to be installed to use the .NET 6 build of Omnisharp, as it supplies the MSBuild.
