### ISSUE TITLE
Debugger pauses twice on user-unhandled exception when 'all exceptions' setting is enabled

### ISSUE THREAD

**Issue by natemcmaster** [OmniSharp/omnisharp-vscode#448]
## Environment data

`dotnet --info` output: 1.0.0-preview2-003116
VS Code version: 1.2.1
C# Extension version: 1.1.6
## Steps to reproduce

Create an app that throws a user-unhandled exception.
Debug Pane > Breakpoints > enable both 'All Exceptions' and 'User-Unhandled Exceptions'
![image](https://cloud.githubusercontent.com/assets/2696087/16128203/8dc8b2f4-33b4-11e6-9efd-377dae7d2be0.png)
Start debugging
## Expected  behavior

Only pauses on exception once. `Continue`-ing the debugger moves to the next step in app execution.
## Actual behavior

Pauses first time on exception. When 'Continue' is pressed, the debugger pauses again on the same exception.

**Comment by WardenGnaw** [comment]
This is by design. If you have All Exceptions enabled, it will stop on the line that throws the exception. If you also do not handle the exception, a unhandled exception will be displayed. 

The unhandled exception can be removed with a try catch block around the line that throws the exception.
