### ISSUE TITLE
Download dependency fail

### ISSUE THREAD

**Issue by heartacker** [OmniSharp/omnisharp-vscode#4499]
## Environment data
VS Code version:
版本: 1.56.0-insider (system setup)
提交: 394a2e4779ff767e2761a59a51b15848dcd24173
日期: 2021-04-13T11:13:44.235Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.14393
C# Extension version: v1.23.11

## OmniSharp log
Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (38361 KB). Done!
Validating download...
Package OmniSharp for Windows (.NET 4.6 / x64) failed integrity check. Retrying..
Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (38361 KB) Done!
Validating download...
Package OmniSharp for Windows (.NET 4.6 / x64) download from https://download.visualstudio.microsoft.com/download/pr/9166c456-55b4-4c77-92e5-92c9314f8eeb/4fdbe776755c2467591dcba0a900ed32/omnisharp-win-x64-1.37.8.zip failed integrity check. Some features may not work as expected. Please restart Visual Studio Code to retrigger the download.
Downloading package '.NET Core Debugger (Windows / x64)' (45048 KB). Done!
Validating download...
Package .NET Core Debugger (Windows / x64) failed integrity check. Retrying..
Downloading package '.NET Core Debugger (Windows / x64)' (45048 KB).

## Actual behavior
Package OmniSharp for Windows (.NET 4.6 / x64) download from https://download.visualstudio.microsoft.com/download/pr/9166c456-55b4-4c77-92e5-92c9314f8eeb/4fdbe776755c2467591dcba0a900ed32/omnisharp-win-x64-1.37.8.zip failed integrity check. Some features may not work as expected. Please restart Visual Studio Code to retrigger the download

**Comment by nohwnd** [comment]
After taking the recommended action of: 
> Please restart Visual Studio Code to retrigger the download. 

Were you able to get this to work? Is there an antivirus installed on your system?
