### ISSUE TITLE
Not generating correct namespaces

### ISSUE THREAD

**Issue by adammartiniri** [OmniSharp/omnisharp-vscode#4514]
I mean when in a project creating a new folder .
Then adding a class or enum or interface it should mention the main project namespace but extension only write the folder name as namespace.

**Comment by JoeRobich** [comment]
@adammartiniri Can you give the steps you are following to generate the class file and namespace? Do you have any other C# extensions which may be the source of this behavior?

**Comment by adammartiniri** [comment]
so sorry to fill this issue . I use another extension to generate class and interface called C# extension by JosKreativ .
it was stupid to make sure before filling the form.

**Comment by JoeRobich** [comment]
> so sorry to fill this issue

No worries! I hope they are able to help you.
