### ISSUE TITLE
Visual Studio 2019 Blue theme

### ISSUE THREAD

**Issue by simonbinyamin** [OmniSharp/omnisharp-vscode#4517]
There are currently two default themes, namely, Visual Studio 2019 Dark and Visual Studio 2019 Light, It would be great to have a Visual Studio 2019 Blue as well

**Comment by BlueStaggo** [comment]
I decided to have my own take. Here's my result:
![image](https://user-images.githubusercontent.com/71090710/118375587-7962e180-b5ba-11eb-8347-4ff185b24f70.png)
It's just Visual Studio 2019 Light with some blue in the UI. If this was part of the extension, it would probably look better than mine.

```json
"[Visual Studio 2019 Light]": {
    "editorLineNumber.foreground": "#aaa",
    "editorLineNumber.activeForeground": "#222",
    "tab.activeBackground": "#fff29d",
    "tab.inactiveBackground": "#364e6f",
    "tab.inactiveForeground": "#fff",
    "tab.border": "#364e6f",
    "editorGroupHeader.tabsBackground": "#293a56",
    "editorGroup.border": "#8e9bbc",
    "titleBar.activeBackground": "#d6dbe9",
    "gitDecoration.modifiedResourceForeground": "#d68100",
    "gitDecoration.untrackedResourceForeground": "#00c400",
    "gitDecoration.deletedResourceForeground": "#dd0000",
    "breadcrumb.background": "#fff29d",
    "breadcrumb.foreground": "#000",
    "breadcrumb.focusForeground": "#666",
    "icon.foreground": "#fff",
    "sideBarSectionHeader.background": "#4d6082",
    "sideBarSectionHeader.foreground": "#fff",
    "sideBarSectionHeader.border": "#8e9bbc",
    "sideBar.background": "#fff",
    "sideBar.border": "#ced4dd",
    "sideBar.foreground": "#000",
    "activityBar.background": "#293955",
    "list.inactiveSelectionBackground": "#ced4dd",
    "list.inactiveSelectionForeground": "#000",
},
```
Reference:
- https://unaura.com/wp-content/uploads/2015/12/ColorThemeBlue.png

Here is your theme:
![image](https://user-images.githubusercontent.com/71090710/118375770-ca270a00-b5bb-11eb-83f1-e615fe7d929e.png)
You should probably use my version instead.

**Comment by BlueStaggo** [comment]
I'm back again, but this time with a better Visual Studio 2019 Dark theme:
```json
"[Visual Studio 2019 Dark]": {
    "editorGroupHeader.tabsBackground": "#2d2d30",
    "tab.inactiveBackground": "#2d2d30",
    "tab.border": "#0000",
    "tab.activeBackground": "#007acc",
    "tab.inactiveForeground": "#fff",
    "tab.activeForeground": "#fff",
    "titleBar.activeBackground": "#2d2d30",
    "titleBar.inactiveBackground": "#2d2d30",
    "titleBar.activeForeground": "#9a9a9a",
    "editorGroup.border": "#3f3f46",
    "activityBar.background": "#2d2d30",
    "sideBarSectionHeader.background": "#2d2d30",
    "sideBarSectionHeader.border": "#3f3f46",
    "sideBar.background": "#252525"
}
```
Omnisharp's version:
![image](https://user-images.githubusercontent.com/71090710/118402604-80452f00-b662-11eb-8c0a-9c07a87f3cd6.png)
My version:
![image](https://user-images.githubusercontent.com/71090710/118402616-8f2be180-b662-11eb-9877-963bc0e20300.png)

By the way, I shrunk the tabs through an extension called Monkey Patch.

**Comment by JoeRobich** [comment]
@simonbinyamin Unfortunately, we don't have any plans to add additional themes at this time. Our two included themes are intended to bring the syntax colors of the VS 2019 Light and Dark Editor themes to VS Code. We don't intend to ship themes witth changes to the out-of-the-box IDE colors.

I do encourage you to package and ship your theme on the VS Marketplace, as I am sure there are many other developers who would appreciate your work. For instructions you can follow this guide, https://code.visualstudio.com/api/extension-guides/color-theme#create-a-new-color-theme.

**Comment by simonbinyamin** [comment]
Ok thanks,
just published the extension under the name 'realvisualstudio19' for those interested,
BR
