### ISSUE TITLE
Omnisharp 'downloading packages' every time I open VS Code

### ISSUE THREAD

**Issue by akshayKhot** [OmniSharp/omnisharp-vscode#4522]
## Issue Description ##
When I open VS Code, the extension tries to re-download the packages even if it downloaded them last time. It disables the IntelliSense on the C# code until the download finishes, preventing you to make use of the extension. Clicking on `downloading packages` gives a `command not found` error. 

![image](https://user-images.githubusercontent.com/14203386/116219649-74540480-a769-11eb-84bd-1fe56a16a22b.png)

## Steps to Reproduce ##

1. Download the latest VS Code. 
2. Install the C# extension. 
3. After normal usage, close the editor and open it after a while. 

## Expected Behavior ##
- Once installed, the extension shouldn't try to install/download the packages each and every time I open VS Code. 
- It should provide IntelliSense immediately once you open VS Code. 

## Actual Behavior ##
- If I close VS Code and re-open it, the extension tries to download the packages, which takes a long time. 
- While it's downloading, I can't access the IntelliSense features for C#. 

### OmniSharp log ###
Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.37.9-beta.28...
Platform: darwin, x86_64

Downloading package 'OmniSharp for OSX, Version = 1.37.9-beta.28' (37354 KB).....

## Environment information ##

**VSCode version**: 1.55.2
**C# Extension**: 1.23.11

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  3.1.408 [/usr/local/share/dotnet/sdk]
  5.0.100 [/usr/local/share/dotnet/sdk]
  5.0.202 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.5.0|
|csharp|ms-dotnettools|1.23.11|
|gitlens|eamodio|11.4.1|
|go|golang|0.24.2|;

</details>

**Comment by filipw** [comment]
that's because you have "omnisharp.path":"latest" enabled in your settings. This opts you in to the beta builds which can come even several times a day.

You can remove this setting if you don't want to pull every beta pre-release.

**Comment by akshayKhot** [comment]
Hi @filipw, 

That resolved the issue. Thanks for the tip.  

Regards,
Akshay
