### ISSUE TITLE
Tests debug socket too long on domain users

### ISSUE THREAD

**Issue by valters-tomsons** [OmniSharp/omnisharp-vscode#4523]
## Issue Description ##

When logged in as a domain user which results in a longer `$HOME` path, trying to debug any unit tests fails with the following error message:

```
WARNING: Unable to connect to debuggerEventsPipeName '/home/internal.domain.com/name.surname/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.TestDebugEvents-592495'. Socket name '/home/internal.domain.com/name.surname/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.TestDebugEvents-592495' exceeds the maximum length 107. (Parameter 'path')
```

## Steps to Reproduce ##

1. Create a user inside of the domain (I guess a wierdly long username would work too)
2. Try to debug xunit project
3. Debug console will print a warning message

## Expected Behavior ##

Debugger gets attached and tests can be debugged. 
There should be an option to specify a different location for sockets (like `/tmp`)

## Actual Behavior ##

Debugger does not attach, socket name is too long.

## Environment information ##

**VSCode version**: 1.55.2
**C# Extension**: 1.23.11

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.10
 OS Platform: Linux
 RID:         ubuntu.20.10-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  3.1.408 [/usr/share/dotnet/sdk]
  5.0.202 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|code-spell-checker|streetsidesoftware|1.10.2|
|csharp|ms-dotnettools|1.23.11|
|csharpextensions|kreativ-software|1.3.6|
|csharpsortusings|jongrant|0.0.3|
|dotnet-test-explorer|formulahendry|0.7.5|
|githd|huizhou|2.2.4|
|gitlens|eamodio|11.4.1|
|quokka-vscode|WallabyJs|1.0.360|
|remote-ssh|ms-vscode-remote|0.65.4|
|remote-ssh-edit|ms-vscode-remote|0.65.4|
|rest-client|humao|0.24.5|
|roslynator|josefpihrt-vscode|3.2.0|
|shellcheck|timonwong|0.14.1|
|unique-window-colors|stuart|1.0.51|
|vim|vscodevim|1.20.1|
|vscode-eslint|dbaeumer|2.1.20|
|vscode-google-translate|funkyremi|1.4.13|
|vscode-html-format|mohd-akram|0.0.4|
|vscode-markdownlint|DavidAnson|0.40.4|
|vscode-nuget-gallery|patcx|0.0.24|;

</details>

**Comment by gregg-miskelly** [comment]
Thanks for opening this. The only work around I can think of for now would be to launch the test outside of the debugger and attach. You could put in a loop like the following to give yourself a chance:

```
while (!Debugger.IsAttached)
{
    Thread.Sleep(100);
}
```

**Comment by vedard** [comment]
I currently have the same problem :/

**Comment by valters-tomsons** [comment]
For people who absolutely cannot live without the ability to debug tests, here's a temporary workaround:

1. Open `extension.js` file in `~/.vscode/extensions/ms-dotnettools.csharp-1.23.12` (depending on version)
2. Find string `TestDebugEvents` and replace it with `TDE`
3. Restart vscode and debugger will be attachable

This helped bring down the length of my socket path to 101 characters.

**Comment by gregg-miskelly** [comment]
Thanks for fixing this @valters-tomsons!
