### ISSUE TITLE
VSCode downloads Omnisharp and .NET Tools when doing JS/Chrome debugging

### ISSUE THREAD

**Issue by Petermarcu** [OmniSharp/omnisharp-vscode#4525]
- VS Code Version:
Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT ia32 10.0.19041

Steps to Reproduce:

1. Create a hello world react js application: 
`npm install –g create-react-app`
`npx create-react-app hello-world-example`
2. Open the folder where you created the application in VSCode
3. `ctrl+shift+d` to open the debugger settings.
4. Click on the link to create a launch.json file.
5. Wait for VSCode to download over 140+MB of stuff for C# before showing the dropdown to select "Chrome" as the debugger target. Why is C# required for this scenario?

I don't expect to get C# tools as part of my JS workflow.

```
Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (38361 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'

Downloading package '.NET Core Debugger (Windows / x64)' (45048 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (Windows / x64)'

Downloading package 'Razor Language Server (Windows / x64)' (60477 KB).................... Done!
Installing package 'Razor Language Server (Windows / x64)'
```
ddcc1

**Comment by JoeRobich** [comment]
@Petermarcu Sorry we do not control this behavior. It seems that VS Code must activate all packages that include debugger extensions so that it can populate the list for you. The C# extension includes debugger support and as part of extension activation is downloading platform components necessary for the extension to function.

**Comment by gregg-miskelly** [comment]
The real fix for this requires the VS Code team to address: https://github.com/microsoft/vscode/issues/23251
