### ISSUE TITLE
Stop stealing focus when writing to Omnisharp Log

### ISSUE THREAD

**Issue by AArnott** [OmniSharp/omnisharp-vscode#4528]
## Issue Description ##

After opening a folder, or checking out a branch, or merging one, the Omnisharp Log output window keeps appearing, stealing focus from and hiding the Terminal which is where I'm actively typing in commands including the one that triggered Omnisharp's frequest focus stealing.

See also https://twitter.com/aarnott/status/1389232717674401796

## Steps to Reproduce ##

1. Open a folder with C# projects in it.
2. Open the terminal (<kbd>Ctrl</kbd>+<kbd>`` ` ``</kbd>)
3. Start typing (soon after opening the folder)
4. If you're too late, just try a `git checkout` command and OmniSharp Log will steal visibility and focus almost immediately.

## Expected Behavior ##

The terminal remains open.

## Actual Behavior ##

The OmniSharp Log steals focus and the terminal disappears.
This happens repeatedly, when I try to switch back to the terminal, focus is just stolen again.

### OmniSharp log ###
<details>Starting OmniSharp server at 5/3/2021, 9:09:34 AM
    Target: c:\git\streamjsonrpc\StreamJsonRpc.sln

OmniSharp server started.
    Path: c:\Users\andarno\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\OmniSharp.exe
    PID: 19264

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 4 MSBuild instance(s)
            1: Visual Studio Enterprise 2022 17.0.31230.316 - "C:\Program Files\Microsoft Visual Studio\2022\MergedInterops\MSBuild\Current\Bin"
            2: Visual Studio Build Tools 2017 15.9.28307.1500 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            3: Visual Studio Enterprise 2019 16.10.31230.10 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\main\MSBuild\Current\Bin"
            4: StandAlone 16.9.0 - "c:\Users\andarno\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Enterprise 2022 17.0.31230.316 - "C:\Program Files\Microsoft Visual Studio\2022\MergedInterops\MSBuild\Current\Bin"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\git\streamjsonrpc'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\git\streamjsonrpc\StreamJsonRpc.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\git\streamjsonrpc\src\StreamJsonRpc\StreamJsonRpc.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\git\streamjsonrpc\test\StreamJsonRpc.Tests\StreamJsonRpc.Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\git\streamjsonrpc\test\Benchmarks\Benchmarks.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\git\streamjsonrpc\test\StreamJsonRpc.Tests.ExternalAssembly\StreamJsonRpc.Tests.ExternalAssembly.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\git\streamjsonrpc'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\git\streamjsonrpc\src\StreamJsonRpc\StreamJsonRpc.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\git\streamjsonrpc' on host 60296.
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\git\streamjsonrpc\src\StreamJsonRpc\StreamJsonRpc.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\git\streamjsonrpc\src\StreamJsonRpc\StreamJsonRpc.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\git\streamjsonrpc\test\StreamJsonRpc.Tests\StreamJsonRpc.Tests.csproj
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
[warn]: OmniSharp.MSBuild.ProjectLoader
        Unable to locate the .NET SDK as specified by global.json, please check that the specified version is installed.
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\git\streamjsonrpc\test\StreamJsonRpc.Tests\StreamJsonRpc.Tests.csproj'.
c:\git\streamjsonrpc\test\StreamJsonRpc.Tests\StreamJsonRpc.Tests.csproj
c:\git\streamjsonrpc\test\StreamJsonRpc.Tests.ExternalAssembly\StreamJsonRpc.Tests.ExternalAssembly.csproj(0,0): Error: Unable to locate the .NET SDK as specified by global.json, please check that the specified version is installed.

[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\git\streamjsonrpc\test\StreamJsonRpc.Tests\StreamJsonRpc.Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\git\streamjsonrpc\test\Benchmarks\Benchmarks.csproj
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
2.1.523 [C:\Program Files\dotnet\sdk]
2.1.815 [C:\Program Files\dotnet\sdk]
2.2.301 [C:\Program Files\dotnet\sdk]
3.1.114 [C:\Program Files\dotnet\sdk]
3.1.408 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21228.15 [C:\Program Files\dotnet\sdk]
2.1.523 [C:\Program Files\dotnet\sdk]
2.1.815 [C:\Program Files\dotnet\sdk]
2.2.301 [C:\Program Files\dotnet\sdk]
3.1.114 [C:\Program Files\dotnet\sdk]
3.1.408 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21228.15 [C:\Program Files\dotnet\sdk]
2.1.523 [C:\Program Files\dotnet\sdk]
2.1.815 [C:\Program Files\dotnet\sdk]
2.2.301 [C:\Program Files\dotnet\sdk]
3.1.114 [C:\Program Files\dotnet\sdk]
3.1.408 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21228.15 [C:\Program Files\dotnet\sdk]
2.1.523 [C:\Program Files\dotnet\sdk]
2.1.815 [C:\Program Files\dotnet\sdk]
2.2.301 [C:\Program Files\dotnet\sdk]
3.1.114 [C:\Program Files\dotnet\sdk]
3.1.408 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21228.15 [C:\Program Files\dotnet\sdk]
2.1.523 [C:\Program Files\dotnet\sdk]
2.1.815 [C:\Program Files\dotnet\sdk]
2.2.301 [C:\Program Files\dotnet\sdk]
3.1.114 [C:\Program Files\dotnet\sdk]
3.1.408 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21228.15 [C:\Program Files\dotnet\sdk]
2.1.523 [C:\Program Files\dotnet\sdk]
2.1.815 [C:\Program Files\dotnet\sdk]
2.2.301 [C:\Program Files\dotnet\sdk]
3.1.114 [C:\Program Files\dotnet\sdk]
3.1.408 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21228.15 [C:\Program Files\dotnet\sdk]
2.1.523 [C:\Program Files\dotnet\sdk]
2.1.815 [C:\Program Files\dotnet\sdk]
2.2.301 [C:\Program Files\dotnet\sdk]
3.1.114 [C:\Program Files\dotnet\sdk]
3.1.408 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21228.15 [C:\Program Files\dotnet\sdk]
2.1.523 [C:\Program Files\dotnet\sdk]
2.1.815 [C:\Program Files\dotnet\sdk]
2.2.301 [C:\Program Files\dotnet\sdk]
3.1.114 [C:\Program Files\dotnet\sdk]
3.1.408 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21228.15 [C:\Program Files\dotnet\sdk]
2.1.523 [C:\Program Files\dotnet\sdk]
2.1.815 [C:\Program Files\dotnet\sdk]
2.2.301 [C:\Program Files\dotnet\sdk]
3.1.114 [C:\Program Files\dotnet\sdk]
3.1.408 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21228.15 [C:\Program Files\dotnet\sdk]
2.1.523 [C:\Program Files\dotnet\sdk]
2.1.815 [C:\Program Files\dotnet\sdk]
2.2.301 [C:\Program Files\dotnet\sdk]
3.1.114 [C:\Program Files\dotnet\sdk]
3.1.408 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21228.15 [C:\Program Files\dotnet\sdk]
2.1.523 [C:\Program Files\dotnet\sdk]
2.1.815 [C:\Program Files\dotnet\sdk]
2.2.301 [C:\Program Files\dotnet\sdk]
3.1.114 [C:\Program Files\dotnet\sdk]
3.1.408 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21228.15 [C:\Program Files\dotnet\sdk]
2.1.523 [C:\Program Files\dotnet\sdk]
2.1.815 [C:\Program Files\dotnet\sdk]
2.2.301 [C:\Program Files\dotnet\sdk]
3.1.114 [C:\Program Files\dotnet\sdk]
3.1.408 [C:\Program Files\dotnet\sdk]
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
[warn]: OmniSharp.MSBuild.ProjectLoader
        Unable to locate the .NET SDK as specified by global.json, please check that the specified version is installed.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "GetPackageDirectory" task failed unexpectedly.
NuGet.Packaging.Core.PackagingException: Unable to find fallback package folder 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages'.
   at NuGet.Packaging.FallbackPackagePathResolver..ctor(String userPackageFolder, IEnumerable`1 fallbackPackageFolders)
   at Microsoft.NET.Build.Tasks.NuGetPackageResolver.CreateResolver(IEnumerable`1 packageFolders)
   at Microsoft.NET.Build.Tasks.GetPackageDirectory.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\git\streamjsonrpc\test\Benchmarks\Benchmarks.csproj'.
c:\git\streamjsonrpc\test\Benchmarks\Benchmarks.csproj
c:\git\streamjsonrpc\src\StreamJsonRpc\StreamJsonRpc.csproj(0,0): Error: Unable to locate the .NET SDK as specified by global.json, please check that the specified version is installed.
C:\Program Files\dotnet\sdk\5.0.300-preview.21228.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(181,5): Error: The "GetPackageDirectory" task failed unexpectedly.
NuGet.Packaging.Core.PackagingException: Unable to find fallback package folder 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages'.
   at NuGet.Packaging.FallbackPackagePathResolver..ctor(String userPackageFolder, IEnumerable`1 fallbackPackageFolders)
   at Microsoft.NET.Build.Tasks.NuGetPackageResolver.CreateResolver(IEnumerable`1 packageFolders)
   at Microsoft.NET.Build.Tasks.GetPackageDirectory.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\git\streamjsonrpc\test\StreamJsonRpc.Tests.ExternalAssembly\StreamJsonRpc.Tests.ExternalAssembly.csproj
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
A compatible installed .NET SDK for global.json version [5.0.102] from [c:\git\streamjsonrpc\global.json] was not found.
Install the [5.0.102] .NET SDK or update [c:\git\streamjsonrpc\global.json] with an installed .NET SDK:
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\git\streamjsonrpc\test\StreamJsonRpc.Tests.ExternalAssembly\StreamJsonRpc.Tests.ExternalAssembly.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\git\streamjsonrpc\test\StreamJsonRpc.Tests.ExternalAssembly\StreamJsonRpc.Tests.ExternalAssembly.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: StreamJsonRpc
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: StreamJsonRpc.Tests
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\git\streamjsonrpc\test\Benchmarks\Benchmarks.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: StreamJsonRpc.Tests.ExternalAssembly
</details>

### C# log ###
(empty)

## Environment information ##

**VSCode version**: 1.55.2
**C# Extension**: 1.23.11

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.300-preview.21228.15
 Commit:    cc8452c18e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300-preview.21228.15\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  2.1.523 [C:\Program Files\dotnet\sdk]
  2.1.815 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  3.1.114 [C:\Program Files\dotnet\sdk]
  3.1.408 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21228.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.9.8|
|azure-pipelines|ms-azure-devops|1.183.0|
|azurite|Azurite|3.12.0|
|beautify|HookyQR|1.5.0|
|cpptools|ms-vscode|1.3.1|
|csharp|ms-dotnettools|1.23.11|
|debugger-for-chrome|msjsdiag|4.12.12|
|docker-linter|henriiik|0.5.0|
|docomment|k--kato|0.1.20|
|dotnet-test-explorer|formulahendry|0.7.5|
|EditorConfig|EditorConfig|0.16.4|
|git-project-manager|felipecaputo|1.7.1|
|gitconfig|sidneys1|2.0.1|
|githistory|donjayamanne|0.6.16|
|gitlens|eamodio|11.4.1|
|java|redhat|0.79.0|
|jshint|dbaeumer|0.11.0|
|npm-intellisense|christian-kohler|1.3.1|
|path-intellisense|christian-kohler|2.3.0|
|powershell|ms-vscode|2021.2.2|
|remote-containers|ms-vscode-remote|0.166.1|
|remote-wsl|ms-vscode-remote|0.54.6|
|remotehub|eamodio|0.5.0|
|theme-cobalt2|wesbos|2.2.5|
|tslint|eg2|1.0.46|
|vsc-docker|Zim|0.34.0|
|vscode-docker|ms-azuretools|1.12.1|
|vscode-eslint|dbaeumer|2.1.20|
|vscode-icons|vscode-icons-team|11.4.0|
|vscode-jasmine-test-adapter|hbenl|1.7.1|
|vscode-java-debug|vscjava|0.33.1|
|vscode-java-dependency|vscjava|0.18.3|
|vscode-java-pack|vscjava|0.14.0|
|vscode-java-test|vscjava|0.29.0|
|vscode-jest|Orta|3.2.0|
|vscode-markdownlint|DavidAnson|0.40.4|
|vscode-maven|vscjava|0.30.0|
|vscode-npm-script|eg2|0.3.21|
|vscode-pull-request-github|GitHub|0.25.1|
|vscode-test-explorer|hbenl|2.19.6|
|vscode-typescript-tslint-plugin|ms-vscode|1.3.3|
|vscode-versionlens|pflannery|1.0.9|
|vscode-zipfs|arcanis|2.3.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.12|
|vsliveshare|ms-vsliveshare|1.0.4131|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by JoeRobich** [comment]
@AArnott In VS Code settings you can set `"csharp.showOmnisharpLogOnError"` to `false`.
