### ISSUE TITLE
OmniSharp server with Snap .NET 5.0 is not working 

### ISSUE THREAD

**Issue by tomchavakis** [OmniSharp/omnisharp-vscode#4529]
## Issue Description ##
I've installed the .net 5.0 on Ubuntu from Snap. 
The Omnisharp server is not working in that way.

I've uninstall the Snap version and install it following the documentation guide:
https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu
Now the Omnisharp Server works perfectly.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.55.2
**C# Extension**: 1.23.11

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.10
 OS Platform: Linux
 RID:         ubuntu.20.10-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  5.0.202 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|advanced-new-file|patbenatar|1.2.2|
|ayu-one-dark|faceair|1.1.1|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|copy-text|salbert|0.4.9|
|csharp|ms-dotnettools|1.23.11|
|csharpextensions|kreativ-software|1.3.6|
|csharpfixformat|Leopotam|0.0.84|
|docomment|k--kato|0.1.20|
|dotnet-core-essentials|KishoreIthadi|0.0.8|
|git-graph|mhutchie|1.30.0|
|githistory|donjayamanne|0.6.16|
|github-vscode-theme|GitHub|4.1.1|
|gitlens|eamodio|11.4.1|
|go|golang|0.24.2|
|gruvbox-material|sainnhe|6.4.1|
|gruvbox-themes|tomphilbin|1.0.0|
|jira-plugin|gioboa|0.22.2|
|makefile-creator|zenor|0.0.3|
|markdown-all-in-one|yzhang|3.4.0|
|material-icon-theme|PKief|4.6.0|
|material-theme|zhuangtongfa|3.10.13|
|msbuild-project-tools|tintoy|0.3.15|
|netcore-snippets|doggy8088|3.15.1|
|online-help|salbert|0.2.8|
|path-intellisense|christian-kohler|2.3.0|
|polacode|pnp|0.3.4|
|prettier-vscode|esbenp|6.3.2|
|prettier-vscode|SimonSiefke|2.0.7|
|quicktype|quicktype|12.0.46|
|remote-containers|ms-vscode-remote|0.166.1|
|remote-ssh|ms-vscode-remote|0.65.4|
|remote-ssh-edit|ms-vscode-remote|0.65.4|
|remote-ssh-explorer|ms-vscode-remote|0.56.0|
|remote-wsl|ms-vscode-remote|0.54.6|
|rest-client|humao|0.24.5|
|simple-react-snippets|burkeholland|1.2.3|
|sqltools|mtxr|0.23.0|
|sqltools-driver-mysql|mtxr|0.2.0|
|supersharp|craigthomas|0.1.4|
|theme-cobalt2|wesbos|2.2.5|
|theme-dracula|dracula-theme|2.22.3|
|theme-github|thomaspink|1.0.1|
|todo-tree|Gruntfuggly|0.0.213|
|vs-sharper|eservice-online|0.2.0|
|vsc-material-theme|Equinusocio|33.2.0|
|vscode-coverlet|urbanoanderson|1.1.2|
|vscode-csharp-snippets|jorgeserrano|1.1.0|
|vscode-dotnet-adapter|derivitec-ltd|1.4.3|
|vscode-fileutils|sleistner|3.4.5|
|vscode-github-actions|cschleiden|0.17.0|
|vscode-java-debug|vscjava|0.33.1|
|vscode-maven|vscjava|0.30.0|
|vscode-pull-request-github|GitHub|0.25.1|
|vscode-remote-extensionpack|ms-vscode-remote|0.20.0|
|vscode-test-explorer|hbenl|2.19.6|
|vscode-theme-onelight|akamud|2.2.3|
|vscode-thunder-client|rangav|1.2.0|
|vscode-versionlens|pflannery|1.0.9|
|vscode-wakatime|WakaTime|5.0.1|
|vscode-yaml|redhat|0.18.0|
|vscodeilviewer|josephwoodward|0.0.1|
|vsliveshare|ms-vsliveshare|1.0.4131|;

</details>

**Comment by JoeRobich** [comment]
@tomchavakis  Please try following these instructions https://github.com/OmniSharp/omnisharp-vscode/wiki/Configuring-Snap-installs-of-dotnet-sdk

**Comment by tomchavakis** [comment]
@JoeRobich, thank you for the quick response.
The symlink resolves the issue. 
I think that it would be a good idea to add this information to the README file.
