### ISSUE TITLE
Terminating blazor wasm client sessions should end the server, too

### ISSUE THREAD

**Issue by connor4312** [OmniSharp/omnisharp-vscode#4530]
1. Start a blazor wasm debug session
2. Do something (like hit a wasm breakpoint) to focus the client debug session
2. Click the ⏹️ button in the debug toolbar to end the session
3. You're left with the `.NET Application Server` session still running

I think this is probably a bug, and that stopping the wasm debug session should also stop the server session. You can do this manually, or use the `cascadeTerminateToConfigurations` configuration property to have js-debug do this automatically. [Example use in a launch.json](https://github.com/microsoft/vscode/blob/486072c4a016a432b80ed7c5c913dd9ad70954b0/.vscode/launch.json#L237-L239)

**Comment by gregg-miskelly** [comment]
CC @captainsafia

**Comment by captainsafia** [comment]
Ah yeah, we recently moved to a model where we always launched a debug session for the .NET server and the logic we had to clean it up no longer applies.

I'm not familiar with the `cascadeTerminateToConfigurations` but that looks like a good thing to try out.

Transferring this to the aspnetcore repo.

**Comment by captainsafia** [comment]
This issue was moved to dotnet/aspnetcore#32393

**Comment by captainsafia** [comment]
@gregg-miskelly Moved. This can be closed now.
