### ISSUE TITLE
Variable names that starts with switch break C# text color themes

### ISSUE THREAD

**Issue by De-Panther** [OmniSharp/omnisharp-vscode#4539]
## Issue Description ##
Name a variable with a name that starts with `switch`, all the text after it will become white on dark themes.
On light themes it will become black.
Tested with all the basic themes:
Light, Light+, Quiet Light, Solarized Light, Visual Studio 2019 Light,
Abyss, Dark, Dark+, Kimbie Dark, Monokai, Monokai Dimmed, Red.

![image](https://user-images.githubusercontent.com/4749703/117474283-7422e880-af63-11eb-9561-927f8496012a.png)

## Steps to Reproduce ##
Name a variable with `switch` at the start. It's not consistent, some of the times this behavior will happen when you use the variable.

## Expected Behavior ##
Text colors shouldn't be one color after this name.

## Actual Behavior ##
All the text after variable name that starts with `switch` will become white on dark themes.
On light themes it will become black.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.56.0
**C# Extension**: 1.23.11

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|1.3.1|
|csharp|ms-dotnettools|1.23.11|
|php-intellisense|felixfbecker|2.3.14|
|shaderlabformatter|litefeel|0.4.0|
|unity-debug|Unity|3.0.2|
|vetur|octref|0.33.1|;

</details>

**Comment by De-Panther** [comment]
Also reported on the VSCode repo, but it seems that it's the extension bug.
https://github.com/microsoft/vscode/issues/123123

**Comment by JoeRobich** [comment]
@De-Panther Thanks for reporting this issue. It is a problem with the C# textmate grammar that ships with VS Code. The repo for the grammar is https://github.com/dotnet/csharp-tmLanguage.

As a workaround, you can set `csharp.semanticHighlighting.enabled` to `true` to get a richer experience (works great with the included Visual Studio 2019 themes).

**Comment by JoeRobich** [comment]
Closing since I moved the issue to the grammar repo.
