### ISSUE TITLE
Wiki: Windows troubleshooting

### ISSUE THREAD

**Issue by Siccity** [OmniSharp/omnisharp-vscode#4547]
[Troubleshooting: 'The .NET Core SDK cannot be located.' errors #General troubleshooting steps on Windows](https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshooting:-'The-.NET-Core-SDK-cannot-be-located.'-errors#general-troubleshooting-steps-on-windows)

In this section, the following text is found
> If the result of running where.exe is that a path to dotnet.exe is printed (example: C:\Program Files\dotnet\dotnet.exe) then the .NET SDK has successfully added itself to the Windows Path. There are no known reasons why PATH wouldn't be propagated to the VS Code process. You could try starting VS Code from the command prompt to see if that helps.

It should be added to this text that restarting your computer fixes the PATH propagation issue.

**Comment by gregg-miskelly** [comment]
Sorry for the delay. That advice was actually already mentioned at the top of the article, but I added some text to elaborate on it where you mentioned...
