### ISSUE TITLE
Format-on-type indentation bug

### ISSUE THREAD

**Issue by jfd16** [OmniSharp/omnisharp-vscode#4548]
## Steps to Reproduce ##
Enable "Editor: Format On Type" in VS Code preferences.

Copy and paste the following code:
```csharp
using System;

class C {
    
    public static void Main() {
        
        Console.WriteLine();
        Console.WriteLine();
    }
}
```
Then type `for (int i = 0;` on line 6 (the blank line before the first `Console.WriteLine();` statement)

## Actual Behavior ##
The statement on line 7 gets indented when `;` is typed.

## Expected Behavior ##
The `Console.WriteLine();` statement on line 7 should not be indented. In most cases the intention of the user is to create a new for-loop block instead of applying the for statement to the one below it. This issue does not exist for other control statements such as `if`, `while` and `switch`.

## Environment information ##

**VSCode version**: 1.56.0
**C# Extension**: 1.23.11

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

**Comment by 333fred** [comment]
This is a roslyn behavior, and not something we can control here. I'd suggest filling an issue on the dotnet/roslyn repository.

That being said, the behavior that occurs is exactly what I'd expect, and I'd file a bug on roslyn if it worked the way you suggest. The for syntax isn't complete, and the next line appears like it's the single embedded statement of that for loop.
