### ISSUE TITLE
Recurring error message in Omnisharp log.

### ISSUE THREAD

**Issue by KyleC69** [OmniSharp/omnisharp-vscode#4549]
## Issue Description ##

I haven't identified a specific problem linked to message. Omni sharp is very slow to respond at times though. The missing request message does appear often. Please advise.
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>
Received response for /v2/codestructure but could not find request.
Received response for /v2/blockstructure but could not find request.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No symbol found. File: /home/savaho/Documents/code/back/services/NetScraper.cs, Line: 314, Column: 18.
Received response for /completion but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /quickinfo but could not find request.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No symbol found. File: /home/savaho/Documents/code/back/services/DownloadService.cs, Line: 72, Column: 49.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.56.2
**C# Extension**: 1.23.11

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    383637d63f

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.203/

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  5.0.203 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.15 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.5.0|
|csharp|ms-dotnettools|1.23.11|
|mssql|ms-mssql|1.10.1|
|vscode-nuget-package-manager|jmrog|1.1.6|;

</details>

**Comment by filipw** [comment]
These are not really errors. The C# extensions sends requests to OmniSharp server for all kinds of information - file structure, hover help, intellisense, syntax highlighting, available code actions etc.
If you switch between different UI elements, VS Code can decide to cancel the request because there is no longer time for them to be displayed to you - in those cases, it is possible that by the time the response from the server arrives, the UI no longer needs it and this log message shows up.
