### ISSUE TITLE
Couldn't find a debug adapter descriptor for debug type 'coreclr' (extension might have failed to activate) in VScode version 1.56.2

### ISSUE THREAD

**Issue by cristian2422** [OmniSharp/omnisharp-vscode#4557]
from the moment we upgraded to VSCode to latest version 1.56.2 we can not debug any kind of project...
ERROR:

Couldn't find a debug adapter descriptor for debug type 'coreclr' (extension might have failed to activate).
Downloading package 'Razor Language Server (Windows / x64)' Failed at stage: downloadPackage
Error: unable to get local issuer certificate

just in case; we do not have this folder: C:\Users...vscode\extensions\ms-vscode-csharp not even the .razor directory.
we have the folder: ms-dotnettools.csharp-1.23.11. And inside this there is a .razor folder.

we saw other post on github but below commands did not work for us:

git clean -xfd
Update to the latest version of node
npm i -g gulp
gulp vsix:offline:package
we uninstalled the C# extensions packaged and then re-installing we get this failure:

Downloading package 'Razor Language Server (Windows / x64)' Failed at stage: downloadPackage
Error: unable to get local issuer certificate

When we try to run debug, we get a prompt to Select the process to attach to with a long list, what we should select?.

is this a bug on latest VCode Version as it did not happens in previous ones?
your help please_

**Comment by ptn77** [comment]
I'm having the same issue. Did you find a resolution?

**Comment by cristian2422** [comment]
there´s a proxy in between which block downloads.
from VSCode there´s a setting should be false: http.proxyStrictSSL 
that will solve it.

https://code.visualstudio.com/docs/setup/network
