### ISSUE TITLE
Not detecting projects on build in vscode

### ISSUE THREAD

**Issue by eByte23** [OmniSharp/omnisharp-vscode#456]
VS Code version: 1.3
C# Extension version: latest as of 21/06/2016

See this ticket as for details https://github.com/Microsoft/vscode/issues/7572

Issue is not detecting projects to build automatically and if solution/worksapce only contains 1 project with an entrypoint then run that.

**Comment by eByte23** [comment]
https://github.com/OmniSharp/omnisharp-roslyn/issues/589

**Comment by DustinCampbell** [comment]
This should be fixed by #590
