### ISSUE TITLE
No intellisense support in an Azure Function project after adding it to a solution with existing WebApi project in VS Code

### ISSUE THREAD

**Issue by chuckdawit** [OmniSharp/omnisharp-vscode#4571]
I added a Azure Function project to my VS Code solution (has other projects) but I'm not receiving any intellisense support. Is this normal, is there no intellisense support for Azure functions?

Do I need to add something, somewhere to get intellisense for these types of projects?

FYI - Maybe it's the way I added the Azure Function, it was added as a project to a solution. And I have other C# projects in the solution that are working fine. If I create a new Azure Function project on it's own, itellisense works fine, just not in a solution with other projects.

Using: C# VS Code latest version .Net 5 latest Azure Function tools lib C# extension v1.23.11

Git project to test: https://github.com/chuckdawit/TestProject 
This is a project I created to demo no intellisense support in the Azure Function project.

**Comment by JoeRobich** [comment]
@chuckdawit Can you share the OmniSharp log from the Output pane that is generated when opening the folder containing the non-working solution?

**Comment by chuckdawit** [comment]
Hi Joe. I hope this is the correct info. I selected OmniSharp Log and then cut and pasted it below.

> Starting OmniSharp server at 5/25/2021, 3:31:39 PM
    Target: /Users/charlespareto/testprojects/testItellisenseProjects

OmniSharp server started.
    Path: /Users/charlespareto/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.8/run
    PID: 14176

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.15.7 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.9.0 - "/Users/charlespareto/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.8/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/Users/charlespareto/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.8/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.9.0 - "/Users/charlespareto/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.8/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /Users/charlespareto/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.8/omnisharp/.msbuild/Current/Bin
            CscToolPath = /Users/charlespareto/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.8/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /Users/charlespareto/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.8/omnisharp/.msbuild
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/charlespareto/testprojects/testItellisenseProjects'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/charlespareto/testprojects/testItellisenseProjects'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/charlespareto/testprojects/testItellisenseProjects/AzureFunctions/AzureFunctions.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/charlespareto/testprojects/testItellisenseProjects/API/API.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/charlespareto/testprojects/testItellisenseProjects'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/charlespareto/testprojects/testItellisenseProjects' on host 13859.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/charlespareto/testprojects/testItellisenseProjects/AzureFunctions/AzureFunctions.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/charlespareto/testprojects/testItellisenseProjects/AzureFunctions/AzureFunctions.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/charlespareto/testprojects/testItellisenseProjects/AzureFunctions/AzureFunctions.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/charlespareto/testprojects/testItellisenseProjects/API/API.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/charlespareto/testprojects/testItellisenseProjects/API/API.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/charlespareto/testprojects/testItellisenseProjects/API/API.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: AzureFunctions
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: API
Received response for /v2/getcodeactions but could not find request.

**Comment by JoeRobich** [comment]
@chuckdawit I can see it trying to load Core, API, and Infrastructure projects. Which project is the Azure/Functions/ServiceBusQueueTrigger.cs file a part of?

**Comment by chuckdawit** [comment]
Well, I have given it different names while trying to test different things. It would be something like Functions.csproj or AzureFunctions.csproj, something like that. I can see it doesn't look like it's loading it, according to the log data I posted above. This makes me question the way I added the project to the solution (with the Azure Function tools wizard inside VS Code). Do you know if there is a file (settings) somewhere where I can check what OmniSarp is looking for in terms of projects to add? Maybe I can manually add a line, so that it loads it?

**Comment by JoeRobich** [comment]
@chuckdawit It might be easiest if you are able to share your solution file. The dotnet CLI tool can be used to add projects to solutions - see https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln#add

**Comment by JoeRobich** [comment]
> maybe OmniSharp uses the .sln as some sort of reference for loading all projects?

OmniSharp does use the solution file to determine which projects to load. We will display the opened solution file in the status bar.

**Comment by chuckdawit** [comment]
ah ha! Yes, that was it, I needed to add the .csproj to the .sln for OmniSarp to use it for intellisense. Problem solved. Should I close/resolve this issue?

**Comment by JoeRobich** [comment]
That is great news! I am happy to close it. Happy coding!

**Comment by chuckdawit** [comment]
Thanks for your help!
