### ISSUE TITLE
scriptcs is not recognized

### ISSUE THREAD

**Issue by R-Code-Studios** [OmniSharp/omnisharp-vscode#4585]
[Running] scriptcs "f:\RayyanPrograms\c++\test.cs"
'scriptcs' is not recognized as an internal or external command,
operable program or batch file.

[Done] exited with code=1 in 0.219 seconds

I get this error on clicking run in vscode, I am running a simple hello world program. yet this problem appears.
i even installed the scriptcs extension.

code:
using System;
namespace HelloWorld
{
        class Hello
          {
                                                                  static void Main(string[] args)
                                                                  {
                                                                      Console.WriteLine("Hello user!");
                                                                      Console.ReadKey();
                                                                  }
                                                              }
                                                          }

i am on windows 10 64bit vscode ver 1.56.2

i attached the screenshot too
![Screenshot 2021-06-01 170134](https://user-images.githubusercontent.com/81691504/120316794-6e6ab980-c2fb-11eb-87b9-c316b4b761af.png)

plase tell me the solution

**Comment by filipw** [comment]
I am sorry you are having troubles but this has nothing to do with the C# extension. The output that you are showing doesn't come from OmniSharp. We do not use scriptcs for anything.

**Comment by diulytofalo** [comment]
Same here.... In Visual Studio Code's repository, they said that is a C# extension problem. 😢
