### ISSUE TITLE
c# project build exe not running

### ISSUE THREAD

**Issue by R-Code-Studios** [OmniSharp/omnisharp-vscode#4586]
@filipw i got over the old poblem , but there is a new problem when i try to run the exe fie from bin/debug folder it runs for less than half a second

please dont close this issue until it is solved.

thankyou for your time

**Comment by filipw** [comment]
This repo is only related to the language extension providing intellisense and C# language services in the VS Code editor window. If you are having troubles with running dotnet/C# programs you should open an issue in https://github.com/dotnet/sdk

**Comment by JoeRobich** [comment]
@R-Code-Studios Sorry you are running into issues. As Filip has said, this repo is only responsible for C# experience within VS Code. If you are experiencing issues running C# programs, then https://github.com/dotnet/sdk would be better able to assist you. Closing
