### ISSUE TITLE
Not build, analyze, intellisense and no errors logs on linux with netcoreapp1.0

### ISSUE THREAD

**Issue by branciat** [OmniSharp/omnisharp-vscode#459]
## Environment data
.NET Command Line Tools (1.0.0-preview1-002702)
Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e
Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
VS Code version: 1.2.1
C# Extension version: 1.1.6

## output omnisharp log
[INFO] Starting OmniSharp at '/home/jerome/source/MediagralV2.Net/mediagralnet/Cedalis/Mediagral'...
[INFO] Started OmniSharp from '/home/jerome/.vscode/extensions/ms-vscode.csharp-1.1.6/.omnisharp/OmniSharp' with process id 9820...
OmniSharp: -s /home/jerome/source/MediagralV2.Net/mediagralnet/Cedalis/Mediagral --hostPID 9684 dnx:enablePackageRestore=false --stdio
[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location '/home/jerome/source/MediagralV2.Net/mediagralnet/Cedalis/Mediagral' on host 9684.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /home/jerome/source/MediagralV2.Net/mediagralnet/Cedalis/Mediagral
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: True
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update project /home/jerome/source/MediagralV2.Net/mediagralnet/Cedalis/Mediagral
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Add project /home/jerome/source/MediagralV2.Net/mediagralnet/Cedalis/Mediagral/project.json => 3db5a378-eb6c-4252-82a9-7c72cdb436ce
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] Mediagral/.NETCoreApp,Version=v1.0
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 198 and removed 0 file references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 224 and removed 0 documents.
[INFORMATION:OmniSharp.Startup] Configuration finished.
[INFO] Starting OmniSharp at '/home/jerome/source/MediagralV2.Net/mediagralnet/Cedalis/Mediagral'...
[INFO] Started OmniSharp from '/home/jerome/.vscode/extensions/ms-vscode.csharp-1.1.6/.omnisharp/OmniSharp' with process id 9880...
OmniSharp: -s /home/jerome/source/MediagralV2.Net/mediagralnet/Cedalis/Mediagral --hostPID 9684 dnx:enablePackageRestore=false --stdio
[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location '/home/jerome/source/MediagralV2.Net/mediagralnet/Cedalis/Mediagral' on host 9684.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /home/jerome/source/MediagralV2.Net/mediagralnet/Cedalis/Mediagral
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: True
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update project /home/jerome/source/MediagralV2.Net/mediagralnet/Cedalis/Mediagral
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Add project /home/jerome/source/MediagralV2.Net/mediagralnet/Cedalis/Mediagral/project.json => da4e295f-5862-4ad8-b4e8-f6be34d576bd
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]   Processing [ProjectState] Mediagral/.NETCoreApp,Version=v1.0
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 198 and removed 0 file references
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem]     Added 224 and removed 0 documents.
[INFORMATION:OmniSharp.Startup] Configuration finished.

I open a directory which contain one project.json.
The behaviour is normal with net451, break with netcoreapp1.0.

**Comment by DustinCampbell** [comment]
Hi @branciat, I'm wondering if this is still an issue for you. Could you try the latest release, [v1.3.0](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.3.0) and let me know if you're still experiencing this problem? If so, could you provide a project that reproduces the problem?

**Comment by DustinCampbell** [comment]
Closing this issue as there hasn't been a response. Let me know if this is still a problem.

**Comment by branciat** [comment]
Sorry I haven't seen the message, all is fine in the latest version. Thanks

**Comment by DustinCampbell** [comment]
That's great to hear @branciat. thanks for following up!
