### ISSUE TITLE
Using declaration (C# 8) not properly highlighted 

### ISSUE THREAD

**Issue by petrus0x13** [OmniSharp/omnisharp-vscode#4590]
## Issue Description ##
Using declaration (C# 8) not properly highlighted 

## Steps to Reproduce ##
Write a code with "using declaration".

## Expected Behavior ##
Both words: "using" and type definition should be properly highlighted.

## Actual Behavior ##
The word "using" is not highlighted.

![image](https://user-images.githubusercontent.com/1884647/120481114-104bde00-c3b0-11eb-9248-3160a4d5dadf.png)

## Environment information ##

**VSCode version**: 1.56.2
**C# Extension**: 1.23.12

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    383637d63f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.203\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.9.8|
|csharp|ms-dotnettools|1.23.12|
|jsonpath-extract|davidmarek|1.2.3|
|mssql|ms-mssql|1.10.1|
|preview-vscode|myh|1.3.0|
|remote-wsl|ms-vscode-remote|0.56.4|
|rest-client|humao|0.24.5|
|vscode-asa|ms-bigdatatools|0.8.3|
|vscode-azurefunctions|ms-azuretools|1.4.0|
|vscode-azureresourcegroups|ms-azuretools|0.4.0|
|vscode-hasher-extended|espresso3389|1.1.1|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by filipw** [comment]
Thanks for reporting this issue. It is really an issue with the C# textmate grammar located at https://github.com/dotnet/csharp-tmLanguage not with this extension. You can set `"csharp.semanticHighlighting.enabled":true` to enable semantic highlighting which will then work correctly.
