### ISSUE TITLE
$"Hello {myV...}" doesn't suggest variables.

### ISSUE THREAD

**Issue by Maelep** [OmniSharp/omnisharp-vscode#4597]
## Issue Description ##
Reported on Visual Studio Code GitHub, they redirected me to you. [Issue #125477](https://github.com/microsoft/vscode/issues/125477)

Concatenating string using $"My String {myVar}" doesn't suggest myVar like Visual Studio do.

## Steps to Reproduce ##

1. Create a method with a string variable (e.g. var myString = "My String")
2. Create a second string that will concatenate myString. (e.g. var mySecondString = $"This string contains {myString}")
3. You see that it doesn't suggest myString when starting typing it while it does in Visual Studio.

## Expected Behavior ##

![image](https://user-images.githubusercontent.com/53207714/120899447-1d770000-c630-11eb-93e9-073b184a58a0.png)

## Actual Behavior ##

![image](https://user-images.githubusercontent.com/53207714/120899456-2667d180-c630-11eb-905e-ec80bede7cff.png)

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.56.2
**C# Extension**: 1.23.12

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.202\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  5.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-using|Fudge|0.7.15|
|better-comments|aaron-bond|2.1.0|
|bracket-pair-colorizer-2|CoenraadS|0.2.0|
|comment-anchors|ExodiusStudios|1.9.5|
|csharp|ms-dotnettools|1.23.12|
|vscodeintellicode|VisualStudioExptTeam|1.2.14|;

</details>

**Comment by filipw** [comment]
This is the default behavior of VS Code - it does not trigger autocomplete in strings.

You can set:

```
    "editor.quickSuggestions": {
        "other": true,
        "comments": true,
        "strings": true
    }
```

to enable it explicitly.
