### ISSUE TITLE
New C# file is not added to the project (OmniSharp recognizes file as Miscellaneous)

### ISSUE THREAD

**Issue by jiristary** [OmniSharp/omnisharp-vscode#4603]
When I try to add new C# file into the project by clicking "New C# class".  It is added as miscellaneous file and not added to .csproj file. According to log, the project seems to be correctly recognized. Am I doing something wrong?

## OmniSharp log
Starting OmniSharp server at 10. 6. 2021 14:57:04
    Target: c:\apps\quantum\AIFighting\AIFighting\quantum_code\quantum_code.sln

OmniSharp server started.
    Path: c:\Users\stary\.vscode\extensions\ms-dotnettools.csharp-1.23.12\.omnisharp\1.37.11-beta.25\OmniSharp.exe
    PID: 15480

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.8.31005.135 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.11.0 - "c:\Users\stary\.vscode\extensions\ms-dotnettools.csharp-1.23.12\.omnisharp\1.37.11-beta.25\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.8.31005.135 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\apps\quantum\AIFighting\AIFighting\quantum_code'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\apps\quantum\AIFighting\AIFighting\quantum_code\quantum_code.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\apps\quantum\AIFighting\AIFighting\quantum_code\quantum.code\quantum.code.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\apps\quantum\AIFighting\AIFighting\quantum_code'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\apps\quantum\AIFighting\AIFighting\quantum_code' on host 1972.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\apps\quantum\AIFighting\AIFighting\quantum_code\quantum.code\quantum.code.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\apps\quantum\AIFighting\AIFighting\quantum_code\quantum.code\quantum.code.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\apps\quantum\AIFighting\AIFighting\quantum_code\quantum.code\quantum.code.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: quantum.code
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\apps\quantum\AIFighting\AIFighting\quantum_code\quantum.code\Game\AI\Decisions\TestDecision.cs added to workspace

**Comment by filipw** [comment]
There is no "new C# class" functionality in the extension. It sounds like you are using a feature from a different extension.

**Comment by jiristary** [comment]
> There is no "new C# class" functionality in the C# extension. It sounds like you are using a feature from a different extension (possibly from https://marketplace.visualstudio.com/items?itemName=jchannon.csharpextensions which has "new c# class" feature?).

Ah, yes, correct. Does not matter how is the file created though. If I use New File menu or directly copy some .cs file into the directory, result is the same. My csproj file uses the older format where every file is included specifically. Could that be the issue here?

**Comment by filipw** [comment]
thanks for confirming.

yes this is by design, if you manually create  the file and use the old csproj format, you need to manually include it in the project file. For the new project system this happens automatically
