### ISSUE TITLE
Formatter moves cursor to beginning of line

### ISSUE THREAD

**Issue by gabrieldechichi** [OmniSharp/omnisharp-vscode#4604]
Running the Omnisharp formatter places the cursor carret to the beginning of the line, if the line is empty, not respecting indentation.

## Steps to reproduce

1. Write an empty function with braces in new lines
2. Note that the cursor position is respecting the braces indentation
3. Format the document

![image](https://user-images.githubusercontent.com/15620434/121606124-d19ad100-ca0a-11eb-82d0-d2320466151e.png)

## Expected  behavior

Cursor should respect indentation

![image](https://user-images.githubusercontent.com/15620434/121606152-dbbccf80-ca0a-11eb-8c52-c21d6d28a93c.png)

## Actual behavior

Cursor is moved to beginning of line

![image](https://user-images.githubusercontent.com/15620434/121606223-fe4ee880-ca0a-11eb-933c-882ff3e82b4c.png)

**Comment by 333fred** [comment]
This isn't really something that OmniSharp can control, it's a Roslyn behavior (and matches that VS does here). If you would like to see a change to the formatter, you'll need to open an issue on dotnet/roslyn.
