### ISSUE TITLE
IntelliSense is not working on Mac for Unity Project

### ISSUE THREAD

**Issue by visualskyrim** [OmniSharp/omnisharp-vscode#461]
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

VS Code version:
```
1.2.1 (1.2.1)
```

C# Extension version:

1.1.6

## Steps to reproduce

- Open a Unity project with `.sln` and `.csproj` files.
- Click on a `.cs` file.
- write `this.` in a member function of a class.

## Expected  behavior

Intellisense should have worked.

## Actual behavior

No intellisense working out.
The fire icon at the right bottom of the VS code window shows running all the time.

Here is Omnisharp's log, if it would help:

```
[INFO] Starting OmniSharp at '/Users/user-name/work/ProjectName/ProjectName.sln'...
[INFO] Started OmniSharp from '/Users/user-name/.vscode/extensions/ms-vscode.csharp-1.1.6/.omnisharp/OmniSharp' with process id 11754...
OmniSharp: -s /Users/user-name/work/ProjectName/ProjectName.sln --hostPID 11743 dnx:enablePackageRestore=false --stdio
[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location '/Users/user-name/work/ProjectName' on host 11743.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /Users/user-name/work/ProjectName
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: True
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp.Startup] Configuration finished.
```

And the Unity version is 5.4.1

Let me know if more information is needed.
Thanks in advance!

**Comment by DustinCampbell** [comment]
Please note this information on the project readme:

>**Support for .csproj projects has been temporarily disabled on OS X and Linux.** This will impact anyone doing .csproj development on OS X or Linux (e.g. Unity, Xamarin, etc.). Rest assured that this will be restored in the near future. However, for now, you can use the [Legacy C# Support extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.omnisharp).

I'm currently in the process of producing a version of the C# Extension that attempts to bring back support for .csproj on OS X and Linux. If you'd be willing to test the extension once it's ready, I'd be grateful.

**Comment by DustinCampbell** [comment]
I've just added a new release that provides support for MSBuild projects on OS X and Linux [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.1.7). Could you install this new VSIX into VS Code and see if it works for you? Be sure to uninstall the Legacy C# Support extension if you have it installed.

**Comment by aukaost** [comment]
I am getting the following error trying to use 1.1.7 in combination with a Unity project:

> [ERROR:OmniSharp.Startup] The project system 'MSBuildProjectSystem' threw exception during initialization.
The type initializer for 'Crypto' threw an exception.
   at Interop.Crypto.EvpMd5()
   at Internal.Cryptography.HashProviderDispenser.CreateHashProvider(String hashAlgorithmId)
   at System.Security.Cryptography.MD5.Implementation..ctor()
   at OmniSharp.MSBuild.MSBuildProjectSystem.UnityTypeGuid(String projectName) in /Users/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp.MSBuild/MSBuildProjectSystem.cs:line 187
   at OmniSharp.MSBuild.MSBuildProjectSystem.Initalize(IConfiguration configuration) in /Users/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp.MSBuild/MSBuildProjectSystem.cs:line 68
   at OmniSharp.Startup.Configure(IApplicationBuilder app, IServiceProvider serviceProvider, IOmnisharpEnvironment env, ILoggerFactory loggerFactory, ISharedTextWriter writer, IOmnisharpAssemblyLoader loader, IOptions`1 optionsAccessor) in /Users/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp.Host/Startup.cs:line 183

**Comment by aukaost** [comment]
worked around it as per the hint on issue #410

**Comment by visualskyrim** [comment]
@DustinCampbell 
Thanks for the quick response!
The [v1.1.7](v1.1.7) works pretty well for me.

Only I got a warning when I was loading the project:
(Although I think that was probably an environment issue of mine)

```
[WARNING:OmniSharp#ProjectFileInfo] The reference assemblies for framework ".NETFramework,Version=v2.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend
```

Thanks!
