### ISSUE TITLE
[Feature Request] Customize the ContextMenu

### ISSUE THREAD

**Issue by m4ss1m0g** [OmniSharp/omnisharp-vscode#4624]
## Issue Description ##
I want to customize the context menu when over a constructor parameter particular, the `Create and assign field 'xxx'`.

![image](https://user-images.githubusercontent.com/4323707/122958975-43680880-d383-11eb-8449-15517ddd18ad.png)

## Actual Behavior ##
When clicked the extension create a code like this
`this.xxx = xxx`

## Preferred Behaviour ##
`_xxx = xxx`

## Notes
I'm looking at the source code but I cannot find the point.

## Environment information ##

**VSCode version**: 1.57.1
**C# Extension**: 1.23.12

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.816 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]
  3.1.410 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.204 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|arkham-theme|lucasmsa|1.13.0|
|auto-using|Fudge|0.7.15|
|azure-account|ms-vscode|0.9.8|
|azurecli|ms-vscode|0.5.0|
|code-settings-sync|Shan|3.4.3|
|color-highlight|naumovs|2.3.0|
|csharp|ms-dotnettools|1.23.12|
|csharp-to-typescript|adrianwilczynski|1.12.1|
|debugger-for-chrome|msjsdiag|4.12.12|
|debugger-for-edge|msjsdiag|1.0.15|
|docthis|joelday|0.7.1|
|dotnet-core-add|solidcube|0.1.2|
|electron|kuscamara|0.2.5|
|eslint-disable-snippets|drKnoxy|1.3.0|
|fluent-icons|miguelsolorio|0.0.12|
|git-graph|mhutchie|1.30.0|
|githistory|donjayamanne|0.6.16|
|github-vscode-theme|GitHub|4.1.1|
|gitlens|eamodio|11.5.1|
|halcyon-vscode|brittanychiang|0.2.20|
|markdown-all-in-one|yzhang|3.4.0|
|material-icon-theme|PKief|4.7.0|
|msbuild-project-tools|tintoy|0.3.15|
|npm-intellisense|christian-kohler|1.3.1|
|nugetpackagemanagergui|aliasadidev|1.1.6|
|numbered-bookmarks|alefragnani|8.1.0|
|output-colorizer|IBM|0.1.2|
|powershell|ms-vscode|2021.6.1|
|prettier-vscode|esbenp|8.0.0|
|quicktype|quicktype|12.0.46|
|rainbow-csv|mechatroner|1.8.1|
|remote-containers|ms-vscode-remote|0.183.0|
|remote-ssh|ms-vscode-remote|0.65.7|
|remote-ssh-edit|ms-vscode-remote|0.65.7|
|remote-ssh-explorer|ms-vscode-remote|0.56.0|
|remote-wsl|ms-vscode-remote|0.56.5|
|slack-theme|felipe-mendes|1.9.17|
|sqlops-debug|ms-mssql|1.3.0|
|test-adapter-converter|ms-vscode|0.0.10|
|theme-material-theme|jprestidge|1.0.1|
|todo-tree|Gruntfuggly|0.0.213|
|vetur|octref|0.34.1|
|vsc-community-material-theme|Equinusocio|1.4.2|
|vsc-material-theme|Equinusocio|33.1.2|
|vscode-azureresourcegroups|ms-azuretools|0.4.0|
|vscode-commons|redhat|0.0.6|
|vscode-docker|ms-azuretools|1.14.0|
|vscode-drawio|hediet|1.5.0|
|vscode-eslint|dbaeumer|2.1.23|
|vscode-import-cost|wix|2.15.0|
|vscode-jest|Orta|4.0.3|
|vscode-jest-runner|firsttris|0.4.44|
|vscode-markdownlint|DavidAnson|0.42.1|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-nupkg|eridem|1.0.1|
|vscode-pylance|ms-python|2021.6.2|
|vscode-remote-extensionpack|ms-vscode-remote|0.21.0|
|vscode-taskexplorer|spmeesseman|2.3.0|
|vscode-test-explorer|hbenl|2.20.4|
|vscode-theme-onedark|akamud|2.2.3|
|vscode-versionlens|pflannery|1.0.9|
|vscode-yaml|redhat|0.20.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.14|
|vtpw|snovakovic|0.1.2|
|Vue2|ducksoupdev|0.1.3|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by JoeRobich** [comment]
The C# extension supports codestyle configuration using an .editorconfig file. See https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options for more details on what options are available. These codestyle options will be used when applying code fixes.

In particular it seems that you would want to configure the following settings at a minimum:
this and Me preferences - https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0003-ide0009
Naming rules - https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules

```ini
# EditorConfig is awesome:http://EditorConfig.org

# top-most EditorConfig file
root = true

# Don't use tabs for indentation.
[*]
indent_style = space

# Code files
[*.{cs,csx,vb,vbx}]
indent_size = 4
insert_final_newline = true
charset = utf-8-bom

# Dotnet code style settings:
[*.{cs,vb}]
# Avoid "this." and "Me." if not necessary
dotnet_style_qualification_for_field = false:error
dotnet_style_qualification_for_property = false:error
dotnet_style_qualification_for_method = false:error
dotnet_style_qualification_for_event = false:error

# Instance fields are camelCase and start with _
dotnet_naming_rule.instance_fields_should_be_camel_case.severity = suggestion
dotnet_naming_rule.instance_fields_should_be_camel_case.symbols = instance_fields
dotnet_naming_rule.instance_fields_should_be_camel_case.style = instance_field_style

dotnet_naming_symbols.instance_fields.applicable_kinds = field

dotnet_naming_style.instance_field_style.capitalization = camel_case
dotnet_naming_style.instance_field_style.required_prefix = _
```

**Comment by m4ss1m0g** [comment]
Its seem that on VSCode only this properties are available:

indent_style
indent_size
tab_width
end_of_line (on save)
insert_final_newline (on save)
trim_trailing_whitespace (on save)

[EditorConfig for VS Code](https://github.com/editorconfig/editorconfig-vscode)

**Comment by JoeRobich** [comment]
@m4ss1m0g C# reads codestyle settings from the .editorconfig separately from that extension. We do not currently provide any intellisense when editing the file. Please refer to the documentation to ensure spelling of settings is correct.

**Comment by m4ss1m0g** [comment]
Yes, sorry, I found this useful [article](https://www.strathweb.com/2019/07/editorconfig-support-in-omnisharp-and-c-extension-vs-code/) were explained how to do its work.

Thanks.
