### ISSUE TITLE
Update to 1.58 and take advantage of the new completion labels

### ISSUE THREAD

**Issue by 333fred** [OmniSharp/omnisharp-vscode#4640]
https://code.visualstudio.com/updates/v1_58#_detailed-completion-item-labels

Should let us display more info for types of things and the namespace import completions will bring in. Related to https://github.com/microsoft/vscode/issues/39441.

**Comment by 333fred** [comment]
@david-driscoll these are also in the 3.17 draft LSP spec, so we could do similar for LSP in general when clients support it.

**Comment by JoeRobich** [comment]
It is neat in the TypeScript completion that you can see the member declaration inlined.
![image](https://user-images.githubusercontent.com/611219/125006161-554bdb80-e012-11eb-9d6b-c2c0d281c503.png)

**Comment by 333fred** [comment]
> It is neat in the TypeScript completion that you can see the member declaration inlined.

For this, btw, we'll need new Roslyn APIs. Currently, that's a section in the documentation that's retrieved by the resolve step, and I don't want to try and resolve all documentation for every completion item on completion list pop.
