### ISSUE TITLE
IntelliSense stopped working on the latest build v1.23.13 on Linux X64

### ISSUE THREAD

**Issue by vyshnavks8** [OmniSharp/omnisharp-vscode#4655]
## Problem
Everything was running perfect on c# extension version 1.23.12 but after updating to 1.23.13 IntelliSense stopped working.
I tried uninstall and reinstalling c# extension. Downgrading and again upgrading but nothing solves the issue. 
No error are shown and solution also loads fine, only problem affected  is to the Intellisense.
Currently i am using the previous version 1.23.12 which is working fine, Please look into this issue .

## Environment data

Platform: linux, x86_64, name=pop, version=21.04
Mono Version : Mono JIT compiler version 6.12.0.122
Dotnet SDK Version : 5.0.302
Dontnet runtime Version : 5.0.8

VS Code version: 1.57.1
C# Extension version: 1.23.13

## VScode about data
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.11.0-7620-generic

**Comment by JoeRobich** [comment]
@vyshnavks8 Can you please share the OmniSharp Log from the Output pane for one of the projects you are having issues with?

**Comment by vyshnavks8** [comment]
## NOTE
Even with warning of "Mono installed which contains a MSBuild lower than 16.8.0" the version 1.23.12 works fine.
I just added both OmniSharp Log for v1.23.13 and v1.23.12 for comparison.

## OmniSharp Log for v1.23.13

Starting OmniSharp server at 15/7/2021, 12:25:44 am
    Target: /home/vks/Godot Project/Multiplayer/Multiplayer.sln

OmniSharp server started with Mono 6.12.0.
    Path: /home/vks/.vscode/extensions/ms-dotnettools.csharp-1.23.13/.omnisharp/1.37.12/omnisharp/OmniSharp.exe
    PID: 15252

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on pop 21.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.6.0 - "/usr/lib/mono/msbuild/Current/bin"
            2: StandAlone 17.0.0 - "/home/vks/.vscode/extensions/ms-dotnettools.csharp-1.23.13/.omnisharp/1.37.12/omnisharp/.msbuild/Current/Bin"
[warn]: OmniSharp.CompositionHostBuilder
        It looks like you have Mono installed which contains a MSBuild lower than 16.8.0 which is the minimum supported by the configured .NET Core Sdk.
 Try updating Mono to the latest stable or preview version to enable better .NET Core Sdk support.
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.6.0 - "/usr/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /home/vks/.vscode/extensions/ms-dotnettools.csharp-1.23.13/.omnisharp/1.37.12/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/vks/Godot Project/Multiplayer'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/vks/Godot Project/Multiplayer/Multiplayer.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/vks/Godot Project/Multiplayer/Multiplayer.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/vks/Godot Project/Multiplayer'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/vks/Godot Project/Multiplayer' on host 15135.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/vks/Godot Project/Multiplayer/Multiplayer.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/vks/Godot Project/Multiplayer/Multiplayer.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/vks/Godot Project/Multiplayer/Multiplayer.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Multiplayer
Received response for /quickinfo but could not find request.

## OmniSharp Log for v1.23.12

Starting OmniSharp server at 15/7/2021, 12:32:40 am
    Target: /home/vks/Godot Project/Multiplayer/Multiplayer.sln

OmniSharp server started with Mono 6.12.0.
    Path: /home/vks/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/omnisharp/OmniSharp.exe
    PID: 15815

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on pop 21.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.6.0 - "/usr/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.11.0 - "/home/vks/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/omnisharp/.msbuild/Current/Bin"
[warn]: OmniSharp.CompositionHostBuilder
        It looks like you have Mono installed which contains a MSBuild lower than 16.8.0 which is the minimum supported by the configured .NET Core Sdk.
 Try updating Mono to the latest stable or preview version to enable better .NET Core Sdk support.
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.6.0 - "/usr/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /home/vks/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/vks/Godot Project/Multiplayer'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/vks/Godot Project/Multiplayer/Multiplayer.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/vks/Godot Project/Multiplayer/Multiplayer.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/vks/Godot Project/Multiplayer'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/vks/Godot Project/Multiplayer' on host 15705.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/vks/Godot Project/Multiplayer/Multiplayer.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/vks/Godot Project/Multiplayer/Multiplayer.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/vks/Godot Project/Multiplayer/Multiplayer.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Multiplayer

**Comment by JoeRobich** [comment]
@vyshnavks8 Can you share this project with us or create a minimal repo that you can share?

**Comment by vyshnavks8** [comment]
Its does not matter which project I open , a newly created project with Godot Engine also does not  work with  IntelliSense having  the latest build v1.23.13. 
Maybe this only happen to c# extension for Linux build. 
Maybe the bug is inside the packages that is installed after upgrading to latest build.

Here is the solution and cs project file. 
[Multiplayer.zip](https://github.com/OmniSharp/omnisharp-vscode/files/6820983/Multiplayer.zip)

**Comment by dwmoeller1** [comment]
Am experiencing the same problem. 
OmniSharp logs are identical except for Omnisharp version numbers and host port. 
Was able to replicate this using a basic console app targeting netcore3.1 as well as one targetting netstandard5.0

Note that standard Intellisense works but contextual help for C# objects is basically non existent.

**Comment by adam-becker** [comment]
Same issue, running in a docker container based on the `mcr.microsoft.com/dotnet/core/sdk:3.1` image. Host OS is Arch Linux.

**Comment by valters-tomsons** [comment]
I have the same issue, [here is my omnisharp log,](https://gist.github.com/valters-tomsons/f4abdb4cdfd78abf6a50aa97241f554c) which seems to contain quite a lot of exceptions.

This is on Arch Linux, but I noticed the same behavior on Ubuntu LTS. [Here is the code repository](https://github.com/valters-tomsons/spectabis-next) which the logs reference.

**Comment by filipw** [comment]
please make sure to update VS Code to latest version - the new extension version uses a new completion API that is not available in VS Code older than 1.58

**Comment by cateyes99** [comment]
See this #4663

**Comment by vyshnavks8** [comment]
Updating VS Code to 1.58 solved the issue. Closing this thread.
