### ISSUE TITLE
VS 2019 16.10 < 16.3 ?

### ISSUE THREAD

**Issue by spazmodius** [OmniSharp/omnisharp-vscode#4686]
I have a C# project that imports `Microsoft.WebApplication.targets`, a rather old type of project.  

I believe this would work in vscode if Omnisharp pinned to my best Msbuild from VS 2019 Community, but it instead settles on it's own stand-alone Msbuild. 

In particular, it finds `Visual Studio Community 2019 16.10.31515.178`, but says `It looks like you have Visual Studio lower than VS 2019 16.3 installed` !.

```
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 4 MSBuild instance(s)
            1: DEVCONSOLE 16.10.4 16.10.2 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: Visual Studio Community 2017 15.9.28307.1585 15.9.21 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            3: Visual Studio Community 2019 16.10.31515.178 16.10.2 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            4: StandAlone 17.0.0 - "C:\Portable\VSCode\data\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.14\.msbuild\Current\Bin"
[warn]: OmniSharp.CompositionHostBuilder
        It looks like you have Visual Studio lower than VS 2019 16.3 installed.
 Try updating Visual Studio to the most recent release to enable better MSBuild support.
[warn]: OmniSharp.CompositionHostBuilder
        It looks like you have Visual Studio 2019 installed without .NET Core SDK support which is required by OmniSharp.
 Try updating Visual Studio 2019 installation with .NET Core SDK to enable better MSBuild support.
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Portable\VSCode\data\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.14\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 17.0.0 - "C:\Portable\VSCode\data\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.14\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Portable\VSCode\data\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.14\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = C:\Portable\VSCode\data\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.14\.msbuild
            MSBuildToolsPath = C:\Portable\VSCode\data\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.14\.msbuild\Current\Bin
```

### OmniSharp log ###
<details>Starting OmniSharp server at 7/28/2021, 5:06:24 PM
    Target: c:\spazmodius\xyz\Core\xyzEnterprise.sln

OmniSharp server started.
    Path: C:\Portable\VSCode\data\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.14\OmniSharp.exe
    PID: 7408

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 4 MSBuild instance(s)
            1: DEVCONSOLE 16.10.4 16.10.2 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: Visual Studio Community 2017 15.9.28307.1585 15.9.21 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            3: Visual Studio Community 2019 16.10.31515.178 16.10.2 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            4: StandAlone 17.0.0 - "C:\Portable\VSCode\data\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.14\.msbuild\Current\Bin"
[warn]: OmniSharp.CompositionHostBuilder
        It looks like you have Visual Studio lower than VS 2019 16.3 installed.
 Try updating Visual Studio to the most recent release to enable better MSBuild support.
[warn]: OmniSharp.CompositionHostBuilder
        It looks like you have Visual Studio 2019 installed without .NET Core SDK support which is required by OmniSharp.
 Try updating Visual Studio 2019 installation with .NET Core SDK to enable better MSBuild support.
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Portable\VSCode\data\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.14\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 17.0.0 - "C:\Portable\VSCode\data\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.14\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Portable\VSCode\data\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.14\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = C:\Portable\VSCode\data\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.14\.msbuild
            MSBuildToolsPath = C:\Portable\VSCode\data\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.14\.msbuild\Current\Bin
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\spazmodius\xyz\Core'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\spazmodius\xyz\Core\xyzEnterprise.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\spazmodius\xyz\Core\Setup\Setup.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\spazmodius\xyz\Core\xyz\xyz.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\spazmodius\xyz\Core\xyz.Tests\xyz.Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\spazmodius\xyz\Core\xyz.Data.Sql2k\xyz.Data.Sql2k.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\spazmodius\xyz\Core\xyz.Domain\xyz.Domain.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\spazmodius\xyz\Core\xyzUtility\xyzUtility.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\spazmodius\xyz\Core\xyz.Setup\xyz.Setup.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\spazmodius\xyz\Core\xyz.Web\xyz.Web.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\spazmodius\xyz\Core\xyz.Model\xyz.Model.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\spazmodius\xyz\Core\xyz.Specs\xyz.Specs.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\spazmodius\xyz\Core\xyz.NUnit\xyz.NUnit.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\spazmodius\xyz\Core\xyz.Module.ProjectRoles\xyz.Module.ProjectRoles.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\spazmodius\xyz\Core\xyz.Contract\xyz.Contract.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\spazmodius\xyz\Core\xyz.Module.ProjectRoles.Tests\xyz.Module.ProjectRoles.Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\spazmodius\xyz\Core\xyz.Module.SlackIntegration\xyz.Module.SlackIntegration.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\spazmodius\xyz\Core\xyz.Module.SlackIntegration.Tests\xyz.Module.SlackIntegration.Tests.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\spazmodius\xyz\Core'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\spazmodius\xyz\Core' on host 9532.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\spazmodius\xyz\Core\Setup\Setup.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\spazmodius\xyz\Core\Setup\Setup.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\spazmodius\xyz\Core\Setup\Setup.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\spazmodius\xyz\Core\xyz\xyz.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\spazmodius\xyz\Core\xyz\xyz.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\spazmodius\xyz\Core\xyz\xyz.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\spazmodius\xyz\Core\xyz.Tests\xyz.Tests.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The value "" of the "Project" attribute in element <Import> is invalid.
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\NUnit.3.12.0\build\NUnit.props.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\spazmodius\xyz\Core\xyz.Tests\xyz.Tests.csproj'.
c:\spazmodius\xyz\Core\xyz.Tests\xyz.Tests.csproj
c:\spazmodius\xyz\Core\xyz.StructuredQuery\xyz.StructuredQuery.fsproj(52,3): Error: The value "" of the "Project" attribute in element <Import> is invalid.
c:\spazmodius\xyz\Core\xyz.Tests\xyz.Tests.csproj(1403,5): Error: This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\NUnit.3.12.0\build\NUnit.props.

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\spazmodius\xyz\Core\xyz.Data.Sql2k\xyz.Data.Sql2k.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\spazmodius\xyz\Core\xyz.Data.Sql2k\xyz.Data.Sql2k.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\spazmodius\xyz\Core\xyz.Data.Sql2k\xyz.Data.Sql2k.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\spazmodius\xyz\Core\xyz.Domain\xyz.Domain.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\spazmodius\xyz\Core\xyz.Domain\xyz.Domain.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\spazmodius\xyz\Core\xyz.Domain\xyz.Domain.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\spazmodius\xyz\Core\xyzUtility\xyzUtility.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\spazmodius\xyz\Core\xyzUtility\xyzUtility.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\spazmodius\xyz\Core\xyzUtility\xyzUtility.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\spazmodius\xyz\Core\xyz.Setup\xyz.Setup.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\spazmodius\xyz\Core\xyz.Setup\xyz.Setup.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\spazmodius\xyz\Core\xyz.Setup\xyz.Setup.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\spazmodius\xyz\Core\xyz.Web\xyz.Web.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The value "" of the "Project" attribute in element <Import> is invalid.
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\MSBuild.Microsoft.VisualStudio.Web.targets.14.0.0.3\build\MSBuild.Microsoft.VisualStudio.Web.targets.props.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\spazmodius\xyz\Core\xyz.Web\xyz.Web.csproj'.
c:\spazmodius\xyz\Core\xyz.Web\xyz.Web.csproj
c:\spazmodius\xyz\Core\xyz.StructuredQuery\xyz.StructuredQuery.fsproj(52,3): Error: The value "" of the "Project" attribute in element <Import> is invalid.
c:\spazmodius\xyz\Core\xyz.Web\xyz.Web.csproj(5027,5): Error: This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\MSBuild.Microsoft.VisualStudio.Web.targets.14.0.0.3\build\MSBuild.Microsoft.VisualStudio.Web.targets.props.

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\spazmodius\xyz\Core\xyz.Model\xyz.Model.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\spazmodius\xyz\Core\xyz.Model\xyz.Model.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\spazmodius\xyz\Core\xyz.Model\xyz.Model.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\spazmodius\xyz\Core\xyz.Specs\xyz.Specs.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\NUnit.3.12.0\build\NUnit.props.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\spazmodius\xyz\Core\xyz.Specs\xyz.Specs.csproj'.
c:\spazmodius\xyz\Core\xyz.Specs\xyz.Specs.csproj
c:\spazmodius\xyz\Core\xyz.Specs\xyz.Specs.csproj(449,5): Error: This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\NUnit.3.12.0\build\NUnit.props.

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\spazmodius\xyz\Core\xyz.NUnit\xyz.NUnit.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\NUnit.3.12.0\build\NUnit.props.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\spazmodius\xyz\Core\xyz.NUnit\xyz.NUnit.csproj'.
c:\spazmodius\xyz\Core\xyz.NUnit\xyz.NUnit.csproj
c:\spazmodius\xyz\Core\xyz.NUnit\xyz.NUnit.csproj(162,5): Error: This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\NUnit.3.12.0\build\NUnit.props.

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\spazmodius\xyz\Core\xyz.Module.ProjectRoles\xyz.Module.ProjectRoles.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\spazmodius\xyz\Core\xyz.Module.ProjectRoles\xyz.Module.ProjectRoles.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\spazmodius\xyz\Core\xyz.Module.ProjectRoles\xyz.Module.ProjectRoles.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\spazmodius\xyz\Core\xyz.Contract\xyz.Contract.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\spazmodius\xyz\Core\xyz.Contract\xyz.Contract.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\spazmodius\xyz\Core\xyz.Contract\xyz.Contract.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\spazmodius\xyz\Core\xyz.Module.ProjectRoles.Tests\xyz.Module.ProjectRoles.Tests.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\NUnit.3.12.0\build\NUnit.props.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\spazmodius\xyz\Core\xyz.Module.ProjectRoles.Tests\xyz.Module.ProjectRoles.Tests.csproj'.
c:\spazmodius\xyz\Core\xyz.Module.ProjectRoles.Tests\xyz.Module.ProjectRoles.Tests.csproj
c:\spazmodius\xyz\Core\xyz.Module.ProjectRoles.Tests\xyz.Module.ProjectRoles.Tests.csproj(102,5): Error: This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\NUnit.3.12.0\build\NUnit.props.

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\spazmodius\xyz\Core\xyz.Module.SlackIntegration\xyz.Module.SlackIntegration.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\spazmodius\xyz\Core\xyz.Module.SlackIntegration\xyz.Module.SlackIntegration.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\spazmodius\xyz\Core\xyz.Module.SlackIntegration\xyz.Module.SlackIntegration.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\spazmodius\xyz\Core\xyz.Module.SlackIntegration.Tests\xyz.Module.SlackIntegration.Tests.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\NUnit.3.12.0\build\NUnit.props.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\spazmodius\xyz\Core\xyz.Module.SlackIntegration.Tests\xyz.Module.SlackIntegration.Tests.csproj'.
c:\spazmodius\xyz\Core\xyz.Module.SlackIntegration.Tests\xyz.Module.SlackIntegration.Tests.csproj
c:\spazmodius\xyz\Core\xyz.Module.SlackIntegration.Tests\xyz.Module.SlackIntegration.Tests.csproj(111,5): Error: This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\NUnit.3.12.0\build\NUnit.props.

[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Setup
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: xyz
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\spazmodius\xyz\Core\xyz.Tests\xyz.Tests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: xyz.Data.Sql2k
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: xyz.Domain
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: xyzUtility
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: xyz.Setup
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\spazmodius\xyz\Core\xyz.Web\xyz.Web.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: xyz.Model
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\spazmodius\xyz\Core\xyz.Specs\xyz.Specs.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\spazmodius\xyz\Core\xyz.NUnit\xyz.NUnit.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: xyz.Module.ProjectRoles
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: xyz.Contract
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\spazmodius\xyz\Core\xyz.Module.ProjectRoles.Tests\xyz.Module.ProjectRoles.Tests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: xyz.Module.SlackIntegration
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\spazmodius\xyz\Core\xyz.Module.SlackIntegration.Tests\xyz.Module.SlackIntegration.Tests.csproj
</details>

### C# log ###
<details>
Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (39180 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'

Downloading package '.NET Core Debugger (Windows / x64)' (45302 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (Windows / x64)'

Downloading package 'Razor Language Server (Windows / x64)' (62313 KB).................... Done!
Installing package 'Razor Language Server (Windows / x64)'

Finished
</details>

## Environment information ##

**VSCode version**: 1.58.2
**C# Extension**: 1.23.14

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.302\

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|basic-dark-color-theme|spazmodius|0.0.4|
|csharp|ms-dotnettools|1.23.14|
|TabOut|albert|0.2.0|
|vscode-eslint|dbaeumer|2.1.23|
|vscode-hexdump|slevesque|1.8.1|
|vscode-navigate-edit-history|codeandstuff|1.5.2|
|vscode-toggle-quotes|BriteSnow|0.3.4|;

</details>

**Comment by filipw** [comment]
The error message is a bit misleading. The actual problem is in the log too though:

>  It looks like you have Visual Studio 2019 installed without .NET Core SDK support which is required by OmniSharp.
> Try updating Visual Studio 2019 installation with .NET Core SDK to enable better MSBuild support.

It doesn'tt matter that you have VS 16.10 there if it doesn't have .NET Core SDK installed as part of the installation bundle. Try rerunning the setup and ensure that .NET Core development toolset is included.

**Comment by spazmodius** [comment]
Thanks for the help.  

I had puzzled over how to address that message too, but there is no option in my VS installer for ".NET Core SDK".  I just now tried adding ".NET SDK", and it seems to have worked.
