### ISSUE TITLE
C# extension uses x86 OmniSharp on arm64

### ISSUE THREAD

**Issue by Alovchin91** [OmniSharp/omnisharp-vscode#4687]
## Environment information ##

**VSCode version**: 1.58.2
**C# Extension**: 1.23.14

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-arm64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.302\

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  5.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

## OmniSharp log

```
Installing C# dependencies...
Platform: win32, arm64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x86)' (39180 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Windows (.NET 4.6 / x86)'
```

## Steps to reproduce

Install C# extension in arm64 Visual Studio Code on Windows arm64.

## Expected  behavior

C# extension downloads [OmniSharp package for arm64](https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.37.14/omnisharp-win-arm64.zip).

## Actual behavior

C# extension downloads OmniSharp package for x86.

**Comment by gregg-miskelly** [comment]
This is expected.

**Comment by Alovchin91** [comment]
What the arm64 version of OmniSharp is for then? 🤔 Are there any plans to start using it?

**Comment by gregg-miskelly** [comment]
I don't work on the language service side of the house, but what I can tell you is that an win10-arm64 version of OmniSharp would run on .NET Core, but this extension always runs on .NET Framework or Mono. So on a Windows ARM device it currently must run as an x86 process.
