### ISSUE TITLE
[Question] Project selection feature

### ISSUE THREAD

**Issue by lonix1** [OmniSharp/omnisharp-vscode#4688]
## Environment data
C# Extension version: 1.23.14

## Question
I just installed the latest version. There's a new feature I can't find documented in the [release notes](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.14).

Now when vscode opens it shows a dropdown asking to "select a project". It also shows a "project selector" button in the status bar.

What is this new feature?

**Comment by JoeRobich** [comment]
Thanks for asking. Sorry will update the changelog to include this PR https://github.com/OmniSharp/omnisharp-vscode/pull/4644.

There has always been a project selector available from the VS Code status bar or through the "OmniSharp: Select Project" command. When you are working from a folder with multiple projects you can now select a particular project to work against with the selector.

**Comment by lonix1** [comment]
It forces me to select a project, then there's a little tick next to it, and omnisharp doesn't seem to load anything else.

What if I want the existing behavior - to load everything... how do I do that?

**Comment by lonix1** [comment]
I think it may be related to https://github.com/OmniSharp/omnisharp-vscode/issues/4691

This is a major break, because I need to keep switching between projects in that little dropdown.

Unless there's a config setting I need to use or something?
