### ISSUE TITLE
.editorconfig is not working or respected

### ISSUE THREAD

**Issue by mifriis** [OmniSharp/omnisharp-vscode#4693]
## Issue Description ##
We are attempting to use .editorconfig in vscode, but are not having success with it. I have attempted to boil the issue down to the core, by implementing a sample project here: https://github.com/mifriis/editor-config

Instead of our custom editorconfig, in the sample i am using the simple one from this blogpost: https://www.strathweb.com/2019/07/editorconfig-support-in-omnisharp-and-c-extension-vs-code/

```
[*.cs]
dotnet_style_qualification_for_field = false
dotnet_naming_style.instance_field_style.capitalization = camel_case
dotnet_naming_style.instance_field_style.required_prefix = _
```

But without success. It seems the analyzers are running, but not based on the editorconfig file. When using our production editorconfig we are seeing it being respected in VS, but not VSCode. We have not installed any plugins to make it work.

## Steps to Reproduce ##

open `Class1.cs` and `Ctrl + .` on `myField`

You should see the option for `Create and assign field for myField` 

## Expected Behavior ##

```c#
 public class Class1
    {
        private readonly string _myfield;

        public Class1(string myfield) {
            _myfield = myfield;
        }
    }
```

## Actual Behavior ##

```c#
    public class Class1
    {
        private readonly string myfield;

        public Class1(string myfield) {
            this.myfield = myfield;
        }
    }
```

### OmniSharp log ###
<details>[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: Create and assign field 'myfield'</details>

### C# log ###
<details>None, the log is empty</details>

## Environment information ##

**VSCode version**: 1.57.0
**C# Extension**: 1.23.13

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.302\

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  2.1.617 [C:\Program Files\dotnet\sdk]
  3.1.411 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|code-coverage|markis|1.3.3|
|code-spell-checker|streetsidesoftware|1.10.2|
|csharp|ms-dotnettools|1.23.13|
|jupyter|ms-toolsai|2021.6.999662501|
|markdown-all-in-one|yzhang|3.4.0|
|python|ms-python|2021.7.1060902895|
|remote-wsl|ms-vscode-remote|0.56.5|
|vscode-drawio|hediet|1.6.1|
|vscode-github|KnisterPeter|0.30.6|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-pylance|ms-python|2021.7.7|
|vsliveshare|ms-vsliveshare|1.0.4631|;

</details>

**Comment by JoeRobich** [comment]
@mifriis Naming style configuration can be tricky to configure ([See the docs](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules)). Below is an excerpt from [Roslyn's .editorconfig](https://github.com/dotnet/roslyn/blob/main/.editorconfig#L110-L118).

```ini
# Instance fields are camelCase and start with _
dotnet_naming_rule.instance_fields_should_be_camel_case.severity = suggestion
dotnet_naming_rule.instance_fields_should_be_camel_case.symbols = instance_fields
dotnet_naming_rule.instance_fields_should_be_camel_case.style = instance_field_style

dotnet_naming_symbols.instance_fields.applicable_kinds = field

dotnet_naming_style.instance_field_style.capitalization = camel_case
dotnet_naming_style.instance_field_style.required_prefix = _
```

First, Roslyn declares a naming rule `instance_fields_should_be_camel_case` which suggests that `instance_fields` symbols have the `instance_field_style` naming style applied. Next, Roslyn declares a naming symbol configuration `instance_fields` which applies only to fields. Finally, Roslyn declares a naming style `instance_field_style` which is camel case and requires a `_` prefix. Each part is necessary to have a working naming rule.

Also, let me recommend that you begin your .editorconfig with `root = true`. This tells editors that it can stop walking up the filesystem looking for applicable configurations and will ensure that only the settings defined in the file will be applied to your code.

**Comment by mifriis** [comment]
Hi @JoeRobich 
Using Roslyn's editorconfig just kicks in and works. I wonder if there's a, bad,  setting in our .editorconfig that Visual Studio can interpret or ignore, while VSCode doesn't. I don't suppose there's a more verbose log or way to see more in depth what is going on?

**Comment by JoeRobich** [comment]
@mifriis I believe things are working as expected here. A naming rule requires information about what the style is and which symbols it applies to. I believe the sample from the blog post may have been incomplete.
