### ISSUE TITLE
No IntelliSense in C# file that is not included in a project

### ISSUE THREAD

**Issue by leocrespo** [OmniSharp/omnisharp-vscode#47]
Seriously? What kind of editor is this? 

If I need to follow certain instructions in order to get basic Intellisense on C# just to edit a single .cs file, then this needs to be really freaking obvious. 

![screen capture on 2016-02-28 at 13-09-47](https://cloud.githubusercontent.com/assets/2193314/13377654/233e1bd4-dd99-11e5-8c39-1d8b1321f1ff.gif)

**Comment by DustinCampbell** [comment]
This is something we'll definitely be working on. Today, you can't get IntelliSense for a file without it belonging to a project file, which is not a great experience.

**Comment by leocrespo** [comment]
And I can't create a project too, because there is no "New Project" option on the menu, which is also not a great experience either.

**Comment by DustinCampbell** [comment]
@leocrespo -- bear in mind that this is an editor and not an IDE. "New Project" isn't something that you find in many other editors (like, say Sublime Text).

**Comment by leocrespo** [comment]
So there's no Intellisense because the file doesn't belong to a project, and yet I can't create a project. Sure, makes sense.

**Comment by DustinCampbell** [comment]
As I said, we'll be working on IntelliSense for project-less scenarios. At the moment, the most common way to create a C# project for VS Code scenarios is to use a scaffolding tool like yeoman or to create a project.json manually. Eventually, you'll be able to use the .NET command-line tools to create a project with "dotnet new".

**Comment by dhnnjy** [comment]
@DustinCampbell  'Dotnet new' creates simple Console app template. vscode can't reate a project. Yeoman is probably outdated, it doesn't work with latest CLI. Is there any way of creating web api or class library?

**Comment by gregg-miskelly** [comment]
Sorry if this is obvious, but the problem is that there is a major shift in how ASP.NET Core works, and it hasn't been fully released. I think your best bet is https://github.com/aspnet/cli-samples. If you have trouble, you may want to follow up with @sayedihashimi, and I believe he owns the yoman generator.

**Comment by sayedihashimi** [comment]
`yo aspnet` is typically updated a few days before the release. We don't have a good mechanism to get pre-release templates out today. The main issue on my side here is that we have to author templates twice. Once for VS and once for yo aspnet. The Microsoft team authors templates in [aspnet/templates](http://github.com/aspnet/templates) initially for VS, and then we post the final result to get added in `yo aspnet`. I'm working to define a new approach to templates where we can have one source of truth for templates which then get added to both VS and `yo aspnet`. Once I make good progress there then we will have a better story for pre-release templates. That will likely take me at least a few months as I'm doing all the work on the side at nights.

**Comment by filipw** [comment]
this looks like the same as this https://github.com/OmniSharp/omnisharp-roslyn/issues/207

I would like to mention that you can get project-less intellisense in CSX files already in omnisharp

**Comment by landaire** [comment]
This is an old issue but what needs to be done to accomplish this? At my job I review and trace code more than I write it. Usually I'll clone multiple repos and go through code, tracing things by hovering over a symbol and going to definition.

For example, I cloned https://github.com/aspnet/mvc. In Sublime with no additional setup I can just hover over a symbol and see where it's defined:

<img width="1392" alt="screen shot 2017-09-13 at 19 52 13" src="https://user-images.githubusercontent.com/1313522/30410164-53ce62b8-98be-11e7-930a-41b3a15c2974.png">

In VS Code the story is different:

![screen shot 2017-09-13 at 19 52 20](https://user-images.githubusercontent.com/1313522/30410215-976f16ac-98be-11e7-8fdd-46d2fabf61e1.png)

What would need to be done in order to match Sublime's out-of-box experience with projects like this?

**Comment by DustinCampbell** [comment]
@landaire: This issue is different than what you've reported here. This issue is about opening just a single file with no project file. However, in your scenario (cloning MVC), you certainly have a project file.

**Comment by landaire** [comment]
Hmmm. True. I was under the impression I was using a different C# plugin that was not backed by Omnisharp but that's the plugin I'm using. Is there a separate issue already that you're aware of for what I'm referring to?

**Comment by DustinCampbell** [comment]
Without more information, it's hard to determine what's going on and whether there's an existing issue that matches what you're seeing. Have you tried clicking the OmniSharp icon at the bottom right of the status bar and picking a particular solution or project to launch OmniSharp on? Also, what does the OmniSharp Log display? (You can see this by selecting View->Output and then picking "OmniSharp Log" from the dropdown in the top-right of the Output pane).

**Comment by Davilink** [comment]
Will a good use when you want to create small script to be use with dotnet script (https://github.com/filipw/dotnet-script). Otherwise i have to create a console application just to test something out.

**Comment by hifall** [comment]
So this still is the case, that in order to use OmniSharp's services, one needs to create a full project, instead of using a single file?

**Comment by mzhukovs** [comment]
Nice - when will v1.16 be released with this?

**Comment by akshita31** [comment]
The latest version of the c# extension which includes intellisense support for standalone c# files is out. Please do give it a try.
