### ISSUE TITLE
There is no notifications pop up when open a project. 

### ISSUE THREAD

**Issue by haiyanliu2** [OmniSharp/omnisharp-vscode#4700]
## Environment data
`dotnet --info` output:
.NET SDK (reflecting any global.json):
Version: 6.0.100-rc.1.21409.11
Commit: 170ccc4ceb

Runtime Environment:
OS Name: Mac OS X
OS Version: 10.15
OS Platform: Darwin
RID: osx.10.15-x64
Base Path: /usr/local/share/dotnet/sdk/6.0.100-rc.1.21409.11/

Host (useful for support):
Version: 6.0.0-rc.1.21406.5
Commit: 58efa4b797

.NET SDKs installed:
6.0.100-rc.1.21409.11 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 6.0.0-rc.1.21409.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.0-rc.1.21406.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
https://aka.ms/dotnet-download
VS Code version:1.59.0
C# Extension version:1.23.15-beta1

## Steps to reproduce
create a console then open it
## Expected  behavior
Notifications can pop up properly.
![Screen Shot 2021-08-10 at 3 24 58 PM](https://user-images.githubusercontent.com/87641893/128842009-27337145-d27d-46ec-b745-bf219c1eaa0e.png)

## Actual behavior
There is no notifications pop up, the project fails to load as expected.
![Screen Shot 2021-08-10 at 4 46 05 PM](https://user-images.githubusercontent.com/87641893/128842025-1c19326d-6b48-4568-b025-ab2f3fcb50b7.png)

Note:
With C# extension 1.23.14 installed,the project can be opened successfully.

**Comment by JoeRobich** [comment]
@haiyanliu2 You will need to select either the folder `cs2` in order to load all projects beneath the folder or select specifically the `cs2.csproj` from the project selector.

**Comment by haiyanliu2** [comment]
@JoeRobich Thanks, it can work fine now.

**Comment by DarqueWarrior** [comment]
Is there a way to disable this behavior? When I open a folder with csproj files I don't want to be forced to select one. I just press Esc on my keyboard anyway.

**Comment by JoeRobich** [comment]
@DarqueWarrior I opened https://github.com/OmniSharp/omnisharp-vscode/pull/4780 to restore the previous behavior.
