### ISSUE TITLE
Nullable arrays lose highlight.

### ISSUE THREAD

**Issue by jeffswt** [OmniSharp/omnisharp-vscode#4701]
## Issue Description ##
Nullable arrays loses highlight (though they can be rightfully compiled).

## Steps to Reproduce ##
```cs
namespace MyNS {
    public class MyClass {
        public string? aString { get; set; }
        public int? anInt { get; set; }
        public string[]? nullableStringArray { get; set; }
    }
}
```

## Expected Behavior ##
The line should highlight as normal.

## Actual Behavior ##
But it didn't.
![image](https://user-images.githubusercontent.com/18145331/129006861-8a37f6ce-eb26-44ce-9963-a349768d73cd.png)

### OmniSharp log ###
N/A

### C# log ###
N/A

## Environment information ##

**VSCode version**: 1.58.2
**C# Extension**: 1.23.14

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.303
 Commit:    6409b42649

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.303\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  3.1.412 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|city-lights-icon-vsc|Yummygum|1.1.3|
|city-lights-theme|yummygum|1.1.8|
|cpptools|ms-vscode|1.5.1|
|csharp|ms-dotnettools|1.23.14|
|hexeditor|ms-vscode|1.8.2|
|java|redhat|0.80.0|
|jupyter|ms-toolsai|2021.8.1054968649|
|python|ms-python|2021.8.1105858891|
|remote-ssh|ms-vscode-remote|0.65.7|
|remote-ssh-edit|ms-vscode-remote|0.65.7|
|remote-wsl|ms-vscode-remote|0.58.2|
|vscode-docker|ms-azuretools|1.15.0|
|vscode-graphql|GraphQL|0.3.16|
|vscode-html-css|ecmel|1.10.2|
|vscode-java-debug|vscjava|0.35.0|
|vscode-java-dependency|vscjava|0.18.6|
|vscode-java-pack|vscjava|0.18.2|
|vscode-java-test|vscjava|0.30.1|
|vscode-maven|vscjava|0.32.2|
|vscode-pylance|ms-python|2021.8.0|
|vscode-typescript-next|ms-vscode|4.5.20210810|
|vscode-yaml|redhat|0.22.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.14|;

</details>

**Comment by filipw** [comment]
This works correctly with semantic highlighting:

```
    "editor.semanticHighlighting.enabled": true,
    "csharp.semanticHighlighting.enabled": true
```

The issue with the built-in textmate grammar (not maintained in this repo but, in https://github.com/dotnet/csharp-tmLanguage). Semantic highlighting will generally speaking what you want to use anyway, because it is much better especially with modern language features.
