### ISSUE TITLE
Won't format arrays in C#

### ISSUE THREAD

**Issue by th3W3n** [OmniSharp/omnisharp-vscode#4703]
Hi Guys please help
I use VSCode and Unity to make games. As the image shown below, when I pressed Alt+Shift+F to format the C# file, codes within the array won't change, while other codes can format as usual.
![](https://user-images.githubusercontent.com/41976652/129116840-f306c2d1-98dd-4333-b196-36a8aed64ed9.png)

**Comment by JoeRobich** [comment]
@th3W3n The Roslyn formatter doesn't format object and array initializers. They have an open issue (https://github.com/dotnet/roslyn/issues/8269) to add support for these scenarios. You should vote it up to show your interest.

**Comment by th3W3n** [comment]
> @th3W3n The Roslyn formatter doesn't format object and array initializers. They have an open issue ([dotnet/roslyn#8269](https://github.com/dotnet/roslyn/issues/8269)) to add support for these scenarios. You should vote it up to show your interest.

Thanks for this information!
