### ISSUE TITLE
On Linux, when using CSharp script (.csx), using "less than" after "else if" causes all of the code following it to lose syntax features.

### ISSUE THREAD

**Issue by MostHated** [OmniSharp/omnisharp-vscode#4704]
## Issue Description ##
On Linux, when using CSharp script (.csx), using "less than" after "else if" causes all of the code following it to lose syntax features.

## Steps to Reproduce ##

 Using a "<" less than, after "else if" (but not if using "if" on it's own) seems to cause the issue. It seems quite weird, but you can see it in action below.

![](https://i.imgur.com/MJ9lAq8.gif)

## Expected Behavior ##
Syntax features to work regardless of keyword else

## Actual Behavior ##
Code loses syntax features when using "<" after "else if"

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.59.0-insider
**C# Extension**: 1.23.14

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     pop
 OS Version:  21.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.400/

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  3.1.405 [/usr/share/dotnet/sdk]
  5.0.103 [/usr/share/dotnet/sdk]
  5.0.400 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|aw-watcher-vscode|lindraupe|0.4.1|
|awesome-flutter-snippets|Nash|3.0.1|
|bash-beautify|shakram02|0.1.1|
|bash-debug|rogalmic|0.3.9|
|bash-ide-vscode|mads-hartmann|1.11.0|
|better-toml|bungcip|0.3.2|
|code-settings-sync|Shan|3.4.3|
|color-highlight|naumovs|2.4.0|
|color-manager|royaction|0.6.2|
|comment-anchors|ExodiusStudios|1.9.6|
|copilot|GitHub|1.3.2335|
|cpptools|ms-vscode|1.5.1|
|csharp|ms-dotnettools|1.23.14|
|customize-ui|iocave|0.1.54|
|dart-code|Dart-Code|3.25.1|
|dartgettersetter|PeterHdd|1.0.2|
|debug|webfreak|0.25.1|
|dotfiles-syntax-highlighting|dotiful|0.1.0|
|dotnetscriptr|Wivuu|0.2.4|
|expand-region|letrieu|0.1.4|
|flutter|Dart-Code|3.25.0|
|flutter-snippets|alexisvt|2.0.0|
|font-switcher|evan-buss|4.0.1|
|fzf-quick-open|rlivings39|0.4.3|
|gitignore|codezombiech|0.7.0|
|gitkraken-glo|axosoft|1.1.1|
|go|golang|0.27.1|
|go-snippets|zsh|0.0.4|
|horizon-theme-vscode|jolaleye|2.0.2|
|json-and-jsonc|htwx|1.0.1|
|jupyter|ms-toolsai|2021.8.1195043623|
|l13-sh-snippets|L13RARY|0.15.1|
|linux-desktop-file|nico-castell|0.0.18|
|lldb-vscode|lanza|0.2.3|
|local-history|xyz|1.8.1|
|lua|sumneko|2.3.6|
|luna-paint|Tyriar|0.8.1|
|markdown-all-in-one|yzhang|3.4.0|
|material-icon-theme|PKief|4.9.0|
|monkey-patch|iocave|0.1.15|
|path-autocomplete|ionutvmi|1.17.1|
|path-intellisense|christian-kohler|2.4.0|
|powershell-preview|ms-vscode|2021.8.0|
|project-manager|alefragnani|12.3.0|
|python|ms-python|2021.8.1105858891|
|rainbow-brackets|2gua|0.0.6|
|rainbow-csv|mechatroner|1.9.1|
|regionfolder|maptz|1.0.15|
|remote-containers|ms-vscode-remote|0.191.0|
|remote-ssh|ms-vscode-remote|0.65.7|
|remote-ssh-edit|ms-vscode-remote|0.65.7|
|remote-wsl|ms-vscode-remote|0.58.2|
|shell-format|foxundermoon|7.1.0|
|shell-syntax|bmalehorn|1.0.2|
|stylua|JohnnyMorganz|1.2.0|
|systemd-unit-file|coolbear|1.0.6|
|tabnine-vscode|TabNine|3.4.22|
|terraform|hashicorp|2.14.0|
|themeinfo|McNerdius|0.11.0|
|todo-tree|Gruntfuggly|0.0.213|
|turnipultimate-theme-vscode|instanceid|0.0.1|
|vsc-community-material-theme|Equinusocio|1.4.2|
|vsc-material-theme|Equinusocio|33.2.0|
|vsc-material-theme-icons|equinusocio|1.2.2|
|vscode-autohotkey-plus-slimcode|rafaelcavasani|2.1.18|
|vscode-commons|redhat|0.0.6|
|vscode-docker|ms-azuretools|1.15.0|
|vscode-home-assistant|keesschollaart|1.21.0|
|vscode-lldb|vadimcn|1.6.5|
|vscode-lua-format|Koihik|1.3.8|
|vscode-pylance|ms-python|2021.8.1|
|vscode-shell-snippets|DeepInThought|0.3.1|
|vscode-todo-highlight|wayou|1.0.4|
|vscode-wakatime|WakaTime|15.0.0|
|vscode-xml|redhat|0.18.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.14|;

</details>

**Comment by filipw** [comment]
Can you confirm that it works correctly with semantic highlighting?

```
    "editor.semanticHighlighting.enabled": true,
    "csharp.semanticHighlighting.enabled": true,
```

If so, then the issue with the built-in textmate grammar (not maintained in this repo but https://github.com/dotnet/csharp-tmLanguage). Semantic highlighting will generally speaking what you want to use anyway, because it is much better especially with modern language features.

**Comment by MostHated** [comment]
Hello, I have had semantic highlighting enabled since the option was first introduced, at least the editor.semanticHighlighting option. I did not have any language-specific options set for it, though. I went and set csharp.semanticHighlighting, then reloaded the window, and it looks like that might have done the trick. I had assumed that enabling it at the editor level setting would have made it active for all unless specified otherwise? Does this mean I should do the same for all languages, just to make sure they are using it if they can?

Thanks,
-MH

**Comment by filipw** [comment]
In this case it is a separate setting because it is still experimental and we want it to be possible to be explicitly enabled/disabled if needed, irrespective of VS Code settings.

**Comment by MostHated** [comment]
Well, I do appreciate the assistance, it looks like things are back to being as expected. Thanks.

**Comment by MostHated** [comment]
One last thing if you don't mind, I am not sure if this is an editor option or omnisharp specific, but is it possible to move those reference counts to variables? In Rider I am able to have them off to the right of each one, but on the same line, instead of making a separate line up above it. For some reason, it just bothers me to have that wasted space above every declaration.

**Comment by filipw** [comment]
No this is not possible in VS Code, you may want to open a request in VS Code repo for that https://github.com/Microsoft/vscode/issues/22127#issuecomment-285061033

**Comment by MostHated** [comment]
I just wanted to add a solution I just found, in case a search ever brings anyone to this thread.

This extension named [Toggle](https://marketplace.visualstudio.com/items?itemName=rebornix.toggle) lets you set a hotkey to toggle between editor settings, so I just setup the following:

```json
{
        "key": "F4",
        "command": "toggle",
        "when": "editorTextFocus",
        "args": {
            "id": "csCodeLenseToggle",
            "value": [
                {
                    "csharp.referencesCodeLens.enabled": true,
                },
                {
                    "csharp.referencesCodeLens.enabled": false,
                }
            ]
        }
    }
```

It's not the best solution, as the enable/disable takes a few seconds for it to actually do anything, but is nice if I simply want to remove them all relatively quickly without having to edit the settings manually.
