### ISSUE TITLE
Syntax highlighting and auto-complete not supporting the latest C# 10 features

### ISSUE THREAD

**Issue by vanka78bg** [OmniSharp/omnisharp-vscode#4709]
The latest version of OmniSharp for Visual Studio Code - 1.23.14 adds support for .NET 6 preview 7. Unfortunately, trying out the new version is quite difficult, because the syntax highlighting and auto-complete do not support the latest language features. Here is a screenshot of how the code currently looks in the editor:

![image](https://user-images.githubusercontent.com/1614598/129862833-df5ccaf0-56dd-4e48-8be3-7fe3e6b2d688.png)

This does not make Visual Studio Code a viable option to do any .NET 6 preview testing in its current state. The only viable option so far is to install the full-blown Visual Studio 2022 preview. Since Visual Studio Code has a much smaller footprint than Visual Studio 2022 preview, it would be a better option to do any preliminary testing of .NET 6, provided the C# syntax highlighting and auto-complete are fixed.

Are there any plans to add support for the new C# 10 features, before the .NET 6 gets official? The preview 7 is the latest preview version of .NET 6, before it goes to a release candidate, so it would be an ideal time to do it now. This would help testing the framework and the new language features before the official release.

**Comment by filipw** [comment]
Please enable semantic highlighting to get compiler based highlighting which is aware of all languague features:

```
    "editor.semanticHighlighting.enabled": true,
    "csharp.semanticHighlighting.enabled": true,
```

The built in C# textmate grammar is very basic.

With regards to completion, can you please explain which language features is not working for you? 
Certainly C# 10 is supported and the OmniSharp compiler version is aligned with .NET 6 Preview 7.

For example global implicit usings are certainly supported:

<img width="1011" alt="Bildschirmfoto 2021-08-18 um 10 47 50" src="https://user-images.githubusercontent.com/1710369/129868627-f5f3e5bf-2170-42d0-8a79-401a3e298016.png">

or the C# 10 ssignment and declaration in same deconstruction:

<img width="346" alt="Bildschirmfoto 2021-08-18 um 10 51 35" src="https://user-images.githubusercontent.com/1710369/129868637-cf5f12a1-a427-41c6-9aad-3b29d4bfcbd9.png">

Anything specific that doesn't work for you? Can you post your OmniSharp log?

**Comment by vanka78bg** [comment]
Thank you for the help!

Enabling the following option did the trick for me:
```
"csharp.semanticHighlighting.enabled": true,
```
The following option was already enabled, but that was not sufficient:
```
"editor.semanticHighlighting.enabled": true,
```
(Sorry, my bad, I did not knew there was a separate option for the C# extension)

Regarding the auto-complete not working reliably, it is working correctly now. Recently, I have cleaned remnants of earlier .NET 6 preview versions and uninstalled some unneeded VS Code extensions and now the auto-complete seems to be working. I do not know which action fixed the issue for me.

Again, thanks for the help! You can close this issue now.

**Comment by filipw** [comment]
Thanks, that's great to hear!
