### ISSUE TITLE
Omnisharp for new Linux distros supported by dotnet

### ISSUE THREAD

**Issue by rajkumar42** [OmniSharp/omnisharp-vscode#471]
@DustinCampbell dotnet has added support for couple of new Linux distros (https://www.microsoft.com/net/core) OpenSUSE, Fedora 23, Ubuntu 16. Can you please add support?

**Comment by DustinCampbell** [comment]
Wow, that's news to me. Note that we can only realistically support distros that VS Code supports.

Are you certain that Ubuntu 16 doesn't already work?

**Comment by rajkumar42** [comment]
VSCode installs and runs fine on Fedora 23 and Ubuntu 16. Installing the debugger fails at the publish stage, @caslan and @gregg-miskelly looking at fixing them.
VSCode compressed zip had to be downloaded and extracted for OpenSuse. I think for the above three we need the right assests in method getOmnisharpAssetName(). 

For Oracle Linux, which is binary compatible with CentOS, I've sent a pull request https://github.com/OmniSharp/omnisharp-vscode/pull/470

**Comment by DustinCampbell** [comment]
But, does Ubuntu 16 require any work? My expectation is that Ubuntu 16 is the same. Does Ubuntu 16 have a different RID in .NET Core?

**Comment by rajkumar42** [comment]
Yep it is a different RID for Ubuntu 16. dotnet cli installers are not the same for Ubuntu 14 & 16, they are not binary compatible.

RID: ubuntu.14.04-x64

**Comment by DustinCampbell** [comment]
thanks @rajkumar42 -- that's helpful.

**Comment by gregg-miskelly** [comment]
@DustinCampbell you will need three new zip's -- ubuntu.16.04-x64, fedora.23-x64, opensuse.13.2-x64

**Comment by DustinCampbell** [comment]
Thanks -- will take a look.

**Comment by DustinCampbell** [comment]
Changes to create new OmniSharp builds that target the new RIDs is here: https://github.com/OmniSharp/omnisharp-roslyn/pull/596. I'm also updating OmniSharp to the .NET Core 1.0 packages.

**Comment by DustinCampbell** [comment]
OmniSharp release with new distros is ready here: https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.9-beta11. I'll need to update our distro-sniffing OmniSharp download code next.

**Comment by DustinCampbell** [comment]
Addressed with #500

**Comment by damonmcminn** [comment]
@DustinCampbell thanks very much!

I'm running on Fedora 23. Am I right to assume upgrading to Fedora 24 will result in OmniSharp no longer working? If so, is it a fix I could be directed to implement?

Thanks :)

**Comment by DustinCampbell** [comment]
It *might* break. The extension will certainly download the Fedora-targeted OmniSharp. However, OmniSharp is dependent on .NET Core to run, which only supports Fedora 23 at the moment. So, if there are any changes in Fedora 24 that would break .NET Core, it would break OmniSharp. There isn't a simple fix.

**Comment by damonmcminn** [comment]
I'll put that unnecessary idea to bed then :)
 
 
On Thu, 30 Jun 2016, at 02:33 PM, Dustin Campbell wrote:
> It *might* break. The extension will certainly download the Fedora-
> targeted OmniSharp. However, OmniSharp is dependent on .NET Core to
> run, which only supports Fedora 23 at the moment. So, if there are any
> changes in Fedora 24 that would break .NET Core, it would break
> OmniSharp. There isn't a simple fix.
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>

Links:

  1. https://github.com/OmniSharp/omnisharp-vscode/issues/471#issuecomment-229658924
  2. https://github.com/notifications/unsubscribe/AFKj3MQRBv-FqmiXaoQYT2qM3IswuBYnks5qQ8WNgaJpZM4I_foz
