### ISSUE TITLE
Hot Code Replace

### ISSUE THREAD

**Issue by badsyntax** [OmniSharp/omnisharp-vscode#4714]
## Issue Description ##

I can't find any documentation on how to handle hot code when debugging. I'd like to be able to edit code and get that hot code replaced without having to stop and restart the debugger.

## Steps to Reproduce ##

1. Add a breakpoint
2. Run the c# debugger
3. Change code
4. Code is not updated in running debug session

## Expected Behavior ##

I'd like to see a "Hot Code Replace" button in the debug toolbar, similar to debugging Java:

<img width="250" alt="Screenshot 2021-08-20 at 08 59 10" src="https://user-images.githubusercontent.com/102141/130200642-632ea681-738b-4a43-bc7e-fb9c915d9d50.png">

## Actual Behavior ##

There's no option to replace hot code.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.59.1
**C# Extension**: 1.23.14

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.13.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.302/

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  3.1.411 [/usr/local/share/dotnet/sdk]
  5.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.9.8|
|azure-pipelines|ms-azure-devops|1.191.0|
|bash-debug|rogalmic|0.3.9|
|bats|jetmartin|0.1.7|
|code-spell-checker|streetsidesoftware|1.10.2|
|cpptools|ms-vscode|1.5.1|
|csharp|ms-dotnettools|1.23.14|
|debugger-for-chrome|msjsdiag|4.12.12|
|dotenv|mikestead|1.0.1|
|EditorConfig|EditorConfig|0.16.4|
|java|redhat|0.81.0|
|path-autocomplete|ionutvmi|1.17.1|
|polacode-fixed-edition|mrrefactoring|0.3.6|
|postcss|csstools|1.0.9|
|powershell|ms-vscode|2021.8.0|
|prettier-vscode|esbenp|8.1.0|
|python|ms-python|2021.8.1147840270|
|richard-willis-extension-pack|richardwillis|1.3.44|
|shell-format|foxundermoon|7.1.0|
|shellcheck|timonwong|0.15.2|
|vscode-docker|ms-azuretools|1.16.0|
|vscode-eslint|dbaeumer|2.1.23|
|vscode-java-debug|vscjava|0.35.0|
|vscode-java-dependency|vscjava|0.18.6|
|vscode-java-pack|vscjava|0.18.4|
|vscode-java-test|vscjava|0.31.2|
|vscode-markdownlint|DavidAnson|0.43.2|
|vscode-maven|vscjava|0.32.2|
|vscode-proto3|zxh404|0.5.4|
|vscode-pylance|ms-python|2021.8.2|
|vscode-styled-components|jpoissonnier|1.6.6|
|vscode-stylelint|stylelint|0.86.0|
|vscode-xml|redhat|0.18.0|
|vscode-yaml|redhat|0.22.0|;

</details>

**Comment by gregg-miskelly** [comment]
Currently this is not possible with this extension. This feature is tracked with #490.
