### ISSUE TITLE
How to disable omnisharp without uninstalling?

### ISSUE THREAD

**Issue by edwardmeshuris** [OmniSharp/omnisharp-vscode#472]
We have old projects that have not been converted to core yet, when i open these in vscode, i just get a bunch of errors. How to disable?

**Comment by edwardmeshuris** [comment]
I guess the answer is to uninstall it, which is unfortunate.

**Comment by DustinCampbell** [comment]
Sorry for the delay here. That's not a great answer, but I think it's probably the state of things today.

**Comment by johnypony3** [comment]
its alright, i stopped using vscode altogether. Why not use the thing that this is written on?

**Comment by DustinCampbell** [comment]
> Why not use the thing that this is written on?

Sorry, I don't follow.

**Comment by edwardmeshuris** [comment]
Vscode is based on atom, I switched to using atom.
