### ISSUE TITLE
References should be above attributes, not below, for better visual clarity

### ISSUE THREAD

**Issue by yunruse** [OmniSharp/omnisharp-vscode#4724]
## Issue Description ##

This is a terribly nitpicky nitpick at something that seems to be a bit irksome when looking at code, and makes my eyes move towards the wrong code, due to the presence of the references in the wrong places.

## Steps to Reproduce ##

Create a C# file with an attribute below something else. For example:
```csharp
namespace MyAttributes
{
    public class AttributeScanner { }
    [System.AttributeUsage(System.AttributeTargets.Parameter)]
    public class SomeAttribute : System.Attribute { }
}
```
and allow OmniSharp to display references.

## Expected Behavior ##

The reference for `SomeAttribute` can act, when viewing code, as a line of pseudo-whitespace, which has implications on how programmers (or at the _very_ least, myself :) subconsciously view the code around it. By providing a list of references, this line acts as a sort of "header" to the item. As such, one would expect the reference line to be displayed above attributes.

This would not cause any conflicts – after all, attributes only call an instantiator and do not declare anything, so attributes themselves would not have references.

## Actual Behavior ##

The reference line is displayed below attributes. The pseudo-whitespace visually implies that the attributes are somehow applying to something above them, or nothing at all. This can get a little confusing when working with a lot of attributes – having the reference _inside_ of the entity, rather than above it, can mess with muscle memory.

My team's code style is to not have empty lines after imports other than a _single_ empty line to leverage logically separate blocks of functions or code. This kinda makes this issue stand out a lot more.

## Logs ##

None relevant

### OmniSharp log ###

(None relevant. This is a feature change request, not a bug fix.)

### C# log ###

(None relevant. This is a feature change request, not a bug fix.)

## Environment information ##

**VSCode version**: 1.59.1
**C# Extension**: 1.23.14

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.206
 Commit:    0cf287db1b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.0
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/Cellar/dotnet/5.0.206/libexec/sdk/5.0.206/

Host (useful for support):
  Version: 5.0.9
  Commit:  7422fa72e3

.NET SDKs installed:
  5.0.206 [/usr/local/Cellar/dotnet/5.0.206/libexec/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [/usr/local/Cellar/dotnet/5.0.206/libexec/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/local/Cellar/dotnet/5.0.206/libexec/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|binary-plist|dnicolson|0.6.0|
|csharp|ms-dotnettools|1.23.14|
|jupyter|ms-toolsai|2021.8.1236758218|
|python|ms-python|2021.8.1159798656|
|vscode-pylance|ms-python|2021.8.3|;

</details>

**Comment by nohwnd** [comment]
This is how Visual Studio Code shows it, and it also is how Visual Studio shows it. The reference belongs to the method not the attribute. This is by design and we won't change that. Sorry.
