### ISSUE TITLE
The launch.json is not generated automatically when open existing aspnet core mvc project

### ISSUE THREAD

**Issue by richardzeng1985** [OmniSharp/omnisharp-vscode#473]
## Environment data
`dotnet --info` output:
VS Code version: 1.2.1 
C# Extension version: .1.1.7

## Steps to reproduce
1. Launch vscode
2. Open the existing asp.net core mvc project "src\musicstore" <is there a way can allow me upload the sample project ?>
3. Click "Yes" when pop up a prompt "adding missing build and debug assets ?" when  the status bar indicate "Successfully installed .NET Core Debugger".

## Expected  behavior
both tasks.json and launch.json should be generated under .vscode folder automatically

## Actual behavior
only tasks.json is generated automatically, and I need manually select the ".NET Core" to generate the launch.json and configure the target binary for "program" in launch.json.

**Comment by richardzeng1985** [comment]
Attached repro project.
[musicstore.zip](https://github.com/OmniSharp/omnisharp-vscode/files/336372/musicstore.zip)

**Comment by DustinCampbell** [comment]
@caslan: I don't think this is a debugger issue. It's with the tasks.json/launch.json generation code. I  suspect this is the same issue as #170.

**Comment by caslan** [comment]
Yes, this the same issue. Closing this one as dupe.
