### ISSUE TITLE
Syntax highlighting issue when null conditional accessor split with a newline

### ISSUE THREAD

**Issue by AshleyWorkmanBoomi** [OmniSharp/omnisharp-vscode#4734]
## Issue Description ##
Syntax highlighting breaks when the null conditional access operator is split, first the wrong colours are used and then this progresses to a complete lack of colour. Enabling the `csharp.semanticHighlighting.enabled` option corrects the highlighting issue.

## Steps to Reproduce ##
The following example reproduces this issue:
```
            var list = new List<string>()?
                            .Select(x => x).Distinct().ToArray();

            foreach(var element in list)
            {
                switch (element)
                {
                    case "Case One":
                        break;
                    default:
                        break;

                }
            }

            return list;
```
## Expected Behavior ##
![image](https://user-images.githubusercontent.com/81561002/131662570-c7336e7c-58b6-458a-b92d-3cd329d1d668.png)

## Actual Behavior ##
![image](https://user-images.githubusercontent.com/81561002/131662514-38459f44-6a55-48ce-9d7c-c49fc49310c1.png)

## Environment information ##

**VSCode version**: 1.59.1
**C# Extension**: 1.23.14

**Comment by JoeRobich** [comment]
This was recently fixed in the C# textmate grammar (https://github.com/dotnet/csharp-tmLanguage/pull/216). It should flow automatically flow into VS Code for the October release. You can set `csharp.semanticHighlighting.enabled` to `true` to enable our semantic highlighting which will also resolve this issues for you.
