### ISSUE TITLE
Incorrect "Additional setup is required to debug Blazor WebAssembly applications."

### ISSUE THREAD

**Issue by niktek** [OmniSharp/omnisharp-vscode#4739]
## Issue Description ##
Fresh install of vscode and C# extension on a new VM and opened to a dotnet new blazorwasm folder and the alert for "Additional setup is required to debug Blazor WebAssembly applications." appears.

The 'Learn more' button points to the documentation at https://docs.microsoft.com/en-gb/aspnet/core/blazor/debug?tabs=visual-studio-code&view=aspnetcore-5.0#vscode that instructs at point 3 Javascript: Use Preview - but this option is not present in the user settings.

It looks like there is a test for Debug > Javascript: Use Preview ("debug.javascript" === 'usePreview' in src/omnisharp/utils.ts -> hasBlazorWebAssemblyDebugPrerequisites() that now fails.

## Steps to Reproduce ##
Open a C# blazorwasm project

## Expected Behavior ##
Debugging to be enabled

## Actual Behavior ##
Debugging is not available

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.60.0
**C# Extension**: 1.23.15

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  5.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|blazorwasm-companion|ms-dotnettools|1.1.0|
|csharp|ms-dotnettools|1.23.15|
|vscode-dotnet-runtime|ms-dotnettools|1.2.0|;

</details>

**Comment by sergiojrdotnet** [comment]
I have the same issue here

**Comment by 50Wliu** [comment]
@JoeRobich - This is fixed with #4964.
