### ISSUE TITLE
Debugger: Start without debugging (Ctrl+F5) doesn't take effect

### ISSUE THREAD

**Issue by richardzeng1985** [OmniSharp/omnisharp-vscode#474]
## Environment data
`dotnet --info` output:
VS Code version:1.2.1 
C# Extension version:1.1.7

## Steps to reproduce
1. Open existing sample project "src\musicstore" 
2. Set a breakpoint in line "19" in file HomeController.cs
3. Ctrl +F5

## Expected  behavior
The web application should be launched without hitting the breakpoint. 

<From the Command Palettle,  I can see this command via type :Debug: Start Without Debugging, so I assume this should be supported, correct ? >

## Actual behavior
The breakpoint is hit

**Comment by chuckries** [comment]
This is being tracked by #199
