### ISSUE TITLE
Wrong highlighting in code

### ISSUE THREAD

**Issue by SuperJura** [OmniSharp/omnisharp-vscode#4741]
Wrong highlighting in code

1 - Create/Open a Unity project
2 - Start writing code
3 - Add "switch" in a variable name. e.g. "var switches = ..."
4 - It will highlight only switch as a keyword and for some next n lines, the text will be white.

Expected behavior: Don't highlight "switch" in a variable name

Actual behavior:  Highlights "switch" in a variable name

**VSCode version**: 1.60.0
**C# Extension**: 1.23.15

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.300
 Commit:    2e0c8c940e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  3.1.408 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|aspnetcorerazor-html-css-class-completion|kevin-chatham|1.0.3|
|awesome-flutter-snippets|Nash|3.0.1|
|blazorwasm-companion|ms-dotnettools|1.1.0|
|code-runner|formulahendry|0.11.5|
|cpptools|ms-vscode|1.6.0|
|csharp|ms-dotnettools|1.23.15|
|dart-code|Dart-Code|3.26.0|
|flutter|Dart-Code|3.26.0|
|json|ZainChen|2.0.2|
|jupyter|ms-toolsai|2021.8.1236758218|
|jupyter-keymap|ms-toolsai|1.0.0|
|python|ms-python|2021.9.1191016588|
|svn-scm|johnstoncode|2.13.6|
|unity-debug|Unity|3.0.2|
|vsc-python-indent|KevinRose|1.14.2|
|vscode-dotnet-runtime|ms-dotnettools|1.2.0|
|vscode-html-css|ecmel|1.10.2|
|vscode-pylance|ms-python|2021.9.0|;

</details>
![image](https://user-images.githubusercontent.com/6891009/131986312-5531e40e-14e1-4867-af1f-a62629ca2f95.png)

**Comment by JoeRobich** [comment]
This issue was fixed in the C# textmate grammar in https://github.com/dotnet/csharp-tmLanguage/pull/215. As a workaround today, you can set `csharp.semanticHighlighting.enabled` to `true` in VS Code settings to enable our semantic highlighting.

**Comment by SuperJura** [comment]
Great, thanks :)
