### ISSUE TITLE
Downloading package 'OmniSharp for Linux (x64), Version = 1.37.16-beta.2' (36680 KB) is taking forever

### ISSUE THREAD

**Issue by shpendpalushi** [OmniSharp/omnisharp-vscode#4743]
I have seen this issue previously and the single solution to it was switching to Rider and closing it.
Lets open this again a hopefully someone will go for a solution to it. Whenever I try to install Omnisharp on Linux machine it is taking forever either on the latest version or in the specified one. Is there a convenient solution to that?

**Comment by filipw** [comment]
please remove the setting "omnisharp.path": "latest" - this forces a download of every pre-release build of Omnisharp upon every merge to master. This is only suitable for testing.
