### ISSUE TITLE
File Scoped Namespaces Break CodeLens

### ISSUE THREAD

**Issue by JohnCampionJr** [OmniSharp/omnisharp-vscode#4748]
## Issue Description ##
In files with File-scoped namespaces, the CodeLens feature is broken

## Steps to Reproduce ##
Change a file to file-scoped namespace from block

## Expected Behavior ##
No change to CodeLens

![codelens](https://user-images.githubusercontent.com/1094820/132281134-9be8a552-8adc-4a61-b2d7-12d4c88089c7.png)

## Actual Behavior ##
CodeLens disappears

![no codelense](https://user-images.githubusercontent.com/1094820/132281151-2865ac7c-c5eb-4676-b160-1fdfa6796757.png)

### OmniSharp log ###
No errors reported

### C# log ###
Nothing

## Environment information ##

**VSCode version**: 1.60.0
**C# Extension**: 1.23.15

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.15|
|dotnet-test-explorer|formulahendry|0.7.6|
|EditorConfig|EditorConfig|0.16.4|
|msbuild-project-tools|tintoy|0.3.15|
|volar|johnsoncodehk|0.27.15|
|vscode-icons|vscode-icons-team|11.6.0|;

</details>

**Comment by filipw** [comment]
This was already fixed in https://github.com/OmniSharp/omnisharp-roslyn/pull/2226
