### ISSUE TITLE
Mystery "0" characters in Output window

### ISSUE THREAD

**Issue by jtsom** [OmniSharp/omnisharp-vscode#4749]
## Issue Description ## 
Output window showing "0" character at the beginning of every output line:

<img width="429" alt="image" src="https://user-images.githubusercontent.com/13488/132367347-edf2b3ec-b02f-47cb-952d-5cb1a0285193.png">

## Steps to Reproduce ##
Load .Net project, click run.

## Expected Behavior ##
Don't show unexpected characters (or document what it means)

## Actual Behavior ##
Showing extra characters

### OmniSharp log ###
<details>Starting OmniSharp server at 9/7/2021, 10:59:51 AM
    Target: /Users/john/Developer/DotNet/BlazorApp

OmniSharp server started.
    Path: /Users/john/.vscode-insiders/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/run
    PID: 66299

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 11.5.2 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 17.0.0 - "/Users/john/.vscode-insiders/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/Users/john/.vscode-insiders/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 17.0.0 - "/Users/john/.vscode-insiders/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /Users/john/.vscode-insiders/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin
            CscToolPath = /Users/john/.vscode-insiders/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /Users/john/.vscode-insiders/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/john/Developer/DotNet/BlazorApp'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/john/Developer/DotNet/BlazorApp'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/john/Developer/DotNet/BlazorApp/BlazorApp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/john/Developer/DotNet/BlazorApp'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/john/Developer/DotNet/BlazorApp' on host 66211.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/john/Developer/DotNet/BlazorApp/BlazorApp.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/john/Developer/DotNet/BlazorApp/BlazorApp.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/john/Developer/DotNet/BlazorApp/BlazorApp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: BlazorApp
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 16.
Received response for /v2/getcodeactions but could not find request.
</details>

### C# log ###
<details>Empty</details>

## Environment information ##

**VSCode version**: 1.61.0-insider
**C# Extension**: 1.23.15

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

** INCORRECT - global.json file IS in project:
```
{
  "sdk": {
    "version": "5.0.400"
  }
}
```

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-preview.7.21379.14/

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  2.2.402 [/usr/local/share/dotnet/sdk]
  3.1.412 [/usr/local/share/dotnet/sdk]
  5.0.400 [/usr/local/share/dotnet/sdk]
  6.0.100-preview.7.21379.14 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Angular2|johnpapa|12.0.0|
|blazorwasm-companion|ms-dotnettools|1.1.0|
|csharp|ms-dotnettools|1.23.15|
|EditorConfig|EditorConfig|0.16.4|
|githistory|donjayamanne|0.6.18|
|hexeditor|ms-vscode|1.8.2|
|js-debug-nightly|ms-vscode|2021.9.417|
|material-icon-theme|PKief|4.10.0|
|msbuild-project-tools|tintoy|0.3.15|
|ng-template|Angular|12.2.0|
|night-owl|sdras|2.0.1|
|open-in-browser|techer|2.0.0|
|ossaction|pgarcia|1.0.0|
|path-intellisense|christian-kohler|2.4.0|
|quicktype|quicktype|12.0.46|
|vscode-dotnet-runtime|ms-dotnettools|1.2.0|
|vscode-eslint|dbaeumer|2.1.23|
|vscode-thunder-client|rangav|1.9.1|
|vscode-typescript-next|ms-vscode|4.5.20210906|
|vscodeintellicode|VisualStudioExptTeam|1.2.14|
|winteriscoming|johnpapa|1.4.4|;

</details>

**Comment by nohwnd** [comment]
It looks like something you can see in the chrome developer tools, and it should show number of repeated messages. Looks like part of the actual VSCode experience. I see you are on insider build, they are probably trying something new. 

@gregg-miskelly have you seen this before?

**Comment by gregg-miskelly** [comment]
I haven't seen this before, but I can repro it. I opened https://github.com/microsoft/vscode/issues/132563 to track it.
