### ISSUE TITLE
Debugger: There is no error message when attempt to launch the program (web) which contains a space

### ISSUE THREAD

**Issue by richardzeng1985** [OmniSharp/omnisharp-vscode#475]
## Environment data
`dotnet --info` output:
VS Code version:1.2.1
C# Extension version:1.1.7

## Steps to reproduce
1. Download and launch the sample project from https://github.com/OmniSharp/omnisharp-vscode/files/336372/musicstore.zip 
2. Select ".NET Core Launch Web" and configure the location of musicstore.dll for "program which contains the space at the end as following: 
    "program": "${workspaceRoot}/bin/Debug/netcoreapp1.0/musicstore.dll  ",
3. Set the "stopAtEntry": true
4. F5

## Expected  behavior

If we don't support the binary location which contains a space for web, then we should prompt a error indicate this location is invalid. 

## Actual behavior

The application didn't start debugging successfully and there is not any message prompt.

**Comment by wesrupert** [comment]
This fix will be available in the next release.
