### ISSUE TITLE
Omnisharp crashes when loading Csharp file

### ISSUE THREAD

**Issue by gjoedev** [OmniSharp/omnisharp-vscode#4757]
## Issue Description ##
Upon loading Csharp file, the omnisharp extension crashes.
## Steps to Reproduce ##
1. Open Csharp file in vscode
## Expected Behavior ##
1. Open Csharp file
2. Extension works
## Actual Behavior ##
1. Open Csharp file
2. Extension crashes
### OmniSharp log ###
<details>Starting OmniSharp server at 9/9/2021, 8:52:49 PM
    Target: c:\Users\conno\2D fps\2D fps.sln

OmniSharp server started.
    Path: c:\Users\conno\.vscode\extensions\ms-dotnettools.csharp-1.23.15\.omnisharp\1.37.15\OmniSharp.exe
    PID: 5816

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 17.0.0 - "c:\Users\conno\.vscode\extensions\ms-dotnettools.csharp-1.23.15\.omnisharp\1.37.15\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\conno\.vscode\extensions\ms-dotnettools.csharp-1.23.15\.omnisharp\1.37.15\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 17.0.0 - "c:\Users\conno\.vscode\extensions\ms-dotnettools.csharp-1.23.15\.omnisharp\1.37.15\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\conno\.vscode\extensions\ms-dotnettools.csharp-1.23.15\.omnisharp\1.37.15\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\conno\.vscode\extensions\ms-dotnettools.csharp-1.23.15\.omnisharp\1.37.15\.msbuild
            MSBuildToolsPath = c:\Users\conno\.vscode\extensions\ms-dotnettools.csharp-1.23.15\.omnisharp\1.37.15\.msbuild\Current\Bin
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\conno\2D fps'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\conno\2D fps\2D fps.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\conno\2D fps\Assembly-CSharp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\conno\2D fps'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\conno\2D fps' on host 10624.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\conno\2D fps\Assembly-CSharp.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\conno\2D fps\Assembly-CSharp.csproj'.
c:\Users\conno\2D fps\Assembly-CSharp.csproj
c:\Users\conno\.vscode\extensions\ms-dotnettools.csharp-1.23.15\.omnisharp\1.37.15\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1217,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\conno\2D fps\Assembly-CSharp.csproj
</details>

### C# log ###
No log

## Environment information ##

**VSCode version**: 1.60.0
**C# Extension**: 1.23.15

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.200
 Commit:    70b3e65d53

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  5.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.15|
|csharp-extentions-pack|boundarystudio|0.3.0|
|csharpextensions|jchannon|1.3.1|
|ctrl-semicolon|Gforcedev|0.1.0|
|discord-theme|SmallBlueDevelopment|0.0.1|
|discord-tools|Darkempire78|1.4.3|
|discord-vscode|icrawl|5.7.0|
|glassit|s-nlf-fh|0.2.3|
|html-snippets|abusaidm|0.2.1|
|java|redhat|0.81.0|
|jupyter|ms-toolsai|2021.8.2041215044|
|jupyter-keymap|ms-toolsai|1.0.0|
|LiveServer|ritwickdey|5.6.1|
|markdown-all-in-one|yzhang|3.4.0|
|markdown-preview-enhanced|shd101wyy|0.6.0|
|material-theme|zhuangtongfa|3.11.4|
|python|ms-python|2021.9.1191016588|
|remote-containers|ms-vscode-remote|0.194.0|
|remote-ssh|ms-vscode-remote|0.65.7|
|remote-ssh-edit|ms-vscode-remote|0.65.7|
|remote-wsl|ms-vscode-remote|0.58.2|
|shader|slevesque|1.1.5|
|shaderlabvscodefree|amlovey|1.2.8|
|synthwave-x-fluoromachine|webrender|0.0.12|
|tic80-vscode|Gi972|1.7.0|
|unity-code-snippets|cemuka|0.1.0|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-debug|Unity|3.0.2|
|unity-snippets|YclepticStudios|0.1.2|
|unity-snippets-modified|lionize|0.4.0|
|vscode-csharp-snippets|jorgeserrano|1.1.0|
|vscode-icons|vscode-icons-team|11.6.0|
|vscode-java-debug|vscjava|0.35.0|
|vscode-java-dependency|vscjava|0.18.7|
|vscode-java-pack|vscjava|0.18.4|
|vscode-java-test|vscjava|0.31.3|
|vscode-maven|vscjava|0.33.0|
|vscode-pylance|ms-python|2021.9.1|
|vscode-remote-extensionpack|ms-vscode-remote|0.21.0|
|vscode-typescript-next|ms-vscode|4.5.20210908|
|vscodeintellicode|VisualStudioExptTeam|1.2.14|;

</details>

**Comment by filipw** [comment]
Omnisharp does not ship with reference assemblies for .NET Framework - you need to install them separately as the error message says

> The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

**Comment by filipw** [comment]
you can install MS Build Tools from https://go.microsoft.com/fwlink/?linkid=840931

**Comment by gjoedev** [comment]
My bad, I had runtime installed but not the dev pack

**Comment by gjoedev** [comment]
Note to future travelers that find this issue, Make sure to install **[.NET 4.7.1](https://dotnet.microsoft.com/download/dotnet-framework/net471), and Not the latest version.** Omnisharp does not yet appear to work with .NET 4.8

**Comment by JoeRobich** [comment]
> Omnisharp does not yet appear to work with .NET 4.8

To be fair to OmniSharp, it is Unity that is targeting .NET 4.7.1 instead of 4.8 in their generated .csproj files.
