### ISSUE TITLE
Forming an incorrect database connection string

### ISSUE THREAD

**Issue by b1t2byte** [OmniSharp/omnisharp-vscode#4758]
## Environment data
`dotnet --info` output:
Пакет SDK для .NET (отражающий любой global.json):
 Version:   5.0.400     
 Commit:    d61950f9bf  

Среда выполнения:       
 OS Name:     Windows   
 OS Version:  10.0.19043
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  5.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]        
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App] 

VS Code version: 
Версия: 1.60.0 (system setup)
Фиксация: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Дата: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
ОС: Windows_NT x64 10.0.19043

C# Extension version:
1.23.15

## Steps to reproduce
1) https://docs.microsoft.com/ru-ru/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-5.0&tabs=visual-studio-code
2) https://docs.microsoft.com/ru-ru/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-5.0&tabs=visual-studio-code
3) https://docs.microsoft.com/ru-ru/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-5.0&tabs=visual-studio-code
4) https://docs.microsoft.com/ru-ru/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-5.0&tabs=visual-studio-code

dotnet-aspnet-codegenerator controller -name MoviesController -m Movie -dc MvcMovieContext --relativeFolderPath Controllers --useDefaultLayout --referenceScriptLibraries

## Expected  behavior
Creating ConnectionStrings in appsettings.json file
appsettings.json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  **"ConnectionStrings": {
    "MvcMovieContext": "Data Source=MvcMovie.db"
  }**
}

## Actual behavior
Creating ConnectionStrings in appsettings.json file
appsettings.json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  **"ConnectionStrings": {
    "MvcMovieContext": "Server=(localdb)\\mssqllocaldb;Database=MvcMovieContext-1;Trusted_Connection=True;MultipleActiveResultSets=true"**
  }
}

**Comment by JoeRobich** [comment]
@b1t2byte This repo is for the C# extension for VS Code. You can report issues with the dotnet-aspnet-codegenerator global tool that is generating your `appsettings.json` file at https://github.com/dotnet/Scaffolding/issues.
