### ISSUE TITLE
Feature: Class View

### ISSUE THREAD

**Issue by manojbaishya** [OmniSharp/omnisharp-vscode#4759]
Is there a class view panel available like in Visual Studio 2019, which shows namespaces as well? Currently I am using https://github.com/pierre3/PlantUmlClassDiagramGenerator but it does not show namespaces in the UML diagram.

Please close this issue if there is, or if there is an extension for this feature. I could not find another issue with this topic here. (Request you to set up the github discussion boards for non-issue queries like these)

![image](https://user-images.githubusercontent.com/28330014/132841004-ab24d108-0558-4f67-af45-64ebfdd49dbc.png)

**Comment by nohwnd** [comment]
We will take this into consideration, but there are not current plans to do this. If you really want this feature please consider contributing it as a PR to this project, or prototype it and we can talk about it further. There is also this extension https://marketplace.visualstudio.com/items?itemName=fernandoescolar.vscode-solution-explorer that might be more advanced, or closer to what you need.

**Comment by manojbaishya** [comment]
Thanks a lot for the explanation. I am not familiar with typescript or extension development at this point, so I am going to close this issue, but if I am ready at a later date, I shall be very happy to demo a prototype! 

I do use the aforementioned extension, and it is a feature-to-feature mapping of the VS solution explorer, which does not show namespaces yet (out of scope)… But it has greatly bridged the gap between VS and VSC !
