### ISSUE TITLE
Debugger: Disable JMC doesn't work correctly

### ISSUE THREAD

**Issue by richardzeng1985** [OmniSharp/omnisharp-vscode#476]
## Environment data
`dotnet --info` output:
VS Code version:1.2.1
C# Extension version:1.1.7

## Steps to reproduce
1. Create a sample .net core console app via "dotnet new "
2. Launch the project and click "Yes" to add debug/build assets
3. Disable JMC in launch.json  < Note:  The "justMyCode" item is not in this file by default and I need to manually add it,  is it a bug ? >
     "justMyCode": false
4. Set "stopAtEntry" = true
5. F5, and verify the callstack window

## Expected  behavior

The callstack window should display the fame of "main" and all of the frame of system libraries (The function frame of non-user code).

## Actual behavior
It only displays the frame of "main" function, plus a "[Native to Manged Transition]"

**Comment by gregg-miskelly** [comment]
That sounds correct. I wouldn't expect there to be a non-user code in that scenario. You need some non-user code on the call stack (ex: use a Lazy<T>).
