### ISSUE TITLE
.NET Core 3.1 projects not working correctly since installing .NET 5 SDK

### ISSUE THREAD

**Issue by no-stack-dub-sack** [OmniSharp/omnisharp-vscode#4772]
## Issue Description ##
I've recently installed the .NET 5 SDK (and consequently also updated Visual Studio to 16.11.2 as my .NET 5 projects weren't building until I did this - I think because I needed the latest version of the MS Build Engine 16.11.00?). In any case, since installing the .NET 5 SDK, my .NET Core 3.1 projects only _kind of_ work in VS Code. They build and debug fine, however many intellisense features, code completion, and code navigation features just no longer work. For example, <kbd>F12</kbd> to navigate to definition does not work and hints about compilation errors/warnings that used to show up as I type (such as a missing `new` keyword or violations of formatting rules) no longer show up until I actually build the project.

I could not find any similar issues in my search, so not sure if this has been reported yet. Happy to provide additional details if needed.

I'm wondering if this is something that can be addressed using `omnisharp.json`? Perhaps by setting the `msBuild` version?

Thanks in advance for your help.

## Steps to Reproduce ##
Install the .NET 5 SDK and open a .NET Core 3.1 project.

## Expected Behavior ##
Intellisense, code nav, code completion, and real time build errors should work / be displayed in source code files.

## Actual Behavior ##
The above mentioned features are not working.

### OmniSharp log ###
Some recent logs with warnings which I'm not sure are relevant:
<details>
Received response for /v2/codestructure but could not find request.
Received response for /v2/codestructure but could not find request.
Received response for /v2/codestructure but could not find request.
Received response for /v2/codestructure but could not find request.
Received response for /v2/codestructure but could not find request.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No document found. File: c:\Users\pweinberg\Code\Projects\RevAttributionPortal\RevAttributionPortal\Controllers\AuthenticatedController.cs.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No document found. File: c:\Users\pweinberg\Code\Projects\RevAttributionPortal\RevAttributionPortal\Controllers\AuthenticatedController.cs.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No document found. File: c:\Users\pweinberg\Code\Projects\RevAttributionPortal\RevAttributionPortal\Controllers\AuthenticatedController.cs.
Received response for /v2/codestructure but could not find request.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No symbol found. File: c:\Users\pweinberg\Code\Projects\RevAttributionPortal\RevAttributionPortal\Controllers\FilesController.cs, Line: 394, Column: 66.
</details>

### C# log ###
Not relevant

## Environment information ##

**VSCode version**: 1.60.0
**C# Extension**: 1.23.15

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.2.109 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|apexdox-vs-code|PeterWeinberg|1.1.3|
|atom-keybindings|ms-vscode|3.0.9|
|auto-comment-blocks|kevinkyang|1.0.1|
|auto-using|Fudge|0.7.15|
|ayu|teabyii|1.0.5|
|beautify|HookyQR|1.5.0|
|Bookmarks|alefragnani|13.2.1|
|code-runner|formulahendry|0.11.5|
|code-settings-sync|Shan|3.4.3|
|code-spell-checker|streetsidesoftware|2.0.4|
|crayon-vscode|jansenfuller|0.6.4|
|csharp|ms-dotnettools|1.23.15|
|csharpextensions|jchannon|1.3.1|
|debugger-for-chrome|msjsdiag|4.13.0|
|dotenv|mikestead|1.0.1|
|forcecode|JohnAaronNelson|4.0.1|
|gatekeeper|vsls-contrib|0.0.9|
|gitlens|eamodio|11.6.0|
|htmltagwrap|bradgashler|0.0.7|
|JavaScriptSnippets|xabikos|1.8.0|
|mario-theme|alphatr|0.0.2|
|markdown-all-in-one|yzhang|3.4.0|
|material-dark|romanrei|1.1.0|
|material-icon-theme|PKief|4.10.0|
|material-theme|zhuangtongfa|3.11.4|
|npm-intellisense|christian-kohler|1.4.0|
|path-autocomplete|ionutvmi|1.17.1|
|prettier-vscode|esbenp|8.1.0|
|reasonml|freebroccolo|1.0.38|
|remote-wsl|ms-vscode-remote|0.58.2|
|salesforce-vscode-slds|salesforce|1.4.8|
|salesforcedx-vscode|salesforce|52.13.0|
|salesforcedx-vscode-apex|salesforce|52.13.0|
|salesforcedx-vscode-apex-debugger|salesforce|52.13.0|
|salesforcedx-vscode-apex-replay-debugger|salesforce|52.13.0|
|salesforcedx-vscode-core|salesforce|52.13.0|
|salesforcedx-vscode-lightning|salesforce|52.13.0|
|salesforcedx-vscode-lwc|salesforce|52.13.0|
|salesforcedx-vscode-soql|salesforce|52.13.0|
|salesforcedx-vscode-visualforce|salesforce|52.13.0|
|save-and-run|wk-j|0.0.22|
|Seti-theme|TsumiNa|0.0.1|
|sort-imports|amatiasq|6.2.6|
|sort-lines|Tyriar|1.9.0|
|theme-monokai-dark-soda|AdamCaviness|1.0.0|
|theme-onedark|azemoh|0.6.0|
|todo-tree|Gruntfuggly|0.0.214|
|trailing-spaces|shardulm94|0.3.1|
|tslint|eg2|1.0.47|
|user-secrets|adrianwilczynski|2.0.1|
|vetur|octref|0.34.1|
|vs-code-xml-format|fabianlauer|0.1.5|
|vscode-counter|uctakeoff|2.3.0|
|vscode-eslint|dbaeumer|2.1.25|
|vscode-express|Compulim|0.0.5|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-pull-request-github|GitHub|0.15.0|
|vscode-theme-darcula|rokoroku|1.2.3|
|vscode-theme-superonedark|seansassenrath|0.0.15|
|vscode-todo-highlight|wayou|1.0.4|
|vscode-todo-plus|fabiospampinato|4.18.4|
|vscode-typescript-tslint-plugin|ms-vscode|1.3.3|
|vsliveshare|ms-vsliveshare|1.0.4836|
|vue|jcbuisson|0.1.5|;

</details>

**Comment by JoeRobich** [comment]
Hi @no-stack-dub-sack, Could you please share the OmniSharp log from the Output pane?

**Comment by no-stack-dub-sack** [comment]
@JoeRobich they're already in the issue template under the **OmniSharp Log** section. This is just a small sample but its mostly the same stuff repeated. Please let me know if you need more than this. Thanks.

**Comment by no-stack-dub-sack** [comment]
@JoeRobich Actually, from looking at these startup logs, I was able to identify the path of both MSBuild instances. By setting the the extension path to the standalone instance, normal behavior has been restored:

```json
{
  "msbuild": {
    "MSBuildExtensionsPath": "c:\\Users\\\\pweinberg\\.vscode\\extensions\\ms-dotnettools.csharp-1.23.15\\.omnisharp\\1.37.15\\.msbuild"
  }
}
```

Out of curiosity, is this behavior expected when updating to newer versions of the .NET SDK and if so is the solution documented anywhere for future reference?

**Comment by JoeRobich** [comment]
@no-stack-dub-sack VS 16.11 should support .NET Core 3.1 and .NET 5 scenarios. You could potentially set the OmniSharp LogLevel to trace to see more detail about what might be failing.

**Comment by no-stack-dub-sack** [comment]
@JoeRobich huh, despite having restarted my machine and VS Code several times over the last few days before reporting this issue, things are working completely normally now. I deleted the `omnisharp.json` file which I pasted above and set the logging level to trace as you suggested to see what might be going on, but now it seems like everything is working so there's no logs worth inspecting at this point 🤷‍♂️ 

Not sure what happened here, but I suppose this can be closed for the time being.

**Comment by JoeRobich** [comment]
> despite having restarted my machine and VS Code several times over the last few days before reporting this issue, things are working completely normally now.

@no-stack-dub-sack Computers, am I right? Glad things are working again. Closing this one out.
