### ISSUE TITLE
`mono` eats up CPU on MacOS

### ISSUE THREAD

**Issue by TanayParikh** [OmniSharp/omnisharp-vscode#4777]
## Issue Description ##
Not sure exactly where to put this (here, VSCode or dotnet/runtime). Mono is absolutely killing my CPU randomly. Don't have anything special running (just [this app](https://github.com/dotnet/aspnetcore/tree/main/src/Components/Samples/BlazorServerApp)) with 2 tabs open. This issue is not specific to that sample app as I've seen it occur randomly in the past as well. 

![image](https://user-images.githubusercontent.com/14852843/133835348-9576827a-5602-48d4-92b6-1608098538b5.png)

I have the `macos` `sample` which I believe is a proc dump to share offline. 

### OmniSharp log ###
<details>
[Logs.txt](https://github.com/OmniSharp/omnisharp-vscode/files/7187660/Logs.txt)
</details>

### C# log ###
<details>Does not show anything</details>

## Environment information ##

**VSCode version**: 1.60.1
**C# Extension**: 1.23.15

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21457.23
 Commit:    7b7148685e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.6
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /Users/tanay/dev/aspnetcore/.dotnet/sdk/6.0.100-rc.2.21457.23/

Host (useful for support):
  Version: 7.0.0-alpha.1.21457.1
  Commit:  7292301fc5

.NET SDKs installed:
  6.0.100-preview.3.21160.5 [/Users/tanay/dev/aspnetcore/.dotnet/sdk]
  6.0.100-preview.3.21168.19 [/Users/tanay/dev/aspnetcore/.dotnet/sdk]
  6.0.100-preview.4.21216.8 [/Users/tanay/dev/aspnetcore/.dotnet/sdk]
  6.0.100-preview.5.21264.3 [/Users/tanay/dev/aspnetcore/.dotnet/sdk]
  6.0.100-preview.7.21324.2 [/Users/tanay/dev/aspnetcore/.dotnet/sdk]
  6.0.100-preview.7.21356.3 [/Users/tanay/dev/aspnetcore/.dotnet/sdk]
  6.0.100-preview.7.21364.4 [/Users/tanay/dev/aspnetcore/.dotnet/sdk]
  6.0.100-rc.1.21401.2 [/Users/tanay/dev/aspnetcore/.dotnet/sdk]
  6.0.100-rc.1.21415.3 [/Users/tanay/dev/aspnetcore/.dotnet/sdk]
  6.0.100-rc.2.21424.34 [/Users/tanay/dev/aspnetcore/.dotnet/sdk]
  6.0.100-rc.2.21430.28 [/Users/tanay/dev/aspnetcore/.dotnet/sdk]
  6.0.100-rc.2.21457.23 [/Users/tanay/dev/aspnetcore/.dotnet/sdk]
  7.0.100-alpha.1.21463.2 [/Users/tanay/dev/aspnetcore/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.13 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-dev [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21158.2 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21168.5 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.4.21215.16 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21263.4 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21322.5 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21355.4 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21363.16 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21381.3 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21413.12 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21420.26 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21430.13 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21455.6 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-alpha.1.21426.33 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-dev [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.27 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21157.6 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21166.1 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21167.1 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.4.21201.1 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.4.21211.7 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.4.21215.2 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.4.21216.6 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21263.1 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21302.1 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21321.15 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21325.1 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21351.2 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21355.1 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21360.10 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21363.9 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21372.1 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21372.4 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21374.7 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21375.2 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21376.24 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21378.2 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21378.9 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21401.1 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21401.3 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21405.1 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21414.4 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21421.1 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21423.6 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21424.25 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21430.13 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21457.6 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21466.4 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-alpha.1.21419.1 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-alpha.1.21425.4 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-alpha.1.21430.29 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-alpha.1.21457.1 [/Users/tanay/dev/aspnetcore/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.9.8|
|csharp|ms-dotnettools|1.23.15|
|EditorConfig|EditorConfig|0.16.4|
|jupyter|ms-toolsai|2021.8.2041215044|
|jupyter-keymap|ms-toolsai|1.0.0|
|markdown-all-in-one|yzhang|3.4.0|
|python|ms-python|2021.9.1230869389|
|vscode-icons|vscode-icons-team|11.6.0|
|vscode-paste-image|mushan|1.0.4|
|vscode-pylance|ms-python|2021.9.1|
|vscode-typescript-tslint-plugin|ms-vscode|1.3.3|;

</details>

**Comment by TanayParikh** [comment]
Here's the process "sample"

[Sample of mono.txt](https://github.com/OmniSharp/omnisharp-vscode/files/7187686/Sample.of.mono.txt)

**Comment by JoeRobich** [comment]
@TanayParikh Can you try the latest omnisharp build by setting `omnisharp.path` to `latest`? I am hoping [this unreleased bug fix](https://github.com/OmniSharp/omnisharp-roslyn/pull/2234) resolves your problem.

**Comment by TanayParikh** [comment]
> @TanayParikh Can you try the latest omnisharp build by setting `omnisharp.path` to `latest`? I am hoping [this unreleased bug fix](https://github.com/OmniSharp/omnisharp-roslyn/pull/2234) resolves your problem.

Updated config, and will update!

**Comment by JoeRobich** [comment]
closing out
