### ISSUE TITLE
Using @ in Razor Page .cshtml in Visual Code

### ISSUE THREAD

**Issue by abdollahkahne** [OmniSharp/omnisharp-vscode#4784]
Issue Type: Feature Request

When I try to use` @{` in Razor Page to switch the context to c#, The IntelliSense feature replace it with `@__o{` which is not Intended. It is the case if you use parenthesis instead of curly brace. It would be great to resolve this.
Thanks in advance

VS Code version: Code 1.60.1
OS version: Linux x64 5.11.0-34-generic
Restricted Mode: No

**Comment by JoeRobich** [comment]
@ryanbrandenburg Have you seen this before?

**Comment by JoeRobich** [comment]
Closing. This appears to be a duplicate of https://github.com/dotnet/aspnetcore/issues/35601
