### ISSUE TITLE
Respectively change the value of the variable in the "WATCH" and "DEBUG CONSOLE" operated, can not be fully synchronized.

### ISSUE THREAD

**Issue by JiuzhouLulu** [OmniSharp/omnisharp-vscode#479]
## Environment data
`dotnet --info` output:
 VS Code version:1.2.1
 C# Extension version:1.1.7
VS Code version:
        public HomeController(IOptions<AppSettings> options)
        {
            int a=3,b=3;
            int c=a*b;
            _appSettings = options.Value;
        }
C# Extension version:

## Steps to reproduce
1.Set a breakpoint in "int c = a * c" at, hit F5 to start debugging.
2.In the "DEBUG CONSOLE" Console manually modify a = 1, b = 4; In the "WATCH" console manually 
   modify a = 2.
3.Repeatedly modified 'a' value in the "DEBUG CONSOLE" observe the 'a' value in "WATCH" .
## Expected  behavior
The "DEBUG CONSOLE" and the "WATCH" value of console variables are consistent, changing the value of one variable, the other party also changed, they are synchronized.
## Actual behavior
If the "WATCH" determined that the variable value, "DEBUG CONSOLE" change the variable value is invalid and can not be synchronized.

**Comment by wesrupert** [comment]
This is an issue with VS Code, as it currently doesn't ask for updated values after expression evaluation. Please see [VS Code issue #8118](https://github.com/Microsoft/vscode/issues/8118). Once this functionality is fixed in VS Code, it should work here.
