### ISSUE TITLE
debugger: Error processing 'configurationDone' request. The system cannot find the file specified.

### ISSUE THREAD

**Issue by DianaGiulietti** [OmniSharp/omnisharp-vscode#4791]
## Issue Description ##

Receiving "Error processing 'configurationDone' request. The system cannot find the file specified." error when running the dotnet debugger.

## Steps to Reproduce ##

Fresh installation of vscode from the vscode website for macOS. Installed c# extension. I've set `omnisharp.useGlobalMono` to `never`. 

Using tutorial code located here: https://docs.microsoft.com/en-us/dotnet/core/tutorials/debugging-with-visual-studio-code
Set a line break at line 12 just like the example. 

task.json was generated with:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/helloworld.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "publish",
            "command": "dotnet",
            "type": "process",
            "args": [
                "publish",
                "${workspaceFolder}/helloworld.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "watch",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "run",
                "${workspaceFolder}/helloworld.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        }
    ]
}
```

launch.json:
```
{
    "version": "0.2.0",
    "configurations": [

        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "<REDACTED>/helloworld.csproj",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "console": "integratedTerminal",
            "logging": {
                "engineLogging": true
            }
        }
    ]
}
```

## Logs ##

only failure from the debugger log is:
```
-> (C) {"command":"configurationDone","type":"request","seq":7}
<- (E) {"seq":9,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/LaunchFailed","data":{"VS.Diagnostics.Debugger.vsdbg.Distribution.Version":"20.4.0","VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"Darwin","VS.Diagnostics.Debugger.vsdbg.Version":"17.0.10712.2 commit:70a83505117741ba30f92c713a4bb0d0395c3197","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Darwin","VS.Diagnostics.Debugger.vsdbg.ErrorCode":-2147024894}}}
<- (R) {"seq":10,"type":"response","request_seq":7,"success":false,"command":"configurationDone","message":"Error processing 'configurationDone' request. The system cannot find the file specified."}
```

## Environment information ##

**VSCode version**: 1.60.2
**C# Extension**: 1.23.15

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.401
 Commit:    4bef5f3dbf

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.401/

Host (useful for support):
  Version: 5.0.10
  Commit:  e1825b4928

.NET SDKs installed:
  5.0.401 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.15|
|jupyter|ms-toolsai|2021.8.2041215044|
|jupyter-keymap|ms-toolsai|1.0.0|
|python|ms-python|2021.9.1246542782|
|vscode-pylance|ms-python|2021.9.4|;

</details>

**Comment by gregg-miskelly** [comment]
In your launch.json, this is not correct: `"program": "<REDACTED>/helloworld.csproj",`. This should be the path to the .dll that your project built.

**Comment by gregg-miskelly** [comment]
BTW: The C# extension can generate a launch.json for you. Hopefully you see set #2 from https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code#enhance-the-app. If you aren't seeing the prompt:
1. If you have a launch.json already, delete it
2. View->Command Pallette
3. Run: .NET: Generate Assets for Build and Debug

**Comment by DianaGiulietti** [comment]
Oh that's embarrassing. I thought I had reset everything by having the C# extension generate a launch.json for me. I was having trouble getting the prompt to pop up, so I appreciate the manual process. Will close this out. Thanks.
