### ISSUE TITLE
Debugger:variable of local window won't be change while changing variable in watch window

### ISSUE THREAD

**Issue by Serena01** [OmniSharp/omnisharp-vscode#480]
## Environment data
`dotnet --info` output:
VS Code version:1.2.1
C# Extension version:1.1.7

## Steps to reproduce
1.Download and launch the sample project from https://github.com/OmniSharp/omnisharp-vscode/files/336372/musicstore.zip 
2.Select ".NET Core Launch Web" and configure the location of musicstore.dll for "program which contains the space at the end as following: "program": "${workspaceRoot}/bin/Debug/netcoreapp1.0/musicstore.dll ",
3.Add some simple code in HomeController.cs, then set bp as bellow:
 HomeController(IOptions<AppSettings> options){
   int a=1;
   int  b=20;//set Breakpoint here
   int c=a+1;
}
4.F5, add variable "a" in watch window , then wait VS hit BP
5.Change variable a=10 in watch window, and click "Enter".

## Expected  behavior
variable "a" value should be 10 in local window

## Actual behavior
variable "a" value is 1 in local window

**Comment by wesrupert** [comment]
This is an issue with VS Code, as it currently doesn't ask for updated values after expression evaluation. Please see [VS Code issue #8118](https://github.com/Microsoft/vscode/issues/8118). Once this functionality is fixed in VS Code, it should work here.
