### ISSUE TITLE
"Accept changes" bar slow to appear, not clickable for some time

### ISSUE THREAD

**Issue by cdonnellytx** [OmniSharp/omnisharp-vscode#4800]
Issue Type: <b>Bug</b>

While solving merge conflicts in VSCode with C# enabled.

Possibly related to https://github.com/OmniSharp/omnisharp-vscode/issues/2076.

Extension version: 1.23.15
VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.82GB (42.73GB free)|
|Process Argv|. --crash-reporter-id 865f3002-55e1-4f1a-a893-f1b432b691bd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30378365
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis200:30374795
vsaa593cf:30376535

```

</details>

**Comment by nohwnd** [comment]
When exactly does this happen? Is that every time you open the file, or only after you just started VSCode? It might be that some other extension is blocking the git features from starting up, because the extension takes a long time to activate.

You can also `code --prof-startup` to profile the startup. Thanks @JoeRobich for the tip!
