### ISSUE TITLE
Debugger: Function breakpoint cannot be hit

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#481]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Steps to reproduce
1 In breakpoints window of VSCode, click button to add a new function breakpoint
2 Input "HomeController" in that text pane
3 Press F5 to start debugging

## Expected  behavior
HomeController constructor should be hit

## Actual behavior
That function breakpoint cannot be hit

**Comment by gregg-miskelly** [comment]
Duplicate of #295
