### ISSUE TITLE
console attribute of launch.json has no effect (and internalConsole is broken)

### ISSUE THREAD

**Issue by triaxx** [OmniSharp/omnisharp-vscode#4814]
## Environment data
`dotnet --info` output:
.NET SDK (reflecting any global.json):
 Version:   5.0.205
 Commit:    64a0cf25eb

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.205/

Host (useful for support):
  Version: 5.0.8
  Commit:  42ac4d6d5a

.NET SDKs installed:
  5.0.205 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
VS Code version: 1.61.0
C# Extension version: 1.23.16

## OmniSharp log
Starting OmniSharp server at 12/10/2021, 15:02:07
    Target: /home/triaxx/devel/c#/algopoo-a2-2021/td01

OmniSharp server started.
    Path: /home/triaxx/.vscode-oss/extensions/muhammad-sammy.csharp-1.23.15/.omnisharp/1.37.15/run
    PID: 105782

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on arch 0.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 17.0.0 - "/home/triaxx/.vscode-oss/extensions/muhammad-sammy.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/triaxx/.vscode-oss/extensions/muhammad-sammy.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 17.0.0 - "/home/triaxx/.vscode-oss/extensions/muhammad-sammy.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/triaxx/.vscode-oss/extensions/muhammad-sammy.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/triaxx/.vscode-oss/extensions/muhammad-sammy.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/triaxx/.vscode-oss/extensions/muhammad-sammy.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/triaxx/devel/c#/algopoo-a2-2021/td01'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/triaxx/devel/c#/algopoo-a2-2021/td01'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/triaxx/devel/c#/algopoo-a2-2021/td01/td01.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/triaxx/devel/c#/algopoo-a2-2021/td01'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/triaxx/devel/c#/algopoo-a2-2021/td01' on host 105678.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/triaxx/devel/c#/algopoo-a2-2021/td01/td01.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/triaxx/devel/c#/algopoo-a2-2021/td01/td01.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/triaxx/devel/c#/algopoo-a2-2021/td01/td01.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: td01
Received response for /v2/getcodeactions but could not find request.

## Expected  behavior
I set console attribute to both integratedTerminal and externalTerminal in launch.json. I would like to not use the internalConsole (that is broken for input).

## Actual behavior
No matter the value of console, the (broken) debug console is always used to launch the program.

**Comment by gregg-miskelly** [comment]
@triaxx You are not using this extension -- you are using something called `muhammad-sammy.csharp-1.23.15`. My guess is this is because you are using the OSS version of VS Code which doesn't support the debugger in this extension. If you want to use this extension with the debugger you would need to install the official Microsoft version of VS Code and the official C# extension.
