### ISSUE TITLE
The omnisharp.enableDecompilationSupport  setting doesn't enable decompilation

### ISSUE THREAD

**Issue by cateyes99** [OmniSharp/omnisharp-vscode#4817]
**VSCode version**: 1.60.2
**C# Extension**: 1.23.16

## Steps to reproduce
Set the `omnisharp.enableDecompilationSupport` to **true** in **VSCode**'s **settings.json**.

## Expected  behavior
F12 (**_Go to Definition_**) should navigate to the decompiled the source code.

## Actual behavior
It doesn't, but just navigates to metadata. So `omnisharp.enableDecompilationSupport` looks like having no effect.

Look like, leave this setting with its default value, i.e., `omnisharp.enableDecompilationSupport = false`, but [adding the below settings into the file `%USERPROFILE%/.omnisharp/omnisharp.json`](https://www.strathweb.com/2020/05/decompilation-support-in-omnisharp-and-c-extension-for-vs-code)
```json
    "RoslynExtensionsOptions": {
        "enableDecompilationSupport": true
    }
```
will just enable the decompilation feature.

**Comment by filipw** [comment]
Oh I think I know what you mean now. This works fine when decompilation agreement is accepted in the current workspace. But the decompilation agreement is not shown anymore on subsequent starts of the VS Code and the decompilation consent is not persisted across starts, making the whole thing behave as if decompilation was off.

@JoeRobich @nohwnd  looks like this change (?) broke this https://github.com/OmniSharp/omnisharp-vscode/pull/4760? would you mind checking whether the consent is persisted correctly across VS Code starts

**Comment by JoeRobich** [comment]
@cateyes99 Thanks for reporting. Once the fix merges I'll make a prerelease build that you can install. Will likely wait until next week for a new release to see if any other issues are reported.

**Comment by karl-gardner** [comment]
@cateyes99 @JoeRobich 
After reading this I cannot find the command for "CSharp: Show the decompiler terms agreement". Would I enter this in the command palette in vscode:

![image](https://github.com/dotnet/vscode-csharp/assets/91646805/c837906e-a8e0-448d-ad4d-62a26cabcee3)

As you can see in the image I can't see any command that matches that.
