### ISSUE TITLE
Debugger: "justMyCode" option should be existed in launch.json by default

### ISSUE THREAD

**Issue by Serena01** [OmniSharp/omnisharp-vscode#482]
## Environment data
`dotnet --info` output:
VS Code version:1.2.1
C# Extension version:1.1.7

## Steps to reproduce
Download and launch the sample project from https://github.com/OmniSharp/omnisharp-vscode/files/336372/musicstore.zip 
2.Select ".NET Core Launch Web" and configure the location of musicstore.dll for "program which contains the space at the end as following: "program": "${workspaceRoot}/bin/Debug/netcoreapp1.0/musicstore.dll ",
3.Open launch.json

## Expected  behavior
"justMyCode" should be exist in launch.json

## Actual behavior
There is no :"justMyCode" option in launch.json

**Comment by caslan** [comment]
This is by design. To keep the launch.json file minimal, we don't display the setting and use the default value for the setting. You should see "justMyCode" in intellisense if you try to add it to the file with its default value of true.
