### ISSUE TITLE
Debugger: Input box for function breakpoint will stay in breakpoints window and not disappeared

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#483]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Steps to reproduce
1 In breakpoints window of VSCode, click button to add a new function breakpoint
2 Input "HomeController" in that text pane then press Enter

## Expected  behavior
Input box should disappear at once 

## Actual behavior
Input box can't disappear and the newly input function breakpoint couldn't be added in to the lists in breakpoints window at once

**Comment by gregg-miskelly** [comment]
Hi @GraceDong any UI bugs should be opened in http://github.com/Microsoft/vscode/issues. For this one, the C# extension doesn't support function breakpoints. So I would guess that is why you are seeing this. But you can certainly ask the VS Code team.
