### ISSUE TITLE
Debugger: Setting variable's value in watch window before debug session should not affect that variable

### ISSUE THREAD

**Issue by ClaireKang** [OmniSharp/omnisharp-vscode#484]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Steps to reproduce
1.  Add expression of cacheKey = "Hello" in watch window before setting breakpoint
2. Setting breakpoint in  var cacheKey = "topselling "
3.  Press F5 to start debugging
4.  Press F10 twice to step over
5.  Observe the data tip of cacheKey  in local window.

## Expected  behavior
CacheKey's data tip shoule be raw data "topselling" 

## Actual behavior
Local window's data tip of cacheKey is "Hello"

**Comment by wesrupert** [comment]
Expressions in the watch window are evaluated after stopping at every breakpoint/step command/async break in VS Code. This is the expected behavior, VS Code has no concept of stale/manual reevaluation for locals or watch expressions.
