### ISSUE TITLE
Debugger: The messages are duplicate in data tip

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#485]
## Environment data

`dotnet --info` output:
VS Code version:
C# Extension version:
## Steps to reproduce

1 Insert an expression “int a=10;” in HomeController function 
2 move the mouse on variable a to show data tip
## Expected  behavior

Data tip should not display the duplicate message
## Actual behavior

The messages are duplicate in data tip

**Comment by chuckries** [comment]
@GraceDong Can you get a screenshot of this behavior? It would be very helpful.

**Comment by GraceDong** [comment]
Hi Chuck,

Thanks  for your following up on this. Here’s the screenshot(please see attachment for details)
[cid:image002.png@01D1D1EB.ACE8C230]

Best Regards,

Grace

**Comment by chuckries** [comment]
@GraceDong unfortunately sending the screenshot in the email didn't work, you will have to paste it directly into github. Can you provide more detailed repro steps? Where are you stopped? What are you seeing in the data tip?

**Comment by GraceDong** [comment]
@chuckries I‘m sorry, the screenshot didn't work and I updated the screenshot as below.
Steps to reproduce:
1 Open the MusicStore app in VSCode
2 Write an expression “int a=10;” in front of  "_appSettings = options.Value;" in HomeController.cs
3 Move the mouse on variable "a" to show data tip
4 Observe the content of the data tip

![datatip](https://cloud.githubusercontent.com/assets/20184778/16549385/77d18414-41d1-11e6-99cf-fa4a1c37e140.png)

**Comment by gregg-miskelly** [comment]
@GraceDong. I see. That isn't a data tip. @DustinCampbell does this sound like a language service bug? Or should we open this in VS Code for displaying build warnings when debugging?

**Comment by DustinCampbell** [comment]
It's probably not coming from the build. It's probably just a diagnostic coming from OmniSharp. Diagnostics are displayed during edit-time as well as compile-time. Showing duplicates is definitely a bug though.

**Comment by chuckries** [comment]
@DustinCampbell @gregg-miskelly If that's the case I'm going to change the debugger label to Omnisharp and assign to Dustin.

**Comment by DustinCampbell** [comment]
This should have been fixed long ago.
