### ISSUE TITLE
missing a using directive or an assembly reference

### ISSUE THREAD

**Issue by Califkidd** [OmniSharp/omnisharp-vscode#4864]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

**Comment by Califkidd** [comment]
When running C#, using System.Collections, receive error: 

Program.cs(14,10): error CS0246: The type or namespace name 'Hashtable' could not be found (are you missing a using directive or an assembly reference?) [C:\wamp64.3.2.3\www\knowledge\Library\EMPLOYMENT\REVATURE\20210927-COURSE\C-Sharp\hashTable\hashTable.csproj]

Program.cs(14,29): error CS0246: The type or namespace name 'Hashtable' could not be found (are you missing a using directive or an assembly reference?) [C:\wamp64.3.2.3\www\knowledge\Library\EMPLOYMENT\REVATURE\20210927-COURSE\C-Sharp\hashTable\hashTable.csproj]

Can you please provide a solution.

**Comment by Blokyk** [comment]
Judging by that file path and how recent your profile is, I'm guessing you're still a beginner in C# and/or are taking a course teaching it. Therefore, you should first ask whoever your teacher/instructor is, and then search on google/stackoverflow for problems similar to your own. If you're still having issues with it, I'd very strongly encourage you to join the [official C# discord](https://discord.gg/csharp), you'll find many great ressources and people willing to help you.

As for specific error, you probably just forgot `using System.Collections;` at the top of your file ; if that's not it it's probably a problem with your setup/sdk installation

**Comment by filipw** [comment]
Unfortunately this is not actionable. If you have a problem with the extension, please open an issue where you provide all the data requested by the issue template. Thanks.
