### ISSUE TITLE
OmniSharp took 2 seconds  to response. Is that normal?

### ISSUE THREAD

**Issue by papperock** [OmniSharp/omnisharp-vscode#4865]
`[fail]: OmniSharp.Stdio.Host
        ************  Response (1.8994ms) ************ 
{
  "Request_seq": 1610,
  "Command": "/filesChanged",
  "Running": true,
  "Success": false,
  "Message": "\"System.IO.IOException: The process cannot access the file 'c:\\\\Users\\\\owen\\\\Desktop\\\\FirstC\\\\Program.cs' because it is being used by another process.\\r\\n   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\\r\\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\\r\\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\\r\\n   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)\\r\\n   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)\\r\\n   at OmniSharp.Roslyn.BufferManager.<UpdateBufferAsync>d__8.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn\\\\BufferManager.cs:line 47\"",
  "Body": null,
  "Seq": 9623,
  "Type": "response"
}
Received response for /quickinfo but could not find request.
`

**Comment by filipw** [comment]
These logs are in milliseconds - it's not 1.89 second, but 1.89 ms. https://github.com/OmniSharp/omnisharp-roslyn/blob/da1e65b1e2badf80adc7db8ccd37e4cf253ca7b2/src/OmniSharp.Stdio/Host.cs#L280
