### ISSUE TITLE
how debug source code with net6.0 instend of net5.0?

### ISSUE THREAD

**Issue by newpost** [OmniSharp/omnisharp-vscode#4870]
error description
C:\Program Files\dotnet\sdk\5.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045:

**Comment by JoeRobich** [comment]
Hi @newpost, could you please include more details about the problem you are running into? From the error it seems that you have the NET 5.0 SDK installed but are trying to work with a net6.0 project. You can install the .NET 6.0 RC2 SDK from https://dotnet.microsoft.com/download/dotnet/6.0

**Comment by newpost** [comment]
@JoeRobich Do I need to set net6.0 environment variables？ [manually-install](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net50#download-and-manually-install)

**Comment by JoeRobich** [comment]
@newpost I believe so. If you have multiple SDKs installed in different locations, you may want to ensure the 6.0 SDK location appears first in the PATH variable.
