### ISSUE TITLE
Omnisharp still appearing in VSCode but doesn't work, even tried restarting, uninstalling C# extensions etc ...

### ISSUE THREAD

**Issue by TKNguyen12a9** [OmniSharp/omnisharp-vscode#4873]
## Environment data
C# Extension version: 1.23.16
VSCode version:  1.61.2

`dotnet --info` output:
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.301     
 Commit:    ef17233f86  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.19043
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

## Steps to reproduce
Omnisharp was fine, But it still slow a little bit after I open VSCode, and need to restart it or select project to get it work. However today I open it and it didn't work anymore.

What I tried are:
-  `Ctrl + shift + p` select `omnisharp` from the dropdown list and choose restarting, selecting project.
-  Uninstaling and reinstalling, disabled and enabled C# extensions etc.
- Also tried reinstalling another version of `omnisharp`, the installing process was WELL.

All of them didn't worked! Plus that omnisharp is still appearing in the dropdown list when I `Ctrl + shift + p`, but the logo in the bottom left was totally disappeared.

## Expected  behavior
C# Intellisence working again and logo of `omnisharp` appearing like it was.

**Comment by TKNguyen12a9** [comment]
![omnisharp_issues](https://user-images.githubusercontent.com/48620639/140174391-4c156db0-2c71-4cf3-96be-fdd7e13d1a0e.png)
This is `Omnisharp` log when I tried reinstalling another version from 1.23.16 (current) to 1.23.15.

**Comment by JoeRobich** [comment]
@TKNguyen12a9 From the Output pane dropdown can you choose OmniSharp and share that log?

**Comment by TKNguyen12a9** [comment]
@JoeRobich It logs:
`Getting latest OmniSharp version information`
`Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!`

**Comment by JoeRobich** [comment]
@TKNguyen12a9 Sorry, the log you are sharing is the C# log. There should be a separate entry for OmniSharp in the dropdown.

**Comment by TKNguyen12a9** [comment]
Sorry, but do you mean this dropdow
![omnisharp_logs](https://user-images.githubusercontent.com/48620639/140176387-9a6215d2-406b-4e14-94ae-7a4f83ada2a3.png)
n?

**Comment by JoeRobich** [comment]
The ENOENT error has been reported before in https://github.com/OmniSharp/omnisharp-vscode/issues/3908. Can you check your PATH environment variable and ensure that it contains `C:\Windows\System32`?

**Comment by TKNguyen12a9** [comment]
@JoeRobich I just checked that solution and omnisharp worked again. Thank you!
