### ISSUE TITLE
Suggestion: support Samsung/netcoredbg as an open source alternative 

### ISSUE THREAD

**Issue by Banyc** [OmniSharp/omnisharp-vscode#4875]
This is not a bug report, thus I didn't follow the template. Sorry about that in advance.

`Samsung/netcoredbg` (https://github.com/Samsung/netcoredbg) is open-source licensed with MIT, but MS's vsdbg is closed-source for some reasons.

```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
```

How about providing an alternative to the debugger in case some **funny incidents** happen **AGAIN**?

**Comment by gregg-miskelly** [comment]
The community has already provided this with https://github.com/muhammadsammy/free-omnisharp-vscode
