### ISSUE TITLE
Cannot set launchSettingsProfile

### ISSUE THREAD

**Issue by aforslow** [OmniSharp/omnisharp-vscode#4879]
## Issue Description ##
As the title says, I can't set the launchSettingsProfile variable in launch.json. Or rather, it doesn't work as [mentioned in the docs](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#launchsettingsjson-support). I don't even get a suggestion from the text editor that this option is available.

## Steps to Reproduce ##
Provide the "launchSettingsProfile" option in launch.json and run debug.

## Expected Behavior ##
The specified launch profile is launched.

## Actual Behavior ##
The default launch profile is always launched.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.61.2
**C# Extension**: 1.23.16

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.402
 Commit:    e9d3381880

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.402/

Host (useful for support):
  Version: 5.0.11
  Commit:  f431858f8b

.NET SDKs installed:
  5.0.402 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.16|
|dotnet|leo-labs|1.3.0|;

</details>

**Comment by gregg-miskelly** [comment]
This is because you are looking at the documentation for a new feature that isn't out yet. See [instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) if you want to install a beta release.
