### ISSUE TITLE
After changing Display Language to `en`, the refactor options still do appear in non-english

### ISSUE THREAD

**Issue by Swiftly1** [OmniSharp/omnisharp-vscode#4883]
Accidentally I've agreed to install Polish language when VS Code asked me about it and now

even after switching to `en`, then

![obraz](https://user-images.githubusercontent.com/77643169/141022509-aff39ce0-56e4-43a8-9e42-f61bca2f236f.png)

I receive mixed: English and Polish hints.

![obraz](https://user-images.githubusercontent.com/77643169/141022533-56b3e8d0-2868-4e1d-a4df-96f83d789c15.png)

I have Roslynator installed

edit: even with Roslynator disabled it does happen

![obraz](https://user-images.githubusercontent.com/77643169/141023402-b733843a-0245-4ccc-b111-b7315889561f.png)

	More Info:

	Released on 13.08.2019, 19:21:08
	Last updated 15.08.2021, 23:03:56
	Identifier josefpihrt-vscode.roslynator

	C# for Visual Studio Code (powered by OmniSharp).
	Released on 26.02.2016, 17:20:58
	Last updated 12.10.2021, 12:35:03
	Identifier ms-dotnettools.csharp

	dotnet --version
	6.0.100-preview.4.21255.9

	dotnet --info
	Zestaw .NET SDK (odzwierciedlenie dowolnego pliku global.json):
	 Version:   6.0.100-preview.4.21255.9
	 Commit:    950e4949a7

	Środowisko uruchomieniowe:
	 OS Name:     Windows
	 OS Version:  10.0.19042
	 OS Platform: Windows
	 RID:         win10-x64
	 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\

	Host (useful for support):
	  Version: 6.0.0-preview.4.21253.7
	  Commit:  bfd6048a60

	.NET SDKs installed:
	  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]
	  5.0.402 [C:\Program Files\dotnet\sdk]
	  6.0.100-preview.4.21255.9 [C:\Program Files\dotnet\sdk]

**Comment by JoeRobich** [comment]
@Swiftly1 Sorry this isn't the expected behavior. This issue is being tracked by https://github.com/OmniSharp/omnisharp-vscode/issues/2513
