### ISSUE TITLE
.NET Core Attach fails to run on Windows 11

### ISSUE THREAD

**Issue by LeNitrous** [OmniSharp/omnisharp-vscode#4885]
## Issue Description ##
Despite what .NET reports, I am on Windows 11 Pro Insiders (Dev Channel) Build 22494.rs_prerelease.211029-1421. I've read articles about Microsoft deprecating `wmic` in favor of the new commands usable in Powershell.

This is further enforced by the fact that `%SystemRoot%/System32/wmic.exe` does not exist anymore in my installation.

## Steps to Reproduce ##
1. Create a `launch.json` with the following configuration
```json
{
    "name": ".NET Core Attach",
    "type": "coreclr",
    "request": "attach"
}
```
2. Select the configuration and run.
3. Error displays immediately.

## Expected Behavior ##
- A window listing all processes that can be attached to.

## Actual Behavior ##
- A dialog box showing this:
![image](https://user-images.githubusercontent.com/20495991/141071519-03e200f4-40c0-4dff-80a3-a1a4e6162587.png)

## Environment information ##

**VSCode version**: 1.62.0
**C# Extension**: 1.23.16

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21505.57
 Commit:    ab39070116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22494
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  5.0.402 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|1.7.1|
|csharp|ms-dotnettools|1.23.16|
|dart-code|Dart-Code|3.28.0|
|EditorConfig|EditorConfig|0.16.4|
|errorlens|usernamehw|3.4.0|
|flutter|Dart-Code|3.28.0|
|gitlens|eamodio|11.6.1|
|hexeditor|ms-vscode|1.8.2|
|jupyter|ms-toolsai|2021.10.1001414422|
|jupyter-keymap|ms-toolsai|1.0.0|
|jupyter-renderers|ms-toolsai|1.0.3|
|material-icon-theme|PKief|4.10.0|
|msbuild-project-tools|tintoy|0.3.15|
|psi-header|psioniq|1.15.2|
|python|ms-python|2021.11.1422169775|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-pylance|ms-python|2021.11.0|
|vscode-solution-explorer|fernandoescolar|0.4.4|
|vscode-tailwindcss|bradlc|0.7.2|
|vscord|LeonardSSH|4.1.6|;

</details>

**Comment by WardenGnaw** [comment]
This was solved in: https://github.com/OmniSharp/omnisharp-vscode/pull/4848

You can try out the pre-release [1.23.17](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.17) that has these changes.
