### ISSUE TITLE
Colours only applied to Class's second method and forward when using NetCore 6 File-scoped namespace

### ISSUE THREAD

**Issue by mdmoura** [OmniSharp/omnisharp-vscode#4889]
I am using Net Core 6 and Omnisharp 1.23.16 and in a .CS file I am using File-scoped namespace.

The project compiles but the different colours are only applied to the Class's second method and forward:

<img width="834" alt="Screenshot 2021-11-12 at 12 45 18" src="https://user-images.githubusercontent.com/372865/141470127-e8e506a0-456d-478b-b69c-3ac950bae9f5.png">

Any idea why this happens? Is this a bug?

## Environment data

Omnisharp version: 1.23.16

.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.0
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by filipw** [comment]
see https://github.com/OmniSharp/omnisharp-vscode/issues/4884#issuecomment-965652712
