### ISSUE TITLE
Debugger: '\r\n' doesn't perform line feed operations

### ISSUE THREAD

**Issue by xdhywj** [OmniSharp/omnisharp-vscode#489]
## Environment data
`dotnet --info` output:
VS Code version: 1.2.1
C# Extension version: 1.1.7

## Steps to reproduce
1. Select 'All Exceptions' in Breakpoints window.
2. Add following code and execute them.

                List<int> list=new List<int>();
                for(int i=0;i<10;i++)
                {
                    list.Add(i);
                }
                int b=list[10]+1;
3. When it is in break mode, please pay attention to the value of '$exception' in Locals window.

## Expected  behavior
It should have a line feed at string "\r\n".

## Actual behavior
There're many "\r\n" in the value of '$exception', perhaps we should use "\n" here?

![screenshot when issue occured](https://cloud.githubusercontent.com/assets/10482819/16439268/8e4ccd12-3d6b-11e6-8989-a1d950bcb677.png)

**Comment by gregg-miskelly** [comment]
The CLR/CoreFX is what is going to decide what this string looks like. The debugger just shows it. This seems pretty 'by design' to me.
