### ISSUE TITLE
Incorrect Syntax Highlighting for Integer Extension Methods

### ISSUE THREAD

**Issue by PixelatedLagg** [OmniSharp/omnisharp-vscode#4895]
![image_2021-11-15_232154](https://user-images.githubusercontent.com/81400034/141914054-8dcbb90f-bfa8-4d65-ac2b-ac05e02c5fca.png)
In the screenshot, an extension method I made for a string and integer are invoked, however the string highlights the method, while the integer doesn't. I am assuming the syntax highlighter thinks I am creating a numerical value with a decimal point and an invalid word afterwards, hence the white.

**Comment by JoeRobich** [comment]
@PixelatedLagg This looks like an issue with the C# textmate grammar that lives in a separate repo https://github.com/dotnet/csharp-tmLanguage/issues. if you set "csharp.semanticHighlight.enabled" to "true" in settings you will enable our semantic highlighting which provides a better experience although is still experimental.
