### ISSUE TITLE
File scope namespaces first item syntax highlighting not working

### ISSUE THREAD

**Issue by nameOfUser0236** [OmniSharp/omnisharp-vscode#4906]
## Issue Description ##
In files with file scoped namespaces, the first members of the first type in that file are not syntax highlighted.
Only after (not including) the first function of property is there syntax highlighting.
## Steps to Reproduce ##
1. Create dotnet6 project from cli
2. Create a file with the following contents
```c#
namespace MyNamespace;

public class MyClass
{
	int x;
	int Size2 { get; }
	int Size { get; }
	int y;
}
```
3. Look
## Expected Behavior ##
Syntax highlighting on the entire file
## Actual Behavior ##
![Screenshot 2021-11-21 125931](https://user-images.githubusercontent.com/61810409/142775366-c8f407df-2b79-408c-9079-a372df12a12e.png)

### OmniSharp log ###
<details>Starting OmniSharp server at 11/21/2021, 12:39:36 PM
    Target: f:\Repos\temp\c#extension

OmniSharp server started.
    Path: c:\Users\user\.vscode\extensions\ms-dotnettools.csharp-1.23.16\.omnisharp\1.37.16\OmniSharp.exe
    PID: 13560

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 17.0.0 - "c:\Users\user\.vscode\extensions\ms-dotnettools.csharp-1.23.16\.omnisharp\1.37.16\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\user\.vscode\extensions\ms-dotnettools.csharp-1.23.16\.omnisharp\1.37.16\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 17.0.0 - "c:\Users\user\.vscode\extensions\ms-dotnettools.csharp-1.23.16\.omnisharp\1.37.16\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\user\.vscode\extensions\ms-dotnettools.csharp-1.23.16\.omnisharp\1.37.16\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\user\.vscode\extensions\ms-dotnettools.csharp-1.23.16\.omnisharp\1.37.16\.msbuild
            MSBuildToolsPath = c:\Users\user\.vscode\extensions\ms-dotnettools.csharp-1.23.16\.omnisharp\1.37.16\.msbuild\Current\Bin
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'f:\Repos\temp\c#extension'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'f:\Repos\temp\c#extension'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'f:\Repos\temp\c#extension\c#extension.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'f:\Repos\temp\c#extension'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'f:\Repos\temp\c#extension' on host 16012.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: f:\Repos\temp\c#extension\c#extension.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'f:\Repos\temp\c#extension\c#extension.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'f:\Repos\temp\c#extension\c#extension.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: c#extension
</details>

### C# log ###
<details></details>

## Environment information ##

**VSCode version**: 1.62.3
**C# Extension**: 1.23.16

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.16|;
</details>

**Comment by filipw** [comment]
see https://github.com/OmniSharp/omnisharp-vscode/issues/4884#issuecomment-965652712

**Comment by nameOfUser0236** [comment]
Thanks, will these settings be made default?
