### ISSUE TITLE
Cannot select project with omnisharp because of quickPickSeparators

### ISSUE THREAD

**Issue by jeffhollan** [OmniSharp/omnisharp-vscode#4907]
Issue Type: <b>Bug</b>

I'm using the insider build, at first I thought this was because of one machine, but now I have the same behavior on my Mac M1 and my Windows 11 device. Whenever I try to select a project I get the below.

> Command 'OmniSharp: Select Project' resulted in an error (Extension 'ms-dotnettools.csharp' CANNOT use API proposal: quickPickSeparators.
Its package.json#enabledApiProposals-property declares: [] but NOT quickPickSeparators.
The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-dotnettools.csharp)

Extension version: 1.23.16
VS Code version: Code - Insiders 1.63.0-insider (Universal) (1e473b624f088fc05269891170a8ffa1c84a35a6, 2021-11-25T07:59:08.754Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 3|
|Memory (System)|64.00GB (16.10GB free)|
|Process Argv|. --crash-reporter-id a3331069-8570-41bd-a870-a2bc43c4f676|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593:30376534
vsc1dst:30396469
pythonvs932:30404738
vscexrecpromptt2:30397559
vscop804cf:30404767
vs360:30404995

```

</details>

**Comment by jeffhollan** [comment]
as an FYI on both of these I have .NET installed already and in the path

dotnet --list-sdks
6.0.100 [/usr/local/share/dotnet/sdk]

**Comment by microdee** [comment]
same happening for me on windows with .NET 5

**Comment by ddjerqq** [comment]
im having same issue, anyone got solution?

**Comment by stevef51** [comment]
I too have just discovered this - this is more than painful, I have a MBPro with 64GB RAM (ie plenty) and a large Git repo with 10 or so .NET (Core) 5 projects each with their own Dev Containers - I was mounting my sourcecode from the Mac host into the dev containers, however I think the OSX host mount driver was too slow and caused endless issues with OmniSharp timing out and basically meant Intellisense was almost always broken (ie shows "Loading..." tooltip and never returns) - so I went to the trouble of creating Dev Containers with no host mount, ie the Dev Container would Git fetch into a standard Docker volume sidestepping the host volume driver altogether - this seems mostly to work, but I still find I have to occasionally perform an "OmniSharp Select Project" to get Intellisense working - but now with this new error I have no intellisense at all

**Comment by jesperkristensen** [comment]
Does anyone know how to install an old working version until a fix is released? My VS Code is basically bricked now.

**Comment by DiomedesDominguez** [comment]
In my case my problem was fixed by looking at the sln file and checking that every project was referenced correctly: correct path and name. After that, a simple restart of the VSCode was enough.

**Comment by EternalQuasar0206** [comment]
> In my case my problem was fixed by looking at the sln file and checking that every project was referenced correctly: correct path and name. After that, a simple restart of the VSCode was enough.

I dont even have a solution file, your comment is useless

**Comment by DiomedesDominguez** [comment]
> > In my case my problem was fixed by looking at the sln file and checking that every project was referenced correctly: correct path and name. After that, a simple restart of the VSCode was enough.
> 
> I dont even have a solution file, your comment is useless

Sorry for bother you, I came to this issue a few hours ago, managed to resolve it and wanted to share my findings. Check in your .csproj files for inconsistences regarding other projects references. 

The omnisharp have a several weeks since the last release, so maybe the problem is in the VSCode. To test this you can create a new project in a clean folder and watch if the message persists.

**Comment by EternalQuasar0206** [comment]
> > > In my case my problem was fixed by looking at the sln file and checking that every project was referenced correctly: correct path and name. After that, a simple restart of the VSCode was enough.
> > 
> > 
> > I dont even have a solution file, your comment is useless
> 
> Sorry for bother you, I came to this issue a few hours ago, managed to resolve it and wanted to share my findings. Check in your .csproj files for inconsistences regarding other projects references.
> 
> The omnisharp have a several weeks since the last release, so maybe the problem is in the VSCode. To test this you can create a new project in a clean folder and watch if the message persists.

It is happening with default created projects, like dotnet new console

**Comment by stevef51** [comment]
Yeah, my csproj files have not changed for some time and compile just fine,
its simply the OmniSharp Select Project command that fails

**Comment by yentheo** [comment]
Had the same problem, downgrading to VS Code 1.62 worked for me based on this so question (and response)
https://stackoverflow.com/questions/70290626/how-to-solve-the-problem-that-cant-select-project-using-omni-sharp-on-vs-core

**Comment by itsmuntadhar** [comment]
can confirm that the issue happened after upgrading VSCode to 1.63, downgrading to 1.62 solved it

**Comment by OdisBy** [comment]
I downgraded to 1.62 and solved it too.

**Comment by two-bridges** [comment]
Hi all,

From here: https://github.com/OmniSharp/omnisharp-vscode/pull/4914#issuecomment-990243539

... you can install the prerelease build from https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.18-beta2 as a workaround until a release is ready

**Comment by srgonzalez** [comment]
Hello, in my case installing the beta version [1.24.0](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.24.0-beta1) of OmniSharp extension solved the error.

**Comment by HMBond** [comment]
> In my case my problem was fixed by looking at the sln file and checking that every project was referenced correctly: correct path and name. After that, a simple restart of the VSCode was enough.

It is worth to mention that omnisharp (and C# extension for VSCode) throws errors and does not auto-suggest when there is no .sln file or your project is not referenced correctly within the .sln file.

**Comment by ras-relativity** [comment]
Omnisharp v1.24.0-beta1 did not fix my issue, I downgraded vscode to 1.62.3 and 1.23.17 omnisharp to get it working.

**Comment by nathan130200** [comment]
For me on vscode on windows, v1.24.0 beta fixed problem.

**Comment by admachiano** [comment]
> Hello, in my case installing the beta version [1.24.0](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.24.0-beta1) of OmniSharp extension solved the error.

This solved it for me too

**Comment by Skyebold** [comment]
Quick downgrade command for linux users:

> apt-get install code=1.62.3-1637137107

I'm a little surprised this is broken in the default shipping configuration of vscode and the fix hasn't been deployed yet a month later.  Given how important intellisense is, losing it makes vscode basically unusable.  Priority up, please?

**Comment by m4ss1m0g** [comment]
> Quick downgrade command for linux users:
> 
> > apt-get install code=1.62.3-1637137107
> 
> I'm a little surprised this is broken in the default shipping configuration of vscode and the fix hasn't been deployed yet a month later. Given how important intellisense is, losing it makes vscode basically unusable. Priority up, please?

And the issue is marked closed!

**Comment by thug1705** [comment]
Updating to `v1.24.0` resolved my issue on Windows x64. Here are instructions how you can install `pre-release` version in VsCode.

https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases

**Comment by jesperkristensen** [comment]
I can't get the new version installed. https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp says that the latest version is 1.24.0, but if I check for extension updates within Code, it says v1.23.17 is the newest. If I uninstall the extension and restart Code, it says the version is v1.24.0, but if I then click Install it changes to v1.23.17. I am not sure if it is safe to install a VSIX file from a github page.

**Comment by nathan130200** [comment]
You need manually install version from github releases tab.
