### ISSUE TITLE
Debugger: Couldn't break at the exception even after we checked the User-Unhandled Exceptions

### ISSUE THREAD

**Issue by AmberZhang2016** [OmniSharp/omnisharp-vscode#491]
## Environment data
`dotnet --info` output:
VS Code version:1.2.1
C# Extension version: 1.1.7

## Steps to reproduce
1. add one User-Unhandled Exception like below:
     int j = 0;
     j = 1/j;
2. F5

## Expected  behavior
can be break on this exception

## Actual behavior
doesn't break and see the error in the webpage

## comment:
If we checked the All exception, it will break on this User-Unhandled Exception as expected.

**Comment by gregg-miskelly** [comment]
@AmberZhang2016 are you saying you have a console app with a main method with just the divide by zero expression you referenced? 
.NET Core 1.0?
Windows?

**Comment by AmberZhang2016** [comment]
sorry for the confuse,
1.Download and launch the sample project from https://github.com/OmniSharp/omnisharp-vscode/files/336372/musicstore.zip 
2.Insert below code in public async Task Index() function of HomeController.cs
3. add one User-Unhandled Exception like below: int j = 0; j = 1/j;
4. F5

**Comment by gregg-miskelly** [comment]
This is by design - exceptions in an async method that return a task aren't considered user handled.
