### ISSUE TITLE
coreclr debugger can not set breakpoints in code opened in a folder.

### ISSUE THREAD

**Issue by ColinCohan** [OmniSharp/omnisharp-vscode#4917]
## Issue Description ##
The C# Debugger in VSCode cannot debug in code that is just in the current open folder (Open Folder instead of a project file)

## Steps to Reproduce ##
I have C# code that is compiled via a nonstandard build process into an exe, that is inside a folder. I opened that folder in VSCode, and I setup a launch.json file that would run the built exe. When I Run the debug target, VSCode launches the exe and attaches a debugger, but I can't set breakpoints in my code and the pause button does nothing. Mousing over breakpoints indicates that no symbols were loaded, but the pdb files are right next to the exe and I have set the symbol search path to include the same path.

## Expected Behavior ##

I can set breakpoints, pause, and debug my code

## Actual Behavior ##

The debugger does nothing beyond launching the title.

## Environment information ##

**VSCode version**: 1.62.3
**C# Extension**: 1.23.16

<details><summary>Dotnet Information</summary>
A valid dotnet installation could not be found.</details>

**Comment by gregg-miskelly** [comment]
You didn't include enough information to make much of a guess as to what you are setting up incorrectly. Based on very little I might suspect you aren't debugging the process containing your code.

Breakpoint troubleshooting instructions: [link](https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshoot-Breakpoints)

If you aren't able to figure out your problem that way, please include the content of your launch.json and a debugger log ([instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging)).

**Comment by ColinCohan** [comment]
This was due to using the wrong debugger type, I was using coreclr instead of clr.
