### ISSUE TITLE
OmniSharp gets autoupdated even with "extensions.autoUpdate": false

### ISSUE THREAD

**Issue by jay-m-z** [OmniSharp/omnisharp-vscode#4919]
## Issue Description ##
OmniSharp is always autoupdating, even after asking it not to. It makes working on metered and slow connections like I have hard/impossible. Other installed extensions are not updating automatically and only show update prompt in extensions tab.
## Steps to Reproduce ##
Open VS Code with installed OmniSharp and extensions.autoUpdate set to false.
## Expected Behavior ##
OmniSharp respects extensions.autoUpdate setting.
## Actual Behavior ##
OmniSharp does not respect extensions.autoUpdate setting.
### OmniSharp log ###
<details>empty</details>

### C# log ###
<details>Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.37.18-beta.28...
Platform: darwin, arm64

Downloading package 'OmniSharp for OSX, Version = 1.37.18-beta.28' (40267 KB)...</details>

## Environment information ##

**VSCode version**: 1.63.0-insider
**C# Extension**: 1.23.16

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.401
 Commit:    4bef5f3dbf

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.401/

Host (useful for support):
  Version: 5.0.10
  Commit:  e1825b4928

.NET SDKs installed:
  5.0.401 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|autoconf|maelvalais|0.1.0|
|binary-plist|dnicolson|0.8.0|
|cmake|twxs|0.0.17|
|cmake-tools|ms-vscode|1.9.1|
|cpptools|ms-vscode|1.7.1|
|csharp|ms-dotnettools|1.23.16|
|eppz-code|eppz|1.2.52|
|fig|withfig|0.0.5|
|jupyter|ms-toolsai|2021.11.1001515174|
|jupyter-keymap|ms-toolsai|1.0.0|
|jupyter-renderers|ms-toolsai|1.0.3|
|pico-go|ChrisWood|1.4.3|
|platformio-ide|platformio|2.4.0|
|propertylist|zhouronghui|0.0.2|
|python|ms-python|2021.11.1422169775|
|txt-syntax|xshrim|0.2.0|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-debug|Unity|3.0.2|
|unity-tools|Tobiah|1.2.12|
|vscode-make|technosophos|1.0.2|
|vscode-pylance|ms-python|2021.11.2|;

</details>

**Comment by JoeRobich** [comment]
@jay-m-z It seems that "omnisharp.path" has been configured as "latest" in your VS Code settings. Remove this configuration and it should abide your auto update setting.

**Comment by jay-m-z** [comment]
That was it! I manually put last installed number version in there and it works.
