### ISSUE TITLE
Hot reload for vs code?

### ISSUE THREAD

**Issue by ziaulhasanhamim** [OmniSharp/omnisharp-vscode#4927]
Is it possible to hot reload while debugging in vs code like flutter? If not why not add it? Vs code is the ultimate cross-platform solution. So it should support hot reload.

**Comment by gregg-miskelly** [comment]
Thanks for the suggestion. Support for hot reload would very likely come along with edit and continue support, so I am duping this against https://github.com/OmniSharp/omnisharp-vscode/issues/490.

**Comment by rhyek** [comment]
What about hot reload when not debugging, but just running a project? Any change I can make to the launch.json configuration added by the "generate assets for build and debug" command? Basically what I can currently get by running `dotnet watch run` in a terminal.

**Comment by gregg-miskelly** [comment]
The C# Extension will generate a VS Code task to start the project with `dotnet watch`. In the version of the extension in the marketplace, there were some bugs in the task generated. But you can either install the latest beta release (see [instructions here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases)) or manually tweak the generated tasks.json.
