### ISSUE TITLE
Debugger: EE window couldn't displayed values normally when break on exception

### ISSUE THREAD

**Issue by AmberZhang2016** [OmniSharp/omnisharp-vscode#493]
## Environment data
`dotnet --info` output:
VS Code version:1.2.1
C# Extension version:1.1.7

## Steps to reproduce
1. Download and launch the sample project from https://github.com/OmniSharp/omnisharp-vscode/files/336372/musicstore.zip 
2. Insert below code in  public async Task<IActionResult> Index() function of HomeController.cs
     // Get most popular albums
            var cacheKey = "topsellingnew";
            int i=1 ; 
            string str = "dfdfs";  
            try  
           {                 
                i = Convert.ToInt32(str);       
           }  
            catch //(Exception e)  
           {  
                i = 3;
           } 
            int j = 0;
            j = 1/j;

            List<Album> albums;
            if (!cache.TryGetValue(cacheKey, out albums))
            {
3. checked All Exception in BP window
4. F5, it will break on line "i = Convert.ToInt32(str); "
5. F5, it will break on line "j = 1/j; "

## Expected  behavior
All variable can be displayed normally in EE window

## Actual behavior
the values of all variable is: cannot evaluate from annotated frame 

![capture](https://cloud.githubusercontent.com/assets/20198228/16443958/25daaec2-3e0e-11e6-949b-82e0b371ad60.PNG)

**Comment by gregg-miskelly** [comment]
@AmberZhang2016 what does the call stack window list?

**Comment by AmberZhang2016** [comment]
![capture2](https://cloud.githubusercontent.com/assets/20198228/16472846/5c41443a-3e9a-11e6-9091-9b13168bf180.PNG)
Call Stack window looks normal, and this is an unstable issue, there are half chance to repro.

**Comment by gregg-miskelly** [comment]
@AmberZhang2016 the issue I sure is because of that '[External Code]' frame on the top. It shouldn't really be there.

**Comment by wesrupert** [comment]
@AmberZhang2016, are you able to reproduce this using the newest version of [VSCode](https://code.visualstudio.com/Download) and [the C# extension](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.2.2)? I tried to reproduce it, but when I broke on the exception I was given the correct call stack/variables.

**Comment by caslan** [comment]
Closing the issue as it has been stale for a while. @AmberZhang2016 please reopen if you are still seeing this issue.
