### ISSUE TITLE
\.omnisharp\1.37.17-net6.0\OmniSharp.dll does not exist.

### ISSUE THREAD

**Issue by heartacker** [OmniSharp/omnisharp-vscode#4938]
## Environment data
名称: C#
ID: ms-dotnettools.csharp
说明: C# for Visual Studio Code (powered by OmniSharp).
版本: 1.23.18
发布者: Microsoft
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp

## OmniSharp log
```
OmniSharp server started with .NET 6.0.100
.
    Path: c:\Users\heart\.vscode-insiders\extensions\ms-dotnettools.csharp-1.23.18\.omnisharp\1.37.17-net6.0\OmniSharp.dll
    PID: 4244

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-c:\Users\heart\.vscode-insiders\extensions\ms-dotnettools.csharp-1.23.18\.omnisharp\1.37.17-net6.0\OmniSharp.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```
## Steps to reproduce

```
"omnisharp.useModernNet": true
```

**Comment by JoeRobich** [comment]
@heartacker There is no current release of the net6 version of OmniSharp. You will need to also set "omnisharp.path" to "latest".

**Comment by tarekahf** [comment]
I've been struggling with this error for hours. This step `"omnisharp.path" to "latest"` should have been added to the instructions of the C# Extension Installation.

**Comment by filipw** [comment]
> I've been struggling with this error for hours. This step `"omnisharp.path" to "latest"` should have been added to the instructions of the C# Extension Installation.

you should not need this - it opts you into master builds which are quite unstable. It was only needed prior to 1.24.0 release when there was no other possibility to run net6 version of OmniSharp.

**Comment by JoeRobich** [comment]
@tarekahf The dotnet install script is not intended to be used outside of CI environments where you don't have permissions for a system install. It does temporarily update the shell PATH with the SDK folder but that would not persist to other applications or shells. I would recommend using one of the installers from https://dotnet.microsoft.com/en-us/download/dotnet/6.0.

Other information that might be useful in your scenario is running `dotnet --info` from the vscode terminal to see which dotnet is being used.

**Comment by tmitchel2** [comment]
Updating the extension does not seem to pull this file in.  I had to uninstall and then reinstall the extension completely to make this work.  I only now require "omnisharp.useModernNet": true.

**Comment by jake-carpenter** [comment]
I've been putting up with a barely functioning OmniSharp for a while with .NET 6, but using `omnisharp.path: "latest"` and `omnisharp.useModernNet: true` seem to have solved it. I guess I'd rather put up with the potential bugs from running the latest than not having any intellisense or tooling at all.
