### ISSUE TITLE
Installing debugger: timeout when restoring packages

### ISSUE THREAD

**Issue by sharok** [OmniSharp/omnisharp-vscode#494]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
VS Code version: 1.2.1
C# Extension version: 1.1.7

## Steps to reproduce
Install .net core SDK,
Install vscode 1.2.1
Install c# extension

## Expected  behavior
Debugger is installed.

## Actual behavior
A lot of errors about restoring packages with timeout.

I have the text in the status bar: 
> Downloading and configuring the .net core debugger

 I had been waiting for 1 hour, but text didn't dissapear.

I don't have antivirus or something else programs. VS Code is added to Windows Firewall.
By the way, I can open links in a browser. I tried to open `'https://api.nuget.org/v3-flatcontainer/system.text.regularexpressions/index.json` and got json response.

I have cyrillic symbols in my username, as you can see in a log, may be the problem starts here.

In the log I have:

Creating C:\Users\Макс\.vscode\extensions\ms-vscode.csharp-1.1.7\coreclr-debug\project.json
Telemetry is: Enabled

log  : Restoring packages for C:\Users\����\.vscode\extensions\ms-vscode.csharp-1.1.7\coreclr-debug\project.json...

log  : Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/system.text.regularexpressions/index.json'.
log  : The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/system.text.regularexpressions/index.json' has timed out after 100000ms.
log  : Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/system.text.encoding.extensions/index.json'.
log  : The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/system.text.encoding.extensions/index.json' has timed out after 100000ms.

.... a lot of the same errors here 

log  : Failed to download package from 'https://api.nuget.org/v3-flatcontainer/system.runtime.interopservices.runtimeinformation/4.0.0-rc2-24027/system.runtime.interopservices.runtimeinformation.4.0.0-rc2-24027.nupkg'.
log  : The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/system.runtime.interopservices.runtimeinformation/4.0.0-rc2-24027/system.runtime.interopservices.runtimeinformation.4.0.0-rc2-24027.nupkg' has timed out after 100000ms.

error: Failed to retrieve information from remote source 'https://api.nuget.org/v3-flatcontainer/system.threading/index.json'.
error: The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/system.threading/index.json' has timed out after 100000ms.
error: Failed to retrieve information from remote source 'https://api.nuget.org/v3-flatcontainer/system.text.encoding.extensions/index.json'.
error: The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/system.text.encoding.extensions/index.json' has timed out after 100000ms.

error: Failed to retrieve information from remote source 'https://api.nuget.org/v3-flatcontainer/system.threading.tasks/index.json'.
error: The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/system.threading.tasks/index.json' has timed out after 100000ms.

error: Failed to retrieve information from remote source 'https://api.nuget.org/v3-flatcontainer/system.text.regularexpressions/index.json'.
error: The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/system.text.regularexpressions/index.json' has timed out after 100000ms.

error: Failed to retrieve information from remote source 'https://api.nuget.org/v3-flatcontainer/system.threading/index.json'.
error:   The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/system.threading/index.json' has timed out after 100000ms.

dotnet exited with error code 1

**Comment by gregg-miskelly** [comment]
@sharok: can you try this and see if you run into the same problem:

     cd /d %USERPROFILE%
     mkdir RestoreTest
     cd RestoreTest
     dotnet new

open project.json, add an entry under 'dependencies' to anything that isn't already in your nuget cache. You could try `"System.Security.Cryptography.Algorithms": "4.2.0"`.

    dotnet restore

**Comment by sharok** [comment]
I @gregg-miskelly I got the following:

```

C:\Users\Макс\RestoreTest>dotnet restore
log  : Restoring packages for C:\Users\Макс\RestoreTest\project.json...
log  : Writing lock file to disk. Path: C:\Users\Макс\RestoreTest\project.lock.j
son
log  : C:\Users\Макс\RestoreTest\project.json
log  : Restore completed in 2254ms.```

**Comment by gregg-miskelly** [comment]
@sharok I tried to recreate your setup as best I could - same user name, on Win7. Unfortunately I didn't have any luck. We may need to pass you off to the NuGet team to see if they have any guesses. But:

1. We are planning to push a new release tomorrow (1.2.1) which will make some changes to restore which maybe solves your problem if it is something to do with restoring those specific package. Note that a 1.2 was uploaded today, but that will NOT work for you. So just hold off for 1.2.1.
2. If that doesn't help either, maybe we can try manually restoring on the command line to see if that help us troubleshoot this.

**Comment by sharok** [comment]
@gregg-miskelly Ok. I will try again when a new release will be available.

**Comment by sharok** [comment]
@gregg-miskelly  I don't know what happened, but after upgrading to 1.2.0 version debugger was installed correctly. Thanks.
