### ISSUE TITLE
[Feature Request] Allow Jump to Any Line (up and down) while debugging

### ISSUE THREAD

**Issue by alefragnani** [OmniSharp/omnisharp-vscode#4940]
## Environment data
VS Code version: 1.62
C# Extension version: 1.23.27

## Feature Request

While debugging, sometimes you need to go back to previous lines instead of running again the whole debugging, or go forward to further lines, ignoring some lines of code.

I use VS Code on a daily basis for C#, and from time to time I miss this feature. I came from Delphi, which calls this feature New EIP (https://docwiki.embarcadero.com/RADStudio/Sydney/en/Disassembly_Pane). Just recently I started using Jetbrains Rider too, and it also has a similar feature, called Jump to Any Line/Drag to Skip Code (https://blog.jetbrains.com/idea/2020/08/jump-to-any-line-while-debugging/).

I posted this same request on VS Code repo (https://github.com/microsoft/vscode/issues/138410), and the team answered that the VS Code's generic debugger UI supports that, but it's up the the debugger extension to properly implement it. 

In this case, it is wha they calls "Back in time debugging". I looked at JS/TS debugger and it also doesn't provide that, but instead, the "Restart Frame" feature, which is not exactly the same thing, but it's already helpful.

Thank you

**Comment by gregg-miskelly** [comment]
This feature already exists in the C# debugger -- 
1. Right click on the line you want to execute next
2. Invoke 'Jump to cursor'

**Comment by alefragnani** [comment]
How I missed the context menu? 🤦 

I only looked at the gutter. My bad...

Thanks!
