### ISSUE TITLE
Unable to debug project code invoked by a nuget package using `Activator.CreateInstance`

### ISSUE THREAD

**Issue by eduherminio** [OmniSharp/omnisharp-vscode#4945]
## Issue Description ##

Unable to debug code from my project invoked by a nuget package using `Activator.CreateInstance`.
This works as expected in VS.

Library code example:

```csharp
        public static void SolveLast()
        {
                    var lastProblem = LoadAllProblems(Assembly.GetEntryAssembly()!).LastOrDefault();
                    if (lastProblem is not null)
                    {
                        var potentialProblem = Activator.CreateInstance(lastProblem);
                        if (potentialProblem is BaseProblem problem)
                        {
                              var result1 = await potentialProblem.Solve_1();
                              var result2 = await potentialProblem.Solve_2();
                        }
                    }
         }

        private static IEnumerable<Type> LoadAllProblems(Assembly assembly)
        {
            return assembly.GetTypes()
                .Where(type => typeof(BaseProblem).IsAssignableFrom(type) && !type.IsInterface && !type.IsAbstract);
        }
```

Project code (from where `SolveLast()` method is invoked:

```csharp
    public class Day_01 : BaseProblem
    {
        public override ValueTask<string> Solve_1() => new("Solution 1");

        public override ValueTask<string> Solve_2() => new("Solution 2");
    }
```

## Steps to Reproduce ##

* Clone [AoC2021](https://github.com/eduherminio/AoC2021)
* Add a breakpoint in any of the days
* `dotnet run x`, being x the day where you placed a breakpoint, or `dotnet run all`

Library/nuget package I'm experiencing this issue with: [AoCHelper](https://github.com/eduherminio/AoCHelper)

## Expected Behavior ##

* Breakpoints are hit

## Actual Behavior ##

* Breakpoints aren't hit

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.62.3
**C# Extension**: 1.23.17

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.118 [C:\Program Files\dotnet\sdk]
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.209 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|1.7.1|
|csharp|ms-dotnettools|1.23.17|
|dotnet-test-explorer|formulahendry|0.7.7|
|markdown-preview-github-styles|bierner|0.2.0|
|rainbow-brackets|2gua|0.0.6|
|remote-containers|ms-vscode-remote|0.205.2|
|remote-wsl|ms-vscode-remote|0.58.5|
|vs-keybindings|ms-vscode|0.2.1|
|vscode-docker|ms-azuretools|1.18.0|
|vscode-markdownlint|DavidAnson|0.45.0|;

</details>

**Comment by WardenGnaw** [comment]
It seems like Spectre.Console.dll throws an exception when using `"console": "internalConsole" since it is not a real terminal.

![image](https://user-images.githubusercontent.com/3953714/145634353-5a68996c-c334-4241-99fe-511e797aeb01.png)

If you switch to `"console": "integratedTerminal"` or `"console": "externalTerminal"', Spectre.Console will not throw an exception and you should be able to hit your breakpoint. 

![image](https://user-images.githubusercontent.com/3953714/145634761-84d76e4e-5d56-4552-bd4f-c7a71251b6b9.png)

I hope you will be able to Debug with VS Code for Day 11 (and onwards) of AoC 2021.

**Comment by eduherminio** [comment]
Awesome, thx @WardenGnaw!
