### ISSUE TITLE
runtimeExecutable support in launch config

### ISSUE THREAD

**Issue by watsonian** [OmniSharp/omnisharp-vscode#4947]
## Issue Description ##
I'm trying to get [Doppler](https://www.doppler.com) working with C# in VS Code. Essentially, you execute Doppler and it fetches environment variables and passes them through to your app like this:

```shell
doppler run -- dotnet run
```

You can modify the build task to use Doppler, but that doesn't really cut it since the launch config really needs to execute the app using Doppler.

In the Node extension, it supports `runtimeExecutable` and `runtimeArgs` options in its launch config that allow you to do this as follows:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "node: server",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "doppler",
      "runtimeArgs": [
        "run",
        "--",
        "npm",
        "start"
      ]
    }
  ]
}
```

Is there any chance we could get support for something like this? Or is there maybe another way to get this working that I'm not seeing?

## Environment information ##

**VSCode version**: 1.62.1
**C# Extension**: 1.23.17

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.403
 Commit:    bf9d168ac2

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.6
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.403/

Host (useful for support):
  Version: 5.0.12
  Commit:  7211aa01b3

.NET SDKs installed:
  3.1.415 [/usr/local/share/dotnet/sdk]
  5.0.403 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.17|
|go|golang|0.29.0|
|HCL|wholroyd|0.0.5|
|jupyter|ms-toolsai|2021.10.1101450599|
|jupyter-keymap|ms-toolsai|1.0.0|
|jupyter-renderers|ms-toolsai|1.0.4|
|python|ms-python|2021.12.1559732655|
|ruby|rebornix|0.28.1|
|vscode-pylance|ms-python|2021.12.0|
|vscode-ruby|wingrunr21|0.28.0|;

</details>

**Comment by gregg-miskelly** [comment]
The best you could do with something like this would be to attach to the process after Doppler launches it. If you need to debug startup code, you could add something like support for a new `--wait-for-debug` to your code, and have that do something like `while (!Debugger.IsAttached) Thread.Sleep(100);`
