### ISSUE TITLE
.NET 6 Syntax Highlighting Broken

### ISSUE THREAD

**Issue by grumpyTofu** [OmniSharp/omnisharp-vscode#4951]
## Issue Description ##
Syntax Highlighting not working with new .NET 6 style of declaring namespaces

## Steps to Reproduce ##
dotnet new grpc -o GrpcGreeter
code -r GrpcGreeter
Open the GreeterService.cs in Services folder

## Expected Behavior ##
Syntax Highlighting works as expected

## Actual Behavior ##
Not all code receives syntax highlighting unless the code is placed inside of curly brackets (old style). With the new .NET 6 style of just listing the namespace at the top, it breaks syntax highlighting.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.62.1
**C# Extension**: 1.23.17

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.3
 OS Platform: Darwin
 RID:         osx.11.0-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|aadb2c|AzureADB2CTools|1.3.1|
|auto-rename-tag|formulahendry|0.1.9|
|better-toml|bungcip|0.3.2|
|csharp|ms-dotnettools|1.23.17|
|dotenv|mikestead|1.0.1|
|dotnet-test-explorer|formulahendry|0.7.7|
|jupyter|ms-toolsai|2021.10.1101450599|
|jupyter-keymap|ms-toolsai|1.0.0|
|jupyter-renderers|ms-toolsai|1.0.4|
|material-icon-theme|PKief|4.11.0|
|nugetpackagemanagergui|aliasadidev|1.1.9|
|prettier-vscode|esbenp|9.0.0|
|python|ms-python|2021.12.1559732655|
|rust|rust-lang|0.7.8|
|vscode-coverage-gutters|ryanluker|2.8.2|
|vscode-graphql|GraphQL|0.3.41|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-pylance|ms-python|2021.12.1|
|vscode-tailwindcss|bradlc|0.7.4|
|vscodeintellicode|VisualStudioExptTeam|1.2.14|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by filipw** [comment]
The issue is with the built-in textmate grammar (not maintained in this repo but, in https://github.com/dotnet/csharp-tmLanguage) that ships with VS Code directly not with this extension. They already corrected this and it is fixed in VS Code Insiders and should be part of next VS Code release.

btw, this works correctly with semantic highlighting enabled:

```
    "editor.semanticHighlighting.enabled": true,
    "csharp.semanticHighlighting.enabled": true
```

**Comment by grumpyTofu** [comment]
Attaching screenshots for clarity:

Broken Behavior:

![image](https://user-images.githubusercontent.com/30991516/145689217-22f9a3f9-e95d-46a1-b7f1-30fc24efe740.png)

Workaround:

![image](https://user-images.githubusercontent.com/30991516/145689244-7ea1261f-a1b3-474d-b8cf-0efd54d29e4c.png)
