### ISSUE TITLE
OmniSharp Cannot access my file

### ISSUE THREAD

**Issue by Rabbit0w0** [OmniSharp/omnisharp-vscode#4956]
# Environment Data
.NET SDK (reflecting any global.json):
 Version:   5.0.403
 Commit:    bf9d168ac2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.403\

Host (useful for support):
  Version: 5.0.12
  Commit:  7211aa01b3

.NET SDKs installed:
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

# Expected behavior
Access my file normally and analyze it.

```
[fail]: OmniSharp.Stdio.Host
        ************  Response (9.0975ms) ************ 
{
  "Request_seq": 5596,
  "Command": "/filesChanged",
  "Running": true,
  "Success": false,
  "Message": "\"System.IO.IOException: The process cannot access the file 'c:\\\\Users\\\\Administrator\\\\Desktop\\\\ZOO\\\\Zoogulation\\\\Assets\\\\Editor\\\\BundleBuilder.cs' because it is being used by another process.\\r\\n   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\\r\\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\\r\\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\\r\\n   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)\\r\\n   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)\\r\\n   at OmniSharp.Roslyn.BufferManager.<UpdateBufferAsync>d__8.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn\\\\BufferManager.cs:line 47\"",
  "Body": null,
  "Seq": 42236,
  "Type": "response"
}
```

**Comment by youegraillot** [comment]
@Rabbit0w0 Did you found a fix ? I got the same error
