### ISSUE TITLE
Debugger:Breakpoints hit the wrong line after editing.

### ISSUE THREAD

**Issue by Serena01** [OmniSharp/omnisharp-vscode#496]
## Environment data
`dotnet --info` output:
VS Code version:1.2.1
 C# Extension version:1.1.7

## Steps to reproduce
1.Download and launch the sample project from https://github.com/OmniSharp/omnisharp-vscode/files/336372/musicstore.zip 
2.Select ".NET Core Launch Web" and configure the location of musicstore.dll for "program which contains the space at the end as following: "program": "${workspaceRoot}/bin/Debug/netcoreapp1.0/musicstore.dll ",
3.Add some simple code in HomeController.cs, then set bp as bellow:
 HomeController(IOptions options){
 int a=1;//set breakpiont1 here
 int b=20;
 int c=a+1;//set breakpoint2 here
 }
4.F5
5.When VS code hit breakpoint1, press "Enter".
6.F5

## Expected  behavior
1.Both breakpoints should be red.
2.Breakpoint2 should be at line which contains "int c=a+b"
3.VS code should hit the line which contains "int c=a+b"

## Actual behavior
1.Both breakpoints should be grey.
2.Breakpoint2 is not at line which contains "int c=a+b"
3.VS code did not hit the line which contains "int c=a+b"
please see the before_enter.png ,after_enter.png and Twice_F5.png

![before_enter](https://cloud.githubusercontent.com/assets/20184641/16448972/0ad9c658-3e27-11e6-91b5-b57dc851edeb.PNG)
![after_enter](https://cloud.githubusercontent.com/assets/20184641/16448971/0a7b844e-3e27-11e6-960c-5c913668da98.PNG)
![twice_f5](https://cloud.githubusercontent.com/assets/20184641/16449105/f4d10c26-3e27-11e6-9a4e-138887b2aada.PNG)

**Comment by wesrupert** [comment]
VS Code currently does not let us know when the buffer has been modified, so we don't know that these breakpoints shouldn't be bound to the now-stale source information. [VS Code issue #8077](https://github.com/Microsoft/vscode/issues/8077) should enable detecting this, then we can disable stale breakpoints.

**Comment by wesrupert** [comment]
Fix should be available in the next release to address breakpoints binding to the wrong location after saving. We don't get any information from VS Code about a modified buffer currently, I've filed [VS Code issue #9823](https://github.com/Microsoft/vscode/issues/9823) for this.
