### ISSUE TITLE
Add auto usings statements

### ISSUE THREAD

**Issue by ziaulhasanhamim** [OmniSharp/omnisharp-vscode#4963]
In vs code to import C# namespaces, We have to manually do `Ctrl + .` then add the usings. But there is not an option like `Show unimported namespace" of Visual Studio from IntelliSense. Even languages like Golang and Python support this feature for vs code. Very productive

**Comment by JoeRobich** [comment]
@ziaulhasanhamim I am happy to say that we do support this feature. It is disabled by default because it may impact performance. Please set `omnisharp.enableImportCompletion` to `true` in your VS Code settings.
