### ISSUE TITLE
LogPoint pauses execution like BreakPoint

### ISSUE THREAD

**Issue by aconcagua21** [OmniSharp/omnisharp-vscode#4966]
Issue Type: <b>Bug</b>

Add a new LogPoint and let the code run through. It logs the message, but then stops, as if it were a BreakPoint.

Extension version: 1.23.17
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id c081a328-d5f9-41db-8d32-18987e2a3b2a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30405999
vscexrecpromp3t1:30407762

```

</details>

**Comment by gregg-miskelly** [comment]
I missed this at first, but we already have an issue for this: https://github.com/OmniSharp/omnisharp-vscode/issues/1797
