### ISSUE TITLE
Debugger: Conditional breakpoint not supported by this debug type

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#497]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Steps to reproduce
1 Add a conditional breakpoint at  line of " _appSettings = options.Value; " in HomeController.cs  
and edit that breakpoint with condition of "1<0"
2 Press F5 to start debugging

## Expected  behavior
The conditional breakpoint I just added shouldn't be hit in editor window. I input a false expression, so the breakpoint would not be hit.

## Actual behavior
The conditional breakpoint would be hit and error message show "Conditional breakpoints not supported by this debug type". I don't know whether the conditional breakpoint is supported on CoreCLR.

**Comment by gregg-miskelly** [comment]
@GraceDong conditional breakpoints are just about to go in, but there aren't in yet.

**Comment by gregg-miskelly** [comment]
@chuckries do you want to resolve this once you checkin?

**Comment by chuckries** [comment]
@gregg-miskelly sure.

**Comment by chuckries** [comment]
This will be available in the next release.

**Comment by xCyborg** [comment]
mm

**Comment by AlejandroHuerta** [comment]
Going with what @xCyborg said. I'm not able to use conditional breakpoints with Unity 5.4.3f1. Is this an issue with this extension or the Debugger for Unity extension?

**Comment by gregg-miskelly** [comment]
For debugging, this extension only supports .NET core (and limited .NET Full Framework on Windows) development. AFAIK Unity doesn't use either of these, so you want a different debugger.
