### ISSUE TITLE
`Install Another Version...` doesn't work for the C# extension only

### ISSUE THREAD

**Issue by cateyes99** [OmniSharp/omnisharp-vscode#4973]
## Environment data
`dotnet --info` output:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.302\

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
VS Code version: ___1.63.2___
C# Extension version: **_1.23.16_**

## OmniSharp log
**_No log_**

## Steps to reproduce
For weeks, i've noticed that among the all extensions i've installed, the C# one is the only has this issue. Go to the Extensions view. Click `Install Another Version...` on the menu for the **C#** extension. Observe the expected list of versions not showing, instead it's just hanging ... Not sure if this is **VSCode** team's responsibility or the **C# extension** team's.
![VSCodeCSharpExtensionInstallAnotherVer](https://user-images.githubusercontent.com/19678455/147300602-5ef4f46a-4b36-4a9d-972f-e3c56efefb3b.gif)

## Expected  behavior
The list of versions show display without problem.

## Actual behavior
Just hanging, not displaying the list of versions.

**Comment by JoeRobich** [comment]
The list will display if you give it enough time. It would be best to open this issue against https://github.com/microsoft/vscode/issues.
