### ISSUE TITLE
Enabling Roslyn Analyzers Makes Errors Not Show Up Until Modified

### ISSUE THREAD

**Issue by TheKingOfLettuce** [OmniSharp/omnisharp-vscode#4977]
## Issue Description ##
With the `Omnisharp: Enable Roslyn Analyzers`  setting checked, it causes errors to not show up until the file is modified. For example, if MyClass1 references anything from MyClass2, deleting MyClass2 will not cause any errors to appear in MyClass1 until it is modified in any way. Disabling the Roslyn Analyzer seems to fix this issue
## Steps to Reproduce ##

1. Create a blank folder and open it in VS Code
2. Open the terminal and create a new console project: `dotnet new console`
3. Make sure `Omnisharp: Enable Roslyn Analyzers` is checked in settings and restart Omnisharp
4. Create a new file called MyClass.cs and make sure you can reference something from main. Example: 
`public static class MyClass {
    public static int a;
}`
5. Add the following line to Main: `Console.WriteLine(MyClass.a);`
6. Delete MyClass.cs
7. Observe Program.cs

## Expected Behavior ##
Intellisense should kick in and tell me about the unknown class being referenced  
## Actual Behavior ##
No errors show up, unless I modify Program.cs in anyway such as adding a space anywhere.
### OmniSharp log ###
<details>Starting OmniSharp server at 12/26/2021, 2:04:58 PM
    Target: c:\Users\Cam\Documents\Coding_Projects\Test

OmniSharp server started.
    Path: c:\Users\Cam\.vscode\extensions\ms-dotnettools.csharp-1.23.17\.omnisharp\1.37.17\OmniSharp.exe
    PID: 6472

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 17.0.0 - "c:\Users\Cam\.vscode\extensions\ms-dotnettools.csharp-1.23.17\.omnisharp\1.37.17\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\Cam\.vscode\extensions\ms-dotnettools.csharp-1.23.17\.omnisharp\1.37.17\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 17.0.0 - "c:\Users\Cam\.vscode\extensions\ms-dotnettools.csharp-1.23.17\.omnisharp\1.37.17\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\Cam\.vscode\extensions\ms-dotnettools.csharp-1.23.17\.omnisharp\1.37.17\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\Cam\.vscode\extensions\ms-dotnettools.csharp-1.23.17\.omnisharp\1.37.17\.msbuild
            MSBuildToolsPath = c:\Users\Cam\.vscode\extensions\ms-dotnettools.csharp-1.23.17\.omnisharp\1.37.17\.msbuild\Current\Bin
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Cam\Documents\Coding_Projects\Test'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\Cam\Documents\Coding_Projects\Test'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Cam\Documents\Coding_Projects\Test\Test.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Cam\Documents\Coding_Projects\Test'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Cam\Documents\Coding_Projects\Test' on host 14236.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\Cam\Documents\Coding_Projects\Test\Test.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\Cam\Documents\Coding_Projects\Test\Test.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\Cam\Documents\Coding_Projects\Test\Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Test
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 4.
Received response for /quickinfo but could not find request.</details>

### C# log ###
C# log is empty
<details></details>

## Environment information ##

**VSCode version**: 1.63.2
**C# Extension**: 1.23.17

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|code-plus-theme|ceciljacob|1.0.0|
|cpptools|ms-vscode|1.7.1|
|csharp|ms-dotnettools|1.23.17|
|docomment|k--kato|0.1.30|
|eclipse-new-java-project|mellena1|1.0.1|
|java|redhat|1.2.0|
|python|ms-python|2021.12.1559732655|
|theme|tal7aouy|1.2.1|
|theme-cobalt2|wesbos|2.2.5|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-debug|Unity|3.0.2|
|vscode-java-debug|vscjava|0.37.0|
|vscode-java-dependency|vscjava|0.18.9|
|vscode-java-pack|vscjava|0.20.0|
|vscode-maven|vscjava|0.34.2|
|vscode-pylance|ms-python|2021.12.2|
|vscodeintellicode|VisualStudioExptTeam|1.2.15|;

</details>

**Comment by gregor160300** [comment]
I believe this is a duplicate of #4754

**Comment by TheKingOfLettuce** [comment]
Duplicate of #4754
