### ISSUE TITLE
Can't format C# code

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#5]
_From @darktutu on January 11, 2016 9:12_

version 0.10.6
![image 032](https://cloud.githubusercontent.com/assets/1868626/12229877/a00d59fa-b886-11e5-9dd1-e0fcc02caa02.png)

_Copied from original issue: Microsoft/vscode#1918_

**Comment by jrieken** [comment]
_From @isidorn on January 11, 2016 15:23_

Not sure if we support C# formating, joh?

**Comment by jrieken** [comment]
@darktutu What does the OmniSharp log read (press Cmd+L, L)?

**Comment by jrieken** [comment]
_From @darktutu on January 13, 2016 9:26_

@jrieken  nothing in omnisharp log

**Comment by jrieken** [comment]
do you have a project.json file or a  set of csproj/sln files? otherwise it won't work

**Comment by jrieken** [comment]
_From @FaicSilier on January 19, 2016 9:2_

Hello, I have kind of the same problem with formatting javascript: Nothing happens if I format it.

How can I add a project.json file or set a csproj/sln file so that formatting works. (as a suggestion: would be great if you wouldn't need to create files to format code)

**Comment by jrieken** [comment]
@FaicSilier JavaScript is independent of that. If you see issue with formatting JS please file a separate bug

**Comment by jrieken** [comment]
_From @darktutu on January 20, 2016 3:37_

@jrieken  I open a solution. but  it didn't work。is vscode support c# format ?

**Comment by jrieken** [comment]
@darktutu What does the OmniSharp log read (press Cmd+L, L)? It should not be empty

**Comment by DustinCampbell** [comment]
This is pretty old and I can't repro. When I open a folder containing an .sln file and right-click within a C# file, I see the Format Code in the context menu. @darktutu is it still a problem for you?

![image](https://cloud.githubusercontent.com/assets/116161/14726299/06da19fe-07d6-11e6-8230-58ddbf5a96b7.png)

**Comment by zerowang** [comment]
I got the same context menu as darktutu's screenshot.
and OmniSharp Log has:
[INFO] Starting OmniSharp at 'c:\Working Directory\Test_ASPNETCore'...

This is on:
vscode: 1.1.1
C#: 1.0.11

**Comment by jlmakes** [comment]
I _see_ the option in the context menu, and it works for JavaScript files… but does nothing for C# (on OSX) using VSCode: `1.2.0`

I’m not sure what I’m doing wrong, but my OmniSharp log looks like this (and doesn't output anything when I attempt to format my code):
```
[INFO] Starting OmniSharp at '/Users/jlmakes/Unity/SampleProject/SampleProject.sln'...
[INFO] Started OmniSharp from '/Users/jlmakes/.vscode/extensions/ms-vscode.csharp-1.0.11/.omnisharp/OmniSharp' with process id 2500...
OmniSharp: -s /Users/jlmakes/Unity/SampleProject/SampleProject.sln --hostPID 2479 dnx:enablePackageRestore=false --stdio
[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location '/Users/jlmakes/Unity/SampleProject' on host 2479.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /Users/jlmakes/Unity/SampleProject
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: True
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp.Startup] Configuration finished.

```
