### ISSUE TITLE
javascript code extension, beginscripts doesn't recognize in partials view

### ISSUE THREAD

**Issue by jonatanfelipesiqueira** [OmniSharp/omnisharp-vscode#5000]
![image](https://user-images.githubusercontent.com/43968142/148840136-f942398f-6f93-4328-9baf-f80981935d7e.png)

when using code extension to send the javascript from a partial view to the index, the code is not recognized, would this correction be possible? same works in visual studio 2019

in vs 2019

![image](https://user-images.githubusercontent.com/43968142/148840150-c19218f5-51c1-4f92-89be-6ad7d61dc9f2.png)

**Comment by JoeRobich** [comment]
@ryanbrandenburg Is this a known issue?

**Comment by ryanbrandenburg** [comment]
We've had some issues about JavaScript not being represented properly but not this one specifically. I'd say send it our way.

**Comment by JoeRobich** [comment]
Moved this issue to the dotnet/razor-tooling repo as https://github.com/dotnet/razor-tooling/issues/5962. Closing.
