### ISSUE TITLE
Debug Windows x86_64 on ARM64

### ISSUE THREAD

**Issue by cwensley** [OmniSharp/omnisharp-vscode#5004]
## Issue Description ##
Hi, I'm trying to use VSCode to debug an x64 app with .NET Framework on a Windows ARM64 device.  Is this possible?  on MacOS, you can specify `"targetArchitecture": "x86_64"` for the launch config, but this doesn't appear to work on Windows.

I have tried both the x64 and ARM64 version of VS Code, and neither work now.  This worked at one point using the x64 version of VS Code but then stopped working recently, and it would be nice if this worked again. 

## Steps to Reproduce ##

Add a launch.json that uses the "clr" debug type on Windows 11 ARM to an executable that is x86_64 running in emulation on Windows 11 ARM. 

## Expected Behavior ##

Should be able to debug

## Actual Behavior ##

Cannot debug, gives the message:

```
Error processing 'configurationDone' request. The remote computer does not have a CLR version which is compatible with the remote debugging components. To install a compatible CLR version, see the instructions in the 'Remote Components Setup' page on the Visual Studio CD.
```

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.63.2
**C# Extension**: 1.23.17

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-arm64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.403 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|1.7.1|
|csharp|ms-dotnettools|1.23.17|
|csharpextensions|kreativ-software|1.5.3|
|EditorConfig|EditorConfig|0.16.4|
|gitlens|eamodio|11.7.0|
|tasks-shell-input|augustocdias|1.7.0|
|vscode-solution-explorer|fernandoescolar|0.4.5|;

</details>

**Comment by cwensley** [comment]
Aha, so I can do this:

1. Run the x64 version of VS Code
2. Install the x64 version of the OmniSharp-vscode extension
3. Wait until OmniSharp downloads and installs the .NET 6 / x64 version of OmniSharp
3. Close the x64 version of VS Code
4. Run the ARM64 version of VS Code
5. Try to debug an x64 app using "clr" debug type
6. Success! (sort of)

It would be nice if this worked out of the box, however.  There also appears to be problems running OmniSharp for IntelliSense though running x64 or ARM64 versions of VS Code, with this message in the OmniSharp Log:
```
Starting OmniSharp server at 2022-01-12, 10:17:27 p.m.
    Target: c:\Users\curtis\Projects\McNeel\rhino8

OmniSharp server started with .NET 6.0.100
.
    Path: c:\Users\curti\.vscode\extensions\ms-dotnettools.csharp-1.24.0\.omnisharp\1.38.1-beta.15-net6.0\OmniSharp.dll
    PID: 7680

Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)

```

**Comment by cwensley** [comment]
Another aha.  I had this, synced from macOS in my settings.json.  Removing it makes IntelliSense work:

```
"omnisharp.useModernNet": true,
```

Perhaps something to take into account when using the .NET 6 version of OmniSharp.

**Comment by gregg-miskelly** [comment]
My recommended work around would be to use full Visual Studio to debug x64 projects on ARM64 Windows. We don't have any plans to support this scenario in VS Code, though obviously plans can change.

**Comment by gregg-miskelly** [comment]
You could talk to the VS Code team to see if either they would consider it a bug that they use the same extension folder for both architectures or if there is a way you can configure VS Code to use a different folder.

**Comment by hajekj** [comment]
I think it would be rather better if the `targetArchitecture` switch worked. Rather than having two versions of VS Code and everything duplicated.

**Comment by cwensley** [comment]
I agree @hajekj, it is not ideal and I wish I could debug x64 apps from VS Code running in ARM64.  

Additionally, the x64 build of VS Code no longer allows you to debug x64 .NET Core apps, only x64 .NET Framework apps.  

I have now resorted to using VS 2022 to do pretty much everything.  Which works great under ARM64 now, but it's a shame because I would prefer to use VS Code instead.

**Comment by hajekj** [comment]
I think there should be more attention to this - I have Surface Pro X, there is https://learn.microsoft.com/en-us/windows/arm/dev-kit/ on ARM64, and it for example prevents me from debugging/building Azure Functions in VS Code.

**Comment by gregg-miskelly** [comment]
Definitely agree that it would be better if `targetArchitecture` worked on Windows. If anyone is super passionate about this and has the cycles, we would be happy to accept a PR that moved that option from macOS-only to something that worked on both macOS and Windows. If not, I would expect us to eventually fix this, but we are fully booked at the moment.

**Comment by hajekj** [comment]
@gregg-miskelly - I could look into it - could you provide some basic guidance on how this works? I suppose it would need to download both ARM64/X64 debuggers side-by-side and switch between them? If that would be the case, changing the folder structure and respecting the selected architecture would do the job I guess?

**Comment by cwensley** [comment]
@hajekj, I've just tried doing that by hacking some things together.. I'm not sure entirely, but it looks like vsdbg-ui will likely have to be changed, which I believe is closed source?  It gives the message `Unable to start program '<path to program>'. The .NET debugger can only debug x64 processes.`.  

This is the same message I get when trying to run VS Code and everything else in x64, which one would think would work but does not.

**Comment by gregg-miskelly** [comment]
You don't need/want a new vsdbg-ui for this. Instead, this extension needs to install both the ARM64 and x64 vsdbg-ui when installing on Windows ARM64 (the same as it does on macOS).

To do so:
1. Update package.json: 
    A. Update the [install path for the x64 debugger](https://github.com/OmniSharp/omnisharp-vscode/blob/b8b07bb12557b4400198895f82a94895cb90c461/package.json#L405) to be something like ".debugger/x64_64" like on macOS
    B. Update the supported architectures to also include "arm64"
    C. Update the install path for the arm64 debugger as well
2. Update [getTargetArchitecture](https://github.com/OmniSharp/omnisharp-vscode/blob/b8b07bb12557b4400198895f82a94895cb90c461/src/coreclr-debug/util.ts#L104) to do something on ARM64 Windows. Probably it can just act the same.
3. Update the documentation for `targetArchitecture` to indicate that it works on arm64 Windows.
4. Bonus points -- support attach, figure out the equivalent of [this code](https://github.com/OmniSharp/omnisharp-vscode/blob/b8b07bb12557b4400198895f82a94895cb90c461/src/coreclr-debug/debugConfigurationProvider.ts#L44) for Windows. This will mean figuring out how to get the architecture of a process from PowerShell and modifying [CimAttachItemsProvider](https://github.com/OmniSharp/omnisharp-vscode/blob/f807bafc3a332ea612f7b82a7bc0dc1a793825de/src/features/processPicker.ts#L429)

**Comment by cwensley** [comment]
Thanks @gregg-miskelly, I understand that and did that.  The problem is, using the x64 vsdbg-ui on ARM64 doesn't actually work.

**Comment by hajekj** [comment]
Where does the `Unable to start debugging. Failed to attach to process: The .NET debugger can only debug x64 processes.` come from?

In Visual Studio 2022, I am able to run and debug Azure Functions just fine. I enabled vsdbg-ui.exe's logging, but the output is:

```
-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true,"supportsArgsCanBeInterpretedByShell":true,"supportsMemoryEvent":true,"supportsStartDebuggingRequest":true},"type":"request","seq":1}

<- (R) {"seq":2,"type":"response","request_seq":1,"success":true,"command":"initialize","body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":true,"supportsConditionalBreakpoints":true,"supportsHitConditionalBreakpoints":true,"supportsEvaluateForHovers":true,"exceptionBreakpointFilters":[{"filter":"all","label":"All Exceptions","description":"Break when an exception is thrown. For more information about exception settings, see: https://aka.ms/VSCode-CS-ExceptionSettings","default":false,"supportsCondition":true,"conditionDescription":"Comma-separated list of exception types to break on, or if the list starts with '!', a list of exception types to ignore. \nExample 1: System.NullReferenceException -- this will break on just null reference exceptions. \nExample 2: !System.Threading.Tasks.TaskCanceledException -- this will break on all exceptions except for task canceled.\n\nFor more information about exception settings, see: https://aka.ms/VSCode-CS-ExceptionSettings"},{"filter":"user-unhandled","label":"User-Unhandled Exceptions","description":"Break when an exception is caught in non-user code (system code) after having passed through user code. For more information about exception settings, see: https://aka.ms/VSCode-CS-ExceptionSettings","default":true,"supportsCondition":true,"conditionDescription":"Comma-separated list of exception types to break on, or if the list starts with '!', a list of exception types to ignore. \nExample 1: System.NullReferenceException -- this will break on just null reference exceptions. \nExample 2: !System.Threading.Tasks.TaskCanceledException -- this will break on all exceptions except for task canceled.\n\nFor more information about exception settings, see: https://aka.ms/VSCode-CS-ExceptionSettings"}],"supportsSetVariable":true,"supportsGotoTargetsRequest":true,"supportsModulesRequest":true,"supportedChecksumAlgorithms":["MD5","SHA1","SHA256"],"supportsExceptionOptions":true,"supportsValueFormattingOptions":true,"supportsExceptionInfoRequest":true,"supportTerminateDebuggee":true,"supportsSetExpression":true,"supportsReadMemoryRequest":true,"supportsCancelRequest":true,"supportsExceptionFilterOptions":true,"supportsExceptionConditions":true,"supportsLoadSymbolsRequest":true,"supportsModuleSymbolSearchLog":true,"supportsDebuggerProperties":true,"supportsSetSymbolOptions":true,"supportsHitBreakpointIds":true,"supportsVsIndividualBreakpointOperations":true,"supportsVsBreakpointLanguage":true,"supportsSetHitCount":true,"supportsVsCustomMessages":true,"supportsEvaluationOptions":true,"supportsExceptionStackTrace":true,"memoryReferencesAreAddresses":true,"supportsObjectFavorites":true,"supportsObjectId":true,"supportsVariableEnumerators":false}}

-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true,"supportsArgsCanBeInterpretedByShell":true,"supportsMemoryEvent":true,"supportsStartDebuggingRequest":true},"type":"request","seq":1}

<- (R) {"seq":5,"type":"response","request_seq":1,"success":true,"command":"initialize","body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":true,"supportsConditionalBreakpoints":true,"supportsHitConditionalBreakpoints":true,"supportsEvaluateForHovers":true,"exceptionBreakpointFilters":[{"filter":"all","label":"All Exceptions","description":"Break when an exception is thrown. For more information about exception settings, see: https://aka.ms/VSCode-CS-ExceptionSettings","default":false,"supportsCondition":true,"conditionDescription":"Comma-separated list of exception types to break on, or if the list starts with '!', a list of exception types to ignore. \nExample 1: System.NullReferenceException -- this will break on just null reference exceptions. \nExample 2: !System.Threading.Tasks.TaskCanceledException -- this will break on all exceptions except for task canceled.\n\nFor more information about exception settings, see: https://aka.ms/VSCode-CS-ExceptionSettings"},{"filter":"user-unhandled","label":"User-Unhandled Exceptions","description":"Break when an exception is caught in non-user code (system code) after having passed through user code. For more information about exception settings, see: https://aka.ms/VSCode-CS-ExceptionSettings","default":true,"supportsCondition":true,"conditionDescription":"Comma-separated list of exception types to break on, or if the list starts with '!', a list of exception types to ignore. \nExample 1: System.NullReferenceException -- this will break on just null reference exceptions. \nExample 2: !System.Threading.Tasks.TaskCanceledException -- this will break on all exceptions except for task canceled.\n\nFor more information about exception settings, see: https://aka.ms/VSCode-CS-ExceptionSettings"}],"supportsSetVariable":true,"supportsGotoTargetsRequest":true,"supportsModulesRequest":true,"supportedChecksumAlgorithms":["MD5","SHA1","SHA256"],"supportsExceptionOptions":true,"supportsValueFormattingOptions":true,"supportsExceptionInfoRequest":true,"supportTerminateDebuggee":true,"supportsSetExpression":true,"supportsReadMemoryRequest":true,"supportsCancelRequest":true,"supportsExceptionFilterOptions":true,"supportsExceptionConditions":true,"supportsLoadSymbolsRequest":true,"supportsModuleSymbolSearchLog":true,"supportsDebuggerProperties":true,"supportsSetSymbolOptions":true,"supportsHitBreakpointIds":true,"supportsVsIndividualBreakpointOperations":true,"supportsVsBreakpointLanguage":true,"supportsSetHitCount":true,"supportsVsCustomMessages":true,"supportsEvaluationOptions":true,"supportsExceptionStackTrace":true,"memoryReferencesAreAddresses":true,"supportsObjectFavorites":true,"supportsObjectId":true,"supportsVariableEnumerators":false}}

-> (C) {"command":"attach","arguments":{"name":"Attach to .NET Functions","type":"coreclr","request":"attach","processId":"11004","__configurationTarget":6,"__sessionId":"bbb7747a-1b80-4576-a787-f2634b3bd8ab"},"type":"request","seq":2}

-> (C) {"seq":8,"type":"request","command":"handshake","arguments":{"value":"XzzXIz0D1gndnKrMyONLSnDLN2YD7Ncj+t4GP2+K0EQ="}}

-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------


```

**Comment by hajekj** [comment]
@gregg-miskelly - I am trying to debug standard Azure Functions .NET 6.0 C# project on my ARM64 device (V4 runtime). The architecture of Functions runtime is x64 (as per task manager) and I can run the Function just fine on my device. I am however unable to attach debugger to it from VS Code.

I have a VM in Azure running ARM64 setup to demonstrate, if you want access, I am happy to share the credentials.

**Comment by gregg-miskelly** [comment]
With @hajekj's help, I found the issue with vsdbg-ui. When we insert the next vsdbg-ui it should allow this scenario, though [these steps](https://github.com/OmniSharp/omnisharp-vscode/issues/5004#issuecomment-1489462038) will still need to be done.

**Comment by hajekj** [comment]
I will try to draft a PR during next week.

**Comment by cwensley** [comment]
Hey @hajekj, thanks for looking into this.  If you need help with any of the updates, I've done a few things as well but would still need some polishing.

**Comment by gregg-miskelly** [comment]
> We will need to ship both x86_64 and arm64 versions of OmniSharp DLLs (which will impact the size on disk), since x64 OmniSharp.dll doesn't seem to run under ARM64 dotnet and vice-versa, which seems weird as I thought the DLLs are just IL, which should run everywhere, but I haven't looked into this yet.

To be clear, I don't think you want to change the PATH in the VS Code/VS Code Extension Host process, but rather just the target process. In this case of Azure Functions, this may require a change to the Azure Functions VS Code extension rather than this.

**Comment by hajekj** [comment]
As per the docs - https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/path-x64-emulated - the guidance on ARM64 is:
If I want to use X64 SDK instead of ARM64, I should add it to PATH. When I do this, the `dotnet OmniSharp.dll` fails with (and vice-versa):
```
C:\Users\AzureUser\Documents\omnisharp-vscode\.omnisharp\1.39.6-net6.0>dotnet OmniSharp.dll
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'C:\Users\AzureUser\Documents\omnisharp-vscode\.omnisharp\1.39.6-net6.0\OmniSharp.dll'. Format of the executable (.exe) or library (.dll) is invalid.
File name: 'C:\Users\AzureUser\Documents\omnisharp-vscode\.omnisharp\1.39.6-net6.0\OmniSharp.dll'
```
Is there any reason why the OmniSharp.dll isn't targeted as Any CPU? Or at least [`RuntimeIdentifiers`](https://github.com/OmniSharp/omnisharp-roslyn/blob/ed467d0ad2d877b837380a849f856dcd210d69f7/src/OmniSharp.Stdio.Driver/OmniSharp.Stdio.Driver.csproj) set as `win` so that it works with all runtimes and we skip the differentiation between X64 and ARM64? (the same would also apply to Razor Language Server).
![image](https://user-images.githubusercontent.com/8337913/230016939-68ebed50-1e1b-443a-b5c1-975688b42039.png)

However I don't think this is going to be a big deal right now, at least for my scenario, since with the initial changes I can debug Azure Functions just fine by setting `targetArchitecture` and still use ARM64 .NET SDK for the rest. But if there is going to be a need for broader ARM64 scenarios support, I think this will be one of the things to focus on in future.

**Comment by hajekj** [comment]
I have submitted the PR for enabling support of `targetArchitecture`. I believe that it can be merged as it is not breaking and will enable more scenarios to work, however we should continue with discussing the above.

**Comment by gregg-miskelly** [comment]
I am closing this. I opened https://github.com/OmniSharp/omnisharp-vscode/issues/5649 to track potentially further improving this scenario to support automatic architecture detection for attach.
