### ISSUE TITLE
System.BadImageFormatException starting omnisharp server (osx-arm64)

### ISSUE THREAD

**Issue by jonathaneckman** [OmniSharp/omnisharp-vscode#5008]
## Steps to Reproduce ##

1. Install prerelease 1.24.0 from VSIX to VS Code.
2. Observe output. Extension installs but Omnisharp server fails to start. Output:

```
Starting OmniSharp server at 1/15/2022, 4:01:18 PM
    Target: /Users/eck/Code/my-project

OmniSharp server started with .NET 6.0.100
.
    Path: /Users/eck/.vscode/extensions/ms-dotnettools.csharp-1.24.0/.omnisharp/1.38.1-beta.15-net6.0/OmniSharp.dll
    PID: 64647

Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (0x8007000B)
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```

## Expected Behavior ##

Omnisharp server starts. 

## Actual Behavior ##

Omnisharp server does not start.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.63.2
**C# Extension**: 1.24.0

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.24.0|
|docomment|k--kato|0.1.30|
|githistory|donjayamanne|0.6.19|
|markdown-image-size|bierner|0.0.4|
|remote-containers|ms-vscode-remote|0.209.6|
|remote-ssh|ms-vscode-remote|0.70.0|
|remote-ssh-edit|ms-vscode-remote|0.70.0|
|sort-js-object-keys|zengxingxin|1.0.6|
|terraform|hashicorp|2.18.0|
|vscode-docker|ms-azuretools|1.18.0|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.3.6|
|vscode-markdownlint|DavidAnson|0.45.0|
|vscode-sort|henriiik|0.2.5|
|vscode-yaml|redhat|1.3.0|;

</details>

**Comment by filipw** [comment]
did you set `omnisharp.useModernNet` to `true`? it seems like it is not set.

**Comment by spotnick** [comment]
I have the same error here. Without useModernNet Omnisharp loads but with the option enabled I receive the above error.

**Comment by filipw** [comment]
the O# server is not bundled into the extension but acquired at first run – perhaps it did not download correctly or was interrupted. an extension reinstall may help.

**Comment by nilzzzzzz** [comment]
Hi, i have the same issue (only when `omnisharp.useModernNet` is set to `true`)  and tried uninstalling/reinstalling the extension.

**Comment by JoeRobich** [comment]
@spotnick @nilzzzzzz Do you have the x64 or the arm64 build of the SDK installed? Both will run on a arm64 Mac but you will need to use the arm64 build with the C# extension.

**Comment by nilzzzzzz** [comment]
@JoeRobich that was the right hint. I uninstalled the x64 and installed the arm64 version and now everything is working. I had the x64 installed because i restored the backup of my old mac.

 Thank you!

**Comment by filipw** [comment]
Thans for confirming. Then the behavior is really as expected for now and this issue can be closed. 

There is a separate issue tracking the ability to acquire x64 build on arm64 here https://github.com/OmniSharp/omnisharp-vscode/issues/5035#issuecomment-1026088935

**Comment by spotnick** [comment]
@JoeRobich hmm I still have the same issue. Just installed the arm64 version from vsix and received the following after restarting vscode:

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/Users/t<user>.vscode/extensions/ms-dotnettools.csharp-1.24.0/.omnisharp/1.38.0-net6.0/OmniSharp.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by JoeRobich** [comment]
@spotnick That is odd. Could you uninstall the C# extension and reinstall. Seems like there was an incomplete download of O#.

**Comment by spotnick** [comment]
@JoeRobich after reinstalling it from the extensionspanel I got again the following error:

```

OmniSharp server started with .NET 6.0.101
.
    Path: /Users/<user>/.vscode/extensions/ms-dotnettools.csharp-1.24.0/.omnisharp/1.38.0-net6.0/OmniSharp.dll
    PID: 30726

Unhandled exception. System.BadImageFormatException: Could not load file or assembly '/Users/<user>.vscode/extensions/ms-dotnettools.csharp-1.24.0/.omnisharp/1.38.0-net6.0/OmniSharp.dll'. An attempt was made to load a program with an incorrect format.

File name: '/Users/<user>/.vscode/extensions/ms-dotnettools.csharp-1.24.0/.omnisharp/1.38.0-net6.0/OmniSharp.dll'

```

I uninstalled it, relaunched vscode again, installed the extension and I could see that the arm64 extension was installed in the logs but again, the above error occured. 

My settings are these: 

```json
    "omnisharp.useModernNet": true,
    "omnisharp.useGlobalMono": "always",
```

**Comment by filipw** [comment]
Reinstalling the extension would not help. It sounds like on your path you have the emulated x64 dotnet. Extension pulls in arm64 OmniSharp which is correct for your architecture, but then in your setup `dotnet` command seems to be pointing to x64 dotnet SDK.

This thread lists the steps you need to go through to move from x64 dotnet to arm64 dotnet SDK https://github.com/dotnet/sdk/issues/21686. Basically, with how it was done by the SDK team for .NET 6 timeframe, you would need to uninstall all SDKs and start from scratch. From now, on ARM devices, arm64 SDKs would go to the default dotnet path, while x64 ones would go to a dedicated x64 folder.

**Comment by spotnick** [comment]
> Reinstalling the extension would not help. It sounds like on your path you have the emulated x64 dotnet. Extension pulls in arm64 OmniSharp which is correct for your architecture, but then in your setup `dotnet` command seems to be pointing to x64 dotnet SDK.
> 
> This thread lists the steps you need to go through to move from x64 dotnet to arm64 dotnet SDK [dotnet/sdk#21686](https://github.com/dotnet/sdk/issues/21686). Basically, with how it was done by the SDK team for .NET 6 timeframe, you would need to uninstall all SDKs and start from scratch. From now, on ARM devices, arm64 SDKs would go to the default dotnet path, while x64 ones would go to a dedicated x64 folder.

Thanks! I will try that :-)

**Comment by spotnick** [comment]
@filipw now I reinstalled .net 6 with the arm version and set the global PATH to the arm version but Omnisharp keeps displaying this error now:

`[ERROR] Error: Found dotnet version 5.0.404. Minimum required version is 6.0.100.`

this is what `dotnet` gives me:

![image](https://user-images.githubusercontent.com/10115809/152492002-96a70a45-e330-474e-9f2c-60b5f83c73e9.png)

**Comment by filipw** [comment]
check if you don't have `"omnisharp.dotnetPath"` setting set to a custom path, if you do clear it.
The C# extension simply executes `dotnet --version` to determine the version of dotnet on your PATH https://github.com/OmniSharp/omnisharp-vscode/blob/fc0c72037be40ba346216cf56e1a0ccb526fb5ec/src/omnisharp/OmniSharpDotnetResolver.ts#L30

If it resolves to 5.0.404 it indicates that your VS Code process still sees the wrong dotnet on your PATH (or is started with wrong PATH settings) but this is not something the C# extension can solve.

**Comment by spotnick** [comment]
@filipw  Yeah you are totally right. Somehow my dotnet is still pointing to the wrong version...

![image](https://user-images.githubusercontent.com/10115809/152532148-93a8e182-0940-471e-818d-af8099567b0c.png)

I need to figure out how I can change this. I followed the steps above but somehow this does not work. Well maybe I'll find a solution somehow. Thanks a lot!

**Comment by victorcappa** [comment]
Tried everything, but what seems to have solved the issue for me was deleting the "omnisharp use modern net" from the .json settings.

**Comment by filipw** [comment]
you need to make sure you do not have emulated x64 dotnet installed, but native arm64 dotnet

**Comment by BQgot** [comment]
I have the same problem,
my solution if you use dotnet-sdk-6.0.300-win-x64 and net framework 4.7.1-devpack via VS Code 1.62.2:
in settings.json:
"omnisharp.useModernNet": true,
"omnisharp.dotnetPath": "[your dotnet.exe path]/dotnet"

**Comment by SaIG** [comment]
Had the same issue ... and when installing the C# extension of vsCode it always downloaded the x64 version despite me having installed the arm64 dotnet version and deleted the x64 version. 

Check if you have the old intel vscode version installed 
![Bildschirmfoto 2022-05-28 um 12 01 44](https://user-images.githubusercontent.com/3542194/170820596-3160c988-8ebf-435e-b7e0-6dcb1a55acf7.png)
It said Intel here for me first so thats why he downloaded the x64 omisharp tools after updating to the "apple branch" of vscode it said apple there and it downloaded the correct arm64 version of it.

hope this helps!

**Comment by hassandaru** [comment]
> 

how do you do that? shifting it to the arm64 i mean. i cant see that option in reinstall options. only shows 1.24.4

**Comment by SaIG** [comment]
Just uninstall and download & install the Apple silicon version :)[image](https://user-images.githubusercontent.com/3542194/192699854-15f39d69-222e-40f4-8883-7456f45dbca3.jpeg)

**Comment by yveshwang** [comment]
It helped with the following steps. If like me, you have transferred from an older mbp to m1s...

* uninstalled omni-sharp vscode extension
* delete the previously downloaded extension in your home directory for example `~/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-x86`
* reinstall
* see that `~/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-arm64` or another arm64 based extension is downloaded and installed.

**Comment by tomdohnal** [comment]
For me (on an M1 MacBook), the problem was that I had mistakenly installed the x64 `dotnet` instead of the Arm64 one.
The fix was to:
1) Delete the current `dotnet`:
```
sudo rm -r /usr/local/share/dotnet
sudo rm -r /etc/dotnet
```
2) Re-install `dotnet` (Arm64 version), (https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.402-macos-arm64-installer)
3) Restart VSCode

**Comment by estevaoMG** [comment]
@jonathaneckman 

Thanks!


My problem allowed installing the C# extension version for 1.24.

**Comment by shpsyte** [comment]
> For me (on an M1 MacBook), the problem was that I had mistakenly installed the x64 `dotnet` instead of the Arm64 one. The fix was to:
> 
> 1. Delete the current `dotnet`:
> 
> ```
> sudo rm -r /usr/local/share/dotnet
> sudo rm -r /etc/dotnet
> ```
> 
> 2. Re-install `dotnet` (Arm64 version), (https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.402-macos-arm64-installer)
> 3. Restart VSCode

That was absolutely 100% and right!

**Comment by shanekunz** [comment]
> It helped with the following steps. If like me, you have transferred from an older mbp to m1s...
> 
> * uninstalled omni-sharp vscode extension
> * delete the previously downloaded extension in your home directory for example `~/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-x86`
> * reinstall
> * see that `~/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-arm64` or another arm64 based extension is downloaded and installed.

This fixed it for me. I did reinstall vs code also, I may have not been on the arm64/apple silicon version of vs code originally, so that may have been why that directory existed in the first place.
