### ISSUE TITLE
Output tab in VSCode does not show cyrillic symbols

### ISSUE THREAD

**Issue by tvardero** [OmniSharp/omnisharp-vscode#5009]
## Issue Description ##
Omnisharp does not show cyrillic output correctly in VSCode output tab, unknown symbol is shown (rombus with '?' on it).
Been occuring both with dotnet 5 and dotnet 6.0.1.
Win10, ru-RU

This issue also had been written in VSCode repo: https://github.com/microsoft/vscode/issues/139985
They asked to reach out you first.

## Steps to Reproduce ##
To make omnisharp write something to the output tab you can:
1. Delete /obj folder
2. When omnisharp prompts you to run 'dotnet restore' - accept it.
3. In output tab it is.

## Expected Behavior ##
Cyrillic symbols

## Actual Behavior ##
Only latin and numeric symbols are handled ok.

## Logs ##
No logs.

## Environment information ##

**VSCode version**: 1.63.2
**C# Extension**: 1.23.17

<details><summary>Dotnet Information</summary>
����� SDK ��� .NET (��ࠦ��騩 �� global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

�।� �믮������:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.17|
|gitlens|eamodio|11.7.0|
|markdown-all-in-one|yzhang|3.4.0|
|test-adapter-converter|ms-vscode|0.1.5|
|vsc-material-theme|Equinusocio|33.2.2|
|vsc-material-theme-icons|equinusocio|2.2.1|
|vscode-language-pack-ru|MS-CEINTL|1.63.3|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-test-explorer|hbenl|2.21.1|;

</details>

**Comment by tvardero** [comment]
![image](https://user-images.githubusercontent.com/45442278/149818423-6711c780-aa9e-409c-9c04-3164883f9411.png)

Also just did notice, reporting this issue using command palette made some symbols go '?' rombus here.

**Comment by filipw** [comment]
this is the same issue as https://github.com/OmniSharp/omnisharp-roslyn/issues/1763 (even though that one was marked as "test runner issue").

I think we should close this here since it's duplicate and not an extension problem but an internal Omnisharp server issue.
