### ISSUE TITLE
Use Roslyn 4.0.1 instead of 4.0.0-6.final

### ISSUE THREAD

**Issue by JosefPihrt** [OmniSharp/omnisharp-vscode#5022]
## Issue Description ##

Hi,

I noticed that currently used version of Roslyn is 4.0.0-6.final whereas there is 4.0.1. Are there any reason to reference pre-release version?

## Environment information ##

**VSCode version**: 1.63.2
**C# Extension**: 1.24.0

**Comment by JoeRobich** [comment]
That just happened to be the version of Roslyn that O# was using at the time of its release. O# has already [updated to 4.0.1](https://github.com/OmniSharp/omnisharp-roslyn/blob/b4042a7389a5492ce5a892576a8df91d31488367/build/Packages.props#L10) and we are [working on moving it to 4.1.0-3](https://github.com/OmniSharp/omnisharp-roslyn/pull/2329).

**Comment by JosefPihrt** [comment]
Thanks for answer.

Is my understanding correct that O# was updated to 4.0.1 but the new version of C# extension for VS Code has not been release yet?

**Comment by filipw** [comment]
yes correct

**Comment by JosefPihrt** [comment]
Thanks for answer.
