### ISSUE TITLE
`new()` is colored as if it's a method call

### ISSUE THREAD

**Issue by AradAlvand** [OmniSharp/omnisharp-vscode#5030]
## Issue Description ##
C# 9.0 introduced a feature called "target-typed `new` expressions" — see [this](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/target-typed-new) — which is simply the ability to omit the type name after the `new` keyword if it can be inferred from the context. So, for example:
```csharp
SomeClass instance = new();
```

## Expected Behavior ##
Since `new` is a keyword, it should have the color of a keyword (blue, in the default theme), just like in Visual Studio:

![image](https://user-images.githubusercontent.com/26527405/151677254-1f29b655-3f9f-4cb9-8c27-2b73f7e4eba1.png)

## Actual Behavior ##
but it's colored as if it's method call expression in VSCode

![image](https://user-images.githubusercontent.com/26527405/151677224-e9663ab0-d9d0-4024-a20a-99ed6332d1de.png)
With the type specified:

![image](https://user-images.githubusercontent.com/26527405/151677238-e7b9600d-68d6-4331-84a3-517cebf06386.png)

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.63.2
**C# Extension**: 1.24.0

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-rename-tag|formulahendry|0.1.9|
|csharp|ms-dotnettools|1.24.0|
|default-material-dark-theme|yuchiu2002|0.0.4|
|EditorConfig|EditorConfig|0.16.4|
|gitlens|eamodio|11.7.0|
|material-icon-theme|PKief|4.12.1|
|mssql|ms-mssql|1.12.0|
|polacode-2019|jeff-hykin|0.5.2|
|prettier-vscode|esbenp|9.2.0|
|prisma|Prisma|3.8.1|
|sass-indented|syler|1.8.18|
|subtitles-editor|pepri|1.1.6|
|svelte-vscode|svelte|105.10.0|
|svg|jock|1.4.15|
|volar|johnsoncodehk|0.31.1|
|vscode-graphql|GraphQL|0.3.41|
|vscode-m3u|af4jm|1.0.0|
|vscode-scss|mrmlnc|0.10.0|
|vscode-typescript-next|ms-vscode|4.6.20220128|
|vscode-yaml|redhat|1.3.0|;

</details>

**Comment by AradAlvand** [comment]
Can anybody please respond? Thanks.

**Comment by filipw** [comment]
You need to enable semantic highlighting for this to work correctly

```
    "csharp.semanticHighlighting.enabled": true,
    "editor.semanticHighlighting.enabled": true,
```

The default highlighting rules are quite primitive and regex based, and are not maintained here but in https://github.com/dotnet/csharp-tmLanguage and are included by default by VS Code independently from this extension.

**Comment by AradAlvand** [comment]
@filipw I have semantic highlighting enabled, but this issue still exists:

![image](https://user-images.githubusercontent.com/26527405/161269296-18023b1d-7287-46ed-b17f-53d76145ef4d.png)

![image](https://user-images.githubusercontent.com/26527405/161269377-ada9ce54-0ec3-4f23-92c5-d1f96b61903e.png)

Am I doing anything wrong?!

**Comment by wise0704** [comment]
Only if you set colouring for `plainKeyword` semantic token or `"keyword"` textmate scope.

Then there is no way to differentiate the `new` keyword from any other keyword since the `plainKeyword` token is overused for literally every single keyword except control keywords, let alone the `new` type modifier which correctly works with textmate scope `"source.cs storage.modifier.cs"`.

Target-typed `new` should also be scoped correctly as `"source.cs keyword.other.new.cs"`.

FYI, `new()` is currently classified as:
- semantic `plainKeyword` (= textmate `"keyword"`)
- textmate `"source.cs entity.name.function.cs"`

`new Type()` is currently classified as:
- semantic `plainKeyword` (= textmate `"keyword"`)
- textmate `"source.cs keyword.other.new.cs"`

**Comment by wise0704** [comment]
With quick testing I could fix this by changing `#object-creation-expression-with-parameters` in csharp.tmLanguage.json

from
```
(?x)
(new)\s+
(?<type_name>
  (?:
    (?:
      (?:(?<identifier>@?[_[:alpha:]][_[:alnum:]]*)\s*\:\:\s*)? # alias-qualification
      (?<name_and_type_args> # identifier + type arguments (if any)
        \g<identifier>\s*
        (?<type_args>\s*<(?:[^<>]|\g<type_args>)+>\s*)?
      )
      (?:\s*\.\s*\g<name_and_type_args>)* | # Are there any more names being dotted into?
      (?<tuple>\s*\((?:[^\(\)]|\g<tuple>)+\))
    )
    (?:\s*\?\s*)? # nullable suffix?
    (?:\s* # array suffix?
      \[
        (?:\s*,\s*)* # commata for multi-dimensional arrays
      \]
      \s*
      (?:\?)? # arrays can be nullable reference types
      \s*
    )*
  )
)\s*
(?=\()
```

to
```
(?x)
(new)(?:\s+
(?<type_name>
  ...
))?\s*
(?=\()
```.
