### ISSUE TITLE
Disable terminal output each time a c# project is opened

### ISSUE THREAD

**Issue by hichemfantar** [OmniSharp/omnisharp-vscode#5032]
1. Start any c# project, I mainly open unity projects
This wasn't a thing before, now It's very annoying.

## Environment data
`dotnet --info` output: 6.0.101
VS Code version: 1.63.2
C# Extension version: 1.24.0

## OmniSharp log
"
Installing C# dependencies...
Platform: win32, x86_64

Finished
"

## Actual behavior
![image](https://user-images.githubusercontent.com/34947993/151709372-fbacb7bd-9e5b-4efc-a8f5-d47c24fdd77f.png)

**Comment by TheBinaryGuy** [comment]
I can confirm that this has been happening recently, even for non-C# projects.

For example, this is a NextJs project:

![image](https://user-images.githubusercontent.com/13674136/151802235-06ff4d09-ed16-4f87-ac8f-0dd610c91ffe.png)

**Comment by onionhammer** [comment]
This is pretty annoying... pops up every time I open a workspace

**Comment by shoaibshakeel381** [comment]
+1
This is incredly annoying when you have to open vscode multiple times

**Comment by TheOnlyWei** [comment]
Each time I open vs code, I have to wait for it to finish output logging before I can switch to terminal and run a quick console command. Please fix this.

**Comment by babysnakes** [comment]
Same here, It doesn't need to be a project. Just starting new empty VS code project causes this message to appear ...
