### ISSUE TITLE
There doesn't seem to be a way to suppress static analyzer's warnings and some reformatting rules

### ISSUE THREAD

**Issue by vmelamed** [OmniSharp/omnisharp-vscode#5033]
I am sorry if this is not the right place to ask, but it seems that there is no way to suppress/enforce some warnings from the static analyzer, e.g. "use explicit types instead of vars". Also, some of the formatting rules are also not accessible from the configuration, e.g. insisting on prepending calls to functions with returning values with discards if they are not assigned, or wrapping one-liners with braces.

If I am wrong can you please point me to the right documentation?

**Comment by filipw** [comment]
OmniSharp supports regular editorconfig files https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022

**Comment by vmelamed** [comment]
Awesome! Thank you!
