### ISSUE TITLE
[Question] How to change format settings for C# code?

### ISSUE THREAD

**Issue by altwarg** [OmniSharp/omnisharp-vscode#5036]
I would like to know how can I change format settings for brackets, prefer "this" and other options that I can change on Visual Studio.

**Comment by JoeRobich** [comment]
The C# extension supports configuring formatting options in an .editorconfig file. You can see details at https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options?view=vs-2022. Here is the configuration for [newline before brace](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/formatting-rules#csharp_new_line_before_open_brace).

**Comment by altwarg** [comment]
Thanks, I figured it out.

.editorconfig will always work. And we also can use generated Visual Studio .editorconfig.
