### ISSUE TITLE
C# dotnet command show ???? text after run

### ISSUE THREAD

**Issue by sonpn82** [OmniSharp/omnisharp-vscode#5052]
Issue Type: <b>Bug</b>

Running simple dotnet command such as: dotnet -h result in many ??? text as below:

sdk-options:
  -d|--diagnostics  ?? ??? ?????.
  -h|--help         ??? ???? ?????.
  --info            .NET ??? ?????.
  --list-runtimes   ??? ???? ?????.
  --list-sdks       ??? SDK? ?????.
  --version         ?? ?? .NET SDK ??? ?????.

How can I see the ??? text?

Extension version: 1.24.0
VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:16:22.147Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (6.64GB free)|
|Process Argv|--open-url --crash-reporter-id d8c4bc19-b15e-4837-9092-95cdb0b3c7a2 --crash-reporter-id d8c4bc19-b15e-4837-9092-95cdb0b3c7a2 -- vscode:extension/ms-dotnettools.csharp|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vscop940:30404999
vsrem710:30416614

```

</details>

**Comment by JoeRobich** [comment]
@sonpn82 Looks like maybe there is an encoding mismatch with your terminal.  You can see information for all the dotnet CLI options at https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet.
