### ISSUE TITLE
The Output window & C# log always shown whenever opening a .net core C# project

### ISSUE THREAD

**Issue by cateyes99** [OmniSharp/omnisharp-vscode#5055]
## Environment data
VS Code version: **_1.63.2_**, **_1.64.2_**
C# Extension version: **_1.24.0_**

Each time, whenever a .net core C# project is opened, it always open up the **Output** window & show **C# log** on it, as shown below. The previous versions don't have this behaviour which is quite annoying.
![image](https://user-images.githubusercontent.com/19678455/153537831-251aa282-e39d-4d7d-83ca-c16ce650dc77.png)

**Comment by filipw** [comment]
This is a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/5032 which was fixed in https://github.com/OmniSharp/omnisharp-vscode/pull/5041
