### ISSUE TITLE
Suppor for single .cs (.csx) file

### ISSUE THREAD

**Issue by DomenPigeon** [OmniSharp/omnisharp-vscode#5062]
## Steps to reproduce
Open a *.cs file with VS Code.

## Expected  behavior
Get autocompletion for the script.

## Actual behavior
There is no autocompletion.

## Why?
It would be really nice if this would be supported, because it would really bring .net scripting to the next level.
I could write script fast and efficiently and the use the `dotnet script` command to run them, avoiding all the soultion mesiness.
Just doing simple stuff in C# super fast and easy.

**Note:** if I open a C# solution and then open a cs script which is not in the solution, everything is already working :).

## How could this work wihtout solution?
Because .NET 6 already introduced that you don't have to have an actual `Main` function in order to run a console app, I believe all the support should already be there.
These scripts would just behave as if there is an .NET 6 console project soution in "the background".

## Extra
If I could run the code without saving it to the file that would be even more awesome, then C# would feel like an interprete language.

**Comment by filipw** [comment]
`dotnet script` is already supported, what does not work for you?

**Comment by DomenPigeon** [comment]
Hi filipw, thanks for the answer, like I have mentioned above, when opening a .cs (.csx) file in vscode without a solution, autocompletion is not working for me.

**Comment by filipw** [comment]
Can you please provide the OmniSharp log then?

Individual `.cs` files are indeed not supported - they require a project file to define the framework and references as prescribed by normal C# applications. But `.csx` files have been supported since the beginning of OmniSharp.

**Comment by DomenPigeon** [comment]
Sorry for my lack of knowledge, but I have googled and looked at the documentation of this repo and didn't find a way how to get OmniSharp logs. If you can tell where I can find them I will send to you.

Otherwise the steps for this are really simple, I have installed VSCode, and added the C# extension 
![image](https://user-images.githubusercontent.com/35853390/154857841-6744c1a2-0db1-4a7a-8bb5-8b3c3f7711ba.png)

Then if I create a `.csx` file with VSCode or outside VSCode and go and edit it, I don't get autocompletion. I only get autocompletion if I open a cs project.

I have also tried on my brothers computer (Mac) and it also doesn't work.

I also discovered your scriptcsRunner extension, it didn't work with that either.

Anything I have tried so far, was not working. And it's a clean install of VSCode on a resetted computer. Maybe I am lacking some depencies of the C# extension or something like that.

**Comment by filipw** [comment]
You can find the logs under View > Output > OmniSharp Log.

When using dotnet script make sure to run `dotnet script init` in the script folder to bootstrap OmniSharp correctly https://github.com/filipw/dotnet-script#scaffolding

**Comment by DomenPigeon** [comment]
I have run the command `dotnet script init` in a new folder:
![image](https://user-images.githubusercontent.com/35853390/154859028-8caeac23-faf8-45da-934d-6dbc1d03070e.png)

Still no autocomplete support:
![image](https://user-images.githubusercontent.com/35853390/154859056-844ea37d-dceb-48fb-870d-7c7acc6e978e.png)

When I have opened the logs they were empty. I tried restaring OmniSharp via command palett, nothing happened.
I tried analyzing current project, then I go this error:
![image](https://user-images.githubusercontent.com/35853390/154859426-2a984082-a823-42fc-b45a-e542b5ad7244.png)

**Comment by filipw** [comment]
You should not just open the individual file in VS Code into the edit mode - the way the C# extension works (and really all other language extensions too), you need to launch VS Code, and open the folder containing the file instead.

**Comment by DomenPigeon** [comment]
Oh I see, I am very sorry for the inconvenience and my inexperience ...
Thank you very much for your time and effort.
And thank you for all your work on the Omnisharp and `dotnet script` project I like it very much :D.

Will be closing thing issue now.

If you maybe have one more minute I still get this error:
![image](https://user-images.githubusercontent.com/35853390/154861181-31763be5-c16a-4440-a2e3-c83a0964d922.png)

**Comment by filipw** [comment]
thanks!
