### ISSUE TITLE
intellisense doesn't work in vs code for unity

### ISSUE THREAD

**Issue by leozhang1** [OmniSharp/omnisharp-vscode#5074]
Hello there,

I have .net 6 sdk installed and have configured all the settings mentioned in the vs code extension yet Im still getting these errors. I am on windows 10.

here's my error message:
```
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
c:\Users\Leo Zhang\Documents\GitHub\ARHW1\VuforiaPackageTests.csproj
C:\Program Files\dotnet\sdk\6.0.102\Microsoft.Common.CurrentVersion.targets(1217,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\User1\Documents\GitHub\ARHW1\UnityEngine.UI.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\User1\Documents\GitHub\ARHW1\VuforiaScripts.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\User1\Documents\GitHub\ARHW1\Assembly-CSharp.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\User1\Documents\GitHub\ARHW1\UnityEditor.UI.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\User1\Documents\GitHub\ARHW1\VuforiaEditorScripts.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\User1\Documents\GitHub\ARHW1\Assembly-CSharp-Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\User1\Documents\GitHub\ARHW1\VuforiaPackageTests.csproj
```

**Comment by SupinePandora43** [comment]
Set `useModernNet` to `false`

**Comment by JoeRobich** [comment]
For Unity development it is recommended you install the Visual Studios MSBuild Tools from https://visualstudio.microsoft.com/downloads/. Scroll to the bottom of the page and expand the Tools for Visual Studio 2022 section. Also, as mentioned earlier you will need to use the Full Framework version of OmniSharp by setting `omnisharp.useModernNet` to `false`.

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/611219/155569528-da6a9f88-e08a-4a43-9f30-b3c605d33b0e.png">

**Comment by leozhang1** [comment]
The instructions in VS code says set omnisharp.useModernNet to true for .net 6 builds tho. Also I am trying to avoid using visual studio and just use vs code. Can you please show me how I can do that? Thanks.

**Comment by esklarski** [comment]
> The instructions in VS code says set omnisharp.useModernNet to true for .net 6 builds tho. Either way, I tried setting it to false and it didn't work. Also I am trying to avoid using visual studio and just use vs code. Can you please show me how I can do that? Thanks.

Try closing VS Code and Unity, then open your project folder and delete the .sln and .csproj files therein. Next open the project in Unity and once that loads reopen VS Code. I find nuking those files and forcing a regen is the only thing that ever works for me.

**Comment by JoeRobich** [comment]
> The instructions in VS code says set omnisharp.useModernNet to true for .net 6 builds tho. Either way, I tried setting it to false and it didn't work. 

Unless there have been recent changes, Unity projects are not .NET SDK projects. The net6 build of OmniSharp will not load Full Framework projects. 

> Also I am trying to avoid using visual studio and just use vs code. Can you please show me how I can do that? Thanks.

The reason you need the Visual Studio MSBuild Tools is to get a build environment that supports .NET 4.7.1 Full Framework projects.

**Comment by leozhang1** [comment]
> > The instructions in VS code says set omnisharp.useModernNet to true for .net 6 builds tho. Either way, I tried setting it to false and it didn't work. Also I am trying to avoid using visual studio and just use vs code. Can you please show me how I can do that? Thanks.
> 
> Try closing VS Code and Unity, then open your project folder and delete the .sln and .csproj files therein. Next open the project in Unity and once that loads reopen VS Code. I find nuking those files and forcing a regen is the only thing that ever works for me.

That didn't work for me, but it was definitely worth trying thanks.

**Comment by leozhang1** [comment]
> > The instructions in VS code says set omnisharp.useModernNet to true for .net 6 builds tho. Either way, I tried setting it to false and it didn't work.
> 
> Unless there have been recent changes, Unity projects are not .NET SDK projects. The net6 build of OmniSharp will not load Full Framework projects.
> 
> > Also I am trying to avoid using visual studio and just use vs code. Can you please show me how I can do that? Thanks.
> 
> The reason you need the Visual Studio MSBuild Tools is to get a build environment that supports .NET 4.7.1 Full Framework projects. The C# extension does not support all Full Framework project types out of the box.

That's unfortunate that the extension doesn't support it yet, but I'm sure the team is working hard! I installed the msbuild tools like you said and though I'm not entirely sure if that fixed the issue, the visual studio ide did redirect me to this link ```https://dotnet.microsoft.com/en-us/download/visual-studio-sdks?utm_source=getdotnetsdk&utm_medium=referral``` after telling me that I have v4.6.1 and that vuforia uses v4.7.1, so I went ahead and got that and now intellisense is working again in vs code despite a new error: ```[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.6.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
c:\Users\User1\Documents\GitHub\ARHW1\Assembly-CSharp-Editor.csproj``` it seems I cant please everyone, but at least intellisense is back, so I'm good for now. Thanks.
