### ISSUE TITLE
Dependency update is workspace agnostic

### ISSUE THREAD

**Issue by ProphetLamb** [OmniSharp/omnisharp-vscode#5076]
# Steps to reproduce
1. Open VSCode
    1. without a workspace, 
    2. or with any non C# workspace. 

We expect the C# extension to do nothing.

But what actually happens is:

2. VSCode output window for "C#" opens.
4. Dependency check and subsequent installation is performed

When working with a rust or js project, this is but a mildly infuriating annoyance, on a Windows machine with dotnet installed.

```
Installing C# dependencies...
Platform: win32, x86_64

Finished
```

The real problem arises when working with a Linux system where no dotnet is installed. The C# extension attempts to start, using up an unreasonable amount of CPU time and displaying a very much annoying and inappropriate error message. That it failed to locate the dotnet sdk.

The C# extension is not required in an empty, rust, tex, js or any other non C# workspace and thus should - according to the [VSCode extension guidelines](https://code.visualstudio.com/api/references/extension-guidelines) not install unrelated software, or even initialize anything at all. That should be delayed until the extension is actually required.

## Why is this an issue?

The user is unable to prevent the extension from acting. Disabling the extension is really an option, because we need the extension in other projects. Even the "disable in workspace" option does not solve the problem, because by the time we have navigated to the settings, the extension is already doing its thing.

## Solution

Delay loading the extension dependencies until required by the workspace. Believe in workspaces.

**Comment by JoeRobich** [comment]
@ProphetLamb Our extension limits activation based on the [activation events](https://code.visualstudio.com/api/references/activation-events) that are declared in our package.json.

https://github.com/OmniSharp/omnisharp-vscode/blob/65c110a03b0ca2f97a897d71996e46f30f5235bb/package.json#L544-L564

The `Log (Extension Host)` in the VS Code Output pane should list the reason that the `ms-dotnettools.csharp` extension was activated.

```
[2022-02-25 10:40:50.170] [exthost] [info] ExtensionService#_doActivateExtension ms-dotnettools.csharp, startup: false, activationEvent: 'onLanguage:csharp'
```

Perhaps you can identify which events are triggering the activation in your workspaces.

**Comment by ProphetLamb** [comment]
@JoeRobich Thanks for the info on where to look for the activation events. Excerpt from the log
```
[...]
[2022-02-28 10:40:08.560] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.test-adapter-converter, startup: true, activationEvent: '*', root cause: hbenl.vscode-test-explorer
[2022-02-28 10:40:08.563] [exthost] [info] ExtensionService#_doActivateExtension ms-dotnettools.csharp, startup: true, activationEvent: '*', root cause: josefpihrt-vscode.roslynator 

[...]

[2022-02-28 10:40:10.917] [exthost] [info] ExtensionService#_doActivateExtension hbenl.vscode-test-explorer, startup: true, activationEvent: '*', root cause: Swellaby.vscode-rust-test-adapter
[2022-02-28 10:40:10.953] [exthost] [info] ExtensionService#_doActivateExtension josefpihrt-vscode.roslynator, startup: true, activationEvent: '*'
```
The way I am reading the log. The log implies that the `roslynator` analyzer extension caused `ms-dotnettools` to start. Now the question is why did ` josefpihrt-vscode.roslynator` start. That would then be an issue for the mentioned extension.
Am I reading this correctly?

**Comment by JoeRobich** [comment]
That is correct. Looks like the extension launches whenever VS Code does. See https://github.com/JosefPihrt/Roslynator/blob/master/src/VisualStudioCode/package/package.json#L37-L39

Closing this out as it is unrelated to our extension.
