### ISSUE TITLE
Typing `/*` unfolds everything below cursor

### ISSUE THREAD

**Issue by lonix1** [OmniSharp/omnisharp-vscode#5078]
## Environment data
dotnet version: 6.0.102
VS Code version: 1.64.2
C# Extension version: 1.24.0

## OmniSharp log
n/a

## Steps to reproduce
- fold a .cs document
- place cursor above folded block
- type `/*`

## Expected  behavior
Nothing should happen.

## Actual behavior
Folded blocks beneath the cursor are unfolded.

**Comment by JoeRobich** [comment]
@lonix1 This is a tough problem. Without the closing comment characters being present, it turns the rest of the file into one large comment block. If you are consistently running into this, the best workaround would be to select the range you want to comment out and use the "Toggle Block Comment" command.

**Comment by lonix1** [comment]
What I've done is made this mistake 1000 times, so I've trained myself to (usually) type `*/` first, and then `/*`. :laughing:

I take it from your answer that this is "by design"? Thanks and feel free to close.

(It sure is annoying though, happens every day.)

**Comment by lonix1** [comment]
Wait one more question. I realise this is a dirty hack (!), but what if the code folder waits, e.g. 1000 ms, for the second part `*/`. Only then it unfolds everything?
