### ISSUE TITLE
.csx file not working 

### ISSUE THREAD

**Issue by colinfang** [OmniSharp/omnisharp-vscode#5081]
## Issue Description ##

`csx` not working. Full of erros e.g.

Predefined type 'System.Object' is not defined or imported [main.csx]

However it works with normal projects (`cs` with `csproj`)

## Steps to Reproduce ##

- Ceate a project via `dotnet script init`
- Open VS Code on the folder (only 2 files, `main.csx` & `omnisharp.json`

```
# omnisharp.json
{
  "script": {
    "enableScriptNuGetReferences": true,
    "defaultTargetFramework": "net6.0"
  }
}
```

settings

```
    "omnisharp.enableRoslynAnalyzers": true,
    "omnisharp.useModernNet": true,
```

### OmniSharp log ###
Starting OmniSharp server at 27/02/2022, 00:18:13
    Target: c:\Users\colin\tmp2

OmniSharp server started with .NET 6.0.102
.
    Path: c:\Users\colin\.vscode\extensions\ms-dotnettools.csharp-1.24.0\.omnisharp\1.38.0-net6.0\OmniSharp.dll
    PID: 18120

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 10.0.19044.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: .NET Core SDK 6.0.102 17.0.0 - "C:\Program Files\dotnet\sdk\6.0.102\"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 6.0.102 17.0.0 - "C:\Program Files\dotnet\sdk\6.0.102\"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\colin\tmp2'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\colin\tmp2'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Found 1 CSX files.
[info]: OmniSharp.Script.ScriptContextProvider
        Searching for compilation dependencies with the fallback framework of 'net6.0'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Added CSX project 'c:\Users\colin\tmp2\main.csx' to the workspace.
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\colin\tmp2' on host 23232.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No symbol found. File: c:\Users\colin\tmp2\main.csx, Line: 1, Column: 20.
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 1.
Received response for /v2/getcodeactions but could not find request.

## Environment information ##

**VSCode version**: 1.64.2
**C# Extension**: 1.24.0

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.102
 Commit:    02d5242ed7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.102\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by filipw** [comment]
This was fixed in https://github.com/OmniSharp/omnisharp-roslyn/pull/2290 
It will ship in extension 1.24.1.

**Comment by colinfang** [comment]
@filipw  Fantastic. Just installed 1.24.1 pre-release and it works!
