### ISSUE TITLE
No syntax highlighting in XML document tag after Omnisharp is loaded

### ISSUE THREAD

**Issue by ultimaweapon** [OmniSharp/omnisharp-vscode#5086]
## Issue Description ##

Before Omnisharp is loaded (initialization in progress):
![Screenshot from 2022-03-03 11-02-02](https://user-images.githubusercontent.com/3048307/156494388-0fb74482-e86a-4ad5-8705-3645de46b0c9.png)

After Omnisharp is loaded:
![Screenshot from 2022-03-03 11-02-14](https://user-images.githubusercontent.com/3048307/156494512-3b5ca6a6-7893-4af3-b1e4-963a71b72310.png)

## Steps to Reproduce ##

Just waiting for Omnisharp to load.

## Expected Behavior ##

XML document tag should have syntax highlighting.

## Actual Behavior ##

No syntax highlighting for XML document tag.

### OmniSharp log ###

<details>
Starting OmniSharp server at 3/3/2022, 11:01:51 AM
    Target: PATH_TO_SOLUTION

OmniSharp server started with .NET 6.0.102
.
    Path: /home/ultimaweapon/.vscode/extensions/ms-dotnettools.csharp-1.24.1/.omnisharp/1.38.1-net6.0/OmniSharp.dll
    PID: 5904

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Unknown 0.0 (Unknown)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to /usr/share/dotnet/dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: .NET Core SDK 6.0.102 17.0.0 - "/usr/share/dotnet/sdk/6.0.102/"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 6.0.102 17.0.0 - "/usr/share/dotnet/sdk/6.0.102/"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'PATH_TO_SOLUTION'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'PATH_TO_PROJECT'

...

[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'PATH_TO_SOLUTION_DIR'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'PATH_TO_SOLUTION_DIR' on host 5711.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: PATH_TO_PROJECT
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'PATH_TO_PROJECT'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'PATH_TO_PROJECT'

...

[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PROJECT_NAME

...

[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 630.
</details>

### C# log ###

Blank

## Environment information ##

**VSCode version**: 1.64.2
**C# Extension**: 1.24.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.102
 Commit:    49861cb924

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.102/

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.102 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|autoconf|maelvalais|0.1.0|
|cpptools|ms-vscode|1.8.4|
|csharp|ms-dotnettools|1.24.1|
|go|golang|0.31.1|
|i18n-ally|lokalise|2.8.1|
|latex-workshop|James-Yu|8.23.0|
|ooxml-viewer|yuenm18|1.2.0|
|rust|rust-lang|0.7.8|
|vala|prince781|1.0.5|
|vetur|octref|0.35.0|
|vscode-antlr4|mike-lischke|2.2.4|
|vscode-github-actions|me-dutour-mathieu|3.0.1|
|vscode-yaml|redhat|1.4.0|;

</details>

**Comment by nunofachada** [comment]
This is related with issue #3816

**Comment by ultimaweapon** [comment]
Looks exactly the same. I'll close mine.
