### ISSUE TITLE
Option needed to disable autocompletion

### ISSUE THREAD

**Issue by tilkinsc** [OmniSharp/omnisharp-vscode#5090]
When I am typing code, I will press `.` on a known variable, likely one that omnisharp hasnt detected yet or there is a compilation error, and it just dumps out whatever long class it can detect. I hate it. I force myself to use tab to autocomplete because I am tired of editors inserting crap when I press enter and having to smack esc thousands of times after every little thing I enter. It's annoying. Especially if its something such as code shortcuts dumping blocks of code.

**Comment by JoeRobich** [comment]
@tilkinsc Perhaps one of these VS Code setting will help you: `editor.acceptSuggestionOnEnter`, `editor.acceptSuggestionOnCommitCharacter`, `editor.suggestOnTriggerCharacters` ([see docs](https://code.visualstudio.com/docs/editor/intellisense#_settings))

You can even scope the settings to the c# language like so in your settings.json:
```json
    "[csharp]": {
        "editor.acceptSuggestionOnEnter": false,
        "editor.acceptSuggestionOnCommitCharacter": false,
        "editor.suggestOnTriggerCharacters": false
    }
```

**Comment by tilkinsc** [comment]
Solution was
"editor.acceptSuggestionOnCommitCharacter": false,
