### ISSUE TITLE
My System Get Very Slow After updating to last version of VS Code

### ISSUE THREAD

**Issue by abdollahkahne** [OmniSharp/omnisharp-vscode#5091]
Issue Type: <b>Bug</b>

I am not sure what is the source of this performance difficulties but after updating VS Code and running the dotnet run my system get very slow or even locked the screen totally. I am using Omnisharp Extension for C# and also .NET SDK 6.0.200 too which is responsible for executing the dotnet run command in my ubuntu.

Extension version: 1.24.1
VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:36.248Z)
OS version: Linux x64 5.13.0-30-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 370  @ 2.40GHz (4 x 1599)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|3.64GB (0.11GB free)|
|Process Argv|--unity-launch --crash-reporter-id 020e1364-b40c-422c-98be-c370c1a3b40a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
testflightcf:30433671
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrt:30448491
vsrem710:30416614
dsvsc009:30440023
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmc:30438804
vscgsvidc:30447482
helix:30440343

```

</details>

**Comment by abdollahkahne** [comment]
I do not reported this to VS Code Repository. If it is necessary please let me know. Thanks

**Comment by abdollahkahne** [comment]
Since I am not sure this issue be related to this extension I already hold it to be sure about it. Thank you

**Comment by lonix1** [comment]
Seems the same as in my [issue](https://github.com/OmniSharp/omnisharp-vscode/issues/5085).

I'm also on ubuntu, same versions of vscode and o# as you.

**Comment by valderrey** [comment]
I have the same problem in windows with vscode

**Comment by lonix1** [comment]
@abdollahkahne @valderrey Do you find also that something like searching for file is slow? If you use <kbd>CTRL p</kbd> and try open a file, even that is slow to find the file?

**Comment by lonix1** [comment]
I also noticed even saving a file <kbd>ctrl s</kbd> takes more time, like 1-2 seconds. Before it was almost instant.

**Comment by abdollahkahne** [comment]
> I also noticed even saving a file ctrl s takes more time, like 1-2 seconds. Before it was almost instant.

I see this from about one month ago (After upgrading from .Net 5 to .Net 6). It happens for me, usually for file with much lines of code . Personally I see it for files with more than 200 lines of code. It is related to beautifying the codes (.Net Formatter)

**Comment by lonix1** [comment]
I hope that [this PR](https://github.com/OmniSharp/omnisharp-vscode/pull/5089) will fix it.

**Comment by lonix1** [comment]
Debugging is also VERY slow.

**Comment by abdollahkahne** [comment]
I close this issue as I think my problem already is resolved. Thanks for following.

**Comment by lonix1** [comment]
What did you do to fix it?

**Comment by abdollahkahne** [comment]
> What did you do to fix it?

I am not sure my problem is same as other but I propose some general tips:
* The first thing I should mention here is that I am using Visual Code Debian version and not the snap one which install automatically if we install it using `dotnet apt install code `(run command `snap list` to see if code is snap or debian).
* I decrease size of my workspace. It included more than 30 .Net project with lots of assets. I try to create the workspace specific to my current solutions/projects. 
* I also have trouble with project picker in omnisharp in the same time. I tries to manually install the `vsix` of a beta version (I do not remember what was the version I think it was 1.23.18 Beta [Link](https://github.com/OmniSharp/omnisharp-vscode/issues/4955)  )
May be my projects are not big enough to see errors again. It would be great to test the project that have problem for others.

**Comment by lonix1** [comment]
Thanks for the tips!

**Comment by abdollahkahne** [comment]
@lonix1 
Today I encounter the problem again. I just copy a large Div from Google results with lots of css style and html elements inside and then save it. It shows Formatting before save for a while and I close the message. Also even after deleting it the message that shows again the message since it can not completed the last format and save (it shows them on index.razor__virtual.html yet) .After closing the code and re-opening it, the problem was fixed. I also find out that there is a setting in visual code regarding formatter which makes formatting specific to modification only which may be help your case (The default is on file).
![image](https://user-images.githubusercontent.com/48277995/162628310-b9fc0c80-dbea-4d05-a605-f74ce7695573.png)
