### ISSUE TITLE
Unexpected 'await' at top of other suggestions

### ISSUE THREAD

**Issue by DanteMarshal** [OmniSharp/omnisharp-vscode#5096]
## Environment data
`dotnet --info` output:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.405     
 Commit:    63325e1c7d  
Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.19044
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.405\
Host (useful for support):
  Version: 5.0.14
  Commit:  d5b56c6327
.NET SDKs installed:
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.402 [C:\Program Files\dotnet\sdk]
  5.0.405 [C:\Program Files\dotnet\sdk]
.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
VS Code version: 1.65.0
C# Extension version: v1.24.1

## Steps to reproduce
1. When C# Extension is enabled, open a C# code and try to index an array with, let's say, `i`
2. Trigger suggestions (either automatically or manually by the key binding)

## Expected  behavior
Since it's the simplest possible suggestion, `i` should be the first

## Actual behavior
There's this weird `await` keyword suggestions that appears first. This happened on different circumstances, not just when indexing arrays; but this one was the one I could reproduce.
![image](https://user-images.githubusercontent.com/17954172/156999437-3a73473a-872a-40fd-be0c-f95fa1fe7b79.png)
Note that it's not a snippet suggestion, cuz the snippet setting (put snippets at the bottom, after other suggestions) is not fixing this.

**Comment by scriptwelder** [comment]
I'm experiencing the same issue - reverting to 1.24.0 helps for now

**Comment by JuanPixelatto** [comment]
Same here

**Comment by leebailey88** [comment]
Yes, this is a very frustrating issue. Makes writing a simple for loop difficult as the `i` gets auto-replaced to await constantly. Even worse, it also adds `async` in front of the function

**Comment by JoeRobich** [comment]
A fix depends on this change getting into Roslyn and then O#. https://github.com/dotnet/roslyn/pull/60197

**Comment by tasty0tomato** [comment]
Seems fix in the latest version.

**Comment by filipw** [comment]
Fixed by https://github.com/OmniSharp/omnisharp-roslyn/pull/2363
