### ISSUE TITLE
MIssing dll?  /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-1.24.1/.omnisharp/1.38.1-net6.0/OmniSharp.dll

### ISSUE THREAD

**Issue by andygemis** [OmniSharp/omnisharp-vscode#5097]
## Issue Description ##
Trying to use omnisharp with vscode .devcontainer Dockerfle "6.0-bullseye-slim"
Have .vscode/settings.json with

{
"omnisharp.useModernNet": true,
}

When devconatiner/vs code start up - get 

```
OmniSharp server started with .NET 6.0.200
 (/usr/bin/dotnet).
    Path: /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-1.24.1/.omnisharp/1.38.1-net6.0/OmniSharp.dll
    PID: 455

Could not execute because the specified command or file was not found.

```

Performing ls - the /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-1.24.1/.omnisharp/1.38.1-net6.0 is empty

```
vscode ➜ /workspaces/somedir $  ls /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-1.24.1/.omnisharp/1.38.1-net6.0 -la
total 8
drwxr-xr-x 2 vscode vscode 4096 Mar  7 17:04 .
drwxr-xr-x 4 vscode vscode 4096 Mar  7 17:04 ..

vscode ➜ /workspaces/somedir $  ls /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-1.24.1/.omnisharp -la
total 16
drwxr-xr-x  4 vscode vscode 4096 Mar  7 17:04 .
drwxr-xr-x 12 vscode vscode 4096 Mar  7 17:04 ..
drwxr-xr-x  6 vscode vscode 4096 Mar  7 17:04 1.38.1
drwxr-xr-x  2 vscode vscode 4096 Mar  7 17:04 1.38.1-net6.0


vscode ➜ /workspaces/somedir $ ls /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-1.24.1/.omnisharp/1.38.1 -la
total 40
drwxr-xr-x 6 vscode vscode  4096 Mar  7 17:04 .
drwxr-xr-x 4 vscode vscode  4096 Mar  7 17:04 ..
drwxr-xr-x 2 vscode vscode  4096 Mar  7 17:04 bin
drwxr-xr-x 3 vscode vscode  4096 Mar  7 17:04 etc
-rw-r--r-- 1 vscode vscode     0 Mar  7 17:04 install.Lock
drwxr-xr-x 3 vscode vscode  4096 Mar  7 17:04 lib
-rw-r--r-- 1 vscode vscode  1104 Mar  7 17:04 license.md
drwxr-xr-x 3 vscode vscode 12288 Mar  7 17:04 omnisharp
-rwxr-xr-x 1 vscode vscode   590 Mar  7 17:04 run

```

## Steps to Reproduce ##

Using windows, wsl2, docker.
.devconatiner\Dockerfile  using 6.0-bullseye-slim
.devcomatiner.json has 
	"extensions": [
		"ms-dotnettools.csharp",
 }

.vscode/settings.json has 

{
  "omnisharp.useModernNet": true,
}

(As trying to debugging the .net xunit tests without the  useModernNet  produces errors over  DirectoryNotFoundException  /usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error MSB3883: Unexpected exception 
I **ASSUME**  these are because I need to enable to useModernNet to true.

## Expected Behavior ##
omnisharp to start up/be able to debug .net 6 xunit test

## Actual Behavior ##
Errors on omnisharp startup

### OmniSharp log ###
<details>

```
Starting OmniSharp server at 3/7/2022, 5:38:15 PM
    Target: /workspaces/fhir-facade-infrastructure/fhir-facade-infrastructure.sln

OmniSharp server started with .NET 6.0.200
 (/usr/bin/dotnet).
    Path: /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-1.24.1/.omnisharp/1.38.1-net6.0/OmniSharp.dll
    PID: 2304

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-1.24.1/.omnisharp/1.38.1-net6.0/OmniSharp.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

</details>

## Environment information ##

**VSCode version**: 1.65.0
**C# Extension**: 1.24.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.200/

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.200 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.24.1|
|gitlens|eamodio|12.0.1|
|markdown-all-in-one|yzhang|3.4.0|
|markdown-link-updater|mathiassoeholm|2.1.2|
|prettier-vscode|esbenp|9.3.0|
|rest-client|humao|0.24.6|
|vscode-docker|ms-azuretools|1.20.0|
|vscode-env|IronGeek|0.1.0|
|vscode-markdownlint|DavidAnson|0.46.0|;

</details>

**Comment by JoeRobich** [comment]
@andygemis It sounds like there must have been an error when downloading the net6 build of OmniSharp. Can you share the C# Log from the VS Code Output pane?

**Comment by andygemis** [comment]
Sorry - didn't spot this.

```
Installing C# dependencies...
Platform: linux, x86_64, name=debian, version=11

Downloading package 'OmniSharp for Linux (.NET 6 / x64)' Failed at stage: downloadPackage
Error: Failed to establish a socket connection to proxies: ["PROXY 127.0.0.1:9000"]

```

Our network/proxy/infrastructure must be doing something strange (again).

 
I'll try downloading/extracting the "OmniSharp for Linux (.NET 6 / x64)" from

https://github.com/OmniSharp/omnisharp-vscode/blob/v1.24.1/package.json

(https://roslynomnisharp.blob.core.windows.net/releases/1.38.1/omnisharp-linux-x64-net6.0-1.38.1.zip)

Sorry for wasting your time.

**Comment by JoeRobich** [comment]
@andygemis It is never a waste of time to offer help. In the future we plan to ship the net6 build in our extension so it isn't an additional download. Reply back if you have any issues getting that build setup.
