### ISSUE TITLE
Problem with OmniSharp...

### ISSUE THREAD

**Issue by MahouEcho** [OmniSharp/omnisharp-vscode#5099]
I'm a student and one of these day I had a error with OmniSharp I don't know what cause the error or when exactly it happened but because of the error Intellisense is not working at all. Which is for me quite a problem since I'm trying to learn C#.

Here is the error I get when I launch vscode or a project. 
![OmniSharp_error](https://user-images.githubusercontent.com/49239448/157158268-1c3268a9-ec21-458c-b5af-203efbf8848a.PNG)

and after a long time I will get a timeout error. 

Also I did try to do a OmniSharp restart and I get this error, "[ERROR] Attempt to restart OmniSharp server failed because another server instance is starting." I don't know if it help or not but I figure it did hurt to try.

vscode version: 1.65.0(user setup)
C# extension version: v.1.24.1
and here is my dotnet --info :
![dotnet_version](https://user-images.githubusercontent.com/49239448/157158473-fa1da076-c777-4f0c-acf6-088d5130eb12.PNG)

If I forgot to give some info please tell me and I will try to provide it as fast as possible. Would help me a lot if this error get fix.
If it's not possible to fix than I will just do a factory reset of my pc and start fresh.
Thank you in advance. Also sorry if I'm posting at the wrong place.

**Comment by JoeRobich** [comment]
A pre-release is now available with this change. https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.24.2-beta1
