### ISSUE TITLE
Graceful shutdown when ending debugging?

### ISSUE THREAD

**Issue by winzig** [OmniSharp/omnisharp-vscode#5100]
Currently when you call "Stop Debugging," omnisharp just kills the process, giving the process no way to gracefully shutdown (or debug the graceful shutdown process). 

Previously this was brought up in #4263, but the issue was closed with no solution.

Subsequent to that, the vscode team implemented a global solution in https://github.com/microsoft/vscode/issues/54384.

It seems that if omnisharp would tie into the work the vscode team has done, graceful shutdown should be possible now?

**Comment by gregg-miskelly** [comment]
This is tracked with https://github.com/OmniSharp/omnisharp-vscode/issues/4533

**Comment by winzig** [comment]
@gregg-miskelly  OK I've read #4533 now and don't understand the status of it... it starts out being closed, then is reopened, and then several ideas are mentioned, but doesn't seem like there's a consensus. Also, there's no mention of the solution the vscode team developed in https://github.com/microsoft/vscode/issues/54384. Is that because they didn't realize vscode team did that, or because they don't like that solution, or something else? Thanks!

**Comment by gregg-miskelly** [comment]
@winzig it is a proposed feature that tracks the scenario that you are requesting -- somehow support a graceful shutdown of the target app. Somehow incorporating the changes from https://github.com/microsoft/vscode/issues/54384 seems likely to be the right way to go, at least if the target process was running at the time. Though the debugger team would need to investigate more to say for sure if that approach would work, and on what OSs.
