### ISSUE TITLE
coreclr debug configuration should support input variables for `envFile`

### ISSUE THREAD

**Issue by karolz-ms** [OmniSharp/omnisharp-vscode#5102]
VS Code has a mechanism called "input variables" where debug configuration values can be resolved by running arbitrary commands, picking an item from predefined list, or prompting the user: https://code.visualstudio.com/docs/editor/variables-reference#_input-variables 

Node.js and Python debug configuration providers support this mechanism. Unfortunately, `coreclr` seems to lack this support. 

## Repro steps
1. Create a debug configuration that uses an input variable, for example

```jsonc
{
    "configurations": [
        {
            "name": "Debug API",
            "type": "coreclr",
            "request": "launch",
            // other properties as necessary
            "envFile": "${input:getPathToFile}"
        }
    ],
    "inputs": [
        {
            "id": "getPathToFile",
            "type": "promptString"
             // The really interesting/important case is type==command.
             // promptString is used just to simplify the repro
         }
    ]
}
``` 

2. Try using the configuration

## Expected result
Should prompt the user for the path to the `.env` file

## Actual result
```text
Can't parse envFile ${input:getPathToFile} because of Error: ENOENT: no such file or directory, open '${input:getPathToFile}'
```

**Comment by gregg-miskelly** [comment]
The C# extension does support 'inputs', except for `envFile`. I am not sure if it would be possible for `envFile` to support `inputs` or not -- we handle `envFile` in our configuration resolver, which runs before inputs are completed. I don't know if we can push it to a later stage.

**Comment by karolz-ms** [comment]
Well, Node and Python do support input variables for `envFile`, so maybe C# can do that too. 

Maybe @connor4312 can help by explaining how it is done, or point us to relevant code in JS debugger extension?

**Comment by gregg-miskelly** [comment]
I don't think how it is done in the JS debugger will be relevant -- we __could__ make this work by reimplementing `envFile` natively in our debug adapter. But if there isn't a good way to solve this without doing that I think we would probably just "Won't Fix" this bug.

**Comment by connor4312** [comment]
js-debug handles it at launch time, but you could also change this extension to resolve envFile after variables are substituted via the relatively-new [post-substitution method](https://github.com/microsoft/vscode/blob/f407da25ec62fc82d8f038eb4ae0df1fe8ff246a/src/vscode-dts/vscode.d.ts#L13648-L13661) in the resolver.

**Comment by karolz-ms** [comment]
@gregg-miskelly we came to the point in our schedule where we will need this, so I am going to try to come up with a PR if that is OK with you

**Comment by gregg-miskelly** [comment]
@karolz-ms Sounds great
