### ISSUE TITLE
Launching always first project in multiroot project

### ISSUE THREAD

**Issue by adamijak** [OmniSharp/omnisharp-vscode#5106]
## Issue Description ##
Code seems to be ingoring project I am launching using its launch.json . It always launches first project in the multiroot workspace.
Projects are azure functions with generated launch.json and tasks.json

## Expected Behavior ##
Launch the project I selected.

## Actual Behavior ##
Launches first project in multiroot project.

## Environment information ##

**VSCode version**: 1.65.2
**C# Extension**: 1.24.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.102
 Commit:    49861cb924

Runtime Environment:
 OS Name:     fedora
 OS Version:  35
 OS Platform: Linux
 RID:         fedora.35-x64
 Base Path:   /usr/lib64/dotnet/sdk/6.0.102/

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  3.1.416 [/usr/lib64/dotnet/sdk]
  5.0.206 [/usr/lib64/dotnet/sdk]
  6.0.102 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|armview|bencoleman|0.4.6|
|azure-account|ms-vscode|0.10.1|
|azure-pipelines|ms-azure-devops|1.195.0|
|azurecli|ms-vscode|0.5.0|
|csharp|ms-dotnettools|1.24.1|
|vscode-azureappservice|ms-azuretools|0.23.1|
|vscode-azurefunctions|ms-azuretools|1.6.0|
|vscode-azureresourcegroups|ms-azuretools|0.4.0|
|vscode-azurestorage|ms-azuretools|0.13.0|
|vscode-azurevirtualmachines|ms-azuretools|0.5.0|
|vscode-cosmosdb|ms-azuretools|0.18.1|
|vscode-docker|ms-azuretools|1.20.0|
|vscode-node-azure-pack|ms-vscode|0.2.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.17|;

</details>

**Comment by gregg-miskelly** [comment]
Thanks! Looks like you already opened an issue in the vscode-azurefunctions repo, which I think is where this belongs (https://github.com/microsoft/vscode-azurefunctions/issues/3077).

Closing as external.
