### ISSUE TITLE
Highlighting is incorrect after project is selected

### ISSUE THREAD

**Issue by LoyalPotato** [OmniSharp/omnisharp-vscode#5116]
## Issue Description ##

When I select a project that I want omnisharp to watch, the colors are all messed up, while another file that omnisharp isn't watching shows correctly (it used to show colors like the right side of the image, even when it was the selected project).
I'm using Material Theme High Contrast from "Equinusocio.vsc-material-theme".

![image](https://user-images.githubusercontent.com/10759876/159046380-466dbc45-1ede-4c37-9c83-6dec5c27c44e.png)

## Steps to Reproduce ##

Install the theme and select a project and see the colors show differently than another one that isn't selected.

## Expected Behavior ##

Colors to not change

## Actual Behavior ##

Colors change when the project is selected.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.65.2
**C# Extension**: 1.24.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.404
 Commit:    72c68b830a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.404/

Host (useful for support):
  Version: 5.0.13
  Commit:  b3afe99225

.NET SDKs installed:
  3.1.405 [/usr/local/share/dotnet/sdk]
  5.0.103 [/usr/local/share/dotnet/sdk]
  5.0.401 [/usr/local/share/dotnet/sdk]
  5.0.404 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|add-reference|adrianwilczynski|1.0.2|
|anaconda-extension-pack|ms-python|1.0.1|
|auto-close-tag|formulahendry|0.5.14|
|autoimport|steoates|1.5.4|
|azure-account|ms-vscode|0.10.1|
|azure-pipelines|ms-azure-devops|1.202.0|
|azurecli|ms-vscode|0.5.0|
|Bookmarks|alefragnani|13.2.4|
|code-settings-sync|Shan|3.4.3|
|csharp|ms-dotnettools|1.24.1|
|csharpextensions|jchannon|1.3.1|
|data-workspace-vscode|ms-mssql|0.1.1|
|dotnet|formulahendry|0.0.4|
|errorlens|usernamehw|3.4.2|
|gitflow|vector-of-bool|1.2.1|
|githistory|donjayamanne|0.6.19|
|gitlens|eamodio|12.0.5|
|gruvbox|jdinhlife|1.5.1|
|html-css-class-completion|Zignd|1.20.0|
|java|redhat|1.4.0|
|JavaScriptSnippets|xabikos|1.8.0|
|markdown-all-in-one|yzhang|3.4.0|
|material-icon-theme|PKief|4.14.1|
|material-theme|zhuangtongfa|3.13.20|
|namespace|adrianwilczynski|1.1.2|
|output-colorizer|IBM|0.1.2|
|project-manager|alefragnani|12.5.0|
|quitcontrol-vscode|artdiniz|4.0.0|
|todo-tree|Gruntfuggly|0.0.215|
|user-secrets|adrianwilczynski|2.0.1|
|vsc-material-theme|Equinusocio|33.4.0|
|vscode-azureappservice|ms-azuretools|0.23.1|
|vscode-azurefunctions|ms-azuretools|1.6.0|
|vscode-azureresourcegroups|ms-azuretools|0.4.0|
|vscode-azurestorage|ms-azuretools|0.13.0|
|vscode-commons|redhat|0.0.6|
|vscode-cosmosdb|ms-azuretools|0.18.1|
|vscode-csharp-snippets|jorgeserrano|1.1.0|
|vscode-dotnet-runtime|ms-dotnettools|1.5.0|
|vscode-eslint|dbaeumer|2.2.2|
|vscode-java-debug|vscjava|0.38.0|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-pull-request-github|GitHub|0.38.1|
|vscode-taskexplorer|spmeesseman|2.9.1|
|vscode-todo-highlight|wayou|1.0.5|
|vscode-yaml|redhat|1.5.1|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by JoeRobich** [comment]
Files present in the OmniSharp workspace are colorized using SemanticHighlighting. Loose C# files outside of the workspace are colorized using the C# textmate grammar since O# doesn't have semantic information for them. If you prefer all files use the C# textmate grammar you can disable `csharp.semanticHighlighting.enabled` in your VS Code settings.

**Comment by LoyalPotato** [comment]
@JoeRobich 
What is the OmniSharp workspace? The project selected?

**Comment by JoeRobich** [comment]
Sorry, yes, the selected project or solution.

**Comment by LoyalPotato** [comment]
That "fixed" it.
Was it changed in a new version? Because previously it showed with c# textmate grammar highlighting (is calling it highlighting correct?) all the time and just recently did it start showing as the SemanticHighlighting.

**Comment by JoeRobich** [comment]
It was changed so that semantic highlighting was the default. The benefits are that you have consistent highlighting that correctly handles new language semantics as they are added to the compiler. The downside is that it is missing some of the textmate grammars more niche classifications. That said, the textmate grammar is well behind in its support of new C# language features.

**Comment by LoyalPotato** [comment]
Oh okay. Thanks for the quick help and explanation :)
