### ISSUE TITLE
Debugger: Pop up exception dialog when click the 'Stop' button during the debug session

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#513]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Steps to reproduce
1 Press F5
2 Press the  "Stop" button before the breakpoint comes to be in break mode

## Expected  behavior
This project should be stop

## Actual behavior
VSCode would pop up an exception dialog
![error](https://cloud.githubusercontent.com/assets/20184778/16485711/fcc32614-3ef2-11e6-8431-12a8e2017549.PNG)

**Comment by wesrupert** [comment]
This fix will be available in the next release.
