### ISSUE TITLE
Omnisharp Server tries to load analyzers from even disabled extensions

### ISSUE THREAD

**Issue by rpavlik** [OmniSharp/omnisharp-vscode#5134]
## Issue Description ##
Per #5029 it seems that the current version is incompatible also with Roslynator 4.1.0. So, I disabled the extension, but it still tries to load it. Even if I install the older 4.0.2 version, because the 4.1.0 version isn't removed from the folder by vscode, it's still trying to be loaded.

(EDIT: is it cached in my project somewhere? Even if I remove the 4.1.0 version and all mentions of it I can find, I get:

```
[fail]: OmniSharp.Services.AssemblyLoader
        An error occurred when attempting to access 'c:/Users/Ryan/.vscode/extensions/josefpihrt-vscode.roslynator-4.1.0/roslyn/analyzers'.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'c:\Users\Ryan\.vscode\extensions\josefpihrt-vscode.roslynator-4.1.0\roslyn\analyzers'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
   at OmniSharp.Services.AssemblyLoader.LoadAllFrom(String folderPath) in D:\a\1\s\src\OmniSharp.Host\Services\AssemblyLoader.cs:line 46
[warn]: OmniSharp.Roslyn.CSharp.Services.ExternalFeaturesHostServicesProvider
        The path 'c:/Users/Ryan/.vscode/extensions/josefpihrt-vscode.roslynator-4.1.0/roslyn/analyzers' is configured in the RoslynExtensionsOptions as the external features source but no assemblies were found at this path.
[fail]: OmniSharp.Services.AssemblyLoader
        An error occurred when attempting to access 'c:/Users/Ryan/.vscode/extensions/josefpihrt-vscode.roslynator-4.1.0/roslyn/refactorings'.
```
EDIT 2: Ah, it got added to "C:\Users\Ryan\.omnisharp\omnisharp.json" somehow. Removed from there fixed it. Not sure if this is still a bug now.
)

## Steps to Reproduce ##

- Install and disable the Roslynator extension.
- Restart the OmniSharp server

## Expected Behavior ##

- Should not crash (but that's #5029, I think) - though not loading a third-party analyzer shouldn't be fatal either...
- Should not attempt to load analyzers from an extension that's disabled.

## Actual Behavior ##

OmniSharp tries to load the Roslynator assemblies anyway, currently crashing because of this.

### OmniSharp log ###
<details>
```
OmniSharp server started.
    Path: c:\Users\Ryan\.vscode\extensions\ms-dotnettools.csharp-1.24.1\.omnisharp\1.38.1\OmniSharp.exe
    PID: 25156

[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded: OmniSharp.Cake
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Cake, Version=1.38.0.0, Culture=neutral, PublicKeyToken=7e5bf7b3b470b509
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded: OmniSharp.DotNetTest
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.DotNetTest, Version=1.38.0.0, Culture=neutral, PublicKeyToken=7e5bf7b3b470b509
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded: OmniSharp.Host
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Host, Version=1.38.0.0, Culture=neutral, PublicKeyToken=7e5bf7b3b470b509
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded: OmniSharp.MSBuild
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.MSBuild, Version=1.38.0.0, Culture=neutral, PublicKeyToken=7e5bf7b3b470b509
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded: OmniSharp.Roslyn
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Roslyn, Version=1.38.0.0, Culture=neutral, PublicKeyToken=7e5bf7b3b470b509
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded: OmniSharp.Roslyn.CSharp
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Roslyn.CSharp, Version=1.38.0.0, Culture=neutral, PublicKeyToken=7e5bf7b3b470b509
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded: OmniSharp.Script
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Script, Version=1.38.0.0, Culture=neutral, PublicKeyToken=7e5bf7b3b470b509
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded: OmniSharp.Shared
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Shared, Version=1.38.0.0, Culture=neutral, PublicKeyToken=7e5bf7b3b470b509
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded from path: c:\Users\Ryan\.vscode\extensions\ms-dotnettools.csharp-1.24.1\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll
[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[dbug]: OmniSharp.CompositionHostBuilder
        .NET SDK requires MSBuild instances version 16.3 or higher
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 5 MSBuild instance(s)
            1: Visual Studio Build Tools 2022 17.1.32319.34 17.1.0 - "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin"
            2: Visual Studio Community 2022 17.1.32319.34 17.1.0 - "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin"
            3: Visual Studio Build Tools 2019 16.11.32228.343 16.11.2 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
            4: Visual Studio Professional 2022 17.2.32210.308 17.2.0 - "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin"
            5: StandAlone 17.1.0 - "c:\Users\Ryan\.vscode\extensions\ms-dotnettools.csharp-1.24.1\.omnisharp\1.38.1\.msbuild\Current\Bin"
[dbug]: OmniSharp.CompositionHostBuilder
        MSBuild instance Visual Studio Build Tools 2022 17.1.32319.34 17.1.0 scored at -2147483648
[dbug]: OmniSharp.CompositionHostBuilder
        MSBuild instance Visual Studio Community 2022 17.1.32319.34 17.1.0 scored at 2
[dbug]: OmniSharp.CompositionHostBuilder
        MSBuild instance Visual Studio Build Tools 2019 16.11.32228.343 16.11.2 scored at 2
[dbug]: OmniSharp.CompositionHostBuilder
        MSBuild instance Visual Studio Professional 2022 17.2.32210.308 17.2.0 scored at -2147483648
[dbug]: OmniSharp.CompositionHostBuilder
        MSBuild instance StandAlone 17.1.0 scored at 1
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2022 17.1.32319.34 17.1.0 - "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin"
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded from path: z:\src\XRPlugin\./NuGet/microsoft.unity.analyzers.1.12.0\Microsoft.Unity.Analyzers.dll
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded from path: c:/Users/Ryan/.vscode/extensions/josefpihrt-vscode.roslynator-4.1.0/roslyn/analyzers\Roslynator.CSharp.Analyzers.CodeFixes.dll
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded from path: c:/Users/Ryan/.vscode/extensions/josefpihrt-vscode.roslynator-4.1.0/roslyn/analyzers\Roslynator.CSharp.Analyzers.dll
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded from path: c:/Users/Ryan/.vscode/extensions/josefpihrt-vscode.roslynator-4.1.0/roslyn/analyzers\Roslynator.Formatting.Analyzers.CodeFixes.dll
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded from path: c:/Users/Ryan/.vscode/extensions/josefpihrt-vscode.roslynator-4.1.0/roslyn/analyzers\Roslynator.Formatting.Analyzers.dll
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded from path: c:/Users/Ryan/.vscode/extensions/josefpihrt-vscode.roslynator-4.1.0/roslyn/refactorings\Roslynator.CSharp.Refactorings.dll
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded from path: c:/Users/Ryan/.vscode/extensions/josefpihrt-vscode.roslynator-4.1.0/roslyn/fixes\Roslynator.CSharp.CodeFixes.dll
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded: Microsoft.CodeAnalysis.Features, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded: Microsoft.CodeAnalysis.CSharp.Features, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded: Microsoft.CodeAnalysis.ExternalAccess.OmniSharp, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
[trce]: OmniSharp.Services.AssemblyLoader
        Assembly loaded: Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.CSharp, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
[trce]: OmniSharp.HostServicesAggregator
        Successfully added Microsoft.Unity.Analyzers, Version=1.12.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a to host service assemblies.
[warn]: OmniSharp.HostServicesAggregator
        Expected to use Roslynator.CSharp.Analyzers.CodeFixes, Version=4.1.0.0, Culture=neutral, PublicKeyToken=926ea54d246a765e in host services but the assembly cannot be loaded due to an exception: Could not load file or assembly 'Roslynator.Workspaces.Common, Version=4.1.0.0, Culture=neutral, PublicKeyToken=926ea54d246a765e' or one of its dependencies. The system cannot find the file specified..
[warn]: OmniSharp.HostServicesAggregator
        Expected to use Roslynator.CSharp.Analyzers, Version=4.1.0.0, Culture=neutral, PublicKeyToken=926ea54d246a765e in host services but the assembly cannot be loaded due to an exception: Could not load file or assembly 'Roslynator.Common, Version=4.1.0.0, Culture=neutral, PublicKeyToken=926ea54d246a765e' or one of its dependencies. The system cannot find the file specified..
[warn]: OmniSharp.HostServicesAggregator
        Expected to use Roslynator.Formatting.Analyzers.CodeFixes, Version=4.1.0.0, Culture=neutral, PublicKeyToken=926ea54d246a765e in host services but the assembly cannot be loaded due to an exception: Could not load file or assembly 'Roslynator.Workspaces.Common, Version=4.1.0.0, Culture=neutral, PublicKeyToken=926ea54d246a765e' or one of its dependencies. The system cannot find the file specified..
[trce]: OmniSharp.HostServicesAggregator
        Successfully added Roslynator.Formatting.Analyzers, Version=4.1.0.0, Culture=neutral, PublicKeyToken=926ea54d246a765e to host service assemblies.
[warn]: OmniSharp.HostServicesAggregator
        Expected to use Roslynator.CSharp.Refactorings, Version=4.1.0.0, Culture=neutral, PublicKeyToken=926ea54d246a765e in host services but the assembly cannot be loaded due to an exception: Could not load file or assembly 'Roslynator.Common, Version=4.1.0.0, Culture=neutral, PublicKeyToken=926ea54d246a765e' or one of its dependencies. The system cannot find the file specified..
[warn]: OmniSharp.HostServicesAggregator
        Expected to use Roslynator.CSharp.CodeFixes, Version=4.1.0.0, Culture=neutral, PublicKeyToken=926ea54d246a765e in host services but the assembly cannot be loaded due to an exception: Could not load file or assembly 'Roslynator.Workspaces.Common, Version=4.1.0.0, Culture=neutral, PublicKeyToken=926ea54d246a765e' or one of its dependencies. The system cannot find the file specified..
[trce]: OmniSharp.HostServicesAggregator
        Successfully added Microsoft.CodeAnalysis.Features, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 to host service assemblies.
[trce]: OmniSharp.HostServicesAggregator
        Successfully added Microsoft.CodeAnalysis.CSharp.Features, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 to host service assemblies.
[trce]: OmniSharp.HostServicesAggregator
        Successfully added Microsoft.CodeAnalysis.ExternalAccess.OmniSharp, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 to host service assemblies.
[trce]: OmniSharp.HostServicesAggregator
        Successfully added Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.CSharp, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 to host service assemblies.
[trce]: OmniSharp.HostServicesAggregator
        Successfully added Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to host service assemblies.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
   at OmniSharp.OmniSharpWorkspace..ctor(HostServicesAggregator aggregator, ILoggerFactory loggerFactory, IFileSystemWatcher fileSystemWatcher) in D:\a\1\s\src\OmniSharp.Roslyn\OmniSharpWorkspace.cs:line 53
   at lambda_method(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.TypedParts.ActivationFeatures.DisposalFeature.<>c__DisplayClass0_0.<RewriteActivator>b__0(LifetimeContext c, CompositionOperation o)
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext outermostLifetimeContext, CompositeActivator compositionRootActivator)
   at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract contract, Object& export)
   at System.Composition.CompositionContext.GetExport(CompositionContract contract)
   at System.Composition.CompositionContext.GetExport[TExport](String contractName)
   at OmniSharp.Stdio.Host.Initialize() in D:\a\1\s\src\OmniSharp.Stdio\Host.cs:line 58
   at OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource) in D:\a\1\s\src\OmniSharp.Stdio\Host.cs:line 53
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1() in D:\a\1\s\src\OmniSharp.Stdio.Driver\Program.cs:line 74
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass146_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<ExecuteAsync>d__157.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at OmniSharp.HostHelpers.Start(Func`1 action) in D:\a\1\s\src\OmniSharp.Host\HostHelpers.cs:line 30
```
</details>

## Environment information ##

**VSCode version**: 1.65.2
**C# Extension**: 1.24.1

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  5.0.406 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|adb-filesystem|MakotoHamanaka|0.0.3|
|android-system-tools|flimberger|0.0.2|
|arm|dan-c-underwood|1.7.4|
|asciidoctor-vscode|asciidoctor|2.9.8|
|auto-comment-blocks|kevinkyang|1.0.1|
|azure-account|ms-vscode|0.10.1|
|azure-pipelines|ms-azure-devops|1.202.0|
|bash-beautify|shakram02|0.1.1|
|better-comments|aaron-bond|2.1.0|
|better-cpp-syntax|jeff-hykin|1.15.13|
|better-toml|bungcip|0.3.2|
|cargo-inspect|cargo-inspect-vscode|0.1.0|
|cargo-toml-snippets|kevinkassimo|0.1.1|
|change-case|wmaurer|1.0.0|
|chordpro|ricardomfmsousa|0.2.0|
|clang-format|mjohns|1.10.0|
|cmake|twxs|0.0.17|
|cmake-format|cheshirekow|0.6.11|
|cmake-tools|ms-vscode|1.10.5|
|cmantic|tdennis4496|0.9.0|
|code-gnu-global|austin|0.2.2|
|code-groovy|marlon407|0.1.2|
|cortex-debug|marus25|1.4.4|
|cpptools|ms-vscode|1.9.7|
|cpptools-extension-pack|ms-vscode|1.1.0|
|cpptools-themes|ms-vscode|1.0.0|
|crates|serayuzgur|0.5.10|
|crates-completer|jedeop|1.2.1|
|csharp|ms-dotnettools|1.24.1|
|debian-vscode|dawidd6|0.1.2|
|debug|webfreak|0.25.1|
|dot|Stephanvs|0.0.1|
|dotenv|mikestead|1.0.1|
|dotnet|formulahendry|0.0.4|
|dotnet-core-essentials|KishoreIthadi|0.0.8|
|doxdocgen|cschlosser|1.4.0|
|easy-snippet-maker|tariky|0.0.6|
|EditorConfig|EditorConfig|0.16.4|
|editorconfiggenerator|nepaul|0.2.1|
|fish-ide|lunaryorn|0.4.0|
|fish-vscode|skyapps|0.2.1|
|font-switcher|evan-buss|4.0.3|
|git-graph|mhutchie|1.30.0|
|git-project-manager|felipecaputo|1.8.2|
|gitconfig|sidneys1|2.0.1|
|githistory|donjayamanne|0.6.19|
|gitlab-ci-validator|cstuder|1.0.0|
|gitlab-mr|jasonn-porch|1.4.3|
|gnuplot|mammothb|1.0.5|
|gnuplot|MarioSchwalbe|1.0.11|
|gradle-language|naco-siren|0.2.3|
|graphql-for-vscode|kumar-harsh|1.15.3|
|graphviz-preview|EFanZh|1.5.0|
|gremlins|nhoizey|0.26.0|
|haml|karunamurti|1.4.0|
|hexeditor|ms-vscode|1.9.5|
|html-preview-vscode|tht13|0.2.5|
|inf|bagetx|0.0.1|
|jinja|wholroyd|0.0.8|
|jupyter|ms-toolsai|2022.2.1030672458|
|jupyter-keymap|ms-toolsai|1.0.0|
|jupyter-renderers|ms-toolsai|1.0.6|
|kconfig|luveti|1.0.3|
|khr-reflow-vsc|ryanpavlik|1.0.1|
|Kotlin|mathiasfrohlich|1.7.1|
|language-gettext|mrorz|0.2.0|
|linux-desktop-file|nico-castell|0.0.18|
|markdown-all-in-one|yzhang|3.4.0|
|mermaid-markdown-syntax-highlighting|bpruitt-goddard|1.2.3|
|meson|asabil|1.3.0|
|msbuild-project-tools|tintoy|0.4.3|
|ninja|surajbarkale|0.0.1|
|npm-intellisense|christian-kohler|1.4.1|
|openscad-format|AlexEaton|1.0.1|
|pdf|tomoki1207|1.2.0|
|plantuml|jebbs|2.17.2|
|platformio-ide|platformio|2.4.3|
|postscript|mxschmitt|1.0.1|
|prettier-java|dotdevru|0.1.1|
|prettier-vscode|esbenp|9.5.0|
|proto|peterj|0.0.2|
|python|ms-python|2022.2.1924087327|
|rainbow-csv|mechatroner|2.2.0|
|rech-editor-batch|rechinformatica|0.0.19|
|reflow-markdown|marvhen|2.1.0|
|reflow-paragraph|TroelsDamgaard|1.3.0|
|remote-containers|ms-vscode-remote|0.231.0|
|remote-ssh|ms-vscode-remote|0.76.1|
|remote-ssh-edit|ms-vscode-remote|0.76.1|
|remote-wsl|ms-vscode-remote|0.64.2|
|restructuredtext|lextudio|183.0.0|
|rewrap|stkb|1.16.3|
|rnc|russillglover|0.0.1|
|ruby|rebornix|0.28.1|
|rust-analyzer|matklad|0.2.993|
|rust-mod-generator|ZhangYue|1.0.10|
|scad|efbenson|1.0.1|
|shader|slevesque|1.1.5|
|shell-format|foxundermoon|7.2.2|
|shellcheck|timonwong|0.18.10|
|simple-rst|trond-snekvik|1.5.2|
|sleighighlight|CarloMaragno|0.0.3|
|solargraph|castwide|0.23.0|
|sort-lines|Tyriar|1.9.1|
|strict-whitespace|sidp|0.0.2|
|systemd-unit-file|coolbear|1.0.6|
|targetframeworksswitcher|yamachu|1.0.3|
|template-finder|Artymaury|1.3.3|
|terraform|hashicorp|2.21.0|
|todo-tree|Gruntfuggly|0.0.215|
|toml|be5invis|0.6.0|
|troff|ban|1.0.22|
|tslint|eg2|1.0.47|
|unity-debug|Unity|3.0.2|
|unity-find-in-prefabs|jarvisjiang|1.0.8|
|unity-tools|Tobiah|1.2.12|
|vdf|GEEKiDoS|0.0.7|
|vscode-catch2-test-adapter|matepek|4.0.26|
|vscode-circuitpython|joedevivo|0.1.16|
|vscode-color|anseki|0.4.5|
|vscode-commons|redhat|0.0.6|
|vscode-docker|ms-azuretools|1.21.0|
|vscode-drawio|hediet|1.6.4|
|vscode-eslint|dbaeumer|2.2.2|
|vscode-gn|npclaudiu|1.1.0|
|vscode-graphql|GraphQL|0.3.53|
|vscode-hexdump|slevesque|1.8.1|
|vscode-html-css|ecmel|1.11.0|
|vscode-icalendar|af4jm|1.0.1|
|vscode-icons|vscode-icons-team|11.10.0|
|vscode-inline-values-powershell|TylerLeonhardt|0.0.5|
|vscode-jest|Orta|4.2.1|
|vscode-lldb|vadimcn|1.7.0|
|vscode-make|technosophos|1.0.2|
|vscode-markdownlint|DavidAnson|0.46.0|
|vscode-npm-script|eg2|0.3.24|
|vscode-open-in-github|ziyasal|1.3.6|
|vscode-proto3|zxh404|0.5.5|
|vscode-pull-request-github|GitHub|0.38.1|
|vscode-pylance|ms-python|2022.3.3|
|vscode-qt-for-python|seanwu|1.1.7|
|vscode-ruby|wingrunr21|0.28.0|
|vscode-rufo|jnbt|0.0.5|
|vscode-status-bar-format-toggle|tombonnike|3.0.0|
|vscode-typescript-tslint-plugin|ms-vscode|1.3.3|
|vscode-yaml|redhat|1.6.0|
|xdg-open-explorer|Ottomated|0.1.1|
|xml|DotJoshJohnson|2.5.1|
|xslt-xpath|deltaxml|1.2.2|;

</details>

**Comment by filipw** [comment]
> EDIT 2: Ah, it got added to "C:\Users\Ryan.omnisharp\omnisharp.json" somehow. Removed from there fixed it. Not sure if this is still a bug now.

This is not a bug. This is a global file to control the server behavior. Looks like the external extension you used modified this file, thus globally affecting OmniSharp server behavior. This is independent on enabling/disabling extension in VS Code. It would have affected e.g. the analyzers that are loaded in OmniSharp extension in Vim too, if you started that on your machine.
