### ISSUE TITLE
1.24.2 ; so, when will it come to vscode? 

### ISSUE THREAD

**Issue by saeed-barari** [OmniSharp/omnisharp-vscode#5136]
hey, sorry if I'm writing this in the issue section, but I didn't find any conversation section anywhere ... is there a discord by the way?

**Comment by filipw** [comment]
There is a slack org, you can join here https://github.com/OmniSharp/omnisharp-roslyn#help-wanted 
There is normally a release ~ once a month. The beta is available to install already from here https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.24.2-beta3
