### ISSUE TITLE
[ERROR] Error: OmniSharp server load timed out

### ISSUE THREAD

**Issue by heartacker** [OmniSharp/omnisharp-vscode#5138]
## Environment data
名称: C#
ID: ms-dotnettools.csharp
说明: C# for Visual Studio Code (powered by OmniSharp).
版本: 1.24.2
发布者: Microsoft
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp

版本: 1.67.0-insider (system setup)
提交: 909602cf04e0fa42528d692676d0d4e15e67bba2
日期: 2022-03-31T11:00:49.798Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22581

## OmniSharp log
```
Starting OmniSharp server at 2022/3/31 23:41:22
    Target: d:\heart\Git\ATC.sln\ATC.GUI.sln

OmniSharp server started with .NET 6.0.201
.
    Path: c:\Users\heart\.vscode-insiders\extensions\ms-dotnettools.csharp-1.24.2\.omnisharp\1.38.2-net6.0\OmniSharp.dll
    PID: 4204

�޷�ִ�У���Ϊ�Ҳ���ָ����������ļ���
���ܵ�ԭ�����:
  *���õ� dotnet ����ƴд����
  *�����ִ�� .NET ���򣬵� dotnet-"c:\Users\heart\.vscode-insiders\extensions\ms-dotnettools.csharp-1.24.2\.omnisharp\1.38.2-net6.0\OmniSharp.dll" �����ڡ�
  *���������ȫ�ֹ��ߣ�����·�����Ҳ������д�������ǰ׺Ϊ dotnet �Ŀ�ִ���ļ���
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```

**Comment by heartacker** [comment]
when `"omnisharp.useModernNet": true`

**Comment by filipw** [comment]
This was fixed in https://github.com/OmniSharp/omnisharp-vscode/pull/5122
You can try the beta https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.24.2-beta3
