### ISSUE TITLE
OmniSharp doesn't look for "exclude" in project.json under "buildOptions": "compile" or "embed"

### ISSUE THREAD

**Issue by kjbetz** [OmniSharp/omnisharp-vscode#514]
## Environment data
`dotnet --info` output: 
```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
```

VS Code version: `1.2.1`
C# Extension version: `1.2.0`

## Steps to reproduce

In Asp.Net Core 1.0.0 (RTM) project `exclude` has been deprecated from `project.json`. The warning given is this: `warning DOTNET1015: The 'exclude' option is deprecated. Use 'exclude' within 'compile' or 'embed' instead.`

I moved my `exclude` under `compile`.

## Expected  behavior

That OmniSharp will work and look in `buildOptions:` `compile` or `embed` for the `exclude`.

## Actual behavior

It doesn't and I encountered this error: https://github.com/OmniSharp/omnisharp-vscode/issues/362 due to `node_modules`.

----

For the time being, I've re-added `"exclude": [ "node_modules" ]` back into my `project.json` at the root level.

Thank you!

**Comment by DustinCampbell** [comment]
Hi! Thanks for the report. This is being tracked by https://github.com/OmniSharp/omnisharp-vscode/issues/422.
