### ISSUE TITLE
C# v1.24.2 omnisharp/OmniSharp.exe"': No such file or directory.

### ISSUE THREAD

**Issue by spdrcd** [OmniSharp/omnisharp-vscode#5140]
## Environment data
`dotnet --info` output:
VS Code version: 1.66.0
C# Extension version: 1.24.2

## OmniSharp log
Starting OmniSharp server at 4/1/2022, 11:50:34 AM
    Target: project location

OmniSharp server started with Mono 6.8.0.
    Path: /Users/{{username}}/.vscode/extensions/ms-dotnettools.csharp-1.24.2-darwin-x64/.omnisharp/1.38.3-beta.31/omnisharp/OmniSharp.exe
    PID: 1898

Cannot open assembly '"/Users/chiehchihchen/.vscode/extensions/ms-dotnettools.csharp-1.24.2-darwin-x64/.omnisharp/1.38.3-beta.31/omnisharp/OmniSharp.exe"': No such file or directory.
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

## Steps to reproduce
update to v1.24.2 on mac, tries to run VScode C# on mac

## Expected  behavior
To be able to run, use intellisense properly without issue

## Actual behavior
Cannot open assembly '"Users/{{username}}/.vscode/extensions/ms-dotnettools.csharp-1.24.2-darwin-x64/.omnisharp/1.38.3-beta.31/omnisharp/OmniSharp.exe"': No such file or directory.
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

**Comment by hansihe** [comment]
Having the same issue

**Comment by filipw** [comment]
According to the logs you are using prerelease of OmniSharp server - `1.38.3-beta.31`. This means you opted into pulling the latest builds from master. Remove the setting `"omnisharp.path":"latest"` from your config and try again.

**Comment by dmackdev** [comment]
I am having the same issue on mac, even with `omnisharp 1.38.2` and `ms-dotnettools.csharp 1.24.2` and `"omnisharp.path":"latest` not present in my `.vscode/settings.json`.

I have installed `ms-dotnettools.csharp 1.24.1` and removed `.vscode/extensions/ms-dotnettools.csharp-1.24.2-darwin-arm64` and this now works. Culprit seems to be latest version of this extension.

**Comment by verbess** [comment]
> According to the logs you are using prerelease of OmniSharp server - `1.38.3-beta.31`. This means you opted into pulling the latest builds from master. Remove the setting `"omnisharp.path":"latest"` from your config and try again.

The same issue was encountered with C# Extension version - `1.24.2`, OmniSharp server - `1.38.2`.  
But C# Extension version - `1.24.1`, OmniSharp server - `1.38.1` works.

## OmniSharp Log
OmniSharp server started with Mono 6.12.0.
    Path: /Users/{{username}}/.vscode/extensions/ms-dotnettools.csharp-1.24.2-darwin-x64/.omnisharp/1.38.2/omnisharp/OmniSharp.exe
    PID: 13348

Cannot open assembly '"/Users/{{username}}/.vscode/extensions/ms-dotnettools.csharp-1.24.2-darwin-x64/.omnisharp/1.38.2/omnisharp/OmniSharp.exe"': No such file or directory.

**Comment by filipw** [comment]
You are right, it's an unfortunate regression. Really sorry about that. 

We have a fix in the making, in the meantime, if you are doing .NET Core development only, you can set `"omnisharp.useModernNet": true` which will opt you into .NET 6 build of OmniSharp which is anyway much more stable and more performant. This variant is not affected.

If you are doing .NET Framework development, you need to roll back to 1.24.1 until the fix is rolled out.

**Comment by filipw** [comment]
You are right, it's an unfortunate regression. Really sorry about that. 

We have a fix in the making, in the meantime, if you are doing .NET Core development only, you can set `"omnisharp.useModernNet": true` which will opt you into .NET 6 build of OmniSharp which is anyway much more stable and more performant. This variant is not affected.

If you are doing .NET Framework development, you need to roll back to 1.24.1 until the fix is rolled out.

**Comment by Ping-Gao** [comment]
> I am having the same issue on mac, even with `omnisharp 1.38.2` and `ms-dotnettools.csharp 1.24.2` and `"omnisharp.path":"latest` not present in my `.vscode/settings.json`.
> 
> I have installed `ms-dotnettools.csharp 1.24.1` and removed `.vscode/extensions/ms-dotnettools.csharp-1.24.2-darwin-arm64` and this now works. Culprit seems to be latest version of this extension.

That worked for me, thx.

**Comment by spdrcd** [comment]
> 

I did rolled back and it works for now...

**Comment by spdrcd** [comment]
> You are right, it's an unfortunate regression. Really sorry about that.
> 
> We have a fix in the making, in the meantime, if you are doing .NET Core development only, you can set `"omnisharp.useModernNet": true` which will opt you into .NET 6 build of OmniSharp which is anyway much more stable and more performant. This variant is not affected.
> 
> If you are doing .NET Framework development, you need to roll back to 1.24.1 until the fix is rolled out.



> You are right, it's an unfortunate regression. Really sorry about that.
> 
> We have a fix in the making, in the meantime, if you are doing .NET Core development only, you can set `"omnisharp.useModernNet": true` which will opt you into .NET 6 build of OmniSharp which is anyway much more stable and more performant. This variant is not affected.
> 
> If you are doing .NET Framework development, you need to roll back to 1.24.1 until the fix is rolled out.

Thank you so much to letting me know about working on fixing this issue!!
I did rolled back and it works for now...

**Comment by nohwnd** [comment]
Fix is merged, thanks @filipw  The packages for 1.24.3 are building.

**Comment by spdrcd** [comment]
> Fix is merged, thanks @filipw The packages for 1.24.3 are building.

@nohwnd Thank you all I see it is building right now. Hope to update to the new version once issue is fixed 😄
