### ISSUE TITLE
OmniSharp.MSBuild.ProjectLoader   The "ValidateExecutableReferences" task failed unexpectedly.

### ISSUE THREAD

**Issue by senal** [OmniSharp/omnisharp-vscode#5148]
## Environment data
`dotnet --info` output:
.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22581
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  5.0.406 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]        
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
VS Code version:
1.66.0
C# Extension version:
1.24.3
## OmniSharp log
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\workspace\learning\Play.Catalog\src\Play.Catalog.Service' on host 25764.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\workspace\learning\Play.Catalog\src\Play.Catalog.Service\Play.Catalog.Service.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "ValidateExecutableReferences" task failed unexpectedly.
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.NET.Build.Tasks.ValidateExecutableReferences.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\workspace\learning\Play.Catalog\src\Play.Catalog.Service\Play.Catalog.Service.csproj'.
c:\workspace\learning\Play.Catalog\src\Play.Catalog.Service\Play.Catalog.Service.csproj
C:\Program Files\dotnet\sdk\6.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(1092,5): Error: The "ValidateExecutableReferences" task failed unexpectedly.
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.NET.Build.Tasks.ValidateExecutableReferences.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\workspace\learning\Play.Catalog\src\Play.Catalog.Service\Play.Catalog.Service.csproj

## Steps to reproduce
Create a class library 
dotnet new classlib -n <name> --framework net5.0

reference this class lib in your api project

## Expected  behavior

Should be able to reference types defined in the class lib.

## Actual behavior
Can not reference types defined in the class lib.
VS code complains "Some projects have trouble loading. Please review the output for more details." clicking on  'Show output' bring up the OmniSharp error log.

**Comment by filipw** [comment]
Can you please post the full log, not an abbreviated one? In particular, the beginning of the log would show which variant of OmniSharp you are using. Thanks.

**Comment by senal** [comment]
@filipw ,
Thanks for your feedback.
Please find the details you requested:

---------------------------------------------- complete OmniSharp Log --------------------------------------------------
Starting OmniSharp server at 4/4/2022, 7:22:49 PM
    Target: c:\workspace\learning\microservices\julio\Play.Catalog\src\Play.Catalog.Service

OmniSharp server started.
    Path: c:\Users\ranga\.vscode\extensions\ms-dotnettools.csharp-1.24.3\.omnisharp\1.38.2\OmniSharp.exe
    PID: 33076

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 3 MSBuild instance(s)
            1: Visual Studio Community 2022 17.0.31606.5 17.0.0 - "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin"
            2: Visual Studio Community 2019 16.11.32228.343 16.11.2 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            3: StandAlone 17.1.1 - "c:\Users\ranga\.vscode\extensions\ms-dotnettools.csharp-1.24.3\.omnisharp\1.38.2\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2022 17.0.31606.5 17.0.0 - "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\workspace\learning\microservices\julio\Play.Catalog\src\Play.Catalog.Service'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\workspace\learning\microservices\julio\Play.Catalog\src\Play.Catalog.Service'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\workspace\learning\microservices\julio\Play.Catalog\src\Play.Catalog.Service\Play.Catalog.Service.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\workspace\learning\microservices\julio\Play.Catalog\src\Play.Catalog.Service'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\workspace\learning\microservices\julio\Play.Catalog\src\Play.Catalog.Service' on host 11748.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\workspace\learning\microservices\julio\Play.Catalog\src\Play.Catalog.Service\Play.Catalog.Service.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The "ValidateExecutableReferences" task failed unexpectedly.
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.NET.Build.Tasks.ValidateExecutableReferences.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\workspace\learning\microservices\julio\Play.Catalog\src\Play.Catalog.Service\Play.Catalog.Service.csproj'.
c:\workspace\learning\microservices\julio\Play.Catalog\src\Play.Catalog.Service\Play.Catalog.Service.csproj
C:\Program Files\dotnet\sdk\6.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(1092,5): Error: The "ValidateExecutableReferences" task failed unexpectedly.
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.NET.Build.Tasks.ValidateExecutableReferences.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\workspace\learning\microservices\julio\Play.Catalog\src\Play.Catalog.Service\Play.Catalog.Service.csproj

------------------------------------------------------------------------------------------------------------------------------

Screenshot of the alert that pops up in VS code when loading the project
![image](https://user-images.githubusercontent.com/2841066/161515293-d9f9bbab-08d1-4186-96ab-50f18f49f85a.png)

**Comment by filipw** [comment]
According to your log, the MSBuild picked up by OmniSharp is coming from you VS installation:

> 1: Visual Studio Community 2022 17.0.31606.5 17.0.0 - "C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin"

Make sure to update it to the latest version.

**Comment by senal** [comment]
@filipw ,
Thank you very much. that helped!
I did remove VS 2022 Preview and installed the VS 2022 Community edition. The issue got fixed.
