### ISSUE TITLE
The 1 extension(s) below, in workspace recommendations have issues: ms-vscode.go (not found in marketplace)

### ISSUE THREAD

**Issue by 1055373165** [OmniSharp/omnisharp-vscode#5166]
i  try usr the IBM BlockChain platform, when i open the vscode, system report this problem.
So i try resolve this problem.
In _**.vscode/extension.json**_ 
I see 
{
    "recommendations": [
        "ibmblockchain.ibm-blockchain-platform",
        "ms-vscode.go"
    ]
}

when i change **.go** to **.Go** 
this problem solved.....

**Comment by nohwnd** [comment]
Hello this is not the correct repository. We have nothing in common with golang extension for vscode. I think you meant this repository: https://github.com/microsoft/vscode-go which is archived. Your toolchain is probably outdated and should use some other GO extension. 

Here is some guidance directly from vscode: https://code.visualstudio.com/docs/languages/go

If you still want to pursue this, and think it is a general VSCode problem, you might want to raise the issue directly on vscode repo: https://github.com/microsoft/vscode
