### ISSUE TITLE
OmniSharp doesn't work

### ISSUE THREAD

**Issue by af4jm** [OmniSharp/omnisharp-vscode#5168]
## Environment data
`dotnet --info` output:

.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.405 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

VS Code version: 1.66.2
C# Extension version: 1.24.4

***

*note:* VS22 Enterprise is also installed on this machine

## OmniSharp log

it's empty

## Steps to reproduce

launch a workspace with 2 .NET 5 solutions, e.g. MyTeamProject.sln & MyTeamProject.AzureResources.sln ... in workspace settings:

`"projects.defaultLaunchSolution": "MyTeamProject.sln"`

actual behavior is that setting is ignored and the alphabetically first solution loads instead... "OmniSharp: Select Project" does nothing... restarting OmniSharp or VSCode has no effect

so I found `omnisharp.useModernNet` and set it to `true`, restarted OmniSharp, and got the error shown in [this comment](https://github.com/OmniSharp/omnisharp-vscode/issues/5159#issuecomment-1092636173)

Since then, the only thing I can get in the OmniSharp log is re-downloading OmniSharp every time I reload VSCode... I never get the status bar icon, the commands to restart OmniSharp or to select a project both do nothing

## Expected  behavior

- OmniSharp starts, respects it's settings, displays IntelliSense
- "OmniSharp: select project" gives me a way to choose a project to load

## Actual behavior

- OmniSharp either ignores it's settings or fails to load (depending on the `useModernNet` setting)
- "OmniSharp: select project" does nothing

**Comment by af4jm** [comment]
Update: while I was creating this issue, it loaded... I restarted VSCode and nothing happened for over 4 minutes, then OmniSharp started correctly, with Intellisense, etc. working on the project indicated in `defaultLaunchSolution` setting

The first line of the OmniSharp log "Starting OmniSharp server at ..." shows the time 4 minutes after VSCode launched.

OmniSharp: Select Project still does nothing (and when I tried it yesterday without useModernNet turned on, VSCode had been idle in the background for over an hour, so definitely not a case of it still loading)

**Comment by af4jm** [comment]
LOL, now I go back to VSCode again and I have the list of projects to pick

so maybe I should rename to "OmniSharp is slooooooooow with useModernNet", although that doesn't cover the issues with that setting off

**Comment by af4jm** [comment]
to clarify, I should point out that no other VSCode extensions and no other apps on this PC behave this way... it's as if every OnmiSharp command has `sleep(250)` as its first step

**Comment by JoeRobich** [comment]
@af4jm Could you share the "csharp" and "omnisharp" related configuration from your VS Code settings? 

Also, It would be beneficial from a fresh start of VS Code to get a copy of the "Log (Extension Host)" logs from the Output pane after opening the folder with your C# project.

**Comment by af4jm** [comment]
I don't have any "csharp" settings, these are the only Omnisharp ones... I'll grab a log when I fire up the work PC

``` json
{
    "omnisharp.autoStart": true,
    "omnisharp.enableEditorConfigSupport": true,
    "omnisharp.enableRoslynAnalyzers": true,
    "omnisharp.useModernNet": true
}
```

**Comment by af4jm** [comment]
the crazy thing is working right now... must've been a something weird going on... I only have 1 PC (the work one) setup for dev, so  I couldn't try it on another box...  I guess I'll just blame electron (if there was a non-electron alternative to VSCode, I'd switch, precisely because of these perf issues... but any alternatives would have me run 2 things side-by-side, which is even worse)
