### ISSUE TITLE
Extension remains in memory even after vscode is closed

### ISSUE THREAD

**Issue by lonix1** [OmniSharp/omnisharp-vscode#5178]
## Environment data
dotnet: 6.0.202
VS Code version: 1.66.2
C# Extension version: 1.24.4
OS: linux

## OmniSharp log
none

## Steps to reproduce
I often reload vscode during the day, because it gets slow, or to update extensions, or some other reason.

When I do, the extension is not unloaded from memory, and a new one is loaded. Over time, I have many of them in memory, taking up `inotify` instances and memory, eventually leading to me killing them with `kill -9`.

So when I do a `ps aux | grep dotnettools` I get many like this:
````
/home/username/.vscode/extensions/ms-dotnettools.csharp-1.24-linux-x64/.razor/rzls -lsp --trace 0
/home/username/.vscode/extensions/ms-dotnettools.csharp-1.24-linux-x64/.razor/rzls -lsp --trace 0
/home/username/.vscode/extensions/ms-dotnettools.csharp-1.24-linux-x64/.razor/rzls -lsp --trace 0
/home/username/.vscode/extensions/ms-dotnettools.csharp-1.24-linux-x64/.razor/rzls -lsp --trace 0
/home/username/.vscode/extensions/ms-dotnettools.csharp-1.24-linux-x64/.razor/rzls -lsp --trace 0
...
````

This is not a new problem (netcore6 without mono), because it's been happening for a long time (netcore5 with mono, and netcore5 without mono).

## Expected  behavior
When vscode is closed or reloaded, the extension should be terminated.

## Actual behavior
Extension remains in memory, even though vscode is closed.

**Comment by fortiasoft** [comment]
Same here any workaround?

**Comment by lonix1** [comment]
ubuntu 20.04, vscode 1.67.1, o# 1.24.4
Since I'm not the only one with this problem, it must be something particular to our setup.
If anyoe has tips for troubleshooting, please share. Let's try get to the bottom of this.

**Comment by AAulicino** [comment]
The same thing has been happening here for some time now, it stays there forever, even after vscode is completely closed.

I'm on macOS 12.4 Monterey, this also happens with my coworker at MacOS 11 Big Sur.
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/6969647/173176339-bdc68984-1efa-4444-8202-bee5167f7c7e.png">

**Comment by jtsom** [comment]
I'm seeing this also, with the latest version of the C# extension, and the latest Insiders VSCode. Note in the screenshot, there are `rzls` processes even for old versions of the C# extension.

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/13488/173709960-f796939c-d7e1-4536-b1d0-5d4b3c44631a.png">

**Comment by jtsom** [comment]
Is this issue even being looked at? Seem like a major problem, and no status update since April.

**Comment by jtsom** [comment]
A Month and a half later and nothing.....

**Comment by allisonchou** [comment]
Hi all! C# extension v1.25.4 was released earlier today which should address this problem. Please let us know if you continue to run into issues. Thanks, and happy coding!

@dibarbet Could you help close out this issue? (I don't have permissions.)
