### ISSUE TITLE
Irrelevant code fix suggestions

### ISSUE THREAD

**Issue by geirsagberg** [OmniSharp/omnisharp-vscode#518]
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

VS Code version:
Version 1.3.0-insider

C# Extension version:
1.2.0
## Steps to reproduce
1. Put caret on a squiggly line
2. Press <kbd>Cmd</kbd>+<kbd>.</kbd>

![screen shot 2016-06-30 at 21 57 21](https://cloud.githubusercontent.com/assets/594564/16502404/840b6e36-3f0e-11e6-8c86-a41cd7d0a2f2.png)
## Expected  behavior

Only relevant code fixes are shown, e.g. "Remove unnecessary usings".
## Actual behavior

Many irrelevant code fixes are shown, e.g. "Make method synchronous" or "Delegate invocation can be simplified".

![screen shot 2016-06-30 at 21 57 29](https://cloud.githubusercontent.com/assets/594564/16502411/8cee84c0-3f0e-11e6-8569-ecaa2a16d625.png)

**Comment by DustinCampbell** [comment]
This has been fixed for the 1.7 release. There are several fixes that contribute to this, but the most relevant is https://github.com/OmniSharp/omnisharp-roslyn/pull/754.
