### ISSUE TITLE
omnisharp server is not running

### ISSUE THREAD

**Issue by Sourabh1432** [OmniSharp/omnisharp-vscode#5180]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Sourabh1432** [comment]
![Screenshot (42)](https://user-images.githubusercontent.com/93909878/164420402-2355ce29-ac26-4c70-b13e-23e2f6c04098.png)

**Comment by Sourabh1432** [comment]
nothing is there in the omnisharp output

**Comment by JoeRobich** [comment]
@Sourabh1432 The C# extension expects that you have opened a folder in VSCode containing a .csproj or .sln file. Without the additional information from these files, O# wouldn't know what references to use with your C# file.

**Comment by filipw** [comment]
Please make sure you open a folder with a C# project or a C# solution, otherwise OmniSharp will not be activated.

**Comment by rugglcon** [comment]
I have opened a folder with a `.sln` and `.csproj` file and OmniSharp has not triggered in either case. I try and manually start it from the command palette and nothing happens. Then I will try and run the `Analyze all projects` command, and I get an error saying the OmniSharp server is not running, and it fails.

Please advise. I've tried uninstalling and reinstalling the extension as well.

**Comment by JoeRobich** [comment]
@rugglcon Please open a new issue and provide the requested OmniSharp Log from the VS Code output pane, as well as the output of running `dotnet --info` from the terminal.

**Comment by cvetanov** [comment]
I had not been working with .NET for a while, so when I needed to do that, I had a similar issue on my MacBook. The VS Code output for OmniSharp pointed out that the latest .NET version I had installed locally was .NET Core 3.1 and that the OmniSharp server needed at least .NET version 6.1. I downloaded and installed that one and after a restart OmniSharp works as expected. I hope someone finds this helpful.

**Comment by faizu2k01** [comment]
I've tried all the approaches like




![Screenshot (4)](https://user-images.githubusercontent.com/91092261/222730598-6b145725-967b-4291-bd7c-fff8a4190996.png)

**Comment by NCLnclNCL** [comment]
me too with errors 
[STDERR] Unhandled exception. 
[STDERR] System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)

**Comment by buddy326** [comment]
I have the same thing, 

[STDERR] Unhandled exception. 
[STDERR] System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (0x8007000B)
 
 Did someone figure this out? I've tried a bunch of stuff
