### ISSUE TITLE
Partial syntax highlighting with records

### ISSUE THREAD

**Issue by RicardoValero95** [OmniSharp/omnisharp-vscode#5182]
## Issue Description ##

Partial syntax highlighting when having multiple records in one file

## Steps to Reproduce ##

```csharp
namespace Sample.GraphQL.Products;
public record ProductAddInput(string Name);
public record ProductUpdateInput(Guid Id, string Name);
public record ProductDeleteInput(Guid Id);

```

## Expected Behavior ##
Something similar to classes 
<img width="306" alt="image" src="https://user-images.githubusercontent.com/55701657/164768363-83679833-105a-47d8-90f6-31c38cd86f15.png">

## Actual Behavior ##
<img width="411" alt="image" src="https://user-images.githubusercontent.com/55701657/164768518-65667b47-1367-483c-a71d-f7114472adcc.png">

## Environment information ##

**VSCode version**: 1.66.2
**C# Extension**: 1.24.4

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.3
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.202/

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  6.0.202 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|blazorwasm-companion|ms-dotnettools|1.1.0|
|csharp|ms-dotnettools|1.24.4|
|debugger-for-edge|msjsdiag|1.0.15|
|remote-containers|ms-vscode-remote|0.231.6|
|remote-wsl|ms-vscode-remote|0.66.0|
|vscode-dotnet-runtime|ms-dotnettools|1.5.0|
|vscode-fix-checksums|lehni|1.1.0|
|vsliveshare|ms-vsliveshare|1.0.5527|

</details>

**Comment by JoeRobich** [comment]
This is an issue with the C# TextMate Grammar (https://github.com/dotnet/csharp-tmLanguage/issues). If you set `csharp.semanticHighlighting.enabled` to `true` you should see consistent highlighting.

Closing as I've opened an issue to track this bug.
