### ISSUE TITLE
Can't start OmniSharp server. Ripgrep process using 100% CPU

### ISSUE THREAD

**Issue by Tacodude7729** [OmniSharp/omnisharp-vscode#5184]
## Issue Description ##
When I try to start VSCode, OmniSharp starts three processes like this;
```
/usr/share/code/resources/app/node_modules.asar.unpacked/@vscode/ripgrep/bin/rg --files --hidden --case-sensitive -g /{**/*.sln,**/*.slnf,**/*.csproj,**/project.json,**/*.csx,**/*.cake} -g Projects/CS/Projects/TopDownGame*/.git -g Projects/CS/Projects/TopDownGame*/.svn -g Projects/CS/Projects/TopDownGame*/.hg -g Projects/CS/Projects/TopDownGame*/CVS -g Projects/CS/Projects/TopDownGame*/.DS_Store -g Projects/CS/Projects/TopDownGame*/Thumbs.db -g */node_modules/**,**/.git/**,**/bower_components/**\} --no-ignore --follow --no-config --no-ignore-global
```
These process use 100% of all my CPU cores and OmniSharp never starts. I believe this is because of a directory in my project which contains a wine prefix (and all the weird links are screwing with ripgrep), but when I put the below into my `omnisharp.json` in the project root, nothing about the above process seems to change.
```json
"fileOptions": {
    "excludeSearchPatterns": ["**/tools/**"]
}
```
**Is there something I can do to exclude the weird directory or is this a bug?**

## Logs ##

Both 'OmniSharp Log' and 'C#' are empty.

## Environment information ##

**VSCode version**: 1.66.2
**C# Extension**: 1.24.4

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  21.10
 OS Platform: Linux
 RID:         ubuntu.21.10-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.202/

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  3.1.418 [/usr/share/dotnet/sdk]
  5.0.407 [/usr/share/dotnet/sdk]
  6.0.202 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.24 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.24 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

**Comment by JoeRobich** [comment]
@Tacodude7729 So this looks like VS Code trying to locate files in the open folder that satisfy extension activation requirements. I think you should reopen the issue against https://github.com/microsoft/vscode/issues since it is not the C# extension that is running ripgrep.

**Comment by JoeRobich** [comment]
Closing as issue is now open against VSCode https://github.com/microsoft/vscode/issues/148091
