### ISSUE TITLE
[M1]Debug should not be stopped if step into Console.WriteLine (F11) for IL symbols

### ISSUE THREAD

**Issue by Jiangpeng14** [OmniSharp/omnisharp-vscode#5193]
## Environment data
`dotnet --info` output:
m1e2e@m1e2es-Mac-mini ~ % dotnet --info
.NET SDK (reflecting any global.json):
Version: 6.0.203
Commit: a20feadf6d

Runtime Environment:
OS Name: Mac OS X
OS Version: 12.3
OS Platform: Darwin
RID: osx.12-arm64
Base Path: /usr/local/share/dotnet/sdk/6.0.203/

Host (useful for support):
Version: 6.0.5
Commit: 70ae3df4a6

.NET SDKs installed:
6.0.203 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
https://aka.ms/dotnet-download

VS Code version:1.66.2

C# Extension version:1.24.4

## Steps to reproduce
1.Create a new ASP.NET Razor project by doing

mkdir razor
cd razor
dotnet new razor

2.Use File -> Open Folder to open the razor folder you have created in step 1

3.It may ask at the bottom right to install assets to build and debug, say yes.

4.After it has done this it will have created a .vscode directory in the ‘razor’ directory and a ‘launch.json’ file in that directory. Open the ‘.vscode’ directory, and double click on the ‘launch.json to edit it.

5.Add the following lines after the “name” line of the “Configurations” object. (This allows debugging through the framework.
"justMyCode": false,
"symbolOptions": {
"searchMicrosoftSymbolServer": true
},
"suppressJITOptimizations": true,

6.Double click on the ‘Startup.cs’ file in the ‘Explorer’ pane to bring up that source code.

7.Add the following line to the Startup.cs file at the beginning of the ‘Configure’ method (at the bottom of the file).
Console.WriteLine("x " + 3);

8.Place a breakpoint on that line (F9).

9.Run the application until it hit that breakpoint (F5). It will load symbols from the Microsoft symbol server, and may take a few seconds to hit the breakpoint. You should see 20-30 lines of ‘Loaded XXX Symbols loaded’. Lines as it does this).

10.Step into the concatination method (F11). This tests CoreCLR symbols AT THIS POINT IT SHOULD SHOW YOU THE SOURCE CODE FOR Concat(). If it does not that is a FAILURE. Please report it.

11.Step out of Concat (Shift F11). Then step into Console.WriteLine (F11).

## Expected behavior

Debug works normally

## Actual behavior
The debug finished after clicking F11
![MicrosoftTeams-image](https://user-images.githubusercontent.com/84758135/165723280-a9cf65aa-912e-4d95-b09a-438eb29a54c8.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/84758135/165723313-0914f184-47b4-4928-a7dd-0c1d324fde1e.png)

**Comment by Jiangpeng14** [comment]
This issue only repro on Mac M1, not repro on Mac Intel Chip

**Comment by JoeRobich** [comment]
FYI @gregg-miskelly

**Comment by gregg-miskelly** [comment]
@Jiangpeng14 I cannot reproduce this. A few questions:
1: Did symbol load for System.Private.CoreLib.dll and System.Console.dll? You can check in the output. Example:

```
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.4/System.Private.CoreLib.dll'. Symbols loaded.
...
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.4/System.Console.dll'. Symbols loaded.
```

2. What version of the .NET Runtime do you have installed?
3. If symbol do load, can you fix this by disabling ReadyToRun? [Instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Debugging-into-the-.NET-Framework-itself)

**Comment by Jiangpeng14** [comment]
[logs.txt](https://github.com/OmniSharp/omnisharp-vscode/files/8587540/logs.txt)
@gregg-miskelly thanks, for question 1, we check symbol load for System.Private.CoreLib.dll and System.Console.dll in the output, they load failed. For details, please see the attachment I uploaded.
For question 2, the runtime we installed is 6.0.5 arm64.

**Comment by gregg-miskelly** [comment]
@Jiangpeng14 The issue is that you have some sort of pre-release version of .NET 6 on you box, and those PDBs aren't on the symbol server since they are pre-release.

**Comment by JoeRobich** [comment]
> This issue only repro on Mac M1, not repro on Mac Intel Chip

@gregg-miskelly Any thoughts about why it would appear to work with x64 bits?

**Comment by gregg-miskelly** [comment]
@JoeRobich My **guess** would be that @Jiangpeng14 is using a released .NET runtime on x64 and a pre-release runtime on arm64.
