### ISSUE TITLE
Can't run debugger using C# in VS Code

### ISSUE THREAD

**Issue by GuilhermeFrSaito** [OmniSharp/omnisharp-vscode#5206]
## Issue Description ##
I'm just starting to code in C#, using VS Code with all the apparently needed extensions, but when I hit F5, the following message pops up on the lower right of the editor window:

"Cannot set properties of undefined (setting 'PYTHONPATH')"

**EVEN** if the "dotnet run" command in the terminal works fine. Just the debugger that doesn't run at all.

## Steps to Reproduce ##

The code is of a simple hello world console project.

### OmniSharp log ###
<details>There is not any log printed in any of the terminal windows</details>

### C# log ###
<details>No output from trying to run the debugger, just the aforementioned message writen above</details>

## Environment information ##

**VSCode version**: 1.67.1
**C# Extension**: 1.24.4

<details><summary>Dotnet Information</summary>
SDK do .NET (refletindo qualquer global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Ambiente de runtime:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|autodocstring|njpwerner|0.6.1|
|code-runner|formulahendry|0.11.7|
|csharp|ms-dotnettools|1.24.4|
|csharpextensions|kreativ-software|1.7.0|
|dotnet|formulahendry|0.0.4|
|jinja|wholroyd|0.0.8|
|jupyter|ms-toolsai|2022.4.1011282140|
|jupyter-keymap|ms-toolsai|1.0.0|
|jupyter-renderers|ms-toolsai|1.0.6|
|material-theme|zhuangtongfa|3.13.26|
|python|ms-python|2022.6.2|
|python-environment-manager|donjayamanne|1.0.4|
|python-extension-pack|donjayamanne|1.7.0|
|python-path|mgesbert|0.0.11|
|pythonpath-setter|datasentics|0.0.1|
|remote-wsl|ms-vscode-remote|0.66.2|
|vsc-python-indent|KevinRose|1.15.0|
|vscode-database-client2|cweijan|5.2.7|
|vscode-django|batisteo|1.10.0|
|vscode-docker|ms-azuretools|1.22.0|
|vscode-env-selector|andricdev|0.3.0|
|vscode-ipython|ChenJun|0.6.2|
|vscode-ipython|pancho111203|0.5.0|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-pylance|ms-python|2022.5.1|
|vscode-yaml|redhat|1.7.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.20|;

</details>

**Note:** I've been looking all over the net over several foruns and found absolutely no one discussing anything like this. Maybe I'm doing something wrong. Anyway, I've reinstalled VS Code and some of the extensions, but to no avail. Thank you for your time.

**Comment by gregg-miskelly** [comment]
@GuilhermeFrSaito I have no idea why you would see an error like "Cannot set properties of undefined (setting 'PYTHONPATH')". What does your launch.json look like?

**Comment by gregg-miskelly** [comment]
In case it is helpful, here are the instructions: https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md. Make sure you have done step 3 under 'Once for each project'.

**Comment by GuilhermeFrSaito** [comment]
Hello Gregg, sorry I didn't answer earlier.
My launch.json file is as follows:
{
    "version": "0.2.0",
    "configurations": [
        {
            // Use IntelliSense to find out which attributes exist for C#
debugging
            // Use hover for the description of the existing attributes
            // For further information visit
https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update
the program path.
            "program": "${workspaceFolder}/bin/Debug/net6.0/WS_Project1.dll"
,
            "args": [],
            "cwd": "${workspaceFolder}",

            // For more information about the 'console' field, see
https://aka.ms/VSCode-CS-LaunchJson-Console
            "console": "internalConsole",
            "stopAtEntry": false
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach"
        }
    ]
}

It's the default file that is created when you set and choose the debugger
up/left.

Anyway, thank you for your reply and I really appreciate the instructions
you sent. I'll be sure to apply at my first chance and let you know what
happens.

Thanks again and have a great weekend!

**Comment by gregg-miskelly** [comment]
Thanks. That all looks totally normal. I suspect you are running into a bug from one of your other extensions. Looks like you have an extension called 'python-path', so that would be my guess, though I could totally be wrong.
