### ISSUE TITLE
C# formatter broken in ms-dotnettools.csharp-1.25.0-linux-x64

### ISSUE THREAD

**Issue by vdbg** [OmniSharp/omnisharp-vscode#5223]
Trying to format a C# file with `ms-dotnettools.csharp-1.25.0-linux-x64` installed gives error message: "there is no formatter for 'csharp' files installed"

Reverting to `ms-dotnettools.csharp-1.24.4-linux-x64` fixes it.

VS version: code/stable,stable,now 1.67.2-1652812855 amd64 [installed]
OS version: Ubuntu 20.04.4 LTS

**Comment by JoeRobich** [comment]
@vdbg Please share your complete OmniSharp Log from the VS Code Output pane.

**Comment by vdbg** [comment]
```
[ERROR] Error: Found dotnet version 5.0.408. Minimum required version is 6.0.100.
Starting OmniSharp server at 5/24/2022, 2:53:36 PM
```

Note: the extension auto-upgraded itself from `ms-dotnettools.csharp-1.24.4-linux-x64` to `ms-dotnettools.csharp-1.25.0-linux-x64`

**Comment by JoeRobich** [comment]
Starting in 1.25.0 O# will run by default against an installed .NET 6 SDK (see the announcement at https://github.com/OmniSharp/omnisharp-vscode/issues/5120). If you want to continue running against a system install of Mono, you can set `omnisharp.useModernNet` to `false` in your settings.

**Comment by vdbg** [comment]
My system isn't on Mono

```
dotnet-apphost-pack-5.0/focal,now 5.0.17-1 amd64 [installed,automatic]
dotnet-host/focal,now 6.0.5-1 amd64 [installed,automatic]
dotnet-hostfxr-5.0/focal,now 5.0.17-1 amd64 [installed,automatic]
dotnet-runtime-5.0/focal,now 5.0.17-1 amd64 [installed,automatic]
dotnet-runtime-deps-5.0/focal,now 5.0.17-1 amd64 [installed,automatic]
dotnet-sdk-5.0/focal,now 5.0.408-1 amd64 [installed]
dotnet-targeting-pack-5.0/focal,now 5.0.0-1 amd64 [installed,automatic]
```

**Comment by JoeRobich** [comment]
@vdbg Then you will need to install the .NET 6 SDK.

**Comment by vdbg** [comment]
Yes, my issue is fixed. 

It may make sense to disable auto-upgrades of packages on systems where the new required dependencies aren't met. Or to provide a direct explicit error message in the modal dialog (vs. "there is no formatter for 'csharp' files installed"). That'd would minimize the disruption to others.

**Comment by filipw** [comment]
It is also worth mentioning that .NET 5 has reached the end of life already https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
