### ISSUE TITLE
version 1.25.0 "omnisharp.useGlobalMono" Disappeared

### ISSUE THREAD

**Issue by liujinlong123** [OmniSharp/omnisharp-vscode#5228]
## Environment data
`dotnet --info` output:

```bash
mk@mk:~$ dotnet --info
.NET SDK (反映任何 global.json):
 Version:   6.0.300
 Commit:    8473146e7d

运行时环境:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/mk/.dotnet/sdk/6.0.300/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.104 [/home/mk/.dotnet/sdk]
  6.0.202 [/home/mk/.dotnet/sdk]
  6.0.300 [/home/mk/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [/home/mk/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [/home/mk/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [/home/mk/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [/home/mk/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

VS Code version: `version 1.67`
C# Extension version: `version 1.25.0`

## OmniSharp log

```log
Starting OmniSharp server at 2022/5/25 21:24:06
    Target: /home/mk/workLiu/simulation/unity/L_Learn

OmniSharp server started with .NET 6.0.300
.
    Path: /home/mk/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/.omnisharp/1.39.0-net6.0/OmniSharp.dll
    PID: 26112

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Unknown 0.0 (Unknown)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 3 MSBuild instance(s)
            1: .NET Core SDK 6.0.300 17.2.0 - "/home/mk/.dotnet/sdk/6.0.300/"
            2: .NET Core SDK 6.0.202 17.1.1 - "/home/mk/.dotnet/sdk/6.0.202/"
            3: .NET Core SDK 6.0.104 17.0.0 - "/home/mk/.dotnet/sdk/6.0.104/"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 6.0.300 17.2.0 - "/home/mk/.dotnet/sdk/6.0.300/"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/mk/workLiu/simulation/unity/L_Learn/L_Learn.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/mk/workLiu/simulation/unity/L_Learn/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/mk/workLiu/simulation/unity/L_Learn/Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/mk/workLiu/simulation/unity/L_Learn'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/mk/workLiu/simulation/unity/L_Learn' on host 25934.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/mk/workLiu/simulation/unity/L_Learn/Assembly-CSharp.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project targets .NET version that requires reference assemblies that are not installed (e.g. .NET Framework). The most common solution is to make sure Mono is fully updated on your machine (https://mono-project.com/download/) and that you are running the .NET Framework build of OmniSharp (e.g. 'omnisharp.useModernNet': false in C# Extension for VS Code).
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/home/mk/workLiu/simulation/unity/L_Learn/Assembly-CSharp.csproj'.
/home/mk/workLiu/simulation/unity/L_Learn/Assembly-CSharp.csproj
/home/mk/.dotnet/sdk/6.0.300/Microsoft.Common.CurrentVersion.targets(1221,5): Error: This project targets .NET version that requires reference assemblies that are not installed (e.g. .NET Framework). The most common solution is to make sure Mono is fully updated on your machine (https://mono-project.com/download/) and that you are running the .NET Framework build of OmniSharp (e.g. 'omnisharp.useModernNet': false in C# Extension for VS Code).

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/mk/workLiu/simulation/unity/L_Learn/Assembly-CSharp-Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project targets .NET version that requires reference assemblies that are not installed (e.g. .NET Framework). The most common solution is to make sure Mono is fully updated on your machine (https://mono-project.com/download/) and that you are running the .NET Framework build of OmniSharp (e.g. 'omnisharp.useModernNet': false in C# Extension for VS Code).
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/home/mk/workLiu/simulation/unity/L_Learn/Assembly-CSharp-Editor.csproj'.
/home/mk/workLiu/simulation/unity/L_Learn/Assembly-CSharp-Editor.csproj
/home/mk/.dotnet/sdk/6.0.300/Microsoft.Common.CurrentVersion.targets(1221,5): Error: This project targets .NET version that requires reference assemblies that are not installed (e.g. .NET Framework). The most common solution is to make sure Mono is fully updated on your machine (https://mono-project.com/download/) and that you are running the .NET Framework build of OmniSharp (e.g. 'omnisharp.useModernNet': false in C# Extension for VS Code).

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /home/mk/workLiu/simulation/unity/L_Learn/Assembly-CSharp.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /home/mk/workLiu/simulation/unity/L_Learn/Assembly-CSharp-Editor.csproj
[warn]: OmniSharp.Roslyn.CSharp.Services.InlayHints.InlayHintService
        Inlay hints requested for document not in workspace Location { FileName = /home/mk/workLiu/simulation/unity/L_Learn/Assets/Scripts/ExperimentB/RelationFeedbackGroupController.cs, Range = Range { Start = Point { Line = 0, Column = 0 }, End = Point { Line = 113, Column = 9 } } }
```

## Steps to reproduce

```log
when i open my unity project, then show the error.
```

## Additional context
1. "omnisharp.useGlobalMono": "always" in vscode settings.json at version 1.25.0 turns to grey, and no setting in setting view.

2. however, when i reduce version to 1.24.4, "omnisharp.useGlobalMono": "always" highlight in settings.json, and there are no more mistakes

**Comment by JoeRobich** [comment]
Since OmniSharp no longer ships with an included Mono or MSBuild tools there is no need for the "useGlobalMono" setting and it was removed. See the announcement at https://github.com/OmniSharp/omnisharp-vscode/issues/5120

**Comment by liujinlong123** [comment]
```log
mk@mk:~$ mono --version
Mono JIT compiler version 6.12.0.179 (tarball Tue May 17 21:33:45 UTC 2022)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
mk@mk:~$
```

And i use `apt install mono-complete`

**Comment by dkeele** [comment]
I'm having a similar log. It started two days ago out of the blue.
`This project targets .NET version that requires reference assemblies that are not installed`

**Comment by liujinlong123** [comment]
> ~I'm having a similar problem and log. It started two days ago out of the blue.~
> 
> Edit: Search `omnisharp.useModernNet` in your VS code settings and uncheck the box.
> 
> Omnisharp recently released a breaking change that flips the default state of this boolean. See the announcement [here](https://github.com/OmniSharp/omnisharp-vscode/blob/master/README.md#announcements).

Thank you! It bothered me all day until I reduced the version. Thanks for solving my problem on new version.

**Comment by dandre9** [comment]
> ~I'm having a similar problem and log. It started two days ago out of the blue.~
> 
> Edit: Search `omnisharp.useModernNet` in your VS code settings and uncheck the box.
> 
> Omnisharp recently released a breaking change that flips the default state of this boolean. See the announcement [here](https://github.com/OmniSharp/omnisharp-vscode/blob/master/README.md#announcements).

I was having the same problem, your solution solved for me. Thanks!!

**Comment by filipw** [comment]
Glad to hear it helped - and sorry for any convenience.

**Comment by denravonska** [comment]
I'm generally confused about the whole .NET ecosystem, but I noticed that format on save (or manually) no longer works in VSCode under Linux. Is this related or are both my installations broken for some other reason?

**Comment by MichaelLykkeStrand** [comment]
Not too happy about this change :(

**Comment by SushiWaUmai** [comment]
> ~I'm having a similar problem and log. It started two days ago out of the blue.~
> 
> Edit: Search `omnisharp.useModernNet` in your VS code settings and uncheck the box.
> 
> Omnisharp recently released a breaking change that flips the default state of this boolean. See the announcement [here](https://github.com/OmniSharp/omnisharp-vscode/blob/master/README.md#announcements).

I also had to update the default mono path for it to work.

**Comment by caelanreid** [comment]
This has broken my workspace developing with Unity on ubuntu 20.4
Unchecking useModernNet does not fix the problem

`[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 0 MSBuild instance(s)`
I do not understand why this is happening, I installed mono and mono-complete from apt and still no luck
I tried changing omnisharp.monopath from blank to the system path for mono and still no luck
Any help in fixing this would be greatly appreciated or I will probably have to find a new IDE

**Comment by JoeRobich** [comment]
@caelanreid C# extension no longer ships with Mono and MSBuild tooling. You will need to follow the steps at https://www.mono-project.com/download/preview/#download-lin-ubuntu to install Mono for Unity development.

**Comment by caelanreid** [comment]
> @caelanreid C# extension no longer ships with Mono and MSBuild tooling. You will need to follow the steps at https://www.mono-project.com/download/preview/#download-lin-ubuntu to install Mono for Unity development.

I installed and updated all existing mono packages and the ones in the link you provided but still no luck, I think there must be something wrong with my mono. I've fixed this by rolling back my C# extension until I have the time to investigate further. Thank you for the help!

**Comment by JoeRobich** [comment]
@caelanreid When you do find time, please open a new issue and provide all the requested logs. Thanks!

**Comment by JoeRobich** [comment]
@chopin1998 You will need to set `omnisharp.useModernNet` to `false` and ensure you have a complete Mono installation https://www.mono-project.com/download/preview/#download-lin-ubuntu

**Comment by chopin1998** [comment]
> @chopin1998 You will need to set `omnisharp.useModernNet` to `false` and ensure you have a complete Mono installation https://www.mono-project.com/download/preview/#download-lin-ubuntu

use omnisharp.useModernNet cann't work with unity dev env...

**Comment by Pollyanna584** [comment]
> Edit: Search `omnisharp.useModernNet` in your VS code settings and uncheck the box.


I've bene messing with this for an hour and this is finally what fixed it
