### ISSUE TITLE
Starting Omnisharp throws System.BadImageFormatException and crashes

### ISSUE THREAD

**Issue by PixelatedLagg** [OmniSharp/omnisharp-vscode#5235]
## Issue Description ##
Starting Omnisharp throws System.BadImageFormatException and crashes

## Steps to Reproduce ##
Start Omnisharp

## Expected Behavior ##
Omnisharp working as normal without errors

## Actual Behavior ##
Omnisharp throws an error and crashes

### OmniSharp log ###
<details>
Starting OmniSharp server at 5/26/2022, 7:08:38 PM
    Target: c:\Users\pixil\Desktop\Impart

OmniSharp server started with .NET 6.0.100
.
    Path: c:\Users\pixil\.vscode-insiders\extensions\ms-dotnettools.csharp-1.25.0-win32-x64\.omnisharp\1.39.0-net6.0\OmniSharp.dll
    PID: 14936

Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
</details>

### C# log ###
<details>
Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 6 / x64)' (40438 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Windows (.NET 6 / x64)'

Finished
</details>

## Environment information ##

**VSCode version**: 1.68.0-insider
**C# Extension**: 1.25.0

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.403 [C:\Program Files (x86)\dotnet\sdk]
  6.0.100 [C:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.25.0|
|remote-containers|ms-vscode-remote|0.236.1|
|remote-ssh|ms-vscode-remote|0.80.0|
|remote-ssh-edit|ms-vscode-remote|0.80.0|
|remote-wsl|ms-vscode-remote|0.66.3|
|vim-theme|HarryHopkinson|1.0.1|
|vscode-counter|uctakeoff|3.0.4|
|vscode-remote-extensionpack|ms-vscode-remote|0.21.0|;

</details>

**Comment by JoeRobich** [comment]
It appears you have the x86 SDK folder (`C:\Program Files (x86)\dotnet`) before the x64 SDK folder (`C:\Program Files\dotnet`) in your environment PATH. To fix this issue, update your System Environment PATH by removing the x86 folder.

**Comment by PixelatedLagg** [comment]
Thanks, it worked!
