### ISSUE TITLE
Debugger:Different representation in Watch window between VS & VSCode

### ISSUE THREAD

**Issue by ClaireKang** [OmniSharp/omnisharp-vscode#524]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Steps to reproduce
1 Set bp at line of "_appSettings = options.Value;"  
2 Press F5 to start debugging
3 Change to watch window and input an expression of "this.good()" to evaluate

## Expected  behavior
Prompt wrong information rather than "not available" 

## Actual behavior
I have tried this in VS, and VS reports that cannot find the definition for good. Is it a by-design behavior in VSCode? At the same time, when you input this express in debug console in VSCode, it would tell nothing and this would lead customers' feel confused.

**Comment by wesrupert** [comment]
@ClaireKang, could you please provide the dotnet, VS Code, and C# version information, as well as any other unusual configuration you may have? I just tried to reproduce this on my machine, and got the expected error message that you saw in VS, both in the watch window and in the debug console:
![not found](https://cloud.githubusercontent.com/assets/2474675/16537152/f48b044e-3fb0-11e6-946c-6b5d12166709.png)
![not found 2](https://cloud.githubusercontent.com/assets/2474675/16537167/341cba12-3fb1-11e6-83aa-84f96c8ff4c6.png)

**Comment by ClaireKang** [comment]
![pic1](https://cloud.githubusercontent.com/assets/20184768/16549848/ecf5ff8c-41d5-11e6-86cf-376dcac72175.png)
This is vscode and other plugins' version, and I use visual studio2015 to retest this result.

**Comment by ClaireKang** [comment]
This pic is vscode and plugins' version, and I use Visual Studio 2015 to retest it

**Comment by ClaireKang** [comment]
This pic is vscode and plugins' version, and I use Visual Studio 2015 to retest it
![pic1](https://cloud.githubusercontent.com/assets/20184768/16550069/bdcafb2e-41d8-11e6-8bb3-4416bb74d8b7.png)
