### ISSUE TITLE
Syntax Correction/Highlighting has Vanished in VSC

### ISSUE THREAD

**Issue by NinjaNezumi** [OmniSharp/omnisharp-vscode#5244]
HI everyone!

So, apparently OmniSharp broke, I don't know why or how, and it took me a half dozen uninstalls and reinstalls.  At one point I accidentally installed x86 dotnet.  Well, I also installed and reinstalled the main version of VS.

Whatever happened, it now works.

## Issue Description ##

As of 1 week ago (or so) my VSC stopped showing syntax issues with my code.  The red wavy lines disappeared.  I am in the middle of programming a game in Unity 3D and using VSC to do it.

## Steps to Reproduce ##

It just won't show errors in my code as being errors.

## Expected Behavior ##

When I mistype code, like this:

pubblic int variable;

I expect pubblic to have wavy red lines under it.

## Actual Behavior ##

But VSC stopped doing wavy lines under mistyped code a week ago.

I don't know if I accidentally hit a button or not.

### OmniSharp log ###
<details>Starting OmniSharp server at 5/28/2022, 4:42:03 PM
    Target: c:\Users\bobth\unity projects\8 Bit Testing Grounds\8 Bit Testing Grounds.sln

OmniSharp server started with .NET 6.0.300
.
    Path: c:\Users\bobth\.vscode\extensions\ms-dotnettools.csharp-1.25.0-win32-x64\.omnisharp\1.39.0-net6.0\OmniSharp.dll
    PID: 16976

Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
</details>

### C# log ###
<details> there is nothing in the C# log </details>

## Environment information ##

**VSCode version**: 1.67.2
**C# Extension**: 1.25.0

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.300 [C:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.25.0|;

</details>

**Comment by Bolisk** [comment]
I use unity to create game apps and VSCode is constantly loosisng intellisence. Please fix a stable solution to not have to constantly search for workarounds, or anounce that VSCode should not be used with unity!!

**Comment by filipw** [comment]
Since version 1.25.0 the extension moved by default to .NET 6.0 build of Omnisharp. For Unity development (see https://github.com/OmniSharp/omnisharp-vscode/issues/5120#issue-1174145025 for more details) you have to set the `omnisharp.useModernNet` option to `false`.

**Comment by filipw** [comment]
> Starting OmniSharp server at 5/28/2022, 4:42:03 PM Target: c:\Users\bobth\unity projects\8 Bit Testing Grounds\8 Bit Testing Grounds.sln
> OmniSharp server started with .NET 6.0.300 . Path: c:\Users\bobth.vscode\extensions\ms-dotnettools.csharp-1.25.0-win32-x64.omnisharp\1.39.0-net6.0\OmniSharp.dll PID: 16976
> 
> Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B) [ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

with regards to this error, see https://github.com/OmniSharp/omnisharp-vscode/issues/5242#issuecomment-1140321376
