### ISSUE TITLE
Coredump Instead Of Caught Exception While Debugging An Incorrect DllImport Invocation

### ISSUE THREAD

**Issue by vindicatorr** [OmniSharp/omnisharp-vscode#5249]
## Issue Description ##
When I pinvoke a method inside of a `try...catch`, it isn't caught when I debug in vscode.
## Steps to Reproduce ##
```
        [System.Runtime.InteropServices.DllImport(dllName: "<lib>", EntryPoint = "<doesntExist>", CharSet = System.Runtime.InteropServices.CharSet.Auto)]
        public extern static <returnType> callMeMaybe(System.String param);

            try
            {
                <returnType> ret = callMeMaybe("I dunno");
            }
            catch (System.Exception ex)
            {
                System.Console.WriteLine(ex.ToString());
            }
```
## Expected Behavior ##
Catch the error WHILE debugging in vscode.

## Actual Behavior ##
Exception isn't caught (even with `System.AppDomain.CurrentDomain.UnhandledException` also set) WHILE debugging in vscode...
BUT, it IS caught when running the console program directly.

## Logs ##
```
                Module /opt/dotnet/dotnet with build-id bd83c0b8567ded8aab8d9924fa114b2a5e46fd18
                Module /usr/lib/libicui18n.so.71.1 with build-id 6fd5c97fd2808ee29958bf809656d5885e7e8963
                Module /usr/lib/libicudata.so.71.1 with build-id 4fef196388e678deb881978139e125e20ee2d94d
                Module /usr/lib/libicuuc.so.71.1 with build-id 633fdc0c5385d916571f6140e7a978ad0630ef55
                Module <pathToLib> with build-id a28a51ca719b67f08e7d2e7339c181d3ee60bd2e
                Stack trace of thread 1248890:
                #0  0x00007f8e603d9e84 n/a (n/a + 0x0)
                ELF object binary architecture: AMD x86-64
```
```
                Module /opt/dotnet/dotnet with build-id bd83c0b8567ded8aab8d9924fa114b2a5e46fd18
                Module /usr/lib/libicudata.so.71.1 with build-id 4fef196388e678deb881978139e125e20ee2d94d
                Module /usr/lib/libicui18n.so.71.1 with build-id 6fd5c97fd2808ee29958bf809656d5885e7e8963
                Module /usr/lib/libicuuc.so.71.1 with build-id 633fdc0c5385d916571f6140e7a978ad0630ef55
                Module /opt/dotnet/shared/Microsoft.NETCore.App/6.0.2/libSystem.Native.so with build-id b8d1d024a5920a51614cb1d4acd693aabfdffd87
                Module <pathToLib> with build-id a28a51ca719b67f08e7d2e7339c181d3ee60bd2e
                Stack trace of thread 1243571:
                #0  0x00007f78be3bfe84 n/a (n/a + 0x0)
                ELF object binary architecture: AMD x86-64
```
The address is the same even though you can see the "Modules" may be a little different (not everything being included every time).

It's just for pinvokes only though. If I manually throw, the exception is caught just fine while debugging in vscode.
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.67.0
**C# Extension**: 1.24.5

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/6.0.200/

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.200 [/opt/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [/opt/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [/opt/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cloudcode|googlecloudtools|1.19.0-insiders.0|
|csharp|ms-dotnettools|1.24.5|
|msbuild-project-tools|tintoy|0.4.3|
|vscode-docker|ms-azuretools|1.22.0|;

</details>

EDIT0: I also meant to add that if I select "all" in vscode `BREAKPOINTS`, vscode at least catches the exception, even if it isn't caught by `try...catch`.

EDIT1: And unintentionally causing another coredump differently:
```
                Module /opt/dotnet/dotnet with build-id bd83c0b8567ded8aab8d9924fa114b2a5e46fd18
                Module <pathToLib>
                Stack trace of thread 1298180:
                #0  0x00007f00989b0e84 n/a (n/a + 0x0)
                ELF object binary architecture: AMD x86-64
```
This comes from changing the return value to IntPtr while I figure out what the structs should look like.
It dumps while debugging (stepover) in vscode, but running the console from the cli comes out clean without even any exception being trapped.

**Comment by gregg-miskelly** [comment]
This isn't a problem with this extension -- it sounds like something in the target process has decided that these binding failures should be treated as fatal and is causing the process to abort before the .NET runtime has a chance to convert that failure into an exception.

I will see if I can help get you to the right place.

Questions:
1. Does this work correctly if you Ctrl-F5 from VS Code?
2. Do you get any additional information in stdout/stderr? For example, the signal that the app is terminating with or anything else that might be useful in understanding what is deciding to terminate the app?
3. Can you include a full example app in case that lets me reproduce the failure? I couldn't reproduce this with my example app. I am guessing because of some sort of environment difference, but good to confirm.
4. If this doesn't work in VS Code Ctrl-F5 but does work from `dotnet run` can you add code to your app to print all the environment variables it is launched with and see if there are any differences?

**Comment by vindicatorr** [comment]
Weird, I had advanced on the issue (incorrect dll), and went to revert everything so I could reproduce while answering your questions, but now my initial issue is no longer behaving that way.

I had closed vscode before so I didn't have the full CTRL+Z history. Because I had so few lines of code, I am sure I reverted it well, but can't reproduce the initial dumping issue.

1. It didn't dump for the first case ("dllimport" file "doesntExist"), but not for the second case (likely how I initially am attempting to deal with the return structs which I'll figure out).
2. Nope. If I handle `System.AppDomain.CurrentDomain.FirstChanceException`, I get (for the second case):
```
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll: 'Object reference not set to an instance of an object.'
   at System.SpanHelpers.IndexOf(Byte& searchSpace, Byte value, Int32 length)
```
which of course helps me work through my problems (probably my intptr), but it still coredumps. I'd like to be able to catch ANY exception so it doesn't have to dump.
I'm currently investigating https://docs.microsoft.com/en-us/dotnet/csharp/how-to/how-to-catch-a-non-cls-exception (not looking relevant)
I came across https://docs.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0032, so `[System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptions]` is a no-go.

3. This is where I was going to revert everything except I couldn't reproduce anymore which had me prepend this response with what I said.
4. N/A since I can't reproduce anymore.

Know I'm not looking a solution to my problems (like the incorrect dllname) that are causing the dumps. I'll work through those myself.
I just wanted to be able to catch all exceptions so dumps didn't happen.

But basically I was looking to pinvoke https://github.com/storj/uplink-c (`$ make build` I believe, and `libuplink.so` can be found in `.build`), specifically (https://github.com/storj/uplink-c/blob/main/testsuite/testplanet/example_test.c) `UplinkAccessResult access_result = uplink_parse_access(access_string);`.
(yes, I like being verbose in my code)
```
        public struct UplinkAccess
        {
            public System.IntPtr _handle;
        };

        public struct UplinkError
        {
            public System.Int32 code;
            public System.String message;
        };

        public struct UplinkAccessResult
        {
            public UplinkAccess access;
            public UplinkError error;
        };

        [System.Runtime.InteropServices.DllImport(dllName: "uplink-c/libuplink.so")]
        public extern static UplinkAccessResult uplink_parse_access(System.String accessString);
```
```
        public static System.String test = "i dunno";
        public static System.Int32 Main(System.String[] pArgs)
        {
            System.AppDomain.CurrentDomain.FirstChanceException += OnFirstChanceException;
            System.AppDomain.CurrentDomain.UnhandledException += OnUnhandledException;
            try
            {
                UplinkAccessResult lUplinkAccessResult = uplink_parse_access(test);
            }
            catch (System.Exception cEx)
            {
                System.Console.WriteLine(cEx.ToString());
            }

            System.Console.WriteLine("Hello, World!");

            return 0;
        }

        static void OnUnhandledException(System.Object pObject, System.UnhandledExceptionEventArgs pUnhandledExceptionEventArgs)
        {
            System.Console.WriteLine(pUnhandledExceptionEventArgs.ToString());
        }

        static void OnFirstChanceException(System.Object? pObject, System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs pUnhandledExceptionEventArgs)
        {
            System.Console.WriteLine(pUnhandledExceptionEventArgs.ToString());
        }
```

**Comment by vindicatorr** [comment]
Okay, I managed to replicate it again...
```
public class catchMeTest
{
    public struct UplinkAccessResult
    {
        public System.IntPtr access;

        public System.IntPtr error;
    };

    [System.Runtime.InteropServices.DllImport(dllName: "uplink-c/libuplink.so")]
    public extern static catchMeTest.UplinkAccessResult uplink_parse_access(System.String accessString);

    static void OnUnhandledException(System.Object pObject, System.UnhandledExceptionEventArgs pUnhandledExceptionEventArgs)
    {
        System.Console.WriteLine("unhandled" + pUnhandledExceptionEventArgs.ExceptionObject.ToString());
    }

    static void OnFirstChanceException(System.Object? pObject, System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs pUnhandledExceptionEventArgs)
    {
        System.Console.WriteLine("first" + pUnhandledExceptionEventArgs.Exception.ToString());
    }

    public static System.Int32 Main(System.String[] pArgs)
    {
        System.AppDomain.CurrentDomain.FirstChanceException += OnFirstChanceException;
        System.AppDomain.CurrentDomain.UnhandledException += OnUnhandledException;
        
        catchMeTest.uplink_parse_access("test");

        System.Console.WriteLine("Hello, World!");

        return 0;
    }
}
```
vscode: No firstexception, No unhandledexception. It just dumps.
dotnet cli: "Hello, World!". No dump.

**Comment by gregg-miskelly** [comment]
Thanks! That stack trace should be enough for the .NET Runtime to take a look. It is probably better for you to open the issue since you have the repro. https://github.com/dotnet/runtime/issues
