### ISSUE TITLE
Auto closing brackets not functioning for c# in 1.3.0-insider

### ISSUE THREAD

**Issue by jcloutz** [OmniSharp/omnisharp-vscode#525]
## Environment data
`dotnet --info` output: `bash: dotnet: command not found`
VS Code version: 1.3.0-Insider
C# Extension version: 1.2.1
Legacy C# Extension version: 0.3.3
OS: OSX 10.11.5

## Steps to reproduce
1. Create new c# file (.cs)
2. Type the following `void Foo() {` and the bracket fails to auto close.

## Expected  behavior
Closing bracket should be created to enclose the cursor

## Actual behavior
Closing bracket is not created in the Insiders version of VS Code using either the C# or the Legacy C# extension.

The closing brackets are generated in other languages tested: C, C++, JS, PHP etc. The only language I found that doesn't work it C#.

Both extensions work properly in 1.2.1, but fail to close brackets in 1.3.0-Insider. Originally filed on the VS Code issue tracker (https://github.com/Microsoft/vscode/issues/8662), but they say it's a problem with the plugin.

**Comment by DustinCampbell** [comment]
@jcloutz: Do you have _both_ the C# Extension and the Legacy C# Support Extension installed at once. This is not supported, and its entirely possible that they're conflicting with one another.

**Comment by jcloutz** [comment]
@DustinCampbell, I only had one installed at a time to see if I could replicate the problem across extensions. When it failed for both I figured it was an issue with VSCode, but closed it immediately and claimed it was the extension.

**Comment by DustinCampbell** [comment]
Got it -- thanks for clarifying!

**Comment by DustinCampbell** [comment]
Thanks for filing over here @jcloutz. It looks like the issue was indeed in VS Code and a fix has already been submitted. Thanks!
