### ISSUE TITLE
Exception. System.BadImageFormatException

### ISSUE THREAD

**Issue by justPaulo** [OmniSharp/omnisharp-vscode#5256]
Starting OmniSharp server at 6/7/2022, 3:57:49 PM
    Target: /Users/user/app

OmniSharp server started with .NET 7.0.100-preview.2.22153.17
.
    Path: /Users/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-x64/.omnisharp/1.39.0-net6.0/OmniSharp.dll
    PID: 54684

Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (0x8007000B)
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

**Comment by mreouven** [comment]
I have the same probleme 😢

**Comment by JoeRobich** [comment]
@justPaulo Typically we see this issue with M1 Macs that have a x64 SDK installed instead of the arm64 build. Your situation seems like it may be a little different. Are you on a M1 Mac and have the x64 version of Visual Studio Code installed?

Please provided the output from `dotnet --info`

**Comment by justPaulo** [comment]
@JoeRobich I'm on an M1 Mac with the following details regarding SDKs and VS Code.

~ $ dotnet --info
**.NET SDK** (reflecting any global.json):
 Version:   7.0.100-preview.2.22153.17
 Commit:    9c52c56c13

**Runtime Environment**:
 OS Name:     Mac OS X
 OS Version:  12.4
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100-preview.2.22153.17/

Host (useful for support):
  Version: 7.0.0-preview.2.22152.2
  Commit:  e24f66dff0

**.NET SDKs installed**:
  7.0.100-preview.2.22153.17 [/usr/local/share/dotnet/sdk]

**.NET runtimes installed**:
  Microsoft.AspNetCore.App 7.0.0-preview.2.22153.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-preview.2.22152.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Visual Studio Code**:
Version: 1.67.2
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:57.384Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
**_OS: Darwin x64 21.5.0_**

**Note**: last line of Visual Studio Code details indicate Darwin x64 OS (which is not the case), so I went right now installing a more recent version of Visual Studio Code from https://code.visualstudio.com but previous output error message keeps showing as before:

Version: 1.68.1 (Universal)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:52:13.188Z (3 days ago)
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
_**OS: Darwin arm64 21.5.0**_ 



Starting OmniSharp server at 6/17/2022, 2:40:18 PM
    Target: /Users/user/Toggl3

OmniSharp server started with .NET 7.0.100-preview.2.22153.17
.
    Path: /Users/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-x64/.omnisharp/1.39.0-net6.0/OmniSharp.dll
    PID: 44625

Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (0x8007000B)
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

**Comment by mreouven** [comment]
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.4
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.101 [/usr/local/share/dotnet/sdk]
  6.0.203 [/usr/local/share/dotnet/sdk]
  6.0.300 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.2.22153.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download




I have delete version 7 and reinstall vscode and its work fine 
there is a probleme with the version 7

**Comment by JoeRobich** [comment]
@justPaulo It appears you have the "Universal" install of VS Code installed. 

> Version: 1.68.1 **(Universal)**

This version of VS Code incorrectly downloaded the x64 build of the C# extension.

> Path: /Users/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-**darwin-x64**/.omnisharp/1.39.0-net6.0/OmniSharp.dll

Meaning that it may be running under Rosetta instead of as a native application. I would recommend that you remove VS Code and [download the apple silicon version](https://code.visualstudio.com/Download).

<img width="967" alt="image" src="https://user-images.githubusercontent.com/611219/174646669-63cd1873-2ec8-40f5-9d25-93dd6c6a8109.png">

**Comment by JoeRobich** [comment]
> I have delete version 7 and reinstall vscode and its work fine
there is a probleme with the version 7

@mreouven You may have had the x64 build of the SDK installed, which is incompatible with the arm64 build of the C# extension.

**Comment by justPaulo** [comment]
Already done.



Thanks

**Comment by JoeRobich** [comment]
@justPaulo Did it resolve your issue?

**Comment by justPaulo** [comment]
Well, mostly yes. The only issue now is that if I launch VS Code without sudo, I get this:



But I think this has nothing to do with the support architecture of VS Code or the C# extension that allows debugging.
Hey, much better now ;-)
