### ISSUE TITLE
1.25 is messing with intellisense, no completion/intellisense, no methods recognized... reverting to 1.24.4 makes everything ok

### ISSUE THREAD

**Issue by theAnoOfEarth** [OmniSharp/omnisharp-vscode#5257]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

**Comment by JoeRobich** [comment]
@theAnoOfEarth In 1.25.0 we no longer ship with MSBuild tooling (see announcement at https://github.com/OmniSharp/omnisharp-vscode/issues/5120). Please ensure you have the requirements installed see https://github.com/OmniSharp/omnisharp-vscode#requirements. If you still have troubles, please open a new issues and provide the requested logs and information.
