### ISSUE TITLE
No formatter installed

### ISSUE THREAD

**Issue by Emerix** [OmniSharp/omnisharp-vscode#5263]
We have written the needed data into your clipboard because it was too large to send. Please 
Issue Type: <b>Bug</b>

Trying to format c# files ( in a correct workspace ) does not work any longer. It just says " No formatter for csharp installed " - reinstalling VS Code and/or Omnisharp didn't help either.

Extension version: 1.25.0
VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:16.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (9.15GB free)|
|Process Argv|--crash-reporter-id dcaffdd5-9aa9-49fe-b007-7d6f1669383f|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550

```

</details>

**Comment by JoeRobich** [comment]
@Emerix Can you please share the OmniSharp Log from the VS Code Output Pane? Along with the output of `dotnet --info`.

**Comment by hossein-abdn** [comment]
I had the same problem. The minimum version of .NET for Omnisharp 1.25.0 is 6. I had to update .Net version to fix the problem.

**Comment by Emerix** [comment]
Thanks the the hint with the omnisharp log. It turns out that I needed to install the vs build tools. https://visualstudio.microsoft.com/downloads/?q=build+tools#:~:text=Build%20Tools%20for%20Visual%20Studio%202022
