### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by TannorWallace** [OmniSharp/omnisharp-vscode#5264]
- Issue Type: `Bug`
- Extension Name: `csharp`
- Extension Version: `1.25.0`
- OS Version: `Windows_NT x64 10.0.19043````json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 185,
		"activateCallTime": 6,
		"activateResolvedTime": 44,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-dotnettools.csharp",
				"_lower": "ms-dotnettools.csharp"
			},
			"activationEvent": "workspaceContains:**/*.{csproj,sln,slnf,csx,cake}"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

Unable to generate assets to build and debug. OmniSharp server is not running.

No C# Intellisense or auto fix in visual studio code. 
No options to restart omisharp server
Install/ reinstall / restart processes do not return functionality.
Essentially app is dead in water.

**Comment by JoeRobich** [comment]
@TannorWallace Can you please share the OmniSharp Log from the VS Code Output Pane? As well as the output of `dotnet --info`

**Comment by TannorWallace** [comment]
Issue was due to outdated .NET5 sdk. 
Updated to newer version and problem resolved.
