### ISSUE TITLE
No intellisense in v.1.25.0 on Linux (downgrading to v1.24.4 resolves issue)

### ISSUE THREAD

**Issue by elliottp6** [OmniSharp/omnisharp-vscode#5265]
There's no intellisense on v1.25.0 on Linux with VSCode 1.68.0. Downgrading to v1.24.4 resolves the issue.

Here is a dump of dotnet --info, if this helps. I'm not sure what other information would help to diagnose the issue.

I'm happy with v1.24.4 but figured you should know about the behavior regression on linux.

.NET SDK (reflecting any global.json):
 Version:   5.0.408
 Commit:    da985e2a23

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.408/

Host (useful for support):
  Version: 5.0.17
  Commit:  6a98414363

.NET SDKs installed:
  3.0.103 [/usr/share/dotnet/sdk]
  3.1.419 [/usr/share/dotnet/sdk]
  5.0.408 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by JoeRobich** [comment]
@elliottp6 Can you please share the OmniSharp Log from the VS Code Output pane?
