### ISSUE TITLE
v 1.25.0 intellisense not working with Unity editor v 2020.3.24f1

### ISSUE THREAD

**Issue by GetTheCatExcited** [OmniSharp/omnisharp-vscode#5266]
Started working when I downgraded to C# 1.23.0

**Comment by JoeRobich** [comment]
@GetTheCatExcited For Unity development with v1.25.0 you need to set `OmniSharp.useModernNet` to `false` and to have MSBuild installed. See the requirements at https://github.com/OmniSharp/omnisharp-vscode#requirements for links to download.

**Comment by GetTheCatExcited** [comment]
Thank you for this! Works now with newest versions of both!
