### ISSUE TITLE
Ctrl+P is as slow as in Visual Studio

### ISSUE THREAD

**Issue by floriansimon1** [OmniSharp/omnisharp-vscode#5268]
## Issue Description ##

Whenever I work on a C# project, Ctrl+P becomes borderline unusable. It is so slow to find anything that I can't use it at all. If I open the parent folder, which is not a C# project, then Ctrl+P finds my results immediately, even with an additional million of files. I'm guessing that the C# extension is trying to do something clever which I'd love to just disable if possible.

What I had to do to make my use cases work was to disable Omnisharp on load and enable it manually when I need it (which is like 25% of the time I'd say?).

Visual Studio is the same, and this is one of the reasons why I hate using Visual Studio: it's terrible for quick code exploration.

## Steps to Reproduce ##
Try to use Ctrl+P and find a random class in a big project

## Expected Behavior ##
I'd love to get results within 5s. 10s would be OK as well.

## Actual Behavior ##
Even when I wait a full minute, I don't see anything.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.67.2
**C# Extension**: 1.24.1

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.24.1|
|gitlens|eamodio|12.0.7|
|hexeditor|ms-vscode|1.9.6|
|unity-debug|Unity|3.0.2|
|unity-tools|Tobiah|1.2.12|;

</details>

**Comment by JoeRobich** [comment]
@floriansimon1 With the problematic folder option in VSCode, can you share the OmniSharp Log from the VS Code Output pane?

**Comment by floriansimon1** [comment]
I hadn't re-enabled in a few weeks, and the problem seems to be gone now. I'll reopen if I can reproduce.

The logs were showing that loading my project was taking a while (around 1 minute). I could see each individual project being loaded over time. It's full of private paths so I can't really paste it, and obfuscating it would take a lot of time.

Sorry for the false flag 😨
