### ISSUE TITLE
Namespace usage

### ISSUE THREAD

**Issue by HypeillingerChillinger** [OmniSharp/omnisharp-vscode#5269]
## Describe the solution you would like
When creating a new C# file should use 
```c# 
namespace SampleNamespace;
```

instead of

```c# 
namespace SampleNamespace
{
}
```

**Comment by JoeRobich** [comment]
@HypeillingerChillinger The C# extension does not have a command to create a new C# file. How are you creating new C# files?

**Comment by HypeillingerChillinger** [comment]
You are right. Thats done by
https://marketplace.visualstudio.com/items?itemName=jchannon.csharpextensions

But may be omnisharp-vscode could provide a command with correct namespace?
