### ISSUE TITLE
How can I references too many projects (folders) in Visual Studio Code?

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#527]
_From @HamedFathi on July 4, 2016 20:30_

- VSCode Version: 1.2.1
- OS Version: Windows,Mac

When I used Visual Studio, I had two files format solution (.sln) and project (.csproj).

I want to know in Visual Code

How can I have solution (Root folder) and many projects (sub folders) with dependencies to itself ?

How can I set folders dependencies ? (I want to reference folders together)

please guide me or introduce a source that How can I add many related project with their dependencies in Visual Code.

_Copied from original issue: Microsoft/vscode#8741_

**Comment by jrieken** [comment]
_From @joaomoreno on July 5, 2016 9:8_

@jrieken Can you provide some guidance here?

**Comment by gregg-miskelly** [comment]
@HamedFathi are you using .NET Core or Mono?

This is probably obvious, but VS Code doesn't really have projects or solutions. It just has directories. So you want to open the root directory and VS Code (and the C# extension) will try and figure out what you want.

If you are using .NET Core, then I believe want you would want would be to have one project.json reference another project.json, and I believe you want to build from the directory of whatever root project.json you want to launch (or create a build script if you need to build more than that). In your .vscode/tasks.json you can customize the working directory (`cwd`) to build the project you want. See [debugger.md](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md#3-add-vs-code-configuration-files-to-the-workspace) for more information.

If you are using Mono then the Mono build system does usually use .sln's and .csproj's. The C# extension has limited support for this, though you may want to install the legacy version instead.

**Comment by DustinCampbell** [comment]
@HamedFathi: I'm curious to know whether this is working better for you with the latest version of the C# extension.

**Comment by HamedFathi** [comment]
@DustinCampbell  : few months ago my friend wrote an article for this purpose on codeproject `http://www.codeproject.com/Articles/1110660/How-To-Open-Build-Debug-Multiple-Projects-in-VS-Co` but after vs updates some of that settings automatically added by VS Code. any way, my problem solved. thanks for your efforts . MICROSOFT is BEST

**Comment by DustinCampbell** [comment]
I'm glad to hear that it's working for you. Thanks!

**Comment by Artur-A** [comment]
Now there is a good article in the official VS Code documentation: [how-to-use-multiple-projects](https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries#how-to-use-multiple-projects)
