### ISSUE TITLE
Debugging is broken on fresh install (macOS)

### ISSUE THREAD

**Issue by DaRosenberg** [OmniSharp/omnisharp-vscode#5274]
## Issue Description ##

I am on a fresh install of the whole stack (macOS Monterey, .NET SDK 6.0.300, VS Code and OmniSharp) and for some reason debugging is not working at all:

- No breakpoints are hit (no breakpoint loading errors)
- `Debugger.Break()` has no effect
- `Debug.WriteLine()` prints nothing to the debug console
- Autos, watch etc. I have not been able to test since I cannot get execution to pause

I have gone through the information here:
https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshoot-Breakpoints

But none of it applies (no symbol load issues, no remote debugging, etc.) This is reproducible for me on a completely fresh and clean install of the latest release version of all components involved, with a bare-minimum local .NET 6 console app.

## Steps to Reproduce ##

- `dotnet new console`
- Open folder in VS Code
- Accept the prompt to create launch configuration, build tasks etc.
- Edit `Program.cs` to add the following code:

```cs
using System.Diagnostics;
Debugger.Break(); // Has no effect
var x = Random.Shared.NextInt64(); // <-- Set a breakpoint on this line
Console.WriteLine("Hello, World!"); // Prints to whatever is set in launch.json/configurations[x].console
Debug.WriteLine("Hello, Debugger!"); // Has no effect
```

- Set a breakpoint on line 3
- Start debugging (F5)

## Expected Behavior ##

- Execution should break on line 2, then again on line 3
- "Hello, Debugger" should be printed to the debug console

## Actual Behavior ##

- Execution never breaks
- Nothing is printed to the debug console

### Debugger log ###
<details>
<- (C) {"command":"runInTerminal","arguments":{"kind":"integrated","title":"DebugTest.dll","cwd":"","args":["/Users/danielrosenberg/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-x64/.debugger/x86_64/vsdbg","--interpreter=vscode","--connection=/var/folders/20/nsgrpspd3b10hw186k67vrr00000gn/T/CoreFxPipe_vsdbg-ui-c1794c680fe845a7ae1957ee025e5e6b"]},"seq":2,"type":"request"}
-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-gb","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true},"type":"request","seq":1}
-> (R) {"type":"response","seq":3,"command":"runInTerminal","request_seq":2,"success":true,"body":{"shellProcessId":39619}}
-> (C) {"command":"launch","arguments":{"name":".NET Core Launch (console)","type":"coreclr","request":"launch","preLaunchTask":"build","program":"/Volumes/danielrosenberg/Temp/DebugTest/bin/Debug/net6.0/DebugTest.dll","args":[],"cwd":"/Volumes/danielrosenberg/Temp/DebugTest","console":"integratedTerminal","stopAtEntry":false,"logging":{"engineLogging":false},"__configurationTarget":5,"noDebug":true,"internalConsoleOptions":"openOnSessionStart","__sessionId":"2e098c32-2356-477a-82f2-f7f68f2b38ed"},"type":"request","seq":2}
<- (E) {"seq":3,"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n","severity":"ok"}}
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"launch"}
<- (E) {"seq":5,"type":"event","event":"initialized","body":{}}
-> (C) {"command":"configurationDone","type":"request","seq":4}
<- (E) {"seq":6,"type":"event","event":"process","body":{"name":"/Volumes/danielrosenberg/Temp/DebugTest/bin/Debug/net6.0/DebugTest.dll","systemProcessId":40503,"isLocalProcess":true,"startMethod":null}}
<- (E) {"seq":7,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/Launch","data":{"VS.Diagnostics.Debugger.vsdbg.Launch.Duration":22,"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr","VS.Diagnostics.Debugger.vsdbg.SourceFileMappings":0,"VS.Diagnostics.Debugger.vsdbg.Distribution.Version":"21.5.0","VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"Darwin","VS.Diagnostics.Debugger.vsdbg.TargetType":"Live","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Darwin","VS.Diagnostics.Debugger.vsdbg.VisualizerFileUsed":false,"VS.Diagnostics.Debugger.vsdbg.Version":"17.2.10512.2 commit:9347ab79400fa806261d50481ba445cc6cb0d5e0"}}}
<- (R) {"seq":8,"type":"response","request_seq":4,"success":true,"command":"configurationDone"}
-> (C) {"command":"threads","type":"request","seq":5}
<- (R) {"seq":9,"type":"response","request_seq":5,"success":true,"command":"threads","body":{"threads":[]}}
<- (E) {"seq":10,"type":"event","event":"exited","body":{"exitCode":0}}
<- (E) {"seq":11,"type":"event","event":"terminated","body":{}}
-> (C) {"command":"disconnect","arguments":{"restart":false,"terminateDebuggee":false},"type":"request","seq":6}
<- (E) {"seq":12,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/DebugCompleted","data":{"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr","VS.Diagnostics.Debugger.vsdbg.Distribution.Version":"21.5.0","VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"Darwin","VS.Diagnostics.Debugger.vsdbg.DebugCompleted.BreakCounter":0,"VS.Diagnostics.Debugger.vsdbg.Version":"17.2.10512.2 commit:9347ab79400fa806261d50481ba445cc6cb0d5e0","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Darwin"}}}
<- (R) {"seq":13,"type":"response","request_seq":6,"success":true,"command":"disconnect"}
</details>

### OmniSharp log ###
<details>
Starting OmniSharp server at 6/15/2022, 11:58:07 AM
    Target: /Volumes/danielrosenberg/Temp/DebugTest

OmniSharp server started with .NET 6.0.300
.
    Path: /Users/danielrosenberg/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-x64/.omnisharp/1.39.0-net6.0/OmniSharp.dll
    PID: 40701

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Unknown 0.0 (Unknown)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: .NET Core SDK 6.0.300 17.2.0 - "/usr/local/share/dotnet/sdk/6.0.300/"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 6.0.300 17.2.0 - "/usr/local/share/dotnet/sdk/6.0.300/"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Volumes/danielrosenberg/Temp/DebugTest'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Volumes/danielrosenberg/Temp/DebugTest/DebugTest.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Volumes/danielrosenberg/Temp/DebugTest'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Volumes/danielrosenberg/Temp/DebugTest' on host 39369.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Volumes/danielrosenberg/Temp/DebugTest/DebugTest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Volumes/danielrosenberg/Temp/DebugTest/DebugTest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Volumes/danielrosenberg/Temp/DebugTest/DebugTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: DebugTest
</details>

### C# log ###
<details>
EMPTY
</details>

## Environment information ##

**VSCode version**: 1.68.0
**C# Extension**: 1.25.0

<details><summary>Mono Information</summary>
        There is a problem with running OmniSharp on mono: Error: Unable to find Mono. Ensure that Mono's '/bin' folder is added to your environment's PATH variable.</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.4
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.300/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.300 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|appadmin|AppAdmin|0.1.18|
|azure-account|ms-vscode|0.10.1|
|azurite|Azurite|3.17.1|
|csharp|ms-dotnettools|1.25.0|
|EditorConfig|EditorConfig|0.16.4|
|ng-template|Angular|14.0.1|
|vscode-azurefunctions|ms-azuretools|1.7.3|
|vscode-azureresourcegroups|ms-azuretools|0.5.3|
|vscode-eslint|dbaeumer|2.2.2|;

</details>

**Comment by gregg-miskelly** [comment]
In the trace you provided, the debugger is being told to launch without debugging (`"noDebug":true` is passed). Is that in your launch.json? Or are you executing the "Start without debugging" command?

**Comment by DaRosenberg** [comment]
I am Daniel Rosenberg's complete and utter sense of embarrassment.

I was using the touch bar on the MacBook to start, and apparently there, as opposed to in the VS Code UI, the normal debug icon (green play symbol) means run *without* debugging, whereas the one next to it with a little bug icon overlay is your regular F5.

Might have been more intuitive to use the same icon in the touch bar as in the UI... just sayin'. 😅

Thanks @gregg-miskelly for pointing out the painfully obvious.
