### ISSUE TITLE
OmniSharp cannot find mono when vscode launched from Unity

### ISSUE THREAD

**Issue by dankox** [OmniSharp/omnisharp-vscode#5277]
## Issue Description ##
I'm not sure if this is a problem with Unity or extension or something else, but I thought I might try to ask here first. 
I have `mono` installed and I can open Unity project from the terminal and the vscode properly load the solution and everything works.

However, when I open a file from Unity (without prior opening vscode), Unity will launch vscode and open the project, and omnisharp will not recognize `mono` in path.
My mono is installed from webpage and the path is setup in `/etc/paths.d/mono-commands`. From terminal I can see it:
```
$ which mono
/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono
```

But when executed from Unity, it seems like the path is not used. I can hardcode the path into omnisharp settings, but was wondering, if there is anything else I could use.
Also if I open terminal in vscode the PATH is loaded correctly and I can execute `mono`, so I'm not sure if it's just at start up or what is going on.

Thanks for any suggestion.

## Steps to Reproduce ##
Open C# script from Unity

## Expected Behavior ##
OmniSharp would load solution using installed mono.

## Actual Behavior ##
OmniSharp cannot find mono in PATH.

## Environment information ##

**VSCode version**: 1.68.0
**C# Extension**: 1.25.0
**System**: MacOS Big Sur 11.6

<details><summary>Mono Information</summary>
        There is a problem with running OmniSharp on mono: Error: Unable to find Mono. Ensure that Mono's '/bin' folder is added to your environment's PATH variable.</details>
<details><summary>Mono Information - from terminal</summary>
running command in terminal

```
$ mono --version
Mono JIT compiler version 6.12.0.181 (2020-02/f354099a6b6 Tue May 24 14:18:55 EDT 2022)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```
</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.104
 Commit:    915d644e45

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.6
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/Cellar/dotnet/6.0.104_1/libexec/sdk/6.0.104/

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  6.0.104 [/usr/local/Cellar/dotnet/6.0.104_1/libexec/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [/usr/local/Cellar/dotnet/6.0.104_1/libexec/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [/usr/local/Cellar/dotnet/6.0.104_1/libexec/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

**Comment by JoeRobich** [comment]
@dankox The C# extension expects to find mono from the Environment PATH variable. It sounds like when you launch from a terminal VS Code in inheriting the environment from the shell which is launching it. 

> However, when I open a file from Unity (without prior opening vscode), Unity will launch vscode and open the project, and omnisharp will not recognize mono in path.

Seems like when you launch VS Code from Unity it is not inheriting a fully initialized environment. 

> Also if I open terminal in vscode the PATH is loaded correctly and I can execute mono, so I'm not sure if it's just at start up or what is going on.

VS Code terminal launches your shell which initializes the environment. This is separate from the environment that VS Code is currently running from.


Since I have no clue what is going on behind the scenes when Unity launches VS Code, I would recommend setting the `omnisharp.monoPath` to work around this.

**Comment by dankox** [comment]
@JoeRobich thanks for the response. I was looking around a bit to try to understand what is going on and I think the main "problem" is Mac OS itself. Apparently the first process `launchd` has some specific path set which is the basic one. Paths from `/etc/paths.d` are loaded by shell. And because Unity is started from launcher/docker and afterwards vscode is started from Unity, they all inherit just this basic path :/

I found partial solution to setup the user path to my actual path by issuing this command and restarting computer:
```
sudo launchctl config user path $PATH
```
It worked, however it has a side effect that if my path is changed it won't be reflected anymore.

Anyway, I wrote it all down in case somebody would find this issue and would have the same problem.

I'm closing this issue as it is not really omnisharp issue at all.

**Comment by MisutaaAsriel** [comment]
> Since I have no clue what is going on behind the scenes when Unity launches VS Code, I would recommend setting the `omnisharp.monoPath` to work around this.

FYI this does not work. I have monoPath set but when launched from Unity it still complains and says to download Mono.

Launching VSCode **first** and then opening a project from Unity works. Issue seems directly related to launching VSCode from other executables.
