### ISSUE TITLE
 Code Hints Error 

### ISSUE THREAD

**Issue by linezero** [OmniSharp/omnisharp-vscode#528]
## Environment data
`dotnet --info` output:1.0.0-preview2-003121
VS Code version:1.2.1
C# Extension version:1.2.1
OS Version: Windows

After I input Chinese punctuation, code hints will be no effect.
`’`

I found json.net debug exception is thrown, VS Code then console 

> rejected promise not handled with 1 second

![vscode](https://cloud.githubusercontent.com/assets/4251393/16682824/0c6f15b8-452f-11e6-8282-6baca07a7eb0.gif)

**Comment by RickyLin** [comment]
I tried it out in OS X and there's no problem.

**Comment by DustinCampbell** [comment]
FYI that this is a duplicate issue of #427.
