### ISSUE TITLE
Msbuild Locator problem

### ISSUE THREAD

**Issue by 1w1f** [OmniSharp/omnisharp-vscode#5296]
## Environment data
`dotnet --info` output:
PS C:\Users\82316> dotnet --info
.NET SDK (反映任何 global.json):
 Version:   6.0.301
 Commit:    43f9b18481

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.301\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-sdk [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
VS Code version:1.68.1
C# Extension version:v1.25.0

## OmniSharp log
Starting OmniSharp server at 2022/7/2 19:30:24
    Target: c:\Users\82316\Desktop\test\sln.sln

OmniSharp server started with .NET 6.0.301
.
    Path: c:\Users\82316\.vscode\extensions\ms-dotnettools.csharp-1.25.0-win32-x64\.omnisharp\1.39.0-net6.0\OmniSharp.dll
    PID: 6184

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 10.0.22000.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: .NET Core SDK 6.0.301 17.2.0 - "C:\Program Files\dotnet\sdk\6.0.301\"
            2: .NET Core SDK 6.0.100 17.0.0 - "C:\Program Files\dotnet\sdk\6.0.100\"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 6.0.301 17.2.0 - "C:\Program Files\dotnet\sdk\6.0.301\"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\82316\Desktop\test\sln.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\82316\Desktop\test\testapi\testapi.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\82316\Desktop\test'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\82316\Desktop\test' on host 3776.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\82316\Desktop\test\testapi\testapi.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\82316\Desktop\test\testapi\testapi.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\82316\Desktop\test\testapi\testapi.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: testapi
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 6.

## Steps to reproduce

   Located 2 MSBuild instance(s)
            1: .NET Core SDK 6.0.301 17.2.0 - "C:\Program Files\dotnet\sdk\6.0.301\"
            2: .NET Core SDK 6.0.100 17.0.0 - "C:\Program Files\dotnet\sdk\6.0.100\"

I want to choice  the second instance ( version .NET Core SDK 6.0.100)  but the old way  configure in omnishap.json override msbuild is not work .and I found MSBuildLocator from  the  dotnet SDK path . this is not same to the old c# extension version.i guess something changed with the extension updated. Now How to selected msbuild whatever I want use.

**Comment by JoeRobich** [comment]
@1w1f You can configure the `omnisharp.sdkVersion` to be `6.0.100` in VSCode or you can update your omnisharp.json like so ([see SDKOptions.cs](https://github.com/OmniSharp/omnisharp-roslyn/blob/d086e5bfb634427a82978ff6eed7522938012f8d/src/OmniSharp.Host/MSBuild/Discovery/Providers/SdkOptions.cs#L5-L14)). 
```json
{
 "SDK": {
   "Version": "6.0.100"
 }
}
```

**Comment by 1w1f** [comment]
Oh!Thank you .It work By update Omnisharp.json.
