### ISSUE TITLE
[M1] With SDK 7.0.100-preview.7.22370.3 installed, debug does not respond in VSCode.

### ISSUE THREAD

**Issue by WenJunJi01** [OmniSharp/omnisharp-vscode#5317]
## Steps to reproduce

1. Create a console app.
2. Open it in VSCode.
3. Place a breakpoint.
4. Start debug(F5).

## Expected  behavior
Debug can work fine.

## Actual behavior
Debug does not respond.
![image](https://user-images.githubusercontent.com/87680983/180958254-80d587c7-47f6-4c8c-a5ed-d4831226148a.png)

## Environment data
`dotnet --info` output:
.NET SDK:
 Version:   7.0.100-preview.7.22370.3
 Commit:    dbdda95142

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.5
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100-preview.7.22370.3/

Host:
  Version:      7.0.0-preview.7.22369.4
  Architecture: arm64
  Commit:       db5d4dfd16

.NET SDKs installed:
  7.0.100-preview.7.22370.3 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-preview.7.22369.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-preview.7.22369.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

VS Code version: 1.69.2

C# Extension version: 1.25.0

**Comment by WenJunJi01** [comment]
Not repro on Mac Intel chip and windows arm64.

**Comment by gregg-miskelly** [comment]
I am guessing you are running into: https://github.com/dotnet/runtime/pull/72736

**Comment by WenJunJi01** [comment]
Closed it as not repro.
