### ISSUE TITLE
Omnisharp 1.39.1-beta.31 fails to run after installing

### ISSUE THREAD

**Issue by akakira** [OmniSharp/omnisharp-vscode#5318]
## Issue Description ##
Omnisharp fails to load.
## Steps to Reproduce ##
Install .omnisharp/1.39.1-beta.31-net6.0/ on M1 mac. 

## Expected Behavior ##
I expect omnisharp to run.

## Actual Behavior ##
Omnisharp doesn't run 

### OmniSharp log ###
Unhandled exception. System.BadImageFormatException: Could not load file or assembly '/Users/aarongregory/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-arm64/.omnisharp/1.39.1-beta.31-net6.0/OmniSharp.dll'. An attempt was made to load a program with an incorrect format.

### C# log ###
<details>Starting OmniSharp server at 7/26/2022, 11:31:18 AM
    Target: /Users/aarongregory/projects/virtuescript/eightysixborders-maintenance

OmniSharp server started with .NET 6.0.300
.
    Path: /Users/aarongregory/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-arm64/.omnisharp/1.39.1-beta.31-net6.0/OmniSharp.dll
    PID: 4594

Unhandled exception. System.BadImageFormatException: Could not load file or assembly '/Users/aarongregory/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-arm64/.omnisharp/1.39.1-beta.31-net6.0/OmniSharp.dll'. An attempt was made to load a program with an incorrect format.

File name: '/Users/aarongregory/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-arm64/.omnisharp/1.39.1-beta.31-net6.0/OmniSharp.dll'
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
Starting OmniSharp server at 7/26/2022, 11:32:40 AM
    Target: /Users/aarongregory/projects/virtuescript/eightysixborders-maintenance

OmniSharp server started with .NET 6.0.300
.
    Path: /Users/aarongregory/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-arm64/.omnisharp/1.39.1-beta.31-net6.0/OmniSharp.dll
    PID: 4641

Unhandled exception. System.BadImageFormatException: Could not load file or assembly '/Users/aarongregory/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-arm64/.omnisharp/1.39.1-beta.31-net6.0/OmniSharp.dll'. An attempt was made to load a program with an incorrect format.

File name: '/Users/aarongregory/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-arm64/.omnisharp/1.39.1-beta.31-net6.0/OmniSharp.dll'
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
</details>

## Environment information ##

**VSCode version**: 1.69.2
**C# Extension**: 1.25.0

<details><summary>Mono Information</summary>
        OmniSharp using mono :6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.4
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.300/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  2.1.3 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.105 [/usr/local/share/dotnet/sdk]
  2.1.500 [/usr/local/share/dotnet/sdk]
  2.2.103 [/usr/local/share/dotnet/sdk]
  3.1.102 [/usr/local/share/dotnet/sdk]
  6.0.300 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.25.0|
|nativescript|NativeScript|0.12.3|;

</details>

**Comment by JoeRobich** [comment]
@akakira How did you install 1.39.1-beta.31 ?

Also, can you copy and share the information from the "About Visual Studio Code" screen?

**Comment by akakira** [comment]
ok, i installed it a long time ago and just updated it. Cheers mate!

**Comment by akakira** [comment]
No dice though. I installed the apple silicon version and deleted the extension folder and downloaded the extensions. Still getting this.
Unhandled exception. System.BadImageFormatException: Could not load file or assembly '/Users/aarongregory/.vscode/extensions/ms-dotnettools.csharp-1.25.0-darwin-arm64/.omnisharp/1.39.0-net6.0/OmniSharp.dll'. An attempt was made to load a program with an incorrect format.

Visual Studio
Version: 1.69.2
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:32:39.000Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.5.0

**Comment by JoeRobich** [comment]
Shoot, I should have checked your .NET SDK info first.

Looks like you have the x64 SDK installed. Everything should work if you install the arm64 build of the SDK.

**Comment by akakira** [comment]
I just upgraded from an Intel mac to a M1 Mac, so i'm still working out the kinks, I'll try that.
