### ISSUE TITLE
Code cleanup and Import usings on save

### ISSUE THREAD

**Issue by ziaulhasanhamim** [OmniSharp/omnisharp-vscode#5324]
Recently When I was using golang on vs code I noticed its extensions do some tasks on save like adding import statements, sorting the imports, removing unnecessary imports, formatting the file, etc.

It's a great feature. It boots productivity a lot.

Is there a way we can get these features for C#?

**Comment by filipw** [comment]
you can set `omnisharp.organizeImportsOnFormat: true` in VS code to sort usings when formatting the document.

You can also enable editorconfig and analyzer support support by setting:

```
omnisharp.enableEditorConfigSupport: true
omnisharp.enableRoslynAnalyzers: true
```

You can then configure the many formatting behaviors such as organize imports by changing settings within your `.editorconfig` file. See https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/formatting-rules#organize-using-directives for more details.

Below is an example which will disable sorting system directives to the top.

```ini
root = true

# .NET formatting rules
[*.{cs,vb}]
dotnet_sort_system_directives_first = true
dotnet_separate_import_directive_groups = true
```

you also enable `"editor.formatOnSave": true` in VS Code to execute formatting on save.
