### ISSUE TITLE
Not able to see the red squiggles

### ISSUE THREAD

**Issue by tugberkugurlu** [OmniSharp/omnisharp-vscode#535]
I am not able to see the red squiggles for error conditions like below one:

![image](https://cloud.githubusercontent.com/assets/328122/16654696/d5e6858e-444e-11e6-8f65-7cbc88a8dd9e.png)

I believe it should have highlighted under `var requestCommand`. It's the same for all other cases, I never get red squiggles. Is there a switch now that I should activate?
### VS Code Info

```
Version 1.2.1
Commit fe7f407b95b7f78405846188259504b34ef72761
Date 2016-06-14T12:54:38.105Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```
### C# Extension

![image](https://cloud.githubusercontent.com/assets/328122/16654861/9aec06ec-444f-11e6-9ac3-89d7fbfb079d.png)
### dotnet CLI Info

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

**Comment by DustinCampbell** [comment]
Hi, I'm curious to know if this is still a problem with the latest release of the C# extension (1.3.0).

**Comment by tugberkugurlu** [comment]
I will try this again with the latest version. I think that was mainly the case when I chose global.json as the main project. Then, I started selecting individual projects as omnisharp projects and it had no issues with that but obviously, it was not great for solution wide refactorings.
