### ISSUE TITLE
[NetSDKE2E]With Released .NET 7, CoreFX symbols are missing for IL symbols on MacOS x64

### ISSUE THREAD

**Issue by WenJunJi01** [OmniSharp/omnisharp-vscode#5365]
With SDK:7.0.100-rc.1.22431.12 from (https://dev.azure.com/dnceng/internal/_build/results?buildId=1981363&view=artifacts&pathAsName=false&type=publishedArtifacts) installed.
 
## Steps to reproduce
Testing on Linux with VSCode -
1.	Create a new ASP.NET Razor project by doing
 
mkdir razor
cd razor
dotnet new razor
 
2.	Install VS code (if you have not already) https://code.visualstudio.com/Download 
3.	Launch VSCode and install the C# extension. 
4.	Install the 1.15 or later C# (by OmniSharp) Extention (View -> Extensions, then type OmniSharp, and click on ‘Install’) 
5.	Use File -> Open Folder to open the razor folder you have created in step 1
6.	It may ask at the bottom right to install assets to build and debug, say yes.  
7.	After it has done this it will have created a .vscode directory in the ‘razor’ directory and a ‘launch.json’ file in that directory.   Open the ‘.vscode’ directory, and double click on the ‘launch.json to edit it. 
8.	Add the following lines after the “name” line of the “Configurations” object.   (This allows debugging through the framework.  
 
"justMyCode": false,
"symbolOptions": {
      "searchMicrosoftSymbolServer": true
},
"suppressJITOptimizations": true,
 
 
9.	Double click on the ‘Startup.cs’ file in the ‘Explorer’ pane to bring up that source code. 
10.	 Add the following line to the Startup.cs file at the beginning of the ‘Configure’ method (at the bottom of the file).  
Console.WriteLine("x " + 3);
 
11.	Place a breakpoint on that line (F9). 
12.	Run the application until it hit that breakpoint (F5).   It will load symbols from the Microsoft symbol server, and may take a few seconds to hit the breakpoint.   You should see 20-30 lines of ‘Loaded XXX Symbols loaded’.  Lines as it does this).  
13.	Step into the concatination method (F11).  

## Expected  behavior
CoreCLR symbols are displayed in step13.

## Actual behavior
CoreCLR symbols are missing in step13.
![image](https://user-images.githubusercontent.com/87680983/188420497-93653c02-348e-4c9a-b020-74a999eb8c1f.png)

VS Code version: 1.71.0

C# Extension version: 1.25.1

`dotnet --info` output:
.NET SDK:
 Version:   7.0.100-rc.1.22431.12
 Commit:    f1cf61e1c0

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.6
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100-rc.1.22431.12/

Host:
  Version:      7.0.0-rc.1.22426.10
  Architecture: x64
  Commit:       06aceb7015

.NET SDKs installed:
  7.0.100-rc.1.22431.12 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-rc.1.22427.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-rc.1.22426.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

Note:
It can also repro on 7.0.100-preview.7.22377.5 on MacOS x64.

**Comment by WenJunJi01** [comment]
Not repro on Windows x64 and Windows ARM64.

**Comment by JoeRobich** [comment]
```
The request failed: Connection refused (raw.githubusercontent.com:443) Connection
refused

The URL where the source file will be downloaded from:
https://raw.githubusercontent.com/dotnet/runtime/06aceb7015f3bd...
```

@WenJunJi01 I see that the debugger attempted to locate the source using SourceLink but the connection was refused by GitHub. Is this machines networking configured differently or was this potentially a point-in-time problem with networking?

**Comment by richaverma1** [comment]
@WenJunJi01 can you re-check this scenario as per Joey?

**Comment by WenJunJi01** [comment]
@JoeRobich @richaverma1 I recheck this scenario after downloading [GlobalProtect Portal (microsoft.com)](https://msftvpn-alt.ras.microsoft.com/global-protect/getsoftwarepage.esp) and with VPN connected on the MacOS, it can work fine.
![Screen Shot 2022-09-09 at 1 57 35 PM](https://user-images.githubusercontent.com/87680983/189283330-1f60d469-8c4e-40b8-a16d-ba21f14d87c1.png)
