### ISSUE TITLE
debug: integratedTerminal not working with pipeTransport

### ISSUE THREAD

**Issue by rodrigo455** [OmniSharp/omnisharp-vscode#5374]
## Issue Description ##

following [instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/How-to-run-and-debug-unit-tests) to debug unit tests within a docker container with `pipeTransport` and `console=integratedTerminal`.

Without `pipeTransport`, i.e. running locally, stdin seems to work with `console=integratedTerminal`

## Steps to Reproduce ##

populate `csharp.unitTestDebuggingOptions` with `console=integratedTerminal` and `pipeTransport` configurations and start debugging

## Expected Behavior ##

dotnet terminal appears, enabling interaction with the application(stdin) while debugging

## Actual Behavior ##

no dotnet terminal is created

## Environment information ##

**VSCode version**: 1.70.1
**C# Extension**: 1.25.0

<details><summary>Mono Information</summary>
        OmniSharp using mono :6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.300/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.300 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|1.10.8|
|cpptools-extension-pack|ms-vscode|1.2.0|
|csharp|ms-dotnettools|1.25.0|
|dotnet-interactive-vscode|ms-dotnettools|1.0.3405010|
|doxdocgen|cschlosser|1.4.0|
|jupyter|ms-toolsai|2022.7.1102252217|
|jupyter-renderers|ms-toolsai|1.0.9|
|live-server|ms-vscode|0.2.13|
|python|ms-python|2022.4.1|
|vscode-docker|ms-azuretools|1.22.1|
|vscode-pylance|ms-python|2022.5.1|;

</details>

**Comment by gregg-miskelly** [comment]
This is "by design" for the following two reasons:

* `console` isn't supported with unit test debugging -- it is up to the particular test platform you are using if the platform wants to launch the process, or if it lets the debugger launch. As such, no option that requires the debugger to launch is supported.
* `console` and `pipeTransport` are currently incompatible. It's not impossible to have them work together, but it would require a significant change to how they work. https://github.com/OmniSharp/omnisharp-vscode/issues/4779 tracks this.
