### ISSUE TITLE
c# formatter not work

### ISSUE THREAD

**Issue by 1w1f** [OmniSharp/omnisharp-vscode#5376]
Starting OmniSharp server at 2022/9/18 02:34:42
    Target: d:\Repo\FileService\FileService.sln

OmniSharp server started with .NET 6.0.100
.
    Path: c:\Users\82316\.vscode\extensions\ms-dotnettools.csharp-1.25.0-win32-x64\.omnisharp\1.39.0-net6.0\OmniSharp.dll
    PID: 6640

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 10.0.22000.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: .NET Core SDK 6.0.100 17.0.0 - "C:\Program Files\dotnet\sdk\6.0.100\"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 6.0.100 17.0.0 - "C:\Program Files\dotnet\sdk\6.0.100\"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'd:\Repo\FileService\FileService.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Repo\FileService\FileServiceApi\FileService.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Repo\FileService\FileServiceRepsitory\FileServiceRepsitory.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Repo\FileService\DataModel\DataModel.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\Repo\FileService'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\Repo\FileService' on host 10892.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Repo\FileService\FileServiceApi\FileService.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\Repo\FileService\FileServiceApi\FileService.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\Repo\FileService\FileServiceApi\FileService.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Repo\FileService\FileServiceRepsitory\FileServiceRepsitory.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\Repo\FileService\FileServiceRepsitory\FileServiceRepsitory.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\Repo\FileService\FileServiceRepsitory\FileServiceRepsitory.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Repo\FileService\DataModel\DataModel.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\Repo\FileService\DataModel\DataModel.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\Repo\FileService\DataModel\DataModel.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: FileService
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: FileServiceRepsitory
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: DataModel
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 47.
Received response for /v2/getcodeactions but could not find request.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No symbol found. File: d:\Repo\FileService\FileServiceApi\Controllers\FileController.cs, Line: 48, Column: 22.

 # dotent info 

PS D:\Repo\FileService> dotnet --info
.NET SDK (反映任何 global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.418 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-sdk [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

# vscode version is 1.70.2
I don't not what is wrong . 
omnisharp work good .only formatter feat not work. I rember V1.25.0 c# extesion working  before. format enable is true . default formatter setting is not override.

**Comment by IXLLEGACYIXL** [comment]
its a difference if the formatter doesnt work or omnisharp doesnt work.. omnisharp looks okayish..

try to add that in your vscode settings
`    "[csharp]": {
        "editor.defaultFormatter": "ms-dotnettools.csharp"
    },`

**Comment by 1w1f** [comment]
I already try this way before. it seem to work (vscode don`t show no formatter),but it can`t clear blank line and help Code indentation .....

**Comment by IXLLEGACYIXL** [comment]
`"editor.detectIndentation": true,
    "editor.autoIndent": "advanced",
"editor.formatOnSave": true,
    "editor.formatOnPaste": true,
    "editor.formatOnType": true,`
you can add that for indentation in your settings and add the extension "curly brace formatter" to get the normal c# brace style with next line { and correct indentation on curly braces


it will still delete the tabs on blank lines on a save as thats still an issue in vscode

**Comment by 1w1f** [comment]
It worked  well yesterday! I not change setting.
