### ISSUE TITLE
Why is this extention advertised in Visual Studio market place as developed by Microsoft 

### ISSUE THREAD

**Issue by kev1010** [OmniSharp/omnisharp-vscode#5392]
This extension is published by omnisharp; however, inside VS marketplace it is advertised as developed by Microsoft:

![image](https://user-images.githubusercontent.com/101215507/194167766-271ef723-9246-4481-8bb2-73cbd8b71367.png)

**Comment by JoeRobich** [comment]
@kev1010 This repo is part of the .NET Foundation and Microsoft builds and publishes the C# extension from it. It has been announced that this repo will move under the dotnet GitHub org at some point in the future ([see announcement](https://github.com/OmniSharp/omnisharp-vscode/issues/5276)).

**Comment by kev1010** [comment]
Thank you. I thought the .NET foundation was independent as well and even though Microsoft might publish the Extention, they are not taking responsibility for it. For example, if we were using a CICD pipeline to publish this extension, who would be the publisher then? It also seems weird that Microsoft was able to take over this project. It seems if they wanted to build something on top of it that was closed source they should be allowed, but taking over an open source project (even though there are no user stories or other ways to communicate with the community in this project) seems to undermine the open source community. Are they allowed to do this because they used the .Net Foundation license?

**Comment by filipw** [comment]
Microsoft has never taken over this project. From the beginning of Omnisharp, the VS Code extension was built in house by Microsoft and there was never an Omnisharp VS Code extension not published by Microsoft. 

At the same time, the extension has always been using the Omnisharp server component (which is community built) and just hosted in this Omnisharp organization. Because of that Omnisharp maintainers that are not MS employees contributed here as well.

I will close this issue now - thanks.

**Comment by kev1010** [comment]
According to the [about us page on OmniSharps website](http://www.omnisharp.net/#about), Microsoft didn't own the project but a few of Microsoft's employees worked on the project. Is Microsoft saying the employees didn't have the right to work on the project as individuals? The project was always stored in OmniSharp's repository. If it was owned by Microsoft, why did they not store the project in one of their repos?

![image](https://user-images.githubusercontent.com/101215507/194564009-ef80520c-9287-4903-8121-dd93e0279b03.png)

**Comment by filipw** [comment]
The website is a bit confusing on this topic.

Originally the C# support for VS Code was built as integral part of VS Code (and based on the OmniSharp server which is developed in https://github.com/OmniSharp/omnisharp-roslyn). It was later extracted into a stand alone extension which is developed in this repo, but has - from the beginning - been published into the Extension Marketplace as a Microsoft extension (this also aligned with licensing of e.g. debugger, which is a separate closed source component included with the extension).

The placement in this repo allowed OmniSharp server maintainers (and other OmniSharp extension owners) who are non-MS employees (like me) to easier contribute/triage issues/merge PRs to the extension, and let to the extension becoming part of .NET Foundation too, when OmniSharp joined it a few years ago. But the extension has always been published to the marketplace by Microsoft, under the Microsoft brand.

**Comment by kev1010** [comment]
I don't think publishing code is what creates the ownership. Someone was going to have to publish the code regardless. Just because Microsoft did it, does not make them the owners. Any other member of the project could have published it as well but that doesn't make them own the project. That would undermine open source in general. 

Industry standards such as microservices and dependency injection specifically eliminate the need for the tight coupling that is causing this confusion. It seems that any code that was included in this project now belongs to the project and if the author did not have the right to include the code, then this is a matter between the rightful owner and the author and remedied. 

The [.Net foundation](https://dotnetfoundation.org/) advertises as always open source too. 
![image](https://user-images.githubusercontent.com/101215507/194574729-2ff9f791-a59b-4527-9a29-5c9eb8aff777.png)

**Comment by kev1010** [comment]
This project is also under the [MIT License](https://opensource.org/licenses/MIT)

![image](https://user-images.githubusercontent.com/101215507/194579530-45ba0935-f40b-4b76-b22e-d7b707a2e954.png)
