### ISSUE TITLE
Blazor page formatting continually adding tabs on format/save

### ISSUE THREAD

**Issue by mindflux** [OmniSharp/omnisharp-vscode#5394]
I came across an odd bug, if I have a razor page open and press Ctrl+K, C (compare file to clipboard) the output window throws a couple errors:

`
[Client - 1:49:20 PM] (Warning) Failed to update the C# document buffer. This is unexpected and may result in incorrect C# interactions.

[Client - 1:49:20 PM] (Warning) Failed to update the HTML document buffer. This is unexpected and may result in incorrect HTML interactions.
`

I then press Ctrl+W to close the window and go back to my editor window and press Shift+Alt+F or Ctrl+S (with Format on Save enabled). Once I do that the indents just keep tabbing further and further to the right.   If I close and re-open the malformed file and then press Shift+Alt+F again (or save), it fixes the formatting and does not reproduce itself unless I again use the Ctrl-K, C combo again.

Windows 10 Pro: 21H2
VSCode: 1.71.2
C# Ext : v1.25.0

**Comment by dibarbet** [comment]
@davidwengier FYI razor issue.

**Comment by dibarbet** [comment]
oops, didn't mean to close

**Comment by davidwengier** [comment]
Moved to the Razor repo
