### ISSUE TITLE
Unable to display syntax errors

### ISSUE THREAD

**Issue by kumar231114** [OmniSharp/omnisharp-vscode#5395]
On our current project when we started vscode, unfortunately typing any error codes fails to display any syntax errors on one of the computers, however on my other computer it will work.

I checked the version of `dotnet` (by typing `dotnet --info` on both computers and on the computer that it was working on shows this version number `Version:   6.0.304`

On the computer where it does not work the `dotnet` version is: `Version:   3.1.410`

On the computer where it is not working, I have been using the extension with an old version of `dotnet` for many months with no issues, just suddenly today I started having issues.

I even tried to roll back the c# extension however the issue still persisted.

Any ideas?

**Comment by dibarbet** [comment]
You'll need to be running dotnet 6 or higher to load omnisharp.  We do not support running with dotnet 3.1.
