### ISSUE TITLE
Extension Authoring: Goto Implementation, New Item:class, interface

### ISSUE THREAD

**Issue by agoretsky** [OmniSharp/omnisharp-vscode#540]
In VS Code 1.3 it looks like it's possible to add custom menu items to context menu and etc. What about add GotoImplementation possibility? And also I would like to see in project file's context menu option to add class, interface with automatically generated right namespace. PLEASE

**Comment by DustinCampbell** [comment]
VS Code now supports Go To Implementation as a feature. We'll be tracking the work to add this with https://github.com/OmniSharp/omnisharp-vscode/issues/37.
