### ISSUE TITLE
Unable to attach to CoreCLR. Unknown Error: 0x80131c3c

### ISSUE THREAD

**Issue by cosmic-blunder** [OmniSharp/omnisharp-vscode#5402]
![Screenshot from 2022-10-10 00-17-29](https://user-images.githubusercontent.com/87091993/194774254-35a6d351-8565-47e9-9257-df531eda13c6.png)

**.net6 version is used**
![Screenshot from 2022-10-10 00-18-26](https://user-images.githubusercontent.com/87091993/194774296-d0bc090c-1c26-48b7-8e42-827e8b7ec713.png)

unable to debug the project in LINUX MINT OS 
kernel version-5.15
INTEL CPU i7
16gb ram

**USING VSCODE VERSION-1.72.2**

I**nstalled .net6 by**
`sudo apt-get install dotnet6`

Just created the console app and try to debug the hello world code.

**BUILD WORKS
CODE RUNIG FINE
ON DEBUGGING  IS SHOWING**
**Unable to attach to CoreCLR. Unknown Error: 0x80131c3c**

_Following is my launch and task files_
**### LAUNCH.JSON**

```
{
    "version": "0.2.0",
    "configurations": [
    
        
    
        {
            // Use IntelliSense to find out which attributes exist for C# debugging
            // Use hover for the description of the existing attributes
            // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/bin/Debug/net6.0/gini-projects.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            // For more information about the 'console' field, see https://aka.ms/VSCode-CS-LaunchJson-Console
            "console": "internalConsole",
            "stopAtEntry": false,
            "targetArchitecture": "x86_64"
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "targetArchitecture": "x86_64"
        
        }
    ]
}

```

**### TASK.JSON**
```

{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/gini-projects.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "publish",
            "command": "dotnet",
            "type": "process",
            "args": [
                "publish",
                "${workspaceFolder}/gini-projects.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "watch",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "run",
                "--project",
                "${workspaceFolder}/gini-projects.csproj"
            ],
            "problemMatcher": "$msCompile"
            
        }
    ]
}
```

**Comment by gregg-miskelly** [comment]
That error code is CORDBG_E_DEBUG_COMPONENT_MISSING, which means that the .NET's debugging services dlls (libmscordbi.so and libmscordaccore.so) couldn't be found (or loaded).

Are you publishing a self-contained app? Or is your app using the shared framework? If you haven't modified your project file to do something special, it will default to the shared framework.

Do you have those .sos? Here is where they are on my Ubuntu 22.04 system:
/usr/lib/dotnet/dotnet6-6.0.109/shared/Microsoft.NETCore.App/6.0.9/libmscordaccore.so
/usr/lib/dotnet/dotnet6-6.0.109/shared/Microsoft.NETCore.App/6.0.9/libmscordbi.so

**Comment by cosmic-blunder** [comment]
> /usr/lib/dotnet/dotnet6-6.0.109/shared/Microsoft.NETCore.App/6.0.9/libmscordaccore.so
/usr/lib/dotnet/dotnet6-6.0.109/shared/Microsoft.NETCore.App/6.0.9/libmscordbi.so


@gregg-miskelly  NO i have found no shared libs in those directories.

**Comment by cosmic-blunder** [comment]
Issue fixed by uninstalling prev installed dotnet6 with package manager and  following steps :
1. Installing manually tarbal latest 6.0 and extracting to a path .
2. Setting the path value which  containing dotnet bin   to DOTNET_ROOT env variable in ~/.bashrc
3. restarting vscode fixed  that issue.

**Comment by Kemsekov** [comment]
I have the same error scince dotnet 6 up to current dotnet 7. I don't know where it tries to find these libraries so I don't know where to put them.
I tried to create /usr/lib/dotnet/dotnet7-7.0.0/shared/Microsoft.NETCore.App/7.0.0/libmscordbi.so
files and all of these, but omnisharp path for searching these libraries is mysterious to me. It just cannot find them whatever I do
