### ISSUE TITLE
Code folding does not work for anonymous objects

### ISSUE THREAD

**Issue by mdddev** [OmniSharp/omnisharp-vscode#5406]
Code folding for anonymous object instantiations should be possible as it is for typed object instantiations. This is especially convenient for large and complex anon objects which have multiple nested levels.

![G0sUE](https://user-images.githubusercontent.com/33447232/195400235-406aef67-ffbf-4bfb-8262-8ba2ee2e5109.png)

**Comment by JoeRobich** [comment]
This is a roslyn request. Moved to https://github.com/dotnet/roslyn/issues/64679
