### ISSUE TITLE
Intellisense Suggestion Methods/Properties While Implementing Interface

### ISSUE THREAD

**Issue by MasoudAbdaal** [OmniSharp/omnisharp-vscode#5411]
## Issue Description ##
Intellisense do not show methods and properties which we should implement when we had inherited from an interface.
 
## Steps to Reproduce ##
1. Create new ```dotnet``` project
2. Define an ```interface``` with any property or methods
3. Define an ```class``` which is an implementation from our interface
4. Try to override method with it's name ```(Press CTRL + SPACE)```

![Intellisense](https://user-images.githubusercontent.com/81800801/196907980-27a41888-29f4-4088-b70a-5f1e75636563.png)

## Expected Behavior ##
Show methods and properties should implement from our interface.

## Actual Behavior ##
No suggestion! 
**This behavior also appears in ```abstract class fields```.** 

### OmniSharp log ###
<details>[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 10.0.19043.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: .NET Core SDK 6.0.402 17.3.2 - "C:\Program Files\dotnet\sdk\6.0.402\"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 6.0.402 17.3.2 - "C:\Program Files\dotnet\sdk\6.0.402\"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'd:\dev\.NET\InterfaceTesting'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\dev\.NET\InterfaceTesting\InterfaceTesting.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\dev\.NET\InterfaceTesting'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\dev\.NET\InterfaceTesting' on host 7584.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\dev\.NET\InterfaceTesting\InterfaceTesting.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\dev\.NET\InterfaceTesting\InterfaceTesting.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\dev\.NET\InterfaceTesting\InterfaceTesting.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: InterfaceTesting
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /completion/resolve but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /completion/resolve but could not find request.
Received response for /quickinfo but could not find request.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No symbol found. File: d:\dev\.NET\InterfaceTesting\Program.cs, Line: 10, Column: 15.
Received response for /completion/resolve but could not find request.</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.72.2
**C# Extension**: 1.25.0

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.402
 Commit:    6862418796

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.402\

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  6.0.402 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.25.0|
|es7-react-js-snippets|dsznajder|4.4.3|
|git-graph|mhutchie|1.30.0|
|hexeditor|ms-vscode|1.9.9|
|powershell|ms-vscode|2022.8.5|
|prettier-vscode|esbenp|9.9.0|
|theme-dracula|dracula-theme|2.24.2|;

</details>

**Comment by dibarbet** [comment]
We would need this to be supported by Roslyn.  Tracking issue in roslyn - https://github.com/dotnet/roslyn/issues/63872
Closing as external
