### ISSUE TITLE
coreclr launch/debug has wrong order of priority on envFile and env

### ISSUE THREAD

**Issue by JohnGalt1717** [OmniSharp/omnisharp-vscode#5413]
## Environment data
`dotnet --info` output:

```
.NET SDK:
 Version:   7.0.100-rc.2.22477.23
 Commit:    0a5360315a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-rc.2.22477.23\

Host:
  Version:      7.0.0-rc.2.22472.3
  Architecture: x64
  Commit:       550605cc93

.NET SDKs installed:
  6.0.402 [C:\Program Files\dotnet\sdk]
  7.0.100-rc.2.22477.23 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.2.22476.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22472.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.2.22472.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  D:\Repos\4D\pltfrmd\services\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

VS Code version: 1.72.2
C# Extension version:  1.25.1

## OmniSharp log
NA

## Steps to reproduce

Right now, if you fill in both the env and envFile setting on launch config for any dotnet project, the envFile property overrides the env property. This is backwards to how node/python and many others do it and backwards to how makes logical sense.

## Expected  behavior
env values should override envFile so that if you're getting an automated dump from an envFile you can override those values being put into the environment. (This is especially important for things like Telepresence with k8s because it dumps the ASPNETCORE_ENVIRONMENT variable into the .env that you need to work with other mappings and you can't use that because other things need to be set so you need to have a local versus Kubernetes environment.

## Actual behavior

envFile is overriding the env array.

**Comment by gregg-miskelly** [comment]
Code is here if anyone from the community would like to submit a PR to fix this: https://github.com/OmniSharp/omnisharp-vscode/blob/e3960a0d41155502c2cdbb427573f913ab38f075/src/coreclr-debug/ParsedEnvironmentFile.ts#L22
