### ISSUE TITLE
Rename Symbol `F2` doesn’t work in Razor templates

### ISSUE THREAD

**Issue by patrikholcak** [OmniSharp/omnisharp-vscode#5419]
## Issue Description ##
Renaming a symbol using <kbd>F2</kbd> renames symbols only in `.cs` files but doesn’t update Razor templates. This requires you to remember to manually change all Razor templates. The server fails to start up and lets you know where you messed up but I got caught by this too many times.

## Steps to Reproduce ##
1. Create a class
1. Use it in a Razor template
1. Rename the class in your `.cs` using <kbd>F2</kbd>

## Expected Behavior ##
All occurrences are renamed

## Actual Behavior ##
Only occurrences in `.cs` files are renamed. Razor templates are ignored and need to be manually changed.

## Environment information ##

**VSCode version**: 1.72.2
**C# Extension**: 1.25.0
**.NET SDK**: 6.0.401 (0906eae6f8)

**Comment by dibarbet** [comment]
@davidwengier it looks like we is calling the Razor middleware to remap rename text edits - is there something missing on the razor end?
https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/features/renameProvider.ts#L40

**Comment by davidwengier** [comment]
Moved to the Razor repo
