### ISSUE TITLE
VS Code Doesn't honor "nowarn" in project.json for CS1591 disabling xmlDoc comments

### ISSUE THREAD

**Issue by greghroberts** [OmniSharp/omnisharp-vscode#542]
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version:
Version 1.2.1 (1.2.1)

C# Extension version:
1.2.1
## Steps to reproduce

Set build options to:

```
"buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "warningsAsErrors": true,
    "nowarn": [
      "CS1591"
    ],
    "xmlDoc": true
  },
```
## Expected  behavior

public class and properties should not have a red squiggly.
## Actual behavior

Red squiggly.
![image](https://cloud.githubusercontent.com/assets/294025/16691106/152fa0ea-44e0-11e6-98d5-0b6e93c5f4c8.png)

**Comment by anfomin** [comment]
This issue reproduces in the latest OmniSharp. Any updates?

**Comment by anfomin** [comment]
It's very inconvenient to find real warnings and errors in the list of 1207 items:
![2016-09-07 10 00 52](https://cloud.githubusercontent.com/assets/1905503/18300371/73c90a4e-74ea-11e6-982a-f99a34a7795e.png)

However this warnings are in ignore list in `project.json`:
```json
"buildOptions": {
	"emitEntryPoint": true,
	"preserveCompilationContext": true,
	"xmlDoc": true,
	"nowarn": [ "CS1591", "CS1573" ]
}
```

**Comment by craig006** [comment]
Has anyone figured out a workaround for this? I've also bumped into it and its really difficult to spot actual errors and warnings with so much in the way!
