### ISSUE TITLE
Shared Session? Reduce Memory / CPU use

### ISSUE THREAD

**Issue by lixaotec** [OmniSharp/omnisharp-vscode#5422]
Dear folks,

Pershaps this is more a question than a feature request, as this project is so huge.

We use to develop C# with VSCode and omnisharp in a Windows Server RDS (multiple devs sharing a machine).

Omnisharp seems to rise an instance for each user in his VSCode, and they consume a lot of memory and CPU.

Is it possible to optimize this? Like sharing somehow the Omnisharp ? So it would reduce resources..

Forgive me if this question goes too far away from omnisharp scope.

Thanks in advance

**Comment by dibarbet** [comment]
Unfortunately allowing omnisharp to share resources between different VSCode instances would be extremely complicated.  This is out of scope for the current VSCode extension and we currently don't have any future plans to support this.
