### ISSUE TITLE
C# extension's intellisense is not working

### ISSUE THREAD

**Issue by shaikhshoaib0420** [OmniSharp/omnisharp-vscode#5432]
In my system C# extension's intellisense is not working for .NET Core 6, although I have installed all necessary requirements. Please try to help me here as I have been stucked. can anyone please help me out.

**Comment by 333fred** [comment]
When filing an issue, please fill out the _whole_ bug report form. You haven't given us enough information to help you out. Feel free to open a new issue and provide all the requested information.
