### ISSUE TITLE
Updating past v1.23.9 disables all intellisense functions.

### ISSUE THREAD

**Issue by damaltor** [OmniSharp/omnisharp-vscode#5439]
## Issue Description ##
I used this Extension very much in the end of the last year. it worked perfectly. I then did not use any C# unfortunately for quite a while, but now have to make some changes to the programs i worked on last year. unfortunately, intellisense does no longer work if the c# extension is updated to any version beyond 1.23.9, but it instantly works again when installing 1.23.9 or prior versions.
While the source code is nicely colored, no autocompletion other than text-completion ("abc" in front of the name) is available. This means that autocompletion is only available for any word that i manually typed before, wothout any context, and no other words are in the autocompletion popup. Also, the small "x references" on top of each function name is gone.
As soon as i downgrade to 1.23.9, everything works as expected. This is true for old and for new c# programs made with "dotnet new" command on the console.
## Steps to Reproduce ##
Open VSCODE.
Install current version of C# plugin.
open a new, empty folder.
open console and type "dotnet new console" to start a new c# console project.
try to use autocompletion/intellisense, for example by tying "Console." and maybe pressing ctrl+space, if the popup does not come up.
## Expected Behavior ##
a list of meaningful completions should pop up, for example "Console.Debug", "Console.BackgroundColor", "Console.Beep"
## Actual Behavior ##
Random Words which are in the same file do pop up and can be "completed" without generating valid code in the end

Please tell me what i can do. If i can provide more Information, please let me know. I am not the only one i guess, this stackoverflow thread mentioned downgrading to 1.23.9 twice, so i tried it, and it worked: https://stackoverflow.com/questions/29975152/intellisense-not-automatically-working-vscode
From this thread, i also learned that it might be a problem that c# programs started with "dotnet new console" do not have a sln file, but a csproj file (as they are a single project without a solution around it), but i see no reason why intellisense is not working on simply any c# file. thanks in advance!

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.72.2
**C# Extension**: 1.23.9

<details><summary>Dotnet Information</summary>
.NET SDK (gem�� "global.json"):
 Version:   5.0.408
 Commit:    da985e2a23

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.408\

Host (useful for support):
  Version: 5.0.17
  Commit:  6a98414363

.NET SDKs installed:
  5.0.408 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cmake|twxs|0.0.17|
|cmake-language-support-vscode|josetr|0.0.7|
|cmake-tools|ms-vscode|1.12.27|
|cpptools|ms-vscode|1.12.4|
|csharp|ms-dotnettools|1.23.9|
|doxdocgen|cschlosser|1.4.0|
|git-graph|mhutchie|1.30.0|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|
|vscode-peacock|johnpapa|4.2.2|;

</details>

**Comment by 333fred** [comment]
We'll need you to provide the OmniSharp log in order to help. See the dropdown under `OmniSharp Log` in your issue.

**Comment by damaltor** [comment]
i just wanted to get the log file for you to have a look at, and therefore updated the extension to the most recent version. for some reason or another, it works now.
also i am shocked to see that .net6 does not need a class prorgam and a main function anymore! this is somewhat unsettling...
however, as i cannot reproduce the error now, feel free to close it and i will come back to you whenever i am able to do so again.
thanks for your time!

**Comment by 333fred** [comment]
Alright, glad to hear it's working for you.
