### ISSUE TITLE
1.25.1 no longer finds Mono installation

### ISSUE THREAD

**Issue by heshuimu** [OmniSharp/omnisharp-vscode#5443]
## Issue Description ##
1.25.1 no longer finds Mono installation

## Steps to Reproduce ##
Configure Mono with 1.25.0 and see things are working, and then upgrade C# plugin to 1.25.1 and see the dialog when opening C# project saying that Mono must be installed.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/7824592/200748642-f5327112-8645-49a9-8784-ae8468d3af65.png">

### OmniSharp log ###
OmniSharp failed to start because of missing requirements.

### C# log ###
Empty

## Environment information ##

**VSCode version**: 1.72.0
**C# Extension**: 1.25.1

<details><summary>Mono Information</summary>
        OmniSharp using mono: 6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.0
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: arm64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.201 [/usr/local/share/dotnet/sdk]
  6.0.301 [/usr/local/share/dotnet/sdk]
  6.0.402 [/usr/local/share/dotnet/sdk]
  6.0.403 [/usr/local/share/dotnet/sdk]
  7.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|better-cpp-syntax|jeff-hykin|1.16.3|
|cpptools|ms-vscode|1.12.4|
|cpptools-extension-pack|ms-vscode|1.3.0|
|cpptools-themes|ms-vscode|2.0.0|
|csharp|ms-dotnettools|1.25.1|
|doxdocgen|cschlosser|1.4.0|
|errorlens|usernamehw|3.6.0|
|mono-debug|ms-vscode|0.16.3|
|shaderlabvscode|amlovey|1.2.4|
|subtitles-editor|pepri|1.1.7|
|unity-debug|deitry|3.0.11|
|vscode-antlr4|mike-lischke|2.3.1|
|vscode-clang|mitaki28|0.2.4|
|vscode-icons|vscode-icons-team|12.0.1|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|;

</details>

**Comment by Seikho** [comment]
Same situation here as well on Ubuntu 22.

**Comment by Weiged** [comment]
same here

**Comment by jtsorlinis** [comment]
Same issue here on Mac OS Ventura 13.0.

Working fine on 1.25.0

**Comment by ZeroBloodedge** [comment]
Same here on MacOS Ventura.

**Comment by filipw** [comment]
I apologize for the trouble you are going through. 
This is addressed in #5444.

**Comment by filipw** [comment]
FWIW @dibarbet is empowered to release an update (or perhaps first a prerelease VISX package)

**Comment by stewartm83** [comment]
@filipw did they manage to release the patch?

**Comment by dartyuhov** [comment]
for those who searching for a quick solution:

uninstall c# extension from vscode
download vsix for your platform from here https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.25.0
and install it like this:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/30840813/200874587-14d55f12-2094-4e65-8dc1-17794d8e3d29.png">

**Comment by RaimondZoc** [comment]
> for those who searching for a quick solution:
> 
> uninstall c# extension from vscode download vsix for your platform from here https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.25.0 and install it like this: <img alt="image" width="500" src="https://user-images.githubusercontent.com/30840813/200874587-14d55f12-2094-4e65-8dc1-17794d8e3d29.png">

worked for me, thanks a lot!

**Comment by sq5** [comment]
downgraded to 1.25 to fix this problem

**Comment by DMaxwell02** [comment]
downgraded to 1.25 also fixed my problem

**Comment by EnderDremurr** [comment]
downgrade helped

**Comment by dibarbet** [comment]
1.25.2 has been released.  Please file a new issue if you still encounter issues.  Thanks all!

**Comment by proelf98** [comment]
On MacOS Ventura it worked again when I installed .Net (ARM Version) instead of x64.
Thanks for the tip @Hamedkabir

**Comment by PedroSaraviaQ** [comment]
Hope it'll work for Windows too in future versions ...
