### ISSUE TITLE
On mac m1. Error starting vscode: "Starting client failed Error: spawn Unknown system error -86"

### ISSUE THREAD

**Issue by marvfinsy** [OmniSharp/omnisharp-vscode#5452]
Macbook Pro M1

.NET SDK (reflecting any global.json):
 Version:   6.0.402
 Commit:    6862418796

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.3
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.402/

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: arm64
  Commit:       5a400c212a

.NET SDKs installed:
  6.0.402 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Installed extension in vscode.

1. I receive the below error when opening a blazor project created using dotnet command as described in Dotnet core tutorial.
2. I also receive this error in other directories that are not Blazor projects.

Note that i also installed dotnet 7 and received the same error.
I also removed my virus protection to ensure that it was not the cause.

~thx Marvin Foster
marvinfoster@finsync.com
mmarvb7@gmail.com

------------------

[Client - 1:37:52 AM] Razor language server path: /Users/mb/.vscode/extensions/ms-dotnettools.csharp-1.25.2-darwin-arm64/.razor/rzls
[Client - 1:37:55 AM] Starting Razor Language Server...
[Client - 1:37:55 AM] Server started, waiting for client to be ready...
[Error - 1:37:55 AM] Starting client failed
Error: spawn Unknown system error -86
	at ChildProcess.spawn (node:internal/child_process:413:11)
	at Object.spawn (node:child_process:720:9)
	at /Users/mb/.vscode/extensions/ms-dotnettools.csharp-1.25.2-darwin-arm64/dist/extension.js:2:1254792

**Comment by GeorgePetri** [comment]
I have the same issue.

**Comment by allisonchou** [comment]
Hi all! We released a new version of the C# extension earlier today (v1.25.4) which should fix this issue.

@dibarbet Could you please close this issue out as well?
