### ISSUE TITLE
Project.json intellisense doesn't suggest ASP.NET Core packages

### ISSUE THREAD

**Issue by danroth27** [OmniSharp/omnisharp-vscode#546]
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

VS Code version: 1.3.0
C# Extension version: 1.2.1
## Steps to reproduce

Create a new .NET Core project and open in VS Code:

```
dotnet new
code .
```

Open `project.json`
Try to add any Microsoft.AspNetCore.\* package under `dependencies`
## Expected  behavior

IntelliSense suggestions for ASP.NET Core packages
## Actual behavior

Intellisense simply drops off for ASP.NET Core packages:
![image](https://cloud.githubusercontent.com/assets/1874516/16695671/f06f1734-44f5-11e6-8c12-fae571189a29.png)
![image](https://cloud.githubusercontent.com/assets/1874516/16695697/152c6cfc-44f6-11e6-8940-238029ee562b.png)

**Comment by daniel-refahi** [comment]
having the same problem. no workaround so far.

**Comment by danroth27** [comment]
Project.json is no more

**Comment by filipw** [comment]
@danroth27 you'd be surprised at the places it still lives in 😀
