### ISSUE TITLE
Linux debug launch hangs if the .NET SDK is installed with Snap

### ISSUE THREAD

**Issue by DmitryNaumov** [OmniSharp/omnisharp-vscode#5460]
### Edits by the repro owner:

**Repro steps**:
1. Install the .NET SDK or .NET Runtime via [Snap](https://learn.microsoft.com/en-us/dotnet/core/install/linux-snap) on Linux. There are probably some other technologies that might trigger this problem as well.
2. Create a hello world project
3. Try to debug

**Result**:
Target process hangs when the .NET Runtime loads in the target process and debugging never proceeds

**Work around**:
Install the .NET Runtime using a different technology such as `apt` or the [dotnet-install script](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script).

### Original text
It took me a while to figure out why my remote debugging suddenly stopped working. Here is short version:
I've managed to find how to enable engine logging and here is output:

-> (C) {"command":"threads","type":"request","seq":6}
<- (R) {"seq":13,"type":"response","request_seq":6,"success":true,"command":"threads","body":{"threads":[]}}

v1.25.0 successfully goes further, v1.25.2 stucks at this point until you terminate debugging session.

**Comment by SteveCurran** [comment]
I am seeing the same thing but with launching local debugging on Ubuntu 20.04 using Dotnet 6. Just stops never loads any debug symbols. Works fine with 1.25.0

**Comment by DmitryNaumov** [comment]
@gregg-miskelly  Win10 as client OS running VS Code, .net core 6 & 7 (tried both) on Ubuntu 20.04 as remote OS. It worked like a charm 2 weeks ago (launch) and I would agree that many factors may contribute to this strange behaviour, but downgrading to v1.25.0 fixes that immediately. And looking to changelog gives me idea that this is what has changed in my setup during last week, cause v1.25.1 and v1.25.2 were released a few days ago and v1.25.0 was around for monthes. So you still may be right, but I would say "it is highly likely that recent extension upgrade caused the trouble". Btw I've checked with Golang and it's remote debugging works perfectly. And just in case I've disabled extensions auto update...

**Comment by gregg-miskelly** [comment]
Please provide a full log

**Comment by SteveCurran** [comment]
@gregg-miskelly  opened #5461

**Comment by DmitryNaumov** [comment]
@gregg-miskelly 

<- (C) {"command":"runInTerminal","arguments":{"kind":"integrated","title":"mailer.dll","cwd":"","args":["/home/dmitry-naumov/.vscode-server/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/.debugger/vsdbg","--interpreter=vscode","--connection=/tmp/CoreFxPipe_vsdbg-ui-1301ed2865b1464b9286cc174539dd89"]},"seq":2,"type":"request"}
-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true,"supportsArgsCanBeInterpretedByShell":true},"type":"request","seq":1}
-> (R) {"type":"response","seq":3,"command":"runInTerminal","request_seq":2,"success":true,"body":{"shellProcessId":28895}}
-> (C) {"command":"launch","arguments":{"name":".NET Core Launch (console)","type":"coreclr","request":"launch","preLaunchTask":"build","program":"/home/dmitry-naumov/src/mailer/bin/Debug/net6.0/mailer.dll","args":[],"cwd":"/home/dmitry-naumov/src/mailer","console":"integratedTerminal","stopAtEntry":false,"logging":{"engineLogging":false},"__configurationTarget":6,"internalConsoleOptions":"openOnSessionStart","__sessionId":"d4f72c22-cd70-4e96-b6b2-70fc4008c876"},"type":"request","seq":2}
<- (E) {"seq":3,"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n","severity":"ok"}}

**Comment by DmitryNaumov** [comment]
@gregg-miskelly 

See attached
[Log.txt](https://github.com/OmniSharp/omnisharp-vscode/files/10020918/Log.txt)

**Comment by gregg-miskelly** [comment]
Got it. When you said 'remote debugging' I was thinking of [PipeTransport](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#pipetransport), which would mean that it would be very strange that a new version of the extension would break anything. But you mean you are using VS Code remoting, which makes much more sense. It looks like the two issues are indeed the same.

@DmitryNaumov How did you install the .NET SDK into your Linux machine?

**Comment by gregg-miskelly** [comment]
The underlying problem is tracked with https://github.com/dotnet/diagnostics/issues/3510. This issue will be used to track updating the C# extension once there is a new libdbgshim.so with the fix.

**Comment by DmitryNaumov** [comment]
> How did you install the .NET SDK into your Linux machine?

I've installed .NET via Snap

**Comment by gregg-miskelly** [comment]
> But why downgrading extensions helps to overcome the issue?

.NET Debuggers include a library named libdbgshim.so that comes from the .NET team that is used to load the .NET debugging services. The new version of this library has the bug referenced above. The old version of the extension shipped the previous version of libdbgshim.so. We can't just roll back to the old version though, as new versions of the debugger depend on functionality from the new libdbgshim. So for now, you can either continue using the old version of the C# extension, or you can switch to the Microsoft-built versions of the .NET runtime, such as the one pulled by the dotnet-install script, or the version on the Microsoft apt feed.
