### ISSUE TITLE
Local debugging on Ubuntu no longer works

### ISSUE THREAD

**Issue by SteveCurran** [OmniSharp/omnisharp-vscode#5461]
## Environment data
`dotnet --info` output:

.NET SDK (reflecting any global.json):
 Version:   6.0.403
 Commit:    2bc18bf292

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /snap/dotnet-sdk/187/sdk/6.0.403/

global.json file:
  Not found

Host:
  Version:      6.0.11
  Architecture: x64
  Commit:       943474ca16

.NET SDKs installed:
  6.0.403 [/snap/dotnet-sdk/187/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/snap/dotnet-sdk/187/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/snap/dotnet-sdk/187/shared/Microsoft.NETCore.App]

VS Code version: 1.73.1
C# Extension version: 1.25.2

## OmniSharp log
Starting OmniSharp server at 11/15/2022, 12:52:25 PM
    Target: /home/steve/development/Bot Service/BotService.Service.Host/BotService.Service.Host

OmniSharp server started with .NET 6.0.403
.
    Path: /home/steve/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/.omnisharp/1.39.2-net6.0/OmniSharp.dll
    PID: 1108207

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Unknown 0.0 (Unknown)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: .NET Core SDK 6.0.403 17.3.2 - "/snap/dotnet-sdk/187/sdk/6.0.403/"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 6.0.403 17.3.2 - "/snap/dotnet-sdk/187/sdk/6.0.403/"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/steve/development/Bot Service/BotService.Service.Host/BotService.Service.Host'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/steve/development/Bot Service/BotService.Service.Host/BotService.Service.Host'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/steve/development/Bot Service/BotService.Service.Host/BotService.Service.Host/BotService.Service.Host.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/steve/development/Bot Service/BotService.Service.Host/BotService.Service.Host'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/steve/development/Bot Service/BotService.Service.Host/BotService.Service.Host' on host 1107834.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/steve/development/Bot Service/BotService.Service.Host/BotService.Service.Host/BotService.Service.Host.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/steve/development/Bot Service/BotService.Service.Host/BotService.Service.Host/BotService.Service.Host.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/steve/development/Bot Service/BotService.Service.Host/BotService.Service.Host/BotService.Service.Host.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: BotService.Service.Host
Received response for /v2/codestructure but could not find request.
Received response for /v2/getcodeactions but could not find request.

## Steps to reproduce
Choose a donet sdk project
Debug with launch configuration
Debug launches and no debug symbols are ever loaded, process stops with the following displayed in the debug console

-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------

## Expected  behavior
Expect debugging to start and debug symbols to load

## Actual behavior
Cannot debug because no debug code is loaded

**Comment by gregg-miskelly** [comment]
@SteveCurran can you provide a [debugger log](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging)?

**Comment by SteveCurran** [comment]
@gregg-miskelly 

<- (E) {"seq":25,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/ProcessCreate","data":{"VS.Diagnostics.Debugger.vsdbg.Distribution.Version":"20.04","VS.Diagnostics.Debugger.vsdbg.TargetArchitecture":"AMD64","VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"ubuntu","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Linux","VS.Diagnostics.Debugger.vsdbg.Version":"17.4.11017.1 commit:fe68eee3d38c1935f4872cebf5f8a86033673f76"}}}
<- (E) {"seq":26,"type":"event","event":"process","body":{"name":"/home/steve/development/Bot Service/BotService.Service.Host/BotService.Service.Host/bin/Debug/net6.0/BotService.Service.Host.dll","systemProcessId":1131231,"isLocalProcess":true,"startMethod":"launch"}}
<- (E) {"seq":27,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":1,"verified":false,"message":"No symbols have been loaded for this document.","line":104}}}
<- (E) {"seq":28,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":2,"verified":false,"message":"No symbols have been loaded for this document.","line":127}}}
<- (E) {"seq":29,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":3,"verified":false,"message":"No symbols have been loaded for this document.","line":145}}}
<- (E) {"seq":30,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":4,"verified":false,"message":"No symbols have been loaded for this document.","line":121}}}
<- (E) {"seq":31,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":5,"verified":false,"message":"No symbols have been loaded for this document.","line":125}}}
<- (E) {"seq":32,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":6,"verified":false,"message":"No symbols have been loaded for this document.","line":127}}}
<- (E) {"seq":33,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":7,"verified":false,"message":"No symbols have been loaded for this document.","line":21}}}
<- (E) {"seq":34,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":8,"verified":false,"message":"No symbols have been loaded for this document.","line":32}}}
<- (E) {"seq":35,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":9,"verified":false,"message":"No symbols have been loaded for this document.","line":31}}}
<- (E) {"seq":36,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":10,"verified":false,"message":"No symbols have been loaded for this document.","line":63}}}
<- (E) {"seq":37,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":11,"verified":false,"message":"No symbols have been loaded for this document.","line":91}}}
<- (E) {"seq":38,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":12,"verified":false,"message":"No symbols have been loaded for this document.","line":39}}}
<- (E) {"seq":39,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":13,"verified":false,"message":"No symbols have been loaded for this document.","line":54}}}
<- (E) {"seq":40,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":14,"verified":false,"message":"No symbols have been loaded for this document.","line":24}}}
<- (E) {"seq":41,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":15,"verified":false,"message":"No symbols have been loaded for this document.","line":36}}}
<- (E) {"seq":42,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":16,"verified":false,"message":"No symbols have been loaded for this document.","line":24}}}
<- (E) {"seq":43,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":17,"verified":false,"message":"No symbols have been loaded for this document.","line":29}}}
<- (E) {"seq":44,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":18,"verified":false,"message":"No symbols have been loaded for this document.","line":70}}}
<- (E) {"seq":45,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":19,"verified":false,"message":"No symbols have been loaded for this document.","line":146}}}
<- (E) {"seq":46,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":20,"verified":false,"message":"No symbols have been loaded for this document.","line":100}}}
<- (E) {"seq":47,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":21,"verified":false,"message":"No symbols have been loaded for this document.","line":186}}}
<- (E) {"seq":48,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":22,"verified":false,"message":"No symbols have been loaded for this document.","line":214}}}
<- (E) {"seq":49,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":23,"verified":false,"message":"No symbols have been loaded for this document.","line":221}}}
<- (E) {"seq":50,"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":24,"verified":false,"message":"No symbols have been loaded for this document.","line":25}}}
<- (E) {"seq":51,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/Launch","data":{"VS.Diagnostics.Debugger.vsdbg.Launch.Duration":500,"VS.Diagnostics.Debugger.vsdbg.SourceFileMappings":0,"VS.Diagnostics.Debugger.vsdbg.VisualizerFileUsed":false,"VS.Diagnostics.Debugger.vsdbg.TargetType":"Live","VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr","VS.Diagnostics.Debugger.vsdbg.Distribution.Version":"20.04","VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"ubuntu","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Linux","VS.Diagnostics.Debugger.vsdbg.Version":"17.4.11017.1 commit:fe68eee3d38c1935f4872cebf5f8a86033673f76"}}}
<- (R) {"seq":52,"type":"response","request_seq":21,"success":true,"command":"configurationDone"}
-> (C) {"command":"threads","type":"request","seq":22}
<- (R) {"seq":53,"type":"response","request_seq":22,"success":true,"command":"threads","body":{"threads":[]}}

**Comment by SteveCurran** [comment]
@gregg-miskelly I tried launching and attaching and I see the same issue.

**Comment by gregg-miskelly** [comment]
Looks like this really is the same problem as #5460. Thanks for the logs!

I setup a new Linux VM and installed the .NET SDK using Snap, and I could reproduce the problem.

In case this is useful: I don't see this problem installing the .NET SDK via either `apt` or the [dotnet-install script](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script). So potentially you could temporarily switch to installing it that way.
