### ISSUE TITLE
Omnisharp 1.25.1/2 doesn't respect formatting definitions in omnisharp.json

### ISSUE THREAD

**Issue by RaniSharim** [OmniSharp/omnisharp-vscode#5465]
Please paste the output from your clipboard## Issue Description ##
## Steps to Reproduce ##
I have a c# project.
settings.json have
```
 "[csharp]": {
        "editor.defaultFormatter":  "ms-dotnettools.csharp" ,
        
    },
    "omnisharp.enableRoslynAnalyzers": true,
    "omnisharp.enableEditorConfigSupport": true,
```

I also have an omnisharp.json file which defines formatting options to be applied on `alt-shift-f`
They work fine in 1.25.0. Once the addon was updated to 1.25.1 it stopped respecting them and seems to apply some default options.

## Expected Behavior ##
Formatting rules defined omnisharp.json should be applied.

## Actual Behavior ##
Seems like its applying some default c# formatting options.

### OmniSharp log ###
Starting OmniSharp server at 17/11/2022, 8:04:49
    Target: c:\Users\ranis\Projects\Unity\TagFight\TagFight.sln

OmniSharp server started.
    Path: c:\Users\ranis\.vscode\extensions\ms-dotnettools.csharp-1.25.2-win32-x64\.omnisharp\1.39.2\OmniSharp.exe
    PID: 9916

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: Visual Studio Community 2022 17.1.32414.318 17.1.0 - "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2022 17.1.32414.318 17.1.0 - "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\ranis\Projects\Unity\TagFight'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\ranis\Projects\Unity\TagFight\TagFight.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\ranis\Projects\Unity\TagFight\Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\ranis\Projects\Unity\TagFight\Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\ranis\Projects\Unity\TagFight'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\ranis\Projects\Unity\TagFight' on host 14720.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\ranis\Projects\Unity\TagFight\Assembly-CSharp.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\ranis\Projects\Unity\TagFight\Assembly-CSharp.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\ranis\Projects\Unity\TagFight\Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\ranis\Projects\Unity\TagFight\Assembly-CSharp-Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\ranis\Projects\Unity\TagFight\Assembly-CSharp-Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\ranis\Projects\Unity\TagFight\Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-Editor
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 104.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No symbol found. File: c:\Users\ranis\Projects\Unity\TagFight\Assets\Scripts\Combat\Runes\Effects\AreaOfEffect.cs, Line: 99, Column: 25.
[warn]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 24,
  "Command": "/inlayHint",
  "Arguments": {
    "Location": {
      "FileName": "c:\\Users\\ranis\\Projects\\Unity\\TagFight\\Assets\\Scripts\\Combat\\Runes\\Effects\\AreaOfEffect.cs",
      "Range": {
        "Start": {
          "Line": 29,
          "Column": 0
        },
        "End": {
          "Line": 116,
          "Column": 0
        }
      }
    }
  }
}
[fail]: OmniSharp.Stdio.Host
        ************  Response (124.2120ms) ************ 
{
  "Request_seq": 24,
  "Command": "/inlayHint",
  "Running": true,
  "Success": false,
  "Message": "\"System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.\\r\\nParameter name: index\\r\\n   at Microsoft.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index)\\r\\n   at OmniSharp.Extensions.TextExtensions.GetPositionFromLineAndOffset(SourceText text, Int32 lineNumber, Int32 offset) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn\\\\Extensions\\\\TextExtensions.cs:line 28\\r\\n   at OmniSharp.Extensions.TextExtensions.GetSpanFromRange(SourceText text, Range range) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn\\\\Extensions\\\\TextExtensions.cs:line 55\\r\\n   at OmniSharp.Roslyn.CSharp.Services.InlayHints.InlayHintService.<Handle>d__6.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn.CSharp\\\\Services\\\\InlayHints\\\\InlayHintService.cs:line 58\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.<GetFirstNotEmptyResponseFromHandlers>d__19.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.<HandleRequestForLanguage>d__20.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:line 229\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:line 137\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Stdio.Host.<HandleRequest>d__14.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Stdio\\\\Host.cs:line 218\"",
  "Body": null,
  "Seq": 66,
  "Type": "response"
}
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.

### C# log ###
c# log is empty.

## Environment information ##

**VSCode version**: 1.73.1
**C# Extension**: 1.25.2

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|better-cpp-syntax|jeff-hykin|1.16.3|
|cmake|twxs|0.0.17|
|cmake-tools|ms-vscode|1.12.27|
|cpptools|ms-vscode|1.12.4|
|cpptools-extension-pack|ms-vscode|1.3.0|
|cpptools-themes|ms-vscode|2.0.0|
|csharp|ms-dotnettools|1.25.2|
|doxdocgen|cschlosser|1.4.0|
|gc-excelviewer|GrapeCity|4.2.56|
|gitlens|eamodio|13.0.4|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.6|
|isort|ms-python|2022.6.0|
|java|redhat|1.12.0|
|jupyter|ms-toolsai|2022.9.1202862440|
|jupyter-keymap|ms-toolsai|1.0.0|
|jupyter-renderers|ms-toolsai|1.0.12|
|lalrpop-highlight|mnxn|0.0.1|
|metals|scalameta|1.20.0|
|onehalf-dark|quandinh|0.3.0|
|python|ms-python|2022.18.2|
|qiskit-vscode|qiskit|0.5.5|
|rust-analyzer|rust-lang|0.3.1285|
|rust-syntax|dustypomerleau|0.6.1|
|scala|scala-lang|0.5.6|
|unity-code-snippets|kleber-swf|1.3.0|
|vsc-community-material-theme|Equinusocio|1.4.2|
|vscode-antlr4|mike-lischke|2.3.1|
|vscode-java-debug|vscjava|0.46.0|
|vscode-java-dependency|vscjava|0.21.1|
|vscode-java-pack|vscjava|0.25.6|
|vscode-java-test|vscjava|0.37.1|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.6|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|
|vscode-maven|vscjava|0.39.2|
|vscode-pylance|ms-python|2022.11.20|
|vscode-theme-onedark|akamud|2.3.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.29|;

</details>

**Comment by filipw** [comment]
See the top entry in the readme https://github.com/OmniSharp/omnisharp-vscode#whats-new-in-1251 
The legacy formatting settings from `omnisharp.json` are no longer respected if editorconfig is enabled. You can transfer your formatting to editorconfig file or disable editorconfig.
