### ISSUE TITLE
Can't debug file where multiple file have main method.

### ISSUE THREAD

**Issue by anirugu** [OmniSharp/omnisharp-vscode#5468]
I am maintaining a repos where I write the code in cpp. for debug the specific file I create new file, put the logic and debug and that's work.

I want to do same in C# as well. What I am looking for is creating a new file and debug it and it must work. Right now this is not possible since multiple main method doesn't work in c#.

For better understanding this is the repo https://github.com/anirugu/cpp

You can debug every file by just opening and start debugging. Can we have this feature for C# as well. I know this issue can be simply closed by "By design"

@MadsTorgersen any idea, we can get it worked in C#. Every other language I am seeing have this, like Python, CPP etc.

I write this earlier in vscode https://github.com/microsoft/vscode/issues/164621 

The nearest solution I see is notebook in c# in vs code. Would be great if there is a way to compile simple c# file that is opened (excluding other file from context).

**Comment by gregg-miskelly** [comment]
Assuming I am understanding your scenario, here is how you do what you want:
* Rename all your existing `Main` methods to something like `FileMain`
* Make sure that all of your class names are the same as the source file they are in
* Make a new 'EntryPoint.cs' that contains the real `Main` method. This method should take a command line argument of the class name to run. Use reflection to find this class, find the `FileMain` method, and call it.
* Change launch.json to pass `${fileBasenameNoExtension}` as an argument

**Comment by anirugu** [comment]
@gregg-miskelly  Thanks for your help, I tried to setup both compiler (cpp and csharp) and it's worked for me
this is the repos where I setup all this https://github.com/anirugu/cpp

Additional Steps I followed

1. Use ubuntu 22.04 image to support 7.0
2.  Make the fake csproj file to make dotnet cli happy
3. compile the file against csharp.dll it will let you have Main entrypoint per file.

**Comment by anirugu** [comment]
Whoever is looking for a solution to a problem like this, use .Net Interactive. It will let you code in a single notebook. The good part is you can call the same method with different values so

1. You can test the code with multiple values [test case].
2. It does show the execution time of a method.
3. You don't need to set the .net version, use the latest LTS
4. Don't require the whole project either, just creating a .dib file is enough to solve the problem.
