### ISSUE TITLE
Adding using statements for namespaces using ctrl-. is unreliable

### ISSUE THREAD

**Issue by danroth27** [OmniSharp/omnisharp-vscode#547]
Adding using statements for namespaces using ctrl-. seems really hit and miss. Sometimes it works. Sometimes it only suggests fully qualifying the type name. Sometimes it doesn’t work at all.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

VS Code version: 1.3.0
C# Extension version: 1.2.1
## Repro setup steps

Create a new .NET Core project and open in VS Code:

```
dotnet new
code .
```
## Issue 1

Add the ASP.NET Core Kestrel package in `project.json` in the dependencies node:

``` json
"dependencies": {
  "Microsoft.AspNetCore.Server.Kestrel": "1.0.0"
}
```

Open `Program.cs` and start adding code to create a `WebHostBuilder`:

``` c#
var host = new WebHostBuilder
```

Hit ctrl-. to try to resolve the namespace for `WebHostBuilder` or click on the lightbulb.
### Expected  behavior

Quick fix option to add a using statement for `Microsoft.AspNetCore.Hosting`.
### Actual behavior

While typing you only get the option to fully qualify the type name:
![image](https://cloud.githubusercontent.com/assets/1874516/16695797/933c2042-44f6-11e6-8ef1-07b5de56ad28.png)
## Issue 2

Add the following additional code to `Program.cs` that uses the Run extension method that lives in a different namespace:

``` c#
var host = new WebHostBuilder()
    .UseKestrel()
    .Configure(app => {
        app.Run
```

Hit ctrl-. to try to resolve the namespace for the Run extension method
### Expected behavior

Quick fix option to add a using statement for `Microsoft.AspNetCore.Builder`.
### Actual behavior

No namespace suggestions:
![image](https://cloud.githubusercontent.com/assets/1874516/16696043/dd1eec2a-44f7-11e6-878a-c5e7c76540cc.png)
## Issue 3

Create a Startup.cs file and add the following code:

``` c#
namespace ConsoleApplication
{
    public class Startup 
    {
        public void Configure(IApplicationBuilder)
    }
}
```

Hit ctrl-. to try to resolve the namespace for IApplicationBuilder.
### Expected behavior

Quick fix option to add a using statement for `Microsoft.AspNetCore.Builder`.
### Actual behavior

No namespace suggestions:
![image](https://cloud.githubusercontent.com/assets/1874516/16696025/c7813a9e-44f7-11e6-931a-ceca6675edf1.png)

**Comment by tverboon** [comment]
What I notice on the Mac version is that it sometimes takes while before the using statement appears and it refreshes the menu so it closes again. When hitting CMD+. again the menu option is there. It would be great if the menu doesn't close and refreshes in place, maybe with an indicator that it's still searching?

**Comment by DustinCampbell** [comment]
This should be better with the 1.5 release, but I'm going to keep this bug for the future to take a closer look at it.

**Comment by tverboon** [comment]
After two days working with this new extension, I didn't have a single miss. Performance overall is really great now. Thanks Dustin and team.

**Comment by DustinCampbell** [comment]
@danroth27: I'm going to call this done for 1.7. It's not perfect, but it's much better.

![image](https://cloud.githubusercontent.com/assets/116161/22714913/81ecd502-ed43-11e6-9704-3cbf2a4698bd.png)

![image](https://cloud.githubusercontent.com/assets/116161/22714995/e6104bf4-ed43-11e6-847c-48bfa2b3f01f.png)

![image](https://cloud.githubusercontent.com/assets/116161/22715033/0afb8bb8-ed44-11e6-8fdc-553385c7d186.png)
