### ISSUE TITLE
Cannot find Mono (including MSBuild) on VS Code (Fedora Linux)

### ISSUE THREAD

**Issue by cassis163** [OmniSharp/omnisharp-vscode#5476]
## Environment data
`dotnet --info` output:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.110
 Commit:    ce0a42998a

Runtime Environment:
 OS Name:     fedora
 OS Version:  37
 OS Platform: Linux
 RID:         fedora.37-x64
 Base Path:   /usr/lib64/dotnet/sdk/6.0.110/

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  6.0.110 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```
C# Extension version: 1.25.1

## OmniSharp log
```
OmniSharp failed to start because of missing requirements.
```

## Steps to reproduce
1. Install the VS Code plugin (C#)
2. Install Mono ([according to the documentation](https://www.mono-project.com/download/stable/#download-lin-fedora))
3. Disable 'Use Modern Net' setting in VS Code
4. Set 'Mono Path' to the output of `which mono` (which is 'usr/bin/mono' for me)
5. Ensure that 'msbuild' is installed
6. Restart VS Code
7. VS Code mentions that it still cannot find Mono

## Expected  behavior
VS Code should find my Mono installation and not display an error.

## Actual behavior
VS Code cannot find Mono somehow, even though all requirements seem to be met.

## Additional context
I am on Fedora 37.

**Comment by filipw** [comment]
Which version of Mono do you have? Make sure it is at least `6.12.0.182` and that both `mono` and `msbuild` commands are available via PATH

**Comment by cassis163** [comment]
```
❯ mono --version
Mono JIT compiler version 6.12.0.107 (tarball Wed Dec  9 21:44:58 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```
```
❯ which mono
/usr/bin/mono
❯ which msbuild
/usr/bin/msbuild
```

**Comment by filipw** [comment]
Yes so as as I wrote you need to upgrade to Mono to at least `6.12.0.182`

**Comment by cassis163** [comment]
I upgraded Mono to the nightly version. The documentation promises the stable release version `6.12.0.182` on Fedora, but actually returns an old one (the one I initially used in this issue). It still does not work.
```
❯ mono --version
Mono JIT compiler version 6.13.0.1204 (tarball Sat Oct 30 01:06:02 UTC 2021)
Copyright (C) Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

**Comment by filipw** [comment]
and what does `msbuild --version` print? you need to make sure that the msbuild included in the newly installed Mono is the one discovered on the PATH.

**Comment by cassis163** [comment]
Ok, I apparently removed `msbuild` after my issues with the outdated Mono version. Now it works!

**Comment by filipw** [comment]
ah great!

**Comment by nekochan-no-gittohabu** [comment]
@cassis163 I'm having the same issue but I couldn't find how to upgrade mono. How did you manage to upgrade it?

**Comment by kamisori** [comment]
@nekochan-no-gittohabu try following the directions given here: https://www.mono-project.com/download/stable/#download-lin-ubuntu

ubuntu 23.04 default packages only contain mono 6.8. so you will have to use the repo from the mono project instead for getting 6.12... i did and am happy now
