### ISSUE TITLE
Debugging hangs on Linux, Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 

### ISSUE THREAD

**Issue by steelwil** [OmniSharp/omnisharp-vscode#5488]
## Steps to Reproduce ##
Create simple console project
Create simple classlib project
Include the project reference in csproj
Start Debugging
Sample project [CalcTest.zip](https://github.com/OmniSharp/omnisharp-vscode/files/10198168/CalcTest.zip)

## Expected Behavior ##
Debugging should work.

## Actual Behavior ##
Start Debugging - hangs - press Continue gives
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Operations, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
The same project works fine on Windows

## Logs ##
Loaded '/home/hdd/home/wil/downloads/Microsoft/dotnet-sdk-7.0.100-linux-x64/shared/Microsoft.NETCore.App/7.0.0/System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/hdd/home/wil/projects/dev-work/MES/CalcTest/CalcTest/bin/Debug/net7.0/CalcTest.dll'. Symbols loaded.
Loaded '/home/hdd/home/wil/downloads/Microsoft/dotnet-sdk-7.0.100-linux-x64/shared/Microsoft.NETCore.App/7.0.0/System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Operations, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'Operations, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
The program '[20088] CalcTest.dll' has exited with code 0 (0x0).

### OmniSharp log ###
Starting OmniSharp server at 2022/12/09, 22:17:29
    Target: /home/wil/Projects/dev-work/MES/CalcTest

OmniSharp server started with .NET 7.0.100
.
    Path: /home/wil/.vscode/extensions/ms-dotnettools.csharp-1.25.2/.omnisharp/1.39.2-net6.0/OmniSharp.dll
    PID: 18165

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Unknown 0.0 (Unknown)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: .NET Core SDK 7.0.100 17.4.0 - "/home/hdd/home/wil/downloads/Microsoft/dotnet-sdk-7.0.100-linux-x64/sdk/7.0.100/"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 7.0.100 17.4.0 - "/home/hdd/home/wil/downloads/Microsoft/dotnet-sdk-7.0.100-linux-x64/sdk/7.0.100/"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/wil/Projects/dev-work/MES/CalcTest'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/wil/Projects/dev-work/MES/CalcTest'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/wil/Projects/dev-work/MES/CalcTest/Operations/Operations.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/wil/Projects/dev-work/MES/CalcTest/CalcTest/CalcTest.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/wil/Projects/dev-work/MES/CalcTest'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/wil/Projects/dev-work/MES/CalcTest' on host 17830.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/wil/Projects/dev-work/MES/CalcTest/Operations/Operations.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/wil/Projects/dev-work/MES/CalcTest/Operations/Operations.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/wil/Projects/dev-work/MES/CalcTest/Operations/Operations.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/wil/Projects/dev-work/MES/CalcTest/CalcTest/CalcTest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/wil/Projects/dev-work/MES/CalcTest/CalcTest/CalcTest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/wil/Projects/dev-work/MES/CalcTest/CalcTest/CalcTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Operations
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: CalcTest

### C# log ###
 *  Executing task: dotnet build /home/wil/Projects/dev-work/MES/CalcTest/CalcTest/CalcTest.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary 

MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Operations -> /home/wil/Projects/dev-work/MES/CalcTest/Operations/bin/Debug/net7.0/Operations.dll
  CalcTest -> /home/wil/Projects/dev-work/MES/CalcTest/CalcTest/bin/Debug/net7.0/CalcTest.dll
 *  Terminal will be reused by tasks, press any key to close it. 

## Environment information ##

**VSCode version**: 1.74.0
**C# Extension**: 1.25.2

<details><summary>Mono Information</summary>
        OmniSharp using mono: 6.8.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.10
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/hdd/home/wil/downloads/Microsoft/dotnet-sdk-7.0.100-linux-x64/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [/home/hdd/home/wil/downloads/Microsoft/dotnet-sdk-7.0.100-linux-x64/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/home/hdd/home/wil/downloads/Microsoft/dotnet-sdk-7.0.100-linux-x64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/home/hdd/home/wil/downloads/Microsoft/dotnet-sdk-7.0.100-linux-x64/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|code-spell-checker|streetsidesoftware|2.12.0|
|cpptools|ms-vscode|1.13.7|
|csharp|ms-dotnettools|1.25.2|
|dart-code|Dart-Code|3.54.1|
|flutter|Dart-Code|3.54.0|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.6|
|isort|ms-python|2022.8.0|
|jupyter|ms-toolsai|2022.11.1003412109|
|python|ms-python|2022.20.0|
|test-adapter-converter|ms-vscode|0.1.6|
|vscode-arduino|vsciot-vscode|0.4.12|
|vscode-hp42s-free42|JHeilingbrunner|1.0.7|
|vscode-html-css|ecmel|1.13.1|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.6|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|
|vscode-pylance|ms-python|2022.12.20|
|vscodeintellicode|VisualStudioExptTeam|1.2.29|;

</details>

**Comment by gregg-miskelly** [comment]
@steelwil this doesn't sound like an issue with this extension. It sounds like what is going on is that your app is crashing because 'Operations.dll' isn't being found by the .NET Runtime when you run the app.

**Comment by steelwil** [comment]
Operations.dll is part of the demo example.
`<ProjectReference Include="..\Operations\Operations.csproj" />`
If I change this to use the absolute path it works, but it my real project it starts but crashes with a InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area: }.
`<ProjectReference Include="/home/wil/Projects/dev-work/MES/CalcTest/Operations/Operations.csproj" />`

I would expect relative paths to work.
dotnet run works without an issue.

**Comment by gregg-miskelly** [comment]
@steelwil yes, I looked at your project and saw that Operations.dll was part of the solution.

One possible cause. I saw in your debug logs that you are launching '/home/**hdd/home/wil/projects**/dev-work/MES/CalcTest/CalcTest/bin/Debug/net7.0/CalcTest.dll', but the build output is saying that it is writing '/home/**wil/Projects**/dev-work/MES/CalcTest/CalcTest/bin/Debug/net7.0/CalcTest.dll'. Are those paths actually pointing at the same thing? Or is your launch.json out-of-date or wrong?

I am not an expert on either `dotnet build` or the way the .NET Runtime resolves dependencies at runtime, but my understanding is what should happen is that `dotnet build` should be dropping Operations.dll next to CalcTest.dll, and that is what should allow the .NET runtime to find it. The only role that this extension plays in the process is generating a launch.json for you.

For reference, here is the launch.json that I get with your project (which works on my machine):
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            // Use IntelliSense to find out which attributes exist for C# debugging
            // Use hover for the description of the existing attributes
            // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/CalcTest/bin/Debug/net7.0/CalcTest.dll",
            "args": [],
            "cwd": "${workspaceFolder}/CalcTest",
            // For more information about the 'console' field, see https://aka.ms/VSCode-CS-LaunchJson-Console
            "console": "internalConsole",
            "stopAtEntry": false
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach"
        }
    ]
}
```

**Comment by steelwil** [comment]
@gregg-miskelly thank you for the time that you have spent on this.

The locations are one and the same. It seems that it is getting confused with the symlinks. I moved the project to another non-symlink location and it works. 

I have a small main SSD drive, with a normal drive for the bulk of my user files, I have symlinks to the normal drive. I now just have to figure out a way of doing this so as not to confuse the tooling.
