### ISSUE TITLE
Debugging a project  opened via symlink containing a ProjectReference hangs (Linux)

### ISSUE THREAD

**Issue by steelwil** [OmniSharp/omnisharp-vscode#5492]
## Issue Description ##
I have a simple console project which references a classlib. If I open the project it compiles and debugs as expected.
If I have a symlink to the project location and open VSCode using the symlink debugging hangs with `Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly` Related Issue: #5488
 
## Steps to Reproduce ##
```
cd ~
mkdir wk1
```
extract [CalcTest.zip](https://github.com/OmniSharp/omnisharp-vscode/files/10215815/CalcTest.zip) to wk1
with VSCode open folder ~/wk1/CalcTest/CalcTest/
build and debugging works as expected
```
cd ~
ln -s wk1 wk2
```
with VSCode open folder ~/wk2/CalcTest/CalcTest/
build works but when you try to debug it hangs, pressing continue you get the following error:

## Expected Behavior ##
I would expect both configurations to work. wk1 should not be referenced when working in the wk2 (symlink) directory.

## Actual Behavior ##
Symlink configuration fails to debug

### OmniSharp log ###
<details>
Starting OmniSharp server at 2022/12/13, 10:23:17
    Target: /home/wil/wk2/CalcTest

OmniSharp server started with .NET 7.0.100
.
    Path: /home/wil/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/.omnisharp/1.39.2-net6.0/OmniSharp.dll
    PID: 9408

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Unknown 0.0 (Unknown)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: .NET Core SDK 7.0.100 17.4.0 - "/home/hdd/home/wil/downloads/Microsoft/dotnet-sdk-7.0.100-linux-x64/sdk/7.0.100/"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 7.0.100 17.4.0 - "/home/hdd/home/wil/downloads/Microsoft/dotnet-sdk-7.0.100-linux-x64/sdk/7.0.100/"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/wil/wk2/CalcTest'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/wil/wk2/CalcTest'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/wil/wk2/CalcTest/CalcTest/CalcTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/wil/wk2/CalcTest/Operations/Operations.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/wil/wk2/CalcTest'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/wil/wk2/CalcTest' on host 9175.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/wil/wk2/CalcTest/CalcTest/CalcTest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/wil/wk2/CalcTest/CalcTest/CalcTest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/wil/wk2/CalcTest/CalcTest/CalcTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/wil/wk2/CalcTest/Operations/Operations.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/wil/wk2/CalcTest/Operations/Operations.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/wil/wk2/CalcTest/Operations/Operations.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: CalcTest
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Operations
</details>

### C# log ###
<details>
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  Restored /home/wil/wk2/CalcTest/CalcTest/CalcTest.csproj (in 82 ms).
  1 of 2 projects are up-to-date for restore.
  Operations -> /home/wil/wk2/CalcTest/Operations/bin/Debug/net7.0/Operations.dll
CSC : error CS0006: Metadata file '/home/wil/wk2/CalcTest/Operations/obj/Debug/net7.0/ref/Operations.dll' could not be found [/home/wil/wk2/CalcTest/CalcTest/CalcTest.csproj]

 *  The terminal process "dotnet 'build', '/home/wil/wk2/CalcTest/CalcTest/CalcTest.csproj', '/property:GenerateFullPaths=true', '/consoleloggerparameters:NoSummary'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: dotnet build /home/wil/wk2/CalcTest/CalcTest/CalcTest.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary 

MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Operations -> /home/wil/wk2/CalcTest/Operations/bin/Debug/net7.0/Operations.dll
  CalcTest -> /home/wil/wk2/CalcTest/CalcTest/bin/Debug/net7.0/CalcTest.dll
 *  Terminal will be reused by tasks, press any key to close it. 
</details>

### Debug Console ###
<details>
Loaded '/home/hdd/home/wil/downloads/Microsoft/dotnet-sdk-7.0.100-linux-x64/shared/Microsoft.NETCore.App/7.0.0/System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/wil/wk1/CalcTest/CalcTest/bin/Debug/net7.0/CalcTest.dll'. Symbols loaded.
Loaded '/home/hdd/home/wil/downloads/Microsoft/dotnet-sdk-7.0.100-linux-x64/shared/Microsoft.NETCore.App/7.0.0/System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Operations, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'Operations, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
The program '[9961] CalcTest.dll' has exited with code 0 (0x0).
</details>

## Environment information ##

**VSCode version**: 1.74.0
**C# Extension**: 1.25.2

<details><summary>Mono Information</summary>
        OmniSharp using mono: 6.8.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.10
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/hdd/home/wil/downloads/Microsoft/dotnet-sdk-7.0.100-linux-x64/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [/home/hdd/home/wil/downloads/Microsoft/dotnet-sdk-7.0.100-linux-x64/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/home/hdd/home/wil/downloads/Microsoft/dotnet-sdk-7.0.100-linux-x64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/home/hdd/home/wil/downloads/Microsoft/dotnet-sdk-7.0.100-linux-x64/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|code-spell-checker|streetsidesoftware|2.12.0|
|cpptools|ms-vscode|1.13.7|
|csharp|ms-dotnettools|1.25.2|
|dart-code|Dart-Code|3.54.1|
|flutter|Dart-Code|3.54.0|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.6|
|isort|ms-python|2022.8.0|
|jupyter|ms-toolsai|2022.11.1003412109|
|python|ms-python|2022.20.1|
|test-adapter-converter|ms-vscode|0.1.6|
|vscode-arduino|vsciot-vscode|0.4.12|
|vscode-hp42s-free42|JHeilingbrunner|1.0.7|
|vscode-html-css|ecmel|1.13.1|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.6|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|
|vscode-pylance|ms-python|2022.12.20|
|vscodeintellicode|VisualStudioExptTeam|1.2.29|;

</details>

**Comment by gregg-miskelly** [comment]
This is outside of my area of expertise, but this seems like a problem with `dotnet build`. So, I believe you want to file the issue with https://github.com/dotnet/sdk/issues.

### Minimal repro steps
1. Follow your above steps to create the project and sym link
2. Remove the 'obj' and 'bin' folders to make sure everything is in a clean state
3. `cd wk2/CalcTest/CalcTest`
4. dotnet build "$(pwd)/CalcTest.csproj"

### Result:
dotnet build will generate an incomplete `CalcTest.deps.json` (note the missing entries for Operations.dll):

```json
{
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v7.0",
    "signature": ""
  },
  "compilationOptions": {},
  "targets": {
    ".NETCoreApp,Version=v7.0": {
      "CalcTest/1.0.0": {
        "runtime": {
          "CalcTest.dll": {}
        }
      }
    }
  },
  "libraries": {
    "CalcTest/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    }
  }
}
```

### Expected:
```json
{
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v7.0",
    "signature": ""
  },
  "compilationOptions": {},
  "targets": {
    ".NETCoreApp,Version=v7.0": {
      "CalcTest/1.0.0": {
        "dependencies": {
          "Operations": "1.0.0"
        },
        "runtime": {
          "CalcTest.dll": {}
        }
      },
      "Operations/1.0.0": {
        "runtime": {
          "Operations.dll": {}
        }
      }
    }
  },
  "libraries": {
    "CalcTest/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    },
    "Operations/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    }
  }
}
```

If you replace the incorrect CalcTest.deps.json with a working one, everything works.

### Work around

Modify your tasks.json, and remove the path to the .csproj from `args`, and instead set the `cwd`. Like this:

```json
            "args": [
                "build",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "options": {
                "cwd": "${workspaceFolder}/CalcTest"
            },
```

**Comment by steelwil** [comment]
Thanks @gregg-miskelly for the time you spent on this, the work around works.
