### ISSUE TITLE
Debug console opens every time even when closed before

### ISSUE THREAD

**Issue by ygoe** [OmniSharp/omnisharp-vscode#5497]
## Issue Description ##

Every time I run a simple console application written in C# from VSCode, the debug console opens and comes into the foreground. It contains all kinds of log output that I know from Visual Studio's Output panel. But there I disabled much of the information like loading assemblies because I never ever needed them. Usually, the application then opens in a console window where I can see its output only. In VSCode I had to manually change the launch config from `internalConsole` to `integratedTerminal` to separate the app output from the other noise. While the app output now appears in a separate terminal view, the debug console is always in the front, hiding my app output. That's annoying because I always have to use the mouse to see what my program is doing.

## Steps to Reproduce ##

1. `dotnet new console`
2. Change launch.json `console` setting from `internalConsole` to `integratedTerminal`
3. Press F5

## Expected Behavior ##

I see what the app is printing to the console.

At least that's what happens when I run a Python program. I wanted to see if I can solve my problem better in C# than in Python, still using VSCode. But that makes using C# with VSCode really uncomfortable.

## Actual Behavior ##

That useless debug console pops in front and gives me loads of irrelevant information.

## Logs ##

Haven't seen any.

### OmniSharp log ###
<details>Starting OmniSharp server at 19.12.2022, 20:58:43
    Target: c:\Source\Experiments\VSCodeDotnet

OmniSharp server started with .NET 7.0.100
.
    Path: c:\Users\Yves\.vscode\extensions\ms-dotnettools.csharp-1.25.2-win32-x64\.omnisharp\1.39.2-net6.0\OmniSharp.dll
    PID: 12008

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 10.0.19045.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: .NET Core SDK 7.0.100 17.4.0 - "C:\Program Files\dotnet\sdk\7.0.100\"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 7.0.100 17.4.0 - "C:\Program Files\dotnet\sdk\7.0.100\"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Source\Experiments\VSCodeDotnet'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Source\Experiments\VSCodeDotnet'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Source\Experiments\VSCodeDotnet\VSCodeDotnet.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Source\Experiments\VSCodeDotnet'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Source\Experiments\VSCodeDotnet' on host 36808.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Source\Experiments\VSCodeDotnet\VSCodeDotnet.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Source\Experiments\VSCodeDotnet\VSCodeDotnet.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Source\Experiments\VSCodeDotnet\VSCodeDotnet.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: VSCodeDotnet
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 4.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
</details>

### C# log ###
<details>(empty)</details>

## Environment information ##

**VSCode version**: 1.74.1
**C# Extension**: 1.25.2

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.400 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|better-pageup-pagedown|russelldavis|0.0.1|
|cpptools|ms-vscode|1.13.8|
|csharp|ms-dotnettools|1.25.2|
|cursorCharCode|zeithaste|0.2.2|
|ecdc|mitchdenny|1.8.0|
|isort|ms-python|2022.8.0|
|jinjahtml|samuelcolvin|0.19.0|
|jupyter|ms-toolsai|2022.11.1003412109|
|jupyter-keymap|ms-toolsai|1.0.0|
|jupyter-renderers|ms-toolsai|1.0.12|
|platformio-ide|platformio|2.5.5|
|python|ms-python|2022.20.1|
|remote-explorer|ms-vscode|0.0.3|
|remote-ssh|ms-vscode-remote|0.94.0|
|remote-ssh-edit|ms-vscode-remote|0.84.0|
|trailing-spaces|shardulm94|0.4.1|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.6|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|
|vscode-language-pack-de|MS-CEINTL|1.74.12140926|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-pylance|ms-python|2022.12.20|
|vscode-solution-explorer|fernandoescolar|0.7.4|
|vscode-todo-highlight|jgclark|2.0.4|
|ygoe-theme|Yves Goergen|1.0.0|;

</details>

**Comment by gregg-miskelly** [comment]
Set `"internalConsoleOptions": "neverOpen"` to achieve what you are asking for.
