### ISSUE TITLE
The Sdk path specified in the OmniSharp settings does not exist

### ISSUE THREAD

**Issue by jungaretti** [OmniSharp/omnisharp-vscode#5499]
## Issue Description ##

The `omnisharp.dotnetPath` and `omnisharp.sdkPath` settings aren't working. If I set `omnisharp.sdkPath` to `/usr/local/share/dotnet/sdk/7.0.100`, then I see the following error in OmniSharp's output:

```
The Sdk path specified in the OmniSharp settings does not exist. Configured path is ''/usr/local/share/dotnet/sdk/7.0.100''. Please update your settings and restart OmniSharp.
```

Why are there extra single quotes in that string? Here's my output of `dotnet --list-sdks`

```
7.0.100 [/usr/local/share/dotnet/sdk]
```

There is definitely a .NET SDK at `/usr/local/share/dotnet/sdk/7.0.100`.

## Steps to Reproduce ##

1. Clone https://github.com/jungaretti/playground/tree/omnisharp-bug-repro
2. Use `dotnet --list-sdks` to list SDKs
3. Update `.vscode/settings.json` to point to your SDK
4. `Restart OmniSharp` and check its output
5. Notice that the extension cannot find your SDK

## Expected Behavior ##

The extension should respect whichever SDK you specify with `omnisharp.sdkPath`.

## Actual Behavior ##

The extension adds extra quotes to my SDK path and cannot find the malformed directory.

### OmniSharp log ###
<details>
Starting OmniSharp server at 12/20/2022, 11:43:33 PM
    Target: /Users/jungaretti/Repos/playground

OmniSharp server started with .NET 7.0.100
.
    Path: /Users/jungaretti/.vscode/extensions/ms-dotnettools.csharp-1.25.2-darwin-arm64/.omnisharp/1.39.2-net6.0/OmniSharp.dll
    PID: 8591

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Unknown 0.0 (Unknown)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[fail]: OmniSharp.MSBuild.Discovery.Providers.SdkOverrideInstanceProvider
        The Sdk path specified in the OmniSharp settings does not exist. Configured path is ''/usr/local/share/dotnet/sdk/7.0.100''. Please update your settings and restart OmniSharp.
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: .NET Core SDK 7.0.100 17.4.0 - "/usr/local/share/dotnet/sdk/7.0.100/"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 7.0.100 17.4.0 - "/usr/local/share/dotnet/sdk/7.0.100/"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/jungaretti/Repos/playground'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/jungaretti/Repos/playground'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/jungaretti/Repos/playground/playground.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/jungaretti/Repos/playground'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/jungaretti/Repos/playground' on host 8509.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/jungaretti/Repos/playground/playground.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/jungaretti/Repos/playground/playground.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/jungaretti/Repos/playground/playground.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: playground
</details>

## Environment information ##

**VSCode version**: 1.74.1
**C# Extension**: 1.25.2

<details><summary>Mono Information</summary>
        There is a problem with running OmniSharp on mono: Error: Unable to find Mono. Ensure that Mono's '/bin' folder is added to your environment's PATH variable.</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: arm64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|astro-vscode|astro-build|0.28.2|
|azure-account|ms-vscode|0.11.2|
|cmake|twxs|0.0.17|
|codespaces|GitHub|1.13.5|
|cpptools|ms-vscode|1.13.8|
|csharp|ms-dotnettools|1.25.2|
|file-icons|file-icons|1.0.29|
|go|golang|0.37.0|
|isort|ms-python|2022.8.0|
|jupyter|ms-toolsai|2023.1.1003441034|
|jupyter-keymap|ms-toolsai|1.0.0|
|jupyter-renderers|ms-toolsai|1.0.12|
|markdown-preview-github-styles|bierner|1.0.1|
|one-monokai|azemoh|0.5.0|
|postcss|csstools|1.0.9|
|powershell|ms-vscode|2022.12.1|
|prettier-vscode|esbenp|9.10.3|
|python|ms-python|2022.20.1|
|remote-containers|ms-vscode-remote|0.266.1|
|remote-explorer|ms-vscode|0.0.3|
|remote-ssh|ms-vscode-remote|0.94.0|
|remote-ssh-edit|ms-vscode-remote|0.84.0|
|remote-wsl|ms-vscode-remote|0.72.0|
|sort-typescript-imports|miclo|1.4.1|
|svelte-vscode|svelte|106.4.0|
|vetur|octref|0.36.1|
|vitest-explorer|ZixuanChen|0.2.34|
|vscode-azurefunctions|ms-azuretools|1.9.0|
|vscode-azureresourcegroups|ms-azuretools|0.5.6|
|vscode-azurestaticwebapps|ms-azuretools|0.11.3|
|vscode-choosealicense|ultram4rine|0.9.0|
|vscode-docker|ms-azuretools|1.23.3|
|vscode-github-actions|me-dutour-mathieu|3.0.1|
|vscode-gitignore-generator|piotrpalarz|1.0.3|
|vscode-gitweblinks|reduckted|2.9.0|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.6|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|
|vscode-pull-request-github|GitHub|0.56.0|
|vscode-pylance|ms-python|2022.12.20|
|vscode-remote-extensionpack|ms-vscode-remote|0.23.0|
|vscode-tailwindcss|bradlc|0.9.1|
|vscode-theme-onedark|akamud|2.3.0|
|vscode-yaml|redhat|1.10.1|;

</details>

**Comment by filipw** [comment]
This is a duplicate issue - [see here](https://github.com/OmniSharp/omnisharp-vscode/issues/5463#issuecomment-1359077300) for more details
