### ISSUE TITLE
Invalid launch.json configuration created for hosted Blazor apps

### ISSUE THREAD

**Issue by julioct** [OmniSharp/omnisharp-vscode#5501]
## Issue Description ##
The incorrect launch configuration is populated for hosted Blazor apps. This should work like a charm out of the box, since it's a great start model for new devs.

## Steps to Reproduce ##
1. Create a new hosted Blazor app using `dotnet new blazorwasm --hosted -n hosted`.
2. Open the project in VS Code.
3. When the pop-up to add required assets for build and debug opens up, select YES.
4. Select the Client project (if you select Server, same result, just different value for cwd in launch.json)
5. Open launch.json and notice the incorrect configuration gets generated:

![image](https://user-images.githubusercontent.com/2374270/209027857-62825e3c-7632-4592-b524-5d15b03c324f.png)

## Expected Behavior ##
The generated launch.json should look like this (I think):
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch and Debug Hosted Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}/Client",
            "hosted": true,
            "program": "${workspaceFolder}/Server/bin/Debug/net7.0/hosted.dll",
            "url": "[URL FROM launch.json => profiles => http => applicationUrl]"
        }
    ]
}

```

## Actual Behavior ##
launch.json looks like this:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch and Debug Standalone Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}/Client"
        }
    ]
}
```

### OmniSharp log ###
<details>
Starting OmniSharp server at 12/21/2022, 4:15:52 PM
    Target: d:\Trash\hosted\hosted.sln

OmniSharp server started with .NET 7.0.101
.
    Path: c:\Users\julio\.vscode\extensions\ms-dotnettools.csharp-1.25.2-win32-x64\.omnisharp\1.39.2-net6.0\OmniSharp.dll
    PID: 4332

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 10.0.22621.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: .NET Core SDK 7.0.101 17.4.0 - "C:\Program Files\dotnet\sdk\7.0.101\"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 7.0.101 17.4.0 - "C:\Program Files\dotnet\sdk\7.0.101\"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\Trash\hosted'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'd:\Trash\hosted\hosted.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Trash\hosted\Server\hosted.Server.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Trash\hosted\Client\hosted.Client.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Trash\hosted\Shared\hosted.Shared.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\Trash\hosted'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\Trash\hosted' on host 23744.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Trash\hosted\Server\hosted.Server.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\Trash\hosted\Server\hosted.Server.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\Trash\hosted\Server\hosted.Server.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Trash\hosted\Client\hosted.Client.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\Trash\hosted\Client\hosted.Client.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\Trash\hosted\Client\hosted.Client.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Trash\hosted\Shared\hosted.Shared.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\Trash\hosted\Shared\hosted.Shared.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\Trash\hosted\Shared\hosted.Shared.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: hosted.Server
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: hosted.Client
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: hosted.Shared
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 22.

</details>

### C# log ###
<details>
Empty
</details>

## Environment information ##

**VSCode version**: 1.74.2
**C# Extension**: 1.25.2

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  7.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|blazorwasm-companion|ms-dotnettools|1.1.0|
|csharp|ms-dotnettools|1.25.2|
|csharpextensions|kreativ-software|1.7.3|
|data-workspace-vscode|ms-mssql|0.3.0|
|gitlens|eamodio|13.2.0|
|mongodb-vscode|mongodb|0.9.5|
|mssql|ms-mssql|1.16.0|
|remote-containers|ms-vscode-remote|0.266.1|
|rest-client|humao|0.25.1|
|roslynator|josefpihrt-vscode|4.2.0|
|sql-bindings-vscode|ms-mssql|0.3.0|
|sql-database-projects-vscode|ms-mssql|0.19.0|
|vscode-docker|ms-azuretools|1.23.3|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|
|vscode-icons|vscode-icons-team|12.0.1|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-yaml|redhat|1.10.1|;

</details>

**Comment by gregg-miskelly** [comment]
@NTaylorMullen is this still your area?

**Comment by NTaylorMullen** [comment]
@gregg-miskelly unfortunately not 😢. @danroth27 might know who to route to

**Comment by TanayParikh** [comment]
Just leaving the src here for future reference:

https://github.com/OmniSharp/omnisharp-vscode/blob/a60f4946c7283a4895b9157b1ff2ee6abb25d0b7/src/assets.ts#L333-L342

**Comment by UsernameByCommittee** [comment]
Hi @julioct 

I was looking into this and recently (12/03/2023) updated directions were provided for this very issue [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-7.0&tabs=visual-studio-code#launch-configuration-options)

For an out-of-the-box **hosted** blazorwasm project template in VS Code I used the following settings and they worked like a charm:

`            "name": "Launch and Debug",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}/Server",
            "browser": "chrome",
            "hosted": true,
            "program": "${workspaceFolder}/Server/bin/Debug/net7.0/[PROJECT NAME HERE].Server.dll",
            "url": "http://localhost:[PORT FROM Server/Properties/launchSettings.json here]"`

I'm a fan of your videos, btw! Thank you for the education you provide to the .NET community.

**Comment by julioct** [comment]
@UsernameByCommittee Yes, I've seen those instructions. Yet, I think things should work out of the box and, as of today, you get same broken experience until you make the manual changes.

I'm glad you're liking the videos!
