### ISSUE TITLE
dotnet build to use cwd of active file or parent

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-vscode#551]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

```

VS Code version: 1.3
C# Extension version: 1.2.2

## Steps to reproduce
Open a csharp file under src/MyProject

VSCode is open at a root where it has a `src` and `tests` subfolder

Select `Run Build Task` from command pallette

## Expected  behavior

It builds the project.

## Actual behavior

Output, `Couldn't find 'project.json' in current directory`

The reason this is so is because in `tasks.json` the `cwd` property under `options` property uses the cwd of vscode workspace not the active file.  It would be better if the `dotnet build` task set the `cwd` automatically from where the active file is and search parent directories until it finds the project.json

**Comment by gregg-miskelly** [comment]
@jchannon I don't think your suggestion would really work. Two cases where I **think** this falls down:

1. If you have an entry that references a class library, and you are editing both files. With your suggestion, if the class library file happens to be what is in the foreground when you hit F5, only the class library is going to get recompiled.
2. If you have source files in a subdirectory of the project.json, I would guess that `dotnet build` isn't going to traverse up trying to find your project.json file.

For these reasons, I think the best answer is for the tasks.json to hard code the 'best' `cwd` and to change it as necessary.

Does that sound right to you also, or is there something I am missing?

**Comment by jchannon** [comment]
In the end this is what i ended up doing with some `zsh` magic to traverse up directories and to build/restore all

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "zsh",
    "isShellCommand": true,
    "showOutput": "always",
    "args": [
        "-c"
    ],
    "options": {
        "cwd": "${fileDirname}"
    },
    "tasks": [
        {
            "taskName": "Build Current Project",
            "suppressTaskName": true,
            "isBuildCommand": true,
            "args": [
                "setopt extended_glob && print -l (../)#project.json(:h) | xargs dotnet build 2>&1 | grep -iv warning && echo Build Current Project Completed"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "taskName": "Build All Projects",
            "suppressTaskName": true,
            "isBuildCommand": true,
            "args": [
                "cd ${workspaceRoot} && dotnet build ./**/**/project.json && echo Build All Completed"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "taskName": "Restore All Projects",
            "suppressTaskName": true,
            "isBuildCommand": true,
            "args": [
                "cd ${workspaceRoot} && dotnet restore ./**/**/project.json --verbosity Information && echo Restore All Completed"
            ]
        },
        {
            "taskName": "Restore Current Project",
            "suppressTaskName": true,
            "isBuildCommand": true,
            "args": [
                "setopt extended_glob && print -l (../)#project.json(:h) | xargs dotnet restore --verbosity Information && echo Restore Current Project Completed"
            ]
        }
    ]
}
```

**Comment by gregg-miskelly** [comment]
@jchannon glad you found a solution that you are happy with. I don't think it is necessarily the right thing for all scenarios, but I can certainly see how it can work great for some workflows. I don't always like how loosely couple VS Code is, but the nice thing about it is that it means that everyone can pick something that makes sense for their workflow. We have an existing issue to try and improve the workflow when there are multiple projects -- #310. So I will close this issue for now. But I want to thank you for taking the time to write this up. We will point others to your solution for folks who would like the build to follow the currently open file.
