### ISSUE TITLE
F# support?

### ISSUE THREAD

**Issue by DannyRyman** [OmniSharp/omnisharp-vscode#552]
Should it be possible to debug F# using this extension? I gave it a try and I managed to get some output to the debug console; however, I am unable to add breakpoints to my .fs files.

**Comment by caslan** [comment]
@DannyRyman No, not at the moment. As you have seen yourself, you would get events such as module loads, program output, exceptions etc. but not have any ability to look at callstacks, view variables, bind breakpoints etc. as the support needed for F# debugging is simply not there.

**Comment by caslan** [comment]
@DannyRyman Also, I'm personally not familiar with our F# roadmap. I'll ping a couple folks here and update this post if I can find something to share.

**Comment by DannyRyman** [comment]
ok, thanks for the confirmation.
