### ISSUE TITLE
VS Code: After installing Visual Studio Green extension, errors occurred when open a project and click close solution in Solution Explorer.

### ISSUE THREAD

**Issue by 6Ella** [OmniSharp/omnisharp-vscode#5529]
**Describe the bug:**
After installing Visual Studio Green extension, errors occurred when open a project and click close solution in Solution Explorer.
 
**Version used:**
VS Code: 1.74.3
Visual Studio Green version: v0.0.187-alpha
SDK: 7.0.2
 
**Platform**
 
- [x] Windows ARM64
- [x] Mac ARM64

**To reproduce:**
 
1. Go to [VS-GREEN vsix ](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7169232&view=artifacts&pathAsName=false&type=publishedArtifacts) Download the Visual Studio Green.vsix.
![extension](https://user-images.githubusercontent.com/92350568/212037529-e5229df8-041d-41f9-90e1-0cfb10863f65.png)

2. In VS Code and go to the Extensions Tab, select "Install from VSIX" > install the file you downloaded.
3. Open a normal Terminal Emulator, create MVC project and open it using VS code
```
mkdir MVC3x
cd MVC3x
dotnet new mvc 
code .
```

 4. In VS Code, wait for a minute an error will occurred then click "..." > "close solution" in Solution Explorer, another error also occurred.
 
**Actual behavior:**
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/92350568/212037571-99b4ea71-9a2b-4edb-b28e-b38cb7f705f1.png)

**Expected behavior:**
Open solution with VS Code without any error.

Note:
This issue only repro in Windows ARM64 and Mac ARM64, not repro in Windows X64 and Mac X64

**Comment by sayedihashimi** [comment]
@6Ella we should not be filing issues here, let's discuss over email.
