### ISSUE TITLE
wrong url of Legacy C# Support extension in VSCode's introduction view with Mac OS X.

### ISSUE THREAD

**Issue by sassembla** [OmniSharp/omnisharp-vscode#553]
correct Legacy C# Support extension url is below.
https://marketplace.visualstudio.com/items?itemName=ms-vscode.omnisharp

but current target url is below.(goes to wrong empty page of marketplace.)
https://marketplace.visualstudio.com/items?itemName%3Dms-vscode.omnisharp

<img width="807" alt="2016-07-11 1 17 20" src="https://cloud.githubusercontent.com/assets/944441/16714672/6ba008d0-4705-11e6-8510-92570860f35e.png">

**Comment by sassembla** [comment]
Oops, Close button has been pressed by my mistake.

**Comment by DustinCampbell** [comment]
Thanks @sassembla! Apologies for the error!

**Comment by DustinCampbell** [comment]
This should go away with this release. We're removing the need for the Legacy C# Support extension in 1.3

**Comment by DustinCampbell** [comment]
This has been removed from our readme.md. Once we ship the latest extension (1.3.0) to the marketplace, this will be reflected there as well.
