### ISSUE TITLE
Code folding buggy in 1.25.4

### ISSUE THREAD

**Issue by lonix1** [OmniSharp/omnisharp-vscode#5553]
## Environment data
Latest of everything
`dotnet --info` output: 1.25.4
VS Code version: 1.74.3
C# Extension version: 6.0.405

## OmniSharp log
Massive... what is of interest?

## Steps to reproduce
- Open vscode
- Open blazor component (`Foo.razor`)

## Expected  behavior
Code folding to work

## Actual behavior
Does not work properly. Some ranges folded and others not. No plus/minus buttons to fold those ranges.

## Additional context
This problem goes back years, but I thought today's update would fix it. It feels slightly worse in fact, as files I was working on before updating are now not foldable.

**Comment by allisonchou** [comment]
@lonix1 Thanks for the report! We're working on this. On the Razor side, this is tracked by https://github.com/dotnet/razor/issues/6811. We'll need to work with some partner teams to get this implemented.

**Comment by allisonchou** [comment]
Closing out as a dupe, but have followed up again with partner teams.

**Comment by allisonchou** [comment]
Hi @lonix1, we have to do some work on the Razor side to adopt the changes made in the upstream issue. The good news is that this work is on our roadmap, so it should hopefully be a part of an upcoming release.
