### ISSUE TITLE
1.25.4 macOS Intel missing from extension marketplace

### ISSUE THREAD

**Issue by tillig** [OmniSharp/omnisharp-vscode#5565]
v1.25.4 doesn't appear to have support for macOS Intel so does not show up as an available upgrade. The last upgrade available for macOS Intel is 1.25.2.

Forcing a refresh in VS Code to check for updates does not detect anything.

Looking in the Marketplace I can see 1.25.2 has a download for macOS Intel

<img width="400" alt="1.25.2 has macOS Intel as a download option" src="https://user-images.githubusercontent.com/1156571/215588420-f612389f-b069-42fc-882f-4e252765db62.png">

1.25.4 does not have that entry

<img width="400" alt="1.25.4 does not have macOS Intel as a download option" src="https://user-images.githubusercontent.com/1156571/215588553-b584f20f-3c2b-4887-93d6-8cdbaec16c96.png">

I do see that the [release on GitHub for 1.25.4](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.25.4) has a `csharp-1.25.4-darwin-x64.vsix` artifact so it looks like the build generated it, it just didn't get pushed to the marketplace. Possible bug in the deployment pipeline?

**Comment by tillig** [comment]
Installing from VSIX using the artifact in the release works as a workaround, you just can't get the update from the marketplace.

**Comment by tillig** [comment]
Turns out installing from VSIX is great as long as you ignore settings sync. Really hoses things up if you go to another machine, like Mac to Windows and back.

**Comment by dibarbet** [comment]
Apologies - this should be fixed now
<img width="545" alt="image" src="https://user-images.githubusercontent.com/5749229/217134402-02b9dc5a-98de-4aa6-8024-6eb911acf27d.png">
