### ISSUE TITLE
Feature request: filter errors and warnings

### ISSUE THREAD

**Issue by troydai** [OmniSharp/omnisharp-vscode#557]
Today, all the errors and warnings generated are all shown up in the errors panel. However, there are situations in which although many of them are valid users will want them to be ignored. 

For example, errors like `XML comments missing` shows up consistently makes the editing experience bad.

**Comment by filipw** [comment]
fixed by https://github.com/OmniSharp/omnisharp-roslyn/pull/734?
or is this intended to be something else?

**Comment by DustinCampbell** [comment]
Yeah, I think this is fixed. At least @troydai's comment about XML comments is fixed. Of course, it was @troydai's bug in the first place, since he didn't pass the NoWarn values down into the C# completion. 😃
