### ISSUE TITLE
unable to start omnisharp

### ISSUE THREAD

**Issue by rajwcg** [OmniSharp/omnisharp-vscode#558]
[INFO] Starting OmniSharp at 'd:\StudyMaterial\VSCODE\DemoApp2'...
[ERROR] Error: spawn cmd ENOENT

I am using window7 64 bit. with latest VSCODE

Omnisharp log

[INFO] Starting OmniSharp at 'd:\StudyMaterial\VSCODE\DemoApp2'...
[INFO] Installing to C:\Users\rajbahadur.singh\.vscode\extensions\ms-vscode.csharp-1.2.2\.omnisharp
[INFO] Attempting to download omnisharp-1.9-beta11-win-x64-net451.zip...
[INFO] Downloading to C:\Users\RAJBAH~1.SIN\AppData\Local\Temp\tmp-10828cg3fW5H36pDo.tmp...
[INFO] Download complete!
[INFO] Decompressing...
[INFO] Done! 159 files unpacked.
[ERROR] Error: spawn cmd ENOENT

**Comment by DustinCampbell** [comment]
Hi, could you try the latest beta that we just release, [v1.3.0-beta1](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.3.0-beta1) and see if that works better for you?

**Comment by rajwcg** [comment]
Hi, This has been started working.

**Comment by DustinCampbell** [comment]
Hi, glad to hear it!

**Comment by wiseman17** [comment]
This answer https://github.com/OmniSharp/omnisharp-vscode/issues/32#issuecomment-241223579 helped me with similar issue.
