### ISSUE TITLE
[NETSDKE2E] With NET 8.0 preview2, Debugging is failed with "Unable to attach to CoreCLR. Unknown Error: 0x80131c3c" on Ubuntu20.04

### ISSUE THREAD

**Issue by NicoleWang001** [OmniSharp/omnisharp-vscode#5592]
## Environment data
`dotnet --info` output:

.NET SDK:
 Version:   8.0.100-preview.2.23121.17
 Commit:    1b05e59daa

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.100-preview.2.23121.17/

Host:
  Version:      8.0.0-preview.2.23116.1
  Architecture: x64
  Commit:       f2f734a7e4

.NET SDKs installed:
  8.0.100-preview.2.23121.17 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-preview.2.23116.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-preview.2.23116.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

VS Code version:

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:35:30.018Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 5.15.0-1033-azure
Sandboxed: No

C# Extension version:
v1.25.4
## Steps to reproduce

1. Install .NET 8.0 Preview2 SDK on Ubuntu20.04
2. Create a new console app
3. cd into new created application folder and launch code 
4. Run debugger pressing F5 or from Run menu

## Expected  behavior
Can debug c# code

## Actual behavior
Get error "Unable to attach to CoreCLR. Unknown Error: 0x80131c3c"
![image](https://user-images.githubusercontent.com/1578239/220577363-42c3ecf2-d94e-4dab-9459-64fa003ea281.png)

## Additional context
1. This issue is not repro on Mac OS
2. This issue is not repro with .NET 7.0 or .NET 8.0 Preview1

**Comment by v-xiaofchen** [comment]
Not repro on .NET SDK 8.0.100-preview.2.23127.13, we will keep tracking.
![vscode2](https://user-images.githubusercontent.com/99376012/221778526-ac6144ca-d163-438f-8550-e39750afbf5b.png)

**Comment by v-xiaofchen** [comment]
Not repro on .NET SDK 8.0.100-preview.2.23151.8 (runtime-8.0.100-preview.2.23128.3)，so closed it.
![preview2 1](https://user-images.githubusercontent.com/99376012/222667414-6c93e6a7-cb5b-4d3b-8f3e-d4669808e605.png)
