### ISSUE TITLE
I can't use intellisense on Unity.

### ISSUE THREAD

**Issue by hyesun03** [OmniSharp/omnisharp-vscode#561]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version: 1.3
C# Extension version: 1.2.2
.
.
below is my Omnisharp Log.
I already installed everything to be required.
Error about .net framework version and I cannot use intellisense.
.
.
[INFO] Starting OmniSharp at '/Users/hsun/UnityProjects/First Game/First Game.sln'...
[INFO] Installing to /Users/hsun/.vscode/extensions/ms-vscode.csharp-1.2.2/.omnisharp
[INFO] Attempting to download omnisharp-1.9-beta11-osx-x64-netcoreapp1.0.tar.gz...
[INFO] Downloading to /var/folders/b4/bdngv6ys6fx7l54k36fywg600000gn/T/tmp-1039qFnwwpkStpxd.tmp...
[INFO] Download complete!
[INFO] Decompressing...
[INFO] Done! 321 files unpacked.
[INFO] Started OmniSharp from '/Users/hsun/.vscode/extensions/ms-vscode.csharp-1.2.2/.omnisharp/OmniSharp' with process id 1058...
OmniSharp: -s /Users/hsun/UnityProjects/First Game/First Game.sln --hostPID 1039 dnx:enablePackageRestore=false --stdio
[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location '/Users/hsun/UnityProjects/First Game' on host 1039.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /Users/hsun/UnityProjects/First Game
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: True
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp#MSBuild] Detecting projects in '/Users/hsun/UnityProjects/First Game/First Game.sln'.
[INFORMATION:OmniSharp#MSBuild] Loading project from '/Users/hsun/UnityProjects/First Game/Assembly-CSharp.csproj'.
[INFORMATION:OmniSharp#ProjectFileInfo] Using toolset 15.0 for /Users/hsun/UnityProjects/First Game/Assembly-CSharp.csproj
[ERROR:OmniSharp#ProjectFileInfo] The reference assemblies for framework ".NETFramework,Version=v2.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[WARNING:OmniSharp#MSBuild] Failed to process project file '/Users/hsun/UnityProjects/First Game/Assembly-CSharp.csproj'.
/Users/hsun/UnityProjects/First Game/Assembly-CSharp.csproj

[INFORMATION:OmniSharp#MSBuild] Loading project from '/Users/hsun/UnityProjects/First Game/Assembly-CSharp-Editor.csproj'.
[INFORMATION:OmniSharp#ProjectFileInfo] Using toolset 15.0 for /Users/hsun/UnityProjects/First Game/Assembly-CSharp-Editor.csproj
[ERROR:OmniSharp#ProjectFileInfo] The reference assemblies for framework ".NETFramework,Version=v2.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[WARNING:OmniSharp#MSBuild] Failed to process project file '/Users/hsun/UnityProjects/First Game/Assembly-CSharp-Editor.csproj'.
/Users/hsun/UnityProjects/First Game/Assembly-CSharp-Editor.csproj

[INFORMATION:OmniSharp.Startup] Configuration finished.

-----------------------

**Comment by DustinCampbell** [comment]
Thanks for reporting this issue. Please note this information on the our repo's home page about the current state of Unity support:

**Support for .csproj projects is partially functional on OS X and Linux.** This will impact anyone doing .csproj development on OS X or Linux (e.g. Unity, Xamarin, etc.). We are working to address this in the near future. However, for now, you can use the [Legacy C# Support extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.omnisharp).

**Comment by DustinCampbell** [comment]
Take Two! I've just released [v.1.3.0-beta1](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.3.0-beta1) which brings support for two OmniSharp servers: a .NET Core one for project.json projects, and a Mono/Desktop version for .csproj/.sln projects. Please try this out and let me know if it fixes Unity development for you.

**Comment by DustinCampbell** [comment]
Hi, I've put up another release, [v1.3.2-beta2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.3.0-beta2), which should improve support even more. If you have a chance, please let me know if this new extension works for you.

**Comment by DustinCampbell** [comment]
I haven't heard back from you yet. We're going to update the extension soon with the changes in the latest beta. Once released, let me know if it still doesn't work for you.

**Comment by hyesun03** [comment]
ah...really sorry about late feedback. I had resolve this problem throught editting ~/.bash_profile.

I added it on ~/.bash_profile.
`export PATH=/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/bin`

My macbook got some problems.. so I'll contact to you next week. 
I sincerely sorry to late reply.
