### ISSUE TITLE
"Build task" forgets there is a tasks.json file

### ISSUE THREAD

**Issue by jtsom** [OmniSharp/omnisharp-vscode#5612]
## Issue Description ##
I don't know what triggers this, but the Control-Shift-B "Build" task seems to forget that there is a tasks.json file, and fails to build the project. It started happening within the last version  or two. Only quitting and relaunching, or "Developer Reload Window" makes things work again.

## Steps to Reproduce ##
Unsure how to trigger, but when it happens, Ctrl-Shift-B shows a message that it can't find the build tasks, even though there clearly is a tasks.json file (and it build not long before)

![image](https://user-images.githubusercontent.com/13488/223756674-b9627f20-86e2-4a87-abca-00e77ef2f1f8.png)

## Expected Behavior ##
Build works.

## Actual Behavior ##
![image](https://user-images.githubusercontent.com/13488/223756735-7fad1ca0-e2d5-445d-8a1e-8fd161d48dc5.png)

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.77.0-insider
**C# Extension**: 1.25.4

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.200
 Commit:    534117727b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.200\

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.114 [C:\Program Files\dotnet\sdk]
  6.0.309 [C:\Program Files\dotnet\sdk]
  6.0.406 [C:\Program Files\dotnet\sdk]
  7.0.103 [C:\Program Files\dotnet\sdk]
  7.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.11.3|
|csharp|ms-dotnettools|1.25.4|
|csharpextensions|kreativ-software|1.7.3|
|ecdc|mitchdenny|1.8.0|
|git-graph|mhutchie|1.30.0|
|hexeditor|ms-vscode|1.9.11|
|hl7tools|RobHolme|2.0.1|
|js-debug-nightly|ms-vscode|2023.3.617|
|jwt-debugger|yokawasa|0.4.2|
|material-icon-theme|PKief|4.24.0|
|msbuild-project-tools|tintoy|0.4.9|
|night-owl|sdras|2.0.1|
|quicktype|quicktype|12.0.46|
|sync-scroll|dqisme|1.3.1|
|TabOut|albert|0.2.2|
|vs-code-xml-format|fabianlauer|0.1.5|
|vscode-azureappservice|ms-azuretools|0.24.7|
|vscode-azurefunctions|ms-azuretools|1.10.3|
|vscode-azureresourcegroups|ms-azuretools|0.6.1|
|vscode-azurestorage|ms-azuretools|0.15.1|
|vscode-base64|adamhartford|0.1.0|
|vscode-cosmosdb|ms-azuretools|0.19.3|
|vscode-thunder-client|rangav|2.5.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|;

</details>

**Comment by JoeRobich** [comment]
This would be an issue with VS Code itself, not the C# extension. You could report it via the built in feedback tooling.
