### ISSUE TITLE
Archlinux OmniSharp.exe "cannot execute binary file"

### ISSUE THREAD

**Issue by vindicatorr** [OmniSharp/omnisharp-vscode#563]
## Environment data
`dotnet --info` output: 1.0.0-preview2-003121
VS Code version: 1.3.1
C# Extension version: 1.2.2

## Steps to reproduce
5. Continuing from https://github.com/Microsoft/vscode/issues/9192
    ```
[INFO] Starting OmniSharp at '/home/username/Documents/Visual Studio Code/test'...
[ERROR] Could not locate an OmniSharp server that supports your Linux distribution.

OmniSharp provides a richer C# editing experience, with features like IntelliSense and Find All References.
It is recommend that you download the version of OmniSharp that runs on Mono using the following steps:
    1. If it's not already installed, download and install Mono (http://www.mono-project.com)
    2. Download and untar https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.9-alpha13/omnisharp-linux-mono.tar.gz
    3. In Visual Studio Code, select Preferences->User Settings to open settings.json.
    4. In settings.json, add a new setting: "csharp.omnisharp": "/path/to/omnisharp/OmniSharp.exe"
    5. Restart Visual Studio Code.
[ERROR] Error: ENOENT: no such file or directory, lstat '/home/username/.vscode/extensions/ms-vscode.csharp-1.2.2/.omnisharp'
    ```
6. wget https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.9-alpha13/omnisharp-linux-mono.tar.gz
7. mkdir /home/username/.vscode/extensions/ms-vscode.csharp-1.2.2/.omnisharp
8. tar -xa -C /home/username/.vscode/extensions/ms-vscode.csharp-1.2.2/.omnisharp -f omnisharp-linux-mono.tar.gz
9. Preferences->"User Settings" = "csharp.omnisharp": "/home/username/.vscode/extensions/ms-vscode.csharp-1.2.2/.omnisharp/OmniSharp.exe"
10. Restart VSCode

## Expected  behavior
Whatever gets omnisharp to execute.

## Actual behavior
```
INFO] Starting OmniSharp at '/home/username/Documents/Visual Studio Code/test'...
[INFO] Started OmniSharp from '/home/username/.vscode/extensions/ms-vscode.csharp-1.2.2/.omnisharp/OmniSharp.exe' with process id 4321...
/home/username/.vscode/extensions/ms-vscode.csharp-1.2.2/.omnisharp/OmniSharp.exe: /home/username/.vscode/extensions/ms-vscode.csharp-1.2.2/.omnisharp/OmniSharp.exe: cannot execute binary file
[ERROR] Error: Failed to start OmniSharp
```
("$ code --verbose" didn't offer any more details)

Trying something different, I manually ran "$ mono /home/username/.vscode/extensions/ms-vscode.csharp-1.2.2/.omnisharp/OmniSharp.exe" from the "test" project directory and got:
```
OmniSharp: 
info: OmniSharp.Startup[0]
      Omnisharp server running on port '2000' at location '/home/username/Documents/Visual Studio Code/test' on host -1.
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Initializing in /home/username/Documents/Visual Studio Code/test
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Auto package restore: True
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Update workspace context
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Update project /home/username/Documents/Visual Studio Code/test
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Add project /home/username/Documents/Visual Studio Code/test/project.json => 6af02a93-e4da-4138-b91c-3d81bb41375a
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Resolving projects references
info: OmniSharp.DotNet.DotNetProjectSystem[0]
        Processing [ProjectState] test/.NETCoreApp,Version=v1.0
info: OmniSharp.DotNet.Tools.PackagesRestoreTool[0]
      Begin restoring project /home/username/Documents/Visual Studio Code/test
info: OmniSharp.DotNet.DotNetProjectSystem[0]
          Added 1 and removed 0 documents.
info: OmniSharp.MSBuild.MSBuildProjectSystem[0]
      No solution files found in '/home/username/Documents/Visual Studio Code/test'
info: OmniSharp.ScriptCs.ScriptCsProjectSystem[0]
      Detecting CSX files in '/home/username/Documents/Visual Studio Code/test'.
info: OmniSharp.ScriptCs.ScriptCsProjectSystem[0]
      Could not find any CSX files
info: OmniSharp.Startup[0]
      Configuration finished.
info: OmniSharp.DotNet.Tools.PackagesRestoreTool[0]
      Finish restoring project /home/username/Documents/Visual Studio Code/test. Exit code 0
```
... and no omnisharp error in VSCode.

**Comment by cra0zy** [comment]
I also use Arch Linux, and OmniSharp initialized correctly for me after downloading and extracting it.

**Comment by DustinCampbell** [comment]
Sorry for taking so long to get back to you. Try the following steps:

1. Download and install the latest beta version of the C# extension [v1.3.0-beta2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.3.0-beta2). (Note: you can install it by opening the VSIX in VS Code with File->Open File).
2. Download and untar the latest OmniSharp for Mono from https://github.com/OmniSharp/omnisharp-roslyn/releases.
3. In Visual Studio Code, select Preferences->User Settings to open settings.json.
4. In settings.json, add a new setting: `"csharp.omnisharp": "/path/to/omnisharp/OmniSharp.exe"`
5. In settings.json, add another setting: `"csharp.omnisharpUsesMono": true`.
6. Restart Visual Studio Code.

**Comment by DustinCampbell** [comment]
Also, note that I've filed #593 to track improving the OmniSharp acquisition experience on any linux distros that we don't *officially* support.

**Comment by vanthome** [comment]
@DustinCampbell many thanks, your instructions worked for me under Gentoo Linux as well.

**Comment by DustinCampbell** [comment]
I'm going to go ahead and close this issue. We'll use #593 to track making it easier to acquire the mono-flavor of OmniSharp for linux distros that don't have specific .NET Core support.
