### ISSUE TITLE
debugging problem

### ISSUE THREAD

**Issue by mansi725** [OmniSharp/omnisharp-vscode#5632]
Type: <b>Performance Issue</b>

.scss and .css debugger extension not executing

Extension version: 1.25.4
VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|5.89GB (0.87GB free)|
|Process Argv|C:\\Users\\DELL\\Desktop\\xamp\\htdocs\\gym\\admin-login.php --crash-reporter-id c4d309a3-008a-4ee4-8424-546c6f483e2f|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   118	  8048	code main
    1	    87	  2916	   issue-reporter
    0	   121	  5560	   shared-process
    0	    82	 12696	     fileWatcher
    0	    73	 20988	     ptyHost
    0	   180	  8076	   window (billing.php - gym - Visual Studio Code)
    0	    40	 13208	   utility-network-service
    0	    31	 14516	   crashpad-handler
    0	   110	 16824	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (billing.php - gym - Visual Studio Code)
|    Folder (gym): 12 files
|      File types: php(6) jpg(3) png(1) jpeg(1)
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30677849
funwalk2:30682974
pythonms35cf:30686773

```

</details>

**Comment by WardenGnaw** [comment]
omnisharp-vscode debugs .NET Code which typically end in `.cs`

.scss and .css are style sheets and should be used with one of the extensions listed in the docs.
