### ISSUE TITLE
Windows ARM64: The .NET debugger can only debug ARM64 processes.

### ISSUE THREAD

**Issue by hajekj** [OmniSharp/omnisharp-vscode#5639]
## Issue Description ##
When attempting to debug Azure Function running on my ARM64 machine, the following error occurs: `The .NET debugger can only debug ARM64 processes.`

## Steps to Reproduce ##
1. Get a Windows ARM64 device and install Windows 11 on it (I believe this is reproducible on Windows 10 as well)
1. Install .NET 6.0 SDK for Windows ARM64
1. Install VS Code with Azure Functions Extensions
1. Create a .NET in-process Azure Function and launch it via F5
1. When the it starts, the attach doesn't happen and error `The .NET debugger can only debug ARM64 processes.` occurs.

## Expected Behavior ##
I expect the debugging experience to work the same way on ARM64 as on a regular x86_64 machine.

## Logs ##
```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Unable to start debugging. Failed to attach to process: The .NET debugger can only debug ARM64 processes.
```

### OmniSharp log ###
<details>
Starting OmniSharp server at 3/25/2023, 6:00:47 PM
    Target: c:\Users\hajek\Scratch\functions-arm64

OmniSharp server started with .NET 7.0.100
.
    Path: c:\Users\hajek\.vscode\extensions\ms-dotnettools.csharp-1.25.4-win32-arm64\.omnisharp\1.39.4-net6.0\OmniSharp.dll
    PID: 3900

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 10.0.22624.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: .NET Core SDK 7.0.100 17.4.0 - "C:\Program Files\dotnet\sdk\7.0.100\"
            2: .NET Core SDK 6.0.402 17.3.2 - "C:\Program Files\dotnet\sdk\6.0.402\"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 7.0.100 17.4.0 - "C:\Program Files\dotnet\sdk\7.0.100\"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\hajek\Scratch\functions-arm64'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\hajek\Scratch\functions-arm64'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\hajek\Scratch\functions-arm64\functions-arm64.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\hajek\Scratch\functions-arm64'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\hajek\Scratch\functions-arm64' on host 9748.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\hajek\Scratch\functions-arm64\functions-arm64.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\hajek\Scratch\functions-arm64\functions-arm64.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\hajek\Scratch\functions-arm64\functions-arm64.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: functions-arm64
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\hajek\Scratch\functions-arm64\functions-arm64.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\hajek\Scratch\functions-arm64\functions-arm64.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\hajek\Scratch\functions-arm64\functions-arm64.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\hajek\Scratch\functions-arm64\functions-arm64.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\hajek\Scratch\functions-arm64\functions-arm64.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: functions-arm64
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: C:\Users\hajek\.nuget\packages\microsoft.azure.functions.analyzers\1.0.0\analyzers\dotnet\cs\Microsoft.Azure.Functions.Analyzers.dll
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: C:\Users\hajek\.nuget\packages\microsoft.netcore.app.ref\6.0.11\analyzers\dotnet\cs\System.Text.Json.SourceGeneration.dll
Received response for /quickinfo but could not find request.
[warn]: OmniSharp.MSBuild.ProjectManager
        The change was reported in c:\Users\hajek\Scratch\functions-arm64\obj\Debug\net6.0\functions-arm64.GeneratedMSBuildEditorConfig.editorconfig but it doesn't exist on disk.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\hajek\Scratch\functions-arm64\functions-arm64.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\hajek\Scratch\functions-arm64\functions-arm64.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\hajek\Scratch\functions-arm64\functions-arm64.csproj'.
[warn]: OmniSharp.MSBuild.ProjectManager
        The change was reported in c:\Users\hajek\Scratch\functions-arm64\obj\Debug\net6.0\functions-arm64.GeneratedMSBuildEditorConfig.editorconfig but it doesn't exist on disk.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\hajek\Scratch\functions-arm64\functions-arm64.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\hajek\Scratch\functions-arm64\functions-arm64.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\hajek\Scratch\functions-arm64\functions-arm64.csproj'.
</details>

### C# log ###
<details>N/A</details>

## Environment information ##

**VSCode version**: 1.76.2
**C# Extension**: 1.25.4

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22624
 OS Platform: Windows
 RID:         win10-arm64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: arm64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.402 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|aadb2c|AzureADB2CTools|1.3.5|
|azure-account|ms-vscode|0.11.3|
|azure-pipelines|ms-azure-devops|1.208.0|
|azure-repos|ms-vscode|0.28.0|
|azurerm-vscode-tools|msazurermtools|0.15.10|
|azurite|Azurite|3.22.0|
|codespaces|GitHub|1.14.1|
|csharp|ms-dotnettools|1.25.4|
|dotnet-interactive-vscode|ms-dotnettools|1.0.4172010|
|gitlens|eamodio|13.4.0|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.7|
|jupyter|ms-toolsai|2023.2.1200692131|
|jupyter-keymap|ms-toolsai|1.1.0|
|jupyter-renderers|ms-toolsai|1.0.15|
|npm-intellisense|christian-kohler|1.4.4|
|powerplatform-vscode|microsoft-IsvExpTools|1.1.20|
|powershell|ms-vscode|2023.2.1|
|remote-containers|ms-vscode-remote|0.282.0|
|remote-explorer|ms-vscode|0.3.2023032309|
|remote-repositories|ms-vscode|0.30.0|
|remote-server|ms-vscode|1.1.2023032309|
|remote-ssh|ms-vscode-remote|0.98.0|
|remote-ssh-edit|ms-vscode-remote|0.84.0|
|remote-wsl|ms-vscode-remote|0.76.1|
|remotehub|GitHub|0.52.0|
|rest-client|humao|0.25.1|
|user-secrets|adrianwilczynski|2.0.1|
|vscode-apimanagement|ms-azuretools|1.0.5|
|vscode-azureappservice|ms-azuretools|0.24.8|
|vscode-azurefunctions|ms-azuretools|1.10.4|
|vscode-azurelogicapps|ms-azuretools|1.0.49|
|vscode-azureresourcegroups|ms-azuretools|0.6.2|
|vscode-azurestaticwebapps|ms-azuretools|0.11.4|
|vscode-azurestorage|ms-azuretools|0.15.1|
|vscode-cosmosdb|ms-azuretools|0.19.3|
|vscode-docker|ms-azuretools|1.24.0|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|
|vscode-eslint|dbaeumer|2.4.0|
|vscode-icons|vscode-icons-team|12.2.0|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.8|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|
|vscode-logicapps|ms-azuretools|1.2.2|
|vscode-pull-request-github|GitHub|0.60.0|
|vscode-remote-extensionpack|ms-vscode-remote|0.24.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|
|vsliveshare|ms-vsliveshare|1.0.5834|;

</details>

**Comment by gregg-miskelly** [comment]
This is tracked with https://github.com/OmniSharp/omnisharp-vscode/issues/5004
