### ISSUE TITLE
VScode autocompletion not recognize partial class

### ISSUE THREAD

**Issue by wind198** [OmniSharp/omnisharp-vscode#5640]
1. Create new console app by `dotnet new console --name testApp`
2. Create Program.Helpers.cs file
3. Defind partial class with 1 method
`partial class Program
{
    static void SayHello()
    {
Console.WriteLine("Hello");
    }
}
`
5. Go to Program.cs,  try to use `SayHello` method, autocompletion not work
## Expected  behavior
SayHello must show up  in the suggestion list

## Actual behavior
SayHello not show up

**Comment by wind198** [comment]
Actually if I type `Program.SayHello`, it work but not for `SayHello` only

**Comment by stonstad** [comment]
I'm surprised that VS Code does not support partial classes.  It appears to have no awareness of other class members.

**Comment by JoeRobich** [comment]
@stonstad this issue has been closed. If you are experiencing a regression here, please open a new issue with a repro and logs so that we can investigate.

**Comment by stonstad** [comment]
Thanks, @JoeRobich.  I believe the issue is that I was not being specific in the command bar.  If I type # for a symbol search, it does work as expected. Thanks for replying and encouraging me to research further.
