### ISSUE TITLE
No `omnisharp.enableDecompilationSupport` option?!

### ISSUE THREAD

**Issue by aradalvand** [OmniSharp/omnisharp-vscode#5645]
I wanted to enable decompilation support, but the option doesn't actually exist:

![image](https://user-images.githubusercontent.com/26527405/229841566-eeea826e-a25c-4194-a534-babb4df4a0cc.png)

I also tried running the "CSharp: Show the decompiler terms agreement" command, but nothing happens when I run it:

![image](https://user-images.githubusercontent.com/26527405/229841645-0edf4b27-5d34-41f2-80f9-0b0fd8d60763.png)

I'm on Ubuntu 22.04, running .NET 7, in case that's relevant.

**Comment by filipw** [comment]
The option is still there, I am not sure why it would not show up in autocomplete. https://github.com/OmniSharp/omnisharp-vscode/blob/master/package.json#L1138-L1143

Try switching to the UI editor and check there, it should be there:

<img width="1164" alt="Bildschirm­foto 2023-04-06 um 09 33 51" src="https://user-images.githubusercontent.com/1710369/230306698-6e87eb44-c4ec-4db3-a3bc-64a41f6d345a.png">

**Comment by filipw** [comment]
Ah I see why. It's a `machine` setting. So you have to make sure you toggle between the workspace and user settings when opening settings. It will not show up in user settings and it will show up in workspace settings - in both UI and JSON mode.

<img width="676" alt="Bildschirm­foto 2023-04-06 um 09 36 13" src="https://user-images.githubusercontent.com/1710369/230307478-6428490f-1e21-48fa-a4a8-dd7ba0e5b79c.png">
