### ISSUE TITLE
[NETSDKE2E] With .NET 8.0 Preview4, debugging does not work normally on Mac X64

### ISSUE THREAD

**Issue by v-xiaofchen** [OmniSharp/omnisharp-vscode#5648]
**Environment:**
VSCode: 1.77.1
C# extension:1.25.5
.NET 8.0.100-preview.4.23205.4 (runtime- 8.0.0-preview.4.23181.2)

**Repro steps:**
1.Create a new project via CLI.
2.Open the project in VSCode and hit F5.

**Expected behavior:** 
Debugging works fine and see "Hello,World!"
![MicrosoftTeams-image](https://user-images.githubusercontent.com/99376012/230321511-e94c25cd-7295-4975-9edb-68bf2accf0c7.png)

**Actual behavior:** 
Debugging could not be finished normally, could not see "Hello, World!"
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/99376012/230323740-cb2f0716-3284-4868-b500-b114a971013e.png)

**Note:**
1. This issue is only repro on Mac X64, not repro on Mac M1 and Windows.
2. This issue is not repro with .NET 8 Preview3, Preview2

dotnet --info:

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/99376012/230323883-1e03cfc5-a240-4afa-9d0f-c906ff60c6c5.png)

-->**The OmniSharp Log:**
[OmniSharpLog.txt](https://github.com/OmniSharp/omnisharp-vscode/files/11168595/OmniSharpLog.txt)

**Comment by gregg-miskelly** [comment]
@v-xiaofchen Can you reopen this issue in the dotnet/runtime repo. I don't have write access to do so.

**Comment by v-xiaofchen** [comment]
@gregg-miskelly I have reopened this issue in the dotnet/runtime repo,you can find it from https://github.com/dotnet/runtime/issues/84466
