### ISSUE TITLE
Intellisense, Format document are not working.

### ISSUE THREAD

**Issue by simon-dibble** [OmniSharp/omnisharp-vscode#5661]
Hi there

All of the intellisense and error checking in my VSCode c# (.NET 6) project seems to have stopped working.  My context menu looks like this:
![image](https://user-images.githubusercontent.com/62878285/234171551-0c09b340-9343-4638-94da-b9c467462d99.png)

  At the moment I only get error checking when I build the project.

I am using version 1.25.4 of the extension.  I have tried changing to earlier versions which made no difference.  The Use Modern Net setting is set to true and the dotnet cli works from the projects folder.

Please let me know if you can help and what other information I can provide.

**Comment by JoeRobich** [comment]
Can you please reopen your project folder in VS Code and share the complete OmniSharp Log from the Output pane?

**Comment by simon-dibble** [comment]
Hi Joe, thanks for coming back to me.  After trying uninstalling the add-in, vs code etc.  I ended up creating a new development user and started with a fresh user profile (windows).  This solved the problem so unfortunately I don't have any more details to share.
