### ISSUE TITLE
Error E5248 in Neovim 0.9

### ISSUE THREAD

**Issue by fraidev** [OmniSharp/omnisharp-vscode#5667]
Similar to an issue on rescript-vscode project. https://github.com/rescript-lang/rescript-vscode/issues/758.

**Comment by JoeRobich** [comment]
This extension is for Visual Studio Code. We do not currently support installing it in neovim. There is a related omnisharp-vim project which may be relevant, https://github.com/OmniSharp/Omnisharp-vim.

**Comment by fraidev** [comment]
> Similar to an issue on rescript-vscode project. [rescript-lang/rescript-vscode#758](https://github.com/rescript-lang/rescript-vscode/issues/758).

You are right, I am using Omnisharp-vim by [Mason](https://github.com/mason-org/mason-registry/blob/main/packages/omnisharp-mono/package.yaml)

Thanks!
