### ISSUE TITLE
Nothing happens with 'Start Debugging'

### ISSUE THREAD

**Issue by sebzap** [OmniSharp/omnisharp-vscode#5678]
## Issue Description ##
Created new Azure Function according to this guide: https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-csharp?tabs=in-process

Running `func start` runs the application fine.
However 'Start Debugging' in VS Code does nothing:
![image](https://github.com/OmniSharp/omnisharp-vscode/assets/12527892/57de9134-e70c-4e9a-9c62-f2d9104ef62e)
(just a blue bar running beneath, application is not starting, no errors/warnings anywhere)

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to .NET Functions",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:azureFunctions.pickProcess}"
        }
    ]
}
``` 

tasks.json
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "clean (functions)",
			"command": "dotnet",
			"args": [
				"clean",
				"/property:GenerateFullPaths=true",
				"/consoleloggerparameters:NoSummary"
			],
			"type": "process",
			"problemMatcher": "$msCompile"
		},
		{
			"label": "build (functions)",
			"command": "dotnet",
			"args": [
				"build",
				"/property:GenerateFullPaths=true",
				"/consoleloggerparameters:NoSummary"
			],
			"type": "process",
			"dependsOn": "clean (functions)",
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"problemMatcher": "$msCompile"
		},
		{
			"label": "clean release (functions)",
			"command": "dotnet",
			"args": [
				"clean",
				"--configuration",
				"Release",
				"/property:GenerateFullPaths=true",
				"/consoleloggerparameters:NoSummary"
			],
			"type": "process",
			"problemMatcher": "$msCompile"
		},
		{
			"label": "publish (functions)",
			"command": "dotnet",
			"args": [
				"publish",
				"--configuration",
				"Release",
				"/property:GenerateFullPaths=true",
				"/consoleloggerparameters:NoSummary"
			],
			"type": "process",
			"dependsOn": "clean release (functions)",
			"problemMatcher": "$msCompile"
		},
		{
			"type": "func",
			"dependsOn": "build (functions)",
			"options": {
				"cwd": "${workspaceFolder}/bin/Debug/net7.0"
			},
			"command": "host start",
			"isBackground": true,
			"problemMatcher": "$func-dotnet-watch"
		}
	]
}
```

## Steps to Reproduce ##
1. Create new C# application
2. run Debug

## Expected Behavior ##
Debugging should start application

## Actual Behavior ##
Nothing happens

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.78.2
**C# Extension**: 1.25.7

<details><summary>Mono Information</summary>
        OmniSharp using mono: 6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.203/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  6.0.408 [/usr/local/share/dotnet/sdk]
  7.0.203 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|autodocstring|njpwerner|0.6.1|
|azure-account|ms-vscode|0.11.4|
|better-phpunit|calebporzio|1.5.3|
|clipboard-history|Anjali|1.0.7|
|code-spell-checker|streetsidesoftware|2.20.4|
|codestream|CodeStream|14.19.0|
|csharp|ms-dotnettools|1.25.7|
|dotenv|mikestead|1.0.1|
|elastic|ria|0.13.3|
|gitlens|eamodio|13.6.0|
|isort|ms-python|2022.8.0|
|jupyter|ms-toolsai|2023.4.1011241018|
|jupyter-keymap|ms-toolsai|1.1.0|
|jupyter-renderers|ms-toolsai|1.0.15|
|laravel-blade|cjhowe7|1.1.2|
|live-server|ms-vscode|0.4.8|
|php-cs-fixer|junstyle|0.3.9|
|prettier-vscode|esbenp|9.12.0|
|python|ms-python|2023.8.0|
|remote-containers|ms-vscode-remote|0.292.0|
|vetur|octref|0.37.3|
|vscode-azurefunctions|ms-azuretools|1.10.5|
|vscode-azureresourcegroups|ms-azuretools|0.7.1|
|vscode-coverage-gutters|ryanluker|2.10.4|
|vscode-docker|ms-azuretools|1.25.0|
|vscode-eslint|dbaeumer|2.4.0|
|vscode-intelephense-client|bmewburn|1.9.5|
|vscode-jest-runner|firsttris|0.4.60|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.8|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|
|vscode-pylance|ms-python|2023.5.20|
|vue-autoimport|ishiyama|1.0.5|;

</details>

**Comment by gregg-miskelly** [comment]
Can you [enable logging](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging#quick-method) and see if anything is printed to the debug console? If not, this sounds like something that needs to go to the vscode-azurefunctions extension.

**Comment by sebzap** [comment]
Created issue on vscode-azurefunctions. Debug works for C# console applications.
