### ISSUE TITLE
Intellisense breaks completely when using System.Xml.XmlWriter

### ISSUE THREAD

**Issue by atticae** [OmniSharp/omnisharp-vscode#568]
## Environment data
`dotnet --info` output:
> .NET Command Line Tools (1.0.0-preview2-003121)
> 
> Product Information:
>  Version:            1.0.0-preview2-003121
>  Commit SHA-1 hash:  1e9d529bc5
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  6.1.7601
>  OS Platform: Windows
>  RID:         win7-x64

VS Code version: 1.3.1
C# Extension version: 1.2.2

## Steps to reproduce
1. Create a new project with `dotnet new`.
1. Open it in VS Code.
1. Add the following lines to Main() in Program.cs:

 ```
var sw = new System.IO.StringWriter();
var writer = System.Xml.XmlWriter.Create(sw);
```

## Expected  behavior
Intellisense should provide autocompletion for methods of `writer`.

## Actual behavior
Intellisense breaks completely and only shows "loading" ("wird geladen" in German).

![xmlwriter](https://cloud.githubusercontent.com/assets/7560166/16836315/461efdc2-49bd-11e6-9ccd-88611ebcecb3.gif)

After that, Intellisense won't even work for simple things like Console.WriteLine anymore. I have to reopen VS Code completely to get it working again, but the error can be reproduced indefinitely with the code above.

OmniSharp Log shows instances of:

> [ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

**Comment by DustinCampbell** [comment]
Hi, could you try the latest beta release, [v1.3.0-beta](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.3.0-beta1)? I just tried that version and couldn't reproduce this issue.

**Comment by atticae** [comment]
Installed v1.3.0-beta1, but unfortunately the problem is still there.

**Comment by DustinCampbell** [comment]
> EDIT: Nevermind, I still had an instance of VS Code open. Problem seems fixed in the beta!

That's fantastic news!
