### ISSUE TITLE
[ERROR] A .NET 6 SDK for x86_64 was not found

### ISSUE THREAD

**Issue by lispercat** [OmniSharp/omnisharp-vscode#5680]
Keep seeing the message:
[ERROR] A .NET 6 SDK for x86_64 was not found.

I installed both x64 and x86 version of SDK from https://dotnet.microsoft.com/en-us/download/dotnet/6.0 but the error keeps popping up.

Why using 6.0 when the newer 7.0 is installed on the system?

## Environment information ##
**VSCode version**: 1.78.2
**C# Extension**: 1.25.7

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.203\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  6.0.408 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.25.7|
|fabric8-analytics|redhat|0.3.6|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.7|
|java|redhat|1.18.0|
|python|ms-python|2023.8.0|
|sailpoint-iiq-dev-accelerator|AndreiStebakov|1.0.46|
|vscode-java-debug|vscjava|0.50.0|
|vscode-java-dependency|vscjava|0.22.0|
|vscode-java-pack|vscjava|0.25.11|
|vscode-java-test|vscjava|0.38.2|
|vscode-maven|vscjava|0.41.0|
|vscode-neovim|asvetliakov|0.0.97|
|vscode-pull-request-github|GitHub|0.64.0|
|vscode-pylance|ms-python|2023.5.20|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|;

</details>

**Comment by JoeRobich** [comment]
@lispercat It is likely the 32-bit sdk location is earlier than the x64 in your environment PATH variable. You can update the PATH variable or uninstall the x86 sdk if you don't require it.

**Comment by lispercat** [comment]
I only installed the 32bit version after seeing the error.
Let me uninstall it

**Comment by lispercat** [comment]
Same error after I removed 32bit version

**Comment by JoeRobich** [comment]
Can you share your 'About Visual Studio Code' version and build information?

**Comment by lispercat** [comment]
Version: 1.78.2 (system setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

**Comment by JoeRobich** [comment]
I had hoped that would give us the version of VS Code that was installed. Is it possible that the 32-bit version installed on your machine?

Also, can you share the OmniSharp Log from the Output pane when you see this popup?

**Comment by lispercat** [comment]
VS Code is 64 bit (I gave all the rest information above)
Here is the log:
Starting OmniSharp server at 5/17/2023, 11:34:44 AM
    Target: c:\Dev\DataService\DataService.sln

OmniSharp server started with .NET 7.0.302
.
    Path:
c:\Users\user\.vscode\extensions\ms-dotnettools.csharp-1.25.7-win32-ia32\.omnisharp\1.39.6-net6.0\OmniSharp.dll
    PID: 30600

[STDERR] Unhandled exception.
[ERROR] A .NET 6 SDK for x86_64 was not found. Please install the latest
x86_64 SDK from https://dotnet.microsoft.com/en-us/download/dotnet/6.0.
[ERROR] Error: OmniSharp server load timed out. Use the
'omnisharp.projectLoadTimeout' setting to override the default delay (one
minute).

**Comment by JoeRobich** [comment]
@lispercat It is just odd that it installed the 32-bit version of the C# extension (see `-win32-ia32` in the path above). Try uninstalling and reinstalling the C# extension.

**Comment by lispercat** [comment]
When I just uninstall/install the extension it falls back on the 32bit path.
What I did was after I uninstalled, I
deleted c:\Users\user\.vscode\extensions\ms-dotnettools.csharp-1.25.7-win32-ia32
path manually from the disk.
After I installed it again, now it installed the right 64bit version.
Why do we need .net 6 when we already have .net 7 installed?
