### ISSUE TITLE
Quickfix using statements not working 

### ISSUE THREAD

**Issue by TCROC** [OmniSharp/omnisharp-vscode#5682]
Currently using mono version:

Mono JIT compiler version 6.12.0.182 (tarball Tue Jun 14 22:35:00 UTC 2022)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
        

Quick fix suggestions for ``using`` statements are no longer working.  Test with a Unity project

**Comment by JoeRobich** [comment]
@TCROC Can you re-open your project folder in VS Code share the complete OmniSharp Log from the Output pane?

**Comment by TCROC** [comment]
It looks like I may have needed to enable it in the settings:

![image](https://github.com/OmniSharp/omnisharp-vscode/assets/24307049/cfb7a9c9-8a49-4ab9-9286-1e9e3fb1e12e)

I restarted omnisharp and my project is loading back up now.  Gonna take a quick walk and come back and check it out.  Will let you know if that fixes it.

And if it does, I might suggest enabling this feature by default as it seems like a pretty common use case.

**Comment by TCROC** [comment]
Ok yep that was indeed the issue.  I could've sworn this used to just work out of the box.  Maybe I'm remembering things wrong.

Anyways, should I put in a separate issue to request enabling this by default?  Or just update this issue?

**Comment by JoeRobich** [comment]
@TCROC Glad you were able to work it out. Please open a feature request asking to make this enabled by default. Thanks!
