### ISSUE TITLE
Code hinting messed up, references missing since last C# extension update.

### ISSUE THREAD

**Issue by SomeTallGy** [OmniSharp/omnisharp-vscode#569]
## Environment data

`dotnet --info` output:
VS Code version: 1.3.1
C# Extension version: 1.2
## Steps to reproduce

I updated my C# extension
## Expected  behavior

Work as normal.
## Actual behavior

All my code doesn't seem to correctly code hint anymore -- references are not coming up and if I write jibberish, it doesn't mark it as an error.

**Comment by SomeTallGy** [comment]
Seems that this was related to me working with Unity -- i reverted back to the LEgacy C# Support extension and things seem to be back to normal.

**Comment by DustinCampbell** [comment]
@SommTallGy: What sort of project is this? Unity? Mono? .NET Core?

**Comment by armartinez** [comment]
I'm having the same issue with .NET Core Project, I get a lot of errors similar to this:

The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [netcoreapp1.0]

I'm running VS Code version: 1.3.1 with C# Extension version: 1.2.2

**Comment by eric-swann-q2** [comment]
Same issue, working with VSCode 1.3.1 on Ubuntu 16.04 and seems like omnisharp is only "half-working".  Not getting any intellisense, some code is highlighted property, some is not etc...  this is a new .Net core web api project (via yeoman).

**Comment by armartinez** [comment]
Ok this solved the issue for me https://github.com/OmniSharp/omnisharp-roslyn/issues/563

**Comment by eric-swann-q2** [comment]
In my case, user error.  I have a complex nested project and didn't realize I had to select the containing folder in VSCode as the project root (on the status bar).  That's surprisingly unintuitive for somebody new to the IDE.  I thought it would pick up the settings from the global.json on it's own.

**Comment by DustinCampbell** [comment]
From what I can tell, it sounds like this issue is dead. Let me know if there are further problems that I'm missing here.
