### ISSUE TITLE
Unable to increase scroll-back buffer size to troubleshoot test execution

### ISSUE THREAD

**Issue by asilverman** [OmniSharp/omnisharp-vscode#5692]
## Issue Description ##
* How I can increase the scrollback buffer for the .NET Test Log view in VSCode?
![Screenshot 2023-05-25 122430](https://github.com/OmniSharp/omnisharp-vscode/assets/9611108/480eb194-a92f-4c2e-8c88-589da2cf5df6)

The log is getting cutoff and I have no way of customizing the scroll back amounts 😢 

## Steps to Reproduce ##
1.  Download and clone a test that has a lot of output, for example: https://github.com/Azure/bicep/blob/asilverman/test-reporting/src/Bicep.LangServer.IntegrationTests/RenameSymbolTests.cs#L131
1. Run the test from the VSCode IDE using the 'Run Test' CodeLens feature
![image](https://github.com/OmniSharp/omnisharp-vscode/assets/9611108/05a1ec82-66e2-48c8-8827-904bc1fe86c7)

## Expected Behavior ##
- **I want to be able to configure the scrollback buffer size so that I can see all the output**

## Actual Behavior ##
- I cannot configure the scrollback buffer size so that I can see all the output
## Environment information ##

**VSCode version**: 1.79.0-insider
**C# Extension**: 1.25.7

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.400-preview.23272.53
 Commit:    22c8483b95

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.400-preview.23272.53\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.408 [C:\Program Files\dotnet\sdk]
  7.0.302 [C:\Program Files\dotnet\sdk]
  7.0.400-preview.23272.53 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|copilot-chat|GitHub|0.1.2023052205|
|copilot-nightly|GitHub|1.86.116|
|csharp|ms-dotnettools|1.25.7|
|gitlens|eamodio|2023.5.2405|
|remote-containers|ms-vscode-remote|0.293.0|
|remote-wsl|ms-vscode-remote|0.78.7|
|trxviewer|scabana|1.0.3|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|
|vscode-github-actions|github|0.25.7|
|vscode-pull-request-github|GitHub|0.65.2023051809|
|vscode-solution-explorer|fernandoescolar|0.8.2|;

</details>

**Comment by dibarbet** [comment]
The non-truncated view of the output window logs can be found in the extension logs folder.  You can get to it from vscode from this command:
![image](https://github.com/OmniSharp/omnisharp-vscode/assets/5749229/d79177be-ed62-44d3-b859-e08ac06129b1)

Then navigating to output window logs and looking for the '.NET Test log.log' file
