### ISSUE TITLE
.NET8 support for Omnisharp is missing

### ISSUE THREAD

**Issue by arkalyanms** [OmniSharp/omnisharp-vscode#5698]
## Steps to reproduce
1.  Install .NET 8 preview SDK
2. dotnet new blazorserver
3. code .

## Expected  behavior
Project loads and has no errors

## Actual behavior
Multiple type errors along the lines of 

The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [BlazorServer, BlazorServer, BlazorServer, BlazorServer]

**Comment by JoeRobich** [comment]
Can you share the OmniSharp log from the Output pane? I do not see these errors locally with .NET 8p4.

**Comment by arkalyanms** [comment]
I dont seem to have access to add Andrew to the repo. Will ping him internally.

**Comment by ryzngard** [comment]
Updating to preview 4 seems to fix. I was on preview 3

> OmniSharp server started with .NET 8.0.100-preview.3.23178.7

**Comment by JoeRobich** [comment]
Thanks for confirming @ryzngard. Closing this out.
