### ISSUE TITLE
Marketplace page should have 64 bit as a minimum requirement

### ISSUE THREAD

**Issue by DoubleCouponDay** [OmniSharp/omnisharp-vscode#578]
Looks like there is only a 64bit version of OmniSharp but perhaps a minimum requirement should be put on this extensions' marketplace page. This would let the readers know they will have to upgrade. 

How hard is it to convert the dll to x86? I could help out if you think its a reachable goal :]
![omnisharp snap](https://cloud.githubusercontent.com/assets/7555725/16909337/759668d2-4d15-11e6-9130-64dbc19bd0ca.PNG)

**Comment by DustinCampbell** [comment]
If you're interested in helping out, this is the issue we're tracking on the OmniSharp server: https://github.com/OmniSharp/omnisharp-roslyn/issues/603.

**Comment by DustinCampbell** [comment]
This is now listed in the Supported Operating Systems section of our readme.md. Once we ship the latest extension (1.3.0) on the marketplace, it will be reflected there as well.
