### ISSUE TITLE
Pagination for variable expansion

### ISSUE THREAD

**Issue by rajkumar42** [OmniSharp/omnisharp-vscode#583]
VSCode is slow to expand really long variables. An 10K array takes few seconds to expand on the watch window. 

Solution: Provide pagination like
1
2
3
4
5
[Click to expand]

"[Click to expand]" will expand the list to include the next 'n' elements.

**Comment by gregg-miskelly** [comment]
The VS Code team has an issue tracking this problem: https://github.com/Microsoft/vscode/issues/9537

**Comment by gregg-miskelly** [comment]
Assuming that VS Code addresses this through 9537, we would need to implement the protocol additions from https://github.com/Microsoft/vscode-debugadapter-node/issues/31

**Comment by gregg-miskelly** [comment]
Support for added to this a while back.
