### ISSUE TITLE
EditorConfig support flakey after LSP initialization / restart.

### ISSUE THREAD

**Issue by StringEpsilon** [OmniSharp/omnisharp-vscode#5874]
In version v2.0.238, I noticed that under some circumstances my editorconfig formatting settings are ignored in favor of the defaults.

Notably this affects [csharp_new_line_before_open_brace](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/csharp-formatting-options#new-line-options).

Before:
```cs
public class ExampleClass {
	public string TestProperty { get; set; }
}
```

After:
```
public class ExampleClass 
{
	public string TestProperty { get; set; }
}
```

The problem sometimes fixes itself after a couple minutes. Sometimes I need to restart the language server again. Sometimes I need to restart VS Code.

It can also be tricky to reliably replicate.

Relevant editorconfig section:

```
[*]
csharp_style_var_when_type_is_apparent = true
csharp_prefer_braces = true:error
csharp_new_line_before_else = false
csharp_new_line_before_open_brace = none
csharp_new_line_before_catch = false
csharp_new_line_before_finally = false
csharp_style_prefer_range_operator = false
csharp_indent_case_contents = true
csharp_indent_case_contents_when_block = false
csharp_indent_labels = one_less_than_current
csharp_indent_switch_labels = true
```

Final note: The formatter still respects my indentation settings, even if I change back and forth in the .editorconfig without reloading the LSP. But the `csharp_new_line_before_open_brace` option remains broken.

**Comment by dibarbet** [comment]
@StringEpsilon can you still reproduce this issue on the latest (prerelease) version of the extension?  I have not been able to.

If you can - can you let me know if you're using DevKit and what commands you're using to restart the server?
