### ISSUE TITLE
Show pattern formats in intellisense for DateTime.ToString

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-vscode#589]
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

VS Code version:1.3.1
C# Extension version:1.2.2
## Steps to reproduce

Have some code that tries to convert a `DateTime` to string using `ToString()`
## Expected  behavior

When the bracket opens on ToString, like R# does, it gives you the format options eg/d,g and what that looks like in intellisense
## Actual behavior

No intellisense

**Comment by DustinCampbell** [comment]
This issue was moved to dotnet/roslyn#17011

**Comment by DustinCampbell** [comment]
I've moved this over to Roslyn. If we decide to add it to Roslyn and Visual Studio, it'll certainly make it's way into C# for VS Code.
