### ISSUE TITLE
Debugger should support pipeTransport for attach

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#602]
The debugger currently only supports `pipeTransport` for launch. It should also support it for attach so that we can enable attach into a Docker container, or into other scenarios where we may want a pipe executable (SSH?). This is especially helpful for programming models that we don't yet support launch for.

**Comment by gregg-miskelly** [comment]
This issue was fixed in https://github.com/OmniSharp/omnisharp-vscode/pull/798

**Comment by DustinCampbell** [comment]
@gregg-miskelly: You marked this as fixed in 1.5 but the PR you linked to is still outstanding.

**Comment by gregg-miskelly** [comment]
Oh, shoot, I thought we merged that PR ages ago.

**Comment by DustinCampbell** [comment]
Should I update the readme to remove that line?

**Comment by gregg-miskelly** [comment]
@DustinCampbell any objection if we merge the PR? We should either merge in 798, or take it out of the readme.

**Comment by DustinCampbell** [comment]
I don't mind as it's not invasive. It needs updating against master though.

**Comment by gregg-miskelly** [comment]
I will get Andrew to rebase it.

**Comment by gregg-miskelly** [comment]
https://github.com/OmniSharp/omnisharp-vscode/pull/918 fixes this.
