### ISSUE TITLE
Add mechanism to suppress 'Get .NET CLI tools' error message

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#603]
## Steps to reproduce

Install the C# extension for the purposes of Unity development
Open a Unity Project
## Expected  behavior

No reference to the .NET CLI since you aren't working on a scenario involving .NET Core
## Possible fixes

The code for this is in [active.ts](https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/coreclr-debug/activate.ts#L30):

```
if (!isDotnetOnPath()) {
    const getDotNetMessage = "Get .NET CLI tools"; 
    vscode.window.showErrorMessage("The .NET CLI tools cannot be located. .NET Core debugging will not be enabled. Make sure .NET CLI tools are installed and are on the path.",
        getDotNetMessage).then(value => {
```

Two possible fixes:
1. Instead of downloading the debugger on C# extension activation, we download it when opening a .NET Core App or when they first try to start debugging.
2. Instead of using an error message, maybe we can use a different piece of VS Code UI that lets the user pick 'never show me this again'.

**Comment by wesrupert** [comment]
PR #700 provides a mechanism to get the message to stop appearing. However, leaving this open to track implementing fix 1.

**Comment by gregg-miskelly** [comment]
With this new download system, I don't think it makes sense to do fix 1 anymore. So closing this.
