### ISSUE TITLE
Omnisharp harderrors in vscode with csproj moved files but didn't check into csproj

### ISSUE THREAD

**Issue by eByte23** [OmniSharp/omnisharp-vscode#604]
## Environment data

.net 451
VS Code version: 1.4.0-insider
C# Extension version: 1.3.0

When a file has moved but the reference in the csproj hasn't been change then omnisharp hard errors with FileNotFound exception trying to find the csproj file.

Should register project work space as projects like visual studio and when moving a file in workspace update csproj.

**Comment by rchande** [comment]
@eByte23 The easiest way for you to accomplish this would be to use "file globbing" in your csproj. You can then use the "restart omnisharp" command to reload the csproj when you move files and have omnisharp properly detect the new files. Feel free to file a new issue if you have more questions.
