### ISSUE TITLE
Access Omnisharp API from another VSCode extension

### ISSUE THREAD

**Issue by Souk21** [OmniSharp/omnisharp-vscode#615]
I'm authoring a VSCode extension, and would need to access Omnisharp API.
For example I would need to know if a certain class inherits from another, is this possible?

Sorry if it's not the right place to ask that.

**Comment by DustinCampbell** [comment]
FWIW, this is probably better asked on the https://github.com/OmniSharp/omnisharp-roslyn repo, or in the OmniSharp Slack channels. This repo is specially for the C# extension for VS Code, which uses OmniSharp.
