### ISSUE TITLE
Omnisharp new 1.3 Version can not work with Unity csproj project on Win10

### ISSUE THREAD

**Issue by ChongWangUBI** [OmniSharp/omnisharp-vscode#621]
## Environment data
`dotnet --info` output: 1.0.0-preview2-003121
VS Code version: 1.3.1
C# Extension version: 1.3.0 
OS: Win10
Work: Unity3.5.2
## Steps to reproduce
Open Unity .sln，csproj File. 
Get the Error:

[INFORMATION:OmniSharp#MSBuild] Loading project from 'e:\DNF_Project\Program\Client\Assembly-CSharp-Editor.csproj'.
[INFORMATION:OmniSharp#ProjectFileInfo] Using toolset 15.0 for e:\DNF_Project\Program\Client\Assembly-CSharp-Editor.csproj
[ERROR:OmniSharp#ProjectFileInfo] The reference assemblies for framework ".NETFramework,Version=v3.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

**Comment by gregg-miskelly** [comment]
@ChongWangUBI in case this isn't obvious - you may be able to work around this by now by installing .NET Framework 3.5 in the 'Windows Features' dialog.

**Comment by ChongWangUBI** [comment]
@gregg-miskelly  installing .Net Framework3.5 in the windows Features Dialog. can not resovle this problem .

**Comment by gregg-miskelly** [comment]
@ChongWangUBI Thanks for trying. Unfortunately I don't know enough the language service side of the extension to have any other ideas, and the primary language service dev is on vacation. So it may be a little while before anyone gets back to you. But thank you for reporting the issue.

**Comment by DustinCampbell** [comment]
@ChongWangUBI, could you provide the entire OmniSharp log when trying to load your project?

**Comment by ChongWangUBI** [comment]
@DustinCampbell 
The Entire OmniSharp Log is:

Flavor: 0, Platform: 1
[INFO] Installing OmniSharp to C:\Users\Administrator\.vscode\extensions\ms-vscode.csharp-1.3.0\out\.omnisharp-coreclr
[INFO] Attempting to download omnisharp-1.9-beta12-win-x64-netcoreapp1.0.zip...
[INFO] Downloading to C:\Users\ADMINI~1\AppData\Local\Temp\tmp-61122OYi0pRjX3qY.tmp...
[INFO] Download complete!
[INFO] Decompressing...
[INFO] Done! 441 files unpacked.
[INFO] Starting OmniSharp at 'e:\DNF_Project\Program\Client'...
[INFO] Started OmniSharp from 'C:\Users\Administrator\.vscode\extensions\ms-vscode.csharp-1.3.0\out\.omnisharp-coreclr\OmniSharp.exe' with process id 13348...
OmniSharp: -s e:\DNF_Project\Program\Client --hostPID 6112 DotNet:enablePackageRestore=false --stdio
[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location 'e:\DNF_Project\Program\Client' on host 6112.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in e:\DNF_Project\Program\Client
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp#MSBuild] Detecting projects in 'e:\DNF_Project\Program\Client\Client.sln'.
[INFORMATION:OmniSharp#MSBuild] Loading project from 'e:\DNF_Project\Program\Client\Assembly-CSharp-firstpass.csproj'.
[INFORMATION:OmniSharp#ProjectFileInfo] Using toolset 15.0 for e:\DNF_Project\Program\Client\Assembly-CSharp-firstpass.csproj
[ERROR:OmniSharp#ProjectFileInfo] The reference assemblies for framework ".NETFramework,Version=v3.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[WARNING:OmniSharp#MSBuild] Failed to process project file 'e:\DNF_Project\Program\Client\Assembly-CSharp-firstpass.csproj'.
e:\DNF_Project\Program\Client\Assembly-CSharp-firstpass.csproj

[INFORMATION:OmniSharp#MSBuild] Loading project from 'e:\DNF_Project\Program\Client\Assembly-CSharp.csproj'.
[INFORMATION:OmniSharp#ProjectFileInfo] Using toolset 15.0 for e:\DNF_Project\Program\Client\Assembly-CSharp.csproj
[ERROR:OmniSharp#ProjectFileInfo] The reference assemblies for framework ".NETFramework,Version=v3.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[WARNING:OmniSharp#MSBuild] Failed to process project file 'e:\DNF_Project\Program\Client\Assembly-CSharp.csproj'.
e:\DNF_Project\Program\Client\Assembly-CSharp.csproj

[INFORMATION:OmniSharp#MSBuild] Loading project from 'e:\DNF_Project\Program\Client\Assembly-CSharp-Editor-firstpass.csproj'.
[INFORMATION:OmniSharp#ProjectFileInfo] Using toolset 15.0 for e:\DNF_Project\Program\Client\Assembly-CSharp-Editor-firstpass.csproj
[ERROR:OmniSharp#ProjectFileInfo] The reference assemblies for framework ".NETFramework,Version=v3.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[WARNING:OmniSharp#MSBuild] Failed to process project file 'e:\DNF_Project\Program\Client\Assembly-CSharp-Editor-firstpass.csproj'.
e:\DNF_Project\Program\Client\Assembly-CSharp-Editor-firstpass.csproj

[INFORMATION:OmniSharp#MSBuild] Loading project from 'e:\DNF_Project\Program\Client\Assembly-CSharp-Editor.csproj'.
[INFORMATION:OmniSharp#ProjectFileInfo] Using toolset 15.0 for e:\DNF_Project\Program\Client\Assembly-CSharp-Editor.csproj
[ERROR:OmniSharp#ProjectFileInfo] The reference assemblies for framework ".NETFramework,Version=v3.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[WARNING:OmniSharp#MSBuild] Failed to process project file 'e:\DNF_Project\Program\Client\Assembly-CSharp-Editor.csproj'.
e:\DNF_Project\Program\Client\Assembly-CSharp-Editor.csproj

[INFORMATION:OmniSharp.Startup] Configuration finished.

**Comment by ChongWangUBI** [comment]
@DustinCampbell 
I change use the win-x64-net451.zip ,fixed this problem.
and, 
by add  omnisharp start cmd  "--encoding utf-8"
OmniSharp: -s e:\DNF_Project\Program\Client --hostPID 14820 DotNet:enablePackageRestore=false --stdio --encoding utf-8
fixed OmniSharp Stop Working with Odd Multi-Byte characters problem.

**Comment by DustinCampbell** [comment]
Ah, of course. Did your Unity project contact a project.json file by chance? That would have tricked the extension into trying to use the CoreCLR version of OmniSharp, which is what failed here.
