### ISSUE TITLE
1.3 regression: Lots of errors reported: "The type 'X' is defined in an assembly that is not referenced"

### ISSUE THREAD

**Issue by ivanz** [OmniSharp/omnisharp-vscode#622]
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

VS Code version: 1.3.1
C# Extension version: 1.3.0
## Steps to reproduce

**project.json**

``` json
{
    "frameworks": {
        "net45": { }
    },
    "dependencies": {
        "FluentAssertions": "4.*"
    }
}
```

**test.cs**

``` C#
using FluentAssertions;

namespace Test
{
    public class Tester
    {
        public static void Bla()
        {
            true.Should().BeTrue(); // problem reported here
        }
    }
}
```
## Expected  behaviour

No problems/errors reported in Visual Studio code.
## Actual behaviour

Problem reported on the above source code line:

```
The type "Object" is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0....
```

**Comment by DustinCampbell** [comment]
I suspect the reason for this regression is because we're now using the CoreCLR version of OmniSharp on Windows for .NET Core projects rather than the Desktop version.

**Comment by DustinCampbell** [comment]
Compiled and digging with IL Spy:

* Test.dll references FluentAssertions.dll and FluentAssertions.Core.dll.
* FluentAssertions.dll references mscorlib, 4.0.0.0
* FluentAssertions.Core.dll references mscorlib, 2.0.5.0

Doesn't seem related to CoreCLR OmniSharp. I just tried running it with the Desktop OmniSharp and see the same error. Hmmm....

**Comment by DustinCampbell** [comment]
@ivanz: Are you sure this is a regression? I just tried this with version 1.2.2 and still see the same error.

**Comment by ivanz** [comment]
Hmm. As far as I recall I wasn't seeing any of those errors, updated the extension (not sure from which version) and then I started seeing them. I wonder if FluentAssertions.Core is a portable assembly or something.

**Comment by DustinCampbell** [comment]
Hey @ivanz. I just checked this with the latest .NET CLI using a .csproj and it looks much better:

Project file:

```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net46</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="4.*" />
  </ItemGroup>

</Project>
```

![image](https://cloud.githubusercontent.com/assets/116161/22715479/fd29e230-ed45-11e6-95b9-84c15fe3f098.png)

Look OK to you?

**Comment by ivanz** [comment]
Cool cool.
