### ISSUE TITLE
Unable to install coreclr-debug on Elementary OS

### ISSUE THREAD

**Issue by kieferrm** [OmniSharp/omnisharp-vscode#625]
Moved from https://github.com/Microsoft/vscode/issues/9780:
- VSCode Version: Version 1.3.1 and Version 1.4.0-insider
- OS Version: Elementary OS Freya 0.3.2

Steps to Reproduce:
1. Install Elementary OS
2. Install Visual Studio Code
3. Install C# extension
4. Load a .NET Core project
5. Attempt to debug the project

Able to see the error log when the developer console is open within Visual Studio Code.
Should this not install correctly even if using Elementary OS? 
Elementary OS is built on Ubuntu 14.04.

Thanks very much.

![image](https://cloud.githubusercontent.com/assets/8898038/17138956/d4605fd2-5385-11e6-8697-b3bb8f609024.png)

**Comment by gregg-miskelly** [comment]
@kieferrm if Elementary OS is based on Ubuntu 14.04, hopefully this is just a tweak to this [switch statement](https://github.com/OmniSharp/omnisharp-vscode/blob/735f90a299e857fc5de97216f961c4dd16907cac/src/platform.ts#L59). If you are interested, we would happily take a PR. Otherwise, if you want to paste in the output of `cat /etc/os-release` I can try to send you a private .vsix which will send us down that way.

**Comment by Firaenix** [comment]
Here is my output from `cat /etc/os-release`

```
$ cat /etc/os-release
NAME="elementary OS"
VERSION="0.3.2 Freya"
ID="elementary OS"
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS Freya"
VERSION_ID="0.3.2"
HOME_URL="http://elementary.io/"
SUPPORT_URL="http://elementary.io/support/"
BUG_REPORT_URL="https://bugs.launchpad.net/elementary/+filebug"
```

I have fixed the issue locally on my PC, I'd be more than happy to make a pull request. 
Change is pretty straight forward.

Thanks very much for your help

**Comment by Firaenix** [comment]
I have created pull request for this feature here: https://github.com/OmniSharp/omnisharp-vscode/pull/628

**Comment by gregg-miskelly** [comment]
@Firaenix Thanks again!

**Comment by yehudag** [comment]
You might want to reopen this issue: the value of ID was changed. 
Here is my output from `cat /etc/os-release`

```
$ cat /etc/os-release
NAME="elementary OS"
VERSION="0.4 Freya"
ID="elementary"
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 0.4 Loki"
VERSION_ID="0.4"
HOME_URL="http://elementary.io/"
SUPPORT_URL="http://elementary.io/support/"
BUG_REPORT_URL="https://bugs.launchpad.net/elementary/+filebug"
```

**Comment by gregg-miskelly** [comment]
So it sounds like it is now `VERSION` instead of `VERSION_ID`?

**Comment by yehudag** [comment]
Yes. Sorry for delay

**Comment by gregg-miskelly** [comment]
@yehudag I am attaching a version of the C# extension which I think will fix your issue. Would you mind giving it a quick try?

1. Save the file
2. Remove the '.renamed.zip' extension
3. Open the file in VS Code
4. You should see the file install, when prompted, restart VS Code

[csharp-1.5.0-dev5.vsix.renamed.zip](https://github.com/OmniSharp/omnisharp-vscode/files/530549/csharp-1.5.0-dev5.vsix.renamed.zip)

**Comment by yehudag** [comment]
Yes that worked. Thanks
