### ISSUE TITLE
Quick fix menu does not close when cursor has moved

### ISSUE THREAD

**Issue by natemcmaster** [OmniSharp/omnisharp-vscode#629]
## Environment data

`dotnet --info` output: `1.0.0-preview3-003206`, OSX 10.10
VS Code version: 1.3.1
C# Extension version: 1.3.0
## Steps to reproduce

Request the quick fix tooltip (keyboard or click on lightbulb).
Move text cursor before tooltip finishes loading
## Expected  behavior

Tooltip should not appear when cursor has moved
## Actual behavior

Tooltip appears and stays around, even after omnisharp has shutdown, and even after click on one of the quick fix suggestions.

This happens the most when omnisharp server is running slowly, which happens often on solutions with many projects or after file/folder renames ([example](https://github.com/aspnet/EntityFramework)).

![tooltip](https://cloud.githubusercontent.com/assets/2696087/17226822/2ff5e656-54c0-11e6-84ff-db7dbbe26ec6.gif)

**Comment by DustinCampbell** [comment]
I suspect this was a VS Code issue that was fixed at some point. I can no longer reproduce it.
