### ISSUE TITLE
Give fair warning upfront that this C# is Windows 64-bit only. Or (better) support 32-bit.

### ISSUE THREAD

**Issue by manukautech** [OmniSharp/omnisharp-vscode#634]
## Environment data

`dotnet --info` output:
VS Code version:
C# Extension version:all
## Steps to reproduce:

Take on what turns out to be the very difficult challenge of teaching MVC6 and ASP.NET Core to my PolyTech programming class. Spend many hours setting up a virtual machine running Windows 10 32-bit with Visual Studio Code and resources for many good reasons coming from the special challenges of this teaching and learning environment including many many installation failures on student laptops. Get many errors. Click an obscure blue OmniSharp error message in the bottom right hand corner of VS Code. Display happens to mention X64 in an installation error message. Be like a Sherlock Holmes detective and follow the trail to this github site and discover - well scrolled down and therefore obscure - the sad sad information that support for Windows is 64-bit only.
## Expected  behavior:

Preferably support 32-bit. Because everything else in this ASP.NET Core ecosystem supports 32-bit. Wide support of OSs is a stated Core aim so this exception comes as a less than obvious surprise. 
ALTERNATIVE expected behaviour:  Warn us about 64-bit only - UPFRONT - as in visible when this item appears in the Extensions panel of VS Code. Further suggestion is better indication of error when installing into 32-bit Windows. 
## Actual behavior:

dotnet run of the "Blogging" example app aka "EFGetStarted.AspNetCore.ExistingDB" results in bright red text giving 608 errors "error NU1001: The dependency ... could not be resolved". See attached screen shots.
![20160730 jpc screenshot error dotnet run](https://cloud.githubusercontent.com/assets/4345497/17268215/b67c6a60-5678-11e6-821b-dabab81498e2.jpg)
![20160730 jpc screenshot omnisharp not installed](https://cloud.githubusercontent.com/assets/4345497/17268216/b680d334-5678-11e6-9272-ae2a75b62f1e.jpg)

**Comment by DustinCampbell** [comment]
I just wanted to let you know that the latest release of the C# extension (1.5.2) supports 32-bit Windows for IntelliSense, go to definition, find all references, and other editor features. The debugger still does not support 32-bit Windows, and that is being tracked with https://github.com/OmniSharp/omnisharp-vscode/issues/844.
