### ISSUE TITLE
Allow permanent dismissal of build/debug assets message

### ISSUE THREAD

**Issue by Tyriar** [OmniSharp/omnisharp-vscode#635]
![image](https://cloud.githubusercontent.com/assets/2193314/17301255/e4a7d28c-57ca-11e6-8536-cbae5856b8ca.png)

I have no desire to add the `.vscode` directory for this project, yet every time I open the folder the extension bugs me. I'd like a way to dismiss it permanently for this PC.

The project in question is a library (no entry point) with a set of tests: https://github.com/gwtw/csharp-data-structures
The message: https://github.com/OmniSharp/omnisharp-vscode/blob/6ecb840f6c9e0d90cf7f10625d0347e6ade6b0b2/src/assets.ts#L126

**Comment by DustinCampbell** [comment]
There is a new beta of the C# extension available [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.5-beta3) that includes this feature if you'd like to try it.
