### ISSUE TITLE
Can't copy the values of debugging elements such as exception messages

### ISSUE THREAD

**Issue by CarlosTorrecillas** [OmniSharp/omnisharp-vscode#639]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version: 1.3.1
C# Extension version: 1.3

## Steps to reproduce
- Create a .NET Console app
- Add the code to throw an exception
- On the debugging section try copy the value of either the message or the stacktrace

## Expected  behavior
- I would expect the value to be copied in the clipboard

## Actual behavior
- I get the message "error CS1012: Too many characters in character literal"

**Comment by chuckries** [comment]
This issue was moved to Microsoft/vscode#10210

**Comment by chuckries** [comment]
This is an issue with VS Code's debug UI, moving to their repo.
