### ISSUE TITLE
Parameter hints throw null access error

### ISSUE THREAD

**Issue by joaomoreno** [OmniSharp/omnisharp-vscode#64]
Triggering the parameter hints in Code and moving the cursor to outside of that method call will cause the following exception:

```
Cannot read property 'ActiveSignature' of null: TypeError: Cannot read property 'ActiveSignature' of null
    at /Users/joao/.vscode-oss-dev/extensions/ms-vscode.csharp-0.3.3/out/features/signatureHelpProvider.js:24:38
    at process._tickCallback (node.js:369:9)
```

![bug](https://cloud.githubusercontent.com/assets/22350/13574574/fe6b91e0-e484-11e5-99ca-f757afc0fbc3.gif)

**Comment by joaomoreno** [comment]
Related to Microsoft/vscode#3173

**Comment by DustinCampbell** [comment]
Great bug -- thanks!

**Comment by joaomoreno** [comment]
:+1: cc @chrisdias

**Comment by DustinCampbell** [comment]
I took a quick look. It looks like this is a bug with omnisharp here: https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Roslyn.CSharp/Services/Signatures/SignatureHelpService.cs#L94

Essentially, OmniSharp is too permissive and returns signatures even if the position requested falls outside of the ()'s.

**Comment by DustinCampbell** [comment]
This is fixed in the dev branch
