### ISSUE TITLE
CoreCLR Debug: more than just C#

### ISSUE THREAD

**Issue by borgdylan** [OmniSharp/omnisharp-vscode#641]
## Environment data
`dotnet --info` output: 1.0.0-preview3-003236
VS Code version: 1.5.0 insider
C# Extension version: 1.3
OS: Ubuntu 16.04 on Intel x64

Can the CoreCLR debugger be allowed to accept breakpoints on non-C# files? I have a custom compiler that can make ppdb debug files when targeting .NET Core. I would like to be able to step thru source code like I can do with mono. The debugger already tells vscode to show the correct line when I throw exceptions and this reflects in the ui breaking on the line when I throw exceptions. It would be nice to also be able to step thru code when it runs fine to validate the behavior of the running code. This will help my efforts I am taking to support .NET Core with my compiler.

**Comment by gregg-miskelly** [comment]
@borgdylan The way VSCode works, an extension needs to statically declare the set of languages (and extensions) it supports in in package.json file. You can try manually editing the file. If you like the results, you are free to enable it in the C# extension's package.json.

**Comment by borgdylan** [comment]
I have added my language id to the package.json. That allowed the debugger to support breaking on exceptions but did not allow me to activate breakpoints in the code. With mono I had to change the package.json and also modify the extension's OpenDebug adapter to support my language. With clrdbg I do not have access to the source code for the open debug adapter.

**Comment by borgdylan** [comment]
I added it in the "enableBreakpointsFor" section of the file. I cannot add the extension with the C# language definition as that would override my syntax highlighter and create a conflict with my extension.

**Comment by borgdylan** [comment]
This will also be an issue once VB and F# use on .Net Core picks up.

**Comment by gregg-miskelly** [comment]
@borgdylan there isn't any code that we have that you will need to modify. Do you have the mono extension installed at the same time? I don't know how well VS Code deals with multiple extensions supporting breakpoints on the same file type.

**Comment by borgdylan** [comment]
I do have the mono extension. It lets me place the breakpoint but then declares that the debugger engine does not support placing a breakpoint there. This happens for clrdbg only.

**Comment by gregg-miskelly** [comment]
@borgdylan you might try either building a new version of the .vsix with the change to package.json (in case VS Code does some caching on VS Code install) and/or uninstall the mono extension to see if either of these resolves it.

Another thought - you could search VS Code for the exact error message string in case that reveals anything.

**Comment by borgdylan** [comment]
Thanks. I will try and report back. VSCode does not cache package.json changes AFAIK. I have configured extensions ij teh past and just needed a restart to have changes take effect.

**Comment by borgdylan** [comment]
The message:
```
No executable code of the debugger’s target code type is associated with this line.
Possible causes include: conditional compilation, compiler optimizations, or the target architecture of this line is not supported by the current debugger code type.
```

It is not coming from VSCode itself. In fact it is not in its codebase. People have seen this happen in Visual Studio as well so it is coming from the VS MI Engine.

**Comment by borgdylan** [comment]
The issue persists even with the mono extension being uninstalled.

**Comment by borgdylan** [comment]
If in launch.json I specify that I want to stop on the first line, the debugger stops and highlights the first line in Program.Main. The only thing that works after that is stepping into/over.

**Comment by borgdylan** [comment]
Question: does the debugger expect the use of full or relative paths? Most debuggers including mono need full paths in pdb files.

**Comment by borgdylan** [comment]
NB: This message that VSCode shows, appears when the debugger engine is connected. It is not VSCode itself that is rejecting the breakpoints but clrdbg/MIEngine. The package.json tells VSCode to allow placing breakpoints but it is the debugger engine that must accept them at debug time. Clrdbg seems to find the source files when signalling unhandled exceptions (it gets the line in the source file correct).

**Comment by borgdylan** [comment]
This means I was pointed to the right direction. The MI Engine code: https://github.com/Microsoft/MIEngine/blob/2187999976a8606700097b649d2ffb2b3ff070a5/src/MIDebugEngine/AD7.Impl/AD7DocumentContext.cs#L84

I plan to add another branch to that if statement with my language's extension (which also uses the c# guid in pdb files) and see where I get to.

**Comment by borgdylan** [comment]
That plan has stalled. To build MIEngine I will have to have Windows and VisualStudio. Is there a .NET core 1.0 variant of MIEngine (not referencing ancient dnxcore50)?

**Comment by gregg-miskelly** [comment]
That is okay, because you are looking at the wrong code anyway :). That line is either not called at all for VS Code (which would be my guess) or it does something really unimportant.

The problem is with your PDB file. When we look from instruction->source, we are able to find the instruction, but when we look from source->instruction, we cannot locate the source file or line. What are you using to write portable PDBs?

**Comment by borgdylan** [comment]
I am using the "Managed.Reflection" library. I contacted the author and he states that the pdb files are correct (he examined some pdb file I generated).

**Comment by borgdylan** [comment]
@gregg-miskelly I can send you the same files so you could take a look. I know a lot about IL but I don't have any knowledge on PDBs.

**Comment by gregg-miskelly** [comment]
@jfrijters do you have your own implementation of a portable PDB writer? Or are you using something from Mono?

@tmat is there any tool that one can use to easily dump portable PDBs?

**Comment by tmat** [comment]
@gregg-miskelly Yes, mdv.exe from Roslyn build drop.

**Comment by borgdylan** [comment]
Mono has no pdb writing code. It can only write it's native mdb format. It is capable of reading portable pdbs in its runtime.

**Comment by tmat** [comment]
@borgdylan I'd recommend using [System.Reflection.Metadata](https://dotnet.myget.org/F/dotnet-core/api/v2/package/System.Reflection.Metadata/1.4.1-beta-24406-01) package for writing Portable PDBs (and PE files as well). That's what Roslyn uses.  It's a cross-platform library that works on Mono.

**Comment by borgdylan** [comment]
I cannot, that would mean rewriting my compiler from scratch.

**Comment by borgdylan** [comment]
Can Sys.Refl.Metadata;'s PdbWriter be used independently from its PEWriter?

**Comment by tmat** [comment]
Yes, you can use just what you need. It'd be better if Managed.Reflection worked though to provide folks like your who have already invested in Ref.Emit style APIs a working alternative. Ideally, imo, Managed.Reflection would take advantage of System.Reflection.Metadata builders internally.

**Comment by borgdylan** [comment]
@tmat There was a bugfix released in Managed.Reflection. It was making incorrect pdbs if more than one sequence point got emitted in a single line. I confirm that with the new bits both mono and clrdbg behave as they do with roslyn's output.

**Comment by tmat** [comment]
@borgdylan Cool.

**Comment by borgdylan** [comment]
I can finally get rid of all that extension replacing to change .pdb into .dll.mdb/.ece.mdb and can also retire my patches to .NET CLI for supporting mono's mdb files. Standard portable PDB for everyone!

**Comment by borgdylan** [comment]
@tmat @gregg-miskelly One last question: Does clrdbg currently support local variables? Mono is ignoring the variable names (uses V_0, V_1 etc. instead) but is showing me arguments and variables separately. While with clrdbg I can see arguments but no local variables when I debug.

**Comment by gregg-miskelly** [comment]
@borgdylan this means that you are missing information on local variables from the PDB you are generating. Clrdbg/VS will not show unnamed locals.

**Comment by borgdylan** [comment]
This has been fixed in Managed.Reflection. I can now see the names of all locals.

**Comment by gregg-miskelly** [comment]
@borgdylan great! You are welcome to submit a PR for the package.json change if you would like to enable this by default.

**Comment by borgdylan** [comment]
Which change? To enable my language's file to be debuggable? I do not have a lot of users so I prefer to keep patching the file manually.

**Comment by gregg-miskelly** [comment]
@borgdylan that is certainly fine with us too.
