### ISSUE TITLE
Have a keyboard shortcut for the yellow bulb options (help)

### ISSUE THREAD

**Issue by CarlosTorrecillas** [OmniSharp/omnisharp-vscode#644]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
VS Code version: 1.4.1
C# Extension version: 1.3.0

## Steps to reproduce
- Get a line of code to get the yellow bulb for suggestions
- Click the yellow bulb

## Expected  behavior
- Something like Alt+ Enter or something similar would be useful to show the suggestions/options instead of having to click

## Actual behavior
- You need to click the yellow bulb to get the suggestions

**Comment by Souk21** [comment]
Just add this to your keyboard shortcuts:

    {
        "key": "alt+enter",
        "command": "editor.action.quickFix",
        "when": "editorTextFocus"
    },

**Comment by CarlosTorrecillas** [comment]
Awesome, thanks!

**Comment by johanneskopf** [comment]
Strg + "." (Period)
is already doing this.

**Comment by DustinCampbell** [comment]
Looks like this has resolved itself. :smile:

FWIW, this is really an ask for VS Code, not for the C# Extension in VS Code. That said, there is already a keyboard shortcut, and it's easy to add your own.
