### ISSUE TITLE
Debugger: variable value isn't refeshed while it has been changed

### ISSUE THREAD

**Issue by v-zhanme** [OmniSharp/omnisharp-vscode#645]
## Environment data
`dotnet --info` output:
VS Code version:1.3.1
C# Extension version:1.3.0

## Steps to reproduce
1) Open sample project in VSCode
2) Set a BP at line 30 in Program.cs
3) F5
4) Add i in Watch
5) Add i=10 in Watch

## Expected  behavior
The value of i changes to be 10 in Watch and Locals.

## Actual behavior
The value of i still is 5.
##Attachements
[ScreenShot](https://cloud.githubusercontent.com/assets/20921752/17508959/24a220ce-5e4a-11e6-97d0-a4fd66854428.PNG)
[MIEngine Log](https://github.com/OmniSharp/omnisharp-vscode/files/408450/log.txt)
[Repro Project](https://github.com/OmniSharp/omnisharp-vscode/files/408451/newapp.zip)

**Comment by gregg-miskelly** [comment]
This is a bug/non-feature with the VS Code UI. See https://github.com/Microsoft/vscode/issues/2399.
