### ISSUE TITLE
Debugger: Thread name is <No Name> in call stack and thread quantity is not consistency

### ISSUE THREAD

**Issue by v-zhanme** [OmniSharp/omnisharp-vscode#646]
## Environment data
`dotnet --info` output:
VS Code version:1.3.1
C# Extension version:1.3.0

## Steps to reproduce
1) Open sample project in VSCode
2) Set a BP at line 21 in Program.cs
3) F5
4) Check call stack

## Expected  behavior
I'm not sure if this <No Name> is expected. And here are two threads in call stack.

## Actual behavior
threads name are <No Name>. And here are three threads in call stack.

##Attachments
![1](https://cloud.githubusercontent.com/assets/20921752/17510079/e219384a-5e4f-11e6-9f2a-4cde8132a547.PNG)
[log.txt](https://github.com/OmniSharp/omnisharp-vscode/files/408534/log.txt)
[newapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/408535/newapp.zip)

**Comment by gregg-miskelly** [comment]
The fact that there is an extra thread sounds fine -- the framework is probably just starting one. 
The call stacks of the two threads look correct.
The '<No Name>' part isn't the best string. https://github.com/OmniSharp/omnisharp-vscode/issues/361 tracks coming up with something better.
