### ISSUE TITLE
Debugger: Conditional breakpoint be hit when the left-hand side of an assignment is a variable 

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#647]
## Environment data

`dotnet --info` output:
VS Code version: 1.4.0
C# Extension version: 1.3.0
## Steps to reproduce

1 Add a conditional breakpoint at line of " _appSettings = options.Value; " in HomeController.cs
and edit that breakpoint with condition of "1=0"
2 Press F5 to start debugging
## Expected  behavior

The conditional breakpoint I just added shouldn't be hit in editor window. I input a false expression, so the breakpoint would not be hit and should show a error massage " The left-hand side of an assignment must be a variable, property or indexer."
## Actual behavior

This conditional breakpoint can be hit.

**Comment by gregg-miskelly** [comment]
cc @chuckries

**Comment by WardenGnaw** [comment]
Conditions that can not be executed are treated like normal breakpoints. 

There will be an error message indicating the failure and the conditional breakpoint will be treated as a regular breakpoint.
