### ISSUE TITLE
coreclr-debug/acquisition telemetry should be improved

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#649]
From telemetry in version 1.2.2 of the extension , 24.3% of users hit into a 'dotnetRestore' failure acquiring the debugger.

Currently, our telemetry for dotnetRestore failures isn't great - 
* We don't know the architecture of the OS we are on (currently only important on Windows)
* We don't know the version of the CLI which is installed
* We don't have any sort of error message from the CLI

For scraping the error message, the CLI seems to write the error to stderr similar to the following:

    Errors in C:\proj\clicon\project.json
        Unable to resolve 'does-not-exist (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.

(NOTE: This is a bogus error I came up with by declaring a package named 'does-not-exist').

My suggestion is -- if error code is '1' look for the first error line that starts with four spaces, and isn't empty, and remove the user's alias if it happens to be in it.

**Comment by wesrupert** [comment]
Fixed in [693](https://github.com/OmniSharp/omnisharp-vscode/pull/693). This should be available in the next release.
