### ISSUE TITLE
Custom Class autocomplete not working.

### ISSUE THREAD

**Issue by Ceeten** [OmniSharp/omnisharp-vscode#650]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
VS Code version:
1.3.1
C# Extension version:
1.3

## Steps to reproduce
Install latest visual studio code, have c# extension. Create a new aspnet core application and create your own custom class in the models folder.
Then make a new instance of that class in a controller for example.

## Expected  behavior
see the properties of that instance with autocomplete.

## Actual behavior
properties not suggested.
omnisharp log: 
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 5ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 0ms

**Comment by DustinCampbell** [comment]
Hi! Sorry for the delay on this. Could you provide your full OmniSharp log to help us better understand what's happening? Thanks!

**Comment by Ceeten** [comment]
Hi

I recently formatted my MacBook and thus had to reinstall everything from scratch.
I guess the bug has already been fixed since I can see it now.
My Omnisharp log also doesn't contain any errors any more.

I will close this issue since there is none any more.

Thanks anyway

**Comment by DustinCampbell** [comment]
Not a problem. I'm glad it's working for you!
