### ISSUE TITLE
C# Extension & Debugger Unsupported Linux Platform

### ISSUE THREAD

**Issue by alexandrudima** [OmniSharp/omnisharp-vscode#661]
Moved from Microsoft/vscode#10545
From @alpox

---
- VSCode Version: 1.4.0
- OS Version: Linux Manjaro KDE Version (Arch x64)
                    uname -a --> Linux elias-pc 4.4.16-1-MANJARO #1 SMP PREEMPT Wed Jul 27 21:09:47 UTC 2016 x86_64 GNU/Linux

I get the following error when trying to install the .NET Debugger with Ctrl-Shift-P: Debug: Download .NET Core Debugger

![image](https://cloud.githubusercontent.com/assets/12485194/17664643/de573c0c-62f5-11e6-943e-1695a61f732a.png)

Steps to Reproduce:
1. Install Manjaro KDE Version
2. Install dotnet-cli from the AUR with the following patch http://www.pastefile.com/5T8qbi (Sadly there was no other option available which worked for installing the dotnet-cli on this system)
3. Install visual-studio-code
4. Install C# Extension
5. Try to install the .NET Core Debugger

I'm aware that you didn't focus on such linux systems yet so the error message is quite obvious. I wonder though, if you will try to bring better support for C# development for other linux platforms like Arch Linux as well.

**Comment by gregg-miskelly** [comment]
@alpox I created a [wiki page](https://github.com/OmniSharp/omnisharp-vscode/wiki/C%23-Extension-support-for-new-Linux-Distros-with-.NET-Core) to detail options for Linux distro support. Please give that a read.

**Comment by alpox** [comment]
Okay thanks @gregg-miskelly. I now setup a new Linux KUbuntu on which it works for now. When i next use an Arch system - I still have one somewhere - I'll be happy to give it a try! The switch statement tweaking sounds promising.

Many thanks

**Comment by Fudg40** [comment]
I use Arch Linux myself and can confirm that tweaking the switch statement will fix the issue. There should be a way to allow non hard-coded Linux distros. Maybe just display a warning rather than completely removing support.

**Comment by gregg-miskelly** [comment]
@Fudg40 we are happy to accept a PR or if you can send us /etc/os-release we can try this our self. There is no 'generic Linux' version of CoreCLR, so if we don't understand the distro there is nothing we can do.

**Comment by tomasvarg** [comment]
@DSchroer Could you please specify your tweaks of the switch? I tried that too (for Arch Linux - "arch" as a value of the distribution.name, returning whatever distro constant available from the switch), the debugger downloads & installs but running it fails with "Debug adapter process has terminated unexpectedly"

I can't find any details, are the failures logged somewhere?

**Comment by semyon2105** [comment]
@tomasvarg Installing icu54 from AUR fixed that for me (I used debugger for fedora.23-x64)

**Comment by ckolumbus** [comment]
I can't get the debugger working with Manjaro 17.0.1. I have icu55 installed from AUR but none of the fallback debugger runtime ID settings seem to work. Anyone here with more success?

**Comment by rchande** [comment]
@gregg-miskelly It's been almost a year since your last comment. Can we close this issue?
