### ISSUE TITLE
context menu stuck using Ctrl + . command.

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#664]
_From @mrunixus on August 12, 2016 15:49_
- VSCode Version: 1.4.0
- OS Version: Windows 7

Steps to Reproduce:
Ctrl + .  command, to import a namespace in C#
1.  make the method async
2.  the context method got stuck
   ![capture](https://cloud.githubusercontent.com/assets/1231598/17628260/9beb6e1c-6082-11e6-8be5-b60c313793b6.PNG)

_Copied from original issue: Microsoft/vscode#10479_

**Comment by jrieken** [comment]
@mrunixus Can you check if there is an error in the developer console (F1 > Toggle Developer Tools)

**Comment by jrieken** [comment]
_From @mrunixus on August 15, 2016 17:23_

Good afternoon @jrieken , here it's the error in the developer console.
[consoleOutput.txt](https://github.com/Microsoft/vscode/files/418571/consoleOutput.txt)


Thanks, Pedro Morales.

**Comment by alexandrudima** [comment]
Sorry, lack of communication :) - Same as #663

**Comment by DustinCampbell** [comment]
I've seen this too. It's not clear what makes this happen but it's pretty weird.

**Comment by DustinCampbell** [comment]
I think this got fixed awhile back. I haven't seen it in months. Let me know if anyone sees it again.
