### ISSUE TITLE
'dotnet new -t web' projects don't run correctly from VS Code

### ISSUE THREAD

**Issue by alexandrudima** [OmniSharp/omnisharp-vscode#668]
Moved from Microsoft/vscode#10602

---
From @chopetra 

- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

make asp.net core basic dir file with console 
dotnet new -t web 

and vs code f5 or ctrl+f5 then display result site
but this is wrong result

in cmd dotnet run that makes good result

vs code developer plz answer me
why ?

Steps to Reproduce:

1.
2.

**Comment by gregg-miskelly** [comment]
@chopetra can you tell us more about what is happening?

**Comment by chopetra** [comment]
블로그서명


i am a korean so english not good  
 
in dotnet core  not dotnet framework  
 
first cmd console  
type dotnet new -t web 'appname' then make basic directory and files
 
1. in cmd console  
type dotnet run then make correct result in browser  
but
2. in vs code press f5 or ctrl+f5 key make wrong result in browser and 
debug mode (ctrl+shift+d) ' and select '.net core launch (web)' then make wrong result in browser  
 
i attach 2 result image file check this file  
 
 
-----Original Message-----

**Comment by gregg-miskelly** [comment]
@chopetra hmm... I am not seeing your attachments. Can you try dragging and dropping them into the comment editor in this bug? If that doesn't work, you are welcome to describe what you are seeing in Korean, and I can try and find someone to translate. In case this helps -- I am interested in what the browser is saying, and what, if anything, is in the VS Code debug console.

Thanks!

**Comment by gregg-miskelly** [comment]
@chopetra Thanks! the image came through, though if VS Code, the C# extension / debugger is somehow causing this, I don't have much of an idea how. 

If you refresh the page, does it load any better the second time? Do you see this same problem with other browsers?

**Comment by chopetra** [comment]
chrome,firefox,edge,explorer all 4 browsers display same wrong result  
and after refreshing browser many times then display same wrong result in all 4 browsers 
 
블로그서명


 
-----Original Message-----

**Comment by gregg-miskelly** [comment]
@chopetra Thanks! We were able to track down the problem. This looks to be a bug in the sample itself, but we are looking at it.

**Comment by gregg-miskelly** [comment]
@chopetra I figured out what is wrong with the `dotnet new -t web` template. See https://github.com/dotnet/cli/issues/4076. I added a work around to the issue.
