### ISSUE TITLE
Do I need to install dotnet?

### ISSUE THREAD

**Issue by nojaf** [OmniSharp/omnisharp-vscode#669]
Sorry if this is the wrong place to ask.
I learning about Docker these days and I like the fact that you don't have to install anything to get up and running with a new technology.

Is it possible to download the vscode extension and not having to install dotnet cli tooling on my local machine? The dotnet cli is installed within the Docker container so can vscode use it from there?

**Comment by gregg-miskelly** [comment]
@nojaf You can use VS Code as an editor without a local CLI install, and if you are willing to do a lot more work you can get other things to work. But if you want things to be easy you will need `dotnet` on the path that VS Code is started from. You don't necessarily need to go through the installer, but obviously that makes things easier. Here is how `dotnet` is used --

1. Dotnet includes the ability to restore nuget packages, and that is how we acquire the debugger
2. While you are certainly free to build your code anyway you want, the default experience is to build your code locally, which isn't going to work without a local dotnet CLI.
3. This one is less required, but obviously if you want to run your code locally you will need the .NET CLI.

**Comment by nojaf** [comment]
Ok, thanks. I'll try and get this working.
Any chance some work will be done to streamline this process?
For example a project setting where you can tell vscode what container you are using.
```json
{
  "docker-container-name":"my-container"
}
```
If this setting is present package restore would try and execute:
```docker exec my-container dotnet restore```

**Comment by gregg-miskelly** [comment]
@nojaf I don't know much about the plans for the VS Code Docker tooling. @SteveLasker can you comment?

**Comment by filipw** [comment]
> Is it possible to download the vscode extension and not having to install dotnet cli tooling on my local machine

I think this is true going forward, as it will use desktop .net/embedded mono?

**Comment by DustinCampbell** [comment]
This issue looks pretty stale to me. I'm going to go ahead and close it. Please let me know if there are any concerns -- especially with regard to the Docker question which hasn't been answered (though it's now 6 months old).
