### ISSUE TITLE
IntelliSense - display <paramref /> without space

### ISSUE THREAD

**Issue by codehz** [OmniSharp/omnisharp-vscode#672]
## Environment data

`dotnet --info` output: 1.0.0-preview2-003121
VS Code version: 1.4.0
C# Extension version: 1.3.0
## Steps to reproduce
1. Copy and paste following code.

``` C#
using System;
namespace ConsoleApplication
{
    public class Program
    {
        ///<summary>
        ///<paramref name="args" /> test
        ///</summary>
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```
1. Move mouse to `Main` Function name, and IntelliSense will be displayed.
## Expected  behavior

![image](https://cloud.githubusercontent.com/assets/13158903/17740410/16b69b34-64cb-11e6-8a67-c5b99d3c8a9b.png)
## Actual behavior

![image](https://cloud.githubusercontent.com/assets/13158903/17740240/7c964fe0-64ca-11e6-8464-a766e25bbe2a.png)
![image](https://cloud.githubusercontent.com/assets/13158903/17740677/12bb5f32-64cc-11e6-988e-782781dc6d7b.png)

**Comment by DustinCampbell** [comment]
This has been fixed in OmniSharp (thanks @filipw) and the fix will appear in a future release of the C# extension.

**Comment by DustinCampbell** [comment]
I've created a [v1.6-beta2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.6-beta2) release of the C# extension that contains this fix, among others. See this page for information on [installing beta releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases)
