### ISSUE TITLE
Source files with absolute/relative paths outside of project do not show up in explorer

### ISSUE THREAD

**Issue by JoshEngebretson** [OmniSharp/omnisharp-vscode#694]
## Environment data
VS Code version: 1.4.0 
C# Extension version: 1.3.0

Source files with absolute or relative to csproj paths do not show up in explorer, though project compiles: 
```
	<ItemGroup>
		<Compile Include="Properties\AssemblyInfo.cs" />
		<Compile Include="..\..\..\..\Script\AtomicNET\AtomicNETService\AssemblyInspector.cs">
			<Link>AssemblyInspector.cs</Link>
		</Compile>
		<Compile Include="..\..\..\..\Script\AtomicNET\AtomicNETService\AtomicTools.cs">
			<Link>AtomicTools.cs</Link>
		</Compile>
		<Compile Include="..\..\..\..\Script\AtomicNET\AtomicNETService\CSComponentInspector.cs">
			<Link>CSComponentInspector.cs</Link>
		</Compile>
		<Compile Include="..\..\..\..\Script\AtomicNET\AtomicNETService\Program.cs">
			<Link>Program.cs</Link>
		</Compile>
	</ItemGroup>
```

**Comment by DustinCampbell** [comment]
This behavior is expected. Visual Studio Code doesn't provide a Solution Explorer like VS to show logical project structure. Instead, it shows a file system view rooted at the folder you open.

**Comment by JoshEngebretson** [comment]
Hopefully this changes with VSCode in the future, will have to stick with VS and Xamarin Studio in the meantime.  Thanks.
