### ISSUE TITLE
C# Linter?

### ISSUE THREAD

**Issue by alexandrudima** [OmniSharp/omnisharp-vscode#695]
Moved from Microsoft/vscode#10737

---

From @idchlife

Is there any way to have c# style guides suggesting proper styles? Newbie in c#. Will be very helpful!

I was just thinking is there way to enable c# linter for VSCode and if there is actually any linter rules for c# out there. Did not find any useful info on this, so guessing that c# does not have coding style guides for linter out there.

**Comment by DustinCampbell** [comment]
FWIW, since this question is more about C# and not necessarily the C# support in VS Code, it's probably better asked on the [Roslyn](https://github.com/dotnet/roslyn) repo.

**Comment by shanekenyon87** [comment]
I disagree, this is not a language feature question and Omnisharp certainly seems like the perfect place for this sort of functionality as it already has C# code formatting capabilities.  I guess the good news is that [Sonarlint](https://github.com/SonarSource/sonarlint-vscode) for VSCode is already pretty robust for JS and other languages and they are working towards language and feature parity with the Visual Studio version, which does support C# today.

**Comment by DustinCampbell** [comment]
@shanekenyon87 : Roslyn is not just a repo for the C# language and compiler, but also for IDE features. That is the right place to have that discussion.
