### ISSUE TITLE
Debugger shows wrong value of a C# property when hovered

### ISSUE THREAD

**Issue by anass-b** [OmniSharp/omnisharp-vscode#697]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

VS Code version: 1.4.0
C# Extension version: 1.3.0

![vscode_bug](https://cloud.githubusercontent.com/assets/8070594/17862599/40a10b04-6896-11e6-99d9-330a939f3ee2.png)

## Steps to reproduce
1. Create an empty .NET Core App
2. Use the code in the screenshot
3. Put a breakpoint after the line that says in a comment // Put breakpoint here
4. Hover on SomeProperty in the line if (someNumber > 1 || !someValue.SomeProperty)

## Expected  behavior
The given value should be `false`

## Actual behavior
The given value is `true`

I already filed this issue previously in VSCode repository https://github.com/Microsoft/vscode/issues/10580, the VSCode team investigated on it and found out that the issue is coming from the C# extension.

Thanks.

**Comment by chuckries** [comment]
I wonder if we are evaluating !someValue.SomeProperty, which evaluates to true.

**Comment by gregg-miskelly** [comment]
@anass-b the VS Code team apparently didn't investigate this deeply enough, as this is a VS Code issue. VS Code is asking to evaluate `!someValue.SomeProperty`. As Isidor mentioned though, we sent them a PR to fix their data tip code which should resolve this.
