### ISSUE TITLE
String with curly braces breaks C# highlighting

### ISSUE THREAD

**Issue by sandy081** [OmniSharp/omnisharp-vscode#702]
_From @kuulemart on August 23, 2016 5:9_

- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

When C# string contains curly braces then highlighting breaks down afterwards. Code example (see highlighting after first string in code):

namespace Test
{
    class Test
    {
        string Test1 = string.Format("{0}", 1);
        string Test2 = string.Format("{0}", 2);
    }
}

_Copied from original issue: Microsoft/vscode#10816_

**Comment by DustinCampbell** [comment]
Hi, this should already be fixed for the next release. You can verify it by installing the latest beta release from [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v.1.4.0-beta6).

![image](https://cloud.githubusercontent.com/assets/116161/17938742/227b26b8-69dc-11e6-8b2a-f5b84f5d53d7.png)

**Comment by DustinCampbell** [comment]
Note: this was fixed by the work to fix highlighting of C# 6 interpolated strings. #638

**Comment by DustinCampbell** [comment]
Do over. Try this beta release: (https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.4.0-beta5)

**Comment by kuulemart** [comment]
Yep, beta seems to be working fine.

Thanks!

Egon
