### ISSUE TITLE
Syntax highlighter shows XML comment tags incorrectly

### ISSUE THREAD

**Issue by FiniteReality** [OmniSharp/omnisharp-vscode#706]
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
```

VS Code version:

```
Version 1.4.0
Commit 6276dcb0ae497766056b4c09ea75be1d76a8b679
Date 2016-08-04T16:49:32.489Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```

C# Extension version: 1.3.0
## Steps to reproduce

Make an Enum (or any type for that matter) and place XML comments on the type, and some of the members.

For example:

``` cs
/// <summary> This is a test Enum </summary>
public enum TestEnum
{
    /// <summary> Test Value One </summary>
    TestValueOne = 0,
    /// <summary> Test Value Two </summary>
    TestValueTwo = 1
}
```
## Expected  behavior

The highlighter should highlight the `<summary>` tags using the same colour. (e.g. like GitHub's syntax highlighter does correctly)
## Actual behavior

They aren't:
![](http://i.imgur.com/DdEaO3C.png)

Upon removing part of the closing tag on the topmost XML comment, the inner comments appear to show correctly, though part of the type definition is highlighted incorrectly:

![](http://i.imgur.com/17lLcuB.png)

**Comment by pubwebmarketing** [comment]
°112.888.1.222*"

**Comment by DustinCampbell** [comment]
This should look much better in the next release:

![image](https://cloud.githubusercontent.com/assets/116161/21818344/4b686ba0-d71c-11e6-89c3-ab422eea7a24.png)
