### ISSUE TITLE
Debugger: Internal debug console can't work

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#711]
## Environment data
`dotnet --info` output:
VS Code version: 1.4.0
C# Extension version: v.1.4.0-beta7
.NET Core version: 1.0.0-SDK Preview2

## Steps to reproduce
1. Create a simple .NET Core project:
     using System;
     class Program
     {
           static void Main(string[] args)
          {    
               Console.WriteLine("Please input an integer:");
               int number = Console.Read();
              Console.WriteLine("Hello World");
         }
  }
2.Set "externalConsole" value is "false" and  "internalConsoleOptions" value is "openOnSessionStart" in launch.json file
3. Set a breakpoint at line of "Console.WriteLine("Hello World");" in program.cs file
4. Press F5 to start debugging
5. Input 1 in debug console
6. Press Enter

## Expected  behavior
The breakpoint should be hit.

## Actual behavior
The breakpoint can't be hit and show a message in debug console. Attached as below:
![debug console](https://cloud.githubusercontent.com/assets/20184778/17963736/88516764-6ae9-11e6-8e58-4b534afe0bf7.PNG)

**Comment by gregg-miskelly** [comment]
@GraceDong if you want to use APIs that read from the console you need to set --

    "externalConsole": true,

in your launch.json file.
