### ISSUE TITLE
ScriptCS support broken or working as expected?

### ISSUE THREAD

**Issue by HenrikPoulsen** [OmniSharp/omnisharp-vscode#712]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

VS Code version: 1.4.0
C# Extension version: 1.3.0

## Steps to reproduce
1. Create new folder
2. Create project.json with only {} in it
3. Create csx file and start coding

## Expected  behavior
This is the problem really, I can find no information about how it should actually work. If you google for "scriptcs intellisense" you find at least 2 blog posts showing that they get some pretty decent intellisense inside vscode for types it detects in referenced assemblies etc. If this is what you are supposed to get, well then it is broken for me. If that's not what one should expect then it would be nice if you would write somewhere what actually works currently in regards to scriptcs.

## Actual behavior
I get basically no help at all from the extension in regards to intellisense or anything.
![scriptcs](https://cloud.githubusercontent.com/assets/472627/17964063/9c0b9742-6ab8-11e6-9fcc-e7494aa127f3.PNG)

I have managed to get a C# project working with creating a new folder and running "dotnet new" in it and then loading that folder in VScode, then it works perfectly.
But scriptcs doesn't give much at all as you can see from the image. I can't find any documentation on your wiki of what the actual state of support is either and have to rely on random blogs on google showing what it at least used to support. So I don't know if this is a bug or expected behaviour.
However assuming it is a bug here is what the OmniSharp log shows for me in vscode:

```
[INFO] Starting OmniSharp at 'c:\redacted\Tools\Scripts\scriptcs'...
[INFO] Started OmniSharp from 'C:\Users\redacted\.vscode\extensions\ms-vscode.csharp-1.3.0\out\.omnisharp-coreclr\OmniSharp.exe' with process id 18320...
OmniSharp: -s c:\redacted\Tools\Scripts\scriptcs --hostPID 11048 DotNet:enablePackageRestore=false --stdio
[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location 'c:\redacted\Tools\Scripts\scriptcs' on host 11048.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in c:\redacted\Tools\Scripts\scriptcs
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update project c:\redacted\Tools\Scripts\scriptcs
[WARNING:OmniSharp.DotNet.DotNetProjectSystem] Cannot create any ProjectContext from project c:\redacted\Tools\Scripts\scriptcs
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp#MSBuild] No solution files found in 'c:\redacted\Tools\Scripts\scriptcs'
[INFORMATION:OmniSharp.Startup] Configuration finished.
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Must be able aggregate the response to spread them out across all plugins for /currentfilemembersastree
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 500 12ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Must be able aggregate the response to spread them out across all plugins for /updatebuffer
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 500 2ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Must be able aggregate the response to spread them out across all plugins for /currentfilemembersastree
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 500 0ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Must be able aggregate the response to spread them out across all plugins for /updatebuffer
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /updatebuffer: 500 0ms
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Must be able aggregate the response to spread them out across all plugins for /autocomplete
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 11ms
```
And it just continues on and on with these exceptions whenever I type something. And this is the same if I just do a minimal `Console.WriteLine("Hello World");` and nothing else in the file, exceptions for every keypress basically.

**Comment by DustinCampbell** [comment]
We've had an ask for CSX and ScriptCS support for a long while. I'm not sure when and if we'll get to this, but we're tracking it with #23.
