### ISSUE TITLE
C# 7.0 Syntax Highlighting

### ISSUE THREAD

**Issue by ivanz** [OmniSharp/omnisharp-vscode#728]
This issue track the support for syntax highlighting of C# 7.0 features: https://blogs.msdn.microsoft.com/dotnet/2016/08/24/whats-new-in-csharp-7-0/
- [ ] Constructor and destructor expression bodied
- [ ] Ref returns and locals
- [ ] Literals: `_` separator and binary literals (`0b1010_1011_1100_1101_1110_1111`)
- [ ] Local functions
- [ ] Tuples
- [ ] Switch statements with patterns
- [ ] `is`-expressions with patterns
- [ ] Out variables

There is high potential for regressions here and we should totally implement #696 first

**Comment by DustinCampbell** [comment]
This issue was moved to dotnet/csharp-tmLanguage#6

**Comment by aggieben** [comment]
I see that the issue was moved to dotnet/csharp-tmLanguage#6, but how does that relate back to support in omnisharp-vscode in terms of what is in a given release?

**Comment by DustinCampbell** [comment]
Actually, it doesn't really relate to omnisharp-vscode at all anymore. Starting with VS Code 1.10, the C# TextMate grammar is now included with VS Code and we're in the process of removing the grammar from this extension. That way, if you open a C# file in VS Code and don't have C# for VS Code installed, you'll still get colorization.

**Comment by aggieben** [comment]
ah, cool.
