### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by billmlab** [OmniSharp/omnisharp-vscode#729]
## Environment data
`dotnet --info` output:
Xis-MacBook-Pro:~ bill$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
Xis-MacBook-Pro:~ bill$ .NET Command Line Tools (1.0.0-preview2-003121)
-bash: syntax error near unexpected token `('
Xis-MacBook-Pro:~ bill$ 
Xis-MacBook-Pro:~ bill$ Product Information:
-bash: Product: command not found
Xis-MacBook-Pro:~ bill$  Version:            1.0.0-preview2-003121
-bash: Version:: command not found
Xis-MacBook-Pro:~ bill$  Commit SHA-1 hash:  1e9d529bc5
-bash: Commit: command not found
Xis-MacBook-Pro:~ bill$ 
Xis-MacBook-Pro:~ bill$ Runtime Environment:
-bash: Runtime: command not found
Xis-MacBook-Pro:~ bill$  OS Name:     Mac OS X
-bash: OS: command not found
Xis-MacBook-Pro:~ bill$  OS Version:  10.11
-bash: OS: command not found
Xis-MacBook-Pro:~ bill$  OS Platform: Darwin
-bash: OS: command not found
Xis-MacBook-Pro:~ bill$  RID:         osx.10.11-x64
-bash: RID:: command not found

VS Code version: Latest

C# Extension version: Latest

## Steps to reproduce
1. Simple C# file: 
using System;

public class Program
{
    static void Main()
    {
        Console.WriteLine("Hello, World!")
    }
}

And when I press F5, it first asked me to manually change the launch.json. And how?
Your instruction is so "simple", what program should I change to? I used the net core installer to install the compiler. Any suggestions?

## Expected  behavior
It should print out "Hello, World!"

## Actual behavior
Just errors!

**Comment by caslan** [comment]
1- Are you able to build and run the app from the console (i.e. outside VS Code)? I'm trying to understand if you have a valid and working installation of .NET Core.
2- Can you share the launch.json that is created when you open the project in VS Code?

**Comment by billchenxi** [comment]
Just need to mkdir <folder>
dotnet new

Then open the Code in this folder, then write new code in the program.cs. That's it.

**Comment by DustinCampbell** [comment]
@billchenxi is correct. You need a project to launch the debugger, which `dotnet new` will generate for you.

**Comment by caslan** [comment]
Closing the issue for now, please reactivate if it's still unresolved.
