### ISSUE TITLE
Same issue as debugging

### ISSUE THREAD

**Issue by billchenxi** [OmniSharp/omnisharp-vscode#730]
## Environment data
`dotnet --info` output:
Xis-MacBook-Pro:~ bill$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
Xis-MacBook-Pro:~ bill$ .NET Command Line Tools (1.0.0-preview2-003121)
-bash: syntax error near unexpected token `('
Xis-MacBook-Pro:~ bill$ 
Xis-MacBook-Pro:~ bill$ Product Information:
-bash: Product: command not found
Xis-MacBook-Pro:~ bill$  Version:            1.0.0-preview2-003121
-bash: Version:: command not found
Xis-MacBook-Pro:~ bill$  Commit SHA-1 hash:  1e9d529bc5
-bash: Commit: command not found
Xis-MacBook-Pro:~ bill$ 
Xis-MacBook-Pro:~ bill$ Runtime Environment:
-bash: Runtime: command not found
Xis-MacBook-Pro:~ bill$  OS Name:     Mac OS X
-bash: OS: command not found
Xis-MacBook-Pro:~ bill$  OS Version:  10.11
-bash: OS: command not found
Xis-MacBook-Pro:~ bill$  OS Platform: Darwin
-bash: OS: command not found
Xis-MacBook-Pro:~ bill$  RID:         osx.10.11-x64
-bash: RID:: command not found

VS Code version: Latest

C# Extension version: Latest

## Steps to reproduce
1. Simple C# file: 
using System;

public class Program
{
    static void Main()
    {
        Console.WriteLine("Hello, World!")
    }
}

And when I press F5, it first asked me to manually change the launch.json. And how?
Your instruction is so "simple", what program should I change to? I used the net core installer to install the compiler. Any suggestions?

## Expected  behavior
It should print out "Hello, World!"

## Actual behavior
Just errors!

**Comment by caslan** [comment]
1- Are you able to build and run the app from the console (i.e. outside VS Code)? I'm trying to understand if you have a valid and working installation of .NET Core.
2- Can you share the launch.json that is created when you open the project in VS Code?

**Comment by billchenxi** [comment]
I run the sample code, like dotnet new, then it was working. But I don't know how to use the Visual Studio Code for debugging.
############ launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/hello.cs",
            "args": [],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "externalConsole": false
        },
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/bin/Debug/<target-framework>/<project-name.dll>",
            "args": [],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceRoot}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command.pickProcess}"
        }
    ]
}

############### tasks.json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "dotnet",
    "isShellCommand": true,
    "args": [],
    "tasks": [
        {
            "taskName": "build",
            "args": [ ],
            "isBuildCommand": true,
            "showOutput": "silent",
            "problemMatcher": "$msCompile"
        }
    ]
}

**Comment by gregg-miskelly** [comment]
@billchenxi you set `program` to be a source file. That isn't what you want -- you want a built executable file (a dll file unless you are doing something fancy).

Here are the instructions: https://github.com/OmniSharp/omnisharp-vscode/blob/release/debugger.md

You can try deleting your launch.json file, and reopening your directory. If you do that you should see this prompt: https://github.com/OmniSharp/omnisharp-vscode/blob/release/debugger.md#3-add-vs-code-configuration-files-to-the-workspace and your launch.json should be setup correctly.

**Comment by billchenxi** [comment]
I figured out. I need to use command line to make a new project, then it will make everything right. It is so not intuitive. I was thought I can fully use the Code instead of command line.
