### ISSUE TITLE
c# code with #region, "" and / formatting issue

### ISSUE THREAD

**Issue by dbaeumer** [OmniSharp/omnisharp-vscode#731]
_From @ruchanb on August 29, 2016 11:57_
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

![image](https://cloud.githubusercontent.com/assets/11032047/18050645/97367156-6e0f-11e6-81fe-bbce94bd8000.png)

The formatting goes bad when the `#region` has `""` and `/` on it.

_Copied from original issue: Microsoft/vscode#11098_

**Comment by dbaeumer** [comment]
_From @ruchanb on August 29, 2016 12:2_

I think this issue is to be posted to csharp plugin provider

**Comment by DustinCampbell** [comment]
Thanks for forwarding @dbaeumer!

**Comment by ruchanb** [comment]
This issue is solved with the latest update 1.4.0.

**Comment by DustinCampbell** [comment]
This should look much better in the next release:

![image](https://cloud.githubusercontent.com/assets/116161/21745222/4ec105c0-d4db-11e6-8923-fce9959a89fe.png)
