### ISSUE TITLE
Debugger not showing correct decimal values

### ISSUE THREAD

**Issue by ruicraveiro** [OmniSharp/omnisharp-vscode#738]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version:
C# Extension version:
1.4.0

## Steps to reproduce
Create a simple class with a decimal property, instantiate that class, optionally assign a value to the property and checkout the value the debugger (variables and watch) shows for the property. It is different.

## Expected  behaviour
The value shown on the watch for the property should be the correct one.

## Actual behaviour
Debugger watch is showing wrong values. The value of the property itself is correct, though, because when the application actually uses it, the result is the expected.

![demo](https://cloud.githubusercontent.com/assets/8490712/18116884/124c4c42-6f43-11e6-8f72-490ca79393fd.png)

**Comment by gregg-miskelly** [comment]
This is due to https://github.com/dotnet/coreclr/issues/6935.

**Comment by gregg-miskelly** [comment]
The CoreCLR team has checked in a fix for their 1.1 release

**Comment by ruicraveiro** [comment]
Thanks for the feedback!
