### ISSUE TITLE
Unable to rename identifier using F2

### ISSUE THREAD

**Issue by lewisNotestine** [OmniSharp/omnisharp-vscode#744]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version:
Version 1.4.0 (1.4.0)

C# Extension version:
1.4.1

## Steps to reproduce
1. highlight an identifier
2. Press F2 to rename an identifier
3. rename the identifier to something else.

## Expected  behavior
Identifier gets renamed

## Actual behavior
Info message saying "server has been stopped or not started".  
looks like the proximal issue here is in Server.ts.

**Comment by DustinCampbell** [comment]
Thanks for touching base with us about this issue. Could you do the following for me? Once the informational message appears, select View->Output from the menu and then choose  "OmniSharp Log" from the combo box at the top-right of the Output panel. Copy and paste the content of the log here.

**Comment by DustinCampbell** [comment]
@lewisNotestine: Any update on this issue?

**Comment by lewisNotestine** [comment]
Apologies for the late response.

*embarrassed* I try to repro using the same steps today, and I cannot.
Will advise if I am able
to do so, but i guess this is a cannot-repro for now.

**Comment by DustinCampbell** [comment]
No worries -- I'm very glad to hear that it's not been a persistent issue for you.
