### ISSUE TITLE
[WARNING:OmniSharp#MSBuild] Skipped unsupported project type 'xyz.xproj' - causes intellisense to shut off

### ISSUE THREAD

**Issue by malachib** [OmniSharp/omnisharp-vscode#745]
## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version: 1.4.0
C# Extension version: 1.4.1

## Steps to reproduce

Point at a folder with .NET Core solution file with xproj's

## Expected  behavior

Ignore xproj's and use project.json files, functioning intellisense

## Actual behavior

Soft-aborts with a warning, zero intellisense available

**Comment by DustinCampbell** [comment]
Hi @malachib -- could you paste the full OmniSharp log here?

**Comment by malachib** [comment]
On a different MacBook with `dotnet --info` of `1.0.0-preview3-003180` everything works as expected.  Will try upgrading dotnet on the offending MacBook tomorrow when I have access to it and share the results.

**Comment by malachib** [comment]
On a different MacBook with `dotnet --info` of `1.0.0-preview3-003180` everything works as expected. Will try upgrading dotnet on the offending MacBook tomorrow when I have access to it and share the results.

**Comment by malachib** [comment]
Nevermind.  Pilot error.  I didn't get the memo one has to choose the particular project when opening at the global.json level.  Closing out the issue, thanks for your time!

**Comment by DustinCampbell** [comment]
Glad to hear this is working for you now!
