### ISSUE TITLE
Syntax highlighter broken on line with class inside string

### ISSUE THREAD

**Issue by swhaworth** [OmniSharp/omnisharp-vscode#746]
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64

VS Code version: 1.4.0
C# Extension version: 1.4.1
## Steps to reproduce

Create a new CS file, paste in the following content:

```
namespace X
{
    class Y
    {
        public MethodZ()
        {
            this.Writer.WriteLine("class CInput{0}Register : public {1}", index, baseClass);
        }
    }
}
```
## Expected  behavior

Syntax highlighting will set the string content as a single colour and after the string the highlighting will have correct colours for the variable names, etc.
## Actual behavior

The string content is using standard C# highlighting for class etc and goes back to the inside string highlighting after the second quote.

This used to work fine prior to C# extension version 1.4.0.

**Comment by DustinCampbell** [comment]
This will look much better in the next release:

![image](https://cloud.githubusercontent.com/assets/116161/21743668/b28ac43a-d4bb-11e6-8c35-67179480a1c8.png)
