### ISSUE TITLE
How do i  install this extension with a offline environment

### ISSUE THREAD

**Issue by John0King** [OmniSharp/omnisharp-vscode#747]
I work in a offline environment, How do I install this extension with full omnisharp feature (dotnet debuger and ominisharp Roslyn) ?

**Comment by gregg-miskelly** [comment]
I think this is what you want:

    git clone https://github.com/OmniSharp/omnisharp-vscode.git
    git checkout -b build v1.4.1 v1.4.1
    npm i
    node node_modules/gulp/bin/gulp.js package:offline

That will produce a bunch of platform-dependent .vsix files. You then copy the one you need to your computer and File->Open it from VS Code.

**Comment by John0King** [comment]
the .vsix file  iIcan download from the release channel,  but  how do I download **dotnet debuger** and **ominisharp roslyn** ?  And how do I configurate them ?

**Comment by gregg-miskelly** [comment]
`package:offline` will give you a different .vsix. The normal .vsix is platform neutral and has very little in it. The new .vsix is platform specific and has all the dependences built in.

In case you aren't aware, the other option: install the normal .vsix once (from the VS Code marketplace) and be online *once* while we download the debugger and omnisharp. From there on out you can be offline forever. I would definitely recommend this way unless the machine in question needs to be air gapped, or you are trying to do this to lots of machines all at once over a slow network. But obviously it is up to you.

**Comment by John0King** [comment]
my online compute is windows xp  
:(

**Comment by DustinCampbell** [comment]
@John0King: I'm not sure I follow why windows xp would be a blocker for you. The only prerequisite to doing what @gregg-miskelly suggests is having Node installed.

**Comment by gregg-miskelly** [comment]
@DustinCampbell the offline installer will use `dotnet restore` to acquire the debugger, and the .NET CLI will not install on Windows XP.

**Comment by DustinCampbell** [comment]
Oh of course. I'd forgotten about that.
