### ISSUE TITLE
Failed to start debugger on test because Error: Configured debug type 'coreclr' is not supported..

### ISSUE THREAD

**Issue by rucka** [OmniSharp/omnisharp-vscode#748]
## Environment data
`dotnet --info` output:

dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version:
C# Extension version:

## Steps to reproduce
1 - Wrote the test: 

        [Fact]
        public void FakeTest()
        {
            Assert.True(true);
        }

Click on "debug test" code lens in order to debug a single test

## Expected  behaviour
I can set a breakpoint to a test code line and the debugger stop at the breakpoint line

## Actual behaviour
The error: "Failed to start debugger on test because Error: Configured debug type 'coreclr' is not supported.." appairs on top error bar.

In addition I cannot set a breakpoint into the editor.

Note: 
That's the project.json

{
    "version": "1.0.0-*",
    "testRunner": "xunit",
    "dependencies": {
        "xunit": "2.2.0-beta2-build3300",
        "dotnet-test-xunit": "2.2.0-preview2-build1029",
        "Sgat.Engine": {
          "target": "project"
        }
    },
    "frameworks": {
        "netcoreapp1.0": {
            "dependencies": {
                "Microsoft.NETCore.App": {
                    "type": "platform",
                    "version": "1.0.0"
                }
            }
        }
    }
}

**Comment by chuckries** [comment]
Are you able to start debugging a new blank console application?
Create a new blank app:
```sh
mkdir ~/test
cd ~/test
dotnet new
dotnet restore
code .
```
Then click yes when prompted with "Required assets to build and debug are missing from your project. Add them?"
After the assets have been added, set a breakpoint in Program.cs and start debugging. Does this succeed?

**Comment by rucka** [comment]
Done, but I cannot able to set a breakpoint, and after start debugging the following error show:
`Configured debug type 'coreclr' is not supported.`
Is there a way to completely uninstall vscode and reinstall a clean instance?

**Comment by chuckries** [comment]
[This stackoverflow](http://stackoverflow.com/questions/29964126/visual-studio-code-on-mac) has some info. I would suggest moving the  VS Code app package to the trash as well as wiping out the settings as described in the stackoverflow post. Additionally, delete `~/.vscode/extensions/*` to cleanup all currently installed extensions.

With the error you are describing it sounds like VS Code does not understand that the C# extension is installed.

**Comment by rucka** [comment]
After deleted extensions and uninstall code, I can set breakpoint and start debugging sessions on a new clean vscode installation.
Thanks for the support!
Best Regards
Gianluca
