### ISSUE TITLE
Quote's not automatically being closed in c# files

### ISSUE THREAD

**Issue by Nokel81** [OmniSharp/omnisharp-vscode#749]
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version: 1.4.0
C# Extension version: (from mono) 4.4.2.11
## Steps to reproduce

In a files with the extension ".cs"
Type 'shift+" '
## Expected  behaviour

"$1", where $1 is the cursor
## Actual behaviour

"$1, where $1 is the cursor

In non-cs files (like a js file) this does work and no I do not have the closing-brace option set to false.

**Comment by Leopotam** [comment]
+1
auto closing pairs for " / ' characters should be enabled for "csharp" language in same way, as for js / ts.
