### ISSUE TITLE
Can't debug .Net Core web app

### ISSUE THREAD

**Issue by kcybul** [OmniSharp/omnisharp-vscode#750]
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version: 1.4
C# Extension version: 1.4.1
## Steps to reproduce

I only update VS Code and C# extension. After that I can't debug application by VS Code.
## Expected  behavior

Proper debug
## Actual behavior

1: (2000) STDERR:   Expected in: /Users/karol/.vscode/extensions/ms-vscode.csharp-1.4.1/coreclr-debug/debugAdapters/libmscordaccore.dylib
1: (2559) "/Users/karol/.vscode/extensions/ms-vscode.csharp-1.4.1/coreclr-debug/debugAdapters/clrdbg" exited with code 133 (0x85).
1: (2562) <-logout
E output: {"category":"telemetry","output":"VS/Diagnostics/Debugger/MIEngine/DebuggerAborted","data":{"VS.Diagnostics.Debugger.MIEngine.DebuggerName":"CLRDBG","VS.Diagnostics.Debugger.MIEngine.LastSentCommandName":"-exec-run","VS.Diagnostics.Debugger.MIEngine.DebuggerExitCode":"133 (0x85)","VS.Diagnostics.Debugger.clrdbg.Version":"15.0.25626.0 built by: PREVIEW.DBG2","VS.Diagnostics.Debugger.clrdbg.OSFamily":"Darwin","VS.Diagnostics.Debugger.clrdbg.KernelRelease":"15.6.0"},"type":"output"}
E output: {"category":"stderr","output":"ERROR: CLRDBG exited unexpectedly with exit code 133 (0x85). Debugging will now abort.\n","data":null,"type":"output"}
**## ERROR: CLRDBG exited unexpectedly with exit code 133 (0x85). Debugging will now abort.**
E output: {"category":"console","output":"The program '/Users/karol/Projects/candyandco/CandyAndCo/bin/Debug/netcoreapp1.0/CandyAndCo.dll' has exited with code -1 (0xffffffff).\r\n\n","data":null,"type":"output"}
The program '/Users/karol/Projects/candyandco/CandyAndCo/bin/Debug/netcoreapp1.0/CandyAndCo.dll' has exited with code -1 (0xffffffff).
E exited: {"exitCode":-1,"type":"exited"}
E terminated: {"type":"terminated"}
C disconnect: {"restart":false}
E output: {"category":"telemetry","output":"VS/Diagnostics/Debugger/DebugCompleted","data":{"VS.Diagnostics.Debugger.ImplementationName":"Microsoft.MIDebugEngine","VS.Diagnostics.Debugger.EngineVersion":"14.0.30822.1","VS.Diagnostics.Debugger.HostVersion":"1.0.20822.1","VS.Diagnostics.Debugger.AdapterId":"coreclr","VS.Diagnostics.Debugger.DebugCompleted.BreakCounter":0},"type":"output"}
 R: {"success":true,"message":null,"request_seq":5,"command":"disconnect","body":null,"running":false,"refs":null,"seq":0,"type":"response"}

**Comment by gregg-miskelly** [comment]
@kcybul if you try to run clrdbg on the command line, do you see anything else interesting printed to stdout/err?

    /Users/karol/.vscode/extensions/ms-vscode.csharp-1.4.1/coreclr-debug/debugAdapters/clrdbg --interpreter-mi
   -gdb-exit

**Comment by kcybul** [comment]
MacBook-Pro-Karol:debugAdapters karol$ pwd
/Users/karol/.vscode/extensions/ms-vscode.csharp-1.4.1/coreclr-debug/debugAdapters
MacBook-Pro-Karol:debugAdapters karol$ clrdbg --gdb-exit
-bash: clrdbg: command not found
MacBook-Pro-Karol:debugAdapters karol$

**Comment by chuckries** [comment]
Also, from that directory you will need to run `./clrdbg --interpreter=mi`.

**Comment by DustinCampbell** [comment]
@kcybul: Do you have any further information to provide here?

**Comment by kcybul** [comment]
@DustinCampbell No.

**Comment by DustinCampbell** [comment]
Were you able to get it working?

**Comment by kcybul** [comment]
@DustinCampbell No, but this is now old case, and I don't have this environment anymore.

**Comment by DustinCampbell** [comment]
OK, Thanks!
