### ISSUE TITLE
Syntax highlighting bug for fields

### ISSUE THREAD

**Issue by natemcmaster** [OmniSharp/omnisharp-vscode#757]
## Environment data

`dotnet --info` output: n/a
VS Code version: 1.5.2
C# Extension version:  1.4.1
## Steps to reproduce

```
public class Test
{
    public string _field1 = Path.Combine("",method());
    public string _field2 = Path.Combine("", method());
    public string _field3 = "";
}
```

![image](https://cloud.githubusercontent.com/assets/2696087/18524807/e015140c-7a6e-11e6-8a86-4d826aabc7aa.png)

Highlighter gets into an incorrect state trying to highlight `_field2`.

**Comment by DustinCampbell** [comment]
Interesting. :smile:. Usually the regular expressions fail at the starts/ends of tokens. cc @ivanz.

**Comment by ivanz** [comment]
Hmm I am not sure what's going on here, because the "variable" regex (https://github.com/OmniSharp/omnisharp-vscode/blob/master/syntaxes/csharp.json#L85) seems fine outside of the grammar file: http://regexr.com/3e9vo
