### ISSUE TITLE
Failure to get IntelliSense to work (no solution / project not on solution)

### ISSUE THREAD

**Issue by tritao** [OmniSharp/omnisharp-vscode#7570]
## Issue Description ##

I am just loading a simple csproj below, which references relative csprojs from CppSharp.

IntelliSense won't work and the using directives are not recognized as necessary.

![image](https://github.com/user-attachments/assets/41a30226-4454-4d19-8648-65136f44932c)

Project seems well loaded in the solution explorer:

![image](https://github.com/user-attachments/assets/64e8eb3a-3601-4932-a23f-bcc12ac54f57)

Active context seems correct as well:

![image](https://github.com/user-attachments/assets/fb094de4-5f9a-46ac-a35b-a37a198d59cd)

What could be the issue:

## Steps to Reproduce ##

This is my csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\tools\cppsharp\src\AST\CppSharp.AST.csproj" />
    <ProjectReference Include="..\..\tools\cppsharp\src\Core\CppSharp.csproj" />
    <ProjectReference Include="..\..\tools\cppsharp\src\CppParser\Bindings\CSharp\CppSharp.Parser.CSharp.csproj" />
    <ProjectReference Include="..\..\tools\cppsharp\src\Generator\CppSharp.Generator.csproj" />
    <ProjectReference Include="..\..\tools\cppsharp\src\Parser\CppSharp.Parser.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

## Logs ##

[output_logging_20240915T005141.zip](https://github.com/user-attachments/files/17004107/output_logging_20240915T005141.zip)

## Environment information ##

**VSCode version**: 1.92.2
**C# Extension**: 2.46.32
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.401
 Commit:            811edcc344
 Workload version:  8.0.400-manifests.b6724b7a
 MSBuild version:   17.11.4+37eb419ad

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  20.3
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/joao/.dotnet/sdk/8.0.401/

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.401 [/home/joao/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [/home/joao/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [/home/joao/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|csdevkit|ms-dotnettools|1.11.6|ms-dotnettools.csdevkit-1.11.6-linux-x64|
|csharp|ms-dotnettools|2.46.32|ms-dotnettools.csharp-2.46.32-linux-x64|
|vscode-dotnet-runtime|ms-dotnettools|2.1.5|ms-dotnettools.vscode-dotnet-runtime-2.1.5|;

</details>

**Comment by eqpoqpe** [comment]
C# Dev kit install specific version 1.9.55

**Comment by dibarbet** [comment]
@tritao would you be able to provide the project?  You can email me (dabarbet@microsoft.com and reference the issue number) if you would prefer.

Nothing from the logs is indicating anything obvious is going wrong unfortunately.

**Comment by kdcllc** [comment]
@dibarbet I am experiencing the same issue with IntelliSense with the following 

```
Version: 1.94.0-insider
Commit: c43f508b732d24b0c4732de9db2b38b4c5b88b8a
Date: 2024-09-26T05:04:07.935Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-45-generic
```

**Comment by dibarbet** [comment]
@kdcllc would you mind filing a new issue - and add some additional information?
1.  The 'C#' trace logs - see https://github.com/dotnet/vscode-csharp/blob/main/SUPPORT.md#collecting-general-logs for collecting them
2.  Verify the project is loading correctly, see https://github.com/dotnet/vscode-csharp/blob/main/SUPPORT.md#project-loading-problems

Usually these kinds of issues have very different causes and its easier for us if they're not mixed into the same issue

**Comment by dibarbet** [comment]
@tritao ah - yes C# Dev Kit will only load projects that are a part of the solution.  There are a couple of related issues on their end to allow projects outside of the solution to be loaded, e.g.
https://github.com/microsoft/vscode-dotnettools/issues/1165
https://github.com/microsoft/vscode-dotnettools/issues/588

This is also covered by a couple of issues on the C# standalone side
https://github.com/dotnet/vscode-csharp/issues/6008
https://github.com/dotnet/vscode-csharp/issues/5722

For now I would suggest ensuring that all projects you want to include are a part of the solution file.
