### ISSUE TITLE
Comments after preprocessor instructions are not syntax highlighted correctly

### ISSUE THREAD

**Issue by damieng** [OmniSharp/omnisharp-vscode#759]
## Environment data

VS Code version: 1.0.0-preview2-003131
C# Extension version: fbbf5a13ee1710779b3e337d3a48a0b812fd7b8f

## Steps to reproduce

```csharp
#if DEBUG // Should be a comment
```

## Expected  behavior

![image](https://cloud.githubusercontent.com/assets/118951/18601557/6aa3560e-7c5b-11e6-9e7f-2aab6b1574ac.png)

The comment should be syntax highlighted as a comment.

## Actual behavior

![image](https://cloud.githubusercontent.com/assets/118951/18601530/3e762cbe-7c5b-11e6-86b2-5fee70df86eb.png)

The comment is syntax highlighted as part of the preprocessor value.

**Comment by DustinCampbell** [comment]
Thanks for the report!
