### ISSUE TITLE
OmniSharp is not working on Fedora 23 or 24

### ISSUE THREAD

**Issue by r105m** [OmniSharp/omnisharp-vscode#761]
## Environment data
.NET Command Line Tools (1.0.0-preview3-003612)
Product Information:
 Version:            1.0.0-preview3-003612
 Commit SHA-1 hash:  b1c5cb76eb
Runtime Environment:
 OS Name:     fedora
 OS Version:  24
 OS Platform: Linux
 RID:         fedora.24-x64
VS Code version:
1.4, Версия 1.5.2
C# Extension version:
ms-vscode.csharp-1.4.1
## Steps to reproduce
1. download new aspnet project with YO
2. restore packages
3. open it

## Expected  behavior
omnisharp works correctly

## Actual behavior
1. vscode tries to restore packages every 1 minute
2. several messages like
 type or namespace Microsoft.AspNetCore.Mvc could not be found
 type or namespace System could not be found

autocompletion is not working

**Comment by DustinCampbell** [comment]
Currently, only Fedora 23 is supported.

**Comment by r105m** [comment]
DustinCampbell, specially for you i have reproduced this scenario on F23

**Comment by DustinCampbell** [comment]
I'm updating the title again. There are a few bugs with "OmniSharp is not working" as a title, and I'd like to keep these distinct so I can keep track while investigating.

**Comment by DustinCampbell** [comment]
There is a new beta of the C# extension available [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.5-beta3) that should address this problem. Feel free to try it out and let me know if it address the issue for you.
