### ISSUE TITLE
Enable c# object dump in debugger console from code

### ISSUE THREAD

**Issue by ghisguth** [OmniSharp/omnisharp-vscode#763]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version: 1.5.2
C# Extension version: 1.4.1

## Steps to reproduce

1. Install c# extension
2. Create .net core application
3. Write complex object to console
  1. `Console.WriteLine(new Dictionary<string, string>{{"foo", "bar"}});`
  2. `Debug.WriteLine(new Dictionary<string, string>{{"foo", "bar"}});`
  3.  `Console.WriteLine(Newtonsoft.Json.JsonConvert.SerializeObject(new Dictionary<string, string>{{"foo", "bar"}}));`
4. Run program
5. Inspect debugger console

## Expected  behavior

1. Debugger console contains object which can be interacted with. Same as if `new Dictionary<string, string>{{"foo", "bar"}}` would be executed in debugger console:
    
    Count = 1
    [0] [KeyValuePair]:{[foo, bar]}
    Raw View

## Actual behavior

1. Debugger console contains string representation of the object:  
   
    System.Collections.Generic.Dictionary`2[System.String,System.String]

    or

    {"foo":"bar"}

## Notes

LinqPad has extension method called Dump. It allows to render complex objects in form of tables. It would be great to have something similar in vs code. Yes, I can put breakpoint and manually dump object. But I want to be able to do that from code. So I can re-run program and instantly see complex object in debugger log. Don't really care what would be the method to dump objects. 

## VS Code comment

VS Code reported issue: https://github.com/Microsoft/vscode/issues/11854#issuecomment-248004408

The C# extension would need to return an object with a reference > 0 when the user evaluates an expression like this. Then vscode will display that the object can be expanded and on expansion ask for children from the debug adapter for the given reference.

**Comment by gregg-miskelly** [comment]
@ghisguth what you are asking for isn't possible. The debugger doesn't somehow hook Console.WriteLine or Debug.WriteLine. Instead, the .NET Framework implements these methods, translates the objects into a string (by calling ToString) and then sends the resulting string to the debugger (for Debug.WriteLine) or to stdout (for Console.WriteLine).

What I would probably suggest is making yourself a helper method that calls LinqPad.Dump, or similar.

**Comment by ghisguth** [comment]
Can debugger use reflection to hijack methods like Debug.Write()? 

What you suggests is not good approach. Linqpad is very powerful because of single .Dump() method. You can prototype some code and use single method to visualize it. It outputs it in html/active element which can be drilled down.

.NET supports only simple console output. It is not possible to hook it up with development tool. Only way - serialize data to some html or JSON and open browser or log JSON to console. But this is not useful. Hard to look at large objects.

webkit developer tools are pretty powerful. You can use console.log on JS objects and manipulate them in console. Seems like if you evaluate object in debugger console for c# it uses the same methods to visualize c# objects. Why can't we have the same level from code?

If you can't use refection and override implementation of .net objects you still can provide .net core library, which will do NOOP in runtime. But if it runs inside debugger it will hook up output to debugger console.

**Comment by ghisguth** [comment]
@gregg-miskelly Yes, I am talking exactly about this functionality. I want to be able to use C# code to achieve the same result. I want to be able to run program, see result, change something, run it again, see result. Iterate quickly. If I need to put breakpoint and evaluate expression, it takes not 5 seconds for making change and seeing result, but perhaps 30-40 seconds. Which makes inner loop too long.

**Comment by gregg-miskelly** [comment]
@ghisguth thanks for the explanation. I understand what you are asking for. If we ever did something like this, I don't think we would want to make a breaking change to an existing method. But one could possible imagine adding some new `Debugger.InspectObject` method. 

However, if your aim is to improve your productivity, I _think_ you will find that your proposal will not really help as much as you think --

* If you are talking about 30-40 seconds, I am imaging you are talking about a fairly slow cycle of building the program, and having the program start up. This time should be essentially the same if you are running under the debugger or not. If your project really starts up that much slower under the debugger, we would like to understand why.
* If the slowness you are worried about is in typing the expression into the debugger, you can always just assign the expression you want to evaluate to a temporary variable (see example below), set a breakpoint on the next line, and inspect the variable. If you just give the variable a short name (ex: `i` in my example, this should be nice and fast to type in. So your steps just become - tweak the query, hit F5 (to build your program and launch it), inspect `i`, repeat.
* Assuming that I am correct that you are trying to save yourself program build and startup time. We do have a feature which should eventually bring this -- edit and continue. Its a huge feature, so we don't yet support this for .NET Core, but it is something that I would expect us to eventually bring over. 

Example program:

```csharp
        public static void Main(string[] args)
        {
            var i = new Dictionary<string, string>{{"foo", "bar"}};
        } // set breakpoint here
```

**Comment by ghisguth** [comment]
@gregg-miskelly What I am looking for - very simple and out-of-the-box visualization. For complex projects I'm using VS + Resharper. But for small routine tasks I'm using linqpad. I write perhaps 20-30 new linqpad queries (small programs) every day.  Most of them are very simple. Something like - read data from disk, parse it somehow, group, display, perhaps save to disk. Most of the times I don't need any dependencies. So I open linqpad, write code in 30 seconds, perhaps 2 minutes. Run it few times to ensure I read and parse inputs correctly. It takes 30 seconds - to few minutes. Here visualization is crustal. Then I save data or copy report, close and delete query and forget about it. 

The tasks can be various. Few examples - update csproj automatically to remove some files by patters (which I don't want to do manually). Read tab separated file, filter rows, group by some column, save to other TSV file (visualization is important to ensure I parse it correctly and select proper data to save). Read complex object from azure blob storage, display all its properties. Read particular objects from object store, update some if needed and save them to azure store again.

I like VS code and would be glad to replace LinqPad with it if it would allow the same productivity. 

And it is important to display more than one object. So simple breakpoint won't be that useful. I would need to stop at various places in program and do manual work on printing variable in debugger console. 3 objects to dump - 3 stops, 3 times I need to type and press enter. And instead of getting results from program in <0.5 second, I will spend 10 seconds at least doing that. 

For example below one of programs I write on daily basis. I need to dump data on various stages. In this particular examples these are all strings. But in most cases objects are more complex. So normal write line won't work.

```csharp
var dataContext = new AzureDataContext();
		
dataContext.GetKeysAsync().Result.Dump();
		
foreach(var fileName in Directory.GetFiles(@"C:\tmp\stats\out\fixgz\")) {
	var name = Path.GetFileNameWithoutExtension(fileName);
	var content = File.ReadAllBytes(fileName);
	
	name.Dump("Name");
        content.Dump();
	
	dataContext.UploadAsync(name, content).Wait();
	dataContext.SetMetaDataAsync(name, new Dictionary<string, string>() {
		{"PROCESSED", DateTime.UtcNow.ToUniversalTime().ToString("o")},
		{"UPLOADED", DateTime.UtcNow.ToUniversalTime().ToString("o")}
	});
}
```

Any way would work Debugger.InspectObject will work. Or some object extension like this:

```csharp
void Main()
{
  "Test".DebugDump();
  (new Dictionary<string, string> { {"a", "b"}}).DebugDump();
}

static class Extensions {

  public static void DebugDump(this object value)
  {
    if (Debugger.IsAttached) {
      // Let the magic dump object in VS Code debugger console.
    }
    else {
      // NOOP
      // Or perhaps 
      Console.WriteLine(value?.ToString());
    }
  }
}
```
