### ISSUE TITLE
Update launch.json generation logic for MSBuild-based .NET Core

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-vscode#767]
The current launch.json generation logic needs to be updated to handle MSBuild-based .NET Core. Currently, it only runs on project.json. This requires a few things to happen:

- [x] OmniSharp needs to be updated to understand multiple target frameworks in .csproj ([example](https://github.com/dotnet/sdk/blob/8f09baf9b3c600d7df3495c6eb68814959b4bafb/TestAssets/TestProjects/CrossTargeting/DesktopAndNetStandard/DesktopAndNetStandard.csproj)) files using the latest MSBuild bits.
- [ ] The OmniSharp `/projects` end point needs to be updated to return information for multiple target frameworks (like it does for project.json projects).
- [x] The OmniSharp `/projects` end point needs to be updated to include output file path information.
- [x] The C# extension needs to be updated to a newer version of OmniSharp with the changes above.
- [ ] The launch.json/tasks.json generation logic needs tweaked to work for .csproj projects.

**Comment by nathanielcook** [comment]
I see this is marked as "in progress", which is exciting. Is it slated for 1.6 or 2.0? It will be pretty difficult for new users to get started with .NET Core/VS Code if they have to hand edit those json files to run HelloWorld.

**Comment by DustinCampbell** [comment]
It is currently slated for 1.6.
