### ISSUE TITLE
Detect which OmniSharp to launch (Mono or CoreCLR) for .csproj

### ISSUE THREAD

**Issue by DustinCampbell** [OmniSharp/omnisharp-vscode#769]
With .NET Core projects moving from project.json to .csproj, new logic will be required to determine whether the Mono or CoreCLR version of OmniSharp should be launched.
- Mono: .NET Framework or Unity projects
- CoreCLR: .NET Core projects

This is potentially tricky as its possible for a folder to be opened in VS Code that contains both sorts of projects.

**Comment by gregg-miskelly** [comment]
@DustinCampbell for PCL projects, do we want to use the .NET Core version? Or maybe look at the other projects in the directory and guess what is best?

**Comment by DustinCampbell** [comment]
I think we're going to need to poke around to figure out what's best. However, I can imagine several scenarios that are going to be really problematic. For example, an .sln file that contains some .csproj files that target desktop and some that target .NET Core.

**Comment by gregg-miskelly** [comment]
Yup. Will there be functional differences if the project really is a PCL (only references contract assemblies supported by both)?

**Comment by DustinCampbell** [comment]
Well, define "PCL". If you mean the old-style PCL, it'll need to be launched on desktop. :smile:

**Comment by gregg-miskelly** [comment]
The PCL projects that were created for VS 2015 which can target .NET Core and I believe recent versions of Mono also.

**Comment by DustinCampbell** [comment]
I'm starting consider moving fully to a Mono-based OmniSharp. I'm investigating mkbundle to see whether it might be viable.

**Comment by DustinCampbell** [comment]
This has been solved by using an embedded Mono runtime for OmniSharp. Now it's not necessary to detect which OmniSharp to launch. We only need to launch one.
