### ISSUE TITLE
GoToDefinition is not available in [metadata] files

### ISSUE THREAD

**Issue by chrmarti** [OmniSharp/omnisharp-vscode#771]
@Arnavion reported in Microsoft/vscode#12334:
- VSCode Version: 1.5.2
- OS Version: Windows 7 x64

Steps to Reproduce:
1. Have a C# project with the content:
   
   ``` cs
   class Foo
   {
       System.Collections.Generic.List<int> bar;
   }
   ```
2. Invoke <kbd>F12</kbd> `GoToDefinition` on `List` to be taken to the metadata file for `List`1` (`public class List<T> : IList<T>...`
3. In this file, `GoToDefinition` is not an option on `IList<T>` and pressing <kbd>F12</kbd> on it does nothing.

Other language service things like tooltips are also not available.

**Comment by gbrantzos** [comment]
Anything new about this? I still cannot see "GoToDefinition" for IList<T> on [metadata] List`1.
I use VS Code 1.13.1 and C# extension 1.11.0

**Comment by filipw** [comment]
@gbrantzos this feature was added to OmniSharp recently but the VS Code extension hasn't been updated yet to take advantage of that

**Comment by gbrantzos** [comment]
Glad to hear that! @filipw any clue of when to expect an updated version of VS Code extension?

**Comment by filipw** [comment]
@gbrantzos I just opened a PR here https://github.com/OmniSharp/omnisharp-vscode/pull/1620, now it's in @DustinCampbell's hands 😄
