### ISSUE TITLE
Highlighting inside constructor base call is broken

### ISSUE THREAD

**Issue by Tyriar** [OmniSharp/omnisharp-vscode#782]
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
```

VS Code version: 1.6.0-insiders
Theme: https://marketplace.visualstudio.com/items?itemName=Tyriar.theme-glacier
C# Extension version: 1.4.1
## Steps to reproduce

For code:

``` cs
public class A
{
    public A() : base(
            1,
            'abc'
            new B<char>(),
            new B<string>()) {
        var a = 1;
        var b = "abc";
        var c = new B<char>();
        var c = new B<string>();
    }
}
```
## Expected  behavior

The highlighting inside `base()` should be colored the same as outside it.
## Actual behavior

![image](https://cloud.githubusercontent.com/assets/2193314/18813302/a7a6e908-82aa-11e6-95ac-4a674d896a20.png)

**Comment by DustinCampbell** [comment]
Looks like we need another scope for constructor initializers.

**Comment by DustinCampbell** [comment]
This should be fixed in the next release:

![image](https://cloud.githubusercontent.com/assets/116161/21740194/d4bb2c0c-d466-11e6-8495-40346d9e672b.png)
