### ISSUE TITLE
CPU 100% and vscode host process even sticks around after closing vscode

### ISSUE THREAD

**Issue by eamodio** [OmniSharp/omnisharp-vscode#783]
## Environment data
`dotnet --info` output:
```
> dotnet --info
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
```
VS Code version: `Version 1.6.0-insider (1.6.0-insider)` be5e8d5733c1c012d7e3a6c7e049b59d67c13978 and `Version 1.5.3 (1.5.3)` 5be4091987a98e3870d89d630eb87be6d9bafd27
C# Extension version: `1.5.0-beta1` and `1.4.1`

Issue originally reported here: https://github.com/Microsoft/vscode/issues/12144#issuecomment-249472543

> @bpasero 
It happened again but only noticed it after I closed vscode and one of the processes stuck around.

> VSCode Version: d81ee41c51cae93a5cac967e42a28660a3a7e005
```
> ps aux | grep 15528
eric            15528  99.1  0.5  3298704  78112   ??  R    11:08PM  17:48.37 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper --nolazy --debug-brk=42110 /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap --type=extensionHost
eric            15591   0.0  0.7  4844016 111892   ??  S    11:08PM   0:16.88 /Users/eric/.vscode-insiders/extensions/ms-vscode.csharp-1.5.0-beta1/out/src/.omnisharp-coreclr/OmniSharp -s /Users/eric/Code/ion/faraday --hostPID 15528 DotNet:enablePackageRestore=false --encoding utf-8 --stdio
eric            18153   0.0  0.0  2451236   2132 s000  S+   11:30PM   0:00.00 grep 15528
```

> And just had it happen again this time with version 1.5.3 5be4091987a98e3870d89d630eb87be6d9bafd27
```
> ps aux | grep 16641
eric            16641  99.3  0.5  3264836  77380   ??  R    11:17PM  15:52.47 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --nolazy --debug-brk=24188 /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost
eric            18363   0.0  0.0  2451236   2132 s000  S+   11:34PM   0:00.00 grep 16641
eric            16697   0.0  0.5  4843696  87944   ??  S    11:18PM   0:28.46 /Users/eric/.vscode/extensions/ms-vscode.csharp-1.4.1/out/.omnisharp-coreclr/OmniSharp -s /Users/eric/Code/ion/faraday --hostPID 16641 DotNet:enablePackageRestore=false --encoding utf-8 --stdio
```

> Seems like OmniSharp in both cases

I haven't been able to figure out what triggers it, but I suspect it *may* be providing CodeLens to a large file (1400+ line) `cs` file -- although if it is, so far I haven't been able to repo it on demand.

**Comment by DustinCampbell** [comment]
Did this happen with previous versions of VS Code. If so, I doubt it's a problem with the C# extension or OmniSharp. Given the CPU usage above, it looks to be completely in the VS Code process. Neither the C# extension or OmniSharp processes show any activity.

**Comment by DustinCampbell** [comment]
Also, if you think it might be related to CodeLens, you could turn it off be changing the `editor.codeLens` setting to false.

**Comment by eamodio** [comment]
@DustinCampbell I'm closing this as I haven't had this happen in quite a while now.
