### ISSUE TITLE
Sort Usings

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-vscode#788]
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

```

VS Code version:1.5.3
C# Extension version:1.4.1
## Steps to reproduce

Create a file with lots of usings statement
## Expected  behavior

Intellisense to offer "Sort Usings"
## Actual behavior

Nothing

**Comment by Leopotam** [comment]
For temporaty workaround you can use Uncrustify plugin with proper config option for using sorting.

**Comment by Leopotam** [comment]
[Extension for fix usings order](https://marketplace.visualstudio.com/items?itemName=Leopotam.csharpfixformat)

**Comment by rchande** [comment]
@akshita31 Can figure out if sorting usings is a public API of Roslyn? If it is, we could go ahead and add a command to do this. (I bet we could also add a command that removes the unused ones)

**Comment by DustinCampbell** [comment]
@rchande : I don't believe we've exposed these as public APIs yet.

**Comment by cuibty** [comment]
+1

**Comment by Siccity** [comment]
+1

**Comment by filipw** [comment]
This is already implemented as part of formatting, see release notes here https://github.com/OmniSharp/omnisharp-roslyn/blob/master/CHANGELOG.md#13410---2020-01-27

it's not enabled by default so needs to be enabled with `omnisharp.json` file (global or local https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#global-omnisharpjson)

see also the blog post for more info https://www.strathweb.com/2020/02/hidden-features-of-omnisharp-and-c-extension-for-vs-code/#toc_4

**Comment by filipw** [comment]
I will close this based on the above comment ^
