### ISSUE TITLE
--configfile not recognized

### ISSUE THREAD

**Issue by pflannery** [OmniSharp/omnisharp-vscode#80]
```
Downloading and configuring the .NET Core Debugger...
Running C:\Program Files\dotnet\bin\corerun.exe "C:\Program Files\dotnet\bin\NuGet.CommandLine.XPlat.dll" "restore" "--runtime" "win7-x86" "--runtime" "win7-x64" "--configfile" "NuGet.config"
Process ID: 684
Specify --help for a list of available options and commands.
error: Unrecognized option '--configfile'
dotnet exited with error code 1
Error while installing .NET Core Debugger.
```

```
dotnet --version

.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

**Comment by chuckries** [comment]
@pflannery Thanks for the issue!

1. Is this the latest .NET Core install from [here](https://dotnet.github.io/getting-started/)?
2. Have you had previous versions of .NET Core installed on the box? Did you do a full uninstall before installing a new version?

**Comment by pflannery** [comment]
@chuckries yes

![image](https://cloud.githubusercontent.com/assets/1727302/13716451/0b7620b6-e7d3-11e5-8e2a-420f190a6f2b.png)

**Comment by pflannery** [comment]
> Have you had previous versions of .NET Core installed on the box? Did you do a full uninstall before installing a new version?

will try that now

**Comment by pflannery** [comment]
@chuckries Working now!. Seems I had two dotnet's installed. So uninstalled both and restarted computer. thanks

**Comment by chuckries** [comment]
np, glad it works!
