### ISSUE TITLE
Getting error: "Failed to make the following project runnable: dummy (.NETCoreApp,Version=v1.0) reason: Access to the path 'C:\Users\imgen\.vscode\extensions\ms-vscode.csharp-1.4.1\coreclr-debug\bin\Debug\netcoreapp1.0\win7-x64\1033\VSDebugUI.dll' is denied" when try to debug .NET Core project

### ISSUE THREAD

**Issue by imgen** [OmniSharp/omnisharp-vscode#800]
## Environment data

`dotnet --info` output:
VS Code version:
C# Extension version:
1.4.1
## Steps to reproduce

Create a .NET Core project, try to debug it
## Expected  behavior

Start the debugger
## Actual behavior

There is a message pop up saying "Error while installing .NET Core Debugger." and when I look at the log, it says 

Creating C:\Users\imgen.vscode\extensions\ms-vscode.csharp-1.4.1\coreclr-debug\project.json
Telemetry is: Enabled
log  : Restoring packages for C:\Users\imgen.vscode\extensions\ms-vscode.csharp-1.4.1\coreclr-debug\project.json...
log  : Lock file has not changed. Skipping lock file write. Path: C:\Users\imgen.vscode\extensions\ms-vscode.csharp-1.4.1\coreclr-debug\project.lock.json
log  : C:\Users\imgen.vscode\extensions\ms-vscode.csharp-1.4.1\coreclr-debug\project.json
log  : Restore completed in 1691ms.
Telemetry is: Enabled
Publishing dummy for .NETCoreApp,Version=v1.0/win7-x64
Project dummy (.NETCoreApp,Version=v1.0) will be compiled because inputs were modified
    C:\Users\imgen.vscode\extensions\ms-vscode.csharp-1.4.1\coreclr-debug\project.json
Compiling dummy for .NETCoreApp,Version=v1.0
Running C:\Program Files\dotnet\dotnet.exe "C:\Program Files\dotnet\sdk\1.0.0-preview2-003131\csc.dll" -noconfig @C:\Users\imgen.vscode\extensions\ms-vscode.csharp-1.4.1\coreclr-debug\obj\Debug\netcoreapp1.0\dotnet-compile-csc.rsp
Process ID: 6028

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:03.6262271
Failed to make the following project runnable: dummy (.NETCoreApp,Version=v1.0) reason: Access to the path 'C:\Users\imgen.vscode\extensions\ms-vscode.csharp-1.4.1\coreclr-debug\bin\Debug\netcoreapp1.0\win7-x64\1033\VSDebugUI.dll' is denied.
Published 0/1 projects successfully
dotnet exited with error code 1

It's really really frustrating, it took me 1 hour to try to fix, but to no avail. The file "VSDebugUI.dll" exists but it's just not accessiable

**Comment by imgen** [comment]
The OS is Windows 10, I am running VS Code Stable version 1.5.3, Windows 10 14936 64bit in Mac OS Paralles VM. 
I have another machine with the same OS, same VS Code version and it works flawlessly, I really don't know what happened. Also I tried on Mac itself, it also worked fine.

**Comment by imgen** [comment]
I tried to install VS Code Insiders edition and then install the C# extension without any other extensions at all, the odd thing is that it has the same error. Also upon installation, there is an error below while installing .NET Core Debugger

Publishing file System.Collections.Concurrent.dll to C:\Users\imgen\.vscode-insiders\extensions\ms-vscode.csharp-1.4.1\coreclr-debug\debugAdapters
publish: Publishing System.Collections.Immutable 1.2.0 ...
Publishing file System.Collections.Immutable.dll to C:\Users\imgen\.vscode-insiders\extensions\ms-vscode.csharp-1.4.1\coreclr-debug\debugAdapters
Access to the path 'C:\Users\imgen\.vscode-insiders\extensions\ms-vscode.csharp-1.4.1\coreclr-debug\debugAdapters\System.Collections.Immutable.dll' is denied.
System.UnauthorizedAccessException: Access to the path 'C:\Users\imgen\.vscode-insiders\extensions\ms-vscode.csharp-1.4.1\coreclr-debug\debugAdapters\System.Collections.Immutable.dll' is denied.
   at System.IO.Win32FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.PublishAssetGroups(IEnumerable`1 groups, String outputPath, Boolean nativeSubdirectories, Boolean includeRuntimeGroups)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.PublishProjectContext(ProjectContext context, String buildBasePath, String outputPath, String configuration, Boolean nativeSubdirectories)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.PublishAllProjects()
   at Microsoft.DotNet.Tools.Publish.PublishCommand.<>c__DisplayClass0_0.<Run>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.Run(String[] args)
dotnet exited with error code 1

The odd thing is that the file "System.Collections.Immutable.dll" already there, it's every bit accessible.

**Comment by imgen** [comment]
Anyway, I copied the files of the C# extension from the OK system to the system that's having issue, now everything works fine now. Still don't know why it's having issue in the first place though

**Comment by gregg-miskelly** [comment]
@imgen interesting. Do you have some sort of antivirus program?

**Comment by philipanzelmo45** [comment]
Huuuu wattts

**Comment by gregg-miskelly** [comment]
For 1.5 of the C# extension we are no longer using the .NET CLI to acquire the debugger. So this issue should no longer be relevant.
