### ISSUE TITLE
Omnisharp is stuck at starting phase with nothing happening

### ISSUE THREAD

**Issue by narf** [OmniSharp/omnisharp-vscode#804]
This is probable more of an omnisharp error, but I post the problem here you guys probably know better what to do with this.

## Environment data
`dotnet --info` output:

> .NET Command Line Tools (1.0.0-preview2-003131)
> 
> Product Information:
>  Version:            1.0.0-preview2-003131
>  Commit SHA-1 hash:  635cf40e58
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  16.04
>  OS Platform: Linux
>  RID:         ubuntu.16.04-x64

VS Code version: 1.5.3
C# Extension version: 1.4.1
## Steps to reproduce
Try to install on linux with mono flavour and a mono version <4.0.1 (or maybe no mono installed)

## Expected  behavior
An error should be displayed

> Cannot start Omnisharp because Mono version >=4.0.1 is required.

## Actual behavior
No error is displayed, the omnisharp server just hang on startup stage

> Starting OmniSharp server at 10/8/2016, 7:02:23 PM
>     Target: /blah/blah/blah/blah.sln

## How to fix
in out/omnisharp/launcher.js change 

```javascript
// Original code
function launchNixMono(details) {
    return new Promise(function (resolve, reject) {
        return canLaunchMono().then(function () {
            var args = details.args.slice(0); // create copy of details.args
            args.unshift(details.serverPath);
            var process = child_process_1.spawn('mono', args, {
                detached: false,
                cwd: details.cwd
            });
            return resolve({
                process: process,
                command: details.serverPath,
                usingMono: true
            });
        });
    });
}
```

to

```javascript
// Fixed code
function launchNixMono(details) {
    return new Promise(function (resolve, reject) {
        canLaunchMono().then(function () {
            var args = details.args.slice(0); // create copy of details.args
            args.unshift(details.serverPath);
            var process = child_process_1.spawn('mono', args, {
                detached: false,
                cwd: details.cwd
            });
            resolve({
                process: process,
                command: details.serverPath,
                usingMono: true
            });
        }, reject);
    });
}
```
Why are they returning a promise in a promise? I think this is not how es6 Promise works, the callback of the new Promise thing should not return anything. The whole code return things inside its callback it would probably be better to rewrite them.

**Comment by matthamil** [comment]
The original code should be fine. In your example, 

```javascript
function launchNixMono(details) {
    return new Promise(function (resolve, reject) {
        canLaunchMono().then(function () {
            var args = details.args.slice(0); // create copy of details.args
            args.unshift(details.serverPath);
            var process = child_process_1.spawn('mono', args, {
                detached: false,
                cwd: details.cwd
            });
            resolve({
                process: process,
                command: details.serverPath,
                usingMono: true
            });
        }, reject);
    });
}
```
the call to `canLaunchMono()` would fire, and the code dependent upon `launchNixMono` may or may not happen after `canLaunchMono()` completes. By returning `canLaunchMono()`, this guarantees that the code will wait for `canLaunchMono()` to complete (or fail) before continuing. This also allows you to call `.then()` and `.catch()` on `launchNixMono` elsewhere and expect that the `canLaunchMono` has resolved (or failed). The code should be fine as is.

**Comment by narf** [comment]
I think you are wrong, returning the call to canLaunchMono inside the Promise executor has no effect there since we already returned `new Promise(...)` from launchNixMono.
This mean that async termination of the launchNixMono task is handled by resolve/reject callbacks.

You can see thereafter in the code you quoted that every path is calling either resolve or reject and thus the async termination is fully handled which was not the case in the original code.

And I repeat, returning inside a Promise executor (the callback inside the `new Promise(executor)`) has no effect (I tested it).

**Comment by matthamil** [comment]
Ah, I think you are right @narf . My apologies. Thanks for the opportunity to learn :)

**Comment by DustinCampbell** [comment]
yeah, this is totally a bug. I don't know what I was thinking when I wrote that. :smile:

**Comment by DustinCampbell** [comment]
Sometimes I'll return a `resolve` or `reject` to simplify control flow in a more complex promise. This is totally unnecessary here though.

**Comment by DustinCampbell** [comment]
FWIW, it's not clear to me that this would fix your issue based on the information that you provided. The C# extension does not use Mono by default on ubuntu 16.04. Instead, it will use the Ubuntu 16.04 flavor of OmniSharp, which is a standalone .NET Core app. @narf, did you verify that this actually fixes your problem?

**Comment by narf** [comment]
This fixed the problem of the error not showing ^^
But I'm still fighting to get c# working on vscode ubuntu for my unity project, if you have any hints on were to look I'll be glad to hear from you :)
I installed latest version of mono, because the error said so, and the omnisharp server started correctly but nothing was recognized. I had lot of error on System.Object and lot of other basic stuff not being recognized. It was probably my project settings that were off.

Still looking for it but I'm not sure that it is an omnisharp problem.

**Comment by DustinCampbell** [comment]
I've looked through all of the launch code, and I don't think the right fix is quite what you suggest. 

* First, the promises in launcher.ts all need cleaned up. There's a lot of unnecessary junk in there.
* Then, there should be a `catch` at the end of promise chain [here](https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/omnisharp/server.ts#L300-L306).

Could you take a quick look at #807? I'm curious to know whether this addresses your scenario by properly allowing rejections and thrown exceptions to bubble up and properly cancel the server launch.

**Comment by DustinCampbell** [comment]
There is a new beta of the C# extension available [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.5-beta3) that should address this problem. Feel free to try it out and let me know if it address the issue for you.
