### ISSUE TITLE
Debugging with Xunit throws an error.

### ISSUE THREAD

**Issue by robvanpamel** [OmniSharp/omnisharp-vscode#808]
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
```

VS Code version:

```
Version 1.6.0
Commit e52fb0bc87e6f5c8f144e172639891d8d8c9aa55
Date 2016-10-10T18:30:01.819Z
Shell 1.3.7
Renderer 52.0.2743.82
Node 6.5.0

```
C# Extension version: 1.5.0-beta2

When trying to debug a unit test an exception is thrown. When running the test via dotnet test the test are executed correctly. Maybe there is something wrong with my Tasks file. 

## Steps to reproduce
Create a unit test and press the 'debug test' button provided by OmniSharp. 

## Expected  behavior
The test is executed in Debug mode. 

## Actual behavior
An exception is thrown : 

dotnet-test Error: 0 : System.IO.InvalidDataException: Found invalid data while decoding.
   at System.IO.StringParser.ParseNextChar()
   at Interop.procfs.TryParseStatFile(String statFilePath, ParsedStat& result, ReusableTextReader reusableReader)
   at System.Diagnostics.ProcessManager.CreateProcessInfo(ParsedStat procFsStat, ReusableTextReader reusableReader)
   at System.Diagnostics.ProcessManager.CreateProcessInfo(Int32 pid, ReusableTextReader reusableReader)
   at System.Diagnostics.ProcessManager.GetProcessInfos(String machineName)
   at System.Diagnostics.Process.GetProcesses(String machineName)
   at System.Diagnostics.Process.GetProcesses()
   at Microsoft.DotNet.Tools.Test.TestCommand.RegisterForParentProcessExit(Int32 id)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)

As reference i'm adding my Tasks.json file: 
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "dotnet",
    "isShellCommand": true,
    "args": [
        
    ],
    "tasks": [
        {
            "taskName": "build",
            "args": [ 
                "${workspaceRoot}/src/SAG.NextGen.Owl",
                "${workspaceRoot}/test/SAG.NextGen.Owl.UnitTests"        
            ],
            "isBuildCommand": true,
            "showOutput": "silent",
            "problemMatcher": "$msCompile"
        },
         {
            "taskName": "test",      
            "showOutput": "always",      
            "args":[
                "${workspaceRoot}/test/SAG.NextGen.Owl.UnitTests" 
            ],
            "isTestCommand": true
        }
    ]
}

**Comment by gregg-miskelly** [comment]
@robvanpamel this looks to me like what is happening is that one of your processes has a file under /proc/<pid> that [CoreFX's parsing code](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/Common/src/Interop/Linux/procfs/Interop.ProcFsStat.cs#L222) doesn't like, and this causes the whole process listing to fail. This seems like a CoreFX issue to me. If you have a regular repro, would you mind opening the bug at https://github.com/dotnet/corefx/issues?

**Comment by robvanpamel** [comment]
@gregg-miskelly 
Okay for me to move it to CoreFX, but can't you just move the issue to there? I have no other way to reproduce it then creating a regular unit test and try to debug it...?

**Comment by gregg-miskelly** [comment]
@robvanpamel I did my best to port it.
