### ISSUE TITLE
Intellisense: Auto complete type after new keyword

### ISSUE THREAD

**Issue by andy-wood** [OmniSharp/omnisharp-vscode#809]
## Environment data
`dotnet --info` output: 1.0.0-preview3-003786
VS Code version: 1.6.0
C# Extension version: 1.4.1

## Steps to reproduce
Type the following, then space: int[] a = new

## Expected  behavior
Type is auto completed after the new keyword

## Actual behavior
No auto complete

**Comment by DustinCampbell** [comment]
Thanks for the request -- this is a duplicate of #146.
