### ISSUE TITLE
Error with dotnet restore Mac OS X, ASP.NET Core

### ISSUE THREAD

**Issue by mchomer** [OmniSharp/omnisharp-vscode#81]
Hello,

I want to use the experimental .NET Core Debugger in my ASP.NET Core project, but after
 dotnet restore 
I get the following error:

project.json
    Microsoft.Win32.Registry 4.0.0-rc3-23909 provides a compile-time reference assembly for Microsoft.Win32.Registry on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
    Some packages are not compatible with DNXCore,Version=v5.0 (ox.10.11-x64).

The project.json is:
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "tooling": {
    "defaultNamespace": "mchomerBlog"
  },
  "dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework7.Npgsql": "3.1.0-rc1-3",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.AspNet.Session": "1.0.0-rc1-final",
    "Microsoft.AspNet.Http": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.Dnx.Watcher": "1.0.0-rc1-final",
    "Newtonsoft.Json": "8.0.2",
    "Microsoft.jQuery.Unobtrusive.Validation": "3.2.3"
  },
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel --ASPNET_ENV development",
    "ef": "EntityFramework.Commands"
  },
  "frameworks": {
    "dnx451": {},
    "dnxcore50": {
        "dependencies": {
            "NETStandard.Library":"1.0.0-rc3-*"
        },
        "imports": "portable-net45+win8"
    }
  },
  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [
      "npm install",
      "bower install",
      "gulp clean",
      "gulp min"
    ]
  }
}

**Comment by DustinCampbell** [comment]
Hi -- do you get this error when running "dotnet restore" at the command line? If so, this issue should probably be filed over on http://github.com/dotnet/cli. However, it sounds to me like this is expected.

**Comment by gregg-miskelly** [comment]
You might want to checkout the ASP.NET CLI samples on https://github.com/caslan/cli-samples. We aren't ASP.NET experts, but my guess is that you are going to need to change the version of some of those ASP.NET packages to make them play nice with the CLI and newer CoreCLR.

If that doesn't help, I would definitely agree with Dustin that the CLI folks are more likely to be able to help. The ASP.NET folks might be even better though. I can't say for sure which repo to use, but it looks like there are issues in https://github.com/aspnet/home

I hope this helps and thanks for trying!
Gregg

**Comment by mchomer** [comment]
@DustinCampbell 
@gregg-miskelly 


Thank you for your help. Just tried a little bit more on saturday, but didn't reached something.
Even the cli-sampels did not work.
I will post my question in the asp.net-section.

**Comment by DustinCampbell** [comment]
Thanks @mchomer -- please let us know if you're unable to resolve this. I'll close this issue for now.
