### ISSUE TITLE
onWillSaveTextDocument implementation for VSCode

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-vscode#810]
As of VSCode 1.6, there is an API for `onWillSaveTextDocument` that allows formatting of documents when the save is triggered. See here https://twitter.com/ErichGamma/status/785592894468001792 via @egamma .

Are there plans for Omnisharp to support this?

**Comment by DustinCampbell** [comment]
Eventually, yes! :smile:

**Comment by egamma** [comment]
(I wasn't fully accurate on Twitter)
An extension that has a formatter (which is true for OmniSharp) should get this feature for free. All you need to do is to set `"editor.formatOnSave": true`. 

@jchannon did you try this and it didn't work?

**Comment by jchannon** [comment]
Ah cool so this does work but oddly.

I have this

```
"files.autoSave": "afterDelay",
"files.autoSaveDelay": 1100,
 "editor.formatOnSave": true
```

When it auto saves it doesn't format, if I'm quick and make and edit and
manually save it will format

**Comment by egamma** [comment]
> When it auto saves it doesn't format, if I'm quick and make and edit and manually save it will format

@jchannon we want to improve this so that a manual save behaves deterministically and always triggers a format. 

If you want to format on save but also auto save, then I suggest to use
```json
"files.autoSave": "onFocusChange"
```

Bottom line there is now work for @DustinCampbell and I suggest to close this issue.

**Comment by DustinCampbell** [comment]
Thanks @egamma!
