### ISSUE TITLE
Unable to watch variables in VS Code when

### ISSUE THREAD

**Issue by djbreen7** [OmniSharp/omnisharp-vscode#814]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003131)

**Product Information:**
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

**Runtime Environment:**
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
VS Code version: 1.6.0
C# Extension version: 1.4.1

## Steps to reproduce
1. Create a new csharp project
2. Create a variable of any type (int, string, double, ...)
3. Add a breakpoint with the debugger
4. Start the dubugger
5. Add your variable to watch 

## Expected  behavior:
The variables being watched should be undefined, null, or non-existent until initialized, then have the value assigned to them.

## Actual behavior

Error CS1525: Invalid expression term ''[term]"
![capture](https://cloud.githubusercontent.com/assets/13296622/19316125/7ceec116-905d-11e6-8b24-a9db8693eaf4.PNG)
![capture2](https://cloud.githubusercontent.com/assets/13296622/19316126/7d321330-905d-11e6-8cd0-8f6d7c86b990.PNG)

**Comment by gregg-miskelly** [comment]
@djbreen7 it looks like you might be trying to evaluate `num [int]` is that correct? If so the issue is that you want to evaluate `num` and NOT `num [int]`. The ` [int]` suffix is just how we display types in VS Code since VS Code doesn't have a type column.

**Comment by djbreen7** [comment]
@gregg-miskelly: Forgive me if this question is obvious. I'm new to debugging and also C#. I don't see a way to watch `num` then if `num` and `num [int]` are two separate things. In my locals, only `num [int]` and the Main method arguments are available.

Apologies if you feel this is irrelevant to the issue and more of a google question. I appreciate the feature very much.

**Comment by gregg-miskelly** [comment]
@djbreen7 happy to help. Click the little '+' to add a new expression to the watch window, and type in `num`:

![addwatch](https://cloud.githubusercontent.com/assets/11078489/19364337/971b4682-9142-11e6-8a51-d3c46bc23f32.png)

**Comment by djbreen7** [comment]
👍

**Comment by gregg-miskelly** [comment]
Glad to help. BTW: I opened https://github.com/OmniSharp/omnisharp-vscode/issues/819 to track the fact that 'Add to Watch' doesn't work.
