### ISSUE TITLE
'var' inside foreach not highlighted

### ISSUE THREAD

**Issue by jtzeng** [OmniSharp/omnisharp-vscode#816]
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

VS Code version: 1.6.0
C# Extension version: 1.4.1
## Steps to reproduce

Write a foreach loop anywhere, e.g.
`foreach (var s in myList)
{
   ...
}`
## Expected  behavior

'var' should be colored, like it is when you write something like
`foreach (string s in myList)
{
   ...
}`
## Actual behavior

It isn't, and appears as white.

**Comment by DustinCampbell** [comment]
This should look much better in the next release:

![image](https://cloud.githubusercontent.com/assets/116161/21823689/194e6a1a-d731-11e6-841c-f10d3033e1a9.png)
