### ISSUE TITLE
No feedback if downloading .NET Core Debugger fails

### ISSUE THREAD

**Issue by kylenoteboom** [OmniSharp/omnisharp-vscode#818]
## Environment data

`dotnet --info` output:

```
dotnet --info
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch.-x64
```

VS Code version:
`1.6.0
C# Extension version:
both git and 1.4.1
## Steps to reproduce

Install the extension, download the .NET Core Debugger on an unsupported (Linux) platform.
## Expected  behavior

Any feedback that it's trying to do something.
## Actual behavior

There's an error in coreclr-debug/install.log.

Would be great to get some feedback, right now if I had not read up on things I would've thought it succeeded, only to be disappointed when trying to debug a project.

Which gets me to my real problem: how do I compile and use the changes I've made to the extension? I've edited `platform.ts` to add support for Arch by adding the following case to the `id` switch:

```
            case 'arch':
                return Platform.Fedora;
```

But how do I actually compile the extension and run it? The `README.md` in the repository root tells me to run `npm i`, which appears to install it in the repository folder. I've tried moving that to `~/.vscode/extensions/` but downloading the Debugger still fails. Even better, if I edit a string that does show up in an error message (the one I get when I try to debug without the debugger installed), the edited string does not show up. Edits I make in 

So how do I run the extension with my own code?

**Comment by kylenoteboom** [comment]
Installing [coreclr-git from AUR](https://aur.archlinux.org/packages/coreclr-git/) fixed things. I can now debug applications.

**Comment by gregg-miskelly** [comment]
As part of 1.5 we redid how the debugger is acquired. We will now print a message to the C# log when the debugger doesn't understand the current Linux distro: https://github.com/OmniSharp/omnisharp-vscode/pull/912
