### ISSUE TITLE
Cannot install extension

### ISSUE THREAD

**Issue by tinganho** [OmniSharp/omnisharp-vscode#824]
It seems like I got some problem installing the C# extension.

```
Installing OmniSharp to /Users/tinganho/.vscode/extensions/ms-vscode.csharp-1.4.1/out/.omnisharp-coreclr
    Attempting to download omnisharp-1.9-beta14-osx-x64-netcoreapp1.0.tar.gz
    Downloading to /var/folders/7c/w3bmzm3s1mx8qqfwh0zqdq9m0000gn/T/tmp-18129vEHsVWF8hplE.tmp...
    Download complete!
    Decompressing...
    [ERROR] Error: unexpected end of file
```

I've tried 3 times and here is all three temp files. Notice all of them is having different file sizes:

```
$ ls -la | grep .tmp
-rw-------   1 tinganho  staff  23855104 Oct 15 14:13 tmp-17381N0eXvw0GtJhE.tmp
-rw-------   1 tinganho  staff  23838720 Oct 15 14:18 tmp-17640Gvpn2YunRtAN.tmp
-rw-------   1 tinganho  staff  24313856 Oct 15 14:24 tmp-18129vEHsVWF8hplE.tmp
```

Why does the download complete prematurely?

I'm in China and we have some serious network issue. Though I didn't have problem installing the C# extension before.

**Comment by tinganho** [comment]
I managed to install it on my 10th try.

**Comment by DustinCampbell** [comment]
Sorry to hear that. We're in the process of rebuilding our acquisition story, which should improve stability and also improve feedback on how the download is progressing.
