### ISSUE TITLE
[Syntax Highlighting] Generic Tasks aren't green

### ISSUE THREAD

**Issue by khionu** [OmniSharp/omnisharp-vscode#830]
## Environment data

.NET Command Line Tools (1.0.0-preview2-003131)                                                                                                               

Product Information:  
 Version:            1.0.0-preview2-003131  
 Commit SHA-1 hash:  635cf40e58                                                                                                                               

Runtime Environment:  
 OS Name:     ubuntu  
 OS Version:  14.04  
 OS Platform: Linux  
 RID:         ubuntu.14.04-x64
VS Code version: 1.6.1
C# Extension version: 1.4.1
## Steps to reproduce

Implement a Generic Task
## Expected  behavior

`Task` is Green
## Actual behavior

![image](https://cloud.githubusercontent.com/assets/11195266/19472468/6bdb6d38-94f5-11e6-919b-a6e36ca1cf33.png)

**Comment by DustinCampbell** [comment]
This should look much better in the next release:

![image](https://cloud.githubusercontent.com/assets/116161/21745457/a352903a-d4e1-11e6-9e36-3e195a8ac9bc.png)

**Comment by khionu** [comment]
Wonderful! Looking forward to testing!
