### ISSUE TITLE
Too many changes too fast crashes OmniSharp

### ISSUE THREAD

**Issue by khionu** [OmniSharp/omnisharp-vscode#831]
## Environment data

.NET Command Line Tools (1.0.0-preview2-003131)                                                                                                               

Product Information:  
 Version:            1.0.0-preview2-003131  
 Commit SHA-1 hash:  635cf40e58                                                                                                                               

Runtime Environment:  
 OS Name:     ubuntu  
 OS Version:  14.04  
 OS Platform: Linux  
 RID:         ubuntu.14.04-x64

VS Code version: 1.6.1
C# Extension version: 1.5.0-Beta4
## Steps to reproduce

Make several changes quite fast. In my case, I was editing a class that I just had impliment an interface, via the context menu.
## Expected  behavior

Error handled appropriately
## Actual behavior

![image](https://cloud.githubusercontent.com/assets/11195266/19501376/093ae5fe-9573-11e6-846a-61325ed2d108.png)

It was stopped, and would not resume normal functioning until I restarted VS Code

**Comment by khionu** [comment]
This is happening more and more, even after taking it easy :/

**Comment by DustinCampbell** [comment]
@khionu: The communication with the OmniSharp server has been greatly improved in the latest release. Could you let me know if you still see this problem with 1.5.2 of the C# extension?

**Comment by DustinCampbell** [comment]
This issue has grown a bit cold. I'm going to go ahead and close it, but please let me know if you're still seeing this problem.
