### ISSUE TITLE
editor.formatOnType does not respect editor.insertSpaces setting

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#834]
_From @j-h-a on October 20, 2016 15:58_
- VSCode Version:
  1.6.1
- OS Version:
  OSX (10.11.6)
### Searchable description

VS Code keeps changing some lines to have spaces instead of tabs in the leading whitespace.
### Steps to Reproduce:

Use these settings:
    "editor.tabSize": 4,
    "editor.insertSpaces": false,
    "editor.detectIndentation": false,
    "editor.formatOnType": true,

Type some code that triggers formatOnType to activate a format change.
### Expected behaviour:

Line is formatted using tabs for leading whitespace, because of the insertSpaces setting.
### Actual behaviour:

Line is formatted with spaces instead of tabs for the leading whitespace.

_Copied from original issue: Microsoft/vscode#14108_

**Comment by aeschli** [comment]
_From @roblourens on October 20, 2016 18:25_

Is this in an html file? Could be #13563

**Comment by aeschli** [comment]
_From @j-h-a on October 20, 2016 18:28_

No, this is while editing C#

**Comment by aeschli** [comment]
_From @roblourens on October 20, 2016 18:35_

Related @aeschli?

**Comment by shawnwildermuth** [comment]
Any word on status of this issue? I still cant' seem to find a solution.

**Comment by filipw** [comment]
@shawnwildermuth here is a PR https://github.com/OmniSharp/omnisharp-vscode/issues/1055
