### ISSUE TITLE
OSX + Unity = 0 projects

### ISSUE THREAD

**Issue by jvlppm** [OmniSharp/omnisharp-vscode#835]
I'm using vscode-insiders, with omnisharp-vscode at origin/master ( 034fa7be1419facbed9cc0a0fb48dac527d49e44 ) 1.5-beta4 + 2

When loading a Unity project I'm receiving the '0 projects' status again (even though this was fixed a while ago).

The project is loaded normally, and errors in my code are marked with squiggles, but a few seconds later, the project unloads, errors disappear, and it shows 0 projects at status bar.

<img width="1098" alt="screen shot 2016-10-24 at 10 47 28" src="https://cloud.githubusercontent.com/assets/171599/19646332/c0151048-99d7-11e6-8999-24e635320b84.png">
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003148)

Product Information:
 Version:            1.0.0-preview2-003148
 Commit SHA-1 hash:  18ca244551

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version:
C# Extension version:
## Steps to reproduce

Open a Unity project
## Expected  behavior

OmniSharp status as Running.
## Actual behavior

OmniSharp status as '0 projects'.
## OmniSharp Log

Starting OmniSharp server at 10/24/2016, 10:53:36 AM
    Target: /Users/joao/Projects/PetitFabrik/asset-bundles-demo/asset-bundles-demo.sln

OmniSharp server started wth Mono
    Path: /Users/joao/.vscode-insiders/extensions/ms-vscode.csharp-dev/out/src/.omnisharp-mono/OmniSharp.exe
    PID: 3507

OmniSharp: -s /Users/joao/Projects/PetitFabrik/asset-bundles-demo/asset-bundles-demo.sln --hostPID 3480 DotNet:enablePackageRestore=false --encoding utf-8 --stdio
﻿﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/Users/joao/Projects/PetitFabrik/asset-bundles-demo' on host 3480."},"Seq":1,"Type":"event"}
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /Users/joao/Projects/PetitFabrik/asset-bundles-demo
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp#MSBuild] Detecting projects in '/Users/joao/Projects/PetitFabrik/asset-bundles-demo/asset-bundles-demo.sln'.
[INFORMATION:OmniSharp#MSBuild] Loading project from '/Users/joao/Projects/PetitFabrik/asset-bundles-demo/Assembly-CSharp.csproj'.
[INFORMATION:OmniSharp#MSBuild] Loading project from '/Users/joao/Projects/PetitFabrik/asset-bundles-demo/Assembly-CSharp-Editor-firstpass.csproj'.
[INFORMATION:OmniSharp#MSBuild] Loading project from '/Users/joao/Projects/PetitFabrik/asset-bundles-demo/Assembly-CSharp-Editor.csproj'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in '/Users/joao/Projects/PetitFabrik/asset-bundles-demo'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Configuration finished.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /projects: 200 71ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 13ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /projects: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /filesChanged: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 471ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 843ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 93ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /projects: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 70ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /codecheck: 200 695ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 3ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 4ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 115ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 2ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 6ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 261ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 640ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 101ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 3ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 4ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 6ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 2ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 6ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 5ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /codecheck: 200 1ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 3ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 1ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /codecheck: 200 35ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 11ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 1ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 220ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 3ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /codecheck: 200 1ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 1ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 3ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 534ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 5ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 7ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /codecheck: 200 35ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 4ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 1ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 3ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 0ms

**Comment by greay** [comment]
still a problem in 1.9.0

**Comment by DustinCampbell** [comment]
@greay: The version of Visual Studio Code wouldn't positively impact this. It is the C# for VS Code extension.

**Comment by rchande** [comment]
@jvlppm @greay Can you try again with the latest build of the C# for VS Code extension (1.15) and file new issues if you're still having problems?

**Comment by jvlppm** [comment]
It is working properly, thanks.
