### ISSUE TITLE
Intellisense/OmniSharp stops working

### ISSUE THREAD

**Issue by weinand** [OmniSharp/omnisharp-vscode#836]
_From @widL on October 24, 2016 8:59_
- VSCode Version:
  Version 1.7.0-insider
  Commit 43e46ab67f3bc70490b5e8348cde431dca036397
  Date 2016-10-24T06:19:39.417Z
  Shell 1.3.8
  Renderer 52.0.2743.82
  Node 6.5.0
- OS Version: Ubuntu 16.04 with kernel 4.6.0

Steps to Reproduce:
1. Open any project. OmniSharp works fine for a few seconds up to a minute (different every time).

When it stops working, the "# references" labels above the methods disappear, and when I press ctrl+space anywhere, it just says "Loading..." and nothing happens. The OmniSharp log doesn't give any hints, it simply stops outputting. I'll attach the [omnisharp log](https://github.com/Microsoft/vscode/files/547281/omnisharp_log.txt) of a typical run, where I just opened the project and pressed ctrl+space until it stopped working.

I also have the same issue as #14223. May or may not be related?

_Copied from original issue: Microsoft/vscode#14262_

**Comment by weinand** [comment]
_From @widL on October 24, 2016 9:46_

This should get a Linux tag. Just tried the same project in Windows, and everything works perfectly!

**Comment by brendandixon** [comment]
It occurs under macOS as well.

**Comment by wjk** [comment]
:+1: I get this as well. macOS 10.12.1, VSCode 1.6.1. @luyzfernando claimed that installing version 1.5.0-beta4 of omnisharp-vscode fixes this problem, but I'm running version 1.5.0-beta5 and it still occurs.

**Comment by sethlivingston** [comment]
Just in case this might be useful to others: I landed here because I wasn't getting any Intellisense in VSCode. It was because my project.json file was in a subfolder (I'm using a React Starter Kit project). Running the **OmniSharp: Select Project** command and selecting the `/server/project.json` file fixed everything.

**Comment by brendandixon** [comment]
@sethlivingston That seems to make a difference. However, this also used to work fine. Further, I have multiple projects joined by a global.json. I would think that OmniSharp should handle this case as it is a common .NET pattern.

**Comment by DustinCampbell** [comment]
Hi everyone! I'm curious to know if these issues still occur with the latest release of the extension (1.5.3). Also, I've created a [v1.6-beta2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.6-beta2) release of the C# extension that fixes several issues (including a significant fix for global.json). See this page for information on [installing beta releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases) if you're interested.

**Comment by DustinCampbell** [comment]
It looks to me like this issue has grown stale. Please let me know if anyone is still having trouble with this.
