### ISSUE TITLE
Add Option to Force Full Diagnostics on Large Projects

### ISSUE THREAD

**Issue by heshuimu** [OmniSharp/omnisharp-vscode#838]
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003148)

Product Information:
 Version:            1.0.0-preview2-003148
 Commit SHA-1 hash:  18ca244551

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version: 1.6.3

C# Extension version: 1.5.0-beta4
## Suggestion

In version 1.4, large projects will not have full diagnostics computed except for opened files. I wonder if it is possible to have a new setting that can force the plugin to run full diagnostics regardless of the size of the project.

**Comment by DustinCampbell** [comment]
I had intended to file this same issue awhile back, but hadn't gotten around to it yet. Thanks for filing!
