### ISSUE TITLE
Environment variables ignored ?

### ISSUE THREAD

**Issue by chrismatheson** [OmniSharp/omnisharp-vscode#840]
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
```

VS Code version: 1.6.1
C# Extension version: 1.4.1
## Steps to reproduce

use a launch config  with Environment variables

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Webapp - Debug",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "env": {
                "TR_DB_URI": "Filename=${workspaceRoot}/Trusthub.Tests/testing-only.db"
            },
            "program": "${workspaceRoot}/Trusthub/bin/Debug/netcoreapp1.0/Trusthub.dll",
            "args": [],
            "cwd": "${workspaceRoot}",
            "externalConsole": false,
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart"
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command.pickProcess}"
        }
    ]
}
```

read variable in code `var DB_URI = System.Environment.GetEnvironmentVariable("TH_DB_URI");`
## Expected  behaviour

DB_URI should equal a string beginning with `Filename=` and ending with `.db`
## Actual behaviour

DB_UR === null;

**Comment by gregg-miskelly** [comment]
@chrismatheson when I try this scenario this works for me. Is there something special with the value of your `TH_DB_URI` environment variable that causes this to mess up or do you find that no environment variables work? If it is something special with `TH_DB_URI` do you have any special characters in your root workspace folder?

**Comment by chrismatheson** [comment]
my original value was `Filename=${workspaceRoot}/Trusthub.Tests/testing-only.db` which i changed to 

```
"env": {
                "TR_DB_URI": "something"
            },
```

but still no luck :(

root workspace `/Users/chrismatheson/Code/teachersregister/trusthub` 

however I've made some progress. it seems as though if i read the ENVVAR first thing in `main.cs` its fine. when i do it within another part of the program (while configuring the DB context) its not available. My first thought is that Nancy or OWIN or something is starting new processes which do not have access to the same ENV VARS except that setting using an ENV VAR in the CI system is working fine with the same code

**Comment by gregg-miskelly** [comment]
@chrismatheson thanks for digging. Sounds like this isn't an issue with the C# extension then. In case this is useful - the C# extension doesn't try to debug child processes. So if you get hit a breakpoint in the code that is calling Environment.GetEnvironmentVariable later on, then it must be that there is some code calling `Envirnoment.SetEnvironmentVariable("TR_DB_URI", null)`.

Any objection if I close this since it doesn't sound like it could be a C# extension issue?

**Comment by chrismatheson** [comment]
Yup i think your right, not an extension issue. ill try and update if i find a way round it / a fix of some sort
