### ISSUE TITLE
Error information mismatch when Omnisharp begins/completes analysis

### ISSUE THREAD

**Issue by masaeedu** [OmniSharp/omnisharp-vscode#843]
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

VS Code version: Version 1.6.1
C# Extension version: 1.5.0-beta4

I'm seeing strange behavior in a multi-target project.json-based project. When hovering over a type that is available in the full framework but not available in the `netstandard` target, the expected popups disappear as the project transitions between "building" and "ready" states. 
## Steps to reproduce

There are two scenarios where I'm seeing problems. Here is the setup for both:
1. **Clone the repo**: `git clone git@github.com:masaeedu/language-ext.git`
2. `cd language-ext`
3. **Checkout demo branch**: `git checkout omnisharpmissingerrors`
4. **Restore packages**:  `dotnet restore`
### Scenario 1: Type lookup in open file as project analysis finishes
1. Perform setup
2. **Open in VS Code**: `code .`
3. **Type lookup**: Immediately after the editor opens:
   1. Open `LanguageExt.Tests/TaskTests.cs`
   2. Periodically hover over the `WebClient` parameter type on line 78 and observe the result
### Scenario 2: Type lookup in open file as project analysis begins
1. Perform setup
2. **Open in VS Code**: `code .`
3. **Type lookup**: After the editor opens:
   1. Use "Omnisharp: Select Project" from the command palette to initialize Omnisharp with the root folder (language-ext)
   2. Wait for 1-2 minutes for everything to build successfully (this might take some trial and error)
   3. Open `LanguageExt.Tests/TaskTests.cs`
   4. Observe the bottom ribbon errors and the error information associated with the `WebClient` parameter type on line 78
   5. Make a change in an upstream project (e.g. add whitespace in `LanguageExt.Core/ActionObservable.cs`)
   6. Immediately afterwards, delete line 75-80 in `LanguageExt.Tests/TaskTests.cs`
   7. Observe the bottom ribbon errors
   8. Close and reopen `LanguageExt.Tests/TaskTests.cs`
   9. Observe the location of squiggly underlines in the file
#### Actual

You will see a "Loading..." popup appear for a while as the project is built. After a while, hovering over the `WebClient` symbol will no longer display any popup at all. In the verbose log I see that a type lookup is occurring and comes up with `{"Type":null,"Documentation":null}`, but no errors appear.

After the "Loading..." popup stops appearing, close and reopen the file. Now the appropriate squiggles and bottom ribbon error entries appear.
#### Expected

Once analysis has completed, the appropriate errors should appear in the editor and the bottom ribbon automatically. The user should not have to close and reopen the file.
#### Actual

Once you open the file after waiting an appropriate amount of time, the appropriate squiggles and bottom ribbon errors will appear correctly. After making the described changes to `LanguageExt.Core/ActionObservable.cs` and `LanguageExt.Tests/TaskTests.cs`, errors continue to appear in the bottom ribbon even though the corresponding lines have been deleted.  After reopening the `LanguageExt.Tests/TaskTests.cs` file, error squiggles appear underneath the wrong code:

![error squiggles underlining shifted code](https://ycxx7w.by3302.livefilestore.com/y3mg6yB8Sq66IQ9R3YammNp4hWIOUS9mbBXYSJUyMsy76i37buh2BuXBKuM1VpzaVlDBzUBA7gELwAXwaYmrGHx5z2xdI9K77ythXGtq_QkOt_4UBRkEGgtKkXzAoFJxtRWs5QXQLnlaztVZHVJYfkWFl3pOj3ANzwuRl-5kgGxSZk/Code_2016-10-26_19-05-33.png?psid=1)
#### Expected

Errors should disappear once the code is modified, pending rebuild. At the very least, error underlining should not be applied to the wrong code.
## Additional improvements

When user-requested information is blocked by pending analysis, it would be nice if you could display a specific indication of what Omnisharp is doing and (where possible) how long it will take, instead of just showing the user "Loading...".

**Comment by DustinCampbell** [comment]
@masaeedu: Could you try the latest [v1.5-future-preview1](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.5-future-preview1) release? This should address a lot of the problems with blocking and waiting on the OmniSharp server.

**Comment by DustinCampbell** [comment]
For scenario #1: The "Loading..." should be gone with the latest release. As you deduced, there isn't a popup because 1) type lookup is failing for "WebClient", and 2) there aren't error squiggles in the file. So, technically, this scenario is working as expected. The problem is that the error squiggles aren't appearing, which is broken.

**Comment by masaeedu** [comment]
@DustinCampbell If you close and reopen the file, then hover the symbol, an error popup does appear. I am assuming this error popup should appear without having to close and reopen the file.

**Comment by DustinCampbell** [comment]
Oh, certainly. It's definitely a bug. :smile:

**Comment by DustinCampbell** [comment]
#945 should address scenario 1 above.

**Comment by DustinCampbell** [comment]
OK. I've prepared a new release that should at least fix scenario 1 and (hopefully) scenario 2. It'd be great if you could give it a spin before we release it to the public. Use the following steps to download and install it:

1. Download the VSIX from [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.5.2)
2. Open Visual Studio Code
3. Select View->Extensions to display the Extensions pane.
4. In the Extensions pane, click the little gear icon next to the C# extension and select `Uninstall`.
5. Confirm any prompts and allow Visual Studio Code to reload itself.
6. In the Extensions pane, click the [...] that appears in the top-right corner and select "Install from VSIX..."
7. Select the VSIX you downloaded.
8. Let Visual Studio Code reload itself.

**Comment by masaeedu** [comment]
@DustinCampbell Just went through the steps and scenario 1 looks to be working.

**Comment by DustinCampbell** [comment]
That's great to hear! Progress. :smile:

**Comment by masaeedu** [comment]
I don't know if this new machine is too fast to be able to properly repro scenario 2 or if its fixed. Not seeing the incorrect squiggles either way.

![its a yes from me](https://cdn.meme.am/cache/instances/folder951/500x/37276951.jpg)

**Comment by DustinCampbell** [comment]
This release greatly improves communication with the OmniSharp server. In the past, it was blocking on requests, would would delay the diagnostics.

**Comment by masaeedu** [comment]
Alright, well, that solves my problem. Maybe this release will also fix the disappearing dialogs problem mentioned in the other issues.

**Comment by DustinCampbell** [comment]
Fantastic. I hope so too.
