### ISSUE TITLE
Debugger doesn't support x86 Windows

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#844]
## Steps to reproduce

On x86 (32-bit) Windows, download VS Code, and install the C# extension
## Expected  behavior

32-bit debugger downloads and runs
## Actual behavior

32-bit Windows isn't supported.

**Comment by gregg-miskelly** [comment]
NOTE that when we fix this, we need to remove the code added in https://github.com/OmniSharp/omnisharp-vscode/pull/998

**Comment by Fetandrey** [comment]
Any progress?

**Comment by gregg-miskelly** [comment]
We aren't ready to guess when we will be able release support for this -- we have some hot items which are currently consuming all of our time, but we are much closer to it then we once were. We almost have a new build system in place which among other things, finishes most of the build side of the work for this.

**Comment by Fetandrey** [comment]
Thank you! It's good to know.

**Comment by jayendranarumugam** [comment]
I'm currently using V1.12.2. I couldn't make debug my code with any Break Point,my machine is 32bit. When this be fixed ?

**Comment by sheikhzubayr** [comment]
Is there a fix yet? A x86 user here, not able to debug my c# programs on vs code! But, nonetheless, VS Code is the best editor from Microsoft ever!!

**Comment by gregg-miskelly** [comment]
No news yet I'm afraid.

**Comment by sheikhzubayr** [comment]
@gregg-miskelly This is really unfortunate as I have been eagerly waiting to have C# debugger up and running in VS code for my x86 machine!! Please help us resolve it fast!!

**Comment by PTescAL** [comment]
Any progress on this?
Due to third-party libraries to which we would like to link from .net Core projects, we are limited in our ability to debug our x86 programs, too.

**Comment by twtyypmb** [comment]
any progress?If the problem will not be solved,I have to give up .net core.Is it as design?

**Comment by gregg-miskelly** [comment]
Unfortunately due the low usage of x86 Windows operating systems and many competing priorities, we are unable to fund adding x86 debugging support at this time.  The C# extension will of course continue to function as an editor on x86 Windows. 

We recommend anyone looking for .NET debugging on x86 Windows to use Visual Studio instead. See https://www.visualstudio.com/downloads/ for more information.

**Comment by Yoplayer-1** [comment]
Ya I'm also getting the same error
