### ISSUE TITLE
Disable the "There are unresolved dependencies" info message.

### ISSUE THREAD

**Issue by shaunluttin** [OmniSharp/omnisharp-vscode#845]
How do we disable the "There are unresolved dependencies from..." message that comes up whenever there are unresolved dependencies? 

![171to](https://cloud.githubusercontent.com/assets/2066637/19790604/4af56832-9c6e-11e6-803f-9545b2e95b79.png)

I would rather not be told this.

**Comment by DustinCampbell** [comment]
A new (release)[https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.5-beta6] is ready which includes a `csharp.suppressDotnetRestoreNotification` option.

**Comment by shaunluttin** [comment]
@DustinCampbell That's wonderful. How do we install a specific version such as `1.5-beta6`?

**Comment by shaunluttin** [comment]
@DustinCampbell Figured it out: 

     code --install-extension .\csharp-1.5.0-beta6.vsix

**Comment by DustinCampbell** [comment]
yes, there's also a way on the Extensions pane in VS Code. At the top right-hand corner of the Extensions pane, click the [...] and select "Install from VSIX..."

**Comment by shaunluttin** [comment]
@DustinCampbell I have installed the appropriate version and set my settings.json. The notification info message continues to display, though. 
```
{
    "files.autoSave": "afterDelay",
    "window.zoomLevel": 0,
    "csharp.suppressDotnetRestoreNotification": true
}
```
Does the new release suppress the info message on your machine?

**Comment by DustinCampbell** [comment]
Yes, it works for me. I just set the option and then performed a `git clean -xdf` in a project I had loaded. No notification appeared.

**Comment by shaunluttin** [comment]
Thank you for checking.

**Comment by shaunluttin** [comment]
It works after deleting the previous version of the extension from here: 

    C:\Users\myuser\.vscode\extensions

**Comment by DustinCampbell** [comment]
glad you got it working (and very nice to meet you this week!) :smile:
