### ISSUE TITLE
Error - Enabling C# debugger logging

### ISSUE THREAD

**Issue by luyzfernando** [OmniSharp/omnisharp-vscode#847]
## Environment data

.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID: ubuntu.16.04-x64

VS Code version:
Version 1.6.1

C# Extension version:
Version: 1.5.0-beta4
## Steps to reproduce

Try to follow the steps outlined here
https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging#full-method
## Expected  behavior

Generate log
## Actual behavior

When you open the VS Code, he no longer identifies the extent and asks you to install again.

**Comment by gregg-miskelly** [comment]
@luyzfernando your URL is pointing at the 'quick method' but it sounds like you actually used the 'Full Method'? Can you share out your package.json? Or a diff between the original and what you added?

**Comment by luyzfernando** [comment]
Sorry, wrong link. The correct is 'Full Method'

The only change was to add this line:
![image](https://cloud.githubusercontent.com/assets/1857208/19822680/82f859e4-9d43-11e6-9502-75eb04ca063a.png)

[package.txt](https://github.com/OmniSharp/omnisharp-vscode/files/559447/package.txt)

**Comment by WardenGnaw** [comment]
Added information about specifying own log file in https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging#3-add-args-property
