### ISSUE TITLE
Error highlighting not cleared

### ISSUE THREAD

**Issue by Novack-** [OmniSharp/omnisharp-vscode#858]
## Environment data

.NET Command Line Tools (1.0.0-preview2-003133)
Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:  
 OS Name:     Windows 
 OS Version:  6.1.7601
 OS Platform: Windows 
 RID:         win7-x64

VS Code version: 1.6.1
C# Extension version: 1.5.0-beta4

## Steps to reproduce
Produce any syntax error and fix it. The error underlyning ribbon will not clear. 
A good example is when you dont have the namespace for the introduced class, then fix it with the Ctrl+. suggestion. It wont clear. Then if you brear the sentence with a different type of error, like an unrecognized symbol, and then fix it, the error highlighting will clear correctly.

## Expected  behavior
Error highlighting should clear as soon as fixing any error.

## Actual behavior
Read above, in "Steps to Reproduce".

**Comment by DustinCampbell** [comment]
Should be fixed in our next release (1.5.2), which will be going out sometime later today.
