### ISSUE TITLE
[CSharp] Have "add using ..." on top in quick fix dialog 

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#86]
_From @NinoFloris on March 3, 2016 19:34_

Have "add using ..." on top in quick fix dialog

This is a real timesaver as the suggestion is 99% of the time correct but it's at the bottom, requiring an extra "arrow key up" keystroke to complete the action.

It is a bit of a flow killer

_Copied from original issue: Microsoft/vscode#3689_

**Comment by DustinCampbell** [comment]
This should be much better in the 1.7 release. It's not perfect, but is much improved. https://github.com/OmniSharp/omnisharp-roslyn/issues/758 tracks making this match the behavior in Visual Studio.
