### ISSUE TITLE
self signed certificate

### ISSUE THREAD

**Issue by ErnestoCevallos** [OmniSharp/omnisharp-vscode#860]
I just installed the Visual Studio Code and after the installation finished, I can't install any extension as I am getting an error self signed certificate. How can I fix this?  as I need to install the C# extension.

**Comment by DustinCampbell** [comment]
@ErnestoCevallos: I haven't heard of this problem and wouldn't know where to start. I recommend filing an issue over on https://github.com/microsoft/vscode.
