### ISSUE TITLE
Incorrect highlighting of comments

### ISSUE THREAD

**Issue by vorov2** [OmniSharp/omnisharp-vscode#861]
## Environment data
VS Code version: 1.6.1
C# Extension version: 1.4.1

## Steps to reproduce
1. Open a cs file
2. Try to comment out a block of code starting from the method signature

## Expected  behavior
Code should be commented.

## Actual behavior
Comment is ignored:
![capture2](https://cloud.githubusercontent.com/assets/10725688/19920816/68452726-a0f4-11e6-8201-bbb50cc11df0.PNG)

**Comment by DustinCampbell** [comment]
This should be fixed for the next release:

![image](https://cloud.githubusercontent.com/assets/116161/21739365/11f870c0-d44e-11e6-86e9-58423ba435e6.png)
