### ISSUE TITLE
Code reports errors in removed source files

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#87]
_From @jeffschwMSFT on February 19, 2016 18:13_

![removedfiles](https://cloud.githubusercontent.com/assets/9561583/13184519/42ae62d4-d6f1-11e5-8b4b-0668f44d7e4a.gif)

On my OS X Yosemite machine running Code, I was adding/removing code in a solution.  One of the files I removed had a C# build error.  The interesting thing was the the error persisted in my Code session even after deleting the file (control - click - delete).  The error only went away once I closed the folder and reopened.

_Copied from original issue: Microsoft/vscode#3174_

**Comment by jrieken** [comment]
_From @egamma on February 20, 2016 15:12_

Not clear whether this is Omnisharp or the Code marker infrastructure. The fact that the error count drops to 0 indicates that the marker is properly removed when the file is deleted.

**Comment by jrieken** [comment]
_From @dbaeumer on February 29, 2016 15:53_

Since the error counts drops to zero I suspect this being a problem in OmniSharp land

**Comment by jrieken** [comment]
Omnisharp doesn't really support delete...

**Comment by jeffschwMSFT** [comment]
I wanted to put this higher on the stack.  After using VS Code more I have found that this issue is even worse if you rename a file.  VS Code will always give you the error that XYZ class has already been defind.

**Comment by duraz0rz** [comment]
I've recently come across this bug.

1) Introduce an error in your code. Remove a semi-colon or something.
2) Delete the file.

Expected: The error should go away.
Actual: The error stays in VSCode, even after editing other code. I did **not** observe the error count go down to 0; it remains at 1.

A workaround is to restart Omnisharp after deleting files.

**Comment by DustinCampbell** [comment]
We're going to use https://github.com/OmniSharp/omnisharp-vscode/issues/785 to track the file renaming issue. I believe the other issues mentioned here are addressed.
