### ISSUE TITLE
CodeCheck happens pretty frequent and takes long time to process

### ISSUE THREAD

**Issue by PotterDai** [OmniSharp/omnisharp-vscode#870]
## Environment data
VS Code version:1.7.1
C# Extension version: 1.5.0-beta6
## Steps to reproduce
Open a normal sized project.
Everytime I save, the output log looks like this.

![screenshot 2016-11-04 14 06 46](https://cloud.githubusercontent.com/assets/3758951/20017006/353109b8-a298-11e6-9c44-f42ca90b672b.jpg)

Is this situation normal? As codecheck happens pretty frequently.
During codecheck process, the intellisense no longer works and I have to wait for it to complete.

**Comment by DustinCampbell** [comment]
I'm seeing this as well. Will be taking a look.

**Comment by DustinCampbell** [comment]
#902 should fix this.
