### ISSUE TITLE
Reference link is inside the file explorer

### ISSUE THREAD

**Issue by nklap** [OmniSharp/omnisharp-vscode#872]
## Environment data
.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

VS Code version: 1.7.1
C# Extension version: 1.4.1

## Steps to reproduce
Create a class and reference it in another class

## Expected  behavior
Show reference link above class or method definition

## Actual behavior
Reference link is shown in the file explorer. See the picture.

![image](https://cloud.githubusercontent.com/assets/15824255/20022309/2085ccc8-a2da-11e6-97b7-a63d21f36609.png)

**Comment by DustinCampbell** [comment]
This is a known VS Code issue: https://github.com/Microsoft/vscode/issues/14949
