### ISSUE TITLE
project.json project list capped to 100

### ISSUE THREAD

**Issue by richlander** [OmniSharp/omnisharp-vscode#875]
The project.json project list is capped to 100, for both display and search. I cannot search for my projects that are beyond the capped set.

I most often open a narrow folder so that only a few projects are within scope. When I'm working on a set of cross-repo changes, I sometimes open to my whole "git" directory and then run into this problem. 

I'd like to see one of two user experiences, in order of preference:

1. All projects are visible and all projects are searchable.
2. No projects are listed with some UI explaining why, but all projects are searchable.

Thanks!

Current experience:

<img width="867" alt="screen shot 2016-11-05 at 10 23 57 am" src="https://cloud.githubusercontent.com/assets/2608468/20032169/3915c6cc-a342-11e6-9a18-5ce303f262ca.png">

/cc @DustinCampbell @kendrahavens

**Comment by DustinCampbell** [comment]
Resolving as fixed for 1.6. Thanks @filipw!

**Comment by DustinCampbell** [comment]
I've created a [v1.6-beta2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.6-beta2) release of the C# extension that contains this fix, among others. See this page for information on [installing beta releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases)
