### ISSUE TITLE
Scanned references disappear or move to the left file pane when zooming in or out

### ISSUE THREAD

**Issue by TheAndrewJackson** [OmniSharp/omnisharp-vscode#876]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

VS Code version: 1.7.1
C# Extension version: 1.4.1

## Steps to reproduce
1. Have omnisharp finish scanning the project and create references
2. Zoom in our out

## Expected  behavior
 To adjust the view correctly and still have the references placed above their respective functions and variables. 

## Actual behavior
Moving the reference links to the file pane on the left instead of keeping them above their functions and variables. 

I would provide a video of it happening but the codebase I'm working is a private one so I can't share the code.

**Comment by DustinCampbell** [comment]
This is a VS Code issue: https://github.com/Microsoft/vscode/issues/14949
