### ISSUE TITLE
Error MSB1003 while installing .NET core debugger

### ISSUE THREAD

**Issue by TrevorBurnham** [OmniSharp/omnisharp-vscode#878]
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

VS Code version: 1.7.1

C# Extension version: 1.4.1

## Steps to reproduce

Install the C# extension and open ` .cs` file. The message `Error while installing .NET Core Debugger` appears. Console output:

```
Creating /Users/tburnham/.vscode/extensions/ms-vscode.csharp-1.4.1/coreclr-debug/project.json
Telemetry is: Enabled
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
dotnet exited with error code 1
```

If I `cd` into `~/.vscode/extensions/ms-vscode.csharp-1.4.1/coreclr-debug/` and run `dotnet --verbose restore --configfile NuGet.config`, I get the same error:

```
Telemetry is: Enabled
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```

It's not wrong; the only files in that directory are `NuGet.config` and `dummy.cs`.

Could this problem be unique to the latest dotnet-cli release (1.0.0-preview3)? Possibly related to this ticket: https://github.com/dotnet/cli/issues/4447

**Comment by TrevorBurnham** [comment]
I downgraded to 1.0.0-preview2-003148 and the installation worked. If anyone else runs into this issue, I hope they find their way to this ticket! 😅

**Comment by gregg-miskelly** [comment]
@TrevorBurnham we are working on a solution to this.

**Comment by blomm** [comment]
I've only just started to play with dotnet core, and my dotnet restore command returns the same MSBUILD error.  
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
I scaffolded my project with "yo aspnet" which didn't create any proj or sln file, should it have?

PS C:\Development\test\webapi\admin-tool-0.1> dotnet --info
.NET Command Line Tools (1.0.0-preview4-004071)

Product Information:
 Version:            1.0.0-preview4-004071
 Commit SHA-1 hash:  9855dc0088

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
PS C:\Development\test\webapi\admin-tool-0.1>

**Comment by gregg-miskelly** [comment]
@blomm Correct. 'Preview4' is not yet supported by this extension. I would recommend rolling back to preview2 for now.

**Comment by FvdG** [comment]
Hi,

I've got two (probably newbie) issues : 
1. I cant seem to build the project and run it locally? I'm using..
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

I've tried dotnet run , but it keeps telling me : 

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

And the second thing, when I try docker-compose build i get the following: 

IOError: [Errno 13] Permission denied: 'C:\\source\\<WindowUser>\\AspNetCorePostgreSQLDockerApp\\.vs\\AspNetCorePostgreSQLDockerApp\\v15\\Browse.VC.opendb'
docker-compose returned -1

If it's a totally dumb question, i'm sorry.

With kind regards,

Frank

**Comment by hurricaneMitch** [comment]
Any word on when/if this support will happen? For now following the steps [here](https://docs.microsoft.com/en-us/dotnet/articles/core/docker/building-net-docker-images) is broken.

**Comment by gregg-miskelly** [comment]
What issue are you seeing? The 1.5x version of the extension has basic support for preview 4.

**Comment by stephenyao** [comment]
Hi, I'm using 1.0.0-preview2-003131 and everything is good, but I'm deploying to azure portal via git.

Everything was good except until recently, I'm getting the same error as stated above.

Presumably azure has updated to the latest CLI. 

Is there any work around for this?

Thanks

**Comment by gregg-miskelly** [comment]
@stephenyao do you know if this is the URL being used to obtain GetClrdbg -- https://raw.githubusercontent.com/Microsoft/MIEngine/getclrdbg-release/scripts/GetClrDbg.sh?

GetClrDbg will attempt to download zip files if it thinks it is using a version of the CLI that doesn't support project.json (see [here](https://github.com/Microsoft/MIEngine/blob/getclrdbg-release/scripts/GetClrDbg.sh#L154)). But I am not sure why this isn't working for you. We are planning to switch to all zip files soon, but we have some more work to finish before this can happen.

**Comment by gk-pnglabs** [comment]
@gregg-miskelly  hi, I'm having a similar issue when publishing my project from git to azure. 
from visual studio code, when I pushed my dotnet core preview4 project to azure, I get this:

_remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id '38077d294b'.
remote: Generating deployment script.
remote: Running deployment command...
remote: Handling ASP.NET Core Web Application deployment.
remote: MSBUILD : error MSB1003: Specify a project or solution file. The current working directory doe
s not contain a project or solution file.
remote: Failed exitCode=1, command=dotnet restore
remote: An error has occurred during web site deployment.
remote:
remote: Error - Changes committed to remote repository but deployment to website failed._


On the azure portal, I see the same MSB1003 message.

If I navigate to the project folder directly (on my local machine or in azure), and run the **dotnet restore** command, it works fine. it just seems that publishing to azure causes this issue.

here is the output in azure terminal after the git repo is pushed.
_____________________________________________
_Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling ASP.NET Core Web Application deployment.
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
Failed exitCode=1, command=dotnet restore
An error has occurred during web site deployment.
\r\nD:\Program Files (x86)\SiteExtensions\Kudu\59.51212.2600\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"_
_____________________________________________

Do you know how I can get around this issue? Thanks!
_________________________________________________________
**on my local machine: dotnet --info**
_.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.0-preview4-004233_

_________________________________________________________
**in azure: dotnet --info**
_.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
Version:            1.0.0-preview4-004233
Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
OS Name:     Windows
OS Version:  6.2.9200
OS Platform: Windows
RID:         win8-x86
Base Path:   D:\Program Files (x86)\dotnet\sdk\1.0.0-preview4-004233_

**Comment by gregg-miskelly** [comment]
@gk-pnglabs this isn't something I know anything about. Do you have a .csproj (preview 3+ drops project.json support in favor of .csproj)? I don't even know what the right GitHub is for this question, but you could try https://github.com/aspnet/Tooling/issues which is at least closer to someone who will know something.
