### ISSUE TITLE
Checking ID_LIKE - KDE Neon support

### ISSUE THREAD

**Issue by 0xFireball** [OmniSharp/omnisharp-vscode#879]
## Environment data
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     neon
 OS Version:  16.04
 OS Platform: Linux
 RID:         neon.16.04-x64

## Steps to reproduce
Attempt to start the debugger in VSCode

## Expected  behavior
The debugger will start

## Actual behavior
The VSCode log will display `Error: Unsupported linux platform`

[This code file](https://github.com/OmniSharp/omnisharp-vscode/blob/735f90a299e857fc5de97216f961c4dd16907cac/src/platform.ts#L59) checks the platform by looking at `os-release`. My OS release looks like this:

```
NAME="KDE neon"
VERSION="5.8"
ID=neon                                                                                                             
ID_LIKE="ubuntu debian"                                                                                             
PRETTY_NAME="KDE neon User Edition 5.8"
VERSION_ID="16.04"
HOME_URL="http://neon.kde.org/"
SUPPORT_URL="http://neon.kde.org/"
BUG_REPORT_URL="http://bugs.kde.org/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

Though my distro is clearly Ubuntu based, the code only checks the `id` property. Perhaps the switch could be updated to check the if `ID_LIKE` contains a recognized platform, if it exists, or Ubuntu-based distros like Neon could be mapped to the `Ubuntu` platform.

**Comment by gregg-miskelly** [comment]
@0xFireball Have you tried using the Ubuntu 16.04 version of the .NET CLI? I can build you a custom .vsix that will look at `ID_LIKE`/`VERSION_ID` assuming that the Ubuntu 16 CLI actually works on KDE Neon.

**Comment by 0xFireball** [comment]
KDE Neon is LTS Ubuntu with KDE, unlike Kubuntu, which is the latest Ubuntu with KDE.
Everything should be fully compatible.

A custom VSIX would be really helpful, thanks.

**Comment by 0xFireball** [comment]
Maybe you could change this in the actual code, assuming everything else works as expected

**Comment by gregg-miskelly** [comment]
@0xFireball yes, that is definitely my goal. I just want to verify that I am actually resolving the issue before I submit a checkin a fix.

**Comment by gregg-miskelly** [comment]
@0xFireball I am attaching a new version of the C# extension to this work item:
[csharp-1.5.0-dev-kdeneon.vsix.renamed.zip](https://github.com/OmniSharp/omnisharp-vscode/files/579284/csharp-1.5.0-dev-kdeneon.vsix.renamed.zip)

1. Download the file
2. Remove the '.renamed.zip' part of the extension
3. In VS Code: View->Extensions
4. Click the '...' to bring up the additional command menu and select 'Install from VSIX...', and navigate to the downloaded file
5. Confirm that downloading assets succeeds and debugging works

Thanks!
Gregg

**Comment by gregg-miskelly** [comment]
@0xFireball did you have a chance to give that .vsix a try?

**Comment by 0xFireball** [comment]
Not yet, but I will later today

**Comment by DustinCampbell** [comment]
@0xFireball: Does the latest release (shipped yesterday on the VS Marketplace) fix the issue for you?

**Comment by DustinCampbell** [comment]
I'm going to go ahead and close this. Let us know if the latest release doesn't address this issue.

**Comment by 0xFireball** [comment]
sorry about how long it took me to get back :( @DustinCampbell 
thanks for your quick fix! it works perfectly, just like on Windows :tada:

**Comment by DustinCampbell** [comment]
Excellent! Thanks for letting us know.
