### ISSUE TITLE
Unable to target CoreCLR from Visual Studio Code

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#88]
_From @TheBlueSky on February 26, 2016 13:3_

Hellp everyone,

I created a totally empty project and specified only CoreCLR as targetted framework; i.e., in `project.json` I have:

    "frameworks": {
        "dnxcore50": {}
    }

On my PC, the dnvm confirugration is the following:

    Active Version           Runtime Architecture OperatingSystem Alias
    ------ -------           ------- ------------ --------------- -----
           1.0.0-rc1-update1 clr     x64          win
           1.0.0-rc1-update1 clr     x86          win
      *    1.0.0-rc1-update1 coreclr x64          win             default
           1.0.0-rc1-update1 coreclr x86          win

Still, when I run the application I receive:

    System.InvalidOperationException: The current runtime target framework is not compatible with 'SomeProject'.
    Current runtime target framework: 'DNX,Version=v4.5.1 (dnx451)'
     Version:      1.0.0-rc1-16231
     Type:         Clr
     Architecture: x86
     OS Name:      Windows
     OS Version:   10.0
     Runtime Id:   win10-x86

    Please make sure the runtime matches a framework specified in project.json

Visual Studio Code is still "thinking" that it should run x86 CLR DNX and not the x64 CoreCLR one.

I'm not sure if this is a Visual Studio Code issue, or ASP.Net Core tooling issue; and appreciate any hint and help.

_Copied from original issue: Microsoft/vscode#3489_

**Comment by jrieken** [comment]
_From @TranscendOfSypherus on March 4, 2016 1:56_

I too am seeing this issue, if I launch a command window from the command pallet and invoke dnx web then kestrel launches fine against coreclr.

**Comment by DustinCampbell** [comment]
Hi @TheBlueSky and @TranscendOfSypherus, with DNX replaced with .NET Core, is this still an issue. It seems to be pretty stale. Let me know if you're still experiencing this problem.

**Comment by TheBlueSky** [comment]
@DustinCampbell, it isn't relevant anyway now, after moving to `dotnet`. I'm going to test this later, and if there is an issue, I believe we should open a new "Issue".

**Comment by DustinCampbell** [comment]
yes, that'd be best.
