### ISSUE TITLE
Support for msbuild only projects

### ISSUE THREAD

**Issue by tsolarin** [OmniSharp/omnisharp-vscode#881]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

VS Code version: `1.7.1`

C# Extension version: `1.4.1`

## Steps to reproduce

* Upgrade .NET Cli tools to `1.0.0-preview3-004056`
* Create new project with `dotnet new`, a `csproj` file is created but no project.json is present.

## Expected  behavior

Omnisharp should work with projects that contain a `csproj` but no `project.json`

## Actual behavior

Omnisharp server does not start or offer intellisense features.

**Comment by DustinCampbell** [comment]
Note: This is happening, but it's a lot of work. The work is being tracked in https://github.com/OmniSharp/omnisharp-vscode/projects/2.

**Comment by tsolarin** [comment]
@DustinCampbell thanks for the response. I'll love to contribute any way I can

**Comment by DustinCampbell** [comment]
Thanks! I got much it working today.

![image](https://cloud.githubusercontent.com/assets/116161/20081056/03de29d8-a502-11e6-9451-c2fa7f4db330.png)

**Comment by DustinCampbell** [comment]
There's a new [v1.5-future-preview1](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.5-future-preview1) release that adds initial support for MSBuild-based .NET Core projects.

**Comment by DustinCampbell** [comment]
Note that there's still a lot to do to fill out the experience, but this should unblock you.

**Comment by tsolarin** [comment]
Thanks @DustinCampbell
