### ISSUE TITLE
Problem invoking 'RunCodeAction' on OmniSharp server: null

### ISSUE THREAD

**Issue by balajikris** [OmniSharp/omnisharp-vscode#882]
## Environment data
`dotnet --info` output:
bash-3.2$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003148)

Product Information:
 Version:            1.0.0-preview2-003148
 Commit SHA-1 hash:  18ca244551

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version: 1.7.1
C# Extension version: 1.4.1

## Steps to reproduce
Not sure how to reproduce this reliably, but I'm noticing bogus quick fixes on simple code.

![image](https://cloud.githubusercontent.com/assets/4213867/20040855/1d121138-a414-11e6-98c9-9e1fb14b4f17.png)

I have an unnecessary using, but the other fixes do not seem to be applicable here. If I invoke one of them (other than the unnecessary using), I get this error
**"Problem invoking 'RunCodeAction' on OmniSharp server: null"**

## Expected  behavior

Only fixes applicable to code show up.

## Actual behavior

Bogus fixes show up, I think. Invoking them shows a null error.

**Comment by DustinCampbell** [comment]
thanks @balajikris!

**Comment by DustinCampbell** [comment]
Hey @balajikris: I'm curious to know if you experience this problem with the [latest beta](https://github.com/OmniSharp/omnisharp-vscode/releases) of the extension. I did some work a month or so ago in the OmniSharp server to fix problems with code fixes appearing on incorrect spans: https://github.com/OmniSharp/omnisharp-roslyn/commit/8fceea97bfbea417c7e724bf5d08545385ef7898.

To install a beta, do the following:

1. Download the *.vsix for the release you want.
2. Open VS Code.
3. Select View->Extensions to display the Extensions Pane
4. If it's installed, uninstall the C# extension by clicking the gear next to the extension and selecting "Uninstall". Once uninstalled, be sure to let VS Code reload.
5. Click the [...] at the top-right corner of the Extensions pane and choose "Install from VSIX..." from the menu.
6. Find the VSIX you downloaded and click Open.
7. Let VS Code reload.

**Comment by DustinCampbell** [comment]
This should be fixed in the latest release (1.5.2)

**Comment by balajikris** [comment]
ah -- will test it out, thanks!
