### ISSUE TITLE
Why am I not seeing 'format code' as a command when I press F1? 

### ISSUE THREAD

**Issue by vamichael** [OmniSharp/omnisharp-vscode#892]
## Environment data
`dotnet --info` output: **Please start a debug session to evaluate** where do I execute this command?
VS Code version: 1.7.2
C# Extension version:1.4.1

## Steps to reproduce

Open a C# (cs) file and CTRL-A
Press F1, type **format code**
## Expected  behavior
I expect to see a command that lets me format the code, pretty print, tabs, etc.

## Actual behavior
nothing

**Comment by DustinCampbell** [comment]
Hi! Sorry, we've taken so long to get back to you. Here are answers to your questions:

1. *Where do I execute that `dotnet --info` command?*

   We're expecting you to do this at a Terminal window (OSX/Linux) or a Command Prompt (Windows). However, that would only work if you had the .NET Core SDK installed. You might consider checking on the videos at this link to get started: https://channel9.msdn.com/Blogs/dotnet/Get-started-with-VS-Code-using-CSharp-and-NET-Core.

2. *Why is there no format code command?*

    The command you're looking for is `Format Document`. However, that may not work for unless you're properly set up (see the video link from earlier).

Let me know if this helps, or if you have more questions. Again, sorry for taking so long to reply.

**Comment by DustinCampbell** [comment]
It looks to me like this issue has grown quite stale. I'm going to go ahead and close it, but let me know if this does not answer your questions.
