### ISSUE TITLE
Incorrect intelligence and problem refreshing the error after correction

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#894]
_From @saurabhnachankar on November 8, 2016 6:13_

- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|net-core-project-manager|ksubedi|0.3.6|
|csharp|ms-vscode|1.4.1|

---

Steps to Reproduce:

1. Intelligence should be improved in Visual Studio Code. Proper suggestion are not specified in the intelligence
2. Error are not refreshed in code after correcting it.
3. Very poor approach for developing in code considering other IDE's

_Copied from original issue: Microsoft/vscode#15143_

**Comment by aeschli** [comment]
@saurabhnachankar For what language is that? Can you also add a small code sample that demonstrated the issue?

**Comment by aeschli** [comment]
_From @saurabhnachankar on November 9, 2016 5:52_

This was my controller's method invoking for creating XL file through
Epplus.

*Issue No. 1  :* This was my following using :  using
Microsoft.Net.Http.Headers; for ContentDispositionHeaderValue.
But i was not able to get it through intelligence in Visual Studio Code. so
i opened it in visual studio community and got the appropriate using.

*Eg :*
Response.Headers["Content-Disposition"] = new
ContentDispositionHeaderValue("attachment")

*Issue No 2 :* Even commented code is complied in debugger and later shows
the following error of commented code like

*Eg :*


*In Browser error:*
An error occurred during the compilation of a resource required to process
this request. Please review the following specific error details and modify
your source code appropriately.
Please fix the issue of VS-Code

Regards,
Saurabh Nachankar

On Tue, Nov 8, 2016 at 7:41 PM, Martin Aeschlimann <notifications@github.com

**Comment by aeschli** [comment]
Moving to C#

**Comment by DustinCampbell** [comment]
I suspect this is the same as #858. I've prepared a brand new release of the C# extension that should address this problem. Would you be willing to try this new release before we ship it on the VSCode marketplace? Use the following instructions to try it out.

1. Download the VSIX from [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.5.2)
2. Open Visual Studio Code
3. Select View->Extensions to display the Extensions pane.
4. In the Extensions pane, click the little gear icon next to the C# extension and select `Uninstall`.
5. Confirm any prompts and allow Visual Studio Code to reload itself.
6. In the Extensions pane, click the [...] that appears in the top-right corner and select "Install from VSIX..."
7. Select the VSIX you downloaded.
8. Let Visual Studio Code reload itself.

**Comment by DustinCampbell** [comment]
This should be fixed in the 1.5.2 release. Please let us know if it is still a problem.

**Comment by saurabhnachankar** [comment]
Thank you for replying..

Regards,
Saurabh Nachankar
