### ISSUE TITLE
Debugger: The "hit count" property  has no effect 

### ISSUE THREAD

**Issue by qian6** [OmniSharp/omnisharp-vscode#895]
## Environment data
`dotnet --info` output:
VS Code version: 1.7.1
C# Extension version: v.1.5.0-beta7
 .NET Core version: 1.0.0-SDK Preview4

## Steps to reproduce

1. Open hwapp folder in attachments directly
2. Set a breakpoint at line of 10 in Program.cs file and set breakpoint conditional as hit count =4 
![capture](https://cloud.githubusercontent.com/assets/20922638/20130869/b9292606-a694-11e6-8d51-65dd5a1e384b.PNG)
3. Press F5 to start debugging

## Expected  behavior
It hit breakpoint and  variable "i"  value is 3

## Actual behavior
It can hit breakpoint ,but variable "i" value is 0
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/580186/hwapp.zip)

**Comment by gregg-miskelly** [comment]
Correct. Hit count breakpoints aren't yet implemented.
