### ISSUE TITLE
Debugger:Command failed: wmic process get Name,ProcessId,CommandLine /FORMAT:list

### ISSUE THREAD

**Issue by ClaireKang** [OmniSharp/omnisharp-vscode#897]
## Environment data
`dotnet --info` output:
VS Code version: 1.7.1
C# Extension version: v.1.5.0-beta7
.NET Core version: 1.0.0-SDK Preview4
OS: Win7x64

## Steps to reproduce
1. Launch the project in Command Prompt(cmd window) using the Command 'dotnet run'.
2. Open the attachment project with VSCode.
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/580406/hwapp.zip)
3. Set a bp at line of 12 in Program.cs.
4. Select the debug type '.Net core Attach'
![attach](https://cloud.githubusercontent.com/assets/20184768/20133846/11fa7366-a6a4-11e6-8b3d-30dd5bdaf291.PNG)
5. Press F5 to start debugging

## Expected  behavior
Pop up the UI that we can select the process to start attach.
like the picture:
![ffe42633](https://cloud.githubusercontent.com/assets/20184768/20133971/a0a3d6ac-a6a4-11e6-8204-08f7fafa9224.PNG)

## Actual behavior
The UI window didn't display, and pop up an error message.
![ui](https://cloud.githubusercontent.com/assets/20184768/20134060/e8528a20-a6a4-11e6-85ad-871dbba615c0.PNG)

Investigation:
1. I tried to change attch configurations in launch.json file 
   "processId": "4312"
press F5 again, and the bp can be hit. Attach can work correctly.

**Comment by gregg-miskelly** [comment]
I think the issue here is that the process listing code is broken on Win7.

**Comment by rajkumar42** [comment]
@ClaireKang I did a quick test on Windows 7 with the following and attach seems to work fine. 
VSCode: v1.7.1
dotnet cli: 1.0.0-preview2-003133
OS: Win7x64
C# Extension version: v.1.5.0-beta7

Perhaps it is a unintended consequence of using ".NET Core version: 1.0.0-SDK Preview4", can you try installing Preview2 and try it again? 
Would you also mind just running "wmic process get Name,ProcessId,CommandLine /FORMAT:list" on a cmd prompt in your Windows installation?

**Comment by ClaireKang** [comment]
I tried do the test with 1.0.0-preview2-003133, Attach can work correctly.

**Comment by rajkumar42** [comment]
Closing this issue. Lets revisit this when testing preview3 & preview4.
