### ISSUE TITLE
Debugger:Failed to launch external program msbuild /property:GenerateFullPaths=true. spawn msbuild ENOENT

### ISSUE THREAD

**Issue by ClaireKang** [OmniSharp/omnisharp-vscode#898]
## Environment data
`dotnet --info` output:
VS Code version: 1.7.1
C# Extension version: v.1.5.0-beta7
.NET Core version: 1.0.0-SDK Preview4
OS: Win7x64

## Steps to reproduce
1. Open the attachment project with VSCode.
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/580450/hwapp.zip)
3. Press F5 and configure 'MSBuild' in the Task Runner.
![task](https://cloud.githubusercontent.com/assets/20184768/20134561/cf8f2276-a6a6-11e6-99aa-74c1cb0f1665.PNG)
3. Set a bp at line of 12 in Program.cs.
4. Press F5 to start debugging.

## Expected  behavior
It can correctly start debugging and hit the bp.

## Actual behavior
1. The bp can be hit and the program can work correctly while an error message is shown in Output Window.
![msbuild](https://cloud.githubusercontent.com/assets/20184768/20134707/64bced42-a6a7-11e6-86c6-6f623e308c86.PNG)

Investigation:
1. If configure '.NET Core' in the Task Runner, the program can work correctly and the Output Window didn't display any error message.

**Comment by gregg-miskelly** [comment]
@ClaireKang this is telling you that msbuild isn't on your path, which is pretty normal. For this to work you would need to launch VS Code from a developer command prompt... But there isn't much of a chance you want to be launching msbuild anyway - if you have a .NET Core app you want to use the .NET CLI.
