### ISSUE TITLE
Debugger: Attach doesn't work correctly with app in a tight loop

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#899]
## Environment data
`dotnet --info` output:
VS Code version: 1.7.1
C# Extension version: 1.5-beta7
.NET Core SDK version: 1.0.0-preview4-004061
OS: Fedora23 x64
## Steps to reproduce
1. Download attach folder in attachments directly
[attach.zip](https://github.com/OmniSharp/omnisharp-vscode/files/580422/attach.zip)
2. Launch the project in Command Prompt using the command "dotnet run"
3. Open the project in VSCode
4. Set a bp at line of 11( i++; ) in Program.cs
5. Select the debug type ''.Net core Attach'
6. Press F5 to start debugging
7. Select process ID on UI

## Expected  behavior
This bp should be hit

## Actual behavior
The bp can't be hit

## Investigation
If I uncomment the line of 9 ( //Console.WriteLine("Hello World!"); ), and then rebuild this project, the bp can be hit

**Comment by gregg-miskelly** [comment]
This may or may not be a solvable problem - threads are not necessarily interruptible when in tight loops.

@GraceDong can you repro this if you loop does anything else (ex: even calling a method with no body).

**Comment by GraceDong** [comment]
Sorry, if I have my loop do something, I can't repro it.

**Comment by gregg-miskelly** [comment]
@GraceDong Thanks! In that case this is more or less the same issue as https://github.com/dotnet/coreclr/issues/4623. Please avoid super tight loop in test debuggees until that is resolved (which is likely to be a long time).
