### ISSUE TITLE
Debugger: Some projects have trouble loading

### ISSUE THREAD

**Issue by GraceDong** [OmniSharp/omnisharp-vscode#900]
## Environment data
`dotnet --info` output:
VS Code version: 1.7.1
C# Extension version: 1.5-beta7
.NET Core SDK version: 1.0.0-preview4-004061

## Steps to reproduce
1. Download hwapp folder in attachments directly
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/580552/hwapp.zip)
2. Open the project in VSCode

## Expected  behavior
It has nothing warning

## Actual behavior
It show a warning as following:
![image](https://cloud.githubusercontent.com/assets/20184778/20136117/2839852c-a6ae-11e6-9338-cc94a03cbf3c.png)

And this is output information:
[output.txt](https://github.com/OmniSharp/omnisharp-vscode/files/580546/output.txt)

**Comment by gregg-miskelly** [comment]
@GraceDong the C# extension doesn't yet support loading .csproj based .NET Core projects. Please keep using project.json projects for now. See #881 for tracking support for .NET Core .csproj.
