### ISSUE TITLE
Debugger:Pause can't be normal debugging

### ISSUE THREAD

**Issue by v-zhanme** [OmniSharp/omnisharp-vscode#905]
## Environment data
`dotnet --info` output:
VS Code version: 1.7.1
C# Extension version: v.1.5.0-beta7
.NET Core version: 1.0.0-SDK Preview4

## Steps to reproduce
1.Download attached folder in attachments directly
[mytest.zip](https://github.com/OmniSharp/omnisharp-vscode/files/582713/mytest.zip)
2.Open the mytest project with VSCode.
3.Select the debug type ''.Net core Attach'
4.Choose the task type : .NET Core
5.F5 and start debugging
6.Hit pause
![image](https://cloud.githubusercontent.com/assets/20921752/20168386/e5062a4e-a75c-11e6-975a-e594a2aee781.png)

## Expected  behavior
The cursor will hit at line 18 or up and down.

## Actual behavior
Pause can't be normal debugging. It does not have any changes.

**Comment by v-zhanme** [comment]
This issue repro on windows 10 and Mac OS.

**Comment by rajkumar42** [comment]
@v-zhanme , can you please test with Preview2 SDK? Update the bug description if it also reproduces in preview2 as well. Thanks!

**Comment by gregg-miskelly** [comment]
@v-zhanme @rajkumar42 no need. I can repo this on my box. This is a VS Code issue.

**Comment by gregg-miskelly** [comment]
https://github.com/Microsoft/vscode/issues/15315 opened to track this.

**Comment by v-zhanme** [comment]
yes. It is repro the Preview 2 SDK.
