### ISSUE TITLE
Debugger fails to download on CentOS7

### ISSUE THREAD

**Issue by ClaireKang** [OmniSharp/omnisharp-vscode#910]
## Environment data
`dotnet --info` output:
VS Code version: 1.7.1
C# Extension version: v.1.5.0-beta7 & v1.5-future-preview1
.NET Core version: 1.0.0-preview2-003121
OS: CentOS7

## Steps to reproduce
1. Open vscode.
2. Install the C# extension (I tried to install v.1.5.0-beta7 & v1.5-future-preview1).

## Expected  behavior
Install successfully without error message

## Actual behavior
Pop up following error message:
![f5de4322](https://cloud.githubusercontent.com/assets/20184768/20208361/a40e0e2c-a828-11e6-8448-e085c75370a1.PNG)

Investigation:
I installed the extension on the other OS and it can be installed successfully.

**Comment by chuckries** [comment]
@ClaireKang can you give me the contents of the /etc/os-release file on your CentOS7 machine?

**Comment by gregg-miskelly** [comment]
We _think_ this issue should now be fixed. We think it was a CDN issue, and we resolved it by purging the CDN object and re-adding it.

**Comment by ClaireKang** [comment]
I have verified this issue use the latest c# extension(bate8), and it correctly been fixed.

**Comment by gregg-miskelly** [comment]
@ClaireKang Thanks!
