### ISSUE TITLE
ÅÄÖ (and equally weird characters, in strings) get borked when formatting code.

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#916]
_From @Southgrove on November 11, 2016 7:46_

- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.0.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|unity-debug|Unity|1.0.3|
|Theme-8-Colour-Dark|gerane|0.0.2|
|Theme-red|gerane|0.0.2|
|Theme-x3-alpha|gerane|0.0.2|
|omnisharp|ms-vscode|0.3.3|
|red|red-auto|0.0.4|

---

Steps to Reproduce:

1.
2.

_Copied from original issue: Microsoft/vscode#15332_

**Comment by aeschli** [comment]
For what language is that?

**Comment by aeschli** [comment]
_From @Southgrove on November 11, 2016 20:43_

Oh, sorry. C#.

**Comment by DustinCampbell** [comment]
@Southgrove: Is this still an issue? Do you have any repro steps?

**Comment by DustinCampbell** [comment]
I seem to recall that there was a formatting issue introduced in VS Code awhile back that broke formatting in C# for VS Code as well. I *suspect* this may have been the issue here.

**Comment by Southgrove** [comment]
Ah, sorry I didn't respond. Yes it seems to be fixed.

**Comment by DustinCampbell** [comment]
Great -- thanks for confirming!
