### ISSUE TITLE
[Windows] DebugAdapter bin folder not found on path 

### ISSUE THREAD

**Issue by zach-folwick** [OmniSharp/omnisharp-vscode#92]
DebugAdapter bin folder not found on path C:/..../.vscode/extensions/ms-vscode.csharp-0.3.7/coreclr-debug/debugAdapters/OpenDebugAD7.exe.

Dotnet-Cli info:
OS: Windows 10
dotnet-cli:
Version: 1.0.0-beta-001598
Commit Sha: 7582649f88

This is on a brand new install of VSCode.  Works in linux.  

```
error: The supplied user buffer is not valid for the requested operation
dotnet exited with error code 1
Error while installing .NET Core Debugger.
```

**Comment by chuckries** [comment]
Have you opened a csharp file after installing the C# extension? The acquisition of the debugger bits for the specific platform you are on will not be triggered until a C# file is opened.

**Comment by chuckries** [comment]
Nevermind, I see that the the acquisition is triggered and failing. Is there an install.log file in C:/..../.vscode/extensions/ms-vscode.csharp-0.3.7/coreclr-debug?

**Comment by zach-folwick** [comment]
There is.  I appear to not have access to this file?

**Comment by chuckries** [comment]
That is strange. Are you an administrator on the box?

**Comment by zach-folwick** [comment]
I am opening notepad++ as administrator, and attempting to open the file. 
Getting the following:

![image](https://cloud.githubusercontent.com/assets/16566940/13753096/dfc025c2-e9ce-11e5-84b6-55cc833c148a.png)

**Comment by chuckries** [comment]
I'm not sure why you're seeing this. Here's what I would try:
1. Close all VS Code instances.
2. Delete the debugAdapters directory inside C:/..../.vscode/extensions/ms-vscode.csharp-0.3.7/coreclr-debug.
3. Completely uninstall your current dotnet cli from Control Panel -> Programs -> Programs and Features.
4. Reinstall the dotnet cli from here: https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/1.0.0.001661/dotnet-win-x64.1.0.0.001661.exe (this version supports portable pdb's on windows).
5. Open VS Code and open a C# file, triggering the acquisition of the debugger again.

**Comment by zach-folwick** [comment]
that link just keeps asking if I want to download the C# extensions.  Even after downloading + restarting.

**Comment by chuckries** [comment]
what is "that link"?

**Comment by chuckries** [comment]
@zach-folwick Do you have any more information on this?

**Comment by sessionliang** [comment]
This problem has be solved?
I come with the same one.But I think that focus on the version of .NET Core?
[https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md)

**Comment by sessionliang** [comment]
@zach-folwick you can try open [.vscode\extensions\ms-vscode.csharp-0.3.7] by VSC, then publish.

**Comment by zhanzushun** [comment]
Downloading and configuring the .NET Core Debugger...
log  : Restoring packages for C:\Users\Zushun\.vscode\extensions\ms-vscode.csharp-0.3.7\coreclr-debug\project.json...
info : Committing restore...
log  : Lock file has not changed. Skipping lock file write. Path: C:\Users\Zushun\.vscode\extensions\ms-vscode.csharp-0.3.7\coreclr-debug\project.lock.json
log  : C:\Users\Zushun\.vscode\extensions\ms-vscode.csharp-0.3.7\coreclr-debug\project.json
log  : Restore completed in 2072ms.

NuGet Config files used:
    C:\Users\Zushun\.vscode\extensions\ms-vscode.csharp-0.3.7\coreclr-debug\NuGet.config

Feeds used:
    https://www.myget.org/F/dotnet-core/api/v3/index.json
    https://api.nuget.org/v3/index.json
    https://www.myget.org/F/coreclr-debug/api/v3/index.json
Publishing dummy for DNXCore,Version=v5.0
Project dummy (DNXCore,Version=v5.0) was previously compiled. Skipping compilation.
Publishing dummy 1.0.0 ...
Publishing Microsoft.CSharp 4.0.1-rc3-23829 ...
Publishing Microsoft.DotNet.CoreHost 0.0.1-beta-00001 ...
Publishing Microsoft.NETCore.Platforms 1.0.1-rc3-23829 ...
Publishing Microsoft.NETCore.Runtime 1.0.2-rc3-23829 ...
Publishing Microsoft.NETCore.Runtime.CoreCLR 1.0.2-rc3-23829 ...
Publishing Microsoft.NETCore.Runtime.Native 1.0.2-rc3-23829 ...
Publishing Microsoft.NETCore.Targets 1.0.1-rc3-23829 ...
Publishing Microsoft.NETCore.Targets.DNXCore 5.0.0-rc3-23829 ...
Publishing Microsoft.NETCore.Windows.ApiSets 1.0.1-rc3-23829 ...
Publishing Microsoft.VisualStudio.clrdbg 14.0.25109-preview-2865786 ...
Publishing Microsoft.VisualStudio.clrdbg.MIEngine 14.0.30309-preview-2 ...
Publishing Microsoft.VisualStudio.Debugger.Interop.Portable 1.0.1 ...
Publishing Microsoft.VisualStudio.OpenDebugAD7 1.0.20308-preview-1 ...
Publishing Microsoft.Win32.Primitives 4.0.1-rc3-23829 ...
Publishing NETStandard.Library 1.0.0-rc3-23829 ...
Publishing NETStandard.Platform 1.0.0-rc3-23829 ...
Publishing Newtonsoft.Json 7.0.1 ...
Publishing System.AppContext 4.1.0-rc3-23829 ...
Publishing System.Collections 4.0.11-rc3-23829 ...
Publishing System.Collections.Concurrent 4.0.12-rc3-23829 ...
Publishing System.Collections.Immutable 1.2.0-rc3-23829 ...
Publishing System.Collections.NonGeneric 4.0.1-rc3-23829 ...
Publishing System.Collections.Specialized 4.0.1-rc3-23829 ...
Publishing System.ComponentModel 4.0.1-rc3-23829 ...
Publishing System.ComponentModel.Annotations 4.1.0-rc3-23829 ...
Publishing System.ComponentModel.EventBasedAsync 4.0.11-rc3-23829 ...
Publishing System.Console 4.0.0-rc3-23829 ...
Publishing System.Diagnostics.Contracts 4.0.1-rc3-23829 ...
Publishing System.Diagnostics.Debug 4.0.11-rc3-23829 ...
Publishing System.Diagnostics.Process 4.1.0-rc3-23829 ...
Publishing System.Diagnostics.StackTrace 4.0.1-rc3-23829 ...
Publishing System.Diagnostics.Tools 4.0.1-rc3-23829 ...
Publishing System.Diagnostics.Tracing 4.1.0-rc3-23829 ...
Publishing System.Dynamic.Runtime 4.0.11-rc3-23829 ...
Publishing System.Globalization 4.0.11-rc3-23829 ...
Publishing System.Globalization.Calendars 4.0.1-rc3-23829 ...
Publishing System.Globalization.Extensions 4.0.1-rc3-23829 ...
Publishing System.IO 4.1.0-rc3-23829 ...
Publishing System.IO.FileSystem 4.0.1-rc3-23829 ...
Publishing System.IO.FileSystem.Primitives 4.0.1-rc3-23829 ...
Publishing System.Linq 4.1.0-rc3-23829 ...
Publishing System.Linq.Expressions 4.0.11-rc3-23829 ...
Publishing System.Net.Http 4.0.1-rc3-23829 ...
Publishing System.Net.Primitives 4.0.11-rc3-23829 ...
Publishing System.Net.Sockets 4.1.0-rc3-23829 ...
Publishing System.ObjectModel 4.0.11-rc3-23829 ...
Publishing System.Reflection 4.1.0-rc3-23829 ...
Publishing System.Reflection.Emit 4.0.1-rc3-23829 ...
Publishing System.Reflection.Emit.ILGeneration 4.0.1-rc3-23829 ...
Publishing System.Reflection.Extensions 4.0.1-rc3-23829 ...
Publishing System.Reflection.Primitives 4.0.1-rc3-23829 ...
Publishing System.Reflection.TypeExtensions 4.1.0-rc3-23829 ...
Publishing System.Resources.ResourceManager 4.0.1-rc3-23829 ...
Publishing System.Runtime 4.1.0-rc3-23829 ...
Publishing System.Runtime.Extensions 4.1.0-rc3-23829 ...
Publishing System.Runtime.Handles 4.0.1-rc3-23829 ...
Publishing System.Runtime.InteropServices 4.1.0-rc3-23829 ...
Publishing System.Runtime.InteropServices.PInvoke 4.0.0-rc3-23829 ...
Publishing System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc3-23829 ...
Publishing System.Runtime.Numerics 4.0.1-rc3-23829 ...
Publishing System.Runtime.Serialization.Primitives 4.1.0-rc3-23829 ...
Publishing System.Security.Cryptography.Algorithms 4.0.0-rc3-23829 ...
Publishing System.Security.Cryptography.Primitives 4.0.0-rc3-23829 ...
Publishing System.Text.Encoding 4.0.11-rc3-23829 ...
Publishing System.Text.Encoding.Extensions 4.0.11-rc3-23829 ...
Publishing System.Text.RegularExpressions 4.0.12-rc3-23829 ...
Publishing System.Threading 4.0.11-rc3-23829 ...
Publishing System.Threading.Tasks 4.0.11-rc3-23829 ...
Publishing System.Threading.Tasks.Dataflow 4.6.0-rc3-23829 ...
Publishing System.Threading.Tasks.Extensions 4.0.0-rc3-23829 ...
Publishing System.Threading.Tasks.Parallel 4.0.1-rc3-23829 ...
Publishing System.Threading.Thread 4.0.0-rc3-23829 ...
Publishing System.Threading.Timer 4.0.1-rc3-23829 ...
Publishing System.Xml.ReaderWriter 4.0.11-rc3-23829 ...
Publishing System.Xml.XDocument 4.0.11-rc3-23829 ...
Publishing System.Xml.XmlDocument 4.0.1-rc3-23829 ...
Publishing System.Xml.XmlSerializer 4.0.11-rc3-23829 ...
Published to C:\Users\Zushun\.vscode\extensions\ms-vscode.csharp-0.3.7\coreclr-debug\debugAdapters
Published 1/1 projects successfully
Error while installing .NET Core Debugger.

**Comment by zhanzushun** [comment]
My environment:
>dotnet --version
1.0.0-beta-002202
> code --version
0.10.11

**Comment by gregg-miskelly** [comment]
There have been breaking changes in very recent builds of the .NET CLI that cause problems for the 0.37 version of the extension. If you don't care what version of the .NET CLI you use, I would recommend using the instructions on http://dotnet.github.io/getting-started/. If you need to be on newer bits, you can try building the package from the 'dev' branch of this repo.

**Comment by DustinCampbell** [comment]
The latest version of the extension available [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.0.0-rc2) should work with the latest builds of the .NET CLI.

**Comment by zhanzushun** [comment]
@DustinCampbell  The latest version works perfectly on my machine. Cool~ thanks.

**Comment by DustinCampbell** [comment]
Excellent! That's great to hear.
