### ISSUE TITLE
Display issue with custom window.zoomLevel

### ISSUE THREAD

**Issue by schenkfab** [OmniSharp/omnisharp-vscode#924]
## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003148)

Product Information:
 Version:            1.0.0-preview2-003148
 Commit SHA-1 hash:  18ca244551

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version: 1.7.1
C# Extension version: 1.4.1

## Steps to reproduce
Set "window.zoomLevel" to anything other than 0 (e.g. 0.4). In settings.json

## Expected  behavior

Number of references should be directly on top of the method

<img width="640" alt="screen shot 2016-11-12 at 22 48 39" src="https://cloud.githubusercontent.com/assets/10050222/20242318/9fa117c8-a92a-11e6-8449-761d2c4134e6.png">

## Actual behavior

Number of references is located on the left side of the screen.

<img width="973" alt="screen shot 2016-11-12 at 22 48 26" src="https://cloud.githubusercontent.com/assets/10050222/20242315/906ee546-a92a-11e6-80ce-f2c5c376130f.png">

**Comment by DustinCampbell** [comment]
This is a known issue for VS Code: https://github.com/Microsoft/vscode/issues/14949
