### ISSUE TITLE
Mac OX.Legacy C#. Extract class interface crash

### ISSUE THREAD

**Issue by vahpetr** [OmniSharp/omnisharp-vscode#925]
## Environment data
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64

Mono JIT compiler version 4.6.1 (mono-4.6.0-branch-c8sr0/ef43c15 Mon Oct  3 14:35:32 EDT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/8b1520c)
	GC:            sgen

VS Code version:

1.7.1
02611b40b24c9df2726ad8b33f5ef5f67ac30b44

C# Extension version:

v1.5-beta8 (and various stable previous version)

### Extensions list:

avidAnson.vscode-markdownlint@0.5.0
EditorConfig.EditorConfig@0.3.4
GregorBiswanger.json2ts@0.0.6
cssho.vscode-svgviewer@1.2.0
dbaeumer.vscode-eslint@1.1.0
dbalage.vscode-stylesheet-formatter@0.2.0
donjayamanne.githistory@0.1.0
donjayamanne.javadebugger@0.0.2
eg2.tslint@0.5.40
joelday.docthis@0.3.5
k--kato.docomment@0.0.7
ms-vscode.Theme-MarkdownKit@0.1.1
ms-vscode.csharp@1.5.0-beta8
ms-vscode.mono-debug@0.11.0
ms-vscode.omnisharp@0.3.3
msjsdiag.debugger-for-chrome@2.2.2
naumovs.node-modules-resolve@1.0.2
seanmcbreen.Spell@0.8.6
vladmrnv.expresssnippet@0.0.8
wcwhitehead.bootstrap-3-snippets@0.0.8

## Steps to reproduce
Select C# class -> cmd+. ->Extract Interface

## Expected  behavior

Did create interface

## Actual behavior

Error. Problem invoking 'RunCodeAction' on OmniSharp server: null

### OmniSharp log
Starting OmniSharp server at 13.11.2016, 11:12:21
    Target: /Users/pyotrvasilev/Documents/projects/csharp-cgdk/csharp-cgdk.sln

OmniSharp server started wth Mono
    Path: /Users/pyotrvasilev/.vscode/extensions/ms-vscode.csharp-1.4.1/out/.omnisharp-mono/OmniSharp.exe
    PID: 77979

OmniSharp: -s /Users/pyotrvasilev/Documents/projects/csharp-cgdk/csharp-cgdk.sln --hostPID 77957 DotNet:enablePackageRestore=false --encoding utf-8 --stdio
﻿﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/Users/pyotrvasilev/Documents/projects/csharp-cgdk' on host 77957."},"Seq":1,"Type":"event"}
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /Users/pyotrvasilev/Documents/projects/csharp-cgdk
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp#MSBuild] Detecting projects in '/Users/pyotrvasilev/Documents/projects/csharp-cgdk/csharp-cgdk.sln'.
[INFORMATION:OmniSharp#MSBuild] Loading project from '/Users/pyotrvasilev/Documents/projects/csharp-cgdk/csharp-cgdk.csproj'.
[WARNING:OmniSharp#ProjectFileInfo] TargetFrameworkVersion 'v4.6.1' not supported by this toolset (ToolsVersion: 4.0).
/Users/pyotrvasilev/Documents/projects/csharp-cgdk/csharp-cgdk.csproj

[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in '/Users/pyotrvasilev/Documents/projects/csharp-cgdk'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Configuration finished.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /projects: 200 71ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /projects: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /projects: 200 0ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 562ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /typelookup: 200 655ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 511ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 70ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 129ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 3ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 423ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 200 10ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /codecheck: 200 524ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /gotoDefinition: 200 14ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 117ms
[INFORMATION:OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService] Applying Microsoft.CodeAnalysis.ExtractInterface.ExtractInterfaceCodeAction
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/runcodeaction: 500 162ms

**Comment by DustinCampbell** [comment]
The problem here is that the Extract Interface refactoring wants to display a dialog for picking members. We shouldn't offer this code action unless we can do that.
