### ISSUE TITLE
Format document with conditional compilation in C# will not format code ignored by condition

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#926]
_From @PeterHimschoot on November 13, 2016 11:31_

- VSCode Version:
- OS Version:

Steps to Reproduce:

1. For example, this code:
#define WITH_DISPOSE

using System;

namespace HiddenIDisposables
{
#if WITH_DISPOSE
    public class SomeResource : ISomeResource, IDisposable
    {
        public string Foo()
        {
            return "Foo";
        }

        void IDisposable.Dispose()
        {
            System.Console.WriteLine("Resource has been disposed");
        }
    }
#else
    public class SomeResource : ISomeResource
    {
        public string Foo()
    {
                      return "Foo";
              }
    }
#endif
}

2. Format document ignores the #else part

_Copied from original issue: Microsoft/vscode#15423_

**Comment by DustinCampbell** [comment]
This is by design and works the same as it does in Visual Studio. Disabled blocks are simply never parsed. Remember that *anything* can go in disabled blocks of code, including random non-C# text.
