### ISSUE TITLE
Create commands for running/debugging tests

### ISSUE THREAD

**Issue by nick-korsakov** [OmniSharp/omnisharp-vscode#929]
## Steps to reproduce
Use this keybindings.json in the Visual Studio Code 1.7.1:
```json
[
    {
        "key": "alt+f5",
        "command": "dotnet.test.debug"
    }
]
```
Set breakpoint inside test method, point the cursor inside the test method and hit Alt+F5.

P.S.: Don't offer me to use mouse and click "debug test" link (this one works). I like to hide reference info links and use hotkeys to execute an actions.

## Expected  behavior
Current test executed in debug mode as it happes when I click "debug test" link above this test method.

## Actual behavior
Debug session doesn't started.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by DustinCampbell** [comment]
Hi, what version of the C# extension do you have installed?

**Comment by nick-korsakov** [comment]
C# for Visual Studio Code (powered by OmniSharp). Version 1.5.2.

**Comment by nick-korsakov** [comment]
When I use this keybindings.json I recieve an error: "Failed to run test because null" with "Running test [object Object]..." in the output window:
```json
[
    {
        "key": "alt+f5",
        "command": "dotnet.test.run"
    }
]
```

**Comment by DustinCampbell** [comment]
The problem is that this command specifically expects arguments to be passed with the test method name: https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/features/dotnetTest.ts#L24-L28.

**Comment by nick-korsakov** [comment]
Is it possible to infer arguments from the context (cursor position inside the test method) and pass them to the command? It's necessary for both commands ("dotnet.test.debug" and "dotnet.test.run").

**Comment by DustinCampbell** [comment]
I'm going to repurpose this issue to track adding commands.

**Comment by DustinCampbell** [comment]
Actually, we already have an issue tracking that: https://github.com/OmniSharp/omnisharp-vscode/issues/421. We'll use that issue.
