### ISSUE TITLE
Code formatting does not obey editor.insertSpaces

### ISSUE THREAD

**Issue by alexandrudima** [OmniSharp/omnisharp-vscode#93]
Moved from Microsoft/vscode#3847
I have verified that we call on our side the format on type provider with the configured indentation options.

---

From @nixbb
It seems that the code formatter does not adhere to the indentation mode specified in the user settings.

Here's a simple example using version 0.10.10
In this case "editor.insertSpaces" is set to "auto" but this issue also manifests if it's set to false.
![codeformattingbug](https://cloud.githubusercontent.com/assets/958979/13603388/929fa584-e545-11e5-9009-8b55a45481d9.gif)

The example shows that all the indentation starts off as tabs.
The newly added line (line 11) is also indented using tabs.
When the statement is finished with a semicolon the current line and the next line is then indented with spaces.

Not shown in the gif is that an undo will revert line 11 and 12 to tabs instead of spaces.

Hope this helps narrow down the issue.

**Comment by 0xdeafcafe** [comment]
Any updates on this? It's incredibly annoying.

**Comment by anfomin** [comment]
Is is alive?

**Comment by pavlos256** [comment]
Is this the reason that the "implement interface" uses spaces instead of tabs or should I file a new bug?

**Comment by 0xdeafcafe** [comment]
@pavlos256 Same reason. It runs the format command on the relevant lines, which uses spaces.

**Comment by ivanz** [comment]
For a workaround see here (how to use `omnisharp.json`): https://github.com/OmniSharp/omnisharp-roslyn/issues/366
