### ISSUE TITLE
References label/tag UI Bug

### ISSUE THREAD

**Issue by bsell93** [OmniSharp/omnisharp-vscode#935]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
```
VS Code version: 1.7.1
C# Extension version: 1.5.1

## Steps to reproduce
- Run VSCode
- Open `.cs` file

## Expected  behavior
References label/tag appear next to appropriate line and properly aligned

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/5335177/20292507/0b9fa830-aabc-11e6-8597-1a94dc3064d1.png)

**Comment by DustinCampbell** [comment]
This is a known Visual Studio Code issue: https://github.com/Microsoft/vscode/issues/14949
