### ISSUE TITLE
CodeLens (or Code Annotations): links for detected unit tests appear in random order

### ISSUE THREAD

**Issue by dmccaffery** [OmniSharp/omnisharp-vscode#936]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64

VS Code version:

1.7.1
02611b40b24c9df2726ad8b33f5ef5f67ac30b44

C# Extension version:

1.5.1

OS Version:

macOS 10.12.2 (16C41b)

## Steps to reproduce

Load any project containing unit tests (written in xunit)... currently using the following dependencies:

```json
{
  "version": "2.0.0-*",
  "testRunner": "xunit",

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },

    "Newtonsoft.Json": "*",

    "Moq": "4.6.36-*",
    "xunit": "2.2.0-*",
    "dotnet-test-xunit": "2.2.0-*",

    "PulseBridge.Clients": "1.0.0-*",
    "PulseBridge.Extensions.Xunit": "1.0.0-*"
  },

  "frameworks": {
    "netcoreapp1.0": { }
  }
}
```

## Expected  behavior

Code annotations should appear in a consistent order, preferrably

X references | run test | debug test

## Actual behavior

Code annotations can appear in any order, including:

X references | run test | debug test (this makes the most sense)
<img width="254" alt="screen shot 2016-11-15 at 12 43 51 am" src="https://cloud.githubusercontent.com/assets/1803684/20298773/a012b6be-aacc-11e6-86e3-4d137f5b6d70.png">

run test | X references | debug test
<img width="239" alt="screen shot 2016-11-15 at 12 49 26 am" src="https://cloud.githubusercontent.com/assets/1803684/20299030/db2d08fc-aacd-11e6-82bb-88f9ec5de3bd.png">

run test | debug test | X references
<img width="263" alt="screen shot 2016-11-15 at 12 43 23 am" src="https://cloud.githubusercontent.com/assets/1803684/20298758/8b49b6a6-aacc-11e6-9322-22bd27128029.png">

X references | debug test | run test
<img width="239" alt="screen shot 2016-11-15 at 12 42 59 am" src="https://cloud.githubusercontent.com/assets/1803684/20298787/b9c097ac-aacc-11e6-8be9-89b5cba42a39.png">

I'm sure every order is possible given the behavior, but these are the ones for which I can gather evidence at the moment.

**Comment by dmccaffery** [comment]
Hmm... based on this implementation, it would appear that the order *should* be deterministic:

https://github.com/OmniSharp/omnisharp-vscode/blob/3e996e3bd66c357d3f3488549bf06472d10b277f/src/features/dotnetTest.ts#L75

Perhaps this issue is caused by vscode itself? I'm not 100% sure how the positioning is controlled when resolving/rendering; didn't find a related issue on vscode repo, but maybe I missed it.

**Comment by dmccaffery** [comment]
Did find this: https://github.com/Microsoft/vscode/issues/10061

Seems to have been resolved on their end (supposedly), so unless its a regression in the October release, something is going haywire with the way that the omnisharp plugin is ordering the xunit test CodeLens annotations.

**Comment by DustinCampbell** [comment]
I haven't seen this in a long time. Have you @dmccaffery?

**Comment by dmccaffery** [comment]
@DustinCampbell I will look tomorrow; heading to bed for now. :)

**Comment by DustinCampbell** [comment]
Nevermind. I was able to reproduce it. Just hadn't noticed it in awhile.

![image](https://cloud.githubusercontent.com/assets/116161/22737965/49ff6b88-edba-11e6-80bd-124933636ca0.png)

**Comment by DustinCampbell** [comment]
Also, taking a look at the CodeLensProvider, it appears that the indicators for "debug test" and "run test" were somewhat hacked in. I can imagine that there's a bug here in the extension.

**Comment by dmccaffery** [comment]
Closing. Super-old; no longer an issue.
