### ISSUE TITLE
JustMyCode is always enabled when using "debug test" CodeLens annotation link

### ISSUE THREAD

**Issue by dmccaffery** [OmniSharp/omnisharp-vscode#940]
## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003148)

Product Information:
 Version:            1.0.0-preview2-003148
 Commit SHA-1 hash:  18ca244551

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64

VS Code version:

1.7.1
02611b40b24c9df2726ad8b33f5ef5f67ac30b44

C# Extension version:

1.5.1

## Steps to reproduce

1. Open any project containing unit tests
2. Add a [DebuggerStepThrough] attribute to a method called from the unit test
3. Add a breakpoint inside the [DebuggerStepThrough] method
4. Click the "debug test" CodeLens annotation link

## Expected  behavior

Disable _JustMyCode_ by default when debugging is activated from the "debug test" CodeLens annotation link

**OR**

Add an OmniSharp setting (user/workspace setting) that allows the _JustMyCode_ flag to be overridden for the "debug test" CodeLens annotation link:

```json
"omnisharp.codelens.justmycode": false
```

**OR**

Allow a uniquely identified *configuration* to be included in launch.json that OmniSharp will use when activating the debugger from CodeLens (if present) before falling through to the defaults.

```json
{
    "name": "OmniSharp CodeLens",
    "type": "coreclr",
    "request": "launch",
    "justMyCode": false
}
```

## Actual behavior

The configurations specified in launch.json are seemingly completely ignored, but now that _JustMyCode_ is enabled by default, it is impossible to step into external code or code decorated with the [DebuggerStepThrough] attribute when using the "debug test" CodeLens annotation link.

**Comment by gregg-miskelly** [comment]
@dmccaffery The debugger will always respect DebuggerStepThrough - there is no way to hit breakpoints in those methods unless you remove that attribute. If you want stepping behavior that goes away when JMC is off, use DebuggerNonUserCode. So we can certainly leave this bug open for other reasons, but it will not actually help the exact scenario you described.

For reference, I believe this is the code that will need to be enhanced to enable this: https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/features/dotnetTest.ts#L60

**Comment by dmccaffery** [comment]
Hmmm. Disabling JustMyCode allows you to hit [DebuggerStepThrough] in my experience (and I just checked). I set this up as an arbitrary example to make the point without having to create a repro that relied on symbols and source mappings.

**Comment by gregg-miskelly** [comment]
@dmccaffery I just double checked. I guess we actually do let you hit breakpoints in it. But we will not let you step in that code. So I wouldn't really recommend that as a way to debug DebuggerStepThrough, but I guess it can work in a real pinch...

**Comment by dmccaffery** [comment]
@gregg-miskelly agreed. i very, rarely use it... it was honestly just a fast way to setup the repro to surface the issue and the resulting request :)

**Comment by DustinCampbell** [comment]
PR #1446 adds the ability to specify a `csharp.unitTestDebugingOptions` option where you can set various debugger options, such as `justMyCode`.
