### ISSUE TITLE
Debugging C# on macOS

### ISSUE THREAD

**Issue by iflores782** [OmniSharp/omnisharp-vscode#952]
## Environment data
`dotnet --info` output:
VS Code version: 1.7.1
C# Extension version: 1.5.1
macOS version: 10.12.1

## Steps to reproduce
I'm teaching myself C#. I wrote a hello world program (the .cs file is in a vs code folder in my documents folder). I got to debug it and hit run.

## Expected  behavior
It runs and prints "Hello, world!".

## Actual behavior
.net quits unexpectedly. I get the error message "launch: launch.json must be configured. Change 'program' to the path to the executable file you want to debug."

**Comment by DustinCampbell** [comment]
Hi @iflores782 -- From your description, it sounds like you need to install .NET Core and create a C# project. @kendrahavens has uploaded an excellent video showing how to get started with C# on macOS with VS Code here: https://channel9.msdn.com/Blogs/dotnet/Get-started-with-VS-Code-using-CSharp-and-NET-Core-on-MacOS. It goes all the way from getting installed to hitting a breakpoint.

**Comment by dmccaffery** [comment]
Welcome to C# @iflores782 ... as a .net dev expert and an apple fanboy; welcome to the best language in the world! :-D ... Let me know if you have any questions after watching that video ... you can mention me in the OmniSharp #Slack or reach out to me anywhere and I'll get back to you. :)

**Comment by iflores782** [comment]
@dmccaffery @DustinCampbell Thanks for the video recommendation. I followed those steps and probably solved a few problems, but I'm getting the same error.

**Comment by dmccaffery** [comment]
@iflores782 are you familiar with git? can you push your code to a public repo and I can take a look? make sure you use the following gitignore:

https://raw.githubusercontent.com/github/gitignore/master/VisualStudio.gitignore

**Comment by DustinCampbell** [comment]
@iflores782: You should have been prompted to generate assets for debugging and building. Did you do this? If not, try the following:

1. Select `View->Command Palette...` from the menu.
2. Type "generate" followed by ENTER.

![image](https://cloud.githubusercontent.com/assets/116161/20330705/87a0338e-ab55-11e6-892d-5b011e5be8e9.png)

This should generate a launch.json and tasks.json file for you.

**Comment by dmccaffery** [comment]
... too much automation; vscode is starting to feel like an IDE... :-P lolol

**Comment by iflores782** [comment]
https://github.com/iflores782/macos-help

**Comment by dmccaffery** [comment]
@iflores782 the only issue was that you were missing the launch.json and task.json files, which are used by VSCode to configure the debugger -- its not a dotnet specific issue, its a vscode integration issue. I've forked your code, added the necessary config, and created a pull request:

https://github.com/iflores782/macos-help/pull/1

You can look at the diff to see what I have done. To generate these files for a new C# project, you need to use the palette cmd referenced by @DustinCampbell earlier: ".NET: Generate Assets for Build and Debug". To do this on a mac, hit CMD+SHIFT+P (to bring up the command palette) and type "generate" to isolate the necessary command. You only need to do this once.

Some other things to note:

1) don't add/track project.lock.json to/in a repo; this is a 'temporary' file used to create the dependency and runtime graph for your current target.

2) make sure you run "dotnet restore" (CMD+SHIFT+P, restore) if you ever change the dependencies in a project.json file... the C# plugin should alert you to do this if you forget.

3) Have fun!

<img width="680" alt="screen shot 2016-11-15 at 5 46 02 pm" src="https://cloud.githubusercontent.com/assets/1803684/20331624/6a6ca652-ab5b-11e6-9e97-23200ef65d64.png">

**Comment by iflores782** [comment]
Generate and restore say it could not locate .net core project.

**Comment by dmccaffery** [comment]
did you open up vscode to the working path (root) of the repo? I believe it will only scan the root of the working path for either a project.json or a global.json. I don't know what else could be the issue.

**Comment by DustinCampbell** [comment]
I suspect you're opening the C# file on its own. Try using File->Open Folder and opening the whole directory including the C# file and the project.json file.

**Comment by DustinCampbell** [comment]
@iflores782, were you able to get things working?

**Comment by iflores782** [comment]
Yes, but now when I read in from the console it stops working. I'm doing [this](https://msdn.microsoft.com/en-us/library/aa288470(v=vs.71).aspx) tutorial, but I changed it from person.name = "Joe" to person.name = Console.ReadLine(). When I input a name ("bill"), it says Unable to perform this action because the process is running.
Could you help with that?

**Comment by DustinCampbell** [comment]
Could you provide a bit more detail? Where do you enter "bill"? Did you stop the application from debugging while changing the code?

**Comment by DustinCampbell** [comment]
cc @gregg-miskelly

**Comment by gregg-miskelly** [comment]
@iflores782 if you are going to use Console.ReadLine, make sure to [enable the external console](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md#external-console-terminal-window) in your launch.json file. This should pop up a new terminal window that will let you enter text.

**Comment by DustinCampbell** [comment]
Thanks @gregg-miskelly! I'd completely forgotten about that setting.

**Comment by iflores782** [comment]
@gregg-miskelly @DustinCampbell Yup that was it. I set enable external console to true and it ran fine.

**Comment by DustinCampbell** [comment]
awesome. Glad you got things working. Good luck! Let us know if you run into any other problems
