### ISSUE TITLE
Debugger doesn't support Ubuntu 16.10

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#956]
1. Follow instructions on https://www.microsoft.com/net/core#linuxubuntu to install .NET CLI for Ubuntu 16.10
2. Install VS Code + C# extension

Result:
[WARNING]: The current Linux distribution 'ubuntu' version '16.10' is not currently supported by the .NET Core debugger.

**Comment by fedihor** [comment]
When Ubuntu 16.10 support will be added?

**Comment by gregg-miskelly** [comment]
We don't have supper hard dead lines, but barring something unexpected, I would guess early to mid December.

**Comment by gregg-miskelly** [comment]
@fedihor I've created a [v1.6-beta3](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.6-beta3) release of the C# extension that should address this. See this page for information on [installing beta releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases).
