### ISSUE TITLE
Downloading package 'Mono Runtime (macOS)' Failed at stage: downloadPackages Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by Jamie-McCaw** [OmniSharp/omnisharp-vscode#957]
## Environment data
`dotnet --info` output:.
NET Command Line Tools (1.0.0-preview2-003148)

Product Information:
 Version:            1.0.0-preview2-003148
 Commit SHA-1 hash:  18ca244551

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
VS Code version: 1.7.1
C# Extension version:1.5.2

## Steps to reproduce
Installed Visual Studio Code for Mac OS
Opened VS Code
Because Firewall Set user settings: 
{
    "http.proxyStrictSSL": false
} 
Installed C# for VS Code
Make new dotnet app in terminal
Open dotnet app folder

## Expected  behavior
Normal Behavior

## Actual behavior
Alert = An error occurred during installation of the .NET Core Debugger. The C# extension may need to be reinstalled.

C# Output: 

Updating C# dependencies...
Platform: darwin, x86_64 (osx.10.11-x64)

Downloading package 'Mono Runtime (macOS)' Failed at stage: downloadPackages
Error: self signed certificate in certificate chain

Finished
[ERROR]: C# Extension failed to install the debugger package

Tried reinstall VS Code, Mono, an the C# Extension multiple times.

**Comment by DustinCampbell** [comment]
Hmmm... are you able to download from the following link? https://omnisharpdownload.blob.core.windows.net/ext/mono.osx-4.6.1.zip

**Comment by gregg-miskelly** [comment]
Also, do you somehow have a proxy enabled (ex: "http.proxy" option, or environment variable)?

**Comment by Jamie-McCaw** [comment]
@DustinCampbell I am able to download from that link.

@gregg-miskelly I don't believe I have any environment variables set. Not sure about the "http.proxy" option, except the User Settings one in VS Code I set to allow me to install extensions 
{
"http.proxyStrictSSL": false
}

**Comment by DustinCampbell** [comment]
Hmmm... @gregg-miskelly: it looks like we'll never use that option unless http.proxy is set.

**Comment by DustinCampbell** [comment]
I bet we also need to set `rejectUnauthorized` [here](https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/packages.ts#L176) using the value of `strictSSL`.

**Comment by gregg-miskelly** [comment]
Yup: https://github.com/Microsoft/vscode/blob/2f76c44632b0d47ba97f66fbc158c763628e30b3/src/vs/base/node/proxy.ts#L47

**Comment by DustinCampbell** [comment]
@Jamie-McCaw: I've produced the first beta of our next release which should address this problem. Could you install it and try it out? You can follow the steps below to install the beta:

1. Open Visual Studio Code and select View->Extensions to display the Extensions Pane.
2. In the Extensions pane, clear the little gear icon for the C# extension and select "Uninstall". Confirm Visual Studio Code's prompts and allow it to reload.
3. Download the latest beta .vsix [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.6-beta1).
4. In the Extensions pane, click the [...] in the top-right corner and select "Install from VSIX...". Locate the .vsix you just download and click "Open".
5. Allow Visual Studio Code to reload and open your project.

Let me know if the downloads work for you now.

**Comment by garoyeri** [comment]
This resolves the issue for me on Windows using VSCode 1.7.1.

**Comment by DustinCampbell** [comment]
Excellent! Thanks for letting me know

**Comment by JoeRobich** [comment]
@HjoshM Sorry the storage account that used to host these old packages has been removed. Meaning these packages are no longer available for download.
