### ISSUE TITLE
Cannot watch global variables in Unity

### ISSUE THREAD

**Issue by CoenraadS** [OmniSharp/omnisharp-vscode#959]
## Environment data
Unity b11
VS Code version: 1.7.1
C# Extension version: 1.5.2

## Steps to reproduce

`public class test : MonoBehaviour {

	public int x = 5;
	// Use this for initialization
	void Start () {
		
	}
	
	// Update is called once per frame
	void Update () {
		int y = this.x + 1;
		int z = x + 1;
	}
}`

Add watch to `x`, and `this.x` in the `Update()` method

## Expected  behavior
`x` and `this.x` should show same value

## Actual behavior
![0](https://cloud.githubusercontent.com/assets/5593825/20365682/22735376-ac48-11e6-8029-57ba86bc06a2.png)

**Comment by DustinCampbell** [comment]
If you're using the Debugger for Unity extension, you'll need to file that issue for that extension here: https://github.com/Unity-Technologies/vscode-unity-debug/issues.

**Comment by CoenraadS** [comment]
An issue exists: https://github.com/Unity-Technologies/vscode-unity-debug/issues/15

>The issue is that we do not do any analysis of the C# source code and the debugger protocol does not provide it either. 

Maybe something can be worked out.

**Comment by DustinCampbell** [comment]
Possibly, but it's definitely not an issue we can solve. @gregg-miskelly could speak to this more, but I expect this to be more of a function of the expression evaluator that's used. Note that the .NET Core debugger also does not analyze C# source code.

**Comment by gregg-miskelly** [comment]
In case this is helpful - all of full VS's expression evaluators (and the .NET Core VS Code expression evaluator) don't look at the user's source code at all but instead look at the metadata of the debugged .dll's/.exe's and the content of the symbol files (.pdbs). At a high level - metadata provides information about types and arguments while PDBs tell you about the names of local variables.
