### ISSUE TITLE
Error while Downloading and configuring the .NET Core Debugger

### ISSUE THREAD

**Issue by aeschli** [OmniSharp/omnisharp-vscode#96]
_From @dhnnjy on March 15, 2016 11:55_

- VSCode Version: 0.10.11
- OS Version: ubuntu 14.04-x64

After installing csharp extension, I'm getting message 'installation is successful'. But after that, there is this error,

    error: File '/home/dhananjay/.vscode/extensions/ms-vscode.csharp-0.3.6/NuGet.config' does not exist.
    dotnet exited with error code 1
    Error while installing .NET Core Debugger.

But C# is present in installed extensions list.

_Copied from original issue: Microsoft/vscode#4244_

**Comment by gregg-miskelly** [comment]
Thanks for reporting this. Are you trying to get .NET Core debugging to work? If so, we are happy to help troubleshoot. If not, you can ignore this.

Assuming you want to help, can you tell us -- 

1. What version of .NET CLI do you have installed? (dotnet --version will tell you)
2. Does this work if you call dotent restore by hand?

`cd ~/.vscode/extensions/ms-vscode.csharp-0.3.6/coreclr-debug`
`dotnet --verbose restore --configfile NuGet.config`

**Comment by dhnnjy** [comment]
@gregg-miskelly 

1. Dotnet --version output:


    .NET Command Line Tools (1.0.0-beta-001675)

    Product Information:
     Version:     1.0.0-beta-001675
     Commit Sha:  N/A

    Runtime Environment:
     OS Name:     ubuntu
     OS Version:  14.04
     OS Platform: Linux
     Runtime Id:  ubuntu.14.04-x64


2.cd ~/.vscode/extensions/ms-vscode.csharp-0.3.6/coreclr-debug  Output:

    bash: cd: /home/dhanajay/.vscode/extensions/ms-vscode.csharp-0.3.6/coreclr-debug: No such file or directory

**Comment by dhnnjy** [comment]
Oh wait, It's 
/.vscode/extensions/ms-vscode.csharp-**0.3.7**/coreclr-debug

I guess it's looking for NuGet.config file in wrong path. But why is that?

**Comment by dhnnjy** [comment]
dotnet --verbose restore --configfile NuGet.config output:

    ~/.vscode/extensions/ms-vscode.csharp-0.3.7/coreclr-debug$ dotnet --verbose restore --configfile NuGet.config
    error: File '/home/dhanajay/.vscode/extensions/ms-vscode.csharp-0.3.7/NuGet.config' does not exist.



~/.vscode/extensions/ms-vscode.csharp-0.3.7/coreclr-debug$ ll

total 36

     4096 Mar 17 10:05 ./
     4096 Mar 15 18:40 ../
     374 Mar 15 18:40 dummy.cs
     229 Mar 16 16:46 install.log
     476 Mar 15 18:40 NuGet.config
     12288 Mar 17 10:10 .NuGet.config.swp
     1369 Mar 15 18:40 project.json

**Comment by gregg-miskelly** [comment]
Your .NET CLI is behaving badly. We may need to move your issue over to there. But I have seen this before if you repeatedly install new CLIs without uninstall. So one last thing you can try:
sudo apt-get remove dotnet
sudo apt-get install dotnet=1.0.0.001675-1 // assuming this is the build you want to be on

**Comment by dhnnjy** [comment]
@gregg-miskelly 
I did what you said, and it's still not working.

**Comment by gregg-miskelly** [comment]
I moved this to the .NET CLI repo. Hopefully they will be able to help.

One note BTW: The .NET CLI just checked in a big set of changes that break debugging. Since you don't have debugging anyway, you can certainly install a newer build if you want. But debugging will not work with them.

**Comment by neilyoung** [comment]
Similar issue on MacOSX
```
Downloading and configuring the .NET Core Debugger...
error: File '/Users/decades/.vscode/extensions/ms-vscode.csharp-0.3.7/NuGet.config' does not exist.
dotnet exited with error code 1
Error while installing .NET Core Debugger.

```
```
~/.vscode/extensions/ms-vscode.csharp-0.3.7/coreclr-debug $ dotnet --verbose restore --configfile NuGet.config
error: File '/Users/decades/.vscode/extensions/ms-vscode.csharp-0.3.7/NuGet.config' does not exist.

```

**Comment by mariocatch** [comment]
Similar issue on Windows 10:

```
Downloading and configuring the .NET Core Debugger...
Running C:\Program Files\dotnet\bin\corerun.exe "C:\Program Files\dotnet\bin\NuGet.CommandLine.XPlat.dll" "restore" "--configfile" "NuGet.config" "--runtime" "win7-x86" "--runtime" "win7-x64"
Process ID: 36936
Specify --help for a list of available options and commands.
error: Unrecognized option '--configfile'
dotnet exited with error code 1
Error while installing .NET Core Debugger.
```

**Comment by gregg-miskelly** [comment]
@mariocatch can you try uninstalling your .NET CLI, make sure the directory is clean, and then reinstalling it? Also, what version do you have?

**Comment by manfredk** [comment]
Had the same issue on Windows 10. It disappeared after updating to C# Extension 1.3.0 on .Net Core  1.0.0-preview2-003121. Debugger is now successfully downloaded and installed (once).
