### ISSUE TITLE
manually download and install dependencies

### ISSUE THREAD

**Issue by iiley** [OmniSharp/omnisharp-vscode#961]
Hi, thanks for the great plugin. I have a internet issue to make vscode download the dependencies, i always stuck here:
```
Downloading package 'Mono Runtime (macOS)' (1544 KB) .................... Done!
Downloading package 'Mono Framework Assemblies' (5517 KB) .................... Done!
Downloading package 'OmniSharp (Mono 4.6)' (12693 KB) ...
```
I can find the dependencies links in source code _package.json_, if I manually download all the files, how can i integrated them to the extension?

**Comment by iiley** [comment]
After hours finally i found a way, just download and unzip the files to the directory package.json indicated, and then create a file named "install.Lock" at the root of the plugin. Then restart vscode, it works. But i have not tested the debugger since i use Unity debugger only.

**Comment by DustinCampbell** [comment]
Hi, yes, that should work -- mostly. You might need to use `chmod 755` on a few of the files to make them executable.
