### ISSUE TITLE
References appear far to the left of the window on VS Code for Mac

### ISSUE THREAD

**Issue by Xelnath** [OmniSharp/omnisharp-vscode#965]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:
1.5.2

## Steps to reproduce
Open any C# project. 

## Expected  behavior
References appear above the text. 

## Actual behavior
References appear 1 window's worth of units to the left. 

![screen shot 2016-11-18 at 5 33 49 pm](https://cloud.githubusercontent.com/assets/11283246/20451991/422ddc18-adb5-11e6-8a4b-548ab4190833.png)

**Comment by LeThe-Zhu** [comment]
Maybe you try View->Zoom in  or Zoom out chang display

**Comment by Xelnath** [comment]
That helped.

**Comment by milkowski** [comment]
The zoom level is not respected, it is positioned right only when there is no zoom at all (zoom level == 0). Changing zoom level to other value renders reference adnotations to misaligned.

**Comment by DustinCampbell** [comment]
Note that this is a known issue in VS Code.

**Comment by DustinCampbell** [comment]
Should be fixed with https://github.com/Microsoft/vscode/issues/14949
