### ISSUE TITLE
Can't Support Net Core 1.1 

### ISSUE THREAD

**Issue by LeThe-Zhu** [OmniSharp/omnisharp-vscode#966]
## Environment data
`dotnet --info` output:

C:\Windows\system32>dotnet --info
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14971
 OS Platform: Windows
 RID:         win10-x64

VS Code version:
1.7.1
C# Extension version:
1.5.2

## Steps to reproduce
dotnet new

## Expected  behavior
can't auto find project.json because  of dotnet Core 1.1 has change the directory structure.

## Actual behavior
![2 8m zoyfig acffnpi061](https://cloud.githubusercontent.com/assets/23567962/20453551/23810aa6-ae64-11e6-878f-d8c645927989.png)

**Comment by gregg-miskelly** [comment]
@LeThe-Zhu The work for .NET Core .csproj is partially present in the version of the extension that you have (1.5.2) but we still have some more work ahead of us: https://github.com/OmniSharp/omnisharp-vscode/projects/2. For your scenario, I believe you will find it works okay if you restore from the command line (`dotnet restore`).

**Comment by LeThe-Zhu** [comment]
Thanks you email!
I use “dotnet restore” resolve this problem with your suggestion
But I'm curious I also use this command is not useful before I add issue😂
发件人: Gregg Miskelly [mailto:notifications@github.com]
发送时间: 2016年11月19日 14:48
收件人: OmniSharp/omnisharp-vscode <omnisharp-vscode@noreply.github.com>
抄送: LeThe-Zhu <wdzhuxiang@msn.com>; Mention <mention@noreply.github.com>
主题: Re: [OmniSharp/omnisharp-vscode] Can't Support Net Core 1.1 (#966)


@LeThe-Zhu<https://github.com/LeThe-Zhu> The work for .NET Core .csproj is partially present in the version of the extension that you have (1.5.2) but we still have some more work ahead of us: https://github.com/OmniSharp/omnisharp-vscode/projects/2. For your scenario, I believe you will find it works okay if you restore from the command line (dotnet restore).
