### ISSUE TITLE
Error Loading Projects

### ISSUE THREAD

**Issue by Alonski** [OmniSharp/omnisharp-vscode#968]
## Environment data
`dotnet --info` output: 
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

VS Code version: 1.7.1
![image](https://cloud.githubusercontent.com/assets/452199/20461355/00ff2f94-af04-11e6-926c-2c6efa237cdb.png)

C# Extension version: 1.5.2

## Steps to reproduce
Add Folder with myproject.sln.
Omnisharp starts to try loading projects.
Get errors. See log.

## Expected  behavior
Omnisharp loads projects and I can build?

## Actual behavior
Get errors. See log.
[Omnisharp Log.txt](https://github.com/OmniSharp/omnisharp-vscode/files/601900/Omnisharp.Log.txt)

**Comment by DustinCampbell** [comment]
Do you have a project that reproduces the problem that you could share out?

**Comment by Alonski** [comment]
This is a private project that I can't share. Any ways to debug this without the project?

**Comment by DustinCampbell** [comment]
If you can reproduce the error on different project that you can share, that'd work. I'm going to need to attach a debugger to see what's going wrong.

**Comment by Alonski** [comment]
I am having trouble moving around my projects so that I can have something to show you. Is there a way for me to attach the debugger?
Sorry for not being able to cooperate and thanks for helping.

**Comment by DustinCampbell** [comment]
Does it happen if you create another project in Visual Studio? My suspicion is that several of the paths in your csproj files are incorrect.

**Comment by DustinCampbell** [comment]
Sorry, to be clear, if you create another project in Visual Studio and try to open it in VS Code, do you see the same issue?

**Comment by DustinCampbell** [comment]
@Alonski: Sorry that this issue has grown a bit stale. Is this working better for you with the latest release of the C# extension?

**Comment by Alonski** [comment]
Sorry that I wasn't able to help more.
I think that now things work better but I am still getting errors.
Tomorrow I will check and fill you in.

**Comment by DustinCampbell** [comment]
I'm going to go ahead and close this for now. Please let me know if you're still seeing errors with the latest release of C# for VS Code (1.7.0). If so, it'd be helpful if you could share your OmniSharp Log again.
