### ISSUE TITLE
C# Unity auto complete hints are wrong

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#97]
_From @zeyangl on March 16, 2016 9:35_

- VSCode Version:  0.10.11
- OS Version: 10.11

Steps to Reproduce:

1. As shown in the following image, the autocompletion hints are wrong. It shows raw xml instead of formatted method information.

![image](https://cloud.githubusercontent.com/assets/1244606/13807673/4aa9819c-eb9d-11e5-83ea-6a810e06f0ce.png)

_Copied from original issue: Microsoft/vscode#4295_

**Comment by DustinCampbell** [comment]
This should be fixed with the latest release, [v1.3.0](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.3.0)

**Comment by zeyangl** [comment]
@DustinCampbell  I drag-and-dropped this into VSCode plugin folder. It appears installed in the VSCode extensions panel, with correct version number(1.3.0), but autocomplete does not work. Reverting back to OmniSharp legacy plugin makes autocomplete functional. Please let me know if I did something wrong. I'm really looking forward to the new version as the legacy one seems pretty slow when doing autocompletion.

**Comment by DustinCampbell** [comment]
1. Did you uninstall the Legacy C# extension before installing the new C# extension? They won't function properly together.
2. With the C# extension v1.3.0 installed, open your project. Then, select View->Output from the menu and choose OmniSharp Log from the combobox in the upper-right corner of the Output window. Could you copy and paste the log here?

**Comment by zeyangl** [comment]
1. Yes I did uninstall the legacy version.
2. There is no "OmniSharp Log" option in the combobox, only "git", "extensions", and "tasks". I guess maybe the plugin is not running after all? But it does appear installed though.

![image](https://cloud.githubusercontent.com/assets/1244606/17011303/21999070-4f3f-11e6-8a59-8b0ff590e792.png)

**Comment by DustinCampbell** [comment]
That's really strange! It's like the extension isn't activating at all. If you press F1 to bring up the command palette, is the a "Restart OmniSharp" command?

**Comment by zeyangl** [comment]
As follows:
![image](https://cloud.githubusercontent.com/assets/1244606/17011661/af8badb6-4f42-11e6-944f-85e808a0a467.png)

Is there anything else I need to do, other than coping the src to the .vscode/extensions directory?

**Comment by DustinCampbell** [comment]
Also, you mentioned dragging and dropping the extension to the plugin folder? I've never tried installing an extension that way. Instead, I open the VSIX with File->Open File in VS Code and the restart VS Code for good measure.

**Comment by DustinCampbell** [comment]
oh, yes. You should definitely install it as I suggested. I have no idea how VS Code responds to just copying bits to the extensions folder. I suspect VS Code never scanned the package.json in the extension completely, so you are in a half-installed state.

**Comment by zeyangl** [comment]
Okay I did what you said, and it seems to installed properly now. Sorry for wasting your time like that, as I didn't find anything about opening .vslx

Another problem shows up. It prompts about installing .Net CLI tools, and when I click yes, it takes me to .Net core webpage. I thought the new version would automatically use Mono. So I should keep both Mono and .Net core stuff for this to work properly? I don't have a problem with this as long as it what it takes to get the new version working. Just want to confirm.

**Comment by DustinCampbell** [comment]
Excellent! I'm so glad you were able to get it installed. The prompt is because the .NET CLI tools are required to install the CoreCLR debugger, which you clearly won't be using for Unity development. @gregg-miskelly, do you have any thoughts about this?

**Comment by DustinCampbell** [comment]
FWIW, installing the .NET CLI will make the prompt go away. However, I think it might be a bit of an oversight that the extension doesn't provide a way to turn the prompt off.

**Comment by zeyangl** [comment]
Okay omnisharp is working fine now. I didnt notice the background downloading after installed. That took a couple minutes but everything seems to work fine now. Thanks for the prompt replies. Really helpful.

**Comment by gregg-miskelly** [comment]
I opened #603 to track trying to improve this
