### ISSUE TITLE
Intellisense working for few seconds 

### ISSUE THREAD

**Issue by ammarsabir26** [OmniSharp/omnisharp-vscode#970]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:
![working](https://cloud.githubusercontent.com/assets/12556439/20470810/c688597e-afcd-11e6-958d-92eb7d87ba09.png)
![not working](https://cloud.githubusercontent.com/assets/12556439/20470811/c6b0e7fe-afcd-11e6-84dd-8fa4792bb5e7.png)

## Steps to reproduce
As soon as i start to type some word , intellisense stops working and then after few seconds it appears again. This behaviour is happening continously .
As you can see in the attached screenshots , Intellisense is working and i can see the references but in the second screen shot(taken few seconds after 1st screenshot), the intellisense has stopped working and would come after some delay. Kindly fix this issue
## Expected  behavior

Intellisense should work without any delay

**Comment by wenchengye** [comment]
I've the same problem after i updated C# extension, and it also updated omnisharp.
the follow log show when i open VScode. the problem maybe relative with it.

> [ERROR:OmniSharp.Dnx.DnxPaths] The specified runtime path 'default' does not exist. Searched locations 
> /Users/overspark/.dnx/runtimes/dnx-mono.default
> /Users/overspark/.dnx/runtimes/kre-mono.default
> /Users/overspark/.dnx/packages/KRE-Mono.default
> /Users/overspark/.k/runtimes/dnx-mono.default
> /Users/overspark/.k/runtimes/kre-mono.default
> /Users/overspark/.k/packages/KRE-Mono.default
> /Users/overspark/.kre/runtimes/dnx-mono.default
> /Users/overspark/.kre/runtimes/kre-mono.default
> /Users/overspark/.kre/packages/KRE-Mono.default.

trying to fix it.

**Comment by ammarsabir26** [comment]
i found exactly the same error but my c# extension is already updated .
Actually this problem occurred after updating c# extension

**Comment by HawkenKing** [comment]
I've had this problem for a while...

**Comment by ammarsabir26** [comment]
so were you able to resolve it?

**Comment by DustinCampbell** [comment]
@wenchengye: That would only happen with an old, old version of the C# extension -- possibly the "Legacy C# Extension". You might need to clean out old versions of the C# extension and install the latest.

@ammarsabir26: What version of VS Code and the C# extension are you using? Could you post your full OmniSharp log when it happens? I suspect OmniSharp is restarting.

**Comment by wenchengye** [comment]
@DustinCampbell: Thank you! I updated my C# extension. It worked much better now, except two little things. First, the "references" annotation still show up more slowly than before. Second, it show "0 projects" after the "fire" icon. Here is my OmniSharp log.

> Starting OmniSharp server at 11/22/2016, 5:01:43 AM
>     Target: /Users/overspark/code/gameClient/gameClient-csharp.sln
>
> OmniSharp server started wth Mono
>     Path: /Users/overspark/.vscode/extensions/ms-vscode.csharp-1.5.3/bin/run
>     PID: 10426
>
> OmniSharp: -s /Users/overspark/code/gameClient/gameClient-csharp.sln --hostPID 10398 --> stdio DotNet:enablePackageRestore=false --encoding utf-8
> ﻿﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/Users/overspark/code/gameClient' on host 10398."},"Seq":1,"Type":"event"}
Discovered Mono file path: /usr/local/bin/mono
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /Users/overspark/code/gameClient
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp#MSBuild] Detecting projects in '/Users/overspark/code/gameClient/gameClient-csharp.sln'.
[INFORMATION:OmniSharp#MSBuild] Loading project from '/Users/overspark/code/gameClient/Assembly-CSharp-firstpass-vs.csproj'.
Resolved symbolic link for Mono file path: /usr/local/Cellar/mono/4.6.1.5/bin/mono-sgen
[INFORMATION:OmniSharp#ProjectFileInfo] Using TargetFrameworkRootPath: /usr/local/Cellar/mono/4.6.1.5/lib/mono/xbuild-frameworks
[INFORMATION:OmniSharp#ProjectFileInfo] Using tools version: 15.0
[INFORMATION:OmniSharp#MSBuild] Add project: /Users/overspark/code/gameClient/Assembly-CSharp-firstpass-vs.csproj
[INFORMATION:OmniSharp#MSBuild] Loading project from '/Users/overspark/code/gameClient/Assembly-CSharp-vs.csproj'.
[INFORMATION:OmniSharp#ProjectFileInfo] Using TargetFrameworkRootPath: /usr/local/Cellar/mono/4.6.1.5/lib/mono/xbuild-frameworks
[INFORMATION:OmniSharp#ProjectFileInfo] Using tools version: 15.0
[INFORMATION:OmniSharp#MSBuild] Add project: /Users/overspark/code/gameClient/Assembly-CSharp-vs.csproj
[INFORMATION:OmniSharp#MSBuild] Loading project from '/Users/overspark/code/gameClient/Assembly-CSharp-Editor-vs.csproj'.
[INFORMATION:OmniSharp#ProjectFileInfo] Using TargetFrameworkRootPath: /usr/local/Cellar/mono/4.6.1.5/lib/mono/xbuild-frameworks
[INFORMATION:OmniSharp#ProjectFileInfo] Using tools version: 15.0
[INFORMATION:OmniSharp#MSBuild] Add project: /Users/overspark/code/gameClient/Assembly-CSharp-Editor-vs.csproj
[INFORMATION:OmniSharp#MSBuild] Update project: Assembly-CSharp-firstpass-vs
[INFORMATION:OmniSharp#MSBuild] Update project: Assembly-CSharp-vs
[INFORMATION:OmniSharp#MSBuild] Update project: Assembly-CSharp-Editor-vs
[INFORMATION:OmniSharp.Startup] Configuration finished.
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: The operation was canceled.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /gotoDefinition: 500 2478ms

**Comment by DustinCampbell** [comment]
The "0 projects" is a known issue: https://github.com/OmniSharp/omnisharp-vscode/issues/835.

The "references" annotation may show up more slowly than before because we're no longer blocking on the OmniSharp for each request. Instead, we process more requests in parallel. I'll take a look at improving that in the future. However, it should be more responsive in general.

**Comment by wenchengye** [comment]
@DustinCampbell thank you for your response, it works well now.

**Comment by DustinCampbell** [comment]
@ammarsabir26: What version of VS Code and the C# extension are you using? Could you post your full OmniSharp log when it happens? I suspect OmniSharp is restarting.
