### ISSUE TITLE
Unable to load symbols. Error initializing the symbol reader on Ubuntu 16.10

### ISSUE THREAD

**Issue by asyschikov** [OmniSharp/omnisharp-vscode#972]
Quick question before I include full "Environment data" and all that stuff.
I am using MacOS, I want to debug on Docker (Ubuntu 16).
I managed to set everything up except that I get this error in debug console:

`ERROR: Unable to load symbols. Error initializing the symbol reader (Microsoft.DiaSymReader.PortablePdb.dll).`

I don't understand who is issuing this line, omnisharp-vscode or clrdbg from inside Docker?
There is no explanation of error and symbols of my app are not being loaded.
Any idea which direction should I look at?

Here is the task I am using:

```js
        {
            "name":".NET Core Docker Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "cwd": "/srv",
            "program": "/srv/bin/Debug/netcoreapp1.0/srv.dll",
            "sourceFileMap": {
                "/srv": "${workspaceRoot}"
            },
            "pipeTransport": {
                "pipeProgram": "/bin/bash",
                "pipeCwd": "${workspaceRoot}",
                "pipeArgs": [ "-c", "docker exec -i docker_srv_1 /opt/clrdbg/clrdbg --interpreter=mi" ]
            }
        }
```

**Comment by gregg-miskelly** [comment]
@asyschikov That issue very likely means that clrdbg running on the Ubuntu 16 machine isn't able to run .NET Code inside itself (as the PortablePdb reader is the first bit of managed code that clrdbg runs). You are running GetClrdbg.sh on the Ubuntu 16 machine I assume?

**Comment by asyschikov** [comment]
@gregg-miskelly well the app itself is working, that is the most surprising part. And debug sort of works, for example it stopped on an exception in Program.cs but was not able to show the stack trace, variabless or anything basically. Yes I am using GetClrdbg.sh from here https://raw.githubusercontent.com/Microsoft/MIEngine/c34e83cf56952f544555a74220701e25b2c84767/scripts/GetClrDbg.sh

**Comment by gregg-miskelly** [comment]
@asyschikov I don't know if this will solve it because I don't remember this issue, but that version of the script will pull an old clrdbg. You want to use:

```
curl -sSL https://raw.githubusercontent.com/Microsoft/MIEngine/getclrdbg-release/scripts/GetClrDbg.sh | 
    bash /dev/stdin latest ~/clrdbg
```

Do we have that link somewhere in our docs?

**Comment by asyschikov** [comment]
@gregg-miskelly I used that script to pull recent version: `./GetClrDbg.sh -v 15.0.25904-preview-3404276 -l /opt/clrdbg`

The problem with the script version from "getclrdbg-release" branch (or master) that it doesn't work on ubuntu 16.04, it fails with restore errors. 

I got the link from here: https://github.com/Microsoft/MIEngine/pull/449

Ok, I just replaced ubuntu with debian in my Dockerfile and everything seem to work magically so I guess I can bare debian for now. I can provide my ubuntu Dockerfile which results in error but I am moving on with debian.

**Comment by gregg-miskelly** [comment]
@asyschikov can you tell me what restore error you were getting? We are just about to move away from using dotnet restore in GetClrDbg.sh, but if there is a simple bug we could try to address it.

**Comment by asyschikov** [comment]
@gregg-miskelly This kind of errors:
```
    System.IO.Compression 4.1.0 provides a compile-time reference assembly for System.IO.Compression on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with ubuntu.16.10-x64.
```
Tons of them.

I installed this SDK package dotnet-dev-1.0.0-preview2.1-003177 and it was ubuntu 16.04.

**Comment by gregg-miskelly** [comment]
I did a quick test on my Ubuntu 16 VM but I couldn't repo the problem. If you still have the original container, what does `dotnet --info` give you?

**Comment by asyschikov** [comment]
@gregg-miskelly 

```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.10
 OS Platform: Linux
 RID:         ubuntu.16.10-x64
```

Here is Dockerfile: https://gist.github.com/asyschikov/9add857f41da99cf63c8e41973eba3df

**Comment by gregg-miskelly** [comment]
@asyschikov it looks like you are on 16.10, which we don't support quite yet.

**Comment by gregg-miskelly** [comment]
Looks like there is a bug in our script where we will treat 16.10 as 16.04. We will fix that as part of https://github.com/OmniSharp/omnisharp-vscode/issues/956

**Comment by asyschikov** [comment]
@gregg-miskelly sorry, right, it was 16.10. I got confused with all those versions.

**Comment by gregg-miskelly** [comment]
@asyschikov Thanks. We will use #956 to track this too. So resolving it as a dupe.
