### ISSUE TITLE
when download .NET Core Debugger got Error: "end of central directory record signature not found"

### ISSUE THREAD

**Issue by netcore-jroger** [OmniSharp/omnisharp-vscode#977]
## Environment data
`dotnet --info` output:
------------------------------------------------
Updating C# dependencies...
Platform: win32, x86_64 (win7-x64)

Downloading package 'OmniSharp (.NET 4.6 / x64)' (12310 KB) .................... Done!
Downloading package '.NET Core Debugger (Windows / x64)' (21295 KB) . Done!

Installing package 'OmniSharp (.NET 4.6 / x64)'
Installing package '.NET Core Debugger (Windows / x64)'
Failed at stage: installPackages
Error: end of central directory record signature not found

Finished
**[ERROR]: C# Extension failed to install the debugger package**

---------------------------------------------------
OS: Windows 10 Professional
VS Code version: 1.7.1
C# Extension version: v1.5.2
.NET Core: v1.1.0

## Steps to reproduce
----------------------------------------------
1. F1
2. Download .NET Core Debugger

**Comment by gregg-miskelly** [comment]
@netcore-jroger if you remove %USERPROFILE%\.vscode\extensions\ms-vscode.csharp-1.5.2 directory and re-add the extension, do you get the same result?

**Comment by netcore-jroger** [comment]
Let me try. @gregg-miskelly

**Comment by netcore-jroger** [comment]
+ first, I removed %USERPROFILE%.vscode\extensions\ms-vscode.csharp-1.5.2 directory, then install 1.5.3 the latest version.
+ second: I use a httpProxy.
**It is properly installed.** 
I'm from China. work network environment is relatively slow . May be related to this .

---------------------------- logs ----------------------------------

Updating C# dependencies...
Platform: win32, x86_64 (win7-x64)

Downloading package 'OmniSharp (.NET 4.6 / x64)' (12310 KB) .................... Done!
Downloading package '.NET Core Debugger (Windows / x64)' (21295 KB) .................... Done!

Installing package 'OmniSharp (.NET 4.6 / x64)'
Installing package '.NET Core Debugger (Windows / x64)'

Finished

----------------------------------------------------------------------------

@gregg-miskelly  Thanks.
