### ISSUE TITLE
Autocomplete outputs error to the OmniSharp log

### ISSUE THREAD

**Issue by anfomin** [OmniSharp/omnisharp-vscode#980]
## Environment data
`dotnet --info` output: 
```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
```
VS Code version: 1.7.1
C# Extension version: 1.5.3

## Steps to reproduce

1. Create empty C# project running .NET Standard 1.6.
2. Create C# class.
3. Show autocomplete.

## Expected  behavior

There should be no errors in output.

## Actual behavior

Omnisharp log shows error for each autocomplete:
```
[ERROR:Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred: Object reference not set to an instance of an object
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 36ms
```

**Comment by DustinCampbell** [comment]
Hi! Could you clarify the repro steps a bit? How did you create the empty C# project? Did you use `dotnet new`?

**Comment by anfomin** [comment]
@DustinCampbell I've created project via custom `project.json`:
```json
{
	"version": "1.0.0-*",

	"dependencies": {
		"Microsoft.AspNetCore.Mvc.Core": "1.1.0"
	},

	"frameworks": {
		"net46": { },
		"netstandard1.6": { }
	}
}
```

I've investigated. This exception occurs when autocompletion tries to find completion for variable name. For example, I'm entering: `Exception e`. When I enter `e` then exception logged:

![2016-11-22 23 09 41](https://cloud.githubusercontent.com/assets/1905503/20535961/ee35cc7c-b108-11e6-9f70-a458d8c30ca6.png)

**Comment by DustinCampbell** [comment]
Thanks for the detailed repro. I'll take a look.

**Comment by DustinCampbell** [comment]
OK. I have a PR out to omnisharp-roslyn to fix this issue. FWIW, the behavior should be mostly benign. The completion is the same whether the exception is thrown or not.

**Comment by anfomin** [comment]
I see that completion works but any exception in the log warns. Thanks.

**Comment by DustinCampbell** [comment]
I've created a [v1.6-beta2](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.6-beta2) release of the C# extension that contains this fix, among others. See this page for information on [installing beta releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases)
