### ISSUE TITLE
[ERROR]: C# Extension failed to install the debugger package

### ISSUE THREAD

**Issue by psoszynski** [OmniSharp/omnisharp-vscode#991]
## Environment data
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

VS Code version: 1.7.2
C# Extension version: Both 1.5.2 and 1.6.0-beta2

## Steps to reproduce
dotnet new
Navigate to Program.cs with VSCode

## Expected  behavior
Debugging experience.

## Actual behavior
Updating C# dependencies...
Platform: win32, x86_64 (win7-x64)

Downloading package 'OmniSharp (.NET 4.6 / x64)' (12359 KB) .................... Done!
Downloading package '.NET Core Debugger (Windows / x64)' (21295 KB) ....................	Retrying from 'https://vsdebugger.blob.core.windows.net/coreclr-debug-1-5-0/coreclr-debug-win7-x64.zip' (21295 KB) ....................
Installing package 'OmniSharp (.NET 4.6 / x64)'
Installing package '.NET Core Debugger (Windows / x64)'
Failed at stage: installPackages
Error: end of central directory record signature not found

Finished
[ERROR]: C# Extension failed to install the debugger package

Also error popup with text: "An error during installation of the .NET Core Debugger. The C# extension may need to be reinstalled.

**Comment by DustinCampbell** [comment]
Since it never got to "Done!" for the debugger, I'm guessing the zip file was partially downloaded and corrupted. What's bizarre is that is that it stopped twice for the debugger. @psoszynski: If I understand you. the same thing has happened with multiple versions of the extension, correct?

Any ideas @gregg-miskelly?

**Comment by psoszynski** [comment]
Yes, it happens with multiple versions. I also tried removing the C# extension from VSCode and installing it again but it doesn't help.

What is weird here is the Platform reported by the tool: win32, x86_64 (win7-x64) is not the same as win10-x64 which is the actual platform as shown at Product information part a little higher up.

Yesterday, I had the same issue on a different instance of Windows 10 (also VirtualBox).

**Comment by DustinCampbell** [comment]
Re: `win7-x64` is expected. This isn't necessarily the RID for your OS, it's the RID we're using to piack a download. `win7-x64` is fully compatible with `win10-x64`

**Comment by psoszynski** [comment]
I reinstalled .NET Core Preview3, this time with bits from this location (instead these that came with Visual Studio 2017 RC): https://github.com/dotnet/core/blob/master/release-notes/preview3-download.md

Still not working, the message in output is a little shorter though:

Updating C# dependencies...
Platform: win32, x86 (win7-x86)

Downloading package 'OmniSharp (.NET 4.6 / x86)' (12230 KB) .................... Done!

Installing package 'OmniSharp (.NET 4.6 / x86)'

Finished
[ERROR]: C# Extension failed to install the debugger package

I am suspecting that this has something to do with that I run all this in a Virtual Machine (Virtual Box). I repeated the same steps on my Windows 7 laptop and there it works perfectly.

**Comment by gregg-miskelly** [comment]
@psoszynski: on the computer from the first output (the **x64** computer), does the C# extension try to download the debugger every time you start VS code and open a C# file or do we only try once (per install of the extension)? Does it take a long time to fail the first time (before the 'retrying from...' line gets printed)? If you try downloading the file in a web browser do you have any better luck?

For your second output (**x86** computer) - the failing to install the debugger package is expected, though maybe we should do a better job with the messaging there - looks like this is an x86 Windows box, and the debugger doesn't yet support x86 Windows (https://github.com/OmniSharp/omnisharp-vscode/issues/844).

**Comment by psoszynski** [comment]
@gregg-miskelly yes, on the x64 virtual machine the c# extension tries to download the debugger every time I start VS code and open a C# file. It doesn't take that long, about 15 seconds.

Well, I tried now 3 times and on the 3 attempt it succeeded! Here is the output:

Updating C# dependencies...
Platform: win32, x86_64 (win7-x64)

Downloading package 'OmniSharp (.NET 4.6 / x64)' (12359 KB) .................... Done!
Downloading package '.NET Core Debugger (Windows / x64)' (21295 KB) .................... Done!

Installing package 'OmniSharp (.NET 4.6 / x64)'
Installing package '.NET Core Debugger (Windows / x64)'

Finished

On the previous attempt, that failed, the message was also different then previous ones but I did not copy it and do not remember it exactly.

**Comment by psoszynski** [comment]
@gregg-miskelly  Just a short extra question, is it normal that my breakpoints do not get hit? The compilation and output looks ok.

**Comment by gregg-miskelly** [comment]
@psoszynski are there any warnings printed to the debug console?

**Comment by psoszynski** [comment]
I startet a new clean project and the breakpoints are hit. Thanks anyway.
