### ISSUE TITLE
Support all logging levels via omnisharp.loggingLevel setting

### ISSUE THREAD

**Issue by adamralph** [OmniSharp/omnisharp-vscode#993]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

VS Code version: 1.7.2
C# Extension version: 1.5.3

## Proposed feature

Allow full control of logging levels via the `omnisharp.loggingLevel` setting. Currently only `default` and `verbose` are supported. It would be good if we could have full control, i.e.

- `fatal`
- `error`
- `warn`
- `info`
- `debug`
- `verbose`

**Comment by filipw** [comment]
This can be added easily as soon as https://github.com/OmniSharp/omnisharp-roslyn/issues/714 is merged.

**Comment by jchannon** [comment]
@filipw get busy ;)

**Comment by adamralph** [comment]
Woot! Thanks guys.
